### ISSUE TITLE
Peace treaty offered by AI is accepted twice

### ISSUE THREAD

**Issue by SoraDevin** [yairm210/UnCiv#1000]
Just offered a peace treaty and hit the sounds good button. The dialogue box with the ai saying "excellent" popped up over the top of the trade dialogue box. After closing that one, the trade dialogue box was still present and hitting "sounds good!" A second time closed it, then showed the "excellent" message a second time which I then closed. The trade gold was given twice.

Need to make sure the trade dialogue is hidden before AI messages show.

**Comment by yairm210** [comment]
Solved :)
