### ISSUE TITLE
Unit In Not Owned City Centre Causes Crash when trying to swap

### ISSUE THREAD

**Issue by Riionardo** [yairm210/Unciv#10021]
**Platform**
Android 12

**Version**
4.7.17

**Describe the bug**
When liberating a citystate, the unit you captured it with stays in the city center, and when you click "show more" on it a unit that can swap, the game crashes

**To Reproduce**
1. Liberate a city state by capturing it (or possibly trade away a garrisoned city to an opponent you have open borders with).
2. Click on 'show more' on the unit in the city center or one that can swap with it
3. See error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

```

```
</details>

**Expected behavior**
Game Crash

**Screenshots**
![Uploading Screenshot_2023-09-02-13-15-36-96_5b83b50424e447777d9855d9701553df.jpg…]()

**Additional context**
1.This bug probably also happens when you liberate a city of a major civ you have open borders with.
2.When resuming the game with the "resume" button after the crash, the unit in the city center disappears.
3. The Save has 1 Gameplay mod in use: Fantasia,  but we believe this to be a base game bug.
4.  Trying to upload the Save here causes an error( your body is too long), so please inquire later (save is upload on discord, in the Fantasia channel)

**Comment by yairm210** [comment]
Solved by #06691d4
