### ISSUE TITLE
can't upgrade units

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#1002]
playing as china in the final stages of the game.
can't upgrade musketman to infantry, maybe it's because it says in the civilipedia that infantry become obsolete with nuclear fission (don't think it should be like that)

**Comment by amirberner** [comment]
also couldn't upgrade cavalary to tank until I researched laser, and then it allowed me to upgrade it to modern armor

**Comment by amirberner** [comment]
addition - when I researched tactics I was able to upgrade the musketman to mech infantry.

**Comment by yairm210** [comment]
As for Infantry - you're right, good catch!

> also couldn't upgrade cavalary to tank until I researched laser, and then it allowed me to upgrade it to modern armor

This is because of the required resource - tanks require oil but modern armor doesn't
