### ISSUE TITLE
"Instantly consumes [amount] [stockpiledResource]" going into negative without preventing things from being built

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#10026]
Windows 10, Itch.io v. 4.7.19

In my currently alpha mod, Plants vs UnZombies, I designed units (Plant Hero and Undead Hero) that consumes a stockpiled resource (in my case, "Kills") to be built. The idea is to have a unit that you can only get after earning enough of the resource. The bug is that it's possible to build the unit without having any of the stockpiled resource. If you don't have any of the stockpiled resource, you simply go into the negative when you build the unit.

I attempted to fix this using `"Only available <with [Kills]>"`, but it didn't quite fix the problem, as the unit becomes visible with only one Kills in stock, allowing you to build the unit and immediately go into negative Kills.

I would expect the `"Instantly consumes [5] [Kills]"` unique to prevent the unit from being built if you have less than 5 of the stockpiled resource available.

**Comment by SpacedOutChicken** [comment]
Here's a little test mod, compatible with the base game, that creates a unit that consumes 5 "Stuff". You can go into the negative indefinitely by building more Thingy units that consume Stuff.
[StockpileTest.zip](https://github.com/yairm210/Unciv/files/12504869/StockpileTest.zip)

**Comment by SeventhM** [comment]
Not my ballpark, but to some degree this reads as "intentional" in my eyes. This should be dealt with via `Costs [amount] [stockpiledResource]`... which...  also treats this situation weirdly. Beyond that, an actually suggestion imo would be providing a sort sort of version of "Only available" or "Unbuildable" that still shows the construction in question

**Comment by SpacedOutChicken** [comment]
I was able to solve this problem using the right uniques, so I'll close this as completed.
