### ISSUE TITLE
Another unnecessary icon

### ISSUE THREAD

**Issue by Lesiakower** [yairm210/Unciv#10031]
**Platform**
Any

**Version**
4.7.19

**Describe the bug**
When you choose the difficulty of your new game there's a settler icon next to the "settler" difficulty (Similar to #9669)

**To Reproduce**
1. Start a new game from the main menu
2.  Start choosing the game's difficulty
**Screenshots**
![Zrzut ekranu z 2023-09-03 11-46-21](https://github.com/yairm210/Unciv/assets/125187776/72a2b654-62b7-4986-a92f-1bcea982777f)
![Zrzut ekranu z 2023-09-03 11-47-04](https://github.com/yairm210/Unciv/assets/125187776/6b51d00a-c454-47a7-af0e-a48a66d01802)

**Comment by trentonk23** [comment]
I like the icon...
