### ISSUE TITLE
Snow not turning to Tundra when next to river

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#10040]
Windows 10, Itch,io version 4.8.0

I just spotted a bit of Snow next to a river, when the terrain file states that all such snow tiles should be transformed to tundra tiles.
![Screenshot (161)](https://github.com/yairm210/Unciv/assets/58439827/2eb38c8e-5b10-46ce-ae8a-53cf3629b5be)

[SnowyRiver.zip](https://github.com/yairm210/Unciv/files/12508078/SnowyRiver.zip)

**Comment by RealBamboolord** [comment]
To me, that unique seemed to only work with conversions to terrain features but not for base terraind
