### ISSUE TITLE
I have suspicions about WorkBoat construction AI

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10060]
Questions about `ConstructionAutomation.addWorkBoatChoice`:
* `alreadyHasWorkBoat` doesn't test whether it's _your_ WorkBoat...
* Testing the Unique in the alreadyHasWorkBoat tile search - I get it, the capability may not come from the BaseUnit. But a `.baseunit in buildableWorkboatUnits.toSet` could be much faster...
* alreadyHasWorkBoat searches only over getTiles - what if it's a new city close to an older one with tons of tiles owned that other city, inside the new city workable range but outside the old city workable range??? I'd say looking over tilesInRange would be more in line with the original intention? As in is there a unit close enough to improve our workable tiles - won't matter who or what city the tile belongs to, as it can move there?
* Mods with military units having CreateWaterImprovements??
* ~**Isn't  `if (!alreadyHasWorkBoat) return` the wrong way 'round????????**~
* It counts owned, unimproved, reachable, and improveable tiles as worth to send a boat to - even it it's a Bonus resource outside any city workable range

**Comment by hackedpassword** [comment]
> CreateWaterImprovements

But aren't civilians hardcored to only be able to construct? (observation not code analysis)

Being able to convert a military unit to civilian, or vice versa has mod value. If that is possible, I wouldn't "fix" it unless actual problems are resulting.

**Comment by SeventhM** [comment]
> But aren't civilians hardcored to only be able to construct?

I'm not sure where this assumption comes from

**Comment by SeventhM** [comment]
Uh... Did you upload the wrong image?

**Comment by SeventhM** [comment]
> started out as attempt to fix #10258

Ugh... Wait, I'm knee deep checking something else rn, but why is this in `constructIfEnough`? Seems to me free buildings will come along and trample over this anyways because I added the call to validate the construction queue (in case you get a free building that was building, which was a missed bug before to my knowledge). Shouldn't this be in `addBuilding`?

**Comment by SeventhM** [comment]
> but haven't really got a clue how the code flow really is and how it should be...
Doing some quick searches, `chooseNextConstruction` is called in `CityConstuctionTable.purchaseConstruction` and `CityConstuctions.removeFromQueue`. It seems obvious that it's supposed to be called at the start of a turn to decide if it still makes sense (ideally before stuff is calculated to have the same information as a player) and after anything changes the calculation mid turn (through something being built). Seems to me that if you put it at the bottom of addBuilding, it'll cover these situations as intended with even less side effects (removeFromQueue is called before validating anyways in constructionComplete, so it never actually worked as intended and purchaseConstrcution checks for the improvement set for some reason when I swear chooseNextConstruction already dealt with...)

**Comment by SeventhM** [comment]
Actually, maybe also put it in BaseUnit.postBuildEvent to keep correct functionality

**Comment by rmingkil71** [comment]
Bugs and other bugs

**Comment by rmingkil71** [comment]
Applicatio@n
