### ISSUE TITLE
Politics screen does not show Defensive Pacts

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#10078]
I forgot to change the politics screen to show defensive pacts on the table and diagram.

**Comment by AutumnPizazz** [comment]
Speaking of the defense agreement, I hope to add that during the declaration of friendship, both sides cannot declare war each other.

**Comment by tuvus** [comment]
This has been talked about a lot before, but I don't think it will change. Is there a specific reason that you want this?
Some related issues are #6767 #3755.

**Comment by AutumnPizazz** [comment]
My negligence. I thought of  Friendship  declaration in the context of Civ VI. This will add a little more interesting element to the PVP.

**Comment by AutumnPizazz** [comment]
To put it in a negative way, perhaps we can add an option in the start screen to determine whether this game allows declaration of war during the friendship declaration period?

**Comment by tuvus** [comment]
The AI currently almost never cancels a DoF (Aka not renew) without a DoW. We would have to write much more detailed code to combat this. Otherwise it is likely to have permenent peace. So I don't know how playable this would be. Especially with the AI offering DoFs soon.

**Comment by AutumnPizazz** [comment]
I don't understand the code side of things, so my proposal may not be practical.
I think maybe it can be done by "only for human players"?

**Comment by The-Talik** [comment]
Has this been fixed?  I don't see any way to initiate a defensive pact from the diplomacy screen.

**Comment by tuvus** [comment]
This issue references the politics screen. In order to offer a defensive pact through the diplomacy screen you need to have a declaration of friendship and go into the trades screen and offer a defensive pact. So yes it has been fixed. 
Did that answer your question?

**Comment by The-Talik** [comment]
Hm.  I definitely don't have a defensive pact option in the trades screen.  Is there any other reason why it would not show up?  I do have a signed declaration of friendship, and confirmed I don't already have a def pact with them.

**Comment by tuvus** [comment]
Could you send some screen shots or the game file?

**Comment by The-Talik** [comment]
![Screenshot_20240418-172600](https://github.com/yairm210/Unciv/assets/1664272/f5447602-91b7-4095-b70f-c0128540ad3f)
![Screenshot_20240418-172616](https://github.com/yairm210/Unciv/assets/1664272/0242af6c-b463-461c-a3e3-c0c746aff5bf)

**Comment by tuvus** [comment]
What version are you on?

**Comment by The-Talik** [comment]
4.11.4 (Build 987)  Google Play version.

**Comment by tuvus** [comment]
Weird, I haven't had this problem myself, are you able to sign defensive pacts on a vanilla gods and kings version?

**Comment by The-Talik** [comment]
I'm not sure.  It would take a while to get to a point where I could try in a new game.  Current mods are Alpha Frontier, Barbarian XP farm, and Thin Bubbly Borders.
I've had AI suggest defensive pacts with me in this game, so I don't think it's disabled completely.

**Comment by tuvus** [comment]
You can use AutoPlay on settler difficulty to play through the begging of the game.
