### ISSUE TITLE
Spectator's problems (Multiplayer)

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#10077]
OC:
Android, Windows_64

Version:
4.7.17 (Build 904), Vanilla

To reproduce:
1.Start multiplayer lobby with "Allow anyone to spectate"
2.Login as spectator player_id

For context: I play with friends. And as host I ran into problems like these:

**Case №1:**
I haven't seen this issue in singleplayer as spectator. But when you trying to watch a multiplayer game as spectator, periodically you can't scroll the map to move the screen to another part of the map. The picture just freezes. This can be unlocked by clicking on the minimap, but it freezes again after a while (GIF). This happens the same way on PC and on Android device.
![Unciv_cicCcZS9mM](https://github.com/yairm210/Unciv/assets/59770002/f1b17e3d-71f4-405e-b8f0-acb13d3f5701)

**Case №2:**
What if I don't want to make the game "Allow anyone to spectate", but I want to leave spectatorship for only one player ID?
If you uncheck the "Allow anyone to spectate" option, then Spectator player specified in the lobby can't connect to the game either, because the game is not available for spectating.

I used different IDs for player and spectator
![image](https://github.com/yairm210/Unciv/assets/59770002/966f895f-31b3-497f-bdbf-cf95e5fc93f1)

I tried to make changes on the server in Preview and Save files, but this is an inconvenient crutch, and I don’t even remember what I did exactly.
In addition, there is also problem with Case №1.

**Comment by AutumnPizazz** [comment]
> Case №2:
I haven't seen this issue in singleplayer as spectator. But when you trying to watch a multiplayer game as spectator, periodically you can't scroll the map to move the screen to another part of the map. The picture just freezes. This can be unlocked by clicking on the minimap, but it freezes again after a while (GIF). This happens the same way on PC and on Android device.

This bug was found by #9959 \(  ͯω  ͯ)/

**Comment by AutumnPizazz** [comment]
This bug did not occur since the earliest. I still remember that before 4.3.x (like 4.2.12) this bug was not existing.
