### ISSUE TITLE
can't do trades anymore

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#1007]
for 2 days I try to trade with the AI and I get no response, and the trade isn't made

**Comment by Smashfanful** [comment]
I have the same problem

**Comment by amirberner** [comment]
הי, הבאג של זה שאי אפשר לעשות טרייד עדיין לא תוקן גם בגרסה הנוכחית

בתאריך יום ד׳, 21 באוג׳ 2019, 23:44, מאת Yair Morgenstern ‏<
notifications@github.com>:

**Comment by yairm210** [comment]
If your version in menu-options isn't 2.19.7 then the new version hasn't yet been rolled out to you, check it

**Comment by amirberner** [comment]
2.19.6
that's what I see in the play store as well

בתאריך יום ו׳, 23 באוג׳ 2019, 9:11, מאת Yair Morgenstern ‏<
notifications@github.com>:

**Comment by Quicksand10** [comment]
I also can't trade. I updated the app just now from the Play store and I got 2.19.6.

**Comment by yairm210** [comment]
So you just need to wait a couple of days until the rollout reaches you
