### ISSUE TITLE
Terrain movement should accept floats

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10081]
This is going to be an ugly submission.

Game crashed during "move automated units".

On the crash dump screen, the copy button failed and the open new issue refused to work until the data was copied. Long press to select did not appear so there was no way to copy the text. I'm attaching the crash messages via screenshot.

Save game data to follow. The crash occurred in this turn. The save is at the start of the turn. Any unit requesting an action is simply set to automate. The intent here was it's end game and I'm just running over the last civ so my troops can do whatever as long as cities are falling.

![Screenshot_20230907_022009](https://github.com/yairm210/Unciv/assets/119975434/f2e623a2-1d3f-4b07-9379-4d3c8c117ddf)
![Screenshot_20230907_022043](https://github.com/yairm210/Unciv/assets/119975434/5b0b3e3e-fe6e-45c6-97ff-58b0e0e99318)
![Screenshot_20230907_022126](https://github.com/yairm210/Unciv/assets/119975434/f5fe0e44-f15f-4699-8f80-99019aefc7eb)
![Screenshot_20230907_022205](https://github.com/yairm210/Unciv/assets/119975434/e82aff3f-d02e-4084-a33a-d23f01d3368a)

In the last screenshot (if they're in order) you'll see the crash data begins to loop. This extended effectively indefinitely.

**Comment by hackedpassword** [comment]
[Crash 08072023.json.txt](https://github.com/yairm210/Unciv/files/12546061/Crash.08072023.json.txt)

**Comment by yairm210** [comment]
Loaded the game, was able to 'next turn' with no problem
I'll check the code and see if I can find something in the repeating loop

**Comment by yairm210** [comment]
Ah OK I see something.
SO if looks like the unit is constantly heading towards a destination it never reaches, BUT it keeps moving. The real question is "how can it keep moving forever". Do you have something in the mod where moving between tiles costs 0 movement?

**Comment by yairm210** [comment]
The loop only continues if the unit is in a different tile than when it started, so it IS moving. 
And each movement takes at least 0.1 movement unless there's some wacky uniques, which looking through the mod I can't see anything related

**Comment by hackedpassword** [comment]
Ha, there is! Let's look:

https://github.com/hackedpassword/Z2/blob/main/jsons/Terrains.json

OceanTile and several Bridge* terrains have a movement cost of 0.

Since setting movement costs to floats doesn't work, the idea, for the mod and the theme of Z2 (specifically waterwalking per the NES level) I wanted the player to get across the water non stop. If they stick around they're taking damage.

It makes sense that it's possible for the AI to zit zag back and forth forever, seems unlikely, but here we are.

Optimally, for this and for a number of other scenarios I've run across, movement in floats would solve these issues from a level design standpoint. Even though you can specify movementCost 0.5 for example, the number is treated as an int and zeroed. Since railroads etc can fractionalize movement, movementCost should also allow.

The immediate solution is obvious. If you guys can consider the above, that would be helpful for other gameplay additions.

Appreciate your checking this out!

**Comment by yairm210** [comment]
Movement costs as floats, gotcha
Sounds doable

**Comment by yairm210** [comment]
And we should add a check that all terrain movement is larger than zero
Having negative movement for terrain would really screw up the pathfinding big-time

**Comment by hackedpassword** [comment]
>  movement is larger than zero
> Having negative movement for terrain would really screw up the pathfinding big-time 

Nuh uh. This adds "features". ;)

I'm hoping to see sub 1.0 movements that allow units to use certain terrains to accelerate movement. Since rail/roads are special, making fast terrain isn't possible (until now?)

Exciting times.

**Comment by yairm210** [comment]
If your want that then you need to redesign the pathfinding.
I *do not* want that.

**Comment by hackedpassword** [comment]
So wait, you're saying:
  movementCost: 0.5

..would require a rewrite to pathfinding? But how does this differ than say a automated or ai unit moves 2.1 out of 3, takes an action, can move after the action, then sets off elsewhere up to 0.9 away (so the scenario would happen in rails). The second movement there would require a pathfinding instance having only 0.9 to work with.

Am I getting this right? What just happened?

**Comment by yairm210** [comment]
No, I'm saying *negative* will require a rewrite

**Comment by yairm210** [comment]
I want to disable sub-0 movement costs

**Comment by hackedpassword** [comment]
Not to be excessive, is it possible to implement float movement costs elsewhere?
example:
[cost] Movement point cost to (dis)embark
The above is another example where I'd find it useful to exercise more control over a player being able to decide whether using .5 out of 1.5 M to either traverse embarking or moving along the same terrain type is the better strategy.

**Comment by hackedpassword** [comment]
Ok, on that I'm somewhat lost. I get the inverse fraction of acceleration, which is my hope in adding to movement.

Well, in the end, you guys understand if it's feasible. It's situations like this I regret not having advanced software dev skills to contribute!

**Comment by hackedpassword** [comment]
Float movement costs applicable to terrain.
#3242
