### ISSUE TITLE
Feature request: Expose razing on city screen

### ISSUE THREAD

**Issue by marksteward** [yairm210/Unciv#10111]
I've been playing on deity/immortal recently which basically requires controlled burns of cities. However, the little icon is tiny and hard to see across the whole map. I often start a new turn to find a city in the corner of the map has been razed without me noticing.

It'd be great to have an extra column in the city screen that includes the raze icon for any cities that are currently being razed. Maybe also a column for cities in resistance too?

Thanks for this masterpiece of an open source game!

**Comment by marksteward** [comment]
I think a city and be both razing and in resistance, but this seems like a reasonable way to show it in one column.

**Comment by hackedpassword** [comment]
:+1: to a status column, with any of the 3 statuses per city, like unit ability icons on the unit screen.
