### ISSUE TITLE
Unhappiness messages displayed twice

### ISSUE THREAD

**Issue by SoraDevin** [yairm210/UnCiv#1012]
New game with 2 cities at -1 unhappiness. Got the three messages shown twice.

**Comment by SoraDevin** [comment]
Might be a good idea to review message display functionality as this is the second duplicate message I've run into

**Comment by yairm210** [comment]
Pretty sure this is solved with the latest popup changes, but not 100% sure. If you encounter this again from 2.19.9 onwards, give me a heads-up and we'l reopen this.
