### ISSUE TITLE
RFC: Tile info improvement recommendation

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10121]
Reading #6879 I thought:
![image](https://github.com/yairm210/Unciv/assets/63000004/9e36d272-65f0-41c5-88f7-ceb6d3663f85)

This reuses a worker AI function to generate the recommendation, as such it's quite clever but..
* Nothing that you couldn't do _now_ if you had the proper unit there
* Nothing requiring a placer instead of taking turns (nada on that crab just off the top of the map there)
* Chop-to-Plantation is just Chop

Comments?

**Comment by yairm210** [comment]
I'm for an option to display, but against it being displayed by default - that's long, and screen space is too valuable for something that you can do without
