### ISSUE TITLE
AI appears to ignore defensive pacts when attacking. 

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#10130]
Android 13, Play Store version 4.8.4

(No saved game yet, will try to get you one)

I had a force of about 60000 when the AI attacked me with a force of about 11000. I couldn't figure out why they would do this, but then I noticed that they also declared war with my ally, who only had a force of about 3000, but who had a defensive pact with me. I believe that the AI failed to take that pact into account when declaring war with the weaker side, causing them to start a fight with me that they couldn't win.

**Comment by tuvus** [comment]
Yes, the AI doesn't currently take defensive pact allies into account. From what I have searched on Civ V, their AI also doesn't take defensive pacts into account. (Not that this is preferable behaviour)

I am planning on adding this functionality later, but it takes a while to tune the AI not to value defensive pacts too much (or else it will get stuck not attacking). For a reference, it is taking a while to tune the AI to declare friendship and defensive pacts already.

**Comment by SpacedOutChicken** [comment]
Also, sorry for not adding the "bug" label when I posted this. For some reason, it didn't get added, and now I can't assign it. Can someone fix that?

**Comment by tuvus** [comment]
Only Yairm can change the labels, I think.

**Comment by tuvus** [comment]
I don't know where I can get the source code. I have searched on GitHub and found something but I am unsure if it is accurate or has the expansions. My reference comes from players complaining about it, so it isn't very reliable. It could also depend on the expations.

**Comment by yairm210** [comment]
Solved by linked PR
