### ISSUE TITLE
Mismatch of Science costs

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#10135]
OC:
Android, Windows_64

Version:
Last, Vanilla

I'm not sure if this is a bug. I apologize in advance. But I have a feeling that the costs of technologies and buildings are not transparent, and are somewhere misleading. 
The Civilopedia states that at standard game speed the modifier of technology cost = 100%.
But if you run the game at standard speed, cosit is different.

I ran the games at different speeds and made a table using the Pottery tech (granary for gold cost) as an example.
There's some kind of mess here (Science Modifier). Or am I missing something...
Look:

![image](https://github.com/yairm210/Unciv/assets/59770002/b23baaa6-c784-4adf-b1b1-5bdb3835a51c)
https://docs.google.com/spreadsheets/d/1EHtinkybjeSfCfjERancZD8DMTS-8cCwPMdZcGWHRwE/edit#gid=0
![image](https://github.com/yairm210/Unciv/assets/59770002/72132641-d745-4aab-b3c7-be8ee21baae9)
![image](https://github.com/yairm210/Unciv/assets/59770002/6c14a409-342b-4538-adab-008f107492b9)
![image](https://github.com/yairm210/Unciv/assets/59770002/fdd4c707-9c1a-42c9-a8d3-fb56510100d3)

**Comment by DeStup** [comment]
Closed.Closed. I don't think I took into account the effect of "difficulty" on the calculations

**Comment by DeStup** [comment]
Okay, I corrected it, the difficulty is King, this is a coefficient of 1 for the cost of the player.

The main reason why this attracted my attention, at all is that technology is expensive for a quick game (Multiplayer). And when exploring the issue, I realized that the coefficients from Civilopedia do not match.

**Comment by SeventhM** [comment]
Let's go in order of what's happening:
Production costs: Looks fine to me, no comment
Gold costs: So gold costs are a bit weird. Formula is [here](https://forums.civfanatics.com/threads/rush-buying-formula.393892/). What's important is that the gold prices doesn't actually scale based on game speed in the way you'd think it does
Science cost: I feel like I might need more info. Map size? Number of players? Has anyone researched a tech yet?

**Comment by DeStup** [comment]
> Let's go in order of what's happening: Production costs: Looks fine to me, no comment Gold costs: So gold costs are a bit weird. Formula is [here](https://forums.civfanatics.com/threads/rush-buying-formula.393892/). What's important is that the gold prices doesn't actually scale based on game speed in the way you'd think it does Science cost: I feel like I might need more info. Map size? Number of players? Has anyone researched a tech yet?

hm, thanks.
about Science cost: Huge. Any. No one.

It was a surprise to me that the size of the map affects the cost of technology. Is this how it should be?
