### ISSUE TITLE
Request regarding the reposting of Wikipedia content

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10144]
@yairm210  Hi, can I translate the part about module creation in Wikipedia into Chinese and publish it on a domestic website in China? I hope to let more people learn about Unciv and participate in mod making.
Why should I repost on the Chinese Internet instead of sharing a link? You should know that China has strict internet censorship, and access to the international internet is generally restricted in mainland China.

**Comment by yairm210** [comment]
You can repost anything you want :)
