### ISSUE TITLE
Feature request: json schema for modders

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#10152]
Vscode can support json schemas: https://dev.to/brpaz/how-to-create-your-own-auto-completion-for-json-and-yaml-files-on-vs-code-with-the-help-of-json-schema-k1i 

As do jetbrains, in some of their products: https://www.jetbrains.com/help/idea/json.html

So the idea is to enable modder productivity using this tool.

And json schema can also contain documentation...

But let's do this in baby steps!
- Define basic "building json" schema (where do we save it? Docs/modders/schemas?)
- Instructions for how to set up the schema in vscode (free), and Android Studio (indicated as possible here: https://stackoverflow.com/questions/57408912/reset-json-schema-validation)
- See if we can generate that json schema from the class - not a niche request, there are probably libraries for that
- Definite other json file schemas - automated or not, based on previous step

Once we've done all that, then we can think about subsequent steps ;)

**Comment by Caballero-Arepa** [comment]
Interesting

**Comment by yairm210** [comment]
https://github.com/Kotlin/kotlinx.serialization/blob/1fe9ec1d07125c12a196d5a49959c400ea593cdf/examples/example-visitors/src/main/kotlin/App.kt

Looks like Kotlinx does the hard parts, just need to check if that works as-is or of we need to add yukky `@Serializable` annotations.
Even if so it's a small price to pay

**Comment by yairm210** [comment]
https://github.com/Ricky12Awesome/json-schema-serialization

Looks like this adds support for other json schema limits like int and float ranges, etc. Neat stuff
