### ISSUE TITLE
Feature request: Add ''<with battle text [comment]>''

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10151]
Inspired by mods of Civ6, I would like to add a new entry for the expression of combat bonus. If this entry exists, the source of combat bonus is expressed as the content of this entry. If it does not exist, it is expressed as default.
For example, ''[+15%] Strength <for [Land] units>'' is expressed as 'for land units', and at the same time, '[+15%] Strength <for [Land] units> <with battle text [Fighting Crazily]>' is expressed as 'Fighting Crazily'.

**Comment by yairm210** [comment]
#3242
