### ISSUE TITLE
Lag when combining a lot of mods together

### ISSUE THREAD

**Issue by trentonk23** [yairm210/Unciv#10173]
Loading more than ten  mods is  laggy on Android. Newest version

**Comment by hackedpassword** [comment]
You'll need to provide more information. Hardware info, do note the current version/build of Unciv, Android OS version. Devs will need specifics to replicate.

You might consider a 30 second vid to demonstrate the lag.

**Comment by trentonk23** [comment]
https://media.discordapp.net/attachments/1148088069258498079/1155252249061244998/screen-20230923-171301.mp4
The video shows the loading times being laggy 
Version: 4.8.7 (Build 915)


VLA6
Model
A509DL
CPU
MT6762
RAM
3.0 GB
Storage
32 GB
Battery capacity
3000 mAh
Resolution
720x1440
Camera
Front 5 MP
Rear 8 MP
Android version
11

**Comment by yairm210** [comment]
Managed to get it down to ~280ms from ~380ms but the timings on this vary greatly.

**Comment by yairm210** [comment]
Looks like CheckPromotionCircularReferences is the next thing to optimize

**Comment by yairm210** [comment]
![image](https://github.com/yairm210/Unciv/assets/8366208/87b45a22-3be2-4a3d-b11f-70936ce376bb)
![image](https://github.com/yairm210/Unciv/assets/8366208/7857f822-ec9b-4b9c-a3b2-d771535d7cdf)

Stuck on 'hasUnique'

![image](https://github.com/yairm210/Unciv/assets/8366208/f3a5ba36-c663-4a22-9b56-b726398493bc)

Parsing the uniques into conditionals seems to be pretty heavy
![image](https://github.com/yairm210/Unciv/assets/8366208/2104b795-539d-4d37-8999-b0da63deea0e)
String equality is a big part of that

Not sure what parts of this investigation are actually relevant but we'll do what we can

**Comment by yairm210** [comment]
SO the string equality is in Unique.kt:24 and that's easy to deal with by adding a global hashmap to UniqueType

The HasUniques... hrm a hashset of 'all building uniques' and 'all terrain uniques' would solve that, but it would be very ugly... readability vs performance :(

**Comment by yairm210** [comment]
Okay, I think I've done all I can here that's definitely a good idea, I'm willing to consider this done
