### ISSUE TITLE
New Feature: AutoPlay

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#10176]
**Intro and relavence**
There has been a lot of talk of some some sort of auto next turn feature. The specifics range from a simple end turn without any movements to doing part or the entire turn. Basically, it will need a lot of customizability and options.

My interest is that I need a solution for quickly testing the AI so I have decided to work on implementing this feature.  I don't actually need the full feature but I have decided to do it anyway (Lets hope I can actually finish it).

**End Goal:**
The AutoPlay feature will allow the player do 4 main things:
- Automate certain parts of a turn individually, for example only military or civilian units so the player can focus on the important parts of their turn.
- Automate their turn but go out of automation when the player need handle some major event like tech, diplomacy, policy or religion.
- Completely automate their turn, using the full AI functionality.
- Automate their turn for X turns, while in multiplayer. A player's turn might be completely automated and skipped until they have some important notification, if they turn it on in the settings. The automation would be run on the other player's phone and if it reaches a condition that the automating player set it stops and sends the last save (discarding the automation for that turn). This might help speed up the early game or a stalemate late game.

Because of these use cases each player need to be able to have their own automation settings for their civ attached to the save file. The player might also want to have different settings per game.

<hr>

**Demonstration**
To demonstrate this, I wrote AutoPlayHack. This is a quick demonstration of how the AutoPlay would work.
https://github.com/tuvus/Unciv/tree/AutoPlayHack
<details>
Here is a quick options list. Note that if fullAI is pressed, the other buttons disappear.

![AutoPlayOptions](https://github.com/yairm210/Unciv/assets/7538725/531bd5a5-0c2e-4a0a-aa79-6f31d3694dfe)

AutoPlay button is right next to the next turn button. I have put a temporary symbol on it. Clicking the AutoPlay button or hovering over it while AutoPlay is active deactivates it. 

![AutoPlayButton](https://github.com/yairm210/Unciv/assets/7538725/48b43c81-98b8-46a5-a187-aa44793d917b)

Clicking on the AutoPlay button opens up a menu with the options shown. The Civ's Military, Civilian and Economy can be AutoPlayed independently here.

![AutoPlayPopup](https://github.com/yairm210/Unciv/assets/7538725/c14f2b43-48ee-4ca2-803d-8be977e61867)

</details>

I am working on this on a different branch.
The initial idea and way of handling calling nextTurn() comes from alexban011 in #9888.

Related issues:
#9888
#2375
#9450

**Comment by AdityaMH** [comment]
Using autoplay or auto skipped endturn without knowing what AI to do (player turn or enemy turn) is bad or blind strategy.
and you don't know where your worker get stealed by barbarians.

**Comment by tuvus** [comment]
@yairm210 or @SomeTroglodyte 
What do you think of this idea? Multiplayer multiturn AutoPlay might be a bit much to implement due to its complexity and APIv2 (sort of) underway. But the single-player multiturn AutoPlay and single-use AutoPlay for both single-player and multiplayer would not be as difficult. I have the base already created. It would need a lot more refining, though.

**Comment by yairm210** [comment]
I'm for it, there are 2 things we need to pay attention to:
- UI (how can I input a variable amount of turns)
- Multiplayer (does this mean that other players 'pass turns' for me)

If we limit this for now to singleplayer-only we can solve only problem 1 without touching problem 2, sounds like a good plan for me

**Comment by yairm210** [comment]
It's unclear what 'autoplay' without anything else means in that table

**Comment by yairm210** [comment]
This is already done 👍🏿
