### ISSUE TITLE
Modding Issue: Interraction of < upon founding a city> and Lands tileFilter

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#10198]
**Platform**
Windows 10 64bit

**Version**
v4.8.8

**Describe the bug**
I tried something like this "Gain [100] [Gold] < upon founding a city> <within [2] tiles of a [Enemy Land]>" it doesn't work. But, it works if I change Enemy Land into non-Lands tileFilter (Foreign Land, Enemy Land, Friendly Land). 

I've tried changing < within x tiles> into < in x tiles>. But it went weird.
"Gain [100] [Gold] < upon founding a city> <in [Friendly Land] tiles>" seems to apply even in Foreign Land tiles.
While  "Gain [100] [Gold] < upon founding a city> <in [Foreign Land] tiles>" completely doesn't work.

I've also tested using <with 1 to 6 neighboring x tiles>, and it behaves like < in x tiles> mentioned above.

**Additional Context**
It seems that the Lands tileFilter has problems interracting with < upon founding a city>, but I haven't checked it thoroughly.

Thank you in advance!

**Comment by yairm210** [comment]
The thing is, that the trigger happens *after you create the city* and not before, so the tile is *always* friendly then, since it has your new city

**Comment by yairm210** [comment]
And it can't trigger beforehand, because then city filters won't work...
So given the choice between having city conditionals work, and having those very specific tile conditionals work, I'm choosing the former
This *is* a real problem, but not one solvable in a way that's acceptable to me
