### ISSUE TITLE
the header of the table in the cities tab is not aligned to the table itself

### ISSUE THREAD

**Issue by somesi** [yairm210/Unciv#10204]
**Platform**
Windows 11 x64

**Version**
4.8.9 (itch.io)

**Describe the bug**
In the overview, the table that shows the info of all your cities has its headers "stuck" to the top of the screen below the tab names ([see screenshot](https://ibb.co/zFQ65q3)).

**To Reproduce**
1. Go to overview
2. Click on "Cities" tab
3. The icons are at the top instead of being aligned to the table

</details>

**Expected behavior**
correct alignment

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://ibb.co/zFQ65q3)

**Additional context**
also tested unciv 4.8.9 (gh releases) - same issue
but i couldnt repro the issue in unciv 4.8.8 (gh releases)

**Comment by yairm210** [comment]
@SomeTroglodyte  #10197

**Comment by somesi** [comment]
> I can't see those screenshots
<img width="960" alt="ss-unciv-2" src="https://github.com/yairm210/Unciv/assets/146617020/1c41ccd9-2598-42c2-8ba4-92164b915bc4">

(I didnt knew gh supported inline images in comments)
