### ISSUE TITLE
Feature request: Counter-offer cannot be cancelled

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10218]
**Is your feature request related to a problem? Please describe.**
I've recevied an offer that seemed bad at first, but when i went to counter the offer i realised i didn't have the ressources i wanted. So i tried to send the offer back untouched, hopeful it would be instantly accepted... but it didn't and i just wasted a turn.

**Describe the solution you'd like**
When you counter-offered another player but changed your mind and want the trade as it was sent to you, there should be a way to accept the initial trade. A "Cancel" button perhaps, or "Revert to initial trade" with the assurance it will be instantly accepted if left as such.

**Describe alternatives you've considered**
Maybe it could help if trade offers could be stored in a special menu or button at the start of the round so we can roam the map freely before accepting trade offers (but being prohibited from moving and producing units).

**Comment by PathosEthosLogos** [comment]
+1
There should be 'revert to original offer' button also.
Then after it's clicked, 'accept incoming offer' should be an option, unless changed.
