### ISSUE TITLE
Limited to [amount] per Civilization doesn't work on improvements

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#10223]
A bug or rather a request?

The above-mentioned unique doesn't work on improvements.
I've tried using stockpiled resources to limit an improvement, and it also isn't working for me, so it would be easier if "Limited to 4 per Civilization" worked on improvements.

What if it's in unclaimed land?
The same as roads, the owner is the one who built it.

**Comment by yairm210** [comment]
This is a request
As for unclaimed land, we're just going to ignore that for now. The road owner is a hack we did to be Civ V compliant, I don't see a good reason to do so again

**Comment by yairm210** [comment]
In any case this is a #3242 comment
