### ISSUE TITLE
Single Defensive pact button

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#10236]
I'll fix this soon. Just a documentation of this problem.

When offering a defensive pact and with the DoF flag countdown at one and their DoF flag countdown already at 0 and removed, the Defensvie pact button will only show on one side of the trade.
<details><summary>Picture</summary>

![DoF flags unequal](https://github.com/yairm210/Unciv/assets/7538725/5b392b51-84d1-4a86-8903-d1f96221d9bb)

</details> 

Should the defensive pact be offerable with only 1 DoF flag active? Or should it require 2 DoF flags?

With one flag, the defensive pact could be offered after the DoF expires but we can indefinitely counter offer to have the same effect anyway.
I am currently leaning towards 1 DoF flag.

**Comment by yairm210** [comment]
1, this could also be a solution to the 'extend open borders' request that's still open

**Comment by tuvus** [comment]
> 1, this could also be a solution to the 'extend open borders' request that's still open

I think extending treaties such as open borders, DoF and Defensive pacts should be a separate PR. It would be nice if we could modify DoFs and defensive pacts so that they don't send a notification to everyone when they are extended.
