### ISSUE TITLE
Missionaries no longer behave as intended

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10235]
Vanilla (likely irrelevant: Save created with 4.8.10 on Android, mostly default settings - my Modern Joke Religions mod is in there, but that one has only Religions and Beliefs, no changes to Units or anything else)
* A missionary no longer dissoves into a puff of smoke when their Faith is used up (their spread religion actions are exhausted).
* A missionary retains movement after spreading d... f... ahem, _Religion_ - minus one MP instead of stopping for the turn like before.
* When that "action costs 1 movement" is _intended_ for a mod unit, then the unit should not be marked as non-due, that is, auto-select next unit should stay with the unit.

**Comment by yairm210** [comment]
The second point is known and I have a plan
The first point is not - can you attach a game save?

**Comment by yairm210** [comment]
Third point - good catch! Should be part of unit modifier effects

**Comment by yairm210** [comment]
All remaining is the solution to point 2 that I have planned
