### ISSUE TITLE
Cheap unit upgrade cost

### ISSUE THREAD

**Issue by Danitrst** [yairm210/Unciv#10246]
**Platform**
Android 12

**Version**
4.8.8

**Describe the bug**
Infantry units can be upgraded to mechanised infantry at 15gold only. Same issue with tank to death robot

![Screenshot_2023-10-05-09-06-18-62_5b83b50424e447777d9855d9701553df](https://github.com/yairm210/Unciv/assets/147033635/063b16e3-bcb8-47bb-b037-3f8359cf4f73)

**Comment by yairm210** [comment]
Sounds legit to me, want to upload a save file?

**Comment by yairm210** [comment]
Not a bug, should have been closed long ago
