### ISSUE TITLE
Great prophets don't naturally appear anymore 

### ISSUE THREAD

**Issue by Anon177013** [yairm210/Unciv#10240]
**Platform**
Android 12

**Version**
Bug present in 4.8.9 and 4.8.10 
Bug not present in 4.8.8

**Describe the bug**
Great prophets no longer spawn once a certain faith threshold is hit. 

"Minimal faith required for the next great prophet" is also missing from the Religion tab in the Overview.

**To Reproduce**
1. Start a new game
2. Found a city
3. Start generating faith
4. Once you get enough faith, found a Pantheon
5. Go to 'Overview' then 'Religion' 

"Minimal faith required for the next great prophet" is missing 

6. Continue playing and generating faith 

No matter how much faith players and AIs accumulate, no great prophet ever appear unless a civilization choose to get one upon completing the Liberty policy or the Tower of Pisa wonder.

**Expected behavior**
Great prophets should automatically spawn once you have enough faith. 

"Minimal faith required for the next great prophet" should be displayed in the Religion Overview.

**Other**
Workaround for now : roll back to 4.8.8

**Comment by yairm210** [comment]
Oh, interesting! Yes, if unit is null this should return *true*

**Comment by yairm210** [comment]
Tested locally, works
