### ISSUE TITLE
Auto-assign city production option no longer working

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#10258]
**Platform**
Android

**Version**
4.8.10 (Build 920) from Play Store

**Describe the bug**
The option doesn't appear to work anymore.  Even when the option is on, once city build queues are empty you get the Pick Construction prompt instead of a building or unit automatically being added to the Current construction.

**Additional context**
It still works occasionally, but I think only for your capital city?  I haven't tested exhaustively.

**Comment by RWoof** [comment]
I'm having this issue on both PC and Android after updating to the latest version. I can turn on automated city production but at the start of each new turn the game asks me to assign production again and I have to go into the options and disable/enable automated city production for it to work for that turn only. Unplayable for me until this is fixed.
