### ISSUE TITLE
Religion is broken since 4.8.9 - SOLVED in 4.8.11

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#10257]
**Platform**
Android

**Version**
First noticed this issue in 4.8.9-patch 2 (Build 919) from Play Store

**Describe the bug**
1. Great Prophets never get generated.  Previously several would appear in the early game.  They do still appear from Wonders and Policies though.
2. AI players almost never found religions (I assume because of issue above)
3. After Great Prophets and Missionaries have all their spread religion charges used up the units don't disappear.

**Comment by IsNss-DFFEF** [comment]
> Already fixed in 4.8.11

still yet on mobile tho

**Comment by IsNss-DFFEF** [comment]
i made that 40 minites it was available on mobile
do not blame my past self indirectly for not foreseeing religion would be fixed 40 minutes after he posted.
also "tho" is a word
a word is a something enough people use and recognise for the propagation of information, "tho" is an extremely prevalent shorthand for "though", thus its something enough people use and recognise for the propagation of information, making it a word. also this is the internet, why the fuck do you care?

**Comment by IsNss-DFFEF** [comment]
i profusely apologise for my argumentative tone in responding to your admittedly, pretty useful post.
