### ISSUE TITLE
Feature Request: Select civilizations with defined starting locations on New Game screen

### ISSUE THREAD

**Issue by PLynx01** [yairm210/Unciv#10255]
I've come up with a feature that will make setting up a game with custom map quicker and more convenient. I would like to see the "select civilizations with defined starting locations" option on the new game screen.
Here are the reasons to implement this feature.

1. As I mentioned earlier, it will make setting up a game on a custom map quicker and more convenient, especially when it comes to earth maps. Now, if you want to play on earth map with True Starting Locations, you need to choose civilizations manually, which takes a lot of time.

2. It will make the game a bit more realistic, because there won't be civilizations that don't belong in that part of the world. (No more Egyptian civilization spawning in Australian deserts, unless described feature is turned off)

What do you think about my idea?

**Comment by PLynx01** [comment]
In my opinion, it would make more sense to place that option in New Game screen. I imagine it that way.

Let's assume I would like to play on the world map with true starting locations, but without 2-3 civilizations in Europe (because it tends to be overcrowded), so I do the steps below:

1. I select the "Select the civilizations with defined starting locations and the game selects all civilizations with defined starting locations
2. I remove from the civilizations list, for example Denmark and Portugalm, in order to make more space in Europe
3. I start the new game 

I also believe that this option will be useful on maps that contain one-two continents/regions. As I said earlier, there will be an option to easily eliminate civilizations that don't belong on that continent or region, like Egyptian Civilization in the Australia outback I mentioned earlier.

Maps that doesn't have defined starting locations, wouldn't have this option available.

**Comment by PLynx01** [comment]
> Question: How to choose Human/AI? Human = first? Extend map schema and editor to allow declaring a preferred human?

I think that player should choose the first civilization to play as a human, and then select the option to populate the civilizations list with AI players. 

As I said earlier, the civilizations list has to be editable as it is currently.

Do you have more questions?

**Comment by SeventhM** [comment]
Closing as duplicate of #11229
