### ISSUE TITLE
Missing text icons

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#10265]
![image](https://github.com/yairm210/Unciv/assets/8366208/5e49ded3-c189-4824-821b-87cfbb18af3c)

Version 4.8.12
Seen on Android and PC, reported by multiple users

![image](https://github.com/yairm210/Unciv/assets/8366208/6d649b53-db5c-4bb0-a75c-48c6dffffe2a)

Example with modded images

@SomeTroglodyte

**Comment by yairm210** [comment]
That's fast work, private!

**Comment by Diraven8** [comment]
Is this the same issue where the icons are also gone on the research and policy screens in 4.8.12?

**Comment by Diraven8** [comment]
Maybe you already fixed it for the next version when you said you found it above?  Bug was introduced in 4.8.12.  Basically the tiniest icons for production, food, research, gold, faith, culture, and happiness are gone everywhere in the game, not just the menus in the pics above

**Comment by SeventhM** [comment]
> I see no such issue

Note: current release version is 4.8.12, which does not have your fix. Tbh, given the war taking time from Yairm, someone other than Yairm might need to set up the release from GitHub actions

**Comment by kaspars-vilde** [comment]
Same. Worked fine for years, not all small icons are gone. Last update broke it. Tried uninstalling, removing cache/storage, disabling all mods, zero effect.  How is testing being done? If you see such a game breaking bug, you should instantly revert the version..
