### ISSUE TITLE
Save game fails to load

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10268]
v4.8.12 / Android

I'm updating units and UnitTypes, reloaded my mod ([Z2](https://github.com/hackedpassword/Z2)), Unciv complains it can't load the autosave game, neither via manual load. Most likely tripped some logic - _my guess_ is it has to do with introducing `<before|after discovering [tech]>` to honing timing of some attributes.

[save game](https://github.com/hackedpassword/Unciv-Assets/blob/20d3de1ab42bb856c6c46e773a29df874d023a3b/Issues/10082023%20fail%20to%20load.txt)

Files updated leading to this error, diffs:
[jsons/Units.json (big update)](https://github.com/hackedpassword/Z2/commit/3bd88672341349c2562df72f75065c281c7065ad)
[jsons/UnitTypes.json (initial update)](https://github.com/hackedpassword/Z2/commit/1b758d6e3c217ef63cfa34a0161d82ab8a28ff8b) and further [bracket fix and update](https://github.com/hackedpassword/Z2/commit/b2d57cb56e2965458f78f6fd17ce0b14e2b8b3e9)

**Comment by SeventhM** [comment]
Mod seemingly has errors. Please check the in-game mod checker
Namely, you're missing the unitType named "Payload"

**Comment by hackedpassword** [comment]
Interesting. I suppose I'd been leaning on the general mod checker too hard, and had overlooked the ruleset specific mod checker.

Thank you @SeventhM

**Comment by hackedpassword** [comment]
Solved!

Instead of a cannot load error with just a friendly message to contact yairm210, maybe linking to the mod checker(s) could also be suggested?

Closing
