### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by SoraDevin** [yairm210/UnCiv#1027]
This is open source and unmonetised right? Could probably even use actual civ music (IANAL tho). Otherwise happy to find some free use stuff that's suitable if I ever get the spare time to (same goes for general coding help but don't hold your breath)

**Comment by SoraDevin** [comment]
Also, add option to toggle music and set volume

**Comment by Trilarion** [comment]
"Could probably even use actual civ music (IANAL tho)." That's not how it works usually. The copyright owner of the actual music could then come after you at any time and sue you.

The only way out as far as I know is for people who bought a Civ V copy, write a tool that extracts the music from there and puts it in a local copy from here for your personal use. But even there I'm not sure.

**Comment by SoraDevin** [comment]
I mean anyone could have their own music on their media player, but there are tonnes of other fair use music that would be appropriate.

**Comment by yairm210** [comment]
If you have good example soundtracks for each of the eras, that's a good place to start

**Comment by lishaoxia1985** [comment]
i don't think it's a good idea, that the file size of this app is so small is an advantage. 
i have a suggest: we can use internet resource in this app, and don't put music in app.
in china, there are some good website, such as:
https://music.163.com/
you can find all music of civ 4, 5, 6. 
if we can use the link directly through technology (i think it's not very difficulty).
the only question is about the copyright. i don't understand law.

**Comment by yairm210** [comment]
My understanding is that the original music of the Civ games is the property is the game company.
But, we could find music that fits the 8 erasz for a start, and the user could choose to download them

**Comment by yairm210** [comment]
Added basic background music in 9dee9f8 =D
