### ISSUE TITLE
In game icons missing?

### ISSUE THREAD

**Issue by RevBiskit** [yairm210/Unciv#10300]
**Platform**
Android 8.1 arm

**Version**
Version 4.8.12 build 922

**Describe the bug**
I have tried installing the game from the play store and the APK from GitHub.  Same issue, so it may be me however, the issue is with the icons in the game.  When you start any game, tap the settler, the found city option in the list of available option does not have an icon between the ( ).
Found a city, then go into city production. The icons in the list of buildable items do not appear, meaning next t each item is the number of production and the number of turns.  The icons ( the brown bear and the white hourglass ) no longer appear.
All other icons, map, information bars, etc., Appear fine.

**To Reproduce**
1. Start a new game (any, modded or not)
2. Tap on the settler
3. See the Found city missing icon
4. Found a city
5. Tap on city production.
6. See missing icon in production list

**Expected behavior**
Icons to appear as normal

**Screenshots**
![ScreenshotCapture_2023_10_09_20_24_54_371](https://github.com/yairm210/Unciv/assets/145246726/e2795896-2d00-4018-8d0c-cd5e665faf75)

**Additional context**

**Comment by yairm210** [comment]
Copy of #10265 , done
I'll reopen the other ticket so it's visible

**Comment by Diraven8** [comment]
Is this the same issue where the icons are also gone on the research and policy screens in 4.8.12?
