### ISSUE TITLE
City state declared war on itself

### ISSUE THREAD

**Issue by Dwyriel** [yairm210/Unciv#10304]
**Platform**
POCO F1, Android 11 64 bit.

**Version**
F-droid, version 4.8.8

**Describe the bug**
City state declared war on itself alongside almost everyone else.

**To Reproduce**
No idea, too many things happening at one time, also didn't try to replicate as the game ended soon after and it'd take too long to start a new one.

**Expected behavior**
City state (or any entity) not declaring war on itself.

**Screenshots**
![milan](https://github.com/yairm210/Unciv/assets/61030926/b19fc4b2-006a-4d5e-98b3-a0150afc2198)

**Additional context**
No mods used/installed, game/match created with default settings (didn't change anything other than selecting random for my own civ). Happened around turn 300, I was mostly fast forwarding turns until I saw a bunch of declarations of war. 

I did check the issues page but didn't seem like this was reported yet.

**Comment by tuvus** [comment]
This was fixed in #10238, released in 4.8.11. There wasn't an issue on GitHub about it, only on the Discord server. Please tell me if you can replicate the problem after 4.8.11.

**Comment by Dwyriel** [comment]
@tuvus Oh I see, I'll play a few more games in the following days and see how it goes, if everything is alright I'll close this issue. Sorry to bother about an issue that's supposedly fixed.

**Comment by tuvus** [comment]
No problem!

**Comment by Dwyriel** [comment]
Played 2 more games (same settings) with plenty of wars being declared and no weirdness in sight. Seems to be fixed as previously mentioned.
