### ISSUE TITLE
Resources in tech tree locked

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10317]
Trying to relocate strategic resources to other techs - but they won't move from the default G&K positions. I'll break it down:

v4.8.13
Mod: [Z2](https://github.com/hackedpassword/Z2)
baseruleset: false (is expansion)

We'll use coal as the [target resource](https://github.com/hackedpassword/Z2/blob/b3401eae36538a0621b2580b11b984488e176c5a/jsons/TileResources.json#L37) example. I'm moving the revealedBy tech to [Steam Power](https://github.com/hackedpassword/Z2/blob/b3401eae36538a0621b2580b11b984488e176c5a/jsons/Techs.json#L375). Should be straight forward, change the revealedBy. In-game, the tech tree is unchanged.

I let this go for several iterations as I continued working in the [tech tree](https://github.com/hackedpassword/Z2/jsons/Techs.json) (WIP). No change. Updated to 4.8.13, no change (though that did fix a missing resource icons but). Tried an exclusion of the parent ruleset config via [ModOptions](https://github.com/hackedpassword/Z2/blob/b3401eae36538a0621b2580b11b984488e176c5a/jsons/ModOptions.json#L12), still nothing.

![Screenshot_20231014_133312](https://github.com/yairm210/Unciv/assets/119975434/3cce006c-ed67-43ce-a3e0-2a1b669b077c)

In this instance, the behavior appears that the parent ruleset G&K is taking precedence. Did I not configure something to allow moving the resource? Searching the G&K repo dir reveals no additional config needed.

**Comment by SeventhM** [comment]
Ah, Yeah, remove your copy paste versions of the resources. Things typically override in order of base, then mod, top to bottom. If you list an object twice, it usually only takes the last one (Rekmod actually used to have a whole civ overridden by accident this way). I think you forgot that you can set G&K as a base ruleset, making the duplicates unnecessary

**Comment by hackedpassword** [comment]
Wow, how did this happen? Dupe resource? Did I just work on this too late? (likely)

Before I go any further, I appreciate you guys taking the time to investigate. Thought I covered everything... wrong!!!

> The programming language itself is mocking us, right?

Absolutely. Well just me this time. Ugh!

> you can set G&K as a base ruleset in the mod checker, making the duplicates unnecessary

Really. Having to specify the dupes seemed to be kinda ridiculous. I'll definitely check that out. Nope, didn't know. :)

**Comment by hackedpassword** [comment]
Maybe should not have closed?

Hey, ok, I'm combing the [wiki](https://yairm210.github.io/Unciv/Modders/Mod-file-structure/5-Miscellaneous-JSON-files/#modoptionsjson), stepping through [unciv-mod-expansions](https://github.com/topics/unciv-mod-expansions), only instance of specifying a baseruleset mod is for incompatibility. Trog, [your mod](https://github.com/SomeTroglodyte/Aliens-have-crashed-on-Earth/blob/master/jsons/ModOptions.json) is the closest I have found to specifying a mod, but inversely.

> set G&K as a base ruleset in the mod checker

![Screenshot_20231014_211010](https://github.com/yairm210/Unciv/assets/119975434/6e40fda0-f8d7-4be7-9967-13d122a10b48)

We talking about that, or a config option? I'm not trying to sound clueless, just hitting a lot of dead ends.

**Comment by SeventhM** [comment]
> We talking about that

Yeah. That should combine your mod with the base when checking for mod errors, meaning you shouldn't need to redefine stuff

**Comment by hackedpassword** [comment]
Z2 has become somewhat of a proving grounds for modding unciv. I have a clear direction and outcome, but there's a lot of fun things I've picked up along the way that didn't have anything to do with the intended mod dev. Like the tech tree, something _tiny_ needed to be changed, led to a whole tree shuffle. And it was fun as heck remaking it!

You're right, there is reason to make Z2 a base ruleset. Because the direction is 100% to capture the Hyrule map only as an Unciv battleground, to simplify my learning curve I stripped all the map generation params out, making it unsuitable as a base. Maybe eventually I'll open up to generating other places in the Zelda world - that's a whole project of its own.

The more immediate plan is to split off the content/assets that are not specific to intended Z2 gameplay as their own mod(s) once Z2 is ready in full. The new ordnance and advanced GDR's are super great for example though outside the theme scope. Lot of really good things going on on this mod - bridges, era-based villagers from the game, even lava and caves - and still I see so much more potential. Lots more to learn too. 

Has anyone forked unciv as a game engine to become a different game entirely, to your knowledge?

**Comment by hackedpassword** [comment]
@SeventhM fyi after analyzing all the garbage dupes in that resources json, what I found is within the github web interface via chrome, copy-paste, specifically copy, gets glitchy when scrolling. The repeated dupe fragments made no sense. The behavior looks like fluid responsiveness is where that glitchiness lies. Will have to be more careful.

**Comment by SeventhM** [comment]
> except a lot of extra fields and methods to store loading problems into the Ruleset to retrieve later

Maybe you push down the amount of fields to just a couple
```kotlin
// in Ruleset.kt
val log = ArrayList<String>()

private fun <T : INamed> createHashmap(items: Array<T>): LinkedHashMap<String, T> {
        val hashMap = LinkedHashMap<String, T>(items.size)
        for (item in items) {
            if(hashMap[item.name] == null)
            {
                hashMap[item.name] = item
                (item as? IRulesetObject)?.originRuleset = name
            }
            else
            {
                log.add(item.name)
            }
        }
        return hashMap
    }
```
