### ISSUE TITLE
Music and Android app lifecycle: Plays when it shouldn't

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10316]
**Platform**
Android 12 (LineageOS 19)

**Version**
Build from source

**Describe the bug**
Music re-starts playing while the app is not on-screen.
I am pretty certain I had situations where two tracks were playing simultaneously.

**To Reproduce**
1. Launch Unciv, have music available and volume > 0. You hear music.
2. From main menu screen (the one with the quickstart button), hit Android's "home" button while the track still plays.
3. Music is faded out and stays so until you re-enter Unciv via Android's recent-apps, then fades in and continues the track where it left off - as intended.
4. Now resume or start a game. From WorldScreen, hit Android's "home" button while the track still plays.
5. Music is faded out and stays so for the duration of the "silence between tracks" setting, then starts a new track - while you're still looking at your phone's launcher.

As for double tracks, I do not know how to reproduce!

**Additional context**
The pause problem is partly understood - MusicController.pause should not bail for State=Silence or some other situations. The state is set to Silence from an unknown source within the UncivGame.pause override, *before* it calls MusicController.pause. No idea how yet.

Android app lifecycle is complicated: Home sends the App into a different state than having the Device turn the screen off or go into true sleep. Swiping the app out of the recents list is most of the time the exact moment the process terminates, but 'roid still has the option to allow an app to continue where it left off across processes via its Bundle mechanism (though I can't provoke an Unciv startup with a Bundle). Somehow in there is a loophole to get extra playback through either orphaned MusicController instances or orphaned Gdx.Music instances - challenge: find out which and how.

I'd really love to hear from others on how the Unciv Music system behaves for them: Do you have a device where the above steps do not reproduce the stated observations? Do you know a sequence of steps to provoke double tracks?

**Comment by hackedpassword** [comment]
I don't use music in Unciv at all. Mentioning this only for its statistical value.
