### ISSUE TITLE
RFC: Do you see the difference, is it worth investigating?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10314]
![Screenshot_20231013-Noshadow_Unciv](https://github.com/yairm210/Unciv/assets/63000004/eff63cdc-16ad-4b86-af91-20cf466ac3d8)
![Screenshot_20231013-Shadow_Unciv](https://github.com/yairm210/Unciv/assets/63000004/6ece8a64-267a-47ec-9cde-256f4fb28be4)

**Comment by Caballero-Arepa** [comment]
It looks better imo
(Longer comment later)

**Comment by SeventhM** [comment]
For the menu items it looks better, for the help button at the bottom it looks notably worse

**Comment by SeventhM** [comment]
Ah, on a computer now where those images are super zoomed in, and zoomed in, the shadows look pretty terrible when limited to their bounding box. At a distance it looks fine, but I doubt it'll be a good idea to rely on an atlas for the font of everything, and once you see it up close, it looks a lot like there's ugly artifacts
