### ISSUE TITLE
Feature request: correctly notify players about attacking tile improvements

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#10329]
When a tile improvement deals damage to a unit, the notification always calls it a Citadel, even when the improvement has a different name. If possible, I'd like to see the notification properly name the attacking improvement instead of being hard-coded to call it a Citadel.

**Comment by hackedpassword** [comment]
Take a look, there are two uniques both attacking adjacent units. In G&K, Citadel uses:
["Adjacent enemy units ending their turn take [30] damage"](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/Civ%20V%20-%20Gods%20%26%20Kings/TileImprovements.json#L226)

Maybe try the other?
"Deal [amount] damage to adjacent enemy units"


DamagesAdjacentEnemyUnits("[Adjacent enemy units ending their turn take [amount] damage](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/unique/UniqueType.kt#L575)", UniqueTarget.Improvement),
DamagesAdjacentEnemyUnitsOld("[Deal [amount] damage to adjacent enemy units](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/unique/UniqueType.kt#L935)", UniqueTarget.Improvement),
DamagesAdjacentEnemyUnitsForExactlyThirtyDamage("[Deal 30 damage to adjacent enemy units](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/unique/UniqueType.kt#L1003)", UniqueTarget.Improvement),

Citadel dmg fun: [fun doCitadelDamage()](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/logic/map/mapunit/UnitTurnManager.kt#L73)
