### ISSUE TITLE
Great Mosque of Djenne does not give Devout promotion to auto-created Great Prophets

### ISSUE THREAD

**Issue by Thomas-N** [yairm210/Unciv#10325]
**Platform**
Android 12 (Lineage OS 19)

**Version**
4.8.12

**Describe the bug**
Great Mosque of Djenne should give the Devout promotion to all newly-trained Great Prophet units in the city. It doesn't seem to do this for Great Prophet units that get auto-created (before the Industrial Age). It works fine for Missionary units and for Great Prophets you purposefully train later in the game.

**To Reproduce**
1. Construct Great Mosque of Djenne
2. Wait for a Great Prophet to spawn in that city

**Comment by SpacedOutChicken** [comment]
According to this wiki, this is how it it works in the base game: https://civilization.fandom.com/wiki/Great_Mosque_of_Djenne_(Civ5)

If the wiki is accurate, then this isn't a bug.

**Comment by Thomas-N** [comment]
Thanks for the reply. In that case you're right and the previous behaviour was a bug, that was fixed recently by this change. My mistake.

I guess this makes the Great Mosque a bit less powerful, although you can probably still make it good by training lots of missionaries to keep the Great Prophet cost low, before rushing to Fertilizer and then convert the whole world. New strategies to consider...
