### ISSUE TITLE
Feature request: Automated units stay automated after upgrading

### ISSUE THREAD

**Issue by RWoof** [yairm210/Unciv#10323]
Currently when automated units auto-upgrade this breaks automation and you need to re-automate every unit that upgraded. This normally isn't much of a bother but in the late game for example when tons of units upgrade to mech infantry it's a bit of a pain to automate them all again, especially since you need to click more and then click automate, making it two clicks/presses for each unit. 

It would be nice to have an option to toggle "Automated Units Stay Automated After Upgrading" in the options menu so people could turn it on or off to their liking.

**Comment by RWoof** [comment]
> [Not mysterious...](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/logic/automation/unit/UnitAutomation.kt#L143) But this would be easier with a testing game ready - one at the end of a turn right before your observation hits.

I have a here from my android phone that's 4 turns away from mech infantry, sorry that's the closest I have.

[Unciv.txt](https://github.com/yairm210/Unciv/files/13179787/Unciv.txt)

**Comment by yairm210** [comment]
If an automated unit upgrades it should stay automated, no setting.
