### ISSUE TITLE
Uniques"[stats]" is not valid for Terrain

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10320]
![image](https://github.com/yairm210/Unciv/assets/114050365/21eccaa9-0a3a-456e-9ffc-ffa1427d4645)
`
	{
		"name": "Plains",
		"type": "Land",
//		"food": 1,
//		"production": 1,
		"movementCost": 1,
		"RGB": [153, 180, 51],
		"uniques": ["[+1 Food, +1 Production]"......]
	},`
![image](https://github.com/yairm210/Unciv/assets/114050365/fb93bb99-29fc-4d12-8e7b-15c134605713)

**Comment by AutumnPizazz** [comment]
![image](https://github.com/yairm210/Unciv/assets/114050365/39cde912-cc17-4034-9a33-95c25a06ad02)

**Comment by SeventhM** [comment]
> Hmmm... #6379 added the UniqueTarget.Terrain to that UniqueType even though **there is no implementation**, as you're supposed to use StatsFromTiles instead...

Hmm... I'm not sure this is a satisfying answer from a modding standpoint. Might be something I add to the list of stuff I work on later
