### ISSUE TITLE
Loading Server Error

### ISSUE THREAD

**Issue by Schoenios** [yairm210/Unciv#10331]
Here is the picture of the error message. 

![Screenshot_20231020-215832_Unciv](https://github.com/yairm210/Unciv/assets/136274770/a4f441de-8175-4617-a5d4-bb6fdb04e409)

This message has been sent to me since yesterday. The update fails permanently and so I ask you what could be the problem? Otherwise I had my friends send me the server ID again and deleted the old server. After that the update worked again. But I wanted to get to the bottom of it in more detail. Kind regards, LS.

It's the "newest" Version: 4.8.12

**Comment by pikdox** [comment]
happened to me too
