### ISSUE TITLE
Can the error message for marking class "uniques" be canceled?

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10335]
![image](https://github.com/yairm210/Unciv/assets/114050365/93443f30-4638-4249-ac36-d7fc321291a6)
This type of uniques a powerful tool for modders to categorize the types of buildings or units. While green text errors do not hinder gameplay, such errors should be completely ignored (just my opinion).

**Comment by AutumnPizazz** [comment]
Maybe forget. And by 4.8.16 this defective has not disolved.

**Comment by yairm210** [comment]
When we disabled them, we saw that a lot of uniques that modders thought were working were, in fact, not working at all.
So we need to choose a side, and this is the lesser of two evils

**Comment by yairm210** [comment]
With the recent changes to ignore filtering uniques I think we can consider this closed
