### ISSUE TITLE
Adding alternate colors for Civilizations

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#1033]
I've played the original Civ V, where I played Egypt and I also put an AI as Egypt. I remember that I kept the original colors for Egypt (yellow and purple), while the other IA had another set, like (brown and pink). Thus, I was wondering if there was a way to add alternate colors for the playable civilizations.

**Comment by yairm210** [comment]
It doesn't look like this is an original Civ feature, maybe it was from a mod...?
Anyway, since at the moment it's impossible to have 2 instances of the same civilization in the same game, this is not really relevant
