### ISSUE TITLE
Vanilla ruleset : path to "Nanotechnology" not displayed properly

### ISSUE THREAD

**Issue by Anon177013** [yairm210/Unciv#10357]
Also the only required tech is "Particle Physics", I don't know if it's the expected behavior.

**Platform**
Android 12

**Version**
4.8.14 and before (already present in 4.8.8 if I remember correctly)
Vanilla ruleset only 

**Screenshots**
![Screenshot_20231025-202541](https://github.com/yairm210/Unciv/assets/146986415/e966d758-a335-484d-9279-494b67f067c8)
![Screenshot_20231025-202602](https://github.com/yairm210/Unciv/assets/146986415/0f66b41e-1777-4d05-bb19-25c89db70f66)

**Comment by Anon177013** [comment]
Wouldn't it be clearer by moving the vertical lines to the right of Nanotechnology?

**Comment by SeventhM** [comment]
I'd say 6 or 7. Also, what is this cursed tech tree vanilla has?

**Comment by SeventhM** [comment]
I mean this ghost town of a final era. Between 2 columns there's only 3 techs, despite the efforts to have 5 techs per column
