### ISSUE TITLE
RFC: "if no other Civilization has researched this" Conditional on Policies?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10350]
[Unique.kt line 336](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/unique/Unique.kt#L336) tests policies after making sure the source object is a Technology. Huh??? Any modder using that conditional on a Policy (and wondering why it doesn't work)?

**Comment by SeventhM** [comment]
`ConditionalFirstCivToResearch` equates to `<if no other Civilization has researched this>`. Use of the word "research" implies this is supposed to be for techs only. I'm... Surprised it even has policy code
