### ISSUE TITLE
Luxury resources without techs

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#10366]
**Platform**
Windows, Android

**Version**
4.8.13 (Build881)

**Describe the bug**
If you put a city on a luxury resource, you get it with closed technology.

**To Reproduce**
1. Start the game 
2. Found city on Luxury tile without technology
P.S. This applies to any luxury resource and this works for other cities, not only the capital
P.P.S. But I'm not sure if this is a bug and not a feature. If it's a feature, you can close it right away.

**Expected behavior**
No luxury without technology.

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/59770002/b21b12a7-4339-4721-8e05-4fd013d9eae0)
![image](https://github.com/yairm210/Unciv/assets/59770002/4caba29f-c6c8-44b5-b859-99a08e58072b)
![image](https://github.com/yairm210/Unciv/assets/59770002/67cd9991-e0e5-4cec-8768-3e8ad06d194e)
![image](https://github.com/yairm210/Unciv/assets/59770002/020bff3e-1288-4aa9-84b4-2a45aa07c262)

**Comment by DeStup** [comment]
I am not sure that it is original's rules. i understand that unciv not civilization V, but the mechanics are the same
![image](https://github.com/yairm210/Unciv/assets/59770002/283ab75e-350a-4ad3-b462-adb6fda6c6a6)

**Comment by DeStup** [comment]
Yeah. 
The icon is removed, but the luxury resource is still in the city's place.
In this case, the palace works like a plantation after researching the technology. This applies to any luxury resource
The gif showed citrus tiles and happiness statistic before and after researching Calendar.

https://drop.picasoft.net/r/QXF6rTJP#ntg8zGrhFRwe5GRWeq/QSRFD+Sr4EZf5ugTZJO3Q3oE=

**Comment by yairm210** [comment]
From what I understand, then, Civ V treats lux resources as unobtainable if they require a specific improvement that requires a tech you don't have? What a mess.
