### ISSUE TITLE
RFC: Leader Voice-overs

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10368]
[See new entry on my scrapers page](https://github.com/SomeTroglodyte/Scratchpad/blob/master/README.md#demos): There's a publicly available download on itch containing the leader voice-overs, could be the originals.

I'd like to implement them in game, at first those that have a corresponding text in our Nations.json - but there are more. Peace treaty, they defeat you, they demand, yes and no and 'let's hear it' in various moods - and George is the only one with an "Excellent!". 

* Would be a futile exercise if no-one but me gets these sounds, even if I've prepared almost trivially simple instructions how.
* Those other sounds - are there good places in our diplomacy "flow" where they belong, but we just haven't done them as nation-specific strings?

Opinions?

**Comment by Cwpute** [comment]
I thought this was a call for VAs to entirely re-do the leaders' voice-overs 👀 would've been interested.
But this would be nuce too 👍
