### ISSUE TITLE
City names in field improvements are displayed incorrectly in the German translation

### ISSUE THREAD

**Issue by TheKingOfLight** [yairm210/Unciv#10369]
**Platform**
Linux Mint 21.2, 4.8.14, 64bit.

**Version**
From Flathub, Build 924

**Describe the bug**
When I create a field improvement, the menu shows "- \[city name](dir)".

**To Reproduce**
1. start a game
2. have the game in German
2. choose a worker and select Build Field Improvement
3. the "code" instead of the city name is displayed

**Expected behavior**
Instead of this code, the corresponding city name should be displayed and a "link" to the city.

**Screenshots**
![grafik](https://github.com/yairm210/Unciv/assets/72839891/43bfe46b-5464-483f-a04f-355247cd3a04)

**Additional context**
Happens in all multiplayer games
Tested in single player and multiplayer

Another problem that might have something to do with it: The icon for guilds is not displayed in German (as shown in the screenshot).

**Comment by SeventhM** [comment]
Closed as solved
