### ISSUE TITLE
Ruin reward rollback

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#10373]
**Platform**
Windows, Android

**Version**
4.8.13 (Build 923)

**Describe the bug**
You can change the reward you receive from a ruin by Ctrl-Z unit's move.

**To Reproduce**
1. Find ruin
2. Get the opportunity to roll back the movement. (I don't know, it works weird, sometimes it appears, sometimes it doesn't)
3. Roll back move Unit on ruin.

I'm showing how it works in a multiplayer game. But this can be reproduced in single player as well.
![Unciv_AjHEZCWTfU](https://github.com/yairm210/Unciv/assets/59770002/41c03a4c-a473-4d3e-a3d5-9ebb4679b54b)

UPD. Attached save
Save game 
[Bug_ruin.txt](https://github.com/yairm210/Unciv/files/13196795/Bug_ruin.txt)

**Comment by DeStup** [comment]
Attached the save.
I tested the version you attached. Now you can't cancel your move when you step on a ruin, right?

**Comment by yairm210** [comment]
I think the correct solution is to tie the randomness to the tile location, NOT to disable undo.
This can still be save-scummed manually.
