### ISSUE TITLE
RFC: Numeric Unique parameter types

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10385]
When we fix mod check not catching RekMod's mistake of using the actual letters "amount" for an `amount` parameter, then our vanilla Rulesets will fail too... Because `amount` only accepts integers, and `TileGenerationConditions` declares type `amount` but actually uses decimal fractions.

I went through half of the `UniqueType` enum, and almost all _implementations_ where the Unique uses `relativeAmount` do already accept Float, some even Double. The _check_ on `relativeAmount`, though, demands integers.

But - `GreatPersonPointPercentage` and `GreatPersonBoostWithFriendship` declare `relativeAmount`s that can't trivially be converted to allow Floats, because the function return is cached in an Int, and Great Person Point counters won't count Floats either. So the idea to officially allow decimal places on `relativeAmount` and make `TileGenerationConditions` use `relativeAmount` - not so fast buster.

Q: create and apply new `UniqueParameterType`s for Float-accepting parameters, both absolute and relative, and change a large number of `UniqueType`s over to those? Or simplify, declare `amount` is integer, `relativeAmount` is Float, and patch up `GreatPersonPointPercentage` to declare `amount`?

**Comment by yairm210** [comment]
Refactored the entire base ruleset vs non-base-ruleset to be clearer, and solved this problem and some others along the way

**Comment by SeventhM** [comment]
> so RekMod's "Unlocks" and "Great Art" uniques

Fun fact: it's also a translation aid because they only need to use a single translation key in "Unlocks [buildingFilter]" and it allows for easier linking (something I'm pretty sure civilopediaText can't do)

**Comment by SeventhM** [comment]
> civilopediaText has the explicit `link` field

Ehhhh, why do that when you can let the interpreter guess the object for you? At the very least, `replacementTextForUniques` can't do it
