### ISSUE TITLE
It is profitable for the unfortunate to fight

### ISSUE THREAD

**Issue by janydoe** [yairm210/Unciv#10397]
I play only a few games and noticed that when happiness is less than 10 ([according to the rules of the game](https://github.com/yairm210/Unciv/blob/11108112b513da41fe80875c01332650455f1196/android/assets/jsons/Civ%20V%20-%20Gods%20%26%20Kings/GlobalUniques.json#L5C13-L5C13)), then food in cities ceases to be needed. People are not starving, the population is not falling. By the way, only at this moment the "Avoid Growth" option starts working, by clicking on which people are redistributed from food cells. You can rebuild the production of cities on military rails and forget about food.

When searching for the cause, I found a [possible source](https://github.com/yairm210/Unciv/blob/11108112b513da41fe80875c01332650455f1196/core/src/com/unciv/logic/city/CityStats.kt#L605C2-L605C2).

**Comment by SeventhM** [comment]
Closed as solved (I think)
