### ISSUE TITLE
Automated workers really bad at building railroads

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#10402]
**Platform**
Android

**Version**
4.8.14 (build 924) 
Actually this has been an issue for a long time

**Describe the bug**
Automated workers attempting to build railroads are very inefficient.  They often move locations where it looks like a railroad will go, and then move away from that position without even starting the railroad the very next turn for unexplained reasons.  They also spend far more turns partially building railroads in spaces only to abandon them before they are completed than they they do just staying in one space until the railroad is completely built.

**Expected behavior**
Build railroads efficiently.  Automated workers build regular roads very well in the early game, so it seems like maybe railroads could use this superior algorithm.  Or just make the workers stay in one spot one they start building a railroad until it is actually built instead of abandoning it partially built, that by itself would be a big improvement.

**Additional context**
In the late game when railroads become available I usually have a lot of automated workers (like up to 20 or more) so perhaps this could be contributing to the issue?

**Comment by tuvus** [comment]
This is an issue that I have noticed as well, not only for roads/railroads but also for improvements in general. I plan to look into it soon to see what is up with the code.
