### ISSUE TITLE
Feature request: Zero move

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10400]
Is it possible to have movement:0 be interpreted as impassable?

**Comment by Caballero-Arepa** [comment]
Why not just use the parameter?

**Comment by hackedpassword** [comment]
Well, say a unit can pass impassable tiles, like being granted a promotion that allows traveling across mountains. Then, movement cost is applied.

If zero meant no movement, the tile would become entirely inaccessible.

**Comment by hackedpassword** [comment]
I wondered what makes Carthage special for attributing an ability to bypass mountains, etc. Took a read through their very long wikipedia page, found nothing that indicates any rationale for that ability. Hmm, wonder what the topology looks like then?

![image](https://github.com/yairm210/Unciv/assets/119975434/a61f8a9c-913c-40d2-ad4c-0cc5d2eafc7e)

Nothing special there either. Ok, whatever.

> keeps it impassable to Carthage

Maybe there's a deeper implication, not terrain-based. Socio-political? Superstition? Self-imposed?

Back to the OP, I've come across design situations where a tile clip would be desirable. Since M:0 is potentially problematic with the AI, altering the context of M:0 seems a reasonable target for a hard stop. Making M:100 is still a one-turn obstacle no different than say M:3.

**Comment by Caballero-Arepa** [comment]
The mountain ability is because the best general of the nation, went into the great feat of crossing a very difficult and thought to be impossible path through the mountains, to come down in a surprise move upon his enemy.

Yeah... very unique... *cough napoleonbolivarmartin cough*

**Comment by Caballero-Arepa** [comment]
If a general's job is to command and win battles, then a general who won many did a good job, whether that job is morally correct or not.
If I say "Who's the best film director?", I'm not explicitly saying that movie making is a good thing, I'm just asking who is the best at their job.

But yeah, I agree that war is just a matter of suffering, and the high honors most people give to historical figures like this, are a kind of hipocritical or in some sorts blind.

**Comment by yairm210** [comment]
Ah yes, across the Andes by frog

**Comment by yairm210** [comment]
Sorry, you want *an impassible tile that even units that can pass impassible tiles cannot pass*? Movement:0 is definitely *not* the way to go, that would be super confusing
"Can pass impassible" should be good specific tiles though, not a general catch-all - carthage units can't move through ice tiles

(If we're dropping references: Across the Andes by frog)

**Comment by yairm210** [comment]
Sorry, you want *an impassible tile that even units that can pass impassible tiles cannot pass*? Movement:0 is definitely *not* the way to go, that would be super confusing
"Can pass impassible" should be good specific tiles though, not a general catch-all - carthage units can't move through ice tiles

**Comment by yairm210** [comment]
Sorry, you want *an impassible tile that even units that can pass impassible tiles cannot pass*? Movement:0 is definitely *not* the way to go, that would be super confusing
"Can pass impassible" should be good specific tiles though, not a general catch-all - carthage units can't move through ice tiles

**Comment by yairm210** [comment]
This should *maybe* be a unique.aking this a #3242 issue
