### ISSUE TITLE
Unique barring game start (and solved)

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10426]
4.8.16, Android or Windows

When starting the game, specifically in the Ancient era, with a unit having the following unique, Unciv complains there may be too many players regardless of number selected (2+, civs|CS).

Problem found:
https://github.com/hackedpassword/Z2/blob/55b7f57bb2766afe202836068cd0c3aee24c3c1c/jsons/Units.json#L70
"Ignores terrain cost"  // ok
"Ignores terrain cost <in [Plains] tiles>",  // not ok
"Ignores terrain cost <in tiles without [Mountain]>",   // not ok

The conditional is not being accepted for the starting military unit.

Swapping this Nomad (Scout) unit with a Scout (Scout) had the same behavior, because the Scout's unique also had a conditional.

Huge thanks to @SeventhM for debugging and finding the offending unique!

**Comment by SeventhM** [comment]
Sorry, beat you to reporting it: #10425

**Comment by hackedpassword** [comment]
Ok, your thread looks busy, closing this one!
