### ISSUE TITLE
ÇOK FAZLA ASKER OLDUĞU ZAMAN HATA OLUŞUYOR

### ISSUE THREAD

**Issue by Suleyman3838** [yairm210/Unciv#10433]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Please attach a game save

**Comment by yairm210** [comment]
Yes!!
Didn't know that was an option, nice!

**Comment by yairm210** [comment]
https://github.com/endless-sky/endless-sky/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml?plain=1

Trippy

**Comment by yairm210** [comment]
DONE, now we should get little to none of these :D
