### ISSUE TITLE
Erreur de chargement de tour

### ISSUE THREAD

**Issue by N4r55ou** [yairm210/Unciv#10438]
**Platform**. Phone Samsung ### 

> _**redmi**_

Plateforme version 4.8.15 build 925
**Version** Dans play store version 4.8.15

**Describe the bug**
Le bug apparaît quand je clique sur tour suivant , en plein milieu du chargement je reçois un message (erreur fatale)
**To Reproduce**

1 Aller dans reprendre ou chargé  la partie 2 et cliquez sur tour suivant  ,3 le message erreur fatale apparaît impossible de continuer 

**Expected behavior**

**Screenshots**
If applic

**Additional context**

**Comment by N4r55ou** [comment]
https://drive.google.com/file/d/19sDfYlMKwhXX7WAqHT7TJCFUEbzdIlFA/view?usp=drivesdk

**Comment by N4r55ou** [comment]
https://drive.google.com/file/d/19pZFomcbRPsPdTD7fAi6cwJX4TU-xpXZ/view?usp=drivesdk

**Comment by Ouaz** [comment]
Les fichiers sont en consultation privée.
![image](https://github.com/yairm210/Unciv/assets/11946570/55dd11de-471c-4d92-8fba-932643c99dc1)

Il faut que tu passes les fichiers en public sur gogol drive (consultation libre), pour que les devs puissent télécharger la sauvegarde de partie, et reproduire le bug.

Ou plus imple, un glisser-déposer des fichiers directement ici, dans un commentaire Github.

**Comment by yairm210** [comment]
The first file is an image that doesn't contain the actual error message in full
What we really need here is a *game save*

**Comment by yairm210** [comment]
Second image is just a screenshot of the game
Neither can help us resolve the issue

**Comment by SeventhM** [comment]
No information
