### ISSUE TITLE
Feature request: Remember move destination when threatened

### ISSUE THREAD

**Issue by krushia** [yairm210/Unciv#10441]
**Is your feature request related to a problem? Please describe.**
Units performing multiple turn moves forget where they're going when an enemy is spotted. This gets really annoying when for example you have a harmless barbarian near base and all the workers you sent away to build roads start getting destinations mixed up.

**Describe the solution you'd like**
Remember the intended destination, pause movement, and show a "resume movement" button as an option.

**Describe alternatives you've considered**
Throwing my tablet against the wall.

**Comment by hackedpassword** [comment]
Any chance you'd be able to demonstrate that behavior in a video capture?

**Comment by tuvus** [comment]
Assuming you are talking about automation. This isn't that the workers forget where they are working. It's that they are very bad at figuring out where to work and how to stay there. I plan to change this next.
