### ISSUE TITLE
Help: CoeHarMod cannot be download in game with no obvious reason

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10447]
![Screenshot_2023-11-08-14-18-37-791_com unciv app](https://github.com/yairm210/Unciv/assets/114050365/6905279a-9ea8-447d-8477-cb73bc7fa58b)
I have no idea to solve it and it lasts for about half a month. I have to take it onto this issue for more help.
This problem is, [my mod](https://github.com/AutumnPizazz/CoeHarMod) couldn't be download in game, though I delete many time-out files in GitHub.

WANT TO BE HEILPED!

**Comment by AutumnPizazz** [comment]
Your response is very profound, and all I can say is "keep up the good work"! QAQ

**Comment by hackedpassword** [comment]
@AutumnPizazz you have a very well built mod, impressive! I did not find any mentions on Unciv discord with CoeHarMod. Maybe start a post in [#mods](https://discord.com/channels/586194543280390151/1020322259094753360)? I hope Trog can solve your issue, his skills and dedication are quite commendable. :)

**Comment by hackedpassword** [comment]
> Not skills, masochism

How to ID you as male? See above. Oh and below.

https://silicon-valley.fandom.com/wiki/Tabs_vs._spaces
"Richard's preference is for tabs, and he's _so dead set_ on this preference that _he actually dumps Winnie_, the only woman who has shown any romantic interest in him in years, over her preference for spaces."

Perhaps the most accurate portrayal of coders ever. Which is another reason I can't be a coder, I like spaces. =)

**Comment by SeventhM** [comment]
> I can't be a coder, I like spaces

I mean, I redid the entire formatting of Rekmod from tabs to spaces and I'm more or less a coder

**Comment by hackedpassword** [comment]
> Ah, I have a communication group on CoeHarMod with over a hundred members, all of whom are Chinese.

That's awesome! Your Readme.md doesn't give much information but sounds like it doesn't need to, just have to know the secret knock lol! 

> You should know that in mainland China, accessing the international internet is often restricted. Typically, one needs to pay $0.2 per day for a proxy server, and occasionally, individuals may even be summoned to the police station (because it is out of laws).

This is absolutely fascinating insight. I've read a couple books on the Mao era, leading to how and where your countries' politics ended up where they are. Many current events make immensely more sense with that background in mind.

If you do have a public community hub for your mod, link it and I'd like to stop by one day.

**Comment by AutumnPizazz** [comment]
> If you do have a public community hub for your mod, link it and I'd like to stop by one day.

Okay, it is a tencent QQ community whose number is 718331229. @hackedpassword

**Comment by AutumnPizazz** [comment]
> @AutumnPizazz you have a very well built mod, impressive! I did not find any mentions on Unciv discord with CoeHarMod. Maybe start a post in [#mods](https://discord.com/channels/586194543280390151/1020322259094753360)? I hope Trog can solve your issue, his skills and dedication are quite commendable. :)

Now I create a CoeHarMod top in Discord.

**Comment by SeventhM** [comment]
> something Studio does with one click for you, you did yourself?

Something the online GitHub editor did for me. Had to do it file by file, though.
