### ISSUE TITLE
Android dropdown menu's little bar permanently visible

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10456]
**Platform**
Nokia TA-1157 running Android 11

**Version**
4.8.14

**Describe the bug**
Sometimes the android- ropdown menu will stick on top of Unciv and most important information will be hidden be hidden behind.
Pulling down then pulling up this menu doesn not resolve the issue.
I couldn't really pinpoint how this bug happened, but it hadqsomething to do with switching apps or puting the smartphone to sleep.

**To Reproduce**
Cannot provide any for now, sorry. I will update this issue when i do huve more clues.

**Expected behavior**
Android's dropdown menu's small bar should always b hidden, no matter what.

**Screenshots**
![Screenshot_20231102-202043](https://github.com/yairm210/Unciv/assets/80604512/9c83d3d3-d9fb-4775-adec-2405f46b9b47)

**Comment by Cwpute** [comment]
I think this has something to do with my notifications, some of them might force that bar to appear…
Might be worth adding this directly into the game. A quick FAQ regarding krow issuses etc…

**Comment by yairm210** [comment]
Solved by SomeTrog's Android tweaks last version
