### ISSUE TITLE
<upon gaining a [baseUnitFilter] unit> No work

### ISSUE THREAD

**Issue by QbdqmQ** [yairm210/Unciv#10475]
**Platform**
Win10 (64bit)

**Version**
4.8.17

**To Reproduce**
"Free [Warrior] appears <upon gaining a [Spearman] unit>"

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/137891022/8643e4c4-c3a1-422c-b6a7-0e6506b0d611)

**Comment by yairm210** [comment]
Looks like it's working, can you provide the mod where it fails?

**Comment by QbdqmQ** [comment]
[Enlightenment.zip](https://github.com/yairm210/Unciv/files/13326818/Enlightenment.zip)
@yairm210 China(Qin) Unique Ability in error

**Comment by SeventhM** [comment]
> With the replace(`unique`->`it`) quiggfiggs

Took me too long to understand the issue here... wouldn't this be a name shadowed warning?

**Comment by SeventhM** [comment]
> `unique` means

No, no. I know that much. I'd need to check (was too busy today) but since the "Free [unit] appears" is already named "unique", it'll whine about shadowed names it you do `unique -> it`. Hell, that's not even necessary because you can just do `unit.matchesFilter(it.params[0])`
