### ISSUE TITLE
AI ignores "The promised not to settle near us" agreements 

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#10487]
**Platform**
Android

**Version**
4.8.17 (Build 927)

**Describe the bug**
AI completely ignores "They promised not to settle near us" agreements now.  This worked in previous versions.

**Additional context**
Not sure if this makes a difference, but I noticed it in a game where I played Austria, and the cities settled next to were previously annexed city-states.

**Comment by tuvus** [comment]
Good catch! I remembered at some point that part of the code I rewrote was to account for this but then I forgot to add it back in again. I will fix this.
