### ISSUE TITLE
Citizen Management auto reset

### ISSUE THREAD

**Issue by Jojolasticot73** [yairm210/Unciv#10501]
Hello,

I just discovered Unciv and I am impressed of the game.

I think there is a problem in citizen management (or maybe there is something I don't understand) 
When i manually manage my citizens, the following turn everything is reset and I have to redo everything. 

DOes anyone have the same problem ? Is it a bug or a parameter I didnt see ?

**Comment by tuvus** [comment]
Did we change how tile locking works? Previously, tapping twice would lock it, but now that doesn't seem to be the case.
Oh, wait! I see, there is a lock button on the bottom right panel. In what PR was this change made?

**Comment by tuvus** [comment]
Oh! It was changed to be double tap instead of press to assign then press again to lock, and press again to unasign.

**Comment by Jojolasticot73** [comment]
Thanks guy, I didn't see the "lock" option by double clicking ;-)

**Comment by PizzaProgram** [comment]
I also think it would be better to leave the "last set" as it was, and do not reset every each round, if population management is set to: None

Or at least it would be an Option at main setup (default: do not reset)
