### ISSUE TITLE
Ideas for a compact city menu in portrait mode

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10500]
Currently on my phone, this is what the city menu looks like: 
![screenshot00298](https://github.com/yairm210/Unciv/assets/80604512/37656359-46e6-462f-bc1b-e341fe964499)
As much as i like lasagna, this is unusable 🤡

Here are some ideas to improve that menu so it fits on most screens:

⭐ _Most easy one_: only allow EITHER the left OR the right panel to show on screen at the same time.
Hide the other one behind a button that switches between the two panels (or allow each of them to be hidden by a tap on their own button)

**City production**
1. Let the ressource list overflow to another line
2. Put that-list as a full bar at the top of the screen. The issue is that it might be mistaken for the civilization-wide production, coming from the map view… Can be avoided by puting the city name and butons at the top.

**Expansion and new citizens**
Several ideas
1. Replace ``xx turns before expansion (xx🟣/xx🟣)`` by ``xx⏳ before expansion (xx/xx🟣)`` (same idea for population)
3. A culture-points-coloured loading bar with "Expansion" written inside, that provides the remaining turns and needed points once tapped (same idea for population)
4. A loading bar like it's used for the Great Persons
5. Let it overflow to the next line

**Building queue**
Two complimentary solutions:
1. Allow building list titles to overflow in the next line, as far as to break words.
2. Use icons instead of category names: Buildings, Units, Wonders, National wonders… i'm sure they can be replaced with a small illustration.
3. For Science and Gold production, use instead ``Produces xx🟣/⏳``

**Production focus**
1. Put all the focus options in a drop-down menu
2. Force focus options into a single row when the window takes too much space.

**Religion panel**
1. Remove the precision "major religion". When there is no religion simply say ``No religion``
2. Like for the building queue, allow category names to overflow to the next line.

**City name and buttons**
1. Let it take the whole bottom part of the screen, or rather prevent other panels to take that space at the bottom
2. Same idea with the top of the screen, but as suggested in the City ressources section, this might not be a good idea.

Generaly speaking, most of these options will need the menu to be aware of the screen size and how much space each panel takes in that screen.
And as you can see, many of my suggestions are simply "let it overflow", i think they are the and most easy options to implement!

**Comment by Cwpute** [comment]
This is a lot to take in at the same time 🤯
Could you provide a simple sketch to help visualize ?

**Comment by scheeseman486** [comment]
I'd love to see more work on the portrait mode. Turning it into something you could casually play minutes at a time with a single hand would deliver on what I always wanted out of a portable Civ.

**Comment by Cwpute** [comment]
If you have any practical ideas you already thought of, mock-ups or code contributions you want to provide, feel free to do so @scheeseman486 :)

**Comment by Cwpute** [comment]
So cool to see this mockup in action ! great work.

I'd suggest always having the map as a backdrop, like it usually is, but only interactible once you actually tap once on it, which would make the current visible pannel disapear.
It will free up space in the pannel list and will provide some cohesion between the city pannels.

**Comment by Cwpute** [comment]
Taken from the referenced and closed issue #10606 , several suggestions for symbols in place of text or section names in the city menu.
@yairm210 said he didn't ricognize any of it… surely their are not *that* bad are they ? 😥

![](https://private-user-images.githubusercontent.com/80604512/286054280-0872fd27-9d98-4265-a88f-d6122dd6bf30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQyODAtMDg3MmZkMjctOWQ5OC00MjY1LWE4OGYtZDYxMjJkZDZiZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTc5ZTE0MTE1YWMyMGMzZGE4NDQxMGM4MTFlNzE1N2IyZjQ0MDJkMWE2OTcxMmE1MDZmYWQzOGMzNDhmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HT8f7IqTPHi98ZYkAXgU57C8YmT3Gqyh8F6YZ9wUssY)
![](https://private-user-images.githubusercontent.com/80604512/286054320-a7b5fd8c-0652-46bb-b723-9a230cf1b083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQzMjAtYTdiNWZkOGMtMDY1Mi00NmJiLWI3MjMtOWEyMzBjZjFiMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYjM1NjdkMmFkMDdmZWZhNzU0OTEwZTAyOGM4MjQyOTExMzc4MGY3OWI5MDBhM2RiYTAyMTIxOTE4NWViMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkKJ7OGFPihDQIbUaMAhrJ7FbPBRcBF821XybFPHYCs)
![](https://private-user-images.githubusercontent.com/80604512/286054369-54409555-8dbb-4756-a97a-267a3714dac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQzNjktNTQ0MDk1NTUtOGRiYi00NzU2LWE5N2EtMjY3YTM3MTRkYWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Mjk2YmI0YWFlNzJlNWQwOGNiYzNkYTQzMGZmNDg0YWQxZjk3NTQwZGVmZjYwZWRmZjM2ZjQ3NDRlZmU0OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ru4SD-rSgXzKQI50hSzAY076FVGjs1r4_FCNod66TZQ)
![](https://private-user-images.githubusercontent.com/80604512/286054407-2d941df7-d4bb-4c4c-9e27-31d83a955193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQ0MDctMmQ5NDFkZjctZDRiYi00YzRjLTllMjctMzFkODNhOTU1MTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDZhYjg4MmY2MDE3ZWQxOTFjODQwMjM5NDQ0ODkyODgwMGE5N2Y0YjQxN2E4MzlhOWY0NWZlNzg2NGUyYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4biLHHj6pV3MxQn2j48UyPcLN0DVU0d1tN5-MWDqPnk)
![](https://private-user-images.githubusercontent.com/80604512/286054448-fab631af-f65a-45ed-9b64-1eca6823e4d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQ0NDgtZmFiNjMxYWYtZjY1YS00NWVkLTliNjQtMWVjYTY4MjNlNGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMTE3YTMyMGFmODVmYmU3OTRhNDczNTU2MThkZjVjN2IwZDRiNTgyMDBjMzg3OGExOGNmNDU5OTA0NWZkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stEWvjC-RXIpR5BJxau3dyXONknxg9gYNKB6531mjZo)

**Comment by Cwpute** [comment]
Alternatives to the last one: 
![](https://private-user-images.githubusercontent.com/80604512/286054487-40935605-99b4-4bf0-b730-2eef1590cf8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQ0ODctNDA5MzU2MDUtOTliNC00YmYwLWI3MzAtMmVlZjE1OTBjZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2FjYzNkZmVlMzA1ZmZiMjA3MTA2MTZhYTY2NWYzMGViMWViZmY1Mzg5N2YyNGQwNTIxYWExYThmZjFlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mDGJ3YvchRXh5O4ZQVX0ZWbn-c7DOx5RXnkf_cT1DfI)
![](https://private-user-images.githubusercontent.com/80604512/286054529-a92dda94-62eb-41f7-b5d1-60047dff4061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQ1MjktYTkyZGRhOTQtNjJlYi00MWY3LWI1ZDEtNjAwNDdkZmY0MDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExN2RjMjViOWE3ZmMxY2Q4MmE0ZTdiYWY1MGZhNjlhYzAxZjE5ZmQ1NjI0YjQ4N2Y5MThmNDk5NzM3NTA1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFFiPEtDauYoYGJ87f4C4nZmHmybv1XEF6UORO8aHAE)
![](https://private-user-images.githubusercontent.com/80604512/286054703-98898d39-f0cc-4d38-8ec5-0678d05b901d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTA0NzUsIm5iZiI6MTcwMTE5MDE3NSwicGF0aCI6Ii84MDYwNDUxMi8yODYwNTQ3MDMtOTg4OThkMzktZjBjYy00ZDM4LThlYzUtMDY3OGQwNWI5MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMzI2YjI5N2U0ZjM4ZTNhZDE5ZjNmM2RlZjBiZDVmM2NmM2QxYzBjZWZlYjBiY2Y1MzJlYTIyZDJlNTE2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8mzsgYA_0ZIicPnovx4k7XO0phq_9J2tOdartAbT5E)

**Comment by SeventhM** [comment]
I'll unstale with a comment (and try to pressure Trog into working on NewCityScreen). Not sure if it should have a "will not stale" label, though, given it's not obvious if it will be worked on, despite being an obvious "Portrait mode needs fixes" issue
