### ISSUE TITLE
Feature request: Toggle automatic search through Civilopedia's entries

### ISSUE THREAD

**Issue by Lesiakower** [yairm210/Unciv#10503]
So, when you enter Civilopedia and want to search for something you must first manually click on the search icon in the upper-right of the screen and only then you can start typing what you want to search for. 
I know that's just a matter of a single click, but I find that it sometimes slows down my gameplay flow (you got the point) just a tiny bit.
At the moment if you start typing as soon as you enter Civilopedia you will search through **CATEGORIES** not **ENTRIES**.

I would like to suggest adding a toggle button that controls if you want to automatically search through categories or entries as soon as you're in Civilopedia (and start typing something).

**Comment by Lesiakower** [comment]
> If your version is without that -> F1 for Pedia, F1 for the fulltext search box. 

Ohh, I missed it... Thanks!

**Comment by SeventhM** [comment]
Closing as wontfix
