### ISSUE TITLE
Feature request: custom timespan and manual check for multiplayer turn

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10517]
**Is your feature request related to a problem? Please describe.**
The timespan between game status checks for multiplayer games allows for set timers ranging from 3 seconds to 15 minutes, which is nice… but what if i want to check every hour ? every day ?
What if i want to only check manuall ? or on startup ? These options are not available unfortunately.

**Describe the solution you'd like**
The ability to enter a custom timespan in the game status check options. you would enter a number and choose the units in in a dropdown menu (seconds, minutes, hours… days ? why not).
Also allow for only checking manually. This would need the implementation of a button, possibly on the multiplayer games' panel.

**Describe alternatives you've considered**
Include longer timespans in the dropdown list ? half an hour, 1 hour, 3 hours, 6 hours, 12 hours and 24 hours would probably be enough.

**Comment by Cwpute** [comment]
> ... and consider the comment `// Games that haven't been updated in a week are considered stale` in `MultiplayerTurnCheckWorker` - so yes >24h should not be offered.
Fallacious argument: this was somewhat arbitrarily stated that, for *most* games, a week without plays makes a stale game. What if the people i play with skeep one or two weeks because they're on vacation, or busy at work ? as a player, i don't mind, if they give me a warning before (but that's out of this issue's scope).
What's even a stale game like ? what does that do ?

> So go ahead, PR a change to that

Ooh, never made a PR before but actually… i may have some time this week :eyes: idk. Don't take my word for it.

**Comment by yairm210** [comment]
All that means is that we don't check those games every X amount of time
Since most players checks every 10 seconds, it avoids unnecessary traffic
But if you're only checking once a day, we can definitely show checking more stuff

**Comment by Cwpute** [comment]
> Ooh, never made a PR before but actually… i may have some time this week 👀 idk. Don't take my word for it.

Didn't have the time to do it, and won't until a good while. Anyone willing to do it is free to do so.
