### ISSUE TITLE
License of used music and graphics?

### ISSUE THREAD

**Issue by Trilarion** [yairm210/UnCiv#1051]
Hi,

I could not find any information about the license (and origin) of the used graphics and sounds. Is information about that stored somewhere in the repository?

Taking material from the original game is probably out of the question, but at the very least documenting where the material comes from and what the respective license is seems like it might save a lot of trouble later on.

**Comment by yairm210** [comment]
https://github.com/yairm210/UnCiv/blob/master/docs/Credits.md

Big huge link in the main readme

**Comment by Trilarion** [comment]
Sorry. Thank you
