### ISSUE TITLE
Feature request: About Stockpiled Resource

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10515]
This is a proposal about stockpiled strategic resources, which accumulates my long-term suggestions and feedback.

- [ ] Stockpiled Resource cannot be traded.
- [ ] Stockpiled Resource has no limit for accumulation.

In other words, stockpiled resources should be allowed for trading; new Uniques should be set to accommodate the limit issue of stackable resources, such as

- Clear the per-turn output of [Stockpiled Resource] <when above [amount] [Stockpiled Resource]>

Furthermore, a more general unique can also be set:

- [Stockpiled Resource]'s per-turn output is multiplied by [amount]%

**Comment by yairm210** [comment]
Resource multiplication uniques already exist

"trade stockpiled" - good point
"limit accumulation" - good point, but NOT in the way suggested. Should be a unique on the resource itself, like "Resource accumulation limited to [amount]"

**Comment by AutumnPizazz** [comment]
> Resource multiplication uniques already exist

Now we have only "Double quantity of [resource] produced", which has the [100]% amount for that. So I suggest to extend it for applying for more amount, like [50]%, [200]% and so on.

**Comment by yairm210** [comment]
What exactly is 50% of 1 resource? Resources are int values. What we *could* have is `[amount]` multipliers, but again, #3242
