### ISSUE TITLE
UI: Display option for Explore button

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10533]
My bad @SomeTroglodyte you're right UI issue not modding. I'll delete the post if it's way too off 3242 topic, just drop a hint here.

-----

A `Display` option allowing toggling of the ever present Explore button.

Personally, after a few early eras there's no use for it. There are exceptions.

This is a constant source of UI grief for me. In later eras, it doesn't even make sense to be onscreen, _especially after revealing the map_. Should be auto-removed at that point regardless. :/

_Originally posted by @hackedpassword in https://github.com/yairm210/Unciv/issues/3242#issuecomment-1819833384_

-----

Really, was only trying to seed a suggestion, since we're here...

> branch

Seems awfully sophisticated for an if-then checkbox option render. Like creating a swiss army knife for a toothpick. Though those features sound interesting. Anyway, this issue bugs me and I want to crush that button into digital dust. Since I recently [dabbled with android studio](https://github.com/hackedpassword/atlas-regen) that button is now on my radar of destruction buahahaha

**Comment by yairm210** [comment]
How did you open this issue?

**Comment by hackedpassword** [comment]
> How did you open this issue?

I came from 3242, and I think I stayed in the github app, but exactly how I can't recall. Looked over at chrome cause that works better for issues, used that for another issue. I'm not sure, but I do see the reasoning for you asking. Strange. I'll let you know if I figure it out.

**Comment by yairm210** [comment]
https://github.com/orgs/community/discussions/23034
Known issue for *checks watch* 4 years, so I'm sure they'll be dealing with it aaaany day now

**Comment by hackedpassword** [comment]
> ... that one, right?

That looks right. Sidestepped the tagging/assignment process, had no idea. Now we know and knowing is half the battle - hmm half seems like a disproportionate percentile

**Comment by hackedpassword** [comment]
> but I'd like swap to be reachable easier...

Since there's a unique that puts the automate button front and top, wouldn't it make sense to say:
"Swap is a primary action",
"Explore is a secondary action",

**Comment by yairm210** [comment]
I'm fine with having explore be a secondary action after map reveal
But swap as a primary... I'll need to meditate on that

**Comment by yairm210** [comment]
That would look awful on horizontal

**Comment by yairm210** [comment]
@SomeTroglodyte I'm working on the standardization, there is a problem with actions that can be optionally placed in different places - I'd be glad to hear your thoughts on how to structure unit actions that will sometimes be in primary and sometimes in secondary

**Comment by hackedpassword** [comment]
Modder note - I addressed that huge menu stack with a unit transformation chain:

worker - > cheatUnit1 - > cheatUnit2 - > cheatUnit1 - > ... (swap 1 & 2 as needed) 

The menu stack is divided between the two units, could continue to divide and assign if needed.

**Comment by hackedpassword** [comment]
Would it be difficult to make the button menu scrollable like the Notification log, or build menus? eg. swipe up/down

![Screenshot_20231215_122205](https://github.com/yairm210/Unciv/assets/119975434/6e843915-0bd8-426f-a249-ff78591186bb)
shown: (vanilla) Alpha Frontier

**Comment by SeventhM** [comment]
Closing as unit actions is now paged. Please send a comment explaining if this is still relevant

**Comment by hackedpassword** [comment]
Explore button still makes no sense to retain after certain points (like starting in future era). Maybe next time.

**Comment by SeventhM** [comment]
I'm not sure how the explore button works, but if it functions at all past revealing the whole map, then I don't see the harm in keeping it. I'm not against reopening, but in general it seems this issue moved towards having the explore button paged alongside other actions which avoids the larger problem of having the screen fill up with too many actions. It might be better to reopen this as a newer issue to keep the discussion more focused

**Comment by hackedpassword** [comment]
It doesn't. That's why I have issue with this, there is literally no use for that button once the map is revealed. After 150-200 turns either. Meh. Thanks for the consideration anyway @SeventhM :)
