### ISSUE TITLE
Buying Castles and associated ideas

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10538]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

As we know, buying Happiness buildings takes a lot of time compared to other buildings - ~because someone whined about starving cities~ because the limit for nullifies growth may be passed and cities might need food again, so all of them may perhaps need their worked tiles re-optimized. That may well be several seconds on a fast phone and ~20 cities.

Apart from optimizing that code (e.g. intelligently parse mods to see where happiness limits affecting nullify growth really are) -

* Doesn't happen for Castles and their follow-ups with Professional Army and/or Neuschweinstein: The code might need to go and scan all StatsFromObject uniques from the Civ too!

### Related Issue Links

#9799, #9425, #9238, #10397 - PR #9395 introduced the re-eval

### Desired Solution

Advice... How can we best deal with that

### Alternative Approaches

* Could that recalculation be done in a Coroutine while the user stays in the CityScreen, complete with preemption when they buy _another_ Happiness building or queue reordering when they change to view one of the affected cities? And background processing continuing to run to finish while user changes views, potentially updating WorldScreen map tiles overlays while the user is looking at them?

### Additional Context

* I see a StatsFromBuildings unique where a StatsFromObject should suffice from an implementation viewpoint - is that for prettier language only? (Sovereignty policy)

**Comment by yairm210** [comment]
Buying castles should change the happiness is the civ which would trigger recalc for all cities
If we *manually* check for happiness buildings, we can get rid of that check

**Comment by yairm210** [comment]
That's an extra recalc we can throw away

**Comment by SeventhM** [comment]
> ...in Building.isStatRelated be the ticket?
I'm not so sure about doing that tbh
1. `Building.getMatchingUniques` only checks the uniques of the object itself, not any uniques the civ my have by this point. E.g., Neuschwanstein wouldn't male castles into a culture building, but `"[stats] from every [Castle]"` on the building itself would. You would need to pass in the city/civ into `Building.isStatRelated` to do what you want
2. From what I'm aware, Civ 5 itself wouldn't consider Castles as culture buildings with Neuschwanstein, so this seems slightly wrong, not what we currently do

**Comment by SeventhM** [comment]
Can't find the PR Yairm did to reduce the amount of recalculations, but this should be solved by now. Does this need to stay open?
