### ISSUE TITLE
Feature request: reduce Ranking and Chart infos

### ISSUE THREAD

**Issue by xtf0** [yairm210/Unciv#10545]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

In Victory status the Rankings and Charts are to infomative, only the Score should be visible, not the detailed Gold, Force, Tech etc.
This IS a gameplay feature of vanilla civ and default, but seams not to be considered atm.

### Desired Solution

- [ ] "reduced info" option at gamesetup 
  - [ ] for hiding all other info in Rankging and Charts besides actual Score
- [ ] charts of hidden infos should only be visible after the session
- [ ] Enabled  by default because it represents vanilla civ v

### Alternative Approaches

outsource into a mod

**Comment by Ouaz** [comment]
Did you try the "Experimental Demographics Scoreboard" in the options?
It only shows the best and worst values for each stats, and the average values aswell.
I agree the default scoreboard is way too informative, that's why this alternative one has been implemented.
Note: it is tagged as "experimental", but it's fully functional.

**Comment by xtf0** [comment]
With 3

**Comment by xtf0** [comment]
With 3 players it would be full info again. Showing only activated victory conditions with their sub conditions?
Scientific -> x of 5 parts
Cultural -> x of 5 politic trees
Domination -> x of y players/territorial percentage
Diplomatic -> obvious
time -> show score

**Comment by SeventhM** [comment]
I might be overstepping my bounds closing this, but given the stale warning, might as well. I probably could've also let this close on its own, but I do feel like commenting here

While it probably correct to move to something like the experimental demographics screen, there's basically been no work been done to it with most seeming to prefer the current one. There's also an obvious comparison to Civ 5, where by far one of the most popular mods is a mod that does expand the amount of info you get about your opponents significantly. So it seems to me almost as though it'll be unlikely this issue actually goes anywhere in the future
