### ISSUE TITLE
Modded Custom Maps Causing Problems

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#10543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.8.x to 4.9.0

### Describe the bug

When you download, update or make a custom map with mods (or a mod with inbuilt custom maps), a particular problem happens:

> When making new game, map selection is automatically switched to Custom Map
> Ruleset and mod selection gets forced into the custom map's ruleset and mod selection
> Changing rulesets and mods doesn't work properly (for example, see steps to reproduce below)

### Steps to Reproduce

1. Download Latin American Civs mod
2. Go to Start New Game menu
3. Note the custom map and the mod list, civ selection menu should be GnK civs + Latin American civs from the mod
4. Change ruleset to non-vanilla (Deciv or Alpha Frontier)
5. Check civ selection, Latin American civs gets included as well
6. Try to start, either it fills up with errors or it gets the 'map too small' error

### Expected Behavior

1) It does not default to Custom Map selection when starting a new game
2) To be able to select/deselect mods and use other rulesets without problem afterwards

### Operating System

Android

### Additional Information

Bug also exists in the Windows version

**Comment by Why-not-now** [comment]
There definitely is a bug in it. If you deselect the mods, it will autoselect the custom map mods again.

**Comment by carriontrooper** [comment]
Bug resurfaces again (did it ever get fixed?) in 4.10.x, same issue as before - modded custom maps 'locking' the mod selection in new games.

**Comment by yairm210** [comment]
Tried to repro, Discord says this is caused by mods that have *just been downloaded* so if we can repro we can fix

**Comment by SeventhM** [comment]
I mean, I can confirm, it only happens for a mod that have just been downloaded. I more just haven't really touched that area of the code

Side note is that we also need to fix the issue of a custom map being null on that screen

**Comment by yairm210** [comment]
Has since been fixed
