### ISSUE TITLE
Feature request: Additional ways to export games

### ISSUE THREAD

**Issue by Bjastkuliar** [yairm210/Unciv#10567]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

When trying to export a game i've started (for example from Android over to desktop), the data is saved onto the clipboard. The issues here is that if a large game is saved to it, then the entire Android device is basically compromised, because said save is basically loaded every time one wishes to access the keyboard (throughout the device).

### Desired Solution

Provide alternative ways to export games (especially large games), like a save-file or similar (cloud access would be ideal, but this being free and open-source I understand that it is far from easy...)

### Alternative Approaches

Prevent the usage of the clipboard for very large games (that may cripple the device functionality)

### Additional Context

I encountered this issue on Android, I don't know how it would perform on desktop or other environments...

**Comment by yairm210** [comment]
As stated, you can choose a location to save your file to, which should be the preferred alternative if clipboard is unacceptable
