### ISSUE TITLE
AI building too many Inquisitors

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#10576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.0 (Build 930)

### Describe the bug

AI civs build lots of Inquisitors (which it doesn't seem to ever actually use) but few Missionaries or Great Prophets.

### Steps to Reproduce

Play a game with AI Civs

### Expected Behavior

In previous versions AI built a much better balance of religious units to spread their religion better.

### Operating System

Android

### Additional Information

I think I actually first noticed this issue in the version before 4.9.0.

**Comment by SeventhM** [comment]
Can someone confirm this is still an issue? I'm pretty sure it is, but it would be nice to have the confirmation
