### ISSUE TITLE
Everything is blurry on Mobian/Postmarketos

### ISSUE THREAD

**Issue by kevinwidjaja21** [yairm210/Unciv#10598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.2-patch2

### Describe the bug

I am using OnePlus 6T to run Mobian. But in the past, PostmarketOS also have this issue. Obviously, it looks fine in Android. 

### Steps to Reproduce

1. Obtain any PostmarketOS/Mobian compatible smartphone
2. Install Unciv
3. Run Unciv

### Expected Behavior

Clear text/UI

### Screenshots

![Screenshot from Audio](https://github.com/yairm210/Unciv/assets/19798208/a3e230df-d5ca-4f88-9f28-121a52edc36d)

### Operating System

Linux

### Additional Information

Not sure if this is a freedreno driver issue or mainline linux issue for OnePlus 6T. Might need to test it with pinephone but I don't own one.

Neofetch and inxi output. I am using phosh (a fork of gnome for mobile) if that is matter. Using Gnome Mobile, plasma mobile or other interface may result in different behaviour.
```
mobian@mobian:~$ inxi -GSC -xx --display
System:
  Host: mobian Kernel: 6.6-sdm845 arch: aarch64 bits: 64 compiler: gcc v: 13.2.0 Desktop: phoc
    dm: greetd Distro: Debian GNU/Linux trixie/sid
CPU:
  Info: 8-core model: N/A variant: kryo385 bits: 64 type: MCP arch: ARMv8 rev: C
  Speed (MHz): avg: 1651 high: 2650 min/max: 300:826/1766:2650 boost: disabled cores: 1: 653
    2: 653 3: 653 4: 653 5: 2650 6: 2650 7: 2650 8: 2650 bogomips: N/A
  Features: Use -f option to see features
Graphics:
  Device-1: adreno-630.2 driver: adreno v: N/A bus-ID: N/A chip-ID: qcom:5000000
  Device-2: sdm845-mdss driver: msm_mdss v: N/A bus-ID: N/A chip-ID: qcom:ae00000
  Device-3: sdm845-dpu driver: msm_dpu v: N/A bus-ID: N/A chip-ID: qcom:ae01000
  Display: server: Xwayland v: 23.2.2 compositor: phoc driver: N/A
  Monitor-1: DSI-1 size-res: N/A
  API: EGL v: 1.5 platforms: device: 0 drv: msm device: 1 drv: swrast gbm: drv: msm surfaceless:
    drv: msm wayland: drv: msm inactive: x11
  API: OpenGL Message: No GL data available.
  API: Vulkan v: 1.3.268 surfaces: wayland device: 0 type: integrated-gpu driver: mesa turnip
    device-ID: 5143:6030002 device: 1 type: cpu driver: mesa llvmpipe device-ID: 10005:0000
mobian@mobian:~$ neofetch
       _,met$$$$$gg.          mobian@mobian 
    ,g$$$$$$$$$$$$$$$P.       ------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux trixie/sid aarch64 
 ,$$P'              `$$$.     Host: OnePlus 6T 
',$$P       ,ggs.     `$$b:   Kernel: 6.6-sdm845 
`d$$'     ,$P"'   .    $$$    Uptime: 32 mins 
 $$P      d$'     ,    $$P    Packages: 1680 (dpkg), 7 (flatpak) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1080x2340 
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/1 
 `$$b      "-.__              CPU: (8) @ 1.766GHz 
  `Y$$                        Memory: 2103MiB / 7560MiB 
   `Y$$.
     `$$b.                                            
       `Y$$b.                                         
          `"Y$b._
              `"""
```

**Comment by kevinwidjaja21** [comment]
Ah sorry, that OpenGL support missing is likely because I got this from SSH seession. I support OpenGL 4.6 and OpenGL ES 3.2. Here is the output of `glxinfo -B` and `inxi -GSC -xx` running from the phone directly. Screen capture tool in the phone was not working well currently.


![PXL_20231128_001605522](https://github.com/yairm210/Unciv/assets/19798208/f1e905e5-3785-485e-8250-066cdd23147a)
![PXL_20231128_002308062](https://github.com/yairm210/Unciv/assets/19798208/69827b95-040e-4784-a731-6e01ab5357c6)

**Comment by kevinwidjaja21** [comment]
Also, to add. Unciv doesn't have this issue when ran through waydroid.

**Comment by yairm210** [comment]
I'm pretty sure this is a lwjgl or libgdx issue, I'm betting on the former.

Searched "lwjgl mobian" and found [this](https://www.reddit.com/r/PinePhoneOfficial/comments/m6r919/was_able_to_get_unciv_running_on_mobian/) so either that's you 3 years ago, or you're not the first to do this and get that result

Nothing on either LibGDX or lwjgl regarding this, I understand the issue at hand but I wouldn't know where to start trying to debug this, let alone solve it :/

**Comment by kevinwidjaja21** [comment]
I didn't know this game exist until a year ago lol. The pinephone seems to run phosh also it seems. Last time I tried running unciv on postmarketos, it was also with phosh. I see if switching to other desktop enviroment change anything. I suspect changing to an X11 based DE may have some different result.

I guess to add, this is not driver related issue as both pinephone and oneplus 6t use different gallium driver. I also tried running unciv with zink opengl to vulkan driver and still the same issue.

Time to wipe mobian then from my phone then.

**Comment by kevinwidjaja21** [comment]
Intersting update. With plasma mobile, it look great. So maybe an issue with Gnome or Phosh fork of gnome. Pinch to zoom doesn't work though.
![Screenshot_20231201_164056_124209](https://github.com/yairm210/Unciv/assets/19798208/49f1c071-65d5-4722-aaee-2ff800bd3ad1)

**Comment by yairm210** [comment]
I'm going to close this as 'unactionable' - I understand the problem, but there's not really anything I can do about it at the moment

**Comment by kevinwidjaja21** [comment]
I was about to comment that this seems to be a problem upstream with gnome as turns out, this also happens with other games.
