### ISSUE TITLE
Units don't move on turn start multiplayer

### ISSUE THREAD

**Issue by Comp643** [yairm210/Unciv#10600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.1

### Describe the bug

Units move on turn start option does not work on multiplayer 
explore,  automate, unit moves to destination also dont do anything
leaving the units to stay in the same hex until moved manually
maybe caused by loading saved data which syncs games

### Steps to Reproduce

On multiplayer game use automate, explore etc finishs move when the other player ends their turn and your turn starts  

### Expected Behavior

Units to auto move when turn starts 

### Operating System

Android

**Comment by tuvus** [comment]
What do you mean by manual? Clicking the automate button?
If so, this is a part of the fix since they use the same code.

**Comment by yairm210** [comment]
This results from the previous player having "move on turn *end*" and this player having "move on turn *Start*", known bug, I know we have an issue open for it, but we don't have a good solution

**Comment by yairm210** [comment]
The question is, how to indicate to the next multiplayer player that the "beginning of turn" actions have not yet been taken, we could do it with a bool now that I think of it but this will require some thought
