### ISSUE TITLE
Several suggestions for new symbols and icons

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10606]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

The interface for Unciv is very text-heavy, which takes a lot of space on small screen and devices. It can be a problem for some translations as well which can further lenghten a section name, a button's description etc…

### Related Issue Links

* #10500 

### Desired Solution

One way it could be helped with is replacing some of that text with symbols, icons or logos that give you the desired information without text.

Following is a first draft at several icons and symbols mostly for sections in the city pannel:
![expan1](https://github.com/yairm210/Unciv/assets/80604512/0872fd27-9d98-4265-a88f-d6122dd6bf30)
![expan2](https://github.com/yairm210/Unciv/assets/80604512/a7b5fd8c-0652-46bb-b723-9a230cf1b083)
![newctz](https://github.com/yairm210/Unciv/assets/80604512/54409555-8dbb-4756-a97a-267a3714dac0)
![sleepctz](https://github.com/yairm210/Unciv/assets/80604512/2d941df7-d4bb-4c4c-9e27-31d83a955193)
![greatperson1](https://github.com/yairm210/Unciv/assets/80604512/fab631af-f65a-45ed-9b64-1eca6823e4d2)
![greatperson2](https://github.com/yairm210/Unciv/assets/80604512/40935605-99b4-4bf0-b730-2eef1590cf8c)
![greatperson3](https://github.com/yairm210/Unciv/assets/80604512/a92dda94-62eb-41f7-b5d1-60047dff4061)
![greatperson4](https://github.com/yairm210/Unciv/assets/80604512/5547a810-0631-4b60-bd87-f9ef1bde2662)
![greatperson7](https://github.com/yairm210/Unciv/assets/80604512/98898d39-f0cc-4d38-8ec5-0678d05b901d)

### Alternative Approaches

Of course we have to be careful with this because too much symbols and icons will have the opposite effect and drown the player in too much images.

**Comment by yairm210** [comment]
I have no idea what these icons are meant to represent
This definitely sounds like part of #10500 and not a standalone issue
