### ISSUE TITLE
Crash during next turn : unit can't be put in tile 

### ISSUE THREAD

**Issue by stity** [yairm210/Unciv#10619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.8.19

### Describe the bug

Game crashes on next turn loading.

### Steps to Reproduce

Load save and click next turn

### Expected Behavior

Game should not crash

### Link to save file

https://hastebin.com/share/mapuwokulo.perl

### Operating System

Android

EDIT: changed link to save file

**Comment by willjallen** [comment]
The pastebin link is broken

**Comment by stity** [comment]
Sorry about that, here is another link :
https://hastebin.com/share/mapuwokulo.perl

**Comment by willjallen** [comment]
![image](https://github.com/yairm210/Unciv/assets/30008534/aa797694-b1e7-4042-8ee3-d0c1c3454d72)

I've done a little digging, here's what i've found. In this code:

https://github.com/yairm210/Unciv/blob/d2148d4ea5e2f99d3c56cedf3c325feffb446c5c/core/src/com/unciv/logic/map/mapunit/movement/UnitMovement.kt#L509C9-L524C10

- The knight at `(-11, -3)` swaps with the crossbowman at `(-11, -6)` via `swapMoveToTile`.
- The knight successfully moves to the new position (as well as the releasing restoring)

Now, here:

https://github.com/yairm210/Unciv/blob/d2148d4ea5e2f99d3c56cedf3c325feffb446c5c/core/src/com/unciv/logic/map/mapunit/movement/UnitMovement.kt#L525C8-L526C54

I find that when the crossbowman tries to move to where the knight was, it can't. Thus `lastReachedEnterableTile` is never set and remains as `(-11, -6)`

Therefore, we put the crossbowman at `(-11, -6)`

https://github.com/yairm210/Unciv/blob/d2148d4ea5e2f99d3c56cedf3c325feffb446c5c/core/src/com/unciv/logic/map/mapunit/movement/UnitMovement.kt#L458C13-L458C45

Then when we put the knight in the tile, we're putting it at the crossbowman's old location, `(-11, -6)`, where it still is

https://github.com/yairm210/Unciv/blob/d2148d4ea5e2f99d3c56cedf3c325feffb446c5c/core/src/com/unciv/logic/map/mapunit/movement/UnitMovement.kt#L528

**Comment by willjallen** [comment]
Interesting to note, the internal logic of canMoveTo for this case was specifically blocked by `canSwap` being false. Given the context, I tried passing in a canSwap paramater to the function and using it

```kotlin
            if (unit.movement.canMoveTo(tile, assumeCanPassThrough = true, canSwap)) {
                debug("MOVING $unit$lastReachedEnterableTile")
                lastReachedEnterableTile = tile
                unit.useMovementPoints(passingMovementSpent)
                passingMovementSpent = 0f
            }


```kotlin
// Step 5: Perform the another movement
otherUnit.movement.moveToTile(ourOldPosition, canSwap = true)
```

then the crossbowman makes it to (-11, -4) before crashing, since a pikeman is already there. 

This seems ancillary, though. I agree the fundamental issue is has to do with `canUnitSwapTo` or something similar.

 Also, agreed. Makingcalls to `removeFromTile`, `putInTile` and `moveToTiles` inside `swapMoveToTile` where the same `Tile` calls are made in `moveToTile` is dizzying to keep track of.

**Comment by willjallen** [comment]
```kotlin
    private fun canReachInCurrentTurn(destination: Tile): Boolean {
        if (unit.cache.cannotMove) return destination == unit.getTile()
        if (unit.baseUnit.movesLikeAirUnits())
            return unit.currentTile.aerialDistanceTo(destination) <= unit.getMaxMovementForAirUnits()
        if (unit.isPreparingParadrop())
            return getDistance(unit.currentTile.position, destination.position) <= unit.cache.paradropRange && canParadropOn(destination)
        return getDistanceToTiles().containsKey(destination)
    }
```
?

**Comment by willjallen** [comment]
There is the nuclear option of invalidating the entire pathfinding cache for every unit in the game after a road is pillaged-- you could probably do some bounding radius around the pillaged tile but I could see that being somewhat involved. 

I vaguely remember Civ 5 having a noticeable lag spike upon pillaging a road during the late game, so it's possible they took a similar approach.

**Comment by willjallen** [comment]
Confused as to why
```kotlin
swapTile.militaryUnit?.movement?.clearPathfindingCache()
```
in the `trySwapRetreat` location above works to fix this crash, but when I try to implement
```kotlin
    fun setPillaged() {
        // If a road is pillaged, invalidate the pathfinding cache for all units
        val allUnits = UncivGame.Current.gameInfo!!.civilizations.flatMap { it.units.getCivUnits() }
        for (unit in allUnits){
            unit.movement.clearPathfindingCache()
            debug("Auto invalidated %s", unit)
        }
```
and manually force it in the same location in `trySwapRetreat`
```kotlin
val currentTile = unit.getTile()
currentTile.setPillaged()
```
Does not work. It should be accessing the same unit in the end? I guess I am misunderstanding.

**Comment by willjallen** [comment]
I guess so. I'm still working to understand the object hierarchies and relationships. 

In any case, I've confirmed your patch fixes the issue. Unless you can think of anything else this seems good to go.

**Comment by yairm210** [comment]
I think done, with #10619
