### ISSUE TITLE
GPP boost malfunctioning

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#10671]
- [X] I have searched the existing issues

### Version/OS

4.9.5 apk
Android 13

### Description

Great Person generation boost becomes weird when specialist and wonder is combined. See case D.

A. 1 slot from Workshop(3) = 3 pt
B. 1 slot(3) + Angkor Wat(1) = 4 pt
C. 1 slot(3) + Garden(+25%) = 3 pt
D. ( 1 slot + 1 wonder ) + Garden = 4 pt 🤨

### Steps

1. Download & load savefile. It requires [Difficulty_Sandbox mod](https://github.com/paontv/Difficulty_Sandbox).
2. Enter city screen to see there's 1 engineer specialist(3 pt), Great Mosque of Djenne(1 pt) and Garden is available.
3. Buy Garden to see if great person point changes.
4. Go to next turn to see accumulated eng point rise from 6 to 10, not to 11, meaning it's not a visual but calculation bug.

### Expected Behavior

Math time. ***4 × 1.25 = 5***. But i'm getting only 4 pt. What's the point of Garden?

### Savefile

[Arabia_-_2_turns.zip](https://github.com/yairm210/Unciv/files/13560933/Arabia_-_2_turns.zip)

![Screenshot_20231205_212610_Unciv](https://github.com/yairm210/Unciv/assets/64586749/195c9a39-5375-444b-9b60-688c3e3a1556)

### Additional Information

Actually Garden seems to work when the value is big enough. When my city have 14 pt then got extra +25%, 3 pt was added thus it became 17 pt. I guess instead of `rnd[ ( specialist + wonder ) × 1.25 ]` current calculation is `rnd( spc × 1.25) + rnd( wnd × 1.25)`.

**Comment by yairm210** [comment]
I think we *should* fix it, in cases like this my philosophy is "it feels like a bug, that's a bug". We shouldn't aim to copy bugs from the the original.
*how* to solve may be discussed further

**Comment by yairm210** [comment]
Looks good!
