### ISSUE TITLE
Feature request: Movement uniques should register with conditionals 

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#10674]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I've implemented this UnitPromotions.json unique:
https://github.com/hackedpassword/Z2/blob/0c0a0ee3c9b036da8d774935ebde0d0c6e4c7e4e/jsons/UnitPromotions.json#L46

`"Ignores terrain cost <for [Military] units> <with [Citrus]>",`

The behavior, when both conditions are met, is on the first action of the unit in its turn, it does not ignore the terrain cost.

Next action it will respect the unique until end of turn, repeat behavior next turn.

An action could be movement or promotion, haven't gotten to an attack scenario. Actions wait, sleep, swap, automate, do not respect the unique until the above two actions occur.

### Desired Solution

I'd like for the conditionals to be caught and applied first action. 

### Alternative Approaches

Using logical and/or as condition separators, yea. Nope.

**Comment by yairm210** [comment]
I actually already added this as a todo - tldr everything related to movement is cached
We can add a reevaluation of unit movement cache on turn start
Please provide a mod link :)

**Comment by hackedpassword** [comment]
Right! Line in question linked above, mod jsons below. Thank you! 

https://github.com/hackedpassword/Z2/jsons

**Comment by yairm210** [comment]
Couldn't reconstruct - can you attach a save file?

**Comment by yairm210** [comment]
In any case we need to warm that per-tile modifiers will not with, since we can't check for each tile - performance-wise we can't allow that

**Comment by yairm210** [comment]
So we'll need unique validation additions anyway

**Comment by hackedpassword** [comment]
Mod at the commit originally marked has been cloned as a new mod. https://github.com/hackedpassword/Z2-10674

Origin unique once more, from this mod:
https://github.com/hackedpassword/Z2-10674/blob/main/jsons/UnitPromotions.json#L46

You may have to do a little finagling to align the savegame to the alt-mod ... ? I defer to your/devs expertise.

```
"gameParameters": {
    "baseRuleset": "Z2",  // should now be z2-10674

"tileMap": {
    "mapParameters": {
      "mods": [
        "Z2"
      ],
```
Savegame:
[China - 322 turns - 10674.json](https://github.com/yairm210/Unciv/files/13693961/China.-.322.turns.-.10674.json)
