### ISSUE TITLE
UX change: allow unlimited autoplay turns or starting game without human

### ISSUE THREAD

**Issue by ceciltilley898** [yairm210/Unciv#10705]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Sometimes I enjoy watching civilizations fight without playing the game myself, so I use autoplay for the whole game. This means I have to turn it on every 200 turns

Update: I discovered that I can increase the value of `autoPlay.autoPlayMaxTurns` in the GameSettings.json file. However, this is just a workaround and this problem should still be fixed in the game

### Desired Solution

I want to be able to make autoplay keep going from the start to the end of the game, no matter how many turns it takes

### Alternative Approaches

Starting the game with only AI playing would have the same result

**Comment by tuvus** [comment]
Glad to know that someone else likes doing that, too. I'll see if I can do that once I have time.
