### ISSUE TITLE
Feature request: color code notifications

### ISSUE THREAD

**Issue by The-Talik** [yairm210/Unciv#10702]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

During war there can be a lot of notifications and important ones can be missed.

### Desired Solution

An easy UI help would be to color code them, so beneficial ones are green, alerts orange, danger red, etc..  specifically, unit destroyed messages should stand out visually from unit attacked ones.

### Alternative Approaches

NA

**Comment by yairm210** [comment]
What would such 'standing out' would look like, visually?

**Comment by yairm210** [comment]
We already have the icons specifically for this purpose, from past attempts coloring the entire notification looks very bad and is not the way to go

**Comment by The-Talik** [comment]
Yeah, I was picturing background coloring.  Bootstrap alerts do a pretty good job of coloring without being obnoxious: https://getbootstrap.com/docs/4.0/components/alerts/
Looks like they tint the text slightly to match the background, which might be why it's easier on the eyes.
But if you've tried it, and it doesn't work, then it doesn't work.  Just an idea.
Thanks for responding so quickly!

**Comment by yairm210** [comment]
Hmmm
I think the solution may be the wrong one, but the problem is real - some notifications are more important than others.
I think this can be solved by adding an 'importance' to each notification, defaults to low, and displayed notifications will be sorted by importance

**Comment by The-Talik** [comment]
Maybe a few ways to display notifications, then.  Since you don't get animations for enemy turns, I read through the combat log from the bottom to get a sense of what the enemy did each turn.  If the "destroyed" messages were somewhere else, that would make it hard to understand the order of things.  Honestly, the "destroyed" messages are the only ones that I wish stood out more.  Maybe even just bolding the word "destroyed" or "captured" would be enough.

**Comment by hackedpassword** [comment]
I've wanted to mention making "destroyed" colored red for some time. The topic makes sense, at minimum, destroyed actions are the highlights of notifications during war.
