### ISSUE TITLE
No notification for unit captured

### ISSUE THREAD

**Issue by The-Talik** [yairm210/Unciv#10703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.5

### Describe the bug

I noticed that if a unit is captured by a privateer, there is no "unit destroyed" notification, or any other notification indicating that the unit has been captured.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

"unit captured" notification.

### Operating System

Android

**Comment by yairm210** [comment]
Can you provide an autosave for the turn this happens?

**Comment by The-Talik** [comment]
Holy shit!  Less than an hour, and you have a fix pushed for this!  Amazing!  Do you still need a save?  I don't have it handy, but could try to reproduce.

**Comment by yairm210** [comment]
Nope, found the source, this should be it
