### ISSUE TITLE
Units inconsistently waking up from fortification when attacked

### ISSUE THREAD

**Issue by The-Talik** [yairm210/Unciv#10715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.5

### Describe the bug

This might be me not understanding how something is supposed to operate, but most of my units that are fortified or sleeping will wake up when an enemy is nearby, putting themselves in the Next Unit queue.  Scouts seem to never do that, letting an enemy pound on them till they are destroyed.  I'd expect behavior to be consistent across units.

### Steps to Reproduce

1) Fortify a scout in barbarian territory.  
2) ...
3) Profit.

### Operating System

Android

**Comment by yairm210** [comment]
Please provide a save file with an example
