### ISSUE TITLE
Persian Civilization

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#1072]
Hello. I'm on my way to create the Persian Civilization on this game. The only things that seem missing are the icons. Now I need some help. You guys say that the icons must be white on trasparent background. How do I get that transparent background? Do I need to use Photoshop, which I don't have?

Oh, almost forgot. These are all the icons I managed to find:

![hoplite](https://user-images.githubusercontent.com/41149920/64791315-d4d40500-d577-11e9-9e91-b3ce975b8fd6.png)
This is my idea for the Immortal's icon

![mansion](https://user-images.githubusercontent.com/41149920/64791333-dac9e600-d577-11e9-87d0-12e33df787f8.png)
This is my idea for the Satrap's Court icon

![sword](https://user-images.githubusercontent.com/41149920/64791339-dc93a980-d577-11e9-8a99-ea53e984240a.png)
This is my idea for the Civilization icon (but it's better if there's two of these icons, either crossed or circling like in the original game)

**Comment by Smashfanful** [comment]
Thanks. I'll keep that in mind

**Comment by Smashfanful** [comment]
Here are my results

![Persia](https://user-images.githubusercontent.com/41149920/64910814-ffaa8e80-d71a-11e9-8347-d34df196d2a1.png)
![Satrap's Court](https://user-images.githubusercontent.com/41149920/64910815-ffaa8e80-d71a-11e9-8cc9-06baadf1fac6.png)
![Immortal](https://user-images.githubusercontent.com/41149920/64910816-ffaa8e80-d71a-11e9-9463-c15117423833.png)

**Comment by Smashfanful** [comment]
Now, I want to upload these icons in the folder they belong, but I cant, because file uploads require push access to their repository. how do I do that?

**Comment by yairm210** [comment]
A. Fork this repo to your own (this will create Smashfanful/Unciv)
B. Add the necessary files in your own repo
C. Create a pull request to my repo - this is a request to add the changes that you made on yours, to mine.

**Comment by Smashfanful** [comment]
Please, show me how

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/64913283-c3405800-d745-11e9-8893-84c7c6916e42.png)

At the top-right corner of Unciv

**Comment by yairm210** [comment]
Added the Civ (implemented all uniques, added all icons)
You need to still edit the credits.md file, because I don't know where you got the images from

**Comment by Smashfanful** [comment]
Sure, I'll do it tomorrow

**Comment by Smashfanful** [comment]
> Added the Civ (implemented all uniques, added all icons)
> You need to still edit the credits.md file, because I don't know where you got the images from

Done so ^^
