### ISSUE TITLE
We're running on a mix of Gdx versions

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

current master from source

### Describe the bug

https://github.com/yairm210/Unciv/blob/master/buildSrc/build.gradle.kts#L10 introduced in #8208 hard-pulls most of the Gdx 1.11.0 stack into the project.

### Steps to Reproduce

Inspect Project-External Libraries. Change that line and click the offered "Sync now" and see the libraries change to whatever version you typed - if it's 1.12.1 then there will be less entries.

### Operating System

Linux

### Additional Information

Since it seems it's not possible to import BuildConfig.gdxVersion from that file - and the PR deals with android only - should it not be possible to move that linking into the android-specific build.gradle.kts? Or, what's the use of an extra TexturePacker for Android if it can't run on Android (or does someone really install gradle on their device)? Oh I see - that tool actually has nothing to do with Android, despite the name, and despite being crammed into the android branch of the gradle tasks.

Ugly, but it seems there's no way around it - Gdx version needs to be manually maintained in both places??? Or revert that tool - anybody _actually_ running `./gradlew android:texturePacker`?

**Comment by yairm210** [comment]
The idea was for it to run automatically so anyone building from source would always have a texturepacked version of the game ready on Android
This is really a don't care for me, I'm fine with keeping it different and fine with unifying, and if it causes problems I'm fine with getting rid of it. Really cannot find the care-bear within myself to give this a stare.
