### ISSUE TITLE
crash while loading next turn

### ISSUE THREAD

**Issue by kacpeG** [yairm210/Unciv#10755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.9

### Describe the bug

Next turn tries to load but crashes half way through, turn 236, didnt happen before.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Link to save file

[Autosave.zip](https://github.com/yairm210/Unciv/files/13691885/Autosave.zip)

### Operating System

Windows

**Comment by SeventhM** [comment]
> Link to save file

403 Forbidden. Can't see the save

**Comment by kacpeG** [comment]
> > Link to save file
> 
> 403 Forbidden. Can't see the save
then how can i put my save here?

**Comment by kacpeG** [comment]
Something being done about this? newest version didnt fix this problem

**Comment by yairm210** [comment]
@SomeTroglodyte caused by #10714
Also, the code there is borderline unreadable

**Comment by yairm210** [comment]
I'm sorry, I'm going to just revert that because it is *way* unreadable, I obviously auto-approved that because it is just... 
????????
