### ISSUE TITLE
Mouse position is incorrect on Macos in fullscreen

### ISSUE THREAD

**Issue by VisenDev** [yairm210/Unciv#10761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.9

### Describe the bug

When going into full screen on macos, the mouse has an incorrect offset. So the game things the mouse is lower than it actually is. Making for a very unpleasant playing experience

I have to avoid using native fullscreen to resolve this

The macos system setting `automatically hide and display the dock` seems to be related to this. There may be some sort of error with the JVM when this setting is enabled. I think(??) that this issue does not occur when that setting isn't set

### Steps to Reproduce

1. Open the game on a mac machine with this setting on

<img width="469" alt="Screenshot 2023-12-16 at 12 40 13 PM" src="https://github.com/yairm210/Unciv/assets/48253336/25c5b7e5-3092-4c86-b82b-d6f781fb07d2">

2. Enter full screen mode

### Screenshots

I tried to get the best example I could with a small enough file size here

https://github.com/yairm210/Unciv/assets/48253336/3b938811-3b8d-48e1-a67d-0b3af71fe86b

### Operating System

Linux

### Additional Information

Operating system is macos not linux

**Comment by VisenDev** [comment]
I'm aware this may be an issue with the JVM, not with the game, but I wanted to post it here just in case it was related

**Comment by yairm210** [comment]
Not directly an Unciv problem, but probably not a JVM problem either - probably under LibGDX or LWJGL3, searching their issues naively I couldn't find anything related

**Comment by VisenDev** [comment]
> * Is @VisenDev now our Mac tester / dev? We're lacking one, right? How about it?

Sure, I'd be happy to contribute

> You could start by investigating how to install Android Studio on mac and get Unciv to run as debuggee - taking notes, then updating our dev documentation 👼

I'll see what I can do

**Comment by SeventhM** [comment]
Unstaling with a comment? is this still an issue? Idk if any of us actually tests on Mac, so I doubt any of us could confirm it

I also kinda feel like if this is an upstream issue, it should be closed as not our jurisdiction
