### ISSUE TITLE
Feature request: Toggle to disable "Start turn with unit selected."

### ISSUE THREAD

**Issue by kesken1745** [yairm210/Unciv#10770]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

The frustration arises from the game asking me for commands on a unit I've just fortified on the border. And this isn't a one time thing, it happens EVERY turn. The game is auto-selecting an unit that doesn't need to be selected. Why is this needed? You can't get rid of it even with "Check for idle units." turned off. This is clearly annoying a lot of people.

This issue has persistently plagued water units, where there's no option to "freeze" them on certain tiles, defending/ partrolling certain islands/ waterways, preventing the initiation of queries for commands on units I didn't intend to move. The recent update has exacerbated this annoyance, extending it to most landlocked maps as well.

### Desired Solution

- Add a toggle for disabling the new "Start turn with unit selected." Feature.

- Adding a "fortify" equivalent for (intended to be stationary) water units.

### Alternative Approaches

Perhaps you could add a "Guard" feature for units, allowing them to remain stationed at specific tiles. This functionality could operate similarly to automation, wherein units or civilians detecting nearby barbarian threats could respond and subsequently return to their designated tile. It's frustrating that all my units, even when at full health, automatically retreat into my cities when there's no immediate task at hand. I desire the ability to have them strategically defending specific regions around my empire instead of congregating in cities unnecessarily. Forts could have something to do with this.

**Comment by yairm210** [comment]
I'm fine with a redesign
But I won't have the headspace to check it, tbh

**Comment by yairm210** [comment]
Forgot we had this, this is actually done a while ago
