### ISSUE TITLE
Units removed as obsoleted in production - SOLVED in 4.9.10-patch1

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#10773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.10

### Describe the bug

When finishing researching a technology, all units in the production are removed as obsolete. There are a lot of duplicate bug reports in Discord, and I thought that we should formally make an issue on Git Hub.

This is due to a regression in #10664.
Line 354, ` .filter { it.value.isObsoletedBy(techName) } ` was removed in In TechManager.kt, which is the problem.
The discussion about this on Discord has led me to believe that simply adding this line back in would go against the intention. This means we should probably consider reverting the entire PR, since it is a game-breaking bug, until we can get it sorted.

### Steps to Reproduce

1. Have units in production
2. Finish researching any technology

### Screenshots

<details><summary>Pictures from discord from 3 different people</summary>

![Screenshot_2023-12-18-19-18-29-31](https://github.com/yairm210/Unciv/assets/7538725/4bbed354-7b02-4c1c-8b96-1d72e965c22f)
![Screenshot_20231218-184654](https://github.com/yairm210/Unciv/assets/7538725/571200c7-e735-4faf-963c-49d06840c2de)
![image](https://github.com/yairm210/Unciv/assets/7538725/c3402b43-ab06-4ad9-a788-05939c0d20cf)

</details> 

### Operating System

Android

**Comment by tuvus** [comment]
No specific test cases were given since researching any tech will cause the problem.

**Comment by willjallen** [comment]
I vote that, in the interim, we simply revert #10664 and push that as a hotfix. This is a pretty nasty bug to play around.
