### ISSUE TITLE
Deciv Mod Crash

### ISSUE THREAD

**Issue by Pween** [yairm210/Unciv#10783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.10

### Describe the bug

The game crashes unexpectedly after a few hundred turns.

### Steps to Reproduce

Simply continue the game for a few turns.

### Link to save file

[Unciv Deciv Save for Github.txt](https://github.com/yairm210/Unciv/files/13730294/Unciv.Deciv.Save.for.Github.txt)

### Operating System

Android

### Additional Information

[Unciv Deciv Error info for Github.txt](https://github.com/yairm210/Unciv/files/13730308/Unciv.Deciv.Error.info.for.Github.txt)

**Comment by yairm210** [comment]
Solved in 4.9.10-patch1

**Comment by yairm210** [comment]
Actually no I misremembered

**Comment by dHannasch** [comment]
I reproduced the crash on 08514cbd2e26852cf4f800f4d9bc7b88e419fb80 (just hit Next turn once). On f09700396c69aa8b87268d34c4b7773f21acbce6, the crash does not happen after six turns. As @SomeTroglodyte predicted.

I think this can be closed thanks to https://github.com/yairm210/Unciv/commit/7a28f151062ad71c473ebcfa3fede7de0d4e378b.
