### ISSUE TITLE
Philippines

### ISSUE THREAD

**Issue by MrUldiggg** [yairm210/UnCiv#1079]
![PH](https://user-images.githubusercontent.com/55134079/64907649-f8d64880-d727-11e9-9afe-a9f0819709d0.png)
Philippines Icon

**Comment by MrUldiggg** [comment]
![noun_Church_2087599](https://user-images.githubusercontent.com/55134079/64907656-0c81af00-d728-11e9-9851-a7f25f5d66b6.png)
Coral Church

**Comment by MrUldiggg** [comment]
![noun_soldier_2096478](https://user-images.githubusercontent.com/55134079/64907730-eb6d8e00-d728-11e9-9ba1-91b42482d799.png)
Philippines Katipunero

**Comment by yairm210** [comment]
Good images!

Reminding you that this is on pause for now, but the imigaes are crucial when creating a new civ they really make things go much faster, thanks!

Remember to add here a link to the original icon, so we can add it to the credits.md page eventually!

**Comment by MrUldiggg** [comment]
i add a assyria
what do you think?
i add next?

**Comment by Smashfanful** [comment]
Assyria is already a CivV original civilization, introduced in Brave New World. I've send you the link in your Assyrian Civilization issue

**Comment by yairm210** [comment]
I just checked, and Philippines isn't even an original Civ V civ. It's from a mod.
So I'm probably not going to add this anytime soon =/

**Comment by yairm210** [comment]
So are both australia AND nubia
...
