### ISSUE TITLE
Next unit not presented all the time

### ISSUE THREAD

**Issue by Malvisk** [yairm210/Unciv#10790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.10 patch1

### Describe the bug

Started a new game with current release. Once I get two units, manually moving both units I find there are turns that it doesn't go to both units. Move first unit and given Next Turn option. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by yairm210** [comment]
Can you provide a save file with an example?

**Comment by SeventhM** [comment]
Definitely needs a save, but I have a suspicion

Are you by chance pressing for the next unit immediately as the turn starts, then moving? If so, it may be you missed that the first unit was already selected

**Comment by yairm210** [comment]
If so, that will be solved next version, where we're removing the 'select first unit at start of turn'
