### ISSUE TITLE
Feature request: Depeche/Telegram function

### ISSUE THREAD

**Issue by Lesiakower** [yairm210/Unciv#10808]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Sometimes when I'm playing with a non-AI player I want to send them a short text message (not only resources, open border treaties etc.) that would tell or briefly describe them a problem.

### Desired Solution

I imagine that in the the trade offer window (picture below) a fountain pen or quill icon would be added after clicking which a pop-up window with space for text (~100 letters maximum) would show up.
![11111111111](https://github.com/yairm210/Unciv/assets/125187776/32d5be53-b38a-4acf-ba88-21318ce527f3)
The player I'm giving the offer to would be then automatically given the message in the next turn.

### Alternative Approaches

_None_

**Comment by SeventhM** [comment]
I'm 100% aware that this will go stale again in a few months, and I'll let it close then... But actually I'm curious what the chances could be that this gets added to APIv2
