### ISSUE TITLE
Combat damage floating text doubles in black

### ISSUE THREAD

**Issue by prod0ad** [yairm210/Unciv#10802]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.9.11

### Describe the bug

When units attack the red text is applied a second time, in black/dark grey and a bit displaced.

### Steps to Reproduce

Just play I guess, not sure if it happens on all systems since none else mentioned it on discord.

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/9596638/b2799149-52f4-425f-b470-3b3319d00355)

### Operating System

Linux

**Comment by yairm210** [comment]
Can you add a screenshot?
@SomeTroglodyte sounds like shadowed text

**Comment by prod0ad** [comment]
Just uploaded screenshot, was kinda hard to time correctly:p

**Comment by prod0ad** [comment]
> Ah now I see it - _**that far**_ displaced. No, displacement should only be 1 logical world coord unit. So - which mods, including permanent visual ones? Which Linux? Graphics layer? Which Java? Display settings?

Mods: Invalid. Happens even when I disable my mod, the border mod and play the base game.
Linux: Devuan Beowolf
Graphics: GeForce GT 1030, NVIDIA Driver Version:418.181.07
Java: openjdk version "11.0.11" 2021-04-20
Display: 1600 x 900 60hz

**Comment by prod0ad** [comment]
Np and thank for working to fix this. I got a bit confused though with the oldschool game pics and the technicalities:)

**Comment by prod0ad** [comment]
> Nice profile pic by the way.
Credit to Unciv/Hexarealm and Failine/Tanelorn units for Civ2 mods.
