### ISSUE TITLE
AI plays always on Chieftan difficulty

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#10830]
### Game Version

since forever to 4.9.13

### Describe the bug

There are a few comments looking through the code talking about how the AI is never unhappy. They found new cities very early, which is impossible for the player to do. And when using the new AutoPlay feature to play as a Civ against the AIs, I don't have the same benefits they do. Even on Prince difficulty, the AI swamps the AutoPlay Civ even though they supposedly have only an 85% maintenance modifier difference.

After some investigation, I found that in Civilization.kt lines 303 to 309 tell quite the story.
```
    fun getDifficulty(): Difficulty {
        if (isHuman()) return gameInfo.getDifficulty()
        // TODO We should be able to mark a difficulty as 'default AI difficulty' somehow
        val chieftainDifficulty = gameInfo.ruleset.difficulties["Chieftain"]
        if (chieftainDifficulty != null) return chieftainDifficulty
        return gameInfo.ruleset.difficulties.values.first()
    }
```
It turns out that the AI has been playing against us with the Cheftain difficulty all along! And if it can't find the chieftain difficulty, then it finds an even easier difficulty.

Unless there is any other background that I am missing, it seems like we should change this to be more in line with the expectations given to the players. Any thoughts?

### Steps to Reproduce

1. Start a new default game on prince difficulty
2. Use AutoPlay until your civ dies

**Comment by SeventhM** [comment]
This is a direct copy of [how it works in Civ 5](https://civilization.fandom.com/wiki/Difficulty_level_(Civ5)). If there's actually a want to fix it, in theory it likely should be allowing a mod to specify what difficulty the AI play on by default. But it playing on chieftain is in fact, intentional

**Comment by tuvus** [comment]
Okay, it's a little weird, though, how the players can't copy or learn from the AI at the beginning since they are not equal. I know that making a good AI is very hard and will never be as good as a good player. Can we at least state this clearly in the Civilopedia somewhere?

**Comment by yairm210** [comment]
Sure, I don't think it's that interesting to the player what logic the AI is using to play with, though. I only know this because I needed to know in order to program it, it never affected me as a player.

**Comment by yairm210** [comment]
In general if your strategy is 'learn from the AI' then it really doesn't matter what difficulty it's on, since it doesn't *really* change its behavior between difficulties. But that's for another time...

**Comment by SeventhM** [comment]
> anyone care to test?

Completely forgot about this. Though, this seems like something that should be in modOptions, not Difficulty

Tbh, considering closing this myself as this only matters for BNW and mods, not any of the rulesets currently implemented

**Comment by tuvus** [comment]
> Completely forgot about this. Though, this seems like something that should be in modOptions

Yes, modability is probably the solution. 
I don't particularly have the time to work on this now so I am fine with it being closed.
