### ISSUE TITLE
Console commands request

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#10846]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

After making the first scenario, here a a few commands that would be good to have:
- [x] Change city name
- [ ] Add CS (it would be good to have a way to set which CS you want to be in the game)
- [ ] Set year date (would be nice to have)
- [x] Change the terrain (not so crucial, its mostly for generated maps, where you want to change one tile, or you spotted a mistake with your custom map. Or to increase the resource amount. But well, one can be just mire careful.)

Great feature btw! I'm loving it.

**Comment by Caballero-Arepa** [comment]
Is this template thingy new? Good thing, I'll read it later.

**Comment by yairm210** [comment]
1+3 are simple
2 could get messy but doable
4 is something that's been in the backlog for a while, allowing terrain changes dynamically also means allowing terrain change from uniques, not simple but yes planned

**Comment by Caballero-Arepa** [comment]
> Simple? I'd have a lot of respect here - change turn number backwards - side effects??? Well, console is a 'use at your own risk' thing. Or - change turn-number-to-year translation rules? Does not belong in console.
I was thinking in just a symbolic change not the turn number, just the year independently

**Comment by yairm210** [comment]
Ahh, that's actually more difficult, since turn determines year currently, they're not independent...

**Comment by Caballero-Arepa** [comment]
Ah, I see. 
Well, so then perhaps we should change the name of the Issue to just "Command request: Change City Name"

**Comment by yairm210** [comment]
...no?
We can allow set turn, and it you want a discussion year you can binary search for it

**Comment by Caballero-Arepa** [comment]
![image](https://github.com/yairm210/Unciv/assets/78449553/828a3452-9780-4f3b-8604-8670e51170e8)
![image](https://github.com/yairm210/Unciv/assets/78449553/a9ac332b-3802-4821-b63e-f62138920e99)
It would be great if possible

Also, I don't we can set religions or CS influences yet.

- [ ] Set religions
- [ ] Set CS influence
- [ ] Mass delete units

**Comment by Caballero-Arepa** [comment]
I've found a bug.

I created, then I removed a city, and it left a road there. I tried to delete, but I apparently can't.
![image](https://github.com/yairm210/Unciv/assets/78449553/136f0aa3-bf54-477e-9a2b-c382d6078bbc)

**Comment by yairm210** [comment]
This is meant to be for non-devs, the original goal was to enable scenario building
