### ISSUE TITLE
Bug.... same.... 3 save file

### ISSUE THREAD

**Issue by jdw870** [yairm210/Unciv#10874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.15

### Describe the bug

Go to... after bug pop up

### Screenshots

![Screenshot_20240105_014422_Unciv](https://github.com/yairm210/Unciv/assets/131377953/978d31bb-d24b-42e6-a38b-8c5a728767c4)
![Screenshot_20240105_014406_Unciv](https://github.com/yairm210/Unciv/assets/131377953/59c121ae-738d-4651-8bd1-5090f87671f7)
![Screenshot_20240105_014352_Unciv](https://github.com/yairm210/Unciv/assets/131377953/e3d0cd52-b924-4cfd-aeae-a50b6fc4ceeb)
![Screenshot_20240105_014337_Unciv](https://github.com/yairm210/Unciv/assets/131377953/844d6a40-48d2-4c59-a88c-87cc258d2aec)

### Link to save file

[아즈텍 - 118 턴.json](https://github.com/yairm210/Unciv/files/13833312/-.118.json)
[미국 - 158 턴.json](https://github.com/yairm210/Unciv/files/13833315/-.158.json)
[이집트 - 187 턴.json](https://github.com/yairm210/Unciv/files/13833308/-.187.json)

### Operating System

Android

**Comment by yairm210** [comment]
Copy of 10865, please update
