### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by UnderSampled** [yairm210/UnCiv#1088]
UnCiv seems to meet the requirements for inclusion into The F-Droid Android FOSS app repository. There isn't anything you need to do, but if you would like to support us and give people a better experience, you can add screenshots and descriptions to a 'metadata' folder in your repository ( https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository ). If you would prefer not to be included, please let us know.

**Comment by yairm210** [comment]
Have you checked #919 ?

**Comment by UnderSampled** [comment]
My apologies. I didn't realize it was already in progress. I will close this issue and create a new one just for the screenshots and metadata bit.
