### ISSUE TITLE
Add Fastlane app metadata

### ISSUE THREAD

**Issue by UnderSampled** [yairm210/Unciv#1089]
Fastlane is a way of providing app stores with metadata as part of a continuous deployment pipeline. This can be used for easy updating of the app in Google Play, and is also supported by F-Droid as a way of providing Screenshots and other information.

Since there are already some screenshots in the extraimages directory, this should be as simple as reorganizing the information that is already available.

General instructions: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

F-Droid instructions: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository

**Comment by yairm210** [comment]
I've tried using this and it doesn't fit well with my current deployment arrangement at all =(
