### ISSUE TITLE
Mod Checker adds an entry for G&K to every single extension mod in the problem list

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10911]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

`Civ V - Gods & Kings: (Nation) Denmark's unique "[1] Movement point cost to disembark <for [All] units>" contains a conditional on a unit movement unique. Due to performance considerations, this unique is cached on the unit, and the conditional may not always limit the unique correctly.`

An otherwise flawless mod (e.g. a pure music mod) will list this just before 'No problems found'. A teensy bit disconcerting.

### Desired Solution

Would that Unique work properly with no Conditional at all? _Sounds_ like a no-op condition. Technically, that condition can only be false if called with a StateForConditionals that does neither contain a unit nor a ourCombatant... For which probably there is no code path.

### Alternative Approaches

Or - suppress this check for builtin?
Or - ... no idea?

### Additional Context

Introduced by https://github.com/yairm210/Unciv/commit/c0f837628bcfa7683568890d99dde0e76e87940a - skipping the check for builtin would be relatively easy and clean, but somehow a little... unfriendly?

**Comment by yairm210** [comment]
We can just remove that conditional...? :)
