### ISSUE TITLE
Crash a la création d'un panthéon 

### ISSUE THREAD

**Issue by Niky38** [yairm210/Unciv#10914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.17

### Describe the bug

Crash systématique lors de la création d'un panthéon quel qu'il soit. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

Uploading SVID_20240110_183537_1.mp4…

### Operating System

Android

**Comment by yairm210** [comment]
Copy of #10895
