### ISSUE TITLE
Installation on Windows via Google Play games (beta) reserves an extremely large amount of storage space

### ISSUE THREAD

**Issue by Marcel1605** [yairm210/Unciv#10913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.17-patch2 (Build 955)

### Describe the bug

I am able to install the game via Google Play Games (Beta) on my Windows 11 in Germany. This involves first installing Google Play Games (Beta) and then installing the game Unciv.

When the game is installed, a disc image is created that reserves 512 GB on the hard drive.
The userdata file is located under C:\Users\{username}\AppData\Local\Google\Play Games\userdata_02yywfjy.2ez\avd.

Who controls the size of this file?

Best regards

### Steps to Reproduce

1. Go to 'C:\Users\{username}\AppData\Local\Google\Play Games\userdata_02yywfjy.2ez\avd'

### Link to save file

![image](https://github.com/yairm210/Unciv/assets/14981018/7e62d13c-8c08-4daf-8099-987e989a8884)

### Operating System

Windows

**Comment by Marcel1605** [comment]
Install of Google Play Games (Beta) --> No large space reserved.
Install of Unciv --> Large Space is reserved.

**Comment by yairm210** [comment]
This 100% looks like a Google play desktop issue, I have no connection to that
https://support.google.com/googleplay/thread/192037392/google-play-games-beta-creating-500gb-userdata-file?hl=en
https://www.reddit.com/r/AndroidGaming/comments/18wont7/why_does_pc_google_play_games_take_up_512gb/

I don't recommend using it, we have other installation paths
