### ISSUE TITLE
Feature request: Adjustable barbarian settings

### ISSUE THREAD

**Issue by mahurinj** [yairm210/Unciv#10923]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I like having barbarians but I wish they could be toned down a little. 

### Desired Solution

Having a new game settings toggle for spawn rate or something would be great. 

### Alternative Approaches

I don't really know how they are set to work now so it's hard to give great ideas.

**Comment by tuvus** [comment]
The Bonus vs Barbarians in the difficulty level gives civilization an easier time against barbarians.
