### ISSUE TITLE
Feature request: Allow custom emoji packs for mods

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10949]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I encountered some confusion while creating a module, including not finding a way to customize emoji characters. For example, I hope to define [Livability] as this icon
![Livability](https://github.com/yairm210/Unciv/assets/114050365/e2bd5506-65d5-4a66-beb5-5597545e47fb)
 in the uniques text, but I can't do it. It seems that the current Unciv can only support five kinds of Stats emojis. I hope to allow module expansion (of course, I don't expect to be able to customize Stats, which is a huge amount of work).

### Desired Solution

Above.

### Alternative Approaches

Above.

### Additional Context

For example,
<img width="284" alt="image" src="https://github.com/yairm210/Unciv/assets/114050365/32d000fc-12b1-40b3-84ed-277923db3d73">
is not good, and
![屏幕截图 2024-01-16 170019](https://github.com/yairm210/Unciv/assets/114050365/79630175-3cb0-4fff-a94e-0e203d73da33)
this is good.

**Comment by yairm210** [comment]
Is Livability a resource?

**Comment by AutumnPizazz** [comment]
Yes. This is a Resource, but I hope to "disguise" it at the unique level

**Comment by AutumnPizazz** [comment]
>  Seven Samurais, seven Flies, seven Dials, seven Bridges, seven Wizards...

I have difficulty capturing the original meaning of this passage, whether it's through a dictionary or GPT. What does it mean?

**Comment by AutumnPizazz** [comment]
> Will the autoicons code trigger?

It doesn't work...
<img width="764" alt="image" src="https://github.com/yairm210/Unciv/assets/114050365/78e0a9ec-beee-48b7-9a0f-f06013637058">
<img width="208" alt="image" src="https://github.com/yairm210/Unciv/assets/114050365/bf7aaeff-db8e-4585-a8e0-8ff6d138159b">
And I store this png file in unciv\mods\CoeHarMod\Images\OtherIcons

**Comment by AutumnPizazz** [comment]
This does work in the country selection interface, but it's not as good in the civilization encyclopedia interface.
<img width="408" alt="image" src="https://github.com/yairm210/Unciv/assets/114050365/f9f748e2-fd0c-40ce-a23e-c24d48872d41">
<img width="681" alt="image" src="https://github.com/yairm210/Unciv/assets/114050365/55183059-b87a-402c-92e3-dc1dc71cbaa2">

**Comment by yairm210** [comment]
I see, this is because of a conscious choice to remove those extra icons so you won't have double images - one because of the *link* for Livability, and one for the *resource name*
I think this is nicer this way

**Comment by AutumnPizazz** [comment]
Sry to bring up this issue again, but this feature is very useful for richer mods. Hope creators can pick up this project.

**Comment by AutumnPizazz** [comment]
It's cool.

**Comment by AutumnPizazz** [comment]
This should be not stale.
