### ISSUE TITLE
Feature request:   tree replanting

### ISSUE THREAD

**Issue by AdamTeodoro** [yairm210/Unciv#10961]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

regions become unproductive when trees are cut down and it is not possible to create more sawmills, making it impossible to change strategy

### Desired Solution

create tecnology from tree replants in early or mid game.

### Alternative Approaches

create another ground to upgrade production

**Comment by tuvus** [comment]
I think this can be done in a simple mod. Just add a replant tree improvement, and when a worker builds the improvement, it adds the forest again.

**Comment by tuvus** [comment]
Hmm, maybe we could add two new unique:
Addfeaturewhenbuilt
and
AbstractImprovement, the improvement isn't actually built. Instead gives like a one-time resource bonus or something (so it is more useful in other senarios).
Combining them would then create a forest without adding the improvement to the tile.

**Comment by tuvus** [comment]
>Introduce Tile-context triggers?

I don't know what you mean by that specifically.
For AbstractImprovement (needs a better name) it gives the improvements resource values one time. If that's what you are asking.
