### ISSUE TITLE
Feature request: Mods inside a Mod.io

### ISSUE THREAD

**Issue by Caiuzx** [yairm210/Unciv#10981]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

hello 
I had an idea about the game . 
Why NOT put all the mods , scattered a little everywhere on the internet , inside one community ? 
https://mod.io/ 
is the case of OpenXcom - (Xcom Ufodefence game)
Load the mods from menu , and there is no need to register for download . 
This is my Idea for this fantastic game . 
ps : for steam change name :P 
pss : it would need more visibility !
psss : it would sell more than civ V, yes it would.

### Related Issue Links

https://mod.io/ 

### Desired Solution

a menu mods , that load from mod.io for insert all mods of internet of unciv inside a mod.io .thanks

### Alternative Approaches

there are no
but all mods , are on the internet - i don't want download internet.zip !

### Additional Context

![mod_io_screenshot](https://github.com/yairm210/Unciv/assets/49367470/c6e4c7c8-c536-4ae5-950f-4d1d1745736f)

**Comment by yairm210** [comment]
Already considered, and the answer is no.
Mod.io doesn't give us anything that the current modding system is lacking, and it's actively *worse* for long-term maintenance and community collaboration.
Look at Alpha Frontier's [merged PRs](https://github.com/carriontrooper/Alpha-Frontier/pulls?q=is%3Apr+is%3Aclosed) - That's not something you can do in mod.io, and this type of game is not the kind that mod.io is geared towards.

**Comment by yairm210** [comment]
"If only there was one place we could search for, download, and update mods"
![image](https://github.com/yairm210/Unciv/assets/8366208/25348e28-0247-4cf5-9d0e-e21feec51817)

**Comment by Caiuzx** [comment]
Thanks. The best solution it's home-server or pay-server online ? Where the mods for unciv are upload ?
If want upload my mod ? 
ps : for my future game :D

**Comment by yairm210** [comment]
Github
There's a guide here
https://yairm210.github.io/Unciv/Modders/Making-a-new-Civilization/

**Comment by yairm210** [comment]
Nothing in Unciv is paid for
