### ISSUE TITLE
Cannot trade away your last piece of resource.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1099]
1. You have 1 piece of gem, or any resource.
2. Propose a trade to give your gem to a neighbour for anything or for nothing.
3. Next turn you get a message "Our proposed trade is no longer relevant!", and the trade proposal automatically fails.
4. Also next turn your gem is spent in trades in Resources screen. You need one more turn for your gem to return to your disposal.

100% reproducible.

**Comment by yairm210** [comment]
Damn, good catch!
