### ISSUE TITLE
Feature request: plz, Let the AI ​​perform the action as the option name is.

### ISSUE THREAD

**Issue by bisramia** [yairm210/Unciv#11022]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I'm using mod, but mods do not include AI changes. Only images and jsons. 
And the example right now is problems trading post and farm in vanilla.

I'm choosing 'Autamated workers replace improvements' option or not... Workers always turn trading post into farm. And removing jungle&forest

### Desired Solution

I searched about 'auto', but it's all about serious, complicated something... And I don't understand everything.

But I think, If I didn't select the 'Autamated workers replace improvements' option, That means automated workers will don't replace improvements.

### Alternative Approaches

I don't want a great worker AI. Instead of having to press everything one by one, I just want an AI that passingly takes care of the rest without touching what I've set.

At first I thought this was a bug. However, even though I didn't understand it, I saw that there was a discussion about AI that was being improved, so I wrote it with this tag.

**Comment by bisramia** [comment]
I wrote the title when writing it in the bug report, but forgot it while moving it... The title is, "Please let the AI ​​perform the action as the option name is." It was.

**Comment by tuvus** [comment]
>Workers always turn trading post into farm. And removing jungle and forest

This is the current worker automation, yes. Are you using the autoplay feature or manually automating the workers? What do you think the behavior of the worker automation should be?

**Comment by bisramia** [comment]
> > Workers always turn trading post into farm. And removing jungle and forest
> 
> This is the current worker automation, yes. Are you using the autoplay feature or manually automating the workers? What do you think the behavior of the worker automation should be?

I use manually automating the workers. But what difference does it make what use?
I think it is good for AI to perform automatic tasks in a precise and efficient manner. And I think that people who want to completely let AI do as designed should be able to do so.
However, Should be able to choose whether to replace the built improvement, and isn't there even a corresponding option? 
Looking at the answer, is it still a bug to replace even if the option is not checked?

**Comment by bisramia** [comment]
> > Workers always turn trading post into farm. And removing jungle and forest
> 
> This is the current worker automation, yes. Are you using the autoplay feature or manually automating the workers? What do you think the behavior of the worker automation should be?


I'm not raising a problem with the AI's design. I'm taking issue with an option that isn't working properly.

I don't know if it would be efficient for automated AI to remove all forests and jungles and turn trading posts into farms. If not, I don't know it might be better to change it somehow.

I just want AI don't touch trading post I built manually and the forest and jungle I left behind.
Oh, and holy site.

**Comment by bisramia** [comment]
I don't know about AI behavior. I just want, If I did't check 'Autamated workers replace improvements' option, Autamated workers don't touch tiles that already have anything improvements.

**Comment by tuvus** [comment]
Yes, this is an oversight of mine. I will fix this.
