### ISSUE TITLE
Mod not starting, even though mod manager catches no errors

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.2

### Describe the bug

The [Upside-Down mod](https://github.com/SpacedOutChicken/Upside-Down) has started failing. When you attempt to start a new game with Upside-Down as the human player's civilization, you get the old message: "Maybe you put too many players into too small a map?" This is in spite of the fact that the mod error finds nothing wrong with the game.

Strangely enough, the bug doesn't kick in for me when you have Upside-Down as an AI civilization. It only affects human players.

### Steps to Reproduce

1. Install Upside-Down mod
2. Enable Upside-Down mod
3. Choose Upside-Down as player civilization
4. Attempt to start new game

### Operating System

Android

**Comment by yairm210** [comment]
I can manage it
![image](https://github.com/yairm210/Unciv/assets/8366208/03618aa7-063a-4f2d-a9af-ae502be0c124)

Can you give more details regarding your new game setup? Maybe a screenshot?

**Comment by yairm210** [comment]
I tried several map types and sizes

**Comment by SpacedOutChicken** [comment]
![Screenshot_20240128_132233_Unciv.jpg](https://github.com/yairm210/Unciv/assets/58439827/9624a6ca-17b8-4120-8859-11e20e940a13)

It's only on Android where this is happening, so the bug might be unique to version 4.10.2.

**Comment by yairm210** [comment]
Added a 'copy to clipboard' for map failures so we can at least get the stacktrace

**Comment by SpacedOutChicken** [comment]
I'm unable to reproduce the bug now, so whatever the issue was, the recent updates seem to have solved it. I'll open a new issue if it starts happening again.
