### ISSUE TITLE
Feature request: cancel "swap unit" display

### ISSUE THREAD

**Issue by jum-s** [yairm210/Unciv#11043]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

When one selects a unit, then selects "Show more" option, then selects "Swap unit" option, possibilities of swapping units are displayed (a purple dot on movement accessible units). Then one may decide to actually *not* swap the unit, but still want to do something with the unit instead (ie. movement, attack). 

In that case, one have to unselect the unit and re-select it again. If one select "Back" (to main menu, aka "Fortify", "Explore" etc.) then the unit swapping purple dots are still displayed.

### Related Issue Links

Context to unit swapping PR https://github.com/yairm210/Unciv/pull/4049

### Desired Solution

When selecting "Back" option, purple dots should disappear, and moving possibilities (white dots) should be displayed.

### Alternative Approaches

Clicking on the unit may clear the swapping unit possibilities and display movement dots.

### Additional Context

Thank you for this wonderful game.

**Comment by tuvus** [comment]
Click the swap units button again to cancel.

**Comment by jum-s** [comment]
Indeed, thank you. Closing issue for the moment, as I dont have arguments to support that "it feels more intuitive" to only have to click Back to cancel too.
