### ISSUE TITLE
Bug reoccured

### ISSUE THREAD

**Issue by jdw870** [yairm210/Unciv#11069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.5

### Describe the bug

After upgrading the version, the same error occurred again.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![Screenshot_20240203_030711_Unciv](https://github.com/yairm210/Unciv/assets/131377953/4609bd25-8b80-40ec-9450-fef7c708a278)

### Link to save file

[켈트 - 92 턴.json](https://github.com/yairm210/Unciv/files/14143717/-.92.json)

### Operating System

Android

**Comment by tuvus** [comment]
This was fixed in 4.10.6. Please update when you can.
