### ISSUE TITLE
Adding unit conditionals to tile damage unit causes it to stop working entirely

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.5

### Describe the bug

In this mod, water (lava) tiles are supposed to deal damage to units that walk on them. I added the conditional of `<for [All] units>` to the `"Units ending their turn on this terrain take [1] damage"` unique, and it stopped working. If I remove the conditional, it works again, but with that conditional added, it does damage to no units at all.

### Steps to Reproduce

[ConditionalTileDamage.zip](https://github.com/yairm210/Unciv/files/14126796/ConditionalTileDamage.zip)
Run that mod, and park a Basic Drone on top of a Lava tile, and it will do no tile damage to the unit.

### Operating System

Windows

### Additional Information

I'm hoping to be able to target the unique to only specific units, but as it is now, adding any kind of conditional to the unique just shuts it down.

**Comment by RealBamboolord** [comment]
I know this has been requested before, so afaik this isn't a bug report but rather a feature request (I'm no dev though, so I can't tell for sure)

**Comment by SpacedOutChicken** [comment]
It *seems* like this should already work based on how the conditionals are written, but if this is actually a feature request, I can close this and make a comment in the modding request thread instead.

**Comment by RealBamboolord** [comment]
That's probably the better option. Anyways, I support this feature request

**Comment by yairm210** [comment]
After looking into this, this is limited by caching.
We have all kinds of caching going on for making movement faster, and this is one of them - since "make units avoid tiles they will be damaged by" was requested, and we need to retain speed.
I'm sure it's possible to retain much of that speed by having smart caching for "potential problem" vs "definite problem" but it's not trivial.

**Comment by yairm210** [comment]
For now I'll add this to the list of uniques that suffer this same fate...

**Comment by SpacedOutChicken** [comment]
I do appreciate the feature of having units automatically try to avoid tile damage, so thank you for keeping that. I wonder how this will affect my mod. Oh well, that's my problem.
