### ISSUE TITLE
Clicking on the notifications on the right doesn't move map on the affected tile

### ISSUE THREAD

**Issue by andoruB** [yairm210/Unciv#11073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.4 -> 4.10.6

### Describe the bug

As the title suggests, when clicking on the notifications on the right, the game no longer moves the map view to be centred on the affected tile. This was the usual behaviour in the last version I played (4.9.10 IIRC).

### Steps to Reproduce

1. Load/continue game
2. See the notifications mentioning all changes on the map on the right side
3. Click on one of the notifications
4. The map view doesn't centre on the affected tile

### Screenshots

N/A

### Link to save file
https://hastebin.skyra.pw/uzetahomec

### Operating System

Linux

### Additional Information

N/A

**Comment by andoruB** [comment]
Did some more testing:
On the latest version on Android, clicking on the notifications works.

Tried starting a new game -> clicking on notifications works.

Tried continuing the saved game with the bug, getting to the next turn -> clicking on notifications works.

The save file with the bug present was added to the original post above. Here's the savegame on the next turn: https://hastebin.skyra.pw/vosinixoqe

**Comment by yairm210** [comment]
Hmmm
Notifications are saved with a location, when relevant - sounds like there was a bug in previous versions where the notifications generated were not getting locations?
If this works in the latest version, after 'next turn' generates the new notifications, then I'm considering this 'solved;

Thanks for investigating this! If you encounter problems where notifications are not generated properly in the *current version*, don't hesitate to reopen this issue!
