### ISSUE TITLE
4.10.6 Windows JNI error while opening jar

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#11074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.6

### Describe the bug

When opening the jar, an error window titled Java Virtual Machine Launcher opens with the content saying:
`Error: a JNI error has occurred, please check your installation and try again`

I've tried re-installing, re-downloading then re-installing, and the game still opens to that error.

### Steps to Reproduce

1. Download 4.10.6 Windows version "Unciv-Windows64.zip" from GitHub Releases
2. Extract and install
3. Open the jar

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/78248399/8c7f8981-8bdc-4bb5-9049-38f4bb648b34)

### Operating System

Windows

### Additional Information

Note that the Android version opens just fine

**Comment by carriontrooper** [comment]
After trying to rollback, turns out that the problem also exists in 4.10.5 Windows version. Android version works.

**Comment by carriontrooper** [comment]
Tested some more versions back and the problem started appearing in 4.10.4-gradle82 Windows version, since 4.10.4 Windows version works.

**Comment by chr56** [comment]
Same. It seems that it's caused by JRE.

And **it launches successfully with JRE in Adoptium Temurin 17 JDK**.

So, is JRE 11 still used in packing?

**Comment by chr56** [comment]
@carriontrooper 
Well, JRE was updated since `4.10.4-gradle82`.

Please download the completed with JRE (`Unciv-Windows64.zip`).

**Comment by yairm210** [comment]
Hard for me to remote-debug this, first issue is to figure out if this is a *jar* problem or a *bundling* problem
Context: Java target is set to JRE 11, so *theoretically* this should run with that.
Works fine on my OpenJDK 11 locally

So test no. 1 java version
- open command line with winkey+r
- write "cmd"
- enter

Test 2, does original jar work?
- Download the [jar](https://github.com/yairm210/Unciv/releases/download/4.10.6/Unciv.jar)
- Run, either doubleclick (don't know but assume this works in Windows?) or with `java -jar Unciv.jar` command in cmd

**Comment by yairm210** [comment]
Maybe you have JRE 8??? And the builds so far were Java 8 compatible?
Who uses Java 8? That's like a decade old?! Test 1 should reveal if that's indeed the problem
But that's why we have the bundle, and the Unciv.exe - so you don't need to rely on the local JRE
So third question, does the .exe file work?

**Comment by yairm210** [comment]
Actually tested out a virtualbox vm for Windows, but it can't run Unciv due to opengl compatibility.
What this DOES prove is that the JAVA component works fine from the .exe, so my guess is that you're *not* running the .exe file.

**Comment by carriontrooper** [comment]
Regarding running from .exe, I can't - it doesn't open unciv at all since 4.8 or something. I even checked task manager and there's no unciv process/app running, nor does a java instance. That's why I directly open the java file, which usually worked - up until 4.10.4-gradle82, I guess.

**Comment by SeventhM** [comment]
> Regarding running from .exe, I can't - it doesn't open unciv at all since 4.8 or something

Not to be disparaging... But why wasn't there an issue about this? Am I missing something or shouldn't we have investigated this a while ago?

**Comment by carriontrooper** [comment]
Sorry, just had time to check this, tested this with the newest release
![image](https://github.com/yairm210/Unciv/assets/78248399/370aca09-9ee1-4337-b2cb-d33d61e6f6c1)
![image](https://github.com/yairm210/Unciv/assets/78248399/f22a4dbc-cfc7-4181-b7da-21c612731626)

**Comment by SeventhM** [comment]
I forget if it was shift + right click or alt + right click in Win10 (Win11 just has powershell on normal right click), but that should also let you open command prompt in the current folder

**Comment by SeventhM** [comment]
> Curious question is - why does calling the exe not prefer the bundled jre? Did you delete the jre subfolder or bychance unpack only parts?

Curious question: did it actually not prefer the bundled jre? Failure message is different (couldn't create VM vs "compiled on newer version". Seems like the issue there is deeper. 

> No, blanks are not the problem

I've run games done in Shift\_JIS. Actually, because reasons, I sometimes set my text editors/file managers to Shift\_JIS in android to deal with some files. Windows should be able to handle stuff like that just fine, as long as it gets the characters right. The only time you should have issues with windows paths is if you hit the character limit

**Comment by SeventhM** [comment]
> link
Is on the medium. No thanks, don't feel like dropping accounts on sites and guessing whether I need to pay or not. Besides, I know all too well how annoying it is to find out it's in Shift\_JIS. My favorite is having bad file names in Shift\_JIS only to realize it was proper Unicode, but now I gotta switch over half my equipment

> No, it has fallen way behind

Could be wrong but I believe it's more complicated than that. Modern Windows (Win11 definitely, probably Win10 and Win8) uses UTF-16, older parts of windows may or may not use windows-1252 as it was previously the standard (ah yes... Good ole excessive backwards compatibility). But most of the time it isn't needed over Utf

**Comment by carriontrooper** [comment]
Well, just went and downloaded the latest java and jdk (java 8 401 and jdk 21), and now latest Unciv (4.10.8-jdktest/build 967) on windows works... when you click the jar. Exe still doesn't work.
![image](https://github.com/yairm210/Unciv/assets/78248399/bb0ec4ba-090d-4b90-b9fb-26b2ed43de10)

**Comment by yairm210** [comment]
The latest version we reduced the minimum java version back to 8, would have worked even if you didn't change anything
But the fact that the exe isn't working bothers me
Do you have a 32 bit machine maybe...?
