### ISSUE TITLE
Automated Workers replacing Great Improvements

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#11082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.6 (Build 965)

### Describe the bug

Automated Workers now replace Great Improvements (Customs house, Holy site, Landmark, Manufactory) with regular tile improvements.  I'm pretty sure they didn't do this in earlier versions, and I hope this is not a new feature.

### Steps to Reproduce

1. Place a Great Improvement on a tile (any except snow tile) with a Great Person.
2. Set some Workers to automated
3. Eventually the automated Workers will replace the Great Improvement with the regular improvement for that tile (farm, mine, lumber mill, etc.)

### Operating System

Android

**Comment by tuvus** [comment]
I have noticed it for Customs House, Holy site, but I thought that was just the way the stat valuing system works. I'll look into a more complete solution that isn't `don't replace great improvements`.

**Comment by tuvus** [comment]
> Holy site is explained by the tile ranking function valuing faith at zero, and Customs house -probably- is explained by the ranking function devaluating gold yield by 67% (imho a slight contradiction with the comment text there - the comment would justify 33%).

I did notice that the AI workers don't like the base holy site and customs house. But since it was a stat rating problem I deemed it out of the scope of what I wanted to change. Interestingly, it is only causing a problem now since the automated workers do work. 
Are holy sites even worth it as a player? I never build them or the culture great improvements.

**Comment by yairm210** [comment]
Tile ranking for Faith should definitely not be zero, good catch!

**Comment by SHHHHHHH2024** [comment]
[worker left of berlin.json](https://github.com/yairm210/Unciv/files/14630939/worker.left.of.berlin.json)

High chance I have misunderstood this but please see attached my save of an automated working replacing a citadel.

**Comment by yairm210** [comment]
I think the correct action would be to add "is not replaced by automated workers" unique
