### ISSUE TITLE
Unable to purchase tile within city range

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.6

### Describe the bug

In a game of Smoky Skies Redux with Dreams of Steam enabled, there's one tile within city range which should be available for purchase but which isn't.

### Steps to Reproduce

The tile to the lower left of Harar, next to Mogadishu, with the worker sitting on it, is within range of Harar and not owned by anyone, but when I open the city screen, I can't buy it.

### Screenshots

![Screenshot_20240205_121615_Unciv](https://github.com/yairm210/Unciv/assets/58439827/10716d93-5d1a-4b84-a78c-a4748045bbee)

### Link to save file

[purchase_tile.txt](https://github.com/yairm210/Unciv/files/14170937/purchase_tile.txt)

### Operating System

Android

**Comment by SpacedOutChicken** [comment]
I can't buy the tile through Tomboucto either, because it's out of that city's range.

**Comment by yairm210** [comment]
Buying tiles non-contiguously - bad, if an enemy takes the city you'll have floating tiles
Moving tiles between cities - messes up all kinds of things
Allowing cities to purchase outside 3 range when within 3 range of other city - possible, not sure I like it
