### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by Gospedius** [yairm210/Unciv#11098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.7 (build 966)

### Describe the bug

I'm trying to start a new game and some mods I have previously used are not working. The 3 main ones that aren't working are the 2 future expansion mods ("2022 09 18" and "continued") , and the better pantheons mod. There is a long "incorrectly defined" message when I check the box to select them. I am having the same issue on my Chromebook and my Android. I am current on the updates. This started about a week ago when I tried starting a new game.

### Steps to Reproduce

1. Go to '...' start new gam
2. Click on '...' select mods
3. Scroll down to '...' quick flashing pop up

### Operating System

Android

**Comment by yairm210** [comment]
Please open an issue in the mod's repo, or even better, submit a PR to fix it there :)
Not an Unciv error

**Comment by Gospedius** [comment]
Is there anyway to fix them? I don't know diddly squat about coding and they are really good mods, adds a lot to the game. Especially the future ones.

**Comment by yairm210** [comment]
I mean, it actually has some serious problems, but only 2 of those are blockers - and they can be fixed by adding "+" to the "1 Faith" to make it "+1 Faith"
So you can open a [PR for that](https://github.com/Mechworks-all-day/Better-Pantheons)
I'm not responsible for mod upkeep, game upkeep is hard enough as it is 😓

**Comment by yairm210** [comment]
![image](https://github.com/yairm210/Unciv/assets/8366208/a70fab02-0236-43df-95a0-fa7a7748f556)

**Comment by Gospedius** [comment]
I really appreciate you looking into it, and the work you do for this game. This is an awesome game and it keeps getting better. Thank you ^^

**Comment by Gospedius** [comment]
I was really hoping you could fix the future expansion mod. I will make it
worth your time and effort $$

**Comment by Gospedius** [comment]
I managed to fix the better pantheons mod. I renamed it B.P. and it seems to work just fine now :) 
   I have been trying to tinker with the Future-Expansion-2022-9-18 but I cannot seem to get the alien monolith to do what its supposed to do. it seems wheelchair2 or SpacedOutChicken got it fixed but i have tried many newbish ways to get it to apply to my local/downloaded version to no avail. I have tried to message them as well without luck.        
   If you could somehow fix it on the in game list, or provide me with a download link (https://github......) it would be so appreciated...rename it and what not if you need to. I really like that mod, it adds so much to the mid and late games...I would almost dare suggest to add most or all of it to the main game. 
   I am starting to learn about this "coding" on git hub and I have some other ideas I am pondering for when I eventually get a real computer. Civilization: Call to Power that came out between civ2 and civ3 had some good features, esp as far as future stuff goes...underwater rails and cities...orbital colonies, hover tanks ect ect...

**Comment by jiangsheng** [comment]
The value of the "turnsInto" property should be a string, not an array. You can see the error when opening it in VS Code, with the Unciv extension installed. You can fork and fix it, just remove the [] around "Mountain". 

Somehow Unciv's mod validator failed to parse the json, though, it is passes RFC 8259. The json parser needs to be fixed.

**Comment by SomeTroglodyte** [comment]
> The json parser needs to be fixed

What do you mean exactly - or can you construct a test zip that shows your claim?

> Unciv extension

Wait what, there's such a thing? Where? Is it documented in our wiki?

**Comment by jiangsheng** [comment]
steps to reproduce: 

1. download unciv 4.20.1 for Windows
2. run unciv and download "Future Expansion 2022 09 18" in the mod list
3. In settings, switch to the "Locate mod errors" tab

You would see the Error message

```
Exception loading mod "Future Expansion 2022 09 18"
 Cound not parse json of file Terrains.json
Error reading file: mods/Future Expansion 2022 09 18/jsons/Terrains.json


```
Does Unciv's json parser support space in path on Windows? If it doesn't, then there are probably more characters that can not be used in repo name.

The Unciv extension for VS code (https://marketplace.visualstudio.com/items?itemName=robloach.unciv) provides error highlighting for mod files.

**Comment by SomeTroglodyte** [comment]
> Cound not parse json of file Terrains.json

Well if it throws than that is correct. We do give the parser a schema after all, in the form of the destination class type-object. We only ignore entries that have no field in the target class, we cannot ignore or re-map fields that have an incorrect type.

> The Unciv extension for VS code

Wow, @RobLoach again. I could have guessed. 🥳 🏅 👍 

> probably more characters that can not be used in repo name

Maybe, though we seem to not have encountered them yet. You're welcome to investigate. OS path issues have some history, mainly with older JRE's accepting the moronic Windows 1252 idiocy instead of doing UTF-8 by default - those should be solved by using explicit UTF-8 everywhere we can... I suspect github's rules prevent the worst. Maybe find their actual limits, compare with other git hosters for good measure, then analyze the most suspect allowed chars?

**Comment by RobLoach** [comment]
turnsInto is a string, or null: https://github.com/EmperorPinguin/Future-Expansion-2022-09-18/pull/6

https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/tile/Terrain.kt#L31-L34

**Comment by jiangsheng** [comment]
I just check my mods folder and there are plenty of them with space in names. I think the path issue can be ruled out.

"Error reading file" is not very descriptive on a schema mismatch. Can it locate error like the extension does?

**Comment by SomeTroglodyte** [comment]
> Can it locate error like the extension does?

That would require entirely new code, more than a simple upgrade of what's existing. Even extracting the actual reason from the Exception chain, if Gdx even logs it, would be ugly and potentially fragile code... You're welcome to try. Maybe even just running desktop from a console with logging enabled would show something useful to start with, I don't remember. FYI - the entire validator is build on top of the already parsed rules in memory, the display of load errors was "glued on" much later. Can't find the PR, but #14116 is related...
