### ISSUE TITLE
UnCiv freezes after liberation of worker barbarians on foreign land without open borders

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#11090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.6 (build 965)

### Describe the bug

Hello,

I have a scout, which has the ability to enter all fields without open borders due to a promotion. Now I wanted to free a foreign barbarian worker unit. However, this resulted in UnCiv not responding. I have attached a video about this.

Unfortunately I could not find the game file with the problem, but I could create another one which has the same problem.
After a restart it sometimes worked, but sometimes not.

### Steps to Reproduce

1. Have scout unit with corresponding property
2. Free a barbarian worker unit on foreign land3.

### Screenshots

https://github.com/yairm210/Unciv/assets/46723399/7d42adc0-c142-4e8f-969c-c6e032f1a310
(Compressed, as GitHub does not allow uploads over 10 MB. [Original file](https://upload.disroot.org/r/chxj_Bd8#yDdEh3QIEd/6jT5BwaRnWnK0KVXaW+gltknJHBav73U=))

### Link to save file

[Logiker (191 Runden).json](https://github.com/yairm210/Unciv/files/14180076/Logiker.191.Runden.json)

### Operating System

Android

### Additional Information

Also 4.10.7 (build 966) is also affected.

**Comment by marek22k** [comment]
This time, however, the promotion was not my idea: https://github.com/Mechworks-all-day/Extra-Promotions/blob/8ef87e7d73d521027552267ea4e5cdf6f1ff4c47/jsons/UnitPromotions.json#L31

**Comment by SeventhM** [comment]
That's strictly backwards. That check is to prevent issues like `Free [unit] appears <upon researching [tech]>` from triggering immediately. If it has a trigger conditional (or a unit action conditional), then it's an explicit contract saying "This shouldn't trigger immediately, it should trigger at the conditional". `if (unique.hasTriggerConditional()) triggerUnique()` breaks the established contract

**Comment by SeventhM** [comment]
If so, the Kdoc should be on hasTriggerConditional not UniqueTriggerActivation. Again, it's the intent of the trigger conditional that determines when and how it triggers, it's not UniqueTriggerActivation's job to care
