### ISSUE TITLE
A Translation BUG in Mod Selection Screen about not Properties

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.7

### Describe the bug

This "Resource" should be translated as "资源“  in Chinese, but in fact be "起源" which is not accurate.

![image](https://github.com/yairm210/Unciv/assets/114050365/6ea809ad-53d6-4451-aa33-9280f7ba9377)
<img width="1280" alt="ddb94b354119dd251decb802ca9b7dce" src="https://github.com/yairm210/Unciv/assets/114050365/1e8b9ee5-5750-47d1-b070-9e36150a9a61">

And this Error is not about Properties. I cannot find a wat to solve it so this issue exists.

### Steps to Reproduce

nothing

### Operating System

Windows

**Comment by woo1127** [comment]
![IMG_20240208_144824.jpg](https://github.com/yairm210/Unciv/assets/71725118/c3ff34b6-896c-4927-8488-0e61db021f95)

**Comment by woo1127** [comment]
@SomeTroglodyte Are you in the discord server ?

**Comment by AutumnPizazz** [comment]
https://github.com/yairm210/Unciv/compare/master...AutumnPizazz:Unciv:patch-1
Yeah, I have fixed it.

**Comment by AutumnPizazz** [comment]
![ee642bece019cb428e58c3bfc994825a](https://github.com/yairm210/Unciv/assets/114050365/f7bc4b5c-8527-4aa6-8f78-6bb4daa087b7)
Okay, there's a true BUG for not Properties.
This is a notification triggered when using the Mayan civilization's Long Count calendar.

**Comment by woo1127** [comment]
> They are in my "hostile environments" list. I've managed to log in once (after years of them blocking my privacy tools), found it too chaotic, not worth the pain

No wonder I've never encountered you in the Discord server before 😥; it's always so lively with everyone there.
Also, could I make a small quick request? Can we add a new condition <when discovering [tech]> that triggers only when a civilization is currently researching that technology? This feature will be valuable for us mod creators in numerous cases.

**Comment by woo1127** [comment]
> > Can we add
> 
> a) That's a request for that [Modding requests](https://github.com/yairm210/Unciv/issues/3242) **sticky** b) What now, researching or discovering? Trigger or condition? You're contradicting yourself with that choice of words. c) You must mean condition _while researching_, because ConditionalTech("after discovering [tech]", UniqueTarget.Conditional), ConditionalNoTech("before discovering [tech]", UniqueTarget.Conditional), and TriggerUponResearch("upon discovering [tech]", UniqueTarget.TriggerCondition) already exist.

Feel bad about my English, yes what I exactly mean is "<while researching [tech]>"

**Comment by woo1127** [comment]
yes I think the line of code `UniqueType.ConditionalWhileResearching -> checkOnCiv { tech.currentTechnologyName() == condition.params[0] }` should match the case

The condition should remain triggered as long as the technology is still being displayed as the one being researched on the world screen.

**Comment by woo1127** [comment]
> > Feel bad about my English
> 
> No need. If it wasn't clear enough - it's because Unciv attaches specific meanings to these words that one needs to be a little picky with them. Outside context - 🤷 who cares, no two individuals speak a common language, communication is futile guesswork 🥳

yes I deeply agree 👍

**Comment by woo1127** [comment]
> As for the "you have unlocked" thing - **can't decide** whether to remove the `!` in code ->existing translations become valid, but saves keep the bug. ... or add it in the template -> existing translations will be removed by the generator run on release, but saves will retroactively translate once the translation lines are redone. Or - add the `!` to template _and_ existing translations, presuming the translator's prerogative whether they want it in their translations or not.
> 
> ## Someone wants to add votes or do a poll?

Sorry I am not the translator :(

</br>

> ```diff
> UniqueType.ConditionalWhileResearching -> checkOnCiv { tech.currentTechnologyName() == condition.params[0] }
> ```

I have tested it on my PC, and it works as I intended. Now just need your help to make PR

**Comment by woo1127** [comment]
> Hey wow, 👍 ... So how have you tested? Forked repository, cloned the fork using Android Studio, split off a branch, applied changes, edited mod to test with, run from Studio? 

I didn't go through as many steps as you mentioned. What I did was simply clone the repo -> download gradle -> install kotlin in my vscode -> copy the code you wrote -> build and run -> then edit and download my mod to test it. 

As for now I'm only a second year college student with basic knowledge about web development, deep learning, and basic Java for my previous OOP class, however have little to no knowledge for Kotlin and libGDX. I wonder how much time and effort should I invest to learn enough until I can contribute to this game ? My time is limited and I need to avoid trying learning multiple things simultaneously for long term.

**Comment by woo1127** [comment]
I like open source project, and this is the best 4x Android games I ever play. At the moment, the only way I can contribute is through modding. However, transitioning to become the dev of game is still unfamiliar territory for me, but once I have the time, I might consider learning. Currently my focus would be on my study. 

So, for now, my answer is "no" for temporarily, but that may change in the future.

back to the main point, should I submit the PR for the new unique myself, or would you prefer to do it since you are the one that wrote the code 😂
