### ISSUE TITLE
Exit to desktop after launch

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#1110]
While upgrading from some version below 2.17.10 to some higher version of 2.18.x application stopped running immediately after launch. Instead of displaying black screen at the time of initial launch followed by start screen or world map of a current game, it exited to device desktop screen after the initial black screen. This behaviour continues to the current app versions.

After uninstalling the app from the device, the most recent app version that I managed to install on the device without this error is 2.17.10 p2.  The device is Samsung GT-P5100 Android 4.1.2 with 1GB RAM (usually around 400MB available).

**Comment by yairm210** [comment]
Please attach the game data =)

**Comment by Am-per-Sand** [comment]
Sorry, none available: I uninstalled the app from the device (several times) together with app data and cache cleared. NB This occurs even on fresh installs. I suppose no game game data exists in such cases?

**Comment by yairm210** [comment]
Is this still happening for you?

**Comment by Am-per-Sand** [comment]
Yes, unfortunately it is. Upgraded to 3.0.6 from the Play Store and it exited as described above. Uninstalling (with cache and user data included) and installing 2.17.10p2 resulted in display of language picker and correct gameplay afterwards.

I supposed there was something in the code causing exit because an older version works on the device and a newer one does not on the same device. 

Nevertheless I can remember playing on this device some version with a "goose feather" icon in the top left corner, which appeared somewhere around 2.17.13. Now I have this error with this release and later ones. Therefore I think it may be something device-specific that appeared in the code and was harmless previously - like number or size of some game data files.

**Comment by yairm210** [comment]
Okay, since we can't really check this and it doesn't seem to have happened again, I'm closing this until I hear of it happening again
