### ISSUE TITLE
Forwarded from Unciv Chinese Community: Version 4.10.6 has been reported to contain the a.gray.BulimiaTGen.f virus after being reviewed by Huawei AppGallery, and is prohibited from being installed on Huawei phones.

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.6

### Describe the bug

【a.gray.BulimiaTGen.f】virus does not meet the review standards of Huawei AppGallery. 

Suggestion for modification: Please check the APK file, code, third-party SDKs, and other information of your app, and remove any virus-related content.

Problem speculation: I have searched for many solutions online and conducted tests, but there is no trace of this virus in the package. Therefore, I suspect that there may be an issue with the key, such as a mismatch or corruption.

Solution: The problem can be resolved by repackaging the app with a new key. This issue has persisted across several versions, and we remind developers that repackaging with a new key can effectively address the issue.

### Steps to Reproduce

Nothing.

### Screenshots

![fd281dbc-8cc8-482b-8c22-2df3049b1edf](https://github.com/yairm210/Unciv/assets/114050365/18adbc9b-73d6-48cd-83ce-1135daaf6ef0)

### Operating System

Android

**Comment by AutumnPizazz** [comment]
Forwarded message: The issue with game version 4.10.6 has persisted across several versions. Although it doesn't have any significant impact, it still feels uncomfortable to see it there.

Chinese original text:游戏版本4.10.6这个问题已经持续好几个版本了虽然本身没什么影响但是看着怪难受的

**Comment by yairm210** [comment]
https://www.androidheadlines.com/2023/10/huawei-smartphones-flagging-google-app-virus.html

They have a history of buggy virus checks

 I'm not planning on maintaining an alternative  deployment path because of their buggy software

I don't seem to be the first - see https://github.com/flutter/flutter/issues/85848

**Comment by yairm210** [comment]
I don't even put Unciv there, it looks like it's an entirely different app store
https://consumer.huawei.com/en/mobileservices/appgallery/

I guess that just about settles it. I can't force them to accept the app, there's nothing wrong with it, they have a history of buggy virus checks, case closed
