### ISSUE TITLE
Ввлетел код

### ISSUE THREAD

**Issue by Tihon123eq** [yairm210/Unciv#11108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

Last

### Describe the bug

Я играл и у меня вылетел код, код показать не могу так как много символов
![Screenshot_20240209-021749](https://github.com/yairm210/Unciv/assets/159495994/98745e5b-a792-4992-a7b8-897c3b2ba70f)
Игра зависла

### Steps to Reproduce

1.Зайди в город
2. У тебя мало памяти
3. Вылетает код
4.при втором запуске всë зависло

### Screenshots

![Screenshot_20240209-021749](https://github.com/yairm210/Unciv/assets/159495994/6c3f3709-393c-49c0-bc99-f2cdc8fbab99)

### Operating System

Android

### Additional Information

Это было после последнего обновления

**Comment by Tihon123eq** [comment]
Можно пожалуйста на русском


сб, 10 февр. 2024 г., 01:30 SomeTroglodyte ***@***.***>:

**Comment by yairm210** [comment]
Closing as unactionable
