### ISSUE TITLE
UI dialogs are broken.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1111]
![Screenshot_20190923_162856_com unciv app](https://user-images.githubusercontent.com/6846049/65411492-9ebc3e00-de1f-11e9-8688-798c4bc6ab81.jpg)
![Screenshot_20190923_162907_com unciv app](https://user-images.githubusercontent.com/6846049/65411535-b7c4ef00-de1f-11e9-87ef-40edda4554ee.jpg)

**Comment by yairm210** [comment]
No matter how much I play around with the sizes and resolutions, I'm not getting these results.

**Comment by ninjatao** [comment]
Very Strange. I updated code today and it has become better(topbar in worldscreen is OK now), with still with problems. I failed to upload new screenshots, and will try again tomorrow.

**Comment by lishaoxia1985** [comment]
@ninjatao i have encountered this problem in Huawei mobile phone.How do you solve it? are you Chinese?

**Comment by ninjatao** [comment]
> @ninjatao i have encountered this problem in Huawei mobile phone.How do you solve it? are you Chinese?

No I have not solved it yet. FYI I also use a Huawei mate 10 pro.
And Yes I am Chinese. ^_^

**Comment by lishaoxia1985** [comment]
@yairm210 @ninjatao you can look at the second picture, at the bottom there is a blue block, why? i think it's maybe the reason.

**Comment by ninjatao** [comment]
I have noticed that blue dot very long before this UI problem appears. So probably it is unrelated.

**Comment by yairm210** [comment]
Yeah, that's the empty BattleTable, no relation.
We could make it invisible written empty, is no big deal

**Comment by lishaoxia1985** [comment]
@ninjatao you can package it into Apk and install in mobile phone or run it in virtual machine, i'm not sure it is useful or not.
i check it, find this problem maybe is related in table().

**Comment by ninjatao** [comment]
Updated the game today, and UI became even borkener..

Huawei Mate10 Pro Android 9

**Comment by UniqueActive** [comment]
Mine got worse with 3.1.5 too, Samsung Galaxy S8, see screenshot:
https://upload.disroot.org/r/vof6sepq#jF+1KDJdOVn/Gdl+LmoGV+KUkX5HdfmCOHiSCDI4dAc=

**Comment by yairm210** [comment]
@ninjatao Fantastic! Can you pin down which commit caused it by going back to when it wasn't worse?

**Comment by yairm210** [comment]
Also @lishaoxia1985 seeing as you have both the git to play with and a phone that registers the problem...

**Comment by ninjatao** [comment]
> @ninjatao Fantastic! Can you pin down which commit caused it by going back to when it wasn't worse?

Sure.

**Comment by ninjatao** [comment]
Lastest commit ran OK, so I went for which commits made it better. So I have narrowed down to 3 commit:

commit fb768682fefa6d7869d785d549a6afa0c7a407b2 (HEAD)
Author: Yair Morgenstern <yairm210@hotmail.com>
Date:   Sun Oct 13 11:49:34 2019 +0300

    Added more unit icons =)
    Organized tileset image locations

Very buggy.
![Screenshot_20191016_110650_com unciv app](https://user-images.githubusercontent.com/6846049/66885790-02ddb680-f008-11e9-98ab-6814c4da898e.jpg)

**Comment by ninjatao** [comment]
signing: lib/armeabi/libgdx-freetype.so
commit 5473afbecf2f2cde8f86dfc03124722e259b3ef5 (HEAD)
Author: Yair Morgenstern <yairm210@hotmail.com>
Date:   Sun Oct 13 14:06:18 2019 +0300

    Added icons for the major unit types

Less buggy
![Screenshot_20191016_112550_com unciv app](https://user-images.githubusercontent.com/6846049/66885883-46d0bb80-f008-11e9-948e-ed3c6dc1f9cc.jpg)

**Comment by ninjatao** [comment]
commit 0f351ad964c4a147225b9ca9a618a18c470bff94 (HEAD)
Author: Yair Morgenstern <yairm210@hotmail.com>
Date:   Mon Oct 14 21:43:34 2019 +0300

    Solved "Free tech but all techs already researched" problem

Totally OK.
![Screenshot_20191016_113446_com unciv app](https://user-images.githubusercontent.com/6846049/66886142-06be0880-f009-11e9-9ae5-11fc669403fa.jpg)

Hope these can help.

**Comment by yairm210** [comment]
WHAT
The "Free tech" commit is WAY 3.1.5, where we definitely had problems!
What the hell?!

**Comment by yairm210** [comment]
Wait, does that mean that the problem is resolved in the latest commits? If not, when did the problem arise again?

**Comment by yairm210** [comment]
Literally nothing of note to either backgrounds, tables, or rendering happened in 0f351ad, there's no way that it solved the problem. 0_0

**Comment by ninjatao** [comment]
For me the latest commit is OK, So I went back until encountered problem on 5473afb. This time I uninstall and reinstall apk every time because I was backtracking versions. No idea if it is related.
Maybe you can packetize the latest commit and let more people try it on community?

**Comment by UniqueActive** [comment]
I would be happy to try any fixes, just don't have the time or build env to look into building the apk myself :)

**Comment by ninjatao** [comment]
> I would be happy to try any fixes, just don't have the time or build env to look into building the apk myself :)
> 
> Edit: Just for clarity, the 3.1.5 F-Droid APK is broken for me.

Tell me your QQ or weChat account or Email. I can send you my package.

**Comment by UniqueActive** [comment]
@ninjatao sesamesticks@tutanota.com

Btw is there a way to pm on Github? ;)

**Comment by yairm210** [comment]
@ninjatao How utterly bizarre.
So we basically still have no idea what happened.
3.1.6 is already rolling out on Google Play, I'm not sure when F-droid decide to package and release.

**Comment by UniqueActive** [comment]
@ninjatao The APK you sent looks flawless, not even the little cutoff I had from 3.1.2, who the heck knows what is going on? :D

**Comment by ninjatao** [comment]
OK. Seems we still have no idea what happened but the problem just vanished. I have never thought that would happen o_O

**Comment by UniqueActive** [comment]
@yairm210 @ninjatao 

You will not enjoy this, but I am experiencing this again since the latest F-Droid update. :grimacing: 
It is a very small and non-breaking cutoff at the top of boxes, but it is there, so I wanted to mention it. :)
