### ISSUE TITLE
AI bonus bugs.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1112]
Current AI bonus are not working well. For example, Deity AI should have 100% production bonus, but in fact 2%.

Maybe we can fix ai bonus following this page : https://www.civfanatics.com/civ5/info/difficulties/

When we do this, AI will definitely be much harder to beat.

**Comment by ninjatao** [comment]
@yairm210 Why CivilizationInfo.difficulty is deprecated?

**Comment by yairm210** [comment]
Because it's on the Game level, therefore in gameparameters

**Comment by ninjatao** [comment]
> Because it's on the Game level, therefore in gameparameters

So, we use gameInfo.GetDifficulty() for AI difficulty right?

**Comment by yairm210** [comment]
I'm pretty sure that there's a function like getDifficulty in civinfo
