### ISSUE TITLE
Feature request:A setting about random effects can change to save load.

### ISSUE THREAD

**Issue by fuyiwind** [yairm210/Unciv#11127]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

In Vanilla Civ V the random like Ancient ruins,some player can use S/L to get they need effect,we need a setting can open it.

### Desired Solution

get a setting can use S/L to change random number.

### Alternative Approaches

Or at a game setting?

**Comment by yairm210** [comment]
Feature, not bug - we had to add functionality to get to that :)
