### ISSUE TITLE
Unciv refuses to open with message: "a java exception has occured"

### ISSUE THREAD

**Issue by kacpeG** [yairm210/Unciv#11121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.8

### Describe the bug

i try to open the game and only the a java exception has occured window opens up

### Steps to Reproduce

1. Go to game
2. Click on game
3. Scroll down to game

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/75324317/5e24927b-ee86-4a11-907c-1228a5b163b1)

### Operating System

Windows

### Additional Information

I saw some talk about java versions so maybe i have a wrong one?
![image](https://github.com/yairm210/Unciv/assets/75324317/4a940a42-5e69-4fdc-8814-b63b977e522d)

**Comment by yairm210** [comment]
Yes, your Java version is 10 years old (congrats!) 
Copy of #11074 but with more information - this is what we guessed it would be
The solution should be pretty simple then

BTW, this is why we provide a Windows version with an executable .exe file - I assume you're running the JAR file directly and not the .exe

**Comment by kacpeG** [comment]
> 👍 👍 👍 the veil lifts...
> 
> As for 10 years old - curious story - build 401 _is_ pretty much recent, at least largely security-patched. But - I thought Oracle maliciously barred access to any build after - 202 was it? Suddenly you had to get a Developer account to be allowed to download their Java - I mean I got one, probably, unused for years, but why cripple the general public?
> 
> Anyway, the result _was_ vastly better Java VM's, just not from them.

So which version should i download and from what site? after searching up java i get to the java site and to the same version 8 that i have
