### ISSUE TITLE
Game crashes while transitioning to victory turn.

### ISSUE THREAD

**Issue by Emkazas** [yairm210/Unciv#11130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.5 build 964

### Describe the bug

I once played unciv on an android device, however when I was about to finish apollo program (1 turn left), pressing "Next turn" would always result in a crash. Now I am playing with a computer (windows 10 pro ver. 22H2) through google play. The same thing happens as before with the phone: as I was about to finish the utopia project, proceeding to next turn would always crash the game. Bug report says that platform is andrid though. I have no mods installed, game speed is epic, map is huge with world wrap and with 6 civs and city states.I dont know if i copied the bug report succesfully so i am posting both images of the report and the thing that was presumably copied. Also, on the computer, game tends to crash at random sometimes.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![Screenshot 2024-02-13 212806](https://github.com/yairm210/Unciv/assets/86793882/86914088-07e6-4826-88fa-c899d32f120f)
![Screenshot 2024-02-13 212903](https://github.com/yairm210/Unciv/assets/86793882/51f6a3df-10b6-456d-a459-e3ea011840da)
![Screenshot 2024-02-13 213008](https://github.com/yairm210/Unciv/assets/86793882/364644a0-fb8e-42b6-808b-8986efbd468a)

### Link to save file

![image](https://github.com/yairm210/Unciv/assets/86793882/82b81e4e-82f2-4725-8d50-2390e6f411c8)

### Operating System

Windows

### Additional Information

![image](https://github.com/yairm210/Unciv/assets/86793882/72500718-66c9-45e8-9cdd-e019138a7a9b)

**Comment by yairm210** [comment]
Copy of #11062 - please update
