### ISSUE TITLE
"cant download"

### ISSUE THREAD

**Issue by jeeznutzlmao** [yairm210/Unciv#11147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

"4.10.9"

### Describe the bug

"simply wont download"

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Link to save file

"! Cannot execute "C:\Users\FBCF\AppData\Local\Temp\Rar$EXa1644.39939\Unciv.exe"

### Operating System

Windows

**Comment by yairm210** [comment]
Well at least I learned *something* today
Please unzip the file properly :)
