### ISSUE TITLE
UX improvement: allow disabling Declaration of Friendship

### ISSUE THREAD

**Issue by ceciltilley898** [yairm210/Unciv#11146]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

*No response*

### Desired Solution

I would like to be able to completely turn off Declaration of Friendship so all civilizations would be at war with each other

### Alternative Approaches

*No response*

**Comment by yairm210** [comment]
This sounds like a modding requests, therefore #3242
