### ISSUE TITLE
Credits.md maintenance - broken links

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11176]
### Problem Description

Searching for a specific icon's source sometimes fails - e.g. OtherIcons/Notifications

### Desired Solution

- Document in-game use where none is given, at least in the "Others" category
        - even if it seems obvious now it might not be in the future, especially if TNP deletes a source
- Find missing sources
- Identify broken links
- Decide on a consistent way to deal with broken links where attempts to find a valid one fail
- Replace thenounproject `?search=` links with direct `/icon/<id>` syntax. I'd accept `/term/<term>/<id>` or `/icon/<term>-<id>` too. TNP currently redirects all URLs containing a recognized ID to the last of these.

### Alternative Approaches

ignore, and when a fresh gimp is needed, find an unrelated replacement then document that one?

### Additional Context

List of known broken or incomplete ones:
- [Connection](https://thenounproject.com/search/?q=connection&i=1521886) By Travis Avery
        - Don't know which one in-game this means
        - https://thenounproject.com/browse/creator/travisavery/search/?creator=1815328&name=Travis%20Avery&q=connection
        - ???
- [City](https://thenounproject.com/search/?q=city&i=571332) By Felix Westphal
        - in-game = ?, the creator I can only find in a FAQ comment on TNP, not as actual user
- [Fire](https://thenounproject.com/search/?q=Fire&i=96564) By Lloyd Humphreys for "city being razed" icon
        - use clear, https://duckduckgo.com/?q=site%3Athenounproject.com+Lloyd+Humphreys inconclusive
- Puppet by [vegeta1k95](https://github.com/veget1k95) based on [Puppet](https://thenounproject.com/search/?q=puppet&i=285735) by Ben Davis, for puppeted cities
        - https://thenounproject.com/icon/puppet-1605261/ seems close, but is by HeadsOfBirds, same as resistance?
        - User name is mentioned on TNP only in https://blog.thenounproject.com/free-resources-for-teachers/ - broken too
- [Pumpkin vector](https://www.freepik.com/vectors/pumpkin) by freepik
        - Why did I link a generic search page back then? Can't find the guy... Found!
        - https://www.freepik.com/free-vector/halloween-pumpkin_753628.htm
- [Lollipop vector](https://www.freepik.com/vectors/lollipop) by macrovector
        - Found: https://www.freepik.com/free-vector/vector-set-different-sweets-pink-red-striped-foil-wrappers-swirl-lollipops-xmas-cane-cotton-candy-isolated-white-background_11060369.htm
- (rest of my bad easter egg attributions: identified)
- [Timer](https://www.flaticon.com/free-icons/timer) created by Gregor Cresnar Premium - Flaticon
        - to be investigated: #6856 - must mean the stopwatch for the civilopedia category - so it is:
        - https://www.flaticon.com/free-icon/stopwatch_563480
- [Political Science](https://www.flaticon.com/premium-icon/political-science_5403775) created by Hilmy Abiyyu A. - Flaticon
        - Link OK, but where is it used, exactly? #7469 - should be enough as "used for"
- Icon for Unique created by [vegeta1k95](https://github.com/vegeta1k95)
        - #8188
        - Look: [Double five-pointed star](https://github.com/vegeta1k95/Unciv/blob/9a74b093c20db0cdc2d35f77b2662506efa23a84/android/Images/OtherIcons/Unique.png)
        - seems removed in current master
- [Transform] created by letstalkaboutdune
        - could link the user here, "for" should be "unit action": #8120

... all links in "Others" and "Main Menu" checked. Somebody else please do the rest?

Known missing:
- "OtherIcons/Notifications": From #7122 - @alexban011 do you remember?

**Comment by yairm210** [comment]
It's entirely possibly that users have since removed themselves from thenounproject. 
In such cases our licensing would still hold up
