### ISSUE TITLE
Unciv Wiki Page: Mod File Structure - Uniques Page is broken on the Unciv Wiki

### ISSUE THREAD

**Issue by ClementineAccount** [yairm210/Unciv#11183]
### Is there an existing issue for this?

- I have searched the existing issues

### Describe the bug

The webpage for Mod File Structures: Unique is broken.
https://yairm210.github.io/Unciv/Modders/Mod-file-structure/uniques

I looked around and don't know if I should be using the Issues page to report bugs with the wiki itself but I will document it here in the meantime. I had verified that it was not only on my machine as another friend had the same issue. I had searched for 'Unique' in Issues but did not find an existing issue.

Unsure if it is related to: #11176 

```
Empty string passed to getElementById(). [uniques:1151:29](https://yairm210.github.io/Unciv/Modders/Mod-file-structure/uniques)
Loading failed for the <script> with source “https://yairm210.github.io/assets/javascripts/bundle.8fd75fb4.min.js”.
```

### Steps to Reproduce

1. Go to https://yairm210.github.io/Unciv/Modders/Mod-file-structure/uniques

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/26779639/2394dbfd-2275-42ff-9c01-38edf6bb0c78)
<img width="666" alt="image" src="https://github.com/yairm210/Unciv/assets/26779639/480b9d99-2647-4fd3-8bc5-953eefdbcddc">

### Operating System

Windows

### Additional Information

Firefox: 122.0.1 (64-bit) on Windows 11
Arc

**Comment by ClementineAccount** [comment]
This should be labelled as Documentation too.

**Comment by SeventhM** [comment]
Works fine for me. Can't reproduce. Actually, that's a lie, I can reproduce but only in browsers that have just opened that haven't refreshed yet. Have you tried refreshing the page?

**Comment by SeventhM** [comment]
Wait nevermind. I'm dumb, I should've noticed... You have the wrong link. Please go to https://yairm210.github.io/Unciv/Modders/uniques/ as the page moved recently

**Comment by yairm210** [comment]
How did you get this link? Maybe we have a broken link somewhere else?

**Comment by ClementineAccount** [comment]
> How did you get this link? Maybe we have a broken link somewhere else?

Ah yes! I found it from: https://yairm210.github.io/Unciv/Modders/Mod-file-structure/2-Civilization-related-JSON-files/#techsjson

![image](https://github.com/yairm210/Unciv/assets/26779639/a85bb748-bdb2-4abc-ac8f-06c510d506f9)

**Comment by yairm210** [comment]
Thanks! Looks like that was a problem with all the files that moved to the subfolder, should be fixed now 👍🏿
