### ISSUE TITLE
Automated workers get lost in the ocean

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#11180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.11 (Build 970)

### Describe the bug

Automated workers kind of get stuck in the middle of oceans between two landmasses where you have cities.  They just go back and forth every other turn and never make it back to land unless you turn off their automation.

### Steps to Reproduce

1. Make cites on two landmasses separated by an ocean.
2. Make a bunch of workers in one of the landmasses.
3. Set the workers to automated
4. After they build up one landmass they'll start across the ocean to go to the other landmass.
5. But they'll get stuck in the middle of the ocean and just cycle between two positions every other turn.

### Screenshots

![Screenshot_20240222-173912](https://github.com/yairm210/Unciv/assets/128776112/525540b9-2e68-4435-9533-ef0fe2e26ee4)

### Operating System

Android

### Additional Information

I usually play games with very large worlds if that is a factor.

**Comment by tuvus** [comment]
A save game would be very helpful. This seems like a hard problem to fix. 

They might be looking for unimproved tiles, which get taken by workers closer to the tile. In that case, I had already thought of a solution that would be a very good fix, but it also add a lot of complexity. Hence why I haven't tried to implement it yet.

**Comment by fincentxyz** [comment]
I have noticed this too in games (no mods) where I have 1 or 2 workers around every city on automation mode. Sometimes they just go into the sea and freeze there, until I stop automation, move them to land and put them into automation mode again...

Will try to post a save file where this happens next time I notice it in one of my games.
