### ISSUE TITLE
Feature request: Flat north and south boundaries for rectangular map

### ISSUE THREAD

**Issue by PLynx01** [yairm210/Unciv#11203]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I would like to see the "flat north and south boundaries" rectangular map option, just like in original Civilization 5. For now UnCiv supports only West and east flat boundaries. 

### Desired Solution

The "flat north and south rectangular" map shape option

### Alternative Approaches

I don't know what would be the alternative. If the desired solution is not possible, please suggest something.

### Additional Context

This feature would enable modders to directly copy original Civ5 maps into UnCiv, without the need for rotating them 90 degrees.

**Comment by PLynx01** [comment]
In UnCiv, the upper and lower boundary are jagged, and left and right are flat
In original Civ5, it's inverse. 

See this screenshot to understand what I mean.
![UnCiv edge](https://github.com/yairm210/Unciv/assets/26824047/cdd622b5-bbc4-486f-805b-f817e84abedd)

**Comment by yairm210** [comment]
...
That means turning the entire tile 30 degrees.
That means we'll need entirely new tilesets and unitsets.
Waaaaay out of scope.
