### ISSUE TITLE
AI declaring war on me and declaring friendship with me on the same turn

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.12

### Describe the bug

New Star asked to declare friendship with me and declared war on me at the same time. The declaring war was especially foolish of them since my military outnumbers theirs by about 40 to 1, but they attacked anyway.

### Steps to Reproduce

I've attached a save file from before it happens. Sometimes it happens on the turn right after this turn, and sometimes it takes a few turns. I don't know why New Star is so eager to declare war on anyone, since they're so much weaker than me.

### Link to save file

[BeforeFriendlyWar.json](https://github.com/yairm210/Unciv/files/14399440/BeforeFriendlyWar.json)

### Operating System

Windows

**Comment by yairm210** [comment]
Resulted from land-based nukes (warhead truck) being unconsidered in the AI, therefore leading it to 'attack' like a regular unit and subsequently declare war on you as unfortunate fallout (pun intended)
Solved by adding special treatment for land nukes
