### ISSUE TITLE
AI may not puppet cities by default.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1120]
Annex city : extra 100% population unhappiness
Annex city with courthouse : build time and 4 gold maintenance afterwards
Puppet city : extra 50% population unhappiness

Annex city and build a courthouse ASAP seems best option to me, in most situations.

**Comment by yairm210** [comment]
Remember that annexing a city also means that your next social policy will cost 10% more!

I checked several internet chats on this topics, and most seem to say the same me thing - raze the bad cities, puppet the medium cities, and annex only the good ones.
Even in the case that you annex the city, you should wait until the resistance ends, so the choice to annex should be in the automateCivActions function.

I'm not sure what's a good way to determine bad cities fit for razing... But I guess any city whose production is less than 75% of your cities is a good start...?

**Comment by ninjatao** [comment]
I think razing bad cities may not be as important as it seems. Because AI will much likely build another city on exact the same location and suffer 10% culture cost.

Maybe best strategy is to raze any city with less than a certain amount of population?

**Comment by yairm210** [comment]
Hm, that sounds fair
Any city with less than 3 should definitely be razed, I'd say even with less than 4

**Comment by ninjatao** [comment]
So on conquer:
if pop <=3
    Raze
else 
    Puppet 

Then for puppet cities :
If pop >=10
    Annex

Right?

**Comment by yairm210** [comment]
Sure, sounds good to start with, if necessary we can always change it later

**Comment by yairm210** [comment]
For puppet cities (in next turn automation)

If pop >=10 && !inResistance 
  Annex

**Comment by ninjatao** [comment]
"city.unhappiness * 0.33 < civInfo.happiness"

What does this stand for?

**Comment by yairm210** [comment]
Can the Civ afford to suffer the unhappiness hit from annexing

**Comment by ninjatao** [comment]
Even if civ has negative happiness, it should annex large cities and build courthouses in them. This removes 50% population unhappiness penalty and helps solve happiness problem.

**Comment by yairm210** [comment]
I see, good point
