### ISSUE TITLE
ИИ

### ISSUE THREAD

**Issue by NesQic** [yairm210/Unciv#11219]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Как по мне, надо добавить каких то мозгов ботам. Так как очень много случаев, когда война начинается без причины. Второе, это то, что в моменте все цивилизации могут напасть на игрока, при том, что никакой агрессии не было. Ещё заметил, бот не видит угрозы в виде варваров, для рабочих. У меня в забеге бот отправил 4 рабочих на форт варваров, было, что три поселенца просто терялись. 

### Desired Solution

Сделать логически и  последовательные действия бота 

### Alternative Approaches

-

**Comment by yairm210** [comment]
Translation for the weak:

> As for me, we need to add some brains to the bots. Since there are many cases when war starts for no reason. The second thing is that at the moment all civilizations can attack the player, despite the fact that there was no aggression. I also noticed that the bot does not see a threat in the form of barbarians to workers. In my race, the bot sent 4 workers to the barbarian fort, it was that three settlers were simply lost.

1. War for no reason - AI is trying to win, that's the reason. Explains 'when no aggression' - what, only you're allowed to be aggressive?
2. 4 workers to barbarian fort - sounds interesting! We'll need a game save to debug this

**Comment by yairm210** [comment]
No further input, closing as unworkable
