### ISSUE TITLE
Feature request: Reuse the same ID across multiple platforms.

### ISSUE THREAD

**Issue by Luppyn** [yairm210/Unciv#11239]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Typically, in my gaming sessions with my cousin, I start the game on my phone. To introduce various difficulties and scenarios, we enjoy adding many mods. I've never had a problem with this before, but currently, my game is crashing three out of five times, when I it's my turn. The issues are reported as "Insufficient Memory" (My phone only has 4 GB), and I know it may seem strange to circumvent this problem in this way, but the performance level on the computer is much higher.

### Desired Solution

The idea is to allow the use of the same game ID on both the mobile phone and the computer. This involves creating a tab for entering the value and, in the event of joining a game with mods, initiating the download of those mods.

### Alternative Approaches

Indeed, as I also mentioned, another possible solution is optimizing the game for mobile devices. However, I believe this is something that y'all already strive for by default and not necessarily a feature for improving the quality-of-life.

**Comment by yairm210** [comment]
Sounds like you created a very very large map to me.
Could you attach the save file? Maybe that will help us with memory profiling

For your issue though:
- Main menu > Multiplayer > "copy user ID"
- Main menu > options > advanced > "Take user ID from clipboard"

It's a rare ask, hence why it's hidden
Your games won't automatically be transferred, though, you'll need to send yourself the game IDs as well, unfortunately
Regarding 'download mods when opening game' - I know this is an option when loading a game form a file, I don't recall if this is also the case in multiplayer, would be glad to know :)
