### ISSUE TITLE
Attacking unit that annexed city should end up garrisoning in the city.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1123]
I added cityInfo.conquer for that. Now I don't know how to do it.

**Comment by yairm210** [comment]
That's part of the regular automateUnit function :)

**Comment by ninjatao** [comment]
In current version when you defeat a city and choose to puppet it, your infantry unit will stop in front of the city instead of entering it.

**Comment by yairm210** [comment]
Wierd... I think this is because it still hasn't been moved to our Civ, so the unit can't enter it...?
Probably if we activate moveToCiv in the conquerCity before moving on it will be all me to enter
