### ISSUE TITLE
Infinity symbol not rendered correctly on Windows

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11246]
### Game Version

from current source

### Describe the bug

On Windows with default settings, the infinity symbol used in a few places (six of them) is rendered as '°' instead.
(the other four are - perpetual construction, turns to starvation, turns to growth, turns to construction)

### Steps to Reproduce

1. Start Unciv with default configuration on Windows 10
2. Start a new game, and before founding a city, look at the top bar - culture should show an infinity symbol but doesn't
3. Change Unciv's font selection to Segoe UI - which should **be** the default system font -> infinity renders
4. Change Unciv's font selection back to Default -> no infinity

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/63000004/290e29a1-4bc9-4e0c-a2a7-3f9b396152e0)
![image](https://github.com/yairm210/Unciv/assets/63000004/066e9dba-7f9d-424f-a4c2-e4c06729b45d)

### Operating System

Windows

### Additional Information

Anyone else seeing this? Windoze 11 - same or not?

I can easily make it so that infinity is rendered from EmojiIcons instead - but is is worth it for such an outdated cr* 😈 ?

**Comment by yairm210** [comment]
Adding another custom emoji for infinity sounds a lot less error prone than forcing fonts, especially since user can change the font manually

**Comment by yairm210** [comment]
It also won't break if Windows 14 decides to ship without this font
