### ISSUE TITLE
Got crash on Android, likely after trying swap melee units.

### ISSUE THREAD

**Issue by belonesox** [yairm210/Unciv#11245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.12 (Build 971)

### Describe the bug

Got crash on Android, likely after trying swap melee units.

### Steps to Reproduce

Oww. I am not sure how to reliable reproduce, just want to attach crash report.

### Link to save file
https://gist.github.com/belonesox/f7436c3f21c14a7d8610442022c7e010#file-unciv-2024-03-04-crash-last-saved-game

### Operating System

Android

### Additional Information

Crash report itself:
https://gist.github.com/belonesox/c88debdba47135efaecc50532656c10b

**Comment by yairm210** [comment]
@tuvus 
Is this something we've solved?
