### ISSUE TITLE
Rendering per unit movement paths

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#11261]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Longshot. As originally proposed in #8099, resulting in a most useful progress bar, I'd like to ask what the feasibility of having units slide themselves to their destination, rather than teleport. More specifically, on the mention of #8099, as the AI completes the destination tile during Next Turn, the above action occurs. Later in the game, the player would see rapid unit shifts throughout the battlefield, adding an unsophisticated UX element with significant appeal.

A design note I would consider for the wizard coders present, would be handing each unit movement to a thread (or however the wand waves) so that the unit can move independently of AI calcs. Visual result here would be a cascaded flow of movement. Issue may be resource allocation, prompting an opt in options checkbox. Would likely require 'continuous rendering' on. 

Any feasibility behind the feature described?

### Desired Solution

Visual appeal. 

### Alternative Approaches

Port to Unreal engine.

**Comment by Rincovsk** [comment]
Interesting...reminds me that I would love to see a system similar to Civilization II during turn by turn action, but this might be too complicated. Sometimes I get lost in unciv, specially with bigger maps with lots of Civs. I normally play small maps with no more than 4 Civs for this reason...relying on the reports turn by turn sometimes dont help much...just too much thing happening at the same time in bigger maps and at later stages. Anyway, this game is fantastic!

**Comment by hackedpassword** [comment]
"Doable!"
-Nathan Explosion

**Comment by yairm210** [comment]
Actually, if we're only animating source to destination, only on worldscreen creation, it is doable. But the visual effect would be "everyone moves at once".
Animating the actual path would require saving that info, which sounds like"noooo"

**Comment by hackedpassword** [comment]
Moving forward as hypothetical, since there are obvious technical hurdles.

Can you help me understand why everyone would move at once? Maybe this wouldn't be terrible if it were each civ per move iteration within Next Turn to see what happened like the previous commenter mentioned. I would have thought in OOP where all data is instanciated that forking micro-actions would be "easy" vs logically trivial features being "[hard](https://github.com/yairm210/Unciv/issues/3242#issuecomment-1910630383)" to implement. Reminds me of quantum computing.
