### ISSUE TITLE
"Gain [amount]-[amount] [stat]" cannot work in Unit's unique

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.16

### Describe the bug

![image](https://github.com/yairm210/Unciv/assets/114050365/b8c3daaf-c6ee-4e88-ad29-96a2c660a18f)
![image](https://github.com/yairm210/Unciv/assets/114050365/dfeedee7-f084-4f9e-9c35-9869b09a3ad2)
![image](https://github.com/yairm210/Unciv/assets/114050365/e6caa5a3-d60f-4ff7-8482-dcc9360dd183)
![image](https://github.com/yairm210/Unciv/assets/114050365/15270c87-e0c8-450a-8377-d08a2da5fb10)

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Windows

**Comment by SeventhM** [comment]
\*Squints eyes\* hmm... Does that mean no unit triggers work on turn end? Do building triggers for "in this city" work either? Might have to investigate this later
