### ISSUE TITLE
"Does not need removal of [tileFilter]" not accepting "All" or "Terrain" as filters

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.17

### Describe the bug

I attempted to make a tile improvement that's buildable anywhere, including on top of jungles and forests and marshes. I did this by giving it the unique of `"Does not need removal of [All]"`, hoping that this would cover all possible cases, instead of having to make a unique for every single kind of terrain. It is not working. This unique fails to make the improvement buildable on unbuildable terrain features.

### Steps to Reproduce

I've also tested this with `"Does not need removal of [Terrain]"` and `"Does not need removal of [Land]"`. None of these produce the desired effect.

### Link to save file

This mod contains a simple "Test" tile improvement that's buildable on Land and includes the unique discussed above.
[ImprovementTest.zip](https://github.com/yairm210/Unciv/files/14563852/ImprovementTest.zip)

### Operating System

Windows

### Additional Information

This issue also shows up in the Bio-Tech-aliens mod by @Doomstar00.

**Comment by yairm210** [comment]
That shouldn't be a tileFilter so begin with, it only accepts terrain feature names

**Comment by SpacedOutChicken** [comment]
With that in mind, is there any way to get the effect I want in a single unique, or does each terrain feature need to be specified in its own unique?

**Comment by SeventhM** [comment]
> Each one needs its own unique currently

Last I remember, this also doesn't work. There's some quirky behavior where this unique only works if you're improving a resource. I forget what the reason for it was
