### ISSUE TITLE
"Connect road" command building roads where they're normally not possible

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.17

### Describe the bug

In a ruleset mod I'm working on, I made it so that roads and rails cannot be built in certain tiles. I did this by adding `"Unavailable <in [Not buildable] tiles>"` to the road and rail uniques, and by giving certain terrain features (Rubble and Pyroclasts) the `"Not buildable"` unique. When your worker unit is in a tile and you try to build a road there, this setup works, preventing you from building the road until the terrain feature is removed. If you use the "connect road" command, however, your worker may select a path that cuts right through the "Not buildable" tiles, putting roads in places where you shouldn't be able to build them.

### Steps to Reproduce

1. Using "Rivers of Lava" mod, place at least two cities, with Rubble or Pyroclasts tiles in between cities
2. Instruct worker unit to connect road between two cities
3. Worker unit will build a road that crosses all terrain features, including "not buildable" ones

### Screenshots

![Screenshot (191)](https://github.com/yairm210/Unciv/assets/58439827/23254464-be1e-41aa-8f16-267293871231)
As you can see, the Terraformer has selected a path that has Rubble and Pyroclasts in it. The Terraformer will proceed to build a road right through these terrain features.

### Link to save file

[ImpossibleRoad.json](https://github.com/yairm210/Unciv/files/14551236/ImpossibleRoad.json)

### Operating System

Windows

### Additional Information

[RiversOfLava.zip](https://github.com/yairm210/Unciv/files/14551237/RiversOfLava.zip)
Here's the mod. Still a work in progress.

**Comment by AppTrailblazer** [comment]
Hi, could we have a meeting for the solving this bug?
