### ISSUE TITLE
Enemy units visible through fog of war via movement

### ISSUE THREAD

**Issue by nism** [yairm210/Unciv#11313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.16

### Describe the bug

Available movement is precalculated based on invisible units, allowing player to avoid and/or find enemy units without risk.
Same trick can be used to find barbarian camps (try to move unit to general vicinity of known camp until game will not let you move. That will be the tile of camp <or other player unit if there>)

### Steps to Reproduce

1. Select Destroyer in bottom left near Lillibaeum
2. From movement select screen, 2 tiles up 2 tiles right is a hidden submarine in enemy territory
3. Also unable to move to take Lillibaeum due to precalculated movement penalty adjacent to enemy unit
4. (for advantage) move Destroyer one tile up/right, kill Submarine with aircraft, then successfully take city w/ Destroyer

### Screenshots

![Screenshot_20240315_202846_Unciv](https://github.com/yairm210/Unciv/assets/1823314/64df66c0-571e-4c20-80c4-c18012612cbf)

### Link to save file

Too large, see
https://pastebin.com/7US5U6Zw

### Operating System

Android

### Additional Information

By my memory, original CivV handled this by allowing all movement in fog of war without penalties, recalculating in case an enemy unit came into view (or calculating visible movement possible and actual movement possible seperately?), forcing players to either move with care or risk unintended consequences, as:

Case 1) When movement is cut short by adjacemt enemy penalty: leave unit stranded with 0 movement left
Case 2) When final destination would have been enemy, do not attack and stop unit one tile short. Allow for retreat if remaining movement is available.

**Comment by yairm210** [comment]
#7670
