### ISSUE TITLE
Promotion button not showing up for Civilian units that can be promoted

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.19

### Describe the bug

It's possible to make promotions for civilian units that become accessible if you give the unit XP, but when you build the civilian unit, the button to promote the unit does not show up.

It's still possible to access the promotion menu by other ways. On the menu tab for units, you can see a star by the unit indicating that it can be promoted, and when you select the star, it takes you to the place to select promotions where you can select anything accessible to that unit. Also, if the unit already has a promotion, you can select the promotion area and it takes you to the screen to select a new promotion. It's just that the standard button for promoting the unit never shows up.

### Steps to Reproduce

This mod contains a simple building that grants XP to civilians and a promotion that's only accessible to civilians.
[PromotionTest.zip](https://github.com/yairm210/Unciv/files/14625598/PromotionTest.zip)

### Screenshots

![Screenshot (192)](https://github.com/yairm210/Unciv/assets/58439827/2184c836-f1bb-412d-a7e1-071f3b0ea8ff)
You can see here that the usual button to promote the unit has not shown up.
![Screenshot (193)](https://github.com/yairm210/Unciv/assets/58439827/9f68c932-4152-43bc-af65-e008ada6eec3)
On the list of units, you can see that the unit is eligible for promotion, and selecting the star takes you to the promotion selection menu.

### Link to save file

[WorkerCanPromote.json](https://github.com/yairm210/Unciv/files/14625605/WorkerCanPromote.json)
The worker just built has 15 XP and is ready to be promoted.

### Operating System

Windows

**Comment by yairm210** [comment]
Civilian promotion is a feature the game dies not currently contain

**Comment by SeventhM** [comment]
Probably mod suggestion, so #3242, but actually I'd be willing to allow civilian promotion

**Comment by yairm210** [comment]
Correct, this is a modding proposal
