### ISSUE TITLE
StackOverflowError when building on unbuildable terrain (customs house on snow)

### ISSUE THREAD

**Issue by Bjastkuliar** [yairm210/Unciv#11332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.20

### Describe the bug

While playing a single-player game, the game suddenly crashed after building a customs house on a snow tile.

### Steps to Reproduce

1. Get a great person.
2. Move to a snow tile.
3. Create the great improvement.

I still have to thoroughly test this, but it was the first occurrence of such an event.

### Link to save file

https://gist.github.com/Bjastkuliar/ce292a30dbbd168341e6e7ff28443786

### Operating System

Windows

### Additional Information

I've just updated the game today and therefore it might be an issue of this specific version, I just downloaded the JAR file and swapped the old JAR in the unciv folder (I originally had downloaded the whole "windows edition", but I was using the JRE game, not the .exe

**Comment by SeventhM** [comment]
Close. It wasn't a customs house on snow, it was a customs house on oasis
