### ISSUE TITLE
Crashes repeatedly

### ISSUE THREAD

**Issue by snd846** [yairm210/Unciv#11338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.20

### Describe the bug

Crashes repeatedly with the same message with/without mods and on a new install of the game

### Steps to Reproduce

1. Load save
2. Next turn
3. Crash

### Link to save file

https://hastebin.com/share/okuhecevey.bash

### Operating System

Android

**Comment by yairm210** [comment]
???
What happened??

**Comment by snd846** [comment]
there's already an issue open for crashing that I didn't see before creating this issue, I assumed they were related because both involved tile improvements, didn't want to make a duplicate issue
