### ISSUE TITLE
event didn't work

### ISSUE THREAD

**Issue by Jiangeshi** [yairm210/Unciv#11354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.21

### Describe the bug

I noticed the addition of event.json and related code (such as Triggers a [] event) in the encyclopedia, but after writing the relevant code, I found that it did not have any actual effect. May I ask if this is because the relevant content has not been actually installed in the game yet?

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by yairm210** [comment]
This is one of the vaguest things I've seen
What's the kids? What's the event? What does the mod checker say?
Events do work, and they've been working in other kids
