### ISSUE TITLE
Raze City prompt not going away

### ISSUE THREAD

**Issue by ASnideGitHubUser** [yairm210/Unciv#11357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10. 17-patch1

### Describe the bug

The "Raze City" Prompt on the top of the screen doesn't go away after

***EDIT: THIS WAS ALWAYS MEANT TO BE AN OPTION, IGNORE THIS ISSUE, I WILL KEEP IT UP FOR POSTERITY OR IF SOMETHING SIMILAR BECOMES AN ISSUE***
### Steps to Reproduce

As soon as you double-tap into the city menu, it shows a prompt to "Raze City" not only do I not see any option to raze it but the prompt does not go away even after long periods of time

### Operating System

Android

**Comment by yairm210** [comment]
What prompt? If you mean the button, then yes, that's supposed to remain a constant option

**Comment by ASnideGitHubUser** [comment]
Alright then, if a similar issue occurs I'll put it here
