### ISSUE TITLE
Bug: Repeated trade cut-short and reoffered every turn

### ISSUE THREAD

**Issue by Green-Sky** [yairm210/Unciv#11358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.21 - github .jar

### Describe the bug

**Every** turn for a while now luxury trades get cut short, and the AI offers new trades.

### Steps to Reproduce

1. load game
2. next turn
3. re-accept cut short trades
4. go to step 2.

### save file

https://gist.github.com/Green-Sky/1ba5f7971fe53868fdbede0c9bc55abb

### Operating System
Linux

edit: version was .21 actually.

**Comment by yairm210** [comment]
Not being cut off for me... This seems to be a recurring bug, but one that goes away when loading the game anew, which makes it very hard to debug.

**Comment by SeventhM** [comment]
Possible duplicate of https://github.com/yairm210/Unciv/issues/11325#issuecomment-2002553125. Something tells me the problem is is we're tracking stuff removing resources incorrectly somehow, but I wouldn't know where to start

**Comment by Green-Sky** [comment]
I also had a bug in the same game a few turns later where positive and negative stockpiles where their own resources for some reason, but it went away when reloaded.
