### ISSUE TITLE
Feature request: Improve UI when there are too many kinds of strategic resource

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11362]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

![image](https://github.com/yairm210/Unciv/assets/114050365/5ac55b77-ef2e-42cc-8449-fb44a80b53d8)
You see, it looks ugly when you have too many kinds of Strategic Resource.

### Desired Solution

Make it smarter that this column will automatically wrap when there are too many kinds of strategic resource to fit on the screen.

### Alternative Approaches

Nothing.

**Comment by yairm210** [comment]
Oh, come on, why would you even have that many resources.
That's just bad game design. Let's discuss the specific case, because the UI here is just showing you you have a different problem with the design phase.

**Comment by AutumnPizazz** [comment]
This could be improved even if this bug happened in a bad environment. Doing nothing could harm some modders who like to try anything new especially me QAQ.

**Comment by yairm210** [comment]
No.
This should indicate to the modder that something has gone horribly wrong.
I am fundamentally against this, this is just a bad experience for the player.

**Comment by SeventhM** [comment]
I'mma be funny asnd say that there is still a problem here: accessing the victory screen. Otherwise, use icons and the resource screen, it's not that big a deal. You can hide resources from the world screen, anyways

@yairm210 what even happened to that alternative vertical resource screen anyways?

**Comment by AutumnPizazz** [comment]
> This should indicate to the modder that something has gone horribly wrong.

It is necessary to elaborate on my ideas. I am planning a new mod, Vic3Mod, which is based on Paradox's Victoria 3. This means that I will introduce a large variety of resources to simulate commodities, such as tea, cotton, silk, artillery, and so on. The core gameplay of this mod will deviate from the civilization-style games to some extent. That is to say, this is a mod that focuses on the industrial chain. In summary, the reason why I introduce so many kinds of strategic resources is that Bonus resources cannot be traded, while luxury resources provide extra happiness (happiness will be changed to "prestige" in this mod).
