### ISSUE TITLE
Mods with maps bug new game creation

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#11368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.21

### Describe the bug

It has been happening for a long time now.
I believe it has something to do with the code that automatically sets a recently saved map [from the Map Editor] in the New Game settup.

It mostly happens when you have few maps or is your first time downloading the mod. For some it is fixed by closing and opening the game, but for others it stays.

The bug is that the mod with the maps is forced to be played, even if you manually change the map to a generated map, or not select the mod, and even using the Reset to Default, once you start the match, the app will deselect all the other mods, activate the map mod and use a custom map.

### Steps to Reproduce

1. Open the game
2. Download Latin American Civs
3. Click "start new game"
4. Check the ruleset mod's list
5. Gods and Kings is selected
6. Latin American Civs mod is not selected
7. The map is automatically selected, and is a map of the Americas
8. Check the available civs
9. See Argentina, Bolivia, Chile, different Brazil, Colombia, Costa Rica, Cuba etc... (all Latin American Civs mod's civs) as available civs
10. Try adding more mods and set a generated map
11. Start game
12. Realize it's a custom map and only the Latin American civs mod is active

### Operating System

Windows

**Comment by Caballero-Arepa** [comment]
Thanks a lot!

**Comment by yairm210** [comment]
Hmmm going through the description this is not actually 100% solved, didn't check the 'reset to default' &c

**Comment by Caballero-Arepa** [comment]
Sure! As always, we appreciate your work

**Comment by Caballero-Arepa** [comment]
Unfortunately, the bug is not solved.

I got a good screen recorder and I'll show you.
https://youtu.be/_rNy5_Op-1A

Important note: The mouse is hidden, but when I go to the Main menu, and then back inside New Game, the Latam mod is turned on BY ITSELF! I didn't check it.

**Comment by Caballero-Arepa** [comment]
> Lat-am is supposed to activate if a map using it automatically activates

Of course, but as you can see, I change the map to a generated one, and it still forces me to a Custom map
