### ISSUE TITLE
Feature request: Flathub Verification

### ISSUE THREAD

**Issue by sr66139p** [yairm210/Unciv#11375]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I noticed that the Flatpak is mentioned in the README, but Unciv isn't verified on Flathub. Would you consider verifying it to let people know it's an official package? Here's a link to the documentation on how to verify on Flathub https://docs.flathub.org/docs/for-app-authors/verification.

### Desired Solution

You could verify the flatpak by putting the verification token on the website.

### Alternative Approaches

You could also verify the flatpak through the GitHub repo.

### Additional Context

Verifying lets people know that the package is officially created by, or officially endorsed by, the original project. This makes people more confident in getting the package from Flathub.

**Comment by yairm210** [comment]
I'm not the one who created the flathub app
@MayeulC Can you can give me permissions to the flatpak so I can authenticate it with my github account?

**Comment by yairm210** [comment]
@MayeulC still relevant :)
If you could grant me permissions to the flatpak I could authenticate this

**Comment by MayeulC** [comment]
Hey there,
Sorry I missed the notifications. I've been busy, and they got buried under a pile of other things :/

I was actually looking into getting the Flatpak verified this evening. Unfortunately, I don't control the settings of the flatpak repository, so I will need to ask help from the Flathub team.

Another option would be to create a file at https://yairm210.github.io/.well-known/org.flathub.VerifiedApps.txt containing the following token: `7f709bf6-abe1-4ab3-b20c-effbf0baafb5`, but I'll ask the Flathub team, they are usually quite responsive (much more than I am, anyway...).

I was going to open a dedicated issue for this, but we can also now set [brand colors](https://docs.flathub.org/blog/introducing-app-brand-colors/) to be displayed on flathub.org, should we pick some?

**Comment by sr66139p** [comment]
Picking a color sounds like a good idea. I think it's required to be featured. How about #000032? It's the color of the background in the game

**Comment by MayeulC** [comment]
Well, I was considering this one, but we also need a light one for light backgrounds. It could be the same color, desaturated and lightened, or something different, such as a lighter shade of yellow to go with the smiley face :smiley: 

I will try to perform some other maintenance on the Flathub listing:
* Add release notes
* Use screenshots from the git repository

These will probably go together, as I will need to fetch the full git repository and upgrade the appstream xml with content sourced from there. All automated, of course, as I am far too slow to react, and Unciv releases far too often (which is a good thing :)).

**Comment by MayeulC** [comment]
@yairm210 I had not noticed before, but you were already added as a co-maintainer at the end of July: https://github.com/flathub/flathub/issues/5461

Are you able to login into flathub.org using your github account and verify the listing in https://flathub.org/developer-portal ?

**Comment by yairm210** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/f9f06f23-6f4e-43cd-aefe-d1d28fbbfd03">
Still can't :(

**Comment by yairm210** [comment]
Can you see Unciv in your 'developer portal'? If so maybe the easiest way is to add you as an Unciv admin so you van verify

**Comment by MayeulC** [comment]
@yairm210 I can see it, but I don't have any settings to manage users.
![image](https://github.com/user-attachments/assets/0316c16d-5752-4e78-91ef-3e9f68cc8931)

This is the verification screen on https://flathub.org/apps/manage/io.github.yairm210.unciv

![image](https://github.com/user-attachments/assets/9f6ba01d-d094-4ef8-8dcc-e68fe746b052)

So I don't think adding me as an admin would help at all. I'll ask Flathub maintainers about this.

Another workaround would be for you to create a `yairm210.github.io` repository under your account, with the file suggested in the screenshot above:
```
# file in .well-known/org.flathub.VerifiedApps.txt
7f709bf6-abe1-4ab3-b20c-effbf0baafb5
```

This would create a personal "github pages" website for your account, with the indicated file living at https://yairm210.github.io/.well-known/org.flathub.VerifiedApps.txt
Account GitHub pages are documented on the [GitHub pages](https://pages.github.com/) website.

**Comment by yairm210** [comment]
It works, and verified!!
Tell me if that's enough or if there's something else

**Comment by MayeulC** [comment]
@yairm210 Thanks! Did you end up going the `.txt` route, or did you refresh your account as hinted [here](https://github.com/flathub/flathub/issues/5559#issuecomment-2336667769) (clicking "refresh" in the flathub developer portal, same line as "verified apps")?

We have to decide on colors, for the Flathub listing, but I can create a dedicated issue with mock-ups. I think this can be closed.

**Comment by yairm210** [comment]
I refreshed the account
