### ISSUE TITLE
AI declaration of war

### ISSUE THREAD

**Issue by lolafur** [yairm210/Unciv#11380]
### Before creating

- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697
- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap

### Problem Description

The main problem is to infuse the game with more realism in terms of declaring war on states

### Desired Solution

Hi all. I propose to improve and make the gameplay in Unciv more realistic. I propose to introduce a small detail into the game that will relate to diplomacy and declaration of war. Usually, even friendly cities or allies can suddenly declare war on you. However, this war has no basis. It would be possible to provide some reason why friendly cities or allies declare war.
The reasons for declaring war can be different: the enemy has a strong army and the AI wants to weaken the army, intrusive religious politics, troops are located very close to the borders, or cultural superiority and the enemy wants to weaken your state.
I have suggested perhaps strange reasons for declaring war, but in this way the declared war will have a basis. But in the game it turns out that there is no basis for war. Today he is your ally, and tomorrow he just hates you for no reason.

### Alternative Approaches

No alternative solutions and functions

**Comment by RealBamboolord** [comment]
> ### Desired Solution
> Hi all. I propose @yairm210 to improve and make the gameplay in Unciv more realistic... 
Small hint: pinging the main developer usually makes it less likely for your request to be worked on. The developers regularly read through all issues so they will see your request regardless. So pinging them explicitly is just annoying.

**Comment by lolafur** [comment]
> > ### Desired Solution
> > Hi all. I propose @yairm210 to improve and make the gameplay in Unciv more realistic...
> 
> Small hint: pinging the main developer usually makes it less likely for your request to be worked on. The developers regularly read through all issues so they will see your request regardless. So pinging them explicitly is just annoying.

Thank you, I understand :) I corrected my request

**Comment by tuvus** [comment]
The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.

If we had a justified denunciation mechanic that then provided a smaller penalty for declaring war on another Civ that provide a good incentive to denounce before declaring war.

**Comment by lolafur** [comment]
> The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.
> 
> If we had a justified denunciation mechanic that then provided a smaller penalty for declaring war on another Civ that provide a good incentive to denounce before declaring war.

I opened this topic because I don’t like it and I don’t understand: you and the bot are allies with the state, then after a while he declares war on you, although even a move ago I was allies with him 90 moves ahead. Such mechanics are not correct and fair.
Then, after a union state declares war on me, 5 more states declare war at the same time. And how should I fight back? 6 bots per 1 person. I think this is a flaw in the game.

**Comment by RealBamboolord** [comment]
> > The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.
> > If we had 
> I opened this topic because I don’t like it and I don’t understand: you and the bot are allies with the state, then after a while he declares war on you, although even a move ago I was allies with him 90 moves ahead. Such mechanics are not correct and fair. Then, after a union state declares war on me, 5 more states declare war at the same time. And how should I fight back? 6 bots per 1 person. I think this is a flaw in the game.



> > The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.
> > If we had a justified denunciation mechanic that then provided a smaller penalty for declaring war on another Civ that provide a good incentive to denounce before declaring war.
> 
> I opened this topic because I don’t like it and I don’t understand: you and the bot are allies with the state, then after a while he declares war on you, although even a move ago I was allies with him 90 moves ahead. Such mechanics are not correct and fair. Then, after a union state declares war on me, 5 more states declare war at the same time. And how should I fight back? 6 bots per 1 person. I think this is a flaw in the game.

This usually happens when you have a really low strength ratinn compared to the AI players. The solution is to build more military units beforehand, so only 1 or 2 declare a war on you. You can check strength rating in the victory status screen in the charts.

**Comment by lolafur** [comment]
> > > The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.
> > > If we had
> > > I opened this topic because I don’t like it and I don’t understand: you and the bot are allies with the state, then after a while he declares war on you, although even a move ago I was allies with him 90 moves ahead. Such mechanics are not correct and fair. Then, after a union state declares war on me, 5 more states declare war at the same time. And how should I fight back? 6 bots per 1 person. I think this is a flaw in the game.
> 
> > > The AI factors in relative combat strength, research, production, wonders, score, treaties/trades and other diplomatic relations. Each of them play a part when the AI decides to declare war. Are you asking that an AI should denounce you before declaring war? Then there would be some warning.
> > > If we had a justified denunciation mechanic that then provided a smaller penalty for declaring war on another Civ that provide a good incentive to denounce before declaring war.
> > 
> > 
> > I opened this topic because I don’t like it and I don’t understand: you and the bot are allies with the state, then after a while he declares war on you, although even a move ago I was allies with him 90 moves ahead. Such mechanics are not correct and fair. Then, after a union state declares war on me, 5 more states declare war at the same time. And how should I fight back? 6 bots per 1 person. I think this is a flaw in the game.
> 
> This usually happens when you have a really low strength ratinn compared to the AI players. The solution is to build more military units beforehand, so only 1 or 2 declare a war on you. You can check strength rating in the victory status screen in the charts.


That is, the weak force in this is like a driving motive for me to declare war, if I understand you correctly. Thank you for the clarification, I will take it into account :) In addition to power, science, wonders of the world, diplomacy and more also play a role, the person above wrote this to me.
Now the situation has become clearer to me. I hope my open topic on this matter will be taken into account in the future. Perhaps it will be useful

**Comment by yairm210** [comment]
As per our [guiding principles](https://yairm210.github.io/Unciv/Guiding-Principles/), the AI plays to win.
"Realism" in this case should be "acts like a human player", not "didn't attack unless provoked".
If you have any concrete suggestions to improve under what conditions should the AI declare or not declare war, we can consider them

**Comment by tuvus** [comment]
AHA! This is what I was talking about! It's implemented in Civ VI, something like this would make diplomacy more dynamic and gives the AI more of conquest goal.
https://www.civilopedia.net/gathering-storm/concepts/diplo_3

**Comment by lolafur** [comment]
> AHA! This is what I was talking about! It's implemented in Civ VI, something like this would make diplomacy more dynamic and gives the AI more of conquest goal. https://www.civilopedia.net/gathering-storm/concepts/diplo_3

An excellent site that talks about the different reasons for the start of the war. I don’t presume to judge to what extent this can be implemented in Unciv, but if it were possible to implement at least part of everything written there, it would be very interesting :) But here it’s up to the developers to decide

**Comment by SHypoleac** [comment]
Hello, I also noticed that the AI diplomacy in Civilization requires improvement. I'm new and I'm not exactly sure how the "thinking" mechanism of these bots works, but it seems to me that they are at a lower level than in real Civilization production. Playing at the "Imperator" difficulty level, after the introductory phase, 5 out of 6 civilizations declared war on me, and their reason was that they had about two military units more than me, but some of them didn't even approach my lands. After a few turns, not only did I manage to repel this funny attack, but without any resistance, I boldly attacked these losers, accepting hefty payments for 10 turns of peace. After those turns, their military strength was still at a low level, and to top it off, they were attacking each other, as if they were begging me to take over and end the game in the Middle Ages.

**Comment by yairm210** [comment]
That is definitely something we should fix :)
If you can send a game save of the turn *before* they declare war that could help a lot

**Comment by yairm210** [comment]
Load game - show autosaves

**Comment by SHypoleac** [comment]
Thanks for quick reply, but i haven't got this saves. I'll try to do this one more time, but it'll be better if you show me some file which could show me their thoughts :) Firstly i'll try to translate this lastly 2% of polish language :P

**Comment by SHypoleac** [comment]
You know Crusader Kings game? There is such mod as "Social Relations Expanded" :)  I think that here we can create something similiar
