### ISSUE TITLE
Denunciation quotes

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1138]
I think we should also add some unique denunciation quotes to Civilization. Here are some examples.

JAPAN
Denounced: ["Empty words are no threat. Show me action, purpose, discipline!"]
Denouncing: ["You are a foolish, simple leader. And your people should know the truth."]

ROME
Denounced: ["So, it is true; one who is full of envy, disparages everything, good or bad."]
Denouncing: ["The more corrupt the state, the more numerous the laws. And look how many you have!"]

EGYPT
Denounced: ["You dare insult the Pharaoh? You will regret this!"]
Denouncing: ["Indeed, you are worse than the Libyan scoundrels that me and my ancestors always fight. May the world learn the truth about you."]

CHINA
Denounced: ["So, an insect dares to offend a dragon. That was not wise."]
Denouncing: ["How pathetic is your rule. Your mere presence has forever tarnished your people's reputation."]

FRANCE
Denounced: ["The glory and might of France will not be tarnished by such obvious lies."]
Denouncing: ["I don't like the look of what you've been up to. What would your friends think of this information?"]

BABYLON
Denounced: ["Hah! I am stronger than your false, pathetic words!"]
Denouncing: ["Let the world hear my words: you are as treacherous as Ishtar."]

**Comment by yairm210** [comment]
When a leader denounces you, there's no popup - it just says "X has denounced you"
How do you imagine the UI for this? Regular popup on the turn after denouncing?

**Comment by Smashfanful** [comment]
Well, why not? We can try it out.

**Comment by yairm210** [comment]
Moved to #663
