### ISSUE TITLE
Opening borders in online multiplayer broken

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/UnCiv#1139]
After researching the necessary technology and mutually accepting open borders in diplomacy, my friend was able to enter my territory for one turn and was then thrown out, forcing us to open borders in diplomacy again.
We have not been able to enter each others territories afterwards, even after multiple attempts of opening borders from both of us.

Any help or fix would be appreciated since the only way of being able to play together right now is by declaring war to enter each others territory :)

**Comment by yairm210** [comment]
Fixed, will enter the next version :)

**Comment by UniqueActive** [comment]
Thank you for the quick response, can't wait for the update! :)
