### ISSUE TITLE
World wrap does not work for spectators

### ISSUE THREAD

**Issue by SeventhM** [yairm210/Unciv#11408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.1

### Describe the bug

By default, Spectators don't have the flag set that allows them to scroll the map freely. I believe this has something to do with how `com.unciv.logic.civilization.ExploredRegion` updates explored tiles, though I'm not entirely sure what the fix is here. Do note: this bug does not affect singleplayer spectators in the built-in ruleset presumably due to them gaining every tech a the start of a game, unlike multiplayer spectators, which unlocks Satellites which does not have this issue when revealing the map. Though, I'm not sure if that's the reason or there is a different reason I'm missing
<details>
<summary></summary>

### Steps to Reproduce

Open a multiplayer game as spectator

### Operating System

Android

**Comment by yairm210** [comment]
Arrived independently at the same solution as SomeTrog :)
