### ISSUE TITLE
Chrome OS bugs that make the gamescreen hard to get to

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#1140]
Hello, I'm still playing & enjoying the game more than ever on chrome os! 
Do we still have no other players on the platform? I'd like to help test and iron out two very, very annoying bug upon game start under chrome os's ARC environment:
1. Often the game will show a dark blue screen with nothing on it upon starting; can only be solved by rebooting the machine
2. Sometimes when the gamescreen finally shows up, touch input is screwed: multitouch is not detected (pinch to zoom for example), and buttons in the bottom right corner of the app are not registered, either by finger or stylus input
Since many other apps function perfectly well on the platform and my machine, including while running side-to-side with the game, I assume it's got more to do with Unciv's code than with ARC's? Thanks for any answer

**Comment by yairm210** [comment]
0_0
That DOES sound annoying, but unfortunately I can't think of why this could happen...
The "Dark blue screen" means that it didn't manage to render anything, which is super weird

**Comment by flecheapolinienne** [comment]
The blue screen issue has been going on a while but it was much more manageable before the other bug got on top of it. It seems like it has to do with the switching to "tablet mode" in Chrome OS (what happens when I flip the screen over) since it happens most often... when I switch the screen over.

I'm gonna be on the lookout for both those bugs in order to give you data from inside the game for them. Also, do you have any idea how I might grab data from the Chrome OS system as well and if that'll be any help for you?

**Comment by yairm210** [comment]
Nope, no idea whatsoever :(

**Comment by yairm210** [comment]
Solved in the latest version?

**Comment by flecheapolinienne** [comment]
#2 appears to be solved! #1 still happens sometimes

**Comment by yairm210** [comment]
I have no idea why this happens and no practical way of dealing with this, and it doesn't seem to be a huge issue in any case. So I'm closing it for now as part of spring cleaning.
