### ISSUE TITLE
Feature request: Allow to extend workable tiles of a city through a modifier or tile improvement

### ISSUE THREAD

**Issue by WushingPongPung** [yairm210/Unciv#11422]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I have been trying to make a nomad civilization, but I have found no way extend a city's reach and work tiles outside the 3 tiles limit. I have tried the tile improvement modifier that works a tile without an assigned population but it doesn't also work. I also tried to look if enclaves or outposts disconnected from cities could be done, but I also haven't found any way to do so.

### Desired Solution

I hope that there can be some uniques, either a city, nation, or any other unique really that allows for a city or capital to extend it's workable tiles. Alternatively, maybe there could be a way to achieve this working of tiles outside the 3 tile limit through specific tile improvements that can truly be worked without an assigned population EVEN without being inside the 3 tile limit of a city. 

### Alternative Approaches

Another more complicated approach I think, but will open up a lot more possibilities for modding is to allow enclaves or outposts, that is allowing to claim tiles disconnected from city tiles but still allowing pops to work tiles inside it, or to claim lands similar to a citadel of a great general and work tiles it is built on or the tiles around it. 

There is the question of where exactly would the enclave or outpost's output go to? Maybe this could be achieved through somehow linking a unit that is responsible for the creating the tile improvement to a city or link the tile improvement itself to a city, or just send the resources to the nearest city the outpost is to. 

Although actually I think it will just be easier to just allow cities to exchange ownership or workability of a tile through the city menu and clicking on the tile to unassign and assign it to another city. As to what happens to the outpost when the civ that had it is destroyed is something I am not too sure yet.

**Comment by tuvus** [comment]
A simple global setting that can be changed by mods would be best I think. We might have too much code depending on the distance in which tiles are workable to allow for cities to dynamically change their work radius.

Either way this would take a decent effort to implement and test.

**Comment by WushingPongPung** [comment]
I've tried asking in the Discord but nobody was able to answer me. I would
love to know how to do it with just the global setting, I can settle with
that. I completely understand that coding this could be too much work for
possible minimal results or for fringe cases only. Thanks chief!

**Comment by yairm210** [comment]
This sounds like a classic modding request - #3242

**Comment by 1etsp1ay** [comment]
> This sounds like a classic modding request - #3242

This comes down to gameplay ... the 2 tile limit impacts what you can see approaching your city border ... so an attacker with movement 4 can bumrush an undefended city (aka Mongol style). If you randomly alter this 2 tile parameter, the game dynamics will shift and you need to rethink all the movement modifiers and what units can be detectable (eg pillaging). 

I'd rather implement a **trading system between civs** ... you already can do this with city state gift improvement ... adding more space just makes bigger cities (and unhappy conquerors) but having more diversity adds to the fun rather than feeding the military industrial complex.

**Comment by yairm210** [comment]
Trading what, for example?

**Comment by yairm210** [comment]
I'll close this issue since it's done in #11708
