### ISSUE TITLE
City-State quest "Invest" does not end after its turn limit is reached

### ISSUE THREAD

**Issue by the-s-is-silent** [yairm210/Unciv#11426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.2

### Describe the bug

This bug has existed since at least 4.10.16 according to comments in the bugs discussion channel on the Discord server. Only this one specific CS quest is affected. Invest is effectively permanent once given as long as the CS isn't conquered and you don't demand tribute or get into a war with it.

Mod/ruleset dependencies: None. It can be observed on G&K, DeCiv Redux, Alpha Frontier, Rekmod, etc.

### Steps to Reproduce

1. Open any saved game or start a new game.
2. Play until you see a CS assign the Invest quest and continue play for the normal duration of that quest on your game speed.
3. Observe that once it reaches the last turn for the quest, it gets stuck there and will read 0 turns left for the rest of the game, but will never expire no matter how many turns pass after it would normally expire provided the CS remains alive and unprovoked by you.

### Operating System

Linux

**Comment by SpacedOutChicken** [comment]
I can confirm that this problem still exists as of version 4.11.4. Here is a saved game in which Jerusalem has just started offering an Invest quest: 
[JerusalemInvestStart.json](https://github.com/yairm210/Unciv/files/14974126/JerusalemInvestStart.json)
And here is the game many turns later, with the Invest quest still on the table:
[JerusalemInvestForever.json](https://github.com/yairm210/Unciv/files/14974130/JerusalemInvestForever.json)
