### ISSUE TITLE
Warrior vanished from map

### ISSUE THREAD

**Issue by Puzzlers100** [yairm210/Unciv#11437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.0 Flatpak

### Describe the bug

I moved a warrior escorting a builder onto ruins, spawning a settler. The warrior sprite seems to have vanished, and I cannot interact with it, however it still appears on the units screen, until I tried reloading the save.

I tried including the save, however it seems to have deleted the bugged warrior

### Steps to Reproduce

1. Set warrior (possibly other combat unit, untested) to escort a builder (or other peaceful unit(untested))
2. Move the formation onto a tile containing ruin
3. If a settler(or possibly builder) spawns from ruins, the warrior vanishes from the map

### Operating System

Linux

**Comment by yairm210** [comment]
Can you attach a save file of the autosave for that turn? Load file - show autosaves

**Comment by Puzzlers100** [comment]
I cannot, I reset the game several times trying to replicate the issue, however had not had luck with the loot from the ruins.

**Comment by NeoNeon04** [comment]
I have a similar issue, one of my great war infantry despawned on capturing a city in an escort formation with a great general and the game crashed. Should I start a new discussion with details? I will try to recreate it and save the game file.

**Comment by yairm210** [comment]
This problem should be resolved as of 4.11.9
