### ISSUE TITLE
Russian translation for number of civilizations too long

### ISSUE THREAD

**Issue by lolafur** [yairm210/Unciv#11440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.3

### Describe the bug

The game menu interface in Russian is displayed incorrectly and inconveniently. When you go to Unciv and click create a new game, the columns for choosing parameters: basic set of rules, difficulty, game speed, initial era, as well as the minimum and maximum number of civilizations, city-states, begin to shift. You have to swipe your finger to the left to scroll the menu to the side. In this case, you must select the Russian interface language.
If you switch the menu language to English, this problem also appears, but not so much. This applies to the first two columns when setting up the game.

### Steps to Reproduce

1. Go to 'Game menu'
2. Click on 'Start new game'
3. Scroll down to 'Game and map option'
4. See the menu with a drop-down list and the sliders are shifted and you have to swipe to the left, see the full text

### Screenshots

![Screenshot_20240410_111124](https://github.com/yairm210/Unciv/assets/43754210/c7686164-f90f-4fc3-90ff-ecbe1aeb7dd5)
![Screenshot_20240410_111146](https://github.com/yairm210/Unciv/assets/43754210/9bff1f88-0f06-4df2-a32c-45b3b083879b)

### Operating System

Android

**Comment by yairm210** [comment]
Sounds like this can be solved with a shorter translation for min/max number of civilizations - any suggestions?

**Comment by lolafur** [comment]
> Sounds like this can be solved with a shorter translation for min/max number of civilizations - any suggestions?

I am grateful to you for consulting with me :) I am more used to relying on developers, they better understand how to fix the flaw. I think that a shorter translation of some settings would be the best solution to this problem

**Comment by lolafur** [comment]
> Translators often do not really search for the context, so in a way they're not to blame.
> 
> Possibilities:
> 
> * Comment these in templates, telling the xlator "prease keep as sholt as possibre" [1](#user-content-fn-1-9369d362a19e49e5f2a0eb47bb4350b3)
> * Additionally: Give the label a separately templated tooltip. Now it's possible to have "Max # Civs" on the label and "Upper limit to\nthe number of civilizations that\nwill be randomly chosen" as tooltip... Yesiknowmobile...
> 
> ## Footnotes
> 1. No disrespect meant. Got reminded of a chinese food chain having a bilingual menu - engrish on one side, rocar on the other. There were "spling lolls" on one side and - bingo - "loureaux plintemps" on the other. Bouffe excellente pour le bas prix. [↩](#user-content-fnref-1-9369d362a19e49e5f2a0eb47bb4350b3)

If this shortcoming cannot be corrected in any way, then it’s not scary :)
