### ISSUE TITLE
Feature request: Button to disband units in overview

### ISSUE THREAD

**Issue by Luke-Kitti** [yairm210/Unciv#11467]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I often needed to disband units to decrease the upkeep and earn more. But removing them one by one was a hassle, taking up extra time and requiring too many button clicks. I got to choose a unit on map, then click show more, then click disband, then click confirm.

### Desired Solution

I want to have a disband button in overview page for units tab. 

### Alternative Approaches

The disband button can be located after the unit name in that units tab

**Comment by SeventhM** [comment]
> Still possible on Android [with...](https://support.anker.com/s/)

Uhhh... Bad copy-paste?

**Comment by Luke-Kitti** [comment]
Now don't say "but! mobile!" - you didn't specify. Still possible on Android [with...](https://support.anker.com/s/). Anyway, no overview button, but way faster.

thanks for letting me know that I need to specify. Yes, it is on mobile. I checked out the link provided. As I understood, the solution is that I need to buy usb-c hub to connect to a keyboard to access those shortcut keys (del + enter), right?

**Comment by yairm210** [comment]
I think there is enough space to add a removal button, and I can definitely see the use case 🤔

**Comment by SeventhM** [comment]
> which button did I click?

Why not try to have the popup use similar logic to what's already there for upgrading units?

**Comment by tuvus** [comment]
We could also add the right click menu to the unit button on the units tab. This menu could then have a disband unit button so we aren't adding another column and can add more things to the menu later.
