### ISSUE TITLE
Function to disable mods

### ISSUE THREAD

**Issue by lolafur** [yairm210/Unciv#11479]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Adding the ability to disable unused mods in the game. It was necessary to prevent the user from constantly deleting and reinstalling the mod

### Desired Solution

You can add a convenient and at the same time small function to disable mods to the game. The idea is that usually, if you don't use a mod, you uninstall it. And when you need it, you install it again. To avoid constantly deleting and re-installing, you can create a function with which in the “Mods” section you can disable those mods that you do not use, but leave those that are used.

### Alternative Approaches

I don't see any alternatives to this function. Unless you leave everything as it is now in the game and don’t change anything

**Comment by yairm210** [comment]
Mods, by default, are *not used* when installed.
You pick mods when creating a game - mods you don't pick will not be used.
What am I missing here?
