### ISSUE TITLE
Wrong city-state shown in notification log after being destroyed

### ISSUE THREAD

**Issue by fincentxyz** [yairm210/Unciv#11486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.4

### Describe the bug

In one of my games Babylon attacked and destroyed the city-state of Belgrade. When Belgrade was destoryed, a notification appears saying the city-state of Kathmandu has been destroyed. Clicking on this notification points towards Belgrade.

The city-state of Kathmandu was already destroyed and puppeted earlier in the game by Babylon.

### Steps to Reproduce

1. Load the save file
2. Go to Belgrade in the top left corner of the map
3. Click next turn
4. Belgrade is destroyed, but the notification says Kathmandu is destroyed

### Link to save file

https://hastebin.com/share/mafawewapu.bash

### Operating System

Android

### Additional Information

Had to use a paste website because the save file is longer than 65536 characters.

**Comment by yairm210** [comment]
Wow! Can you please provide the autosave of the turn before, so we can debug how this happened?

**Comment by fincentxyz** [comment]
> Wow! Can you please provide the autosave of the turn before, so we can debug how this happened?

Ah crap, I do not have access to those autosaves anymore... I already started a new game, I guess they have been overwritten... I did not know providing a save more turns prior to a bug occuring is useful for debugging. I will remember this for the next time I submit a bug report!

I hope this save and bug report is still somewhat useful for now.

**Comment by fincentxyz** [comment]
> The notification is correct.
> 
> Load your save, go to diplomacy though the "Belgrade" city's menu -> Belgrade the City belongs to Kathmandu the Nation. How you managed to do that is another matter... Look at the replay: Border changes colour from turn 212 to turn 213 - Kathmandu the Nation conquered Belgrade then lost Kathmandu the City to Babylon on turn 253.
> 
> In other words: Not city destroyed but city-state destroyed - key wording. Should we rename City-States that happen to survive losing their Capital to maybe "Ex-Kathmandu"?[1](#user-content-fn-1-de04772a615dacdf63ccdb4bf3d2d90d)
> ## Footnotes
> 
>     1. Or patterned after "The ~Jo... pardon, -~ Artist Formerly Unknown As X"? [↩](#user-content-fnref-1-de04772a615dacdf63ccdb4bf3d2d90d)

Wow, great find! I did not know city-states could do that, haha.

**Comment by yairm210** [comment]
I'm definitely fine with it as-is, but having the city-state AI change the name to "new X" would be a cool Easter egg for this edge case

**Comment by yairm210** [comment]
Nonono change the city name!!
That's already built in and supported
