### ISSUE TITLE
Automated units and actions

### ISSUE THREAD

**Issue by airisama019** [yairm210/Unciv#11489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.5

### Describe the bug

1. when "worker has nothing to do", automated workers will just move back and forth and that's REALLY ANNOYING when barbarians are close.
2. Also, automated military units will sometimes just freeze and do nothing even when enemy units and barbarians are close by.
3. when I click "explore" some units will just "finished exploring" when they are not close enough to unexplored area.
4. when "auto assign city production" is enabled it will just make buildings even though I am at war.

Honestly, the way it's now this game feels unplayable when using this "automated" stuff.

### Steps to Reproduce

1. play the game

### Operating System

Linux

**Comment by yairm210** [comment]
1. Interesting, we'll see if the wander can get us within range of an enemy and avoid those, I thought that already happens
2. Please send an game save as an example
3. This is a performance trade off we're sticking to - it's not hard to send them manually to keep exploring elsewhere, and it is expensive performance wise
4. Being at war does not mean "build all the units", that's a very poor decision, AI wise. The AI takes your total unit power into account and only builds in appropriate cities. If you have an example of a game where you feel it should be building but isn't we can discuss further

**Comment by airisama019** [comment]
> 1. Interesting, we'll see if the wander can get us within range of an enemy and avoid those, I thought that already happens
> 2. Please send an game save as an example
> 3. This is a performance trade off we're sticking to - it's not hard to send them manually to keep exploring elsewhere, and it is expensive performance wise
> 4. Being at war does not mean "build all the units", that's a very poor decision, AI wise. The AI takes your total unit power into account and only builds in appropriate cities. If you have an example of a game where you feel it should be building but isn't we can discuss further

1. It does avoid it sometimes but that's less than 1/2 a chance; I've seen it on big cities with lots of workers, but on smaller ones, especially the starting ones it does not.
2. I'll play a game and then save right when it happens
3. ok, but I feel like this game doesn't use much ram so maybe it wouldn't matter
4. What is this unit power value even based on? as far as I could experience it will just build a lot weak units and stop when you have around 7-10; it doesn't seem to take into account if unit is upgraded or have promotion; if you have enough land units, then it won't build sea units and vice versa; Also when I was late game (around 400 turns) it will just keep building wonders and buildings when all my units were killed and there's only one left; This doesn't make any sense.

**Comment by airisama019** [comment]
2. there you go. It starts on turn 51 barbarian camp spawned right next to it but it just won't move for 4 turns.
![Screenshot_20240417-203218_Unciv](https://github.com/yairm210/Unciv/assets/155326638/00b75717-ff7d-4036-a792-47862356f33e)
[Siam - 55 turns.json](https://github.com/yairm210/Unciv/files/15018056/Siam.-.55.turns.json)

One day I was at war with more than 15 units and some of my archers refused to shoot enemies close by; spearman would just stand there 5 or 6 tiles away while other units died

**Comment by yairm210** [comment]
1. Solved
2. Cannot replicate, the game you provided works give in latest version?

**Comment by airisama019** [comment]
> 1. Solved
> 
>     2. Cannot replicate, the game you provided works give in latest version?

will start a new game and send it here if something breaks

**Comment by yairm210** [comment]
Automated units do escort settlers, though? Not sure what you mean

**Comment by airisama019** [comment]
> Automated units do escort settlers, though? Not sure what you mean

?? I played many games where settlers and great engineers would sprint off on their own and get taken by barbarians or enemy units.

But  I have seen "AI players" have their settlers escorted

**Comment by airisama019** [comment]
Another behavior I found is that I could just "stop automation" and start it again on next turn and that would "unfreeze" some units but not all of them.

**Comment by airisama019** [comment]
is there a time limit for a unit or city to decide what to do when I click "next turn"?
because if yes that would explain everything.

**Comment by airisama019** [comment]
> Automated units do escort settlers, though? Not sure what you mean

[Egypt - 55 turns.json](https://github.com/yairm210/Unciv/files/15111490/Egypt.-.55.turns.json)

![Screenshot_20240425-112332_Unciv](https://github.com/yairm210/Unciv/assets/155326638/d7cbaaff-f12e-468d-a5f5-5d67d4bb5092)

![Screenshot_20240425-112255_Unciv](https://github.com/yairm210/Unciv/assets/155326638/58db75ad-541d-4d2d-b0d8-d105d24f172e)

![Screenshot_20240425-111814_Unciv](https://github.com/yairm210/Unciv/assets/155326638/5c19b832-9be0-4300-9b0e-26d8d43b08a7)

This one was played on android.
If the neighboring city didn't clear the barbarian camp that settler would've been dead.
