### ISSUE TITLE
Workers don't build roads.

### ISSUE THREAD

**Issue by kesken1745** [yairm210/Unciv#11529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.8

### Describe the bug

I've been using the brave new world mod, and upon progressing to a certain point in the game where you'd expect the automated workers to gradually start connecting your cities, they either choose to sit idle or start working on some un-worked tile that's mostly useless. 

I have the option "auto-build-roads" enabled in the settings.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by yairm210** [comment]
Please provide a game save

**Comment by kesken1745** [comment]
How do I export a saved game?

**Comment by kesken1745** [comment]
[The Huns - 159 turns.json](https://github.com/yairm210/Unciv/files/15146219/The.Huns.-.159.turns.json)
