### ISSUE TITLE
"Open terrain" goes wrong

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.8

### Describe the bug

"[+15]% Strength <when fighting in [Open terrain] tiles>" get valid when this unit was on Hill tiles.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/114050365/1b233494-6459-499e-8bde-bf5d4367d93a)

### Operating System

Windows

**Comment by AutumnPizazz** [comment]
This unique alse appeared in Shock I, II and III
https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/Civ%20V%20-%20Gods%20%26%20Kings/UnitPromotions.json

**Comment by jahodovykolac** [comment]
Not only hills, it happens everywhere, sometimes even together with drill I think
