### ISSUE TITLE
I can't connect to multiplayer

### ISSUE THREAD

**Issue by Maksim3177** [yairm210/Unciv#11532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.7-patch1

### Describe the bug

I was playing with friends in multiplayer, and after a certain move I could not enter the game. The game displays an error message without the ability to make a move

### Screenshots

![IMG_20240428_154013_009](https://github.com/yairm210/Unciv/assets/168346370/47a65fbb-0ec7-4a6d-ba7c-f52a91a64ca1)

### Link to save file

3c4bf20f-02a0-42f6-ad08-1011cf27e97e 
This is our game id

### Operating System

Android

### Additional Information

I am China
my player id: 111154a5-0c51-4682-b86d-ec2625236047

**Comment by yairm210** [comment]
I can join it fine, I'll check if this is a bug that was since solved

**Comment by yairm210** [comment]
Hm nope, I don't get this on the version you're on, either
The best I can do for now is to make this error display more information so we can debug it...

**Comment by Maksim3177** [comment]
We have already been able to resolve the error. Although we have not found out the reason. Apparently, it was all because of my phone. My friends were able to enter the game from their devices and make a move. After this the error disappeared
