### ISSUE TITLE
Unable to decide what to do with a city

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#11530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.7-patch1

### Describe the bug

When conquering a city, I can no longer decide what to do with it, it happens either randomly or is decided like if I was an AI.

### Steps to Reproduce

1. Load the attached save (next message)
2. Conquer Nalaych
3. It gets puppeted without asking
4. Conquer Ghulaman
5. It starts getting razed without asking

### Operating System

Android

**Comment by jahodovykolac** [comment]
Well, seems that GitHub doesn't allow me to paste it even in a separate message, so I have no idea how to send the save

**Comment by AutumnPizazz** [comment]
You could upload it as a Onedrive doc or save it as *.txt to up here.

**Comment by yairm210** [comment]
@tuvus  This sounds like an "acting like it's automated" situation to me

**Comment by tuvus** [comment]
I know there are problems with capturing cities while automated, but usually the problem is they don't decide what to do.
I'll look into it once the file gets posted.

**Comment by tuvus** [comment]
Oh wait, I just encountered this myself.

**Comment by tuvus** [comment]
Aaaahhhh, it's another AutoPlay thing! The exact same style as with the city constructions.

**Comment by AutumnPizazz** [comment]
> Better. Or - zip

Aha, though I can read this without Translator but the Tran says zip as 闭嘴 - means SHUT UP in English.😂
