### ISSUE TITLE
Air units no longer show attack and move range

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#11544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9

### Describe the bug

When selecting an air unit, tiles in attack and move range are no longer coloured, only the target marks are still present

### Steps to Reproduce

See above

### Operating System

Android

**Comment by jahodovykolac** [comment]
Already tried all of that... active mods none, even tried deleting a recent one (and yes, it happens on all tilesets), nothing, and about the screenshot...
![Screenshot_20240501_141526_Unciv](https://github.com/yairm210/Unciv/assets/79529669/23594d71-fd96-461c-a91e-312360177a79)

It just isn't there, the red and blue covering. The description seems vague, but that's because there just isn't anything.

**Comment by Diraven8** [comment]
Also happening for me.  Only mods I have is Community Maps and Vanilla Music Pack

**Comment by jahodovykolac** [comment]
> Took me 20 minutes to get a test game to the point I could by air units. That's what attaching saved games is for.

I'm sorry, I was on mobile and would have to figure out how to create .txt file there (_why_, it's literally the simplest type of file, why can't they create one), or find something like pastebin which wouldn't require login for one paste... you can see why I try to avoid it, but I'll try to find a way for next time (good old times when you could just paste it here...)

> 'they were painted and then some gremlin stole them microseconds later'

Noooooo, not the paint stealing gremlins!

**Comment by yairm210** [comment]
This change was to make the entire screen color according to borders, when on Mac zoom out 
If it's causing problems you can just revert the entire PR and we'll rethink it

**Comment by yairm210** [comment]
The colors will remain forever and that's not what we want on zoom in
