### ISSUE TITLE
Translating site bug

### ISSUE THREAD

**Issue by baHHbaSh** [yairm210/Unciv#11543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9

### Describe the bug

site https://yairm210.github.io/Unciv/Translating/ return 404

### Steps to Reproduce

open https://yairm210.github.io/Unciv/Translating/

### Operating System

Windows

**Comment by yairm210** [comment]
The question is, do we reference the old link anywhere? 
If yes we should fix, if no we should close

**Comment by baHHbaSh** [comment]
MainMenu->Settings->language->Button higher language
