### ISSUE TITLE
Declaration of war bug

### ISSUE THREAD

**Issue by lolafur** [yairm210/Unciv#11540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9

### Describe the bug

I've had strange experiences in the game where, for example, Kuala Lumpur joined America in the war against  Baghdad. And then immediately after this message, America declares war on Kuala Lumpur itself. Looks weird and confusing.
In this case, it wasn’t me who played, the bots played, and I was a spectator. This bug appeared since version 4.11.7

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![Screenshot_20240430_162603](https://github.com/yairm210/Unciv/assets/43754210/52a10a87-b62a-4120-b464-fa180f2ce78a)
![Screenshot_20240430_162636](https://github.com/yairm210/Unciv/assets/43754210/046b420c-9f1a-4e54-b39e-c857c74e34ad)

### Operating System

Android

**Comment by tuvus** [comment]
Can you give a save file? I'll see when I can look into it.

**Comment by lolafur** [comment]
> Can you give a save file? I'll see when I can look into it.

I've never done this before :) How to do this?

**Comment by tuvus** [comment]
The order of events is reversed because thats how we display the notification log.
I think this is the right description of the events:
- America declares war on KL
- Baghdad joins America against KL
- Tripoli joins America against KL

So I must have reversed the Civilization that joins America and the Civ they are fighting against.

**Comment by tuvus** [comment]
Ahhh, I see. I forgot that I have three types of join wars, WarType.DefensivePactWar, WarType.CityStateAllianceWar, WarType.JoinWar. 
CityStateAllianceWar and JoinWar should have the same notification types and I grouped CityStateAllianceWar with DefensivePactWar with an if-else statement.

**Comment by lolafur** [comment]
> Ahhh, I see. I forgot that I have three types of join wars, WarType.DefensivePactWar, WarType.CityStateAllianceWar, WarType.JoinWar. CityStateAllianceWar and JoinWar should have the same notification types and I grouped CityStateAllianceWar with DefensivePactWar with an if-else statement.

I hope this small flaw will be corrected in the next update :))

**Comment by jahodovykolac** [comment]
I have encountered the same problem, and I see that the civ that joins and the target are in fact switched.

Here's a save file (if it works) - I have Allied with Singapore, so they joined me against Persia, but the notification says Persia joined me against Singapore
https://pastebin.com/Zz2cPPTw

![Screenshot_20240505_140035_Unciv](https://github.com/yairm210/Unciv/assets/79529669/0f248098-aa22-498b-8f67-6e65ceb114f4)

**Comment by tuvus** [comment]
The fix is in the next version 4.11.10.
