### ISSUE TITLE
Feature INQUIRY:  AI's predisposition on SAM's

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#11550]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

The AI seems to be quite predisposed to building SAM's. I'm wondering why - what is the logic?

In my current game, the Iroquois have been a super power since the 1800's, finishing off Future Tech way early. However, their posture has been entirely non-aggressive pretty much the entire 2nd half of this game. My civ has been the underdog scrapping up advancement under perpetual bullying by the Maya, then Carthage decided to use my edge territory for weapons testing, which is quite rude of them, so I don't play my music too loud and keep to my side of the yard.

Yet, the Iroquois absolutely dominates this game. This is behavior I haven't seen before, and I'm not complaining either because the gameplay felt more balanced, more time to deal with opponents within my capacity to fend off, incrementally advance based on executing devised strategy. In the past, once one civ sees you're weak, a pile-on begins and now there's 7 piranha civs tearing you up with no tactical possibility of fending them off.

To note in this game, the Z2 map is effectively delineated into large areas that partition against each other. The Iroquois are kitty-corner to my civ, on an adjacent continent, insulated by mountains. The best attack plan would be shore front invasion. Meanwhile, they sit idle, building SAM after SAM. Look at the screenshot here. These devhax fairies were deployed to see what the AI was up to. Movement circles are shown blocked demonstrating total density of units. Nearly all SAM's.

My thought on this is that the AI has taken a defensive position recognizing the danger of air strike units like Cruise Missiles and Bunker Busters. Very dangerous and destructive. Is it that the AI is unable to conceive both an offense and defense, or is this a waiting game to see who's an actual threat? Becoming the superpower so early, perhaps they took on a missile defense strategy. They're not trading either making me more suspicious there might be something glitchy going on. Maybe not. If any coders have an opportunity to contemplate and analyze the situation, I'd be interested in the outcome. 

### Desired Solution

A review of the Iroquois AI logic if the above description leads to some potential AI fault. 

### Alternative Approaches

Are they content with their ground forces? Do they have sufficient air support? Maybe they're leaning into a naval perimeter? 

### Additional Context

![Screenshot_20240502_113047](https://github.com/yairm210/Unciv/assets/119975434/8b11e367-d03a-42f0-ad17-db92f7e51b0e)
[Iroquois AI review.txt](https://github.com/yairm210/Unciv/files/15191739/Iroquois.AI.review.txt)

**Comment by tuvus** [comment]
An interesting story. This problem should probably be added to #11264.
I have observed this before, could it be random chance that they value the SAM more than other units? Or is there some sort of logical bug?
Either way we will probably have to look at this after we rework the way the AI decides which units to build.
