### ISSUE TITLE
Culture order error in declear war notification.

### ISSUE THREAD

**Issue by Orange23333** [yairm210/Unciv#11574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9

### Describe the bug

As you can see, in screenshot the notification is wrong. It should be `Sydney has joined us in the war against Carthage`.

### Steps to Reproduce

1. Open save named "before-war". If everything is okay, you will play the role of Spain when the save is loaded.
2. Declear war on Carthage.
3. Watch notification on the left top.

### Screenshots

![unciv_bug_report_20240509](https://github.com/yairm210/Unciv/assets/18095289/badd51ab-1be1-4ab8-a656-0d7f05e8193c)

### Link to save file

A tiny playground for test this bug: [before-war.zip](https://github.com/yairm210/Unciv/files/15264151/before-war.zip).

### Operating System

Windows

**Comment by tuvus** [comment]
This was fixed in 4.11.10 by #11541 please update to the latest version.
