### ISSUE TITLE
Unit automation uses defunct `UnitActionType.StartGoldenAge`

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11576]
### Game Version

current master from source

### Describe the bug

[This line](https://github.com/yairm210/Unciv/blob/6a61a71c367847395f37ab7c728f1123d30d0cc9/core/src/com/unciv/logic/automation/unit/CivilianUnitAutomation.kt#L117) - the actual UnitActionType used for starting golden ages is now TriggerUnique for the OneTimeEnterGoldenAgeTurns UniqueType.

Actually, all three objects named `StartGoldenAge` are dead - UnitAction, KeyboardBinding and UniqueType - and have no implementation.

### Steps to Reproduce

Read source and use Ctrl-Shift-F and Alt-F7 extensively?

I have no idea hot to coax the AI to run into that line - but it's definitely not clean.

### Additional Information

Replacing that `if` with
```kotlin
            if (!improvementCanBePlacedEventually) {
                val unique = unit.getMatchingUniques(UniqueType.OneTimeEnterGoldenAgeTurns).firstOrNull()
                if (unique != null) UniqueTriggerActivation.triggerUnique(unique, unit)
            }
```
is obviously bull - that's a fallback within specialized UniqueType.ConstructImprovementInstantly AI code. But civilian AI has absolutely nothing elsewhere I can find for the ubiquitous starting golden ages capability of those Great People... sounds like this should be included in some higher-level AI overhaul. @tuvus - specialist to the rescue?? Consider - why is there no fuzzy logic for automateCivilianUnit that compares estimated values? It's all if I can do - done - return. Sounds less than optimally clever.

**Comment by yairm210** [comment]
The unique is already deprecated
Agree that the unit action should be killed since it should have 0 use
