### ISSUE TITLE
Mods broken since 4.11.12

### ISSUE THREAD

**Issue by richcb** [yairm210/Unciv#11613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.12

### Describe the bug

Since updating to game version 4.11.12, my mods have disappeared from the mod menu. Attempting to download mods, I receive the error "Could not download mod list". Attempting to download directly from a url did not work either. 

Rolling back to 4.11.11 did not resolve the issue. 

### Steps to Reproduce

1. Install 4.11.12
2. Click on 'Mods' 
3. Receive error message

### Screenshots

![Screenshot_20240516_175142_Unciv](https://github.com/yairm210/Unciv/assets/127277772/26692f90-e6f5-4c82-b951-adabde804042)

### Operating System

Android

**Comment by yairm210** [comment]
I could not replicate this either
We could make these failures copy the stack trace to clipboard for debugging... would be interesting to see

**Comment by richcb** [comment]
I installed from the compiled apk available to download here on github via releases. I don't believe mods were corrupted, as they were working fine prior to version update. (Rekmod, Absolute Units, Absolute Units XL)

>Do you have root file manager, or an Android Studio Device Explorer connection, or maybe logcat access?

I don't have a rooted device or logcat, AFAIK. I can try a total wipe and clean install. I will come back with results

**Comment by richcb** [comment]
I did not mean to mark closed and don't seem to have an option to undo. I will attempt clean install and return
