### ISSUE TITLE
Atlas and game.png file generation should make exceptions accessible to a Modder

### ISSUE THREAD

**Issue by RealBamboolord** [yairm210/Unciv#11618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.13 (Build 997)

### Describe the bug

https://github.com/RealBamboolord/Hadrodia-RP-game
When downloading this mod, the game isn't able to regenerate the atlas and png files to display icons and sprites. When deleting the existing game.png, game.atlas and atlases.json files, the game won't generate them new when I restart the game.

### Steps to Reproduce

1. Download the mod using the link provided above
2. Go to mods folder and delete the existing atlases.json, game.png and game.atlas files
3. Restart the game
4. See that the files didn't regenerate

### Operating System

Windows

### Additional Information

I have checked all Image file to make sure they are all .png files and tried to figure out which files where causing the error, although I was unsuccessful. Individually deleting the Images subfolders didn't fix the issue. I would therefor like to know what file is causing the issue or what the problem seems to be.

**Comment by RealBamboolord** [comment]
Thanks SomeTrog

**Comment by yairm210** [comment]
That's some mindbending stuff
