### ISSUE TITLE
Feature Request: Support for Civ4-like non-permanent civics

### ISSUE THREAD

**Issue by PLynx01** [yairm210/Unciv#11635]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

The Civ IV mod currently lacks the non-permanent civics present in the original Civ 4. Making the policy categories for non-permanent policies is a relatively easy task. It requires the cancellation of other policies from the same category after adopting one.

The biggest problem is the AI support for these mechanic.

### Desired Solution

I would like to add a new Policies.json attribute. The Policy Type.

The allowed values would be:
"Civ5" (Default value)
"Civ4" (Denotes Civ4-like non-permanent radio button policy branch)
"Civ6" (Denotes the Civ6-like idea tree)

The Civ4 policies must be accompanied with upkeep costs and AI priorities.

The Civ6 idea tree must contain AI priorities for each element. The governments and policy cards can be implemented as buildings.

### Alternative Approaches

Make a separate ruleset .json files for Civ4 and Civ6-like policies.

### Additional Context

For mods based on classic Civilization games, which used the government systems, Civ4 system can be used.

**Comment by yairm210** [comment]
This should all be done with uniques.
AI priority for policies should be independent of the type of policy, and that can certainly be modified by personality

**Comment by PLynx01** [comment]
> This should all be done with uniques. AI priority for policies should be independent of the type of policy, and that can certainly be modified by personality

What do you exactly have on your mind?
Radio Button Policies can be done this way:

Remove [Government branch]
Adopt [Universal Suffrage]

What about AI priorities? Can you write some pseudocode to explain me your idea?

**Comment by yairm210** [comment]
I'm saying that "policy type" doesn't help us at all, and is unnecessary, and if we want special treatment it should be behind a unique

What's really needed is AI value judgement which is independent of "what type of unique"

**Comment by PLynx01** [comment]
> I'm saying that "policy type" doesn't help us at all, and is unnecessary, and if we want special treatment it should be behind a unique
> 
> What's really needed is AI value judgement which is independent of "what type of unique"

The "Policy Type" attribute applies to policy branches, not individual policies.

**Comment by yairm210** [comment]
So what? Policy branches also have uniques, same thing
We need to think in terms of *what functionality* things have, not in terms of *what game is this similar to*
Maybe Civ IV is comprised of several different things, and so is VI? Then we can mix and match elements

**Comment by PLynx01** [comment]
> So what? Policy branches also have uniques, same thing

So, in that case, can mark a policy branch as exclusive (or radio button), either using attribute or unique?

**Comment by PLynx01** [comment]
> > So what? Policy branches also have uniques, same thing
> 
> So, in that case, can I mark a policy branch as exclusive (or radio button), either using attribute or unique?
> 
> That would be useful for making Civ4-like civics, or a single government selection, like in Civ 1, 2 and 3

**Comment by PLynx01** [comment]
@yairm210 @SomeTroglodyte 

Can I try to implement this by myself?

I need to alter Policy Manager and Next Turn automation.

**Comment by PLynx01** [comment]
> 3 sounds like "[-1 Gold]" unique on policy 4 sounds like "only available when" 2 sounds like a generally useful unique, "[relativeAmount] weight for AI, modified by [personality] personality" - @tuvus is the expert here

My remarks:
- Civic upkeep is not fixed, but dependent on number of cities, units, improvements, buildings, population etc.
- AI priorities should be obviously linked to Personalities. But should they be defined by modders themselves or evaluated automatically? I believe the former should be recommended, and the latter should be a fallback.
