### ISSUE TITLE
Feature Request: Event Choice Automation

### ISSUE THREAD

**Issue by PLynx01** [yairm210/Unciv#11698]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Despite the fact that events were added some time ago, they are still not used widely. As for now, AI chooses the Event Choices randomly, without evaluating them.

### Related Issue Links

#11276

### Desired Solution

I think that we should opt for the automatic evaluation of choices, to make the AI choose the best option (or sometimes the least bad). The choice priorities will be of course modified by AI personality.

### Alternative Approaches

If automatic evaluation is not really possible, we should add the possibility for modders to manually set the priorities.

That is particularly relevant in case of events that result in new buildings, also containing uniques.

### Additional Context

@tuvus It's your specialization, so you know the best how to implement that feature.

**Comment by PLynx01** [comment]
> This effectively means evaluating *all* triggers to some common ground (say "lump sum of gold")
> Very complicated task

Let's ask @tuvus what does he think about this.

**Comment by tuvus** [comment]
I don't think there is a general algorithm to allow the AI to accurately decide events.

Similar to your manual Idea, I propose giving the power to the modders, since they are the ones creating the event.

My proposition is to make the chance moddable. When the AI opens an event to decide which one to choose, it will use conditionals along with a new "bonus [amount]% of choosing this option" unique (or something similar). Then based on the sum of these unique the AI will choose one of the options.

Getting the personality values of the Civ will probably become a unique eventually.

**Comment by PLynx01** [comment]
> I don't think there is a general algorithm to allow the AI to accurately decide events.
> 
> Similar to your manual Idea, I propose giving the power to the modders, since they are the ones creating the event.
> 
> My proposition is to make the chance moddable. When the AI opens an event to decide which one to choose, it will use conditionals along with a new "bonus [amount]% of choosing this option" unique (or something similar). Then based on the sum of these unique the AI will choose one of the options.
> 
> Getting the personality values of the Civ will probably become a unique eventually.

I previously thought about priorities similar to these determining the choice of Social Policies, but now I believe your idea is more flexible and versalite, as it will be compatible with most conditionals.

Example:

`Bonus [+100]% of choosing this option <when at war>`

I approve your idea, let's ask other developers for their opinion.

**Comment by yairm210** [comment]
@tuvus 
Nice!! I think that's a fantastic idea 😸
