### ISSUE TITLE
Add Situation Feature from Stellaris

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11691]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Inspired by the Stellaris game, I would like to add a Situation feature.
1. Add a new Situations.json file to define Situations.
2. The Situation is represented as a long integer, constrained by maxSituationPoints and minSituationPoints.
3. Situations are categorized into national and global, determined by the isNationalAndNotGlobal constraint (Boolean value).
4. Add trigger-based unique, such as "Change [±amount] points for [SituationName]".
5. Add a new template for the overview button to display Situations, with an option to change the display to the world screen in the settings.
I believe Situations are different from Resources, at least for players who are not familiar with the game.
PLEASE! PLEASE! PLEASE!

### Desired Solution

See above.

### Alternative Approaches

See above.

**Comment by AutumnPizazz** [comment]
It's about #3242.

**Comment by AutumnPizazz** [comment]
like this:

_[
    {
        "name":"example_situation1",
        "type":"global",//only available for "global", "national" and "urban"
        "Range":[-100,200],
        "uniques":[
            "Nullifies [Science] [in all cities] <when below [0] [example_situation1]>",
            "Nullifies [Culture] [in all cities] <when below [0] [example_situation1]>",
            "[+1 Production] [in all cities] <when between [0] and [100] [example_situation1]>",
            "[+50]% [Science] <when above [100] [example_situation1]>",
            "[+50]% [Culture] <when above [100] [example_situation1]>",
            "Change [+1] [example_situation1] <when above [0] [Happiness]>",
            "Change [-1] [example_situation1] <upon being defeated a [Warrior] unit>",
            "Heal this unit by [50] HP <by changing [-10] [example_situation1]>",//this should be in Units.json
        ]
    }
]_

BUT what I wanna emphasize is to 'Add a new template for the overview button to display Situations, with an option to change the display to the world screen in the settings.'

**Comment by yairm210** [comment]
Okay, then yeah, this is really just another scoped resource
The only new "fields" would be the range, and that can be within the unique defining the resource as a "situation" or however we'd want to call this

The advantages of *not* creating a new file are numerous:
- Conditionals, triggers for adding/removing - all already exist, so we get them "for free"
- New files are a hassle - means adding not only loading but validity checks, typings, etc
- Less things to have to wrap your head around as a modder - goodness knows we have a lot of stuff already!

Regarding UI, that'll need special attention any way we decide to save the data, so doesn't make much of a difference

**Comment by AutumnPizazz** [comment]
Not stellarium, but Paradox's [Stellaris](https://stellaris.paradoxwikis.com/Stellaris_Wiki)

**Comment by AutumnPizazz** [comment]
This should be open now so I send this sentence.

**Comment by yairm210** [comment]
I really don't think so. This is something that should be done with stockpiled resources, which are already handled well throughout the game. There's no reason to add an extra "resource-like" object when one already exists.
If you encounter any specific problems with that implementation, tell me and we can discuss it

**Comment by AutumnPizazz** [comment]
I cannot describe it clearly, just see https://stellaris.paradoxwikis.com/Situations

**Comment by yairm210** [comment]
Now I'm even more convinced it's just stockpiled resources + events

**Comment by AutumnPizazz** [comment]
Well, I mean I wanna make a new UI for SITUATION like that web, to be on World Screen with a Progress Bar.
