### ISSUE TITLE
Feature request: bị lỗi ko chơi đc ở turn tiếp theo

### ISSUE THREAD

**Issue by key1340** [yairm210/Unciv#11709]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

![Screenshot_2024-06-08-21-26-26-707_com unciv app](https://github.com/yairm210/Unciv/assets/172126430/13e1bd45-0be9-4037-9ad6-2a2c4e89bb3b)

### Related Issue Links

![Screenshot_2024-06-08-21-26-26-707_com unciv app](https://github.com/yairm210/Unciv/assets/172126430/282d46ef-72e2-4607-ab99-a058857048a1)

### Desired Solution

![Screenshot_2024-06-08-21-26-26-707_com unciv app](https://github.com/yairm210/Unciv/assets/172126430/0fe539c1-b793-43d7-9718-5f7df88a1813)

### Alternative Approaches

![Screenshot_2024-06-08-21-26-26-707_com unciv app](https://github.com/yairm210/Unciv/assets/172126430/0b5253d7-a290-4673-a780-aae7728da41f)

### Additional Context

![Screenshot_2024-06-08-21-26-26-707_com unciv app](https://github.com/yairm210/Unciv/assets/172126430/ae6b5c20-104c-4b90-9e1b-31f852e35f2c)

**Comment by yairm210** [comment]
I'm assuming this is one of the problems we've already solves, as it's a crashing bug
