### ISSUE TITLE
Improve Building UI

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11713]
![bd56f5b8dc99bd2942bd96884544419c](https://github.com/yairm210/Unciv/assets/114050365/29cddb99-0442-4438-9885-f703ecafd6e0)
<img width="1280" alt="d433926eff2af6634c5adf5e29d96473" src="https://github.com/yairm210/Unciv/assets/114050365/3a3238ce-d824-44a6-a59f-7ac848019a9b">

This will be a revolutionary improvement, because it will greatly expand the editability of modules to buildings, especially when players need to find a specific building in a city with a large number of buildings.

**Comment by AutumnPizazz** [comment]
![image](https://github.com/yairm210/Unciv/assets/114050365/ce4ba1b7-c7d3-4623-9c49-5ba039d70f7e)
And we would add two properties for Buildings.json.

**Comment by kostia1st** [comment]
Maybe it's just simpler and more convenient to add a "Search" input box somewhere? Which would look for everything eventually, but we could start with just buildings for now

**Comment by AutumnPizazz** [comment]
No, no, no. The main reason I suggested this is that my mod may allow a city to have a large number of buildings, and players need to keep track of the number and types of buildings in each city, especially the capital, in real time (these buildings could be called global modifiers here). In the UI I envisioned, players can easily view each building instead of searching for a specific one.

**Comment by AutumnPizazz** [comment]
I need it, QAQ, help me plz. @SomeTroglodyte
