### ISSUE TITLE
Feature Request: Scenario Nation Selector

### ISSUE THREAD

**Issue by PLynx01** [yairm210/Unciv#11724]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Despite scenarios were added some time ago, their development is very slow. That's because it is not currently possible to conveniently select the Nation to play as.

### Desired Solution

I would like to see the "Select Nation" panel in the scenario screen, similar to this from New Game screen.

### Alternative Approaches

Alternatively, we can make it easier to choose a nation after loading the scenario, something like EU4.

### Additional Context

For desired solution, we need to make asynchronous function that will obtain a list of playable civilizations from the scenario or save game.

**Comment by yairm210** [comment]
Already done as part of 'opening scenario from new game screen'
