### ISSUE TITLE
Fail to create a new game after choosing "Tiny world size"

### ISSUE THREAD

**Issue by Zooms233** [yairm210/Unciv#11730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.19(Build 1005)

### Describe the bug

As same as title

### Steps to Reproduce

1. Go to 'Start a new game'
2. Choose 'Tiny' in 'World size'
3. Keep number of civilisation default value(4)
4. Click 'Start game!'' and see the error
5. Though change the ’World size’ to Medium, error remains.

### Screenshots

![error](https://github.com/yairm210/Unciv/assets/129411234/4f4433c0-34e6-4881-9167-0b0b66178194)

### Operating System

Windows

### Additional Information

This error occurs on Android,too.
![Error on Android](https://github.com/yairm210/Unciv/assets/129411234/be90eb93-b12c-4c30-a05b-2d6d2c9cb645)

**Comment by tuvus** [comment]
I have located the error. The fix isn't hard but will take some design thinking.

**Comment by tuvus** [comment]
Done! Thanks for reporting this!

**Comment by AutumnPizazz** [comment]
It also happens when choosing more than 0 city-states.
