### ISSUE TITLE
Possible typo: rigg

### ISSUE THREAD

**Issue by J0anJosep** [yairm210/Unciv#11748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

master, 2024-06-14

### Describe the bug

This string:
Spies set in city-states will try to rigg the elections in order to gain influence and reduce the influence of other civilizations. Only one spy partaking in rigging the election can win.
Has a typo. rigg->rig

(Not a bug; just a typo)
(I've search for any duplicate, but I didn't find it)

### Steps to Reproduce

-

### Screenshots

-

### Link to save file

-

### Operating System

Linux

### Additional Information

-

**Comment by tuvus** [comment]
Whoops. If you want to fix it and make a PR that would be greatly appreciated!
