### ISSUE TITLE
NullPointerException on getDiplomacyManager()

### ISSUE THREAD

**Issue by mouillerart** [yairm210/Unciv#11768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.0

### Describe the bug

Hi there, noticed a game crash with latest version
NullPointerException at com.unciv.logic.civilization.Civilization.getDiplomacyManager(Civilization.kt:324)
What's missing?

### Steps to Reproduce

1. Install mods
2. Load savefile
3. Click on "next turn"

### Link to save file

[The Empire.zip](https://github.com/user-attachments/files/15858661/The.Empire.zip)

### Operating System

Windows

### Additional Information

**Platform:** Desktop
**Version:** 4.12.0 (Build 1007)
**Rulesets:** [Civ V - Vanilla, Tyretes Tileset, Orbis Terrarum for Unciv, Community Maps, Civ V Leader portraits, Civ6 mod, Epic of Fantasy, Civ6 Tileset, Alpha Frontier, Unciv IV mod, UncivWarhammer, Civ V - Gods & Kings, 5Hex Tileset, Fantasia]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

**Comment by tuvus** [comment]
Can you send the full stack trace?

**Comment by tuvus** [comment]
A patch should be going through to fix this, please update when you can.

**Comment by mouillerart** [comment]
The patch corrects the bug. Thank you!
