### ISSUE TITLE
Build lists on city screen load extremely slow

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#11775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

version 4.12.0-patch1

### Describe the bug

When I go to the city screen the list of units and buildings on the left load very slowly.  Sometimes locking up the game for 30 seconds or more.  This was not happening yesterday (I assume an update was released since)

### Steps to Reproduce

1. Click on an owned city in the map to open the city screen.
2. Note that it takes a while for the units and buildings list on the left to populate.

### Operating System

Android

### Additional Information

Seems to take longer the more buildings are in the list?  Like for new cities where nothing has been built yet it takes the longest.  Not entirely sure this is the pattern though.

**Comment by hackedpassword** [comment]
Seen this behavior also with 4.12.0.1

**Comment by Monokiro** [comment]
So queuing anything is also that slow, because it is rebuilding the list. In the case of dozens of constructible items and hundreds of cities the issue became dramatic.

**Comment by hackedpassword** [comment]
The fix didn't work for me, gave it a couple releases, still continues. 

Current version: 4.12.2.1 build 1011


https://github.com/yairm210/Unciv/assets/119975434/9d9a46f3-bd00-484f-83bc-3b1cb9552853

**Comment by hackedpassword** [comment]
4.12.3 solved the issue.
