### ISSUE TITLE
Cannot load save

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#11774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

build 1008 - 4.12.0.1

### Describe the bug

![image](https://github.com/yairm210/Unciv/assets/119975434/d728f46d-9400-41f9-8c03-e34103919f12)

### Steps to Reproduce

Manual load of an ongoing game after updating the Unciv apk. 

### Operating System

Android

### Additional Information

If you guys need a save game or anything else let me know.

**Comment by yairm210** [comment]
What?!
Yes, please provide the game save! 
Super weird!

**Comment by hackedpassword** [comment]
Had to pull this file out with total commander since it won't load. The other saves seem to be fine. 

Note I updated from 4.12.0.0 - pretty certain. 

<details><summary>Savegame</summary>
<p>

[France - 339 turns.txt](https://github.com/user-attachments/files/15873504/France.-.339.turns.txt)

</p>
</details>

<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by hackedpassword** [comment]
Ugh accidentally touched close comment. 

Anyway including the previous save. That will give something to compare to. 

<details><summary>Details</summary>
<p>

[France - 338 turns.txt](https://github.com/user-attachments/files/15873605/France.-.338.turns.txt)

</p>
</details>

**Comment by yairm210** [comment]
@SomeTroglodyte 
LastSeenImprovement.readOldFormat is getting a jsonData with real data, but `jsonData.get("entries")` is null
Putting a breakpoint on LastSeenImprovement.kt:46 and loading the save gets you to the interesting info

**Comment by hackedpassword** [comment]
In the update period, only sprites changed, no json. [history](https://github.com/hackedpassword/Z2/commits)

**Comment by hackedpassword** [comment]
Running android 12, galaxy s10, ATT model, kernel 4.14.190

Everything stock on this phone nothing fancy no hax/rooting etc.

The save did not cross platforms.

Let me know if there's anything missing.

**Comment by hackedpassword** [comment]
Could be a one-off, perhaps a unique artifact inclusive of your recent save size reduction and solar activity. Since no one else is reporting, I'd say neutrino decay bursts have subsided.

Haven't seen the issue reproduce here either since, all load/save actions seem normal.

btw what did the faulty save produce as a wrong version/build value out of curiosity?
