### ISSUE TITLE
Feature request: Add background music or onomatopoeia

### ISSUE THREAD

**Issue by JuanDavid45composer** [yairm210/Unciv#11770]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I think more music needs to be added to the game. For example, when a nation declares war on you, sound trumpets. I can support, have created several example compositions and am able to modify and compose works as needed.
Declared War:

https://github.com/yairm210/Unciv/assets/172998353/355bc7df-af53-4f77-baaf-c7899c73ab94

Peace treaty:

https://github.com/yairm210/Unciv/assets/172998353/e424983d-5077-4ac9-abc1-022ee8737f84

### Desired Solution

More music, onomatopoeia, and sound effects should be added to the game to improve its atmosphere.

### Alternative Approaches

Improving the sound section of the game would make it much better than it already is. Although it is not essential, I and other people would like it to be done.

**Comment by yairm210** [comment]
@SomeTroglodyte This looks to me like your domain :)

**Comment by JuanDavid45composer** [comment]
Yeah!, thank you, I'm a composer.

**Comment by JuanDavid45composer** [comment]
That's for mods, not the base game (like I want). Although the information you gave me was useful, thank you.

**Comment by JuanDavid45composer** [comment]
I think you're right, I still hope that one day the game comes with its own music, that would be amazing. Thanks for answering!
