### ISSUE TITLE
The Great People Improvements should connect strategic resources to empire.

### ISSUE THREAD

**Issue by Emirrian** [yairm210/UnCiv#1177]
The Great People Improvements should connect strategic resources to empire. As I remember it works this way in original Civ5.

**Comment by Emirrian** [comment]
Also, it may works the same for Luxury resources, but I am no sure about it.

**Comment by yairm210** [comment]
https://gaming.stackexchange.com/questions/53155/do-manufactories-and-customs-houses-sacrifice-the-strategic-or-luxury-resources

Apparently so, thanks!
