### ISSUE TITLE
"Removes removable features when built" doesn't remove terrain fetures when used in non-Great Improvement

### ISSUE THREAD

**Issue by LittlePuny** [yairm210/Unciv#11783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.18-patch1

### Describe the bug

Using the following improvement for a mod:

{
		"name": "Scorcher",
		"terrainsCanBeBuiltOn": ["Forest","Jungle","Marsh"],
		"turnsToBuild": 1,
		"uniques": ["Removes removable features when built","Will be replaced by automated workers"],
		"techRequired": "Agriculture"
	},

When the improvement is built, forest tile stays with the improvement. 

Expected behavior should be improvement removes the terrain feature and then removes itself due to lack of terrain it can be built on. 

### Steps to Reproduce

1. copy the code above to TileImprovements.json
2. build the improvement ingame

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/101736256/d91609bb-e988-4d2b-a49f-2442b0d6e7fc)

### Operating System

Windows

**Comment by yairm210** [comment]
The reason it's not removed is because the improvement specifically specifies that they *can* coexist, in order to avoid situations such as this.

In any case, even if we do change this, having the improvement remove the feature will not cause it to be removed.
This is a clear case of #3242
