### ISSUE TITLE
Nukes and Carriers

### ISSUE THREAD

**Issue by Emirrian** [yairm210/Unciv#1178]
What about nuclear bombs? It is part of Civ since 1991. I think we are losing a big part of fun without it. Will you add nuclear weapons to UnCiv? Also, I would like to have aircraft carriers. On large maps it is sometime hard to deliver air units over seas.

- [ ] Nuclear weapons
- [ ] Aircraft carriers

**Comment by ninjatao** [comment]
Implementing nuclear missile.

**Comment by yairm210** [comment]
Nukes are done
Carriers moved to #663
