### ISSUE TITLE
Some problems to solve

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#1179]
- [ ] When you're selecting a civilization, you should be able to close the Civ select window instead of the main menu screen, forcing yourself to close it and return to the game
- [ ] Owned Cities need a growth bar, to see in how many turn the City will grow
- [ ] Cities owned by City-States should have an Influence bar to see what are their relations with you.
- [ ] We also need a Random Civ choice in the Civ select window
- [ ] Add the option of toggling off Civilizations' special powers
- [ ] Add the option of toggling off Civilizations' unique units/building/improvements

**Comment by yairm210** [comment]
Only the first and fourth are problems. The rest are feature requests.

**Comment by Smashfanful** [comment]
Alright, just wanted to keep in mind of the community

**Comment by yairm210** [comment]
Moving to #663 because this is a wishlist.
