### ISSUE TITLE
"pick now" allows scheduling improvements without required techs

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#11798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.1

### Describe the bug

The "pick now" button allows scheduling improvements that we have not researched techs for yet

### Steps to Reproduce

1. Research calendar and not mining
2. Send worker to forest + silk tile, click "pick now" on plantation 

Awaiting user save file for quick fix

**Comment by tuvus** [comment]
I also found this but forgot to report it.
