### ISSUE TITLE
My unit does not gain experience when attacking in no-one's land

### ISSUE THREAD

**Issue by kostia1st** [yairm210/Unciv#11819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.1

### Describe the bug

Trebuchet does not receive experience when attacking a barbarian unit in no-one's land. If that's by design, then maybe that should be present in the civilopedia somewhere. Maybe it is, and I just don't know where to look for it.

### Steps to Reproduce

- make sure your trebuchet stands within a tile of no ownership
- make sure your trebuchet's target barbarian stands on a tile of no ownership
- attack the target with the trebuchet
AR: no experience gained by the trebuchet
ER: trebuchet gains some experience

### Screenshots

![r1x55s0k8a](https://github.com/yairm210/Unciv/assets/9264460/48680477-9f1a-448c-9c91-fa3913a49beb)

### Operating System

Windows

### Additional Information

Could not copy the save game to clipboard, I guess that's another issue

![Unciv_g4aLpHP5dK](https://github.com/yairm210/Unciv/assets/9264460/5c9c60b0-0c10-4f42-87e5-ebec70c4fdf4)

**Comment by kostia1st** [comment]
Just checked, a horseman in that same game does not gain any experience either, attacking the same barbarian unit.

**Comment by kostia1st** [comment]
Just found this comment  somewhere

> Your units stop gaining xp from barbs after their second promotions.

If that's the case, then this issue could be closed immediately.

**Comment by tuvus** [comment]
> Your units stop gaining xp from barbs after their second promotions.

That is the case, so I will be closing this. 
Thanks for having a detailed description!
