### ISSUE TITLE
<after [amount] turns> seems to only apply to Global turns

### ISSUE THREAD

**Issue by mhoo40** [yairm210/Unciv#11829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.2-patch1

### Describe the bug

the line "This Unit gains the [Shock II] promotion <after [10] turns>", which supposes to mean the unit will gain 'Shock II' 10 turns after being trained, but instead, it instantly gets the promotion because it just needs the game to go past turn 10. 
Is there anyway for me to activate the UnitTriggerable based on the number of turns the unit has appeared in the game instead of the total number of turns the game has gone through?
Also, <every [amount] turns><for [amount] turns>, for example: "Can transform to [Musketman]<every [3] turns>", means every turns divisible by 3 this unit can transform, but only during that turn, so i want it to persevere a bit longer like <for [2] turns>, can it be done?

### Operating System

Windows

**Comment by yairm210** [comment]
The meaning of this conditional is "after X global turns", not a bug.
I agree it would be better phrased as "After turn [amount]", that's a change we can make

**Comment by hackedpassword** [comment]
If I may add an opinion - for grammatical clarity, "After turn number [x]" would clearly disambiguate the intent.

**Comment by yairm210** [comment]
Nope, deprecation as usual

**Comment by mhoo40** [comment]
> "Tadpole: Lives only 5 turns, then transforms into a Frog, whether it wants to or not"
Yeah, i want to give my units special abilities like buff with cooldown or transformation for a few turns. Maybe i can just use the promotion system but its still very limited
