### ISSUE TITLE
Sprites of unique units don't change with style.

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#11826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.0

### Describe the bug

![image-2](https://github.com/yairm210/Unciv/assets/78449553/daed3d3c-3b26-4555-a357-547ca4097e43)

I have a different sprite for a base unit (Scout - the one with the doggo) which works fine.
The problem is that if I have a unique unit that replaces it (Ruanero Mapper), that unique dude will still carry the base sprite, and not the unique one.

But oh, add the sprite to the unique duh. - Well yes.. but no.
The problem is that I want to have a separate mod that replaces every single unit for the nation, just for the sake of changing the name of the unit and add lore.

For example, in the add-on I would replace the Catapult with "Onion Trower", and explain why onions. While these unique sprites will be in the normal mod regardless.

So if the sprite style isn't applied over UUs, then I'd have to rename and add again all the sprites, duplicating the storage use for the same thing.
![Screenshot_20240623_090334](https://github.com/yairm210/Unciv/assets/78449553/295ddd38-00b8-4a2f-bef0-1ef94f07c9ab)
![Screenshot_20240623_090356](https://github.com/yairm210/Unciv/assets/78449553/962dab07-ba41-4667-afdf-9e9726b6d2eb)

So:
Community Civs: Sprites for normal units.
Add-on: Replacing of all units.

### Steps to Reproduce

The sprites from the picture are uploaded to the mod "Community Civs"

### Operating System

Windows

### Additional Information

Another option is to be able to use the TileSet.json to edit unit sprites as well.

**Comment by yairm210** [comment]
A. Not a bug, this is a feature request
B. "Take base unit image" sets us into a whole host of complications, in terms if priorities of image locations. This is by no means an easy fix

My instinct is to say no to this, if anyone has any ideas on simplifying image location priority be my guest

**Comment by hackedpassword** [comment]
@op Duplication is really your best option here, imo. :+1:  Another possibility depending on your prefs might be just using English.properties to remap the unit names while replacing the base sprites.

Rest of this comment is a side track towards the subject. 

> Some impressions: For the graphics portion, you have a 2kx1k texture space for sprites that will be loaded into GPU mem regardless of how many sprites you have, unless the atlas tex is full, then built as a 2kx2k tex. Memory sizes on a 4-bit depth tex are 8 and 16MB respectively, a trivial size really. Smartphones starting around 2006 had 128MB shared RAM (no GPU), while the 2005 ROKR had 5MB (awesome phone for its time). With these devices in mind, I'd say a potato has 64MB RAM, equivalent to a tricked-out 486. The concept of duplicating resources is tedious for sure but I'd question any focus on resource usage.

**Comment by yairm210** [comment]
Duplicated images are actually saved only once, so using the same sprite multiple times incurs no performance penalty

**Comment by Caballero-Arepa** [comment]
> @op Duplication is really your best option here, imo. :+1:  Another possibility depending on your prefs might be just using English.properties to remap the unit names while replacing the base sprites.

No because I need different names only for one nation. With translations, universal unit's names will change
