### ISSUE TITLE
Cannot copy save game via in-game button

### ISSUE THREAD

**Issue by kostia1st** [yairm210/Unciv#11822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.2-patch1

### Describe the bug

Before patch1 (`4.12.2`) upon clicking "Copy saved game to clipboard" I was just receiving the "Could not save game to clipboard" message.
With `4.12.2-patch1` the game just terminates immediately.

### Steps to Reproduce

- load a game
- reopen the load game dialog
- select that same game you've just loaded
- click the "Copy saved game to clipboard" button
AR: the game crashes
ER: the game data gets loaded into clipboard

### Screenshots

![Unciv_g4aLpHP5dK](https://github.com/yairm210/Unciv/assets/9264460/19a10306-b002-4fd0-9b28-e7ae6e72e77a)

### Operating System

Windows

**Comment by tuvus** [comment]
I can't reproduce this, is it still happening? Any mods? Does it happen with all of your saves? Does it happen if you start a new game and try and copy it?

**Comment by kostia1st** [comment]
>is it still happening?
It does

>Does it happen if you start a new game and try and copy it?
It works OK in this case

>Does it happen with all of your saves?
It happens to all saves that I have (started with the previous version of binary I guess)

>Any mods?
No mods, clean game.

I guess there must be some kind of a safety mechanism for copying a save file even when not everything is 100% compatible there

**Comment by tuvus** [comment]
Maybe Actual Result and Expected Result?

**Comment by kostia1st** [comment]
> Maybe Actual Result and Expected Result?

Yes, exactly, sorry for causing misunderstanding. Those seem to be industry standard shortenings, I at least I thought so.

Will add a save file in a moment.

**Comment by kostia1st** [comment]
[pesky_save.zip](https://github.com/user-attachments/files/15957254/pesky_save.zip)

**Comment by tuvus** [comment]
I could not replicate this with the save file given, is this still a problem?
