### ISSUE TITLE
Feature request: Missing civilizations from the “Brave New World” expansion.

### ISSUE THREAD

**Issue by JuanDavid45composer** [yairm210/Unciv#11833]
### Before creating

- [ ] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Several civilizations are needed from the “Brave New World” expansion, I list:

- [ ] Brazil
- [ ] Moroccan
- [ ] Polish
- [ ] Portuguese
- [ ] Shoshone
- [ ] Venetian
- [ ] Zulu 

### Desired Solution

Please add them to the game, don't tell me to use Mods, it is not the same as civilizations being in the base game :(

### Alternative Approaches

I don't know, Mods? That's not fun!

### Additional Context

Excuse my English, I don't speak it fluently.

**Comment by yairm210** [comment]
What exactly is the difference, if it's in mods or not...?
I'd you want it in the base game, you'll need to wait until we finish G&K entirely, which - given we've been at it for years - may take a while

**Comment by JuanDavid45composer** [comment]
Oh, I understand, the Mods thing is a personal problem. Thank you for responding!, and forgive me if I have been annoying.

**Comment by yairm210** [comment]
No problem
Closing as 'out of scope'
