### ISSUE TITLE
Modding Feature request: Adding "[Amount] Strength" As a alternative unique to "[RelativeAmount] Strength"

### ISSUE THREAD

**Issue by chenxing61** [yairm210/Unciv#11847]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

When trying to make some unit whose base strength scales with something else, it struck me as "how this isn't a thing yet", and it ruined my plan, a flat strength bonus should not be hard to code?

### Desired Solution

Add said unique, plz?

### Alternative Approaches

Any other way to change unit's base strength according to conditions

**Comment by yairm210** [comment]
Should move to #3242 
Non-trivial, since the entire "conditional bonuses" mechanism for battle is built on the assumption of percentage strength increases
