### ISSUE TITLE
Outdated Mods

### ISSUE THREAD

**Issue by SchoeniosX** [yairm210/Unciv#11843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.2

### Describe the bug

Outdated mods after recent changes are no longer compatible with the rules. Functionality Error: They cannot be removed from the mod list because they appear to have the same components. Bugs like missionaries or prophets belonging to a mod have bugs in their functions (establishing a holy place or spreading religion). However, the change bothers me; For some reason it can't be turned off anymore. Therefore I am forced to continue using outdated mods in the map editor.

### Steps to Reproduce

(-)

### Screenshots

![Screenshot_20240623-220656_Unciv](https://github.com/yairm210/Unciv/assets/148587231/68bfd98d-6afe-4c34-8e31-5970b284cf6e)
![Screenshot_20240624-003134_Unciv](https://github.com/yairm210/Unciv/assets/148587231/73f5462c-17cf-4f87-99f0-2320519e12fb)

### Link to save file

(-)

### Operating System

Android

### Additional Information

![Screenshot_20240624-164331_Unciv](https://github.com/yairm210/Unciv/assets/148587231/a86dc004-2f94-4fe3-a8e4-b9cf8a9764d0)
"Tech Combustion appears to be messing - perhaps two techs have the same row and cowmn"

Message form Research Branches. Displays the same component. And non-existing components. Feedback

**Comment by yairm210** [comment]
Bugs getting outdated aren't a problem for us to fix.
If you want specific mods to be up to date, you can contact their creators or - even better - make the change yourself as a PR to their repo, which I'm sure they will accept
