### ISSUE TITLE
promotion will gives buff to All units when having <for [amount] turns>.

### ISSUE THREAD

**Issue by mhoo40** [yairm210/Unciv#11842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.2-patch1

### Describe the bug

Example:
{
        "name": "Skill1",
		"unitTypes": ["Sword", "Scout"],
		"uniques": [
		"[+40]% Strength",
		]
},
this will give the unit +40%strength.
{
        "name": "Skill2",
		"unitTypes": ["Sword", "Scout"],
		"uniques": [
		"[+40]% Strength <for [3] turns>",
		]
},
this will affect not just the unit but every friendly units as well.

### Steps to Reproduce

[ModScenarios.zip](https://github.com/user-attachments/files/15956672/ModScenarios.zip)
-theres a save file in 'scenario' folder already set up.
-You can pick the 2 promotion called "Coura" and "Beagel" from the 2 units and see how they affect things
Or you can just create a promtion and check it out

### Operating System

Windows

**Comment by yairm210** [comment]
Yes, "for X turns" turns any unique into a global unique that holds for X turns
I will document this better, but this is working as intended
