### ISSUE TITLE
FYI: Keeping up with kotlin and gradle versions

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11870]
### Log

For kicks I just tried the following:

<pre>
Tools - AGP Upgrade Assistant...
  Let it do its thing to 8.4.2
`./gradlew wrapper --gradle-version 8.8`
File - Settings - Other Settings - Kotlin Compiler
  Change Kotlin compiler version to 1.9.24
Edit buildScr/src/main/kotlin/BuildConfig.kt:
    `const val kotlinVersion = "1.9.24"`
    `const val ktorVersion = "2.3.12"`
    `const val coroutinesVersion = "1.8.1"`
Let gradle sync do its stuff
Run desktop config - works
Run on some android device - works

`rm -rf .gradle/8.2`
`rm -rf ~/.gradle/caches/8.2`
`rm -rf ~/.gradle/daemon/8.2`
`rm -rf ~/.gradle/wrapper/dists/gradle-8.2-bin`
// AGP will pull a lot of gradle 8.6 crud before we replace that
`rm -rf .gradle/8.6`
`rm -rf ~/.gradle/caches/8.6`
`rm -rf ~/.gradle/daemon/8.6`
`rm -rf ~/.gradle/wrapper/dists/gradle-8.6-bin`
(or maybe rm -rf ~/.gradle/ and endure a redownload of all dependencies to get rid of old libraries)
</pre>

### Alternative Approaches

Wait for kotlin 2 `> 2.0.0` and gradle 9?

### References

https://ktor.io/docs/releases.html#release-details
https://github.com/Kotlin/kotlinx.coroutines/releases

**Comment by yairm210** [comment]
Kotlin version - definitely yes

AGP version - we'll need to check
I prefer to stick to versions supported by IDEA as well as Android Studio, it has distinct advantages in e.g. performance profiling
