### ISSUE TITLE
4.12.6 : Tile yields have crazy values - SOLVED in 4.12.6-patch1

### ISSUE THREAD

**Issue by Anon177013** [yairm210/Unciv#11884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.6 (No Mod)

### Describe the bug

Tile yields have crazy values all over the map (like several hundreds food, production and gold). Issue is present in the civilopedia too (like the entry for grassland saying +1007 production, +610 food, +950 gold). 

### Steps to Reproduce

Just start a new game or check the civilopedia terrain entries 

### Operating System

Android

### Additional Information

Issue present in 4.12.6, but not in 4.12.5-patch1

**Comment by phil-tomlinson** [comment]
Also experiencing this issue since installing 4.12.6 earlier today.

**Comment by yairm210** [comment]
Can you provide a save file? I'm sure you're right, but can't reproduce

**Comment by yairm210** [comment]
Source found, patch rolling out

**Comment by phil-tomlinson** [comment]
Incredible!
