### ISSUE TITLE
Mod images not showing up after update

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.4

### Describe the bug

After my latest update to the Deciv 2 mod, images for the newest addition aren't showing up. I've checked the atlas files and found the images and locations all there, but the new images don't show up in Android.

### Steps to Reproduce

Update Deciv 2 to the latest version and check out the images for the Hunnu.

### Screenshots

![Screenshot_20240629_123342_Unciv](https://github.com/yairm210/Unciv/assets/58439827/75f6e0e9-31a9-4af5-82ff-b56dd7f32e34)

### Operating System

Android

### Additional Information

The images were generated on Windows by a 4.12.5-patch1 version of the game.

**Comment by yairm210** [comment]
<img width="1260" alt="image" src="https://github.com/yairm210/Unciv/assets/8366208/3a84e263-c1c5-4ab9-a590-a0115a5fac78">

Downloaded for first time
I checked the code, and images *are* reloaded when downloading/updating a mod
Not sure what exactly this case is

**Comment by SpacedOutChicken** [comment]
Well, that's odd. The images were not showing up for me, and for one of the other people testing the mod, but now they're there. I guess I just needed to reload the game.
