### ISSUE TITLE
Politics table is empty

### ISSUE THREAD

**Issue by kostia1st** [yairm210/Unciv#11881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.5-patch1

### Describe the bug

Politics data-table is empty after switching from diagram mode.

### Steps to Reproduce

1. Open a game in which you've already met at least one other nation.
2. Go to Overview -> Politics.
3. Observe the Politics data-table. So far so good.
4. Click "Show diagram", observe the diagram.
5. Close the screen (get back to the game screen)
6. Open Overview -> Politics once again
7. Click "Show global politics" button to show the data-table once again.
8. Observe an empty data-table.

### Screenshots

![Unciv_BGucP9S63Z](https://github.com/yairm210/Unciv/assets/9264460/a935cc84-7635-4293-9076-f0b7a2aa1451)
![Unciv_5avaebxQr1](https://github.com/yairm210/Unciv/assets/9264460/8d5bcc1e-559f-4c8a-805f-c8c96eba4ab4)

### Operating System

Windows

**Comment by yairm210** [comment]
Can reproduce
