### ISSUE TITLE
Can't go to next round

### ISSUE THREAD

**Issue by Tonyx672** [yairm210/Unciv#11896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.5

### Describe the bug

when i click on the next round, a error message displayed

### Steps to Reproduce

1. Go to my Game : Auto save - Japan 788
2. Click next round

### Screenshots

error message:
[error message.txt](https://github.com/user-attachments/files/16053549/error.message.txt)

### Link to save file

[GameSettings.json](https://github.com/user-attachments/files/16053489/GameSettings.json)
[lasterror.txt](https://github.com/user-attachments/files/16053490/lasterror.txt)
[Unciv.json](https://github.com/user-attachments/files/16053491/Unciv.json)

### Operating System

Windows

**Comment by yairm210** [comment]
Already solved in latest version :)
