### ISSUE TITLE
Feature request: Numbers Translation

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#11895]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

As everyone knows, any number we display on our current UI is always English. But if you are not using English as your selected language, the numbers should represent your selected language instead.

### Desired Solution

UI numbers should get auto-translated based on language selection. `NumberFormat` from java, seems to be the perfect choice for this.

### Alternative Approaches
In properties:
```properties
0123456789 = ০১২৩৪৫৬৭৮৯
```
Then manually implement digit translation function
```kt
val digits = "0123456789".toList()

fun Number.tr(): String {
    return this.toString().map { it ->
        if (!it.isDigit()) return@map it
        return@map digits[it.digitToInt()]
    }.joinToString("")
}
```

### Additional Context

https://discuss.kotlinlang.org/t/how-to-override-number-tostring/28830
This seems to work:
```kt
import java.text.NumberFormat
import java.util.Locale

fun main() {
    val nf = NumberFormat.getInstance(Locale.of("bn", "BD"));
    val test = 1234567890.0123456789
    println(nf.format(test)) // ১,২৩৪,৫৬৭,৮৯০.০১২
}
```

**Comment by yairm210** [comment]
Sounds like this should be part of .tr() to me

**Comment by touhidurrr** [comment]
> Sounds like this should be part of .tr() to me

Lazy me says, modify `String.tr()` in such a way that `[value]` parsing detects numbers and formats them with `NumberFormat.format()`

**Comment by touhidurrr** [comment]
> Lazy me says, modify `String.tr()` in such a way that `[value]` parsing detects numbers and formats them with `NumberFormat.format()`

Although not sure if this would account for all cases.

**Comment by touhidurrr** [comment]
Ok, trying to understand `Translations.kt`. It is surely a piece of sophisticated artwork (maybe?). Parsing code always ends up like this huh? Maybe time to learn how to write lexers to better write such stuff for myself. But not now I guess.

**Comment by touhidurrr** [comment]
Ok, after some analysis of how translations are actually being used, I can see that any number being passed to `String.fillPlaceholders()` is being converted to `Number.toString()` which unfortunately we cannot overload. That leaves of with some possible options:
1. Check if strings being passed to `String.fillPlaceholders()` are numbers and if they are, convert them to translated numbers.
2. Implement `Number.toTranslatedString()` and deprecate the usage of `Number.toString()` somehow and replace all existing usage of `Number.toString()` to `Number.toTranslatedString()`.

These are the options that I can think of currently.

**Comment by yairm210** [comment]
tr does a lot of things - breaks text down to individual components, finds matching translation tempates, etc.
We don't need any of that, we just need the "simple" case of "translate this thing directly"

You see at the end of tr() we have lines like "if it's stats do A, if it's a stat do B"? That's where we take individual parameters and handle them in special ways
So all we need to do there is add "if this is a number, show this as a number in this language"

I split tr() into subfunctions - what you need to worry about is translateIndividualWord()

**Comment by touhidurrr** [comment]
So you want me to regex match numbers from string, then convert them to numbers and then again convert them back to string with `NumberFormat`?

**Comment by touhidurrr** [comment]
Getting `java.lang.NullPointerException: Cannot invoke "java.util.Locale.stripExtensions()" because "locale" is null

**Comment by touhidurrr** [comment]
Ok, fixed now. But some new issues. See #11898
