### ISSUE TITLE
Explain city capturing options

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/UnCiv#1189]
Simply add a description to each option, since it is not transparent to new users. Maybe there was a tutorial info about this, but that is a one-time short popup that you can not access again, so just add the information in the prompt :)

This can be done similarly to tile upgrades etc, just provide a description of everything that action entails.

This issue is being opened because I do not understand all the advantages and drawbacks, and those that I do, I largely had to figure out myself by observing the game or checking how it is in Civ.

Thanks for all your work!

**Comment by yairm210** [comment]
Good point, thanks! =D

**Comment by yairm210** [comment]
This is included in a tutorial, but having it there when you need to make the decision is a great idea!

**Comment by yairm210** [comment]
Resolved in 36ffc55
