### ISSUE TITLE
Bangla Translations is broken in master!

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#11903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.7

### Describe the bug

Something happened in 9c864c3. Pretty sure Bangla worked on my `bangla-translations` branch and right before #5826 was merged at its latest state. But it is broken in master? But why? Not sure.

### Steps to Reproduce

Try to build and run 9c864c3, and select Bangla.

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/46617994/9ae23114-3c04-4a98-a053-3cbc059048cf)

### Operating System

Windows

### Additional Information

#11898 works.

**Comment by touhidurrr** [comment]
To be sure, I revived [bangla-translations](https://github.com/touhidurrr/Unciv/tree/bangla-translations) branch, and yes, it is working:
![image](https://github.com/yairm210/Unciv/assets/46617994/27d6c3fa-0e2a-47b4-8f84-7cc7f5ab62b0)

**Comment by yairm210** [comment]
This actually changed in fb473590
This means that Options -> Advanced -> Generate translation files did this
This could be a problem with the encoding we write the translation files in
In TranslationFileWriter line 236 it says "write the new files as UTF-8"
Does Bangla not work with UTF-8?

**Comment by yairm210** [comment]
No, [I see it should](https://en.wikipedia.org/wiki/Bengali_(Unicode_block))

And we read is using that same charset
Not sure what's going on there, maybe the stringbuilder...?

**Comment by yairm210** [comment]
Anyway I would put a breakpoint in translationfilewriter and try to dig into where this change begins

**Comment by yairm210** [comment]
Hilariously "copy file" doesn't copy the bangla - not sure what encoding *the clipboard* uses, and damn am I happy that I have never had to think about that before, what a mess
Okay so that didn't work, the read-to-write flow works but the entire translation mechanism fails
It's midnight here, I'm going to bed

**Comment by yairm210** [comment]
NOPE reading UTF-8 files as UTF-16 did NOT work, that's almost certainly not the way
Not sure what *is* the problem
Debug TranslationFileWriter to find out, I guess

**Comment by touhidurrr** [comment]
> It's midnight here, I'm going to bed

It's 3:00AM here actually. But anyways, good night, see you later!

**Comment by touhidurrr** [comment]
> This actually changed in https://github.com/yairm210/Unciv/commit/fb4735908af908bff2831fd9b33321a3d6783071

Wait.................... This is not it................... I am pretty sure the reason is same as here: https://github.com/yairm210/Unciv/commit/fb4735908af908bff2831fd9b33321a3d6783071#r143772983

**Comment by touhidurrr** [comment]
Basically, diacritics support rewrites strings with unassigned codepoints from UTF-16. Then generates the bitmap fonts for the strings we rewrote so that we can display them.
Now, when you press the `Options -> Advanced -> Generate translation files` button, original translations strings are already rewritten!! And this is causing the issue!!!

**Comment by touhidurrr** [comment]
As, for how to fix it... Since, diacritics support is supposed to do this on the fly.. The originals have to stay somewhere locally...
That button is needed to modified such as it uses the originals, not the modified ones!!!

**Comment by touhidurrr** [comment]
As for now, an easy fix would be copy paste my Bangla.properties from my pr and drop it to master. Unless we wait for this to be fixed. Again take my ping @SomeTroglodyte .

**Comment by touhidurrr** [comment]
This will let us deploy 4.12.7 but maybe we really should not. As this is also problematic:

https://github.com/yairm210/Unciv/blob/fb4735908af908bff2831fd9b33321a3d6783071/fastlane/metadata/android/bn/full_description.txt

**Comment by touhidurrr** [comment]
> My Linux box still is not fully recovered - at least I proved the jumbled colours were due to the oibaf drivers. But checking Studio and the git state of Unciv I haven't had the courage yet, as it'll likely be frustrating with quite a few changes lost.

You don't need to check that history. For correct `Bangla.properties`, copy paste it from #11755. The one at master has been corrupted.
