### ISSUE TITLE
Feature request: Unciv Windows ARM64 / Aarch64 builds

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#11909]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

It would be nice if we had this. Kind of an early support?

### Desired Solution

`.exe` aside, we need correct jre. Some candidates are:
Temurin 21 from here: https://adoptium.net/temurin/nightly/?version=21
Microsoft OpenJDK 11: https://github.com/microsoft/openjdk-aarch64/releases/tag/jdk-11.0.12-ga

I would suggest Temurin 21 (cause 11 does not have arm builds). Microsoft one is quite old. I personally always play Unciv with my locally installed Temurin 21 (now GraalVM 22) without any issues. So, there should not be any problems with using Temurin 21.

If packr does not support it yet, we need to write a `.bat` file to run it maybe? `.exe` that we currently ship is the same right? Users would need to click on it anyways.

### Alternative Approaches

Not Sure.

### Additional Context

1. Recent hype regarding Snapdragon ARM chips on Windows.
2. Not sure if packr supports ARM yet.

**Comment by touhidurrr** [comment]
Wow, did not see this:
https://www.azul.com/downloads/?os=windows&architecture=arm-64-bit#zulu
This looks better as it specifically says ARMv8 (not the general Aaarch64) so should be more performant?

**Comment by yairm210** [comment]
We'll need a way to test this though
I don't have Windows at all, we'll need to ask if anyone has ARM Windows
Interesting point regarding Linux as well, looks like ARM is becoming mainstream...

**Comment by touhidurrr** [comment]
Oh, also, do you have any intention of trying to ship standalone binaries of Unciv with GraalVM?

**Comment by yairm210** [comment]
I don't plan to, I already spend way too much time dealing with distribution issues as it is
Just this week there's the AUR issue, Flatpak stopped auto-releases, and I investigated Snapcraft (no-go, their latest cores don't support gradle, bizarrely)

If you get it working I'm fine with adding it in to the pipeline

Also, why would it be any better? What's the difference between out current standalones and that?
