### ISSUE TITLE
Improvement: Change color of roads when cities are connected

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/UnCiv#1190]
Currently there is no clear UI to tell whether trade routes have been established, so I have to just make sure every tile is built and have faith in the game.

To make this clearer, it would be useful to have the roads turn eg. green when they are connecting two cities. That way you have some sort of visible representation of trade routes.

Another improvement to roads UI would be a notification as suggested in #1168 .

**Comment by yairm210** [comment]
Each city that's connected gets a 'connected' icon to the left of its name, maybe I should specify that on the tutorial

**Comment by yairm210** [comment]
So I don't think this is really necessary
