### ISSUE TITLE
Feature request: Standalone Unciv binaries with GraalVM

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#11911]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

GraalVM allows us to build standalone binaries for jar files. Which means no need to ship java and fast startup etc.

### Desired Solution

Use GraalVM native-image command to build binaries and then ship them.

### Alternative Approaches

Do nothing

### Additional Context

Testing on WSL:
![image](https://github.com/yairm210/Unciv/assets/46617994/65aabe22-a97e-4ef0-9adb-ace08d5013c0)

**Comment by touhidurrr** [comment]
> Also, why would it be any better? What's the difference between out current standalones and that?

from https://github.com/yairm210/Unciv/issues/11909#issuecomment-2206747086

There are some improvements:
1. Faster exec and startup times.
2. Only ship one file (no need to zip)
3. Possibly smaller size (due to having to ship no JRE's)
4. No need for packr
5. Overall better user experience (on systems such as Mac where to recommend `java -jar Unciv.jar`)

**Comment by touhidurrr** [comment]
For some reason, standalone builds are successfully failing. Need to do more research.

**Comment by touhidurrr** [comment]
**Update:** It is fast! But not complete.....

I am getting the error:
```
Warning: Aborting stand-alone image build due to dynamic proxy use without configuration.
Warning: Image 'Unciv' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
```
While only warnings, *requires a JDK* - is a kill switch for us. I did try the `--no-fallback` flag but it made an executable that crashed on runtime. The fallback binary is really fast though.

@yairm210 @SomeTroglodyte can you guys test this on your Linux systems?

The command is `./graalvm*/bin/native-image -jar Unciv.jar --gc=G1 -march=native`.

**Comment by touhidurrr** [comment]
https://www.graalvm.org/latest/reference-manual/native-image/

**Comment by touhidurrr** [comment]
> But even more curious is that you seem to run Unciv with a Java-21-level runtime - I thought neither Gdx nor Gradle are 21-compatible yet?

Java is pretty strongly backwards compatible. Not Java 21 compatible generally means that they don't support new features that comes with Java 21 or something like that. But that's a devtool synergy thing. Once a jar is compiler, you can run it with any higher version as it is still backwards compatible.

At least for me, I am doing almost from the from the time I got my Windows laptop and has faced no problems so far. If I had, you would already have seen an issue. (lol)

**Comment by touhidurrr** [comment]
> Gradle are 21-compatible yet?

No, Gradle 8.8 that I use supports Java 21/22. See: https://docs.gradle.org/current/userguide/compatibility.html#kotlin

Yes, I currently use locally installed gradle, not the `./gradlew.bat` that is shipped with Unciv. I used that also with JRE 21 with almost no issues. Just needed to set jvmToolchain(21) manually. With locally installed gradle, things changes though. As it makes it much better! IDE no longer keeps telling you to update gradle for every project and so on!

**Comment by touhidurrr** [comment]
Although, I did need to downgrade to GraalVM 21 from 22 mainly because of lag issues not stability issues. I often noticed lags with GraalVM 22 while opening multiple IDE's at the same time. But I guess that's and optimization issue with there version 22. But that's to be expected as 22 was current release and 21 is LTE.

**Comment by FuzzyMcWuzzy** [comment]
I cannot get it to startup at all.  Would it make it work if I simply replaced the JRE folder with an Arm64 version?

**Comment by touhidurrr** [comment]
> I cannot get it to startup at all.  Would it make it work if I simply replaced the JRE folder with an Arm64 version?

From my understanding, it cannot resolve dependencies properly. And I do not know how to resolve it.
