### ISSUE TITLE
Unable to build roads on NW

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#11925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.7

### Describe the bug

Some time ago, I recall a change made where roads could no longer be made on Natural Wonders. Didn't want to complain and see how things evolved.

### Steps to Reproduce

I've scoured release descriptions for the last year, didn't find a definitive hit. Went through code history for the below file (my good guess this is probably right) still nothing solid. 
https://github.com/yairm210/Unciv/commits/master/core/src/com/unciv/logic/map/tile/TileImprovementFunctions.kt

The change affected mod Z2 as roads could be built across NW bridges until this alleged modification. Questioning my recollection of the change since I can't seem to find evidence of it. 

### Operating System

Android

### Additional Information

Doesn't appear to be related to terrain or improvement jsons or uniques. Map editor allows laying down roads on NW's. 

Railroads are implied with roads. 

Did that change actually happen? If so is this something that can be reconsidered?

**Comment by yairm210** [comment]
I don't recall this ever being possible
Base ruleset's natural wonders are impassible so this never cropped up

**Comment by hackedpassword** [comment]
Really. Yep, it was possible! :D

The last known instance via screenshots I have is Dec 1 2023. See the bridge tiles, comprised of 4 total NW's ([bridge1&2 coast&ocean](https://github.com/hackedpassword/Z2/blob/bc8e1e41fbee8d7ca1574d96b65eff488f098ab3/jsons/Terrains.json#L899)) 

![Screenshot_20231201-021609_Unciv](https://github.com/yairm210/Unciv/assets/119975434/f3d13556-5b71-4fed-b9f4-cdd12bbe657c)

Somewhere in Nov-Dec, is where a really nasty crash showed itself (#10613 Nov 28)  and I switched gears for a while til SeventhM solved this via #11352 Mar 21. I can't be exactly sure atm but amidst that could be why I didn't address the issue then.

**Comment by hackedpassword** [comment]
When I have time I'm tracing Unciv versions to isolate where a change would have happened. So far looking at about the 4.8-4.9 era.

**Comment by hackedpassword** [comment]
Switched up the bridge tiles to:
```
		"unbuildable": false,
```
As well as commenting those two lines out, no effect on build-ability.

Tried adding terrainFeature "Force" to the roads:
```
		"name": "Railroad",
		"terrainsCanBeBuiltOn": ["Land","Natural Wonder","Force"],  // originally Land only, then w/ NW, then +Force
```

If I force a builder unit to construct Connect road while on the bridge tile, construction will activate, turns do not decrement, builder remains building forever.

Still have to spend time on version assessment.
