### ISSUE TITLE
Unciv on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [yairm210/Unciv#11938]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I am very proud to have Unciv listed in the repo. Please review the listing at https://www.openapk.net/unciv/com.unciv.app/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

### Desired Solution

Please review the listing at https://www.openapk.net/unciv/com.unciv.app/

### Alternative Approaches

Please review the listing at https://www.openapk.net/unciv/com.unciv.app/

**Comment by yairm210** [comment]
Sounds good, but compared to other distribution paths we have, I couldn't find

- Where the APKs are built (in case something goes wrong in the build) - do you build yourself, or do you take the APK we upload on Github release?
-  metadata for the 'current' openapk release (json / yaml)

This is a bit odd for a distribution which is all about open source, tbh 🤔
If I go to most distribution vendors I can see the builds, what happened, etc. 
For [championing transparency, collaboration, and non-proprietary software](https://www.openapk.net/about) it's super weird that there's no transparency on how the APKs are built

I'm 100% fine with you adding it in, but I'm not going to add a link to your distribution unless I could recommend players to download from there, and currently that's not the case

---

In other news, put "integration with shields.io" on your task list - most of the distribution vendors are there and it's *super* easy if you have json metadata ready :)

[Example](https://shields.io/badges/f-droid-version)

**Comment by mobilenetworkltd** [comment]
Hello,

thanks for your response. we don't build apk. It is downloaded from your official Github page. We have a script that points to https://objects.githubusercontent.com/github-production-release-asset-2e65be/111605778/52cdff21-2bd3-4191-b741-6e128ee58ff0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240710%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240710T092357Z&X-Amz-Expires=300&X-Amz-Signature=f6e04d73834feb8d19c9a4106114dc81cdcbc1378a13312847fa4fb3b1c79f7d&X-Amz-SignedHeaders=host&actor_id=125956566&key_id=0&repo_id=111605778&response-content-disposition=attachment%3B%20filename%3DUnciv-signed.apk&response-content-type=application%2Fvnd.android.package-archive and with our script we only track how many times it is downloaded.

**Comment by yairm210** [comment]
OK, that's fine 
Still
A. The link is https://www.openapk.net/unciv/com.unciv.app/apk/download so potentially there's no way to know where this is from
B. Metadata is not public

I'm not trying to be annoying, just - this is far below the expected level of transparency for a project focused on open source releases

**Comment by mobilenetworkltd** [comment]
I truly appreciate your remarks and will try to resolve them. I believe that by doing it I will make OpenAPK as transparent as possible to meet the your and other remarkable developer's as you standards. In your case we use this link https://www.openapk.net/serve/?token=JcpBDoMgEADAF8GyoG3sP3omW9kgEVkiqPH3PTjnQevQ-6X32j4AMfXl-OlZNrgp7ZtFA98ypxN2zkyNGwS5ShYKMGi0elJRJGZWNdP9VNVSLBw01dV7fFvzMm5w4x8  to protect from scaping and hotlinking. 

For the point A. I think to add an explanation to this page that states something like the following "OpenAPK is not hosting APK files, but using the GitHub API to link the latest releases". Is this what you mean?
For the point B. Do you mean the yaml file-a metadata or the metadata of the apk file?

**Comment by yairm210** [comment]
For point, that's definitely a start, but then the question is - if you're just reverse-proxying a well-known link, why not have that link be the source? It's both more transparent (I can immediately tell I got this from the Github page) and 
Regarding tracking, you can still use the onClick of the html button that triggers the download ;)

For Metadata, I mean: where does OpenAPK keep the list of projects, and for each the the last seen version, links, etc

Some examples:

- [Flatpak](https://github.com/flathub/io.github.yairm210.unciv)
- [Pi-apps](https://github.com/Botspot/pi-apps/tree/master/apps/Unciv)
- [F-droid](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.unciv.app.yml)
- [Macports](https://github.com/macports/macports-ports/blob/master/games/unciv/Portfile)

**Comment by mobilenetworkltd** [comment]
We are currently working on this https://github.com/mobilenetworkltd/openapk . Apart from it we are working on F-droid compatible repo which can be loaded in their client for Android. Do you think it is a good idea to include link to this https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.unciv.app.yml on the download page ?

Your suggestion for the link is very reasonable, I will make them directly to the Github page.

**Comment by yairm210** [comment]
That Github repo seems to contain UI-ready markdown files, that's not exactly what I'm talking about

What I means is:
Your website displays the latest versions of things and has links etc
So does the Github repo
I assume that you first go through some process of gathering and updating metadata for the repos, and then - from that - generate the website and repo "new state"

That **intermediate data** constitutes OpenAPK's "current state" for these projects, and *that* is what most other repos have that you currently lack

**Comment by yairm210** [comment]
Still not actually open.
Closing as "don't want any part in this"
