### ISSUE TITLE
4.12.10 boom all mods that include Atlases.json

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.10

### Describe the bug

![image](https://github.com/yairm210/Unciv/assets/114050365/4f754ab8-b4e1-480f-8efa-3100693977fd)

### Steps to Reproduce

Nothing.

### Operating System

Windows

**Comment by yairm210** [comment]
Already fixed and releasing in patch
