### ISSUE TITLE
Misleading/intransparent UI when building settler

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/UnCiv#1194]
This is a puzzle to me, friend in same game (and AI enemies) did not have this issue. I will just explain all the details and circumstances:

- Version: 3.1.5 (did not occur in 3.1.2)
- Online Multiplayer
- Russian Civilization
- Moscow city tile is grassland
- first population automatically assigned onto adjacent fish when building Moscow
- City info says 8 turns to new population, 0/15 food
- Food count doesn't increase, turns number doesn't decrease when pressing next turn

After my city expanded, I reassigned my population to a whales tile, still hadn't noticed my population had not grown. My city continued to not grow even after reassigning. When my city expanded further, I reassigned my population to grassland with horses. 

At this point I noticed my population was not growing, so I reassigned it to a mountain+forest tile just to see what happens if I put it on a tile that only gives 1 food. Then the city food increased to 1/15. I reassigned it to the horses and it worked fine from there.

Since I am not familiar with the code, I have no clue what the cause of this may be.

**Comment by UniqueActive** [comment]
Update: It's not just the starting city, also occured with my third city just now. Food stopped at 3, then did not increase further. I can not get this fixed by assigning to other tiles.
My friend (Japanese) also just started experiencing this on her capital, after it worked just fine for all this while.

**Comment by ninjatao** [comment]
Is this issue muliti-player only?

**Comment by UniqueActive** [comment]
I will test this today as soon as I have the time :)

**Comment by ninjatao** [comment]
Or were you building a settler with this city? Food will covert to production when building settlers.

**Comment by UniqueActive** [comment]
I may have been, and I was not aware that this is how it works! Is this a newly introduced feature?
I will test it again in the coming days and report back.

**Comment by UniqueActive** [comment]
@ninjatao If that is the case, the "X turns until new population" is misleading and this information a bit intransparent :/
I will try to confirm this :)

**Comment by UniqueActive** [comment]
@ninjatao You are correct, it was settler production that caused this. In that case, could the UI be modified to reflect that this happens?

eg. Instead of still saying "X turns to new population", replace that with " Population growth halted while building settler" or "Food converting to production towards settler".

**Comment by UniqueActive** [comment]
Unfortunately never played the originals, so I struggle with everything that is not explained somewhere 😅

**Comment by yairm210** [comment]
Solved by @ninjatao
