### ISSUE TITLE
Feature request: "Heretic" extermination in Religion. (Seasons)

### ISSUE THREAD

**Issue by SchoeniosX** [yairm210/Unciv#11971]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

(-)

### Related Issue Links

(-)

### Desired Solution

There is no problem, but I would like certain functions not only to exist inquisitors that are very effective, but also to have a kind of prevention of religious spread of civilization in (%) building functions. 

Inquisitors are very strong, so without removing the Inquisitors another option could be available. Of course, the moderators depend on whether they make it more difficult to generate inquisitors.

Nothing should be removed, just a function added to the game.

### Alternative Approaches

(-)

### Additional Context

Furthermore, have you already thought about the seasons? Fie the environment and certain effects globally? Or can this already be done yourself?

**Comment by yairm210** [comment]
This is absolutely a #3242 issue
Regarding seasons you can simulate it with stockpiled resources and events every X turns
