### ISSUE TITLE
AutoEndturn bypassed Disabled Auto Build roads Option

### ISSUE THREAD

**Issue by PrivateRoom6863** [yairm210/Unciv#11977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.11 patch1

### Describe the bug

Just currently playing Celts with Unchecked Auto build roads aka Disabled Auto roads in cities and I noticed that my workers started connecting roads to cities even I Disabled it

### Steps to Reproduce

1. new game
2. Be sure to have Disabled Auto roads
3. Settle some cities
4. Research A Tech where it enables Road improvements
5. You may see that workers start connecting roads

### Screenshots

![Screenshot_20240717-215010](https://github.com/user-attachments/assets/d003c769-7e68-4314-b02a-c9e54e875d52)

### Link to save file

[Celts - 59 turns.json](https://github.com/user-attachments/files/16266554/Celts.-.59.turns.json)

### Operating System

Android

**Comment by tuvus** [comment]
Doing AutoEndTurn does not use the automate feature of the workers. One way for you to get around this is to long press the next turn button, then click move automate units. Your workers should have already moved so they will be less likely to do a build road action when pressing autoEndTurn afterwards.
 
Autoplay plays as if you were the AI, so it doesn't do thinks like use the automate unit action.

This could, however be implemented. Would probably be easy.
