### ISSUE TITLE
Unique stopped working, +1

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#11974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.11.1

### Describe the bug

Mod:Z2
Android

[These uniques](https://github.com/hackedpassword/Z2/blob/d01e154cdcc997d8ba0167a1b8acfe8521252a9c/jsons/UnitPromotions.json#L39) seems to have stopped working:
```
"This Unit gains the [Upward Thrust] promotion <in [Darunia Town] tiles> <for all movement> <once>",
"This Unit gains the [Downward Thrust] promotion <in [Mido Town] tiles> <for all movement> <once>",
```

While building this report, paradrop(teleport) also seems to be bugged. 

### Steps to Reproduce

The GDR seen in the screeny is standing on "[Darunia Town](https://github.com/hackedpassword/Z2/blob/d01e154cdcc997d8ba0167a1b8acfe8521252a9c/jsons/UnitPromotions.json#L30)". Because the unit has the "[Jump](https://github.com/hackedpassword/Z2/blob/d01e154cdcc997d8ba0167a1b8acfe8521252a9c/jsons/UnitPromotions.json#L30)" promotion, the above unique should trigger, showing a upgrade button to activate the promo. This stopped working within I'd say the last week. No units seem to be able to upgrade this way, or at the [other town](https://github.com/hackedpassword/Z2/blob/d01e154cdcc997d8ba0167a1b8acfe8521252a9c/jsons/Terrains.json#L752) across the ocean SW from there.

Paradrop=teleport will work inside the area you see, but won't accept the move at tiles over the mountain eastward. 

### Screenshots

![Screenshot_20240717_002629](https://github.com/user-attachments/assets/b4681d24-83e7-4962-b369-ff3dddb5ca20)

### Link to save file

[France bug report.json.txt](https://github.com/user-attachments/files/16260822/France.bug.report.json.txt)

Attached. 

### Operating System

Android

### Additional Information

Town seen is located top center of the map.

Other promotions granted by natural wonder terrain tiles still works fine, so when a unit stands aside the town they receive a specific promotion. Promos are shown in the promo screen but are inaccessible by design, and must be granted. That's a fyi for when you see:
```
"name": "Jump",
	"uniques": [
		"Only available <for units with [Jump]>",
```

**Comment by yairm210** [comment]
<img width="922" alt="image" src="https://github.com/user-attachments/assets/f94940ca-ce34-4769-9ce5-7e603576b63f">

SO
What we see here is that limited unit abilities are defined *by the unique type* and not *by the unique text* so if you have one unit with 2 uniques using the same template, they both count for the same thing
Since this unit already used one, it can't use the other
I think I have a good fix, we'll still need to discount conditionals but we can take the parameters into account

**Comment by hackedpassword** [comment]
> so if you have one unit with 2 uniques using the same template, they both count for the same thing

That would be a great fix to have actually, as I've run into other instances recognizing the behavior you mentioned, but didn't think to apply that here AND it was working! :laughing: Guess fish Friday was serving red herring
