### ISSUE TITLE
Timeline project

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1197]
TO BE DEVELOPED IN FUTURE

After a game is over, it would be nice to include a timeline, like this:
- [ ] A City has been founded
- [ ] A City has been conquered
- [ ] A City has been razed
- [ ] A Civilization has been destroyed
- [ ] A City-State has been defeated
- [ ] A Wonder has been built
- [ ] Was has been declared between two Civilizations
- [ ] Two Civilizations have made peace

**Comment by yairm210** [comment]
Moved to #663
