### ISSUE TITLE
Barbarian encampments appearing on map, even without Honor selected

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.11

### Describe the bug

Barbarian encampments have started appearing on the player's map, even without selecting a policy that notifies you of the encampments. The notification itself doesn't appear, but the encampment improvement shows up on the map where it wasn't before, alerting the player to where the barbarians have just spawned. It's useful intel, but you're not supposed to get that intel without the appropriate unique enabled.

### Steps to Reproduce

1. Start game, preferably in an era when the entire map has been revealed.
2. Do not send units out. Leave as much area unseen as possible.
3. Barbarian encampments will appear on your map in areas where your units can't see them.

### Operating System

Windows

**Comment by yairm210** [comment]
Tried this, got to turn 100 without anything
Can you send a save file?

**Comment by SpacedOutChicken** [comment]
Compare the view of before ending the first turn and then right after:
![Screenshot (210)](https://github.com/user-attachments/assets/676c5f4f-c680-4a00-96db-ad040fbf9d91)
![Screenshot (211)](https://github.com/user-attachments/assets/188215e7-3886-45e5-a760-5a4eae79aca7)
