### ISSUE TITLE
Improvement: Backup settings and savefiles

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/Unciv#1199]
When uninstalling UnCiv, settings such as user-id and savefiles are lost.
I attempted to get around this by backing up the "files" folder in /data/data/com.unciv.app as it appeared to contain all the relevant files, but that was unsuccessful, as the newer version refused to start with the backup I had made.

To get a more elegant solution, please provide a means of exporting and importing user-id and savefiles. Especially the user-id is important as a change in user-id makes it impossible to resume ongoing multiplayer games, even if another player has the savefile.

Also, any temporary hacks to get back my savefiles and userid are welcome :)

**Comment by UniqueActive** [comment]
Okay, I managed to change the user-id in the GameSettings.json (god bless backups) and then was able to join the multplayer game by using the game ID.

Still, an export feature and an option to import on first start would be fantastic for migrating between devices or installations, or through a device reflash, which will certainly happen again soon for me :)

**Comment by yairm210** [comment]
Export for just the settings is pretty simple because it's small, but the save files are less so.
You could probably zip them all to some file, but then what?

**Comment by yairm210** [comment]
The zip/unzip, actually... it would require the "Access files and folders" permission on Android, and I'm loathe to introduce that for such a small feature...

**Comment by UniqueActive** [comment]
It seems like a small feature but it is a very fundamental one in my opinion. I am surprised that it has not come up before honestly, because the ability to backup and migrate data like this is something very fundamental to being able to keep using this game if you change your device or flash a different operating system.
Regarding storage access; I do not know how hard it is to implement, but the app could just ask for it when doing the backup, so it is not always needed. 

Another solution that could maybe circumvent storage access is this:
The app just generates a zip archive and allows you to share it to other apps. Then the concern is importing though, since I don't know if this would work backwards without storage access.

**Comment by rh-github-2015** [comment]
>"files" folder in /data/data/com.unciv.app
When you save those and restore them later using a root file explorer, you often run into the permissions trap. Uninstalling and reinstalling will create a new user for the app, and your copies will probably not conform - they'll be owned by root or the old user. One way that mostly works is have the new app create any file, then transfer its owner, group, chmod flags *and* selinux context to your backups. Depending on the file manager used, you may not need to touch one or two of these areas, but you'll never get a perfect match by default.

**Comment by MayeulC** [comment]
As I do not have a root explorer on the phone I am currently trying to back up, I would appreciate a way to export the savegame, even if not as fully-fledged as #1710 

According to [stackoverflow](https://stackoverflow.com/questions/17985646/android-sharing-files-by-sending-them-via-email-or-other-apps), this should be as simple as (no extra permissions needed):

```java
Intent intentShareFile = new Intent(Intent.ACTION_SEND);
File fileWithinMyDir = new File(theSavegamePath);

if(fileWithinMyDir.exists()) {
    intentShareFile.setType("application/json"); // Or zip, or even your custom application/unciv+savefile
    intentShareFile.putExtra(Intent.EXTRA_STREAM, Uri.parse("file://"+myFilePath));

    intentShareFile.putExtra(Intent.EXTRA_SUBJECT,
                        "Exporting savegame...");
    intentShareFile.putExtra(Intent.EXTRA_TEXT, "Exporting savegame...");

    startActivity(Intent.createChooser(intentShareFile, "Export savegame"));
}
```

[more documentation](https://www.androidcode.ninja/android-share-intent-example/) available [all over](https://developer.android.com/training/secure-file-sharing/) the web ;)
Not sure how it would interact with non-android platforms, though. i guess you don't really need the export option on these, but you could use a file picker as well.

------
Alternatively, [storage access framework](https://developer.android.com/training/data-storage/shared/documents-files) usage might be better (assuming Android 4.4+):

```java
// Request code for creating a PDF document.
private static final int CREATE_FILE = 1;

private void createFile(Uri pickerInitialUri) {
    Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
    intent.addCategory(Intent.CATEGORY_OPENABLE);
    intent.setType("application/json");
    intent.putExtra(Intent.EXTRA_TITLE, "savegame.json");

    // Optionally, specify a URI for the directory that should be opened in
    // the system file picker when your app creates the document.
    intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, pickerInitialUri);

    startActivityForResult(intent, CREATE_FILE);
}
```

**Comment by yairm210** [comment]
This issue can FINALLY be closed - as of the latest version, new save files are generated in the app folder in the SD card and do not require root access!
The user ID was dealt with a while back as well =)
