### ISSUE TITLE
Nation portraits are not working

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#12002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.12

### Describe the bug

I'm trying to have nation portraits, and have followed exactly as mentioned in the wiki, but it doesn't work.
I checked countless times the names of the folders and images, but no.

Result: 
![image](https://github.com/user-attachments/assets/081d9a34-0bb1-4104-a439-96c101bc75a9)

Folder: 
![image](https://github.com/user-attachments/assets/368f282a-acc9-4d4b-812d-6dd04b17fa6a)

Wiki: 
![image](https://github.com/user-attachments/assets/c8f167e8-c9d8-45f7-aae8-8789c95fe679)

Mod: https://github.com/Caballero-Arepa/Iron-and-Blood

I can't figure it out.
Curiously, if I activate the Civ 5 Icons mod, it works, but my icon is way smaller.
Speaking of which, I don't think that mod is a good example for portraits, as the portraits are already compiled outside, and they are not arranged how they would be in a common mod.
I can't figure it out.

### Steps to Reproduce

Download https://github.com/Caballero-Arepa/Iron-and-Blood

### Operating System

Windows

**Comment by Caballero-Arepa** [comment]
Ah yes.
As the wiki says to use the name of the Json...

[to fix the wiki] maybe there could be a tooltip that appears when you hover the mouse (like in the uniques, currently I don't know how to), or place the list of the portrait.kt (making the wiki a bit longer).

I'll look for a solution.

**Comment by yairm210** [comment]
If this is a simple path misname we should catch it in ruleset validator

**Comment by Caballero-Arepa** [comment]
Nah, it is a problem with the wiki.
I removed the S and it kinda works
