### ISSUE TITLE
Religion Buildings and Units Not Building

### ISSUE THREAD

**Issue by ADDictedGamer** [yairm210/Unciv#12000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.12 - patch 1

### Describe the bug

_Religious-Specific Buildings_ (Pagoda) and _Religious Units_ (Missionary, Inquisitor) are unable to be built despite having properly enhanced religion and having adequate amount of faith.

Military Units are still able to be recruited using Faith (with _Holy Warriors_ belief), however
Modded  "Wayfinders" are not.
I have 100% religious dominance in the cities on my Continent.

This is a brand-new issue and it is occurring in both single and multiplayer with my friend.

IMPORTANT NOTES: 
1) This is BRAND NEW. I was able to play the religion the same way in a previous game and previous save with the same player.

2) Issue persists EVEN WITH Single Player, using different civs and different builds. 

3) This even applies to much-older Single Player saves (attached) 

### Steps to Reproduce

Simply play the game and attempt to hire religious Units or build any religious buildings. 

It cannot be done. 

### Screenshots

![Screenshot_20240721_052531_Unciv](https://github.com/user-attachments/assets/7c915ef9-87d4-40b9-a52e-a0b1ac9ddd88)
![Screenshot_20240721_052540_Unciv](https://github.com/user-attachments/assets/1c4afc53-9784-475e-af96-172195290e4f)
![Screenshot_20240721_053816_Unciv](https://github.com/user-attachments/assets/4633151f-f5b0-406a-8719-9bfa5705d5a2)
![Screenshot_20240721_053840_Unciv](https://github.com/user-attachments/assets/84fb0a76-492b-4dae-b7e0-6fcec0da3b92)

### Link to save file

Save File Too Long.  

### Operating System

Android

**Comment by yairm210** [comment]
Solved in patch2, rolling out now
Copy of #11990
