### ISSUE TITLE
Can player use their own Dropbox account?

### ISSUE THREAD

**Issue by leosongwei** [yairm210/UnCiv#1200]
[./core/src/com/unciv/ui/worldscreen/optionstable/DropBox.kt](https://github.com/yairm210/UnCiv/blob/master/core/src/com/unciv/ui/worldscreen/optionstable/DropBox.kt)

What about adding an option to allow player to use their own Dropbox token?

**Comment by yairm210** [comment]
I guess it's possible, but what's the benifit?

**Comment by yairm210** [comment]
Closing this, because I don't see the point of such an option
