### ISSUE TITLE
Force calculations getting massively screwed up in Wakanda mod

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.12-patch2

### Describe the bug

Something about the Black Panther unit in my Wakanda for Unciv mod is messing up the force calculator. The unit itself has a base strength of 20, but it scales with era (maximum strength bonus is 400% during the Future era). Building this unit causes the force calculator to give the civilization a strength of over 800,000. The unit is not actually that overwhelmingly strong.

### Steps to Reproduce

1. Enable Wakanda for Unciv mod
2. Build the Sacred Mound, causing the Black Panther unit to appear
3. Wait one turn for the force calculator to catch up to the changes made
4. The force displayed will now be unreasonably large

### Screenshots

![Screenshot (212)](https://github.com/user-attachments/assets/4d6d9edd-c68b-4741-90bd-f65e9ecb2c51)

### Link to save file

https://github.com/SpacedOutChicken/Wakanda-for-Unciv

### Operating System

Windows

**Comment by yairm210** [comment]
Now that is interesting!!! Yes, zero modder intervention, I approve
