### ISSUE TITLE
Can't buy missionary (and any religious unit) as the button is greyed out

### ISSUE THREAD

**Issue by hl037** [yairm210/Unciv#12016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.12-p1 b1026 (android)

### Describe the bug

The missinary and inquisitor units are proposed in the menu, with a cost of 200 faith... However, I can't buy them since the button to buy them is greyed out...

### Steps to Reproduce

* I have religous beliefs
* I have founded a named religion
* I have enough fait credit (>= 400)
* I have temples and other religious building

### Operating System

Android

**Comment by yairm210** [comment]
Copy of #11990, solved in latest version
