### ISSUE TITLE
Ally AI doesn't know how to deal with open borders with ally's offensive workers within the AI's territory

### ISSUE THREAD

**Issue by PathosEthosLogos** [yairm210/Unciv#12019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.13

### Describe the bug

See description + screenshot below

The AI doesn't know how to handle offensive workers. Building forts in friend's open border territory shouldn't be doable.

### Steps to Reproduce

1) Agree to open borders

2) Start building forts in their territories

3) Block their workers from undoing the forts by letting the workers stay/sleep there

### Screenshots

![image](https://github.com/user-attachments/assets/c99e871c-8106-434b-b141-fe48b3d46cf1)

### Operating System

Android

**Comment by tuvus** [comment]
I think the bug is that we let players build forts in other Civs territory in the first place. Does anyone know if that is Civ V behavior?

Players would also have trouble handling that. The solutions would be to either let the open boarders run out or declare war.
