### ISSUE TITLE
Unable to download game

### ISSUE THREAD

**Issue by WanderingLoon166** [yairm210/Unciv#12020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.10-patch1

### Describe the bug

Unable to download Unciv game from f-droid. Error 404 suggests something is wrong with the mirror site.

### Steps to Reproduce

1. Open f-droid app
2. Find unciv app in games section
3. Click download

### Screenshots

![Screenshot_20240727_114125_F-Droid](https://github.com/user-attachments/assets/59e399e4-6cb3-4cbb-b02f-82e5d17c84df)

### Operating System

Android

### Additional Information

My mobile: Samsung Galaxy A52s 5g
Android 14
One Ui version 6.1

**Comment by yairm210** [comment]
This is an F-droid error, not something I have any control over :/
F-droid is just one of many distribution avenues we have
I assume this is a temporary issue, otherwise you can contact them [here](https://f-droid.org/en/issues/)
