### ISSUE TITLE
The Huns AI taking other civs' city names (without taking the cities over)

### ISSUE THREAD

**Issue by PathosEthosLogos** [yairm210/Unciv#12038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.15

### Describe the bug

Game of Korea, England, Spain, and the Huns

The Huns only had Attila's Court as their correct name, while rest of the cities founded by the Huns were taken from other civs.

No other civs in the game has demonstrated such behaviour.

Someone has reported a similar bug, but unsure if related: https://old.reddit.com/r/Unciv/comments/1e8la6s/there_are_two_kyivs_in_this_world

### Steps to Reproduce

Create a game with four AIs and a spectator

Auto play

See that the Huns only have one correct city name, Attila's Court.

### Screenshots

The cities that the Huns founded:
![image](https://github.com/user-attachments/assets/a4941142-9477-4a05-b8c8-2a00bab35156)

The first three (+1) cities the Huns have founded:
![image](https://github.com/user-attachments/assets/bb608646-5d49-43ed-b22f-b56b6aaf169a)

More cities founded:
![image](https://github.com/user-attachments/assets/6e0117d5-e8f9-4251-8b02-4ced1758bd18)

More cities founded 2:
![image](https://github.com/user-attachments/assets/79fd816d-4e1b-427f-bc5f-3128f5843624)

Aftermath of wars (above founded cities are untouched):
![image](https://github.com/user-attachments/assets/719254fe-1f9a-4254-bf55-7c34f60760cf)

So the cities that have English, Spanish, and Korean names are not the result of wars.

### Operating System

Windows

**Comment by yairm210** [comment]
That is what we in the trade call A Feature

<img width="933" alt="image" src="https://github.com/user-attachments/assets/afb58100-a65a-4504-a365-4763d9bacff5">
