### ISSUE TITLE
World wrap disappears in games saved in 4.12.15 - SOLVED in 4.12.16

### ISSUE THREAD

**Issue by Diraven8** [yairm210/Unciv#12058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.15-patch1 (Build 1031)

### Describe the bug

The world wrap feature no longer works.  I see in the change log for 4.12.15 that the option was removed because it's supposed to be always  the default now.  But instead it seems like world wrap just stopped working altogether.

### Steps to Reproduce

Resumed my previous game and world wrap feature no longer works.

### Operating System

Android

### Additional Information

Word wrap was working until the latest update installed today.

**Comment by yairm210** [comment]
That's super weird, patch1 should have solved this
Can you send your save file?

**Comment by Diraven8** [comment]
Ok, I've played around a little and it appears world wrap is no longer available when I use custom maps?  For generated maps it's there on the new game screen.  But for custom maps I don't see any way to select it anymore.  With the old way the option was selected it worked fine with custom maps.

**Comment by Diraven8** [comment]
Sorry, I can't post a save file, I'm using a very huge map and it says the file is too big

**Comment by vincemolnar** [comment]
I can confirm it is gone. And not only that, the minimap is messed up, too.
![Screenshot_20240803_085335_Unciv](https://github.com/user-attachments/assets/a4036294-0588-4299-aa5f-d863d356b96a)
Here is my save file (saved now, I don't know if it affects the result):
[Japan - 1210 turns.json](https://github.com/user-attachments/files/16478398/Japan.-.1210.turns.json)
(While you are there, you could also investigate why workers seem to oscillate back and forth while automated - I realize there are a lot of them, and there is little to do, but something is off here.)

**Comment by vincemolnar** [comment]
Could you please roll back the public release until you figure this out?

**Comment by yairm210** [comment]
It IS rolled back, that's what's weird
I'll investigate now

**Comment by yairm210** [comment]
OH DAMN I know what it is...

I changed the *default value* so it stopped being serialized
Then when I changed the default value *back* it was still not serialized so changed back to new default
DAMN YOU JSON SERIALIZATION
I'll try to find a good solution

**Comment by yairm210** [comment]
Basically this means this only occurs for games saved in version 4.12.25
So autosaves should work

**Comment by yairm210** [comment]
Mitigated in #6bafab3c, rolling out in new version
