### ISSUE TITLE
City state ideas

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#12057]
Declaring war against your allied city states should lead to a popup like 'pledge to protect' - to allow declaring war for 'good reasons'

City-states can gift units that take you over the resource limit - this should not happen, we should filter them out of the options

**Comment by PLynx01** [comment]
@yairm210 

What about an game setup option that selects only the city states with specified starting locations? 
For now we have major civs auto-select. It would be great to have similar option for city-states.

**Comment by yairm210** [comment]
Also unrelatedly resource overview direct out resiurces with wrong improvements as "unimproved tiles"
E.g. oil with farm

**Comment by yairm210** [comment]
No, "unimproved resources" should mean "resources that are not being provided"
Just because a tile *has an improvement* does not mean that the *resource* is improved

**Comment by yairm210** [comment]
@PLynx01 We should add that as default, surely if we can choose between 'preplaced' and 'non-preplaced' we should choose the former

**Comment by yairm210** [comment]
<img width="823" alt="image" src="https://github.com/user-attachments/assets/6a5371f8-e9b9-4b2d-a085-d96b6f475fa6">
Okay that's already been done
