### ISSUE TITLE
Workers spamming forts

### ISSUE THREAD

**Issue by PathosEthosLogos** [yairm210/Unciv#12076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.17

### Describe the bug

See screenshot below

### Steps to Reproduce

Automate workers

Automated workers build forts for no reason

### Screenshots

![image](https://github.com/user-attachments/assets/ec149faa-b2ff-41de-a359-e1ea44a6e376)

### Operating System

Windows

**Comment by tuvus** [comment]
I could not replicate this. Were you at war with some other civilizations?

**Comment by PathosEthosLogos** [comment]
>I could not replicate this. Were you at war with some other civilizations?

Sorry, only found screenshot, reported by another user/player

Looking at happiness however, it does not seem to be that way.
