### ISSUE TITLE
Crash on next turn

### ISSUE THREAD

**Issue by Doomstar00** [yairm210/Unciv#12083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.17

### Describe the bug

game crashes, when i press "next turn". Save game uses unpublished mod, and i guess because of "Gain a free [Aliens Crisis] [in this city] <starting from the [Information era]> <upon turn end> <after turn number [0]> <hidden from users>", in unpublished mod.
It is building unique, Aliens Crisis is also building, which removes this when built, and civ have unique, which provides for free building with unique 

### Steps to Reproduce

press "next turn", and game crashes

### Link to save file

H4sIAAAAAAAAAO09y3LbynK/gmB1b5Xo8AGSonc0Ldm+ZdmKpBNXyqXFEByKE4MYBg9ZvC6t7ip/cfMJqSTbLPIFPn+Unhm8SIEypTOkBmyUXTY5BAbT7+7p7sEPe0wC+MuIH9qvf9wf2S67ZR77K4kYF0Nff4iREXyOgthNBpPrPpE5tV/bb/IZjmwaLuAackPPiPg3UBfTu4XHAzq5oDfwqxq74d6E+sMbmkx4E1ASnVO+8GDSH/aCMz8KT3nwid5F78Rv76hPA+KNeOxHcmJbDlvJuP263Wzew0QL7jGXpdP+W0zDaGUxAfWYWMbqYMz8cGUkIgCuS7zhh+Q7dWfq0y1zIx4sC1ffHwk0RfKhEmPRch1l9jhmXvQG/pkw/0ZcZ59xP55TPwK0DeeLGYtmAA5MeAQo9b/Bf+fEIy6FDx/ZzSya8TgUX85I8I2Km0bc42FI47m8IwiI+02QYOgx6ofWGzoFlFujgIVMDF+J2QMxwRcefAtnfCEnHgckWMKndwGAA5+ugbSFpf9TTGMqFvt5AUi23ss1wDXTgNIMmPOA37IJnZwGfH41Y+EI4BcgO63mYEy6zUa3O241HDJ2GsdT6jacbsshrc7AGYypQphHQkCJ/a/klrzyiH/z6jIKYGZY1y3xxALKobq/FgSH9frUjejkio/IgkXEu4xIFIsJAQxa5MqMHYFbM06cAkcJOEbsFm458SfWO+Ds5BmWejBMAvjzImCBVrMJnHZkswlcvRWIcG34OQCm84F91Qrt12JpR7bHXSlqAl139utG58gG1DVasCxfiddHIhdnXbJIzLTgi9jLbil+6x7Z4YK6jHgsjIZeOrNkvhMfHk4Fs7buCyKQcDbzEsZdXYH67qjv7fR79qGz9kMnu6J8htY98M134D0g1MoTN864/uh8IjGVEriR0AEUSNE6+qWm2kjaEq1lA7uHl4vlCQl84GweCCG4oD5hYUh8l1rwO9z5wZ/E8EBAejJwxic08JMvw4jPmZtdCqw7lzRJRk7jKA7UTNeCeMuPQDmJloT28HyrZQvwCwPt9YHO+oCzPtBdH+gJ0SnRy/aYR7DmC6FvUpZsNRMyNAWv8MVHOk1/S35qS70rFLr9ut883qFun5Hw5JYGn78DTTZJFAmjS0r9D/MFqCUqFSzM9yfgrkbrzwC/0E6WS+WDhJjxiE2ZWzR4wFA3oOAFx2SKQxiAO5jJ/kKtGbmlVkBdMBrAetZXSaZri4QWsYCK/yAE3lWz2Z9BqwcfxLd/hMsEnYmbPyqbf+gmIn0vCPPMNbQNWEPHgDU4Bqyha8AaejtbA1j8iVKy+SK+Fi3VNSwotMKIBGI1QuuLX0DzfS04EtfFRQmbrdZUmHxtaR8Tm5atbLP9lD6ZEPX8WjdxS9au2wq2MvdDwTgGXWNJ585iAN4KEorwpd6SgrHUnfnD0ILrzhd0wkjhFgauJHAI98EulT/2XtnThUeWNLhaLoSReB/PiW+vONM2mfAFUPM8GwIXFmIFoDELhQ96SkJXfRrGEXfBHxWO5blwUdSwvJNagtLSiQT3dwzKfDpcn1i4MuDuehNgFl8OL8+Z+01YBqXkw0iYrVHsCQNqvx50hd8f8Ds2T2j8JojBNfaED/iJ+0JU3l5arnTwku/g2Y6paylfNR08FeYQrHs+csG4NaHWX4hPWcDz8RGZ8W+M5AOXy4lPs6l2EHnI/8MLGlISuDPh8nyF9UpLfWSfeOABB9xnrvBnPi8i9eEyomRunfPvMqwYuiB1yS8jPh+LL5LLP8WuB7Nap3GoBs74GFw060quRFx+wcEzUB/PmK9c8wvCvICTiXwQfFajJyA8JJn3IwlpIGMSsWIZZ4ziQGB4KWMWT7iqatZ3sb/g3ydynac0iEQQKr+cUTDu1gisejI/yI/wqhQQubeXPAXEzpVMkXlfEPjwYJlEVWqOKwro4vN57GeGX2JkIcIQAIwuROBFxoCCc9BgYuw9D0I6hhDLumATNYtAIXjVE2sYzOUEMzoHeOSzcr8wiaUljiIKEEdUXPwGiPVXan1RmjEhlYgv4BMIgS+dknzt5zMQ7ZAvZvILrIm5YnGzZZiRcxFHCtlvAzInFughIDxVy0nkdGnJuWVMeQ4BlkCpdR5QCfUZAbMg/NOEHqCu5EIZhJk3S8kDIILJfAQw7SuKprGFAkPQgND0FsWWTGpeWNgSXFAVxlyQCQmkSogiNc3wBq5LBBrwB+gpIOeCTRP2EhhJJv9EbtkNWWdh8M/VyDuPj4voHxGP+uqp8HTGFS8lc52RkPtyHUAH6kmMp7i9CshikUA3uRXO/8Ra4d3RjEGYKu+G5VlfZmqGoc/mwLrv43AMxJA/fwlYwsZSWVuXNLhlkhySzb04UJimU3BuwU4mSz8XTq161jAUYs7nCgHgvIJS8FMozmcEIgyXxlJ/SIMilcYVT9WGVBoq7LgSauX6kf2Mx4OpRJ/WwdP6ppb92hHbA/vY33qalew1m+tmckNEXBux2ojVRqw2YmYYsce23JcymDgHngET5Clf/jQA9ph4Yq5fGbHEaX9q3qJW8bWKr1V8reJrFf9CKv49D0XWagsNn+7TmKbifQIcRDy1Lyf30k7FLYT5Fp9a/8JjELHr2hLUlqC2BLUlqC2BBkuQ7e0f2RMGSn8u8hOgpFYSAT/S32A9WRXJOVVlOFzkzUbZhMUbhUo3y8DUlqO2HLXlqC1HbTn+sOUoKvo145EnjJ9iObK7arNRm43abNRmozYbJpqNx63CWmVQrchrRV4r8lqR14rcPEX+R9PEWTVpreRrJV8r+VrJ10reKCUvugGlGEbnsonhsV6/CZtOJV1UrwdTzHMDl34QDZ2d3nTcbk37jZ7bHjec5mDSGFPiNAbE7XWmPeJMnX5yPXAt/Ct5VJS8pobhxBdyNkkV75xPZHp3CMzIwrkF36XoJk3T1t3CmgKQiuWFAEdLC3AZSkbcAMNn31taZ3xijVa6tZMOi2XyjAsC8kj8ZTRLBDJe0MC6BNKN+Z0gLReK6C3oFD+ly2+XZ7ZoibPCeLGAZ0wDPrcWfCHm/vkf8s/frZ//+fvffv7373/7/d9//s/P//r5v1bDmoHWtgTlVMuPnbWTJB11Mx5SX/XXJnXD0jAXhjfCWtKWIugdEBDSm0LveWrnFlTgXrQTCdkQeJBLgotPAtGuUagbznhJzC6J9AAlguFmTBhP4UIE0VUcgHlvqjbD34BYgmnax6qJ9owsBCfMyWKVNVzVo/qFRbN/hiHpIdjOq1b7Vatv/Uk2Blmt//t7s+P8WXgYHr2VDz+5W4DlFe2LzVfwBJj2EkyImBA4STZotrpZm/AV84XABKAIxM6j6Mz8ziaiX7nduc+5sIzvVjnzARc+j9mexFyigFuSrdVvd5rdbss5bva6SWtyVtc9BuN7RYOAMIE/kHQmlwHmE6ir8JR7Ym+WAtyNXFXw6LJC9tVt3kK68EGknxeVJAWE1xmXpI5RyONA9hEJxW/nI8O58OnAARNukITllIpSEMV/75nniclY3rz6wT8P+I00aa/92PPgPuDB8IqvNLg2hTytIuhdAMbfAykwFEcLHrJiM1srb33fhBl4IjwwjHShaMRBim1DEaLwIdChA9SzpLrISGhTuh82TbFQ804fnOYS804jy1ZNU7ezczkOn8gKVl2gGu20bDDI7VV/5hKCQXF00I69l88uJeaqN5xMUcINb6nc0yphBr2emrnsgJERMhGQJrDADu84hLKfA7p7/WC00Wgg8t3v9PG/QTS1m48++pPcGHrgF60KwykLxe63yCiIA6se3ZXEpj7amYDs37Uw2t1+HuMVlPE23LZjBL+lIQ0iE7FbgrvkDKXOI9tOGEyWQkNHkyavFAe0cw6o45wSLa2LKapkn9LgVxfsRpO5tSMyy3wR8UWaTKbBVIr2LLu5rQ7RbTsiP6UGz+icB+k5yuuxZ0dmetOTeGgUeTL45MlBoKnZy8HnD0Zg6XOe1fjcm8+LOpnQXAOUsN9D5xmb3insuWE2PA29O2zGB9C5/37Ycp67W7pgrZJwv4yHeXjhbseQOLdSvPeCGy4bPUISR6JhMi+Wm4h3PUyJF1LlGm7jGd6te4aiyrLUMdxICv6rC8x3G38hSCMpSKxIqJWD8Dfui2y9pyQuyvpeL+DL7vnKdLPe0erEHKAeL00wj4gI7Ow9bpxXarcqeQmKg8FXVLDqArVSZO4gInMnI/NuNgAqRfi2XsIbHea3tcq30QZy8xbzGt8PvXjOfPlSt/Wa8WPcm0IttNyCwxJoJK7RkfnK0Z/C0j04+HPTtjCKbFRDbzqqSnKebwVviokOWwPk/g/GkspOaUnlG+LDnw27mX+J/RuPoihQaXTQ5g1QWMUH+xxIcn8OErZ+1g6hU6oSHwmROqZlhrasgWn1t8t0OIl13CbdkZGQrw+Yn87YJCd7KIww2mH8I1K05lMWejVMEJlq6GmUBbJOeYEs8SJNEUmlsNFV2OjuXhMZ7Y8rNHQRy4Mu2I0ms4OXzJ29CbrR+3EdrRxgtHe1OR2HXdu3MybYTYrWdO8vTdah0PktrRJvNGl10nSDamsZCveaMI94FMmTyhBq+UImvj56LNd2WLZg23qzq2aTVm9Pp+mkLZSYHj5pO49tkQ4jjrPzoZBD2JdyrxJ6GnkCquAN/BYQn5VmWNo1Gku3w+63PBcLPaYaa6j6MgPsIAkju0iSvZu3zQ048mfblGxnu5Rs92FKdvPZBBXPyc6T1y78EneDZ+PujAQA9fNRt/LtK1x0It5QIRd8ZA/nixkbMx6LVwlsEs+1POkeC7BMV1+pEOuvzttWJntP4avtukKRiGS7/WzUvbxIrqWeIQzzSlzTfn2yWYmwYj/ZrIu3ibCrt5fsKvYn8rUpVYC9p2DvlcZlB5+0VdD3kCZtu6W036MjZzRvdLXyRqUUopMzxsGT2TGTzKsAZ3jYReVOr67cMZED9li2s2YB6jNd02TnTjyDbc/73HJjLa256W23tZaAnwej2UAl4viNwGNv/GtpZdjK7JmXqK8Pt+rduYdNco3ENn0/VXNRYRlvG1l9luu3PdTVVkbi80qkxwrRdpERqwC75EcF/XofuIO7R3BjFdTLnD9rrqXJQ0WMrzgo7wrdXPjj7MERrZhcNZyyhPGe5KpK8Xih+AMjm+RlPzWbPJq10MQfZpscpFmZXiYEtcP/IE25phve8yCkYYkRfqT6Vru+2LYmZ8tD2nt1ndzDrdDms3H3kkU5vTK3Z3/vfjV9WycV6p2c/L6tVG5Z7tV7WO6FXipbx8/G3ctL5R7KvSrmeKTiaMDrd7YV3u5TGNCpy1wLFrX1bNS9vOyubW9eRtzXdehrFZ3iwz/yOqP8ejN+QMaaCF9RZd19EWX9fE7ZR1lTX6Gmj6F6TcGqC1Rtlcv7IHMvJ/Nzex70dpcazSg9vIzSfQqjPJIU1d2NbDS/dLXyiza3ah/84pTyi87+a6Mp72il/B/ahNpjETQKb6GjlbRVSpmllc5rQv34EenGetF7K7FCySqtUlZ5wTx02xRMseLi7aHvwmMjK4iVbS+t2lzD4me2wenCFsOnHIZWx5jiY+yvfhlH2Ubeh7Dr09We1VSzZc4qO894q4RfAcX84VAlEgeb4N/d+9UqVYZferDznlwC09UbpncwN/KXMGMgbeGVJodPWr2vrnnyoU3tLd9tlR0utZVpeoAWvumHKpqpwkFbVcqC7a+YWldtVZUC+PJaUZ1VAmZTPq8gPnhY13M6+uoBjN7H1bZbbTZx8fBxWrOAAti+VstkNKgpXdccFI1vBDIa/H7ZqZRYgE9pjyJ46pf2neszx0YDn1IaxQ5IX+tbryp1Vma/vOZSveAVd3lZX+vpQ1Xkit2doGp2te2xAv8YQ/2MglUXqGbTtZ/TdTfOm9GU7mul9KXPv9tP2Ane8vj+tAT6eLut4FVs8dJR7ZvAe6wER6GCeloZs4p13Gsa6ZJ5tzgOK+9qJf3T81Nbdlum9dNbaqUChvjDoUrqIydn1LqXIMsi62fcCgQHnZoVSmpFXt6D3mPJOQpg24jo2kJE1xYSuuKIH1CQMi+4RpElb+R9FgcPa+F1FQcPayN/A8WuC+mNxkNH7+HvRsOahAsoYHX05kzNNbr5jgCK/HDhdZqHT9f8tasHT1fNhzUaDWsjP7nz4GHFVHnYyEtKERakHX58e4ciis8KEXDI7LFeBVUBuuqyO0aDmtIVhZE9xuMnpnRFAeyx1riuEvKKAthjPPswKV11AVsBuuLYPz5G9BL3Yzw5kJSuKA4sbAwUsAMMwCpYXx7UPXYNvDywe1NOukCtRNfAYGc7bEZTuo+I0j1EEtxDRNcuIrp2DaHr/lLQOOjqIKJrRy9djQa2k9EVoXOR1pOjkOA2IgluIaJry5AYdx/15CigPHwg83pyFKUFDb0tH0bD2sa0lar3jR5Gw9pBlPpIAgAUsDqIUpVJwI4C1i6i0oJkgw1FL0D5G8XRBOz5m+YPntKFc04Pn656D7A1GlZMxbcNvVXVRsOKImxHsAOTlY2g4Nq0HAgFsAM8VialKwpgB1q9QqNBTemKAtgBol6AAaKAfYCoF2BQesI5loB9gKg7YIBoi3yAqDtggCilNUByOF2BrijSso1WM4nzmhjATaDFAWwWwqOAdmAKZffY02MAtPs7gUMXrGb3BPQxUbaPSWZ7mCjbM0Vm91dmgISyXUyUdQqURbhL45iin/fY3YMD2g4myrYxUbaNibItTJRtYaEsEpLiIGbe04OiRKiBpe0u7+nBsVGu97VLRsPaQZTYStx+FLA6iBLRSeiOAtYupl6tLp5erR6i0q9kexwFrH1EpZpJQgsFrJqPWTca1gai8/MxtUI0EPW44Nh9wbCVVijtwgBrXrWHAdoEWBSmJqMsCmgTYFE4hxllUUCbAIsinMsoiwLaBFgUGzAZZVFAmwCLYss0oywKaBNgUSQ5MsqigDYBFkVaMqMsCmgTYFEUEmSUfSa013DbLQ3CZEY3oCSiky8smomvfjwf00BgtOPADPQO7rGdV632q1bfhjvT3537+/8HkJHL0X6SAQA=

### Operating System

Android

**Comment by yairm210** [comment]
Free cities that remove when built lead to an endless loop of the game trying to add them and them being removed, this is *not supported*
I'll add documentation regarding this
