### ISSUE TITLE
Samsung S10+: UI elements are out of bounds

### ISSUE THREAD

**Issue by amadare42** [yairm210/UnCiv#1208]
Using version 3.1.5 (downloaded from Google Play @ 2019-10-17).
![photo_2019-10-17_18-06-15](https://user-images.githubusercontent.com/3945692/67022156-71566d80-f109-11e9-9079-c83ea01d9e62.jpg)

**Comment by yairm210** [comment]
Yes, this is #1111 - we have no idea what caused it, but it seems to be solved in 3.1.6
