### ISSUE TITLE
Science points drops from +22 to +1 on Next Turn with no interim changes

### ISSUE THREAD

**Issue by jadiecee** [yairm210/Unciv#12081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.17

### Describe the bug

My Science points unexpectedly and abruptly drops to just +1 from +22 when clicking on "Next Turn".  No changes with Science/Tech assignments were done and no in-city changes were made either.

When the next turn is loaded, the +1 is in the main game window top display but the in-city views display the correct science values (e.g. my capital city has 11 science points). Unfortunately, the Tech window will reflect the +1 science and my pending research turn count went from 12 to 242. Screenshots below.

The game was started using a Random civ (Iroquois), on Warlord. 
Base ruleset: Civ V - Gods & Kings
I noticed the bug earlier when my turn count was higher  (200+) since my tech turn count was in the ridiculous 100s/200s without me adjusting science points and even after building libraries. I loaded to a previous save where the science points were fairly reasonable and continued until I noticed the science drop to just +1.

### Steps to Reproduce

1. Load the attached savegame
2. Click on 'Next Turn'
3. Main window Science points drop from +22 to +1
4. Pending Tech turns spike from 12 to 242

### Screenshots

![Screenshot 2024-08-07 15 33 47](https://github.com/user-attachments/assets/2fc59cea-0cd2-4a7d-bac6-fa61199a7994)
![Screenshot 2024-08-07 15 34 32](https://github.com/user-attachments/assets/55d84999-b127-4b78-946c-9a42d10c5fd4)
![Screenshot 2024-08-07 15 55 06](https://github.com/user-attachments/assets/397663ca-cef3-43b6-a49c-f6ae801d1e74)

### Link to save file

[Iroquois - 187 turns eh.json](https://github.com/user-attachments/files/16520079/Iroquois.-.187.turns.eh.json)

### Operating System

Android

### Additional Information

Playing on ChromeOS Version 126.0.6478.222 (Official Build) (64-bit)

**Comment by yairm210** [comment]
Did you check the stats breakdown of before and after, what's causing this change?

**Comment by jadiecee** [comment]
Hi! After checking, yes, there's a Treasury Deficit that matches the point drop.
The deficit now disappears the turn after I gain more gold from capturing barbarian camps.
However, when I was playing previously (before the latest updates and from a different savegame), even after clearing camps and getting a net positive treasury, the science total remains a +1.

Since I'm unable to reproduce the issue from this savegame, I guess we can close this issue out. I'll definitely make sure to check the stats in the future!

Thanks for the help and really appreciate your awesome effort in creating and maintaining unciv!
