### ISSUE TITLE
Saves seem broken when saving from an old save file

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#12092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.18

### Describe the bug

When there's changes to the save system, I load my old "testing" saves, and overwrite them directly (so no bad surprise of an old save being not usable anymore, later)

When trying to load one of this new save (being overwritten or not):

`The save was created with an incompatible version of Unciv: 4.12.18 (build 1035). Please update Unciv to this version or later and try again`.

### Steps to Reproduce

- Here's a save made **prior** to 4.12.18:
[AirSweep_Nuke_test.zip](https://github.com/user-attachments/files/16554210/AirSweep_Nuke_test.zip)
- Load it in 4.12.18, and save it again directly (overwrite it or create a new save).
- Try to load the new save in 4.12.18 : the message of the save being not compatible is displayed.

### Operating System

Windows & Android

### Additional Information

- Saving from a new game, or from the autosave, works correctly though.
- Loading an old save, **passing a turn**, THEN saving, works (the new save is readable).

**Comment by yairm210** [comment]
That's super weird, I can load that just fine??
Since I'm not sure what's going on, I'll revert the json changes I made and I'll try to debug this later when I have time

**Comment by yairm210** [comment]
Checked on previous versions and... apparently this save file broke a while ago and has nothing to do with current changes

**Comment by Ouaz** [comment]
> That's super weird, I can load that just fine??

Yes, it loads fine in 4.12.18.
But save directly after the save has loaded (do nothing during the turn), and the resulting new save is not readable.

That's old saves  I keep for testing purposes (translation checks or other stuff, at precise in-game moments -_found pantheon, enhance religion, upgrade, nuke, particular battles, etc_-), but I overwrite them from time to time, when there's change to the save system (in case, these saves become unreadable).
It's the first time they are not readable by overwriting them with a new build.

> Checked on previous versions and... apparently this save file broke a while ago and has nothing to do with current changes

Yes, that's what I supposed too. If I load the save, pass a turn, THEN save, the resulting new save is readable. I'll lost some testing saves, but that's not a big deal.

I guess you can close the issue if it has nothing to with the recent save system changes.

**Comment by yairm210** [comment]
I did exactly what you said, and the problem does replicate on older versions

**Comment by yairm210** [comment]
This was since solved
