### ISSUE TITLE
Multiplayer Next Turn Crash in v4.12.18 - SOLVED 4.12.18-patch1

### ISSUE THREAD

**Issue by AyamTVTR** [yairm210/Unciv#12100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.18

### Describe the bug

Hi
Ok
?
![Screenshot_2024-08-10-10-26-30-81](https://github.com/user-attachments/assets/dd1a439f-fe3a-4da2-8252-9cdda5fab113)
Ii

### Steps to Reproduce

1. Go to 'hjj'
2. Click on 'Mod'
3. Scroll down to 'name'
4. See Space

### Screenshots

![Screenshot_2024-08-10-10-26-30-81](https://github.com/user-attachments/assets/0eb9f7c5-67df-4a6b-a1bf-fa57da5bdda2)

### Operating System

Android

### Additional Information

https://github.com/user-attachments/assets/1bab35d4-42f5-4ec4-bfb8-d692307bb2f8

**Comment by yairm210** [comment]
How do I unsubscribe from your blog
