### ISSUE TITLE
ошибка при пропускании хода происходящая с 295 по 390 ход

### ISSUE THREAD

**Issue by TKalachinsky** [yairm210/Unciv#12101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.17 (build 1002)

### Describe the bug

ошибка при пропускании хода от 295 до 390

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Link to save file

[lasterror.txt](https://github.com/user-attachments/files/16569722/lasterror.txt)
надеюсь, это то

### Operating System

Windows

### Additional Information

баг вылетает во всех мирах, от 295 до 390 хода может возникнуть. это происходит, какие бы я не включал настройки

**Comment by yairm210** [comment]
This is the OneTimeSpiesLevelUp error that was since fixed
@TKalachinsky The solution is to upgrade the game
