### ISSUE TITLE
Zip link is invalid

### ISSUE THREAD

**Issue by Ms74-am** [yairm210/Unciv#12118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.7.5

### Describe the bug

Locating zip file to data faied
Then, I copied code-> zip link -> back to unciv download by url. But it is invalid
How can i play mod? Please

(Other mod is valid in this way)

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'
Idont know this blank

### Screenshots

D

### Operating System

Android

**Comment by Ms74-am** [comment]
Playstore unciv is 4.12.19

**Comment by yairm210** [comment]
I have no idea what you actually tried to download?
Download by URL is for e.g. https://github.com/yairm210/Unciv-IV-mod/archive/refs/heads/master.zip 
Or the repo, like https://github.com/yairm210/Unciv-IV-mod

**Comment by Ms74-am** [comment]
> I have no idea what you actually tried to download? Download by URL is for e.g. https://github.com/yairm210/Unciv-IV-mod/archive/refs/heads/master.zip Or the repo, like https://github.com/yairm210/Unciv-IV-mod

Thank you very much! Im not good at english 
I will try second

**Comment by Ms74-am** [comment]
Can you give me civ5 repo link? Civ4 is valid but civ5is not valid

**Comment by Ms74-am** [comment]
https://github.com/yairm210/Unciv/archive/refs/heads/master.zip

This link is not valid onlyciv4 is valid

**Comment by Ms74-am** [comment]
They say invalid mod structure

**Comment by yairm210** [comment]
https://github.com/yairm210/Unciv/archive/refs/heads/master.zip is a link to the *main repository*
That's not a mod, that's the code to the actual game, *inside which* you can load other mods
Civ V rulesets are available in-game without external mods
