### ISSUE TITLE
Feature request: Mod request?

### ISSUE THREAD

**Issue by zxw24** [yairm210/Unciv#12120]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

OK

### Related Issue Links

Hello, great game author, you are one of the best people I know. It is because of you that I am able to play such a fun and lightweight civilized game. I have always wanted to wish you well, because you are like a game saint in my heart. Today, I had the opportunity to log in and I would like to ask if it is possible to update a new entry. This morning, I have been working on a mod called Sacrificial Dragon Clan. Yes, he is following the Sacrificial Flow, but unfortunately, you did not reduce the city's population by providing units, buildings or resources, or by building this unit to reduce the population. I feel very uncomfortable about this and I am also trying to find bugs in it to see if there is a way to block this. Unfortunately, I failed with the entry. I hope to have some updated class entries in the next version. Thank you to all the authors who have contributed to Unciv, Wishing them a lifetime of peace and blessings like the East China Sea.

### Desired Solution

OK

### Alternative Approaches

OK

### Additional Context

OK

**Comment by yairm210** [comment]
I'm not sure what you're actually asking for. There's a trigger for reducing population in a city when building a unit/building - "[-1] population [in this city]" - and that sounds like what you need

**Comment by AutumnPizazz** [comment]
Your language is very reminiscent of something that has been machine-translated from Chinese. To get straight to the point, you are looking for a unique regarding the change in population numbers, and the great Yairm210 has already provided you with the answer.

**Comment by yairm210** [comment]
👍🏿
