### ISSUE TITLE
Invalid mod archive structure

### ISSUE THREAD

**Issue by Ms74-am** [yairm210/Unciv#12122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.19

### Describe the bug

![Screenshot_20240817_085023_Unciv](https://github.com/user-attachments/assets/be6101ce-a034-4c3b-9098-ee11e70dcd42)

Downloading-> invalid mod archive structure

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![Screenshot_20240817_085023_Unciv](https://github.com/user-attachments/assets/18377b44-9279-4a6d-8c2d-207649a2f115)

### Operating System

Android

**Comment by yairm210** [comment]
Answered in #12118 - the main game repo is not a mod
