### ISSUE TITLE
Vanilla missing features recap

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#1213]
- [ ] Civilization: Spain
- [ ] Civilization: Aztec
- [ ] Civilization: Siam
- [ ] Civilization: Mongolia
- [ ] Civilization: Denmark
- [ ] Civilization: Inca
- [ ] Civilization: Songhai
- [ ] Civilization Intro Quotes
- [ ] Diplomatic Victory
- [ ] Time Victory
- [ ] Scores
- [ ] Wonder: Mausoleum of Halicarnassus
- [ ] Wonder: Temple of Artemis
- [ ] Wonder: Statue of Zeus
- [ ] Wonder: Brandenburg Gate
- [ ] Wonder: United Nations (triggers voting for a Diplomatic Victory)
- [ ] National Wonder: National Treasury (requires Market in all Cities)
- [ ] National Wonder: National Epic (requires Monument in all Cities)
- [ ] National Wonder: National College (requires Library in all Cities)
- [ ] Social Branch: Patronage
- [ ] Social Branch: Order
- [ ] Anarchy (no Growth, Production and Science for one turn) - can occur when you unlock a policy tree incompatible with another policy tree already unlocked
- [ ] Choosing Piety when you've already adopted Rationalism (or viceversa) causes Anarchy
- [ ] Choosing Order when you've already adopted Freedom (or viceversa) causes Anarchy
- [ ] Choosing Freedom when you've already adopted Autocracy (or viceversa) causes Anarchy
- [ ] Choosing Autocracy when you've already adopted Order (or viceversa) causes Anarchy
- [ ] Technology: Stealth
- [ ] Technology: Mass Media
- [ ] Technology: Advanced Ballistics
- [ ] Technology: Nuclear Fusion
- [ ] One-City Challenge
- [ ] No Ancient Ruins
- [ ] No City Razing
- [ ] Disable uniques
- [ ] Complete Kills (to destroy a Civilization, you must eliminate all their cities AND units)
- [ ] Galley (Barbarian unique unit, replaces Trireme)

**Comment by yairm210** [comment]
Most of these are NOT VANILLA.

**Comment by Smashfanful** [comment]
Which of these are not in Vanilla?

**Comment by yairm210** [comment]
The autocracy vs order vs freedom
All the 'Wonders of the ancient world' (that's a DLC, later added to BNW)
A lot of the advanced starting features seem pretty pointless, not sure which of them were or were not in Vanilla
I think last of the reason the list is confusing is because it has everything on the same level. There's categories, and several on each category

**Comment by Smashfanful** [comment]
Actually, Autocracy vs Order vs Freedom is in Vanilla.
All these advanced starting features are from Vanilla (I saw it myself)
And who cares if Wonders of the Ancient World is a DLC? We've put Babylon and Polynesia in UnCiv, and they were DLCs
