### ISSUE TITLE
Feature request: Make XP for promotion programmable

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#12151]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

You see, unciv or civ5 define the XP for promotion as 10, 20, 40, 80... But I wish it programmable in mod:
Add a property in ModOptions.json like
```json
{
    "isBaseRuleset": true,
    "constants": {
        "baseXPforPromotion": 10,//default as 10
        "incXPperPromotion": 10,//default as 0
        "mulTimeXPperPromtion":1.50//default as 2.00
    }
}
```

### Desired Solution

See above.

### Alternative Approaches

See above.

**Comment by AutumnPizazz** [comment]
Also in #3242

**Comment by yairm210** [comment]
Definitely a modding request
