### ISSUE TITLE
City overview not updating when city properties are changed from within overview

### ISSUE THREAD

**Issue by stefanct** [yairm210/Unciv#12150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.19

### Describe the bug

I have noticed that if one opens the city view via the "Cities" tab of the overview and changes the output of the city, the change is not reflected in the "Cities" tab after exiting the city afterwards. If I would have to guess, I would say that the data of the "Cities" tab is simply not updated when returning to it but only when it's created initially by opening the overview. I am pretty confident that it is reproducible but I have not extensively tested it out... just noticed it a few times during my initial games. I presume that tile/resource changes etc. are also not updated but since this is more subtle I probably missed it.

### Steps to Reproduce

0. Make sure to have at least one city.
1. Go to the "Cities" tab in the overview.
2. Click on a city's name to open its view.
3. Change the "Current construction" to something different.
4. Exit the city view to return to the overview.
5. Notice that the construction column still shows the previous construction.
6. Exit the overview and open it again.
7. Notice that the construction is now correct.

### Link to save file

Will update if not easily reproducible.

### Operating System

Android

**Comment by stefanct** [comment]
Thank you! I am a bit sad that you don't take donations. At least I couldn't find any references to donating money to the cause - neither here nor in the discord instance. Would that be an appropriate suggestion in the respective discord channel or a here as a bug or not at all because you hate money? :)

**Comment by yairm210** [comment]
It's a little bit of both :)
You can donate to https://www.paypal.me/yairm210 to help pay for the Unciv multiplayer server, if you really want to
But in general I prefer you would support other creators, because I have a full time job and am not lacking funds the way many other creators are
