### ISSUE TITLE
Feature request: Make circular technology better

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#12152]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

In the late stages of the game, Science points become nearly worthless, and researching future technologies yields no tangible benefits. Therefore, I propose the introduction of new uniques to replace the existing `Can be continually researched`, specifically `Can be continually researched with an increasing cost of [positiveAmount] for [amount] times`.
This new uniques should support some non-trigger buff, like '[+5]% [Gold]' and so on.

### Desired Solution

See above.

### Alternative Approaches

See above.

**Comment by AutumnPizazz** [comment]
Also in #3242

**Comment by AutumnPizazz** [comment]
For example, `Can be continually researched with an increasing cost of [5000] for [10] times` means that each iteration will increase the cost of research by 5000 and will iterate at most 10 times.
And `for [-1] times` means it can be researched forever.

**Comment by yairm210** [comment]
You can add any unique to the continually researched tech already
This is definitely a #3242 request though
