### ISSUE TITLE
Feature request: Consider changing autoAssignCityProduction default to false

### ISSUE THREAD

**Issue by teohhanhui** [yairm210/Unciv#12169]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Having automatic constructions in the city is really surprising / confusing for new players like myself.

### Desired Solution

Change `autoAssignCityProduction` default to false.

### Alternative Approaches

N/A

**Comment by yairm210** [comment]
I'll make this a discord poll

**Comment by yairm210** [comment]
Done, we'll go with the poll results (3 days)

**Comment by yairm210** [comment]
<img width="490" alt="image" src="https://github.com/user-attachments/assets/00336d1f-bb56-4b24-889d-8ec5593896cb">

By a narrow margin, but we'll be changing the default to False
