### ISSUE TITLE
ConcurrentModificationException in automation - SOLVED 4.13.3

### ISSUE THREAD

**Issue by OksBlade** [yairm210/Unciv#12161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.1 (build 1040)

### Describe the bug

I pressed the next move and an error occurred. Re-entry does not help, the game crashes on the same turn, although it works.

### Steps to Reproduce

Pressed the next move, loading, error.

### Link to save file

![Screenshot_2024-08-27-06-09-13-663_com unciv app](https://github.com/user-attachments/assets/dd0c564b-8916-4685-962d-9f300ade2db2)
![Screenshot_2024-08-27-06-09-19-751_com unciv app](https://github.com/user-attachments/assets/001a63dd-e5eb-4438-ae0d-da5fa563a384)
![Screenshot_2024-08-27-06-09-26-486_com unciv app](https://github.com/user-attachments/assets/ba987fed-6ebe-4c46-86b4-dd8ee1fae171)
![Screenshot_2024-08-27-06-09-29-405_com unciv app](https://github.com/user-attachments/assets/f1873430-d749-4984-8c86-c669b5de4c74)

 

### Operating System

Android

**Comment by yairm210** [comment]
Same as #12159
