### ISSUE TITLE
some of citties didnt demand resources for celebarating we love the king day

### ISSUE THREAD

**Issue by CSHARPDEVELOPERS8358** [yairm210/Unciv#12177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.3

### Describe the bug

some of citties didnt demand resources for celebarating we love the king day

### Steps to Reproduce

view city of Akkad. it didnt demand any resources for more that 200 turns

### Screenshots

https://drive.google.com/file/d/161qHfpz_qd6ZQLfxou0X-fFqF04hfaLN/view?usp=sharing

### Operating System

Android

**Comment by yairm210** [comment]
It's a random event, not a bug

**Comment by CSHARPDEVELOPERS8358** [comment]
I think it is a bug. 45 cities doest demand any resources during more than 300 turns and only 12 cities coninusely demand only gold ore and celeberating we love the king day.

**Comment by yairm210** [comment]
I'll look into iut

**Comment by yairm210** [comment]
Checked this, and what's going on is there are no suitable luxuries left!
When Akkad's "demand resources" timer times out, we try to find a luxury to demand, but there's nothing suitable so we keep going
What does seem to be problematic is that there are cities *demanding* Gold Ore, when it's a resource that you *already have*, so there is a bug here of some kind

**Comment by yairm210** [comment]
What's happening is since they can't find a new resource to demand they stick with the old one
There's a non-trivial design decision here I'll need to think about 🤔

**Comment by yairm210** [comment]
Various options polled in Discord, will finalize in 3 days

**Comment by CSHARPDEVELOPERS8358** [comment]
I mention that if my country has all luxury resources then no new city demand resources and only old cities that previously celeberating we love the king day and there days fininshed, only demanding for resources.
I notice this issue when i lost control of one resources and saw that, new cities start demanding resources
