### ISSUE TITLE
Great prophet purshased with faith will have civ founding religion instead of city religion

### ISSUE THREAD

**Issue by odrevet** [yairm210/Unciv#12174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.0-patch1

### Describe the bug

When purchase a great prophet with faith, the unit should have the dominant religion of the city. 
however the unit have civ founded religion
 

### Steps to Reproduce

Babylon with Judaism as religion
Go to Berlin (Islam) or Hamburg (Christianity) and buy a great prophet 
A popup will warn, that the city do not follow civ founded religion, click "Purshase"
The great prophet has Judaism religion instead of the religion of the city 

### Link to save file

[babylon.json](https://github.com/user-attachments/files/16804092/babylon.json)

### Operating System

Android

**Comment by Caballero-Arepa** [comment]
That's intended behaviour

**Comment by RealBamboolord** [comment]
It is even stated in the description of the unit that it takes over the civ's religion over the one in the city

**Comment by odrevet** [comment]
you both are right. Then I guess the warning popup is misleading when a great prophet is purchased and should be removed (same warning popup as Missionary and Inquisitor)
