### ISSUE TITLE
Happiness of buildings from policies is handled differently

### ISSUE THREAD

**Issue by vincemolnar** [yairm210/Unciv#12180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.patch1

### Describe the bug

I noticed that in long and large games, buying a happiness-related building (including courthouse) takes a long time, but it does not happen with buildings that give happiness because of a policy or wonder (e.g. Castle, which can give happiness after building Neuschwanstein or adopting a policy from the Honor branch). 

### Steps to Reproduce

1. Have a large civilization with a lot of cities
2. Buy a happiness related building (e.g., Theater)
3. UI will be blocked for a few seconds
4. This does not happen when you buy a building that gives happiness due to a policy or wonder (such as Castle after building Neuschwanstein or adopting the corresponding policy from the Honor branch).

### Operating System

Android

### Additional Information

Digging into the code, the reason for this is most probably here, where (due to being a global stat) the game iterates through all the cities (almost a hundred in my game) and reassigns the population everywhere:
https://github.com/yairm210/Unciv/blob/938cd9008a75a3fc47c73533f91525600d019934/core/src/com/unciv/logic/city/CityConstructions.kt#L547

This is controlled by the function isStatRelated, which checks a couple of cases, but it seems it does not check policies or wonders:
https://github.com/yairm210/Unciv/blob/938cd9008a75a3fc47c73533f91525600d019934/core/src/com/unciv/models/ruleset/Building.kt#L501

The function reassignPopulationDeferred is deferred only in the sense that it will wait for the player's turn, but if we buy for gold, this will happen immediately, every time - hence the long delay when the player has a lot of cities:
https://github.com/yairm210/Unciv/blob/938cd9008a75a3fc47c73533f91525600d019934/core/src/com/unciv/logic/city/City.kt#L327

So, even though my original problem was that it takes a long time to buy happiness buildings for gold, the real issue seems to be that the long operation is not performed for buildings that give happiness due to policies or wonders. I did not specifically verify this, because it would be harder to reproduce (requiring a below-zero happiness), but the code seems to imply it.

For the performance issue, one workaround could be that even if it is the player's turn, only the current city would reassign population, and the rest would do this at the end of the turn or when the city is opened. This might cause an incorrect value on the top of the screen, but will not affect the gameplay.

**Comment by yairm210** [comment]
Well researched! 👍🏿 
There are indeed 2 issues - the first is that the "check related stats" is lacking, the second is the "reassign population for all cities" is a performance problem.
