### ISSUE TITLE
Feature request: Pick "Brand Colors" for Flathub

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#12198]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

"Brand Colors" were introduced for flathub, and are required to be featured on the front page of flathub.org.
As visible on the front page, these colors are used as background colors for the logos.

Here are a few options I could think of (I took the screenshots by changing the listing to look like Unciv in the front page, then tweaked the colors)

### Light theme

| Color | preview |
|--------|--------|
| `#8ec3f2` (lightened from the central UI block/unit info)| ![image](https://github.com/user-attachments/assets/ae2f6ec0-b363-41c4-a09d-b755c3d8b151)|
| `#fbeb90` (desaturated from the smiley face in the logo) | ![image](https://github.com/user-attachments/assets/c4f23e89-d758-48bf-a1a8-27c33da420d1) |
| `#8d9dfe` (Science background from the icon) | ![image](https://github.com/user-attachments/assets/a28e97e5-87d2-40da-aae0-59b70cc65f67) |

### Dark theme

| Color | preview |
|--------|--------|
| `#000032` (Game background, as suggested by @sr66139p in #11375 )| ![image](https://github.com/user-attachments/assets/db84e70a-655f-40a5-8537-7fca3df06a7c) |
| `#00800d` (Green from the apple in the icon) | ![image](https://github.com/user-attachments/assets/547375d3-5c2e-4436-bafc-b52c1cbd2c2f) |
| `#8c60fe` (Music background from the icon) | ![image](https://github.com/user-attachments/assets/3f14bd1e-3e08-432e-94a6-a8d29dd23a32) |

Personally, I think I have a slight preference for the last two options, as they maintain a similar hue across dark/light themes.

### Related Issue Links

Discussed briefly in #11375

### Desired Solution

We should pick two hex values among the ones suggested above, or suggest others.

### Alternative Approaches

I can pick two myself; the choice can always be altered later.

**Comment by yairm210** [comment]
I like the `#8c60fe` option - having the color of "uncivilized" be the color of the culture icon has a cute tongue in cheek element to it ;)
Let's go with that, we can always change it later

**Comment by Roman19S** [comment]
I like #fbeb90. It looks the most legible to me and seems to me like it would be less overused by other apps

**Comment by MayeulC** [comment]
Merged in https://github.com/flathub/io.github.yairm210.unciv/pull/607

I went with your picks; we can always change this later.
