### ISSUE TITLE
You can choose resources if it is LOW MEDIUM OR HIGH

### ISSUE THREAD

**Issue by MrUldiggg** [yairm210/Unciv#1219]

**Comment by UniqueActive** [comment]
I would really like this too. When switching from Warlord to Prince, there is a significant drop in resources (it feels) and my girlfriend and I are not big fans of that :)

**Comment by alextfish** [comment]
Ah! I thought it seemed like there were fewer resources on the board in my Prince games! I half-thought it was just my imagination. I'd definitely like this.

**Comment by amarzot** [comment]
Hey, just submitted a PR to support resource levels. When looking through the code it didn't seem like difficulty had anything to do with how resources spawned, so it probably just felt that way.

**Comment by amarzot** [comment]
Looks like this will be handled in #1806
