### ISSUE TITLE
Malicious use of the new kick / skip multiplayer tools

### ISSUE THREAD

**Issue by AlatarTheYoung** [yairm210/Unciv#12197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.5

### Describe the bug

With just a multiplayer game ID, anyone can add the game in the multiplayer and kick / skip an inactive player, even if :
- The "kicker" is not a player
- The game doesn't allow spectators
- The time limit (24h for skip, 48h for kick) can also be bypassed by changing the clock in the terminal in the future.

### Steps to Reproduce

1. Find a multiplayer game ID (if possible without "anynone can spectate")
2. Add it in the multiplayer game interface
3. Change the time to 3 days in the future on your device
4. See the options to kick and skip appear

### Operating System

Android

### Additional Information

I understand that the game files are not really protected, but currents attacks require at least :
- technical knowledge to get player id from the game id
- a change of the malicious player id in the advanced tab of the game
With this behavior, only the game id and changing the date on the terminal are required.

**Comment by yairm210** [comment]
This is true for all multiplayer actions 
I'm open to suggestions, but if your suggesting disabling this feature my answer is no

**Comment by AlatarTheYoung** [comment]
I requested the feature, and it is great, thanks a lot for it, no need to disabling it.

My suggestion would be to enable the kick / skip buttons only when the "kicker id" is already in the game as player or observer.
That would :
- block an attacker with only the knownledge of the game id and no technical knowledge at all (beside changing android date)
- keep the existing vulnerability (ID usurpation or direct game file modification), but this one is pretty hard to fix without major change.

**Comment by yairm210** [comment]
Sure, doable 👍🏼

**Comment by AlatarTheYoung** [comment]
Thanks a lot for the (free) work on this game to you and the team 
!
