### ISSUE TITLE
TriggerUponExpendingUnit on a belief fails to trigger

### ISSUE THREAD

**Issue by armed-and-grangerous** [yairm210/Unciv#12236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.10

### Describe the bug

TriggerUponExpendingUnit, as the name implies, is meant to trigger when a unit is expended.
https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/unique/UniqueType.kt#L918
```
    TriggerUponExpendingUnit("upon expending a [mapUnitFilter] unit", UniqueTarget.UnitTriggerCondition),
```

This is successfully used in popular mods such as Alpha Frontier.
https://github.com/carriontrooper/Alpha-Frontier/blob/main/jsons/Policies.json#L394
```
					"Gain [50] [Science] <upon expending a [Great Person] unit> <(modified by game speed)>"
```
https://github.com/carriontrooper/Alpha-Frontier/blob/main/jsons/Policies.json#L540
```
					"Gain [50] [Culture] <upon expending a [Great Person] unit> <(modified by game speed)>",
```

This works fine when TriggerUponExpendingUnit is attached to a policy. However, TriggerUponExpendingUnit can also be attached to beliefs. This is *un*successfully used in popular mods such as Alpha Frontier and Deciv.
https://github.com/SpacedOutChicken/DeCiv-Redux/blob/main/jsons/Beliefs.json#L409
```
			"Gain [100] [Faith] <upon expending a [Great Person] unit> <(modified by game speed)>",
			"Gain [20] [Culture] <upon expending a [Great Person] unit> <(modified by game speed)>"
```
https://github.com/carriontrooper/Alpha-Frontier/blob/main/jsons/Beliefs.json#L513
```
		"uniques": ["Gain [50] [Faith] <upon expending a [Great Person] unit> <(modified by game speed)>"]
```
There's no obvious reason why this wouldn't work exactly the same way, and it's accepted from the mods without any error message. However, when Great Person units are expended, the trigger does not trigger. No Faith/Culture is gained.

### Steps to Reproduce

1. Download https://github.com/armed-and-grangerous/Deciv-2/tree/hacked-to-show-bug. It's just Deciv hacked to give a religion immediately. Really the only part that matters is https://github.com/armed-and-grangerous/Deciv-2/blob/hacked-to-show-bug/jsons/Beliefs.json; https://github.com/armed-and-grangerous/Deciv-2/blob/hacked-to-show-bug/jsons/Policies.json is changed just to show that everything works as expected for policies.

2. Start a new game as Cult of Ignis. (They'll start with the Theocracy policy, which yields Gold when a Great Person is expended.)

3. Found city and Found Pantheon. Pick Religious Settlements (chosen arbitrarily, just to give an immediate Great Prophet).

4. Found a Religion. Notice that the Theocracy policy yields Gold upon expending the Great Prophet, as expected.

5. Choose the Interfaith Dialogue founder belief. This will provide another Great Prophet (as expected), and says it will provide Science when that Great Prophet is expended.

6. Enhance your religion. Notice that the policy still yields Gold, as expected, but the Interfaith Dialogue founder belief fails to yield Science.

7. Choose the Funeral Rites enhancer belief. This will provide another Great Prophet (as expected), and says it will provide Culture and Faith when that Great Prophet is expended.

8. Create Oracle to immediately expend the Great Prophet. Notice that the policy still yields Gold, as expected, but the Funeral Rites enhancer belief fails to yield either Culture or Faith.

### Operating System

Linux

### Additional Information

I really have no idea why this happens. Policies are checked literally right next to where beliefs are checked.
https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/logic/civilization/Civilization.kt#L549
```
    fun getTriggeredUniques(
        ...
        if (religionManager.religion != null)
            yieldAll(religionManager.religion!!.founderBeliefUniqueMap.getMatchingUniques(trigger, stateForConditionals))
        yieldAll(policies.policyUniques.getTriggeredUniques(trigger, stateForConditionals))
```
I definitely don't understand what-all goes on inside the Religion object, but it does look like founderBeliefUniqueMap is indeed the thing that getTriggeredUniques() is supposed to be checking.
https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/Religion.kt#L58
```
    private fun updateUniqueMaps(){
        followerBeliefUniqueMap = UniqueMap(mapToExistingBeliefs(followerBeliefs).flatMap { it.uniqueObjects })
        founderBeliefUniqueMap = UniqueMap(mapToExistingBeliefs(founderBeliefs).flatMap { it.uniqueObjects })
    }

    fun addBeliefs(beliefs: Iterable<Belief>){
        for (belief in beliefs){
            when (belief.type){
                BeliefType.Founder, BeliefType.Enhancer -> founderBeliefs.add(belief.name)
                BeliefType.Pantheon, BeliefType.Follower -> followerBeliefs.add(belief.name)
                else -> continue // 'None' and 'Any' are not valid for beliefs, they're used for internal purposes
            }
        }
        updateUniqueMaps()
```

That said, it would really surprise me if these enhancer beliefs never worked and nobody but me ever noticed. So I view https://github.com/yairm210/Unciv/commit/1da5410324fe52970dd5dff7ccc358f15f1a5b3b#diff-d9dbe4725a8c8f9bc69b9b4b1c2cfcca1cd63e14239aa9b48ba5f3bcb128ba60 with deep suspicion.

Incidentally, I assume there's a reason why `getMatchingUniques()` is called on `founderBeliefUniqueMap`, but `getTriggeredUniques()` is called on `policyUniques` (which is also a UniqueMap)?

**Comment by yairm210** [comment]
Looks like you really went deep here!
And your final observation is the key - *all of those* should be getTriggeredUniques, the getMatchingUniques was the bug :)
