### ISSUE TITLE
Modding Bug: The new "upon gaining/losing promotion" UnitTriggerCondition don't work

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#12247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.11

### Describe the bug

I was testing the new "upon gaining/losing [promotion] promotion" uniques. And after testing, I found that these 2 uniques doesn't work. The UnitTriggerCondition fails to trigger its attached Triggerable unique. In the file I've uploaded below, I am trying to make a self-triggering cooldown system (also added other failing test uniques).

I feel like this is the correct way to using it, but please tell me if I'm using the uniques not as intended and how to use it correctly if that's the case. 

I've also tried placing the uniques in both the unit itself & the promotion with no differing result.

I've added commentary in the uploaded UnitPromotion Test file to better explain what I'm trying to do with each unique.

Thank you for the great work.

UnitPromotion Test File:
[UnitPromotion Test.zip](https://github.com/user-attachments/files/17175671/UnitPromotion.Test.zip)

### Steps to Reproduce

1. Play with Babylon
2. Using the "Test" unit, activate Chameleon Cloak
3. See that it doesn't gain the "Chameleon Cloak Cooldown" promotion as coded
4. Also try to attack enemy units, and see that Test unit doesn't get the Drill II and Shock II promotion as coded
5. For extra, remove some of the commented out uniques and see that they also fail to trigger

### Screenshots

Step 2. Activate Chameleon Cloak on Test unit
![image](https://github.com/user-attachments/assets/4f81e1a5-56dc-4985-a05c-47f64c226880)

### Operating System

Windows

**Comment by yairm210** [comment]
That's a Status, not a Promotion
We can make that work as well but that's a request not a bug

**Comment by yairm210** [comment]
Now that I think about it Status should definitely have a different unique than Promotion
