### ISSUE TITLE
Feature request: allow mod download from other locations than GH

### ISSUE THREAD

**Issue by starenka** [yairm210/Unciv#12257]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Allowing mod downloads from any url will be nice for mod development (one does not need to commit and push unfinished work to public repo). Testing changes will be much easier imo. 

f.e one would `cd /prac/unciv-bohemia && zip -r -u unciv-bohemia.zip *; python -m http.server -b 127.0.0.1` and then just make the game download the mod from http://127.0.0.1:8000/unciv-bohemia.zip 

if is there an easier way to test mods, i'm really sorry, but haven't seen it in the docs. (yes, i'm aware of the fact i can just make a branch for the testing but, still the feedback loop is much shorter this way)

### Desired Solution

see problem description

### Alternative Approaches

see problem description

**Comment by yairm210** [comment]
If you're working on Desktop, you can create your git repo *inside* the game's mods folder so it'll always be there - that's what I do :)

If you're on Linux (as appears from the command) you can create a softlink in the mods folder to your existing repo 

Download zip seems to work - if it doesn't for you, please provide an example

**Comment by starenka** [comment]
awesome! thanks, that was actually the stuff i came for. where's the mod
directory (im running it via snap image :/ ) ?
---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by starenka** [comment]
ok found it. it's `~/.var/app/io.github.yairm210.unciv/data/unciv/mods` for the flatpak dist. thanks all!

**Comment by yairm210** [comment]
Yes, in options - locate mod errors there's a "reload mods" button
