### ISSUE TITLE
Unique Ability does not work

### ISSUE THREAD

**Issue by ThunderWasTaken** [yairm210/Unciv#12283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.7.5

### Describe the bug

The unique ability "Empire enters golden age <after generating a Great Prophet>" does not work.

### Steps to Reproduce

1. Download the mod (https://github.com/ThunderWasTaken/other-historical-civs)
2. Load the save
3. Next turn
4. See that the unique ability for the civ does not trigger

### Link to save file

https://hastebin.skyra.pw/raw/viwijijiha

### Operating System

Android

**Comment by yairm210** [comment]
You're not taking over any city, what exactly do you expect to happen...?

**Comment by yairm210** [comment]
Oh you put 'after generating a great prophet'
That's a *conditional* not a *trigger*
In egenral I don't like to have to guess what's going on, I have enough on my plate as it is, please provide much more detailed "error" descriptions so I don't need to go searching
