### ISSUE TITLE
Military Academy XP bonus doesn't appear to work

### ISSUE THREAD

**Issue by Marzek3** [yairm210/UnCiv#1228]
With barracks, armory and military academy, the bonus does not reach 45 on new units.

**Comment by yairm210** [comment]
Works for me, can you send me the game data for one that doesn't?

Menu, save game, copy to clipboard, paste

**Comment by yairm210** [comment]
Okay, since this doesn't seem to actually be happening, I'm closing it until evidence to the contrary appears
