### ISSUE TITLE
Add remaining units

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#123]

**Comment by yairm210** [comment]
A lot of this is super basic - go to Civ V wiki, see the basic unit stats, add to the json. But it's time consuming.

**Comment by Filius-Patris** [comment]
Is UnCiv/android/assets/jsons/Units.json the only Json, which needs to be edited, or is there some other Json (eg. in the ios directory) which needs to be edited?

**Comment by yairm210** [comment]
That's the only one, but
A. There are some techs that currently don't exist in the tech tree (steel, gunpowder) for advanced units
B. Each unit needs an icon in Assets/UnitIcons

**Comment by Filius-Patris** [comment]
Should the contents be based on Civ V (original), Gods & Kings or Brave New World?

Also, should the tech "Agriculture" be added?

**Comment by yairm210** [comment]
So far I've gone with the information in civilization. Wikia.com, it seems to be the most thorough

As for the techs, they're based on the original Civ V tech tree (update .332 to be exact)

Sunday, 03 June 2018, 05:29p.m. +03:00 from Filius-Patris notifications@github.com<mailto:notifications@github.com>:


Should the contents be based on Civ V (original), Gods & Kings or Brave New World?

Also, should the tech "Agriculture" be added?

**Comment by yairm210** [comment]
Thanks for this!
There are a couple of pain points for units:
One is finding a good image =\ (I usually use https://thenounproject.com)
Another is implementing the unique abilities in the code
A third is that (currently) not all of the technologies actually exist 0_0 (I started making this game without units and so removed all "extra" technologies that dealt solely with combat)
So it's not quite as simple as copy-paste
Also, expanding the units is pretty far down the todo list as of now =\

**Comment by Am-per-Sand** [comment]
Therefore I don't expect to see these new units in games only after you paste them into your file. But hope to see them some day when the code and images are ready for them. 
- I noticed you added the _range_ property. Is it necessary to code it when it equals _2_?
Anyway, please derive from https://github.com/Am-per-Sand/unciv/blob/master/units.json, I'll try to enhance it in the following days.

**Comment by yairm210** [comment]
Range for ranged units defaults to 2, so you don't need to specify it
________________________________

**Comment by Am-per-Sand** [comment]
include available promotions in _uniques_?

**Comment by Am-per-Sand** [comment]
include available promotions in uniques?

PS. Found it: they're included in a separate file https://github.com/yairm210/UnCiv/blob/master/android/assets/jsons/UnitPromotions.json

Is _obsoleteTech_ optimal choice? How about the code checking for value of the _upgradesTo_ property and then checking if such a unit (exists and) has _requiredTech_ property and such a technology is currently available? If it is then the unit is obsolete? Or may be it is better to have a redundant property?

Update: All internation land & air units have their properties in json and added some unit icons

**Comment by yairm210** [comment]
In the original game, even if a unit can upgrade out doesn't mean you can't train the previous
For instance horseman upgrades to Knight
But since it has a higher movement than Knight,
It only becomes obsolete after lancer, which has the same movement as it, exists
Also, warrior upgrades to swordsman, but if you don't have iron then you can't train it, so it doesn't get obsoleted until you can train spearman I think?

Tuesday, 10 July 2018, 10:42p.m. +03:00 from Am-per-Sand notifications@github.com<mailto:notifications@github.com>:


include available promotions in uniques?

PS. Found it: they're included in a separate file https://github.com/yairm210/UnCiv/blob/master/android/assets/jsons/UnitPromotions.json

Is obsoleteTech optimal choice? How about the code checking for value of the upgradesTo property and then checking if such a unit (exists and) has requiredTech property and such a technology is currently available? If it is then the unit is obsolete? Or may be it is better to have a redundant property?

Update: All internation land & air units have their properties in json and added some unit icons

**Comment by Am-per-Sand** [comment]
I notice you added the Ballista for Romans. Are you going to add Legion?
Do you still need any help in adding unit properties and icons?

**Comment by yairm210** [comment]
#566 is a subgroup of this, since this issue was not well defined (no clear DoD)
