### ISSUE TITLE
Can no longer aquire tiles from nearby cities.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#1231]
![Screenshot_20191024_141911_com unciv app](https://user-images.githubusercontent.com/6846049/67458643-4f10a280-f669-11e9-8360-cd0cf49c70bb.jpg)

**Comment by Emirrian** [comment]
Yes, I can confirm it. Very annoying.

**Comment by ninjatao** [comment]
By narrowing down commits, I believe this problem happened in commit 33805ca6f8f1c4d3a3cc1b4c6825d3c06e57f030.

**Comment by ninjatao** [comment]
@yairm210 Any idea why this might happen? It's quite frustrating.

**Comment by yairm210** [comment]
Nope, needs debugging
