### ISSUE TITLE
Civ5 variance: City roads in civ5 are auto-built, free, and remove hill movement cost

### ISSUE THREAD

**Issue by legacymtgsalvationuser69544** [yairm210/Unciv#12311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.13

### Describe the bug

In civ5 building a road next to a city automatically creates a free Road in the city tile. So if you have 3 cities connected by 6 road improvements you'll be able to see a road improvement in each city as well but there will be no cost for the city ones.

### Steps to Reproduce

1. Build 3 cities on hills with hills next to them
2. Build roads between the cities

Expected results:
When a road is built next to a city the city automatically gets a free road.

Actual results: Cities do not get free roads in Unciv

3. Check unit move cost between hill city road and hill road

Expected Results:
Units can move to hilled cities from unroaded tiles as if they were moving from a roaded tile and only use .5 movement points  (with basic roads)

Actual results:
Units moving to hilled cities from unroaded tiles use 2 movement points

### Screenshots

![romenyesroadsmove](https://github.com/user-attachments/assets/23a67746-403d-4e33-b2ed-062063d18dad)

### Operating System

Android

### Additional Information

This is just a variance in behavior from civ 5 roads and unciv roads.

**Comment by yairm210** [comment]
Cities are treated as having roads, for all practical purposes they do have them.

Regarding "cities reduce base entrance costs to 1" - interesting, did not know that
