### ISSUE TITLE
Mod list isn't updating properly since 10/17/24

### ISSUE THREAD

**Issue by gareth44** [yairm210/Unciv#12327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.18

### Describe the bug

When I go inside the mod list, the process of the list update is no longer visible.
When I filter by updated, last updated mod is around 10/17/24, and I can't update. When I download, close the app, re-open, go back to Mods, the update marker is still there, as if my download did no have an effect. 
When I go inside a specific mod, for example, The Great Unciv Rework, there are updates even today.

### Steps to Reproduce

1. Go to the Mods section
2. Mod view is not updating
3. Try to download or update a mod
4. This seems to fail quietly

### Operating System

Android

**Comment by yairm210** [comment]
Resolved by #b0be185b
