### ISSUE TITLE
Feature request: version and build numbers on Main Menu screen.

### ISSUE THREAD

**Issue by denismattos** [yairm210/Unciv#12349]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

It would be nice to have the current version and build numbers in a corner of the Main Menu screen.  
It would make modding and bug reporting easier.

### Desired Solution

That the Main Menu screen displays current version and build numbers somewhere.

### Alternative Approaches

I can't think of an alternative approach to this.

**Comment by yairm210** [comment]
Already exists in Options > About, don't see a reason for this to be on the main screen

**Comment by PathosEthosLogos** [comment]
I think it's good to have it on the main screen. It's pretty normal in other games also.

**Comment by yairm210** [comment]
Since this is simple enough, I don't see why not, we can always remove it later
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/45f34cf9-7a0b-4636-b083-e7268ef10b20">

**Comment by denismattos** [comment]
>Already exists in Options > About, don't see a reason for this to be on the main screen
Oh, I didn't know about that.

Thanks for adding it, anyway. =)
