### ISSUE TITLE
City States are not building workers

### ISSUE THREAD

**Issue by MarsRedsun** [yairm210/Unciv#12353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.0

### Describe the bug

City states build order are messed up. On diety quick speed, city states are supposed to  have a worker by turn 20. But they only get thier first at turn 4
50-60. Its like this for all game speeds they skipping worker builds for some reason.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by Gatabdiluan** [comment]
They don't want to you steal their workers with scouts before they get ally.

**Comment by yairm210** [comment]
This is a feature, so civs don't steal their workers. Not a bug.
