### ISSUE TITLE
Automated workers replacing resource-specific improvements with farms

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.0

### Describe the bug

Instead of building resource-specific improvements like pastures or quarries, automated workers are putting farms everywhere, and they're even replacing pastures with farms.

### Steps to Reproduce

In the save file below, you can see an automated worker, ready to replace a pasture with a farm.

### Link to save file

[AutomatedTrouble.json](https://github.com/user-attachments/files/17534749/AutomatedTrouble.json)

### Operating System

Windows

**Comment by yairm210** [comment]
Automation wise this actually makes perfect sense, since the farm provides 1 food over the 1 production currently being provided
I don't see this as a problem necessarily

**Comment by yairm210** [comment]
If this was a _strategic_ or _luxury_ resource this wouldn't have happened, but this is just a bonus resource which is only worth anything for the stats

**Comment by yairm210** [comment]
Closing as 'not a bug'
