### ISSUE TITLE
Crash screen is skipped when on autoplay

### ISSUE THREAD

**Issue by PathosEthosLogos** [yairm210/Unciv#12386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.1

### Describe the bug

This has been happening in previous versions. I think the earliest I noticed was 4.11 but wasn't sure because I would usually be looking away from the screen when this happens

### Steps to Reproduce

1. Set up all AI games with myself as spectator
2. Start the match
3. Autoplay the game
5. As next turn comes, the error screen goes away and the game continues

### Screenshots

Can't screenshot as it happens to fast

### Link to save file

Can't save state because the game continues on autoplay

### Operating System

Windows

### Additional Information

I will try to click on the copy button next time the crash occurs.

**Comment by yairm210** [comment]
Should also be solved by ec6e13c01f61ebba9b590cc5db232f31f2185164
