### ISSUE TITLE
Game Frozen on DoF Offer - SOLVED 4.14.2-patch1

### ISSUE THREAD

**Issue by AC800622** [yairm210/Unciv#12394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.2

### Describe the bug

Have a DoF offer open on turn start, pressing either accept or decline does nothing.  Unable to exit, escape, respond, or minimize.  Cannot progress or play any other aspect of turn.

### Steps to Reproduce

1.  Have DoF offer from AI at start if turn
2. Press any button, nothing happens 
3. No further steps

### Operating System

Android

**Comment by yairm210** [comment]
Solved in 4.14.2-patch1, leaving open for others to see
