### ISSUE TITLE
Add Natural Wonders

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#124]

**Comment by yairm210** [comment]
Artwork for the various Natural Wonders is needed (Tile artwork, as per the existing FantasyHex tiles)

**Comment by Am-per-Sand** [comment]
Which ones?

name | yield
-- | --
Cerro de Potosi | 10 Gold
El Dorado | 5 Culture
Fountain of Youth | 10 Happiness
Krakatoa | 5 Science
Mt. Fuji | 2 Gold, 3 Culture, 3 Faith
Old Faithful | 2 Science, 3 Happiness
Rock of Gibraltar | 2 Food, 5 Gold
The Barringer Crater | 2 Gold, 3 Science
The Grand Mesa | 2 Production, 3 Gold
The Great Barrier Reef | 2 Food, 1 Production, 1 Gold, 2 Science
Mt. Kailash (G&K only) | 6 Faith, 2 Happiness
Mt. Sinai (G&K only) | 8 Faith
Sri Pada (G&K only) | 2 Food, 4 Faith, 2 Happiness
Uluru (G&K only) | 2 Food, 6 Faith

what size and color depth of the (icons/overlay)?

**Comment by yairm210** [comment]
Take a tile from the Fantasy Hex tiles and edit it to be a natural wonder

**Comment by Am-per-Sand** [comment]
Elaborate please the work flow and result:

each above as a separate tile ? { 
   [Kailash, Sinai, Fuji, Giblartar, Krakatoa].forEach( mountain => current mountain fantasy tile with some slight difference)
   The Reef => fantasy sea tile reworked
   [Mesa, Uluru].forEach( hill=> current hills fantasy tile with some slight difference)
 an so on, for example
}

**Comment by yairm210** [comment]
I don't know 0_0
Try to approximate what's in the civ wiki, I guess?
e.g. https://civilization.fandom.com/wiki/Barringer_Crater_(Civ5)

Start with Vanilla Natural Wonders

**Comment by Am-per-Sand** [comment]
64x64 8bpp

icon |name | yield
-- | -- | --
|Cerro de Potosi | 10 Gold
|El Dorado | 5 Culture
|Fountain of Youth | 10 Happiness
|Krakatoa | 5 Science
|Mt. Fuji | 2 Gold, 3 Culture, 3 Faith
![](https://github.com/Am-per-Sand/unciv/raw/master/natural%20wonders/geyser.png)|Old Faithful | 2 Science, 3 Happiness
|Rock of Gibraltar | 2 Food, 5 Gold
|The Barringer Crater | 2 Gold, 3 Science
|The Grand Mesa | 2 Production, 3 Gold
![](https://github.com/Am-per-Sand/unciv/raw/master/natural%20wonders/reef.png)|The Great Barrier Reef | 2 Food, 1 Production, 1 Gold, 2 Science
|Mt. Kailash (G&K only) | 6 Faith, 2 Happiness
|Mt. Sinai (G&K only) | 8 Faith
|Sri Pada (G&K only) | 2 Food, 4 Faith, 2 Happiness
|Uluru (G&K only) | 2 Food, 6 Faith

Will it do to make the remaining ones this way?

**Comment by yairm210** [comment]
Looks good! But please keep it to 32 width and 28 height (normal, can expand), like the existing tiles:
![image](https://user-images.githubusercontent.com/8366208/60536578-358cc900-9d0f-11e9-95e2-f2d203c16ae5.png)

**Comment by Am-per-Sand** [comment]
That exactly what I asked for in first place...
Keeping 2x size (64x56) for preview and easy resize to 32x28

**Comment by yairm210** [comment]
Mmmm...
I opened them up and they just don't look, how do I put it, crisp enough.

Here are some tiles from the original set, opened wide:

![image](https://user-images.githubusercontent.com/8366208/60819603-8afe2580-a1a8-11e9-9662-8921b74b6309.png)
![image](https://user-images.githubusercontent.com/8366208/60819651-a10be600-a1a8-11e9-8cd8-e094ab9ba782.png)

They have 2 shades for each color, one "regular" and one "muted", and so the number of colors is kept small (only 7 unique colors in the Tundra tile!) and they feel stylized even when you open them up.

On the other hand, yours use a lot of intermediate colors, so they feel blurry when you open them up:

![image](https://user-images.githubusercontent.com/8366208/60820044-52128080-a1a9-11e9-92ac-63c71ea0c407.png)

You see what I mean...? Lots of little variations on a color, which make it FEEL like it's a scaled down version of something else.
Part of the reason I'm using the pixel art is because even if people have large screens and zoom in, it looks good, and I personally feel that "blurry" pixel art goes against the feel we're aiming for :\

**Comment by Am-per-Sand** [comment]
:joy: :joy: :joy:

I see. No problem to reduce the color pallete, just a bit more time before saving the final version of the file. Check out [this one](https://raw.githubusercontent.com/Am-per-Sand/unciv/master/natural%20wonders/reef.png) - 4bpp, about 5 colors total.

I might also resize them all down without resampling if you need, for not every software offers this.

**Comment by yairm210** [comment]
Looks much better!
And yes, I'd really prefer it if you sent the 32x28 tiles :)

**Comment by Am-per-Sand** [comment]
1st part done: resized below the preview table.

**Comment by Am-per-Sand** [comment]
all done, please use linked tile packs at the bottom of (https://github.com/yairm210/UnCiv/issues/124#issuecomment-507781820)

**Comment by yairm210** [comment]
A bunch of things are coming together at once
So I think we'll make Puppet cities work first, and then we'll work on natural wonders :)

**Comment by yairm210** [comment]
Completed by @r3versi =D
