### ISSUE TITLE
"[relativeAmount]% Strength for enemy [combatantFilter] units in adjacent [tileFilter] tiles" not working on City units

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.4

### Describe the bug

The `"[relativeAmount]% Strength for enemy [combatantFilter] units in adjacent [tileFilter] tiles"` unique says that it's a combatantFilter unique, so it should work on City units as well as mapUnitFilter units. It doesn't appear to work on City units when tested.

### Steps to Reproduce

I tested this out by giving a unit the unique of `"[-10]% Strength for enemy [City] units in adjacent [All] tiles"`. It doesn't appear to do anything; the combat preview gave no indication that the strength of the city was lowered at all.

### Operating System

Windows

**Comment by yairm210** [comment]
No, cities are not units. Not a bug.

**Comment by SpacedOutChicken** [comment]
The unique still says that it's a combatant filter. Can that be changed to a map unit filter for clarity?
