### ISSUE TITLE
High 'tile click' latency at late game during your turn

### ISSUE THREAD

**Issue by Gatabdiluan** [yairm210/Unciv#12457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.5

### Describe the bug

Lag when you pick tile.
Further turns = laggier.
Changing tileset to minimalistic improve perfomance a bit. My phone is NOT weak and the game positions itself for weak devices. 

### Steps to Reproduce

0. Don't know what cause this. Just pick medium+ map, deity difficulty, enough civs and skip turns.
1.Click at tile or city button. It cause 0.3s microlag. No difference between fog ocean and city tile.
2.Clicking many times in row on city button cause huge lag. Medium lag on different tiles fast clicking.

### Operating System

Android

### Additional Information

Game unplayable at late game since last update.

**Comment by Gatabdiluan** [comment]
[Uploading Celts - 293 turns.json…]()

**Comment by Gatabdiluan** [comment]
In that saves cities not destroyed at all.

**Comment by Gatabdiluan** [comment]
[Celts - 293 turns.json](https://github.com/user-attachments/files/17720302/Celts.-.293.turns.json)

**Comment by yairm210** [comment]
Found one thing to improve there - 1c17a200
