### ISSUE TITLE
Feature request: Player is forced to vote for another civ while UN build.

### ISSUE THREAD

**Issue by Gatabdiluan** [yairm210/Unciv#12460]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I'm always frustrated that civs vote for someone. I'm pretty sure its effect nothing(diplomacy in civ is cutted). So its seems that civs play like non-humans. 

### Desired Solution

To fix it and do not break diplomacy win condition we need evaluate player relation as ai and do force vote. It will also be helpful to look at the logs of who treated you better (not you treat them).

### Alternative Approaches

-

**Comment by yairm210** [comment]
I'm sorry?
You want to choose who civs vote for? I.E. auto-win?
I don't understand. What is the current problem you're facing? And what is the proposed solution?

**Comment by Gatabdiluan** [comment]
The problem is non-human civs vote for another civs and player not. To make thing balanced human must auto-vote for civ who treat them best. Ideal bots should be indistinguishable from humans - one of the developers said so. This can be achieved if bots vote for themselves or a player votes like a bot.
