### ISSUE TITLE
The IA don't respect the game mode "Only one city"

### ISSUE THREAD

**Issue by AdamTeodoro** [yairm210/Unciv#12479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

all versions

### Describe the bug

My cousin and I were playing England and France against Germany, but unfortunately Germany created infinite cities and we were stuck with just one city.

### Steps to Reproduce

1 - I select only one city 
2 - Its only play Versus ia 
3 - play some turns
4 - See IA colonizing new cities

### Operating System

Windows

### Additional Information

THIS OCURRS IN ALL OPERATIONAL SYSTEM

**Comment by yairm210** [comment]
This is intended behaviour, one city challenge is a challenge to Human players only, same as Civ V
