### ISSUE TITLE
Costs [amount] [stockpiledResource] has major issues

### ISSUE THREAD

**Issue by prod0ad** [yairm210/Unciv#12488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.6-patch1

### Describe the bug

When I'm queuing a unit that costs 1000 Manpower (stockpiled resource) and hit the end turn button, 1000 resources are removed from the stockpile. 

That's all good, unless by now I'm below 1000 Manpower. Then the unit is canceled and I've lost the resources for nothing. So if I started with 2000 Manpower, now I have 1000 and the unit under production. If I started with 1200, I'm left with 200 and no unit being trained.

There should be a way to count that a unit is paid for and shouldn't be canceled even if leftover resources aren't enough.

A related issue: I have 1050 Manpower and I can queue two units. I lose 1000 of that and both units are canceled.

### Steps to Reproduce

Test stockpiled resources as above.

### Operating System

Linux

**Comment by prod0ad** [comment]
Thanks for the quick fix. Something I forgot, by queue two units (the related issue) I meant to say in two different cities. Will it now cancel just one of them at random?

Btw is the population countable (total and per city, hopefully) coming along? Those two fixes/additions and I can finally make the best Unciv recruitment system I've thought of, linked with many other systems through events as well:)

**Comment by yairm210** [comment]
Yes, the first one that's buildable should decrease the resources and start being built, and the second one should fail
