### ISSUE TITLE
Event happiness bug

### ISSUE THREAD

**Issue by prod0ad** [yairm210/Unciv#12481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.6-patch1

### Describe the bug

Event choices giving [-Y Happiness] (for X turns) provide positive amount Happiness. Meanwhile, their display in the Stats interface appears correctly negative (EventChoice: -Y).

### Steps to Reproduce

Test an event choice as described above.

### Operating System

Linux

**Comment by yairm210** [comment]
Please provide a save file

**Comment by prod0ad** [comment]
(Would need to upload the messy unfinished mod too.)

Was going to upload a json with the event stripped down to vanilla, but after some further tests I noticed the bug normally doesn't happen. 

It is an issue with modding changes and reloading a pre-change save game. 

Similar happened with (non) Stockpilled and "Provides [-X] [Resource]" vs Instantly Consumes [X] [(stockpilled)Resource]. Interface display at the resource interface displayed negative from EventChoice, but overall resources were not removed. A new savegame fixed everything.

So the issue only matters while testing mod mechanics (and perhaps for Scenarios after updates?)

**Comment by yairm210** [comment]
"instant trigger" "for X turns" is not something that will actually activate every turn, if that's what you were trying

**Comment by prod0ad** [comment]
I get that it's supposed to active once and last for X turns. That's what normally happens. But when (some) changes are modded in and a previous save is loaded, interface and gameplay inconsistencies may happen, as in the cases described. Hope this was a bit clearer.

**Comment by yairm210** [comment]
The way 'for X turns' works, is it's a *trigger*
That means it's activated when the building is built, and that's it
So the building itself could be sold, or the city taken, with no effect
This also means if the building changes its uniques partway through, like with mod changes, this will not be reflected in the long-term effects - sounds like 'working as intended' 👍🏿

**Comment by prod0ad** [comment]
Forgot to clarify, the second similar issue was with an event triggered effect too. 

So like: 

I playtest, change something, reload the same save. Now one interface ("Stats" for the happiness issue, "EventChoice" display for the resource issue) shows the negative numbers from the event, another (main game interface, happiness / strategic resource respectively) doesn't. Same happens if the event is triggered again later. So it's a nuisance for playtesting mod changes, and I wonder if it would also be an issue with scenarios being updated, since they are stored as saves.

Else no big deal as I found out later. A new save and things work properly.
