### ISSUE TITLE
Feature request: json tag field 

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#12493]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Tags can be arbitrarily set as an ambiguous unique. Would it be more apparent if a tags field were introduced? Same behavior, specific field.

### Desired Solution

```
{
	"name": "SomeUnit",
	"tags": [
		"Robot",
		"Metal",
	],
},
```

### Alternative Approaches

As noted. 

### Additional Context

Standard current tag use intermixes tags into uniques, when tags aren't really uniques, whereas tags _alone_ do nothing, while a uniques functional use being present is in creating modifiers.

**Comment by SeventhM** [comment]
My personal opinion, Idk if it matches others:

From a code perspective, I don't think this makes too much sense. Especially with the recent ability to use conditionals for tags, all tags functionally do function as uniques, even if they have no code behind. There's also at least one official unique (fresh water) that code wise is checked as if it were a tag, making the distinction that much more murky to me

Also, one advantage of the unique system is we can reduce the number of fields we need to work from with more flexibility on how everything works. Adding a new field for just tags seems odd with that as a goal

**Comment by yairm210** [comment]
There is no advantage and several disadvantages.
- We'll need to handle both types or force all existing mods to change
- A lot of work was put into performance for checking uniques that will need to be replicated
- Mechanisms such as 'hidden from users' for tags, which work because they're uniques, will fail
All in all, a definitive 'no' from me

**Comment by hackedpassword** [comment]
Appreciate the consideration and the detailed insights!
