### ISSUE TITLE
River tiles not being labeled as "Fresh water" and not generating Flood plains

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.9

### Describe the bug

Tiles that are next to Rivers are no longer displaying the "Fresh water" quality on the map, and tiles that are next to Rivers also aren't transforming into Flood plains (or Swamps in Deciv).

### Steps to Reproduce

Start a new game and check a tile next to a River on the map. The "fresh water" description that should appear for it is no longer showing up.

### Operating System

Windows

**Comment by yairm210** [comment]
Caused by the fix to #12467 
Basically these 2 are incompatible, #12467 will return and I can't think of a way to both stop it and not cause any other problems, sorry
