### ISSUE TITLE
Modding Bug: "[unitTriggerTarget] takes [positiveAmount] damage" & "<upon damaging a [promotion] unit>" broken interaction

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#12536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.11

### Describe the bug

`[unitTriggerTarget] takes [positiveAmount] damage <upon damaging a [Promotion Name] unit>` and `[unitTriggerTarget] takes [positiveAmount] damage <upon damaging a [Filter Unique Inside Promotion] unit>` won't trigger. 

I've tested some combination, and so far, this only happens with specifically using filter from promotion name and filter unique inside a promotion.

Combining `takes damage` UnitTriggerable with any other UnitTriggerCondition and any `upon damaging mapUnitFilter` that isn't related to promotion work fine.

### Steps to Reproduce

1. Combine `[unitTriggerTarget] takes [positiveAmount] damage` and `<upon damaging a [mapUnitFilter] unit>` using promotionName or filter inside a promotion for `mapUnitFilter`
2. See error

### Screenshots

![image](https://github.com/user-attachments/assets/0e3620fd-f40f-467d-9312-b62c6356118b)
The attacker should have halved HP in my test

### Operating System

Windows

### Additional Information

Thank you for the help!

**Comment by yairm210** [comment]
Name part done in df2a56a0
The unique should work though, can you provide the save? Or provide a unique to add to a G&K unit to test this?

**Comment by SeventhM** [comment]
Considering normal promotions was filtering by name currently, I'm half surprised there's not more reports. PR for a fix is ready

**Comment by AceHank** [comment]
[UnitPromotion Trigger Test.zip](https://github.com/user-attachments/files/17953390/UnitPromotion.Trigger.Test.zip)
Test Mod

[Trigger Promotion Test.zip](https://github.com/user-attachments/files/17953464/Trigger.Promotion.Test.zip)
Save File

**Comment by AceHank** [comment]
Sorry for the miss click!
