### ISSUE TITLE
the road we build outside the city edge don't need maintenance

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1254]

**Comment by yairm210** [comment]
Anything within your territory requires maintenance
https://civilization.fandom.com/wiki/Roads_(Civ5)
"Within your territory"

**Comment by yairm210** [comment]
Working as intended

**Comment by yairm210** [comment]
Are you sure? That's not what I remember, and that's not what the wiki seems to indicate

**Comment by lishaoxia1985** [comment]
I'm sure that in original game.

**Comment by yairm210** [comment]
I checked and you are correct

**Comment by yairm210** [comment]
I though about this a lot, and I actually think that it's not really necessary.
Even though it's true that this is how Civ V works, I think that this adds complexity without a clear gameplay benefit, so I think we won't be adding this.
