### ISSUE TITLE
Clicking on allied city state enters the city screen instead of showing diplomacy interaction dialog

### ISSUE THREAD

**Issue by metablaster** [yairm210/Unciv#12545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.11

### Describe the bug

Not always but occasionally (after some time into game) when clicking on allied city state, instead of showing dialog to conduct diplomacy with city state (or to see religious pressure) a player enters city state screen and sees all buildings and output in it as if it's your own city.

### Steps to Reproduce

1. I attached save file, load it to reproduce
3. You play as Rome and you're allied with Singapore
4. Click on Singapore city banner in hope to trigger the dialog
5. What happens instead of the dialog you enter city state screen

### Screenshots

The following screenshot shows I'm in the city state screen:

![Singapore](https://github.com/user-attachments/assets/4ce5c549-c49d-47b2-a1c1-0e7ad8b19104)

### Link to save file

[Rim - 712 poteza.zip](https://github.com/user-attachments/files/17968680/Rim.-.712.poteza.zip)

### Operating System

Linux

### Additional Information

Game was started without mods, no mods are required to load game, all mods used are only permanent audio-visual mods for music.

**Expected behavior:**

This dialog is expected instead (it's just an example of another city state):

![diplo](https://github.com/user-attachments/assets/97b69f58-7e6f-4983-a9bb-e5b0fda341c0)

**Comment by metablaster** [comment]
Yes I have a spy there, so this is by design?

I still think that entering city screen while spy is stationed should be present as an option while clicking on the city-state instead of assuming a player wants to enter the city screen.

e.g. if you want to gift gold or see current influence etc. then you don't want to enter city screen.

**Comment by SpacedOutChicken** [comment]
It looks like this isn't a bug so much as it is a UI issue, and those can be tricky to solve. If I could make a wish to the UI genie, I would wish for a pop-up menu that appears when you select the city that explicitly gives you the options of seeing the city view or the diplomacy view. I don't know if that's actually doable.

**Comment by metablaster** [comment]
I thought it's a bug.
At least now I know what's happening.

If you think it should stay as it is feel free to close this issue, but if I'm asked I'd prefer what you said, an option to choose what to do when clicking on citiy-state when spy is stationed.

**Comment by SpacedOutChicken** [comment]
I say: close the bug report and open a feature request instead. I'd love to hear what the devs think about changing the UI to accommodate this, so make a formal request.

**Comment by metablaster** [comment]
OK, I will, thanks!
