### ISSUE TITLE
Bug with city names

### ISSUE THREAD

**Issue by lolafur** [yairm210/Unciv#12555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.12

### Describe the bug

When you start in the game, when you zoom in with the mouse wheel or using your fingers on the phone, the city names disappear and you can't go to the city menu to select a building. You have to move the focus away, then the name of the city appears.

### Steps to Reproduce

1. Go to 'Enter the game and start playing for any civilization'
2. Scroll down to 'Try zooming in by scrolling the mouse wheel, or by using your fingers on the phone'
4. See error: As you get closer, the names of the towns disappear

### Screenshots

![Screenshot_20241203_022232](https://github.com/user-attachments/assets/d2b3eaca-11af-4bbf-b6ba-ac2550815659)
![Screenshot_20241203_022245](https://github.com/user-attachments/assets/b64a2e98-79a1-4b5d-b276-41c02cc6de3e)

### Operating System

Android

**Comment by yairm210** [comment]
Never happened to me, cannot replicate 
Can you attach a game save?
