### ISSUE TITLE
Inaccurate increase in the cost of culture/technology during capture city

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#12565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.12-patch2 (Build 1079)

### Describe the bug

When I establish a city, the cost of the next policy & technology increases. 
When I capture a city and make it a satellite, only the cost of technology increases, and the cost of politics increases only with annexation.
Is that what it's supposed to be?

I assume that with a satellite, the penalty should be either partial or absent from the cost of the policy and technology. A full penalty upon annexation.

### Steps to Reproduce

settle city, check cost of techs/culture
puppet city, check cost of techs/culture
annex city, check cost of techs/culture

### Link to save file

[test3annex.txt](https://github.com/user-attachments/files/17999125/test3annex.txt)

### Operating System

Android

**Comment by yairm210** [comment]
@ravignir in Civ V do puppeted cities increase tech costs?

**Comment by DeStup** [comment]
![image](https://github.com/user-attachments/assets/b0b13793-02f1-4e0a-8c68-fc5f11fa0525)
![image](https://github.com/user-attachments/assets/7ec7e68d-8771-4f96-9af2-3fce01d90f9e)

My bad for some reason, I thought that the satellite increases the cost slightly, but increases it completely during the annexation
