### ISSUE TITLE
Feature request: A way to move the newly ordered building/unit to the top of the queue

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Unciv#12598]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

In the city screen, when you select a building or a unit ti produce, it is added to the bottom of the queue (as it should). You can move the items in the queue by arrows on the right of the building/unit name, which is also okay. But often there is a long queue and you need to move the new item to the top of the queue. For example if you have a new tech and the new building is the most important for you, or if a war has started and you need a unit to go on top of the buildings that you have scheduled for construction. Moving it to the top one by one, each time clicking on the up arrow is very inconvenient in case of a long queue.

### Desired Solution

Long-tapping/right clicking on the item name moves it to the top.

### Alternative Approaches

Long-tapping/right clicking on the up arrow (to the right of the item name) moves it to the top, long-tapping/right clicking on the down arrow moves it to the bottom.

**Comment by yairm210** [comment]
I think you didn't check your own suggestion? Long-click (also right click on Desktop) already lets you do this
<img width="721" alt="image" src="https://github.com/user-attachments/assets/6b777611-e751-43a6-852b-74f7e57dd725">

**Comment by Kzer-Za** [comment]
Okay, I checked it again and found out that it sometimes works. Though on my tablet most of the times it does not, which is why I missed it. Okay, I'm gonna suppose that it's something on my end then.
