### ISSUE TITLE
In-game UI elements' readability and appearance: suggestions

### ISSUE THREAD

**Issue by Toxile** [yairm210/Unciv#12591]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I'm going to be blunt and just say that I think a great deal of the UI design in this game still looks amateurish and quite bad.  And I should clarify that I'm quite the hypocrite to say that, because I'm not even a design professional.  However, complaining without any good-faith feedback is of no use, so my intent is to make this issue just that; a way to propose changes to the current UI.

### Desired Solution

I'm going to address two aspects of the current in-game HUD that I think are very harshly designed, then go over some general improvements that could be made across the unified UI.

## Unit Info Box

![image](https://github.com/user-attachments/assets/1304d71d-72f1-41bf-ac7c-c55c54d3f923)

My feedback condensed into a few bullet points would look like this:

### The Good
- Good size, contrast, and blending of the border
- Good icons, except for the ranged attack one
### The Bad
- No consistent top-level margin
- Large vestigial high-contrast nontext elements (divider, close button, arrows)
- Unit name text not vertically aligned with its icon
- Unit name text too small in relation to its icon
- Promotion icons too large in relation to importance
- Promotion icons too close together
- Stat icons not aligned amongst themselves
- Stat icons' text not vertically aligned therewith
- Stat icons' size not consistent
- Arranging stats horizontally uses up space without significant benefits to readability or appearance

The interface poorly conveys the most important information about a unit: its type (or name) and its stats.  They are small in relation to the container they're in, they are displaced by less structural elements, their font scales poorly and has odd kerning, and while their contrast with the background is good, _**just about everything**_ else in the vicinity also gets the maximum-contrast treatment, which confounds and distracts users more than it helps them.  Lastly, the lack of proper and consistent margins immediately communicates a careless, haphazard design to encultured users.

### Proposed Solution
![image](https://github.com/user-attachments/assets/5bd2025b-2507-464d-9199-fb5d426a3eaa)

To summarise the changes, I've removed the unnecessary clutter and compressed the **_core information_** just below the unit's name, visually linking the most relevant information in the container, and made the whole easier to digest by consolidating them together, aligning the text elements with their icons and amongst each other, changing the font (more on this later) and adding shadows.  Whether one thinks my mockup looks any better than the original is a matter of preference, of course, but I would at least claim that it's easier to find the key information from and that it consumes a smaller amount of the limited screen space.

## Tile Info Box
![image](https://github.com/user-attachments/assets/105dd68e-6e88-45a1-94fe-4d666e9b7344)

My feedback condensed into a few bullet points would look like this:
### The Good
- Transparency is tasteful and well-defined
- Clear and well-designed icons, as usual
### The Bad
- Display icons (to the left of the map) not distributed vertically
- Border pure white and not blended or rounded
- No separation between map and its neighbouring elements
- Text not vertically aligned with icons
- Terrain type not visually differentiated from other information despite being higher-level
- Tile yield presented as separate from other tile information

Despite actually being quite compact, this interface _**feels**_ cluttered.  It does not organise the information in a hierarchical manner as expected, but lays it out flat and makes the user do unnecessary work to find the key parts.  The sharp pure-white border also just looks grim and not very idiomatic or stylistic.

### Proposed Solution

![image](https://github.com/user-attachments/assets/5eedde56-6b74-4f86-828b-e653bda341c6)

I'll be the first to admit that my solution is far from satisfactory.  After all, it breaks my own axiom about consistent margins (8 top-level, 2-against-3 in glass).  I **_do_** believe, however, that it is an improvement.  "Copper", "road", and "mine" and clearly additional, secondary information about the tile whereas **_"grassland"_**, the terrain type, is the defining feature.  It stands to reason, then, that the terrain and yield of the tile should be the most pronounced, and that they should all be arranged underneath the **_principal feature_**.  Secondly, the piercing white border can simply be changed to a mellow tone that blends with the textured background.  Lastly, the elements have been given some separation from the map; after all, they are not really parts of a whole, but are rather coincidentally arranged closely together to make space for the game itself.

## Closing Remarks

Please change the font for this game.  The current one clearly isn't meant to be used on a game interface, much less an information-heavy game with a lot of numbers and text.  A truly sublime and excellent choice would be [Inter](https://rsms.me/inter/), which is **_free and open-source_**, and specifically designed for interfaces where **_readability is crucial_**.  It is an incredibly "clean" and "efficient" font, and quite similar to the one used in Sid Meier's Civilisation VI.

Whatever algorithm is used to align text with icons is currently disastrous.  A small adjustment to it would go a disproportionately long way towards improving the visual clarity of the game as a whole.

The icons in this game are quite all right.  There is one change, however, that I think would be significant: standardise the "dark" colour in them and change it from pure black (a very unnatural and strong contrast) to a dark charcoal-like colour.  It will still appear "close enough" to black without causing the extreme eye-catching contrast that is currently reflected on, for example, the luxury icons with their pure black-on-gold colour scheme.

### Alternative Approaches

See above; most of my suggestions are flexible and can be adapted into alternatives.

### Additional Context

See above.

**Comment by yairm210** [comment]
## Unit table

- No consistent top-level margin - Please elaborate?
- Large vestigial high-contrast nontext elements (divider, close button, arrows) - I'm not sure why you call the X and arrows "vestigal" - they're required for users, especially on Android, to navigate between units and to close the unit table. I personally hate the X so if you have an alternative I'm all ears.
- Unit name text not vertically aligned with its icon - This is actually extremely difficult due to the way the text is rendered
<img width="286" alt="image" src="https://github.com/user-attachments/assets/a37c682e-5e3b-43de-bbbf-9b46a64aa510" />. I'll need to learn more about font metadata for this

- Unit name text too small in relation to its icon - Done 👍🏿 
- Promotion icons too large in relation to importance - Done 👍🏿 
- Promotion icons too close together - Done 👍🏿 
- Stat icons not aligned amongst themselves - Mostly done
- Stat icons' text not vertically aligned therewith - Done 👍🏿 
- Stat icons' size not consistent - I couldn't tell what you were talking about, but with the stat icon changes, probably done? The ranged attack icon looks smaller because there's very little of it at the edges but it's actually the same size as the others
- Arranging stats horizontally uses up space without significant benefits to readability or appearance - Arranging stats horizontally *saves vertical space*, and tbh it's definitely more readable than your proposal. I initially couldn't read it because the numbers and icons closest together have nothing to do with each other

Result:
<img width="546" alt="image" src="https://github.com/user-attachments/assets/fd2ea133-c44e-4c4b-ae0a-84175fbd2f75" />

**Comment by yairm210** [comment]
Regarding the font, it's taken from your default device font. Because there are so many languages, I can't pack fonts for everything within the game - you can change this in Settings - Advanced - Font Family.

I will see if I can pack a font for the standard roman letters, since that's the majority of the playerbase 🤔

**Comment by yairm210** [comment]
## Tile Info Box

- Display icons (to the left of the map) not distributed vertically - Taken literally this looks much worse:
<img width="293" alt="image" src="https://github.com/user-attachments/assets/ddd135f8-47c4-4dc5-b3fa-717a161234bb" />
So I think the correct course is to just space them out slightly:
<img width="284" alt="image" src="https://github.com/user-attachments/assets/56d52991-002a-4e18-bf4c-0ca077cdf6c9" />
Original for comparison:
<img width="284" alt="image" src="https://github.com/user-attachments/assets/0b451bf6-d0ed-4754-b6cc-88e8c535728e" />

- Border pure white and not blended or rounded - I tried this in the past, it looked bad, tried it again now, still looks bad
- No separation between map and its neighbouring elements - Done 👍🏿 
- Text not vertically aligned with icons - I assume you mean the stats, done 👍🏿 
- Terrain type not visually differentiated from other information despite being higher-level - Disagree! It is no more important than the resource and improvement
- Tile yield presented as separate from other tile information - I have several options

Final:
<img width="507" alt="image" src="https://github.com/user-attachments/assets/496834c5-86af-4e2b-8120-476693d18098" />

<img width="244" alt="image" src="https://github.com/user-attachments/assets/b98025bf-e794-42d4-99bd-68ca5df9eae3" />

**Comment by Toxile** [comment]
Wow, thanks for your detailed response!

> No consistent top-level margin - Please elaborate?

![image](https://github.com/user-attachments/assets/dea07107-7320-43e2-a5c2-584fab18e9b9)

The top-level "wrapper" container, which includes the entire box, doesn't impose any kind of consistent margin onto its children.  The left side has too much white-space, the right and bottom sides have too little, but the top is fine.  The right side in particular feels cramped, especially for units with short names that don't extend the container.

![image](https://github.com/user-attachments/assets/8e5d8f80-2011-4b50-9532-cd1378d2b264)

By picking one comfortable value and applying it for at least the outermost container, and to its children where applicable, the whole becomes more balanced and less cognitively taxing.

> I'm not sure why you call the X and arrows "vestigal"

You've probably seen more people using the UI than I have, but I don't think I've ever deliberately used the arrows or the X.  You can already close the unit menu by clicking or tapping on the selected unit again to de-select it, which is a common and well-understood design pattern; and I'm not sure why you would ever need to hide the info box without de-selecting the unit.

As for the arrows, the reason _**I**_ don't use them is because the "Next unit" button, the ability to click on units on the map, and the "Overview" screen already provide enough navigation for the majority of the cases.  Most of the time, you need the next relevant unit (accessed with the button) or to control nearby units in a specific order (accessed with the map) or to look for a specific unit or one you've forgotten about (accessed with the overview).  Maybe some players do use the arrows a lot, though—I'd love to be proven wrong.

I think the divider should also go, but if you feel it's necessary, I think it should be visually demoted to a much less structural element.  By, for example, shortening it, reducing its opacity (or just changing it to a mellow colour), and making it blend into the background to the left and right; maybe play around with thickness 1 instead of 2, too.

![image](https://github.com/user-attachments/assets/aadaa53a-c282-44bd-98d1-065e0fa81589)

> The ranged attack icon looks smaller because there's very little of it at the edges but it's actually the same size as the others

It might be that the icons' true sizes are the same, but if they don't visually align, that's still a problem IMO.

![image](https://github.com/user-attachments/assets/d00c4e59-9309-4c38-834f-71de25d9a3ed)

You must be playing on a larger screen than I am, because your icons look a lot sharper.  Still, if one accounts for the contrast difference, the ranged attack icon visually appears to be up to 3 pixels smaller than the melee power icon, which sounds small, but really means a difference of up to 16% – especially noticeable on smaller screens like phones.

> Because there are so many languages, I can't pack fonts for everything within the game - you can change this in Settings - Advanced - Font Family.

I'm not experienced enough to comment on how to improve fonts for languages like Chinese and Arabic, but Inter supports _**a lot**_ of languages, so it'd give you a pretty good size-to-coverage ratio:

![image](https://github.com/user-attachments/assets/d580cd6d-dfd6-4480-b1ef-c05a03a492b2)

Otherwise, I think your changes are a step in the right direction.  I still disagree with some things like the terrain type not being structurally important and the horizontal arrangement, but I won't force the issue.

**Comment by yairm210** [comment]
It's mostly the Japanese Chinese and Korean alphabets that are hard to pack in, because there are a gazillion characters

**Comment by yairm210** [comment]
The divider I can probably get rid of
Regarding the X button, I originally added it in because of players who couldn't figure out how to close the unit button, but I can poll this and see
The left and right are definitely in use, because "next unit" only goes forward, and if you want to go back it's very hard to find the exact unit if you have a lot of units

**Comment by yairm210** [comment]
I can probably replace the X with a button on the top-right that goes over the corner, which will free up that space 👍🏿

**Comment by Toxile** [comment]
Good work.  I've come up with some other suggestions in the meantime, but they were easy enough to implement that I reckon I'll submit them as a pull request instead; less work for everyone involved.

**Comment by yairm210** [comment]
What do you think of this X button? I think it's much better than what we currently have

<img width="402" alt="image" src="https://github.com/user-attachments/assets/3fd0113d-1ebf-4c0c-ad41-1040f762b68f" />

<img width="499" alt="image" src="https://github.com/user-attachments/assets/f49b1106-c17c-4736-891a-e93126a8539d" />

**Comment by Toxile** [comment]
Big fan.  Will work well for mobile users, too.  As far as I'm concerned, hit it 👍

**Comment by Toxile** [comment]
Do you reckon text outline and/or shadow would be possible?  I don't enough enough about how Unciv renders text to say, but it's pretty much standard in games like this where the interface is full of information and has a lot of text on complex, noisy backgrounds.  Civ 6 and Stellaris, for example, have them all over the place.

**Comment by yairm210** [comment]
We have our own [ShadowedLabel](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/components/widgets/ShadowedLabel.kt) for that, but it's not great

**Comment by yairm210** [comment]
I think I've done everything from the suggestions that's currently feasible, you can keep asking questions in this thread but if there are more suggestions let's open a new issue

**Comment by najevi** [comment]
I came across this Issue while preparing to write a new issue. My feedback seems relevant to your current discussion. 

wrt: "<", ">" & "(X)" buttons (for next, previous and deselect/close unit) please seriously consider locating these three essential buttons at the far left of that "Unit/city info pane".

Reason: 

1. The present location of the "(X)" and ">" buttons is frequently obscured by the Attack pane whenever that popup appears. By contrast, the location of the "<" button is never obscured. 
2. As you know, whenever a unit name is edited the width of this "Unit information pane" changes and this causes the on-screen location of those two right-hand-border located buttons { ">" & "(X)" } to change from one unit to the next. 
3. Having these three cyclical-unit-stack navigation buttons always in the same location on the "World Screen" means fewer demands for so-called "ballistic eyeball movement" to reestablish the location of a button that performs the very same action that the immediately prior mouse click performed.

So with no fancy graphic but instead using plain old ASCII characters; the left-hand-border of the aforementioned "Unit/city info pane" might have the following appearance:

```
<
(X)
>
```    
As far as a better label for (X) goes: "deselect" or "close" or "hide" come to mind 
... so just as suitable, although considerably wider, might be:
```
Prev
Desel
Next
```

**Comment by najevi** [comment]
New issue #12745 created.

**Comment by najevi** [comment]
New issue created: #12745
