### ISSUE TITLE
Feature request: Guarantee that there are always all types of luxury resources on a generated map

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Unciv#12594]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Maybe it's my bad luck, but currently there are always 1-2 luxury resource types completely absent from a map. For example, for the last 3 games I have not encountered a single tile with Dyes, even though I'm playing on huge maps. (I do not mean within my borders: no civ is offering them for trade until the end of the game). I have encountered Dyes before that, so it's not an issue with them per se, just that map generation is "too random". I have also a couple of times could not find Whales anywhere (again, not only my civ, but also in trade).

### Desired Solution

It would be nice if the map generation process ensured that each luxury resource got at least 1 cluster* of tiles with that resource somewhere in the world because a single tile can easily by missed by all civilizations until the end of the game.

* By cluster I mean several tiles with this resource, each of them several tiles apart from other such tiles

### Alternative Approaches

For Whales it needs to be ensured that not all of them are placed in the middle of the ocean, far from any land. Ensure that at least some of them are within 3 tiles from land tiles, where a city can be built.

**Comment by yairm210** [comment]
For game balance purposes you get a lux on roughly every X amount of tiles, if you have more tiles than X * resources naturally you won't get all lux tiles. Changing this would be to alter the game balance.
Whales are on Coast, so by definition they're placed near land and not in the middle of the ocean
