### ISSUE TITLE
"Victory status" screen always displays 10 "Culture" for every civilization

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Unciv#12609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.9

### Describe the bug

In "Rankings" tab of the "Victory status" screen "Culture" column always displays 10 for every known civilization.

All the other columns display their correct (as far as I can tell) values, but Culture always shows 10 for every civilization, so they are just sorted in that column alphabetically.

### Steps to Reproduce

Prerequisites: have a game started and advanced enough for you to have encountered several other civilizations.

Steps to reproduce:

1. Open the game menu
2. Select the item "Victory status"
3. Switch to the tab "Rankings"
4. Scroll right to see the right-most column "Culture".

The expected result: see the actual Culture level of each civilization in the current game, like for Happiness, Technology, etc.

The actual result: every civilization always has 10 in that column.

### Operating System

Android

**Comment by DeStup** [comment]
can you attach save and screenshots?

**Comment by Kzer-Za** [comment]
Oops, it seems to be observed only in Civ IV ruleset, sorry about it.

4.14.9 is the version that is installed from F-Droid.
