### ISSUE TITLE
Feature request: display city-state name instead of "null" when displaying military bonus from city-states

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12612]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

In Alpha Frontier, if you make a friendship or alliance with a militaristic city-state, you get a strength bonus, which is cool. The issue I have is with how this is displayed on the strength calculator. The strength bonus shows up as `+2% null (City-States)`. It's a bit dry as descriptions go, and it doesn't tell you which city-state is giving you that bonus.

### Desired Solution

If possible, display the name of the specific city-state next to the strength bonus from that specific city-state.

### Alternative Approaches

If displaying the individual names isn't possible, consider displaying something besides "null".

### Additional Context

![Screenshot (230)](https://github.com/user-attachments/assets/cffcffd8-d13d-4441-a34f-4218a8a950eb)

**Comment by yairm210** [comment]
I can't display the city state name, since that information is lost in transit, but I can display the city-state type
