### ISSUE TITLE
Unit sprites not disappearing after expending unit if a military unit is in the same tile

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.13-patch1

### Describe the bug

Under certain conditions, when expending a unit such as a Great Person with a `"Can instantly construct a [improvementFilter] improvement <by consuming this unit>"`, the sprite of the unit will linger after the unit is gone.

### Steps to Reproduce

1. Place an expendable civilian unit on a tile
2. Place a military unit on the same tile
3. Expend the civilian unit
4. The civilian's sprite will remain, next to the military unit's sprite

### Screenshots

![Screenshot (231)](https://github.com/user-attachments/assets/b705783b-eb00-424f-aa9a-dd6c886094bf)
In this screenshot from a RekMOD game, I've just expended a Caravan unit, creating a Land Trade Route (Gold) tile improvement. The Caravan's sprite is still there.

### Operating System

Windows

### Additional Information

Interestingly, if you move the military unit out of the tile during that same turn, the sprite will then disappear, but if you then move the military unit back into the tile, the sprite from the expended unit will reappear. It won't disappear for good until next turn.

**Comment by yairm210** [comment]
Please attach a save

**Comment by SpacedOutChicken** [comment]
Sorry for not including a saved game. Do you still need one?

**Comment by yairm210** [comment]
I'm pretty sure I figured it out, if it persists in next version ping here
