### ISSUE TITLE
Multiplayer Error

### ISSUE THREAD

**Issue by Pemarces273** [yairm210/Unciv#12628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.14

### Describe the bug

![Screenshot 2024-12-11 17 34 48](https://github.com/user-attachments/assets/56905a91-7451-4fb1-8ed1-249eb58557bc)

I am currently playing Unciv multiplayer with my five other friends for a month now. However, today I couldn't seem to enter the game that I hosted with my friends, saying the service has been suspended, as shown in the screenshot. Is it normal for this to happen?

### Steps to Reproduce

Null.

### Screenshots

![Screenshot 2024-12-11 17 34 48](https://github.com/user-attachments/assets/8dbe4b51-495a-44e6-a3a9-6622e02ae95f)

### Operating System

Linux

**Comment by Pemarces273** [comment]
![Screenshot 2024-12-11 17 39 08](https://github.com/user-attachments/assets/0eec6e06-7a44-4d5a-ae35-3c2922fe7ea0)

I tried connecting to the server, but it failed too. Is it a problem on my end?

**Comment by metablaster** [comment]
I'm having the same problem:

![part1](https://github.com/user-attachments/assets/ba157948-567b-48d2-aa5d-eb534cc4d5dd)

![part2](https://github.com/user-attachments/assets/22cdf985-3d71-4d49-9acc-94a437f3338f)
