### ISSUE TITLE
Feature request: HACER EL JUEGO MENOS AGOTADOR

### ISSUE THREAD

**Issue by fabi0M** [yairm210/Unciv#12626]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Resulta que es muy agotador querer mover las unidades, porque con el pasar de la partida el límite de suministros crece muchísimo, y querer mover cuando es unidad por unidad es agotador

### Desired Solution

Puede ser bajar a la mitad los suministros otorgados y en cambio aumentar la fuerza de las unidades al doble 

### Alternative Approaches

Puede ser también bajarle la resistencia a la mitad a las ciudades o cualquier otra cosa que haga que no se necesiten tantas unidades y poner el límite de suministros a la mitad

**Comment by yairm210** [comment]
This differs from Civ V rules, but you can make a mod for this yourself!
https://yairm210.github.io/Unciv/Modders/Mods/
