### ISSUE TITLE
Music starts auto-playing when paused

### ISSUE THREAD

**Issue by pascallj** [yairm210/Unciv#12637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.14

### Describe the bug

If you have downloaded the music files, it will auto-play when the game regains focus, even if the music was paused before in the menu. This seems counterintuitive to me. On Linux this happens when I, minimize and re-open the game, unlock my screen, switch workspaces in Gnome etc. On Android this happens when switching between apps.

### Steps to Reproduce

1. Download the game music files
2. Pause the music
3. Minimize the app (go to homescreen)
4. Re-open the app
5. The music starts playing again

### Operating System

Android

**Comment by metablaster** [comment]
I'm having same issue but there is a solution.

Go to `Options -> Sound` and set `Music Volume` to zero, then this will pause the music for ever until you increase the slider again.

**Comment by pascallj** [comment]
Thank you I since have discovered this too 🙂 However sometimes I'd like the music and sometimes I don't. I don't think this is the expected behaviour of button though.
