### ISSUE TITLE
Modding Bug: Some Improvement uniques don't accept some Conditionals

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#12640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.14

### Describe the bug

Some Improvement uniques don't work with some Conditionals. I did a limited testing and I mostly only tested with `<for [civFilter] Civilizations>`, but tried one with `<after discovering [tech]>` also didn't seem to work. I've listed some uniques that I've tested in the mod file.

Thank you!

Mod file:
[Improvement Conditionals.zip](https://github.com/user-attachments/files/18128320/Improvement.Conditionals.zip)

### Steps to Reproduce

1. Use the Custom Map provided by the mod file
2. Play as both Babylon and other random Civ
3. Remove some `//` from mod file if necessary
4. See errors

### Operating System

Windows

**Comment by yairm210** [comment]
Unhelpful. Please provide a list of uniques.

**Comment by AceHank** [comment]
> Unhelpful. Please provide a list of uniques.

Yes, it's in the mod file, but here it is

```//Not working
				//	"Unpillagable <for [Babylon] Civilizations>", //All Civ can still pillage?
					"Adjacent enemy units ending their turn take [49] damage <for [Babylon] Civilizations>",
					"Tile provides yield without assigned population <for [Babylon] Civilizations>", 
					"Tile provides yield without assigned population <after discovering [Pottery]>", 
					
					"Irremovable <for [Babylon] Civilizations>", //Conditional doesn't work, affecting ALL Civs```

**Comment by yairm210** [comment]
The "unpillagable" and "irremovable" are properties of the improvement, so currently they can't accept civ conditionals
