### ISSUE TITLE
Modding Bug: `Unbuildable` and `Cannot be built` ignores `adjacent to` conditional if construction is underway

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#12686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.16

### Describe the bug

So I have a modded improvement with `Cannot be built on [All] tiles <in tiles adjacent to [Sphinx] tiles>` (also tried using `Unbuildable <in tiles adjacent to [Sphinx] tiles>`). 

Supposedly, they can't be build adjacent to one another, which is true, unless, you're building them at the same time OR pausing one of them and build another Sphinx, then you can have Improvement adjacent to one another when it shouldn't.

I'm pretty sure this isn't supposed to happen? The conditional should also account for unfinished improvement after placed.

Thank you!

Mod File
[Epic of Fantasy Beta.zip](https://github.com/user-attachments/files/18201300/Epic.of.Fantasy.Beta.zip)

### Steps to Reproduce

1. Use Kemetian Dynasty using the provided mod file
2. Build Sphinx with Worker after researching Masonry
3. Quickly move Worker away to different tile the next turn
4. Build Sphinx again in adjacent tile
5. Finish both Sphinx
6. See error

### Screenshots

![image](https://github.com/user-attachments/assets/fa2eae0f-f289-40c4-a421-a451577f5702)

### Operating System

Windows

### Additional Information

My testing is limited with one conditional, but there might be a possibility where the same trick (Pause building) will work on other conditional.

**Comment by yairm210** [comment]
No, the conditional only handles built improvements
Unbuilt are not sphinx tiles yet
Not a big, but perhaps a use case we'll need to think about
I would just have them give zero stats if adjacent to another sphinx, that'll disincentivize players to get them to exactly what you want

**Comment by AceHank** [comment]
Ok I'll do just that!

**Comment by yairm210** [comment]
Actually this is a modding request
So it goes in #3242
