### ISSUE TITLE
Statue of Liberty: Specialist Production Bonus Does Not Apply to Engineers

### ISSUE THREAD

**Issue by ermnsg** [yairm210/Unciv#12719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.11

### Describe the bug

The description for the Statue of Liberty states:
"+1 Production from every Specialist in all cities"

However, the bonus does not apply to Engineers. While other specialists correctly gain the additional 1 Production, Engineers remain at 3 Production when they should increase to 4.

### Steps to Reproduce
- Build the Statue of Liberty in any city.
- Assign specialists, including Engineers, to cities.
- Observe the production values of all specialists.

### Operating System

Windows

### Additional Information

The issue could be due to either:

- A bug in the implementation where Engineers are excluded.
- A wording error in the description that fails to clarify Engineers are not included.

**Comment by yairm210** [comment]
Please provide a save file

**Comment by ermnsg** [comment]
[Statue of Liberty Bug.zip](https://github.com/user-attachments/files/18269356/Statue.of.Liberty.Bug.zip)

**Comment by ermnsg** [comment]
Is this ok?

**Comment by ermnsg** [comment]
Thank you for your swift response—I truly appreciate it.  

I must admit, I initially felt that the request for a save file might not have been necessary, as you were able to clarify the issue so quickly. However, I understand that it may have been a standard step in your troubleshooting process, and I respect your thoroughness.  

I also realized that my assumption was based on the fact that most other specialists have a default of **3 Gold** or **3 Science**, so I mistakenly thought Engineers would also have **3 Production** by default. Thank you for clarifying how it works—it's good to know that everything is functioning as intended.  

Lastly, I want to take a moment to express my admiration for your work. **Unciv** is an excellent game, and its stability and quality are truly impressive. My hat is off to you for creating something so enjoyable and well-crafted. Thank you again for your dedication to this project!

**Comment by yairm210** [comment]
No, I actually need the save file, there are so many cases I can't know I'm handling the same thing unless I have it 
Maybe you have a mod with other specialist s? Maybe you have something that negates? Only save files are the real truth

And thank you 😄

**Comment by ermnsg** [comment]
Thank you for clarifying—your reasoning makes perfect sense, and I truly appreciate the effort you put into thoroughly investigating every case.  

I want to thank you again for your commitment to this project. **Unciv** is an absolutely fantastic game, and I enjoy it thoroughly, even after having played and purchased all the Civilization games! Your dedication and hard work have created something truly special.  

Keep up the great work, and thank you for all the joy this game has brought me. 😊
