### ISSUE TITLE
Siam and Patronage bonuses are not earned

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#12724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.14 (Build 1082)

### Describe the bug

1. I don't see Siam getting any additional bonuses from its features (at least culturally, I haven't checked the rest of the cases, but there may be a problem there too)
2. I don't see that the closure of patronage gives bonuses from the cities of the states. Using the example of culture, I did not check other cases.*

upd. I think we should check other types of city-states as well.

### Steps to Reproduce

Windows/android + Rekmod

### Screenshots

on Gif, I assume that I should receive 48 cultures in industrialization by playing as a Siam and having Patronage. But I get the same 24
![Unciv_6NDlKRgt9r](https://github.com/user-attachments/assets/6a78788e-0996-45d5-9222-cca36440bf83)

### Link to save file

[SiamPatronage.txt](https://github.com/user-attachments/files/18274714/SiamPatronage.txt)

### Operating System

Android

**Comment by yairm210** [comment]
Can't find your rekmod iron mod

**Comment by yairm210** [comment]
Are you even in i ndustrial era? Show your tech tree

**Comment by DeStup** [comment]
oh. i am sory. i can do save with original rekmod.
https://github.com/DeStup/RekMOD-iron

yes, in industrial era. in gif

**Comment by DeStup** [comment]
[PatronageSiamFaith.txt](https://github.com/user-attachments/files/18281005/PatronageSiamFaith.txt)


here rekmod.
Case with faith. I quess i I should have +16 faith. +50% from Siam, +50% from patronage. But i got only +8

**Comment by NahuelGeno** [comment]
I noticed the same thing in my last multiplayer game with Siam, link to discord message and image from the same turn. Siam's bonuses do not apply.

![image](https://github.com/user-attachments/assets/eee1e6ac-362f-4af1-a14a-b2f9886249f8)


https://discord.com/channels/586194543280390151/653651863832363053/1317971239041503282

**Comment by DeStup** [comment]
@yairm210 
![image](https://github.com/user-attachments/assets/972d6f1f-d6c0-4256-8da8-9184df32680f)
the same saves
Can you take a look? It's 54 now. Where else are 6 from? 
It's the same with Faithin the second save. I get 18, not 16.

**Comment by NahuelGeno** [comment]
I understand that the issue has been resolved and the percentages are now applied correctly. @DeStup

**Comment by DeStup** [comment]
> I understand that the issue has been resolved and the percentages are now applied correctly. @DeStup

Yes, I see it, but now it's like something extra is being added? There should be 48 cultures and 16 faiths in the preservation, respectively. Or where did I go wrong?

**Comment by DeStup** [comment]
Hmm.. I think I got it, Patronage gives a compound interest now. Is that how it should be?
