### ISSUE TITLE
Some issues to fix

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#1289]
Okay, after so many UnCiv games, I've come to these following conclusions:
1. Barbarians shouldn't be able to heal themselves in any way, nor get promotions (if they get them).
2. When you see a pop up message, for example when you've entered a Golden Age, researched a technology, or built a World Wonder, you shouldn't be able to press any button except the one that closes the message. For example, if you "accidentally" press the Next Turn button while seeing these pop ups, you'll see that message again in the next turn.
3. Should Cities founded near lakes considered coastal cities?

**Comment by yairm210** [comment]
1. Agree they shouldn't get promotions, disagree they shouldn't heal
2. I thought that was dealt with already, I'll check it
3. Probably not, good point

**Comment by yairm210** [comment]
I checked and they shouldn't be able to get xp, how would they get promotions? Where have you seen this?

**Comment by Smashfanful** [comment]
I'm not entirely sure, but they sometimes seem to heal themselves when I'm about to finish them.
Oh, almost forgot, should City-States have Scouts?

**Comment by yairm210** [comment]
Yeah, why not?
BTW if they're fortified then they'll heal

**Comment by Smashfanful** [comment]
Fortify and heal is okay, then, but why Scouts for City-States?

**Comment by yairm210** [comment]
Why not? I don't understand :/

**Comment by Smashfanful** [comment]
Well, I've never seen a Scout owned by a City-State, let alone exploring the map

**Comment by Smashfanful** [comment]
In the original Civ V, I mean

**Comment by yairm210** [comment]
I checked, and cities are only coastal cities if they're near a Coast tile, where do you see this affecting something?

**Comment by yairm210** [comment]
So in conclusion, all points are fine now =)
