### ISSUE TITLE
[question] How to play?

### ISSUE THREAD

**Issue by paulolimac** [yairm210/UnCiv#1295]
Hi guys!

Where can I get info about "how to play" Unciv?

I started the app, but following the welcome-tutorial i get lost.

So I don't know how to restart the tutorial. Or where I can get informations to a newbie like me?

I went to youtube, and to this github, but didn't found any good manual-file nor video to help me about "how to play".

every help is welcome!

**Comment by yairm210** [comment]
A. The tutorial info is all in the Civilopedia (menu, civilopedia, tutorials)
B. There's an active Discord, link in the main page :)

**Comment by paulolimac** [comment]
I will keep a eye on them.
tyvm @yairm210
