### ISSUE TITLE
Add Greece Hidden Ability

### ISSUE THREAD

**Issue by Breace112** [yairm210/UnCiv#1299]
Greece have a hidden Ability 
https://civilization.fandom.com/wiki/Greek_(Civ5) : 
Even if Greek units end their turn within neutral, unfriendly or hostile city-state borders, Greece will not lose Influence with them and the units will heal as if they were on friendly territory.

**Comment by yairm210** [comment]
I thought about it, and I'm really not fond of having information that's not displayed to the player. And between adding this to the Civ unique ability description and removing this entirely, I'm choosing the latter.
Good point though, and I may change my decision in the future!
