### ISSUE TITLE
UI broken on Note10+

### ISSUE THREAD

**Issue by hausler89** [yairm210/UnCiv#1304]
![Screenshot_20191106-004840_UnCiv](https://user-images.githubusercontent.com/22004432/68256062-4cca2300-002f-11ea-9279-c7083b14723e.jpg)
Last update broke UI. This is on a Note10+ at 2280x1080 screen resolution. Problem occurs on all rendering resolutions. Worked on the previous version.

**Comment by yairm210** [comment]
Damn

**Comment by yairm210** [comment]
@ninjatao @lishaoxia1985 
You've been able to check this before, right?
I have a feeling that if we change the 1x1 pixel 'whiteDot' to a 3x3 that might solve this

**Comment by ninjatao** [comment]
> @ninjatao @lishaoxia1985
> You've been able to check this before, right?
> I have a feeling that if we change the 1x1 pixel 'whiteDot' to a 3x3 that might solve this

Haha. I guess my phone can reproduce this. How can I help exactly?

**Comment by yairm210** [comment]
A. Run the latest master and see if the UI is broken
B. If it is, change the whiteDot image from a 1x1 to a 3x3 and see if that changes something

**Comment by ninjatao** [comment]
> A. Run the latest master and see if the UI is broken
> B. If it is, change the whiteDot image from a 1x1 to a 3x3 and see if that changes something

A.Yes, dialogs are broken again on latest commit.
B.What white dot?

**Comment by ninjatao** [comment]
Latest commit:
![latestcommit](https://user-images.githubusercontent.com/6846049/68292245-6b2f2d80-00c6-11ea-8c27-7848f490835f.jpg)

**Comment by ninjatao** [comment]
Latest commit with whiteDot.png changed to 3*3:
![whiteDot3*3](https://user-images.githubusercontent.com/6846049/68292291-8437de80-00c6-11ea-96ec-e015a1bd0318.jpg)

**Comment by yairm210** [comment]
Okay, that already looks considerably better!
If we change it to 10x10 it should look for, I think, can you check?

**Comment by yairm210** [comment]
I assume this means is a difference in how the GL decides to render the edges of images
Basically we can keep making it larger until the problem is no longer significant

**Comment by ninjatao** [comment]
7*7 works ok for me.
![7*7](https://user-images.githubusercontent.com/6846049/68294135-60769780-00ca-11ea-8a18-f515fb8386ad.jpg)

**Comment by yairm210** [comment]
That's good enough for me!
We never managed to figure out why this happened, so even if we try again chances are we won't manage to figure it out
I'm just glad this root bother is in the future :)

**Comment by ninjatao** [comment]
10*10 looks worse than 7*7. Don't know if you want to adjust it.
![10*10](https://user-images.githubusercontent.com/6846049/68359996-27d1cf00-0159-11ea-99ba-4effd196863e.jpg)

**Comment by yairm210** [comment]
7*7 has its own problems:
![image](https://user-images.githubusercontent.com/8366208/68361816-e677fa00-012d-11ea-91f0-361b530f7216.png)
![image](https://user-images.githubusercontent.com/8366208/68361830-ed9f0800-012d-11ea-9c2d-e2ef958a00c2.png)

I would try going up in size, maybe we're too conservative. How does 50*50 look?

**Comment by ninjatao** [comment]
50*50 is good
![50*50](https://user-images.githubusercontent.com/6846049/68364810-01685f80-016a-11ea-9a20-af4b2c687da6.jpg)

**Comment by ninjatao** [comment]
By 50*50, city health bar is broken. 😂
![50](https://user-images.githubusercontent.com/6846049/68382152-1951da80-018e-11ea-828a-3587b22cc39c.jpg)

**Comment by yairm210** [comment]
Okay, I see that we'll need to add 'minsize' to ImageGetter.getDot just like in getBackground

**Comment by fulmeek** [comment]
Since the previous release totally broke the UI on my Galaxy S5 Neo, the last release looks way more usable so far. However, some positions are still a bit off:

![Screenshot_20191108-213412](https://user-images.githubusercontent.com/36341513/68509456-3e6b4980-0271-11ea-98b8-1e7f9afe98f3.png)
![Screenshot_20191108-213520](https://user-images.githubusercontent.com/36341513/68509471-41663a00-0271-11ea-9585-57d49c597c07.png)

I guess the latest changes are not in there yet?

**Comment by yairm210** [comment]
Indeed, that's the version with the 10*10 fix. The next version should have everything sit much better (50*50 for backgrounds and the regular old 1*1 for other things like health bars)
