### ISSUE TITLE
City-State shouldn't spawn with any military unit (Warrior and Scout)

### ISSUE THREAD

**Issue by Breace112** [yairm210/UnCiv#1305]

**Comment by yairm210** [comment]
They already spawn without acid, but I think they should spawn with warriors or they won't be able to defend against barbarians

**Comment by Breace112** [comment]
Ok, Fair enough.

**Comment by Breace112** [comment]
I don't think so, barbarian usually doesn't spawn on very early turn. I mean city state could produce a military unit after they settle.

**Comment by yairm210** [comment]
I don't understand why, though. Why not let them have a warrior like you do?

**Comment by Breace112** [comment]
Because that's what happens in Civ 5?

**Comment by Breace112** [comment]
https://civilization.fandom.com/wiki/City-state_(Civ5)
"They do start with a Settler, who founds the city state on the same tile it spawned at the beginning of the game. Unlike the major civilizations, City-States don't have a military unit right at the beginning of the game."

**Comment by yairm210** [comment]
I think on this specific micro-point Civ V doesn't really have a reason for doing this, so I'll break from their tradition.
