### ISSUE TITLE
Can't see promotion infomation on promotion screen.

### ISSUE THREAD

**Issue by bingo12345** [yairm210/UnCiv#1312]
**Describe the bug**
When an unit get a promotion, touching a promotion on promotion screen leads to instant confirmation so i cant see what effect the promotion has.

**Comment by bingo12345** [comment]
Please add promotion infomaion to civilopedia. It is confusing because player can't check promotion effect after unit promoting.

**Comment by yairm210** [comment]
You can see it when clicking on the left part, but I guess I should separate it to 2 buttons so it's more obvious to the player
