### ISSUE TITLE
Crash when city is being traded while being captured

### ISSUE THREAD

**Issue by UniqueActive** [yairm210/UnCiv#1323]
**Describe the bug**
While in online multiplayer with my friend, I suggested a trade consisting of the enemy AI's city in exchange for peace, while we were both attacking the AI.

After I proposed trade and ended my turn, my friend proceeded to attack the enemy city in question, capturing it.
When ending her turn, her game simply crashes.

When ending her turn without capturing the city, the game does not crash, and the city now belongs to me since the AI seems to have accepted.

**To Reproduce**
1. Player 1 proposes trading AI's city X with AI
2. Player 2 attempts to capture/raze/puppet city X
3. Player 2 ends their turn
4. Player 2 game crashes, turn is not sent

**Expected behavior**
Not sure honestly, since I dont know the order of events in the background.

**Comment by yairm210** [comment]
Okay wow that's an edge case that I hadn't considered, good catch!
