### ISSUE TITLE
Rivers - current problems

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#1326]
As of now, the main problem with rivers is not technical implementation, it is visual.
We need a way to visualize tiles in the fantasyHex tileset, without harming the current aesthetic.
Remember that currently, "higher" tiles such as mountains and forests partially hide the tiles behind them.
Suggestions welcome, IF they're accompanied with an image.

**Comment by rintaro-okabe** [comment]
do you think it is possible to make the trees and mountains hide rivers and still make them visible? as of now, they are pretty difficult to spot already

**Comment by yairm210** [comment]
Not sure what you mean, as of now there are no rivers

**Comment by rintaro-okabe** [comment]
sry i was unclear. i forked the project and used the visuals you left in the game to implement rivers. i created a separate river object to not save the information in the tiles themselves

**Comment by yairm210** [comment]
So you feel my pain then :/
Yup, that's the gist of it. Rivers need to both be visible and look good.

**Comment by darkninec** [comment]
Yeah now I understand better the problem. I know how it works on civ 5, but i think you didn,t understand me well. But know i have 2 ideas. 
1) how did yo make roads ? Wouldn,t it be posible to make them like roads but in blue and turning them 90 degrees. Exclude mountains they dont need rivers they wont produce anything. If they hide some river its not so bad but you could exclude them around mountains.
2) make all fields new including a copy with rivers at all 6 sides( very hard work). 
PD: i dont know if its posible i do not program with java. Sorry for my bad english i dont know if you understand well what i mean.

**Comment by Whistler11** [comment]
As Darkninc said, how did you do the roads? I really like how the roads work, I think it's smart, with the only downside is that you can't tell if there is only a single road for deconstruction (don't want to have to pay for the maintenance).
I like Darkinecs idea though (maybe with a twist), make a river with a shorter and wider rectangle on the linking side of the cell.

**Comment by mnktuk** [comment]
re:  "higher" tiles such as mountains and forests partially hide the tiles behind them.
As a suggestion - you can try to add a waterfall on the tile edge. This way you can do the 'natural' transition from higher to the lower level.

**Comment by hayounav** [comment]
Out of curiosity, is the problem with the "native" fantasyhex river solution too much visual clutter?

I'm assuming this image as indicative of the default visuals: https://itch.io/post/1026240. I'm under the impression that he's using the river & road add-on published by the tileset author.

**Comment by ManBearPig0** [comment]
To indicate rivers on the topleft and topright sides of the mountain tile you can have a stream coming down the mountain joining up with the river:

![Mockup2](https://user-images.githubusercontent.com/50755379/81484339-128f4780-9245-11ea-92dc-1d88a854c34f.png)

Streams on mountains could also point to a river behind the mountain. Another possibility is to show that river when the mountain tile or the tile behind the mountain tile is selected, and hide it when those tiles aren't selected:

![Mountain](https://user-images.githubusercontent.com/50755379/81485091-f2fb1d80-924a-11ea-9144-3286b6a5e57c.png)

**Comment by AConte0** [comment]
I'm not an expert like you, I really like this game and the idea of ​​rivers. What do you think if the rivers behind the mountains or the jungle cannot be seen unless the player selects the cell where the river is hidden? The player selects that cell (above mountains or jungles) and the other below it changes transparency to show the river behind it. This reasoning may perhaps also extend to the cells above right and above left of mountains and jungles. I hope I have been of help!

**Comment by yairm210** [comment]
Rivers are FINALLY DONE HOT DAMN
