### ISSUE TITLE
Settlers from ruins in One City challenge

### ISSUE THREAD

**Issue by Badgirl420** [yairm210/UnCiv#1332]
I don't know if this counts as a bug, but in the One City challenge, it is still possible to get settlers from ruins if you haven't founded your first city yet. I discovered this when my starting units started on a tile with ruins. I further tested this by searching for more ruins before founding my first city and ended up with 10 settlers by turn 7. Of course I had to cheat by saving before each ruin and reloading until I got another one, so I wouldn't recommend doing this. Plus it completely defeats the point of the One City challenge.

**Comment by Smashfanful** [comment]
You also get Settlers from Policies

**Comment by Emirrian** [comment]
I think settlers should be able to join the city to increase it's population. But they "Found New City" action should be disabled for One City challenge.

**Comment by yairm210** [comment]
Population is a separate random option which will be kept
