### ISSUE TITLE
Art Direction?

### ISSUE THREAD

**Issue by InstanceOfMichael** [yairm210/UnCiv#1333]
I love the hex tileset you've selected. I actually found Unciv when looking for a creative commons hex tileset.

I'm not a fan of the symbol icons for the units.

Is there any set art direction for Unciv? The current icons make the game feel like it's stuck in strategic mode. Is that the intended goal or are we waiting for someone to contribute a unit sprite sheet?

**Comment by yairm210** [comment]
If you'll join us on Discord you'll see that there's somebody working very hard to make that happen, and you're welcome to join us in that endeavor =D

In the next version most of his units will be available in-game =)

**Comment by yairm210** [comment]
You can already see them in the Desktop version :D

And you're welcome to contribute your own ;)
