### ISSUE TITLE
city name will not be changed when language changed.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1338]
if it runs in Chinese, now we build a city, it shows city name in Chinese, when we change the language the name will disappear.
i know the reason, but i have not find the method to solve it.

**Comment by yairm210** [comment]
These are two separate things.
A. Composite Bowman is a G&K unit - see roadmap
B. City name - good point, city names are currently 'baked in', having them be language-fluid is definitely possible but it would require every name to be directly translated in a translation file... Sounds like a lot of with :/

**Comment by yairm210** [comment]
They have for a while now, and I forgot to close this =)

**Comment by lishaoxia1985** [comment]
i don't understand,  it is not solved yet.
________________________________
