### ISSUE TITLE
Annexed city may have reduced assignable population if assigned outside new border before annexing

### ISSUE THREAD

**Issue by hinsenlam** [yairm210/UnCiv#1341]
When I annex a city (after puppetting it), the city border resets. Population outside the new border become nonassignable. 

The major issue is that:
Current and unassigned population numbers remains the same numerically. But population who were assigned outside the new border are gone so actually assigned population is less than the difference between current and unassigned population numbers. 

A minor issue is that:
I am not sure if the resetting border of annexed city is a design choice or a bug.

Since I only noticed the problem after tens of turns, I cannot provide initial moment when it happened. But I believe you can reproduce the problem by:
1. Defeat a enemy city where some assigned population are outside the base 7 hexes (center + 6 outers of center);
2. Puppet the city;
3. Annex the city and wait for the city border resets.

As an example, the following screenshot of my game play shows the annexed city Kyoto has 0/8 unassigned population, while the actual count of assigned population is 7.

![Annotation 2019-11-18 041351](https://user-images.githubusercontent.com/17953884/69013339-e4c5f600-09b9-11ea-89dc-bb46673ecf76.png)

Attaching my save for reference
[unciv_save_201911180410utc+8.txt](https://github.com/yairm210/UnCiv/files/3856040/unciv_save_201911180410utc%2B8.txt)

**Comment by yairm210** [comment]
The reset border is by design - the unassigned population is a silly bug.
Good catch, thanks! =D
