### ISSUE TITLE
Change link in towns overview from map view to "inside town" view

### ISSUE THREAD

**Issue by Coruna** [yairm210/Unciv#1359]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I am in the towns overview (look at screenshot) and when I click a towns name, I am directed to the town on the map. On a normal base, I want to change something inside the town (production for example) and don't want to know where the town is on the map.

**Describe the solution you'd like**
The link should go to the view "inside the town" so I can change whatever I want directly.

**Additional context**
![Screenshot_town](https://user-images.githubusercontent.com/51291572/69429933-ed5d5a00-0d34-11ea-9d76-e26a4f17aa42.png)

**Comment by yairm210** [comment]
Good idea!
