### ISSUE TITLE
Can i go to promotion screen anytime?

### ISSUE THREAD

**Issue by bingo12345** [yairm210/Unciv#1361]
**Is your feature request related to a problem? Please describe.**
I have a unit which has 3 promotions but i can see only the promotion icon below the unit name. 
I want full description of my unit's promotions anytime. Because i can forget.
**Describe the solution you'd like**
Make an icon to show promotion screen so user can check all of promotion description anytime.

**Describe alternatives you've considered**
Describe all promotions with icons onto civilopedia.

**Additional context**
Thanks for your great work and concern.

**Comment by yairm210** [comment]
Promotions in Civilopedia is certainly a good idea, and one that needs to be implemented.
Where do you imagine this icon on the screen? The main screen is pretty full as it is
