### ISSUE TITLE
A bug that requires an uninstall and re-install to keep playing

### ISSUE THREAD

**Issue by godlessanarchist** [yairm210/Unciv#1364]
**Describe the bug**
The game locks up completely if you are forced to adopt a policy that you don't have enough tech for. I built a wonder that gives you a free policy change using a great person(hurried production), but I didn't have enough tech to actually change anything. It wouldn't let me close the screen or adopt anything( obviously not enough tech)

**To Reproduce** 
1. Have a limited tech tree.
2. Have a great person
3. Have a wonder under construction that gives you a free policy upgrade
4. Use the great person to hurry construction of the wonder.
5. Upon completion it forces you to adopt a policy, but without the required tech will not let you leave the screen or access the main menu or anything.

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
I was expecting to lose the free upgrade, or have it saved for when the tech becomes available. 

**Screenshots**

**Additional context**
My tech tree was researched as far as you can go without "Currency." I'm sure it could be done with even less tech, but that's what happened to me.

**Comment by yairm210** [comment]
Whoa
You mean you unlocked 3 entire policy trees before Currency?
That's pretty insane
But yeah, I'll see what I can do, I think you should be able to even keep the free policy =)

**Comment by yairm210** [comment]
Can you give me the game data so I can see if I solved it correctly? Or is that impossible because of the nature of the bug?

**Comment by godlessanarchist** [comment]
Yes, I understand it's insane, lol. But that's what happened. Like I said it could happen with less tech, theoretically.

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 23, 2019 at 4:28 PM, Yair Morgenstern<notifications@github.com> wrote:   
Whoa
You mean you unlocked 3 entire policy trees before Currency?
That's pretty insane
But yeah, I'll see what I can do, I think you should be able to even keep the free policy =)

**Comment by godlessanarchist** [comment]
It's impossible because every time I reopened the game after I closed it the choose policy screen remained upon opening.

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 23, 2019 at 4:29 PM, Yair Morgenstern<notifications@github.com> wrote:   
Can you give me the game data so I can see if I solved it correctly? Or is that impossible because of the nature of the bug?

**Comment by yairm210** [comment]
Okay
I'm pretty sure I understand what's necessary to fix this, so when the next version is available for everyone I'll ping you to ask if it solved it =)

**Comment by godlessanarchist** [comment]
Sounds good. Keep up the good work!
