### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by therealrobster** [yairm210/Unciv#1370]
**Describe the bug**
When trying to run on Linux I get the following output:

    $ sudo java -jar Unciv.jar
    [sudo] password for username: 
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/username/Applications/Games/unciv/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
    WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

**To Reproduce**
1. Go to terminal
2. Go to folder with unCiv
3. use "java -jar Unciv.jar" command

This is Ubuntu 18.04
Intel NUC Skull Canyon

I hope this helps

**Comment by AhmedAA** [comment]
You shouldn't have to run it as `sudo`. It's bad practice.

Does it happen when you run as a regular user as well?

**Comment by therealrobster** [comment]
Sorry, that was an attempt to see if it works with sudo.  Same with running it without.  HOWEVER, I looked and there was a file called `Unciv`.  I simply double clicked that in the GUI file explorer and it loaded up.  So probably this is a non required ticket if there's a direct way to load from the file explorer?

**Comment by yairm210** [comment]
Seems to be related to https://github.com/libgdx/libgdx/issues/4927

I changed the GL version to use 3.0 by default and that doesn't seem to have helped

I'm glad to hear that the standalone is working for you in Linux BTW =D
I''ll have to update the readme as well

**Comment by yairm210** [comment]
I think I will close this though
