### ISSUE TITLE
Nuclear weapons should be able to target tiles with no combattant

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1375]
1. Cities destroyed via nuclear bombings are considered razed and should leave behind ruins. 

2. Any civ whose territory is affected by a nuclear blast should consider that a declaration of war.
![Screenshot_20191125-202343_UnCiv](https://user-images.githubusercontent.com/49125947/69594820-24e13600-0fc3-11ea-825a-448d455a7ba7.jpg)
For instance, in this image nuking China's worker would destroy Babylon's tiles thus forcing Babylon to automatically declare war on me. 

3. Nuclear missiles should be able to target and bomb any tile within their 12 tile radius, not just units and cities, and irrespective of line of sight. 

(this is all as it is with civ v)

**Comment by yairm210** [comment]
1&2 are done, so I'm changing the title

**Comment by JackRainy** [comment]
It seems I have a fix for that, however, need a bit of more testing.

Is that the expected result?
![Unciv 2020-01-19 01 25 46](https://user-images.githubusercontent.com/27405436/72671946-f29c0400-3a5a-11ea-8982-beedc95944e8.png)

**Comment by JackRainy** [comment]
There is the mentioned upper fix in the PR #1746

**Comment by yairm210** [comment]
Solved by @JackRainy
