### ISSUE TITLE
[Feature Request] Support packaging for various Linux distributions

### ISSUE THREAD

**Issue by refola** [yairm210/Unciv#1380]
I think it would be cool to include in the releases all files needed to package the game for various Linux distributions. In particular, I would like the releases to include an executable (script) that handles running the `.jar` file, an `unciv.desktop` file so it can show up in the applications menu, and an icon for the application.

For now, [I've thrown together something that seems to work for my distro](https://ccr.chakralinux.org/packages.php?ID=8416), but the only "proper" part of the `source` array in my `PKGBUILD` is the `Unciv.jar` line.

Would you consider adding my `unciv.desktop` and `Unciv.sh` files somewhere, and then adding them and the icon to future releases?

Thanks for making this great Civ clone!

**Comment by yairm210** [comment]
If you check the releases, you will see that we actually pack a standalone zip that's not dependent on java
Adding a .desktop file to there is a good idea :)

**Comment by refola** [comment]
Thanks, but can you add it somewhere besides the Java-included download? Most Linux systems already have a Java package, so it seems silly to go from a 22 MB download to 89 MB just to get the additional 0.001 MB that's wanted. Maybe bundle the `.desktop` file, icon, etc. as a small "packaging files" download?

**Comment by yairm210** [comment]
Okay, sounds good =)

**Comment by yairm210** [comment]
https://github.com/yairm210/Unciv/releases/tag/packrTest12
=D

**Comment by refola** [comment]
Thanks! Mind adding the icon too? It feels really weird having `"https://raw.githubusercontent.com/yairm210/Unciv/master/extraImages/Unciv%20icon%20v3%20for%20google%20play.png"` in the `PKGBUILD`'s `source` array.

**Comment by orklann** [comment]
@yairm210 I am trying to packaging the `jar` file and the `jre` runtime together, then I saw this issue, is there any guide on doing this like you did on Linux now?

**Comment by yairm210** [comment]
Sure!
We use [Packr](https://github.com/libgdx/packr) for this, and JREs are AdoptOpenJDK, workflow for downloading and building can be found [here](https://github.com/yairm210/Unciv/blob/8e1e8bc27b9bfb2da1cb990f0d5ad966bacbeef9/.github/workflows/buildAndDeploy.yml#L147)
