### ISSUE TITLE
both android and desktop can't compile in MacOS when use GL 3.0.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1381]
when i set config.useGL30 = false in desktoplauncher it will run good, but how to do when i compile the android app?

**Comment by yairm210** [comment]
It's automatically set to false, the only place I set it to true is in the Desktop

**Comment by yairm210** [comment]
You have a mac? Do you know where I can find a zip file of the jdk for macOS for creating standalones? Apparently what I did before worked only for Linux, managed to get it working for Windows (I think) but we still need a mac jdk...

**Comment by lishaoxia1985** [comment]
i link my phone to Mac and test, it can not run, please check.
you can use install homebrew and brew cask,  it is a popular console command tool and very easy to install software and development tool. please look this web:
https://brew.sh/

**Comment by lishaoxia1985** [comment]
i  think i have find the problem in you rewrite the androidlauncher in kotlin, but i don't know how to solve it.

**Comment by yairm210** [comment]
Ahhh you're right, damn
Try uncommenting the apply plugin: "kotlin-android" in build.gradle, now that we're in gradle 5 it should work
Also I think the desktop should work even without setting opengl30 to false

**Comment by yairm210** [comment]
Reverted the Java to Kotlin the the Android launcher in 127bafd and now everything works again
Sorry about that

**Comment by lishaoxia1985** [comment]
you can see it is very good.[Image]
