### ISSUE TITLE
multiplayer 

### ISSUE THREAD

**Issue by Bebarr** [yairm210/Unciv#1392]
Hi :)
(French user)
I don't succeed in the creation of a multiplayer game.
When I'm in the new game screen, the players id are requests : 
I can't create my own id because is always invalid.
If I decide to use the current id I can't select the entire id because the letters "doesn't slide"
![Screenshot_20191128-230722_UnCiv](https://user-images.githubusercontent.com/46008532/69833412-f4540300-1233-11ea-83c0-f5e8690c483b.jpg)

I'm using the game with android 8 on Samsung A520f. Thanks,

**Comment by lishaoxia1985** [comment]
i think id is created accoding to your mobile phone, so inputing word  is not accepted, you can look at the option menu about multiply play

**Comment by yairm210** [comment]
Not a bug
If you think the multiplayer could be better explained, please provide feedback what to change :)

**Comment by Bebarr** [comment]
It's maybe not a bug. I don't know I'm not a pro.
But the fact is that I can't select the entire id to copy it from my Samsung a520f and send it to the other device.
So I can't test this mode. I like this game so I want to play with my girlfriend ^^

**Comment by yairm210** [comment]
That's what the 'copy id' button is for in menu - multiplayer :)
