### ISSUE TITLE
crash, map edit

### ISSUE THREAD

**Issue by Bebarr** [yairm210/Unciv#1393]
When I want to edit a map, the app close automatically.
![Screenshot_20191128-231215_UnCiv](https://user-images.githubusercontent.com/46008532/69833550-d2a74b80-1234-11ea-840f-7f6d4c39ba5d.jpg)
-
![Screenshot_20191128-231245_Samsung Experience Home](https://user-images.githubusercontent.com/46008532/69833559-e5218500-1234-11ea-97e0-53d621ad3d17.jpg)

**Comment by yairm210** [comment]
What version?

**Comment by yairm210** [comment]
If version is before 3.3.1 then this is a bug that's already been fixed

**Comment by Bebarr** [comment]
I downloaded the 3.3.0 from f-droid which is the last version on f-droid.. no?

**Comment by yairm210** [comment]
Okay, so yeah, this has already been fixed =)
Not sure how/when F-droid updates

**Comment by yairm210** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Fcom.unciv.app.yml

**Comment by Bebarr** [comment]
Ok thanks for all !! ;) I'll wait
