### ISSUE TITLE
Computer does not value strategic resources

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1406]
Pretty simple, even a civ without a single strategic resource will reject 20 uranium for 1gpt, for instance. 

In fact here's an example of that very thing happening
![Screenshot_20191203-023627_UnCiv](https://user-images.githubusercontent.com/49125947/70033784-c6ddc100-1575-11ea-8d10-adc801645926.jpg)
![Screenshot_20191203-023634_UnCiv](https://user-images.githubusercontent.com/49125947/70033891-fa205000-1575-11ea-9718-4741d5e7a835.jpg)

Silly Greece..

**Comment by yairm210** [comment]
The question is, does it really need them?
I think the AI in the original Civ was to accepting of resources it didn't need

**Comment by yairm210** [comment]
Do they have anything that they can do with uranium? What's their tech level?

**Comment by ozyxcv** [comment]
The results are the same regardless of tech level or what the resource is. I could offer the greeks 5 horses for 1 gpt and they will deny even if they have no horses.

**Comment by ninjatao** [comment]
I think this could lead to a serious AI disadvantage (selling resources to AI -> AI build army with them -> they get -25% penalty in combat because you cut off trade during war).
Since AI will have problems deciding who is reliable ally anyway, maybe they should just ignore any strategy resource offer.

**Comment by ozyxcv** [comment]
![Screenshot_20191203-051848_UnCiv](https://user-images.githubusercontent.com/49125947/70046865-7b82dd00-158c-11ea-8aa2-d0b53fd12af4.jpg)
![Screenshot_20191203-051854_UnCiv](https://user-images.githubusercontent.com/49125947/70046874-82115480-158c-11ea-9763-7eb1721ad4b2.jpg)
![Screenshot_20191203-051904_UnCiv](https://user-images.githubusercontent.com/49125947/70046882-863d7200-158c-11ea-997f-5d69760b4c57.jpg)

Another example, Babylon is in the future era, with absolutely no strategic resources (third picture) and still refused to buy all those resources from me for just 1gpt.

**Comment by ozyxcv** [comment]
> I think this could lead to a serious AI disadvantage (selling resources to AI -> AI build army with them -> they get -25% penalty in combat because you cut off trade during war).
> Since AI will have problems deciding who is reliable ally anyway, maybe they should just ignore any strategy resource offer.

Players will always find a way to game the system I think. Regardless, strategic resources do have trade value in civ v so even if not now, updating this should at the least be on the roadmap. Just my two cents 🙂

**Comment by yairm210** [comment]
I checked this, and as I thought, it depends on various circumstances. I think the AI actually does a good job at the moment of rejecting player offers that would not help it, this is more of an AI advantage than a disadvantage =)

**Comment by refola** [comment]
> it depends on various circumstances. I think the AI actually does a good job at the moment of rejecting player offers that would not help it

Can you give an example of when the AI would accept a resource trade? Do you have to both be fighting a war against the same enemy?
