### ISSUE TITLE
UnCiv version 2.2.6 shows a blank screen when logging back into the app in android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [yairm210/UnCiv#141]
# Expected behavior
After successfully entering into the app, and access some features in it. Then I minimize the app, and hope to log back into the app smoothly.

# Actual behavior
After successfully minimizing the app, then I try to log back into the app, and find problems with this app. The problem is this app displays a blank screen, and I can not access any features.

# How to reproduce
* Launch app.
* Click on some features in it, *it's up to you.*
* Minimize apps.
* Log back into the app. *Then you will find the problem as I have explained.*

<center>Browser: Samsung Galaxy S6 edge
Operating system: Nougat 7.0
App version: 2.2.6</center>

# Recording Of The Bug
https://youtu.be/i7LbsKPXDho

**Comment by yairm210** [comment]
Huh.
That is extremely odd. Nothing of the sort happens on my phone, and neither can I find in the code anything that could lead to this...?
I'll look into it, thanks!

**Comment by ammarraisafti** [comment]
Thank you for your reply.

I am also surprised at this problem. When I try to find this problem in logcat, there is some information I found. I hope you can improve it, because this is my favorite game.

<code>05-28 23:06:18.952  3711 15223 I ActivityManager: Killing 13908:com.unciv.game/u0a824 (adj 906): remove task
05-28 23:06:18.961  3711  3773 D CompatibilityInfo: mCompatibilityFlags - 0
05-28 23:06:18.961  3711  3773 D CompatibilityInfo: applicationDensity - 640
05-28 23:06:18.961  3711  3773 D CompatibilityInfo: applicationScale - 1.0
05-28 23:06:18.963 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S]onReceive
05-28 23:06:18.963 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [*]onReceive : com.android.settings.nfc.ACTION_OSAIFUKEITAI_NETWORK_CHG received.
05-28 23:06:18.963 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [*] onReceive : state = false
05-28 23:06:18.963 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] setKoreaNetwork ( false)
05-28 23:06:18.964 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [*] setKoreaNetwork : setNfcTypeSettings() = SETTING_TYPE_ABF
05-28 23:06:18.965  3711  4480 W ActivityManager: Request to remove task ignored for non-existent task 883
05-28 23:06:18.969  6230  6249 D SecNfcJni: nfcManager_changeDiscovery: enter
05-28 23:06:18.969  6230  6249 E SecNfcJni: nfcManager_changeDiscovery: It is already the same discovery configuration
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E] setKoreaNetwork ( true)
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] notificationDispJudging
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] getCLFLockStatus
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [*]getCLFLockState  status = 0
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E] getCLFLockStatus (0)
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] getUIMLockStatus
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [*]getUIMLockStatus  status = 129
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E] getUIMLockStatus (0)
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] getKoreaNetwork
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E] getKoreaNetwork ( false)
05-28 23:06:18.971 12215 12215 W [NfcFeliCaSettingsIntentReceiver]: [*] notificationDispJudging  :  Not Korea Networks.
05-28 23:06:18.971 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [S] removeNotification
05-28 23:06:18.973 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E] removeNotification
05-28 23:06:18.974 12215 12215 D [NfcFeliCaSettingsIntentReceiver]: [E]onReceive
05-28 23:06:19.028  3711  4444 D InputReader: Input event(5): value=0 when=759940296000
05-28 23:06:19.028  3711  4444 D InputReader: !@notifyKey(172), action=1
05-28 23:06:19.028  3711  4444 D InputManager-JNI: !@interceptKeyBeforeQueueing(172), action=1, interactive=true
05-28 23:06:19.030  3711  4444 D InputManager-JNI: !@handleInterceptActions(172), action=1, wmActions=1</code>

**Comment by Am-per-Sand** [comment]
The same happens in v2.5.7 under A4.1.2 after you press "back/exit" arrow to display the desktop. Pressing "Home" button instead of "back/exit" prevents the bug

**Comment by yairm210** [comment]
Okay so it turns out this depends on the application lifecycle, and there's a difference between back and home
So... From now on 'back' will act like the 'close' button in almost all the screens, so this will never occur again hopefully!
