### ISSUE TITLE
Difficulty Levels explained.

### ISSUE THREAD

**Issue by zoso1975** [yairm210/Unciv#1411]
No biggie but it would helpful for us players to know what exactly changes in-game with each step up in difficulty level. Maybe an explanation could be added with each level type?

Otherwise though keep up the terrific work!!!

**Comment by yairm210** [comment]
I'm not entirely 100% on board with this one...
I think learning that the AI basically cheats on the higher levels would break the immersion and the experience of the player.
Anyone who wants to learn about the actual mechanical differences can google it, after all.

**Comment by zoso1975** [comment]
Cool. Just an idea. You're probably right though.
