### ISSUE TITLE
AI didn't build city on starting location I set, so I think

### ISSUE THREAD

**Issue by Oend** [yairm210/Unciv#1419]
I edited map with much time, also include starting location of every CIV, but after start game test I saw they didn't build city on starting location I set, they move, then eveything changes to so bad.
So if can, maybe add a new civ icon of starting location in map editor, which tells AI "if no problem, please build city on starting location"?
ah, also there's same problem with city-states.
I had make sure there's three distance between two civ starting location, absolutely.

**Comment by Oend** [comment]
Another problem is, the starting team has three units (Scout, Warrior, Settler), this needs two tiles at aleast, if only have one (like a tiny island), this civ would disappear, if you choose it as player not AI, you would see the whole fog on screen, you could do nothing except next turn.
the solution is maybe offer option to choose the starting team?

**Comment by Oend** [comment]
about two problems, maybe one better solution: scenarios mode edit? (like original CIV5 does? I'm not sure) which could edit CIV city , units, etc, on map; but I guess it's difficult to implement?

**Comment by yairm210** [comment]
We now have scenario editing :D 
See https://github.com/yairm210/Unciv/wiki/Scenarios
