### ISSUE TITLE
Allow cities to bombard nearby units

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#142]

**Comment by mrmrcory** [comment]
HAve a "archer" that is immovable and is called "city"

**Comment by yairm210** [comment]
Okay what?
Can you send me the game data to yairm210@hotmail.com?

Tuesday, 13 November 2018, 01:19am +02:00 from mrmrcory notifications@github.com<mailto:notifications@github.com>:


HAve a "archer" that is immovable and is called "city"

**Comment by ninjatao** [comment]
Allow city to bombard enemy and make AI use this feature seem not that hard, but UI can be painful.
How about this: One click on the city button will highlight it, and unselect any unit. This is when you bombard nearby enemies. Click on the button AGAIN will pop city screen?

BTW, I just can't image how to arrange city UI when you decide to add airplanes >_<

**Comment by ingvart** [comment]
I would say that when you click on a city it should give you the page it should give you the options in a list to 

- further select one of all units (i.e. airplane, worker, cannon) or 
- attack (as in this thread), or 
- zoom into the city interface.

Just adding the one step in-between would solve all these UI issues

**Comment by yairm210** [comment]
That's a good idea for unit selection :)

As for bombard, I'm imagining it like the current 'move unit here' button, so you'll have a button for 'attack' on the left and 'bombard' on the right

Not simple to implement, but should be easier for the player imo

**Comment by yairm210** [comment]
Done by @ninjatao , has entered 2.12.0!
