### ISSUE TITLE
In the map editor, 'Options' button can be pressed as much as you can

### ISSUE THREAD

**Issue by coding-human** [yairm210/Unciv#1420]
**Describe the bug**
In the 'map editor', I can press 'Options' button as much as I can, and it makes another menu popup every time I press the button.
Also, I had to press the 'Close' Button for each of the popup to close them.

**To Reproduce**
1. Press 'menu button' in the game
2. Click on 'Map editor'
3. Press 'Options' button in the map editor.
4. Press the button several more times
5. Now, try to close the popup by pressing the 'Close' button of the 'Options menu popup'.

**Expected behavior**
When the 'Options' menu in the map editor is already opened, why not disable the button, or maybe, just set up the maximum amount of menu that can be opened. :)

**Screenshots**
 - 

**Additional context**
 -

**Comment by coding-human** [comment]
+ in the map editor, I can place several tile improvements on the mountain.
Barbarian encampment, city ruins, ancient ruins, Great-People improvements(like Customs house or Academy), even fishing boats... etc... can be placed on the mountain.
is it intended?

**Comment by yairm210** [comment]
As for your second point - no, and fixed.

**Comment by coding-human** [comment]
Good!
