### ISSUE TITLE
Request: increase frequency of oil resource on land and especially in desert

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1422]
did some testing (listed results in detail on discord) and as of now you will only encounter oil on *any* desert tiles on a large default map once out of every 10 games, and if you do there will only be one single oil on those tiles.. I highly suggest adjusting the frequency of oil spawns on land and especially desert, so that civs like Arabia and landlocked civs aren't at a massive disadvantage in the late game.

**Comment by yairm210** [comment]
Agreed.
