### ISSUE TITLE
`Error compiling shader: Vertex shader` on macOS 10.13

### ISSUE THREAD

**Issue by mikeyhew** [yairm210/Unciv#1428]
**Describe the bug**
Game won't start due to this error:

```
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -jar Unciv.jar
Error in LSRegisterURL: -10811
LwjglGraphics: created OpenGL 3.2+ core profile (GLES 3.0) context. This is experimental!
Loading game basics - 316ms
Loading translation files - 159ms
Loading characters for font - 5ms
Putting glyphs - 4548ms
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:135)
Caused by: java.lang.ExceptionInInitializerError
	at com.unciv.UncivGame.create(UncivGame.kt:60)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:151)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error
Fragment shader:
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:7: 'varying' : syntax error: syntax error

	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:163)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
	at com.unciv.ui.utils.CameraStageBaseScreen.<clinit>(CameraStageBaseScreen.kt:76)
	... 3 more
```

This is on macOS 10.13.6, on an early-2015 Macbook Air. I got the same error when I used my normal version of java, AdoptOpenJDK 0.12, plus another error about a bad reflection access

**To Reproduce**

1. Install java 8 with `brew cask info adoptopenjdk/openjdk/adoptopenjdk8`
2. `mkdir Unciv && cd Unciv`
3. download `Unciv.jar`  from Release 3.3.6 and save it to this folder with `curl -LO https://github.com/yairm210/Unciv/releases/download/3.3.6/Unciv.jar`
4. run the jar file with `/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -jar Unciv.jar`

**Expected behavior**
The game should load and run without errors. Instead I get this error and the screen is black.

**Screenshots**
![Screen Shot 2019-12-07 at 4 54 01 PM](https://user-images.githubusercontent.com/6751033/70381069-37883300-1912-11ea-90b2-3f5105c13821.png)

**Additional context**
The game worked pretty well in a previous weeks a couple weeks ago. I'm not sure which release it was, and seem to have lost the jar file that I downloaded. I'll try out a few versions and see if I can find the last one that worked.

**Comment by mikeyhew** [comment]
OK, it looks like Unciv version 3.3.0 works fine, and this error is introduced in 3.3.1

**Comment by yairm210** [comment]
It's probably the activation of GL 3.0, this is a bummer because it works fine on Windows, Linux and Android... welp =/
Disabled it, please check https://github.com/yairm210/Unciv/releases/tag/3.3.6-forMac to see if that 
helped =)

**Comment by lishaoxia1985** [comment]
@mikeyhew you should watch my new request:
https://github.com/yairm210/Unciv/pull/1376
you only need to modifier "core/src/com/unciv/ui/utils/CameraStageBaseScreen.kt".

**Comment by lishaoxia1985** [comment]
@yairm210 you are wrong, if you delete "config.useGL30 = true", you should also delete "createDefaultShader()", it runs in MacOS 10.15 very well.
by the way, opengl 3 es only be supported in android 4.4 and above, libgdx in opengl 3 runs very bad, you can watch libgdx wiki, now it is on test not normal version.

**Comment by yairm210** [comment]
Thanks!
I really have no way of testing things on MacOS so it's very helpful =D

**Comment by yairm210** [comment]
Please try https://github.com/yairm210/Unciv/releases/tag/3.3.6-forMac3 then =)

**Comment by mikeyhew** [comment]
This version works. Thanks!
