### ISSUE TITLE
when resolution is set to auto and max the window in desktop, the line in techpickscreen will be confusion.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1435]
1. this problem occurs in android when the mobile phone resolution is set highest resolution.
2. the language Russian only show well in resolution 1500*1200, so we must find another solution, such as change the font size when resolution changes.
2. by the way, i want to know how to draw map and replace the default map with others?
for example, i want draw a chinese map. i read some code, but i have not solution. i want use this project code to make a game.
Are the maps created random?

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/70453751-f595f300-1ab1-11ea-8acb-346ea9889bcc.png)

I have no idea what you mean, everything looks fine

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/70453821-13fbee80-1ab2-11ea-850e-bd797d10a05a.png)

This is Russian in 1050*700, looks fine

**Comment by yairm210** [comment]
And this is smallest, 750*500, looks fine
![image](https://user-images.githubusercontent.com/8366208/70453894-3261ea00-1ab2-11ea-8d9b-b14b94739879.png)

**Comment by yairm210** [comment]
BTW first was was Auto on maxed Desktop, which is your point 1

**Comment by yairm210** [comment]
As for maps, that's done in the map editor, but the process is not streamlined, hoping to change it soonish

**Comment by lishaoxia1985** [comment]
about russian,  you can look at cityscreen.
if your mobile or pc is high resolution,  such as  3120*1440, tech screen will be confusion.

**Comment by yairm210** [comment]
Gotcha, so for a start we can set a max resolution of 1500*1000 which should solve the immediate problems

**Comment by yairm210** [comment]
Auto-resolution was a massive failure (see 973c8fb) so we're not doing that anymore.
