### ISSUE TITLE
Documentation/wiki for new contributors

### ISSUE THREAD

**Issue by XethalKhan** [yairm210/Unciv#1438]
My request is not exactly a new game feature.

I would like information source specificly made for developers, like the one for [LibreOffice](https://wiki.documentfoundation.org/Development). I believe many find this project interesting, but they don't contribute because they don't know where to start and README pages on repository are all around the place and not very informative. 

Wiki tab in repository is perfect place for this information.

**Comment by yairm210** [comment]
That's a great idea!
I'll add a contribution markdown file, if it gets big enough then we'll see where we'll put it ;)

**Comment by XethalKhan** [comment]
@yairm210 you or a contributor can try to put files in /docs folder inside **Wiki** tab of repository, to check if that tool is sufficient.

**Comment by yairm210** [comment]
Started with https://github.com/yairm210/Unciv/wiki/Getting-Started

@ninjatao @lishaoxia1985 I'd like your help in pointing out steps I may have missed =)

**Comment by yairm210** [comment]
Added a project structure overview at https://github.com/yairm210/Unciv/wiki/Project-structure-overview

**Comment by yairm210** [comment]
Added the post-development workflow at https://github.com/yairm210/Unciv/wiki/From-code-to-deployment

What kind of things were you aiming for? What kind of explanations do you expect the wiki to contain?

**Comment by XethalKhan** [comment]
Great response time @yairm210 

Material you created looks great. In this comment I will focus on [project structure overview page](https://github.com/yairm210/Unciv/wiki/Project-structure-overview).

The page is good, just the way I think it should be. It contains breif description of classes, and their purpose. Pages like this should not contain all variables and functions listed, except for the most important ones (variables and functions that describe the role of a class in overall game).
If someone wants to explore implementation details, those can be discovered inside source code (consider using documentation comments inside kotlin code to describe in detail what each piece of code does). Inside project structure overview page, next to the class subtitle should be a link to it's source code. For example, **A tile - TileInfo** should have a link to [it's source code inside repository](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/logic/map/TileInfo.kt).

I believe that content inside project structure overview page is badly titled. Project structure overview page should contain information about folders inside root of repository, and than branch from top-down. Example for project structure page per my opinion:

/android - folder for android deployment
/core - basic logic and models of the game, implemented in all deployments
/desktop - folder for desktop deployment
/ios - folder for ios deployment
/tests - folder for unit tests

Of course this description should be more informative. Directory names should be links to pages that better describe what they contain and their subfolders. For example, when we click on **/core** directory, there should be description for **/core/src/com/unciv** subdirectory that describes:
/logic
/models
/ui
and most importand classes inside /core folder and subfolders (currently mentioned at [project structure overview page](https://github.com/yairm210/Unciv/wiki/Project-structure-overview))

P.S. Consider using documentation comments in kotlin code, and using some document generator tools from those comments in the future.

P.P.S. Documenting code is very boring and tedious task, but in the long run it is worth it. Compliments to @yairm210 and anyone who helped him in the process so far :)

**Comment by yairm210** [comment]
https://github.com/yairm210/Unciv/wiki/Project-structure-and-major-classes

I don't think that the internal folder structure is very important, because if I'm interested in a specific class I'll search for it in the IDE on github search anyway =)

I'll also add the screens to the major classes as they're the main UI parts

The problem with document generator tools is, where do I put the generated files afterwards. Couldn't find a generator that compiled Kotlin to Github Wiki documentation

**Comment by XethalKhan** [comment]
On Github, every Wiki tab is a standalone repository created for documentation. When you created your first pages, you had an option to create text, HTML and diffrent other file types. Your document generator tool can generate HTML documents and then put them inside Wiki repository. That way developers can read on repository Wiki, and files can be portable to diffrent web servers.

**Comment by yairm210** [comment]
Yes, but since I change the code all the time, I was thinking of generating and updating the documentation as part of the Travis build

**Comment by XethalKhan** [comment]
Even better. Focus should be on development, documenting should be side quest :)

**Comment by yairm210** [comment]
This seems to be good enough for the people who started developing recently, if there are any particular details we can fill them in later =)

**Comment by refola** [comment]
Getting Started step "Use classpath of module desktop" doesn't work for me. The only option is "Unciv". I'll see if it builds and runs anyway and report back.

**Comment by SomeTroglodyte** [comment]
Um, I know this is closed - but - as my two cents do not affect source controlled files, I hope it's OK to mention this here.

I jotted down a few things while starting over - new nuc, new mint, most of ~ or ./config not migrated. The result is here:
https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Getting-Started.md

So - this might be valuable input or it might not. Discard, merge, want me to offer a merged version?
