### ISSUE TITLE
ability to liberate purchased cities . 

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1449]
Self explanatory I think 🙂

**Comment by yairm210** [comment]
You can just, you know, gift them away

**Comment by Breace112** [comment]
How about liberating city-state from it's previous owner.

**Comment by yairm210** [comment]
I'm pretty sure it is, no?

**Comment by ozyxcv** [comment]
> You can just, you know, gift them away 

I don't see why these are contradictory! Both options exist in civ v and some people prefer to play passively, so buying conquerered cities and liberating them would be nice. (Although admittedly since there is no way to stop them from being reconquered, since we can't broker preace between computer civs yet) 



> How about liberating city-state from it's previous owner? Is it implemented?

You can! Just not Iif you purchase the city.

**Comment by yairm210** [comment]
Basically, if I make 'gift a city originally belonging to that Civ' be pike 'liberate' then they should be fine, no?

**Comment by lishaoxia1985** [comment]
@ozyxcv ,  can you test that how long the peace treaty, god/turn, defence impact and research agreement last in quick, standard and epic speed?  i will do something about research agreement.
thank you.

**Comment by refola** [comment]
> Basically, if I make 'gift a city originally belonging to that Civ' be like 'liberate' then that should be fine, no?

That doesn't work for city states or defeated civs.

**Comment by yairm210** [comment]
I think this is going on the "not going to bee implemented" list.
