### ISSUE TITLE
Make health of own city visible

### ISSUE THREAD

**Issue by Filius-Patris** [yairm210/UnCiv#146]
As far as I know, I have no option to see my the health of a city of mine. Either I'm too dumb to find the option, or this iformation should be displayed somewhere.

**Comment by yairm210** [comment]
You're absolutely right!
For now I added it in the text description,
In the future I'll add it at the top of the city button as a bar (also color coded green,orange,red fir convenience)

Sunday, 10 June 2018, 05:07p.m. +03:00 from Filius-Patris notifications@github.com<mailto:notifications@github.com>:


As far as I know, I have no option to see my the health of a city of mine. Either I'm too dumb to find the option, or this iformation should be displayed somewhere.
