### ISSUE TITLE
Enhancement: Improve battery usage.

### ISSUE THREAD

**Issue by Bacte** [yairm210/Unciv#1464]
When the game is running and waiting for commands, with music disabled, it shows 100% CPU usage of one of four cores available. Other similar turn based games with no map animations (like in this) uses nearly zero CPU usage when in idle state, being most cases the spected behaviour.

I don't know if it's hard to implement, or if it's even posible, but it could improve battery life and diminish heat, which is always welcome.

Awesome game, by the way :)

**Comment by r3versi** [comment]
Might be related https://bitiotic.com/blog/2012/10/01/enabling-non-continuous-rendering-in-libgdx/

**Comment by yairm210** [comment]
Added as a user preference in #1768, when the net version comes out it should be available
We'd like to hear your feedback then =)

**Comment by JackRainy** [comment]
I have done a short test on my Android: it works.
Disabling continious rendering decreases CPU usage for 40-50%.

**Comment by yairm210** [comment]
=D

**Comment by Bacte** [comment]
Tested in Android, played for about 200 turns with continuous rendering off...

It works flawlessly so far, no issues at all.
The CPU usage reported in idle state now is zero. ^^

Amazing job guys!
