### ISSUE TITLE
Display somewhere the special powers of your & opponents' civs

### ISSUE THREAD

**Issue by alextfish** [yairm210/Unciv#1493]
I like to play as a random civilization from all the list. But then once the map is generated, to check the special abilities of my civ, the only way I've found in-game is to go *back to the New Game* screen and hit the "Random civ" button!

Similarly, I don't always remember the special powers of the AIs I'm up against. I was fighting Japan for a while and thought I was just overestimating how much being wounded should reduce the damage they deal. It was only when I went to start a new game that I discovered their units had been fighting at full strength due to their faction special power.

It'd be great if perhaps the Diplomacy screen could show the special abilities of each faction, and perhaps have an entry right at the top for yourself that just shows your own special abilities.

Alternatively, at least the Civilopedia could have a category "Civilizations" which displays the same info that's in the New Game screen.
![2019-12-20 17 40 06](https://user-images.githubusercontent.com/414419/71278644-1121b900-2350-11ea-977b-ac14a1cbc69d.png)

**Comment by yairm210** [comment]
Civilizations in the Civilopedia is definitely needed, I'll think about the Diplomacy screen
