### ISSUE TITLE
Cannot change language on older mobiles

### ISSUE THREAD

**Issue by r3versi** [yairm210/Unciv#1499]
It isn't possible to change language on Android < 4.4 mobiles because they don't support API level 19.

Here is where the `UnsupportedEncodingException` is raised. 
https://github.com/yairm210/Unciv/blob/3f0e33df89454a2804ece9d2ea736ed3a1b432e0/core/src/com/unciv/models/translations/TranslationFileReader.kt#L3-L11

    Charsets.UTF_8.toString() // produces java.nio.charset.CharsetICU[UTF-8]
    Charset.forName("UTF-8").name() // produces UTF-8, no jokes :p 

Apparently the former isn't supported on older versions of Android. Switching to the second charset (plain **UTF-8**) should fix this issue (and all the related ones).

**Comment by naivekook** [comment]
I'll take it

**Comment by yairm210** [comment]
OKAY then, that explains why we were getting crashes on that, I was wondering because I checked and all Java implementations should contain UTF-8 and yet we were getting crashes from some people...

**Comment by yairm210** [comment]
Resolved by @naivekook
