### ISSUE TITLE
Back button can't end Unciv

### ISSUE THREAD

**Issue by Th-o-mas** [yairm210/Unciv#1513]
**Describe the bug**
I can't end Unciv with Android's back button.  I didn't find a corresponding button on the Unciv UI.  How can I exit the app? 
 Can it be a bug? 
Version 3.4.2,
 Android 9, 
Samsung Galaxy A 50

**To Reproduce**
1. Start Unciv
2. Press back button
3. Nothing happens

**Expected behavior**
The app ends or shows the dialog "Close Unciv? Yes - No."

**Comment by Th-o-mas** [comment]
Unfortunately nobody has written anything yet. I am bewildered! Does nobody have the problem? 

How do you end Unciv?

**Comment by yairm210** [comment]
I've had an Android phone for years now and I've never exited any program with the back button TBH
I always just move to the home page with the home button, or to another open application
It never even occurred to me that this would be a required feature

**Comment by JackRainy** [comment]
That was the very first problem, I had experienced, however easily found the workaround mentioned above: using the home button.
If it gets a priority, I volounteer to investigate and fix that.

**Comment by yairm210** [comment]
Fixed by @JackRainy  =D
