### ISSUE TITLE
Polynesian Trireme/Galleass should be able to navigate ocean

### ISSUE THREAD

**Issue by alextfish** [yairm210/Unciv#1514]
The [Civ 5 wiki states](https://civilization.fandom.com/wiki/Polynesian_(Civ5)#Strategy) that for the Polynesia civ, all their ships can cross open ocean. This includes ships that would normally be restricted to coast for other civs such as Trireme and Galleass.

However in Unciv, the Polynesian Galleass cannot cross ocean, though their embarked land units can.
![2019-12-23 11 31 23](https://user-images.githubusercontent.com/414419/71355720-d69a6500-2577-11ea-94a4-43dabe8bac89.png)

**Comment by yairm210** [comment]
Fixed by @lyrjie in #1522 =)
