### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by Remixion** [yairm210/Unciv#1531]
Missing Sentence to Translate

Welcome to Unciv!
Because this is a complex game,there are basic tasks to help familiarize you with the game.
These are completely optional, and you're welcome to explore the game on your own!

**Comment by r3versi** [comment]
PR #1524 should take care of this.

**Comment by Remixion** [comment]
And one more problem 'AI' and 'Human' isn't translated in 'Create game menu'.
Even if there is a translation in the files
