### ISSUE TITLE
Natural Wonder popup message

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1535]
I think it would be a good idea to make a new popup message when you discover a Natural Wonder:

Congratulations! The discovery of [naturalWonder] has increased the Happiness in the Empire.
Output if worked: 

And if you discover El Dorado, you can add:

For finding this wonder first you have gained [goldAmount]

**Comment by yairm210** [comment]
I think this is unnecessary, espeially since the notification revamp
