### ISSUE TITLE
Natural Wonder Old Faithful does not provide Happiness

### ISSUE THREAD

**Issue by MyElementApps** [yairm210/Unciv#1541]
The new natural wonders are a good addition to the game. But there seems to be a bug at least with the Old Faithful wonder. This wonder provides 3 happiness and 2 science according to its description and that is also visibly in the city screen. But when assigning a citizen to work on this tile only the 2 science are added to the city output. The happiness is not added to the national pool and is also not visible in the stats section. I think other natural wonders that provide happiness are also affected.

**Comment by r3versi** [comment]
Heya! Thanks for reporting this issue! The bug was previously reported and we fixed it in version **3.4.4**. Let us know if you are still affected by this bug in the newer version.

**Comment by r3versi** [comment]
@MyElementApps any news regarding this issue? Did you have to chance to update the game?

**Comment by MyElementApps** [comment]
Thanks for the reply, I will have a look today.

**Comment by MyElementApps** [comment]
It works now. 😀
