### ISSUE TITLE
Natural wonder great reef barrier won't make your ships leave the city

### ISSUE THREAD

**Issue by FoxDnA** [yairm210/Unciv#1552]
**Describe the bug**
If you found a city on the shore, but your only coast tiles are reef barrier tiles, your ships won't be able to get out of the city.

**Comment by lyrjie** [comment]
I don't think it's a bug, since Great Barrier Reef is impassable
[Reference](https://civilization.fandom.com/wiki/Great_Barrier_Reef_(Civ5))

**Comment by FoxDnA** [comment]
If you can't sail, you shouldn't be able to craft ships in the first place,
should you?

Il ven 27 dic 2019, 12:58 lyrjie <notifications@github.com> ha scritto:

**Comment by FoxDnA** [comment]
![Screenshot_20191227-130411](https://user-images.githubusercontent.com/59283248/71516513-a8839080-28a9-11ea-90d0-58731de0c1ea.jpg)
![Screenshot_20191227-130446](https://user-images.githubusercontent.com/59283248/71516514-a8839080-28a9-11ea-8f4b-6149a97999e2.jpg)

In this situation i have to recruit a ship only to leave it in the city so that others will be put in coast tiles outside of the reef... It seem stupid to me. Won't it be more reasonable to either let ships leave city or to build them directly outside of the reef?
