### ISSUE TITLE
Translations problem

### ISSUE THREAD

**Issue by RafeHaab** [yairm210/Unciv#1554]
Ok, guys; this is what's happening: I took the time to patiently translate all the famous quotes for each wonder to spanish **by taking them straight out the online "[civilopedia](http://www.dndjunkie.com/civilopedia/)"**, twice.

But someone keeps deleting all of them. So unless whoever is doing that agrees to stop, I won't bother contributing to the game's translations; thinking twice, I won't bother contributing at all.

So who's deleting my quotes, why, and will you stop?

**Comment by uvehj** [comment]
Do you mean in https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translationsByLanguage/Spanish.properties ?
They all seem to be there fine. Is there any missing?

**Comment by uvehj** [comment]
Y found 3 missing, no idea if you referred to them, but I've sent a pull request with those translated

**Comment by RafeHaab** [comment]
Thank you.

**Comment by naivekook** [comment]
@RafeHaab don't worry, if something gets into github it will be in history forever, so your work doesn't disappear
We have a lot of people who helps us to do the game perfect and shit happens
If you find if something wrong just ping us and we do our best :)

**Comment by yairm210** [comment]
So I'm going to mark this as closed
