### ISSUE TITLE
Natural Wonder Great Barrier Reef can have differnt output

### ISSUE THREAD

**Issue by Schallfalke** [yairm210/Unciv#1565]
I found the Great Barrier Reef (GBR) tiles can have different bahaviours, if being "naturally" generated by game or "manually" added in Map Editor.

To demonstrate this, I started a map which already have the GBR tiles (thus "naturally" generated).  They are the upper tiles in this screenshot.  They have output 1,3,1,2.  They count as coast tiles when enclosing the city tile (not demonstrated here, but in my another game), and allows harbor to be built.
![Reef Natural](https://user-images.githubusercontent.com/54190270/71550283-adf6ed00-2a07-11ea-8f98-870cb9d00594.png)

The lower GBR tiles are added by map editor (thus "manually" added).  They have lower output 1,2,1,2.  They do NOT count as coast tiles when enclosing the city tile (again not demonstrated here, but I have that in my another game), and not harbor can be built.
The original tiles are genuine coast tiles without any resources, if that matter to reproduce.
![Reef Manual Added](https://user-images.githubusercontent.com/54190270/71550296-f31b1f00-2a07-11ea-9e8e-f836af86910e.png)

Notice that the text labels are different as well.  The natural ones show "Coast + GBR".  The manual ones show "GBR + Impassible".  Maybe it partly contributes to issue #1552?

Here is the map file, if it helps.
[Map.zip](https://github.com/yairm210/Unciv/files/4007545/Map.zip)

**Comment by r3versi** [comment]
Hey, to be completely honest all natural wonders were bugged when placed by the user in map editor.
This bug has been fixed in https://github.com/yairm210/Unciv/commit/aa034d73c2eff5368dfbb8b6f555d5a7508305d7.

**Comment by Schallfalke** [comment]
Thanks for the work.

Just downloaded 3.4.5-patch1 and repeated the above test.
I found the problem still remains: "natural" GBR gives 1,3,1,2 while "manual" GBR gives 1,2,1,2.
Is it implemented into new version 3.4.5 yet?

**Comment by r3versi** [comment]
Unluckily the commit isn't part of any release yet. It will be in 3.4.6 (or 3.4.5-patch2)

**Comment by Schallfalke** [comment]
Just downloaded 3.4.6 and confirmed this is fixed.
