### ISSUE TITLE
Add battle related buildings

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#158]
Barracks, walls etc.

**Comment by mirdza02** [comment]
Military building should be added to increase the military power,also add military wonder (such as Sun Tzu's Art if War) which give extra benefit to the belongings civilization like promoted units or faster recruit time.

**Comment by mirdza02** [comment]
I have some suggestion for military building
-add military building that can build special unit like (Tavern to recruit Mercenaries9
-add military building that give benefits like faster recruitment for specific units or recruit promoted units
-add military wonder such as Sun Tzu's Art of War and etc
-add defensive building to increase the chance to survive from attacks
