### ISSUE TITLE
happiness should include global happiness and local happiness

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1594]
luxury resources and a few buildings produce global happiness, most of buildings produce local happiness, local happiness can't > population of city.
You can see this web:
https://www.carlsguides.com/strategy/civilization5/happiness.php

**Comment by yairm210** [comment]
Local and global happiness make things difficult, especially for new players. I think original Civ made a mistake with this.
Very low priority for me, if at all.

**Comment by lishaoxia1985** [comment]
i give an explain that the building has a unique "-4 unhappiness from citizens in this city" and don't use the word "location happiness". how do you think?

**Comment by yairm210** [comment]
I thought about this for a long time
My conclusion is that the split into local and global happiness in the original game was a bad one. It complicates the game, but without giving the player any meaningful choices in the process.
I'm not planning on implementing it into Unciv.
