### ISSUE TITLE
Map Options not retained when starting new game

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#1598]
When starting a new game after playing a game, the previously used Game Options and Opponent Count are retained, but the Map Options (map size, generation type, ancient ruins, etc.) default to the original settings and need to be reselected.

**To Reproduce**
1. Start a new game.
2. Change map options, game options, and opponent counts.
3. Start another new game.
4. Note that all options except Map Options were retained.

I would also recommend adding a "reset to defaults" button to clear user choices.

Version: UnCiv Android, 12/30/2019

**Comment by JoshDM** [comment]
Tight turnaround. Do consider a reset to defults button.

**Comment by yairm210** [comment]
I will =)
