### ISSUE TITLE
Songhai Civ

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1599]
We already have the Civilization icon, but the Mandekalu Cavalry and the Mud Pyramid Mosque are still missing, so we need to fix it.
Those are my icon ideas:
MANDEKALU CAVALRY
![mandekalucavalryicon](https://user-images.githubusercontent.com/41149920/71683455-e2193780-2d92-11ea-9dd5-53721c13843a.png)

MUD PYRAMID MOSQUE
![mudpyamidmosqueicon](https://user-images.githubusercontent.com/41149920/71683470-e9404580-2d92-11ea-85ad-24c757235f26.png)

**Comment by yairm210** [comment]
This is not a separate issue but part of #663 
As for the icons, the cavalry one could work, but the pyramid one is A. not filled and more importantly B. Not like a mud pyramid ( see https://live.staticflickr.com/8857/29595013121_0dd49c21af_b.jpg and based on it https://civilization.fandom.com/wiki/Mud_Pyramid_Mosque_(Civ5)  )
