### ISSUE TITLE
Map Editor rework

### ISSUE THREAD

**Issue by r3versi** [yairm210/Unciv#1605]
I'd like to propose two features for the map editor. 

**Composable brush**
Instead of selecting just one tile property (`base`, `feature`, `wonder`, `resource` or `improvement`) it could be useful to let users _compose_ their own brush (as long as the final selection is **compatible**). 
I think that adding this would be mean switching from the current behaviour of "apply the change to the tile as long as it is compatible with existing properties" to "override the tile as long as the brush selection is compatible". 

**Fill option**
The user can pick between two edit modes: **brush** or **fill**.
Brush is the usual mode where the user clicks on the tile he wishes to change.
Fill is supposed to determine the _connected_ group of tiles starting from the user _click point_ and apply the brush selection to all of them (following the behaviours described in the section above) .
I think fill is tricky because of the expected behaviour on composite tiles. 
How to determine the _connection_? By equal `base`? `base` and `feature`? `base`, `feature`, `resource`? ... ? `all`?
How to apply the change? Apply compatible changes or override?

I'd like to work on this features if you think these could be nice to have.

**Comment by ERROR1025-iop** [comment]
I think it is possible to add "NULL" terrain and customize the map size.
No unit can be entered as "NULL", nor can it be expanded by the city
Customizing the map size will mean that the map size can be modified by manually entering values instead of selecting from existing sizes

**Comment by yairm210** [comment]
> I think it is possible to add "NULL" terrain and customize the map size.
> No unit can be entered as "NULL", nor can it be expanded by the city
> Customizing the map size will mean that the map size can be modified by manually entering values instead of selecting from existing sizes

This is currently possible in mods by making the tile have no yield (this is the default!) and making it impassable.

As for modding map size, no. This is a design choice due to memory limitations on older phones.

**Comment by ERROR1025-iop** [comment]
So, I need a function that can adjust the size of the completed map and modify it to another size in the menu


> > I think it is possible to add "NULL" terrain and customize the map size.
> > No unit can be entered as "NULL", nor can it be expanded by the city
> > Customizing the map size will mean that the map size can be modified by manually entering values instead of selecting from existing sizes
> 
> This is currently possible in mods by making the tile have no yield (this is the default!) and making it impassable.
> 
> As for modding map size, no. This is a design choice due to memory limitations on older phones.
So, I need a function that can adjust the size of the completed map and modify it to another size in the menu
