### ISSUE TITLE
Stop automation/exploration/movement doesn't work

### ISSUE THREAD

**Issue by austinked** [yairm210/Unciv#1614]
I'm very new to this game, so I'm sorry if this isn't an issue. I clicked on automate worker, and it just made it so I couldn't use them anymore. Whenever I clicked stop automation the button turned green but nothing happened. I have the same issue with start exploration. I don't know if you're just not supposed to be able to stop them or if it's a problem on my end.

**Comment by michelfperez** [comment]
I have being playing this game for around one month, and this bug was introduced in the last update(yesterday). Before yeaterday we could click in stop exploration and the unit would stop the action, now if you click in explore the unit is lost, unfortunatelly turning the game unplayable.

**Comment by positron96** [comment]
I have just installed the game and have the same issue.
