### ISSUE TITLE
can't install android version of the game

### ISSUE THREAD

**Issue by warriormaster12** [yairm210/Unciv#1618]
Tried to install application and in the installation process it fails and gives you this "error". 

![IMG_20200105_104056_350](https://user-images.githubusercontent.com/33091666/71777383-de123300-2fa7-11ea-8763-bde3973161db.jpg)

My friend also tried to install the game and with no luck.

Tested with Samsung Galaxy S8 and Xiaomi Redmi Note 7

**Comment by yairm210** [comment]
Huh
What version does the app store show?

**Comment by warriormaster12** [comment]
Like Google play store?

**Comment by yairm210** [comment]
I'm confused.
What store did you initially download from?
What version did you try to download from f-droid?

**Comment by warriormaster12** [comment]
Initially we tried to download from GitHub. Once you meantioned that the game is in app store, I decided to check F-droid and there I couldn't even download the game.

**Comment by JonathanCote12** [comment]
I had the same problem trying to install the 3.4.8 on the 3.4.7, but uninstalling the 3.4.7 version before installing the last one worked for me.

Also, I had to download the 3.4.8 apk from F-Droid [website](https://f-droid.org/en/packages/com.unciv.app/). For some reason, the version that I get on Google Play and the F-Droid App is still the 3.4.7.

**Comment by rh-github-2015** [comment]
Remember: These symptoms are regrettably Android's normal reaction to attempts at installing packages with identical common names but different signing CA's. IOW, you *will* always get this when e.g. trying to install the separate APK over an F-Droid installation and vice versa. There's no option to switch sources but a clean uninstall which will delete settings, saves and similar data.

**Comment by yairm210** [comment]
Are you still encountering some sort of problem? Or can we close this issue?

**Comment by warriormaster12** [comment]
Installing the game through google play store worked just fine so I guess yes you can just close the issue.
