### ISSUE TITLE
how do i play this game on pc i have it on android 

### ISSUE THREAD

**Issue by JarofWizardry** [yairm210/Unciv#1628]
**BEFORE creating (delete this in the actual issue)**

Is your feature a gameplay feature from Civ VI, or from G&K or BNW? If so, don't open it in the first place - see Roadmap

Is your feature a gameplay feature from Vanilla Civ V? If so, it should go in https://github.com/yairm210/Unciv/issues/663 - post a comment there!

Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!

Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JarofWizardry** [comment]
i just want to know if and how to play this game on pc

**Comment by r3versi** [comment]
Here you can find a list of [Releases](https://github.com/yairm210/Unciv/releases). You can either download the packaged binaries (Unciv-OS.zip or the JAR and run it by yourself)
