### ISSUE TITLE
Force close on startup

### ISSUE THREAD

**Issue by shaness1** [yairm210/UnCiv#163]
I downloaded the new update and it refuses to start. It might be because I was trying to play a save from before the update, although I tried reinstalling and it didn't help

**Comment by yairm210** [comment]
Is your phone a Motorola? If so, I see your problem.
If not...? I have no idea :|
And what's worse is I have no real way of checking

**Comment by yairm210** [comment]
Thanks to everyone who notified me of the bug!
In the last version I added something that apparently works differently on different versions of Android =(
I released a new version right now, version 2.5.3, that fixes this problem - it may take a few hours to get to all the users though =/
If the NEW version doesn't work for you , contact me again!

**Comment by shaness1** [comment]
Thx for the quick fix! And yes, it is a Motorola phone lol I probably should have said that in my first post
