### ISSUE TITLE
Buildings that won't be auto-queued in city:

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1634]
Walls, Barracks, Castle, Armoury, Seaport, and Military Academy. Your cities will begin science production without building these. 

![Screenshot_20200107-215548_UnCiv](https://user-images.githubusercontent.com/49125947/71949367-e087af00-3198-11ea-9fa7-c97abd9699bc.jpg)

(I manually queued walls in this city)

**Comment by ninjatao** [comment]
@yairm210 I always propose to have an "addOtherBuildingsChoice()" to cover all unfinished buildings in case any commit breaks building choice strategy. It could at least make sure all building be built before building science.

**Comment by yairm210** [comment]
Agree

**Comment by yairm210** [comment]
Seaport should be in production buildings though

**Comment by yairm210** [comment]
Huh, this was closed a while ago and I forgot to close the issue
