### ISSUE TITLE
Remove zoom out limitations/ minimap expand

### ISSUE THREAD

**Issue by shaness1** [yairm210/UnCiv#164]
The addition of resolutions is awesome, but it feels like the lower ones restrict map view because you can't zoom out enough. I propose either removing these restrictions or adding more minimap functionality. Something like a long tap/double tap on the map expands it, and while expanded, tiles with enemies have a red X on them while tiles with friendlies have a blue/green circle? 
P.S. Sorry to be so annoying, I found this game two days ago and probably have clocked more than 35 hours in that time. If that's not a testament to how much I like this nothing is. Also, sorry for the wall of text in the google play comment section yesterday (you know the one lol) I hadn't realized you only had 350 characters to respond

**Comment by Am-per-Sand** [comment]
My hope is available resolutions are enriched with portrait oriented one day an minimap becomes collapsible or simply turned off.
