### ISSUE TITLE
Package it as a Flatpak and submit it to Athenaeum

### ISSUE THREAD

**Issue by ghost** [yairm210/Unciv#1649]
- https://github.com/flathub/flathub/wiki/App-Submission
___

- https://gitlab.com/librebob/athenaeum
- https://riot.im/app/#/room/#athenaeum:matrix.org

**Comment by alexpattyn** [comment]
It would also be good to submit it to flathub. This would be a good game to have on the librem 5 and pinephone later this year. 

https://github.com/flathub/flathub/wiki/App-Submission

**Comment by MayeulC** [comment]
I am currently looking at this.
Right now, there are two things I am unsure about:
- No svg icon file in the repository (this is a bit WTF for me) #1431 
- no domain name? #1728 

Otherwise, I am just familiarizing myself with the flatpak build process, and I am planning to submit that to flathub for starters (I didn't know of Athenaeum, it looks nice, and I don't see any reason why the work couldn't be reused.

**Comment by alexpattyn** [comment]
For the domain name I believe projects that do not have a website just use their github/gitlab page. So you guys would use com.github.Unciv.

**Comment by alexpattyn** [comment]
Although I do see your point about not wanting to use github as the package name, in case of migration later on. However, I am not sure if that is a huge issue for flathub. Feeds (https://flathub.org/apps/details/org.gabmus.gfeeds) had to switch their package name around since they were originally Gnome Feeds. I believe flathub handled the change rather well, but you would have to talk to that dev.

**Comment by MayeulC** [comment]
Well, I'm doing the finishing touches. @yairm210, do we have translated descriptions for the app stores, and a list of screenshots somewhere? I'll pick the one from [f-droid](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.unciv.app.yml) for now, with the screenshot from the github readme.

I guess the input on
- domain name
- svg icon

can wait a bit.

**Comment by yairm210** [comment]
Yeah, we don't really have an svg version of the icon

**Comment by yairm210** [comment]
We have translations for Italian and Ukrainian descriptions, IIRC, but I'm not sure it's mentioned in the wiki, I'll add that now

**Comment by DontUseGithub** [comment]
I can try to manually remake it as a .svg file tho I'd appreciate if you could help me by providing image files or links of each of those icons (7 in total) that are part of the logo. 
If that's impossible, then is it ok if I'll use similar icons, for example: to use this icon https://duckduckgo.com/?q=gold+bars+stack+icon&t=ffab&iar=images&iax=images&ia=images&iai=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F82%2F82306.png for the gold icon?

Alternatively (and probably a better idea) would be to come up with another logo that;s unique and memorable. You can give me some ideas and I'll make some mockups.

**Comment by MayeulC** [comment]
Well, if the source was a raster, maybe it's not worth spending too much time on this? It *could* look nicer in some cases, but I wouldn't lose sleep about it, I thought the icon was originally drawn in a vector format.
If there's a clear case for doing it, I would just redraw the icons in inkscape, they are quite simple, and using the vectorization tool in inkscape would make it very simple (maybe 10-20min). Y
Looks like icons are there: https://github.com/yairm210/Unciv/tree/master/android/ImagesToNotAddToGame

I can have a look at it if you think it's worth it (I sorta want to now), or I can leave it to you.

Of course, if you have better logo ideas, I'd ask yarim, but it looks like UnCiv went trough a few logos already :)

The packaging is basically done, I'm just waiting on the PR review.

> We have translations for Italian and Ukrainian descriptions, IIRC, but I'm not sure it's mentioned in the wiki, I'll add that now

Thank you. I would like to unify that somewhere. I am not sure about the playstore, but we can definitely have both F-droid and Flatpak take the description, screenshots, changelog and metadata from this repository. I'll think a bit more about this, and try to come up with a plan.

**Comment by DontUseGithub** [comment]
I can give it a go. We're missing one icon tho - the city.

**Comment by TheEvilSkeleton** [comment]
> For the domain name I believe projects that do not have a website just use their github/gitlab page. So you guys would use com.github.Unciv.

IMO it should be `com.github.yairm210.Unciv`.

**Comment by MayeulC** [comment]
I believe this issue can be closed thanks to https://github.com/flathub/io.github.yairm210.unciv which is now regularly updated.
