### ISSUE TITLE
Rome national bonus is not applied

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#1664]
**Describe the bug**
The Rome civilization has a +25% production bonus for the building built in the capital.
It is not applied so far.

**To Reproduce**
1. Create a new game playing as Rome civilizatoin
2. Found a capital A
3. Found another city B
4. Note the build time for Monument in the city B
5. Build the Monument in the capital A
**Achieved result**
The build time for Monument in the city B is not changed

**Expected behavior**
The build time for Monument must be decreased for 25%

**Comment by JackRainy** [comment]
![Unciv - Rome bug](https://user-images.githubusercontent.com/27405436/72218549-6febe400-3544-11ea-9937-34f169c7cea7.png)

**Comment by yairm210** [comment]
As stated in #1665 , gold, culture, science, production and food are meaningful in increments of 1. If the base value is so low that the percentage bonuses don't manage too reach even 1, then no change will be visible.
