### ISSUE TITLE
Add an option to notify you if it's your turn in an online match

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#1680]
**Is your feature request related to a problem? Please describe.**
When playing with a friend, it's basically necessary for you to have the game open at the same time and be actively playing together. Otherwise you'll never know if it's your turn or not.

Also, when playing multiple online games, you have to save/load each one again manually and check if it's your turn, which is a hassle.

**Describe the solution you'd like**
Add an option to get a system notification when an online match gets to your turn. Clicking the notification should automatically load this match.

**Describe alternatives you've considered**
I can't really think of an alternative right now.

**Additional context**
none

**Comment by yairm210** [comment]
Resolved!=D
