### ISSUE TITLE
Display names of resources on the overview tab "Resources"

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#1684]
**Is your feature request related to a problem? Please describe.**
When you go to the Overview -> Resources screen, you see a table with the resources' icons as headers. However, if you don't know all icons by heart, you don't know which icon represents which resource.

**Describe the solution you'd like**
When you touch/hover over the icons, the name should be shown as a tooltip. When you stop touching/hovering the icon, the tooltip should disappear.

**Describe alternatives you've considered**
You could also show the tooltip on click/tap and close it with another click/tap.

You could try to fit the name vertically maybe and show it always? 

I think just touching/hovering over the icon is the approach with the best UX.

**Additional context**
none

**Comment by Danciel** [comment]
When you tap the tile with the icon. The bottom right will show the detail of the tile. Like cotton, wheat, etc...

**Comment by Azzurite** [comment]
The tile is irrelevant. This ticket is about the Overview - Resources screen.

**Comment by Danciel** [comment]
> @Danciel The tile is irrelevant. This issue is about the Overview - Resources screen.

Oh ok

**Comment by Azzurite** [comment]
I'm implementing this issue.

**Comment by rh-github-2015** [comment]
While you are at it... Additional statistic 'number of unimproved resources per kind within your territory'? Or, 'did I miss mining one'?

**Comment by yairm210** [comment]
Resolved in #1817 =D
