### ISSUE TITLE
More variety of marine life 

### ISSUE THREAD

**Issue by Danciel** [yairm210/Unciv#1687]
Add more marine life like coral, shark, octopus. The marine life can improve culture like the culture eating puffer fish in Japan. Some marine life might be dangerous and will damage the boat. 

Add more building about the marine.
Discover undiscovered fish will improve science point for the city. 

Add village:
These guys are neutral and won't attack you unless you attack them. 
You can colonise them through friendly way (diplomacy, culture, happiness) or by force (attack them). They will often appear at the luxury resources or strategic resources or near the sea. 
Discover the village and colonise them in friendly way (take time) may improve city's culture and colonise in force (fast way) will just like annex cities

**Comment by Danciel** [comment]
Also make them a target for barbarian.

**Comment by yairm210** [comment]
As mentioned in the FAQ, our goal is to create a copy of Civ V, and any feature not in Civ V will not be added - https://github.com/yairm210/Unciv#will-you-implement-feature
But if you want, you can add it in a mod =D
https://github.com/yairm210/Unciv/wiki/Mods

**Comment by Danciel** [comment]
Thanks for reminding me

Vào 12:25 SA Th 3, 14 thg 1 2020 Yair Morgenstern <notifications@github.com>
đã viết:
