### ISSUE TITLE
Spectate features

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1689]
This is a popular suggestion on the discord so I thought maybe it would be good to have it down in writing. 

A few possibilities that would be nice:
1. Ability to create and spectate an AI-only match
2. Ability to continue spectating a match after the player is defeated (conquered)
3. Ability to remove fog of war (this would allow for 1. and 2. and would also help us bug testers see what is happening during a match!

**Comment by lyrjie** [comment]
#1681 adds  the functionality proposed in point 2.
To create AI-only match you can start a match and disband your settler right away.

**Comment by yairm210** [comment]
lyrjie's way is now the 'official' way of doing this =)
