### ISSUE TITLE
Display specialist allocation directly on the city screen

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#1696]
**Is your feature request related to a problem? Please describe.**
To play optimally, you need to manage your worker allocation in your cities. However, that is currently only possible by going to the city screen, clicking "show stats drilldown", then scrolling down a bunch until you find "Specialist allocation".

This takes a long time, especially when you're managing a larger amount of cities.

**Describe the solution you'd like**
Put the specialist allocation right on the city main screen. Already most of the screen is being taken up by worker allocation - arguably worker allocation is mostly what the city screen is **for**. Hence, the specialist allocation should also be directly visible.

There is currently a large amount of space on the right side of the city screen, beneath the production display, which would lend itself perfectly.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/2777158/72394574-067ff700-3737-11ea-9cc9-c48e849edfe4.png)
![image](https://user-images.githubusercontent.com/2777158/72394581-0da70500-3737-11ea-9a29-d35a743e9ff8.png)

**Comment by rh-github-2015** [comment]
This is a regression introduced by the construction queue... Exactly my first thought on the first queue-having version.

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/72844523-59acf900-3ca5-11ea-9a71-f5976df4f6f7.png)
