### ISSUE TITLE
Display amount of gold/science being produced in a city directly on the button(s)

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#1697]
**Is your feature request related to a problem? Please describe.**
It's a little annoying to have to turn on and off again the production of gold/science in a city to see how much exactly it gives you, by watching the production table, then subtracting the smaller amount from the larger amount.

**Describe the solution you'd like**
It would be much more comfortable if the useless display of "0 turns" (for production time) would be replaced by something like "72 per turn".

**Additional context**
![image](https://user-images.githubusercontent.com/2777158/72395016-675bff00-3738-11ea-8bfb-719291f3fef3.png)

**Comment by Kentalot** [comment]
I will probably take a crack at this as my first issue.

**Comment by Kentalot** [comment]
PR submitted.

**Comment by Kentalot** [comment]
should we close this issue?

**Comment by yairm210** [comment]
Yup :)
