### ISSUE TITLE
No free Aqueduct with tradition finisher?

### ISSUE THREAD

**Issue by qchenac** [yairm210/Unciv#1699]
I’m not sure if it’s a bug. Just found this weird. I was assuming the finisher would give a a free aqueduct in my first four cities as civ5 wiki says. Then I found the in game description doesn’t mention that...

**Comment by yairm210** [comment]
That's something of Civ V that I'm forgoing - the free aqueducts mechanic is just plain weird in original Civ:
https://forums.civfanatics.com/threads/about-the-free-aqueducts-in-tradition.467779/
