### ISSUE TITLE
unable to bombard if single unit in city and enemy 1 tile above

### ISSUE THREAD

**Issue by dafhi** [yairm210/Unciv#1708]
friendly popup covers enemy

**Comment by JackRainy** [comment]
There is a workaround: select the city by tapping at city name, try to attack empty space near the enemy - nothing happens but the popup will disappear, then attack the enemy as usual.

**Comment by yairm210** [comment]
Try as we may, there's no way to both have the city popup be big enough to be clickable and also to not cover anything.
Instead, you have 2 options:
- As JackRainy said, click the city name, an empty tile and then the enemy
- Deselect the current unit if there is one with the X button, then click the enemy directly - the city will automatically be selected and bombard table will pop up!
