### ISSUE TITLE
Bug report: New adjacent enemy cities eat pop

### ISSUE THREAD

**Issue by testott** [yairm210/UnCiv#171]
I was playing a match and had 7 pop in a city. An enemy city was created right next to a tile from my city, and therefore claimed the tile when it was formed. The tile had been worked by one of my pops before it got absorbed. After that, my city still showed 7 pop but i could only use 6 and was unable to place any more than that.

**Comment by yairm210** [comment]
Thanks for this!
This is indeed a bug!
I fixed it and the fix should be in the next release =)
________________________________

**Comment by testott** [comment]
Awesome, great work btw loving the game so far. I'll keep track of any other bugs i find
