### ISSUE TITLE
Allow specifying a path to save games

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#1710]
**Is your feature request related to a problem? Please describe.**
I would like to resume my game from one device to another, and have backups of my saved games.
Please note that I am not using google services, so I don't know if such a thing is already implemented with google play games (and this wouldn't work on PC, anyway).

**Describe the solution you'd like**
In the settings, a "savegame location" button that opens a storage access framework picker.
That would allow me to select any folder on my phone to be used, as well as Nextcloud/Syncthing/Dropbox/GDrive/other to be used as cloud storage.

**Describe alternatives you've considered**
Manual copy-pasting of the files: this is tedious, you need to plan in advance, or have access to both devices.

**Additional context**
The SAF method could be used for exporting data without requiring extra permissions, as in #1199 
Some other open source apps I know that leverage this android feature are Newpipe, Nextcloud, gadgetbridge, open camera, andotp

**Comment by yairm210** [comment]
This was solved a while back but somehow we missed closing the issue :)
