### ISSUE TITLE
Preview tile improvements on the worker's build menu

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#1711]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is a bit unclear which improvement will bring the most value, for instance when picking from mine or lumber mill.

**Describe the solution you'd like**
In the build menu, display icons next to the improvements to clarify what resources they bring: +1 production, +1 gold for one, +1 food for the other, -1 gold for build route, etc.

**Describe alternatives you've considered**
Well, until now, I was looking for information in the civilopedia, but I have to infer that information from the tile type. Having the bonuses determined automatically would be a plus

**Additional context**
I didn't find a cheat or console menu to spawn units/unlock tech trees in a new game, but here is a screenshot I took after a few turns:
![screen](https://user-images.githubusercontent.com/3952726/72618247-fc2e4a80-393a-11ea-9830-96dd0b3af0b0.png)
Here, the farm should show +1 food, and the pasture +1 production.
It could be interesting to show later improvements (depending on tech/buildings) and effects of citizens, but that could clutter the interface a bit. Maybe write it in the details at the bottom?

**Comment by yairm210** [comment]
You can click on the improvement (not the 'pick now' part) and it'll show it
![image](https://user-images.githubusercontent.com/8366208/72669934-7399d200-3a40-11ea-9662-0f5ca213193c.png)

**Comment by MayeulC** [comment]
Right, but the game already knows what kind of tile it is, so it could compute the actual bonus and display it for a quick comparison.

This is a feature request, so it's possible for you to refuse it, of course :)

I am unsure if it wouldn't be better aligned in a table, BTW.

**Comment by yairm210** [comment]
Ah, I see what you're saying, gotcha :)
