### ISSUE TITLE
Legalism doesn’t auto build museum or broadcast tower

### ISSUE THREAD

**Issue by qchenac** [yairm210/Unciv#1712]
I have just tried. Legalism does provide monument or temple if they were the cheapest available culture building but for museum or broadcast tower, the in game mechanics seemingly doesn’t recognize these two as the cheapest available culture building which I guess they should count one or I am wrong?

**Comment by qchenac** [comment]
To clarify, legalism was adopted after I have built the monument and temple ;)

**Comment by r3versi** [comment]
I see no issue relative to Museum. If you have a save game where Museum should be granted by legalism and it doesn't, please share it so we can check it. (Please check the save at the turn right before adopting legalism).

As for the Broadcast Tower, you are right: at the moment it isn't flagged as a `Culture building`. Tbh I don't know if this is a rational decision, or just a piece of code that must be updated. @yairm210 do you think it would be ok to flag as culture buildings all the buildings that grant culture? If so, maybe we can determine what buildings to flag as culture ones dynamically and not hard code them in 
https://github.com/yairm210/Unciv/blob/51ecb0e99d3aee975f59dc14390f0cdaca1d1784/core/src/com/unciv/logic/city/CityConstructions.kt#L282

**Comment by yairm210** [comment]
The problem with that is that 'all buildings that grant culture' includes, e.g., Wat, Mughal Fort, but it should work if you check the base building
