### ISSUE TITLE
Support for more recent jre

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#1713]
**Is your feature request related to a problem? Please describe.**
The default java implementation on Archlinux is `java-13-openjdk`, it would be nice if it was supported.

**Describe the solution you'd like**
I would like the game to run with openjdk 13.

**Describe alternatives you've considered**
I installed openjdk 8, but Unciv is the only program that requires it on my computer.

**Additional context**
Current error:
```
$ java -jar Unciv.jar
Packing textures - 26ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/mayeul/T%c3%a9l%c3%a9chargements/jeux/unciv/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by yairm210** [comment]
0_0
I have literally no idea how to do this, this sounds like an inner-LibGDX issue

**Comment by MayeulC** [comment]
Actually, it seems to work fine (with the warnings) with openjdk11 in a flatpak, but not natively on ArchLinux (works fine with jre8).
Needs more investigation, but I am tempted to close this as platform-specific.

**Comment by yairm210** [comment]
Fasinating

**Comment by yairm210** [comment]
Since this doesn't seem to affect being able to play the game, I'll be closing this
If you do have more information on this, is be glad to hear it for future users :)
