### ISSUE TITLE
Website and domain name

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#1728]
**Is your feature request related to a problem? Please describe.**
A lot of features might require the use of a domain name, and the game could use a landing page.
Instead of being dependent on github pages, I suggest we invest into a domain name.

The current app package name is `com.unciv.app`, both on F-droid and Google play.
I see two issues with this:
- unciv.com is **not being controlled by the project** (ovh tells me I can pay $35K for this :fearful: ).
- com is a commercial domain name.

For the first point, while I don't think Google or any other store checks it at the moment, some troll could get a hold of the domain name and ask the package to be removed.

**Describe the solution you'd like**
I suggest we decide and register a domain name as soon as possible. The domain name can then be pointed to some github pages. Ideally a github "unciv" organization would be made, with a repository for the website. I can handle the domain name registration & configuration if needed, as well as some rough initial website (I am not a web designer by any means).

**Describe alternatives you've considered**
I suggest we have a look at the `.net` TLD, which is available. This would cost €10/year.
A few other possible TLDs:
- space (€8) -- has some space race conotations, but might be a better fit for an alpha centauri/beyond earth conversion
- dev (€10)
- download (€24 initially, but then just €2)

More expensive fitting ones:
- earth (€18)
- games (€18)

Alternative ones:
- unciv-game.[anything] (including .org for €9)

**Additional context**
I would like to finalize this ASAP, as I would like to incorporate it in the package name for #1649, and it might be desirable to change the package name for the main app.

This can help combat cybersquatting as I have seen with newpipe, and SEO problems where someone else registers the website, puts ads on it with a download link to a malware-ridden app, which ends up higher in the search results.

It's a shame we cannot get .org for this. Please do not put full unciv.tld names in that thread, I am afraid some bots might see them and perform some cybersquatting, though the chance is slim...

**Comment by yairm210** [comment]
I think this is way overthinking this
I have no intention atm of making a website, and changing the package name means making a completely new Google play entry, losing all your downloads, ratings and reviews, and resetting your SEO. I've had to do that once before and I'm not going to do it again, this is an unacceptable move for me.

**Comment by MayeulC** [comment]
Not changing the package name is fine, but I think that having a domain name is probably going to be necessary at some point, and I would prefer avoid cybersquatting of the domain names, while building some momentum in the search engines.
Moreover, I am currently looking at packaging the app as a flatpak (#1649), and I would like a domain name to use as a base. This might be way overthinking, as you say. But that would also allow more flexibility in the future.
I can register `unciv-game` dot `org` myself, and transfer ownership to you in the future if you want.
This could enable the following in the future:
- Better matchmaking (STUN server, dedicated resources)
- Browser version
- Mods, resource packs, etc. downloads
- Independent of Github, in case a migration happens in the future
- Better onboarding for new players
- Controlled domain name for
  - Package names
  - e-mail adresses
