### ISSUE TITLE
Insta-skip turns

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#1732]
**What happens:**
Having a lot of units can be annoying to skip all the time. especially great generals who wake from 'sleep' whenever an enemy unit comes close, but when they're close to the front line (that may not shift for a while) this can be every turn.
Whilst this isn't too annoying on PC, on the phone, it's very tedious.

**Describe the solution you'd like**
A way of skipping all unit moves before ending a turn, like it is possible in the earlier versions of Civ. I suggest tapping and holding the "next unit" button, and after 3s, it autoskips units. If there is unselected policy, research or another critical alert, the function won't work. 
The function should not auto-sleep the unts, as when a player decides to act, it should be simple for them to find the rest of their units. (the 'units' section in the menu really helps with this, so great work there)

This would be a huge quality of life update for warmongering games, and help streamline gameplay

**Describe alternatives you've considered**
* In the "Units" menu, you could have a button besides units which lets you sleep units easily when it becomes next available to them, so you don't get alerted to units you don't care about.

**Comment by yairm210** [comment]
Menu, options, check for idle units - no
Does that solve your problem?

**Comment by Whistler11** [comment]
Hmmmm. Yeah... Actually, that would! 
I am embarrassed for not being able to think of it myself. 

I think, eventually, a more polished version would make the option faster to access than to enter the options menu each time. But your suggestion would easily make my experience smoother.
Love your work!

**Comment by yairm210** [comment]
Okay, I'm closing this for now then =)
