### ISSUE TITLE
Workers automate roads without considering current roads

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#1734]
**Describe the bug**
Workers automatically constructing roads will sometimes double up on roads between cities. This can double road maintenance costs

**To Reproduce**
I don't know how to recreate it, but (using the image uploaded as reference) I have deconstructed roads before and automated workers will simply rebuild them each time.

**Expected behavior**
I expect workers to just link cities by constructing roads to the closest road by the shortest possible path. If I want a more efficient route, or if the side of a triangle is left out, I can do it myself.

**Screenshots**
![Screenshot_20200120-181326](https://user-images.githubusercontent.com/60082415/72706320-d78fd800-3bb1-11ea-8675-68a6e2e56103.png)

**Comment by MayeulC** [comment]
Just a small detail: you can disable road creation in the settings. I did so when my workers insisted on constructing a long road between coastal cities (while I had planned to build a harbor later).

Maybe this would warrant an advanced screen for worker automation? I always wished to list them, blacklist or otherwise reorganize the planned improvements.

**Comment by Whistler11** [comment]
You can?? I'll probably do just that then. Upgrading roads to rail could be a pain later on though. 
I will do that from now on, and this resolves my issue with the roads, but I think this is still a bug to be addressed eventually.

**Comment by JoshDM** [comment]
They also simultaneously automate way too many roads without considering roads being built. 

A recent government assigned automated project:
![Screenshot_20200312-105502](https://user-images.githubusercontent.com/3236760/76535879-f55f1800-6451-11ea-8293-d382669c907b.png)

**Comment by yairm210** [comment]
Solved recently by @ninjatao
