### ISSUE TITLE
Add a Changelog to the repository

### ISSUE THREAD

**Issue by MayeulC** [yairm210/Unciv#1741]
**Is your feature request related to a problem? Please describe.**
It is a bit hard to know what has changed from one version to another, as a player.

**Describe the solution you'd like**
I suggest a changelog be added to keep track of the changes. It can be a file in this repository, automatically parsed to be displayed in the [F-droid](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) and Flatpak stores. Not sure about google play, but it could be pasted there as well. Additionally, the changelog could be displayed in-game after an update.

It doesn't have to be a lot of work to maintain. As an example, RiotX has a [CHANGES.md file](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md), in which they write a line when a major bugfix or change happens.

**Describe alternatives you've considered**
No changelog. This is also fine, but changelogs on app stores also show that the application is usable (it gives an idea of how far along things are) and in active development.

**Additional context**
This is more a question/discussion I am writing here instead of making more noise in #1649.

**Comment by yairm210** [comment]
I can't imagine how this would work well 0_0
There have been almost 400 versions so far
Someone suggested to use Fastlane, I think I'll give it a shot

**Comment by yairm210** [comment]
So fastlane divides each version into its own file, which makes it easier for parsing for computers but definitely not for humans.
Would be really annoying to go though manually.

**Comment by Prosta4okua** [comment]
You can write changes when you make release.

**Comment by Whistler11** [comment]
he does lots of tiny releases. like... a couple every few hours here and there. I think that'd be exhausting to keep on top of. I just check the code changes and track it that way.

**Comment by MayeulC** [comment]
Somehow, I had not realized that you had implemented this. Thanks a lot, I'll try to use it for FlatHub releases!

Maybe I'll have a look at integrating it with F-Droid as well, but I am less familiar with their architecture.
