### ISSUE TITLE
Some letters are not  supported 

### ISSUE THREAD

**Issue by rayray61** [yairm210/Unciv#1753]
Game's font doesn't support some letters

**Comment by lishaoxia1985** [comment]
you should say which letter. in fact, it uses system font, if your system don't support, it doesn't support too. it's not a bug. some strings have not been translated so it may show in english.

**Comment by yairm210** [comment]
which letters?

**Comment by yairm210** [comment]
Found your Discord comment =)

**Comment by yairm210** [comment]
Solved in e419443
