### ISSUE TITLE
Legalism auto enabled in 3.5.5

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#1758]
**Describe the bug**
No more scout, but a free monument in every city?

**To Reproduce**
From version 3.5.5 I get a free monument whenever I build a city. I tried starting with Korea and Babylon, both building a couple of cities. It seems like I get Legalism for free (had no policies unlocked).

**Screenshots**
![image](https://user-images.githubusercontent.com/21982451/72972623-14cfb200-3dcc-11ea-9da7-4cc3822a0a83.png)

**Comment by lyrjie** [comment]
Was already fixed in #1747
Thanks for reporting, still
