### ISSUE TITLE
Cost for multiple units of the same type is wrong

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#1759]
**Describe the bug**
I've been producing a unit for some turns. Say it took 30 at the start and 19 now, just because I put in production. If I look at the costs to produce that same unit again (add 1 to the queue), it will say 19. That is wrong, it should be 30.

In this example I've been working on a worker for several turns, but as you see every next worker will show 19 turns. It might be that this calculation resets when the first item of the queue is produced, haven't checked that.
![image](https://user-images.githubusercontent.com/21982451/72973934-6ed17700-3dce-11ea-8dea-cba96949030a.png)

**Comment by yairm210** [comment]
This is indeed a bug, which has to do with how you calculate how long a construction will take
@r3versi

**Comment by r3versi** [comment]
I see, let me think of a nice solution to fix this.
