### ISSUE TITLE
Missing features on implemented buildings or wonders

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#1762]
**Describe the bug**
Some buildings have missing features:
Forge (+15% production on land units)
Machu Picchu ( must be built near mountain)
Terracotta Army (duplicates current existing unique type of units)

Buildings that provide specialist slots, dont mention this ability in their tooltip.
(e.g. workshop, temple etc.)

Some building are mentioned in social policies but they don't exist in the game yet.
Complete Autocracy (Arsenal)
**Not mentioned in Complete Autocracy but probably should be (Military Base)

 

**To Reproduce**
1. Start the game
2. Look at their in game descriptions
3. Show shocked face

If game data is required, please add from menu, save game, copy to clipboard, paste here
NA
**Expected behavior**
The features mentioned should be there.

**Screenshots**
NA

**Additional context**
Did not mention buildings that require river but hoping for them to be implemented soon :)

**Comment by yairm210** [comment]
Terracotta is a BNW thing (https://civilization.fandom.com/wiki/Terracotta_Army_(Civ5))
The others are correct though

**Comment by Alkeif** [comment]
Oh I see. Another one. Neuchwenstein can also be built if there is a mountain within 2 tiles of the city tile. 
Observatory is correct.

**Comment by yairm210** [comment]
So it looks like we've solved all the issues here! =)
