### ISSUE TITLE
Lock worked tiles assignment

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv#1779]
H3110 guys! (•ω•)

Sometimes it’s annoying that the cities changes the population assignments on tiles after pop or border growth - especially after when players have manual settings made on the population assignments. 
I have a couple of times the population shifted away from the tile I wished to work on (especially food, there’s a couple of times people automatically goes mining rather than farming and the city starved), causing some production/population targets cannot be accompanished. I have to manage the assignments each time this happens.
(Note: this is not a bug)

In Civ5, players are able to ‘lock’ population assignments on player-selected tiles, which can effectively prevent the cases I mentioned above. This feature can solve the problem.

To lock tile assigment in Unciv, my idea is: doing this in the way that in a similar manner as buying tiles. The only difference is the lock action is reversible.

Hopefully this feature can be a useful feature in Unciv. (>ω•)
(And sorry if I have poor expression skills)

**Comment by TeagueLander** [comment]
How about tapping a tile once locks it (would put a little lock icon on the green citizen icon) and clicking it again would unassign it?  Or how about not allowing one to unassign anything, and locking an unworked tile would automatically unassign another (lower yield) tile.

**Comment by yairm210** [comment]
I think that Civ V works in the first way
