### ISSUE TITLE
Iron production ?

### ISSUE THREAD

**Issue by SuperPaprika** [yairm210/Unciv#1785]
Just dowloaded the game and i love it. One question though: I have a tile with iron and built a mine on it and connected it to my city. Still, the game doesn't allow me to build swordsmen and says I need iron. Did I misunderstand something there about how iron is produced?

**Comment by TeagueLander** [comment]
I wasn't able to reproduce.  Do you have a save game you could post?

**Comment by yairm210** [comment]
I see this was answered in the Discord :)
