### ISSUE TITLE
Popup once known nation learn/earn a new tech.

### ISSUE THREAD

**Issue by rdebaguio** [yairm210/Unciv#1786]

**Comment by yairm210** [comment]
Nations learn new techs all the time, this doesn't sound like something important enough for a popup. Maybe when they advance an era you could get a notification

**Comment by rdebaguio** [comment]
Well that makes sense.

My reason for this was that, I do have the tendency to check diplomacy in
every turn for every update other nations may have had for me to capitalize
on.

Would be great if there's an option where we could turn on those small
details.

Thank you!
