### ISSUE TITLE
Able to set maximum era at start game.

### ISSUE THREAD

**Issue by rdebaguio** [yairm210/Unciv#1787]

**Comment by yairm210** [comment]
How would this work? Once you reach that era, what happens with the science?

**Comment by rdebaguio** [comment]
I haven't actually thought past it (science). I was just checking out if
there's a probability ending the tech in a certain era and not continue
further eg Medieval era. If it's not possible or if it wouldn't make sense
its definitely fine. Thanks for looking into it.

I really love the game.

**Comment by yairm210** [comment]
It would be possible, but as of now I don't know how this could work, gameplay wise
