### ISSUE TITLE
Make DESTINATED ROAD-PAVING return! (^ω^)

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv#1795]
Before the long tap function was removed from the game, workers can pave road from their initial position to the destination given by the player via the long tap options.

Now this useful function was gone since the long tap is removed...
[Sad Violin meme intensifies 🎻]

So here may I introduce my idea (•ω•)
This is the way I suggest how to command workers to pave road from their initial position to the destination:
• Choose the worker.
• Tap on somewhere else accessable.
• The tile shows 2 command options, illustrated as follows:
![explain](https://user-images.githubusercontent.com/57716526/73233945-1382f880-41c3-11ea-8c1b-3693b859a87b.png)
Clicking on the road icon will begin the destinated road-paving.
Workers will pave roads/railroads one by one until the destination tile got a road/railroad.

**Comment by yairm210** [comment]
This was removed since it was bugged, not because of the long click.
We could try to make it with again, but my point is it's not just a UI problem.

**Comment by GeneralWadaling** [comment]
> This was removed since it was bugged, not because of the long click.
> We could try to make it with again, but my point is it's not just a UI problem.

Oof

**Comment by r3versi** [comment]
> This was removed since it was bugged, not because of the long click.
> We could try to make it with again, but my point is it's not just a UI problem.

What was the issue @yairm210 ? Using the BFS search to determine the optimal path to other cities (in a 2-way dumb enough way) isn't good enough?

**Comment by yairm210** [comment]
TBH I didn't check it very deeply, since it was bugged and the long click was causing problems, I solved both at once by simply removing it
It should be noted that automated workers currently build roads between cities, but not in a very smart way - see #1734

**Comment by yairm210** [comment]
Merged into #663 which was where this should be =)
