### ISSUE TITLE
Unit type and promotion have the same string "Siege". Luxury resource and basic resource have the same string "Gold".

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1804]

**Comment by yairm210** [comment]
Okay, how do you suggest we solve this?

**Comment by lishaoxia1985** [comment]
change the promotion name "Siege capability", maybe.

**Comment by lyrjie** [comment]
May I ask, why's it a problem?

**Comment by lishaoxia1985** [comment]
@lyrjie it in the different place will have different translation or different mean.
