### ISSUE TITLE
Rectangular maps and map generation algorithms

### ISSUE THREAD

**Issue by r3versi** [yairm210/Unciv#1806]
Hi, I created this issue to notify you I started working on implenting rectangular maps and improving map gen algorithms (with help by CPT. Klutz).
The rectangular map (although it is ready) cannot be deployed yet because the mapgen algorithms don't work well in such a shape.
The following is a sketched to do list; if you have requests/suggestions post them below!

- [x] rectangular maps
- [x] archipelago map type
- [x] mapgen advanced settings (height, temperature, moisture etc.)

**Comment by Whistler11** [comment]
This sounds great! excited for this feature!

**Comment by hyunamae** [comment]
I hope this don't take eons. I'm very excited for rectangular map : 3

**Comment by krijnsent** [comment]
If you need inspiration, this is a tool I made a while ago for rectangular map generation: https://steemit.com/map/@beeheap/create-a-fantasy-grid-map-in-excel

**Comment by r3versi** [comment]
Kudos for doing this in excel and thanks for sharing it! It's really close to the approach we took. Once the PR is ready I'd like to receive your feedback about it

**Comment by krijnsent** [comment]
I had a swing at the current version and map editor, here the "unsorted feedback" which I maybe should spread over several issues:

Map editor:
- in the map editor, a button to get to "generate new map" with settings would be great, now have to exit the editor every time I want to make a new map
- can the map editor please remember my last settings (map size, pangaea/hex etc)?
- is there some description of the map file format, it looks base64, but I can't make much sense out of it? (To make my own maps and e.g. a world map with my excel tool ;-))

Map generation:
- with the default settings (for which I saw also a "restore defaults" button is in the works), the mountains look very spread out: you hardly see mountain ranges but lot of lonely Kilimanjaros (mountain on a plain). With Perlin noise, you'd need some more of the higher octaves to smoothen the map.
- I think lowering the lacunarity and increasing the persistance helps creating smoother maps, but I'll have to modify my excel to give that a try (don't have Kotlin skills). See e.g. the lacunarity images here: https://gamedev.stackexchange.com/a/20909
- in general, as mountains are almost useless, you probably want to limit them to 0%-5% of the map, but I guess that's something for an improved UI: the basic sliders work great to get an idea of what's possible (set mountains to max for an unplayable map :)).
- continents map: I see you're slicing the map in 2 in the middle with getTwoContinentsTransform. This does have 2 consequences: the total land mass on the map decreases vs Pangaea (as far as I can see, there is no tile counter in the map editor) and there is a massive ocean in the middle. I would opt for a "softer" and smaller line down the middle and raise the rest of the land a bit to get to the same land percentage as the Pangaea map. A less reliable alternative I'm using in my excel tool is to use Perlin noise settings and trust that outcome. 

I'll see if I can update my Excel tool to help with some concepts for better map generation, but don't know when I'll have the time for that.

**Comment by Eddh** [comment]
By the way if we want to make maps in which the left and right side wraps so that we can go around the world seamlessly we need to make some kind of cylinder in 3D perlin noise like the 3rd comment here says https://www.reddit.com/r/proceduralgeneration/comments/37azql/using_simplex_noise_for_2d_horizontal_wrapping/

**Comment by krijnsent** [comment]
@r3versi Any chance the map specs can be specified somewhere and/or can you point me to the right place where this can be found?
