### ISSUE TITLE
BUCKETEER’S UNIT SPRITES - For FantasyHex!

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv#1826]
Hello sir!

Here introduces my sprite pack for replacing the current sprites of the implemented units.

[FantasyHex MKII Unit Sprites Vol1.zip](https://github.com/yairm210/Unciv/files/4143724/FantasyHex.MKII.Unit.Sprites.Vol1.zip)

**Comment by GeneralWadaling** [comment]
More sprites will come - for those un-implemented units and even units from Expansions!

**Comment by yairm210** [comment]
The units need to be put on a 32*28 tile in order to be able to be displayed in-game

**Comment by Whistler11** [comment]
_I am so ready for these_

**Comment by Whistler11** [comment]
How will these work to be discernable between civs? like which are mine and which are the enemies?

**Comment by yairm210** [comment]
@Whistler11 these come as an addition to the current icons, not instead

**Comment by yairm210** [comment]
This was added waaaay back but we forgot to close the issue
