### ISSUE TITLE
Bug report: "stop moving" & "move unit" buttons

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#183]
Units start turn with a button in "stop moving" state even though they don't move when tapping on map. To make them move you have to press the button twice to enter "stop moving" state.

**Comment by yairm210** [comment]
This happens I they were on the move but there's an enemy unit nearby
You're right, though, their move action should probably be disabled entirely and not just put on hold

Thursday, 28 June 2018, 00:56p.m. +03:00 from Am-per-Sand notifications@github.com<mailto:notifications@github.com>:


Units start turn with a button in "stop moving" state even though they don't move when tapping on map. To make them move you have to press the button twice to enter "stop moving" state.
