### ISSUE TITLE
Improvements to the Diplomacy screen

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#1830]
**Description**
While playing versus a lot of civilization the diplomacy screen looks useless.
(Do you see my Rome empire here? =))
![Unciv 2020-02-02 17 34 23](https://user-images.githubusercontent.com/27405436/73610680-c77ced00-45e2-11ea-880a-0c2a4ddff422.png)

**Solution**
I am going to rearrange it a bit: get more space between the Civs.
Also, I would like to highlight the more strong relations with more bright colors, and the neutrals - more grayish one.

**Describe alternatives you've considered**
The screen can be replaced with the table of relations, however, it seems to me too official and nerdy.
However, any input is welcome.

**Comment by yairm210** [comment]
I was thinking of adding an onClick to the various civ buttons that would show only the relations to that specific civ

**Comment by yairm210** [comment]
Doesn't conflict with spacing and highlighting of course, is tangential =)

**Comment by JackRainy** [comment]
@yairm210 , I assume this is the behaviour you have mentioned.

![2020-02-05-00-28-08](https://user-images.githubusercontent.com/27405436/73793918-02804b80-47b0-11ea-8330-d5d9459f2fc3.gif)

I put it in the PR #1851.

The further improvements are to add the "Open borders" indicators.
