### ISSUE TITLE
Game crash when annexed city state influence degrades

### ISSUE THREAD

**Issue by CaptainKlutz** [yairm210/Unciv#1835]
**Describe the bug**
Allying to a city state which subsequently gets conquered by a civ, then having your relationship degrade crashes the game.

**To Reproduce**
1. Load https://pastebin.com/E3EDqr7Q
2. Click 'next turn'

**Expected behavior**
Game safely exits loop when it can't find an existing city state to degrade relationship with.

**Comment by yairm210** [comment]
Thanks!!!!
This is indeed a bug! Fixing, will enter 3.5.9-patch1!
