### ISSUE TITLE
Police state

### ISSUE THREAD

**Issue by Rodri3003** [yairm210/Unciv#1838]
What about changing the police state policy, in original Civ V it was not the maintenance of the city borders once it is conquered; it was a +3 on happiness from each courthouse and build Courthouses in half the usual time. This wouldd be (in my opinion) a good implementation in Unciv since conquering cities in the actual version of the game is horrible because they never maintein their borders and feels a bit bad when you have to pay in order to recover the lost tiles.

**Comment by Whistler11** [comment]
You mean like... keep the police state policy as it is instead of updating it when they adjust for BNW?

**Comment by Rodri3003** [comment]
I'm not sure and correct me if I'm wrong but, are you telling me that police state is changed in CIV 5 for the BNW expansion as the way is now in UNCIV (maintenance of conquered city borders)?

**Comment by JackRainy** [comment]
Fixed in #2105 (now it is about Courthouses)
