### ISSUE TITLE
Ability to place Great Person Tile Improvements over unimproved terrain 

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#1842]
In Civ V great person tile improvements function much like cities in that you may place them over Marshes, Forests, and Jungles. This also clears those terrains. (You would also gain the same amount of extra hammers from clearing them in this way as you would have by chopping them with workers)

**Comment by yairm210** [comment]
I'm pretty sure this is already the case, if not please send me game data

**Comment by ozyxcv** [comment]
![Screenshot_20200204-134311_UnCiv](https://user-images.githubusercontent.com/49125947/73780611-65dc9000-4754-11ea-872a-633076a63498.jpg)


<details>
<Summary> tried to make it easy for ya </summary>
H4sIAAAAAAAAAO1dXXPbuJL9K9p5JlMCv6k3x5OvrTjxxpmdh1QeIAmyWSORWkrKxOPKf1+ABImmCEhHvpm6s1VbdyqXpsCDRqO70d1ogk+L4luxLv7i+6Iqd7MvT/LvD3wjZi95Ped1wcudd1+tl6K8uhe72VN52MxF/XH1xtwLvN2+qsXyLd9ui1LsdrN0+sO7rwXf34pquxazJ/1HvavK26oo9xLoxw9vW62LRaFQ1fX2sL1ai3qviNg/bsWs78L7xtcHMfvllx+e85ev3k5ClQvx38VCUvOoMPdi8TB7Uv/uPomd4PXiQSxnX67u62JxWO8Ptfj6w/vWtr/hJb8XdUOX5MFekaWYsX+8lnzZ14dFy6Cn+aFY71/Kf5ZFeS/b3PI1XwjvveClvDH5XP0p6km1mtwWO+59fhCTjzVfrIX3lpf3qsEbXkvad95tVS/Emhdl+4j3ppYU1I/e3b4qxYMo79Uj9wWf3FXbh4J/9RaHuhblnpIz+1DtHySo7bd3u992or4T+5m8I7yivK0rOQ273dF4FInvq8O3WsyCZCpHr8Z8t+fNHHni+1ZKgOrqSbPsrpnrpq23qg6lYsN18U3Ky/xxXZVesZzlSc6yMA18nky5H2VR6M8zsfLjeSiWIsmzKFt662rRyNzs6fss9x5nwQ+vbOWuxVECsdYtVlW11P2yhP7CMm+3FYuCr4udFqp9sW6m7vssk6hMzqa8av5N+r+Ttj/dxlyF/VXUXLGpvIz7m755urtsmzHzBOsBm8sWMe9hmpvMgAfmsm2amhuEhvaJtH8gHdzzzaXpL+ivWH+lf+3/JjTHUoP+rOo/xPKzYeBJFrFTfBly4RRvsAGTcTiol/S3anutbI2SFM+YslakpDCvlRCZERKROKL7aDD+MQdYYCYyMOMKCF2jCWdWroS9cMR9U/N30F9pamJDDZsezTth3bF0RYa++IiPRj6CI97mplvN5p7i0Fwa1hnh8Il0BEQHh4JjmDrSt4ZSwurEpkihuUxO64UmIrXoUdQTER8rY3NpejbKlZjRR1Lw1AI5i6VpuniljIPzK6U2vJIP2YssivLA29bVUq8AjGUvoiCIwm79k1QFL1iSZWpNVQCvq/qD+L5/Y4BnwXSqrK1E5evfq3Ip786+NA0mctmvC7mCfRJi5b1aT36tar6svnpltS9WxaJ3E3jb/dNizeUwFtXmxaGU+vZiXd0XixfUqXjxXlv6q+aR3vC3GtiKnVyHF5XUzdkTl3p7r+ZwL2me/fJF6+7XyQPfTe7r6s/yP5Qb8Hd2P59NX0zTKJ7mmaJl+iJIp3GWBbFXyz/i5odp2lOoF+6WwrkQ5aRxESZyZe+pv5Dka7kEa3LVamyWyH+Bzt+lcW9I3O15Le3jpJL0qZui/qrcp+2aP4r6s3Kv3h42vCTemRSArXzitrvx5UbUxb5aSMfm0fss5aNoSH1fSHnfP06uq40U5b3w5DCKv6Sv81BsvU9iK50P6aNw2tZ7XQuxrDbq58NcwstnJB+kzyM7kj//Kja6m9/K4psUUy5/O6xWtfTVvOtqvRaSS9/E5NNhrf6Wjk2xP6gOpMBq9bs6Il5ai1YJr7VaBZHUZpfzqO9/XL3nu332+VAruYkiz/bf1+aZ3bve05o9fRKrupBuJe90ddoCD/zRj9t9sdhJx0/wzeS2cQavFtVh19y9KZRb6d1xKR3y/19JvW85eKWelv7ideP6SQ69OZTb6k+py95ryVolTPLyRuwly64l8c3Ti6qsNgqWOoENVCHJUuzwXvLyD9VWzaIUVO9tVe/EnC/+mHwqls0PD2IjvS3Z9btyKamslffVCq73sq7Kv8REiVVDteJeYzcm0s2UjPVuH4p1tZMe7aMc2bqQovg4uWt57N3W0lwpF/lWMc+74XvZE2+48Eb52zvvZSGl/14+yiXBpRr9K+VUCymOsjc1DC7aFq+UZEg3v1BC9CgdSzk+6XLv9+ohEgB47yTFPb2filXDZUVsA/OBfyvu26F9kjNQV3zpXfO1KJdc8pZLW9p47EKs5cged4pUqQ/KuCs+FTI6kb8rD/v3B9Xmqiw2cjreHnZzXi7lT79LPWratlIvahmNiHbS1odaEnAl+avm7FEL1+eqk5zZl4Fwea/Xxf3DXimSikf4fC0mt1LRd5LwZVFphlSlIvF2zVvheim7KdrLq70SjG6a5DNygLcPvN5IMKlRC77eeR8OMpDh9eR1sVMhgRKndjqqufSoJp+VhVvsfkJMdVNJ7ZWS43XBVTGvueZku0x1dzrja42Obri0bnt36NP+PgtzOOph0TDoeXX/uN2rkCcIwoixgPmLQMR+tJwyPw+ncz+RwU8QZQu24qtByONrr6eJeeS45mLnCnnClP6Sn4h4fONK+Wnv0PjGa/WT3nlp7pLL2DxGEBJzqRGIN9mg6eeMf+Tn2iuSfJOL7v8cCjWIeBRdHHcVWymMT9FChkDJ0gS0QgfLGiRS75WSPUjjfCKiNm1mYQKLVuaQrDAOwiRfBH4ULlIpWWzqz5fhwl/mYRaGLMvTo2Da77z2RrRuxGb7UDhlK87pL6ei6ZbD2o/2MzMB2svWvzMzSYy0CWgbIidd+5w0ynVb1rY9FiQ2lqRB15mdAktHXQ/eeHjt9T9BhOLEa1y3l5WSIIYLFJs6JGoaRvOQ58IX89VCSlQY+vMoi/x5IDK+DFd5Ki3OQKJa3uRapN6KdVEp79AtVRH9JT4vVTqS1X9lZKoGwpDTVin9Y9CsQ8uPwQaPyAD9SLSSfCxa4+eyIxA3fZeKzxmxaWXrhMw0DdS8oyKSOCRkJYKYr1jgJ4vVyo8Czv0s4nM/Dlky5fN5FGTZUEIiNeJEC4j0NbYPXPlywiUhAwEJTglIh6yuYzIZKvb29eoQkfsRuR8eP0uvM7PeyOsjUciTsSjQHjXChTNsn9ku8+v2U/TjMubTbdtQEJpjl8eSrqYBy+a5L5cV5kdJxPwsiYQfJqslD5OMR2E+nONYW8tmjq/W4rvyYQvumuLk1KzGxPI2MxCR2QsIjyNyHZA29NnRGsGYRZN1N+NEYdwnClvmjNOEYZ8waoWgvY6GbpVPfBmfeF6d0BGyCYhvsMMelY5u5CFRTOIAEWp08krd0aawSaF1hisaW9zOwAXUwAXGpLVYbABAkp854UI8mryM9KCuU8InMg7d5HjWo7Htba6J+o58RArdDqPjQzMOkqvt2dCOaeCm5AMARgDCwUMkV5gTZDaS6KifajUo7ZN0XkpAnBSTW9acoGphUHyTc/WPkqjdNJCMasvkATtjOsLEDDCl40sHmtaRSiilPh9VAjKJhMiBgJCEMSGS0j6cxtTQOJDmzNzP6f2cKC1xBo0WMqOPzIyTqCa5O3AOOw01Hce04wFnLTasHRu1GBpwgDIYe2y6IstYYCCIHA6m2YgQFUmivr0LbHLumqPREeOICNq8ewpGsu5D/4n8TvYnBm44MWAR5QcJO+l0Mdp9TwsZH6WPLi7MXNMgZjBH/R+GpoH6E9G2hBskCiE7EqwflQENKOiAoTRyYWYPorM7tA3Zlep8YbrvGFMks8XDqLTYormcIOUEiIWEpq5D+kynjPGIFM2IkJjTnBjqnNpmRmxz+3Qw6J+MZEDwkBFks4jRFZLynQ1wicb5tNmgE7I/OQgru7lllMF0IOYJetun90Niz0LDz4ad/ehiMtaWnzT8SSlNmSEpoxSFhqJwwIEpoS8k9IWEjmBAB6HcFhs114Mh9a0o0wzP6G2f3o8ptbFFDsdBYEvVUHYC2ntseo9JL9GgFzqvhD+EoZS3Wd8io9QlpEneN8kJyYaWXov6Fg3tKR1HasjNKLVZL50+Uf6YDtqMYTDdU8LyqUEfaPQg6k4J8XR4nWgSrT+edyq9GR1WRmZhSnsmZqLrzOzLaq/EKFd7O6Cz3z1oGtKH/L7tUEnJuLqHQ9rlQAIj02vYIhG1SehoEjrmmFBDwKn96pd3UkZAlZ1IBxEOczcgghx0Et7dMgKfH3flmyXAJ20iSv5gCsxYmsvu1lC/UsoKSmHWP62FwqjsQLN8Yh7aEZgnO700KAO9H1gEA2X4SsKbPh7q/4+Y44GNMI/65NmjvCYZEZ1aKkLGLlONJZaB3NZ8nVJcQkf3Qx/0HN3r/iBBEY1i8hHNMX2WaUAd0DDDl5jyZbRXQEMrn/bXypKhn0pVQsjQs0ujNxLiGXtCH+zw+jsUyTwymA1N8cD1HixLvpkrE13Q8KOffcObweo1MB2GfBrC5HSwISWEeFaD5DaxZlqzAq1w/Q260Pu9+9BrZXQsSERBaSZOI4z8j2FOn6741EUwxUd65kmepGtD20dk1CQYJLGgTyIvU5RFFxJirboqpoH++8QstCZH/9Yj9WwjsJQEQxm1jKZkigaHhkYa2XQynRAzlZIZST1jrQcUkQEQOaCuIomVSajMSCXagI7Q0EHyVAQgp9TFhrreABi5H3iMNK9mRJRaF71ymNnuR9lnuAa7hx1zEsIc+hjJi/nUaSXerPGvSOjtG8IItb5pS5NkNEfmU/eU+K3G2aaiH9CR0EETJ8mnykKDcpNLovaBLqrUiFPmJH1PRie0W0CUkaSjSN4xMSqR9qynCfbMEEO4RqwKcXRaO0sLGjWZGZmrjCiEDlVpMoVURnYzTUgyFBmC0mOJz/umA8kexpTkD1IrStKhOSWd1M7S4RmVI2yi65FvhM609UljkqwhZpsm7jQXEsOQdGRSaHqLmdTtQIWMoJPVg+y20ORe3tNK45pBksRktGluYmB4DF873qeEmalhJo1Iuk57Go27Qe1NSEZmJHsQrLcaoCOE3p52HotuSRdJNggzBkEF2et8JGA+jYTMTBK2m8XLJ3aO5LpJSj01HCCRBHEoiAEgWkdXCCNk1KqS8gvf6AzJ6/umxJfk6YnkUSeOClvePzfYQO0M3pTMPRvGWdQPYDSNd5ze842JMoYuNipLdMWMjZYSGHtBNxENFt2KpLuSlIPGNtItkEEpxdQoxGCD5kigaKW8qWQmJdZUVfK+wcAaDRN91CANc0CDjkkF+CBZxroq6DDPz1VBs3EVdBifL4Pu65tVCcRx8XJTtlzei3pyXfO9qL+eKl+9OnTFq7dNlel1tdmIeiGaWlYx+a1U267uCtLoqICUTXN3AemqFuKzqtxTw7YWkzJP/heGXhg3/yVemHnR1FZMqisQJQfUPPx/Hen/yTrSf075qBYna71mX6lw25SF96/QLIvVqhnz4+xO7PdrKRr3fCPeLWf5kgVsulj6KWOpH6Ux9/kq5f58HqXJcsl4uOJN21tey3/3Sm2fHHB3WyEF+r8OxeIPr6zMm4jtq2xtpXpTSvpQ7URJ3z47rmKXJso0arb31ZuCqgJe8u1VzWc3lZT0suOAelACfxCHvbQu3q9SyMtm2r621Qs3fDt72vAtHUNbZvc4WRX1bj+RP/IkCYJEEv5haKRWfL0T3k7q0+w9r++F17zL+Op70ShV28F7+Ycc2JzvpNWoa16Us+tKap0cx+ieNHG7wtRotSb5qOHHhWhK+U3D1ss4g4dAATDfkSbjnt4W6/WwiXYZzmK1ngzIrFFDO7PO4iFQEFnoFPrQHH6HOAEyFZnHwEr+rXrHdTdsqf3Qs5Ctj4pJBwAX2OBc0jFqaJeOs3gIFEQWKrM+JLR9wcl5POv8j2YBYSw45YiwhVbq7XjSQ5aeQHWQLt7sdbF7OCtQXYqlf+quWP8hV9Cm/WvBG7fvtfQBR4bZJu06mjtq+aaWXtFaruODxjra6zv+9VHsjjv+z0N5vxbYIEbd2jkENOsSqpBcIXjMimfXsrPNECiILFT3fUj5++gbY++o3VjLdODVC8gbsdlh2jJSlpvqUO7lxVAAAVJHbexIoCZHVk12QiK8jKxMd2tc+ONYx254DdiJyCosNhug8yoQRW3iBes8HlFuNUtjHkVYJ11+z1hCGYlsIZsyQnfZlFHDsbYFIB4D8ZgNz2JTgDZgb4il862mzmFTkPVWp9NPLX72uYMsVmjTRqfeIou1b7UZY0YhogDMSwxaqBi3UDFooWIrk52QLhuz0bmP38pirwr/m5D9pvommtcFgrZU/w3fr5uTZw6lV/1Zymi+rXPf1tWm0q8YNKfxHNOnRKfiS/WOwWE3+yQvYfs1kuKxaekqJZ7rVumkNERSm31GuN1li+GRjpo6LHVyjpl2Gz2Cd/nCQMMQxAuseHarDDTriq0gO3m2GQIFkYWuFT60WPS7+Rh7Qb8csvLWKNlth0dWxxWzALGm3TK6HCCHrR3k8meWY0gGmox05mo07Kk/3WRkKqARJScWtcuGZOO1s0dgVpITK8YYEBOdxCa0GrM9u4SX7SrUrDntwSLwcpPY1wJrpOu28KAz7OTESMltLfX+J0SU3iBFiBqvGskFHbV7itiSCxLkXvFGHTmTHqOW9jUOaNbVB0FWE8ELrHh2qw406wptoVXnbDMECiILXXl969LriDzQwA5oh+aofGuSyr3GjWyaXZp9PPh3rH1gkqF7VQvo6JkLyHglclCiX5jqY8Lfal4Wh83fRBpov8bi/vlQLmt+tLSMA5wN36qfrk6erSUbvWhP33pxt1dbvPpsLX0i1926SWm0sVIzHL3fLAfbLmD97qJ7CdMvej13/Ul/ljOR2pyJ9/wPYevQEale3OFI3VwdAonVFNb07oVTpG1qs0cuKsE8XWqzmc7JBeLErojqmUKkC68QH+oEPzN88KOmTs8KJMvt3GTEYr3kpfwfti3izMVSwHflQpS740fHq1BsG7Mr/Qw0jEC80Io3Vp3QhufY0EPwAhCPgXgMwUOgILJQj8y3umQO3wdNn4DZGMiXsibT3b4PuNPYFZY+3/eBNz4Aq28PbU+4MGNn6sTGx8UL2ilvqthIN0A7INd8sx3bUOpevT7Uu+PE399FucseU4pf83pztOqcS0w6lhrQ27EzzkIGmkrKrLNvtf6WBT77WX5PBvo92SlVQRJSmc0hcnUE7DJloCuUWe2T1e5kqCeUWW2oY5KBhEZ3bszzMiz6iIKzFli1GzVzEJM/d0M2s3Xi9CYBqlMb4AmLimAmF2DGIGZsw3R5VaOGY/mOQLwQxAtteC6vCmgYgHgMxGMIHgIFkYX6er7V2XN4VYiXZk3EObwqdNPsfEzWFVkM1/Pnabhvrblw7vmObbnLvwI3UR1eF7xTME6Ugd3Ycw0u2xaA/gi6dmL7U9lP2p9CLA9oQXOrkwWHud3bdqeZOZL4fDwF+kWBZzp2+RnX/t+T4ruqL8vv5bgCOCcDfP45UocnzfITKfeL+4R2zHKrIzk2EznqRXanvjw705U7vUsqyjft+aXHHadkNbhaHzZFedignYLJte7QovOmpH+l9GzT7mVMXEgQ1NwK6nT9EcjMCunaN0BR00tQ+1emEQmze8kITf2RDVC+BUKMUMTIimjxu0IUMUQRAxQxQBEZisggRAgMIw114n2rF+9wl9EcL2BA0G1137qvbneXE5par6sSk1qsPM9eR+1yjDFnO4Gd7eRfcbbtG2CoF6UP+DztzNmTPZjrbU+r/UwHBXPE7V7vz6IDMqKuRhf2ZIsooIxsf/Zmr0a/P8i+/mEedPfKNO5Dd4erHs2tbcvBko/sjmO12aB/DwduhHpTvLwgiuhOt0Wk2+GbdKfl/iQJRXeLumOFnx+L66OozyoEOfKg2SyxkKEK/dTpCZ+rd0SR2PnVeGpbaE6O+GzZtnVJaZ49UftyTl7BGko711wGJR0NBeGinTvdEeyXCTI1e3Liu4/BWWi17fc/510EfSr72dx9f+L7pTX65tTj8xGYPurU2nCwIhQ79VXf9pMv1qVhuDbwtTj/DmB3jA6QnrIPyB6wQ4gZipihiOmIDZZ3m+w+GISfoBQnKGKMIsZWRIuLH6GIEYoYooghihigiAGK6FA3R6wHnGIBgGGkwVGobw9DHdEeuvcERI/2QiJHtDdq96vYiXpcwQSFj9Yyb3eEB6UB9QFcP6surPt6CfL4ibwRFnPaSxftK+U4D6m/rtGPXDJ8/bzQEHm/yFrpYF8NsFCz+5Yt4q1Br43aYy0LIgTmCtogJ9d6NIuNCd0Jkj/Bj7ce+OHyaruTYf+uANt6LgKa5eiOwP5JdMDBjf0N7UvnHawbNmepA4GwTYgvCWLsb4DYgxZrIeRJYLA1sxYDnEQGWzNr3vQycQO3Y/svPgCz5o4TIPegOzX0vFOvDxuFu0cwGYw5tWM6TDmEmaOQOYqYoYgZipiiiCmKmKCIiRXRIkMxihijiBGKGKGIIYoYoogOxXGEG+hhWpiIQ4gQGEYaHAj5p/IOo3AD3sJDAhi0xs63Ftm5Ag70HYxRu37ZGy7px4fHjuMRJMRBX421n1th2RhwZciSo7jnutrvR7tslo7Pvdt0PuaIT+/sOWuD4XcS9FcMLw1lcjSUybFQxrHV4FoCEWU95e2PF2okloFCLQZWytvw4Uim+wId0tFzXHnr0WhuSn5GdT+znhVpyRvbz2K6JHKwHgfi6gncfX7uiIETwbqPUWIChFTi9p8fPZ3StscsYFlw//1QzNUHqyf6D+biqEh9KLPn/Qzq8NinZrNIHTktNhw+4YmhS7j5gC4YjUBGDs4Lm29Mnhc4/TFJOMBCMAMYk8GYDMacwphTFDNHIXMUMUMRMxQxRRFTFDFBERMUMUYRYxQxQhEjFBFWHVhzYMXB9QYWcQgRAsNIg0M/H4v9zOfuwAALPN4YC9ns5Zn2l9KR17Z863tWlpBt9Lr9nYxWzhfR+ta37S349nOSXOV7SMPu8/Hnyrwvqd0DE7bdp9ARV/qSN2uxXSn7uwFQzRr+BsLJAqbx8ocdT9Zta4DxFXbyZhfYgP4MdkLo2PLY8GB3BwKzDsOBeP4M6v47dRggEkV1H6bqNa75WsxxBODoAAme7AdNOQCRKCi0KypYC8zQoziZ/X1Gh2ShsRBa9c2sdQBORDQOsib7nKjo9gy6wJlvm2PjxwIaR+mMCxPyKuD8uPkC3XnJa5xH6DDqEMYMYcwAxgxgTAZjMhhzCmNOUcwchcxRxAxFzFDEFEVMUcQERUxQxBhFjFFEWHlg3YFVB9YcWHFwvYFFHEKEwDDS4JDQRzMp8L6gj24MwqWSPrqGwK/u+fZ39+wna0ChHHgER2Jd5B3b2Ujo1n1L1HzNpFpjdd36U6fnu7CfOGMPndTnH1XdtXzeUkMAvnBsoSG3+4of+a44dnFPvA+M1Qs5Cr9P7cD9rS8juHmqXz+xM9X2ZkJ4fqinysfGTgPy0S34+z32XSqH/4cFlWCANzapNjAwOEe/2sMu+GwPQ7/bw+wH1LtBoam2nwjsBkXiSftJe25MLP+icbHGDP08BIsuiCHR87gZWvrNrJUYzhgGWF6YNfPoRAQWNga/Dc8cq7QLE9rhcrzI4cI88zk7dw9IxgbeW2DwdkX3NW5kz7jx2aGPckQwZgRjhjBmCGMGMGYAYzIYk8GYUxhzimLmKGSOImYoYoYipihiiiImKGKCIsLqA2sPrDyw7sCqA2sOrDi43sAiDiFCYBhpcCzuoykseKPWR3dq8WwkmuGEX2D07WupI+KFFnL0RB30ZEzfejSm/RwiKIZuD1g3K/3HYn32oQz0yXzr8ar2052gwxStR3e5QlHoQ47WwwJcEV902iNyxX/0sVvB6zXwFjX87UV7BaErHoT3A1AfDvuOOPi9Rcy6ItNl/QyY22UEEaHY0v69FgciNMP2U9AdiFCQHh9LMyqW1tOOnD2gMwVFl/YXdh2+PRRadp+puizKYdaCEadsIYGmNS/qREQCTfuy41YAJNCEDwxgjjMIXJiQUYJfNGJwIRyDa+sYvMfD+m2jr/rwGDm+4Mf/AlN5AAX/vAAA
</Details>
