### ISSUE TITLE
Battle outcome unrealistic in some cases

### ISSUE THREAD

**Issue by aori6425** [yairm210/Unciv#1850]
First of all, I've played for a while now (few weeks) and I love it, it's a great game! I hope you'll keep working on it :)

I was wondering, if there is a way to fix the way how the outcome of battles is calculated? Often far advanced units sustain significant damage against obviously old units. For instance, today just happened my destroyer lost 21 points against a crossbowman. The other day my musketman lost 10 points against an archer. This seems very unrealistic to me and i remember quite a few civ games having the same problem.

**Comment by yairm210** [comment]
Not a bug!
That's the way the game rules work, we're not aiming for realism, we're aiming for playability =)

**Comment by aori6425** [comment]
Then what's the point of technological advancement? Interesting that you're saying it's for playability because for me, this really impacts playability just like it did with other civ games. I must be the minority i guess...

**Comment by yairm210** [comment]
You get much stronger units. Maybe the musketman lost 10 points to the archer, but if you attacked with the musketman the archer would probably be immediately defeated, no? Or at least lost a *lot* more health

**Comment by aori6425** [comment]
True. I guess it's like you said it just depends on what you're aiming for. For me, I tend to get annoyed with things like this because it makes the game "less accurate or real" and therefore not a good simulation. But i could also see people get frustrated the other way because it's too easy/hard i guess.
