### ISSUE TITLE
Game waits for defeated player in multiplayer game

### ISSUE THREAD

**Issue by YonniF** [yairm210/Unciv#1859]
Hi,

When a player is defeated in a multiplayer game (in this case a 3-player game), we still need to wait for them to hit next turn every time.

Keep up the good work,
Yonni

**Comment by yairm210** [comment]
Ouch, good point!
It's quite telling that we haven't encountered this yet, almost all multiplayer games are 2-human-player games
Thanks! :)

**Comment by YonniF** [comment]
No problem. I've been playing a bunch of 3p with my brother and sister that
are scattered across the globe. Thanks for the making the game.

The other multiplayer thing that we cant quite figure out is research
agreements. I can't find a way to declare friendship between human players
so we can't make research agreements.

-Yonni
