### ISSUE TITLE
Diplomacy - Relationship points overflow

### ISSUE THREAD

**Issue by DNSHmiu** [yairm210/Unciv#1868]
Win10
Latest 3.5.9-patch1-win64 Version.

![bug](https://user-images.githubusercontent.com/53578426/73997493-9e20e000-4999-11ea-8b5b-98459b54b73e.jpg)

Happens to all civilizations.

SaveFiles: Overflow starts from the third.
[SaveFiles.zip](https://github.com/yairm210/Unciv/files/4168796/SaveFiles.zip)

**Comment by cplir-c** [comment]
Confirmed on Linux x64
I have my save if you'd like it

**Comment by r3versi** [comment]
Fixed in 3.5.11

**Comment by yairm210** [comment]
Already fixed =)
