### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by Damjan94** [yairm210/UnCiv#188]
there is a division by zero in the file [CityConstructions.kt](https://github.com/yairm210/UnCiv/blob/45db23bd95f4945e235e2c2af7c2b24856cf35aa/core/src/com/unciv/logic/city/CityConstructions.kt#L138) in the function turnsToConstruction, when the city production is 0.
my problem is that it looks ugly in city view
![unciv_largeproduciontime_20180701_135950](https://user-images.githubusercontent.com/20781278/42135207-f360c9ce-7d47-11e8-8248-01725765e514.png)
![unciv_largeproduction_time2_20180701_140110](https://user-images.githubusercontent.com/20781278/42135210-f5666eea-7d47-11e8-91dc-ff3df44bfec9.png)

maybe write something like "infinite" or something that isn't a number? but that would than require translation?

**Comment by yairm210** [comment]
How is it possible to have 0 production?
The center tile of a city should always be worked and should always provide at least 1 production

**Comment by Am-per-Sand** [comment]
When Happiness is -19.

**Comment by Damjan94** [comment]
I did cheat in a ton of gold, and made a ton of settlers, so it is likely a situation that a normal player will never encounter, but I thought it would be best to bring this to your attention.

**Comment by yairm210** [comment]
Goods points, all
Production in a city can now not go lower than 1 (Civ III "cities in revolt" flashbacks intensify)
