### ISSUE TITLE
Diplomacy - luxury goods deals

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#1885]
I found 1 bug and have a feature request attached to it:
-if you do a trade deal with the AI, after 30 turns you get the message "deal ended". However, if you than go to the diplomacy screen, the luxury that "had ended" hasn't returned to your stack. Say I have 2 fur and had a trade deal for 1, I'd expect a 2 again after that "deal ended" message. However, that takes 1 turn extra.
-If I have 2 fur and send a proposal to an AI, that wouldn't show till the deal gets accepted the next turn. It would be practical if your "deals sent out but not reacted to yet" are also shown somehow, as I tend to renegociate all my deals in the same turn and it's rather confusing to see what deals I've already proposed and what goods I can still safely sell.

**Comment by aboehler** [comment]
I noticed this as well. It also happens with an "Open border" agreement. One side gets terminated first, then the next turn the other party gets terminated. What is also annoying is that the open border cannot be easily renewed, I have to wait until the deal ceased, resulting in all units being removed from each others territories, and then I have to reopen the deal.

**Comment by krijnsent** [comment]
One addition/feature: could you please order the Luxuries in some logical way (alphabetical?)? It's really hard to check which luxuries the AI doesn't have.

**Comment by rh-github-2015** [comment]
Reminds me of freshly mined resources not appearing in the totals. That one is worked around by saving/reloading - would your issue react similarly?

Sorting of stuff in trade screen: I just coded that yesterday and it's a huge relief for the cheap price. I just haven't figured out git yet to submit the diff.

the sortBy{} / sortWith{} down here - some of them may be redundant as the base collection perhaps already have a logical intrinsic ordering, but many are hashSet based thus ordering appears random to humans:
`    fun getAvailableOffers(civInfo: CivilizationInfo, otherCivilization: CivilizationInfo): TradeOffersList {
        val offers = TradeOffersList()
        if (civInfo.isCityState() && otherCivilization.isCityState()) return offers
        if(civInfo.isAtWarWith(otherCivilization))
            offers.add(TradeOffer(Constants.peaceTreaty, TradeType.Treaty, 30))

        if(!otherCivilization.getDiplomacyManager(civInfo).hasOpenBorders
                && !otherCivilization.isCityState()
                && civInfo.tech.getTechUniques().contains("Enables Open Borders agreements")
                && otherCivilization.tech.getTechUniques().contains("Enables Open Borders agreements")) {
            val relationshipLevel = otherCivilization.getDiplomacyManager(civInfo).relationshipLevel()

            offers.add(TradeOffer(Constants.openBorders, TradeType.Agreement, 30))
        }

        for(entry in civInfo.getCivResources()
                .filterNot { it.resource.resourceType == ResourceType.Bonus }
                .sortedWith(compareBy({it.resource.resourceType},{it.resource.name}))) {
            val resourceTradeType = if(entry.resource.resourceType== ResourceType.Luxury) TradeType.Luxury_Resource
            else TradeType.Strategic_Resource
            offers.add(TradeOffer(entry.resource.name, resourceTradeType, 30, entry.amount))
        }
        if (!civInfo.isCityState() && !otherCivilization.isCityState()) {
            for (entry in civInfo.tech.techsResearched
                    .filterNot { otherCivilization.tech.isResearched(it) }
                    .filter { otherCivilization.tech.canBeResearched(it) }.sortedBy { it }) {
                offers.add(TradeOffer(entry, TradeType.Technology, 0))
            }
        }

        offers.add(TradeOffer("Gold".tr(), TradeType.Gold, 0, civInfo.gold))
        offers.add(TradeOffer("Gold per turn".tr(), TradeType.Gold_Per_Turn, 30, civInfo.statsForNextTurn.gold.toInt()))

        if (!civInfo.isOneCityChallenger() && !otherCivilization.isOneCityChallenger()
                && !civInfo.isCityState() && !otherCivilization.isCityState()) {
            for (city in civInfo.cities.filterNot { it.isCapital() }.sortedBy { it.name })
                offers.add(TradeOffer(city.id, TradeType.City, 0))
        }

        val otherCivsWeKnow = civInfo.getKnownCivs()
                .filter { it.civName != otherCivilization.civName && it.isMajorCiv() && !it.isDefeated() }
        val civsWeKnowAndTheyDont = otherCivsWeKnow
                .filter { !otherCivilization.diplomacy.containsKey(it.civName) && !it.isDefeated() }

        for (thirdCiv in civsWeKnowAndTheyDont.sortedBy { it.civName }) {
            offers.add(TradeOffer(thirdCiv.civName, TradeType.Introduction, 0))
        }

        if (!civInfo.isCityState() && !otherCivilization.isCityState()) {
            val civsWeBothKnow = otherCivsWeKnow
                    .filter { otherCivilization.diplomacy.containsKey(it.civName) }
            val civsWeArentAtWarWith = civsWeBothKnow
                    .filter { civInfo.getDiplomacyManager(it).diplomaticStatus == DiplomaticStatus.Peace }
            for (thirdCiv in civsWeArentAtWarWith.sortedBy { it.civName }) {
                offers.add(TradeOffer(thirdCiv.civName, TradeType.WarDeclaration, 0))
            }
        }

        return offers
    }
`

**Comment by rh-github-2015** [comment]
So, my sorting change can be seen [here](https://github.com/rh-github-2015/Unciv/commit/c0e6653f1100d36dc0254267c8ddc75afb06153e) - but I hesitate to do a pull request because it isn't yet perfect. English works fine, but choosing a different language sorts by the english name (the "key") and simply appending .tr() somehow does nothing.

And the bug you mentioned - I suspect the transient detailedCivResources on CivilizationInfo didn't get updated properly. I looked for that when I did "[Fix resources not updating properly when tile improvements change](https://github.com/rh-github-2015/Unciv/commit/be89ab9292ca1f6cc1132f3a0f3020bed9af954f)" on my fork... Yup, I can see the call to updateDetailedCivResources() in acceptTrade (TradeLogic line 121) and the counterpart in DiplomacyManager, fun nextTurnTrades, line 334 - looks OK to me...

I'll probably try to debug this later. Debugging kotlin is fun.

**Comment by rh-github-2015** [comment]
Sorry, my take on offer sorting was misled as OfferListScroll.kt re-sorts. How it sorts: By amount descending, then by the _english_ name of the offer, or in the case of cities, by their internal guid - random to the user. My code probably worked pre- #2152. I have an [improved version here in my fork](https://github.com/rh-github-2015/Unciv/commit/0b00bcabd4cccf9143dae30eb294407c5c2674a1), but I still haven't learned the pull request procedure...
