### ISSUE TITLE
Continents maps don't really have continents (commit ddf86ecf2f)

### ISSUE THREAD

**Issue by ninjatao** [yairm210/Unciv#1886]
Hex continents now have very few land tiles, and each continent is likely to be broken.

![Screenshot_20200209_195126_com unciv app](https://user-images.githubusercontent.com/6846049/74101571-35db2580-4b76-11ea-91b4-fff2d8123f23.jpg)

![Screenshot_20200209_195407_com unciv app](https://user-images.githubusercontent.com/6846049/74101580-468b9b80-4b76-11ea-88f4-eb5242c23b4b.jpg)

**Comment by CaptainKlutz** [comment]
Looks like the middle ocean line and land gradient need to be scaled to the map size in the new continents generator @r3versi

**Comment by ninjatao** [comment]
Medium maps share the same problem.
![Screenshot_20200209_200313_com unciv app](https://user-images.githubusercontent.com/6846049/74101675-5e175400-4b77-11ea-9e8a-facb6709f4c6.jpg)

**Comment by r3versi** [comment]
What do you expect from a continents type map? I assumed the main requirement was to have a big ocean in the middle. Do you expect more land? Smaller ocean? Bigger continents?

**Comment by ninjatao** [comment]
I kind of expect two (or more) large continents separated by some ocean. As in original civ games, each continent should have enough lands for several civs to battle with land units. Now it's more like Archipelago?

**Comment by r3versi** [comment]
How _wide_ should the ocean be? Currently it is between 1/3 and 1/4 of the map width. I find it to be nice, let me know if you think it should be wider or smaller (btw, it scales with map size properly).

A small update, the "two continents" was only providing a central ocean, not forcing anything on the borders. I added a small positive value to force some land on the sides and I think this improved the generation. I could post some screenshot, but I don't think a few maps would be enough to prove the point, so I'll let you test by yourself on a future version (or applying the small change by yourself).

If you want to test it, switch `min(0.0, ...` to `min(0.1, ...` (or higher) in `MapGenerator.getTwoContinentsTransform`:
https://github.com/yairm210/Unciv/blob/d43afe38e6494e3e63ac26e088d40a9a5a248ccf/core/src/com/unciv/logic/map/MapGenerator.kt#L634

**Comment by ninjatao** [comment]
The width of ocean really depends on map size. Sometime ago some users suggest that continent-type maps should have more land tiles so in previous generator it's just several-tiles wide.
Another suggestion is maybe you could generate two continents separately instead of one continent sliced by ocean. That looks for natural.

**Comment by ninjatao** [comment]
If none of that applies, could you please leave old generator as an option. Thanks!

**Comment by r3versi** [comment]
The old generator doesn't work properly with rectangular maps or hex maps with bigger radii, that's why I started reworking it. I think I reached a good point for the two continents map type adjusting some parameters to have more land a slightly smaller oceans. Waiting for your feedback on next update
