### ISSUE TITLE
Upgrading a Great War Bomber in an Ocean tile crashes the app

### ISSUE THREAD

**Issue by savingprivatebryan** [yairm210/Unciv#1889]
**Describe the bug**
Upgrading a Great War Bomber in an Ocean tile crashes the app.

**To Reproduce**
1. Have a Carrier in an Ocean tile in friendly territory.
2. Move a Great War Bomber onto the Carrier.
3. Select the Great War Bomber and select 'Upgrade to Bomber' (Must have discovered Radar)

**Expected behavior**
The bomber should be upgraded, and the app does not crash

**Additional context**
Android V3.5.7

**Comment by yairm210** [comment]
This was actually just fixed in 3.5.12! Thanks for reporting! =D
