### ISSUE TITLE
Bug: advanced promotions

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#190]
March and Charge promotions require one OR the other earlier promotions listed in the promotion description. Now any of them is not available despite meeting one of the required in arrays placed in https://github.com/yairm210/UnCiv/blob/master/android/assets/jsons/UnitPromotions.json
I don't know java but it is probably coded in line 24 of https://github.com/yairm210/UnCiv/blob/master/core/src/com/unciv/logic/map/UnitPromotions.kt so that all items of array listing prerequisites are required.

**Comment by yairm210** [comment]
💯
This is a very easy fix and will enter the next version :)
