### ISSUE TITLE
Production bonus of railroad is not applied to cities connected via harbor

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#1900]
**Describe the bug**
Railroad's 25% production bonus is not applied to cities connected to the capital through a harbor

**To Reproduce**
1. Found 2  coastal cities.
2. Construct harbor for both.
3. Research railroad.
4. Notice the non-capital city of the two cities constructed has no railroad bonus.

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
Once railroad is researched, cities connected via harbor will get the production bonus

**Screenshots**
![Screenshot_20200210-235021](https://user-images.githubusercontent.com/60229808/74166121-06edae00-4c61-11ea-8355-6280172f95fb.png)

**Additional context**
That is all

**Comment by Kentalot** [comment]
Do you have a saved game handy?

**Comment by Alkeif** [comment]
H4sIAAAAAAAAAOydW5fbNpbvv4rOPJNZAkiJYr057jju6Tj2cbkna04vP7AkVhU7KrFaF3cqXvXdD3gB8ftTKqeSVma655ysLBdEABvAxr4B2Nj4vKw+Vevq52Jf1ZvdxV8+u9/fF3flxdfF9qrYVsVmF5U/3a/rbbn6UK3LpshPF/E8eriI08fIpRcuOW9TzcfuW5y4pG2TaVMy6b426T7Z/zEtIGP7X21hM+1/2ebXovvRtBLP+4xp8yNrf2QuOes+N8l4JnAT5IQ+zoZ+Z9KulbopGg5t9V2Yh7ZmARXxLGCgh6nj7GrYBqbtIbU/4v5Xl5NJTjb0Nh1GkKBvKZEyI+rm7EmGjidhZmyYmT7ZVDX916FBP19ovBtS3v5IpqFSm44Negg8JQFPyTCu2YDdFPMl45pzXDJrC0HwlFm5ZJlhMBaosEMviFNPpMOoUDYOIDwxdHOXByBtuoeShc8ZYHfjSjku4MkGPIUe9h/JEZi+rqN9pm2bst2v9ofVnBw5fTr3fQ/DsRyOJYBkGgD06W54XanAML5aNoALqX4m54F45oF2kIxDiRm+zsKoA4RFKIBkHEq0gzEcGL7HzDBhECYMInzFR1/AJO0PT5QGXB/nFAg5ZUxfbi6/OtwYyIDYQDoYTLDB/OZssge1AKgFQC0IKg+gcpTPUT5nE3NU7inAgBg6MdD/an/4HDOTLiZASwM5l++p1PEyc07qnnMoM+DOl8tRLmfO0KNEpHMQxQPNg/36JhbI6Yu1QD1MgrHSzFx++elciLqYQWT1JfMBQxmmIZMKVoB1uLPQL61w97qGlGVBWVboZCb9WgyIGnBuPfoxJYRgw/S0ZOC70hEIOzbMlJ8o/2mYtw5AJgAyQacdsKQDSGUAbNRLMj93/tMwlV2jC2mU48klB7wD9iKnBW7k1zC9syGf/CYcLSQkJNB3jKhNAtITYiwJuLQUlRbStAOaC/JMqMIavnoCNCQBP80g5hiPCDuZQ524qbRt0YafHoqWANkM7QnGQi+6lju6SImvNOBLOhc4D5/DV0vtboPWb0abYuAi80UIon0/uJQSJR/xSMd0PcvlKrjTjpLBgyTHlBA9A+RsK0y77Qmx/+Cp0gilDgMZvloqfxt0PqwkGEmm/xqwAFJIBlahWWsxlUNtMnYQc75YRlkGoZpA7WQUFzA3aXnaftL9vyiSCZgZ5sZ3LQeteQYfMGOBGYvKmVTWRmB+DjI3pwQGcSUBG7Ce0yCLZPjCgVypWRCyHeiJRJzo7NgWT0EhpehDPvQhZ7NiESZB3voVptjPGXqaBJYcqDGGpIStHfsSQzlZgapSzSj9aPRZGIMpC82JJqyOe1B26G5ADFbKHpWz0PVZoLB5mL75MH3pgPUETYcWYt9EWMVZ0FC/KJGlr4H9PlqaG3YlH7qSs4JY5bL0MbJWNdConkGnEKhQbjHWs8kww+mAmlmgZlkUEukxLSTfIWAOVDOTMqEJEmtgYAMGFgqWxQLXml5IcJltwzq7MyC78WTDGOf9RAfbMrRNmzXYcXOZ5xTDXwR82UEEJehNMnQmBVWloOc5yaFvOEf3dSW+kE6E3RhfyhJHHTSvo9qFujfLPJkEyvHmwTTIz26CwuZPNgwk0E0M5udm0kI6pBs782FGSGuBPBTTGaDmQ00d8ExqYHEzzGi38/AxuqnXq6bI3CG0SZebFzfl7uLz5nB3VW7fXn8bvs2j3b7Zu3td3N9Xm3K3uzBZ5jB2sy2L/buyvl+XF5/bH9+Wm3JbrN/V1Wa/c+hM577Qdldv+s+fHx+j+3pdLaumvSZ9f7h/sS63+2ZjcP9wX14MjUefivWhvPi3f3O9/+/O+RjtXJc3y/I/qqXDx0PT9325vL343Py7e1/uymK7vC1XF395e7+vlrvoTbG/Le+KNv3toVqv3KdqU21uom82Nw6T5bZJXxbVuvn7oqm8fYheHrZb18xD9K7e75sPL2621fKw3h+2ZfTHbb2Z/FBvf2xqfLgt63V98xC9KffFevKy2O2bzy/rzW6/PSyb7djoZbEuN6ti6zrjpqABX9/dF7td9Lre7sqrYvnj5H21aqFt2/m9ib52bfxcspXJD7dluY5ebKo7187rw+6q2KwcrB+2VddiswE8uSy3n6plGb27rdb1rr6/ffj4GH3qkPWm2BQ35bad/M9LV6vsNor3D+yto4crh6f91w2yHGBX5k3tKLLc7KPLqhldOXl5W9y7vnxXFg0mJx/qv5fbSX09eVftihY9f3f93kUvHImt68m7bX2zLe6i76qb2/1tfdiV0Ydyuy2WDrfF5MX27qEd31v3ZV22yW8bgp2g/OW+3nTY2DnkuZHtysNddPmw2pQPk7f3juAnr9uCL/52KFduIK5GsT+UTae+qxwz7d0EFZvbwrW4aTr019KV+aHarO6q9drN8nZZrotq0w3FzcvuvnLTGX27dThrpn9z82O9nfxQ7COHDDfHDU24OSpWS/ejr/WuWBcO9a/q7VW1cpQ76T84etu76dkuD7vJm+Kn6u7gBnFbOUrbTP64/7mIvqmur8t1D+WNo8S9a3PyYlmsSoeb19Vd+deqpSyHnjfF9sdy3yHEAXDM8bq4qYrJpZvrqoiIi6+LBskOY9+Xh93y9u+Fm+Sy2kR/3lSfnDBw8x693LoZrSfvS9ddRyIN8ou9I3HPSJPviqvozaHDdlnc19u9m8arbYOTH4r1etfgeVW53K+LzY/9IF2PtlcO2Otye+eG4rr4Yn1b3Lla0auipURXomG+m8m3xda1vJNJ76A3X949OLKpHMe+vdo5ui7aqm/KVbV0HND07N3hysmwyeXytq7dLLoxFDeO397+dF1vVxOMs6Wc2/o++lD81c3BrZtah0HHd9/8tLwtGiw6MmyhF8vbg6PjpfvT9uG7+vDJIeTy3s3k7ra6nwxDOFxdrctJmzH5UK7L3bK+dwXrdbGdvFsXbs6/rm4mX5ebBkeuaPR9ezjTCAnHFqVrs6Nkh7CvHZk5PFwdtg1K9mXU4aLBsGOVu/umcu3mZfKH4s5V6yjhT9vyzgmtj9ES3Pu/D6WTlH+57KSky2sF2Z4M3srVUxl/3P3Zofmy3F+4L+Vj1EiGho1aDVH+dO/op6n+uZeDl61Cukhyp+Ku68OmERZOCF04jDgic4S03t86A3sWVa5Qma6Wi6SM09U8j9Myy+J8nl3Fy3xR5lcmnV4tZ9GmOa96U6y21apVSOsWXxefr+t61TdmFjPDPAd9d18uq2Lt6Hg3dM2ZPa1uTaP7bb3qh5143eHMHac1wiFYQt3s7aVgNqXhU7Ce5PjLwMgyyAxWVjDdE5g3wbgMJxS6jv6JR3DsZ6gQh+WGDf0A7BjdC2XDpnswjsMxRTzen+/bDQdjvZUzQxEsU+KwpWAew5JxWOcNjRuMyQzNm1HvsQOKQQOCXxaJKd3+4Bi6FWJfOLQWDyBAA6QHMzQfUmEBzT0GoiBMRCAbri7DllU64DbYsjgR4ulQHAYNXBKDfYl+kME2RtMdZvzGRPcjjIxDJxZC37jGng31Ag1xrRfoucc+dphiv2T/GDUGA0+mA31jnk6iVefZgk/JkqCVY8LTmSXhkaCSET7GHIUDV6BxjMXQOnrHFZruv0ImxGOuiAOzGEosy+k1fno/dkbf8229pxW7V4G/aKBRbw+W2dMKfLDHBnV9bIh1anqkvINNdqynx1Zaa41RS/fa+cju6i2tkxZVr5RhYZy0nLzN9gUD6r9CReep+WUVfb28zmyeruLZ3KzitJiXcbGYLmJ7XeZlWqyui6tFtK6XvVL+yW99Nzsim97TxBnRbiaeVt4LVd7ZGZS3nMYeu5qc3PaiEwr230bbZnrqS2cVOckbe7vokZ/6xegmnSUQ3UtLBGQqIHU3UxxkTh1Ay3kyDzAyoomeDbJlmxOWdFZ3VfQI1kjPuVenB53qVkO3kTk7RE+PoSUjv6y0mwiO1IVnipHkHIicMMpuX6B0tGUJbzT+RFrWw2+6EeTADHfuuSOr7gR6Bs0dXiVH3ZXVHVvZ3FS6lca0ZfF4UERrY+IMo65Zc9Ic93OPN998ZwXNwjrKLeqrITysR8uyo5fL6D0udPKnx8Pn+Y6MidvDubNrnEDbvFj+7VA1AnC2OLJzvkhMJBElJRLMiOTMCXg6W4Ib4eKTO7dfEkYkPCUnnbxny4j8CPqIw2WrX+dcMCBy67SUyI9B6EHCkxJDTx90IIo16+yuj1G32fayWdQ7MrCRd87s9PCqul/Xd8Xy4eJzuw+237tfjW3WZ+yr5Zt6VV1XztS4+PyfzrzYvb1+VzpDp908D6XaPa/dRZsV1fvbcvuyb4hwH6NLZwY0pkh5ziYGoI/R/z6UV+Vy8tIZJ+dsAWCbMRR35+1+cffoDLb7srETN+cEPQB9jF41DriNFXNG8B7mY/TNzcP9/pygW4CP0R8aK/2sKOkgPjZ78M4GX521zx3Ix2a/t1oX5wTdQXyM/nQo1sXku8Pd/WF7TviE61oprg7rs4JvADacs6rPOpktwMfo/WG3q86K7w7iY7MbWp6XZzqIrs/13VnhNvAe3SK1uDovJjqIj9G7ev2wKc+M5gHoY3MssTkr7BZgQ8v7W6d7Vofz0nMP1GF8s3dr+/uzorwD6WDfldtqed7p7EA6+edW5M2u/+1ZJaAH6jin3NRn7XkL0OmxbXFuLdZCfIxel+tdtfmxOidsD/Mx+j/F5ufqqjir1PYwHZU7RXxWbLcAH6Ovt04QujGcE7SH6WRKs4N1XoHSQnyM/r24L86qaVqATmpX9WRVTv692JTVtj6r/BbIjvfXrsJZjdgO4mNzAlqfl8gbgI5WiquH9Xn1ew/yMfqPclOdl+s7iI/RHzer85JgC/Ax+vBw3kVOA++x2So+L123AJ1lVm9ubouzUkUP8rHxyvjboa7OKkM8zMfoz2eVqH92srTz7TgrKlqIjU7cOqvhrKB7kI+PJ+5Y6sZx86N3X23v2vnDw+nx9kPv

**Comment by Alkeif** [comment]
Try this one. Check the production bonus of Barcelona and/or the other cities of Polynesia aside from its capital.

**Comment by Alkeif** [comment]
Instead of something like this
![received_558547098093913](https://user-images.githubusercontent.com/60229808/74857852-49a93780-537f-11ea-865f-9ef3de342c92.jpeg)
It looks like this
![received_497459747627660](https://user-images.githubusercontent.com/60229808/74857898-5c237100-537f-11ea-8435-e17f35a2ec2d.jpeg)

**Comment by Kentalot** [comment]
Saved game blob seems too short and I tried loading and it failed.  Could you try again?

**Comment by rprzystasz** [comment]
I've also encountered this problem (and some others). I've addressed it in: #2013

**Comment by yairm210** [comment]
Fixed by @rprzystasz =)
