### ISSUE TITLE
Building a city on a resource should allow it to build the respective building that the resource is a prerequisite of

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#1901]
**Describe the bug**
Building a city on a resource does not allow the city to build the respective building that the resource is a prerequisite of.
**To Reproduce**
1. Build a city on top of a resource (e.g. horse, iron, marble, gold, wine).
2. Research the tech needed to build the building that needs the resource.
3. See that you cannot build them (e.g. circus, forge, stoneworks, mint, monastery)

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
Building a city on a resource should allow it to build the respective building that the resource is a prerequisite of.

**Screenshots**
![received_3684950878212462](https://user-images.githubusercontent.com/60229808/74170600-23411900-4c68-11ea-9c03-c70025fa2e30.jpeg)

**Additional context**
Made it into a separate post because the old one was closed. (It was together with GPI post.)

**Comment by yairm210** [comment]
Closed in 942092e =)
