### ISSUE TITLE
Production bonus of forge should affect spaceship parts

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#1902]
**Describe the bug**
Apparently, spaceship parts are classified as land units in the original civ 5 game.
Forge production bonus is not applied  on spaceship parts in this game.

**To Reproduce**
1. Build forge
2. Build a spaceship part
3. Check the production bonus on the city.
4. See that forge has no effect on spaceship parts

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
Spaceship parts are treated as land units thus the +15% production bonus applies to them.

**Screenshots**
![Screenshot_20200211-005452~2](https://user-images.githubusercontent.com/60229808/74171909-44a30480-4c6a-11ea-8f71-575ea28c6585.png)

**Additional context**
That surprised me too but that was how it was in the original.

**Comment by Alkeif** [comment]
Additional link:
https://forums.civfanatics.com/threads/forge-spaceship-production-boost.395122/

**Comment by yairm210** [comment]
Whoops, wrong one
