### ISSUE TITLE
Great Barrier Reef not a sea resource

### ISSUE THREAD

**Issue by mammaspappa** [yairm210/Unciv#1912]
The Great Barrier Reef's stats are not affected by buildings such as lighthouse.

It would be great if the Great Barrier Reef was treated as any other water tile.

**Comment by lyrjie** [comment]
It does for me
![image](https://user-images.githubusercontent.com/26433289/74346589-d9b81180-4dc0-11ea-9f39-b05a6f8f36a3.png)
![image](https://user-images.githubusercontent.com/26433289/74346674-f8b6a380-4dc0-11ea-91e3-cbe7b4691203.png)

What's your game version? Can you provide a save file?

**Comment by mammaspappa** [comment]
I seem to have read the values wrong. Sorry for taking up your time.
