### ISSUE TITLE
Add new translation lines.

### ISSUE THREAD

**Issue by Prosta4okua** [yairm210/Unciv#1918]
Ukrainian is 100%, so this text doesn't exist in translation file.
1."vs"
![Screenshot_20200212-222015](https://user-images.githubusercontent.com/31485341/74374380-f49d7c80-4de6-11ea-9f5b-a6ce86221a7b.jpg)
2. "Delete the map".
![Screenshot_20200212-221811](https://user-images.githubusercontent.com/31485341/74374574-5cec5e00-4de7-11ea-99a1-fd339d36b407.jpg)
3. "show advanced settings"
"Hexagonal"
"Rectangular"
"Map shape"
![Screenshot_20200212-221642](https://user-images.githubusercontent.com/31485341/74374615-6fff2e00-4de7-11ea-85c3-d0b02f5a25cf.jpg)
4. "Hide advanced settings"
"Map height"
"Temperature extremeness"
and many other(see screen)
![Screenshot_20200212-221655](https://user-images.githubusercontent.com/31485341/74374750-b05eac00-4de7-11ea-9118-7d8c7c9bd3f0.jpg)
5. Turns, Japan
![Screenshot_20200212-221923](https://user-images.githubusercontent.com/31485341/74374995-3b3fa680-4de8-11ea-810b-3ff15a818c57.jpg)
6. Default map name.
"My first map"
![Screenshot_20200212-223825](https://user-images.githubusercontent.com/31485341/74375135-7a6df780-4de8-11ea-9649-1aa2cfe5e16e.jpg)

**Comment by JackRainy** [comment]
Which version do you use, I have many of them already translated in 3.5.12.
![Screenshot_20200213-082754](https://user-images.githubusercontent.com/27405436/74407552-e711e200-4e3a-11ea-876e-e3f8a7864c7e.png)

**Comment by JackRainy** [comment]
5 and 6 - the names of the files, so they can't be translated as you give their names.

**Comment by Prosta4okua** [comment]
@JackRainy What about 1?
