### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1935]
If this game is also an Android remake of the original Civ V, then I think this should happen.
When UnCiv has all the missing features from the basic CivV Vanilla version, every last one of them, Civilizations, game features, units, everything, then perhaps we can also add achievements.

Here are some of them:

- [ ] PEACE AND PROSPERITY: Start a Golden Age
- [ ] MARCO POLO: Discover and uncover 1000 tiles in any number of games
- [ ] SERIOUSLY?: Another Civilization completes a Wonder before you ten times in any number of games
- [ ] CITY OF SCIENCE: Have a City that produces more than 100 Science per turn
- [ ] CITY OF GOLD: Have a City that produces more than 100 Gold per turn
- [ ] CITY OF LIGHTS: Have a City that produces more than 100 Culture per turn
- [ ] TWO MEN ENTER, ONE MAN LEAVE: Caputure every City of a Civilization
- [ ] ONE TU RULE THEM ALL: Win the game using the One City Challenge option
- [ ] A MAGNIFICENT VICTORY: Win as the Ottomans
- [ ] A WOMAN'S WORK: Win as China
- [ ] THE IMMORTAL EMPIRE: Win as Persia
- [ ] AMONGST THE CATACOMBS OF NEPHREN-KA: Win as Egypt
- [ ] THE AFRICAN KING: Win as Songhai
- [ ] ARABIAN KNIGHTS: Win as Arabia
- [ ] VENI, VIDI, VICI: Win as Rome
- [ ] BLOOD AND IRON: Win as Germany
- [ ] EMPIRE OF THE EAST: Win as Siam
- [ ] FIRST IN THE HEARTS OF THE COUNTRYMEN: Win as America
- [ ] FIRST OF THE MOHICANS: Win as the Iroquois
- [ ] GIVE PEACE A CHANCE: Win as India
- [ ] THE MAN WHO WOULD BE KING: Win as Greece
- [ ] THE TRUE RISING SUN: Win as Japan
- [ ] STAR OF THE NORTH: Win as Russia
- [ ] VIDEO ET TACEO: Win as England
- [ ] VIVRE LA REVOLUTION: Win as France
- [ ] THE GRACEFUL LIGHT OF GOD: Win as Spain
- [ ] BY THE WATERS OF BABYLON: Win as Babylon
- [ ] LAW OF THE SPLINTERED PADDLE: Win as Polynesia
- [ ] THE GOLDEN HORDE: Win as Mongolia
- [ ] THE CHOSON ONE: Win as Korea
- [ ] KING OF THE MOUNTAIN: Win as the Incas
- [ ] HANDS FREE TO VICTORY!: Win as Denmark
- [ ] MONTEZUMA'S REVENGE: Win as the Aztecs
- [ ] MASTER OF THE HOUSE: Fully unlock Tradition
- [ ] WITH LIBERTY AND JUSTICE FOR ALL: Fully unlock Liberty
- [ ] DEATH BEFORE SHAME: Fully unlock Honor
- [ ] LUX PERPETUA LUCEAT EIS: Fully unlock Piety
- [ ] TEAM PLAYER: Fully unlock Patronage
- [ ] MONEY DOESN'T GROW ON TREES: Fully unlock Commerce
- [ ] EIGHTY-EIGHT MILES PER HOUR: Fully unlock Rationalism
- [ ] FREEDOM ISN'T FREE: Fully unlock Freedom
- [ ] WITH AN IRON FIST: Fully unlock Order
- [ ] DIPLOMACY BY OTHER MEANS: Fully unlock Autocracy
- [ ] GO BOLDLY WHERE NO MAN HAS GONE BEFORE: Win a Space Victory
- [ ] BEST STATE OF A REPUBLIC: Win a Cultural Victory
- [ ] EXTERMINATE! EXTERMINATE!: Win a Domination Victory
- [ ] BABY STEPS: Win on Settler
- [ ] TAKING OFF THE TRAINING WHEELS: Win on Chieftain
- [ ] THE ALEXMAN: Win on Warlord
- [ ] THE PRINCE OF VICTORS: Win on Prince
- [ ] THE ONCE, CURRENT AND FUTURE KING: Win on King
- [ ] THE GOLDEN PATH: Win on Emperor
- [ ] THE WORLD IS A MESS, AND I JUST NEED TO RULE IT: Win on Immortal
- [ ] FLAWLESS STRATEGY: Win on Deity
- [ ] ENLIGHTENED RULER: Unlock every Social Policy over the course of several games
- [ ] WE HAVE THE TECHNOLOGY: Research every Technology, including Future Tech
- [ ] THE WONDER YEARS: Build every Wonder over the course of several games
- [ ] THE APPIAN WAY: Build 1000 roads over any number of games
- [ ] THE EXPLORER: Discover 100 Natural Wonders over any number of games
- [ ] FORTY-NINER: Build 1000 mines over any number of games
- [ ] GOD IS GREAT: Build 1000 temples over any number of games
- [ ] HERE ENDS THE NOBLE SAVAGE: Destroy 100 barbarian camps over any number of games
- [ ] LAND BARON: Purchase 1000 land tiles over any number of games
- [ ] MERCHANT KING: Trade 100 resources over any number of games
- [ ] AN ABSOLUTE GENERAL: Have an army of over 100 military units in a single game
- [ ] KHAN: Win the Rise of the Mongols scenario on any difficulty
- [ ] GRET KHAN: Win the Rise of the Mongols scenario on King or higher
- [ ] SUPREME KHAN: Win the Rise of the Mongols scenario on Emperor or higher
- [ ] KUBLAI KHAN: Win the Rise of the Mongols scenario on Immortal or higher
- [ ] CHINGGIS KHAN: Win the Rise of the Mongols scenario on Deity
- [ ] KHAAAN!: Run out of time in the Rise of the Mongols scenario and lose
- [ ] HUITZILOPOCHTLI'S ARROW: Win the Conquest of the New World scenario as the Aztecs
- [ ] TEA AND CRUMPETS FOR EVERYONE: Win the Conquest of the New World scenario as the Aztecs
- [ ] TOUR LE MONDE FRANCOPHONE: Win the Conquest of the New World scenario as France
- [ ] LEAGUE OF THE EXTRAORDINARY HOYANES: Win the Conquest of the New World scenario as the the Iroquois
- [ ] MACHO PICCHU: Win the Conquest of the New World scenario as the Incas
- [ ] SIGLO DE ORO: Win the Conquest of the New World scenario as Spain
- [ ] AU IN THE EU: Return with a reasure to Europe in the New World scenario
- [ ] ALL ABOARD THE ORIENT EXPRESS: Discover a route to the Orient in the New World scenario
- [ ] SURVIVING THE MARQUESAS: Win as Hiva in the Paradise Found scenario
- [ ] HEAD AND SHOULDERS ABOVE THE REST: Win as Samoa in the Paradise Found scenario
- [ ] BORA! BORA! BORA!: Win as Tahiti in the Paradise Found scenario
- [ ] NGATA CHANCE: Win as Tonga in the Paradise Found scenario
- [ ] THE VIKING CONQUEROR: Win the Viking Destiny scenario on Emperor
- [ ] SURVIVING RAGNAROK: Win the Viking Destiny scenario on Immortal
- [ ] HERO OF THE NORSE GODS: Win the Viking Destiny scenario on Deity
- [ ] THIS WAS THEIR FINEST HOUR: Win the Viking Destiny scenario as Anglo-Saxon England
- [ ] ODIN'S CHOSEN WARRIOR: Win the Viking Destiny scenario as Denmark
- [ ] TIME TO STITCH A TAPESTRY: Win the Viking Destiny scenario as Normandy
- [ ] PURPLE PEOPLE EATERS: Win the Viking Destiny scenario as Norway
- [ ] FETCHEZ LA VACHE!: Build a Motte and Bailey improvement in the Viking Destiny scenario
- [ ] PILLAGE, THEN BURN: Pillage 9 farma on the same turn in the Viking Destiny scenario
- [ ] DRAGON EMPEROR: Win the Imjin War scenario on Emperor
- [ ] A RIGHTEOUS VICTORY: Win the Imjin War scenario on Immortal
- [ ] HONORING THE ANCESTORS: Win the Imjin War scenario on Deity
- [ ] YOU MING!: Win the Imjin War scenario as China
- [ ] SAMURAI DELICATESSEN: Win the Imjin War scenario as Japan
- [ ] FEAR THE TURTLE: Win the Imjin War scenario as Korea
- [ ] EMPEROR FU MANCHU: Win the Imjin War scenario as Manchu
- [ ] SEOUL POWER: Win the Imjin War scenario in less than 100 turn as any Civ
- [ ] TAWKNWON-DOH!: Lose the Imjin War scenario as Korea
- [ ] THOUGHTFUL TELEMACHUS: Win the Wonders of the Ancient World scenario on Prince
- [ ] ODYSSEUS THE GREAT TACTICIAN: Win the Wonders of the Ancient World scenario on King
- [ ] FAR-SHOOTING APOLLO: Win the Wonders of the Ancient World scenario on Emperor
- [ ] BRIGHT-EYED ATHENA: Win the Wonders of the Ancient World scenario on Immortal
- [ ] ALL-ACHIEVING ZEUS: Win the Wonders of the Ancient World scenario on Deity
- [ ] IT SATRAP!: Win the Wonders of the Ancient World scenario as Darius I
- [ ] EPIC GILGAMESH: Win the Wonders of the Ancient World scenario as Gilgamesh
- [ ] PARTY IN HATT-USA: Win the Wonders of the Ancient World scenario as Muwatallis
- [ ] RA'S MIGHTY TRUTH: Win the Wonders of the Ancient World scenario as Ramesses II
- [ ] GRECIAN FORMULA: Win the Wonders of the Ancient World scenario as Alexander
- [ ] REVERSE ENGINEER: Capture three Wonders by conquering enemy cities in the Wonders of the Ancient World scenario
- [ ] BOW AND ARROW: Build the Statue of Zeus and the Temple of Artemis in the same City

**Comment by yairm210** [comment]
I'm merging this into #663 where it should have been =)
