### ISSUE TITLE
Declare Friendship/Research Agreements in Multiplayer

### ISSUE THREAD

**Issue by YonniF** [yairm210/Unciv#1936]
Currently, players cannot declare friendship with other humans. Although this isn't really an issue for game play, it precludes research agreements.

Thanks for all the work,
Yonni

**Comment by Kentalot** [comment]
Initial review of the code seems to disable the button as long as it's not the player's turn (even if it's another human player's turn).  That might've been on purpose?  I can't think of a good reason to disable it though. @yairm210, any comments?
