### ISSUE TITLE
Liberating cities to civs that don't exist

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#1937]
I just took Mumbai off Russia and was given the choice to liberate it. India has been wiped out a while back though.

I didn't screenshot things as I didn't realise this issue until afterwards.

**Comment by JackRainy** [comment]
As far as I see liberating such city leads to the "resurrection" of the wiped civilization.
I don't know whether it is good or bad, but can be applicable, if a friendly civilization wants to return the friend back.
Which behaviour would you expect?

**Comment by yairm210** [comment]
That's a feature, not a bug!

**Comment by yairm210** [comment]
That's how it is in Orig. Civ as well =)

**Comment by Whistler11** [comment]
Oh cool! Didn't know! Thanks for clarifying
