### ISSUE TITLE
map advance options "map height" can't set too large. 

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1938]
1. "map height" should replace with "average altitude" or "mountain percent".
2. map advance options "map height" can't set too large. the reason is that when all the tile of the land is mountain, there will be not enough tile to place civilizations. the game will catch this bug. the solution is giving enough tiles to location civilization at the time of creating map.

**Comment by r3versi** [comment]
Both of these issues will be handled in #1909 (for reference and discussion #1806).
