### ISSUE TITLE
Polinesia can built no improvements except Moai

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#1944]
**Describe the bug**
The Polinesia worker can built no improvements even a simple farm.

**To Reproduce**
1. Play as Polinesia
2. Choose a worker and try to build anything

<details>
<summary>Saved game</summary>
H4sIAAAAAAAAAO1d244jR3L9lfY+swRmsa58G81qJBmaVXtm1oIh6KGarJ4uiE22i+RIvY0BbPgTDPjJgH9hYcCGscbuN4z+yFkXVmYVT2Sd4qyePLrMsJtZJyLvJyIjo55WxbtiU/whOxS77X75/ZP++XfZfb78PCtvsrLItvvZIV/dLZ+qP/ev8n2elau7fL38/sWmeHt3mH2xyVeHcrctVvvZtw+H6q/Xhzy7v7re/ZSXs2er3XFf//b57v6m+rjbzl4W22L7dvY606L131+sj6tagdmzCrt8nD0/lmW+XT3OPs82m6J5/svj9mH301pjvsjLQ6W0/vgyP2Sbq+eZLlIBrXbb3X0jbLs/lMdVh1po/Q/HMp89O1Qlrt7c5buywt/+WD2plXvI9vvZq/xhk63y7GaTX11n5WE/+2pX7vObbPXj1ati3Ra9Kbb5+upZea8F3eX3WkEN9fV2raunm+zUnLPPdbP8Ib/6blfWMl6vinx7KG6N9Ou7YrPb7x7uHmsFjoe83OvG2RSHrHy8qsuv8tl1WWyr6l1dl7lW8WV20DKztk2KzXo/+7zYbXZvH2evdqsf80qXl5mu8bZqyS+2b/WHvKwUqNohy5uiTbcVq+LwOPvt4za71w00e5Wts3J2vTscqkefvdXfHzd1q32tq9JV5FVxW/dbVYsa7HfZu+JtU+dXuk/LXbae/e642uixcvWi2O+rL55nm3xbwWshxa7qqvrRl9l+t9XC9JjJN7pBHvdVvd6U2cND3dh3xbtso7/Xsq6+u6vKPNsW97rPvzrub7LtWn/1XVnUvf+8GspXr/PyXaFbrR4Zm2NZNUt+WxZv87LR8HqTNQPq2b4at7v7qh+y8l53+1H/Ptvsf3g/e9htdNvk++XT+9nb3Wadb5+9rX7aH3Zlvv6q1k53xlL5c12gzLPDdb572OTLp/aHUlfreqc7roJ4P9s3ffn3xUoDPFao75qPL7NtplWrfpP//LCp0N8Um7yaij8vPX/2uPSS97Pqs7I+h9VnNW9+WFhfBMPPym9+qJFS64HURlKWiNR62v7cE3f6IbRl1N/Elrz+I8p6pAes3usWf9IT7zEv3zw+5MuvjvfZtm73pZrPTkvS9W7zqBu9yNoVqW3Tb2+/0R2avDmW1QIWzHr//jD7tG59Wrf+v6xbzWB/szsN9+X3r7NDrkfiIT99+fX2uty9rTpk+WS+XAbz9/ai1yxzz5tGrObg/m533Ky/fcj1oqYLPV4XusfKpR6quXuBTP966+O60Oujrq7++kWZ6dLLp50eUuXzdn1ofnkqppvk9SE7HPfL6zzr/frlbq0Hs9Zg+fQPupn2397WJZbhe63IdleP9I4PHfKfD8vffP/hXz/85cOf9f//+8u/VP//cHWX7a/0iq27Uk+p4rC/utmVepLv/+Y3s2qIaI3L5fyzyI+DUM3e6o/KD4N07s9u9Oc0UCqOwlm21ItiVs/25dNKd/B+udrdf3bc6jXvMz3OitVnNkH77Jtdo9mzZoHY7IyiPy+r1TvRS6leS1utq4Gfl42uN3m+vbrR8+5wVWyvzivUUzsMwnmazONacT+eh0nih7Xm87j+Sv1Kqv+gV/tDUW9/pxLL7vtZsV7eRoEfpPGt5weJ8gK1Tr2bRbz2Vtl8lSa6gRe32WxbDYdhDWe3u+O2Wgn1eLH2kofdw3HTCrrd7dav6wFcj/mHfFWtivt2jFZrjr0+69/W7fl5tZhpXK30dVatwroS9T5wsEsvf/ObeovXjLqW1eBVQ7QmGYdu02/r+vS4bLbSaidttsvqm7j7lHbfNqUtmhDpdvyp6nuLSzQP/9C18PNqHlYVBbxjMTvBVRt0u71X+7YKzO4edfKjWn7zc1SVsj42+i46fWvAhQEMTdHEYJunWgoRGOGn70+lQiMx7EtsGYdSBkf51u8XpnKB0SXtKq/HwEntqF+0afGgk2SJb+TERt/E6JeaatbY/rzrTav3EvNYbB4zzZcaYcootxgMDM98jE3lEqNBahRIjIDQVHTRdURgKla1X1jX3gC2KJGpc2zqbDW+d3q4LWCBK1NWGT0WBtd6LDEfU6O+35W1vjftG9mzw/R+2xmB1RnKiGtGi9V3C9N3bU2bIrEFaQaM1frKKLowcIEFF1rSIws6MdA9DWOrjNUMgWkyM3NiU/nYgkgMRAudWprM+/MqGSxBsWn0pqiNbMaSNX2UeW5hFDaT7lTtuaWbGugWW0VSM9H9TjlrgbKmlFk57LUy6c90ZeRYa1VkVUtZbe5bXb4wo6jXp8oobiaaWbetCixqtVJLlm/JWliyAktW21PWspcYWXbpbt555mPzmDW8TnBWteOuhVKr/nNLP2Xp5/cX6dPsC6yOC03HpQYl7hojMWL8ocSFJdGefKGpbmjVJrKkJ0b6aRItLK2CRqvKCq2NTj/ojM6WVH6yOD9ZnJ8sTsbifLm70Tzy6k1lGqyQ1dkvsFz4DsszGfG+zYNfw7rsjIOBgWmMho+zMaGJc9oMtY0T3vqLIF5EXp7OQy9YJZmXrdPci9aL+VqbPcniJmptnP/48Mdf/unD/3z47551c1q09AL1bPWPx6IyaHzJ0kk+xtApuo4dPNCYnstQr8LIGGq+7hlE7QQ6aSXaRxZrsFi2RSAsHjTk3tZjIbCRWjzOSLJMo9QQK3vjs2yQxJSYG9ZBGCbKMpiUZYIpixVDi0VZHHyKYWJZOpYJgq0Ny7CwTARsB1iGhcX4Mc3vEWyLj1tE36bjFkuXWD22CwTung4qcEbepzJ2YwxI3N0i7BaxtkaywMwlIi9R8l+RiPeosE2RIbe2uLdNrW0KbfkHlOVWUJbtqCwfg4oHTdEjjNaoGVJxm6u7OXZkCU0soekZD2/KWDOx1y+WMqYvLLPftvNs7n9O0HskPrLk+MN6nBPwHpO2GbbFqhkqnfTrYY8GiV+rjl+/Ou6JE535J379iV9/4tcVv9ZTQ/cN4NXNF0s/cfDpeIxPR381Pg1Jbr0j1xw3WQXzVM1vveA2yb0gyddekvk3np/fhlkYqSTLg5bj/vuHv/zyzx/+9OE/P/yxx3JPS4fNcheiPz/4NWnuIryQ5sYizW2b6qn1bHRsaWEoVPfJ+NPNEz7gtw0SR2+bE/zIwjvxB68RvOi+8trz/zp8oPm1HZRgNLQKVECWr9KQwe6TtTGZA4hWdqOc8Y63vNL6rvps/mo3906dnsbNZ78TnnSfok7zXmDFwrSM6aUB1ElRK4zC9F6jYmihGZ+qZ7Ezq7BpbdVUyTSjZzq9fdhydrd6Nnq0n0MjsZHeNlwys4I5IqvCjV5mtzey7cKpXVhZ8E1Fw8EgjU1zRBZ+o50dwmIskFO3WSEkaddOatBidhdXv2+0N0PAeBmtbrMfaseO1b2nMJn5oD18q+ax1ZZtLVKjbtANbDODF11D+NazaU+WspBODRVZ4gJrQCnrc2i63QwxW93E7nqLoy5sgcp6wDR7r4itehvQ08TvJB3V0zvolmB6809M7xPT+8T0pntS/cDB/KIx5pf8uszPU104omZ/+ep2nqyi2LvJ/bUX5Onau4lvM28eR5GfrzL9d955OP/rw59++bcPf+5xv3YtsalfIFI//9ekfoF/IfWLROpntVX9U0N82uVW9YIp25KL3k+qV7KPgmihwSSpYWSRhtjabRKLZKhe0KjqRbLOrZ1L9SNQo57OsV271H7KjoZVdnCr6sWnDlqkF67ayjq1XbN1BT3Jp5+aPS601U+sTTi0miKymqKnbGor2+mHehP3e9TTKLE18huSEPV0D3u6R72ScU8Xm1z0uii19R+o7PdUXvRUDnoqhz2Vo55acU+tpFeBqPdc3Hsu6T2XWm0eWJWx+8XmuL2OjKwHIrvCvd7rauH3dJvb9bV4Xo//2bwwssXMe+2qekPB77XyAkzzoNfmYa/N+0Mh7rVk0mvJ1G5Jf95DiXsoSQ8ltVH8fh38Xv0Qd+1RXB+sb0GvqmGvqlFPyf6gSW0lO7XCXnWiXsnYLmlz4laTsKdJ1ENMbES/t9Z1NVCg6/prX3/l6q+fvSWu00X1JMxB+zWhfuvi9rbmU4/L77JSL+Prept5mT0sn+6zB8029R57qI8p69325ePVbVHuD1f6y9mhCsV/rvnl7n52r/feQ1bvhTfZTcUWH6tg0LT5J9Dc5P6hIjt6e/vi50OZ3+c1rZh/5jclEl2iLDXAi7wu9KpY3Q1L6D12dyxX9ndGwE96NyoH0oPmy7jZO7/Ru7venm6yff6mkbX8stT8eqMZm26ah92+MGSkbqP3M7vwbzXxKg+Dkq1ROQ4q4Q3qvfw22xf7wZOUgJ+HxaC+QyXEFjjZvUzh1jC2i75sxwNs2EFZTX6L7R40rCS+GwnL59nhsMmHDT2OL2MDNbiOe7HRjPLqAdXFc42SMxzNpfbDbvOhBl0zvMzKm0Ez/HzWDF8Vmw3ouEkDghpi9QKzGO87bdLthgOk9XXwGi1QX3Ntei5qwtOdM5MdRVDUcOSOt9rvy2xbHO8HD44/9/r4NivR4IaThW+CCUsEN3rAmAQjdzF1SpqW0BZ7dj5mCdUWE2bLAtS3qgbVsIvzdp3SLYsJS3fjGAy4wq1zEujVNe6X+f3Z6rdwiRhW6W+P27dnS9niXPA0gM7nP7rv+GId+VWBVRVCKEmB4VpBddoZlrAxT1nNPLCcOee9uI/TXUeOZjTr5D1qfJXh2m7YE8PdGW50wbkCWNNAWknM0n6X5w8AXiANu2zdBiWe/KJQJGAP1PgNqL3uJIUdcmFrlo/CVgWZct2JyOUzNTgXJY2QBav+glXfB4h0H/msFAWkOFYQqTmHS5fY7NacyTaDpyjwdiVjVnqPW2nbNYwa0iKlROsUuypqcr+/QwPqcoqA1hQnQ2BWqpBZzWChCaZUSK3bXigsmgCNNFxDV5cBWIZQNqDkEhiej1Z6vjeCqElx8j8SbVIVjci+iC4eq+G5FMeCPkGOWWx+m+dD0yhgpS5EqWDOR+SU8wGoi2FJRU0VP8+2+l+8vo8//V2xHdIyxVbnXMDZIDlDcpFUchvw6P2oXeA/gvQDm8HJUFnSA5whQssgxjalBoAuCpLQyoolYTYPFvDJm0D0kc8PB+R0BbhdKAJtBTeCSGbrTiPCi0C/A02i84Ek6jvuSqriLoCAizeniN2covMpLVYD0ltOn9Nx3IXPV4/Dp6GeMbcWROeg40ZgF8jH8ouYWgK6qLuL6WvANtFC7AqwrlKIPkCcZDeRzekpQRDY0y5TR6hHNyLqILGh14hTSKYEtBMM7PkO667dg/GkdXtugS0L1qxvizMPMr3p440M+CT7lXy2Od4X24Grvt2q8bmDWWHf7cpHNOsm2ArUKZsHLCBh/xBOwcaq6wl7pXvlipGss3Wa2cXPz1O72Onx1olBvUHzxLgRRxbnmNu7Y7x3T9jKGI9EjEczxGO26phn312EGAVKGJzxlBUMT+5TdM6oSu01RWbXjAEmeVAXn0sRiY8ogal4dC7I7ZIlC4cOXKvqxeZHyDWYngjORTg4BSxJH85Rcnwgp+21JvFZtv39tjgsn3Y/bfNyaZIH1JE2TXjoKXL05e5dFTJzqG7pl7v7XSWkiVQd7qGUakpQTWyAX0lhhcf16BmF2LB2kUEJzTngWdvFZNAD1M3pYZji/UH0aboXSz524DnOuMGFjpBlF934LoO8olNdDIPHv8l+zJE1Sey/HjDOhW2aoAoe4B59rgBO0Imlf7xIQrrx2ys61J6WSKcQEHO8ERPOT5GwrCYhT3i6yODLjZ4ETxVuJUnAPKWduMn5ciFRkGTCMpSwFnUCFtGJdOsUGD0qrM0PQSollbxvbzM5drOvt7fZtrq1dJ89VMWeOROZ6kKfNalOP3t9qK41tUlM2/SnXzQ3JN67tsKErVkMaib1YXwOKu46kQuXcepEE4SFQBg9XUK2qQJ2WAUSIhMtsWClLM6l1HUu7vW4aOnSy11WCELRqLXewlAP22fbQ+G9ybY/Xn153E7jYl0GeKd+ncCrfLvK7h+qXwKug2CIplQfMywUljskjuIQdy6zQpWcAbgSy0a1Jsgq8lw6OSRZFp1guuJYaGqKaCLrEwCxNRJTJNwW4OxcZITkOQlBMJGDh3dSeYJXCWzTY66514fd2fmtB/ig0OupGx0cB9H7CBwoKctUU56pptIJG8Qcb/aUY6opGFEODS8+Qktd/BUIooK/UjBhRVaGAy/cQzAFK49La4qOpmCZFLXGbiAztLerfLvHenOOlu4G34Xepi45GjXShgXtxkT0oc0D2We8Do6Qysog+DYBDw1vskx8nB3magbg3x9v3XgKaESCRlNAw7HuHW6Lwphjo3/x42BHHxZEzMW8EugjfK6UIF9qe/p4l5lr6qOkKEYKEHBeYcf4ucBZiMi383Q7He8Q5AN3clayrBwXwF+RGT8KRxGFTsZKlkXB7M6ZP86EUQyNRF1JnkCfHXrgiNLlVeJOplnfIiKBLm+xKybAA9QT305lFiN5crrur572fMZucN45nXMe6VMCNW7azzl6fEoRNc63G8QL4iHqB4kR3wggb0HNWW7coI7Py7ocFUjcJZtg9Rxfv0wilZFhCC+Hzvnl2KQ8uWxHnBOum07Kpf4hK4HGWKedMg67xiSIYbISWjDDApWbYO4RYlJJymjUToIkuBZ1tqxJ/8dwbhY0kkCp9oxcovqODoZAh1PaLgSy4W4SIFSZljOQC7IrFiygTwL6LCCcsdJJ/rAcXDwpPE470QxAtWAYg+iBpxYF4Hd30mc6WIaNKJK9vqzXGsQFTzoVGr1p0s7O8WIohlzi02zoGsPPQRyek0qPESfswALn7DK3ptg68K8KxBmwUoE9s1ycQuOQzkUKaKAW4oVULpXNl7vNOa1CGTqccugr/OjCv9wobGgEvKuq6Cu5ClzaEtgyugs2xa8qxKhjOeMFlRDHj/GIKHwhNA7jMUu5Ai6biWEaSjqfhfNosOGJGaHgNnrxxU0rMd54k5zeQjLV9rTy2MnUGkxopUSBgilxaRaG7j0isn7gfkhnWnAHYBdrZzKJ0+bFoOyb43ZdZti24IL1ROnUmhYhSY1SvXjmd2cDNKKHQDilkUIA67AjpqVkGQtBC1jhiylVWrCocMZP8/ozYuCcF42R0XIUGKea6NhwJ2ZCRpNolzCGDjpAGa6ncNlBMVRIAAihEk3gKTH+7i2FvVow5bqlB+5bui5/MqYNSMjgdO5fHK8KbveI8bcfc8eOjd9FYRaynXKRzQQ937Lhwl2mh3aEbHFQNsxA8rerPDvnXEwojAKZ+LBucnI/JtBJgQRfDjmsNQRy8cjWEErx40QmbfQWeUJuCfcRLZ+4Sb5PizDHonceitU5VVToVossg7xcrlCco4zKOqewZeq4o3Um6WNio00KekbSx0XAWBnkKWGsj11B764w/Lp85NSMOr0Zcooe49F33UseWXcCg6lETNKGnkuSJth1F98HTp3dcsGKlAJ1sG2WXCAaGYJQ2IjN5cVIONQzpsdMhDAnuKAiuTZUX4ZTplgIhDnMw8sHeMAKmrRCoAXCYQpeOj/QguEwBYnlggIEWNASJDQT/VLQ9iNYF1z0xaandgcYDShZe3QgImM+ivd8kCF3+RVxz3ndnV0bKA7kgcRAXAI3lCVBOpGacGXwohwu4PIkE0COot7h0ASx9a7IGs6URDFOTjuPsnHAYRFPDpAhJptSRJjKoHrYmGTivBRIuCygicYkgqTaFKVblSGp9X9KHj/lTF8+4o9Xcp4iJIZNaCyQUzpPsZJugrlz3qgJl80UndNLoXBgftaAGAe4Y6KoCThpzncZ0dhFjk90l0yhvVA2kcQtlm8R3i6EYURMTueTpI86iTGvG6MavHs11iiTqpkss7uYN1KdFXUFGzd1Z55Cd2uaFxz2r9YM7/sq52Ub8xqq0abw6aZQNKaiMecIExpvjXUMS7o9/CkS4bqKRqnjJbLmvMF7+eNejOSL8UkfIymiJUUXdlFISwjZkQXXAjmk0j1Vr/Os3MD4OW7siqsBNnEv7yt+MiNBkpE7CshgcYpB41usAVMQHiDLRi5REO6Joh+EKQiv5UlGLhNtinJwyIEIxGUvlH5ONlqJjAcoES9sQ5ByF5VD6W8gHkipc3ZKeH7rHd2XFs1RimSjqyvyHknMVBT1J2/kFzup0UGdbIcS14mQUSibj4RhGzBYg0ITjjTBOzMEEaK163aZKJCx3SFhJLk4ClUD6WYHO96LArBxlN5WMvBAOjg8SugMcwrkDXFAUpMQXOx0QBKhoiDK3QFInYSCCBXZXkPBMfzcBj7UEVEXJ/RBOxmwK9ErEc3cQkawK+OoQtdn2Kub1vvEL/H2KDqQzrwJXJAzek1J0Sc15hXe40W7d02PkriapfNTlcIMaMwFjbmgMX0a06cxFY2paMw5wnTY0yyl4TBTFjKhIRMAeTIpx6/rxUiObCRjOROMZEZSxDYSnG+yVcxA0tMNzTbsB6FnG5psU1oYTkGoE5qCzpdWSwPMYRCgKQmUodqGbGrZ/zbC20inADxfn3I0yh6xQ6+ufEeR2TT5G7Qee4UWpuWRjWjGLEd5OGUrmjDLUd550YomyqF8r+ICTpRDWcDEPYaKNkS5GeStkHy9JbrEJu/ZhC2OYk6ZmQoCW0WTmbIQwTnqNI7OWebseySH6xxGY942qcDLxgQ00QxHkFSronewSGMLZCx3gMLz9gmpYRRIh+lg85QXZEwcNRtRXiS5FyibXH75JIKkrHJ0ywNNQBAE5ADkXiKiSFdsC8psIwptTBOPYB3b4FhMKTbeFUqLIbsZYMYN2eqkDGx4+07GnGAdM2F89BmWgudiuGhjf0TjC01dkil4Es9ghjRmQGMGNOYCYcoGP4Xp05g+wHQZ/IOiQ1tDyNrT+AAoMXNGDIylbnwCLF87kyHe36IgExoyYSFjR0uMrF3gmDpmxcK5CE06NBcdvgCiJJqJ2HCHM1H0BVCQ9ERE8xBDwnkoW/1krnM4E8XrviNT6cWx7I9QCptsANpJ6LFOQhhjMOWaCxtkAG8B9H30gnsfXQlAyzR0lIvn5gS1h2TDYfMTBoiYMpj3Kw6fRmLQq0OkkO90HA69JG9gwH53l23OY1rBS/NExwBDyUFucDhPUYZFvLODrI2i031osWBEkNlGZApDk0tmH8DNMEqtUeiyzJkITwM6YZaJ3cWeBmSjy5z08uvI1ABhBgd486kAJnofxs4LwbvJHCIufheFAm+8cMghxgzIQ+wARMOcGjMgPZtDDBUOAJIsOCAp1wO4w+OApAICyAirFpIIaiedzS0gUVKhXctltxJFFcrk6cJkXAYoYY8LExV1unQVugnqksA4EFCYrWv1cR8ZwX1coVNKlwyqaGOPEdOhLskUPIlnMCMaM6QxQxozoDEDGnOBMGXHB4Xp05g+jakQJhEY3jg9KBFzWQR0cqAKjgV8p0jGBMsplQRjVwhTmYSFhFNPviXPQMKZJx17UqI9OPFENwceUJRZBWcjMwjQ5JwiGE5Z+dLA9DnjwQkse0xGJEhJxF1TmqJv3JgY76Xh5StyqNEeIE92AUHHCuOqYWPE4A0T8Tb95MgQGPsnuk8IGwGeq0iJmhl/DGRycsQE44+B74ViXgCAXhQluk4YOg1eC4vw0BvJRFcJ82J09OIIeVNlmABKpCszAfZQhXO+gLRZIgPinC/gSvf49WcYHC8zQcKMRkEGMl292PWCHBQy02aMKmpoMcMKvE/dZVeQiFSTOt7v6br2C96W5MD/6GAPkFHeIY6IWwLJHx2AKMeke5KAhCMOfOK+Bbgd5gAkIjtAoJwDkErOTbrcW0jGvYK2Isxd4G4nY1LuFfiWFxmTcq/A7M4ypju0Dp9MKJgoTPY+8BOLKapQgLkLkyiq0Im0C5Mq2hifxByoSzIFT+IZzJjGjGjMiMYMacyQxgxozIDGXCBM2fFDYfo0pk9jKhpT0ZhzhDk0W4XzsTkrJZWFIKcOAwnnFReMAnO0otnncP2Qd7IpRDj1RM8Puo7otLTgLBS9QEwneXASwqJoErqiXSZ0KHLwUJLg1CR8QWiiTnFWwenLBqxxteO6hWwo6JSSnTqsj4zzE6H4I9Gxx/mJ2PuJMNmJ6MghQndgMKvoyCEoFTw+k/LcM54hSELlV9gyniH4hnLRc8O4glLWFZRyJgJ8Fae8SzKcA72zSN7LmeMrlDlcZhxs1C7nDAJp8sTLxJwzCOQxEJ019DUPOvmGI8jw5LqhQ0RY44pzBgHfDESkBitDEBPWGZSwziDwFmoHIpHJBLx6zwHoDIx8mZU35y+PBu/McAgghi1IzuoAvPSdIgrk3HGIIdw+4PqhA5Bw+4CwRQfg5emDFen0bwXBSz7j1Ivdn06ThfEPoRcBuzDZGci91AS+VEx2SvCzkPIHoVx9LkzGH4QSG7gwGX8QuhjhwmSu4aAIAxcmVbQxrxnGU5vX/IShMBMaM6YxYxozojEjGjOkMUMaM6AxAxpzgTBlvxWF6dOYPo2paExFY85pzDmLCaeRFG5PIcJJJGUKYMp5cAqJ3idUzn1nHk4n0Rc1KEfeBXs8P02AM070UUGx2EfFFEUTjvOAenAGyvFHlOJwBsoRRxP6ADukRmqOTKWPkUt1NDcbaH+4R7rPTg4qxueFwr36VgfIc0Nf6fPQnT7ZWcVmK2IKwmvS0tU/dPta9lg5jTSc1R9FfMseLMIlhk5RZf8Vc4TLcvmU9oilpMXR7IL0fsmwD/SWbHlXZ3xi6C11MvdgfGLo1QgyQ2J8YijHpczj2KR9nE+MzDECLwzJnJi5+YDCcmTmPv22BvIdydYGUZCjhrQhxNtWRGOmrP8rBa0uIlL9jV7qOnouqMCrfhzwhPsLJGt2ADrDnVCKOJDUygGP3rhCuZTAFVmHGCcBAExXgbBSB/zFuWfJI5BWDPcOFsVuS6dZwzjCUtoRltKOsJR2hKW0Iwy9vtGFyTjC0OsxXJiMIwwlDXVhMo4wlHTEhck4wtDtHRcmwwvo4BEFA1JgUb95mzUx6uuSTMHTFsAQvJTGTGjMhMaMacyYxoxozIjGDGnMkMYMaMyAxlzQmAsa00eYosOOw1Q0pqIx4TwSHXYUJpxGksOOQoSTSHLYMeU8egqhGSSHizEl0fyR0yExJdHsEX0NFCKaOyNX0k5uNwYeTSPRm0Mhokkkupy48T7eBCAEmwLnVKXd8x5y/EmNxDnmUEzduGUJr33CCY2ufcpuNMYxh/J3MVdd5Xz/bo88ykYue9gIR4LHJjyAEf7iIscwXnjuLPvUCF5OGwUea2i0J0v0nkb56RTtp1Okn86n/XQ+6adDrwaVaQybeoHz05FvjoF5b2VKyPjpUNYcmbgyfjp0GU2m14yfDkVMyUYAa81ynjnSUUaxK9qKYjRrDDNKNdIz15p6xPYG3mftQGReqwfeSuZAJIahDxK2OxCZTIcg1ZsDkZjOPrgR7UAktnGfDNRtEQmG4pMHJy0iQ47YXeM0xBlWOmfdaC0msWM2mPzEYYo2mPzUYYr66FW2LkyiqI9e5+PCJIr6KB2wC5Mo6qPsOy5MoqhPX+vy4eUxGZOfRrjoD+9nb7P7/Dor9Z+HvNwvn9bF7W2xOm4Oj8vvNOneleu6yOuHPF8v/+5YrH6cPWyyx6rs90/NpzePD/nyq+N9tp2t7nb7fPu8eLe83m0et/m+qOIBzG9flNl2VcUNV//9MNsfsvJQbN9+UWbLF8fK+/5+pv/c7ivS2L5S+rqWYfBqdb5eLxehihdzpbzcn994wc381ktX2dqb+9lqnUdqlQTz9/8HH1KDXEQYAQA=
</details>

**Expected behavior**
The Polinesia worker should be able to build improvements same as other civs + Moai at the coast tiles

**Screenshots**
![image](https://user-images.githubusercontent.com/27405436/74587303-8b418780-4ff9-11ea-9cd8-ca98b26e24cc.png)

**Additional context**
Caused by 5117a9faa4b5b8b65e0aa71512a502cf200b83e1

**Comment by yairm210** [comment]
Resolved by Jack Rainy =)
