### ISSUE TITLE
Different language has different length translation makes that designing ui is a hard work, especially Russian. the number of characters in every translation should be limited. 

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1948]

**Comment by JackRainy** [comment]
Excuse me, but I disagree on that. The UI controls must be adjusted to the translation, not vise versa. 
Иначе получ. абсол. бесп-ные пер-ды.

**Comment by stoupa007** [comment]
Also, the limitation of character count is technically incorrect and extremely clumsy when you are rendering any proportional font. And setting character limit to how many W-letters could fit is huuuge waste. So there is not simple way.

Leave the eventual shortcuts (and UI consequences) on translators.

**Comment by lishaoxia1985** [comment]
ok, i understand.
