### ISSUE TITLE
Polynesia can't build Moai

### ISSUE THREAD

**Issue by asilano** [yairm210/Unciv#1953]
Since the latest update, with my save game as Polynesia, I can't build Moai at all.

**To Reproduce**
In the attached save-game, there is a worker on coastal grassland west of Aotearoa. They don't have the option to build Moai. I've found the same on other coastal tiles.

[Savegame](https://gist.github.com/asilano/2a6700bc28d7ca7c12eea13491c56a8b)

**Expected behavior**
Worker for Polynesia can choose "Build Moai" as improvement on normal coastal tiles.

**Additional context**
I would _guess_ this was caused by the change to stop Moai on Jungles etc, but I can't immediately see anything wrong with that code.

**Comment by yairm210** [comment]
See #1926 
Fixed in 3.5.14, please wait for full rollout :)

**Comment by asilano** [comment]
Ah, sorry. I went looking for it already existing, but didn't find that - because you'd already fixed it!
