### ISSUE TITLE
Science victory bugged?

### ISSUE THREAD

**Issue by AcridBrimistic** [yairm210/Unciv#197]
I recently finished researching everything, including "Future Tech" (which doesn't do anything btw) and I've constructed the Apollo Program in my capital. I have access to coal, iron, etc. I have 881 total science, but none of the spaceship parts show up in the construction menu. I've built every wonder except Chrsto Rendtor and the Eiffel Tower. Am I doing something wrong?

Medium map, 4 players of which I and Egypt are remaining.

**Comment by yairm210** [comment]
Am-per-sand, I think you've nailed it 0_0
Do you want to submit a pull request or should I?
________________________________

**Comment by Am-per-Sand** [comment]
Thanks, but I am busy enough with [unit icons](https://github.com/Am-per-Sand/unciv/blob/master/README.md), so I'd rather you fix it your way  :relieved:

**Comment by B5656** [comment]
@yairm210 I have exactly the same problem in the game that i'm currently playing, and I have the last version of the game.
I have the Apollo Program and all technologies, even a space shipyard. The only thing that i doesn't have is alluminium, but i don't think that I need it.

**Comment by yairm210** [comment]
Okay then

**Comment by yairm210** [comment]
Could you put the saved game data here?

**Comment by B5656** [comment]
you mean the string that i get when i do : load game -> click on [game name] -> copy saved game to clipboard ?

**Comment by yairm210** [comment]
Exactly =)

**Comment by B5656** [comment]
here it is so
[uncivgamedata.txt](https://github.com/yairm210/UnCiv/files/3020345/uncivgamedata.txt)
If you are going to launch it, it could lag a bit because i'm in a middle of a war (something like 100 units on the battlefield :) )

**Comment by yairm210** [comment]
Aha
It seems that spaceship parts require aluminum...and you were using all of your aluminum
So I disbanded one of your Rocket Artilleries and I was able to build them =)

**Comment by yairm210** [comment]
So the game works fine, but I need to figure out how to display this information to the player =/

**Comment by B5656** [comment]
oh, yes indeed, I tried it too on my game and it worked.
But it's a bit strange that spaceship parts need aluminum, and without consuming it.
For inform the player you could first change the description of the spaceship parts in the civilopedia, and why not change the name of the building in : "SS Cockpit (need aluminium)" for example ?

**Comment by cplir-c** [comment]
Hello
I traded for 1 aluminum from China, and it's not letting me use it to build spaceship parts. Should I open a new issue?

**Comment by yairm210** [comment]
@cplir-c you're probably using it for another unit - you can see what's happening with your resources at overview - resources

**Comment by AntiSol** [comment]
Hi There,

First, thanks for unciv - it's awesome! :) 

second, I seem to be having this issue, too, but I can't figure out why. it says I have 20 aluminium available and all the other prerequisites to build spaceship parts, but I don't see them in the construction list.

Here's my savegame
[savegame.txt](https://github.com/yairm210/Unciv/files/9258625/savegame.txt)

Thanks for your time

**Comment by xlenstra** [comment]
@AntiSol I'm not sure how, but for some reason your save game doesn't have any victory types enabled.
I've edited your save file to enable all victory types: 
[Fixed Save.txt](https://github.com/yairm210/Unciv/files/9259225/Fixed.Save.txt)

From here you can build Apollo project and win the game that way :)

**Comment by AntiSol** [comment]
@xlenstra Thanks, this works. But I swear I already built the apollo program in constantinople!

I continued my game after posting it, can you tell me what I need to change in the file after run it through `base64` and `gunzip`? :)

**Comment by xlenstra** [comment]
I added the field `victoryTypes:[Scientific,Diplomatic,Cultural,Domination,Time,Diplomatic]` to the `gameParameters` field

**Comment by hyx0329** [comment]
> I added the field `victoryTypes:[Scientific,Diplomatic,Cultural,Domination,Time,Diplomatic]` to the `gameParameters` object

It seems the very first game created after a fresh installation doesn't have these values. My version is 4.2.5 (Build 749) from F-Droid.

**Comment by xlenstra** [comment]
I'm closing this again as this is likely the same problem as #7775 and this issue was originally for another problem, which might get confusing.
