### ISSUE TITLE
Can trade "Future tech"

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#1971]
Similar to the "future tech can be taken for free without prerequisites", future tech can also be traded.
![Screenshot_20200220-151339](https://user-images.githubusercontent.com/60082415/74901385-d04d2b80-53f6-11ea-9713-ba56ac1de28a.png)

**Comment by JackRainy** [comment]
Do you have it researched? Does America have all prerequisite for it? If both yes, I don't think that's a bug.

**Comment by Whistler11** [comment]
I had the tech, I think they had the prereques. So then not a bug? I'll test it again later, but what's to stop us from just trading it back and forth? (not that it currently matters since there is no end scoring in UnCiv yet)

**Comment by yairm210** [comment]
Once you have it, you shouldn't be able to receive it again, but I think everything is fine as is

**Comment by Whistler11** [comment]
No worries then!
