### ISSUE TITLE
Ships and cavalry/chariot units not healing outside my territory

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1981]
Let me picture this bug: a Caravel of mine has been damaged in battle, so I pressed its Sleep until healed button. Three turns have passed and my Caravel hasn't healed not even by a bit.

![image](https://user-images.githubusercontent.com/41149920/75045171-1a9bde80-54c3-11ea-8323-97780dd4aab0.png)
![image](https://user-images.githubusercontent.com/41149920/75045181-1d96cf00-54c3-11ea-8e06-3fa97cd362ff.png)

**Comment by JackRainy** [comment]
Are you sure, that the caravel was not attacked all those moves?
Do you have a saved file to reproduce that?

**Comment by yairm210** [comment]
Ships don't heal outside of friendly territory, as per Civ V, not a bug.
Where in-game do you think 'healing powers' of tiles should be shown?
