### ISSUE TITLE
Mongol Great General = Khan, always?

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1982]
Every time you play the Mongol Civilization, you are supposed to have your Great General replaced by a Khan. This is true on a basis, as I get them the more I fight, but there are issues. When I build the Tower of Pisa or adopt all Liberty social policies, the game allows me to choose a regular Great General, and not a Khan. This is very problematic.

**Comment by Kentalot** [comment]
Does anyone know if Civ5 allows you to choose a khan instead?  I assume so, but this probably loses priority if this behavior is the same as Civ5

**Comment by Smashfanful** [comment]
It certainly does. When I first played the Mongols in the original Civ V, I tried adopting all Liberty policies and I was able to choose the Khan
