### ISSUE TITLE
Increased amount of Strategic Resources in one source

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1983]
Many players, like me, wish to build the spaceship that should fly to Alpha Centauri, thus winning a Scientific Victory, and the Spaceship Factory contributes to this by speeding up Spaceship parts construction. Problem is, they require Aluminium, and if you run out of Aluminium, you can't build Spaceship parts unless you sell something made of Aluminium (like the Spaceship factory itself, or a Rocket Artillery). For that and similiar reasons, I think it should be required for every source of any Strategic Resource to have more of that resource, between 4 and 6. How does that sound?

**Comment by yairm210** [comment]
Nope!
That's part of the balance you need to make as a player - considering that aluminium is used for both the spaceship parts, the factory, and other units, where do I want to use this resource? Which cities do I prioritize for spaceship factories, if any?
Making all resources give more is taking that strategic choice away from the player
