### ISSUE TITLE
The cost of research agreement is inconsistent

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#1986]
This may simply be my lack of understanding of the detailed mechanics of Civ 5, but I thought that research agreements were priced at the highest level of research between 2 civs. Here is a picture of Greece rejecting and requesting a research agreement from me in the same turn:
![Screenshot_20200222-181610](https://user-images.githubusercontent.com/60082415/75088356-2c9f7f00-55a0-11ea-87dd-5d006c3109d6.png)

The cost of my original research agreement was 300:
![Screenshot_20200222-182227](https://user-images.githubusercontent.com/60082415/75088361-535db580-55a0-11ea-8b21-f6f1fec60415.png)

If this is as intended, just close immediately, but it wasn't what I expected.

**Comment by JackRainy** [comment]
Yes, it has happened to me as well.
The civilization denies my offer of Research Agreement and does the same suggestion right after it.

**Comment by Whistler11** [comment]
It could be a cost saving thing? In Civ 5 this would happen sometimes, but they would ask for gold as well to off set the cost of the research agreement. 
They're not doing it here though, and the  cost of the research agreement changed. So i was confused

**Comment by lishaoxia1985** [comment]
it's not a problem. the cost is according the era in which the request civ, if the civs in the RA are in different era, the cost should be different.

**Comment by Whistler11** [comment]
Research agreements have a gold cost that increases based upon the **highest era reached among the participants.** The costs at standard speed are:
Medieval - 250
Renaissance - 250
Industrial - 300
Modern - 350
Atomic - 400
Information - 400


This is from: https://forums.civfanatics.com/resources/research-agreements-bnw.25568/#Costs
