### ISSUE TITLE
When a carrier is destroyed, the units it was carrying persist in game

### ISSUE THREAD

**Issue by alvinsartor** [yairm210/Unciv#2000]
**Describe the bug**
When a carrier is destroyed, the units it was carrying are still in the map. They're invisible but can still be used normally.

**To Reproduce**
1. Build a carrier
2. Build an airplane
3. Put the airplane in the carrier
4. Get the carrier destroyed
5. Note: the airplane is still available and can be used.

**Expected behavior**
The carried units should be destroyed.
Alternatively, they might fly to the nearest friendly city (if there is a city on their range).

**Comment by yairm210** [comment]
Resolved in #1992
