### ISSUE TITLE
Upgrade Chariot -> Cavalry, old promotion to change?

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#2015]
![image](https://user-images.githubusercontent.com/21982451/75249183-06fbbb00-57d6-11ea-93bb-5847080892a1.png)
After I upgraded my Chariot to a Cavalry, I got a promotion with the screenshot happening. I would expect the old chariot Accuracy promotion to be changed to Shock promotion when upgrading the unit.

**Comment by yairm210** [comment]
I understand why, but this is not a bug - promotions are supposed to remain permanent
