### ISSUE TITLE
Iron is WAY too rare

### ISSUE THREAD

**Issue by mmansolf** [yairm210/Unciv#2035]
Regardless of resource density setting, it seems there's only one iron on any given map.i know they should be rare, but this rare seems a bit ridiculous... Is this intended?

**Comment by r3versi** [comment]
I noticed that the resource density parameter does not affect strategic resources. This will be fixed in #1909

**Comment by mmansolf** [comment]
Thank you!!! Happy to help, fantastic work on this game!
