### ISSUE TITLE
No victory notification when completing 4 policy trees? (French translation mistake)

### ISSUE THREAD

**Issue by NicoPL** [yairm210/Unciv#2041]
When completing 4 policy trees, I haven't got a notification saying one of my victory condition is completed. Neither right away, neither at the beginning of the next turn.
On the Victory Status in the menu, I have the 4 policy buttons colored in green.

**Comment by CaptainKlutz** [comment]
Victory is achieved only after completing 5 policy trees. You can check this by clicking the menu in the top left, then opening the 'Victory Status' screen.

**Comment by NicoPL** [comment]
Oops sorry for that, I was pretty sure it written 4...

**Comment by NicoPL** [comment]
Actually, yes, i play in French and in the French translation it's written 4 instead of 5

**Comment by CaptainKlutz** [comment]
![image](https://user-images.githubusercontent.com/38208100/75605691-1edc8300-5ae5-11ea-81f9-ad4ab7d4c0a6.png)
Hmm, what version are you on? It looks like it's fixed in latest

**Comment by NicoPL** [comment]
3.6.2 (20 February), the latest on the Play Store

![Screenshot_20200229-112043](https://user-images.githubusercontent.com/22911491/75605759-dec9d000-5ae5-11ea-8bbe-ddfdc185ef85.png)

**Comment by RobertGine** [comment]
I corrected this in my last pull request, which was added to the 3.6.3 version. The version is already rolling out, so the next update will hopefully fix the issue

**Comment by NicoPL** [comment]
Thanks a lot guys!
