### ISSUE TITLE
UnCiv tries to access my fitness data

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#2045]
**Describe the bug**
Looking through my Android's apps permission, I have found this record.
![IMG_20200301_084055](https://user-images.githubusercontent.com/27405436/75621071-b64ede00-5b98-11ea-98d6-b21ab8dba542.png)

I have no guess why would it be needed.

There is no problem to block that access (that's what I did) and it does not affect the gameplay, but I am just curious: WTF?!

**Comment by yairm210** [comment]
What the hell???
It's not in the permissions or anything else, maybe it's from a 3rd party library? Very weird
This is a problem

**Comment by yairm210** [comment]
Do you know when this started happening, so we can look at the releases in that timeframe?

**Comment by JackRainy** [comment]
I don't know exactly. However, what I can see: on Februrary, 7th, it was already happening.

**Comment by r3versi** [comment]
Can you post info about your device and os? I'm trying to understand what is fitness data. In my device I cannot find such requests from the app

**Comment by JackRainy** [comment]
Device: PRA-TL10
OS: Android 7.0
When I go to the apps permissions it is placed next to "Access list of installed apps".
![IMG_20200301_191815](https://user-images.githubusercontent.com/27405436/75630241-95ff3d80-5bf1-11ea-9a00-2f62d091d0e6.png)

**Comment by r3versi** [comment]
In my device I don't see that option. I have no clue what could cause this

**Comment by krijnsent** [comment]
> In my device I don't see that option. I have no clue what could cause this

Me neither, no special rights needed.
Android 8.0.0, Samsung S7
Unciv 3.6.3patch1

**Comment by Rolleroo** [comment]
No sign of this on OnePlus 6T, Android 10. No option to add this as a permission anywhere.

Legacy Android issue?

**Comment by JackRainy** [comment]
It seems the issue is reproducible only on my device/OS, so I will try to investigate it myself.

**Comment by JackRainy** [comment]
The investigation has shown that `onResume()` method calls `registerSensorListeners()` which has `getSensorList(Sensor.TYPE_ACCELEROMETER)` function. Within this function it enumerates all the device's sensors and I beleive it makes a call to a "fitness" sensor (have no clue what the hell is that!) which is displayed as the access try.
Since it is not within the UnCiv code, I will close the issue.
