### ISSUE TITLE
When we build a city named with Chinese character, if we change the language with English, the name of the city will disappear.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#2046]
for example, we have a city named "北京" in Chinese，then we change the game language with English, the name "北京" will disappear.

**Comment by JackRainy** [comment]
I will try to take a look at this. Also, I have an idea to translate the cities names when changing the language, which is not happening now.

**Comment by r3versi** [comment]
This is a matter we discussed a while ago on discord and never came up with a solution (mainly because we put this on hold to fix urgent bugs). 

At the moment it is possible to give cities a custom name (that is shown to all players). This is a problem if you want to support translatable city names.

In my opinion we should have two different fields: 
- a public name (not customizable, translatable) that is shown to all players except the owner
- a private custom name that is shown to the owner (in case it isn't set up just fallback to the public name)

Thoughts on this approach? You thought of something different?

Also cc @yairm210

**Comment by JackRainy** [comment]
Let's think about the motivation to set the custom name for the city.
One of the scenario: it is not translated into one's language and one does it in this way.
Another option: that's one's favorite (native?) city which is not present in the game, so one gets it here.
The third option: the player wants to mark this city as a special like "City of Science" or "City near Mount Fuji".
In 1-2 options it is an extremely low chance the user will change the language. In the third option - it is good to have the city not translated.
So in any scenarios, having the custom city name not translated should not be a stopper for doing that.

@lishaoxia1985 , do you have a saved game to try it out? I can't reproduce the problem by the moment.

**Comment by yairm210** [comment]
There isn't really any way of displaying all possible city names to everyone without loading all the various characters... which is a very heavy operation, and so in this case I like the idea of the custom names only being viewable by the owner
The ability to name cities does lend a flair of individuality and flavor of the other players when playing in multiplayer, when they can actually see it of course
However, I think the potential damage in not being able to see the city names is bigger than the potential gain - for instance in trading or in notifications, how will I know what happened if I can't differentiate the cities?
So, I think that reversi's idea is a good one

**Comment by r3versi** [comment]
I think we should take this opportunity to complete the refactor of the translation files.

Let me start from noting that currently only some of the languages have a translated `Nations.json` and that almost none of the files is coherent with the master `Nations.json`, both in content and in format: `Nations_Italian.json` have huge lists of cities, while others don't. 

In my opinion we should remove at all the various `Nations_$language.json` and move all the translated entries to the suitable `$language.properties` file.

At this point we could treat the `CityInfo.name` string as any other localized string (`.tr()` I'm looking at you!), without having to invoke special methods like in #2048.

Then here it comes the alleged `privateName` (`customName` or anything else you like). This field could be set in `CityScreen` by the city owner and would replace (only for him) any occurrance of its city name.

**Comment by yairm210** [comment]
The big question is, do we want another 400 city names in the translation files?

**Comment by yairm210** [comment]
I agree that this will solve a lot of problems

**Comment by lishaoxia1985** [comment]
@yairm210 i agree with r3versi, but it also has a problem: you can find different civ have different number of the city.

**Comment by yairm210** [comment]
The number of cities pet Civ is not really relevant, we can translate whatever exists

**Comment by lishaoxia1985** [comment]
but i think the number is large is not necessary. Can you image you build 40 cities in the mobile phone? and you have used the string "new" and "neo" as the name prefix.
