### ISSUE TITLE
Can liberate a warring captured city 

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#2052]
**Describe the bug**
When I captured Jeonju I had the option to liberate it. I did so to see what would happen. i destroyed Korea and revived them in the same action. See pics for the fun.

**To Reproduce**
I am not sure how to reproduce.

**Screenshots**
![Screenshot_20200301-162808](https://user-images.githubusercontent.com/60082415/75636794-ef10b500-5c75-11ea-8388-d60cdfa6408e.png)
Here is the original scene, You can see I got paid out, destroyed the city twice, ended the civ, but they still exist on the map.

![Screenshot_20200301-164429](https://user-images.githubusercontent.com/60082415/75636815-14052800-5c76-11ea-858a-ebb08a87ba76.png)
Here it is next round. I took it again successfully and didn't have the option to liberate. Got paid out (2g woo!) a second time. the civ was destroyed properly this time.

other interesting interactions is that Other civs looked upon me favourably for my liberation action, but the Koreans did not, even though it was their city. 
![england 1](https://user-images.githubusercontent.com/60082415/75636852-60e8fe80-5c76-11ea-8759-01ee61cf3306.png)
![Screenshot_20200301-162214](https://user-images.githubusercontent.com/60082415/75636855-621a2b80-5c76-11ea-9aa6-08c67eee868e.png)

**Comment by yairm210** [comment]
Do you have the autosave files from before? Otherwise we find it hard to fix, and can't necessarily be sure we've fixed it

**Comment by yairm210** [comment]
There's a check in the code to prevent this exact behavior, what version are you on?

**Comment by Whistler11** [comment]
I stay up to date. I'll check though.

**Comment by Whistler11** [comment]
I was on patch 3.6.3-Patch 1

here is the closest pre-event save I have. https://pastebin.com/phBhQ3Q1 
my autosaves are JUST out of the reach of the event. this one is about 40 rounds behind, and still has 2 civs I conquered there.

I'll certainly keep my eye open for this kinda stuff again.

**Comment by Whistler11** [comment]
I have not been able to recreate this bug. if it comes up again, I'll repoen. until I have more evidence, I am going to close this bug.
