### ISSUE TITLE
Years of peace, whilst being at war

### ISSUE THREAD

**Issue by Whistler11** [yairm210/Unciv#2053]
**Describe the bug**
during war I can receive a positive to diplomacy for being at peace for a long time pre-war. 

**Expected behavior**
Once I declare war on a country, I would expect to lose the peace bonus. 

Also the bonus from "a mutual military struggle..." seems a bit weird if I am killing their people. Sure, we both hate the Ottoman empire, I don't know how much weight that should have if I am the one bombing London (they aren't at war) . But I understand that it's technically right.

**Screenshots**

![Screenshot_20200301-164611](https://user-images.githubusercontent.com/60082415/75636886-c5a45900-5c76-11ea-8377-c4e5cf2561c3.png)
![Screenshot_20200301-162214](https://user-images.githubusercontent.com/60082415/75636887-c6d58600-5c76-11ea-9d9b-93f54ad60cc3.png)

**Comment by yairm210** [comment]
Not a bug!
War does not immediately make you forget the years of peace, and as you can see they start to master less and less add time goes by
