### ISSUE TITLE
Follow-up to #1924

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2056]
Currently, Mongolian Chariot Archers and Keshiks have a movement of 4 and 6 respectively. They might be because of Mongolia's Unique Ability.
However, Ranged units and Mounted units and Rangeds are mutually exclusive (for some reasn, Civ5 developers wanted it this way), and Chariot Archers & Keshiks are considered Ranged units (not Mounted units).

Therfore, Mongolian Chariot Archers and Keshiks should have a movement of 3 & 5 respectively. There should also be no bonus in producing these units through stables because they are not mounted units.

Arabian Camel Archers, Egyptian War Chariots, Indian War Elephants, etc. are also not considered mounted units but rather ranged units.

I checked to see if Camel archers work as intended and it seems they do. They are ranged units with a range of 2, can move after attacking and have a movement of 4.
Keshiks are still melee units.

**Comment by yairm210** [comment]
Please add this as a comment to 1924, we don't need 2 separate issues for the same subject :)
