### ISSUE TITLE
Science points don't carry over

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2057]
Example: A tech requires 500 points.
You have already generated 400/500 points.
A research agreement finishes and provides you 700 points.
You would finish the tech you were working for but the 600 extra points would not carry over to the next tech.
This would cause a significant loss of science points especially from Great Scientists and Research Agreements.

In Civ5, extra Science points would carry over to the next tech.
However, each usage of Great Scientist/Research Agreement would only allow you to immediately finish one tech in a turn even if the Science points generated are enough to unlock 5 turns in a row.
2 Great Scientists could allow immediately unlocking 2 techs in a turn.
The remaining Science points would carry over to the next techs allowing you to unlock a number of techs in 1 turn until a certain point where you run of Carried Over points.
You're still generating science per turn which adds to the carried over points.

It's easy to see how it works in Civ5 if you ignore the fishing techs until you have advanced a number of eras and are generating a lot of Science points and then use a Great Scientist on the fishing techs.
You'll immediately unlock the first fishing tech and then you'll unlock the rest of the fishing-related techs at a rate of 1 tech/turn.

**Comment by LeGend172** [comment]
I tried again to check if Science points carry over and it seems like I was wrong.
Science points do carry over but that only appears after a turn has passed.
When there's enough carried over Science points to finish a tech from Great Scientist/Research Agreement, the interface still shows the number of turns that will be needed to finish the tech using only Science per turn. However, the tech finshes in 1 turn, or a significant percentage of the tech is completed (e.g: "8 turns to finish the tech" changes to "3 turns to finish the tech" in only 1 turn).

**Comment by lishaoxia1985** [comment]
it's not a bug. the overflow science have a limited number which can't  ＞the basic cost of the tech which you finish and 5*per turn tech (if I don't forget).
