### ISSUE TITLE
Great Scientist doesn't disappear after creating Academy

### ISSUE THREAD

**Issue by MarcinMich** [yairm210/Unciv#2060]
As in the title. Shouldn't building Academy consume Great Scientist?

I played Babylon, acquired writing and a Great Scientist popped. Then I could move him from tile to tile and create several Academies.

**Comment by lishaoxia1985** [comment]
@MarcinMich you can see #2062 .

**Comment by Sharktornado** [comment]
Had a similar problem here except it was with an engineer creating _manufactories_ (don't know the plural haha).

**Comment by yairm210** [comment]
Resolved :)
