### ISSUE TITLE
Unlimited Landmark

### ISSUE THREAD

**Issue by Eganburg** [yairm210/Unciv#2066]
I just found out that I can create unlimited landmark with just one great artist. It didn't dissappear after I found a Landmark. 

![Screenshot_20200303_133231_com unciv app](https://user-images.githubusercontent.com/61727125/75749128-a6c7c480-5d53-11ea-89d5-c54c1cf3fdb5.jpg)

**Comment by yairm210** [comment]
Fixed in latest version :)
