### ISSUE TITLE
Game crashes when planes are upgraded when they are on carriers

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#2070]
When I tried to upgrade both great war bombers and triplanes, the game immediately crashed.

![Screenshot_2020-02-21-18-02-42](https://user-images.githubusercontent.com/61744611/75784273-ee267300-5d9c-11ea-859d-67dafdcbb7c5.png)
![Screenshot_2020-02-21-18-02-38](https://user-images.githubusercontent.com/61744611/75784282-f2529080-5d9c-11ea-976d-e09bc924ba6d.png)

I captured the crash as soon as possible, hence the unconventional look. You can see the same map from the game if you look closely.

I have the triplane on top of the carrier selected, and when I pressed the upgrade button, the game immediately crashed. Currently, I can only relocate the planes to cities and upgrade them from there, and then relocate them back to the carrier.

**Comment by yairm210** [comment]
This is a problem we solved a while back
The current version is 3.6.4, what version are you on?

**Comment by TheEXAM** [comment]
> This is a problem we solved a while back
> The current version is 3.6.4, what version are you on?

I'm currently on version 3.5.11, I'll try to update it and see if it has been fixed.

**Comment by yairm210** [comment]
Fixed?

**Comment by TheEXAM** [comment]
> Fixed?

Aye
