### ISSUE TITLE
Proposals of research agreements appear really often.

### ISSUE THREAD

**Issue by LeoBoudet** [yairm210/Unciv#2071]
Hi,
In my opinion the frequency of the research agreements propositions by the AI is too high. All the civilisations in almost every turn ask me if I'm interested in it. Is it possible to lower it a bit ?
Thanks to the devs.

Léo

**Comment by TheEXAM** [comment]
Do they still ask again in the next turn after you refused the agreement?

**Comment by LeoBoudet** [comment]
I can't refuse it, I can just click on "Not this time", and they keep asking the next turn until the end of the game (not every single turn but almost).
