### ISSUE TITLE
Add a "money reminder" next to the price of the city squares that can be purchase.

### ISSUE THREAD

**Issue by LeoBoudet** [yairm210/Unciv#2072]
Hi!
I suggest to add a simple reminder of the total of the current money next to the prices of the purchasable squares in the city panel. Just to know the remaining money that we have.
Thanks a lot!

Léo

**Comment by yairm210** [comment]
Okay, now it looks like this:
![image](https://user-images.githubusercontent.com/8366208/76152068-11666080-60c4-11ea-95c6-a8e037389374.png)
How do you imagine it looking afterwards?

**Comment by LeoBoudet** [comment]
With just the total of remaining money below. Like this:
![money-reminder](https://user-images.githubusercontent.com/32602517/76164042-c2fca480-614b-11ea-97c5-9c176456e27c.png)
