### ISSUE TITLE
Domination Victory bug

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#2074]
Still got that freaking bug that prevents me to get a Domination Victory at all. Just downloaded last version.

**Comment by Whistler11** [comment]
Is this the #2005 bug?

**Comment by yairm210** [comment]
@Whistler11 No, that's not a bug
@Smashfanful Can you send a saved game?

**Comment by Whistler11** [comment]
I got it too:
https://pastebin.com/CwCSzKbp
