### ISSUE TITLE
Unit purchasing restrictions

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#2081]
Unit purchasing in Unciv is quite unbalanced at the moment. The player can purchase multiple units with a single city and move them all in one turn, almost guaranteeing a late-game victory when nukes and tanks are available.

To remedy this, I suggest implementing the civ v mechanic which is that you can only purchase a single unit of each type (combat and non-combat) per city and per turn, and those units cannot move until the following turn (landsknechts being the exception as their ability is to start with no movement penalty).

Essentially a unit cannot be purchased inside a city where a unit of their type is already stationed, so if I have a warrior and a worker in my capitol, then I cannot buy a scout and another worker unless I move those two out of my city.

**Comment by TheEXAM** [comment]
Imagine buying units in a city with the wonders Alhambra and Brandenburg Gate, plus Barracks, Armory, and Military Academy buildings, with the Total War policy activated.
