### ISSUE TITLE
Culture Victory may not be working properly...

### ISSUE THREAD

**Issue by erinaceus73** [yairm210/Unciv#2083]
I played a deity game and had France as AI player (among others).  I had 3 policy branches complete and France had 4 - then France stayed on 4 as I completed 5 branches by 1930 on quick speed....

My guess is that sg. went wrong here and France I believe have won this just the game did not show it... I played on to the 1960s and France still has only 4 branches complete...

**Comment by yairm210** [comment]
Nope, you just overtook them
You win with 5 branches, not 4

**Comment by erinaceus73** [comment]
Yes but to me it seems not OK that France stayed on 4 for so long...

**Comment by yairm210** [comment]
It happens sometimes, what can I say

**Comment by LeGend172** [comment]
From my experience, cultural civs AI often picks Liberty as the 4th/5th Social Policy, and plants the settler they receive from Collective Rule.

The 5th city they build increases their social policy costs and doesn't provide enough culture to counter the policy cost increase.
This makes the AI finish 5 policies later than what would be expected.

You can probably help the AI win faster by intercepting their free settler.

Cultural civs usually stick to 4 cities, but whenever they have a settler, they plant it.
