### ISSUE TITLE
Maintain unit state after upgrade

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2092]
Not sure of original Civ behavior, but the following existing behavior seems odd and unnatural.

Upgrade a unit that is fortified.
End turn.
Next turn, the newly upgraded unit is no longer fortified and must be re-fortified.

I think units that are fortified, then upgraded, should remain fortified if possible (for example, if they become a unit that can no longer fortify).

**Comment by JackRainy** [comment]
I believe that the upgrade is the action like a movement (it even requires movement points!), so it makes sense that the fortification state is reset while upgrading.
I would not say this is a bug in such context.

**Comment by yairm210** [comment]
An upgraded unit is like a newly minted unit - I think that the current situation is fine.
IIRC that's how Civ V handled this as well.
