### ISSUE TITLE
Spy 

### ISSUE THREAD

**Issue by DArt497** [yairm210/Unciv#2097]
Spies, strategic units, you would send to the city of other nations or to yours, and they could steal technologies, gold or worsen the relationship of the enemy nation of the other nations of the game, or send to your nation to find enemy spies
You would send the spies to the nation's capital you want

In other nations
*They could steal gold, technologies or diminish their reputations with other nations

In your nation 
* could intercept enemy spies

It would be unlocked in military science

Apologies for possible errors, I used Google translator

D'Art

**Comment by yairm210** [comment]
Not in Vanilla, s it won't be entering the issues - this is specified explicitly when creating a new issue =)
