### ISSUE TITLE
Changes to reflect vanilla Civ5

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2101]
*- National college requires "Philosphy" rather than "Civil Service".

Source: https://civilization.fandom.com/wiki/National_College_(Civ5)

*- It becomes default that annexed cities retain their previous borders,
and Autocracy's "Police State" becomes
"+3 Happiness from every Courthouse. Build Courthouses in half the usual time."

Source:
https://forums.civfanatics.com/resources/social-policy-autocracy-vanilla.25570/- 

*- Autocracy's finisher becomes
"Adopting all Policies in the Autocracy tree will grant a 20% attack bonus to all Military Units for 30 turns." instead of
"+1 Happiness from each Walls, Castle and Arsenal".

Source:
https://forums.civfanatics.com/resources/social-policy-autocracy-vanilla.25570/

*- Missing National Wonders: 
Heroic Epic, National Epic and National Treasury. (These 3 are from vanilla civ)

There are 4 other National Wonders from G&K and BNW, but they rely on Trade routes, Religion, Espionage and Tourism (and so are not relevant for Vanilla)

Source:
https://civilization.fandom.com/wiki/List_of_wonders_in_Civ5

The afforementioned are in the last patches of vanilla Civ5, but I'm not sure if they were in the first patches of it.

These changes seem to be the most relevant imo.

Thanks a lot for the great work as always.

**Comment by JackRainy** [comment]
I will take it for a fix.

**Comment by yairm210** [comment]
This should be part of #663, as stated when opening a new issue
