### ISSUE TITLE
Flag tiles to prevent worker auto-re-assognment

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2110]
If I have a horse tile and force a worker to assign it to a Moai or Farm tile, assuming I prefer it that way, once I get to having too much to manage and automate workers, the worker will go back and make it a pasture.  In the case of a Moai being reassigned and neighboring Moai, I will lose out on bonuses.

Need a way to flag a tile so a worker will ignore it during auto building.

Secondarily an additional flag so a worker will not auto-road it may solve the double roading problem.

2 booleans a land hex, I guess.

**Comment by yairm210** [comment]
????
Please fill out the form =)

**Comment by JoshDM** [comment]
Yeah it auto submitted dude. You should know me enough by now to know I'm all about getting you the info. :-)

**Comment by Whistler11** [comment]
I am a little confused.

Are you saying that you choose a tile improvement and worker auto build over your selected improvement later on? Thus, you want a way to say "Don't change this tile"?

**Comment by JoshDM** [comment]
Yes.  I had a Moai on a horse tile. I didn't need the horse.  The Moai was next to other Moai and it provided the Moai proximity bonus.

I all 3 in use.  A worker came by and sabotaged it by overwriting my Moai with a horse.

Now, *I GET IT*, when it's not optimal, the auto worker SHOULD come by and make a uranium mine.  HOWEVER, there should embe a way to flag a hex to say "leave this alone".  

Being able to set a tile to not be touched by an auto worker would also help to manually prevent the road spider-webbing that keeps happening.

**Comment by Whistler11** [comment]
For the roads, there is an option in the menu to "not automate roads". I have found it useful sometimes. 

As for the other thing about building over prebuilt improvements... I think this is part of a large discussion. 
I feel like there should be (and is) something in the system that doesn't change player actions. e.g. when I assign population to a tile in the city screen early in the game, they will stay in the same position if I forget to micromanage it back to a better tile later on. 

I believe the same thing happens with tiles outside of cities. I haven't observed any problems with this lately.

**Comment by yairm210** [comment]
Mmm I've been debating this for a while
But I think I'll have to decline this. The use cases for this are very rare, and it would require not only adding another field that every single tiles saves, but worse - a UI change for toggling the 'lock' of such tiles.

**Comment by JoshDM** [comment]
Couldn't it piggyback on the lock in the main screen?  I have a really
great Moai placement and am going for a culture victory.  Oil is discovered
on the hex. Auto-worker treks over and places a derrick on my spot, nuking
the moai and by association all the ones around it.
