### ISSUE TITLE
City Names block Units on Android

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2113]
Requesting transparency on City Names, they block visibility of military units for selection. See attached image.
![Screenshot_20200310-104409](https://user-images.githubusercontent.com/3236760/76326381-ebf17680-62be-11ea-947a-351918626704.png)

**Comment by stoupa007** [comment]
what i thought about was some alternate display mode of city button.

it would need easy switch (eg similar like resource or working population visualization icons bottom left) and the alternative might be the smallest possible button eg only name of city (without size, production, timers, etc).

**(2|5 Memphis 3|[A])** vs **(Memphis)**

makes sense?

**Comment by Iver88** [comment]
I am for different approach. Tag is in center of city by default right now. And when clicking on tag, it is moved bottom. And tag is placed on default position when selecting another unit. I have these ideas:

1. Default tag should be above city like in another CIV games. Cities are hidden right now and top tiles are less important in most cases.
2. When clicking tag, tag moves to city position bottom and reveals resources and units below.
3. When clicking tag on city position, it moves back to his default top position.
4. City opens only when clicking on city tile
5. When unit is on city tile, and clicking on this tile, unit big icon is shown actually. So we just need another big icon before for selecting city itself.
