### ISSUE TITLE
City Bombard still shows active target after use

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2117]
Bombard a target with a city. Click city and note that the active red target is still available when the city can no longer Bombard this round.  See image.

![Screenshot_20200310-203640](https://user-images.githubusercontent.com/3236760/76371011-339fee80-630f-11ea-9051-d1b204727a76.png)

**Comment by JackRainy** [comment]
I am not sure, what is the problem here? 
I like that the info about defender (and red crosshair shows which one) is still present - it is useful to understand how much HP left in order to make next attack by units.

**Comment by yairm210** [comment]
Agree, I also don't consider this a bug

**Comment by JoshDM** [comment]
The red target reticule for a regular unit means the unit has the ability to hit that target AND has an attack available.  Once that attack is used, the reticule is not there, just a transparent red circle on the target, meaning it CAN be hit, but the attacking unit has no attacks left.

This is inconsistent behavior from a city, which once it uses the bombard for that turn and no longer has a bombard to attack with, but still shows a reticule on a target.

**Comment by JackRainy** [comment]
Ok, now I understand. You don't need to hide the target info after attack, but hide only red reticule in the name of consistency with military units.
