### ISSUE TITLE
Chichen Itza Wonder doesn't give 50% more golden age turns

### ISSUE THREAD

**Issue by DanVercetti** [yairm210/Unciv#2118]
Like the title says, but has only happened when Chichen Itza wonder is built NOT in the capital. (I built it on the second city I founded)

![Screenshot_2020-03-11-15-48-08](https://user-images.githubusercontent.com/61697783/76394707-e70cef80-63b0-11ea-9bca-5fd9ba2ad584.png)

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
It does, but only when you first create the wonder and then enter a golden age
If you experienced otherwise, do you have a save file?

**Comment by DanVercetti** [comment]
Ohh I see! I thought if the other civs build the wonder first I wouldn't be
able to build it. I have. I'll be back to send it ASAP. Also, thanks for
the speedy response man

**Comment by DanVercetti** [comment]
Sorry but I couldn't find where the unciv files are man

**Comment by DanVercetti** [comment]
[chichen iza bug save.txt](https://github.com/yairm210/Unciv/files/4316992/chichen.iza.bug.save.txt)

Nevermind. I found out how to save it. Here's the file.

**Comment by JackRainy** [comment]
What I see here, that you are playing the "Quick" game, and it means the default value for the Golden Age is 1/3 less.
Playing on "Normal" speed you would get 15 turns (10+50%) of Golden Age, however, here you get 67% of 15 = 10 turns.
There is no bug, as for me.

**Comment by DanVercetti** [comment]
Ooohhh I see! I didn't know game speed has that effect. Thanks for
clarifying!
