### ISSUE TITLE
Conquest victory doesn't work

### ISSUE THREAD

**Issue by Theperserk** [yairm210/Unciv#2119]
**Describe the bug**

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Fixed in 3.6.6, which is rolling out =)

**Comment by Theperserk** [comment]
![Screenshot_20200312-195955](https://user-images.githubusercontent.com/62062369/76419424-e4bb8d00-63d2-11ea-99c6-abf6c650e1dd.png)
