### ISSUE TITLE
Set the view on the oldest tech to research when choosing a tech to research

### ISSUE THREAD

**Issue by LeoBoudet** [yairm210/Unciv#2120]
Hi!
I propose to automatically set the view on the oldest available tech to research when we choose a tech to research in order to avoid to drag again and again all the tech tree to reach the avalaible techs.
What do you think?

Léo

**Comment by JackRainy** [comment]
I assume I did that fix for 3.5.12.
Which version do you use?

**Comment by LeoBoudet** [comment]
I use the 3.5.7 from the F-Droid repository. I will try with the most recent release.

**Comment by LeoBoudet** [comment]
Ok, I downloaded a more recent version form the Aurora store and it works as expected.
