### ISSUE TITLE
Add a tile resource summary to the construction screen

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2122]
If I am constructing on a tile with a worker, the screen like the one below shows up:

![Screenshot_20200311-131739](https://user-images.githubusercontent.com/3236760/76444848-f2552080-639a-11ea-899c-2296680702c3.png)

There should be a summary at the top of all the resources generated by that tile currently.

In fact, one might argue to have a summary at the top of what it appears to be, and for each row show exactly what it would look like post-construction, rather than just the changes, but that might be a bit much.  I am just requesting a pre-construction tile summary embedded on this screen to begin with.

**Comment by JoshDM** [comment]
Summary at top
On left of each choice, maintain the summary, but use a + or - symbol and changes number values to show change, plus the existing luxury symbols.

**Comment by JackRainy** [comment]
You have already seen this information right before you entered this screen (over the minimap).
Why do you need this information again here?

**Comment by JoshDM** [comment]
To make an informed decision.  There is plenty of whitespace; why not use it to advantage?

**Comment by rh-github-2015** [comment]
Just stealing TileInfoPane (what JK said) with a small modification and inserting it looks like this:
![image](https://user-images.githubusercontent.com/16001896/77273728-92bd1600-6cb4-11ea-806a-4a943db5ad97.png)
I'm not convinced.
Also shows a little problem - Ruleset.tileImprovements is a LinkedHashMap so the iterator follows insertion order - and mods are merged last. Roads & Removals no longer at the end. Maybe fix this in RulesetCache.getComplexRuleset? Just moving newRuleset.add(getBaseRuleset()) improves this indeed, but I don't like it. Reeks of unforeseeable side effects. Like the modded nations appearing first in their picker which might even be desirable... 

Any guru have an opinion?

**Comment by rh-github-2015** [comment]
I'll shelve my [playground branch](https://github.com/rh-github-2015/Unciv/tree/improvement-picker), I don't think that's good for inclusion. Looks like this:
![Screenshot from 2020-03-23 22-43-39](https://user-images.githubusercontent.com/16001896/77366756-fb5dce80-6d58-11ea-8a4b-0315b9498fcc.png)

**Comment by JackRainy** [comment]
Well... It does not look "super sexy" ))
Also, I foresee some troubles having small screen and long list of improvements.
I suggest to do nothing here.

**Comment by yairm210** [comment]
Hm
I think I'm fine with saying that we gave it a shot, it didn't turn out great, and we're moving on
As with all things, if later we think of a better way to do this, or we feel that it's more necessary, we can come back to it

**Comment by rh-github-2015** [comment]
Precisely.
