### ISSUE TITLE
Multiple observations not sure are bugs

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2125]
Every barbarian encampment is 37 gold reward, regardless of camp age and ability.

A Caravel floating around the ocean killing barbarian units (water and land) gains no XP.

**Comment by JackRainy** [comment]
> Every barbarian encampment is 37 gold reward, regardless of camp age and ability.

Yes, that's expected. According to the https://civilization.fandom.com/wiki/Encampment_(Civ5) :
_You get a small amount of Gold (25 in Standard speed on Prince) for each encampment you clear._ 

> A Caravel floating around the ocean killing barbarian units (water and land) gains no XP.

Yes, that's expected. If your Caravel is already experienced enough, it stops getting more XP from barbarians. Find more challenging foe :)

**Comment by JoshDM** [comment]
"A small amount" sounds like a random small amount; 37 is consistent.

The Caravel is a base Caravel fighting a Barbarian Caravel which can defeat it 1:1.  No XP awarded.

**Comment by Whistler11** [comment]
Do you have a screen shot or a save file of the caravel incidence you're talking about?

**Comment by JackRainy** [comment]
> The Caravel is a base Caravel fighting a Barbarian Caravel which can defeat it 1:1. No XP awarded.

https://civilization.fandom.com/wiki/Experience_(Civ5)
_In addition, once a single unit has accumulated 30 XP, it no longer gets any additional XP from fighting Barbarians._ I assume, that's a case.

> "A small amount" sounds like a random small amount; 37 is consistent.

No, "A small amount" is a fixed small amount depending on the game speed and some civs special abilities.

**Comment by yairm210** [comment]
Sounds like there are no real bugs here
