### ISSUE TITLE
Sort luxury resources on trade screen

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2129]
For ease of use, sort the luxury resources (or present them all in a standardized order, with 0 if you don't have it) alphabetically.

Counter arguments must logically explain the positioning of Silver and Whales on the following image.

![Screenshot_20200311-203923](https://user-images.githubusercontent.com/3236760/76476534-ad4fdf00-63d8-11ea-9019-e0b766d67ef7.png)

**Comment by krijnsent** [comment]
+1, reported this too in #1885

**Comment by JoshDM** [comment]
And that does as I mentioned - listing them all with 0 if you don't have any.
