### ISSUE TITLE
Culture output per turn skyrocketed from 55 to 2000 during Golden Age, and also, I cannot take over my opponent's cities even thouugh I reduced its health to 0 like 2 times

### ISSUE THREAD

**Issue by higakoryu** [yairm210/UnCiv#213]

**Comment by yairm210** [comment]
About the culture output - please send me the game info (menu - save game - copy game info - paste into an email to  yairm210@hotmail.com)
Taking over cities is done by entering a melee unit into the city - but you're right that there isn't a tutorial explaining this, I'll add one!

**Comment by yairm210** [comment]
Didn't get an email from you so I assume that either you lost interest (acceptable...) or this was solved, so I'm closing this
