### ISSUE TITLE
Map generation - max vegetation = no coal

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#2132]
Just tried 3.6.7, the map editor has made another leap forwards, great work! @r3versi 👍 

One bug & one request:
-bug: try setting the "Vegetation richness" to max, that means that there will be no coal, gold and silver in the game... (Found that out in the industrial era in a game and do see the same in the current editor.) This is caused because those resources are only placed on suitable spots and spots with forest on them are unsuitable. I'd solve this by ignoring the forest/vegetation when placing the resources and removing the vegetation if you place e.g. gold on a hill with forest.
-can the "new map" settings please be remembered? Both the 5 main settings and the list of advanced settings?

**Comment by yairm210** [comment]
New map settings are already remembered, is there something specific that's not transferring?

**Comment by krijnsent** [comment]
Sorry, should have been clearer: it's about the map editor. If you start the map editor, change settings and after that click on "new map", the previous settings are lost (map type, etc.).

**Comment by yairm210** [comment]
Solved =)
