### ISSUE TITLE
Apk binaries are missing from the new releases

### ISSUE THREAD

**Issue by MGislv** [yairm210/Unciv#2134]

**Comment by yairm210** [comment]
A *lot* of users were unable to use the APKs, and we were getting questions about it all the time, so at figured it doesn't work.
Did it work for you?

**Comment by MGislv** [comment]
I actually never tried them. I was looking for a way to get the latest release without compiling it myself (since my PC has a dual core and 2g ram).

**Comment by yairm210** [comment]
Unfortunately I don't know a way to get it on your phone without compiling =/
