### ISSUE TITLE
Civilopedia - add Diplomacy/Trade section

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2135]
There is a section missing from Civilopedia explaining Trade and Diplomacy and how Resource Agreements work.  I noticed this after needing to look up Resource Agreements because I never see my science value increase after an agreement, and I have the Wonder that enhances that effect.

**Comment by l3sy** [comment]
Yes, also some other articles of the general gameplay explanation would be very nice for new players.
- How does combat work, melee and ranged
- How do your units get experience - even after several games I'm still not sure I know if a fight will generate experience and how much
- Pillaging improvements
- Automatic city expansion - how is it coded and how can it be manipulated (improving tiles you want to acquire)

**Comment by JoshDM** [comment]
Combat not "combar"
