### ISSUE TITLE
Tap a worker to find out what they are constructing

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2136]
Currently you cannot find out what a worker is doing until they are done doing it.

Should be able to tap a worker to find out what they are in the middle of building - can use the bottom right unit summary box.

**Comment by MarcinMich** [comment]
You can, though it's not intuitive - in the right bottom corner where the information about the tile is it says e.g. "farm in 2 turns" or something similar.

**Comment by yairm210** [comment]
Yeah, this exists...
If there's something you think could be done better, you can write it here, but I consider this closed
