### ISSUE TITLE
Default slider setting spawn too many strategic resources

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/Unciv#2138]
As of 3.6.6 the default sliders result in far too many strategic resources. 

![Screenshot_20200312-222921_UnCiv](https://user-images.githubusercontent.com/49125947/76587470-fc1d7780-64b1-11ea-903f-bc560d0739f1.jpg)

<Details>
<Summary> example </summary>
H4sIAAAAAAAAAO1c23LbOBL9FdU+kynxLvHNca5b48Rleza7NZUHiIJtVihSS1JJNC7/+wIkyG4SoNjyTO3D7sxUzdASLo3G6QsOmnpK0u9plv7O6rTIq/i3J/H3J7bj8WtWbliZsryy+M99VpR8e5dmXDb5GduOdRT/cZ8t8Ycnn1fNo+3K5xA+blvY8rl9bDp67afyWT4e47ZHKP52oIMaUz62T3LwsGmvprDRaD48IiHagdbNc9DI3PaPoGGEGjrLvqWDFgStB41xEx8J5LZz+O3/8IrCXtQlaMOFrurRh9X7avXH2O+1gRcPmoHv1TSj75UgPkyJBYcRHNCYjZ99eJaPa7T4oF1pAP0bRR7jAGSK0IhKze2Q3R+olddrWg4fgLABHgQrFq0CwxJ/7IEsSFUOyAwgXPZPreo9JC5sYdhjRa0t6FYwhDjajhCW4oFoXj/dGi0JrxXUgpWMp10hEaNeMMAQjAADQLslGgmMBW+xC+BRuF4h+QA56ksXdQUIYiF9tFQPTY9BBNpaQWu0jx60Rfbng6hoBCQRQv+6FRevFCCOdyDAAAPjVchHn+B9C/qNBVWHSAddb+xIxB9frYci2/L84kG426eqlr73A9vv05xXVewvhTIeSs7qa17sMx4/NX+85zkvWXZdpHldxcGqa1JWRa4+fHp+tvZFliapHPfZqsRDnvB/pImY4ig/qXnyGD/J/1Y3vOKsTB75Nv7tXZY+PNbW24wndVnkaVJZn/e1/N9tzdlucV384KV1kRSHqvn0stht5GORW1dpnuYP1i0TQUb8/+32kDShxrqQY5dH6/JQlkKKo/WaZVna9n9/yPfFj60Y8x0vaxmexOMVr1m2uGSiiRwoKfJi106WV3V5SPpRUyF/fSi5dVHLFou7Ry6WJ8bPv8meQrg9qyrrhu8zlnC2yfjimpV1ZX0oyopvWPJtcZNuVdONUPp2cVHuxESPfCcEFEN9zLdieSI4doHTei3U8jtffCnKZo5bqdk6vYfZrx/TrKiK/eOxEeBQi40RysnSmpXHxW27E9Z1KTZKDLC4LsVWW1esFnMypZM021bW67TIioejdVMk37iU5YqJFedSk2/zB/HASymA1APjbdN228Su10frzTFnO6Eg64ZtWWldF3Utu148iO8PWaO1j2Ip/UJu0vtm3+QqmsE+se/pQ7vmG7GnZcG21qdDkgmsLN6lVSW/uGQZz+XwYpK0kFvVdL1iAopiMoEZngmFHCu5rruyQbZQ9mP6nWXiezHX4sujbHORpzux5x8O1YblW/HVlzJtdv9SJi2LW15+T4XWGmRkh1Kqhd+X6YMwhEbC64y1gLqoJG6LndwHVu7Eth/E5yyrvj5b31v4X7GciY6NkYgkqE55mw3VRwwwYTcbsRH1a7kbQhLR5ppJGFnvSzFAefxqJQ2ga9wr/iXdlOJLK82vy+JB7u1oUNUgFrHr2ZKT3tassViZfIkcTA7ypHbotnEI0s3dF4dcSiHUIfK1zTETa063ccL9DfdC1/ZXm8D2l0vfXntRaCdOGGy9KNrcc25lRWuIce+NhDfN28yvHWlf7A+ZanNfFFs1r4e/8KxqzxNpCJVyMDUkif7Yt2Of7+qxAKUmelxQzyFyscqHfrV+CLQO0lPcQ5tB9BB92i2+lE5SLMqxIO9tV79NRdIrkCL8orCIfx+KVKxPfSiwc1VshXkLI46f/iWwX32+v+YCBrETvBLSQTu5j4cqbr60CmHO5aWaqBv1+dmQYPvDQIeUApFG5TmNSlDM86At0nH7aTQISj5SKVYQTOxqGwYi2BHaitUwgQr0zYqgRQBzY1gEQ5Fw9IU8Bi0JNLF6Rpk2RhHqEfZKQMlwE3IhSRjE4eZ5BTKtQFSY3YbpHQ3EMGWrCZwTqoxjPUx5UNoNaZhuBVEv1QoUtRorG6nVg48hVXPQElACM8irnX4hCArOTG6LgbkE4ZAq0Fkw7NfhoXVgtQHwQBokOpoXtIN0hnJbF9SAUkd0MsGHlKhvoeXJEd7NJegazREgFK5HCergtKKwi1JjB/SAktbViVwXnppey14jq1657ZkU7AhNMnDFDigb5/DrfsgOov3Re3BOwIm0g7WFDrkYpKgJYAIOfCfzauikNqGVppt2DZvkdrAGdGMewkP7gE5oIWAQmQQiOgD7CE0jbgOzGqh7CLqGkYA9gTM+PrsgLsMb74SL/lii0QC7GvMRId3hM7hSoAf6D0BaG/VENAniVvCwA8k71a9HRo0+RluHSJQppsJ2hpKHgGl0rMcwhtHGfE3bGJ6Qg2klwQESnUYR2QXMwAqUjvyfjSOERqRgkgTzIpGFIxS2HQTKCNaIIwAERLSniqDAB1owuPZEGkA/mBoFT427AIZlmHchJhDlfjjvwJRAiLCEiTagayD8tlbSGRuK2IhGcRCLMOBUEEuCPwZ2BJ5sIE9aSINOxzTLgIhp4Y+tQ+NV1qjFeoBZlMigII4EQlah8Ro4c+74kmE75FSxN4Stbtsiv4BmggHsTtSuA0hmj2W3cUYYIojCLmBnjFMe5IYH9gEgRYoJoGOoeJR47ZzkUxwvnOdTHH+KT8nYkZd3xz2PPxx2LEcESzvRZXtoiz1/mnBRn3++/0WcV1d3h1Iy8YEVWgH8+7VpW33sT5Dx0604umSZOM0L+aJlO9hfvM1fvM3/A2/Tgv2u6OAe/wbWYAkzktt0U2yKZpirYiNO1os7ljR/fmJ5Ibvn7fokiNJEokkt7d1BKnRxJ5r8l/ghuW3CVCbpofb72KWzQ96QHerIBkkPMW+9du/Dre2uN77ts01gs83Ksd0g2XgrFi43gTugh9QVR0MOfc6LQmDkgU3RQyLoEvkhuDmBVKG7c8FcOUTYcNBjfFcUNU8CGcJ/XiT/PqSNOBo5NMxLBl1P0EK9AhEvpKiiP5cWUoMaWSFMzyDWBtM+4TAG43O0j8KuTtuY6R4z5QQfmi95VwPF4nCPUzycBgb9Tp9kgxCfg3ghAxsEzA3OpuBgrDM9E8TNaiwpOuqhGzDtmrVnlgaJKd4ldG2tsVVTd7BzdBEQPJgOGty5YuZnTBOhxeHm+Focp2YaqzS4mMVc0vheFiflQLTppA8mg4A3QhwUGgwzT4hZwiwU4rFgPuCQcC/4dHghjLJgRTcB6RON9AMHOKQpE2+ECSfMHAH5hBmpZa9vREkNeapOfUbSaw37hZgpIIXQNe4KlIWu7HWCCtFSQDvhi9tpMopMQZ0iwEDA8bXv5AXvi7isRvfIA5zipBDthZgujakamaZOjhkZMcypoTm7G+Rumz20zfNU2CAW4MoRRE+hshqIye14BsrKzHjh6h5cMXQep9YNNq4aegFBdhzzZEPKCz5tdq9FL7bWTpE65aVRaWbiDRciQQvEiGECrWPHfp5DpXVjIH5T49OGxNmYuTJRYGayy0i1AUNmLnpC82jFVJics0eygbfAJV+4ymK6ZqlTiimT1LgzoNQGjAPe424Ljewc0Gs2+ArsqhAjpxFww1wZ76LOxSFeDdJpOqvWrQtz0uA7zByfkYkz035n8nMjqq5zuCYmbpJ/gwPEeBKkj6C3rReQdpi1AhYME18dgQfQHzJx5xNxiGKbJwIRNQdcWycB7gA5Dd4LncmLQHsTnF44NHi0QNiVsB8LRwnor/N9NnQb8X2oMs8eMIKKBnTc5Uke0HMCAg8YGHlAceSVT++K8hP/Wb9H/eLV8nmaE/TO5ARDa/CvgRMcUh2xE7l/8YJ/8YL/z7zg0CKMhF5Pyl03bD6qAbq/b/R4jN/u9rwsSuuB7fjHbbzlTiKLqWwehlvbT6LEXgXh0vZD1wmY461WwaZpK5Ao/ls3jNDEcLd7Lozy7T5N1G1CQyw+FhXPcWHX+KZBuDgheFVL9jJ/eFuyuOUtu/XJlmKkT0I1wg9Zrc8RD4Bl642wp7xR7deWmLti+/hpx/ZY6l1xyGvWUJMbtpEIF1Hj1XLd/uNbAtnFoUz4TZo8No4Uf1nJpTnByl9GS8fxPC+yqkcmlnAjMMzyh0MmYFUJfxDfpflRbJ7UC5PLePuzLvmOqxHddsCVaFGWQph3vGmE5uxb/GCizUhYv/0yalf5i7B6oeINq/hdO1z8WTgOeXdTpR3p6bR0ltDyTLuW6Jlv1+at8+1U4jLbUOX+s+0UhTLbTpFBs+0UXzfbTsXk2XYqw5ttpw6Ns+3UGX9e0Sp5n2nYnrtmR+vfiKEBhtLOIQJrSQPWmoirFRFXERFXIRFXARFXPhFXHhFXLhFXDglXJEwhpnS+pXsWsAgb4jhEAC5NALwsRAzWgCWS3C4OxCJteJzttCKiMSKiMTSiUZ+3u2Lopf3yKLKbarafb0Sn3s4zolNv5xrRqbfrLhp6eT+n2TwEJ2C6U/npr3laywvDJue5Kr7LOFsL1TxyltWPseu3d32XrCxTkakXP/ImKepfCNyXxa5QV5P/vI795r0SDdwUM3CpZuA4RHAvTeA2g1abVqR/qVzeCKcY3M2ZYh4uERHeoRHeE7DVlv8hzTIdpf6cuFq3jhbpu/1asjw97ObV07G3fU8h+hifhm7ddUbf7c2RV6PcLhanaV7VM6qh+W6b5rwR2z/f0jsLuoQAqC4XSNDVIHOlsnQNvBSQRyOQm7dflyQ0onwCvZrIZvR6SA55dJ2X3huD/iI7iHMNGb7B8xh5fz/kDxkfdX9fsqrKxLlVR3I4Z3Ha1CP4T0isa9LW4oEh2k7BmoJ/j4p/dQ1JSjsJoF6ZQK0hRBHrpwCi9QlH4DZ4KK1Pd6vTd7p95HxPMTnfCPUp1Hqn5XrDK14a8gb/ZD5wAqg61I1O1gTX8LTap6BKSMBtagbe3e/NN/TPQjEhrVubwG5GsQZ2835EJMCHI8BPOArzFKo84OXOzTf690bIdCeSQJU49pnhgucJ2+3lhzO5pmvt2F5+ddEWwD0lmRAgTordq0OepN9fZcVDmrwSjV6xpsWr21oSoW1zq/1MgrdO748LVxWn3SbFoT6dro5S1a5+qVfwe74bO+8pK/Q01X5mVTrR+7Q6nFb+j/k9yyUJ3C6hrzkb5dvOyhIQ2PDy8/01fOPgZr9diqHLxcevo/V25RMEwU1OIDjtr4wesSvGmXcY3S34GWcdKCYgOgXNe5htXXMJZgNRRWYjbV6xUovJ004Ax4AvaU6zzNDkPaa9gDNUKsklGNMzzaWazxIElzVxJCachRzjWcgE15clhX0dzjgfftEBBUpciFCmREyfivnAiHkzUNbtzepZyZV6//SUU5hGPt6eS1bXxKikiicpm2FM7Nwzk0F/ZEDm05HREJZnqtMdG49BvgmDmDUcGj/WlfIRUY33/pqzMpunRmwqRWabbwYMDQOjOUweibW5jS0jUxj4hX3jlYZGTV1ts2HMV+RaFP4pqc/fdiLA3xWLwAr+9mzMHvp7Q5Q8mNKGUYYQmFJYo024c6des/l6I3M6w/JdY0JLD7ddIQol/BnMhxCbbHNwmjr0UOzMMzLP2o70RVsv8ot9ediZZ7yu1uxEyqabTPt6ADlMhKeTF/r2h6NgZXbk01mUnukZkaMv2CfZlDeyqXeHksaJGsOIDnNjX11Y4z01KGXo1M45tgTzp5YLWWf0OD62jGKi0decOHpQzNYlXh91pZM0a8Rge8N5+UdsM/zz8tHQGFenDRC7hdt9muhUPdEOQlPw1ZsFtMjrT0fesVkRORl3ZIFEb2O2IY03Mc+5nKcnzR27WlHCgaarD/3jZ8Cu0NXUrv0lUZa3nuHPSHIuDrV8XY6rBEe9JTmd3gixEC+FyiKvxLnaYJ+m82Hz+mB1V3xEBFdAcjbmAgZdheHYnG/T7NtLbTki5shtjS05TEYvjR4BzcR9mol7JhOftl2imTsjMzfnAWNpDBZtYAa71xPmeAczhFzihVr3iibNUfT3agXbqhdPb1StJ22AwBj0JhqH48hHvDLvXhCdbaheajh1AwaiDZ2STkM3jqUp2F6oiu1TWYzhrDTOmc/SMkm6Wy4PSOWMXJiQvxYqk5WgY4ubvaecPrERCVF3TOuQLrUcI6Nzgk3HVjl7DJ2y0pmLRFM38wHUJKjZvj2qfZuvEU+Z58xV4ilj9U8rYqJrNLbzP3Q2619FJ4xgLqMhMPvByHPoh1Vz4RcxV/ZGJnZZ1DVRm+7oaPqa5eJfWp5thJqx5sQ0N5lLnTIj92WG+7N/RR6V4okBCP3GzKo5fpt6dm8Hv6DwwlzDMnW6ImYi/Rv4Z5fedO/3z5pGQDMNn54feqOod85pdBr9WuCfzt1IscgA/ykEe38kXaPUethjzvN9kY2TAlM3442bqWFgjCtmoaklh7a5wHsKioRSoO7nK0iYpVRv+DRseyZsm+8fiZ5e/ToEBfGGe8ngdLxVPf5HKiy6X2k4v7a0e6f5zNrS7ndoXsa1jS/7aOV8P/sf/DizdrH/WYSTlWZTxukOgqehjt1gg9TXgbrfBiEZIcVYPZOxml/HIBirQzVWsqGeYNmIFaLTQYIUijzjKehdVhTbxb6BDjFkuPPxbArBxMuxKSTPEJmmbtHYAKh0AfU9pe7XT+Ybdj/JQ4M8ofLbI5qGS4tjDjVHG+Zn55wlplKkcB5SUxn+LBU0ZQunq1ynwI8Dxq04flGgGxgjxlnIny8QmQI/gSycQj/l9THqa6L9LxPRUE2Y2iWi36GgnxQUbGNUmLju0w4cUzjEAL49PDD9Gm/aRRurP7VMisI1dj/hcS5lFZC5tSlozxJsE+mJcybTon5mjAhp0ju5SzL4qXUb6mfJaOCnvBxEMhJS5mQb48NE6QnFSjyTlUyQlYQaevWTjjQGhXLuNJbQT6S8VFdJeneX+op+/9NjNLhQ3sklwYrmd22j453AC/X1DGr1KqUc1lgHYGhnLMEztItMuJrACzWxJLsh0oaYr/RNLc3F0hPAorw3SwIgzafZNKf2s/uZRRqyqCX+FAQab6knkEVBYEREoPH9oAlkkXM2siMiQbC7gv763FZCyB+u/w+DpyBmJXYAAA==
</Details>

**Comment by yairm210** [comment]
Fixed in 3.6.7
