### ISSUE TITLE
Translation announcement - can now translate tutorials!

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#214]
Using the issue board as a place for non-issues feels a bit iffy to me as well, but there's no better centralized place to do so.
I'm adding in a language picker screen for new players, and in doing so I found out that there's one place which is inherently impossible to translate in the current format - the tutorials.
So!
Within the json files, tutorials in now Tutorials_English
For every language you want, you can create a corresponding file e.g. Tutorials_Russian
While no such file exists, or the user was supposed to get a tutorial but it doesn't exist in that language, they will default to the English tutorial (which definitely exists), so there's no rush in translating the tutorials

**Comment by faantion** [comment]
Hello,
For now just keep adding text to translate. As soon i have time i will
translate.
Yesterday i translated most things there were. In comments you'll see some
words that i wasnt able to translate as i don't know the word or in the
translated language it could result as a synonym of an alredy translated
word.

What is there left to translate but tutorials?

Il sabato 4 agosto 2018, yairm210 <notifications@github.com> ha scritto:

**Comment by yairm210** [comment]
Okay I was wrong, we were missing all policy names and descriptions.
Also added "era" to era translations so they can be translated as each language needs =)
