### ISSUE TITLE
No desert hills are generated in the maps

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2145]
That's mostly irrelevant until Petra is in the game.

**Comment by yairm210** [comment]
@r3versi

**Comment by r3versi** [comment]
Well, in our implementation desert and hills are both base terrains, so you won't ever have the two on the same tile. I'd need some reference to see if this must be patched. What does Petra require?

**Comment by yairm210** [comment]
Oh D'Oh
Obviously, you're right

**Comment by LeGend172** [comment]
https://civilization.fandom.com/wiki/Desert_(Civ5)

Farms can be built on desert tiles, and hills in deserts still provide a yield of 2  Production. Combined with the effect of the Petra, this yields a whopping +3 Production and +1  Food, creating one of the most potent terrains in the game.

**Comment by yairm210** [comment]
I see
If that's all it is, I don't see a good reason to change from the current format.
