### ISSUE TITLE
Multiple trades/Research agreements can be done in the same turn if you can afford the costliest of them, even if not all of them

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2146]
If a research agreement costs 300 gold and you only have 350 gold, it's possible to make 3 trade agreements in the same turn if 3 AI civs offer you research agreements in the same turn.

I often see the AI civs in large amounts of negative gold, like -1000 or -10000 gold, so I'm tempted to believe the AI abuses something that allows them to purchase things with more gold than they currently have.

It's also possible to offer multiple AIs gold for a research agreement or 500/600 gold to war another civ if you have enough gold to afford each individual trade but less gold to afford all the trades. and then go -ve gold next turn. Allowing trades to be done in the same turn is one possible solution for this.

**Comment by JoshDM** [comment]
I think this is related to the argument behind #2111
