### ISSUE TITLE
Ability to change the names of units, similar to how you can rename cities

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2147]

**Comment by yairm210** [comment]
Was this available in Civ V?

**Comment by LeGend172** [comment]
Yes

**Comment by LeGend172** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT1lkRlLVcYtepSWdcOuxTX9634gLR76xi7Wz6speCaS9Dlc4fB

**Comment by yairm210** [comment]
So that should be in #663 then
