### ISSUE TITLE
Features to know more about the gameplan and performance of the other civs in a game.

### ISSUE THREAD

**Issue by LeGend172** [yairm210/Unciv#2148]
- The abililty to see what social policies where adopted by the other civs in a game.

https://forums.civfanatics.com/threads/where-can-i-see-what-social-policies-other-civs-have-picked.468823/

- Ranking of players by science per turn

This is a better representative of how far a civ is advanced science-wise than the number of technologies.
For example, civA is 2 techs behind civB, but it's producing significantly more science per turn than civB. CivA will mange to eventually beat civB in techs despite the fact that civB is ranked higher in no. of techs.

I know that science per turn changes gradually, but seeing how far you are behind a certain civ in science per turn tells you that you need to do something about it, like build a new city if there's place, conquer a neighbouring civ, build science buildings. etc. or simply attack the civ that's leading in science.

That's not present in Civ, even with the expansions, but was available through certain mods, like InfoAddict.

- Rating based on Culture/turn is less relevant imo, but could be helpful if someone is pursuing a cultural victory.

**Comment by yairm210** [comment]
1. is something I'm against. not something I think each civ should see about the others
2. I'm not sure, let's poll it
3. I think it's irrelevant

In general, closing this

**Comment by LeGend172** [comment]
2. I don't think it has to be one or the other.
I was advocating to see how civs compare in science/turn as well as no. of techs.
