### ISSUE TITLE
Land resources transparent on military units but it transparent for settlers

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2149]
This seems inconsistent. I understand the importance of resources for settlers units but sometimes it is tough to see items when they go transparent for military units.  I understand why this is inconsistent between the two unit types, but I think it is a disservice to the user.

See same view comparisons below

Settlers see Bananas
![Screenshot_20200313-210911](https://user-images.githubusercontent.com/3236760/76671878-4ca6da80-656f-11ea-82ad-72fc4ff4cba1.png)

Warrior no Bananas today
![Screenshot_20200313-210906](https://user-images.githubusercontent.com/3236760/76671891-61836e00-656f-11ea-8c9d-6ca0a4987837.png)

**Comment by yairm210** [comment]
I added this feature because it made it much easier for me to play.
I'll make a poll for this in the Discord

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/76708829-89efa180-6702-11ea-8c97-a69bd9146db1.png)

The people have (surprisingly) unanimously spoken
