### ISSUE TITLE
Civilopedia Improvements: Strategic Resources and Cultural Buildings

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2150]
Two different items reference classifications that do not exist:

Cultural Buildings are referenced in Cultural Policies, but there is no definitive list in the Civilopedia of Cultural Buildings. Certainly they are buildings that give +x Culture, but a list somewhere would be good, or a note on each individual building page.

Same goes with Strategic Resources, which are referenced by Russia. What Resource qualifies as a Strategic Resource?

These references are too vague to not be defined explicitly in Civilopedia.

**Comment by yairm210** [comment]
Agree that resources should have what kind of resource they are.
But as for Cultural buildings, I think that's very niche
