### ISSUE TITLE
Cant scroll in diplomacy menu

### ISSUE THREAD

**Issue by Filius-Patris** [yairm210/UnCiv#216]
When you have more than 3 opponents, you need to be able to scroll the menu on the left side in the diplomacy menu. I couldn't. Tested on Samsung SM-T230, Android 4.4.2 (I know, not the newest...)

**Comment by yairm210** [comment]
Good point!!!
Will be dealt with in the next version!

Monday, 06 August 2018, 01:11p.m. +03:00 from Filius-Patris notifications@github.com<mailto:notifications@github.com>:


When you have more than 3 opponents, you need to be able to scroll the menu on the left side in the diplomacy menu. I couldn't. Tested on Samsung SM-T230, Android 4.4.2 (I know, not the newest...)

**Comment by Filius-Patris** [comment]
LOL, you tried to thank me? Thanks a lot, but you failed!
_Left side of diplomacy screen now scrolls (thanks
No longer get notifications for units of other friendly civs around your territory
..._
No matter to be sorry, I'm fine with that, but it's just funny.

**Comment by yairm210** [comment]
0-0
Welp

Friday, 10 August 2018, 08:12pm +03:00 from Filius-Patris notifications@github.com<mailto:notifications@github.com>:


LOL, you tried to thank me? Thanks a lot, but you failed!
Left side of diplomacy screen now scrolls (thanks
No longer get notifications for units of other friendly civs around your territory
...
No matter to be sorry, I'm fine with that, but it's just funny.
