### ISSUE TITLE
World screen unit promotion sorting

### ISSUE THREAD

**Issue by rh-github-2015** [yairm210/Unciv#2160]
"I'm always frustrated when [...]" -> not really. But the order of promotion icons on a unit's world screen box is determined by a dictionary and not consistent - or transparent to a user.

Alphabetic ordering is a simple sortedBy{}, but the following causes same ordering as the promotion picker uses:

```
diff-b H:\Work\UnCiv.original\core\src\com\unciv\ui\worldscreen\unit\UnitTable.kt H:\Work\UnCiv\core\src\com\unciv\ui\worldscreen\unit\UnitTable.kt
170,171c170,172
<             for(promotion in selectedUnit!!.promotions.promotions)
<                 promotionsTable.add(ImageGetter.getPromotionIcon(promotion))
---
>             val promotionsForUnit = selectedUnit!!.civInfo.gameInfo.ruleSet.unitPromotions.values.filter { selectedUnit!!.promotions.promotions.contains(it.name) }
>             for(promotion in promotionsForUnit)
>                 promotionsTable.add(ImageGetter.getPromotionIcon(promotion.name))
```

![image](https://user-images.githubusercontent.com/16001896/76702055-fea4ea80-66c6-11ea-8e2f-9492acbe5324.png)

**Comment by JackRainy** [comment]
Wow) I never look at these icons, usually I have 1-5 of them, and I always know what are they.

**Comment by rh-github-2015** [comment]
@JackRainy  The example was of course cheated to test this, but even with five it can get distracting when different units with the exact same promotions show theirs differently. Gets more obvious with my overview->units->promotions column mod...
