### ISSUE TITLE
Can queue multiple perpetual builds 

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2175]
Should not be able to queue more than one of the same perpetual focus build (science) simultaneously.

See all the science on the top left of this image.

![Screenshot_20200317-092644](https://user-images.githubusercontent.com/3236760/76880549-325e4c80-684e-11ea-90dc-8d1083910a51.png)

**Comment by rh-github-2015** [comment]
... and Produce Gold should auto-replace Produce Science, one should be able to queue three boosters then no more, a wonder in the top slot blocks it from other cities but in the queue it doesn't and so on. Yes I know, I have that in my notes, too. Not really a game breaker, but I mainly haven't looked at the code yet cuz I got the impression someone is already working on that general area ...

**Comment by JoshDM** [comment]
There also needs to be a note in the Civilopedia about what exactly needs to be built for the launch.  I couldn't figure out why the cities kept trying to build boosters.

I would almost suggest treating the spaceship parts as 6 individual Wonders.

**Comment by rh-github-2015** [comment]
The 'exactly' in the 'victory status' screen is not enough?
