### ISSUE TITLE
Automated Worker railroad placement prefers to avoid replacing roads

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2176]
When pathing from city to city to create railroads, if there are multiple paths to the target city, from the current position, if one hex has a road and the other does not, the Worker AI will choose to build a railroad on the hex that does not have a road.  This takes longer (replacing a road is faster) and costs more (paying for the new railroad and the pre-existing road).

If there is only one hex with a road and no other choices (for example, the other hexes are impassable), the AI will build the railroad over the road hex.

**Comment by yairm210** [comment]
This is not true. In fact, they completely ignore all roads and railroads - that's another problem, see #1734
