### ISSUE TITLE
The problem of collapse when the number of rounds reaches a high level

### ISSUE THREAD

**Issue by tianshidoubi** [yairm210/Unciv#2196]
**Describe the bug**
In my UnCiv, when I play 456 rounds, pressing the next round button will cause the game to crash. My friend is in the same situation - but he collapsed in 568 rounds. What's the problem?

**Comment by yairm210** [comment]
We'll need a save file to figure this out

**Comment by tianshidoubi** [comment]
> We'll need a save file to figure this out

Wouldn't auto-save be possible？

**Comment by yairm210** [comment]
Yes, you can take the file you have from your autosave =)
Menu - save game - copy to clipboard - paste here

**Comment by tianshidoubi** [comment]
> Yes, you can take the file you have from your autosave =)
> Menu - save game - copy to clipboard - paste here

OK,thanks.I have always supported unciv.

**Comment by yairm210** [comment]
?? Why did you close this?
If there's a crashing problem, I want to know about it =/

**Comment by tianshidoubi** [comment]
> ?? Why did you close this?
> If there's a crashing problem, I want to know about it =/

Oh,so sorry,My friend and I don't have it on file now
[I am working hard on my English and execuse me should some misunderstanings exsit ]

**Comment by yairm210** [comment]
Hm
Okay, when you encounter this again I'd be glad for a save file =)
