### ISSUE TITLE
Missing features of Tech Tree

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#2199]
I have compiled all missing or inconsistent entries in the tech tree based from the G&K tech tree . 

I have included annotations inside the parenthesis which shows why the feature/unit/building might not yet  be implemented in the current game which includes the following:

1. (G&K) - The feature was first implemented in Gods and Kings version thus not yet a priority.

2. (Religion) - The feature requires Religion mechanics to be first present for it to be implemented

3. (River) - The feature requires to have the river present first before it can be implemented.

4. (Inca) - The feature requires to have the Incan civilization to be present first before it can be implemented.

5. (Denmark) - The feature requires to have the Danish civilization to be present first before it can be implemented.

6. (Desert Hill) - The feature requires to have desert hills be present so that it can be fully implemented.

7. (Espionage) - The feature requires the Espionage mechanic to be present for it to be implemented.

8. (Tech) - The technology where this feature is included is not yet present in the current Tech. Tree.

9. If no parenthetical annotation is present then that item can be worked on if desired.

The following annotations show how the change can be implemented:

1. [Add] - The feature is missing and can be included to this technology.

2. [Move from] - The feature is implemented but it is in the wrong technology. It should be transferred in this technology.

3. [Move to] - The feature is in the wrong technology and should be moved to another.

4. [Split] - The feature is combined and can be separated into 2 or more distinct things. One or more of the feature should be transferred to another technology.

5. [Remove] - The feature should not exist in this technology and should be deleted.

6. [Retain] - After splitting, the feature should remain in this technology.

---------------------------------------------------------
Ancient Era

1. Agriculture
remove Fallout [Remove]
* Remove Fallout is an innate ability of workers and is not affected by any technology.

2. Pottery
Shrine (G&K; Religion) [Add]

3. Archery
Temple of Artemis [Add]

4. Writing
Embassy (G&K) [Add]

5. The Wheel
Water Mill (River) [Add]

6. Masonry
remove Marsh [Move from 7]
Mausoleum of Halicarnassus [Add]

7. Bronze Working
remove Marsh [Move to 6]
Statue of Zeus [Add]

Classical Era

8. Construction
Composite Bowman (G&K) [Add]
Terrace Farm (Inca) [Add]

9. Drama and Poetry (not in tech tree)
National Epic (Tech) [Add]
Amphitheatre (G&K;Tech) [Add]
*replacement of temple as culture building once Religion is implemented

10.Currency
Petra (G&K; Desert Hill) [Add]

11. Engineering
Fort [Add]
Bridge over rivers (River) [Add]

12. Iron Working
Heroic Epic [Add]

Medieval Era

13. Theology
Garden (River) [Add]
Great Mosque of Djenne (G&K; Religion) [Add]

14. Civil Service
+1 Food on farm tiles with freshwater (River) [Move from 25.B]

15. Guilds
National Treasury [Add]
Polder (G&K; Denmark) [Add]

16. Education
Angkor Wat [Move from 17]

17. Chivalry
Angkor Wat [Move to 16]
Defensive Pact Treaties [Add]

Renaissance Era

18. Banking
Constabulary (G&K; Espionage) [Add]

19. Navigation
Privateer (G&K) [Add]

20. Architecture
Hermitage [Move from 23]

21. Economics
Polder +2 Gold +1 Production (G&K; Denmark) [Add]

22. Metallurgy
Arsenal [Add]
The Kremlin [Move from 33]

Industrial Era

23. Archaeology
Hermitage [Move to 20]

24. Scientific Theory
Lumber Mill +1 Production [Move from 28]

25. Fertilizer
+1 Food on farm tiles [Split]
A. +1 Food on farm tiles with fresh water [Retain]
B. +1 Food on farm tiles without fresh water [Move to 14]

26. Biology
Oil Well [Split]
A. Oil Well [Retain]
B. Offshore Platform [Move to 29]

27. Electricity
Hydro Plant (River) [Add]
Police Station (G&K; Espionage) [Add]

28. Steam Power
Lumber Mill +1 Production [Move to 24]

Modern Era

29. Refrigeration
Offshore Platform [Move from 26.B]

30. Radio
National Intelligence Agency (G&K; Espionage) [Add]

31. Replaceable Parts
Military Base [Add]

32. Flight
Cristo Redentor [Move to 34]

33. Railroad
The Kremlin [Move to 22]

34. Plastics
Cristo Redentor [Move to 32]

Atomic Era

35. Penicillin (Pharmaceuticals)
Marine (G&K) [Add]

36. Atomic Theory
Manhattan Project [Move from 39]
Academy +2 Science [Add]

37. Radar
Paratrooper [Add]
 
38. Ecology
Recycling Center (G&K) [Add]

39. Nuclear Fission
Manhattan Project [Split]
A. Manhattan Project [Move to 36]
B. Nuclear Missile [Move to 43]
C. Atomic Bomb [Add]

40. Rocketry
Mobile SAM [Add]

41. Computers
Helicopter Gunship [Add]
Great Firewall (G&K; Espionage) [Add]

Information Era

42. Telecommunications (not in tech tree)
Nuclear Submarine (Tech) [Add]
Bomb Shelter (G&K; Tech) [Add]
CN Tower (G&K; Tech) ([Add]

43. Advanced Ballistics (not in tech tree)
SS Booster [Move from 45]
Nuclear Missile [Move from 39]
Guided Missile (Tech) [Add]

44. Satellites
Reveal the entire Map [Add]

45. Robotics
SS Booster [Move to 43]
Missile Cruiser [Add]

46. Lasers
Jet Fighter [Add]

47. Globalization (not in tech tree)
United Nations (Tech) [Add]

48. Nuclear Fusion (not in tech tree)
Giant Death Robot (Tech) [Add]

49. Stealth (not in tech tree)
Stealth Bomber (Tech) [Add]

Notes:
Unique units or buildings that replace another unit or building are not included. Unique improvements that does not replace anything are included.

**Comment by yairm210** [comment]
As I stated before, we're not doing G&K until we've finished Vanilla, and we've already been working on that for a year now.
Please remove ALL G&K related things.

**Comment by yairm210** [comment]
The rest should be added into #663 as a comment
