### ISSUE TITLE
Food glitch.

### ISSUE THREAD

**Issue by bitappend** [yairm210/Unciv#2207]
**Describe the bug**
Food and Expansion is off, i suspect a declared variable is of the wrong type exceding a full byte.  This kind of issue caused the now famous Ghandi glitch in the Original civilisation.

**To Reproduce**
Make a bad ass city that is yuge rolling the food generation over 255
Alternately 
I have seen this if you build up  town and destroy all the buildings that produce science. That will cause an unstoppable population collapse in the town.

**Expected behavior**
The more farming the more food. This does the oposite. 

**Screenshots**

![Screenshot_2020-03-20-04-52-35](https://user-images.githubusercontent.com/45378636/77163067-93626c00-6a6a-11ea-81ef-6103eb572575.jpg)

![Screenshot_2020-03-20-04-51-30](https://user-images.githubusercontent.com/45378636/77163006-775eca80-6a6a-11ea-8c58-3b3c4f217448.jpg)

**Comment by yairm210** [comment]
It's entirely possible that this is legitimate, with so much population eating away at the food
Please display the stats drilldown of this city

**Comment by bitappend** [comment]
Wish I could. When this starts happening. The game crashes.

**Comment by JackRainy** [comment]
Sorry, I do not see a bug from your screenshots.
If you produce almost no food (the 1st screen), the population is starving a lot and the population wil decrease fast (in 12 turns). 
If you produce a lot of food but still not enough (the 2nd screen), the population is starving slowly and the population will decrease not so fast (in 75 turns).
Everything is right here.

**Comment by yairm210** [comment]
If you're crashing that's a different problem - please update the game and if it's still happening, open a new issue about that =)
This does indeed look fine
