### ISSUE TITLE
Purchase with gold issue and upgrade.

### ISSUE THREAD

**Issue by vita10gy** [yairm210/UnCiv#221]
I was trying to buy a building that buffed production. I forget which one. Something that added some and then a percentage.

I switched to it, hit buy and nothing (I thought) happed. So I hit it again and again and exited thinking I had not done anything. Turns out I had like 10 of that building and 550 production in that city. (I had a ton of gold at the time.)

As fun as that was I'm guessing that's a bug. The windmill should probably leave the list when you buy it.

Along those lines it would be great if you didn't have to switch to producing something to buy it.

Amazing work so far.

**Comment by yairm210** [comment]
You're absolutely current, this is an unintended side effect of changing how the city decides what to work on
Fixed, and will enter the next version!
