### ISSUE TITLE
New game and options help

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2213]
What about to add special buttons into new game screen and options screen pointing on Civilopedia page with description of options?

**Comment by yairm210** [comment]
What options do you feel require an explanation?

**Comment by Iver88** [comment]
1. What is "default" map generation size? One of map type or something special?
2. What is "Continuous rendering"?

**Comment by rh-github-2015** [comment]
Trying to imagine coding something I get two feelings: Good - more interactivity in form of context help is nice, I could imagine how the code to jump forward might look (imgination probably 10% of what would actually work). Bad - from what I've seen you'd be thrown back to world view automatically upon closing the civilopedia unless we coded a way back and that might prove more complicated than the link forward.

But linking stuff _within_ the civilopedia - been on my todo for a long time. Along with those completely empty entries.

**Comment by yairm210** [comment]
I think in this specific case, we could add 'information' buttons that pop up with the relevant information if you need it
I'm thinking, maybe this should be applied to the whole game - certain labels will be clickable, and when clicked will show info
We'll need to make the labels stand out in some way to show they are different

**Comment by rh-github-2015** [comment]
In the olden Civ times (I think as far back as Civ2) the civilopedia was already crosslinked.

Idea: One clickable unicode character... 🛈 U+1F6C8? Unicode 7.0 probably not too well supported.  ℹ⃝  U+2139 U+20DD ?

**Comment by SomeTroglodyte** [comment]
See also #2304

**Comment by yairm210** [comment]
The "Options" was already done a while ago, but try as I might I can't think of a good name for the "Default" map. It just looks like a map, I dunno, nothing really special?
If you have any names I'm open to suggestions, but for now this is unactionable for me

**Comment by SomeTroglodyte** [comment]
Uh, that's what happens when reading mail bottom up: Mouthed off in wrong issue. "Default" technically does 4 rounds of a kind of cellular automaton on top of a random noise seed -> "Cellular Automata"!!!
