### ISSUE TITLE
Buttons size/aligment

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2214]
Actual buttons like very unprofessional. Many sizes and they are centered horizontally. What about standardizing of height of these buttons? So same size, icon on left and text in center of rest space between icon and right border (include padding)?

**Comment by JackRainy** [comment]
Could you, please, provide a few specific examples with screenshots?
Also, some _professional_ mockups of how they should look like are appreciated.

**Comment by Iver88** [comment]
<img width="225" alt="Snímek obrazovky 2020-03-21 v 15 24 28" src="https://user-images.githubusercontent.com/1991403/77228479-0f9ea180-6b88-11ea-8ff5-c6c4ca6fcc90.png">

I didn't mean it as an insult. I just think that same size and icon aligment to left side do lot of work. Horizontally positioned buttons with dynamic size are together with Comic Sans most ugly things in software development :)

**Comment by Iver88** [comment]
<img width="184" alt="Snímek obrazovky 2020-03-21 v 15 28 18" src="https://user-images.githubusercontent.com/1991403/77228570-99e70580-6b88-11ea-8b7a-4d4561091794.png">

**Comment by Iver88** [comment]
I love icons position on left. They did't have same size, but it is so much better now. I think same approach can be used for buttons in Civilopedia.
