### ISSUE TITLE
Better tech modification support

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2221]
I was able to add new tech using mod support but have some ideas for improvement of it:

1. Tree should be generated dynamically. Row and column must be hardcoded right now and there should be problem with mods conflict in future. There is line crossing new technology on screenshot due to this hardcoded tree version as well.
2. Era, tech cost, building cost and wonder cost must be part of new tech data. But there should be column and row as location identificator only. These values should be loaded from original when not overwritten. Or just required technologies and era in case of dynamic tree. Again. It can cause problem with mods conflict right now.

<img width="1109" alt="Snímek obrazovky 2020-03-21 v 21 53 56" src="https://user-images.githubusercontent.com/1991403/77236408-7a6acf80-6bbe-11ea-938e-b4451db603ce.png">

**Comment by Iver88** [comment]
3. It is not possible to use "requiredTech" for building from core files withou placing it into Techs.json file in mod. Again.

**Comment by rh-github-2015** [comment]
>     1. It is not possible to use "requiredTech" for building from core files withou placing it into Techs.json file in mod. Again.

Yes you can - provide the `cost` property _explicitly_ and it won't need to access the tech at ruleset load time

**Comment by rh-github-2015** [comment]
Tree should be generated dynamically

I estimate 3 to 5 man-days for someone with really good skills... Maybe if you googled algorithms one could plagiarize - didn't that non-sid-meyer civ clone, CTP, get open-sourced or leaked?

**Comment by rh-github-2015** [comment]
[CTP2 sources](https://apolyton.net/articles/civilization-news/ctp2/sourcecode) if anyone wants to have a go. I'm 33% sure it had a tech tree like that... Still got the CD of the original... Lawyers!

**Comment by Iver88** [comment]
It's not technical problem mainly. I did this kind of dynymic tree stuff for my clients. I can help with it too in my free time. I was add brewery as prerequisite tech for philosophy and looks fine right now. I think this task is not priority right now.

**Comment by JackRainy** [comment]
> brewery as prerequisite tech for philosophy
Haha! No beer - no philosophical thoughts! True story, bro! 🍺

**Comment by Iver88** [comment]
;) "Na zdraví"  🍺

**Comment by Iver88** [comment]
Ribbon should expand automatically as well depending on count of icons, padding above tech name.

<img width="314" alt="Snímek obrazovky 2020-03-27 v 4 52 15" src="https://user-images.githubusercontent.com/1991403/77720793-39712180-6fe9-11ea-8c65-2a137f55299f.png">

**Comment by Iver88** [comment]
And search input button should be nice.

**Comment by Iver88** [comment]
I'll add another stuff for my mod and will start on this task after finish it. Or someone can start it first and I can pull requests to his branch.

**Comment by Iver88** [comment]
Ok. Trying doing some stuff on it.

**Comment by Iver88** [comment]
https://github.com/Iver88/Unciv

**Comment by Iver88** [comment]
Better padding. Longer texts (mainly in translations) are not glued to the right edge. Same with 4th icon.

<img width="225" alt="Snímek obrazovky 2020-03-28 v 21 47 16" src="https://user-images.githubusercontent.com/1991403/77833488-0db38000-713e-11ea-8a5c-03fde91ade65.png">
<img width="175" alt="Snímek obrazovky 2020-03-28 v 21 47 25" src="https://user-images.githubusercontent.com/1991403/77833491-0ee4ad00-713e-11ea-9cbb-b65f836f4e8e.png">

**Comment by yairm210** [comment]
There are a bunch of things here
About button length, JackRainy dealt with that
I managed to mod a tech quite simply, I see that there could be a demand for forgoing bringing in the 'column' wrapper but I think it works well as-is - you can just have the column wrapper and in it only the tech you want to add/edit
To be totally honest, I think that building a dynamic tree will lead to a worse tech tree, from an aesthetic point of view. There is a lot of deliberation in placing the current techs exactly where they are. But if you want to have a shot at it, go ahead!
About "you can't reference original techs from mods" - this is a GOOD POINT, and I'll try to deal with that
