### ISSUE TITLE
Better mod error output

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2227]
<img width="251" alt="Snímek obrazovky 2020-03-22 v 11 39 43" src="https://user-images.githubusercontent.com/1991403/77247474-d7ec3400-6c31-11ea-9034-19cedaae5971.png">

It is really not much relevant information for mod creators :/

**Comment by Iver88** [comment]
[Dacia mod.zip](https://github.com/yairm210/Unciv/files/4365035/Dacia.mod.zip)

**Comment by Iver88** [comment]
Happens when Building requires technology and it is not part of mod in Techs.json. For example using existing technology from core files.

**Comment by Iver88** [comment]
I tried add console error message for non existing Techs.json file in mod folder when using "requiredTech" from vanilla, but I can't simply check null value of column variable.

<img width="428" alt="Snímek obrazovky 2020-03-22 v 14 08 11" src="https://user-images.githubusercontent.com/1991403/77250573-2bb64780-6c49-11ea-9b57-30fe09609bc5.png">

**Comment by rh-github-2015** [comment]
Happens I did/solved everything you mention this morning. Right before that code defaulting cost to tech's is a bug: a building with cost 0 and no prereqtech would not be caught (but there is none in the current jsons). Also stumbled upon that strange fact that an exception of class NullPointerException has such a short message in the Java framework.

What I have still shows 'programming errors' - bad stuff in your mod files - only on the console, not in the UI, but another situation - loading a game demanding a mod that did not load - I thought worthy of a clear message to the user. Let me push that stuff even if I'm not convinced it's complete... OK, last commit in ##2211.

I already tried a lot of ways to break a mod and how console output reacts, and found no more worthwhile catch-and-explain scenarios. Go ahead and find some please.

**Comment by Iver88** [comment]
Ok. Thank you. You are my hero. I prepared these tasks for me primary, but you was faster then me :) It's not my mod. I just wanted help one moder with it and don't have too much time for it right now.
