### ISSUE TITLE
Patronage Policy Tree

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#2229]
In the vanilla version of Civ V, there are ten policy branches. We've got eight: Patronage and Order are missing, so I'm bringing my icons for the Patronage policy branch.

Adopting Patronage first reduces Influence loss with City-States by 25%.

PHILANTHROPY
![iconphilantropy](https://user-images.githubusercontent.com/41149920/77260798-70160780-6c8a-11ea-8fde-4ac08a37949c.png)
Credit by Kev
Requires the simple Patronage adopting
Gold gift to City-States produce 25% more Influence.

AESTHETICS
Just put the City-State icon there
Minimum Influence level with all City-States is 20.

SCHOLASTICISM
![iconscholasticism](https://user-images.githubusercontent.com/41149920/77260799-70ae9e00-6c8a-11ea-9925-64349943d30e.png)
Credit to AFY Studio
Requires Philanthropy
Allied City-States provide a Science bonus equal to 25% of what they produce for themselves.

CULTURAL DIPLOMACY
![iconculturaldiplomacy](https://user-images.githubusercontent.com/41149920/77260800-71dfcb00-6c8a-11ea-86d6-7d4d2e3c0f5e.png)
Credit to shanthagawri
Requires Scholasticism
Doubles the amount of gifted resources, and provides an additional 50% Happiness from gifted luxuries (unfortunately, this also means that City-States gifting resources must be implemented).

EDUCATED ELITE
![iconeducatedelite](https://user-images.githubusercontent.com/41149920/77260802-72786180-6c8a-11ea-9be3-63eda030d533.png)
Credit to P Thanga Vignesh
Requires Aesthetics and Scholasticism
Allied City-States will provide a random Great Person (including Khans) once every 40 turns (Standard Speed)

Adopting all Patronage Policies will decrease the Influence loss to all City-States by 33%.

**Comment by yairm210** [comment]
Part of #663
