### ISSUE TITLE
Desktop controls improvements

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2233]
I have some ideas about missing controls on desktop alongside mobile control. Some of them are working already. Like zooming, but some of them are missing and cumbersome.

1. Scrollable parts must get focus on hovering over. You must click first right now for possibility to scroll up/down.
2. Right click for movement like in Civ games. First right click on tile will do same as left click (placing icon with number of turns) and second right click on same tile will confirm it (unit moves). Attack and other stuff can stay on left button. No need for change.
3. WASD and arrow keys for moving around.
4. ESC for opening/closing game menu and closing dialogs and windows where back/close button is enabled.

**Comment by l3sy** [comment]
The keyboard shortcuts for building tile improvements and founding cities, fortify and sleep would also be cool for the desktop version.

**Comment by rh-github-2015** [comment]
Had this on my list for ages - but what I miss most is a key for next unit, would save kilometers of mouse movement...

Unfortunately I do not understand enough about the interaction between LibGdx and Android-Style widgets or whereever these Table() Button() Label() classes come from. I've read [this](https://www.gamefromscratch.com/post/2013/10/15/LibGDX-Tutorial-4-Handling-the-mouse-and-keyboard.aspx) just minutes ago, but I wouldn't want a global keyTyped event, I'd want a widget .onKey() listener...

**Comment by Iver88** [comment]
Next unit. Yes. I love feature from Civ6 (Civ5 too maybe) where you can cycle through idle units using "Next unit" button, but it doesn't skip unit when clicking again and again. In other word - all units has to do something. Moving, building, must be fortified, set to wait etc. for skipping of turn. So there is no need for finding every unit manually.

**Comment by SomeTroglodyte** [comment]
#2316

**Comment by yairm210** [comment]
We got 1,3 and 4, and I'm not planning on doing 2 at the moment - lost of moving parts there, and a large chance on interfering with the current click actions
