### ISSUE TITLE
City names in overview screens are not translated

### ISSUE THREAD

**Issue by stoupa007** [yairm210/Unciv#2242]
On more overview screens city names are not translated and original strings are used.
Spotted in city overview as well as unit overview.

**Comment by yairm210** [comment]
Hah, I actually fixed the unit name translations in the latest versions, but I missed the cities - thanks!

**Comment by stoupa007** [comment]
i just noted that cities in overview/cities screen are translated, but cities in overview/units (closest city column) screen are still not .. :)
