### ISSUE TITLE
Accuracy on Chariot did not translate to Shock on Knight

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2244]
Upgraded a Chariot Archer with Accuracy to Knight.

I am under the impression Accuracy should have translated to Shock, but it did not.  Not sure if this is a bug, or if you can just double up the XP here.

![Screenshot_20200324-112828](https://user-images.githubusercontent.com/3236760/77445055-fd5c7780-6dc2-11ea-9564-b4c4aa281cb0.png)

**Comment by yairm210** [comment]
It should not have translated, this is as it should be.
