### ISSUE TITLE
Embarked military unit can not stack with naval unit

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#2266]
**Describe the bug**
I am trying to place a Rifleman at the same tile with Submarine or Carrier, but it is not possible.

**To Reproduce**
1. Embark a military unit
2. Try to move it at the same tile as any naval unit

**Expected behavior**
According to https://civilization.fandom.com/wiki/Embarkation_(Civ5) "... embarked civilian and military units are considered to be the same type of unit and thus cannot be stacked, though naval units can stack with embarked units."

**Screenshots**
![Screenshot 2020-03-26 22 54 44](https://user-images.githubusercontent.com/27405436/77695921-34927a80-6fb5-11ea-92d4-e7db9ab428a6.png)

**Comment by rh-github-2015** [comment]
Other places state one can garrison with both a land and a naval unit. 
Like no Hills for Desert/Snow/Plains, this is in the choice of data structure and can only be remedied with quite extensive work. (OK, the hills thing would be faaar easier if one does not separate elevation and humidity into separate attributes for a tileinfo but multiplies the number of distinct baseterrains - except the map generator would need more conditionals).
I think the game is quite fun as it is.

**Comment by JackRainy** [comment]
No hills for plains? Elevation and humidity? Whaaat? o_O
How does it relate to embarkation of the units?
I understand almost nothing out of this comment, sorry :) Except the last sentence, yes, the game is quite fun even with 50 open issues.

**Comment by rh-github-2015** [comment]
I got too long winded trying to explain, deleted. I say the data model for a tile is different between civ and unciv, civ had one more which controlled hills and mountains, separate from the one controlling surface type (grass,plains,desert,tundra). Therefore you had grass hills, plains hills, deserthills etc in civ, and they came naturally. Unciv would need more BaseTerrain entries to  express them. Might be equivalent, but the map generators have it easier with the civ model - they use terran geography concepts to simulate environmyntal rules so the maps look natural, and mapping these - elevation humidity temperature - to the civ model is easier than the unciv model.

Now units 'live' on the map tiles, and unciv has two slots per tile, one for military one for civilian. The link you found and one I read (can't find - it recommended placing both a ranged land unit and a naval unit in a city tile for more firepower during a siege) suggest Civ has three - I think there's sources that show that accompanying embarked land units with generals also is possible in Civ . Low level data model redesign gets expensive. That's all I wanted to say.

**Comment by yairm210** [comment]
As owner, I'm closing this.
Very low benefit (no user has yet complained about this, and they complain about just *anything*) and high potential damage.

**Comment by rh-github-2015** [comment]
Oh, I found that reference: [Combat Strategy](https://civilization.fandom.com/wiki/Combat_strategy_%28Civ5%29) - under Defending against a siege, third paragraph:
"keep a ranged unit as garrison ; in case of a coastal city, put a ranged ship in it too"

But I concur to shelve this.
