### ISSUE TITLE
Celts nation

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2272]
N1 did lot of work on Celts nation mod already. I think it can be used as basis for implementation into game itself later when he gives his consent. https://github.com/N1187/Unciv-celts-mod

Only civ unique is missing, because it's not hardcoded in game right now.

**Comment by yairm210** [comment]
This is a G&K nation, and therefore not on our current todo list =)

**Comment by Iver88** [comment]
Just for info that someone did big part of job on this already. It can stay as mod until implementation.
