### ISSUE TITLE
Units "exploring" feature needs work

### ISSUE THREAD

**Issue by rh-github-2015** [yairm210/Unciv#2278]
"Finished exploring" doesn't clear the action, so the unit won't ask for orders. 
Moving an exploring unit manually should clear the action. 
Exploration stops even if there are undiscovered tiles one step away:
![image](https://user-images.githubusercontent.com/16001896/77842547-dec7f900-7193-11ea-9228-aad964e5b897.png)
(that's right - no capital - I just set both units to explore on a fresh vanilla game and 'waited' for the message)

**Comment by krijnsent** [comment]
Same category: when a unit finished its moves and you press "auto explore" (so with 0 moves left), the game will always return "unit finished exploring".

**Comment by JoshDM** [comment]
Except it's going to continue exploring next turn.

So... "Unit finished exploring" message in that case should be changed to something more relevant.
