### ISSUE TITLE
Setllers bug

### ISSUE THREAD

**Issue by Roumaan** [yairm210/UnCiv#228]
I've just started new game, and saw a Chinese settler trying to claim a good city spot, but i was faster and claimed it... And something  gone wrong.
![screenshot_20180812-005858](https://user-images.githubusercontent.com/16963703/43996452-7cf079e8-9dcb-11e8-8884-e569a290823c.png)

**Comment by Roumaan** [comment]
And it crashed when i returned to the game and clicked on next turn button

**Comment by yairm210** [comment]
Fixed in the latest version (2.7.7), should either already be available to you or should be tomorrow
