### ISSUE TITLE
The Inca Color It's Really Annoying For My Eye

### ISSUE THREAD

**Issue by Bima-Kentang** [yairm210/Unciv#2282]
The Strong Yellow Color Make My Eyes Burned.

**Comment by Bima-Kentang** [comment]
> The Strong Yellow Color Make My Eyes Burned.
![Screenshot_2020-03-29-21-03-18-287_com unciv app](https://user-images.githubusercontent.com/62836197/77851056-d4901400-7200-11ea-9ff7-733627157aa0.jpg)

**Comment by Bima-Kentang** [comment]
With That Green Font....

**Comment by yairm210** [comment]
Original civ:
![image](https://user-images.githubusercontent.com/8366208/77852187-eadca680-71e5-11ea-9749-63f7197d9240.png)

Old:
![image](https://user-images.githubusercontent.com/8366208/77852282-7a825500-71e6-11ea-83f7-7d082c9459f2.png)

New:
![image](https://user-images.githubusercontent.com/8366208/77852319-b87f7900-71e6-11ea-8b27-f4b3cfe59509.png)

It's stretching it a bit from the original, but I hope that's better!

**Comment by yairm210** [comment]
Resolved in f6da534
