### ISSUE TITLE
Modded nation - only one picked

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2299]
When mod with multiple nations is used - https://github.com/GreenFreshy/EuropeMod for example, when enabling mod, only first nation is picked even second one is selected as "human".
<img width="628" alt="Snímek obrazovky 2020-03-31 v 18 15 13" src="https://user-images.githubusercontent.com/1991403/78049652-9703c600-737b-11ea-8051-0d0490b3ce49.png">

**Comment by yairm210** [comment]
This is *definitely* not a bug, and not even an issue, in my mind.
The auto-adding is a bonus feature that replaces a click-scroll-click, and this works perfectly well without it

**Comment by yairm210** [comment]
I don't think multi-nation mods are common enough that we'll want to auto-add ALL of their nations by default into all human players

**Comment by SomeTroglodyte** [comment]
The author of the feature was even aware and chose the simpler way. Multi-nation mods would go in the direction of a 'scenario' feature (scenario = mod+map+setting defaults+setting limits+boilerplate? Idea: pose a specific challenge) - maybe much later.
