### ISSUE TITLE
Cities limit

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2300]
When there is no more city names in mod (in vanilla game too maybe), there is no possibility for creating of new city. In Civ5, city was created without name at least.
![Screenshot_20200331-153043](https://user-images.githubusercontent.com/1991403/78062707-5f9f1480-738f-11ea-9262-e916fa8df836.png)

**Comment by yairm210** [comment]
This has nothing to do with mods or city limits, and everything to do wth the fact that you're 3 tiles away from an existing city.
