### ISSUE TITLE
Tech prerequisites

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2309]
Something changed in code? It worked in past versions. It seems main file has priority before modded one. Lines should be connected from Writing and Fermentation into Philosophy.
<img width="886" alt="Snímek obrazovky 2020-04-02 v 1 50 25" src="https://user-images.githubusercontent.com/1991403/78197105-acb0e280-7484-11ea-9b89-bb56fb3911f6.png">

**Comment by SomeTroglodyte** [comment]
That must have been #2240. Sorry. I'll think about it.

**Comment by rh-github-2015** [comment]
On it.

**Comment by rh-github-2015** [comment]
Could you test #2380?

**Comment by yairm210** [comment]
Solved in latest version =)
