### ISSUE TITLE
Misplaced features in the tech tree

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#2317]
**Describe the bug**
The following shows features/wonders/buildings/units that are in the wrong technology:
1. Agriculture
remove Fallout [Move to Worker as an ability]
* Remove Fallout is an innate ability of workers and is not affected by any technology.

2. Masonry
remove Marsh [Move from 3]

3. Bronze Working
remove Marsh [Move to 2]

4. Education
Angkor Wat [Move from 5]

5. Chivalry
Angkor Wat [Move to 4]

6. Architecture
Hermitage [Move from 8]

7. Metallurgy
The Kremlin [Move from 14]

8. Archaeology
Hermitage [Move to 6]

9. Scientific Theory
Lumber Mill +1 Production [Move from 11]

10. Biology
Oil Well [Split]
A. Oil Well [Retain]
B. Offshore Platform [Move to 12]

11. Steam Power
Lumber Mill +1 Production [Move to 9]

12. Refrigeration
Offshore Platform [Move from 10.B]

13. Flight
Cristo Redentor [Move to 15]

14. Railroad
The Kremlin [Move to 7]

15. Plastics
Cristo Redentor [Move to 13]

16. Penicillin [Name Change from Pharmaceuticals]

17. Atomic Theory
Manhattan Project [Move from 18]
Academy +2 Science [Add]

18. Nuclear Fission
Manhattan Project [Move to 17]
Nuclear Missile [Move to 19]

19. Advanced Ballistics (not in tech tree)
SS Booster [Move from 20]
Nuclear Missile [Move from 18]

20. Robotics
SS Booster [Move to 19]

*Production cost of some of them might need adjustment (e. g. The Kremlin)

**Additional context**
These are things that are already implemented but implemented wrong so I opened a Bug Report issue instead

**Comment by yairm210** [comment]
I'm sure that ou''re working according to a different version than I am. What version of Civ are these from? G&K? BNW?

**Comment by Alkeif** [comment]
It's based on G&K because that's what the current tech tree is based on. I tried doing this using the vanilla tree but there were too many inconsistencies in the current tree than the vanilla tech tree

**Comment by Alkeif** [comment]
Some of them are true also even when based from vanilla tech tree such as:
# 1-3, 9-12, 16-18

**Comment by JackRainy** [comment]
Thank you for the input.
Sorry, but I am a bit frustrated reading those [from N] [to N]. For example, I do not understand where "Cristo Redentor" should be.
Could you, please, write the *expected* result only, e.g. "Tech - Feature".

**Comment by Alkeif** [comment]
Is this ok? I did not totally remove everything but indicated instead those that will be removed. 
1. Agriculture
remove Fallout [Move to Worker as an ability]
* Remove Fallout is an innate ability of workers and is not affected by any technology.

2. Masonry
remove Marsh

3. Bronze Working
remove Marsh [Remove]

4. Education
Angkor Wat

5. Chivalry
Angkor Wat [Remove]

6. Architecture
Hermitage

7. Metallurgy
The Kremlin

8. Archaeology
Hermitage [Remove]

9. Scientific Theory
Lumber Mill +1 Production

10. Biology
Oil Well [Split]
A. Oil Well [Retain]
B. Offshore Platform [Remove]

11. Steam Power
Lumber Mill +1 Production [Remove]

12. Refrigeration
Offshore Platform 

13. Flight
Cristo Redentor [Remove]

14. Railroad
The Kremlin [Remove]

15. Plastics
Cristo Redentor

16. Penicillin [Name Change from Pharmaceuticals]

17. Atomic Theory
Manhattan Project
Academy +2 Science [Add]

18. Nuclear Fission
Manhattan Project [Remove]
Nuclear Missile [Remove]

19. Advanced Ballistics (not in tech tree)
SS Booster
Nuclear Missile

20. Robotics
SS Booster [Remove]

*Production cost of some of them might need adjustment (e. g. The Kremlin)

**Comment by Alkeif** [comment]
I made it like how it was requested anyway. 

1. Agriculture
remove Fallout [Move to Worker as an ability]
* Remove Fallout is an innate ability of workers and is not affected by any technology.

2. Masonry
remove Marsh

3. Education
Angkor Wat

4. Architecture
Hermitage

5. Metallurgy
The Kremlin

6. Scientific Theory
Lumber Mill +1 Production

7. Biology
Oil Well [Split]
A. Oil Well [Retain]
B. Offshore Platform [Remove]

8. Refrigeration
Offshore Platform 

9. Plastics
Cristo Redentor

10. Penicillin [Name Change from Pharmaceuticals]

11. Atomic Theory
Manhattan Project
Academy +2 Science [Add]

12. Advanced Ballistics (not in tech tree)
SS Booster
Nuclear Missile

*Production cost of some of them might need adjustment (e. g. The Kremlin)

**Comment by yairm210** [comment]
I'm closing this, because I think the cost of some of these changes is greater than 0, and the benifit is almost 0.
When we finally get several "Versions" working ('Unciv basic", "Vanilla", "G&K") then we can ensure that each of the Orig Civ tech trees has everything perfectly positioned according to the original.
As of now, not worth the hassle.
