### ISSUE TITLE
Civilopedia - Define culture cost for acquiring new tiles

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2322]
Russia has Krepost which is described as reducing the culture cost of acquiring new tiles.

This cost is not defined in the Civilopedia, or at least not where I can find it. It should be. This jira entry is to track adding this.

**Comment by rh-github-2015** [comment]
Specific suggestion where this should go? Which header?

**Comment by JoshDM** [comment]
Need to identify what it is first and the text to accompany it. That will help decide where to categorize it.

**Comment by rh-github-2015** [comment]
From [this (source given in source code)](https://www.reddit.com/r/civ/comments/58rxkk/how_in_gods_name_do_borders_expand_in_civ_vi/), Civ5 doesn't tell you anything either, so we shouldn't... :)

Ref: `cultureToNextTile = 6 * Math.pow(numTilesClaimed + 1.4813, 1.3)`
  `(gold)cost(oftile) = baseCost * (distanceFromCenter-1) + numTilesClaimed*5.0`
Angkor Wat, Krepost, Tradition and Manifest Destiny are applied multiplicatively after that...

If we'd put this under Tutorials as a nice long textwall - help out by proposing the text? Should it be Civilopedia only or, if not, when exactly should the popup to the player occur first?

**Comment by JoshDM** [comment]
I would make a new (I didn't check if it exists) post under Tutorials
(should be misc.) titled "Tile Acquisition" or similar and describe how to
do it, how far it reaches and identify the costs involved in doing so.

**Comment by JoshDM** [comment]
IMHO, text should say something like "Acquiring a tile costs the city a
small amount of culture, which increases with each additional tile."

**Comment by SomeTroglodyte** [comment]
And 'forever' is not quite true as well. Reminds me I always thought the message in that case (culture pool full but no more tiles available) wrong - and that I thought the cost shouldn't be deducted in that case.
