### ISSUE TITLE
Era Lock

### ISSUE THREAD

**Issue by ImAdjured** [yairm210/Unciv#2328]
Hi Can we make something like Era lock
It's like stopping in a certain era and prevent the era from changing or reaching further or more advanced.
For example: can we make the era to stop in Renaissance
So we can enjoy so feature or Civilization advantage more.
Because the earlier era goes so fast and its upsetting not to fully utilize some units like Samurai of Japan when a few turns after building one you'll have to upgrade it up already.

Hope you put consideration on this.
Really enjoy the game
Thanks

**Comment by yairm210** [comment]
How would you imagine this working? 
You research all the techs of up till that era and then science just...becomes irrelevant?
Not seeing it

**Comment by rh-github-2015** [comment]
Also not a Civ feature?

**Comment by yairm210** [comment]
It's not?
If so, then there's no question. We have enough Civ V things to deal with =)
