### ISSUE TITLE
Representation is retroactive

### ISSUE THREAD

**Issue by N1187** [yairm210/Unciv#2332]
The Representation social policy usually only applies to new cities after it's signing, but recently I've heard that the social policy retroactive and it applies to all cities. It didn't work this way in civ v

**Comment by yairm210** [comment]
You misunderstand how it works.

To quote:

> Retroactive with regards to cities
> 
> Not retroactive with regards to policies

https://forums.civfanatics.com/threads/how-does-the-new-representation-policy-work.414366/#post-10297777

https://forums.civfanatics.com/threads/does-representation-take-into-account-of-existing-cities.478237/

That is to say, it doesn't affect previous policies that were picked.
It does affect **all** cities, even those founded before Representation
