### ISSUE TITLE
Hope to add functions to immigrants

### ISSUE THREAD

**Issue by wanrenze** [yairm210/Unciv#2333]
It is hoped that when immigrants arrive at a city, they can add a function of entering the city to increase the population of the city. In addition, I hope that the Chinese leader can be changed from Wu Zetian to the first emperor of Qin. Wu Zetian's increase in Chinese culture is relatively low.

**Comment by N1187** [comment]
No, civ v didn't have immigrants, nor will we change the leaders or interfere with the features in any account

**Comment by wanrenze** [comment]
> No, civ v didn't have immigrants, nor will we change the leaders or interfere with the features in any account

So what do you use to build your city? I'm Chinese, and I know a lot more about Chinese history than foreign countries. I don't think I'm wrong. Besides, I didn't say any function of account

**Comment by yairm210** [comment]
Cities gain population with enough food
This is just not how Civ works, so it won't be happening =)

**Comment by wanrenze** [comment]
> Cities gain population with enough food
> This is just not how Civ works, so it won't be happening =)

Ok, thank you.
