### ISSUE TITLE
external localization platform for translations

### ISSUE THREAD

**Issue by guilherme-peev** [yairm210/Unciv#2343]
Hello, 
I'm trying to help translate into Portuguese, but having a hard time. I don't know how to use GitHub, and I don't code.
Generally, when I help translating an open source project, I do it by some localization platform, like web-late or stringlate, which are easier for translators.
I suggest migrating translations for one of those. They are also free of charges for open source projects.
I'm going to try some more times to do it directly on GitHub. But I do believe migrating it would increase the number of translators.
Nice game, by the way. Very addictive.

**Comment by yairm210** [comment]
Thanks!
Since the translations are constantly changing, the work of creating the strings for translations is something that happens every couple of days, even, which makes it much simpler to keep everything inside git =)

**Comment by yairm210** [comment]
At the moment, we're not planning on moving them out =)
