### ISSUE TITLE
Lighthouse still in build queue after city builds The Great Lighthouse

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2348]
Start building TGL. Grants a free lighthouse.
Queue a Lighthouse.
Build TGL.
Lighthouse is still in queue.
Probably shouldn't be.

**Comment by rh-github-2015** [comment]
Shouldn't #2192 deal with that? I'll go take a look. But - I would have a hard time resisting touching other quirks in the current queue system - can I finally queue three boosters and no more (even distributed over cities)? Can I queue a building with an unbuilt dependency after queueing its dependency? ......

**Comment by JoshDM** [comment]
Same goes for Castles and wonders that grant free Castles.

**Comment by rh-github-2015** [comment]
> Same goes for

Yes it does. Anyway, 2 details: If your free building is the next one in the queue, this doesn't happen, only if there's something between the grantor and the granted. Also, it's cleaned up in `endTurn`, while constructionComplete is called at `startTurn` - so it'll be gone automatically soon. And my #2192 code isn't related, though it's in the same function as what cleans up your observation in `endTurn` - `fun validateConstructionQueue()`

So - fix is easy - but I don't want to issue any more PR's until I can kill my fork and re-fork. As patch:
```
--- core/src/com/unciv/logic/city/CityConstructions.kt	(revision 7d7d0a1c91ac4e1a31c7aed0ce11f5422fd6ed7f)
+++ core/src/com/unciv/logic/city/CityConstructions.kt	(date 1586529906000)
@@ -265,7 +265,7 @@
         }
         // remove obsolete stuff from in progress constructions - happens often and leaves clutter in memory and save files
         // should have NO visible consequences - any accumulated points that may be reused later should stay (nukes when manhattan project city lost, nat wonder when conquered an empty city...)
-        val inProgressSnapshot = inProgressConstructions.keys.filter { it != currentConstruction }
+        val inProgressSnapshot = inProgressConstructions.keys.filter { true }
         for (constructionName in inProgressSnapshot) {
             val rejectionReason:String =
                     when (val construction = getConstruction(constructionName)) {
@@ -284,8 +284,7 @@
 
     private fun constructionComplete(construction: IConstruction) {
         construction.postBuildEvent(this)
-        if (construction.name in inProgressConstructions)
-            inProgressConstructions.remove(construction.name)
+        validateConstructionQueue()
 
         if (construction is Building && construction.isWonder) {
             cityInfo.civInfo.popupAlerts.add(PopupAlert(AlertType.WonderBuilt, construction.name))
```

Maybe later unless I forget.
