### ISSUE TITLE
Cancel or reset interrupted tile improvement

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2349]
Put a worker on a forest.

Set worker to clear forest.

OOPS OH SHIT I MEANT CLICK BUILD LUMBER MILL.

Move worker off space (you can do that now!) or disband him or get him killed.

Move worker onto space. Previously selected work continues.

BYE BYE FOREST. HELLO GLOBAL WARMING

Now, yeah I understand this is intended behavior where a worker gets killed and another wants to take over, but this isn't great and the ongoing work should be cancelled, though any progress should be tracked (and reset if the tile is changed to be worked a different way).  Tracking progress should be different 2 separate queues for road/railroad/removal and improvement/removal.

**Comment by JackRainy** [comment]
Why do you need to kill a worker? Just give him another order like "build limber mill".

**Comment by JoshDM** [comment]
Until recently, you couldn't give a worker who is actively working a task a
different task, so you kill it (or disband it, same difference).

Anyway, it's irrelevant to the request here. The request is to be able to
cancel the improvement because even if you disband or kill a unit, the next
worker to enter that tile will immediately start working it in the same
fashion.

**Comment by JackRainy** [comment]
I just try that on 3.6.15 version, it is possible to give another order. So it should not be a problem to cancel an order by giving another order.

**Comment by rh-github-2015** [comment]
To clarify: The improvement order is stored with the tile, and is civ-independent. And yes, there is currently no option to clear that - only overwrite.

Workers work on improvements in progress whenever they finish their turn on a tile with unfinished work. No matter how it was interrupted, by who, who the tile belongs to, who the worker belongs to, whether the worker's civ has different accelerating policies/wonders than the civ that started the improvement, whether the worker has 0 or more movement points left (IMHO in Civ, at least all civs before 5, a unit without leftover movement couldn't make any progress - improve, fortify, etc), or whether the worker has other orders like move elsewhere. ... at least that's what I gathered from playing several versions ago for a while. And, from a cursory glance at the code, it might be a challenge to code a correction. Not enough context available at the locus where the decision is made to decrement the turns-to-improvement counter.

However, a 'cancel current' button on the improvement picker? Hmmm... Let me check...

**Comment by yairm210** [comment]
Resolved!
