### ISSUE TITLE
Valid trade deemed no longer relevant

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2354]
Trading to two different nations simultaneously.

I have 3 of a single resource and 60 gold/turn.

I offer Nation A 1 Resource + 20 gold for a tech.
They'll take it.
I offer Nation B the same for a different tech.
I also know they'll take it.

This should leave me with 20 gold and 1 resource.

1 trade goes through and the other is identified as no longer relevant.

Perhaps the system is trying to give the same resource item instead of the SECOND resource item?   No idea, but should not have been rendered invalid. Wasted turn.

**Comment by yairm210** [comment]
Fixed in cc1ae03
