### ISSUE TITLE
Some Chinese characters cannot be input

### ISSUE THREAD

**Issue by Wangrenze2004** [yairm210/Unciv#2374]
When I changed the city name, I found that some Chinese characters could not be input, such as "莆".Although this situation will not cause anything to happen, it will destroy the game experience..
![Screenshot_20200409-170402](https://user-images.githubusercontent.com/63151220/78878381-ef8c3080-7a17-11ea-9998-75fd0d5d742a.png)
![Screenshot_20200409-170409](https://user-images.githubusercontent.com/63151220/78878396-f5821180-7a17-11ea-9e9e-f2fc68a46029.png)

**Comment by wanrenze** [comment]
Attachment: the moment when I went mad while playing civ
![Screenshot_20200409-132254](https://user-images.githubusercontent.com/63151220/78879601-b81e8380-7a19-11ea-94e2-7965ca80cc50.png)

**Comment by rh-github-2015** [comment]
Probably the same with "_" and """" - Unciv limits memory usage by selecting only a limited set of glyphs for inclusion in its fonts. I never rename cities... I'm checking code, but, if you want to help - do you play on desktop? If so, start a new game on the smallest map, rename that first city so its name contains those characters you know get invisible, and post the result of save - copy to clipboard for us (yes on turn 0).

**Comment by wanrenze** [comment]
> Probably the same with "_" and """" - Unciv limits memory usage by selecting only a limited set of glyphs for inclusion in its fonts. I never rename cities... I'm checking code, ~but, if you want to help - do you play on desktop? If so, start a new game on the smallest map, rename that first city so its name contains those characters you know get invisible, and post the result of save - copy to clipboard for us (yes on turn 0).~ Forget it, chars not in the charset do not get saved at all...
> 
> OK. Here's the catch: For chinese and some other languages with large character sets it builds the character set from the translations. That is, it takes all texts the game uses itself, then their translations, compiles all unique occurrences, then builds the font from them. So, if a character is never used in a translation it will stay missing.
> 
> Everyone: Idea: Dummy translation key "Charset"?
> 
> @wanreze: Care to provide a template? List all characters as a text block that are indispensable for city naming or point to a good source? Should be around 2000 chars, that's what Unciv loads for Simplified Chinese right now.

OK, I'll try my best. (I think the author will agree. )

**Comment by wanrenze** [comment]
> Probably the same with "_" and """" - Unciv limits memory usage by selecting only a limited set of glyphs for inclusion in its fonts. I never rename cities... I'm checking code, ~but, if you want to help - do you play on desktop? If so, start a new game on the smallest map, rename that first city so its name contains those characters you know get invisible, and post the result of save - copy to clipboard for us (yes on turn 0).~ Forget it, chars not in the charset do not get saved at all...
> 
> OK. Here's the catch: For chinese and some other languages with large character sets it builds the character set from the translations. That is, it takes all texts the game uses itself, then their translations, compiles all unique occurrences, then builds the font from them. So, if a character is never used in a translation it will stay missing.
> 
> Everyone: Idea: Dummy translation key "Charset"?
> 
> @wanreze: Care to provide a template? List all characters as a text block that are indispensable for city naming or point to a good source? Should be around 2000 chars, that's what Unciv loads for Simplified Chinese right now.

Add: I'm an Android device can't do that.

**Comment by lishaoxia1985** [comment]
@wanrenze  Not a bug. it is because that only the font which is used in game can be inputed. unless we add the input font dynamic into characterSetCache (textfield class should be rewritten) or add usual font into characterSetCache in one time, it is not solved.

**Comment by SomeTroglodyte** [comment]
> @wanrenze Not a bug. it is because that only the font which is used in game can be inputed. 
That's what rh-github-2015 com said.
