### ISSUE TITLE
Hope to have an automatic next round function

### ISSUE THREAD

**Issue by Wangrenze9788** [yairm210/Unciv#2375]
It is hoped that an automatic next round function will appear. You can select the switch in the setting (it is off by default). When the next round is automatic, click the button of the next round to cancel the automatic next round.:-)

**Comment by yairm210** [comment]
Do you mean 'automate all units, pick a random tech and a random policy'?

**Comment by wanrenze** [comment]
> Do you mean 'automate all units, pick a random tech and a random policy'?

No, it will be forced to suspend the automatic next round when policies need to be promulgated and technologies need to be signed.

**Comment by wanrenze** [comment]
@yairm210

**Comment by wanrenze** [comment]
Besides, I'm sorry to reply so late. I have something to do recently.

**Comment by loomy** [comment]
+1
someting like "next turn until event occurs"
if there is no event in the newsfeed, like _enemy units sighted_ or _We have invented the wheel_  .... and the "next turn" button is active on load of the round (all units automated), => auto next turn.
maybe its safer to limit it to 10 rounds maximum

this would be a big game speed improvement, especially in the early phase of a big multiplayer game

**Comment by yairm210** [comment]
Already exists :D
