### ISSUE TITLE
Multiplayer game stopped working

### ISSUE THREAD

**Issue by lorenatrivellato** [yairm210/Unciv#2379]
We are 7 people playing Unciv. Since tonight the game started saying that it "coudn't download the latest games state". it started just as a periodically issue happening to one of us, but now all the 7 of us cannot play anymore. Right now we are at 140th round. Which could be the issue? Can it be solved? Could be better if we paly on phones, instead of laptops? Thanks a lot in advance.

**Comment by JackRainy** [comment]
I assume, some of you using the differ version of the game. Upgrade, the game to the same version (e.g. 3.7.0).

**Comment by lorenatrivellato** [comment]
Thanks. We try to do that and get back to you if we need further help, is
it fine for you?

Il giorno ven 10 apr 2020 alle 01:08 Jack Rainy <notifications@github.com>
ha scritto:

**Comment by JackRainy** [comment]
No problem. If the problem still appear, it would be nice if you attach a saved game file here.

**Comment by yairm210** [comment]
This might have happened because one of you built a fort/citadel and the others haven't yet upgraded to the latest version, this happened to other players
Upgrade to the latest version and that should solve it =)
