### ISSUE TITLE
Add ability to remove definitions in modding

### ISSUE THREAD

**Issue by u-ndefine** [yairm210/Unciv#2381]
This feature will add more flexibility in modding. Hopefully changing of tech tree will work completely fine. I will also work on an unofficial mod and it <sup>(may)</sup> need this feature.

I have an idea that maybe we can add something like `"disable":true` and the specified `"name":` will be disabled. (This idea works for most `*.json` files, I'm not sure how this will work for `Techs.json` and `Policies.json`)

**Comment by SomeTroglodyte** [comment]
And you would be responsible enough to not add the flag to... a worker? But I get you, I had the idea as well.

**Comment by SomeTroglodyte** [comment]
Oh, and this couldn't work without basing on or replacing #2380, so I'd better not start coding.

**Comment by u-ndefine** [comment]
I am responsible enough and will not destroy the `.json` files. I will work on a terrain mod.

**Comment by yairm210** [comment]
I have a good idea for this, I'll get on it ;)
