### ISSUE TITLE
Translation request: translate Google play text into Russian

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#239]
Help wanted!

**Comment by zamonitorom** [comment]
Hey,can I help?

**Comment by yairm210** [comment]
Absolutely!
All I need is the text to display in Google play for Russian users

Wednesday, 07 November 2018, 10:07am +02:00 from zamonitorom notifications@github.com<mailto:notifications@github.com>:


Hey,can I help?

**Comment by zamonitorom** [comment]
HI! I'm so sorry for a delay, there is a russian text for the google play page.

Открытая реализация популярной игры Civilization 5 под платформу Android!
Быстрая, без рекламы, без дополнительных разрешений!
Создайте свою империю, исследуйте технологии, расширьте свои города и победите врагов!
Мир ждет! Сможете ли вы построить цивилизацию, которая превратится в империю, и выдержит испытание временем?

Если у вас есть пожелания, вопросы и предложения, вы можете оставить их здесь:
https://github.com/yairm210/UnCiv/issues
Кроме того, мы будем рады любой вашей помощи!
По другим вопросам, а так же с предложениями по поводу перевода игры на другие языки обращайтесь на почту:
yairm210@hotmail.com
Про в Java, Kotlin, C#? Можешь помочь нам тут: https://github.com/yairm210/UnCiv
Если вы играете на 7 или 10 дюймовых устройствах, пришлите пожалуйста скриншоты!

**Comment by yairm210** [comment]
Thanks!!
