### ISSUE TITLE
Irish Civilisation 

### ISSUE THREAD

**Issue by sirsyolo** [yairm210/Unciv#2397]
Would be great if sometime an Irish nation would be added
The Irish nation would be different from a potential Celtic nation. Here are some suggestions for the civilisation
Nation: Ireland
Logo: 
![Screenshot_20200413-023034_Google](https://user-images.githubusercontent.com/63567339/79085073-050e9c80-7d2f-11ea-9e7f-9171bdb316c0.jpg)
Leader - Brian Ború
Other possible leaders - 
Grace O'Malley/Granuaile
Wolfe Tone
Daniel O'Connell
Padraig Pearse
Michael Collins
Perk: Guerilla Warfare - all non-ranged land units can move after attacking enemy land units
Unit: Fiann - Replaces Longswordsman
No maintenance cost
+1 gold every 2 rounds
Strength 25 vs 21
Movement 4 vs  2
Logo could be something like this:
![Screenshot_20200413-022924_Google](https://user-images.githubusercontent.com/63567339/79085050-e5777400-7d2e-11ea-9b9f-38cbadf07734.jpg)
Unit: Volunteer - Replaces Rifleman
Cost 200 vs 225
Strength 35 vs 34
Movement 3 vs 2
Unique building: GPO/General Post Office 
Replaces bank
+3 gold
+30% gold
+1 Great General points
I'll be happy to answer any questions

**Comment by JackRainy** [comment]
There is a page, how to make a mod which will add it.
https://github.com/yairm210/Unciv/wiki/Mods
You can do that!
There are already the examples of the mods, which you can use for an inspiration.

**Comment by sirsyolo** [comment]
Hi there,
Just wondering, how do you access the directories mentioned in the wiki?
Thanks
