### ISSUE TITLE
New messages

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#2404]
I have more ideas for messages you receive from AI players:

CITY SETTLING LIMITATIONS
REQUEST
I couldn't help but notice that you're expanding in territories that I consider mine. Please stop settling cities near us.
REFUSAL REACTION (POSITIVE RELATIONS)
You do know that this will only bring tension between our peoples, right?
REFUSAL REACTION (NEGATIVE RELATIONS)
It seems that you are beyond reason. What a shame.
ACCEPTION REACTION
Excellent. Hopefully we'll keep finding a common line together in future.

PEACE REQUEST
We can't let war define who we are. It is time to make peace.

DENOUNCING
It is time to reveal your sins and crimes to the entire world!

FRIENDSHIP
REQUEST
It's hard to find true friends in this world. I'd like to have a Declaration of Friendship and have the whole world know the bond that ties our people together. How about that?
ACCEPT
Yes, let's work together.
REFUSE
Sorry, we can do this alone.
ACCEPT REACTION
This makes me happy.
REFUSAL REACTION
Maybe another time, then.

**Comment by logicminimal** [comment]
already included in either diplomacy thread of missing civ5 features thread + ourdated, close?
