### ISSUE TITLE
Produced land units are still placed in water.

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#2406]
![image](https://user-images.githubusercontent.com/63000004/79153669-836e4b80-7dce-11ea-93c3-4f3949588df7.png)
I still say that settler should have been placed in the north tile - or production should habe been halted until the general is moved? Do we not know for sure how Civ5 handled this?

I'd plead for different rules for 3 cases:
- Bought - Placement radius 0: Implemented
- Produced: Placement radius 1 with preference for same domain.
- Gifted (Policy, city state): Placement radius 3 so none is lost??

**Comment by yairm210** [comment]
We can prioritize land for land units, doesn't sound that difficult

**Comment by SomeTroglodyte** [comment]
Simple solutions are often best.
