### ISSUE TITLE
Add mountains

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#241]
The most importation part is how to treat impassible tiles - well probably find a few bugs from this

**Comment by AcridBrimistic** [comment]
Maybe it should be passable, but only with 'Flight' researched? Maybe even an alpine troops unit that could move on tundra and mountain as if they were roads.

**Comment by yairm210** [comment]
The "impassible" problem are most solved. I could go around sticking mountains randomly everywhere, but I wonder if there's a nicer way of doing it.

**Comment by yairm210** [comment]
Can finally cross this one off the list!
