### ISSUE TITLE
I am barbarians after update to version 3.7.1

### ISSUE THREAD

**Issue by Alanalanalanalanalanalan** [yairm210/Unciv#2411]
Hi there guys,

Love the game. Something fun to do in quarantene. 

I am playing with a group of seven, you recieved an email the other day from one of us about how the game had stopped working (lorena trivellato).

So i updated to 3.7.1 to resolve the problem. Now when i join our multiplayer i am given barbarians, tried a few different save and multiplayer files. Happens with all.

I have attached the most recent autosave and multiplayer file as you had asked of Lorena. Any clues what's up?

Thanks and regards

[MultiplayerGames.zip](https://github.com/yairm210/Unciv/files/4476554/MultiplayerGames.zip)

**Comment by JackRainy** [comment]
I can suggest you the next trick:
1) Go to your game folder and find the file : `android\assets\GameSettings.json`
2) Open it by any text editor
3) Find the text like: `userId : abc12345-eda3-12e4-123f-12d12121dcba`
4) Replace it with text `userId:a957800c-0420-45ba-b447-2fab4224cb9c` if you play for Greece
5) Try to load the `Autosave-Greece-140` file

**Comment by JackRainy** [comment]
Also, your friends should check the same file for their values:

Babylon - f5d9f236-ee08-45d4-bf5d-7a4aa73b12be
Iroquois - 5d01e69e-5274-4dd5-8e91-b16def2bc958
Greece - a957800c-0420-45ba-b447-2fab4224cb9c
Egypt - f0f7fb55-28e3-4c77-80e4-5dcfc8a08ccb
Rome - cbae2aab-cdbc-4d24-982b-2d5dcdfe9953
Japan - 1bfa7858-730e-4508-8aa8-8a656b220445
Persia - f58b3743-600f-4b1c-8a69-74469b5bb565
Arabia - 43d66a24-f40e-439f-8be6-4f8a99133a12

**Comment by Alanalanalanalanalanalan** [comment]
Thanks Jack,

Worked a charm. I am trying it out with my friends now.

Much appreciated.

Regards,


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
