### ISSUE TITLE
Map standard description?

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#2423]
Could the technical description of save/map files be added to the documentation somewhere? I guess it's some base64 list, but haven't been able to find out the details.

**Comment by yairm210** [comment]
Where, exactly?
Who would this serve?

**Comment by krijnsent** [comment]
I would like to make some maps like the earth map, the Mediterranean map, etc, but find the current map editor not workable for that purpose. As this is an open source project, I expected to find the map file format somewhere in the documentation (e.g. on the site, not in the game). To answer your second question:  it would serve mod/scenario&map makers.

**Comment by yairm210** [comment]
Closing this as 'not interesting'. You may consider this a wontfix.
