### ISSUE TITLE
New game start throws 'could not generate map' popup

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#2455]
**Describe the bug**
New game with City states, possibly only with starting era = ancient, crashes claiming the map is bad (it's OK).

**Cause**: addTechnology for the aiFreeTechs calls previousEra = civInfo.getEra(), and that isn't hardened against an _empty_ tech.techsResearched.

Not sure about the internals of the era system or why city states but not competitor AI's now start out with no tech, so I'll not attempt a fix, though a simple if isEmpty() return "whatever" in getEra() _does_ allow a clean-looking game start.

**Comment by JackRainy** [comment]
Is it what I have fixed in PR #2450 ?

**Comment by SomeTroglodyte** [comment]
Looks very much like it. Harden civInfo.getEra() _anyway_?
