### ISSUE TITLE
Korean fonts are not displayed(Solved!)

### ISSUE THREAD

**Issue by oolrim** [yairm210/Unciv#2488]
Hi. Before I start writing, I would like to thank the developer who made the great game. this text translated by Google Translator. Please understand if the text is awkward.

 I'm linux user. The game was run with 3.8.0 Unciv-Linux64.zip. When the language is selected as Korean, the font is displayed in a square shape. Perhaps, I think this is because the font file does not contain Korean fonts.

![font error](https://user-images.githubusercontent.com/64135330/79970298-a931d980-84cd-11ea-883e-66bfb0fcf302.png)

 For this reason, ask: **Is there a way to change the font file to something else?** If it is possible to change the font file, I want to test it after changing to a font file containing Korean.

 Thank you for reading the long article and solving it together. Be careful with the corona virus and always be healthy. See you later~! ^o^/

**Comment by yairm210** [comment]
The font is taken directly from your device... if it's squares that means your device doesn't have a Korean default font installed, probably?

**Comment by oolrim** [comment]
> The font is taken directly from your device... if it's squares that means your device doesn't have a Korean default font installed, probably?

 Which font file of the device is imported directly? Is there a font file set as the default? If there is a default font file, can you tell me the name of the font file? To check if the font file exists on my device. You may be busy, but I would appreciate it if you take the time to respond.

**Comment by oolrim** [comment]
I found and solved the problem ! The following solutions are described based on Unciv-Linux64 among release versions. (I am using Linux mint. Therefore, it is explained based on Ubuntu.)

 There is a file called 'fontconfig.Ubuntu.properties'(Find and edit the file for your Linux distribution.) in the folder called 'Installation folder' / jre / lib /. This file contains the settings of the Korean font file.

filename.NanumMyeongjo = / usr / share / fonts / truetype / nanum / NanumMyeongjo.ttf
filename.NanumMyeongjo_Bold = / usr / share / fonts / truetype / nanum / NanumMyeongjoBold.ttf
filename.NanumGothic = / usr / share / fonts / truetype / nanum / NanumGothic.ttf
filename.NanumGothic_Bold = / usr / share / fonts / truetype / nanum / NanumGothicBold.ttf
filename.NanumGothicCoding = / usr / share / fonts / truetype / nanum-coding / NanumGothic_Coding.ttf
filename.NanumGothicCoding_Bold = / usr / share / fonts / truetype / nanum-coding / NanumGothic_Coding_Bold.ttf

Based on the above,

/ usr / share / fonts / truetype / nanum /
/ usr / share / fonts / truetype / nanum-coding /

... in this folder path,

NanumMyeongjo.ttf / NanumMyeongjoBold.ttf / NanumGothic.ttf / NanumGothicBold.ttf / NanumGothic_Coding.ttf / NanumGothic_Coding_Bold.ttf

... you can see that these font files are loaded and written. Therefore, if there are no files in the path, a square shape text is displayed.

The solution is:

/ usr / share / fonts / Since this path requires 'root authority', open the folder with root authority and work.

/ usr / share / fonts / truetype / nanum /
in
NanumMyeongjo.ttf / NanumMyeongjoBold.ttf / NanumGothic.ttf / NanumGothicBold.ttf
Install these files. And...

/ usr / share / fonts / truetype / nanum-coding /
in
NanumGothic_Coding.ttf / NanumGothic_Coding_Bold.ttf
Install these files. Note that the NanumGothic font file is distributed with the following name.
NanumGothic-Coding.ttf / NanumGothic-Coding-Bold.ttf
Therefore, all '-' must be replaced with '_'.

After completing the above, Unciv will be able to print Korean fonts in Linux os.

 Thanks to yairm210 developer for the help. Also, thank you for making a great art and giving pleasure to many people. Be careful with the corona virus, and always be healthy. Have a nice day!

**Comment by yairm210** [comment]
Thanks for this, if anyone else has this problem I'll refer them to your solution =D
