### ISSUE TITLE
In the map editor, is there a way to build mine on a non-hill tile  and oil well on a water tile?

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#2489]
In the map editor:
A mine cannot be placed on a non-hill tile even if a resource that requires it (e.g. gold, silver and gems) to be harvested is present on the tile.
An oil well cannot be placed on a water tile even if there is oil on the water tile.

**Comment by SomeTroglodyte** [comment]
Yes, I'd say a bug. TileEditorOptionsTable.normalizeTile() doesn't take this into consideration. One of us will look into it soon.

**Comment by SomeTroglodyte** [comment]
Had it done yesterday, then when I did the PR github went to that nice CSS-dynamic error page with the git octupus falling into tha canyon.. An then the local git on my other rig annoyed me so royally I deleted the repo to recover. It deleted its own project-specific .gitconfig file! Sorry.
