### ISSUE TITLE
Stolen Territory

### ISSUE THREAD

**Issue by plodonk** [yairm210/Unciv#2493]
A notification appeared saying Japan (AI) has stolen territory but I have no idea what that means and I cant find any information in or out of the game about it

**Comment by plodonk** [comment]
So I just noticed it happened again and it's because they're encroaching using a citadel on my territory. I dont seem to have any recourse to this other than war with an ally. It seems broken.

**Comment by JackRainy** [comment]
Yes, they can steal your territory by citadels. You can also do the same to them. 
Be careful choosing the "friends"...

**Comment by plodonk** [comment]
I appreciate the response but it does seem like an unnecessary mechanic, I have 5 cities starving because a citadel was set up in an inconvenient place and I have no way of getting the territory back without invading allies.

**Comment by SomeTroglodyte** [comment]
https://civilization.fandom.com/wiki/Citadel_(Civ5) - I believe they work as intended.
I think Jack's decision to make an exception and adopt G&K rules for the Citadels was a good one. 

Maybe help out by researching more specific info on the workings in the original? Or, if you find they break the documented rules and can document it (via savegame + repro instructions) that would also be helpful.

On the other hand, if Unciv properly emulates its role model, then discussion about game rules of said original belong elsewhere, sorry.

**Comment by yairm210** [comment]
Not a bug - working as intended
