### ISSUE TITLE
Resizing the game window resets the game to main menu

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#2503]
**Describe the bug**
When the game window is resized (Desktop version, of course), it resets the game screen to main menu, which is quite annoying. Especially, when I do debugging and resize the window quite often.

**To Reproduce**
1. Run the game.
2. Got to the World screen
3. Resize the window.

**Expected behavior**
The same screen should stay.

**Additional context**
In the `UncivGame.kt` method `resize()` calls `resume()` which does `setScreen(MainMenuScreen())`

Initially, the bug was reseting the game to the WorldScreen (e.g. if I was on Tech screen or EmpireOverview screen), and of course, reset from the WorldScreen to the same WorldScreen was not a bit problem. But now it is really annoying since you need to resume the game every time.

**Comment by yairm210** [comment]
This was done because of Android.
It has an annoying tendency to resize things, and if you stay on the previous size then things are either unplayable or look really bad.
Agree that now we can have UncivGame.resize() call the currentScreen.resize(), and implement stuff there.

**Comment by SomeTroglodyte** [comment]
Not to forget this throws you out of a map editor session w/o saving changes. Sometimes any focus loss without even resizing is enough - so I doubt taking things from the resize event can cover all bases.

**Comment by yairm210** [comment]
The map editor part already existed beforehand, and now we have a chance to fix this as well ;)
