### ISSUE TITLE
Choose specific victory conditions on new game

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#251]

**Comment by theodorthegreathe** [comment]
And disable conquest victory if game is started with 1 player only

**Comment by denrique88** [comment]
Is this issue still to do ? I'm new with Kotlin and would like to practice ! :)

**Comment by yairm210** [comment]
@denrique88 Absolutely!

Since you're new I'll give a basic outline of the assignment:

- Create new Enum of VictoryType
- Create list of victory types in GameParameters (default value: list containing all the victory types)
- Add table for enabling\disabling victory types to NewGameScreen
- Toggle victory condition and victory progress display in VictoryScreen according to the victory types in the current game

I could give more detailed instructions, but since this is a learning assignment, we'll do it the proper way via CRs :)

**Comment by denrique88** [comment]
@yairm210 Thank you for the informations !
I don't know what you mean by "we'll do it the proper way via CRs", but I started working on this issue this evening. I don't know if I should put a tag on the issue while working on it. ;)

**Comment by yairm210** [comment]
Your comment here in the issue is good enough :)

**Comment by denrique88** [comment]
I have put a choice with programmatic add of checkbox in the newGameOptionsTable but I'm not satisfied with this. It take too much place and it seems messy.

<img width="578" alt="Capture d’écran 2019-06-12 à 08 26 39" src="https://user-images.githubusercontent.com/30407084/59328112-d7f6f500-8ceb-11e9-86cd-a35157ab5abc.png">

Do you have a different idea ? I can't use a selectbox because the user should be able to choose multiple victory conditions.

**Comment by yairm210** [comment]
You could make a button for each victory type - when enabled, colour is green, and when disabled, colour is gray

**Comment by denrique88** [comment]
I think that this way is not too bad :

<img width="687" alt="Capture d’écran 2019-06-13 à 23 14 26" src="https://user-images.githubusercontent.com/30407084/59467893-14803900-8e31-11e9-8ae8-27e291c836b6.png">

I didn't find how to reduce the size of the checkboxes, at the moment...

I saw that you've added the enum for VictoryTypes. So I deleted mine.

**Comment by yairm210** [comment]
Looks good!
Issue a pull request and I'll merge it!

**Comment by denrique88** [comment]
I did the pull request, but I didn't find how to link the victoryType I created in newGameScreen and newGameParameters with the game itself and the victoryScreen. So I don't know how to use it to determine if the player wins the game.

I would be curious about this. :)

**Comment by yairm210** [comment]
I'm pushing my changes now, you can review what I did.
I accessed the victoryTypes from game.gameParameters.victoryTypes in all cases.

**Comment by denrique88** [comment]
Ok, I understand. Thank you !
