### ISSUE TITLE
portuguese character ã is not showing

### ISSUE THREAD

**Issue by guilherme-peev** [yairm210/Unciv#2510]
**Describe the bug**
Portuguese character ã is not showing

**To Reproduce**
Every time the character ã should appear, it doesn't. So if you just look at the upper right button inside the game you will see "Viso geral" written, instead of "Visão geral".

**Additional context**
Version 3.7.6-patch1

**Comment by SomeTroglodyte** [comment]
Can you think of any other portuguese-specific characters apart from ÃÕãõ that might be missing as well?

**Comment by guilherme-peev** [comment]
That's the only one I've noticed so far. But I've being playing the game
daily basis. If I do notice another character, I'll inform it

Em Sáb, 25 de abr de 2020 11:29, SomeTroglodyte <notifications@github.com>
escreveu:

**Comment by guilherme-peev** [comment]
Well, I don't know if it's missing, but I can think of a few:
ÂâÊêÎîÔôÛûÀàÈèÌìÒòÙùÁáÉéÍíÓóÚúÇçÜü

Em Sáb, 25 de abr de 2020 11:29, SomeTroglodyte <notifications@github.com>
escreveu:

**Comment by SomeTroglodyte** [comment]
Muito obrigado. All of those were already supported:
![image](https://user-images.githubusercontent.com/63000004/80317971-3b581b80-8807-11ea-9521-1a3ee72a86b0.png)
