### ISSUE TITLE
Build errors with Gradle 6

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#2514]
## Symptom:
Starting a debug session for the 'desktop' configuration (not affected: building android, building jar, debugging android) errors out like this:
```
FAILURE: Build failed with an exception.

* Where:
Initialization script '/tmp/DesktopLauncher_main__.gradle' line: 18

* What went wrong:
A problem occurred configuring project ':desktop'.
> Could not create task ':desktop:DesktopLauncher.main()'.
   > Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'DesktopLauncher.main()', but there is no existing task with that name.
```
This happens even with a freshly installed Android Studio and a fresh clone as of today (taking care to clean out anything related under .git, .gradle or .config), and both on Windoze and Linux.

## Cause:
This is as far as I can tell a bug in the IntelliJ IDEA up to 2019.2.x, fixed in 2019.3, but still showing in Android Studio 3.6.3 current as of today. [Here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004383639-How-to-add-Gradle-options) is a passus: "The warning occurs because of the Run delegation feature enabled where IntelliJ IDEA generates the special Gradle code to run the project run configuration in the temp directory. This generated code triggers the warning." - of course, you need gradle <=5 for this to be _only_ a warning.

## Workaround:
Unfortunately, AS hides some IDEA options, specifically the Run delegation controls. So the only WO I'm aware of that works is going into gradle/wrapper/gradle-wrapper.properties and replace "6.2.2" with "5.6.4". Since the file is under git control, this will revert every time you switch branches. No way to have git relinquish its grip on the file without dire consequences, not that I'm aware of.

## Request:
Please tell me how you deal with this. Do you not run desktop at all? Did you install IDEA 2020.1 over AS and somehow got it to not lose the Android Studio integration features? Any local workaround scripting not in the repo? Maybe a setting not visible in the UI?

**Comment by yairm210** [comment]
I just run the regular build:desktop and it works fine
But since there are no real advantages to sticking with 6.2.2 instead of 5.6.4, and other people have encountered this as well, backtracking to 5.6.4 seems like the simplest option at the moment.

**Comment by SomeTroglodyte** [comment]
Wait a minute - I tried to find out exactly what you're doing differently. Since the JetBrain guys will come around to lift Android Studio to base on 2019.3+ of IDEA sooner or later, this will fix itself. It's just super curious that I run into something that looks like a well-known problem and the team here doesn't...

So, if you revert that one script - we all should look out for the AS updates. The two last ones named its version as 192.7142.36.36.something - if those first 3 digits correspond to the IDEA major version, an 193 there and we could keep gradle 6+.

**Comment by bitofagit** [comment]
![image](https://user-images.githubusercontent.com/59574653/121873972-d60f0480-ccfe-11eb-8b09-2b812f5eaabe.png)

Hey guys I'm getting a few error messages when I try to run build.gradle. Would anyone be able to shed some light on it for me?

**Comment by SomeTroglodyte** [comment]
Try Tools-> SDK Manager. I think it's not there when you don't need it, so I can't tell you exactly how to nod off that license, but it's there somewhere. But honestly, the first run wizard should have - ah no you get tools 31 from that and Unciv orders 3.0.2 - yes you have to DL the SDK and build tools Unciv wants _and accept their license_. That is something the scripts can't do for you.
