### ISSUE TITLE
Device sleeping resets turn to beginning (android)

### ISSUE THREAD

**Issue by drgrits** [yairm210/Unciv#2540]
When my Android device sleeps, game returns to "resume" "new game" etc screen. When resume is selected I am returned to the beginning of the turn. Before I would resume progress mid turn under same circumstance, unless app was restarted either on purpose or by opening many other apps. Very frustrating in mid and late game with complex turns. This happens as of update I received today (4/28/2020).

Otherwise I love this game/ project and appreciate the constant work y'all put in! 😍

**Comment by yairm210** [comment]
Already fixed, will enter 3.8.4 =)
