### ISSUE TITLE
Suggestions for the 'new game' dialog

### ISSUE THREAD

**Issue by AcridBrimistic** [yairm210/Unciv#2549]
![defaultpage](https://user-images.githubusercontent.com/18503603/80703362-4b177e80-8aeb-11ea-8d3e-c462f7ad0655.jpg)

Here's what the current 'new game' screen looks like.  In my opinion, it's confusing, overwhelming, and cluttered.  I'm going to list out several issues here, and at the end, propose changes.

1. Font
The font used, while not necessarily bad, just isn't pleasant to look at.  Let's replace it with a common free font, like Droid Sans Bold.  Also, add some shadows to distinguish the text more easily.

2. Layout
The options are all over the place with inconsistent spacing and strange capitalization.  I separated them into three categories, 'Game Options', 'Civilizations', and 'World Options'.  I also moved them to different sections of the screen and made the spacing more consistent.

3. Colour
The dark blue and cyan combo is filthy at best.  The game is hard to play in bright daylight, even on full brightness.  And playing on a real monitor is disorienting.  The buttons and dropdowns look depressed and are hard to make out for colourblind users.  Let's change the theme and make the contrast ratio a bit nicer, how about 3.1:1 against the background?

4. Buttons
The lack of iconography, the strangely coloured buttons and weird placements make the UI confusing to look at for newer users.  Let's move the primary button "Start Game!" to the top of the screen, get rid of the useless "Close" button, and make it green to indicate finality.

5. The 'players' menu
The contrast ratio between the civilization box and the background is 1.01:1, making it invisible in bright conditions and for colourblind users, and hard to see even with perfect eyesight.  I redesigned this altogether, it's just a nightmare as-is.

6. Unnecesary options
The 'advanced settings' should be in the main menu.  Why is it possible to remove the top player?  Shouldn't that always be you?  'Map type' doesn't even have other options, so just change it to the generation type and put a 'load map' button down at the bottom.

The checkboxes below the victory conditions seem like they should also be hidden, maybe in the main menu?  Either way, they're both hard to find and strangely specific.  To me, 'Online Multiplayer' is a big deal, and should go into a completely separate menu.  The rest should be in the aforementioned advanced settings.

Here's my suggestion.  It's not perfect, and there are lots of flaws, like the 'Civilizations' section and the slider, but I think it would be much easier to read for new users and removes a lot of clutter.

![part1](https://user-images.githubusercontent.com/18503603/80705424-19081b80-8aef-11ea-8e93-fac492a773eb.png)

**Comment by SomeTroglodyte** [comment]
While I agree your mock-up looks much nicer in its organization, I would strongly disagree on some details. 
* One - is that... Puce? Come on! This is a Civ, not something bubblegum- or barf-themed. 
* Two - Close is indispensable on desktop? (Up until picker screen keyboard support arrives) 
* Three - those advanced settings are map generator specific thus moving them around two corners is not user-friendly. But - no prob, "Game Difficulty" has no business in the third column anyway, it belongs in the first, so there's your room for that button. And - those options really allow for some extreme map variation, variety is good, therefore these options important be they. 
* Four - you remove some obscure, but right now (I believe) fully functional varieties of Unciv: hotseat multiplayer and spectator mode. 
I hope you got I'm only 95% serious here.

Another idea: If need be we could even dispense with the 'Load custom map' button - have it be last entry in map type dropdown, when selected load dialog pops up, after load the chosen map name becomes extra dropdown entry... No not really, people would not find it easily enough.

Big #5: Some of this is styling that should be consistent throughout the game - a skin.
Question: How did you do that mock-up screenshot? Tools?
Direct follow-up: How about trying out scene2d skin editing tools for us and if you come up with a skin closer to your ideas (colours, fonts, icons and such stuff would be customizable) you could present it here, and we coders could try the geometry aspect? [badlogicgames](https://libgdx.badlogicgames.com/tools.html) doesn't have one, but a search readily turns up a few.

**Comment by AcridBrimistic** [comment]
Most of it is just default Gimp filters and tools with Clarity icons and some things I made manually myself.

I do agree with many of your points, the organization is the main thing here, not the skin.  There are hundreds of design models, accessibility guidelines and visual finesse options that this game breaks.  When a new user loads up the game, it instantly communicates to them that this is an amateur passion project rather than a real game.  Which is a shame, because the way the game works, is really good (it's Civ V after all)

I would be happy giving feedback on the UI elements as they are, but I can't exactly do this design thing full-time, I already have a lot on my back.

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/82479993-d036f780-9adb-11ea-8570-6231638d3429.png)
