### ISSUE TITLE
AI should be able to assign population to be specialists

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#255]
Specialist gets the same treatment as a tile - assignment is by stats alone, plus a tiny bit to give it at edge when being equal, due to the GPP it produces.

**Comment by ninjatao** [comment]
Looked through related code. Maybe we can evaluate most potential specialist position in autoAssignPopulation() and assign the free pop to specialist if it's better than tile? Of cause, unassignExtraPopulation() should no longer remove specialist before tiles. Anything else?

**Comment by yairm210** [comment]
Nope, that's about it

**Comment by ninjatao** [comment]
Food 4 tile now gets lower priority than most specialist position(they both get 3 value in auto rank, plus a GPP bonus for specialist). But a better arrangement should sent a pop to food 4 tile for population growth, then assign the new pop as specialist.
Maybe we can give food a bit more weight? Or else, AI cities now tend to have much fewer population than before.

**Comment by yairm210** [comment]
Sounds good

**Comment by ninjatao** [comment]
Pushed a new commit. Now 4 food tile > 2 food + 1 production tile > 3 science slot > 3 food tile. I tried a game with King AIs, the sizes of their cities are similar to the sizes of mine.
Please review the code and let me know if you have any concern.

**Comment by yairm210** [comment]
Functionality looks good, see my notes there on syntax

**Comment by ninjatao** [comment]
Where are your notes?

**Comment by ninjatao** [comment]
<img width="1225" alt="screen shot 2018-12-09 at 1 35 36 pm" src="https://user-images.githubusercontent.com/6846049/49693785-c0617700-fbb7-11e8-914c-d2ae90f34a88.png">
 
In here? I found nothing... Or do you mean comments in the code files?

**Comment by ninjatao** [comment]
There lefts one problem: 
Population assignment only occurs then population increases or decreases. AI city population may be stuck after conquered, as most population are assigned as specialists because only 6 tiles are available. When city border grows, population assignment does not re-check working populations.
This only happens rarely, but allowing AI city to re-assign a pop every turn will be better.

**Comment by yairm210** [comment]
I'm pretty sure it already does

**Comment by ninjatao** [comment]
Checked. AI now can re-assign pop between tiles, but not from specialist slots. I assigned all pops in a AI city as specialists, AI cannot re-assign them to tiles. I failed to find related code. Can you show me where it is?
![screenshot_20181210-103205](https://user-images.githubusercontent.com/6846049/49707639-20632680-fc67-11e8-8462-95c33c315cef.jpg)

**Comment by ninjatao** [comment]
Found it. Pushed a new commit to resolve this.

**Comment by yairm210** [comment]
Looks like this is done!
