### ISSUE TITLE
Turn initialization after leaving the game

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2550]
**Describe the bug**
Every turn is initialized when I leave the game. Before I press "Next turn" button, I have to save my every progress manually. I think it started v3.8.3 update on Google Playstore. "Leaving" includes 1) quitting the game, 2) occasional task conversion (receiving SMS), 3) going to the main menu, 4) turning off the screen.

**To Reproduce**
1. Start a turn by pressing "Next turn" button.
2. Look around and remember the initial state.
3. Make any change except pressing "Next turn". You can move unit, found a city, capture enemy city, arrange city people, select tech or policy, or make diplomatic suggestion.
4. Save the change to compare.
5. Leave the game. You can quit the game,(It says "Do you want to quit the game?") press multitasking button, go to main menu, or just turn off the screen.
6. Return to the game. You must be seeing the main menu.
7. Press "Resume" button.
8. Game is initialized to step 2. Before v3.8.3 it restarted on step 3.

**Expected behavior**
See step 8.

**Screenshots**

**Additional context**
I think it might be a feature. But for me it's more problematic than heating or lagging. I take time to press "Next turn". So I occasionally turn off the screen or go to another app. When I come back and resume the game, I have to restart all the process. Save & Load system works perfectly. But it's inconvenient to remember saving the progress before leaving the game.

**Comment by yairm210** [comment]
Same as #2540  - fixed in 3.8.4, please wait for the rollout to reach you =)
