### ISSUE TITLE
Android app hangs on smiley face screen (after April 30 update)

### ISSUE THREAD

**Issue by soggerr** [yairm210/Unciv#2552]
**Describe the bug**
When launching the app, the smiley face appears, spins, then stays on the screen forever

**To Reproduce**
1. Updated to most recent Play Store Version April 30
2. Launch App

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
Smiley face should disappear and show menu to resume/start game

**Additional context**
Tried to force close app and re-launch without success. Also tried rebooting, no success. 

(Haven't tried clearing app-data because I have a multiplayer game in progress and don't have my keys saved anywhere.)

**Comment by yairm210** [comment]
You're talking about version 3.8.4 - this was fixed, and 3.8.4-patch1 is rolling out, if you update the game it should work fine =)
