### ISSUE TITLE
City with garrisoned unit cannot bombard an enemy one tile above it

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2553]
If your city has a unit stationed inside of it, then you cannot bombard an enemy exactly one tile above that city and can only select the unit within

![Screenshot_20200430-150545_UnCiv](https://user-images.githubusercontent.com/64375454/80754462-b3b72900-8af4-11ea-8534-c77119e505cd.jpg)

<Details>
<Summary> game example </summary>
H4sIAAAAAAAAAN1bW2/bOhL+K0KfpcC6X95cnzYN0LTZJAddoMgDLdOxcGTJq0t6fIL89x2KkkhJlD1uzwK7iwaJLA0/Dodz+YZyX+PkJUmTv0iV5FkZfX+Fz1/InkbvSbEmRUKyUqd/HtK8oJvHJKVM5M/I0o+R96bDlQ1XVnNlOHBp80sPLs3+udEKCFkuJqTYlQNXHaqAYmOCdjj/Y4pp2GV7W9x1e1S3RQVJdzCV20zlN5/ZUvx+0lZTdtNw+udOr0qrXjPeMJs//LcjNLL6cYYp4PildMMRVmtnFQraPYQ0oH1uCouYwrhiYncw3hXj+ardfi2+MI2wtTyfsKzX4wlJR2yq0RrEFrcc4QhW81Bsjt8v0+rt7okFCb/qzDfSS6jA1+L2yJZYkYD2+1WwK2l5klcawmBBj273EE5/ZUqGF9vBXaAF5MsVu9I7gRgqoQgnMyTfE9rLNrCFx5ji0umX7/aGFfslzdo6tDlYkNvfE2aUNkNA+m9P+nOebmi2fIYs8JrV+zUtvm6vxT1TLyuWJz6RwyHJaFlGdgDmfC4oqe5ofkhp9Np8uKYZLUh6lydZBcMsu5Mpyjxr776+vemHPE3ihM3Grg/1YZnSomIpqDoeaNRPrb+QtKbRu3egY0XjXfTKfpf3tKSkiHd0E31fQXarijpmaU5fkZRmG1LoXw9VEpf6Lal2dE/aa9ChOOqf8qKkaxL/od0nmyR71m+TjP15LJrVPevvizz7i2rf8uIP9vGBQBplz3dwb0dpqi/Z1IB0l1cV+7vMkj1JtU91uSbZBm58K5KKDVk+F0lcp1Vd0Kc3/SWJwYrHW5KRZ1o0doCkXCWUZ+fqKC8FTLOuk7R6D7+YliBzm8PW0KzS70hKYqpfF4BUHJ/0WBr3j5qCwb5/yasdjIJndVHAGBn6pvy9pMUDrSK4Q990NvVDRZqtYSUBKgNIRa+t5g/N1kcWeMw2rzOmzCp5gTKyPqZg8mQTEXft+haxDcvzQsPxLNsIPHdhBOHWNQM/3CwWWz0pvxbJc5KRdEUOSUXSZnY9zeOmQkVy9Ga8TvEJmH+krcw2zzetPo4vPwn18kDjhKRJ2bpY1de0uaQg50JjnJbkoDXk5CBXKKk+Dq47GenWOKnKuab586T/AIeTa7ExSDLjue3p3PZ4IlOtB58PZuTet2IhChY1dUERuOk3CfCDPYmP0et1QWkMYd7egoi6zTfJNoHIjl4fKkpYjDzSAjwffBwmWIC7pOS5XIHPVJv8B+weuFyV0s2qmfULRPDvkCNgHeCrtFi1c/OJ3t4U5GSwQGdsBE8Ups4g3tggooKLuuBNDdYbu//TecmboDISXxk7hgQpuZS0S9IaJF88RX5GsIYrKmKntSut3JVW7gl5wYm6stmzBWe8fqsvqspCyu96Uxd3JfW8GU9V0rCZ4utMa/CAoM0WZD5QwhbQsh6Tmi1xPcke0gjJo6S1DbgeX/m4Wqt537iGB6NqrmaDEgd0JItb0rUprkXJnzBGvmG2dD2gCZwcRJblDFjCmBCYrD6cJQTuDB/I8gpySdz3KiTm+T5OCWDH+f6qziA5XaX5cxJfyZ3N1ee2gCybIVDNcsga0SuBJa+jxdXCd9xFGJj6M3yw/IUbBJarF/DBbR4swP0r+mcVvfvOCvw1U0/7nKwLVlm1HSm1NaWZ1tRiLck0om1JQX6Qo5ZCrX8HlvppXfvaN0z3T4M1FMxhuILLTANr7o/a928E8mxePGk/QL/ywGjIhimX14VWdTmYcaZDSo60eGSc6lO9J5lEvMgmP8Cwu+7G98/0mZXPvf41TZ4Zuzrqn2GJgPwhTSrK+NEmafQGItI8f9I7rrgcgbktYVxxChGZwVvL30p4nsX06/YzKavgsS7Y6k1TN63pD+d85U12V+TgN2Dd1w8ZUAhKCyg2kWdy0P9JOsg1f8w73aPv0tL0VcPaYsDcJWle5gfYjBvQo9dixdxKe6AFkEpggowkwpIo0CptBYZtFQQ3ej7qq10CNBr0uCUxkMJG1d2xZEb4sKm5C+pQwmEpq3x/AC/W70ALBqLdMbPr70nWzLqM87psrHddZ4f8x4YW+hLMnWf5/qh/iNlf9pRZBFwmZivlWqV1AZp8IS/gWnxrYCOAq4EuN9kGQAvG3f5qdWE+0iQEjS0CZO6TbWN0BkzaZd3CPlQQpdoDdyn9I7QQLNZAKUZI9tpd/gOuP6SgCBgeWK7+PuFjfzsCxWRO/RF8fVfp9/TAKDVZp1S7I9CJ6Pfg7Dnc3wJphQzW6HUPW1/kZNNC5hlb611KuEnewyoTfglmXDNDwZhlxUzSr4Mwb2SPYR822rLYA8COFMCxaA1DSVrqX+o4BZfQPiZl2cyax39QZii2OTV4WMks3SzjAXhbyoKzhFAt2ZP7fJ1z987XwJu0R5ad4OMXAikWPC7jA9kak5gttnWEjzXbK+0RRP4DnUqbT/VJhj3ZwzBfpwWihdGTPkOMFOMQQHGwXU4YDLsczkZZk7P1tnZokcBwQ9s2HHMRQH+zdgyXmKHlmxvHWjuYJqelf02Ls4R0lJVzHY6L7nAEExHkUhBKZ3BveKrQ8RFxVCMOwzreMqIuEjvSh6df4thBOsNp4KbNjWpCd3DljlQeHp/IynM9nriTjn1T4Vide/6Sa3UgrLZhvWvWuTzX9f0t8Y3QXDiGE/iesTYD13D9BbU2m9DfbuJhq9zuQuNGDwcIZzLnRgMvsk/1yWJne2I8aEokumpL1Lunx2ynoLBBTV/G/6oTNrlnjXZeQchbwGlDavUNaWspqR9tW9SZhvQ3CmwM5gei9DWDLtMw7auGoQ5azRZD2WuKQHIGgcT9Uxxwq849vX6sp8vnjvPdp/qAdnrqOjw+Hx+/n2tTLzmFPdeFiqNY1Xnt+Jje7e3g9dLTI1z5vF7ZiQ7znHijMD4pdQbTic0TGzDfcfYvAS5sOOcc+9RLA6npNIXYyePi0buMaSsq3jXgus9zfaY7sKBIymf7yhMHzt0OdkfPkR2al59BW/bifMsJRVTRcrZdCDPHobn1MS++QJN1LQFEweLtVL/0CdhuwagN0E5glAlgHoCkUuBpKeOHyQvV7uuUzndJzrhLst2uTdpCwmNkrFm3smXy9fYn6H5C3VK1THLfEJmm99/VNE2apa6LwjVN8uKUxLWv8XdNKywdbW63De4xYs0OFJdnKAk3wADXfujEtg88z4wNx3d9Y+2bpuFtYuLSwCcb221kgUPD76qpN+zzw4GCLf9RJ/Efbd/dsOVdXtJMPjAf9+SMtvRC7ennE6/Lt+QQve7JQZ6qqfjlEf7pzbuSFTQa+Z7Lf4aqDnOuoRdgR7EkyQAQ+jl2VKGDN+R1AU6/IuwYFqZVyyX7Q5G/UMZtJDf6CE2Kvm9brt+zpIped5Sk1S5yHM5C2kMJPf8B4dNVbIDa5y1j+ucdOwDqguFOPLFkMXDGF1poN/pvRZKm2s1T87qoTAbMh+UuxjPAF26Euk3GumRRK1jNBpxRxm/T90XoYjxXrTc1c0/UKPMNIdZUiR77mu7L0aBPYLGRsaQBTdAqhwz3FdwDIrt83CUlSzZgkXanfV+1071fD7faHe9bV9uEH+Yk1Vk/zYhzXUb3cInZQO6LMjavcbNjh8tr88Ftv6398kwdYo0JLU8e6YHQFT/0u3qo2HFNe5zXHgRCKamS7VGztDqDoNQYOt10L7XyH+wY7qTlAqXHW1i3OrfaRo9PUDDZ+cdssI50aPlAxWf7CFWSFSxYKi2rkSa37IUPXAyj4sT2yHITMQVaz71QIdPyMZQsbvbpWiZxZ6nmnAFTrmUayd1LmN4Jlmm9TyCbjkZCVJXVYCgnh6jIuoOx7MxuqqF9LpFM57VU80IZTrLy/KTmeNIHoA2Hs3Oap9c6cEkZ/RsQtzPgSOD+BdOvBSjnRyeLqaWqpaaqliprKEsoJ5Ov0l/V7vo1pkTh18iwm9hVHSlI89uqiWfi6Wx5VEcTKplJ75wxaXMGonuzepq9TZbHu+ILtHROB8O8qZ1zbjQ1vTWe8GQ9O1v5setsX7OiYxglehqSv/0j2clQ54fUJ0vx6XTJN+EyB2nzK95yuCC1lLlvJj0gw8hWppyZHIHPOs6vxeV4Ep4pTuf2tlN6LJICbvQssP8+7gkC5uAX1n2V42wqc1R7gC3Q3dc5ThboGcvzI6VfzYpY722/kIJKMLfsAEce3R4qnuq6TumInHaS1/hZ2wX5273Unifa/HHwuT/dDosvpOD4t2rViqb2AkhTBaluUVCIOLQ2v15SmSay8/l14vgz+RWXsu2/g64+HCh7i51dlNMMJZdSKqlOaeoaoEyVSlFshCGjuF+1RrOY7A/NK/Bz5vtbjxy6F4JxXlcXbYV7QXnpvnOIyTeT4HUvoM/uGc8c4/5aTem+Bne6IZiffRLA08TlKpOC2ovbLxBiZPnLHhSqq0TFHwa0L3VOk835sPyVqZ2fn9r+xantn5/awm+jhd9G88yCxpXIw0XGuI5gJ1HoPS1J6qqtru4TsSmcdUmBVbaJU0wbW12VR2pTOedMAvs/KR6GspGYmsO9oIgrC9IUEhkv+DyKVM/DL8VDk5zu/y5gUZHnZp7Sq2dRL6lPOFkPycHF/1U4H4E+E/TPC/rN1wzO43lKvNnlYCBdJeQ8gfB/Lkl3pRU5U/u1m1MN7UzCQ5rHRprHukBpC4lpKjGVh19n4ZALRimmrtfztR1RTtV99TwJQQSVfQE9tXEVVX1QM+PCCDl1SzATfAg5dR6fyQ8IOYyTIrMWRisfqb6PswbHQwj6uN3ieAhBH+dNHA8h6OMcnuMhBH1cTHI8jGDABIPzgkwOIcYnRgj6SDxPiTdbDjGQLh7SRUI6eEgHCWnjIW0kpIWHtJCQJh7SxEBinAelmboAz6wAIadun2eMjJCzsfzSxmUQB5mQDOUL2Zn6hsmsLi4DqzuKmYBHJn5UvURWMIyzI9MkRqsAqX6ArJcB0rwBsl4GyO0PkPUyQLpngKyXATJ8AmS9DJDhHSD5f4BNPyETDM8LMjmEGJ8YIRgg8Xwkno/E85B4HhLPReK5SDwHiecg8Wwkno3Es5B4FhLPROKZGDwMFEotNa2YUR8hp27xZ8yLkFOf489sP0JO/Yp+xj0Rcur3OzPhg5BTn9zNhDeyzUKxAWS/iC2nBrI+YyIHmbQxWoVI9UMkGwiR5g2RbCBEbn+IZAMh0j1DJBsIkeETItlAiAzvEMkGQmT6CZFdV4hOj4vGsxaIjMskMYKtsyIkQyxigEUMsIg+FtHHInpYRA+L6GIRXSyig0V0sIg2FtHGIlpYRAuLaKJdHIWIAsOphuVWBopctSwGe9CDkFO/S5lxA4Sc+osVM46KkFN/X3ImlBBy6jeFM8GOPNxFsSLkKTW2iTeQpwJYWmEgeQouHNHFBl+/kIgY03FEhGQjiNlcjoiQbAQx7scREZKNICZAOCJCshHEhDBHxHzbZoEkSRwR8w5zgaRJHBFzWLzAdsuLNqU/td9EZv83/9+MRaqr4VoAAA==
</Details>

**Comment by yairm210** [comment]
What you need to do it to *directly click* on the enemy, without selecting the city first - this will automatically select the city and will enable you to bombard
If you feel that there's a better way we could solve this, I'd be glad to hear it =)
