### ISSUE TITLE
Clarify Dropbox usage

### ISSUE THREAD

**Issue by l-jonas** [yairm210/Unciv#2554]
As far as I understand, the multiplayer features uses <https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/worldscreen/mainmenu/DropBox.kt#L22> for syncing. That's something which I would not expect.

Wouldn't it be a good idea to write that into the Readme and to the description at F-Droid?

**Comment by yairm210** [comment]
? Why?
Why would you care how I store my files in the background?

**Comment by l-jonas** [comment]
For F-Droid, I would think that this would be a <https://f-droid.org/wiki/page/Antifeature:NonFreeNet>.

It impacts the privacy of a user because it's a third party and a US service. Some users in Europe (including myself) use open source to prevent/ reduce data transmission to third parties. Moreover, the GDPR requires informing users about such things (I don't care if the info about dropbox is written like a gdpr compliant privacy policy or not, but a short info about that before the network connection to dropbox would be nice).

I came to that fact that it connects to dropbox when I asked how the devices in the multiplayer find each other ... I thought it uses udp broadcast in the local network or something like that and absolutely did not expect that it connects to dropbox.

**Comment by LukeMarlin** [comment]
Entirely agree for the F-Droid part. This usage fits the -quite evasive - description of NonFreeNet.

Regarding GDPR, AFAIK it only comes to play when there is a transmission of personal data. Looking at what is saved here, I guess this is fine as I suppose that "player_id" could not considered personal data. If there was an in-game chat and that conversations would be saved in here this would be a breach though.

On another point, in the current state, anyone can currently peek, modify or delete every multiplayer save file which is an issue.

**Comment by yairm210** [comment]
This is indeed true, but I'm not planning on hosting servers and databases and configuring user identities to solve it. This is a side project, not my job =)

**Comment by yairm210** [comment]
Also, only Multiplayer depends on this, so I'm not sure this is considered:
![image](https://user-images.githubusercontent.com/8366208/80976197-cd75aa80-8e2b-11ea-81d9-f9334e36d857.png)
But sure, I'll add it to the Readme and summary

**Comment by LukeMarlin** [comment]
> This is indeed true, but I'm not planning on hosting servers and databases and configuring user identities to solve it. This is a side project, not my job =)

Would that be OK to open a dedicated issue for that?
Maybe someone can pick this up. Would you allow a PR allowing to specify a simple web server in place of dropbox? This would require some additional fields in menu (password, url, port), and a second logic when it comes to save and retrieve multiplayer games.

Then you wouldn't need to host anything, but people would have the choice.

**Comment by l-jonas** [comment]
>  But sure, I'll add it to the Readme and summary

Is this already done? I don't see anything about that in the Readme of this repo and in the fdroid entry.

**Comment by LukeMarlin** [comment]
> Is this already done? I don't see anything about that in the Readme of this repo and in the fdroid entry.

For `README.md`, yes. See [here](https://github.com/yairm210/Unciv/commit/7484d2c2cf504262df49aa50af80026da391928b)
