### ISSUE TITLE
"Free  policy" blocks android game if none available

### ISSUE THREAD

**Issue by majkaz** [yairm210/Unciv#2561]
Happened to me on Android several times:

On completing Oracle, you get to pick a free policy. If all the  available are already active, there is no way to continue - you can neither choose a policy nor close the dialog. On leaving the game and resuming again, you are back at the step where you finish the Oracle. In this situation, there is no way to avoid the bug, you have to "pick a policy", but again, you cannot really do it.

Android, FDroid version, version 3.8.0.

**Comment by yairm210** [comment]
This was solved in 3.8.3, I think?
Can you send the game data so I can try it out to make sure?

**Comment by yairm210** [comment]
Since there's no answer, and this is a solved problem, closing this

**Comment by Go-rom** [comment]
Hello @yairm210 

I'm encountering the exact same bug. Could you please re-open this ticket ?

Here's the savefile : https://fromsmash.com/unciv-policy-bug

Version : 3.9.14 (F-Droid) on Android 6.0.1

**Comment by yairm210** [comment]
Can you attach a picture as well please?

**Comment by Go-rom** [comment]
Here are some screenshots

 [cid:eu.faircode.email.6026]
 [cid:eu.faircode.email.6027]

Thank you

**Comment by yairm210** [comment]
There are lots of policies available... Every icon is an available policy
How do you think this could be made clearer to users?

**Comment by Go-rom** [comment]
Hello @yairm210 

sorry for the very late answer.
You're right, i misread the informations provided by the policies.

Let's take the first one : tradition.
When i choose tradition for the first time, the word "tradition" is getting green and "aristocracy", "legalism", "oligarchy" are getting light blue.
I don't know why but i thought that at this step, "aristocracy", "legalism" and "oligarchy" are activated.

You have to know that i never played Civ 5 before Unciv.

Thank to your answer, now i understand the meaning for green background color and light blue background color, and i have to admit that it makes sense.

> How do you think this could be made clearer to users?

Well i don't know, now all of that seems very clear to me. I think that my mistake comes from a certain lack of experience with this game.
