### ISSUE TITLE
Years per turn doesnt match with game speed

### ISSUE THREAD

**Issue by CSharpDeveloperss** [yairm210/Unciv#2592]
As i remember turn duration in original civ5 is based on game speed (epic til marathon) but in unciv turns durawion always is equal.
If found following link
https://amp.reddit.com/r/civ5/comments/94yydb/civilization_5_turn_to_year_chart/

**Comment by AcridBrimistic** [comment]
I think this has now been resolved by

https://github.com/yairm210/Unciv/commit/67f7e67f55f08ac2588ae97541dc14c4c43b5806
and
https://github.com/yairm210/Unciv/commit/7668a21ae8fe1c1d63e0e17a3d834d0a087b5b5e
