### ISSUE TITLE
Iroquois Jungle/Forest movement cost is broken

### ISSUE THREAD

**Issue by g1t-dlanor** [yairm210/Unciv#2596]
**Describe the bug**
Units of the Iroquois tribe are documented as moving between any two adjacent tiles that both have forest or jungle as if those tiles are connected by road. And this really did work when I tried it in an earlier version (sorry I can't say which one, as it was some weeks ago).
But when I tested it today (May 7 2020), I found that all such movement cost my Iroquois warrior or settler two movement points rather than the fraction of a point it should cost, and did cost in an earlier version.

**To Reproduce**
1. Start game as Iroquois nation
2. Move some unit into a forest/jungle tile that also has a forest/jungle neighbour tile
3. On a fresh turn move the unit from one of those tiles to the other
4. Note the movement cost of that move.

In my test cases with an Iroquois warrior such a move always consumed both his movement points.

**Expected behavior**
The movement cost should be a fraction of one point, just as for road movement.

Since this did work properly in an earlier version I hope it can be fixed without major problems.

**Comment by yairm210** [comment]
Not reproducible, and nothing has recently changed.
This is probably because you are moving on forest tiles *outside of your territory*
Unique is: "All units move through Forest and Jungle Tiles *in friendly territory* as if they have roads."

**Comment by yairm210** [comment]
If you have a game where the bonus is not applied on tiles inside your territory, send the game info here
Menu, Save game, Copy to clipboard, Paste here
