### ISSUE TITLE
Save ,load game pop ups not displaying text while typing

### ISSUE THREAD

**Issue by lagsicta45** [yairm210/Unciv#2601]
Using android 7.0

**Comment by yairm210** [comment]
I'm unsure what you're trying to do.
In the "Save game" menu, you need to click on the text box of the game name to start typing.
What version of game are you on? What screen? Screenshots would be helpful =)

**Comment by lagsicta45** [comment]
![Screenshot_2020-05-14-13-24-23-139_com unciv app](https://user-images.githubusercontent.com/51542543/81900047-4f14c780-95e6-11ea-8285-bda1e7833df6.jpg)
It's version 3.8.3, android 7 and xiaomi note 4

**Comment by lagsicta45** [comment]
![Screenshot_2020-05-14-13-24-09-816_com unciv app](https://user-images.githubusercontent.com/51542543/81900302-b894d600-95e6-11ea-9ab6-54668b01bcb9.jpg)

**Comment by yairm210** [comment]
I'm still trying to understand the prblem - You're typing and nothing is showing?
And then when you put the keyboard down then it displays?
I think it might be a problem with your keyboard, is that the default phone keyboard? Could you try using another one (maybe the Google Keyboard) instead so we can compare

**Comment by lagsicta45** [comment]
The problem is like what you described. I tried gboard and swiftkey and they work fine. It's Labankey that doesn't display text immediately

**Comment by yairm210** [comment]
So then it's a problem with your keyboard, and not with Unciv =)
