### ISSUE TITLE
Unable to raze a city after conquering

### ISSUE THREAD

**Issue by HeavyMetalFFT** [yairm210/Unciv#2604]
I just conquered Seoul.  I want to raze it (sorry).  The 'raze' option is greyed out.  Maybe because it was a capital, and you cannot raze your capital? (Btw, why can't I raze my capital?)

I am currently able to raze my other non-capital cities, and have been able to raze other conquered cities until now.

**Comment by yairm210** [comment]
Not a bug!
Original capital cities are supposed to be unrazable
