### ISSUE TITLE
A way to (easily?) reinforce the AI in war

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#2616]
So, as you all know, AI in Civ will grow "nervous" with acumulation of troops on its border and sometimes even premptively strike when your relations are neutral/bad. Here's how I think it could be done in Unciv:

IF you have more than X troops within Y hexs of AI's border, THEN is added to your relation qualifier to this civ: - ((Number of your troops * their strength) / by a ratio that brings the number back to something reasonnable) * warmongerer multiplier

(this could not take into account troops you put in forts/citadels?)

Warmongerer multiplier should be cumulative, yes? If it is already (can't remember), that means that after a couple war you've started, any accumulation of troops near an AI's border will MASSIVELY impact your relationship with them.

All of this is to be accompanied with a special Diplomatic request that will pop up when your relation qualifier goes below a certain treshold: "The mustering of your forces along our borders worries us. Please remove them immediately or we will have no choice but to turn them back" or something. You then have the choice to lie and say nothing's going on, but the second you pile another one on their they strike, or after a few turns of staying there, they strike, Or you can outright declare war then, but the AI should have some sort of advantage right then. 

Maybe the advantage could be that AIs will have ramped military production the moment the IF above started modifying your relationship?

Anyways that's it for me! Thx!

**Comment by JackRainy** [comment]
The most easy way to get AI into the war - to declare the war :)
The AI will not declare the war, if it is not profitably (e.g. it understands its force power is too low).
However, if you have no army, but they have a good one, be sure, they will declare it on you (if you are playing on a hard level, of course).

**Comment by flecheapolinienne** [comment]
What I'm trying to get at is that if AI lets you pile up troops on its border, it puts itself in a clear disadvantadge that end up making the game WAY easier, even at the hardest level (which I now play at).

That's why this is a feature of regular Civ that AIs will warn you to not pile troops near its border and attack when you continue doing so. It also preemptively strikes warmongerers much more easily than in Unciv's implementation. We have to do something about it if we want the game to be interesting!

**Comment by wilsoncp8991** [comment]
I think it's a good idea, it gives you too much advantage to stack troops and that the I.A
do not realize, in addition to other leaders they never declare war, unless you are weak, have some personality, as an aggressive leader or pacifist leader, or randomly a civilization is granted to seek victory for domination, or to seek scientific, cultural victory , so this is an aggressive civilization or that seeks to win by domination, regardless of whether its army is less than yours, as it can be an insolent leader ...

**Comment by logicminimal** [comment]
technically included in diplomacy thread under afraid status

**Comment by SeventhM** [comment]
Old Issue. Closing as solved unless someone can comment otherwise
