### ISSUE TITLE
Better resource management

### ISSUE THREAD

**Issue by CSharpDeveloperss** [yairm210/Unciv#2619]
Because resources play an important role in game, i think that a better page needs.
For example a page like overview->units that show witch resources are in my territory, witch inporvement they have, witch are under working, and on witch workers making improvement

**Comment by refola** [comment]
That does sound useful. It can get boring searching through my entire empire to find unimproved coal or uranium tiles. It would also be useful to extend this feature to cover allied city states.

The only part of this feature request that doesn't seem useful is showing if the tile is being worked or not. That has no effect on if the resource is available.

Good suggestion. Maybe someone could make a mod to do it.

**Comment by logicminimal** [comment]
+ we need tile,terrain,feature,improvement searching on top of this

**Comment by yairm210** [comment]
Done
