### ISSUE TITLE
Translation file from mod is loaded when mod not in use.

### ISSUE THREAD

**Issue by 9kgsofrice** [yairm210/Unciv#2622]
I have made a translations file that renames some elements of the game as part of a project I'm working on.

When I install the mod in the game directory, it loads the translation file on game start - before I select and load the mod. I can see the era name "Ancient Era" has been replaced as per my file, before the mod is activated.

This means that if I start a normal game, the renamed elements will still have changed names.

Since the translation file is located within the mod subfolder, I did not expect this to happen. I thought that the translation would be take place when the rest of the features were activated, and otherwise the default translation would remain in place.

I realise that this is probably not the intended use of the translation file.

**Comment by dbaelz** [comment]
I can reproduce the bug and I'm interested to fix it

What happens afaik:
- The translations, including all in the translation files in the mod directories are loaded when the language is selected (initial by the user or the previous selected one).
- Rulesets and images are initially loaded, but only activated when they selected in the `NewGameParametersTable#newGameParameters`

It's hard to say what's the right way to fix the bug. Changing the initialization for mod languages to `NewGameParametersTable` could be a way. Of course, this would mean that mods can't translate  all parts before a game is started (e.g. main menu).

**Comment by yairm210** [comment]
I'm okay with that. I think that Mods should not affect the main menu anyway.
