### ISSUE TITLE
UI for cities on main screen

### ISSUE THREAD

**Issue by Crit-Cee** [yairm210/UnCiv#264]
Tapping city names to go to a city screen is very innacurate. More then half of the times I tap a city name it never registers the tap or it thinks I'm selecting a unit (sometimes the unit is on the city hex other times the unit is on an adjacent hex).

Also the exit button on the city screen sometimes gets covered by the city stats and so it doesn't register that I'm tapping the exit button.

**Comment by flecheapolinienne** [comment]
Same problem even on a 12.5 inch screen

**Comment by yairm210** [comment]
Solved, should enter the next version (2.10.4)
