### ISSUE TITLE
DIfficulty level not shown 

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#2640]
Difficulty level should appear under stats and/or victory status, no?

Anyway thanks for the hard work guys!

**Comment by yairm210** [comment]
Hm
I'm actually not sure where this should be displayed
Do you have any concrete ideas?

**Comment by flecheapolinienne** [comment]
Personnally I'd put leftmost of the victory status listing as a way to put progress in perspective!
