### ISSUE TITLE
Assigning citizens bug

### ISSUE THREAD

**Issue by KLR23** [yairm210/Unciv#2641]
When I assign citizens, they get unassigned the next turn. I think this might be caused by the fairly recent update which allows us to on other city tiles without having the need to assign them. 

This happened to me randomly once when I was playing Spain. This time, there were no other Spanish cities near it nor foreign territories. It just happened randomly. I had to start a new game because it's getting in the way of my growth. So I started a new game.

But the next game, playing the Ottomans, it happened again. But this time, other factors were involved. As I was destroying Germany, they had the audacity to build a citadel next to my farmlands. I didn't really care much, because they're down to 3 cities. After I annexed it, I tried to reassign the citizens in a way that maximizes efficiency for the city and other adjacent cities. After that, I managed the other cities. I assigned citizens to work in the farmlands near the citadel. But then next turn, even though I managed the cities, I noticed Berlin is starving. When I checked the city, it said 2 unassigned citizens. It unassigned the citizens near the citadel which was owned by the adjacent city, Stuttgart. I tried locking it, but it still got unassigned. As of now, one tile of grassy farmland is apparently worked by Dortmund, and I can't unassign it. That tile is grey for other cities.

This has also happened to me while playing America, though I don't remember the context.

Screencaps:
http://imgur.com/a/KUkP8Cq

**Comment by yairm210** [comment]
Since in recent version, please update :)

**Comment by KLR23** [comment]
I'm in the recent update, though the save was before the update. Is this
relevant?

**Comment by yairm210** [comment]
If you're on 3.8.9 and this is still happening, please put the game data here

**Comment by yairm210** [comment]
If you're not responding, I assume that this problem was indeed solved
If you have a saved game that still has this problem in 3.8.9, put it here and we'll reopen the issue =)
