### ISSUE TITLE
[Usability Issue] Cannot touch/tap the left side of the game

### ISSUE THREAD

**Issue by punnycoder** [yairm210/Unciv#2662]
### Describe the bug
I played the game both on my Android Phone, and on my Windows PC. I noticed the same issue. After a bit of playing, I am unable to touch some buttons (Diplomacy) which are on the left-middle of the screen (menu button works). 

For the Diplomacy button, if I press on a character unit, then it's no longer stuck.
But when moving the screen around, sometimes pressing the menu button resolves the issue, otherwise no.

### To Reproduce
I don't know exact steps. I will try to find and update on this soon.

### Additional Context
I am entirely new to this game. Just yesterday I began playing this really cool game. Really amazing.

### Other Details:
Version: **UnCiv [3.8.7](https://github.com/yairm210/Unciv/releases/tag/3.8.11)**
Windows: **Used the JAR file on Java 11**
Android: **Downloaded from F-Droid**

**Comment by 8itMiner** [comment]
Try downgrading to Java 8 by specifying which version of java you want to run it with. You could also try updating Unciv too version 3.8.11, which afaik is the latest version

**Comment by shinodem** [comment]
Still have this bug on android, a bit better but still it persist

**Comment by yairm210** [comment]
Sorry, I'm not encountering this at all, so it's difficult for me to tell...
Can you send me the game data?
Save game, copy to clipboard, send here

**Comment by shinodem** [comment]
Hi, you can take the same data what i sent you with Friends penalty issue.
It looks this bug appear after some time when you enter in city buy menu maybe scroll this menu, and it keep to freeze that left area on the map
