### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by sfspectre** [yairm210/Unciv#2668]
A request I have, and I may be blind, but it is very hard for me to see my civs borders on the map, but maybe have a slider that increases the opacity of the borders, or the ability to choose the color for borders while choosing our civ. 

Game is great, keep up the good work.

**Comment by yairm210** [comment]
The borders are already 100% opaque, and the border's color needs to be the same as the civ's color so you can tell whose order it is... not sure if there's anything actionable I can do here =/

**Comment by yairm210** [comment]
I'd be glad to hear other ideas but for now I have nothing
