### ISSUE TITLE
Orders for Civilopedia - Difficulty Levels

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2672]
I think it's better if "Difficulty Levels" of civilopedia are "ordered by difficulty".

Recently we got them in civilopedia as new items.
It's good that those critical information can be compared in one.
Civilopedia has a rule to be ordered by ABC,
and if it's translated it follows order of corresponding language.
(Non-Latin: Korean - 가나다, Japanese - Gojuon, etc.)
There's no problem that other civilopedia items follows that order.

I think "Difficulty Levels" may be the first exception of ABC ordering.
And if possible, please consider that difficulty ordering is also kept when translated.
They are highly likely to be "compared by difficulty".
We can save wandering, tho it's trivial, by ordering them in difficulty.

Giving numbers in front of them can be one way.
There may be some more elegant method, but i cannot come up more...

**Comment by hyunamae** [comment]
THIS.
