### ISSUE TITLE
Failure of Overall Latin Characters

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2699]
Description:
There are mass failure of Latin characters. I'm using Korean mainly, so I thought it's translation bug. But when I changed Language setting i saw it all over the game. Below 2 is only small part of this bug.

Reproducing:
1. "a sa e"
 - Open map editor
 - Open map (by creating new one, or open existing one whatever)
 - Save the map
 - You can see "a sa e" on top of the screen
※ it seems it should be "Map saved" (Thanks to Bada)
![a sa e](https://user-images.githubusercontent.com/64586749/83941353-9711bd80-a825-11ea-8526-c2e2fb755130.jpg)

2. Mass failure of Civilopedia
 - Open game (by starting new game or open existing one whatever)
 - Open Civilopedia
 - If you can't see body text, close civilopedia and open again. (** This is another bug.)
![Only taps](https://user-images.githubusercontent.com/64586749/83941363-b01a6e80-a825-11ea-8260-f0e8b446754c.jpg)
- Go to "Difficulty Level" tap. (I suppose it looks like "Difficulty le els")
![Difficulty le els](https://user-images.githubusercontent.com/64586749/83941372-be688a80-a825-11ea-8986-42fd4c029123.jpg)

Languages showing this bug:
English
Italian
German
French
Indonesian
Polish
Spanish
Turkish (?)
Brazilian Portuguese
Czech
Portuguese
Romanian (?)
Dutch
?alay (?)
** (?) means it's suspected because there are unnatural blank over the words.

Languages not showing this bug
Ukrainian
Russian
Korean
Japanese
Simplified Chinese
Traditional Chinese

**Comment by vainiovano** [comment]
I can't reproduce this bug. What operating system and device are you using?

**Comment by saud2410** [comment]
Samsung Galaxy S10e (SM-G970N)
Android 10, Security Patch Level 2020. 04. 01
It was fixed by itself after I turn off and on the phone.
It seems temporary, so let me close this bug issue.
I will open another bug that is reproduce-able.
