### ISSUE TITLE
Civilopedia unable to show texts after app is started

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2702]
## Description
When game is shut down and started again, civilopedia doesn't show body texts. It happens only once and at least first one time after app is started(turn on).

## Reproducing
1. Turn off Unciv
  - Touch multitasking button.
  - Wipe out Unciv so that it cannot run at backgrounds

2. Open Unciv

3. Start a game (by either creating new game or loading one)

4. Open Civilopedia

5. See error. It shows like this:
![Only contents](https://user-images.githubusercontent.com/64586749/83947227-c1c53b80-a850-11ea-82c2-c2065b4317af.jpg)

6. Close civilopedia, and open again. It shows again properly.

## User Environment:
Samsung Galaxy S10e (SM-G970N), Android 10
Unciv ver. 3.9.0-patch2

**Comment by vainiovano** [comment]
The blue bar on the bottom should be movable. What happens if you move it up?

**Comment by saud2410** [comment]
Oh... It's movable in mine too. I moved it up and items & texts showed up! I think i should close this one too...
