### ISSUE TITLE
translation issues with renamed objects

### ISSUE THREAD

**Issue by 9kgsofrice** [yairm210/Unciv#2703]
I'm creating a mod that uses the translation system to rename features that exist in the base game. This allows me to re-use hardcoded features without changing the code.

For example, I rename "Temple" to "Town Hall" using the English.properties; the building has a new name and a new graphic, but retains the bonuses that the Temple building receives from policies.

This shows up correctly in the build menu, but not in the updates in the top right of the screen - where it still reads, for example "Temple has been built in Rome".

This problem seems to exist anywhere that [square brackets] are used to insert the name of an object into a text string. In the above case, it's "[construction] has been built in [cityName]". [construction] always returns the name of the base object, even if there's a translation in place for it.

Other examples: I rename "Iron" strategic resource, but the build menu still reads "Consumes 1 Iron" for affected units. I rename natural wonders, but the game still tells me "You have discovered Grand Mesa". I rename the Warrior unit, but the combat dialog still reads "Your Warrior was destroyed"

/*
This presumably also affects the translation of the base game for speakers of other languages - they will see the base names of things in English under these circumstances.
*/

**To reproduce:** rename a unit/resource/building, then look at a text string that involves it - rename "monument" and then construct it.

**Expected behaviour:** Renaming objects with the translation file should affect any situation where the named object appears.

**Comment by 9kgsofrice** [comment]
In other languages, translations of unit names, resource names etc, seem to work correctly in the text strings, but not in English...

**Comment by dbaelz** [comment]
Thanks for the detailed feedback.

After some testing, I could reproduce the bug and found a way to fixed it. Unfortunately, after some testing I realized, that my fix isn't going far enough for all possible cases. So need another attempt to do additional changes. Stay tuned for it. :wink:
