### ISSUE TITLE
Starting biomes

### ISSUE THREAD

**Issue by AConte0** [yairm210/Unciv#2704]
There is some nation that need to have a starting biome like the others. Arabia spawns into deserts and Russia in cold biomes but Rome shouldn't spawn in tundra or desert too! For Rome i suggest to spawn in grassland over hills (the seven hills of Rome!). In conclusion i think it should be also added the possibility to choose if spawning in the nation's starting point or casually, based on temperature extremity.

**Comment by yairm210** [comment]
I'm fine with adding in a start bias for Rome, but not with adding yet another player option
