### ISSUE TITLE
UX suggestions

### ISSUE THREAD

**Issue by contrapunctus-1** [yairm210/Unciv#2706]
Thanks for this great game, for making it FOSS, and releasing it on F-Droid! 😀

Here are some ways in which I hope the UX can be improved -
1. If a unit is headed somewhere where it will take it >1 turn to reach, I often wish to see what tile that is. Sometimes it can be far away, so maybe some way to highlight the path it is taking, too?
2. I'd love to be able to see the Civilopedia entry for units and buildings after selecting them. Perhaps a little ❔ or ℹ️ can be displayed when they are selected?
3. ~The structures built by Great units don't seem to be documented in the Civilopedia.~ Oh, they are Tile Improvements.
4. It is idiomatic for Android users to tap on the background of a menu to close it (e.g. opening the in-game menu, and then tapping on the game screen to close it)
5. The Civilopedia menu is clunky to scroll through, but I can't think of how it might be improved 🤔
6. If a Civilopedia entry refers to another object, it would be convenient if that was made a button so one can jump to the entry for that.
7. Very often, when the creation of a unit is announced, I tap on the announcement and expect that the unit has been selected by that action...but it isn't 😅 I've played many games, but I've still not become used to this behaviour - every now and then I end up making a mistake because of it.

I may add a few more as soon as I run into them again.

**Comment by SomeTroglodyte** [comment]
Not all - 4 isn't, and 7 may refer to units in cities - the notification selects the **tile**. I'm closing this anyway, as the important bits are done and this is over a year old.
