### ISSUE TITLE
No river display with Default tileset.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/Unciv#2708]
**Describe the bug**
Rivers are all invisible with default tileset. Switch to Fantasy tileset and rivers are displayed correctly.

**Expected behavior**
Rivers should be correctly displayed.

**Screenshots**

**Additional context**
Any plan to add river support for default tileset? I tried to reuse River-BottomLeft.png/River-BottomRight.png/River-Bottom.png for default and it seemed working OK, like :
![Screenshot_20200608_173929_com unciv app](https://user-images.githubusercontent.com/6846049/84016133-69588000-a9af-11ea-8ef2-ed5a299fbd56.jpg)

**Comment by yairm210** [comment]
Sure, that looks like a good solution to me
