### ISSUE TITLE
Natural wonders

### ISSUE THREAD

**Issue by AConte0** [yairm210/Unciv#2710]
I recently discovered these two spawning issues (if I'm not mistaken) I have twice found natural wonders that appear above ancient ruins (obviously unreachable).

![Screenshot_20200608-011718](https://user-images.githubusercontent.com/66170578/84144929-58644900-aa59-11ea-8ea5-8c59c52beb78.png)

![Screenshot_20200608-023329](https://user-images.githubusercontent.com/66170578/84145006-72059080-aa59-11ea-874e-2f61c400dfcf.png)

In addition, I saw a natural desert wonder (the crater if I'm not mistaken) spawning in the tundra. 

![Screenshot_20200608-024320](https://user-images.githubusercontent.com/66170578/84145069-877aba80-aa59-11ea-8a4c-adb92562cf29.png)

I hope I have been of help.

**Comment by yairm210** [comment]
B is not an error, is correct =)
A is solved in 3.9.1, thanks!
