### ISSUE TITLE
Resources for coast with whales and fishing boats not adding up

### ISSUE THREAD

**Issue by Falkgeist** [yairm210/Unciv#2723]
According to the in-game civilopedia:
- coast has 1 food
- whales add 1 food + 1 gold
- fishing boats add 1 food + 1 food for whales + 1 gold with compass
The sum of that is 4 food and 2 gold, although I only see 3 food and 2 gold in the city screen.
![Screenshot_20200612-211448_UnCiv](https://user-images.githubusercontent.com/43405953/84538366-cfb40a00-acf1-11ea-84b5-49932ffa4e56.jpg)
Either the civilopedia or the map/city screen is wrong... Or am I wrong?

**Comment by yairm210** [comment]
You are absolutely correct! It seems that the whale bonus *replaced* the regular fishing boat bonus, instead of adding to it.

**Comment by Falkgeist** [comment]
I didn't check the actual mechanics from Civ5, though. Just wanted to point out, that the Civilopedia might not be precise enough. Same goes for the other entries (e.g. forest says "+1 Food, +1 Production", but it actually overwrites the base terrain, instead of adding food and production). Maybe it's better to not say "+" or point out, that the terrain overwrites the values of the base terrain? Anyway, just a though. I'll probably have to check the mechanics and the civilopedia of the original again, to be sure. ;)
