### ISSUE TITLE
Horses should not spawn on Jungle tiles

### ISSUE THREAD

**Issue by Arachnus64** [yairm210/Unciv#2724]
![Screenshot_20200613-101339_UnCiv](https://user-images.githubusercontent.com/66858152/84558959-311fbb80-ad7a-11ea-9de6-a3a639365240.jpg)
See attached image - Horses should not spawn on Jungle or Forest tiles in the Civ V ruleset.

**Comment by lyrjie** [comment]
By the looks of it, all strategic resources can appear on tiles with any removable feature (Forest, Jungle, Marsh)

Apparently in the original game, there was a much more complex logic behind placing resources on tiles with features, here's a table from the official manual:
![image](https://user-images.githubusercontent.com/26433289/85131363-4cd60680-b23f-11ea-92f6-58c219371e76.png)
