### ISSUE TITLE
ECCENTRIC visual bug (3.9.3)

### ISSUE THREAD

**Issue by KidsWatchGhosts** [yairm210/Unciv#2729]
**Describe the bug**
Misplaced line

**To Reproduce**
1. Go to map editor
2. Click on new map
3. Scroll down to bottom of the world

**Expected behavior**
No white line or misplaced button

**Screenshots**
![image](https://user-images.githubusercontent.com/58400615/84610255-ddb08900-aeb1-11ea-83e9-8588d9c3b48e.png)

**Comment by yairm210** [comment]
Fixed, rolling out as a patch =)
