### ISSUE TITLE
Android "parse package error" when downloading from Chinese social software

### ISSUE THREAD

**Issue by tianshidoubi** [yairm210/Unciv#2730]
**Describe the bug**
As the title said, some Android based mobile operating systems will have the problem of "parsing package error" when installing unciv, which causes many players to be unable to install unciv. [my English is not very good, sorry]

**To Reproduce**
Just download the APK installation and there will be errors!

**Screenshots**
![image](https://user-images.githubusercontent.com/48427744/84620942-e766da80-af0b-11ea-9b53-5333be916916.png)
This line in Chinese means:Problem parsing package.

**Comment by yairm210** [comment]
Where are you installing this from?

**Comment by tianshidoubi** [comment]
> Where are you installing this from?

On our social software——you should know that Chinese mainland can not visit Google

**Comment by yairm210** [comment]
:/
Well then unfortunately there's not a lot I can do about that

**Comment by ninjatao** [comment]
@tianshidoubi It is almost certain that the software market inappropriately modified or repacked the application. You could try some other apk sources for an original one.

**Comment by lishaoxia1985** [comment]
@tianshidoubi please choose other appstore. It's not a problem. please close this issue.

**Comment by yairm210** [comment]
Closing this, since it seems to be a problem with the providor and there are alternatives
