### ISSUE TITLE
Mint not function

### ISSUE THREAD

**Issue by joejones314** [yairm210/Unciv#2733]
**Describe the bug**
Mint are not adding $2 to the city even there is working gold or silver mine .

**Comment by yairm210** [comment]
It adds 2 gold to the mine's tile yield, if the mine is not worked it won't affect

**Comment by yairm210** [comment]
So yeah, I'm pretty sure this is a misunderstanding is the mints function
If I'm wedding, you can always reopen it :)

**Comment by joejones314** [comment]
Yes, you are Right!

Thanks for reply :❳
