### ISSUE TITLE
Factories, trading post, hills yields, resource penalty and population bug?

### ISSUE THREAD

**Issue by philn3v** [yairm210/UnCiv#274]
Can't build factories (doesn't show up in build menu even with coal)

Trading posts occasionally displays 1 and 2 gold (before any tech boosts).

Some mines on hills have greater yields, and that hill will eventually have a strategic resource when the tech is unlocked.

Resource penalty at 0. Is this included in original game, sorry I'm unsure.

Tiles and specialists sometimes costing 2-3 population to work.

**Comment by yairm210** [comment]
There's a lot here, and this should be split into separate issues once we see what each one contains.

First off, do you have a saved game with examples of these issues? It would really help me if you could send it to me by email!

Factories - checked it, it seems to work for me...?

Mines - I'm pretty sure I fixed this ages ago, I'll check.

Resource penalty - extremely likely I made a mistake, I'll check

Tiles and specialists - ...What?

**Comment by yairm210** [comment]
About resource penalty - absolutely correct, I'll fix that

**Comment by yairm210** [comment]
Same for mines, correct, and will be fixed

**Comment by philn3v** [comment]
There kind of one sentence issues so I didn't want to spam the thread. Will keep in mine next time. I've sent the China save, thanks for having a look.

**Comment by philn3v** [comment]
I resent the save file. Did you get it?

**Comment by yairm210** [comment]
Yup :)

**Comment by philn3v** [comment]
Ok so on the factory issue; apparently I can build factories if I don't connect any coal (coal count will go into negative but still able to queue factories).

Also how is it that some pop work tiles beyond the cities 3-tile range limit? I noticed that I don't get yields from those pops either. 

Sent you another save file to check (the capital to be precise). Thanks!

**Comment by yairm210** [comment]
Fixed the population issue (will enter 2.10.4)
Auto-assigned pop can no longer go outside 3-tile range
Also, any existing pop outside the 3-tile range will be removed

**Comment by yairm210** [comment]
Also fixed factory bug (literally a single exclamation mark was misssing -_-)
So, that's all folks, see you in the next version!
