### ISSUE TITLE
Hills

### ISSUE THREAD

**Issue by AConte0** [yairm210/Unciv#2748]
Hi, i think that you should create a new rype of terrain. The hills in the deserts (or dunes) that must replace the standard hill cell (same concept pf the jungle and the forest).
It should be like the previous one but the green must be replaced by the yellow of the sand and maybe you can also change the color of the rocks with more red.

**Comment by 8itMiner** [comment]
Red11's Civ 5 Expansion Mod adds this feature into the game. If you just want the "Desert Hills" terrain, then copy over the terrains.json file and the sprite from the mod into a new mod and enable it on map creation.

**Comment by yairm210** [comment]
Same as #2960 which also has more discussion so closing this one
