### ISSUE TITLE
can i create penalties?

### ISSUE THREAD

**Issue by absinthiya** [yairm210/Unciv#2757]
question: if i would like to create a specific promotion for a unit, taking as example the template wolf pack I
{
		"name": "Wolfpack I",
		"effect": "Bonus as Attacker [25]%",
		"unitTypes": ["WaterSubmarine"]
	},
would it then work to change the number 25 to -25 in order to give it a penalty instead of bonus?

**Comment by yairm210** [comment]
You can indeed do that in a mod if you want
