### ISSUE TITLE
Korea second ability

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2773]
Could you consider to implement second ability of Korea?

Korea(Civ 5) ability is:

# Scholars of the Jade Hall

- +2 Science for all specialists and Great Person tile improvements

- Receive a tech boost each time a scientific building/Wonder is built in the Korean capital

Korea supposed to have 2 ability. First one is already implemented, second one is not yet(?).

Why second ability is omitted? I couldn't find whether it's GnK or BNW. I can imagine that it's for balancing; if they are all implemented Korea must be more unstoppable, because each one is exceptionally powerful.

However it's also fact that they are all ability of Korea. If balance isn't good, it's a fault of Civ 5, not of Unciv. I think it's also helpful to improve difficulty. There've been always some way to beat Korea.

**Comment by tianshidoubi** [comment]
Oh, man, as far as I know, South Korea is strong enough - they can easily win in science.just because of their strong scientific research power. I mean, if you add this ability, I think Korea will be invincible!
My English is not very good, excuse me!

**Comment by yairm210** [comment]
I've been debating this for a while, but I think that for balancing purposes, it's best to leave things as-is. Korea is already once of the stronger civs, and it doesn't need to be further buffed.
