### ISSUE TITLE
Game isn't opening on my device.

### ISSUE THREAD

**Issue by HeavyTank-1** [yairm210/Unciv#2774]
I have a Galaxy J5 Prime, the game was running ok since last night, when it crashed. I didn't had any problem so far, i tried to download the game again but it keeps showing the same message: "UnCiv keeps stooping." Here is the print: 
![Screenshot_20200626-141400_Samsung Experience Home](https://user-images.githubusercontent.com/67478243/85883467-6b944a00-b7b7-11ea-878a-03d391d77f79.jpg)
(Sorry for the language, I am brazillian) 

I don't know if it is a game issue or my fhones issue. I would apreciate a lot if you could help me with that, i love the game and want to play more of it.

**Comment by yairm210** [comment]
Hey man, I have absolutely no idea =/
I solved something now that *could* have been the problem, but could just have easily not have been it... there's not much I can do about this since I can't find the source of the problem
