### ISSUE TITLE
Question: Will there be UnCiv for IOS devices?

### ISSUE THREAD

**Issue by HeavyTank-1** [yairm210/Unciv#2783]
Will UnCiv be launched for Apple devices one day?

**Comment by yairm210** [comment]
I'm not planning on it
It means paying money to Apple, yet another release party, and since I don't have an IOS device it means I can't test it properly.

**Comment by wyldcrd** [comment]
Just a new bit of info for you on the iOS front, there are side loading options now

(altstore and sidestore)

in case you (or someone else) wants to ever port it over to iOS

**Comment by Unknownman21229** [comment]
Yes please, consider this, I love the game and I'd like to see it come to IOS too

**Comment by selleronom** [comment]
Hello everyone,

Good news for iOS. I have made an iOS port, it starts and is playable. But it needs optimization to run well.

To put it on the App Store is the main problem. As @yairm210 wrote, Apple demands a developer fee of $99/year.

So, to pay for this fee, I am thinking to charge a small price for the download on the App Store. The code will of course stay open source for anyone to build themselves. The price is just for the App Store version.

What do you think of this idea? Is a small price to cover the Apple fee reasonable?

Thanks.

**Comment by yairm210** [comment]
Sounds reasonable to me, the real question for me is what's the update process
If people are playing there and the versions start to diverge from mainline Unciv they'll start getting version conflicts on Multiplayer

**Comment by selleronom** [comment]
Update on my progress. 

The port works well on iPhone and iPad but Apple stone walls me on releasing it the App Store. TestFlight link could be an option but I don't think it will ever be released officially unfortunately.

**Comment by yairm210** [comment]
That's really cool! Do you have a link?

**Comment by selleronom** [comment]
Here's the link, https://testflight.apple.com/join/fW4KFwUY

Rebuilt from the current version.
 
Some changes have been made as I was trying to meet Apples vague explanations for why the app is blocked from publishing. The built in ruleset is replaced with a very simple one, but it is possible to download and install from the mods list. I also renamed Civilopedia. 

As these changes didn't matter I will revert them.. 

The most common bugs in the iOS port have been network communication and int calculations. RoboVM made it pretty easy otherwise!

**Comment by yairm210** [comment]
I meant a link to the code :)

**Comment by selleronom** [comment]
Synced from upstream (4.19.1) but I have not tested a build yet. 
Checkout the branch here: https://github.com/selleronom/Unciv/tree/ios

**Comment by jerry8870** [comment]
Hi everyone!

I've completed an iOS port of Unciv for iPhone and iPad and finished my own testing. It is now at the TestFlight beta stage, and I'd love to invite more players to try it and share feedback.

**[Join the TestFlight beta](https://testflight.apple.com/join/XSgMMQjt)**

Open the link on your iPhone or iPad and follow the instructions to install through Apple's TestFlight app. The port requires iOS / iPadOS 15.0 or later.

### What's included

- **Unciv on iPhone and iPad**, with support for landscape play.
- **UI and display improvements for iOS**, including layout adjustments and safe-area handling around screen cutouts and the home indicator.
- **iCloud save synchronization in the TestFlight build**, so you can sync your saves between iOS devices using the same iCloud account and continue playing on another device.

The build has passed my own testing, but wider testing across different devices and longer games would be very helpful. I'd especially appreciate feedback on:

- Gameplay stability, performance, and saving/loading games.
- UI layout, text readability, and touch controls on different screen sizes.
- iCloud save synchronization and continuing a game on another device.

Please report iOS-specific issues in the [iOS port repository](https://github.com/jerry8870/Unciv4iOS/issues). Include your device model, iOS/iPadOS version, TestFlight build number, and steps to reproduce the problem. Screenshots are especially helpful for display issues.

The iOS port source is available on the [ios-4.21.16 branch](https://github.com/jerry8870/Unciv4iOS/tree/ios-4.21.16). This is a community-maintained port, and I'll handle feedback about the iOS beta.

Thank you to the Unciv maintainers and contributors for making this game possible, and to everyone who gives the iOS version a try!

---
