### ISSUE TITLE
Pillaged improvements lack identification

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#2785]
When an improvement has been pillaged, the map description does not indicate that it has been pillaged. A farm that has been pillaged will accordingly produce less food, but the map description still just reads "farm" when it should read "pillaged farm."

It would also be helpful if the map drew a red 'X' over the tile (or something like that) to denote the pillaged status, rather than just reverting to the image of an unimproved tile. This 'X' graphic could be reused for all pillaged tile improvements.

![Screenshot_20200629-195212_UnCiv](https://user-images.githubusercontent.com/1423934/86313235-80b71180-bbd9-11ea-8c5c-ee2d4e720a88.png)

Running version 3.9.6.

**Comment by foolishgrunt** [comment]
Another question about this: I notice that when I move a worker over the pillaged tile, he automatically begins work to repair the improvement. Is that by design or not? Because it does not match the behavior from the original game.

**Comment by yairm210** [comment]
That's by design
But yeah, the game currently does not differentiate between a farm that's been pillaged and a farm that's in the middle of being built, I think I should add the icons but with something different, like a line through them

**Comment by logicminimal** [comment]
maybe adding pillaged textures for pillaged improvements is a great idea? (a farm that is burnt on one side and currently on fire on another)

**Comment by yairm210** [comment]
That's not a bad idea, actually!

**Comment by yairm210** [comment]
Pillaged improvements are now shaded for identification
Hopefully we'll allow pillaged versions soon :)
