### ISSUE TITLE
no diplomatic penalty from cutting trades short (easily abused to take the AI's money)

### ISSUE THREAD

**Issue by refola** [yairm210/Unciv#2788]
**Describe the bug**
When a trade is cut short (e.g., from losing access to a luxury), the AI accepts it without protest. Intentionally doing this repeatedly allows efficient farming of the AI's money / tech / luxuries.

**To Reproduce**
1. Trade with an AI for all their gold and tech, offering enough gold-per-turn that it would be worth it.
2. Also put all of one of your luxuries into the trade. (They don't have to want it. Just any luxury that you can pillage.)
3. Wait for the AI to accept the trade.
4. Pillage one instance of that luxury in your land.
5. Wait one turn for the trade to be cut short.
6. Repeat for the other AIs (or with the same AI if you didn't have enough gold-per-turn to get everything in one go).
7. Trade gold (not gold-per-turn) with AIs for any luxuries and open borders you want.
8. Repeat 1-5 to get your gold back.

**Expected behavior**
If a trade is cut short, I expect some sort of penalty. I definitely shouldn't be able to get out of all my obligations after the AI has already fulfilled their end of the bargain upfront.

**Additional context**
I remember Civ5 having a diplomacy bonus for something like "our trade relations have been just and forthright". I expect that respective diplomatic penalties and bonuses for cancelled and completed trades would be the best fix.

**Comment by ravignir** [comment]
I don't remember this in Civ5. I think you were unable to pillage your own resources.

**Comment by logicminimal** [comment]
> I don't remember this in Civ5. I think you were unable to pillage your own resources.

i saw this exact thing in a civ 5 bug video, only difference being that the player builds a fort on the luxury instead of pillaging it

**Comment by logicminimal** [comment]
technically this is the case in civ 5 but i think it is a bad mechanic and there should absolutely be penalties for missing a trade short, aside from precautions like only being able to trade gpt when not friends etc

**Comment by yairm210** [comment]
This has been done a while back, forgot to close it
