### ISSUE TITLE
AI question

### ISSUE THREAD

**Issue by shinodem** [yairm210/Unciv#2791]
Can you explain is it fine behavior what AI can see my units for attack, but i can't see his units without approach?
I thought enemy AI can see the same as i - one hexagon around borders.
Am i something missing?
https://i.imgur.com/CsmZ74p.jpg

Thx

**Comment by yairm210** [comment]
Aircraft can see for 6 tiles, if you had an aircraft you could see him as well =)

**Comment by shinodem** [comment]
Thanks, that's the problem i has Aircraft carriers (It was destroyed) and i can't attack because i do not see enemy but AI can see my units more than one hexagon around border without approaching to me
