### ISSUE TITLE
Ports and querters(?)

### ISSUE THREAD

**Issue by AConte0** [yairm210/Unciv#2795]
Hi, i was questioning what was the next big project after the rivers. Wouldn't be cool if the next feature is querters? Like the cultural one, the economic one, the military one, the industrial one, the scientific one and the portual one? I know that this is hard but maybe you could start with the portual one, cause i think its the more needed. When you Settle for a new city and you want to produce ships an navies, you have to be near the coast (obviously). But what if you introduce the portual zone? You can build it if the city is at least one cell away from the coast and doing so i can use more the territory in land (cause the ocean for now is a bit useless). May be this also the starting of interactive cells? I think i'm going too far but do you think this will be possible one day?

**Comment by yairm210** [comment]
Nah, that's Civ VI stuff, will probably never enter Unciv if I'm being honest, considering the time it's taken us to get this far =)
