### ISSUE TITLE
only text loads for me

### ISSUE THREAD

**Issue by foxymacko** [yairm210/Unciv#2796]
i have no idea if this is just a problem with my laptop or the game,
![bug](https://user-images.githubusercontent.com/67795920/86481055-8898c200-bd4f-11ea-9042-d468ad907f9f.png)
![bug2](https://user-images.githubusercontent.com/67795920/86481068-8d5d7600-bd4f-11ea-98f6-4480673e9248.png)
 
only text loads,nothing else i tried switching tilesets too i have no idea what to do.
any idea how to fix this?

**Comment by yairm210** [comment]
Whoa
What the hell
Can you provide more information? Game version, computer type (win/linux, 32/64)?

**Comment by foxymacko** [comment]
yeah so,  win64 game version newest (today) its a kinda outdated laptop win7 home basic, processor AMD athlon (tm) 64 X2 dual-core processor TK-55 1.80 GHZ . 
installed memroy (RAM 2,00GB
sys type : 64 BIT
im missing on alot of windows updates, the game runs but the tiles and everything else but text wont load

**Comment by yairm210** [comment]
Never seen anything like this
What happens if you minimize? Change the window size?

**Comment by foxymacko** [comment]
lemme check

**Comment by foxymacko** [comment]
tried both,nothing changes.

**Comment by foxymacko** [comment]
![dd](https://user-images.githubusercontent.com/67795920/86530811-3d4ff200-bebc-11ea-9312-4bcfff0dd4c5.png)

**Comment by foxymacko** [comment]
nevermind fixed found out that  i just had a outdated graphics driver, thanks for help thought
