### ISSUE TITLE
Downloading the translation files should be optional, some people don't need all language translation files.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#2810]
Downloading the translation files should be optional, there are two reasons:
- Not all the people need every language translation files.
- In some languages there are too fewer words translated to read.

**Comment by yairm210** [comment]
I don't actually agree with this, since the translation files are very small and it adds another layer of possible failure before the initial success (actually playing the game)
How were you thinking of doing this?

**Comment by lishaoxia1985** [comment]
After you download the language files, the files need MD5 checksum, I'm not sure.
Maybe you are true.

**Comment by yairm210** [comment]
Another point is that the translation files are updated together with the game updates, and separating them would mean that you'd need to check for translation updates as well...
More negatives than positives for this proposal
