### ISSUE TITLE
Improve performance by having each tileInfo hold a transient link to its baseTerrain

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#282]

**Comment by yairm210** [comment]
Every unit movement needs to check if the tile is land or water, both of which use the baseterrain - this could account for up to 10% of next turn time! 0_0

**Comment by Crit-Cee** [comment]
Makes sense. I've noticed that my next turn time is higher when I have a bunch of auto moving units.

**Comment by yairm210** [comment]
Done
