### ISSUE TITLE
Remove ability to revive a civilization you previously destroyed

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2820]
This is not possible in civ v as you cannot liberate a city owned by a player you are at war with, and you cannot make peace with a civ you destroyed.

Currently if you do revive a civ you previously destroyed, or one you were at war with while they were destroyed by another civ, they will return as enemies. This suggestion would fix the former issue and although I do not quite remember what the mechanic is for the latter, I believe they should return as friends not as enemies once they are liberated.

**Comment by ravignir** [comment]
I believe you can't liberate a civ you were at war with at the time when they were destroyed.
Also I remember bonus for liberating a civ being ridiculously huge, making liberated civs basically your puppets.

**Comment by yairm210** [comment]
I don't think I'll remove this option, I'd rather not limit the player if it's not absolutely necessary.
I can just have them not be at war anymore, and that should be fine.
