### ISSUE TITLE
Nukes aren't working as intended when used by AI

### ISSUE THREAD

**Issue by whatsupboy** [yairm210/Unciv#2823]
Nukes used by the AI do neither cause the intended fallout in a two tile radius nor do they kill/damage cities and unites in said two tile radius outside the target tile.

Cities are reduced to 0 health and unites are destroyed as expected but again only on the single tile the AI targeted, essentially working like an overpowered plane but without key features of a nuclear missle such as fallout.

**Comment by yairm210** [comment]
Resolved by @ninjatao
