### ISSUE TITLE
Improve Desktop Experience / Desktop UI

### ISSUE THREAD

**Issue by seniorm0ment** [yairm210/Unciv#2824]
**Is your feature request related to a problem? Please describe.**
The UI is alright for mobile use, but on desktop it feels really half ass (as it's not changed), and not very intuitive. Fonts don't look good, and overall feels like a lot of wasted space and oversized fonts and buttons. I also find it very hard to keep track of my tiles and units as icons blend in so well. Although that is also an issue I have on mobile.

**Describe the solution you'd like**
An overhaul of the UI for desktop usage.
More Civ like colors would be cool for the UI like a brown/blue/yellow/gold mix maybe instead of the heavy blue usage. Maybe some better transparency, or slight blur on prompts? Idk.

**Comment by yairm210** [comment]
This... is not actionable. I ALSO want a better UI, but unless I know what it looks like, I can't actually do anything.
What does an overhaul even look like? Are you thinking of a redesign of some screens? Unless it's a practical change I can make, I have nowhere to go with this.

**Comment by grravity** [comment]
I mean, you are the developer you say you want a better UI, I fail to understand why you wouldn't be able to think of some changes you yourself would want?

Anyways, for the desktop UI, if it was me personally, just my thoughts, I'd consider making it look similar to Civ 5's interface. Not sure the legalities behind it, but I assume similar not exact is fine? 

I think for one, the colors of the windows, transparency strength, and font/font colors are so much better on the Civ 5 interface than the current UnCiv one. I assume these are fairly basic tweaks?
If you wanted to go another step, move around some of the boxes or even better allow the user to move them wherever they choose.
Improve the font rendering, it is very poorly rendered on larger screens, buttons look slightly blurry.
Make all the buttons and boxes take up less space, they have massive margins which make sense for mobile use to make them more clickable, but simply a waste of space and just way too big for desktop use.
And maybe add a very slight highlight to all of the users Units and pieces just to make them stand out more. Especially when you don't click them, they can blend in pretty well with the background tiles taking it a while to look at where each are.

**Comment by yairm210** [comment]
I think that what you're actually looking for is Menu - Options - Resolution - 1500x1000, that should solve most of your problems I think.

As for the first point, There's a big difference between *designing* and *implementing*. "Better" is not a word that means anything, in the context of making stuff - everyone wants everything to be better, the real question is how. And that's a design problem, not an implementation problem.

As for 'what I want', whoo boy you should have seen how many changes the UI went through. As of now, I'm out of ideas.

**Comment by grravity** [comment]
> I think that what you're actually looking for is Menu - Options - Resolution - 1500x1000, that should solve most of your problems I think.
> 
> As for the first point, There's a big difference between designing and implementing. "Better" is not a word that means anything, in the context of making stuff - everyone wants everything to be better, the real question is how. And that's a design problem, not an implementation problem.
Yes, and I suggested how I would improve certain things. For example fonts and buttons are rendered very poorly, that would be a start. Maybe make them more aligned with the boxes too, some of them aren't aligned, some are Color adjustments would be another thing, again I personally find the blue a bit much. I mean I went through on each subject and suggested how I would make each "better". Obviously these are my personal opinions, but they're just suggestions.
As for the resolution change, it gives more realestate but it doesn't help that information is not showed well. There's no need to have the top bar so thick, and stuff happiness, and all those stats in the middle. Why not spread them along the whole bar and thin the bar a bit like Civ 5 does? 

Increasing the resolution helps, I've already done it. It gains you a bit more board realestate, but it makes it even more difficult to see text on the board, and unless you zoom in it is difficult to see where your pieces are, which isn't very good when you have pieces all around the board. 
> 
> As for 'what I want', whoo boy you should have seen how many changes the UI went through. As of now, I'm out of ideas.

I mean you said that there was stuff you wished to be improved, I assume this meant you disliked certain parts of the UI? If not I don't understand what you would want to improve if you didn't dislike anything which was my point of that comment. But I mean I did suggest a bunch of ideas above.

**Comment by refola** [comment]
@grravity mostly focused on visual UI changes, but I've got a bunch of input-side suggestions:

1. scroll wheel / touchpad support for _all_ scrollable interfaces; it's missing for new game interface mod & civ lists, trades with AIs, and the following horizontal scrolling interfaces: overview's stats & resource lists, civ rankings, tech tree, civilopedia category buttons, the save / load game interface (when the game's window is made less wide), and likely others
2. double-clicking to do stuff: adding items to the construction queue, buying tiles, picking a tech / policy, maybe more
3. "escape button to go back" support for the victory status screen (I think that's the only place it's missing from)
4. custom keyboard shortcuts (pretty useful for people who don't use the QWERTY keyboard layout)
5. adding a "Controls" section to the civilopedia (e.g., I wouldn't have known about left-clicking for instant movement if I hadn't read it in the changelog; that should be listed)

**Comment by natrius** [comment]
@yairm210 

Ever considered something like https://opensourcedesign.net/#page-top (Job application https://opensourcedesign.net/jobs/job-form/ ) ? I mean, you could open a job with the form and if nothing happens, well, so be it. Was about to post https://github.com/yairm210/Unciv/issues/3143 there but i think it fits better here, in this issue.

**Comment by yairm210** [comment]
@refola The mouse wheel functionality seems to already exists in the places you mentioned, what platform are you using?

**Comment by natrius** [comment]
Did not work right now in the trade-menu with the AI. Had to left-click and drag it up.

**Comment by refola** [comment]
> @refola The mouse wheel functionality seems to already exists in the places you mentioned, what platform are you using?

I'm on Linux (specifically, Chakra Linux, using the `.jar` file releases from here via [this package I maintain](https://ccr.chakralinux.org/packages.php?ID=8416)). I tested with TrackPoint™ "hold down middle button and move pointer stick to scroll". I'll check with my laptop's touchpad and update this comment in a few minutes.
