### ISSUE TITLE
Naturals wonders shouldn't be effected by fallout

### ISSUE THREAD

**Issue by whatsupboy** [yairm210/Unciv#2827]
Unlike Civ 5, naturals wonders within the two tile nuke radius are effected by fallout meaning they supply -2 food and -2 gold. Obviously the fallout shouldn't have an effect on them because as they are impassable the fallout can't be removed by workers and they are rendered useless/less useful for the rest of the game.

**Comment by ninjatao** [comment]
No idea how does civ5 deal with this. Just committed a pr to stop fallout on impassible terrain.

If anyone knows civ5 logic about this please comment.

**Comment by yairm210** [comment]
Resolved by @ninjatao
