### ISSUE TITLE
Naval melee units attacking land units

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2829]
This isn't possible in civ v and makes these ships overpowered in unciv in my opinion

**Comment by HeavyTank-1** [comment]
Thats true, I keep having my workers on coastal cities beeing destroyed by barbarian Tyremes, Its really anoying and don't make much sense. And naval units in general are very strong, so it really is a pain in the @ss.

**Comment by yairm210** [comment]
I ran a poll in our Discord, and 'naval units should attack' outvoted 'naval units shouldn't attack', so I'm closing this as an acceptable deviation from the original
