### ISSUE TITLE
Feature to see AI army power. 

### ISSUE THREAD

**Issue by HeavyTank-1** [yairm210/Unciv#2835]
**Is your feature request related to a problem? Please describe.**
A way to see the AI army power, like on Civilization 6.
**Describe the solution you'd like**
Adding a system where from the diplomacy screen you could see the AI army power compared with your own. Maybe it could only be unlocked at a certain tecnology.

**Additional context**
I think it is a very useful feature to have in the game, so you could more easely decide wich civilizations to attack.

**Comment by yairm210** [comment]
You can see this in the victory screen, and even that I think is too much. Part of the deal is not knowing exactly how strong everyone is.

**Comment by HeavyTank-1** [comment]
Oh yes, i get it, thank you.
