### ISSUE TITLE
Cannot attack with bomber on carrier

### ISSUE THREAD

**Issue by Improver2000** [yairm210/Unciv#2845]
Hi, marvellous game!!!

I have a problem: I cannot attack with my bombers on the carrier. Seems to be a bug?

**Comment by yairm210** [comment]
Not one that anyone else has reported, and we haven't changed anything related in a while.
A. Are you sure the bomber is selected?
B. Are you sure the target is within attack range? (Shorter than movement range)

**Comment by Improver2000** [comment]
![20200714_122235](https://user-images.githubusercontent.com/65492926/87414938-c22dc080-c5cc-11ea-827a-d9098833418d.jpg)

See pic. Everything in range. But cannot attack.

**Comment by Improver2000** [comment]
![Image4070516606609117496](https://user-images.githubusercontent.com/65492926/87415359-497b3400-c5cd-11ea-9105-5555f3e21d3c.jpg)

See pic. Attack button is grey.

**Comment by yairm210** [comment]
You don't have any line-of-sight to the city, you need the city to be visible in order to attack

**Comment by HeavyTank-1** [comment]
It doesnt make much sense to me, looks like a very silly limitation, the bombers are by your side bur you cant shoot them because you cant see the city they came from? Are you planning on changing them any time soon?

**Comment by yairm210** [comment]
? You can't see the city you're trying to *attack*. Like with all ranged attacks, you need to see what you're aiming at.

**Comment by HeavyTank-1** [comment]
Oh, I misunderstood, I was thinking that the aircraft wasnt able to defend itself. Sorry for this.
