### ISSUE TITLE
Nuova modalità

### ISSUE THREAD

**Issue by Gabriele0005** [yairm210/Unciv#2848]
Gioco ormai da quasi un anno (con un periodo di interruzione) e ho notato le modifiche del nuovo aggiornamento e mi congratulo vivamente con il produttore/produttrice. Dopo un po' di tempo di gioco (più o meno 300/400 turni) inizia ad andare a scatti e prego che sistemiate. Suggerirei inoltre di inserire una modalità per inserire mod e un'altra modalità SENZA TURNI come in alcuni giochi in tempo reale, magari mantenendo tutto uguale, possibilità di migliorare celle, fondare città ecc e il multigiocatore

**Comment by yairm210** [comment]
Hi, this is not the place for suggestions but I'll answer anyway.
We already have mods, you can join our Discord where there are active modders =)
The game wouldn't function without turns though.

**Comment by Gabriele0005** [comment]
I understand. Thank you anyway
