### ISSUE TITLE
Sleeping units keeps them alseep

### ISSUE THREAD

**Issue by Crit-Cee** [yairm210/UnCiv#285]
After putting a unit to sleep any action with that unit afterwards still doesn't awaken them. Example: I put a worker to sleep. A feww turns later I move it to work a tile, but after moving it is still alseep. It won't come up when I press the green arrow to switch between active units. There have been many times that I had an idle unit for many turns cause I didn't realize they didn't wake up from a previous action.

**Comment by Crit-Cee** [comment]
Correction: after doing an action (othe than move) with a work that was asleep they do automatically wake up. Issue I had before with a knight still staying in sleep state is that they can only do move and attack actions; no fortify, set up, improve tile action to break them out of the sleep state.

**Comment by yairm210** [comment]
Solved, correction will enter next version =)
