### ISSUE TITLE
a few missing trade and diplomacy options

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2851]
1. Broker peace between warring AI.
![8930_screenshots_20200715145617_1](https://user-images.githubusercontent.com/64375454/87592268-2f198700-c6af-11ea-9d4c-bf330d988019.jpg)

2. Enter custom amounts during trade (example in screenshot above). Especially in late game some trade deals might require 2000+ gold or so which currently takes quite a bit of clicking! 

2. Gifting units to city states or to other civs.

![8930_screenshots_20200715144624_1](https://user-images.githubusercontent.com/64375454/87592589-bebf3580-c6af-11ea-8c6c-ba117894547f.jpg)

![8930_screenshots_20200715144645_1](https://user-images.githubusercontent.com/64375454/87592608-c5e64380-c6af-11ea-8941-654a0be9ff46.jpg)

This requires open borders with ai Civs but with city states it can be done via the diplomacy screen

**Comment by yairm210** [comment]
Should be in #663 if this was in orig. civ
