### ISSUE TITLE
negative specialists

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#286]
1. assign a population as a specialist
2. start razing city
3. when population decreases (next turn):
  * you have **negative specialists number**
  * you can assign city population to work on city tiles in number equal to city population - 1 (someone becomes lost in the code)
4. call the "negative" specialist off - number of available city population to work on tiles does not raise

**Comment by yairm210** [comment]
Good catch!
Hope to deal with this soon!

**Comment by yairm210** [comment]
Fixed, will enter 2.10.7!
