### ISSUE TITLE
battlefield surveillance/AWACS unit

### ISSUE THREAD

**Issue by flyer1990** [yairm210/Unciv#2870]
**Note:** I hope this is the right place for my request, I never used gitHub before.

Hello,

I think an airborne unit with a great visibility is needed, to e.g. guide ranged attacks by bombers withot the necessarity of land units or just to get an overview of what is happening where.

This could be in form of an AWACS (airborne warning and control system) which wold likely be researched with the technology "radar".

Further, it would have to stay in the air for several turns and, for compensation, just move 5 or so tiles per turn. Here, after half of its turns in operation are gone, it would be just allowed to move in a direction where it is definetely able to land when no turns are left.

But for the rest it would act like a bomber without damage capability. So it would be interceptable and landable in cities and perhaps carriers.

I do not have further details or pictures, this was just an idea I wanted to come up with, and I honestly do not know if this is far too ambitious and even appropriate in this form here at gitHub.

However, thanks for your time : )

**Comment by yairm210** [comment]
As per our guidelines, we're not adding any non Civ. v features, but you could mod this in yourself with the '6 tiles visible' unique
