### ISSUE TITLE
Translation is not applied

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2871]
- Is it impossible to add new translation line?

There are unused diplomatic translation about city liberation in [Korean.properties](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Korean.properties).

In translation: We applaud of your liberation of **_our_** conquered cities! = ...
In game:         We applaud of your liberation of conquered cities! = ...

Little different but obvious. "our" must be deleted in translation file.
So [I made additional translation of in-game one.](https://github.com/yairm210/Unciv/pull/2858/files)
But it was deleted, so for now there's only first translation in Korean.properties.
I think i've fixed it not only this time, but also before, and somehow it returns.
And I've seen that my notation is deleted too. ( # thing )
Is there a standard translation template?
Can't I add some new line or move a line to some other places?

![캡처](https://user-images.githubusercontent.com/64586749/88115557-5b725d80-cbf1-11ea-95d9-e0798d66d9bc.JPG)

- Please add [ Unlock = ]

[ Lock = ] (citizen locking on city screen) is  so natural that I haven't thought that it should be translated.
But if it's added Unlock needs to be translated, too.
I'm insisting to write here cuz I've experienced above one.

**Comment by yairm210** [comment]
You're looking for template.properties :)
You can open a PR door changes there (I think that both 'our conquered cities' and 'conquered cities' exists in game, so it'll be an addition not a replacement)
