### ISSUE TITLE
Unable to build some buildings

### ISSUE THREAD

**Issue by zivvel** [yairm210/UnCiv#288]
I don't know if there is some undocumented requirement, or if it was something related to my particular map, but I am unable to build Circus in the 4 cities on my starting island.  I traded techs with another civ to acquire Trapping, and I was still unable to build Circus.  Later, I embarked a settler over to the big island where the other 3 civs are, found some horses, and plopped a city down.  I can build a Circus there, but still not on my original island.  Access to horses required?

I also traded for Calendar, and I could not build Stone Works anywhere, even in my new city, until I built a quarry on Stone.  I don't see that in any doc. And I still can't build it on my original island.

**Comment by yairm210** [comment]
Circus requires worked horses or ivory *within the city area*
Same for stone works for stone or marble, iron for forge etc

BUT you are correct that this isn't displayed to the user!
I'll fix this now, and will enter the next version

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/49162870-85984d00-f334-11e8-9839-09305b309456.png)

Done!
