### ISSUE TITLE
Plain forest blocking view of river

### ISSUE THREAD

**Issue by gdanskleme** [yairm210/Unciv#2886]
**Describe the bug**
The plain forest blocks viewing of bottom river from the tile north

**To Reproduce**
1. Go to the map editor or any random map
2. Place a plain forest 
3. Place the bottom river on the tile north of it

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/88693924-8cc6be00-d108-11ea-9157-fc4821a48433.png)

Uh, no?
All rivers are perfectly visible

**Comment by gdanskleme** [comment]
I meant forest,not jungle

**Comment by yairm210** [comment]
Ah, you're right
Even I got confused 😓
