### ISSUE TITLE
No resources on Coast tiles.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#289]
I noticed that since 2.10.5 map generator no longer put resources on coast tiles(fish/whales/pearls). As I know absolutely nothing about Android nor kt, I cannot locate it.

But I am pretty sure that it is cause by this commit : 6c9297abc210d06de2fe41d2edf93fcf24dbd2cc, because I compiled the previous commit and worked fine.

**Comment by ninjatao** [comment]
how effective!

**Comment by yairm210** [comment]
Done =)
