### ISSUE TITLE
Can't find my map

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2893]
**Describe the bug**
I make a new map, save and upload it. But can't find it on "Load map".

**To Reproduce**
1. Make a new map on map editor
2. Save your map with not confusing name
3. Upload your map and check it says "Map upload successful!"
4. Go to "Load map" and search your map
5. Check it doesn't come out
6. Check existing maps are downloadable and searchable

**Screenshots**
https://youtu.be/SFW7OhdbPo4

**Additional context**
On discord lots of guys are waiting to see the Brazil map of AlexSCosta :)

**Comment by JackRainy** [comment]
I assume the reason is that you are using the special character such as "?" in the name of the map.

**Comment by saud2410** [comment]
@JackRainy Imao it's not true. Please try yourself.

![Screenshot_20200728-113201_UnCiv](https://user-images.githubusercontent.com/64586749/88612530-62eca780-d0c6-11ea-97c5-f99bf1490b56.jpg)

**Comment by vainiovano** [comment]
`DropBox.getFolderList` is used to get the list of files

https://github.com/yairm210/Unciv/blob/b816d1036d2ef2d6373187a6ad7f4fd20b39db38/core/src/com/unciv/ui/mapeditor/MapDownloadPopup.kt#L49-L59

It uses the `list_folder` API
https://github.com/yairm210/Unciv/blob/b816d1036d2ef2d6373187a6ad7f4fd20b39db38/core/src/com/unciv/ui/worldscreen/mainmenu/DropBox.kt#L48-L52

The problem with this is that [the list_folder API](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) only starts returning the contents of the folder. `list_folder/continue` should be used to get the next chunk.

An another way would be to use the DropBox `search` API to handle the filtering on the server.

**Comment by vainiovano** [comment]
@yairm210 pinging you because you haven't yet responded to this

This is a big issue because it prevents any new uploaded map files from being found from the server. "Can I Download my map?" is on the server but the game can't find it because it doesn't load the whole directory listing.

**Comment by yairm210** [comment]
🙄 
It's been 5 days, man
I have other stuff I'm working on
