### ISSUE TITLE
Cannot resume game

### ISSUE THREAD

**Issue by bitappend** [yairm210/Unciv#2897]
**Describe the bug**
After update sometimes I cannot resume game, first time thought was fluke. It has now happend on my 3rd new gam. Around the time I finished the science tree.
Possible second issue or perhaps related, my romans loose ability to make scouts at some point. I Like using them as spotters for my artillery.

**Screenshots**
Attached
![Screenshot_2020-07-27-12-28-01](https://user-images.githubusercontent.com/45378636/88660696-15534900-d08c-11ea-98cf-68c6fb7e5c8b.jpg)

**Comment by yairm210** [comment]
Please send game data

**Comment by bitappend** [comment]
http://www.filedropper.com/gamesave

**Comment by yairm210** [comment]
Your save file is corrupted, you can load the turn's autosave from load game - show autosaves
Not much I can do with this
What version are you on?

**Comment by bitappend** [comment]
3.9.12
I'll try to save manually more. This has happened several times and is a bit annoying. I might roll back to earlier version. This only appeared after my last update.
