### ISSUE TITLE
Volley promotion overwrites seige weapon bonus.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#290]
Seige weapon has built-in 200% bonus vs. cities. If volley is picked, the bonus drops to 50%(instead of 250%).

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/49163647-42d77480-f336-11e8-81b0-2ff5e9df82ec.png)

Fixed, thanks again!
Will enter 2.10.7
