### ISSUE TITLE
Erratic unit maintenance cost 

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2900]
It's hard to say how to replicate this without playing a full game so I'm using my 800+ turn one as an example. The issue being on one turn I will have multiple hundreds of gpt and then on the next my unit maintenance prices skyrocket and I will immediately go into negative gpt. 

I didn't capture a screenshot right before it happened here but as you can see in the pictures I could not have purchased nearly enough units to go from  400+ gpt to nearly -200 in ~10 turns. The third picture shows how when this happens I can disband a single worker to gain back 40 gpt. This will continue and then suddenly I will gain my gpt back seemingly at random.

![Screenshot_20200729-132935_UnCiv](https://user-images.githubusercontent.com/64375454/88844401-35782a80-d1a8-11ea-877f-ee6a1b32eee4.jpg)

![Screenshot_20200729-142115_UnCiv](https://user-images.githubusercontent.com/64375454/88844673-9e5fa280-d1a8-11ea-8ecb-4d5712c026c8.jpg)

![Screenshot_20200729-142131_UnCiv](https://user-images.githubusercontent.com/64375454/88844678-a0c1fc80-d1a8-11ea-9330-65ec08875efb.jpg)

Unfortunately my save must have too many characters because it won't let me paste it here.

**Comment by yairm210** [comment]
Unit upkeep is exponential with the number of units you own - so your 20th units will have a much higher upkeep than your 10th.
This is in line with the way Civ V considers upkeep

**Comment by halloamigos** [comment]
I see. I looked up the formula for this and it's very indecipherable for me but after looking it this seems like an issue in civ v as well. My apologies, I'll close this one out! Thank you
