### ISSUE TITLE
"enable nuclear weapons" on "start new game" is always checked, even if i start a new game out of a game w/o nukes. 

### ISSUE THREAD

**Issue by scaphander** [yairm210/Unciv#2901]
**Describe the bug**
"Enable nuclear weapons" on "start new game" is always checked, even if i start a new game out of a game w/o nukes.

**To Reproduce**
1. Start a game without nukes
2. Start a new game out of this game
4. See error: nukes enabled on new game screen, previous setting is ignored. 

**Expected behavior**
Checkbox should not be checked, as all other former game settings are transfered to the new game screen.

**Comment by saud2410** [comment]
I think i've seen a poll about this on discord, like "What do you prefer on nuclear weapon when starting a new game?" I know you might not do discord, and I've failed to find the poll. Anyway it's not a bug. However, if you think nuclear isability should be decided by user, not hardcoded, I vote for you.

**Comment by scaphander** [comment]
When starting a fresh new game in the main nenu, i think nukes enabled per default is okay, particulary when there was a poll.

But im talking about starting a new game out of an existing game. I would expect that my current settings are carried over, as all the other setting are already carried over.

**Comment by yairm210** [comment]
Solved in 406959c :)
