### ISSUE TITLE
Can't trade techs

### ISSUE THREAD

**Issue by mbeckish** [yairm210/Unciv#2902]
I can't trade techs with the computer any more.
My techs and the computer's techs don't even show up in the trade screen.
I'm not the only one - there are a number of similar complaints in the reviews section in the Android Play Store.

**Comment by yairm210** [comment]
This is not a bug, this was deliberately removed tp fit Civ V

**Comment by bitappend** [comment]
I was unaware it was removed. It's totally ok that it was. If you add back as an option defaulted to off you might appease people questioning it and reduce tickets for it.  It definitely changes play style. But im cool with it gone

**Comment by refola** [comment]
I could have sworn that Civ V lets you sell techs *that your civ personally researched* and buy techs *that the other civ personally researched*, along with a "tech brokering" option which allows to buy a tech from one civ and sell it to another. Looking it up, I was mistaken and this is actually a Civ IV feature. It would still be an improvement for Unciv, but it makes sense to have tech trade completely disabled by default.
