### ISSUE TITLE
Raging Barbarians! Also Barbarian XP Mod?

### ISSUE THREAD

**Issue by rrross2** [yairm210/Unciv#2905]
New here, so hopefully this is the right place and format for this question. I haven't located prior discussion of this topic so far, but corrections/redirections are welcome.

My favorite single feature in vanilla Civ V was the Raging Barbarians setting. So far this feature has not been implemented in Unciv. Is this planned?

How to build the full tickbox interface and everything is beyond my (lack of) skills, but if my cursory research is right, this would require changes to GameInfo.kt (fun placeBarbarians). Is this possible, given the modding structure? Being a complete neophyte, it looks like I can't do this via JSON-in-a-mod-folder. Instead, I'd need to just create my own fork of the code with this value hardcoded (which would affect all games played on my version).

A similar question extends to my favorite Civ V mod: removing the XP cap from barbarian combat. This looks like another case where a JSON won't cut it -- Battle.kt (private fun addXP) requiring a modification.

Have I understood this correctly, or is there a better/simpler way to build a mod for these two features? Thanks in advance!

**Comment by yairm210** [comment]
Current modding indeed would not allow these modifications
The second mod is sounds super simple to make, barely an inconvenience. but it will require you to fork the project
The first one sounds a lot more ambitious, BUT if it was part of the base game, then if you make it, you can make a PR to add it to Unciv and I'll add it in the general game =D
Missing features from the original game should go in #633 if you want to add them ;)
