### ISSUE TITLE
City capture-destroy mechanism

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#2911]
I think there needs better way to destroy a city.

Korean Civ V wiki says "When a city is captured, defensive & cultural buildings are all destroyed, population drops to the half. Former city-state  and capitals cannot be destroyed."
Sorry that i can't find from English civilization wiki.

Unciv has different capture & destroy mechanism. Captured AI city has intact monuments, city walls, etc. Population drop is not half, it's different by city size and the era, but mostly 2~4 drop. Even on first capturing, razing needs annexing, causing rise of culture on selecting civic. And if you wanna destroy city-state or former capital you have to wait nuc or hit it before it grows to Lv3+.

Here's my personal question: It's good to get benefit from puppet cities on current mechanism. But what if I'm concerned about the position of enemy city? What if I just don't like where the city is, so i wanna completely get rid of it before nuclear bomb, even it's unbreakable?

I know Civ series are about "civilization" - I can't do RPG or FPS on Unciv. I have to bear bitter moments, have to prepare to avoid it - Rules are rules. But I wanted to ask what is your intention of less destroying cities. And if I'm not ridiculous, could you consider implementing more destructive capturing mechanism?

**Comment by yairm210** [comment]
All cities except for the capitals can be razed.
The capitals cannot, for 2 reasons:
1. This means that all civs have a chance to 'get back in the game' if their capital is liberated
2. We have a long-term plan to move to Civ V's conquest victory, which entails being the only Civ still holding it's original capital, and razing capitals effectively means removing one of the civs from the game.
The "no capital razing" is also a Civ V mechanic
