### ISSUE TITLE
Diplomacy should mean more

### ISSUE THREAD

**Issue by sirsyolo** [yairm210/Unciv#2916]
It's very annoying when a civ declares war on you for no reason at all, with your relationship at a positive number. If someone spends time working on diplomacy with trade requests, friendship declarations etc. it isn't fair that war is declared on them for no reason, because it makes diplomacy obsolete.

**Comment by ravignir** [comment]
Well, if you have nonexistent army, there is no diplomacy.

**Comment by yairm210** [comment]
War is just an extension of diplomacy by other means.
I understand your frustration, but the AI is out to win, as well.
