### ISSUE TITLE
Extremely aggressive AI

### ISSUE THREAD

**Issue by Dalcinrafa** [yairm210/Unciv#2920]
Nations declare war even after signing declarations of friendship, with no provocation, when if you do so, you get punished. For some reason, they ask for peace when you build a submarine.

**Comment by refola** [comment]
Go to Menu -> Victory status -> Rankings, and compare Force when they attack you and when they ask for peace. In general, AIs will attack you for being weak (especially on higher difficulties) and try to make peace if you're way stronger than them.

Without more details, I'm guessing you were playing on a medium-ish difficulty and neglected your military for a few eras. Then when you built the submarine that increased your force enough that the AI wanted peace. (Normally I have to build several submarines and kill off most of their units before they want peace, but I've mostly been playing on Emperor and Immortal.)

As for punishment for warmongering, the AIs *should* also face diplomatic penalties from each other. But I'm not sure if they AIs trade with each other enough for the penalties to matter to them.

**Comment by yairm210** [comment]
The AI is out to win, so if you're weak enough that no one cares about you, it will attack despite the diplomatic backlash that it receives from the other civs.
The diplomatic relationships ARE important when you're stronger - you need bto be really, really weak for the AI to declare war on you despite a declaration of friendship =)
