### ISSUE TITLE
Individual difficulty sliders

### ISSUE THREAD

**Issue by Dalcinrafa** [yairm210/Unciv#2922]
I wish there could be set individual difficulty values for each stat, like base happiness, just like Freeciv.

**Comment by refola** [comment]
This could probably be done with mods already. There's already a "[Difficulty sandbox](https://github.com/paontv/Unciv_Difficulty_Sandbox/releases/tag/v1.2)" mod that changes a lot. (I haven't tested it; I just remembered it from the [official(?) spreadsheet of mods](https://docs.google.com/spreadsheets/d/1043Ng9ukrL3y8MUXBVl7-C9JsQGnBi5R5mkmS2l7FFg/edit).)

**Comment by yairm210** [comment]
Since this is not something that was in Civ V, is not something that the average player even thinks about, AND is resolvable via modding, I'm crossing this one from the list.
