### ISSUE TITLE
I am not able to copy my PLAYER ID.

### ISSUE THREAD

**Issue by HeavyTank-1** [yairm210/Unciv#2932]
**Describe the bug**
I am not able to copy player ID to create an miltiplayer game.

**To Reproduce**
1- Go to Create New Game.
2- Activate Multiplayer Option
3- Try to copy your PLAYER ID.
4- The copy option doesnt appear.

**Expected behavior**
A copy option should appear.

**Screenshots**
![Screenshot_20200802-193622_UnCiv.jpg](https://user-images.githubusercontent.com/67478243/89133995-7b5e2700-d4f7-11ea-9b52-0e32cc48e285.jpg)

I know that there is a "special" screen to do that already, but it would be very good to be able to do that from the Create Game page.

**Comment by yairm210** [comment]
A. A feature you want that doesn't appear is not a bug
B. You can just copy it like you would any other text, by long-click. I don't see the problem.
