### ISSUE TITLE
Not able to continue game

### ISSUE THREAD

**Issue by kahngjoonkoh** [yairm210/Unciv#2935]
**Describe the bug**
Random crashes occur. I cannot go to the next turn and it says "waiting for the next player" forever. The only way out is to go to main menu. I tried loading the game again, but it happens during the same turn when the initial crash happened. I have played the game with on mobile but no problems have been found. My laptop is windows 10 and I have only played two games so far. They both crashed and I can't continue playing them. 

Right now for my device, Inca and China has been unable to continue to the next turn.

**To Reproduce**
I am not sure how this happens
I just play the game and it crashes

If game data is required, please add from menu, save game, copy to clipboard, paste here
If needed I will provide, currently, I have emailed the developer.

**Expected behavior**
"waiting for other players" appear forever, until an error message comes up. The game is no longer playable. Even after reloading the game nothing changes.

**Screenshots**
<img width="722" alt="err1" src="https://user-images.githubusercontent.com/46638829/89171482-4c48c380-d592-11ea-98c1-8318fd0fae89.PNG">
<img width="723" alt="err2" src="https://user-images.githubusercontent.com/46638829/89171536-6387b100-d592-11ea-9d64-c46e42c37616.PNG">
<img width="717" alt="err3" src="https://user-images.githubusercontent.com/46638829/89171549-67b3ce80-d592-11ea-8d5d-1eb7a1b8c991.PNG">
<img width="722" alt="err4" src="https://user-images.githubusercontent.com/46638829/89171588-7601ea80-d592-11ea-9e2e-9f8448548c70.PNG">

**Additional context**
It is my first two games playing on a windows laptop. Downloaded from the github download page.

**Comment by yairm210** [comment]
Should be solved in recent versions, please update =)
If not, please add your game data here, and we'll reopen the issue
