### ISSUE TITLE
I've been banned from the discord server

### ISSUE THREAD

**Issue by EFLYT** [yairm210/Unciv#2936]
Hello, I need help, I think I've been banned from the discord server, I cant join anyone, if someone can tell an admin to unban me, or see what's wrong, I would appreciate it, my discord is Charlie Jones#2641

**Comment by yairm210** [comment]
If you were banned, it was for violating the server rules.
I'm not going to second-guess our admins on this.

**Comment by EFLYT** [comment]
> If you were banned, it was for violating the server rules.
> I'm not going to second-guess our admins on this.

That's the thing.. I didn't talk at all and I dont remember violating any rules
