### ISSUE TITLE
Game very laggy in city screen

### ISSUE THREAD

**Issue by sirsyolo** [yairm210/Unciv#2938]
**Describe the bug**
In the city menu/options/whatever it's called, where you can choose a city's constructions and assign its population, my game becomes extremely laggy, with inputs taking about 10-15 seconds to register.

**To Reproduce**
Not sure how it was reproduced, just from playing the game

**Expected behavior**
Game should run as normal when in city screen, I.e. responsive and not laggy

**Comment by yairm210** [comment]
Send me the game data you're working with

**Comment by ravignir** [comment]
I have the same issue (both on windows and android), i think it begun with 3.9.17 update.

**Comment by yairm210** [comment]
Fixed in a393036
