### ISSUE TITLE
add new unit and fix liberate nation

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#2939]
-add declarate peace to other nation 

-if liberate nation auto Alliance and open border and diplomacy following my nation if war join war if made peace join peace

-add stealth fighter & bomber can't  detected by anti aircraft but detected on mobile SAM
-add SAM for counter attack stealth fighter 
-add drone if launch a target location drone can view location view for 1 turn and can counter attacked by anti aircraft 
-add modern missile  destroyer (upgrade battle ship)  this unit can carry Balastic missile
-add Balastic missile only on city and can carry on modern missile destroyer and nuclear submarine 
-add nuclear submarine can carry nuclear missile and Balastic missile 
-add unit herchules plane can carry groun unit and drop unit like a paratrooper
-add spy can sabot work progress in enemy city
-add helicopter unit good mobility and good vs armored unit but weak to anti aircraft and jet fighter
-add give unit to friendly nation
-add sniper unit can hit in long ragnge like a archer but painfull for land unit

**Comment by yairm210** [comment]
Non Civ V units etc. will not be added
Civ V features should be added as a comment to #663

**Comment by HeavyTank-1** [comment]
@AyoPlayGames Maybe you could add this units as a mod.
