### ISSUE TITLE
Cost of units really high & low

### ISSUE THREAD

**Issue by SenorJonno** [yairm210/Unciv#2945]
**Describe the bug**
The costs of purchasing units changes to a minus figure at an unknown point in my game. I can purchase units and increase my gold amount. 

This also happened prior to the current update.

I loaded an older game (500 turns) and on that one the cost of units are 10s and 100s of thousands to purchase.

**To Reproduce**
Playing the latest update of game on Samsung A50.
I'm not sure what point the prices changes. It could be when I reach a certain social policy. 
I started a new game and everything was okay again. But then after around 200 turns it changed.

**Expected behavior**
I'm not sure are these prices correct as of recent updates but they make the game unplayable once you reach a certain point.
Expected behaviour is the prices as they were prior to the update.

**Screenshots**
![Screenshot_20200806-011348_UnCiv](https://user-images.githubusercontent.com/69281060/89560895-a4d8c480-d80f-11ea-9722-0aed5cf289cf.jpg)
![Screenshot_20200806-011434_UnCiv](https://user-images.githubusercontent.com/69281060/89560909-abffd280-d80f-11ea-86a7-0b430da94200.jpg)

**Comment by unknownguy2002** [comment]
I believe this may be caused by the Mercantilism Policy? I believe it may have been fixed

**Comment by SenorJonno** [comment]
Sorry I didn't see that. New to GitHub. Does that mean it will be in a later update or is there something I should do?

**Comment by yairm210** [comment]
Fixed, will roll out in 3.9.19
Caused by having either Big Ben or Mercantilism
