### ISSUE TITLE
open border update

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#2947]
i don't know how many turn open border, and no information open border will end, and give notification if open border will end and give choice continue open border or not. if liberate other nation atomate allied and open border

**Comment by yairm210** [comment]
The first is available in the overview - trades screen
Notifications and option to continue is a good idea
Auto alliance and open borders is not

**Comment by AyoPlayGames** [comment]
![IMG_20200808_000207](https://user-images.githubusercontent.com/69257137/89669973-9c18e900-d90a-11ea-84e8-74b600e9c2bc.jpg)

maybe add like this

"Notifications and option to continue is a good idea" 👍👍👍👍

"Auto alliance and open borders is not" maybe my private problem only because after i liberated other nation and no auto open border my formation unit pulled far far away land and destroy formation 


-good work-
