### ISSUE TITLE
Apk not shipping correctly on play/fdroid

### ISSUE THREAD

**Issue by Dalcinrafa** [yairm210/Unciv#2950]
Latest apk is never on fdroid and Google play. A solution could be adding an apk to releases on github. Both are 3.9.16 for 5 days now and 3.9.16 is crashing like crazy.

**Comment by ravignir** [comment]
I already have 3.9.18 on google play so you are probably in the last batch to get the update.

**Comment by yairm210** [comment]
F-droid has its own schedule, and I manually rollout Google Play gradually to look for errors.
Not a bug

**Comment by Dalcinrafa** [comment]
I apologize, I reinstalled from the play store and now it's up to date. I guess it's fdroid's weird scheduling.
