### ISSUE TITLE
make other nation make peace

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#2952]
add request to other nation make peace simple case, i played nation A and make Alliance to nation B and C for defeat strong nation D but nation B and C condition in war, no trade request make peace at nation B make peace at nation C

-good luck-

**Comment by yairm210** [comment]
Was this is Civ V?

**Comment by yairm210** [comment]
It doesn't look like it was.
If it does happen to have been there, this should go into #663

**Comment by ravignir** [comment]
It is in civ5, can confirm. Make peace with (City State/Cicvilization) - either as a demand or as a trade offer.

**Comment by ravignir** [comment]
![htd6uvipwhgy](https://user-images.githubusercontent.com/30041793/89718545-af39c080-d9bf-11ea-90a5-9ec5d4021ef0.jpg)
You can clearly see it there
