### ISSUE TITLE
Map wraparound on east-west axis 

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2955]
This is the default on the majority of non-scenario maps in civ v and would greatly improve the unciv experience on many levels, not least being making Domination victory more feasible on huge and large maps (where currently the player or the AI are forced to travel the entire distance of the world to capture every city)

**Comment by yairm210** [comment]
Technically impossible right now
Unless you want to have a shot at it

**Comment by halloamigos** [comment]
Forgive me but would it not be better to leave this open as a reminder until the day it is possible? Similar to the older feature requests; or should I add it in a comment to the incomplete features list

**Comment by yairm210** [comment]
I think add it as a comment to #663
