### ISSUE TITLE
update hill

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#2960]
update hill maybe like this

![hillupdate1](https://user-images.githubusercontent.com/69257137/89722914-9eb63400-da19-11ea-900d-3b67c4add224.jpg)

-good luck-

**Comment by ravignir** [comment]
I edited some sprites hill sprites (actually I think all of them). It' a remix of existing tiles. Current Hill tiles - are Grassland Hills.
[Here on my github, they just need to be renamed accordingly.](https://github.com/ravignir/unciv-hill-sprites)

**Comment by AyoPlayGames** [comment]
Good work

**Comment by refola** [comment]
This should also work for things like solar plants which require a city to be in or next to a desert.

**Comment by yairm210** [comment]
This has finally been completed! It's been a long journey
