### ISSUE TITLE
Negative money when buying units

### ISSUE THREAD

**Issue by eliottdbs** [yairm210/Unciv#2972]
Description:
When i want to buy any unit, the price is negative. If i buy it, i get the negative amount add to my money.

Reproduction:
I have no idea when it started so i can't tell you how to reproduce it.
But when i save the game, i still bugs.

![Screenshot_20200811-182029_LI](https://user-images.githubusercontent.com/56924502/89923073-49884700-dc00-11ea-9e34-2f554b5165cb.jpg)

I hope this help for the development.

**Comment by ravignir** [comment]
#2967 #2945 #2956 #2946 #2962 #2964
It is fixed in 3.9.19.
