### ISSUE TITLE
Deserts

### ISSUE THREAD

**Issue by MrSP05** [yairm210/Unciv#2987]
Deserts should appear only in a few places between the equator and the tropics, as well as in civilization. And not on a strip in the middle of the map

**Comment by yairm210** [comment]
I disagree.
This is how deserts form in the real world (see: all of upper Africa, continuing into lower Asia)

**Comment by MrSP05** [comment]
But all this deserts are above Ecuador and below the Tropic of Cancer. Go to Google Maps and you will see. In the middle of the world exist jungles (like in Congo and Brazil)

**Comment by yairm210** [comment]
You're welcome to change the existing map generation code, but it's not something I'll spend time on since I think it's OK as it is
