### ISSUE TITLE
Simultaneous Turns

### ISSUE THREAD

**Issue by MrSP05** [yairm210/Unciv#2989]
I would like if a simultaneous turn option was added in multiplayer matches, because the turns in the late game take a long time and having to wait for your friend to do everything, then you can do it is very boring.

**Comment by yairm210** [comment]
Because of the way we've implemented multiplayer, this is not technically possible :/

**Comment by ingvart** [comment]
This request is so important that you should reimplement multiplayer from scratch to achieve it if necessary. Civ 5 has this, and it is a must. I gave up playing it in multiplayer immediately when I realized it isn't possible. There is no way I'm waiting on three other players to make their moves before my turn every round. The game will take three times as long this way, as if waiting a little isn't boring enough.
