### ISSUE TITLE
Cannot remove roads

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3008]
I am unable to remove roads, either with a worker or by pillaging with a military unit. As seen in the screenshots, I am not presented any such command. This is true both inside and outside my national border.

![Screenshot_20200818-211547_UnCiv](https://user-images.githubusercontent.com/1423934/90592154-c33ca980-e199-11ea-83e6-5388cb20eab1.png)
![Screenshot_20200818-211427_UnCiv](https://user-images.githubusercontent.com/1423934/90592160-c46dd680-e199-11ea-8b1b-9d04ac1b8c9c.png)

**Comment by yairm210** [comment]
Inside your budget it should be 'construct improvement - remove road'

**Comment by foolishgrunt** [comment]
Okay - I see that now. Not sure how I missed it.

Though we still need be able to remove roads outside the territory. The way it's implemented now, does it pose a conflict with the recently-implemented change that prevents building improvements outside national borders?
Aug 18, 2020 11:55:19 PM Yair Morgenstern <notifications@github.com>:

**Comment by yairm210** [comment]
I'm not sure I agree, I'll poll this.
If necessary though it's very simple.

**Comment by foolishgrunt** [comment]
Well, I'll add a little explanation to my opinion. I recall one game where another player attacked me suddenly, and I knew one of my outlying towns was going to be captured right away. It was separated from the rest of my territory, but linked by a road. I took the first few turns of the war to remove roads and slow the other player's advance, but as the mechanics stand in Unciv, I wouldn't be able to do that. So I think it's necessary to be able to remove roads outside of territory.
