### ISSUE TITLE
add information maintenance costs for unit

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#3027]
if my gold per turn minus, i must to disband unit but i don't know where the most expensive unit reduce incoming gold per turn

maybe like this

![IMG_20200825_004630](https://user-images.githubusercontent.com/69257137/91078654-26807d00-e66d-11ea-9b63-1ef78d869fab.jpg)

**Comment by HadeanLake** [comment]
a lot more complicated then few gold per turn per tank [Unit_maintenance civ5](https://civilization.fandom.com/wiki/Mathematics_of_Civilization_V#Unit_maintenance)

**Comment by yairm210** [comment]
Unfortunately, we're going by Civ V rules, which... leave much to be desired in this aspect.
I wish I could help with this, but it's highly likely to change by the time you're finished with your current unit...
