### ISSUE TITLE
Gmes crashes when using next turn and mods dont work

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3028]
Every time When all unit is done when clicking games just freeze and boots out
And Mod files don't shows up and don't work

Using a 9.0 version Tablet
1. Open app
2. Click on 'next turn'
3. Boom games freeze and boots me up
4. Mods don't show up and even has a mods folder

**Comment by yairm210** [comment]
What version?
If you're on 3.9.16 you need to upgrade

**Comment by khurtron6** [comment]
Even the todays update Its sucks Fix it Please

**Comment by yairm210** [comment]
Everything works perfectly
Was your game with a mod? If so, it's probably a problem with the mod and not the base game

**Comment by khurtron6** [comment]
My phone is and the mod is completely fine

**Comment by yairm210** [comment]
If it's crashing then it's obviously not fine.

**Comment by khurtron6** [comment]
then fix it please I will say something if it works

**Comment by yairm210** [comment]
I don't think you get it.
This is not a general problem, or a problem that anyone else seems to be facing.
It's a problem with the specific mod, and I'm not responsible for it.

**Comment by khurtron6** [comment]
yes

**Comment by khurtron6** [comment]
wait no I mean the game it self crashes when clicking next turn and it not the mod the just don't show up even it okay

**Comment by khurtron6** [comment]
I mean is when tap/click on "next turn" the game crashes even without mods
and mods doesn't shows up in game even its working

**Comment by yairm210** [comment]
Does this happen to you on a new game?
In any case, send me the game data

**Comment by khurtron6** [comment]
Yes its the game and how??

**Comment by khurtron6** [comment]
wait is found what is causing the games is okay if I'm not doing anything on the units and I move the units or make a unit it crashes

**Comment by khurtron6** [comment]
[com.unciv.app.zip](https://github.com/yairm210/Unciv/files/5126987/com.unciv.app.zip)

**Comment by yairm210** [comment]
There's nothing there.
You need to:
- Load game
- Copy game to clipboard
- Paste here

**Comment by khurtron6** [comment]
same saving Even playing in tutorial
