### ISSUE TITLE
Allow Mods to remove Nations

### ISSUE THREAD

**Issue by TheRexYo** [yairm210/Unciv#3035]
Recently, while working on a fantasy-themed mod, I noticed that a mod's modOptions file only has settings to remove Buildings, Units, and Techs. These features are very helpful, but there's a glaring issue that prevents true customization - the default nations can't be removed.

Rather simply, why not just add the same code you used for the other three, but with a different variable. Thus, nations could be removed and players can finally have themed mods (i.e. Ancient Greece shouldn't be fighting in a Star Wars campaign or something).

As for alternative solutions, I guess it'd be possible to give the modOptions file an 'override assets' option that disables the default assets. That would be much more tedious to program and less efficient to mod, though.

**Comment by HadeanLake** [comment]
```
{
	"isBaseRuleset":true
}
```

**Comment by TheRexYo** [comment]
There are only two nations in the Civ IV ruleset (which uses that setting). If the setting you're showing me does what I'm asking, then the Civ IV ruleset would only have 2 nations. Since there is no explanation of what that setting does, it's probably not what I'm looking for.

**Comment by TheRexYo** [comment]
In another context, what exactly does that do?

**Comment by HadeanLake** [comment]
Asserts that this mod is base ruleset instead of being addition to game
