### ISSUE TITLE
Bug on version 9.0 phone Crashes when doing anything Mod files donts shows and Useable

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3037]
Games crashes when Moving a Unit or making and etc
Mod folder don't work even the mod file works

1. Buy a crappy phone
2. download unciv
3. Use unit or make or Move
4. Game freeze and Crashes and say Unciv Has Stop working

**Comment by yairm210** [comment]
We're now on version 3.10.2, 9.0 is pretty old
First try to upgrade
If it's still a problem, send the game data

**Comment by khurtron6** [comment]
Its not about the data either and the version is all same outcome I try it
how many times

**Comment by khurtron6** [comment]
its not even the data its the game it self it just keeps doing of in all version I tried it already

**Comment by yairm210** [comment]
It's kind of amazing how in so many messages, you have failed to provide a single useful piece of information.
Not what happens.
Not what version your game is on.
And now you say it's not about a specific game.
How the hell am I supposed to help you of you don't even describe the problem.
Do you get the the main menu?
Do
Can you start a new game?
Does it crash on the first next turn or only after a lot?

**Comment by khurtron6** [comment]
i already and you the save files in the other issues

**Comment by khurtron6** [comment]
And I already described the issues

**Comment by khurtron6** [comment]
You want all the details

**Comment by khurtron6** [comment]
1 I can get in the main menu
2 I can't save either load the game
3 every single version does the same thing "unciv has stopped"
4 game only crashes when moving making working the units 
5 what I suppose to do I can't do anything so unciv will not carsh
6 Mod file don't shows even the mod is not broken
7 Save file Might change a when using other phone that not crappy
8 Its the Game it Self
