### ISSUE TITLE
Create a new civilization: La Gran Colombia

### ISSUE THREAD

**Issue by chriscr2** [yairm210/Unciv#3039]
Leader: Simón Bolívar
Unique ability: Ejército Patriota, which grants their units +1 additional Movement and allows them to promote units without ending their turn. 
Unique unit: Llanero (replaces Cavalry) gets stronger with each adjacent Llanero
Libertador (replaces spear rider)
Comandante General (replaces Grand General)
Unique building: none
Unique upgrade: Hacienda, the Hacienda provides Production, Gold and Housing bonuses, and a Food bonus for each adjacent Plantation.
https://civilization.com/news/entries/civilization-vi-first-look-simon-bolivar-leads-gran-colombia/

**Comment by chriscr2** [comment]
https://civilization.com/news/entries/civilization-vi-first-look-simon-bolivar-leads-gran-colombia/

**Comment by yairm210** [comment]
That's a Civ VI N nation, not on our roadmap :)

**Comment by chriscr2** [comment]
But if it could be added to some mod?
