### ISSUE TITLE
Mountain pain

### ISSUE THREAD

**Issue by zivvel** [yairm210/UnCiv#304]
I have a sad screenshot from my first new game featuring mountains below. Is this supposed to be possible?

![screenshot_2018-12-05-00-48-47](https://user-images.githubusercontent.com/242258/49495407-80ea0200-f828-11e8-9869-b9691c278d46.png)

**Comment by zivvel** [comment]
![screenshot_2018-12-05-00-48-47](https://user-images.githubusercontent.com/242258/49495341-4d0edc80-f828-11e8-8da2-92587e3e22b7.png)

**Comment by yairm210** [comment]
Yes, but I see how this is a problematic starting location... -_-
Maybe I'll make mountain ranges never cut access between land areas

**Comment by zivvel** [comment]
My 2nd starting position had the warrior & settler similarly trapped, and the scout was on the other side of the mountains. It's pretty rough, especially for Prince difficulty.

**Comment by yairm210** [comment]
Whoa
Maybe I should ease off mountain ranges entirely and just have them randomly fit the landscape

**Comment by yairm210** [comment]
Ruins is very easy to solve, that'll definitely be fixed by next version

**Comment by ninjatao** [comment]
![screenshot_20181214-074118](https://user-images.githubusercontent.com/6846049/49992618-8f21e600-ffbf-11e8-93a2-e7fda427d9ae.jpg)

Mountains generation needs some serious improvement. ^_^

**Comment by yairm210** [comment]
Randomly peppered it is then, until we find a non-game-ruining way to do ranges

**Comment by yairm210** [comment]
Mountains no longer appear in ranges as of 2.10.16, should solve this problem
