### ISSUE TITLE
Warning: Class 'com.unciv.app.desktop.DesktopLauncher' not found in module 'Unciv'

### ISSUE THREAD

**Issue by NoNZeeZ** [yairm210/Unciv#3046]
This is just my inexperienced and in Android Studio. I have followed all the steps in https://github.com/yairm210/Unciv/wiki/Getting-Started page. Forked, Cloned and Downloaded all the think I need. But I keep getting the prompt 'com.unciv.app.desktop.DesktopLauncher' not found in module 'Unciv' When I try to ran the Unciv Application in Android Studio. I searched through Google and couldn't find any solution for this simple issue. Do you have any idea or suggestion?

**Comment by yairm210** [comment]
Run it again and it should work, I think this is a cache problem in Gradle?

**Comment by yairm210** [comment]
Solved? Still need help?

**Comment by NoNZeeZ** [comment]
Oh I'm sorry I didn't the Github notification. I would try that today

**Comment by NoNZeeZ** [comment]
Sill not working. But wait! Do I need to complete download gradle-6.1.1-all.zip?

**Comment by NoNZeeZ** [comment]
Nvm Solved!

**Comment by alexban011** [comment]
> Nvm Solved!

what did you do ?
