### ISSUE TITLE
Bug Game crashes When Next turn Freeze

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3048]
My phone Processor Thinks the games Crashes when Clicking on next turn the game freezes naturally when next turn But my Phone thinks the game Stopped And That's why I can't Save Load And Play Game Crashes 99.99%

1. Click on Next turn
2. Game freezes
3. Game crashes

**Comment by HadeanLake** [comment]
Maybe it cant create SaveFiles folder or savefile in it. On pc it crashes if I do `chmod u-rw SaveFiles`

**Comment by khurtron6** [comment]
Nope The Phone thinks it stopped And Crashes the game
