### ISSUE TITLE
Billion Dollar Idea

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3049]
Game Has Own Mod settings so The community Can add Where's the  Modded Country Spawns

Adds New Units ICBM MIRV HGV (Hypersonic Gilde Vehicle [Same as The ICBM But Unpredictable Can Dodge Anti Missile]) Anti Missile Protect And Attack In coming Warheads Thermonuclear Destroys Everything and creates Huge Crater and Antimatter Bombs Fries the Electric Type Units And Destroy Everything Border Walls Make Borders Have Protection walls No Trespassing And Protects In Coming Units More naval units Scenarios

**Comment by DuffLagerleff** [comment]
> Game Has Own Mod settings so The community Can add Where's the Modded Country Spawns
can u plz explain this idea in more detail?

**Comment by khurtron6** [comment]
Fine when opening game and your in the game menu Has The Settings without
going in the game and turning it on just has "setting in the Main menu Tap
it And Has all the settings and Scroll Downward Has " Mods " name on it
turn it on Go editor And Find the nodded country and done places the
Country for example USSR Put the USSR Spawn point where do you want the
USSR To be

**Comment by TheRexYo** [comment]
I think what you're trying to say is, "add a mod selection screen to the map editor"? Is that right?

**Comment by TheRexYo** [comment]
I'm kinda confused.

**Comment by khurtron6** [comment]
its just simple and you manage to FAQ it up When go in the main menu A menu
name "Settings" open the Setting option all the setting stuff slide down to
the bottom Option name "Mods" turn on the mod go the the map editor Go the
nation spawn and the nodded Nation ha its own Custom Spawn Point

**Comment by TheRexYo** [comment]
Dude, I can barely even read half of what you're saying. If you're going to
post a suggestion, post it properly.

**Comment by yairm210** [comment]
What you're looking for is called a scenario.
See 'Scenario' in the wiki.
And yes, it's kind of unreadable... :/
