### ISSUE TITLE
"Automated workers don't replace improvements" and other options

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#3050]
Can you add "Automated Workers do not replace improvements", "Automated Workers do not remove features" and "Auto end turns" options to game options in the main menu just like in the civ5?
I just hate when my workers replace trading post on Bananas Jungle with Plantations - or sometimes other improvement when they are on top of resources.

![KYkgw](https://user-images.githubusercontent.com/30041793/91638138-972cee00-ea0d-11ea-9ea3-95c7049c8bb8.png)

**Comment by bitappend** [comment]
I manually control all of my workers for this reason. It's so annoying

**Comment by TheRexYo** [comment]
I think you circled the wrong options, but yeah. This would help a lot.

**Comment by ravignir** [comment]
> I think you circled the wrong options, but yeah. This would help a lot.

It's googled screenshot, not mine 😄

**Comment by yairm210** [comment]
Added the "don't replace improvements" option, and from what I gather that should be enough for regular use cases.
I don't really think you need the "don't remove features" option.
As for the auto end turn, what does that mean?

**Comment by ravignir** [comment]
Auto end turns means you don't have to manually end turn (click the button) when there is no action to make; all production in cities is set, there is no policy to adopt, no tech to start research, workers are automated/creating improvements and other units have no movement points - or are set to exploration/fortify/sleep. That's mostly useful in early game and/or slower game speeds.

**Comment by SeventhM** [comment]
I'm not sure why ravignir reopened as there's no additional comment explaining. Considering the amount of time that has passed, closing as solved unless someone can comment otherwise
