### ISSUE TITLE
More Generalized and Modulable Unique Effects

### ISSUE THREAD

**Issue by TheRexYo** [yairm210/Unciv#3051]
So recently I've realized a couple of things regarding mods. For starters, many of the uniques have non-parameter amounts for their effects, making it impossible to change values from the hard-coded amounts. I will list these here before I go any further.

- 'Golden Age' effects (the ones that Persia has. I know this because I've tried to modify them for use in one of my own civs).
- '+1 production and gold from all sea resources worked by the city'
- '+1 production from all sea resources worked by the city'
- '+25% Defence against ranged attacks'
- '+25% Combat Bonus when defending'
- '+1 Science Per 2 Population' (this one even has two hard-coded values)
- '+10% science and production in all cities'
- 'Training of settlers increased +50% in capital'
- '+33% culture in all cities with a world wonder'
- '+25% gold in capital'
- '+15% science while empire is happy'
- 'Culture in all cities increased by 25%'
- '+1 happiness from each luxury resource'
- 'Golden Age length increases +50%'
- 'Culture cost of adopting new Policies reduced by 10%'
- 'Science gained from research agreements +50%'
- '+1 Movement' (this one only matters when it comes to promotions, as units already have a speed stat for this purpose)
- '+1 Visibility Range'
- 'Increases embarked movement +1'
- 'Gold cost of upgrading military units reduced by 33%'
- 'Can carry 1 extra air unit'
- '2 free Great Artists appear'
- '2 free great scientists appear' (not sure why the capitalization is different from the previous one)
- 'Provides 2 free workers' (now the order is different, though I guess that's because it's a different effect)
- 'Enemy land units must spend 1 extra movement point when inside your territory (obsolete upon Dynamite)'
- 'Units pay only 1 movement point to embark and disembark' (Technically I don't think this one needs modding unless the default cost is greater than 2. My memory can't confirm if it is either way.)

Anyway, that's a _lot_ of potential parameters. It would be useful to modders if these hard-coded values were converted into something more modulable, preferably using the existing parameter format (since it's easier to program, I think). I don't think this should be the top priority or anything, but they would definitely improve the game without diverging too much from Civ 5. It should also be noted that a lot of uniques have hard-coded requirements as well, such as the 'no maintenance in hills' unique (which I could see being useful for a lot more terrains than hills). If these were to be modulable as well, the game might get a lot more traffic from aspiring modders like me (I originally came from the Freeciv modding community after I heard this game works on Android, even with mods).

I don't think there's really a lot of alternative solutions to this one, as it's a simple black and white, true or false scenario - either the values are modulable, or they aren't. I guess it's plausible that there are other ways than parameters to make them modulable, though. I just feel like this is the easiest way to accomplish this task.

**Comment by yairm210** [comment]
A lot of those are already replaced by generalized parameters, and others are planned.
Not much else I can say about that for now.

**Comment by yairm210** [comment]
Please move to #3242 parts that are still relevant
