### ISSUE TITLE
One-Use Nation Uniques

### ISSUE THREAD

**Issue by TheRexYo** [yairm210/Unciv#3052]
Okay, before I get to this issue, I'm just gonna tell you the story behind it. If you don't want to read it, skip to the next bolded asterisk **(*, after this one.)**

So basically, I was trying to implement an effect for my sauroid nation's "The Elder's Prophecy" unique ability, which in concept is supposed to give them a huge early-game advantage that fizzles away later on. I had been having trouble finding a good effect for this, and I was growing desperate since I planned to release my mod relatively soon after. I already knew that policy uniques can be swapped around with nation uniques, so I figured I'd give the one-time policy bonuses a go. I chose the "Empire enters golden age" unique (from the "Representation" policy) to start them in a golden age, the "+20% attack bonus to all Military Units for 30 turns" unique (from the "Autocracy" completion effect) to give them an early-game damage boost, and the "Free Social Policy" unique (from the "Free Religion" policy) to give them a headstart on the cultural expansion that they seek to win the game. As you might expect, when I opened the game and started a new save, none of these triggered.

**(*)**

Now anyway, let's move on to my suggestion. Why not add more single-use unique effects, or at least make the existing ones from policies trigger at game start (if you have them)?

This task probably isn't as easy to program as the previous suggestions I've made were/would be, but it is still an interesting concept that I hope you'll take into consideration.

**Comment by refola** [comment]
Per [the changelog](https://github.com/yairm210/Unciv/blob/master/changelog.md), Unciv 3.10.11 added the "Start with [] technology" unique. This seems like a genericification thereof. Ideally, it should be made even more generic to be a "Start with [X]" unique, where "X" can be any tech, policy, unit, or quantity of gold / science / culture / happiness, in addition to existing effects.

**Comment by yairm210** [comment]
Please move to #3242 if still relevant
