### ISSUE TITLE
Naval and land units cannot co-occupy city

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3054]
![Screenshot_20200829-133616_UnCiv](https://user-images.githubusercontent.com/1423934/91653196-3f18da80-ea53-11ea-9208-107bc7404d68.png)
My city is garrisoned with a crossbowman. My trireme cannot enter the city unless I first remove the crossbowman.

Per Civ5 behavior, the city should be able to be occupied by one land unit and one naval unit without conflict.

**Comment by TheRexYo** [comment]
I'm kinda' impartial to this one, but I'd like to mention that, according to Uniciv's code, both are military units and should therefore not stack. It doesn't change whether or not it's the expected behavior, but at least that explains what is going on.

**Comment by yairm210** [comment]
As far as I'm concerned this is not a bug, since this is the expected behaviour.
As for changing it to sit Civ V, possible but will require a number of significant changes in the code.

A couple of questions about Civ V:
Can military and civilian naval units occupy the same tile?
Can naval units and embarked units coexist?

**Comment by foolishgrunt** [comment]
Fair enough, it's not a bug.

To answer your questions: yes, military naval units can co-occupy tiles with both civilian naval units and with embarked land units.

**Comment by JackRainy** [comment]
Kind of related to my #2266 and PR #2269

**Comment by yairm210** [comment]
I don't think we'll be changing this in Unciv.

**Comment by ravignir** [comment]
> 
> 
> As far as I'm concerned this is not a bug, since this is the expected behaviour.
> As for changing it to sit Civ V, possible but will require a number of significant changes in the code.
> 
> A couple of questions about Civ V:
> Can military and civilian naval units occupy the same tile?
> Can naval units and embarked units coexist?

Sorry for the late reply, but embarked land units in civ5 G&K and BNW all count as a civilian units. So you can't have an embarked Rifleman on the same tile as embarked Worker, but you can have an embarked Rifleman on the same tile as Frigate.  Great Admiral is a separate type of unit that can be stacked with both at the same time.

In vanilla civ5, there can be only one unit on a single water tile at the same time.
