### ISSUE TITLE
Suggestion : Better map generation for rectangular map

### ISSUE THREAD

**Issue by Breace112** [yairm210/Unciv#3057]
Is this just me or the terrain generation still follows the shape of a hexagon on pangea type, even if the map is rectangular?

**Comment by samyelias** [comment]
Similarly, hexagonal continent maps are always one giant land mass in the east, one in the west, and an ocean down the middle. Also feel like there should be a "small continents" option between archipelago and continents.

**Comment by Breace112** [comment]
Very much agree

**Comment by samyelias** [comment]
Actually, I now realize "Default" might be the option in between Continents and archipelago.

However I also noticed that the Unciv map sizes seem to be 2 sizes lower than the Civ 5 equivalents. eg the Unciv Large is the Civ 5 Small.

**Comment by yairm210** [comment]
That's because of performance issues.
If we let users create maps 10x the size, they'd be 10x as slow, and we'd get loads of complaints from Android users.

**Comment by samyelias** [comment]
Ah, ok. I actually mainly play on desktop (it's so much faster and cleaner than the original) so I haven't seen performance issues.
