### ISSUE TITLE
Suggestion: reprioritize city border expansion

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3059]
![Screenshot_20200821-140258_UnCiv](https://user-images.githubusercontent.com/1423934/91653390-4e008c80-ea55-11ea-9ff3-3730b9c57d3d.png)
_Problem behavior 1:_ in the city in the screenshot, I expected either the desert-silver due south of the city or the plains-forest-furs to the northwest to be the first tile acquired. Instead, the first tile was the grassland-horses, followed by the grassland-cattle, followed by the plains-forest-furs. While this didn't meet my expected behavior, it's still reasonable enough. But as seen in the screenshot, the next tile targeted for expansion is a basic grassland tile. This I think should definitely *not* be targeted before the desert-silver. If I recall correctly from Civ V, luxury resources always took the highest priority (though it may have been tied with strategic resources).

_Problem behavior 2:_ I don't have photographic evidence, but just working from memory, it seems to me that the territory will (for example) expand to **all** tiles 2 spaces away from the city before expanding to **any** tiles 3 spaces away from the city. This does not match Civ V behavior, which would frequently expand city territory in irregular shapes if there was a clearly more productive tile 1 farther away.

_Proposed reprioritization:_ I think it would be more realistic to adopt a prioritization schedule similar to the one compiled at the Civ V wiki [here](https://civilization.fandom.com/wiki/Territory_(Civ5)#Border_Expansion). I cannot vouch that the outlined prioritization is precisely accurate, but at first read it appears much closer to Civ V behavior than Unciv’s current behavior.

To aid in this, perhaps one could assign points values to all possible tiles: for instance 4 points for tiles 2 away from the city, 3 points for 3 tiles away, 2 points for 4 tiles away, add 3 points for luxury resources, add 2 points for strategic resources, and so on. Add all relevant points for each tile and queue accordingly. The thought just occurred to me, but if it would be helpful, I’d be glad to spend a little time to work out a comprehensive points system.

**Comment by ravignir** [comment]
There is a post on reddit explaining how Civ5 border expansion works; 
https://www.reddit.com/r/civ/comments/4o4o6j/civ_v_border_expansion_algorithm/

**Comment by bitappend** [comment]
Is It possibly expanding due to a not yet discovered resource ob the tile like uranium?
