### ISSUE TITLE
Suggestions on civs abilities

### ISSUE THREAD

**Issue by Breace112** [yairm210/Unciv#3065]
Stuff to nations in unciv
These proposed points are interesting additions that could be added as players await patiently for bigger updates.
- France's Chateau
As German Hanse is added already even though is part of BNW, this too shall be added. France culture game will be immensely boosted, it's not like this civ's unique is one of the most unfortunate, right?
- Japan's BNW Ability
Their uniques only favoured domination victory. Which isn't bad if that's what players interested in, but being a militaristic civ means your culture will be bad at best. This ability will give Japan a little help on catching up on culture later, when autocracy opens up later on or even completing honor early. Moreover, this feature don't require any further changes to the game
- Korea's Ability
Developer's argued that korean full ability is too strong to be added, this is unjust for some reasons. I simply cannot think the reason to left out Korea's ability if your intention is to brought civ5 to android platform, otherwise playing korea in civ5 and unciv would certainly feel different. If you saw this as unbalanced, you might as well remove other civilizations unique, so everyone is equal. Oh God, I love communism.
- Ottoman's Ability
I believe the issue is that it's overpowered, correct? Even at both vanilla and expansions, Ottoman's navy will 100% capture defeated ships. I don't think 1/3 chance would be on par with the 3/3 chance, how about implementing prize ship promotion and privateer first?

This may conflict with your roadmap, but i see nothing interesting going on with the civs lately.

**Comment by ravignir** [comment]
100% agree with you.
If it is a civ5 clone, let it be 100% true to the original game. If it is not a clone, then why not make it a completely different game with other uniques and nations?

**Comment by yairm210** [comment]
We're not doing BNW stuff now. At all.
About Ottomans, see here: https://civilization.fandom.com/wiki/Ottoman_(Civ5)
It's 50%, and only for barbarians. So if anything it's overpowered now.

**Comment by yairm210** [comment]
I couldn't find a single source in the entire Internet (!) about how much tech the Korean 'boost when scientific building built' gives, making this currently inactionable
If you find one, reopen this :)

**Comment by Breace112** [comment]
> We're not doing BNW stuff now. At all.
> About Ottomans, see here: https://civilization.fandom.com/wiki/Ottoman_(Civ5)
> It's 50%, and only for barbarians. So if anything it's overpowered now.

I see about the BNW stuff, however I'm thanking you for responding to my mistake. 

> I couldn't find a single source in the entire Internet (!) about how much tech the Korean 'boost when scientific building built' gives, making this currently inactionable
> If you find one, reopen this :)

I found one! I hope it's not too vague https://forums.civfanatics.com/threads/how-does-koreas-science-boost-work.493855/

**Comment by yairm210** [comment]
Um, no - I saw that to, it only says which buildings it applies to, and not how much science each one of those boosts actually gives...

**Comment by Breace112** [comment]
"And also in Vanilla, it was equalivent to an RA; which at the time was based on median tech values. And like RAs; it was worth more if you had PT and/or Rationalism."
This isn't it? RA equal to Research Agreement, right?
