### ISSUE TITLE
create map can't start game, and map buider can't close

### ISSUE THREAD

**Issue by FikaCode** [yairm210/Unciv#3066]
Android  latest version .
q1: I create map for my self，then i can't start game.
![微信图片_20200901093720](https://user-images.githubusercontent.com/42266215/91784965-c1152900-ec36-11ea-851b-b6ffbb228cb5.jpg)
q2: In map buider, if I delete my map, close button is invalid， I can only force exit game and restart。
thanks。

**Comment by yairm210** [comment]
And is there enough space to place all 4 civs in the map...?

**Comment by FikaCode** [comment]
@yairm210 The map is a large map, I try 2 civs start game, but fail.   old version works ok.

**Comment by FikaCode** [comment]
I back to version 3.10.4, It's works OK.

**Comment by HadeanLake** [comment]
UI bug. It works if you select another map and then selects your map back

**Comment by FikaCode** [comment]
@HadeanLake Thanks.
