### ISSUE TITLE
Persistent removal of Produce Science from queue and building inserted every turn - Android

### ISSUE THREAD

**Issue by qbcrunch** [yairm210/Unciv#3067]
This behavior seems to have recently changed.

Late game once completed all non-military buildings have Produce Science set in queue. Each turn Produce science is remove from queue entirely and remaining military building is added. This requires manually adding and moving Produce Science to the top of queue. This doesn't change whether or not there are remaining items in queue after science.  I've also tried stacking Produce Science at top and Produce Gold next. Science gets removed and the available military building gets inserted and placed at the top of the list.

Android 3.10.3

**Comment by HadeanLake** [comment]
Fixed in 3.10.4

**Comment by yairm210** [comment]
Already fixed 💯
