### ISSUE TITLE
Suggestion about adding a new country

### ISSUE THREAD

**Issue by Fenler** [yairm210/Unciv#3068]
Dear developers,
I am writin on behalf of myself and all armenians to draw your attention to the fact, that Armenia is a very old country (many times older than Russia  America, France, and also older than Rome!!). That's why i want to see Armenia in YOUR game! You added Turkey but not Armenia! WHYY! Please add Armenia! If you need help with giving names to Armenian cities, soldiers and other things i can help you! Just check in the google! ARMENIA HAVE TO BE IN YOUR GAME! Hope you luck :))

**Comment by HeavyTank-1** [comment]
No countries that aren't on vanilla Civ5 will be oficially added. You could mod the game, or ask someone to mod it, go to Discord, a lot of modders are there.

**Comment by HadeanLake** [comment]
Armenia is present in [Ancient-Civilizations](https://discord.com/channels/586194543280390151/718432409816662118/748874151682637906) mod by Ravignir

**Comment by yairm210** [comment]
We're not adding non Civ V nations :)
