### ISSUE TITLE
Start New Game crashes on Desktop Win64

### ISSUE THREAD

**Issue by samyelias** [yairm210/Unciv#3075]
3.10.6 introduced a new bug for me: Start New Game crashes the game (quits to Desktop).

I can load an old saved game but not start a new one. This happens both in the starting menu and in-game (after loading an old game). Old releases still work properly.

I'm running Windows 10.

**Comment by Haeherfeder** [comment]
Same for me with Ubuntu, the jar version, fresh install, German language

I can paste the error tomorrow

**Comment by SpacedOutChicken** [comment]
I've got the same issue on Windows 10. I tried the 32-bit version and had the same problem: "Start New Game" just kills the whole thing. Old releases still rolling just fine.

**Comment by HadeanLake** [comment]
make maps folder and put some junk in it

**Comment by samyelias** [comment]
> make maps folder and put some junk in it

Doing these two things worked.
