### ISSUE TITLE
Change auto-movement to occur at end of turn, rather than beginning

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3076]
Currently in Unciv, units engaged in multi-turn movements will move at the beginning of the turn, meaning I cannot change the unit's orders in time to us its movement for that turn - I have to wait until the turn _after_ cancelling the move order. In all Civilization games I can recall (not just Civ V), the unit does not actually move until the end of the turn, offering the player one last chance to change his mind before hitting "Next Turn."

I would love to see Unciv match this behavior. It would also make other units a bit more consistent with the worker, which can have its improvement order canceled and move to a new tile in the same turn.

**Comment by ravignir** [comment]
I also suggested this some time ago.
