### ISSUE TITLE
Game auto-update

### ISSUE THREAD

**Issue by chriscr2** [yairm210/Unciv#3082]
One question is that I play on my laptop and the game seems not to be updated, so I wanted to know if there is a way to update it without having to download the file every time a new version comes out.

Thanks

**Comment by HeavyTank-1** [comment]
Currently, no, you will need to do it manually. Maybe Yarm has a secret plan to deal with this.

**Comment by yairm210** [comment]
Unciv is now available at itch.io, so if you download it through the Itch app it should always stay up-to-date! :)
https://yairm210.itch.io/unciv
