### ISSUE TITLE
Current production/tech research progress as (Y gathered/X required) and other hammer related features

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#3083]
I think it is pretty important to keep track of your production/science progress to perfect your game, so no turns are wasted - it is a part of Civ5.

Also what about losing a Wonder race; in Civ5 you get 1 gold for each hammer lost.

Another request; can you make Production carry over to next thing on the list, an example;
My city yields 6 production/turn, and is currently producing Warrior (39/40 production). It will produce a warrior at the start of next turn, but the remaining 6-1= 5 production is going to be wasted. It should be carried over to next thing you are going to produce - and only next thing - as according to what I've noticed in Civ5; 6 production/turn and three (0/1 production) units does not
grant you 6*3-3= 15 production towards 4th thing, but only 6, so the carried over production does not stack

And the last thing i find missing from Civ5 - Imagine you've just discovered Industrialization and you were producing Crossbowman (which got obsolete) in one of your cities. Instead of removing it from queue it should be automatically changed to Gatling Gun instead with current production progress (if crossbowman was 100/120, the gatling gun should be 100/225).

![production_leftover_civ5](https://user-images.githubusercontent.com/30041793/92018595-a2598400-ed55-11ea-8823-4f7785c96706.png)

**Comment by lishaoxia1985** [comment]
I know what you mean, but at first we should find how to do about overflowProduction in the original game. it's very easy.
I find your mod about map, if the license is legal, it should can be merge into the master.

**Comment by yairm210** [comment]
This is finally done :)
The production overflow is the only thing in this issue not dealt with
