### ISSUE TITLE
"Start new game" causes crash on v3.10.6 from FDroid

### ISSUE THREAD

**Issue by sudomain** [yairm210/Unciv#3092]
**Describe the bug**
Starting a new game from the main menu causes the app to crash.
**To Reproduce**
1. Upgrade to 3.10.6 from fdroid
2. tap start new game

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
no crash

**Screenshots**

**Additional context**
3.10.5-patch1 didn't have this so I downgraded. Android 7 stock rom for an LG Stylo 3

**Comment by HadeanLake** [comment]
3.10.6-patch1 with this fixed is on fdroid already

**Comment by sudomain** [comment]
So it is. Thanks
