### ISSUE TITLE
Move button does not disappear after unit moves.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#310]
I noticed you have a related commit.

**Comment by yairm210** [comment]
Good catch, I'll fix that =)
Indeed a side-effect of moving the "move button" ui change to the main thread

**Comment by yairm210** [comment]
Fixed, thanks!

**Comment by zivvel** [comment]
Fixed in which release?  I'm seeing ghost move buttons starting today (update with the black orbiting dots).

![screenshot_2018-12-07-19-41-09](https://user-images.githubusercontent.com/242258/49680347-1d92e680-fa59-11e8-9873-0a6ac10e45c2.png)

**Comment by zivvel** [comment]
Can confirm it's fixed in yesterday's update. Thanks!
