### ISSUE TITLE
Units "finished exploring" when they're not

### ISSUE THREAD

**Issue by samyelias** [yairm210/Unciv#3100]
This happens to me constantly: a given unit (land or naval) will often report "finished exploring" when there's obviously more to explore. This happens in sometimes very obviously wrong situations, like a Frigate being in the middle of the ocean, with unexplored ocean 10 hexes away in a straight line.

**Comment by samyelias** [comment]
An example (caravel unit)
[finishedexploring.zip](https://github.com/yairm210/Unciv/files/5178320/finishedexploring.zip)

**Comment by yairm210** [comment]
This is a design choice we had to make.
If the unit 'searches ahead' to much, this takes a lot of tone, especially if there are a lot is automated units, so we had to limit the exploration range.
