### ISSUE TITLE
Trillion dollar idea

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3108]
Making Game.atlas Automatic Uses Folder Instead of Game.PNG
Making it Faster And Efficient
Making A Building that protects its Nation Border
Heavy And light Type units
ICBM MIRV Hypersonic Missiles And Thermonuclear Weapons
New Unit Nuclear Bomber (Can be Shot down by anti Air defence To Protect a Area from nuking) 
Anti Ballistic Missile Making ICBM And MIRV Useless (how ever Hypersonic Missile and Bomber Cant) Required Satellite to Detect Incoming Nuke Missile
Radar Increase See range And Detect Enemys in a Distance

**Comment by yairm210** [comment]
We're only having Civ V features.
About the png - using a unified image file is what leads to the game being faster :)

**Comment by khurtron6** [comment]
Bruh
