### ISSUE TITLE
Big Brain Ideas

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3110]
When Pick Tech Can Still Use Old Units Even In future Era
Support Giving Another Nation Allied Military Equipment
Hypersonic Missile / Bomber (Making The Nuclear Warhead Untouchable / 0% of Anti Missile to Intercept it)
Thermonuclear Bombs (Destroy Every Thing Even a City)

**Comment by yairm210** [comment]
Not Civ V features = nope
