### ISSUE TITLE
AI improvement

### ISSUE THREAD

**Issue by rigao1981** [yairm210/Unciv#3115]
I just won a Deity game and I found some AI behavior that needs improvement:

- Not using great persons: While I was conquering the world, I found many great persons lying around. It included great scientists, great artist, great engineers... AI should use this resources, especially Great scientist that can discover a new technology if they have nothing better to do.

- Not upgrading units: To finish off the game, while I was researching "future tech", I invaded Persia. Among the troops I fought were information era units, but also warriors and archers! The AI usually have a surplus in gold at high levels, so it should use it and upgrade!

- AI not expanding: Pretty late in the game after defeating two civilizations, I found islands that were yet to be settled. The places were good enough for me to found 4 or 5 good cities. AI should expand even if it plans to win a cultural game. In that case, seeing the new land, it should change the objective to win the space race.

**Comment by yairm210** [comment]
1. Agree, I'll try to figure this out
2. Fixed, thanks!
3. Disagree. Expanding is not always the correct move, esp. in late-game, when it will take a while for the new cities to get up-to-scratch.
