### ISSUE TITLE
Very Huge Brain Idea

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3117]
Modding Ez Modding
By Not using Game Atlas Or Game.png
To Add units Or Building Tileset Nations And Etc Icons By Adding
 "Image":[".png"], and "Image Tileset":[".png"], Automatic Find the Units or Etc Image Instead of makings a Game altas And Game.png Making Modding Easyer And Faster And Not Questions  Asking Making other User Confuse

**Comment by yairm210** [comment]
No. This causes performance problems.
