### ISSUE TITLE
Thermonuclear Bomb and ICBM And MIRV And Hypersonic Missile

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3118]
Thermonuclear Bomb 12× power full than A Nuclear bomb
Destroying the City with one Shot depends of the power Creates A Huge Hole that impossible to repair
ICBM When Tech is Build ICBM increase the range of the nuclear bomb without causing Lag
MIRV Type of missile that Required 5 or 10 Bomb that Randomly  Targets A range on the Targeted Area by 10 tiles
Hypersonic Missiles Missiles that Cant be Shot down by An ABM System rendering ABMs Useless But building  this unit is 80× expensive
ABM Land / Ships Units that Disabled ICBM MIRV And missiles Using Nukes with this is useless unless using a Hypersonic Weapons

**Comment by yairm210** [comment]
Not in civ V.
