### ISSUE TITLE
Quadrillion Dollar Idea

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3131]
Modern Era
New ICBM Tech On Rocketry And capable to mount on Destroyers and Ballistics trucks by taping
And New MIRV Tech on Rocketry Required ICBM And Bombs
Can hit a target How many Bombs are added
Ballistics Missile Carrier Truck unit Can carries Bomb When Destroyed Its Detonates
Information Era
Thermonuclear Bombs Tech on Nuclear fission 
Can destroy a capital Contaminate Lakes rivers Ocean And many other
Highly expensive creating Radiation poisoning on any units in the contamination 60 damage per Turn
Future Era
Hypersonic Missiles Upgraded Ballistics type Impossible to intercept by ABM system Can carrie Thermonuclear and nuclear bombs and Anti Matter bomb
ABM unit that intercept ICBM Ballistic MIRV Missiles 100%
Antimatter Bombs Very very Long process to make Doesn't creates Radiation
But Very Powerful
Fighter jets "yamir knows"
Stealth Bomber "yamir knows"
Ballistics Submarine Subs that Contains Long Sea to Surfaces and Sea to air Missiles that can Hit a Target in a range very durable
Terminator Tanks unmanned tank that has A Tank turret AA And Missiles and anti tank
Space base A unit That Required use Ballistics missile to destroy it
Shoots lasers and Can Intercept Rockets

**Comment by yairm210** [comment]
Not in civ V.
