### ISSUE TITLE
Feature request: Improve worker actions

### ISSUE THREAD

**Issue by SamuelPlentz** [yairm210/Unciv#3138]
Currently I use workers like this:
- Round 1: construct improvement > remove forest/jungle (3 turns)
- Round 4: construct improvement > farm (3 turns)
- Round 7: construct improvement > road/railroad (3 turns)

I would like to only give one instruction:
- Round 1: construct improvement > remove forest, build farm, build railroad (9 turns)

Perhaps with a dialog with check marks like this:
```
[X] remove forest
build [X] farm [ ] mine [ ] trading post
build [ ] road [X] railroad

remove forest, build farm, build railroad (9 turns)
```

**Comment by yairm210** [comment]
Will complicate the current system too much for too little gain - denied :)

**Comment by ravignir** [comment]
Ok, closed, but what about such situation;
Imagine Forest+Silk tile, i think worker should have "build plantation" enabled and it should display "this will remove forest from that tile" and automaticaly choose "remove forest" first then queue build plantation. Anyway, that's how it works in civ5 and I find it handy i don't have to assign worker twice.

Basically, always display all possible improvements of certain tile to choose from, but add "this will remove forest/jungle" to description if needed.

**Comment by SamuelPlentz** [comment]
I like your idea, ravignir. So in the above situation I would only need 2 actions:
- Round 1: construct improvement > farm (removes forest - 6 turns)
- Round 7: construct improvement > road/railroad (3 turns)

I had another idea: (don't know if you would like a separate topic for it)
The only reason I don't use just that `automate` button is, that workers keep improving fields near to enemy cities. So I keep loosing automated workers.

What about adding an `automate this city` button.
It can only be chosen, when the worker clearly belongs to exactly one city. (no other city has the same distance and it is in the 3 field radius of this city) When choosing a field to improve, the worker only considers fields in a 3 field radius of his city. If the city is destroyed or conquered or if there is no field to improve left, the worker ends its automation.

**Comment by SamuelPlentz** [comment]
A different approach to `automate this city` would be to tag cities, that should be automated and those that should not be automated. So I could use just `automate` but exclude cities that are near to the enemy / to barbarian villages.

**Comment by anton-koerbchen** [comment]
> Imagine Forest+Silk tile, i think worker should have "build plantation" enabled and it should display "this will remove forest from that tile" and automaticaly choose "remove forest" first then queue build plantation.

If "remove forest" is not available (not researched yet), this option is silently not shown. I think it should show all options, with unavailable being grayed out with explanation. I was thinking it's a bug that I cannot build plantation on a silk tile, despite plantations being researched.
