### ISSUE TITLE
Huge Brain Idea

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3140]
Modern Era
Nuclear Carrier land / water :
Nuclear Sub can carrier Nukes under sea Detonates when destroyed
Battle Cruiser Capable carrier nukes Detonates when destroyed
Nuclear Carrier Trucks Carries Nuke on land Detonates when destroyed
ABM intercepts Nukes
Future Era
Stealth Bombers
Fighter Jets
Hypersonic Missile Cant be Intercept Tech (Unit Type cant be intercept)
Smart tank (i have no Name to call it) tank with Missile interception and Attack detection (makes enemy visible even out side the line of sight)
Super carrier can carrier 8 aircraft and Drones
Drones Updgraded Scout +4 visibility can attack
SAM Anti Air Missile +4 stronger than AA

**Comment by yairm210** [comment]
Stop spamming these.
