### ISSUE TITLE
External localization platform for translations

### ISSUE THREAD

**Issue by natrius** [yairm210/Unciv#3148]
There was already an issue (https://github.com/yairm210/Unciv/issues/2343) but i was not sure if should just write there so i opened a new issue. 

Since i looked over all of the strings, i just thought an external tool would be much easier to translate stuff. There are various examples like Weblate - https://weblate.org/de/hosting/ , Zanata - http://zanata.org/ or Pootle - https://pootle.translatehouse.org/index.html 

These service are open source and are free, if you are self-hosting them. I have seen Weblate in Action there https://github.com/bilde2910/Hauk where some nice graphics are created automatically if i understand it correctly. And as far as i know, new string will just show up in weblate as "To do" - but i don't know if you just have to set up a master (i guess english?) and it autogenerates everything else from there.

**Comment by Prosta4okua** [comment]
You forgot to mention https://crowdin.com/. Unlike your submitted sites, this one does not require hosting. The site is also free for open source projects.

**Comment by yairm210** [comment]
I tried doing this, and it was a lot more work.
Currently, translations undergo a number of tests for verification. This allows some language changes to be accepted and others not, and it's all in the same platform.
Migrating part of this to another platform means dealing with back-propagation of faulty translations, which is a huge hassle.
Not going to happen :)

**Comment by comradekingu** [comment]
@Prosta4okua It actually isn't, only for non-commercial libre software. And sublicensing strings into a closed source translation memory along with running tracking and spying isn't "gratis", that is a for profit motive. The most polar opposite is Weblate nowadays.
