### ISSUE TITLE
Visual artifacts in tile rendering

### ISSUE THREAD

**Issue by Artemis256** [yairm210/Unciv#3165]
Firstly, the rendering of individual tiles appears to distort them such that they are slightly too big, this causes tiles whose edges otherwise perfectly align to be overlapped by tiles below/to the side of them:

![Capture](https://user-images.githubusercontent.com/58205725/93727014-86caf600-fbfc-11ea-8758-d4094d2ef218.PNG)

Zoomed in:

![Capture2](https://user-images.githubusercontent.com/58205725/93727022-934f4e80-fbfc-11ea-989a-aa950037b0a5.PNG)

Note that the top-left and bottom-left are not vertically aligned. Additionally there are supposed to be two pixels on the extreme left/extreme right edges of the hexagon, however the distortion causes an overlap to the extent that it appears to be only half a pixel on the edges. This is also present in the FantasyHex tileset, it's just harder to notice because of the low-resolution of FH. It would be a much larger issue for higher-resolution tilesets (and as I mention below, higher-resolution devices); in fact Ravignir's 5Hex tileset does experience this issue (it might be hard to notice but zoom in and you'll see it).

Pixel-wise, the mono-color tiles I used to test this were perfectly aligned, as seen when I try to render the same tiles in Tiled:

![Capture5](https://user-images.githubusercontent.com/58205725/93727221-8717c100-fbfd-11ea-9ce0-f03c2f1eadf0.PNG)

I initially thought this might be fixable by reducing the size of the rendered tile, however, there is another issue. When the map is rendered on a device with sufficiently high resolution and/or rendered with the highest resolution in the Settings (1500x1000), then when the map is zoomed out, there is a black border (gap?) around the tiles (which, as previously mentioned, should perfectly align):

![Capture3](https://user-images.githubusercontent.com/58205725/93727340-14f3ac00-fbfe-11ea-9e6b-d8eba3ed8576.PNG)

Zoomed in:

![Capture4](https://user-images.githubusercontent.com/58205725/93727358-2f2d8a00-fbfe-11ea-9065-e3c5afa424ee.PNG)

These gaps become larger if the size of the rendered tiles are decreased (e.g. by reducing imageScale in TileGroup.kt)

So the tiles appear distorted to be too large when zoomed-in, but distorted to be too small when zoomed out.

(all of this was done on a vanilla copy of Unciv 3.10.10, with some of the images in FantasyHex replaced)

**Comment by yairm210** [comment]
Closing as "wontfix", no one else seems to consider this to be a problem.
