### ISSUE TITLE
Right mouse click to attack enemy units

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#3167]
In the Desktop version, we all can move an unit anywhere with the right mouse button. But I think you've forgotten that the RMB is also used to attack enemy units.

**Comment by lishaoxia1985** [comment]
I don't think it's good because you should notice some units which can not attack, especially aircraft carrier.

**Comment by yairm210** [comment]
Oh right I solved this a while back but forgot to close the issue :)
