### ISSUE TITLE
Impossible to trade a technology

### ISSUE THREAD

**Issue by stephvq** [yairm210/Unciv#3191]
Hi

Sorry for the translation, I'm french... few days ago, I have updated the version of Unciv on F-droid. Actually, I have tried the 3.10.10 and the 3.10.11 versions. 
Since I got those versions, the technologies don't appear in the diplomacy box : neither in my articles, nor in the other nation's articles.

Can you say if it is a new rule, or a bug ?

Thank you, and thank you for the game !!

Stéphane

**Comment by lishaoxia1985** [comment]
New rule,  it's not a bug, because this rule has some problem, for example you can sell tech and get a lot of money, 
this is not fair. now you can sign a research agreement.

**Comment by yairm210** [comment]
This is a design choice, to better fit Civ V :)

**Comment by stephvq** [comment]
Thank you for your answer, I'll play like that now !
