### ISSUE TITLE
bug button close can't closed after complete policy 

### ISSUE THREAD

**Issue by AyoPlayGames** [yairm210/Unciv#3192]
after pick policy and complete close button can't closed

![IMG_20200928_082019](https://user-images.githubusercontent.com/69257137/94381807-bc279480-0164-11eb-95d2-70c7d6d77775.jpg)
image before complete policy close button still work
![IMG_20200928_082112](https://user-images.githubusercontent.com/69257137/94381960-3ce69080-0165-11eb-823c-1dfa6458f088.jpg)

image after complete policy close button can't closed

**Comment by HadeanLake** [comment]
Last policy in piety gives free policy (weird, but it does so in civ 5). You have to spent "free policy" before leaving. You cannot click next turn in civ 5 if you have free policy

**Comment by yairm210** [comment]
Not a bug, as HadeanLake said.
