### ISSUE TITLE
Add fortifications

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#320]
In previous Civs, settlers have always been able to construct fortifications on tiles right? If memory serves right, it should come with Stoneworks or Architecture tech. 

Civ 5 wiki says it should come with Engineering http://civilization.wikia.com/wiki/Fort_(Civ5)

**Comment by yairm210** [comment]
Workers, not settlers, but yes

**Comment by flecheapolinienne** [comment]
Yes alright I know its a bit of work but I'm excited to be able to use forts again eventually!!

**Comment by yairm210** [comment]
The problem with these kinds of things is it's very hard to make an AI which will use them correctly so they end up being tools only at the player's disposal =\

**Comment by flecheapolinienne** [comment]
Yeah I'd guess so. AI really is the secret sauce of these games eh. Although I must say yours is not so bad considering I had to fend off a large scale invasion of my island by the chinese yesterday ;)

**Comment by yairm210** [comment]
Moved to #663
