### ISSUE TITLE
City view lets us see units supposed to be hidden by fog of war

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#321]
![image](https://user-images.githubusercontent.com/45007481/49698708-5506ad80-fb95-11e8-9680-22c2ea1c0050.png)

**Comment by yairm210** [comment]
Fixed, will enter 2.10.14
Thanks, you've really been busy =)

**Comment by yairm210** [comment]
Oh and I forgot to tell you!!!

In the jsons folder, copy the "Tutorials_English" and create a "Tutorials_French" to translate the tutorials!

This is important because it's one of the first things that a user will encounter in-game, and it's supposed to explain the basics
