### ISSUE TITLE
On Chrome OS, game will fail to launch a second time

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#322]
If closed, the game will not load again until a full reboot. Game window stays blank (dark blue).

P.S. I know Chrome OS might be a whole another shtick for ya, but on this system Unciv makes total sense as a way to scratch many Civ players' itch. There is currently a lot of buzz on r/chromeos regarding android apps that are optimized for the system VS those that aren't and I'd make sure to publicize your app whenever you have the time to tackle such bugs!

**Comment by yairm210** [comment]
I honestly don't know why this would happen, and I can't exactly test it, but I added something that might solve it (will enter 2.10.15), so when I release that I'll ask you to test it

**Comment by yairm210** [comment]
You should be able to download 2.10.15 by now, please tell me if this fixed the problem

**Comment by flecheapolinienne** [comment]
Holy shit awesome! You're the best, will do

**Comment by yairm210** [comment]
Checked this?

**Comment by yairm210** [comment]
Awesome :)

**Comment by flecheapolinienne** [comment]
Sorry to re-open this, but a new bug seems to have arised linked with the android container in chrome os... The game lags regularly now, something it never did before. By lag I mean the screen will freeze for up to a minute but will have registered touch for the whole time.
