### ISSUE TITLE
How looks landscape in game(cells texture)

### ISSUE THREAD

**Issue by MichaelGrib** [yairm210/Unciv#3226]
Hello. I like this game. You have a powerful game engine. But it isn't not important, when inferface isn't intuitively understandable. When I'm going make change between cells texture, that I can't do it. Because pixel variable is dirty and the other(svg) isn't understandable. I like design by Civilization 5, because it's simple and comfortable. Exactly I mean strategic design: http://downloads.2kgames.com/civ5/site13/images/features/strategicview/Strategic_Early_large.jpg
I think also, that best way to make excellent cells texture is using svg format. Because it's scalable format and then user can see sharpness cells with absolutely best sharpness and clear look for his display. Engine can being very strong, but design today isn't strong. For people is very important visual interface.

**Comment by yairm210** [comment]
That's why we have 2 tilesets, for 2 different kinds of players (most of which disagree with you by the way)
To change:
Menu > Options > Tileset > Default
