### ISSUE TITLE
"hideUntilBuilding": [building] 

### ISSUE THREAD

**Issue by Subcher** [yairm210/Unciv#3229]
Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!

Hello, i'm Subcher. I'm making a mod about Wwii and i would need a condition for my units. I would like them to be only show in the construction queue when a building is build. Because i have more than a 100 of unit so it will be suoer annoying if there a hundred of red line "need [building]". It would be smoother if there a only show when you can build them. 
And also i would like this for the tech tree. I explain : i have more than a 100 of unit in 15 different tech so there is something like 7 units by tech. My units are unique to them nationalities. Like the M4 Sherman can only be build in an American city. So if you don't have an American city, the American tanks doesn't show up, but when you capture an American city, American units shows up on the tech tree. This is for more comprehension. 

It would be nice to introduce "hideUntilBuilding" : [building] for buildings, units. Example : 
"name" : M4, 
"hideUntilBuilding": ["American Factory"], 
So if i am Germany, i can't build that tank because i don't have the building "American Factory" so the tank doesn't appear in the tech tree. When i will capture an American city, i will have the "American Factory" in the anexed city so i will be able to build the tank ONLY in this city but all the American unit will show up in the tech tree. 

 
I don't know. 

Contact me on discord if you have any questions. 

I hope someone will do it because i really need this feature. If i don't have that, my suoer ideas will be super annoying.

**Comment by yairm210** [comment]
Done, you can add the unique "Not displayed as an available construction unless [] is built" to a building/unit for this

**Comment by Subcher** [comment]
Ok awesome !!!!!!!!!!!!!! And is it visible in the tech tree ?

**Comment by yairm210** [comment]
Yes
I think it would be kind of strange to have a different displayed tech tree depending on the buildings you own
What say you?

**Comment by Subcher** [comment]
i mean, the building/unit will be always visible in the tech tree or only visible if you own a required building ?
