### ISSUE TITLE
Some moar features for modding

### ISSUE THREAD

**Issue by GoldenBronze** [yairm210/Unciv#3236]
_Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!_

I hope so.

_Is your feature request related to a problem? Please describe._

Yeah, so... my problem is that generifying certain uniques and adding some new ones would help modders like me a lot.

The three features in question are:

1. Making roads and railroads modifyable - currently, these seem hardcoded. Putting their parameters in TileResources.json and allowing Unciv to handle modded roads and railroads would be extremely beneficial for, say, a mod with several kinds of roads.

2. Allowing terrain-tied resources - currently, resources stay the same if a terrain feature (most commonly Forest and Jungle) is removed. I'd like it if it were possible to set a (in TileResources.json) a resource such that it disappears if the terrain feature it occurs on is removed. Admittedly, this is not present in Civ 5 itself, but it would be extremely helpful to modders like me in putting resources like Cedarwood: I mean, you can't get cedarwood from a tile you've deforested, after all!

3. Selective improvement construction: currently, the Roman Legion has the "Can construct roads" unique. It would be great if this unique could be generalised so that it works with any improvement: not only would it make it easy to add the Legion's other ability of constructing forts, it would also be extremely fruitful for modders.

_Describe the solution you'd like_

1. When described in the json, roads and railroads could have parameters like "Double movement rate" and "Triple movement rate upon researching [ ]". There's lots of opportunity here.

2. A unique for this, maybe "Is removed by [Remove Forest]".

3. "Can construct [Road], [Fort]"

**Comment by yairm210** [comment]
Please move to #3242
