### ISSUE TITLE
Enemy city was razed immediately upon conquest by a City-State, normal behavior?

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#3258]
**Describe the bug**
This time, I've done a more thorough research on the Civ 5 wiki ;) and couldn't find an answer. Just before I could move a melee troop into a weakened enemy city, an allied City-State conquered it itself and it was immediately razed. Is it how it happens in official Civ also?

**To Reproduce**
Ally with a city-state
Reduce an enemy city's health to low enough
Watch as a City-State's troop enter and immediatly raze the conquered city.

**Expected behavior**
I get that the City-State can't own another city, but it seems to me it introduces a huge imbalance that it can raze it instantly.

**Comment by yairm210** [comment]
I see no problem with it. City States don't behave like regular civs in many ways. Working as intended.

**Comment by ravignir** [comment]
Actually, it works differently in civ5; In civ5 City states can conquer cities like any other civ.
![Ji19s9K](https://user-images.githubusercontent.com/30041793/95903710-d2556780-0d96-11eb-8360-466b975557d6.jpg)
![ca8cf7d](https://user-images.githubusercontent.com/30041793/95903749-dda89300-0d96-11eb-8d08-2a92e5162955.png).

**Comment by HadeanLake** [comment]
![city state burns other city state](https://user-images.githubusercontent.com/69697985/95908443-c2914f80-0da5-11eb-9fa3-efb74ab836bd.jpg)
City-states can burn captured cities

**Comment by ravignir** [comment]
They can raze, puppet or annex, like any other player
![download](https://user-images.githubusercontent.com/30041793/95910437-5cee9480-0da0-11eb-919d-ca73a53617cb.jpeg)

**Comment by 71walceli** [comment]
It also happened to me when I was at war against a normal civ, but it's so long ago I don't have the autosaves anymore... They instantly razed whatever city they took from me.

I'm unable to reproduce it...

**Comment by yairm210** [comment]
Not a bug.
