### ISSUE TITLE
Continue putting keyboard shortcuts in menus

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#3265]
I think a massive life improvement at low cost in terms of work for computer players would be to simply link the "Esc" key with every "Close" button in menus, and also assign shortcuts to the worker "Construct improvement" menu's options :)

Thanks guys!

**Comment by yairm210** [comment]
Isn't esc already linked to them all? I checked tech, overview, policy, diplomacy, victory
I noticed it's missing from the improvement picker screen, but I think that's it

**Comment by flecheapolinienne** [comment]
oh, well it's not working on my chromebook... it's a chrome-related bug again then I guess?

**Comment by flecheapolinienne** [comment]
Hey @yairm210 I just tried the latest version with arrowkeys control and they work so I thought... maybe you could add the X key as an alternative to the Esc key that still won't be recognized and we would have an easy solution to my chrome os container problem!
