### ISSUE TITLE
Some new modding uniques ideas

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#3270]
Here are some ideas for uniques.

"Can not be sold" - for buildings.

"Unlocks at [Era name]" - for buildings and units and improvements (already implemented for Policies).

"Food required for population growth +/- [x]%" - as nation and policy unique (also called civ-wide).

**Comment by EdinCitaku** [comment]
hey there is a thread to collect ideas for modding uniques, could u move ur request there?
https://github.com/yairm210/Unciv/issues/3242

**Comment by yairm210** [comment]
Yep, please move to the orrect issue
