### ISSUE TITLE
Broken tiles

### ISSUE THREAD

**Issue by x7rgaming** [yairm210/UnCiv#328]
If a worker builds for example a mine on a gold tile while the land is neutral and then buys the land, then the land is unusable, you cant build on it or assign people to it. It becomes a unsable blank tile.

**Comment by yairm210** [comment]
Are you sure the land isn't just too far away from the city center (4 tiles away)?

**Comment by x7rgaming** [comment]
Thanks this is the issue, its pretty confusing how you can buy land for a city yet cant do anything with it.

**Comment by yairm210** [comment]
There will be a tutorial to explain this soon :)
