### ISSUE TITLE
Feature request: Portrait mode

### ISSUE THREAD

**Issue by refola** [yairm210/Unciv#3284]
**Is your feature request related to a problem? Please describe.**
I'm mildly inconvenienced when switching between Unciv and other apps on my phone due to Unciv forcing landscape mode and the transition back-and-forth with portrait mode taking additional time.

**Describe the solution you'd like**
Working with portrait mode would be nice!

**Describe alternatives you've considered**
I can put up with slower app switching, switch to landscape mode for other apps (at least ones that don't force portrait mode...), play Unciv on my "real computer" instead, and possibly get a faster phone.

**Additional context**
Almost 2 years ago there was a glitch where Unciv was in portrait mode, and it works in the desktop version, so I know it's possible. Also, @Am-per-Sand [seems to have previously expressed a wish for portrait mode](https://github.com/yairm210/Unciv/issues/164#issuecomment-402710403).

Here's a screenshot of the glitch-that-I-want-to-become-a-feature.

![Screenshot_20181224-122027_UnCiv](https://user-images.githubusercontent.com/8690113/96943792-fc411500-148d-11eb-98e2-fdab390b2f10.png)

**Comment by logicminimal** [comment]
please implement this

**Comment by jahodovykolac** [comment]
Already implemented in 3.14.11 or 3.14.12 (I can't remember now)

**Comment by yairm210** [comment]
Done :)
