### ISSUE TITLE
User ID from Win (3.11.7) to Android (3.11.6)

### ISSUE THREAD

**Issue by Worf3915** [yairm210/Unciv#3293]
**Describe the bug**
It seems not possible to take the user ID from Windows 10 game to Android game and backwards. It ends with error message: invalid ID!.

**To Reproduce**
#1 Starting game in Win10. Language: german. Version: 3.11.7. 
#2 Go to MULTIPLAYER, 
#3 use COPY USER ID, 
#4 transfer them blank to Android device.
#5 Starting game on Android. Language: german. Version 3.11.6. 
#6 Go to OPTIONS, 
#7 use TAKE USER ID FROM CLIPBOARD, 
#8 result: INVALID ID! (marked in red). 

**Expected behavior**
that the user ID from Win10 will be taken also from Android version w/o error message

**Screenshots**
not available

**Additional context**
none

**Comment by yairm210** [comment]
Fixed :)
