### ISSUE TITLE
Blacklist construction items

### ISSUE THREAD

**Issue by ghost** [yairm210/Unciv#3296]
Currently I have a list of items on the suggested construction list that I don't want to build, such as a barracks and stable.
It would help if there was an option to 'blacklist' them, greying them out so that I don't accidentally build them.

**Comment by ArchDuque-Pancake** [comment]
Also for puppeted cities

**Comment by logicminimal** [comment]
this was opened 11 monghs ago but dtill relevant

**Comment by yairm210** [comment]
ALL issues that I am aware of are still relevant. If they weren't they would be closed. There's no need to ping every single one.

**Comment by will-ca** [comment]
Closed by #10061, I guess.
