### ISSUE TITLE
Include war as a trade option

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3303]
You should be able to leverage your armed forces to negotiate, threatening war unless they give you your demands.

**Comment by flecheapolinienne** [comment]
Is this an original Civ 5 issue? Because the roadmap for Unciv doesn't include putting in new rules than the ones present in the original game, you need to check on the Civ 5 wiki / in Vanilla Civilization 5 for your rule before asking for it as a feature.

**Comment by CIZUK** [comment]
Um not sure, just suggesting ideas.

**Comment by flecheapolinienne** [comment]
Like I wrote earlier, go check your feature up on the Civ 5 wiki [here](https://civilization.fandom.com/wiki/Civilization_V)! Or open a game of Civ 5 on your PC if you have access to it and check the gameplay for features! I'm pretty sure that "War as a trade option" should be in the original Civ 5 rule, but then again I am not sure; if it's not there, there will be a good reason, namely for balance purposes.

Checking that and reflecting upon why is part of the work you can put into this project and have it grow and get better with time while others code, make graphics, discuss, etc.

**Comment by yairm210** [comment]
If it is in Original Civ, please add it in #663
If not, it won't be implemented ;)
