### ISSUE TITLE
Strengthen relationship with other Civs with trades

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3306]
Currently, if I help out a civ, there's no benefit to me. If any surplus value of the trade (perceived value minus actual trade) was translated into relationship points it would help. A random value generator could also add a bit of unpredictability.

**Comment by the-Arioch** [comment]
Then building a road (connecting cities) should help too, as roads boost trade (in real world) and as city-states acknowledge it and have a dedicated quest.

**Comment by logicminimal** [comment]
is this already in #663 ?

**Comment by yairm210** [comment]
Closing as "considered, denied".
