### ISSUE TITLE
BUG : Can't launch the game

### ISSUE THREAD

**Issue by Bribrooo** [yairm210/Unciv#3310]
**Describe the bug**
Can't launch the game.

**To Reproduce**
1. Go to 'https://yairm210.itch.io/unciv'
2. Click on 'DOWNLOAD : unciv-windows32.zip'
3. Scroll down to the files and launch Unciv.exe (if doesn't do anything launch Unciv.jar)
4. See that you can't launch the game.

**Expected behavior**
When I try to launch the game, it's pop-up and close automatically.

**Comment by yairm210** [comment]
I assume you're using Windows, but are you sure you're on 32 bit?

**Comment by yairm210** [comment]
If you don't give me more information, there's very little I can do with this

**Comment by Bribrooo** [comment]
yes i am in 32 bit sorry for not reponding quickly i was busy

Le sam. 31 oct. 2020 à 17:22, Yair Morgenstern <notifications@github.com> a
écrit :
