### ISSUE TITLE
Civilization 6 mod some building "water park" cannot be built under the right condition

### ISSUE THREAD

**Issue by Q-San** [yairm210/Unciv#3311]
**Describe the bug**
I had been playing about 200+ turns and I was about to build an aquarium and something that required "water park" in one of my cities nearby coast. But the build "water park" option didn't appear on my building list.
**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots*
![Screenshot_2020-11-01-12-43-43-81_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/73769747/97796060-28a02280-1c40-11eb-87a2-dd93026fea45.png)

**Additional context**

**Comment by yairm210** [comment]
This is a problem with the mod, not the game, therefore you need to talk to the mod owner
