### ISSUE TITLE
Some mods not wanting to download on mobile

### ISSUE THREAD

**Issue by Imperii345** [yairm210/Unciv#3320]
**Describe the bug**
When a new mode is add sometimes they don't want to download when your on mobile

**To Reproduce**
1. Go to 'UnCiv'
2. Click on 'Mods'
3. Scroll down to 'Empire of Sea or Expanded Warfare or HiveCiv mod'
4. Click on 'on any above'
5. See error

**Comment by TheRexYo** [comment]
HiveCiv is my mod, and I can confirm it doesn't install on desktop either.

**Comment by yairm210** [comment]
I see that the main branch on these repositories is called "main", not "master".
This is the source of the problem, and I'll remove such repositories from being displayed in-game

**Comment by yairm210** [comment]
Done
