### ISSUE TITLE
Negative and positive tile yields not adding up properly

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#3323]
If a tile improvement has negative yields, but is affected by a unique with positive values, the results do not add up properly.

In my [Undead mod](https://github.com/SpacedOutChicken/The-Undead), I created a [tile improvement](https://github.com/SpacedOutChicken/The-Undead/blob/master/jsons/TileImprovements.json) that gives negative values (-2 food, -2 gold, -2 production, -2 happiness), and I gave the civilization a [national unique](https://github.com/SpacedOutChicken/The-Undead/blob/master/jsons/Nations.json) that cancels most of those out (+3 food, +2 gold, +2 production, +2 happiness). The end result was supposed to be a tile improvement that works like an ordinary farm (+1 Food) for the Undead but works like fallout for anyone else, forcing any conquerors to remove the plot in order to make the city livable. However, the negatives and positives aren't adding up properly, resulting in a tile that offers massive yields in everything (+4 food, +2 gold, +2 production, +2 happiness). Somewhere, the arithmetic is going wrong.

![Screenshot (31)](https://user-images.githubusercontent.com/58439827/98454368-ffd8cb00-2120-11eb-883f-4938065461e9.png)
![Screenshot (32)](https://user-images.githubusercontent.com/58439827/98454369-00716180-2121-11eb-92d0-f5970c071250.png)

In the first screenshot, you can see that the arithmetic is still working properly in the worker selection screen. The values there are exactly what I intended. But the second screenshot shows you what you actually get: a massive surplus of everything, like a natural wonder you can build anywhere.

Interestingly, this error only appears in 3.11.9. In 3.11.8, the tile improvement works just as expected.

EDIT: It also appears in 3.11.10.

**Comment by SpacedOutChicken** [comment]
I'm still getting this issue in the latest patch.

**Comment by yairm210** [comment]
???
Where are you downloading the patch from?

**Comment by SpacedOutChicken** [comment]
From Itch. I haven't tested it straight off of GitHub.

**Comment by yairm210** [comment]
Patch1 doesn't contain the solution to the problem, it'll be rolled out with the next version
