### ISSUE TITLE
AI hoarding great people

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#3324]
As of the latest and the previous build the AI has a habit of hoarding their great people. They will stand them in one place for dozens of turns even if you declare war, in which case the player can easily capture all of them. The example game I'm providing is from the latest update and doesn't completely show the problem, but recently I've seen up to 5 great people being unused this way by a single civ. 
![Screenshot_20201107-204157_UnCiv](https://user-images.githubusercontent.com/64375454/98455728-4edf2a00-213a-11eb-8a61-b1eeb96b3b59.jpg)

<Details>
<Summary> example </summary>
H4sIAAAAAAAAAOVdW3PbOLL+K6p9plK8X/Rme+IkO3Gstb2Vc07KDxAFSRxTpJYXJx6X//tpkCDRJEEJkp3sbO1DEooCG41G3/FReQ6jxyiO/iRFlCb57NtzGBUR5RdPF3CvyMqw/vJ5UUZxcQ5/LaNkDWOu0qTc0qTQ5iQmIdWuIrj+HK03xSYtc/hMsgdaaLdFmtANTdZUu17kNHskRZo9aRdpnOY5LbfaOckyEj7k2tm/SrqE6bR/JtEjzXJgAegtMgLDv6bZQ75Jd9qHjCTVDRLH+b0WIh7/UdKSzr59qVZD4sn7XRTea1Eyz9J1RvO8t57OuJnjv7xobNW3BSng2xeN/tiRJIchs+ewjIsyo7CUjC5nhh+8aKu0TJggLqLH2e9wm2gbSuJiMzMdXYuWM8emrktNOjUWzmJq+4tgSkJdn7rUtpaB6xFiBFqUX2fROgImLsguKkg8A/6oFqdhxdvs+cds6mhPs6nxoiVkS2e3NC1jbZfuypiPWKXpkvMV+PgbQ9fyHQ0jEkd5cRY3NGFpt2EE2wZ3YWExyfPZH+SRvItJsn73KSnommbaI4lBlOaL9j4B9ijNDg01QHpiOia/F62I4kqXYBEuWwSQY9d2/Y/LP/HltaMMdN8U1/y21b3sPGnV1z66X13b6JpTdPrXfLxT/+Mhck7v2kBD8DWn5r3ca6AryVn4rzJiu2Jr30F36fJOSMMezmLvY244ey2Re/hwjKHKDOwyzcAykdkOLK61EzDZGLa8NUFu4JUltlYsNUlk+HsMEo2aWba6OZruYXMMVt7Stok5BeMzp7anL6YL6q2mnuOHeqAbnrNcde2uUi+X2915mZNkzO4Mw8BfeW9gd3uNqeGMXZvo2kbXBlL8aryPxuP7NhqP6XhovIPGe+jaQWM8pK+YBwfd9we24Q6NwxlZHeYEr5Sv7mRb2Kf6PU2vQtmk+la729DJ/Ckj22iZq5iAMLk9FiAGzUzdU7YAyzhsAEtKjAUNnakbeMbUdl13Giy9xdQNDZ3qixVxnaBrAC4XeGUAf6dp8kc5agGWh7/yxyxAPZpoVzQLNyQ5aCsqgcdFQcJG+oi9PdYs7JOxr/ZQIME0MR0X0ceBx0M0HfQsponp2H1bcc2hrQwoSzg/MOMr7Ga/sfwEm/At9aBgKeRoOvE8ujQW0+XSgqAQWO7UX5lkuvAXtmOFbmBAStWxiSYP+43Q9ag1eA7+xv3rGANPHkzkUA3kqg10H43B6RZ+lOuahb62+krrG0OltfDDfaLdCX6FUx8vJD6QIoYJJh/KZI9+olGQ9CsrqOMc1s/QsxcECoVpEIC7tg13OSUG0083gNJi4en6yunoZxPdKx2dP6XJ+gmUZFRP3b+m00Z5CUpXkNog9WvzHPGPK8bUl8gbopQE5RNtMtP9cpDKG2YwUGerR6bLizNg0j1aqRsF7lS++x2rUP89iisGzQxXWW9NW6H2NW1bt2xnqtOFDbUv0acLw6NTz1oRw/EtYi0XHb1lEc/kavs7oXk6rrSGO+Zc+2rEicIVC3W1unjtld9+y+7Z7T1xVfu9Om8O2tFBOyaoaPVVxB7We2J6v8eE1yFmIsZeqyS1c3sT5bD8yndOzlOmG6Z6CPZkmgLqYXvGyjNsc2qG/mpq2/BXoOtkapKVp9twc2H0eiAGr2DqHkj5PR2txWxfKfa+VUBtKqtegeULs3fFJR4RoLgb1AT4Px76Bhdbho5DtY5juD7QQtfpaaGY3ho878smvgeadTfwAratYOECPj9+qUy02slltIvTLQmfZs+fkpDMnvmNIgqv0mW0iiBrmz3/LyVZfr2aUxKCKunaZRmvojimS1C8bZTTu/RLWtzSoojpRTXdF3jgnzlrX90W4FVAee5olkVVV2AKBK53NDlPsyWjrr8DByumZTpZ5rNqLm0VkzVodZkUy/Q7KMl7yCLPKU0uM6jCl3mV7qTFhmYXfFVsEVqRkWUlsLTMrlcrNsk3riNhun1XJiCDd3G6jsJ31dB3d+zvaqS2LLNa7Uyj1lTG6oTzqhVPOzo7A1ujzGDZjm1odPQcZMtWBNmDXk/xIY2XbK9eKkOMmQ2g2NSGJXOQbtmtE8KVA87HxHP90qK+xOUUD8Y63PJaL+YOyiXm74ZFl9t6QVyiBS2taYBsARVZjngOlVtuO4cneEBlmt/Srdj1BzUaLt3EFIEYGyATZyQCJEYhMH5V25ZR/dM07/ouAWfiIuNG9HB70+1unBgg4hquO23BJy4CRSKFs35cDfg9D1WLwEEiQMlNgDYHb0k/zDktn/3GpuDeQdw7gnvcVOLuKxC3A6EWuJclbxe7wiJQY1p4avHsdNB2xp1sTKeXaNTsoxxVGABff/t5igSCur7NpSCBLQAZnJCspH+MHhSZSy0tu9UyrAI+UmYDJSRiUSaOd6ip3liSYBj1FsVknGp/Mqx6wkDsXsjsqRpeJG5Gcv0whCsQ0ubsoyHNo2L4VIw3haCtVowWEqPYY1zTIsN2X1BZgo843I5SDc9ADGQiiD66bQoDwK1SC5nkoDlriAWZreYYQgUNMbb2WvxpTAjnEI0ttsIxkXDM9lG8k7j/LGyNy6n2mMhHok3mmyHMU5gdVis0V6OC7Th8MISPmnwsIpxqmS0n6DSqkS5uiaOC0uSa1JaVwtolx0c2mpMRRPJGXgI9iASA5hZFKJa1UBSsnrg3KIpk3LsUsdBDium36sqTxkFBPhVT4ZkEW+2cLUeuEKglTBCfQvSLbHQg0T1faHj2sTE1eqrhyIpNQuiugXTXaO9OxWNsDS0fYvE4v5L0YFF7zRB2JcyvURsuwXbiAHGuVw8JbcTBGum+KaSENhzxhHYB6QkOHU7LF84YXKS4uIUs4oCobr1WTbB3EvUtEriOJhZpHT6JcgTDSDXEXUlv2+syxifxWh5doQCeUACv4uxeW0NOPXN9u7qgydka0ulnqLMXFNL1D+KepeVV0fmR7HZRAjX0zDAtILtmBdOcpruYzp75hyxPk3kaJayGrOizE5MsXdYF98xhp/XseBCKJJOxu6vGXqbZF/qj+CBoQGmn66wQhnqPxF/TpKqDvv2ekQdSpOQeHoyjkGE4nsky3UHdNm9ufLvhB7lRvq06dVD/Rs0HqK/CDGo5jRVhf9Ik30Q77SLdbmEc1W7oLqM5lC0VBdZsoFnxpN1SqPhJxkhUZ8Owlkc6uSljeq818jrrcRFwoV3UvYKZb8Ne/6ukeXFFErJmbUYosWm4mT1zgVyvPpO88O+gwIVFmLqttX8st/5jmvUf3b6vns0/tX2N2fMZlPoR3K2msz2jJp/fwIIIfAWV7bd5BtJmTdw5ewRKTCgmc+2KQIlWFZa59oH1XHLtLEzLnH8JVBPKWi1RAo+2SAl2zaYkNIUaDoREorj6Hva6Fh/7lj14UWYZLPBJm6dFwW5AdRjxHor2KUuT6qiRPfuhTHbpd9hq2KqCncSDQNj9uw2f5H2YJlBOA1+4j6N9IY/Rup70gsRQ9pJMOydJRfOKgDrBpFBl05ht9Q4KUO1jmuV0QcKHyU3EGjfafPOUM7pQgzItX2ufkiWIIGMdkT85aZBSBLeetHNg+k/asn2xiR5JDPfZYenXDZvnLIm2sICPZb4gyZJ1M0H1qrEMiTS5pdljxLBEbJlxmcHS5psoTvN0twH5wCRsnU98l+/SZhNn3/Au379oQIV1DIROvWingZs+U8K2d3KXfqfZJF1N5lFOtNuIbQCdXGzIDlaFjhtYs4KEsKFkcpZt66Vfw52YIshTe04xT8G8YhIlNX0Qf17hgNo+3lmyfkizyVdSaMASbDutxUyWIXzgT3EAFniLRbQE7zThN0D+oGnJ5FPxJwEBZ2GZT67Ij2hbgv6CVhYww+QsJEu6bY9DPpJ1RCa3IO+ICGjW9Y5mZPKxWuEXWubh5jsB+dEowVgSWCspMuYu6l2ZfCYL7aqslnxLyS7N0LFh1cW+LcgyqjBgyQPnEDjIFmmmXZJqBysBVg5w0jyKYWTzcgGOZXIbbtI0Fmc8d3QL3pdt11lWMO0Eo9umlbanoNvvf7Du35pWVlzClobwD2NmAds0wLvUxLSaCca39iWFZU5+I1uQMWwD83eSRutt7b/ulY+EAtPstkyrllTTW/cc1jxd2SuDEodMdX9lTO3VwpoS3yRTn9iWZZi2sfBcFVwZr2irJtJF+WeYjnVULV3HX5mvh7dYbwUra+rvNtdBxZO8qYVqelHSo+QY1VacYktXkBVUxcmUaMPYbS6BSnfR3RA5zqD6EumgKMdEcY8KEZ4/Gk0u2nR/GkooPURtnX4xZaCEUiR73RRRtLOE0CycvQ5aVf0SX7TBOkUUYsbsbISJMmHRFxJVj9fL++qOUb//PTiDMTuLsXpL7VbiJhKlaKyJvbVbFjvKJF1OvwU7FCXWpG57bFxB7KPPh1g68b0CLqFYVfXLKy/5f+DTO562HSMJWl+jZLmNwA0OolU/ML2PVisa8w+DiPMx2tI/okntQZv4Iw05KMZcQLpZpJMbCnEOHFQbcz7SLIVAwLC8bxN/zuIN2cJYjpBswtFHwlzXevKBZMBB3gtA1z9WabacIH5FSCJ/QPDdgLTGQlGZpzGwyvbjI/i7kGQQ8HO+MZ/T8jFDwala6Hm0npzTpIlc9V6xB+qIxSX7e0a3kIK+SYwybf9giKK+HdqLlT/1qUEgROmLaUBMb+oFRA99f+kbYTg832tgC3cRpBbkYRRdY1t2Jx4FY/EIIr9CMALT+vWBq+lMdQrdwbHLtNfeQ+eHqHJHbRdEAdX+qAMjWtyiSyvuiU4mag8NOgcNU80KRBOkbgmhcwPk61F8RT0R1LAXDdOgZaPu+KKj0qAdJGKr6Lh5L02rra3uUUvXaGt+cTXt9ZtQMwmdYqBTCrQxqN88BIr4gwDUFfWgK9bfNLkGDLYdiVbsENIm8ZDYNgttnjsQk2hdykTcFXZHqlyWxwamjgfmrhd8+RZCBfK6naAlQLiS4CRiWtOlGCkRhqWW1C23DvcOImNeSoIcd75jBdU5kIdIsYBiFoJGQeURjnvsQ8VUEyv3xLQ3cfOWZx9084bnLx3TsaaeaelTm7rhdOFbxpSQcGFYywVdGWbHzfO2ceXlq8JrHE7cfZNlFJr2Mzz3fvC9aIiL7mbTDue5mt4men571T3lqK/67VJPPCy6qbIucOeg3W0HiMaqrUlarOI83Wq/lnVExfm535tQNFTFSNRaFZWNEIY4W0BiEVwMDj2EP/ZaJp3Oagbn7vUhcB93qg8csNgQIXLZ1rgSMXqSRfmyRQnh9dc0xNNYLZ6mMi4Ep6nwNSN4mi78xQJT7CFs3g4QU8N8XoOIkaNVTkO+CHSNqYCu+bcjYhCoRREcI2sedN5N+O8Ex/Syw78oTkYwiREzImc9jJ0RY38BjMboxgUJiEbaKZMDZzDgBqEcBiCZQ9AaVRANKh3eAk+DUtje4/vxNOI5ObIG42lE+YawLm2r7KnBYIoI2wfcHImoQeWimNDvr4NjnVvyfbSNqMeeGvjNEegbU+jYKBDneABOR2+HOByRWElxOKiketoHyXkaNH6PA+aIu4chOiIdE3UVetW31xDGm43AHwjOUPOPvDh+p0YC4GkTMaHZckjPT4HxICCO1ZMPepFjDNGDsTt+X2a6EGU/Jz8M7RHJnyLIRwWm0ySFRwCCUO4sxQb9R0J/+PwYBYSqHwwIEtk4hvicChMagQahQuYgSqhbjfwijNC0ez6D91AcRvz4mcih/2aMUAcXZBiuqR9CBrlDZFDgBoeRQbwJMzO8wHnnQ23HpzSDd47nGxgx5HveO8N0WtSQY+js8x7kkGXuRw4laQFFZtNb+fZM6olG6jP8yzHvPvOWzFkNOxEdmqbzWb/LGaZQjs2eCdxaQPFqB75uBVDOrfGHDH1gUJ0fxexv31jXjmb3kw3JJ0k6YbX9pEgny/Td32CL3opTnuj9NTi9iIonziXr2Ykz+wF3umc7egDqwbgzPd3xfVAMxp1TfaF7DXfVe1yMs7wgWUGXkzSZtL3B1/PH89K/LoN19Pp5/N1ru5g80eyOdSM+ltvqN0NG8XisuRFV/F0SMON82wDrJgyNFdOCHQomS1LQyfVq8pGSR5po1eN0wjo7FD7sygrBN89Shn0CWjUYj+P22hkExRu6SrNtF8c3JwxXxfrtN3RXdcu1y4zSyQ2NozUbOI8o5qrqyrBDTjCcCoPGoYNdDOA4xpC3yitWEdywmqWPNWzWImY/KzkdtCiEbPxM1/XFWXVSXM94DQthTXS4ytYkgSmXYnWfWYN+OXkPTFHtfVJkjIOEllnFVTtdBcCqaNylDIT3lWT3Gmm+bXhZ1jhFQ4s5H9VOzZ5VcDszfgqgcoDajFXpws+a05aXUVim2cdlmoZtHwXMdHRdq/84mhPY1R/fdDXLdtgfCTATRLZgaErW4jfsQILLvIzZuY/2nqkVaCjDIXJsJns3cDuZVwcwCJRZQzEVIJfnJGbt/Rra2YArL8EamP8Y4CxH4JUYc9jiKhskJegxA+Gxs6HJHJyFBFspgJNDUGUPSslPOiA+T5jBZR1cZHv0xD2R1sOzSoCs51ENHBUw1jH8ai38iLlQ7benhGyjyvEcQKzeRKu4g1BFUNQb2B52hiYwqTfgptIeInUAPH0TNCm4vywCZa45mcek1oF9yFKhptpZwbSg2QHgGnhnX4PglgzumQPXBLxrSEsgS+Jc+1KGMdCZXEZ5Xq09DR9oUf3+3XZXFqx1/T5sgMIFjZkPysEj5eybm3SR1nqdLiJQozsW/eDjF5Iwd79J6geZdkUhUzMussuSbcjkDoZIobD3WljZQTGvolVz/rBaVXv5NKtfx820NdnST8vZwjK8VRCGUxqGy6m99PQpsR17arj+wluE+pKatBoLjMDfRXVOMULudkfBsP9RRuEDJJznJFtAHCDgPyqAYh09WTLWj6MQ+sNNCmGhfZOcpWlpQq/gmnmgq3RJayLssO6K7GbPW7LDHOW0ejNat33ddFzf0G0tB1uf3UXJU33E95mdJH57XoD0KxhvlMx+AzXICi3aQur9WJ0tzC5hh4EdhVEQ/POo+xI71FtM9fnBzA1cnkDK4Hlg58GPDJGFH5uDbjO7FE/y+WmelhBRZ7dgQ7tDVCBAQ7CPO1QGc1+kMFeXxf4Qvq6uRA4JY8ANOHjapdFUje2qPlAwwyPJfq6i4qQCtWHqvOrF1BrfVdS0LimpwiXUWxApe/N8Jg9gzEMlMEeEc3DT5bycsoVDHq7YUR1cdIYNRkl2ulbr43dOqsVD+gMW9u7elodCSE6LWVMtwOZA6HyamI3fu2oe5UeJDbQ7m3xKVpCygn9OvyeNZ4SZtilHHLy89NRvoMJKmiFZpkwaSn7FlG7AhwySkBii4vDpXy2jpqW03yjlDLPcfEuyhw7Fui912Nh4b1JpoqG3bFunrWu5ICyQKRq54rwDuzB6k7K0SsHqD6uKjKeBLdWvr9DJqv+speJ6RrzDSf6OnxQoGc5J/kdqcUP6A5kpMX9Q3T/2Yw0/B32LnRbHt2qqD3d4td1nCAfWr0yCh9nb43iGHA72V/501ceAcgYI9FKIph1+wAn/vUzWA8tV5NTmTa1DVs/PPE60sOb4RtGrDQYqLoafoO3XzTGXduqkhsqkbx+wxA/zjUWq/5nPnLYlMhdfGHjUt1tGBhKMr1GxWWbku3YWwpSsAfXpvhPrThaRgni41dcdTpJ0RMFaVFvWDxyRRN2T3hOuD+7eMHIou3ClwCGhNuKVBvn+RVoUaXJq4qQQYOSuVNkLqzphSf5hH8o95uzV0fwAE5jKVwYqfrtEzJatT1JICLCLylhbti+SpV6UOeh9Pqlx4cPZhrn561aqmNFJduA1CfBIadoew55SfigXwPyAV4XmSZH7MP+vjdyOmnpyvMBp83CAwSnbOy6fBuNxujwuyHY38J0O8gaXJUPOvqW+tGCw0zVGGn8GO3PY88n281BVIJnocCFxKDX6T8leBK7wbWoQefWtWJidXKm2iO1TQqWllhHIY5nCyjgWU3Rgo/iRZqeZhaKzOtgcu40p3Y1pIXuHMo7peK8HdNCQKqHZUUKhc5+Q/mlXaUZiOlBDRf9xVBQzjqDZTbL39sOaH5Ll8qlfmdjXDGswnPuDhYq2OnvSpCNW0Jz77VuBWsRy5EnXW0Z0R+YaJMLqMHmE2tv8BzFIfdL4Kse7x8868oRQSVLqjtCRNRROyTIP91f2NLmPl/6/x+lwAGNvDXdlAkFTzQBqLKNUCB2ljvINe776PW2JtF0UIOaUZHF+pL73dcB9TRI5Us1gJv+ZkYS9wvum+S/HB7/Olyi5wU535LADb1Dqb1nMWdJdepMyy5Sz+5YaYcr0XinfMpRkqRznDXUxHq4EDvMlWeKACraTs7jcRuC1XrO8Uyt+VeOWFluSs3tTHhde4/ya1nRbncJQhYjSt2qrCSIM8aVq1ZZarSJr0jUo+ZbvCubV99kjRcRpZYq0QXZEBqV6MLQ/1Rtm1Mf0JgaYhB9jsbMbpU/vprq94ktxn5oXv05Ow1y1orJ5o/K0bXX3JMZvXM7s101XzZL2SmuQtI5J69QDKVfm5QYnsu2L0QMPruT2OqT4KzGHs8tB046/K9Py8BsddAyuQ0oSCeuD+W6T9PtAEINREvYdNXL8nbGjpWNLyR+XQ/HXtU4P/m9eJkoKFKvbmtuwn5qB6qS5aK8G1Yl1hISk/enBs5JIM3Lk1r45KnTwaeA4FdEtZk+bQRniV8ai5pXsUzJcOWBFUc4jLPVkdR3Fb8KahK1fpMevbXeoZfkSt2DICovDbdbm5OSNc1McCL5uSDwwAZWmePNibPdE9rAopOCQkaRyEH1HPO6e88yfDzPY27GYmmq55Uikek0SNcz0RpIPxRx6oJ3YN1S/h3Mwlp/q9j0ZlzL6B0qC/fXW6HnVwaLLGyKah2Y6xu8pyLGfuRDrGI1V9DrNz5HsdzuSJHIkkHu9Cvs2ih8UU9fDuLaxvMzruc6mW6jeQR5yM8jdhwM9WeyoElbM9D9KkkHgG86A+zbVLw4eVkv+pvtBzurX4BXVXIEef2W9J8+zIo37mdVYnTCYZFAK8Z99aEVyRTL2m4eHD4olUzrSKaW1hMLqm18AOaV1Y/dWpfRCzPBUt/mhmQ5k+yDjlmx9J3V3h5uvGCxNGQvDMrj5matjHbUxvoMqDrAnVEk7sD+lksIY0kpKoqfSSuCIDuRFlub5Iv3O3gJXDCSm9AxKwpu05X5ItD+L6+a3VvafWklWYcnaMDIJnxqYbWnoknAixXjXnOzvnlmnnCE50ix9xFUqZPPyzuGIt38VZOC4dTa/aXRsJJUmrurIjMNM7vXn/v72hCzy/1ov4Svm9f6ecuZn8qaiif4ROfygJer3TlxYS1QpnxxjRMHG/F7ufB2pKIbU/8iJDxzhGD2F5NcfDw9DegoDfcU2cfNDoaflotXPaAWHxVD/vpWitBQG+or0PCk9eUKuQs9VpOcq0nMU6TkyemOZdaByItuPuYGSCoy0uVS2zFJcgqlIz1SkZyjSM1S2TIWU0s4b0hJoJKUdGfcT0hxTNdM2Ze5FvulK2bElc38/bZm21CmPJJkK4xzVpFWK7xuOk5/IjvgjhUgob7+N+EuFg295mjLizxW6syquUsHWA8UsK9jDflfbKt1qfgxlj3K9Te0TKGZigXQ7f26WGMg0bYy3EZVU4u2qzB9ocSRnKrYXKBppoJjZBYpOJBh3bUN6CgMDNdfb/Mq8Ej2VSBQohyy9si9dIQryHztVNVmFkYEqRV+Voq9K0VOl6KlSdFUpuqoUHVWKjpTiWMqpQtGWUmzf7ev8yums+Y1TSa6pMpelyr2pStFUlbChrPxKFJWIqbGmmglPlVLh9tfr1ZJFhXFywMxIsqgwzlZNPm01D+2oZo2OWgSR4+FG3IDCOE81a/TUYrm84TPiShXG7Uu7Bs5eYZyaOSqHIfXIpkhRRXQ1RYWR/H9TUKWoMLIaqKJ+NUWFkfy/YlGlqDCS//8nqhQVRvL/00eVosJI/t/uqFJUGMn/Fx5VijDy/qX6z7TymemaL/8P4Qrv7iOiAAA=
</Details>

**Comment by ravignir** [comment]
I don't think that's a bug. Maybe AI just waits for a better opportunity, like a real player. Same things happens in civ5.

Another thing: Great Person can't be captured in civ5 - except Great Prophet.

**Comment by ninjatao** [comment]
I believe this can have some improvement. Now AIs use great people (except for great general) only on building tile improvements. At least they should consider using them on developing techs, trade missions, or golden ages.
