### ISSUE TITLE
Q: Android Permissions - Run at Startup

### ISSUE THREAD

**Issue by jwmh** [yairm210/Unciv#3325]
Currently, I'm using this app under a separate Work Profile setup,
because I don't want it to:
* Run at bootup (which slows down my already-slow device);

Does anyone happen to know (or recall)...
What was the reason this Android permission was included?

Also, if it's useful, maybe there could be a toggle-switch in Settings,  to disable running at boottime (or whenever)?

**Comment by yairm210** [comment]
This is to allow multiplayer notifications
But I agree, it's not necessary for all players

**Comment by yairm210** [comment]
Waitasecond, I don't see this at all in the android manifest.
Are you sure this is something that's part of the game settings, and not something that's in your personal Android settings?

**Comment by jwmh** [comment]
Thanks for the replies!
Here's a screenshot from the FDroid site
(Note, i'm running a slightly older build than this, but still has the Run At Startup)
(Note2: 
FDroid i think doesnt have _quite_ the latest build,
but unless it got changed
 between Version 3.11.9-patch2 (494)
vs. current dev build,
...?
)
![Capture+_2020-11-09-16-17-19](https://user-images.githubusercontent.com/3449756/98607783-1741c080-22a7-11eb-96c4-4ea66f34ccfb.png)

**Comment by lyrjie** [comment]
It's not tied to the device / settings, it even shows in Google Play.
It is happening because of the notification implementation: `MultiplayerTurnCheckWorker` uses `WorkManager`, which automatically adds some permissions to merged manifest, these ones to be exact:
```
    <uses-permission
        android:name="android.permission.WAKE_LOCK" />

    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE" />

    <uses-permission
        android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <uses-permission
        android:name="android.permission.FOREGROUND_SERVICE" />

This is from the `AndroidManifest.xml` that actually gets shipped with apk

**Comment by yairm210** [comment]
Ahhh I didn't know that :)
That's what happens when you're open source and some of the work is done by other people who know things that you don't ;)
@lyrjie Is it possible to add an option to disable the auto-startup?

**Comment by lyrjie** [comment]
@yairm210 [Documentation](https://developer.android.com/reference/androidx/work/package-summary) just states it uses it. Couldn't find any info on disabling it, and I am pretty sure it's impossible

**Comment by jwmh** [comment]
Idea:
What about:
* adding it as a Plugin,  rather than part of the core app?
* Or releasing a separate fork that has it** removed?

**There are two things i can think of -- either of them theoretically could be separated to resolve this issue.

A.)
 Out-ofGame Notifications as a Plugin;
B.) 
Multiplayer itself as a Plugin.

... Clear as mud? ;p
Does that make sense?

**Comment by yairm210** [comment]
There's really no easy way to add this functionality as a plugin...
Unfortunately I can't see a clear way technologically to solve this problem, so I'm closing this as "unsolvable" :/

**Comment by SomeTroglodyte** [comment]
We should at least update the description that F-droid shows.

`"Internet permissions required in order to download large font files,
especially for Chinese, which, if included by default, would more than
double (!) the app size."`

... seems outdated. Where is that source file? Studio doesn't find the passage ...
