### ISSUE TITLE
add build road to tile feature

### ISSUE THREAD

**Issue by x7rgaming** [yairm210/UnCiv#333]
It's extremely tedious to build roads one at a time or to pray that a worker will auto build one (not a railroad)
In civ 5 you can chose a tile to build a road to and it will automatically build it, something like that would be very useful.

**Comment by yairm210** [comment]
The main problem here is actually the UI.

Do you first select "build road to" and then the tile? Or the tile first? Where does the option appear? etc
Perhaps a long click on the tile could open options other than move here...? I'll think about it

**Comment by theodorthegreathe** [comment]
Something to steal from Android UI. Long press on a destination tile pops additional options around the target tile up. Possible choices:
- Go to
- Go and fortify here
- Go and set up here
- Make road to
- Patrol* to
- Create %improvement% here
- Cancel

**Comment by yairm210** [comment]
Added by @sulai, will enter 2.16.10 =D
