### ISSUE TITLE
Black tiles on Android 7.1.2

### ISSUE THREAD

**Issue by pragma-** [yairm210/Unciv#3330]
Everything was working perfectly until an update ~2 weeks ago or so. Now the tiles are solid black. Let me know if you need more information about my device.

**Comment by yairm210** [comment]
What version if Unciv are you on? Are you using any mods?

**Comment by pragma-** [comment]
Latest version from Google Play. 3.11.10-patch1. No mods.

By the way, it's not just the game tiles that are black. It's all graphics. When the game starts, usually I see a blue screen and a yellow smiley face. Now I see a blue screen and a black square where the smiley face should be. Then when the main menu appears, I see black squares where the buttons are but the white button text appears fine. The blue background appears, but the game tiles are black. So it seems to be something to do with the images/textures and not the solid colors/text.

Is there any place I can get older .apks? If the .apk file was published in Releases, I can try sideloading older versions of the app until I find the exact version that causes the images/textures to be black. I can start from about 2 weeks to 1 month ago -- the graphics were fine for me then. I can try to find the exact release that breaks my graphics but I need the .apk files.

**Comment by krushia** [comment]
You can get old builds from the F-droid archive, but they will have a different signature than the Google hosted ones. Here is a link to 3.11.2 which I'm guessing will work https://f-droid.org/archive/com.unciv.app_483.apk

Then try 484, 485, etc... until you find the first broken version.

**Comment by krushia** [comment]
I believe these are the same signature as the Google Play ones if you don't want to uninstall (as would be required to use the F-droid signed builds) https://unciv.en.uptodown.com/android/versions

**Comment by pragma-** [comment]
@krushia Thanks for linking to the F-droid archives.

@yairm210 I have confirmed that app 486 is the last working apk for my device. Starting with app 487 the textures are black.

**Comment by pragma-** [comment]
I went ahead and looked up the version numbers and dates.

486 is version 3.11.4, Oct 15, 2020. All graphics are working fine.

487 is version 3.11.4-patch1, Oct 16, 2020. All textures are black (including the smiley face logo when the app starts).

**Comment by pragma-** [comment]
Here's a list of all commits between those two versions: https://github.com/yairm210/Unciv/compare/3.11.4...3.11.4-patch1

I hope the issue can be fixed soon!

**Comment by pragma-** [comment]
By the way, my device uses the Nvidia Tegra 3 chipset. I was looking over the code a little bit. I'm just speculating about possible causes for my black textures. I doubt game.png and game2.png have any issues. Maybe changing the max width/height from 2048 to 4096? Maybe adding those com.badlogic.gdx.graphics.g2d.Batch draw() overrides? Maybe ... actually, you probably know better than me what it could be! I'll step out of your way now.

**Comment by krushia** [comment]
Issue # 1340 (No graphics in language and game screens) at yairm210/Unciv - https://github.com/yairm210/Unciv/issues/1340

Looks like the change from 2048 to 4096 is the problem. yarim forgot to put that size limitation in the comment and broke it less than a year later.

**Comment by krushia** [comment]
For the record I just tried on an old Samsung phone and textures are broken on that too. 4096² is a pretty beefy requirement. There are still devices in use that can't handle textures over 1024².

My suggestion would be to have the desktop class pack into (up to 16) 1024x1024 size texture pages. Then on game load, recombine those into (up to 4) 2048x2048 pages or one 4096x4096 page depending on the device GL_MAX_TEXTURE_SIZE. This will keep apk size reasonable and only the higher end devices will need to do extra work on load. It does nothing to solve page swaps at runtime for those low end devices, but at least they'll see graphics.

**Comment by pragma-** [comment]
Good catch, krushia. 

I just spotted an old comment referencing #1340 in commit https://github.com/yairm210/Unciv/compare/3.11.4...3.11.4-patch1#diff-ed127f6dcd258c68ffc9ffcf01c8804215d8e9794d0061269a2ee1918c3cfcd4L118-R136 along with a new comment explaining why the value was changed to 4096.

**Comment by pragma-** [comment]
Regarding page swaps, I just want to mention I have no performance issues. I've sideloaded unciv-app-486.apk for now and I've been playing without issue. I'd much prefer to be on the latest version! :-)

**Comment by yairm210** [comment]
Wow
Tbh it's not like I forgot that in the comment, I wasn't aware that above 2048 was a limitation of the chipset, I thought the only limitation was that it could only handle power-of-2 textures
What we really need to do is a restructuring of the image folders so the tile images are packed separately... But it's such a hassle... :(

**Comment by pragma-** [comment]
In the meantime, must it be 4096? Are the page swaps that noticeable? Can it be dropped back to 2048 for now until things are restructured?

**Comment by krushia** [comment]
I think the performance has improved with the change to 4096. The problem with letting libgdx automatically create more than one texture page is twofold.

1. The icons aren't packed in the order they will be rendered (as yairm noted above)
2. The icons aren't rendered in the order they were packed

Doing those things is a lot of work. Until that organization/optimization is done, performance can be expected to be worse the more texture pages there are (there is a 1/pages probability of the icon being rendered to be on the active page).

A starting point could be to put FlagIcons in another texture, since they're only seen once (I think). Also I didn't mean to insult you yairm, just meant that the texture size restriction was pointed out in https://github.com/yairm210/Unciv/issues/1340#issuecomment-554767429 but it never made it into the code comment (only the power of two note did).

**Comment by yairm210** [comment]
I tried playing around with it now for several hours and there's just too many thing that need to render while panning the map, and separating them half/half between different textures leads to godawful constant swapping between them.

I currently dealt with this by removing a bunch of images that appear sparsely (building images, unit images) and removing them from the "big bad unified image" by loading them separately. 
But this does have a framerate cost.
