### ISSUE TITLE
Mods - wiki, map editor and city state quest

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#3331]
A couple of issues/feature requests:

- on the mod wiki page, let the link at the bottom refer to https://github.com/topics/unciv-mod and not to an outdated google sheet
- some mods (e.g. civ5expansion) introduce new luxuries, so can it be an option to have those available in the map editor when I select that mod?
- having said that, I now have a city state quest to connect to "Nutmeg". As in Civ5, that's a luxury that Indonesia gets and can't be found on the map. I don't know how to solve that, but maybe an extra requirement for that city state quest could be that it can be found on the map?

**Comment by yairm210** [comment]
A. Done
B. Not really...this would require greatly changing the current system, I'm polling this as an idea since this came up a couple of other times but it's really not in the scope of this question.
C. Disagree! I think it's fine that they ask for  resource that you can get through trading ;)

**Comment by krijnsent** [comment]
Thanks! Only addition to c) -> I hope there is a check that Indonesia is in the game?

**Comment by yairm210** [comment]
You know, I'm not sure
I'll leave this open until it's confirmed or fixed
