### ISSUE TITLE
Crash on next turn

### ISSUE THREAD

**Issue by drizt** [yairm210/Unciv#3333]
**Describe the bug**
App crash when I tap on Next turn button.

**To Reproduce**
1. Load my save
2. Tap Next turn

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
No crash

**Additional context**
Generated and sent email

> Game version: 3.11.10
> OS version: 24
> Device model: CUBOT H3
> Mods: 
> Game data: H4sIAAAAAAAAAM19W3MbR7LmX+H6Ge1A9b3xJsvjy4Y10rHl8J5Q6KEBNEmsQYAHAG1zFPrv25eqri+7srqzQdmxMYoxSBaybplZefkq69Nm98duv/tPedkdD+fVh0/1z/8uH6rVN+VpXZ525eG8qP563B9P1fb9bl81Tf5aJYvnVVB8XtQfo/qjWrYfg+Zz0P7Q/Dfsfpk1v0zbz83HFJp2FMLmY9L9uv2s+l93n4K2u6z9nDYf8/ajUvaLLbmo+3Voe2k/686DuKXdkWw+w8eWop1H0bbMNI0lfK8bSg6fu06bj7r7hnJix9rNMchbIpEmaQfetNEL1TbXn7u5RXaeQDy20wxinGdi/5DAlPVqJbAsCSxLS7PrVsX2q+1nTbKwg9HL0c2q/UwmmNklLfoRm/VqJ6i7Sm2vHS/k2G1ku006btK9qMjOuhtJiH/I+s3QJCJYF9vA7Gli11fhuitYSQVcnPRcbD8Fmmnab6ZIJbUsbTlaM3di1wm200wypOIVIINoRmy7SLC7xM7dMCsuvkphKVL75W7fYpCoGHqL+s2KrNzEKE/YGhdUDzq3Q8jguxl+F6Zr9EAGrJJTBaLH1Pw2gylkIJOqXwqzELDSCXBeAt10grC0vGK0QbcdoFwi0BJ5z6l2kmQF9SRTmHw0kD69VKpXBaDvItsf6Di9a1aUdOvcts4HcpSDzESWHTPYS6In7XbbIeHGW36wkobyHPa/JWKOi92vQT/2GMYOzKF3IsRdKSzTFFZ0MspuqHjsb5EHjQJd2sVoP3cfw0752P3peQKGYnQKKFu99XbnLSPbM88sRQjrUqBKC0GWYYNASHO76DkwUga6JAPhAr2sz7i0m6BRGHBipaaXeqARLFjWL6M9kE2DbtYRyJblZz00ENu0H4GmklpO6z4WdtlA65n1BoWO26dPN/2HpP+CstaH1c+gHxWyZ9arM0sXbYkcVs+IdddvYvs16hkIw2Gr+0jxhyX+YJUm8mgvQDF8I8Jvw0moKUWWVNRNSWszZDSryVBNKSvGwDeouEE4yfjDvlMyYmRFBYeK/WjOANspjKQdK7F6zA9w1OvDTm92urAHMzB4+1kfsoQFwPy05k8Gs8+wR1CxqeVF098S1Vy3f9QESa1mi5CsEV8YUcs7CpcvtMsXWjqxXUl7fAdgcbRE7Hhx5xTRsQq0vh6v1heWrgKBSHp5xd7siGELiY7TP4AllOGfrVGp0K6F3THSroAynKwgTwEq1RBWFM1D0MKFpQhWcPPRnMrwdWukm9+CylRWZ8IOocEBJmtsf5vYnQX9j1o/7ZednOBLu2zEr4mtSKPXZY0CkEpN0PaQQ79gUhi5Ww7kF0xmWNAAT2CrnPTy2W5AoIj3YS1AMEP0MuP+BrDBaFMoMJnaz6jhc1wr4l2kdgIoAKCCwTElx4r5AbU8WK3E6rT8hBwLXGAtKziq8Uy1tqAxCJagNJewEAXIUcsQRPWD4KOUw4KCbQj+MbrK9ky3n2L4uzlJ7MKh0rIKDk1PEA5wMlOcEuwJ8XmLVn+BttSThCBF7430P6GdBt+MUKGgT2D1UgIzJUc1Kh3Q7lYACtgIK7CdPYaODBpbeIbCxgdo9ODegMEFZhg6L7YjnAnaNbB8hslxtlpytFzEVkUp9DjQ72w/E14FNUOCBFm/zIQ7UadZEzWBWaHnW+B6wLrioYf8iuYLRKS0WWVEG6dV2GkVdrGst04iS8QQ15E0jEAYswA1jzbyqJVotSqqA6KmgUWQw+Oew63nmsKowGqAA4+Etog0WK0J9n1uVQ56t/qHTuUsyYT0WtA4jR4LuHoKWLFdJRL+sN1iqIhIKWwMnF0FTDpBRUPOJZWDPrTibgZNRL/AH0Bk48XAhNFEITQHRjI5cAcaUX9KYBEweonmpB6+5f8AQgvE5QFPvIuZ9p2jS6yIr4wObt3jx8Xdcb+tv5i0H6rDq7vqvPp0eHpYV6e3t9/b36nF+dIEnn8oHx93h+p8XiVJPZq7U1Ve3lXHx321+qR/OJ2Ph3fH3eFSU/r8efF43O82u4Zs8/nx6fHVvjpdmuD15fmxWvV9LP4o90/V6quv6lH9z1N1vrwpD+VddWq+d6k296tPzf+ff67OVXna3Ffb1YdXh91Dub/54em8Lg/b0/Pi/X1189t9Ve0Xr+5Ou83T/vJ0qhbvjpdLVf/1ze6wO9wtXjXfPj1//Lz4Y7epJ/VsO6rXZbO77Kou+n55fn08nC+np00Xkf+0ftrtL9/U/7et6dRt3lcP9cRvjrc3r06X6mF3bgfwfbMMNz/t1qey7vSXy/FQ3VeHeoJvjvXCVofL4vtT3WP9t3flvtxUdZNyva8W5hu/lfVob97s9vuPiw0M4L+eqnp9PvxQHu7q7m++L0/1wp3rNk+nU00Vx/rj+ddzdfqluqzq31SL3eHd6Vjvzvk8mNCAVq0B8noNmpnXY2r3r8k4lIdz3Xz1Sa/nLy0jrBphuD0+HZq1eL37Y/XjYVMudttVso7DLMrDIKu2aRDnkQrWybYKlvntNsmrNIq3m8Xu/Pa0q7su96/Lx92l3HcD3R83bfZjZY+KQ5MBef30n82x5Z69/vvt8bjVA4ki/EuxOD9Wm1253501A15IrsS6IVanWiM2HQi4tZZy8jt71lqdah0te/jbPoYa3GphGsCxytCmM2x+Yhj27mI4Hxf1vhxebf7nadcsSLj483j6HZNEKTMobsjcJLmhdAP42InLlJT0bG8Y3LD/FKMfT+fqoTy8jMM1kVVYiDk7jHjOXubr222e3QabJFwHcZIUwXqTFsE2uo2zYlmEZRkRFtaJhJaF3+/+rGf9+5OPixP8Qz7CxOBFQuosor91jp6es2xyI1rY0CT5M/hAef/L7oixdnnW/uzwXuwyn+0nHiNuBz7sxgx/Lr9pPmOZ67dyv5foTjHPKJ5n1lW0jcp1FRTLTRLE22oTFGVY1UZQUahsnSzL2oJGnumNgZZr3pSbey/LqAL/Eo7wDGYWMbkS9MHvPh45sO5IRGox+H0Xgqq/P2CCLB0wgdPhl9zKfx8v93Xzj9KtSvmdqrJsG6XrMtgso20Ql9VtUNaCHSRVFG2XqirydUJ2Srs77T693e/Lw6V8vpQPa+9BFeIfopHtAkcAMs42BG/DN0P/H8JrECyw8WRnq3LlyKvtAajpL/PbxmyK3bDrJYzfp3C9zotGC6t1fhvERRzWWriqgtssyrZlERZVUpJ9Mg5EZ0kcT7v7p/L5VAtWbX6QrfJvyCAnouy5iY4qNIBMI7RNhqtf5M7q669/rJt2pujrxpxsDwiDB2lXYrt73B8fys3z6lNjcu/K1Sf9q8tu8+a43d3u6l+vPn1bHZ4O9bTaKQZRsvi22uzLU/vz29vvTrvqsD3f7x5XYfp1UpuiVb0Ah7v31em0a2zjxjv679rgPr+9fVfVxuoqqgXZdtRs29N51f5pcbsv7+rz9+lw2R7/rNeztsGremrHWkDrzb7sq3/XhH49N7PuRlVpzZUuur9vX7cz1s3yxb/+qE7fVNVBj7LlxVrYq9NrvRLdzD8v/nW4q+Vv610CfsZRXM/42slNjk2P6XPtfuyfa4/Ju0NkBGH0deIdA527Ifv5MwMLal3oMViQCVYM4UBgFYwAg8YwQi0HWzMW0QAZnO6BDQlAQCBANEVuXX3AKkFsPgIvfAROpJv4kUWFHXIbJVPW5lcQ82KQR0lPdwyJ1MXeHFRSYPNeBJXU9mtbY0zB2t/K+gwuagmODQpgssopgPwdAJXMQpllxRBFCCsEcSXIu0HQyB5XJs+GuCRlVzmwBmsQ0plj7+PIpci28GGYAuPxQPAODloMxEULdMQCiIsBxg22xc4JwS8YQSPhPj/aCX5PgznmJ5C4SUwU4KBS2IYRFJTK7PpDfD+wXiOCoyzOBGAmHQnolYRR9chh49SQw/N+LTHBpSzKwgSEEccDoWrr6wYQD7Z5Pg4mlQ4XHOcSw2frsgDDGm5CJBUirJQNJGZ24gRYFUDKEMXL5uIgQRcAlMeCONo5kBi61caa/2H/5QAsC6hCxBUGnTvtBolEyESM468U8GVEV0CKygrsGcMDtHKYYz5ccmgDuS7I4CFEwOo5zQeB9VAhx6HAAgxoHAUAAZgfHkN7zYF4EVxXzyR2z2xfiJCE1bBC5kK+eJgXxPUH0K4cuBw/W+aAxE5nGJiUXtcCBg1BA/MxHnQ8RHh1EXawTUDdKDixAFEQglrtXFvA0MIe6SWMLO8iWNNqIh4ShtAve/IVVmsCHsxMzq414lIhMQBiRoBiNraIkDEfUMzGRxEyBs5PYTk5te1IWlfZ7VE2RolcZo4sux89Wgw0bQJ0EB1jtHQPRLJHBtgoQIIDkIFFCWiOHPaAQZUpTCAhSw26JTAyBlOWgUyx8LLOYrD6XWt1hfgRMOqtsYJ4MzjJAXpmTTS7pGg2DTFmgEG7Gm3W7Vtq5wDBQGLAg5piMGg2KA8jBWRaAOArMG0BuO/CyVKry0GaAWSGwLLAhux9wLJu5yisDCBTCKWCTUcPwwWh2UNXWd8MpgPTJli0wK7BJBYtgLx870A9rxhYmsWemRmiSafzkGDyOfA0m2JAoBrC0xwfJYBNhY8GL21XgegG0PcMDq0zypygWQAgTw88DRWWFbchOM2G6DABT4Bq4GjymDUwvjEEC+5Rb39ZYbAIFTyQ4N4FoGIV6EBgPBiT1XBmPcG/Vr3ZzAT4CfKNB8cVsNEePBxYnCgTNk1H9HXed2DcP8jJAzjOOnKIjAusyvKA5Kw2tHY5IucQUMOg5BA9Zy1OMEPbNQObAx02FzpnzLRnBMcqZEICax9mWwIbPwYcXYC4M8BoOHA6khToSWNcCE9wGAjAY8FqRYccYa4wV7iCggGPYepUoXWD6gq0FQLsEHhXWM7L7aITrF0nOMQ1te2hxRgeT0GIzIgIGFJgXyn0WMGDsG6FwnsdnbkP6YHCLhRYi6gP8QS2qhRUh4vrs85DAfKOaL/AOnO9L9ePksf6BTYECfZCgHexwCbNzOSA3yx1lIEhAhAiTAmMPhmOnmw3uT7QrwdiiTzAQIIGBJSggkMOEEeBjRQQjCBEikBvK3Df58AFFbC/gt1AGKH1YhQsk8IpQMgNAlYQiUGcIKgYD0wwx4XGI9ia7DYkp2zgmIETKlxS7QOjbWA1CQZfx/GHAagjG1v3IRGtIg9sPAqu8YE6dZCIgY3g+UCJKXAu4g/htlGPlSOmJoYLDYdDMJlCFjuF6cAXA3AqPfBFRDiCwTcD1Bg41/uGsBlwE4Y3gR1II0UxGp/BrgfFMEJsWqHdbh0tvNdjZQxEjGgNOBgRqVjY8QUgYz6YokI/HNpI0ItgXqveuuqp8XjGAAwmy6eIbERAgAJ3DvR0ACEFgmzsdgSCumgo6h+QHSyXKMxnWXPGxUEi8lGREBD8KjIYyLSYD4Gse2jSueefqtvLd8fT6y7V3X9lxQIkv68O1anca4RkHC4Y2OTj6bjtcuWrbLk4b3bVYVO1A39sW9Sd/bv66/I90FvlyybFXY+n3P92PGyb1OKHN02+8ua7p/+7W/x83PzeIBW/b0BY+0t5+rg4HC+7292mrzdQdj1+2uzLenKb48PXTeb4j6/3x7vd5musTvD1+2pz/6pt3mIzuzIFp+PhP9XNb8fT77vD3efF5rg/nlafynrh1o28XeoRr74y+M1mLB/oVz7e3Jfnm7rferEu1fZ/fVXv04wx/aRz/npcBgJgM/gtYo2Mavl1ESuVpcnirv6swiQuluHiVH9OwyxO+kF/aAGI3fhagMK22t7sLueb9fHUrPQXHaoRK3ewy3pMyyJX7WjDbJnkeZi0w03aPyyzfsDNkt58cywv527U66o63LTwmpvd4eZDiyv6+CVH3TnOdMwnu+2vDjc1nz4833z4ZXN8uny8+bMe1PmxQeZubw41R9wcn043FwM7+JIj07r4+r2nkBFYzxae0jLqx8XjvnyuTu8bSPMPTw/lAXDP5fb4WE/znfnFh5+quwZm8rBo8A7/qQ4NGqFBR1any/Pi5+rxVMvI4dJOYfH+VG537adXp12tgDb1MJ4XP3Us+K/97lJ9XOw1vQYsUKsZCeZs1UOrJLgn21qCgbStJVjgvnWtvrTSfTVYsExr3tcdjqs+N2pdx2PEj39Up9v98c9ftM5MjfZ8e/tTeb7k7xt9vfoQJYsoXUThIorx38eFgzGv179R93eLFkm6Lmst+vOuwSQtfil3+xZPDlBzDTG3OPR397v98Xx8vH9edMfDpkWp14x492yB6eXlvmrhHufF63JfHbblafFbLQkt+SHInSpNA2evidQHSIO4aqfw/mgmsfqA2KsvgHrvd7eDr7OYvA7PU58xXmCublFvUDOR+kMeiwG6cUGhYT0UpsGHRXGeRkVeBFW2zWruD5dBkURlEG+yrCqL7bKqRV6AP4cLuC1y7Ifj4bh/2nvRmBSGHo+iMcm9YnJhHvPJ9MIiogvI9WiTCyFmliFBIsLKvfZC+iVRM/IDKeJDL5T1PynyU+h0RW6YkcnXXxrCiB1c3GDR3HUajOrLYkw1XNjLze3fV6GchYcYc8LCebwMy2RdBHFRq+36XLoNilpfBsk62WzzKK1V8oBX+whVy6q/lA/H0senqZhN0RanAUXmzhvxRhk3k/opOeHfpfsnB6iaMixBhpF7h2F6nskQLCP0TOJlBd2i8TakzJCM8EKsbuO0KpbBJt/UB+42U0G5jG5ryVbr8LbmheU2Gegt48R19w6OhzsvL6hx0Di5YkpuiSIAQxGnMXK+Q6pCkAIdqYOHdW8P2KYOIjbqEbF2xaSw2F8P5WZTPbY3r75tLoi0EM7860yOCL0Cicr3qq7utceYNpBgEbw0lhFu6PG4UkBYePJ3GNQlOpugbyAo0v0hxEisQQyitid1Kkh5CKL5STNy5kC6AXI3REkYlqb3eDttQsPQ9LQhqAEIig6qnGFfCLTAIKlbxYLUrkBMmekK29LqdkQpAkoLM4EgsBlZBLyZDjlCB1Aa0DCTwg0gW0zS/eQiLCkKQ0uLuBlEkiw0pMlldgoScaCq1EZyE4sEqYqpRdMZxpyp3ZXgREJY+ABhFk7CkQJVEeuHCUTIGg7UaUh4Eu6RQyBakUMXQF5YsA9AroBhJWU6vLlFUpuDIFoh10ghsATQOsC6Ykgcy/iRb1AFgDWWAsxjgblIlIS3JIj5Ceq8MEDWgPB4QtQEZY6IjJNa5SCBRNE5FRJ6lkc4JWZBIU9Kq4soUg9MrzMp/kUC1BStTBYkJj8hsM/8ibAZXRs3bUpRsIpUXoAku1bgcEQo8g2m/KCii435OMOhVI+gsUJqXNKcOqnmFoK9aQSC8jdRJVD+jyJosW+oi6cIFFBvItm2mHQ6jp91U7QIKEbV1zMqprd84FlNlrACqla6twDXgalD5hvT8qQcBBkTScni0PHrxPCAVDjBo7rYVOqS93rW/gdhqkaYAKxDVLqLUcVsruFOYltQxYDHF7FtFBVMTEjS848oQSbXi6BW+C0iLTQlahnQDSG2CpEfvE7ilDzs14ApQIPgVxqVgHQ3VqDBNDOtQaMn30cMYNOx4hSB/SkSAqHKmzjCBqGElUcIMhaEhu47Od5MehWGz2SZqe9FTiNcCZVhB3ApQveckpmSRSKDojEWuLrgoGt7QSVTNMuG5jix2EJSi8+NLAjq7FCzlZZ1IvJADxvMdZNMth4TGTqxlRBXg/iVgEC4GezvsHLk0p0ULhGZO7X8mQqTCi8rZe7kFHXEdLIU8cA0DgjQN4DZklw5In5JwR9aYlIzFpF3RVgYrGMnr+6B/spqTpJCk4NKQRhFJfdaBnAIM6XC3ZR+TmTDSKzLV6hytCRl5Epif+mEbCaxw4SVLIkxOcRYm2+QAkXkiFcErg0YHL14mrHgTOcQAJDSp7G70SCztU+fB84BkTAi/TFpRrePGGMaKkSdC4LaDixgIKn3YTZiICwEmAAWEjA39c/k+0cykm+OhyZX9LzoU5Nv97u77ld9BtJJNEri1DYZKIlkCpKB8SAZGEYhW1iqgSjYRJ6uLqVzdt4SU8P0YcinD2tWqtmh5rTmn+r/jaUPR7KFJg3Yp/5G6lrpLF+f9cPg8yAz+CVTfbRiFRsZ19V9RiLjusUqW4oj42lMQ+M64NlW48myzTZeVkGaKxXE0ToP1m1OOlqqcHO7KdaFms7zaalvQ+U/1bJzPMjye6k3cA56Fk4BRfRLiA3QyiDVKAF5ay5kaKUbkt+R+wpYn510Q34g93jMqEhB9WgYm3cLhQRkaMVgnnQQuBZm9FdUE5nMuuRy3lKRl7eSrcqqWlkFWVVVDSZiG6xv49tgexupIt2G8baglZ7szZuWk/67XinCR9I6PSSCSpxBEjIiYQkSCCC+GDk6Y/cvykmyLd1NjrghybeuU1QjO2d0TG3bdW1XsXwPC+8WhmFRpcssCm7zJAniOImDIkyLYFNm5Xob53GUKaoHMr15/67VcU3vvnzwqYJclkLtbaDeuwND0FpXg2u55P0d/SWaUZjKjArIjSXTzCJKU2kvypeNJK78ZVv+vqItbd5rsmLLz9Xt05lUtiGFa4J0TkJvOMYf7w41k9Un/kNLuuZETTbNhtVvRivAOKG7ZKgUQIdgzg5icyMVYEafhjJ38klYqXc40J4mxjW5B29vN9I64GyKzj08qSNlh6FFgKD62Sel3At7vtou9rdq8FtFAg/+BB5x6fk7fphAG5bMcBN50AJu/LgpURisc9WPmgojyT1vOs+XwCMGCROEJ+kHN0sHNwMwug4BB9CuIawbSeX5k3eedJ3JjNkxefN0mJyDoBzlUgjdQC+EeTG140RmuIr4w+yaL6FGauRgDJ0tDjNIrPlBalCWYpBN68n6Umn87cFhGs2bOCORR/6aIQ4UIyAYGsEFH0mgwU0eeHvLhqSF+TUSnvfn0HC5MQxGIn1cBo2YiZgb4+vDDOs6OHcNIUdm+ydZBbyASOxX4upgGoy/eIg2LfhCc2rEAFdjxHz4KIFbMIZQFiXAcAn6zYI/DW8mwsk3qxQM0WVz6sJgMo0wRTJYDePNzawYQyN2duyQ6MKEHMaJnXwck4MD4MpUNo7mosiwmOOMS86NJOQgDA8JKOprk5zd4EbYdFrOXp7EBF1Mt8GtNPM35ufwxEIOJak5MiqCHsaUlD8hB+Uc0CrE9ByAIVJnKW0tPmQDJkdH0v/gliHKgrkHKkzAAdgmtrSHSAS9qjTyLMu5MYm2Z2og2NA/l2vjs2s2XD6SY7sqq4aiYW980oQa+bIvuwa5Am+ejUgeWh9o1ZOTk6bfSGqOZh3QkOXL7fhr7Hhzap5X3agu/cLJNgwCkfXyPMoB5jhfdYcaZP90Rg5lx7nBj1KJQTTid3A5uuvSciT3BlV7/K/IYepteAd3tIgPvYQL7E2vhTDZOOrEkXScNAfnXrQdJuBsns1yjKKn5DCXFkdX3L5dJv9QLs1eox1Notmreq+P+321uez+qG5+fuqe9mju9n30JrWi4Q23yHvDjU9IJYvmX7SoxR3+6YTUj33sdfXJJJlWUf7ZTVdxWarB8yl4Wc17R80mrAa31Ui+SnB1TY/2C+Sy9GMrY7d8pm+tmRRWFC7MBTYVKXnKYTm46dFGQdt3AlKVL5Uqg+g2VUG8LTdBkaa3QbrM0myZbsMw3spurXUK42CCrFXDsGfvBZAM/5KM1aRfEBu8O+gYQ7TXe2CDWCU2iFwlYHzZAIBpjk6N64RQ8ralU2TdvVNCu2bG3hGXJzm6fTzc/PjwcDzV+yJJd6jF8FurJJEnRn2MpIoiXCbLdRBtqjiIl3kc5NswDjbr5Xa9DpNlthw8OGFuI3QsU57O5V25LSsvy8TSZwyIsUPuNiDWCmGGLnxPGz74PUSdutfEmBtE2ANGAeJ/+EaYfHeHlwP73c3jrEyK7DaIwtt6d7dJERRRVOuK9W26zrbrdLukt8F0PKS7Fvh09t4Ei5T4cQptTlmvYYEhQytAze/6X9uYTKc53DdDksHGfbaRpO5rf0fOsWZmnXRMRzbHtxtZnhRJsk2DSBW3QRyq2waCkAVrtd0W8XK9rdSGylqIsvavzbq8lAf/7bzlmHBhfJbcaQATEe9ouIEujNSYkQ2fB3EfqDAU3BRibO/jdUsEGcTxe3F/2+W3Ga9fLNjLecXX4fWpvOErF/9Q+lFFf0v+sUiuyz8OYxjdqW3LvV37zsRYwhGjiiTQAhVNoXcI/EJ0FXJz5OkIBaXW8bkI8kaEN7FoClSNvxgx+QQE/+7DIK3nydLZyZF8nYMTomkXLB5nK1jhcczcroOnIPj8HLztMPGcw/MgbInxRhI/yuxAnUttJCixYF5uQAw1Jnkxqt2ujZtUY19emJ1ewzcYSKwUHj6FBQUUL6SzIAcQAlUSBlR20Wn8LwQuh2KExNm3yUpbdJV7mAEyZeYOQu8LeF5XwDdOQG9AHTrM5mZ996O5LfZ218KK9AICGJCeso8fkPtaCp81YV88wJcNMFcFGSw2a4Wx5WQx82UD+2u74hgdhiy05nsscGjzfIiansxKDTNYspRUZMb+gtcJSIwqtJtpXyfwZZ3gfQI4KexbBnAFz5eT6p8t+Etbw7CVNBOmSzN2f0XVG9OuSVLcDj+0qhaEUUeaM6sTBmE/CDFC6I9c8uuXE1Q+pFxjq0Yp6Gb4dgFmjuCNAozy2nRZn0N7puXpbdV6q4fdZM4wRY1VGpN+PrLXBgjSwpvTmX6NAI4yPEHtcwQ95UFIpI8xkzKPWP8R8yx4IM96ToAmNvBxAZrYGHtfYDz50Z9YVkEiL8LrMfPfGgiH0wv7LkPYCJLtgPcS4KQcvUyEF5yIjUDC7r4sRjcGrasJL6DFoD/Dkw7w0oDvlpDvqQH06TzJBngvwMGiI7bEzS9Y7Q0qnXsvAJYDtTG+GIAXcr7gKwEAi/CWB3GfCSCVQDx1/wmyEDQr6g7bxxWF/4coQZKZR5BgJ5EuRHAI3QPTAGxAiGo6AMFry/9TGOD4YwBQ3h9et8I6HgQfyAP80v77iNyCFzMIVhAhLhS0R2r6Q+ENDFGCbWkNTnDtGKQfooCgOAdwDZ7GCIYArIC1aPAGO4L/QHX6YIBY/J8gAm3pjSGu0anpP1IPA0NFgOoBBxPcdQLTwwcAUFBtVBAeAADtZSv6IyoPY7miYhfe5wAIxg6q/c8r8E8Bd+B7/NPl/j01/nl4nVqQuv5fqsR/vxwaVQJqFlQNRHr+rgr+xKAitbjtBgEXg7o0OtTav8puSTxYWIy5YGcUi2k3BX1i9Hvts1oI78F4i24dAnugjQ47i8uA5fopDIwU7ydgYG8tBsR1YWV/b/2F0SL+fOX+brKdfWDNebdIf7J4WQF+u0RE8RV2x/+pqvwUcyWr0Y94K1+Nfkyx4e0PsPKs6ecpwT+j7D4tsG9hVQOrF06c3mIHt5xU2/fUBUDMlZUYEBgoqw+u1PXV823BfF+lfMsvQmAODCseLCe4vLjB1jy4slA+vUZv7YkpNI+viD4F9Axq6SdJNh/Oky7jaThP+rdcjV8IAT5MuW4/pCdcnO+PT/vt28fq0P7y+d1u0xQ6bjEbA7hPll4J90nwHwf3gcTnKosZyI/khvrbxxbuA2WtNSbIAf445auHF9YHd9SvqFb9cbHpHlp415Zcb5Nmi7vyofqx5rwiqjZJmgbRuik4Hi7DYL3ZhsGtSlWZlre3RZa0bd+Vp/r/L20+bbu7vW1n/Lx6fb+rbi/l7qDrubfYovvjuTo0md+2p2Gh98+tCdP8+2gG2/yxYZd2Ecv9oq0m0L61sPj2+LA7lHpuTTb3Tfm4+vRQPuKAzlWT/U2XiUrDRIXLpera/rQ7X+oBrctz9b46nephrr6t1+10WVy6H7+rypaf3pbn3bkeEtPy8XjeEbBQ0MCXplp2Fs5UO47YD7v9njRp5kJHW8ttzfnj3/tL+j12mp8Xdcvj02lTrd6Up/W+4r/0UAtArQ6efz3sLg0ko+WyN8c/qhYrEHZZ+46RF8c/awVjEt2Pp+PDUWML/s+7VVMGmgzAWLenY7nVydef649TU+4s4alWfSKhn+PrY7mX7Sl+q5bs8jIxRG7LnRHqRvfl+ZtaTRwfft7d3V9+3v1hdN/uoV4vvajflacHQi50t3l/PG5varHbHQQ8LWZp48bKe3P350pW9i7ZcPORcZvDUzArk1fsv9e+WzA5lT6vJJnQu3Z1yPe7DJV0fE5LhmIopahYii9gwj5C9wJG5IbULno/oObRIM946tUwz38gxQh29dtnZ099wsBrEN84nKX18SpVlvqxlppd6nPu+SZcuNqzVi/7y33z0FKrR9+Ux9Pu5rfydNode3Xa1/EeaNSwN7Pe2T+E2OrDq4f10/n+5sfFD+XvZUP35tuyNpwW357q6d78+HGgk0OxnhgK4tudQLmKODcaal8BXdFB/FefYpFRlOgjk72dllwTdOJbjgqejlH1q/LjH7U5JR2b06Oj5brojlRLxeRIrWXlINNaoh7UsIdfavpDu4RK6lCFwR9Y8VWisXALpxuNHtTxlziofWIyyiQm5zFXdkKWgX3bL2kYDQ9blk18DCuRThEvxbPNhFiqRmJWjTiCFUuVSCxVIvFgj7+taqP7SuOkB6Zc+30TXrLCWnvBj1foty5iJR2x07KNU7Te6WClnJbfn8rzuS3j4+pJnMivp/Kwe3qQGXjJ1fYuOxtmwV7XJsW2cr0g57telYqTe7V/qr1tZ3b6u90LcuVh1NvrHqfye3v1uGbpZ5gshGlYA5RZbVCw3cuT748/wurFAl1PuHi3rwd2he4fH5pQ94uPyXjKcfbp+utOF6njYdBsV8ZepHYXr4F9ulXSUKosJEKXcH366LEz4RsnstBHwh4nvZokkd8VvIY67Ir31dyu5p0hk0eBxEb+pjyty1NzT6w6bMqHx7Yepzsy3vidMhFNvocfhsRH1PmGgYC+7KT1jWe+xu4itlRfC1WwztAzalbJ2D0em8pQwp12Ywd4ih7SybE3WbcnnbBePP2F0kmEMyahWKJTEZuJ45Q/RNM5J5Ud7nxOM1UTr2G2bksZTguvOJsFwjj/rHYP/JFjbtp5k5ws4ZiNMH2CS6yLiDUSWvHBDt7sDpUrheicfF89CFbSpJfnRZIM0mTU23VEnj9rOfLsCc40lAq3T66Hh4bUakhlHmjKGQzcCWPQUQN+/t9PtQAP4y/McfyuPLeZ0WHfkRNynzBavWNzbQzp2BxJSCXWs2vqpCKDgmrnYbeMk3ntgozYq6IotsHF2PPv6a4cuj2S5dS3E8anwQxubuCuBzx+KVsznTdw1yKbN5ahIsqmfXJvDCSTqYl40E27xcMxvylP5/sZdpbTN2tZjYxwSnH02DgbQCyb+7wT5visXFb4gr1X7CoMDbWRTBZrk2XDw+wFBovPZBMbaMQKm1ynKdtAsNQMp/P2sMAOUUPDfiSg49hWjlrl43YSW80AaGcPJGAzMmx42RvNcXSGpCEfOPDZR5KGvJ3CUZxh/bh6V2yncDnkvwbn4ONu46SR7UBGM7zKn+GNcl1vZHN8umjp66MY52FqN0oGmdmMWx7ufDD3d6bOFu+MLpdy8/v5/f3u3ODqajE0KWrj4JHktBNLaPLSEZeYViQx/ct9gzd0EtAZx1cePWzurvQz/aY81P87z2GOYd/RzCCCuR4jSUlkI7Etl6av5RcP93THEe+St+fOcA4J65VHsqUSZksmYm1TtmL2ZeNvGXsUedhS38WaJtvd3/obDOVMOoJsfASu9e00Zj3O6VZ96Y8rom8J14PXUhZOL56xEuZmyJVqRl8ykXzbkzPk1/fqEKFjQWkgPAnkSEzAa6XVFKEXeQys8Ty5Iky/7CayKoHjA7pCDbb0Sgt3xFH6RyP7pvALo9oToe0sCXKZe7XTCB/HlBaluyOhcc6jsXzGswvrESY0E7GNLku4pWILnQ39TZixXz3UW/7+eFMs1FfG7Esi127ljD4VMqbcdTAg1tZ1lkJ0BkwfRbnUsM5nJGrzYXR65/C4ULuZqiQyc8JhoDEbZZrbcs5iHSPpygkXXRIGkPNBwLQ1Ea4L2ZjLfuMRpdmHGK9anfM091ij06ktLx/ycZFhp9cHKE0ZqUmDxNQSurKfrirRyyLZ+gqsxAXLhd2NxfHNdVWZee208yQWRkY11P/uaktNT3MvWGxnF8IgrGt3O538VP5euRl+4Vj6aogSNnN7imb0FI7tro8fZ8P+uyO1uVnot93qQzWnMZOu/c1vu8v99lT+yaH3i5cEtSe3271/Nr6yXwwx8OXhhMPpNhY8o5FTkS8wuerswkmd04B1cXxWeHaNyRVyKRtfTHv68NF1MIRmeDLhDviscikUT2bnJy+x81OZQRUMk+JiADfTZyb2BWZEVXkr150IazY7zSSnJBFDeRhIV/CRKjupF2xqdQiAxP5xhVN61CPnplbWNRq88PqPQiu1r8l1TXBXl6kbu2z7klOBx5jzE/PleExRK+KUXWmEFwPXhLuRNbbHPtT/tRG0glO3HmNdglssxjP4LlGnsYeo9MQrJo5H2UXNvuTKld5JX8BFqJ+uDoAWLxyorkclyRgxwsXeLx0zujyCx2E5+oosAzdegCDmQzXLQWBanBJ1lseTXB5bSkkuOXVmXFv21eEsOwNMuaRr/fZkzlyTsbm6Pp2UbDzcpzm37Smv7Pa/yzIq5Gtvd3uRizzmAko3oZ3GaDQ1XBRf+VzA6WR6webSGc9v1oCnrpf1VZplWQyy+gbYOC+1cmW6kx3lNCDJUSNXZm8E4R3WRfY5b5hU4iDNIxwrTGb5nDqJ9xewyD6fWydKB8WDdBCvK32OnSglxF4vZcODPMTXl11xGvY0XwJb

**Comment by drizt** [comment]
Saved Game 
[Inca -  98 turns.zip](https://github.com/yairm210/Unciv/files/5531199/Inca.-.98.turns.zip)

**Comment by drizt** [comment]
I tried to change settings. I set English, another resolution and disable textures and some other uis options. Crash still happens each time when I tap on Next turn button.

**Comment by yairm210** [comment]
Seems to be working in 3.11.11, this is probably something that we fixed in the meantime
Please wait for the rollout to reach you :)
