### ISSUE TITLE
Mysterious manipulation of AI's happiness

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3340]
From what I can see, the AIs seem to have an exaggerated level of happiness. My happiness measurement is as follows:
![Screenshot_20201114-215910_UnCiv](https://user-images.githubusercontent.com/73200638/99157868-bb22d600-26c4-11eb-93c0-f58d65218f22.jpg)
Base of 9, minus 1 per population, minus 3 per city, plus 4 per luxury resource.
Now apply that to England. A base of 9, minus 12 for the population, minus 9 for their 3 cities and plus 4 for their resource, this should make -8. But they end up with 5, it just doesn't make sense.
![Screenshot_20201114-215847_UnCiv](https://user-images.githubusercontent.com/73200638/99157946-63d13580-26c5-11eb-839b-d7704257c496.jpg)
![Screenshot_20201114-215823_UnCiv](https://user-images.githubusercontent.com/73200638/99157949-6895e980-26c5-11eb-8fec-52e2655c7304.jpg)

**Comment by ravignir** [comment]
You are wrong. It all makes sense and it is not bugged.

Regardless of your difficulty, AI always has 12 base happiness, gains 5 happiness per luxury and receives only 60% of unhappiness. It gains additional bonuses from difficulties as listed in civilopedia. For examplr deity AI as 0.6*0.6= 0.36 unhappiness modifier.
That is AI always plays on Chieftain difficulty and is granted additional bonuses from player difficulty.

12+5 - (12+9)*0.6~=5

**Comment by CIZUK** [comment]
Ok, thanks.
What can't there be a level where everything is the same? Or is that Chieftain?

**Comment by yairm210** [comment]
Prince is the 'balanced' difficulty, if you can ever call a human vs ai in a 4x game 'balanced'. Humans have such a host of advantages that proper balance is impossible, the real question is what fantasy you're looking for in your game ;)
If your want a challenge, your can also just pick one of the weaker civs

**Comment by CIZUK** [comment]
I get it, thanks.
However, I think there ought to be less of an economic offset and more of a military one. I find I can wipe out civilisations in 10 goes, but I always have the fewest number of cities, due to the happiness factor. I would suggest a 25% happiness advantage (or unhappiness, but not both like currently,) with a combat bonus of 50-100%. Unfortunately their combat tactics are useless.
