### ISSUE TITLE
Hide hotkeys on devices without keyboard

### ISSUE THREAD

**Issue by drizt** [yairm210/Unciv#3348]
Hotkeys info is useless for devieces without hardware keyboard and take space on a screen. So this can be hidden.

![unciv-hotkeys](https://user-images.githubusercontent.com/534665/99493997-12a99600-2992-11eb-911e-a4c9332b585d.png)

**Comment by drizt** [comment]
I think it can be checked in `UnitActionsTable` class and just create `UnitIconAndKey` without hotkey. Hardware keyboard can be detected with [this](https://stackoverflow.com/questions/2415558/how-to-detect-hardware-keyboard-presence).

P.S. I can't write a patch. I haven't any Kotlin and developing for Android experience.

**Comment by krushia** [comment]
That detection code isn't very good, and will never be. I currently have an app installed that remaps buttons, and it does so by pretending to be a keyboard. Likewise, a Bluetooth keyboard can fail to be detected.

In my humble opinion the proper thing to do is create an option "Show shortcut keys", and leave it off by default.

**Comment by yairm210** [comment]
I think that this is good enough for at least 95% of cases, of course i could always be further improved on in the future but it's better than the current situation
