### ISSUE TITLE
UI element blocking city bombard

### ISSUE THREAD

**Issue by dynger** [yairm210/Unciv#3349]
**Is your feature request related to a problem? Please describe.**
On mobile, there is a UI problem in the following situation:
- A player owned city can bombard an enemy unit
- The enemy unit is on the adjacent hex to the north of the city
- The city has a unit inside
- We want the city to bombard the enemy unit

Problem: The button for selecting the garrisoned unit makes it very hard to select enemy unit below. The button appears north of the city, blocking the tile below. Zooming in or out does not help either.

**Describe the solution you'd like**
Maybe place the button on the intersection point of 3 hexes, so none of them is entirely blocked?

**Describe alternatives you've considered**
There is a workaround: If there is another enemy unit nearby, we can select that one first, making the button disappear. After that we can select the unit we originally wanted to bombard. This only works when there are at least two enemy units in sight.

**Additional context**
![Screenshot_20201118-083437](https://user-images.githubusercontent.com/4800687/99500642-efbfb780-297a-11eb-8291-6d7fadfe5c17.png)

**Comment by yairm210** [comment]
For this reason, when you click on an enemy unit in range of the city, the city is automatically selected so you can bombard it.

Placing the city button in other places had been tried but it ended up covering the lower part of the city tile, meaning there was always part of the city tile that was unviewable :/

This should also not be a problem of you zoom in

At the moment I can't think of anything actionable to improve the situation, ideas are welcome

**Comment by dynger** [comment]
That's actually a pretty good solution. I didn't know that. Works for me!
