### ISSUE TITLE
Missing unit-related icons

### ISSUE THREAD

**Issue by richardsaloga** [yairm210/Unciv#3358]
**Describe the bug**
Various unit-related icons are missing after last upgrade (3.11.14).

**To Reproduce**
Start new game.

**Expected behavior**
Visible icons.

**Screenshots**
![unciv](https://user-images.githubusercontent.com/31358089/99892098-9089cd80-2c2e-11eb-9c5a-5651d394530f.png)

**Additional context**
I'm on an Arch Linux install. Downgrading to 3.11.13 fixes bug.

**Comment by krushia** [comment]
This might be a problem with the Arch pkgbuild. It deletes stuff in the android directory, which is where the icons recently removed from the big bad texture are now located.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unciv#n35

**Comment by yairm210** [comment]
Solved in 3.11.14-imagePacking
