### ISSUE TITLE
Battle modifiers are not applied.

### ISSUE THREAD

**Issue by FrederikCoomans** [yairm210/Unciv#3364]
**Describe the bug**
When doing a battle, strength modifiers don't affect damage. They show up correctly on the battle preview, but both the predicted and the actual battle damage are not taken into account.

**To Reproduce**
1. Start a game,  choose settler difficulty, 1 enemy ai, pangea, tiny map size, choose france.
2. Build some scouts or warriors and 
3. Pick the honor policy to find a barbarian asap.
4. Fight the first barbarian you find with a unit of equal strength. You will have a total modifier of at least 100%, depending on terrain. Notice that these are not applied in the predicted outcome or in the final result.

**Expected behavior**
I did a test game as above, where I fight with my 66 health 8 strength warrior with a 67 health 8 strength barbarian. (If I can get them working, see screenshots)

My warrior has +75% due to difficulty and +25% due to honor. The brute has -10% due to terrain.

The battle preview appears to show equal strength.

Post-battle, my warrior has 35 hp left (took 31 damage) and the brute has 45 hp left (took 22 damage).

The ratioModifier in damageModifier in Battledamage.tk should get a value of about 2.2, since the modified strength of the warrior is (8 * 1.75 * 1.25 =) 17.5 and for the brute (8 * 0.9 = ) 7.2. This means I should expect the brute to do damage in the range of 10 to 15 and my warrior to do about 47 to 70 damage after accounting their hp. This didn't happen.

If modifiers are ignored however, they do between 21 and 32 damage to eachother. In my test, these values are within the margins.

This I didn't go deeper, but the hp modification does appear to be applied.

**Screenshots**
I have some, but can't upload for some reason.

**Additional context**
This is on the latest android version I have access through on the google play store (3.11.13) and without mods activated.

**Comment by yairm210** [comment]
Can you post the game data here?
Save game - copy to clipboar - paste here

**Comment by FrederikCoomans** [comment]
The test game I used:

H4sIAAAAAAAAAK1cbW/bOBL+K8Z+lgvrXda3JLttc2iuviaL7iHIB0ZmYmFlySfJad0g//1GEkWORMqeuosCrSoPh8PhzPB5RrJfk/QlzdIfrE6LvIrvX+H//2ZbHl+y8pGVKcsri3/fZUXJ13dpxhuR7/Hcsw7x3H2zmmu/uQ67a3Gr/TjoroPmOkLXnhAdX0fo2kHXdnftoCltdO2M51qisfjaR+Y6aGyI7ntIj4+u7QUSitAi8eAlui8m6G1Hn0RohI/u46mxZ/upA7ROF117yEfu2C8RuvbQtY386KDr5r76B3sJL2GJzMNW+MgK7BgcFbCcB+u5yNY8v3iGcHqt6ia2PrLdLs15VcVOAIY+l5zVK17sMh6/iv+UVZGvijSvYdDbm7UrsjRJGw1v1v/2vKpvWM6eedn8v+bJJn5t/q6+8IqzMtnwdXx/8VymyT6r9yV/eLNe0gSmPqhhYGWS1inv0qA+XEFG1OU+6VLj9XGfZvUl/LVO82eQuSny/ZbntbViGUu49aEETeXhwUrQuP/s+Z7H919ZWaZFCZ/tyxLGYNXX1Z8VL295HcMdbqX5qixgyVU1ml/oiMGDb1Zj323NWl80CQp5ClLxq1jebevU2IFdeyr2eWPxVfoSvwcTwdIUPmHr5TJ6jObBehHNPW9tzx955M/dJPDDKFiu14u1lVafy/Q5zVl2xXZpzbLOwqxI2nIRw6Y2ewqT5E3JWEG9qGBfdvtMfP5UFGtpCv7EtaodT1KWpZXYzloWF6ESrppA6iLVG1y58tNOrvs7kP/3pYw/uOdB6H0ryr9xKVNzKNlO0wNId/Fw1QQgrMG2+uooHLlOoTJuWXKIXz/wcstyuBD36jS5KdbpUwpxG7/+F2Kw+vy04hAoMSSlEmo2cV/F7SdWUW94eSXmEBrf3gwFWK19HqrMw3nmatV0XFgd6U+coO7Iy0Hrt3H1bibt5ozgqq9KopAsUP5HqEYs0X1UYQOpC9dgX84bqhlCpC1C2ropIzmwr3VKSTd5hMW7KjauirI44kIcSHc4Mly6gtlpbC7xqaBci5yMKqgKMzRBP1mkFhAp+z01aSQtwWdjd9kuzW/XYUvTupUulZ+XyvuhmgLX6nC4Eyqb8NnkSiN9ZLqvDAmwvwNpBY6HQFoZKLc7yivCVcjl+Ay0R3UCAwZ1d46UKp2Rcn+E91oaNEezBhp4UOWiMyuU47or5V6hOVTzobutb/oNUOpC5XBHTe1IF+Ko9tAiVLzZGjyIlMUIHDgyomyl10YxKMci5XOkvcsapQKHam+anGnZCi+lsI8cgr0pvKd8iKqdo6ZCHus14ZBDLlZ7oJzoSkXHcaUjAkDeCJALAuVrBGPdYZ4GSqfSgINTJSvGuG47aSA1LmVU2HiZTiuGEJc60HCFwJAMg+qwW1ooze2uBMpTxcNBMddNKbbaVgGoIm0wBcb5ajnKuzjs1PZOwWYBiT1VdYfaMNRVhRRZid2Nog6BdlV3LXlUuNI1oVIXjpeqg2BHlmRUc+dovK0s95Wmbgi6Me/CYa5OInzIe9JGbHkgPYUrGD6EIxmP6vzsIgIXK+FyTMKUAWMqh/GCzsBclayIQnnSue7IixgbYB7ZE6MuB1TI40hRwWuj4LXl3blyfbP5yFaMpdQ52O0JToTlwIgFcpkKFYyF8ArwligshA4ghDQGTNKTTnZVFGCahkb3g+WHqIqjSPHU/qIzAsFFtNX41FwiX4jlB6NaE0j3qWj0lRE4FjDnDpEvI5y7C+nYCIksBa+M7WhxnGBGgYlgfuA5L1kmGKbtWmbamRc1gPpE9ktY0lGdJGOgOym27/Y5sIR3WfGcJu9wd+XdJ8GbLtohkkaJlopITCCmSQFoP35lsHVls3U1/17Hv13kM7Bwe5jdX5b7mj/MNqyasbpmCfCZWbEvZ5Jl/gau2GXswMu7w47HH/fAIxBfZutiB3Rm1d+4/1jkRWndgKU1ENjZFatqbv2eVgmwFPDZgwVE95GXn58uRiOBxrXOvepYZ7PrZioOqjgQps9Pn0B3dLcvm1X7VvMnaP/A1UMrW11L/hu/XuTplmWzj/vqkeXrEuLR7zQOaP2qqGteHqyvJbC1/NnCNL+Tvit6+fh+rNO6aNTAvzdp3oy+K9tIgYsNn33dcJ5ZVyzj+ZqBixgEA4helkX+Az4FLtlIfizKij/CRsy+pA3VtjBzh0HA6lquV1l/5ECnOS9bobYVkBys1SbNiqrYbQ7WNSiWaq+a4Jnd8vIlbdoLTeehsm448PB2i4SNECzPB+tqk76wrFkFSzYwRdmoPVTtnOt9F2jWbd2sZgWzN4Nnq8bJ1iXL29kukmJftUZ+2Oe74tual9YfCUTGtrnXOCkFXzZO7WzI9iXMe52vYVTZMPkfYpJmq9scmTXWgSFf0qesmQGmZ9vZqvjWaM5AF2xTWh+s91n6vKmtL3zX9FHYY8ZnK1bWlRAqcjDgn+/XGPs0t7yuM14+THdhhETsuuQujD1swghe33Rh7IXzyJzHZM7Y0p179jqcR+v1eh5FYbBIHiMeJgmlCyMJRduHueQl+HuqERPhD5wjfRjMUjApxWwK88QBiNcILW5pOui+A7UKfAVF8X/7tG0UaS2awSCh+Fhzpncw6s50/Zp/sDnTKTT2ZgZdbswUMLqf6tEgT2JOPeiwHGMJ8xGxQCc8OsC1LhBiJgN+MG6mYMrSYSF8Shs6MyPe0dNWBBocCTwwi8JtZcxZPekB3Noet7OFoMJAyjC8AhyfmB10Y3uKq3yOwNWxHozkEorXqEnR/qNdQPwQM3sM/jEMFkQA3UKBg+xBKLqD9JhuYwKDWwi4R4R7LcoRegdm8HQGP/3R6AbOfRTDffS+IeIRSDdizWhyRDkQhTLTExzQfUdFTY+jGFUqtEO+XD2SxQmsUxpMNgadGsRHtCc2OoCfe0NxRf8MSF11cxCqn/vWoEUnnIrpAKIYsoeDFoQ7hBij475sF2GoOYNItt4SUrSkT2RhH4oPzP9xOwunAu4Mqj1Cm4FCHh8heMeRz4ddpKU4bDpi4fvHeYVN4RWLCV5xBJ5/SgF814dpGG6PYHhwBgyXfwwwXABsYFYG9N3DZx1XH4XhQqcR18nHZKuWxKinLU9PrcZDLFCY9Qxn8fU6Xj56y2ARLeZhEq3n3jJcziMWwNV6YYeu5y2Yu2xlAVfC33V77BvUdaSpxZObouI5emY25lNNfjx0cOmG7eLXLdth5RVvIEmwCFxnES2XQRhZVfqDx3dpfuhGfQLIBRM9sorf8bJkaR7/Dt4pa/BV+9/3ECbNbr7PALzNYP40r2BWPOBjmmUQOVUqgaBIPJMc8MVLcHqx/cSf6i/pCzi2BZLyPrqHdYpMHVsFAVfVo3nEAtRokzE3gIVruDjToMaYU9N+Nxk87UbD+PlPKVi1N4cKRIE+LSmq92i2f+3z54wT5rGp8whUAttW7EtAurc7oJUVad5RnJkmNGy9JqOF65Fo1dZI2fXB8vbPwNh/LQiwvq8b0PFP5pVDz6vJ+DL7bis6OX/mad2Q0baW3hQvvKG/MG/LEm+B79dW8S1XBXZXFttC8Nz2SELT9UBF+XfD+e7UznV4ZST1oWRVlcEhYViQJjyRMJrcRCl0z3awTTXdZLUhG07LSJZBKU+WIb9MGWGMEmOsm3LM4BeC56c2EWXE8+ZUqqRbCEcRsu9ZudXiyj6RnBNh1rMBSlgcze+xPdp2HDMAV5bfD8QyLNw4TG/RgAb76/TpMHMsPd/BOVm9iZcLPfPRa344+/9axbY7LgGCCZwOkY55EGqYS9XomjRKIKGXEU1WC1JBtY+WM7WBQ5e3XhTNduHHvueEndjD9ZW6Z2OB+yvYonJ2/TB2dE+ZpHGXgI1zdtZZ3T/WpxWy03sx9NpVkxg5sbBRKuDcWHanChupVJrx1WdWpQQI4JLrp0usn6St+D69Fd0jJZYPsv9iXzcdS25I/i5Ym5ZqefS0R/UWcT+t8opmRNOyBT53jYq0d/Jc8IzOVOs/F0l5I2T7Jyww3W9p9hDLtuignovSvV8DI7Lzcub8XQOIaqePfHn9Atz8lCdFn0UOusj22zQn7IDonNEOAH35Rvcdg5fne9AxeXACdBINnQCd544medKwCLO/tDPoqmAZkY5qpWuqfpNOBNHIPYr1pio3rgof+JbC+YxQziBoLmbmInNajLgrhtC6YWW1oVWAn0G9evWhFO4xsB9bMCDUaT7Ou6lFj7eyfeA+3kyCOacOEp9e5I+Z+nN1nsIvfCqi9o3o926fr0s2lBT9+5HkbV58G8iJN5IUTga8N/aFNqhvzZ+S694JIuIh0e1XJ1OpIc8JLhLQtnTieNIMNHY5qMtwxsv4nGaUlDYSmBPumDDBNq5q+hjAs1yxplNOOIoCSqvop5msgXmd6l0Ztmbi4NWPzyMO1GSnzjjKYSge/FLijFpcpo42ypFrxsXmo835aYhgPkx+IR5OdDL/WrWu1eoT7h+935cau6ZittP1Ya4XILJyIqvsXzQhBXAw3jdSUqsn+ORJfoHwBOZYNxZuiLuq1iY/nU/yTR2FEYtsTdsUaq0IjIVFPzHFI/RTJnevE5/UFhi1GWCAeFdXOgCOnkfzwTjKzfbF0+puk1bNY2Son6LJ6PrEIg1puTSlpW62ETZMLY5opifMbN+lPdkL1Qzt3/JQPVzOSxoYCWk5ocd0/5UCGlnW5AwKHaNCcyA7Jp3HAAZR2D7fJaZJdJlwiLWIUCA43c04snjtSJgCB4SOAq3x4I4rmQlzTWECCkTxyHzdM6GMKRxA6uD6JkquuaB/1fJXThzicPPW40i7TbO/zyTbxGwwLCEktRrk23+/sFJjS53YiZDvXJ3lnvDXYEVoDGO9NoqvxY6muaiLbFxBJo5yLafMcxAKQP8y8In2tlm/VolMrYDQSAgNB4b4BtNJwUaOINZ/t4e0Ek1sAs5F556vAdFon2i0b9In3I8fbkvYMeN5wra79jsKOtqIhtXlRcMbWiCK70cebd1MwQzN8AmYcba3+68gnxR0Rqv4umGZ1vsz6LeJ+m3TNn1OOMPPlU2qdBnibAPg+DPLwePep1qtNfuOlNiOqVTocubHNVOwYvAYCeB/Xp2Ovv5tY0LhNSzD+OKBOTMph0D/Zv0xp5thyMlmtbl4Eal1aOT6E/WVIEepesSqT7EqIpofkWCffFX855s55ikpgRERIyiiBWT/tZMTFab/rQ3Ckd5/k+MYQTWrJ+MAgmBkIo0TO6jJ6eb137g+KdjIEcT6bzCT/KKJTeEZgr6QqC8g6guI+nyjPnOBpOjziPo84n64RH0uUZ9D9J9D1GcT9dkUfRRVJLPMSGfCfIKcuS004V6CnPkp2gTy1OR0fZ4RhUyEpyan6zM/MzWs1/gU1kwkSPAioJ02obFRMlF+CHLm83eiPBLkKJlDLNoUq5ZE85c0b/TfQiXpo+yq+NLYUdRo1k6JwSUxWJem2J+yFgOFFWdlNoarZv2UnF4ak9+sj9Kz7n9EboTvrpMxtzBPQYG6/U/FnTGF+h2Y01W7kaQIyt9WoWUQRWNE1Rh1Gs9yRUidJKSaHVA1BlSNPlWjT9XoUTV6VI0uVaNL1ehQNTpUjTY56kkaScpoplEh25yE2QQ4ooAthwa2zA/1JsKAIOcR6634Lj0NHBFA1Nz4irE5NUlgy/gI31w8dLA1UY4IchERDcyN3QlzTSaBLSL8oaUj+fwhKSMuoRWkuK7/1UKaRsrm9j/3SNNICb9OI0FS/OIqVSNBUvx0KlUjQbIVpBSZ/rd7aRpJnHNBLJitIKlQ97/eawAlD+KbKc0vX/8fi1xTjdteAAA=

**Comment by yairm210** [comment]
Thanks!
You're absolutely correct!
Fixed, will enter next version!
