### ISSUE TITLE
Interlink with and within civilopedia

### ISSUE THREAD

**Issue by anton-koerbchen** [yairm210/Unciv#3369]
Please add interlinks with civilopedia in various places, also within its articles. E.g.:

* From technology tree: link to articles on the provided improvements, units, wonders for each technology.
* From the main UI, where it shows terrain type: link to the article on given terrain.
* From articles on terrain: list and link all the improvements that can be constructed on this terrain (regardless if already unlocked).
* From the articles on improvements: link to the technology providing them, list and link all terrains where this can be constructed.

And so on.

**Comment by b-1** [comment]
- From selected unit description for more info.
- From city menu on all elements: units, buildings, queue, recources. 

it's be a wonderful!

**Comment by SomeTroglodyte** [comment]
That's something I had on my list when I chickened out from contributing a year or two ago... Along with a context-sensitive F1 key or similar. Yair, if you want, I could dig in my pre-migration backups and try to adapt what I find. As I recall I had started on parameterizing the pedia code to enable opening to specific pages / entries in lists but had not done much on how to express linking hints in json data where hardcoding isn't obvious, like tutorials..

**Comment by SomeTroglodyte** [comment]
My WIP progress (the curious can probably view the code [here](https://github.com/SomeTroglodyte/Unciv/tree/LinkableCivilopedia1)):
* Positioning civilopedia to a 'target': done
* Code to access specific entries from world screen: kludge
    * I've hooked the F1 key, so it's desktop only (or droidos w/ bluetooth physical kbd)
    * Intention: test the other code
    * Links selected unit, selected city's construction or terrain entry with no such selection, that's all
    * Current bug: reveals construction in rival cities
    * No idea how to catch long-tap with libGdx as #3403 suggests
    * Ugliness: keeping intended link target in class-level vars
* Difficulty for intra-civilopedia linking: Entries are just text at the moment - one single widget.
    * libGdx afaik has no hyperlinking-capable predefined widgets of any kind.
    * Always linking a unit to its upgrade no matter where you tap the description: easy
    * Approach to allow each *line* to have a link target by splitting into a multitude of widgets: moderate to major. Data model would impact tons of source files as this text is generated by class
    * Allowing phrases within the flowing text to link: preliminary research indicates *way* past my 'pay grade'.

This is now a vehicle for me to test and document the best procedure for rebases when upstream develops past your base requiring non-trivial merges - so no PR until some other commits touching civilopedia, worldscreen or camerastagebase are in.

Also unsure whether the whole thing is desirable at all - so - constructive input welcome.

**Comment by yairm210** [comment]
I can't think of a way to have the links happen within the text.
What I would propose is that the list of links be **separate** from the text.
So each civilopedia entry, along with its text, can receive a list of links - each link is type + name.
That way we can build the list of links for each thing gradually, we can start small and expand with time.

**Comment by AdityaMH** [comment]
I think more better if add icon on left text every that item contain on civilopedia.
For example on research tree:

Wheel:
Unit unlocked: [iconChariotArcher] Chariot Archer
Building unlocked: [iconWaterMill] Water Mill ( +1 [iconProduction] Production, [iconFood] +2 Food; Must be on [iconRiver] River.)
Tile Improvement unlocked: [iconRoad] Road.

And all text with icon must be linked to civilopedia.

How about that?

**Comment by SomeTroglodyte** [comment]
Rest assured we're trying, and improving the Civilopedia has been on our proverbial plate for some time.

**Comment by yairm210** [comment]
Done!
