### ISSUE TITLE
Web browser client

### ISSUE THREAD

**Issue by ajgoda90** [yairm210/Unciv#3374]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to play this from a web browser, kind of like FreeCiv-web.

**Describe the solution you'd like**
A game client available via a web browser. Potentially hosted on a browser game hub like itch.io, and also possible for individuals to run their own web server to host it.

**Describe alternatives you've considered**
N/A

**Additional context**
Several months ago, I looked into Kotlin and libGDX support for web. Both have it, but I couldn't find a straightforward solution for both of them to be in web together. I did find people were working on it from the libGDX side of things though.  If it is supported now, it may still require a lot of work to implement in this code.

Other things that would eventually need to be addressed:
-Hosting/server
-Browser zoom and resizing
-Multiplayer support might be different
-Multiplayer anti-cheat(potentially server-side) since web browsers are much easier to tinker with than Android and desktop clients.

**Comment by yairm210** [comment]
I'm writing this off as 'highly improbable if not virtually impossible' - the amount of work this requires is basically like a rewrite of LibGDX's Html conversion, and way out of the scope of this project

**Comment by adbenitez** [comment]
this would be awesome, I have seen other projects like Pixel Dungeon made available on the browser: https://gnojus.github.io/pixel-dungeon-gdx/

**Comment by haimlm** [comment]
https://haimlm.github.io/unciv-web/game/
(was) virtually impossible :)

**Comment by adbenitez** [comment]
@haimlm man, you are a f*cking hero, the reason I wanted a web version is because with it + https://webxdc.org (sandboxed mini-(web)apps in chats) you can have multi-player in chats, end-to-end encrypted p2p inside groups without any central server, now with a web version it is a matter of packaging as mini-app and figuring out the multi-player mode, thanks a lot!
