### ISSUE TITLE
Wayfinding and embarking uniques not working when applied by building - units getting stuck in ocean

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#3384]
The "Can embark and move over Coasts and Oceans immediately" and "Units pay only 1 movement point to embark and disembark" uniques are not functioning when given by a building instead of by the Nations JSON.

I made a mod nation that (in theory) has the ability to unlock extra uniques by building new national wonders at the capital. Sometimes this works just fine (one of the buildings gives all units a promotion after the right wonder is built, and every unit built after that is getting the new promotion) but the uniques I highlighted aren't working. Sometimes they function (I have had turns when a unit lets me go two units into the sea, or out into the open ocean) but then they stop working the next turn. In the zip file, I have included a saved game that features a unit stuck in the water. The unique let it get onto the ocean, but without unlocking the right tech, it can't move on the ocean, and it's too far from the coast to go back, so it's stuck. (see screenshot)

[Wakanda_bug.zip](https://github.com/yairm210/Unciv/files/5626320/Wakanda_bug.zip)

[Screenshot (34)](https://user-images.githubusercontent.com/58439827/100815291-c8e49500-3400-11eb-8a1b-fa751478dcbf.png)

**Comment by SpacedOutChicken** [comment]
Just noticed the change in labels. Would I be right to conclude that the uniques I'm trying to use aren't supposed to work with buildings at all?

I've noticed that many of the national uniques can be applied by either the Nations JSON or by a building. I assumed that this applied to all of them. If my assumption is wrong, then the actual "bug" I'm seeing isn't that Wayfinding isn't consistently kicking in; in my case, the bug is that it's kicking in at all. Is that right?

**Comment by yairm210** [comment]
There's a lot of stuff that is configured a certain way to work on the base game, and when you try to change it on new ways to will Pro as part of a mod, doesn't work anymore

This isn't a bug in the actual game, it's an incompatibility with the way your trying to modify it ;)
