### ISSUE TITLE
Discourage ai to attack with embarked units.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#339]
I have figured out 2 ways to do it:

1. "attackable units" check can take a parameter, allowing to control if land targets are included when attacker is on water. That means only player units can attack from water.
2. Before "tryAttackNearbyEnemy()", add a "tryLandToAttackPosition()" to check if the embarked unit can land to a position where it can attack enemy next turn.

What's your suggestion?

**Comment by yairm210** [comment]
The second sounds good to me
