### ISSUE TITLE
Unhappiness cap seems not working.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#340]
<img width="851" alt="screen shot 2018-12-12 at 10 39 30 am" src="https://user-images.githubusercontent.com/6846049/49843487-61d80b00-fdfa-11e8-8bbf-958a608aeb17.png">

Do you mean max(0.02f * combatant.getCivilization().happiness,-0.9f) here? Sorry didn't test it because it painful to generate -50 happiness...

**Comment by yairm210** [comment]
Absolutely not!!!!
'Max' would mean that even if you had 1 unhappiness you'd get a 90% penalty!

**Comment by yairm210** [comment]
Done
