### ISSUE TITLE
highlight throughout the river/road if select the river/road tile

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3402]
rivers are not expressive enough. but if it always is, it will bother. so highlight it when it is needed to player. 

roads  may be unfinished. highlight will help to see it.

**Comment by yairm210** [comment]
I have no idea what you mean by 'rivers are not expressive enough', and in general what your expectations are?

**Comment by b-1** [comment]
![screenshot](https://drive.google.com/file/d/1Mzi5OdsXp6kr5cKzfY85nOHvCyJ-YYuq)
something like this. make a transparent blue area for river near the SELECTED tile. at least add an info about river in description of tile to plan city building.

**Comment by b-1** [comment]
![screenshot](https://drive.google.com/file/d/1Mzi5OdsXp6kr5cKzfY85nOHvCyJ-YYuq/view?usp=drivesdk)
something like this. make a transparent blue area for river near the SELECTED tile. at least add an info about river in description of tile to plan city building

**Comment by yairm210** [comment]
I can definitely add it to the tile description, but I see no reason to highlight the entire river, I don't think that's helpful

**Comment by b-1** [comment]
it would be useful for planning to put several cities on the same river. so that every city has a water mill and hydroelectric power station. it will be a shame if it was possible to accommodate one more city, but miscalculated. also near the mountains it will be clear where the river is. the function can be made optional:)

**Comment by b-1** [comment]
the highlighted road will help you see where exactly it was unfinished. under some improvements the road is poorly visible. unfinished and unconnected roads are not displayed at all. you can highlight the unfinished one with a separate color. or you can just make a lens that shows unfinished tile improvements for example in red.

**Comment by b-1** [comment]
one more about the river. 

if the city border goes along the river located in the south (S, SE and SW), then you need to zoom the camera as close as possible to understand if there is a river there, due to the large number of overlapping lines. especially when playing for Greece:D

**Comment by b-1** [comment]
also, during military operations and reconnaissance, the river can interfere. convenient if you can immediately see where the end (source) of the river is. fast units can run around it without losing action points.

**Comment by yairm210** [comment]
I actually think that this is not a good feature.
