### ISSUE TITLE
Wrong text reference for maintenance-reducing unique in CivInfoStats.kt

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#3413]
On line 84, it references the unique "Maintenance on roads & railroads reduced by 33%, +2 gold from all trade routes". You probably recognize as the long text from one of the effects you recently removed. It should instead say "Maintenance on roads & railroads reduced by 33%".

P.S. Sorry for submitting all of these as issues. I wanted to correct the code and do a pull request, but I am so damn bad at git and Github.

**Comment by 9kgsofrice** [comment]
https://github.com/yairm210/Unciv/pull/3414 :)

**Comment by yairm210** [comment]
It's fine!
It's great that there's someone else going over these, since the surface area of the game is so huge and usually the only eyeballs on it are mine when I have a specific goal in mind 😉
