### ISSUE TITLE
Hard to bombard enemy unit right above the city

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#3420]
[Please check this first.](https://youtu.be/PXSgU27joTA)

I tried to bombard enemy knight right above Honolulu, but there was a frigate in the city. When I select Honolulu, frigate icon blocks the knight. Practically I CAN bombard it, but i have to touch another empty tile first. Screen expansion doesn't help cuz all icons are expanded at the same rate. The problem would be similar if I wanted to bombard enemy unit near a city which has many air units in it.

Is it appropriate to give different expanding rate between the whole map and unit icon? Or is it okay to make city icon popped like other unit icons when a city is selected? Or it might help to make all unit icons unpopped when a city is selected twice.

Unciv 3.11.18-patch1

savefile: [India -  374 turns; attention Honolulu.zip](https://github.com/yairm210/Unciv/files/5702453/India.-.374.turns.attention.Honolulu.zip)

Used mods:
Civ5ExpansionMod from ingame
LynxRoTile tileset from unciv discord

**Comment by yairm210** [comment]
Just select the bombardable enemy unit. The city will be auto-selected, and you'll be able to bombard immediately.
