### ISSUE TITLE
upgrade automated workers

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3430]
add three more separately (!) options: 

- automated workers don't remove forest (for Sawmill improvement)
- automated workers don't remove jungle (for University benefit and Brazil unique improvement)
- automated workers don't remove marsh (for Polder benefit)

some buildings and improvements have a benefit from that terrains. also these types of terrain provide a TACTICAL ANDANTAGE in defense.

**Comment by ravignir** [comment]
There is 
"Automated Workers do not remove terrain features" in civ5, I mentioned it in my earlier suggestion #3050 , when i suggested "Automated workers do not replace improvements". Apparently I am not the only one who thinks it is actually useful option to have.

**Comment by b-1** [comment]
I think you need to devote a whole section to workers in the settings in order to improve the game. some do not need swamps at all, some do not farm science in the jungles, and some do not pursue production from sawmills. and someone has not yet understood how best and wants to rely in everything on the opinion of a professional AI.

For example, I don't like it when workers touch the jungle, and let them replace the rest.

**Comment by yairm210** [comment]
Merge this as a comment into #3050, we don't need two issues or the same thing
