### ISSUE TITLE
cities that have not grown together

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3432]
In the original game, a city could process tiles from a neighboring city in the third radius if their borders were fused only.

is it bug or feature?

**Comment by yairm210** [comment]
Feature, I see no reason to differentiate. If it's your territory, it's yours

**Comment by b-1** [comment]
looks like the specialists of one city go to work in a neighboring city) it's a good feature, actually. 

but perhaps the authors thus encouraged to buy cells between their own cities, which adds complexity to the game and you need to make it an option.
