### ISSUE TITLE
let civilopedia explains the mechanics of the game

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3433]
is it possible to add to the game real formulas for calculating damage, penalties and bonuses from terrain changes, the rule for adding funds from roads (how long you need to wait for them to pay off and what it depends on), etc?

**Comment by yairm210** [comment]
No.
Civilopedia already displays terrain bonuses. the damage calculation formulas hardly interest anyone and will only complicate issues (if anyone is interested they can look at the code or google it)
I'll add the road costs to the road improvements so it'll be visible when building

**Comment by b-1** [comment]
thanks! what about the ROI? first, let's say there will be a profit of -6 per turn from one road. but over time there will be free pluses. the player needs to know how much the economy will suffer. let the game explain which buildings are in the cities and which luxury ones give you money or whatever.

**Comment by yairm210** [comment]
Everything except for the money from future trade routes is already shown in-game
In the city screen, clock the 'show drilldown' button
