### ISSUE TITLE
path of movement

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3434]
let the trajectory of the movement of units be displayed without taking into account obstacles in the fog of war, for example, using a line with marks of the number of moves. this would be useful not so much for visualization as for determining the shortest path and throughput in units in mountainous terrain

**Comment by yairm210** [comment]
The unit movement already calculates the shortest path through the map, I'm not sure what this will add

**Comment by b-1** [comment]
it is not always clear that it will be faster in a straight line along the hills or around the plains. and the path may lie close to the enemy. you don't always want to manually choose a safe path. also, if there are two mountains, then all units will not go into the gorge. someone needs to go around. but everyone can rush through the gorge, which slows down the attack, and the game does not show this. and it is also visually beautiful) 

mark each move, perhaps a large pile, but the line through the tiles, I do not think that will greatly increase the size of the application.

**Comment by b-1** [comment]
perhaps the player will be satisfied with only half of the drawn path, and he will shorten it, and then he will manually guide the unit.

**Comment by krushia** [comment]
I believe what you're asking for is implemented in The Battle for Wesnoth. It shows the predicted movement path along with where the unit will be each turn.

**Comment by b-1** [comment]
https://drive.google.com/file/d/1NJH4dNZRYoJm6DFin20R0lowx2GGbz2K/view?usp=drivesdk

at the beginning of the turn, I ordered both units to move automatically to the highlighted cell. of course, the shortest path will be through the gorge. the game does not inform in any way that both units should stand on the same cell, and will put the one whom it decides to put there, while the second, seeing the blocked path, will automatically go around.

I think the player should decide for himself who (warrior or scout) he wants to be first, and who should leave some of the movement points, and go second, following the first. or it really is better for someone to go around. it's hard to constantly calculate it in your head. especially during hostilities.

this is a Tactical Feature, not a visual one. it would be visual if I proposed to make each move on the path of a different color as in the Total War series:)

**Comment by b-1** [comment]
I think Vanilla Civilization has this "visual" also for some strategic reason :)

**Comment by b-1** [comment]
to save resources, just one line without numbers on it is quite enough. it will have to be calculated manually, but that’s a strategy to think about such little things.

but sometimes you may not notice that somewhere there is rough terrain or there is no road. in this case, the counter of moves on the trajectory will help. you will see that the unit takes longer than usual, and you will understand that someone, for example, destroyed the road there. very comfortably.

**Comment by SomeTroglodyte** [comment]
Could also serve as debug tool to find out why the ETA is sometimes wrong (I lately had a settler displaying 2 turns from embarked 2 tiles north of an island 3 tiles high to a nice place on the south coast over virgin territory - impossible. 3 was doable).
