### ISSUE TITLE
unit control zone

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3444]
turn 57: https://drive.google.com/file/d/1N2XW_bF-2izCQu9ebVGMqUqJvH7RwANS/view?usp=drivesdk
turn 58: https://drive.google.com/file/d/1NDKY6P_8NH3lxKtiLbrftsAjAbBICAau/view?usp=drivesdk

does the scout have a zone of control? declared war on Germany so that their unit would move more slowly, placing a scout next to them, but this did not become a hindrance for AI.

**Comment by ravignir** [comment]
Sadly, there is no ZoC in unciv.

**Comment by yairm210** [comment]
If this isn't in #663 you can add it to there
