### ISSUE TITLE
unfinished roads and improvements are incompatible

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3463]
if you start building an improvement and leave the tile, then an unfinished improvement will remain on the tile, which can be completed later. its OK. the same with the road. the decision to build another improvement on the cell replaces the previous unfinished one at any stage. that's OK too. but the decision to provide the construction of improvements and to urgently start building roads should not remove the unfinished improvement! there must be both an unfinished road and an unfinished improvement on the tile.

**Comment by yairm210** [comment]
I disagree, there can only be one thing under construction at any given time.

**Comment by b-1** [comment]
actually original mechanic of Civ5 allows you to leave an unfinished road on that tile with an unfinished improvement at the same time.

**Comment by b-1** [comment]
moreover, it allows you to leave a pillaged improvement and / or a pillaged road on the same tile.

I suggest that when repairing, also show a pop-up window with a choice of what to repair first, as I suggested in #3479 for pillaging.
