### ISSUE TITLE
fast building on hills

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3464]
to start building on a hill, you must first spend all movement points to climb it. and only on the next turn give the order to build. which takes one turn more than the improvement requires, which is logical. but if a worker climbs a hill with an unfinished improvement, then simultaneously with the movement, he will advance the construction by one turn. I think this is a bug.

Yes, according to the mechanics of the game, choosing an improvement does not take action points, and you just need to be at the end of the turn on a tile with an unfinished improvement. so you can only spend 1 MP and complete the improvement on the plain. BUT if we draw an analogy with a long-range military unit, then it loses the opportunity to fire if it spends all its movement points. this means that the builder should also be deprived of the opportunity to build in the same turn, when he moved and spent all the MP.

in the current assembly, you can improve the farthest hills from the city before those that are closer, if you leave unfinished improvements along the path of the worker. which gives some advantages if you know about the bug.

**Comment by krushia** [comment]
I kinda assumed the opposite... that you should be able to pick the improvement to be built even with no movement points remaining. Maybe allow the choice but only increment the build progress if the worker ended the turn with greater than 0 movement points?

**Comment by b-1** [comment]
in vanilla Civilization it works as I described. I think this is the rule for all units of that mechanic. your proposal sounds like a great feature! allow the player to do more than the original for convenience (choose and change the construction of improvements in any of the turns), but not going against the mechanics.
