### ISSUE TITLE
unknown map location

### ISSUE THREAD

**Issue by jaxankey** [yairm210/Unciv#3467]
This is minor, but it would be nice not to know where the edge of the world is until it is explored. The minimap could dynamically zoom around the explored region.

**Comment by ravignir** [comment]
would be even nicer if there was no edge at all (except on the top/bottom) :D

**Comment by jaxankey** [comment]
Submitted that one as well ;)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by b-1** [comment]
I think there are two separate options to do. the first is not to show the player the edges of the map until he finds them (optional, if the player wishes at the beginning of the match). the second is the type of map loop:
- not looped;
- left-right loop only (for square cards);
- looped on all sides (for square and hexagonal maps).

**Comment by jaxankey** [comment]
Careful about looping vertically. To simulate an actual globe one would need to reverse the order of the tiles every other loop, which could be confusing. Civ 5 does east west looping and just has a polar ice cap to skip the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SomeTroglodyte** [comment]
Would you please stop advertising closed source products?

**Comment by yairm210** [comment]
Okay this is now done :)
