### ISSUE TITLE
endless start hotseat session

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3474]
after the start of the hotseat session, the game first waits for a tap anywhere (this is a bug), then only displays "ready?" the screen, which is also closed with a tap (this is OK).

**Comment by yairm210** [comment]
You're wrong, it doesn't require 2 clicks, it just takes it a second to get started the first time.

**Comment by b-1** [comment]
nope. it needs a 2 taps to start hotseat (in solo all is OK). I can send a screen recording as proof, but it will not help:(

**Comment by krushia** [comment]
It might help...

**Comment by krushia** [comment]
Actually I can confirm this on 3.12.4

It wasn't happening on the prior version I had installed.

**Comment by krushia** [comment]
It might be the same thing that keeps the victory screen from showing until after a click.

**Comment by b-1** [comment]
3.12.5. it still takes two clicks:(
