### ISSUE TITLE
settler capturing

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3475]
after capturing a settler, the warrior does not stand on the tile with the settler and remains on the adjacent tile from the captured unit and loses all MP.

**Comment by yairm210** [comment]
Can you add the game data of a game where this happened?

**Comment by b-1** [comment]
it always happens when you capture a settler. try to start any hotseat session and move one nation towards another. by taking a settler, he turns into a worker in his place, and the warrior remains in his place. 

if you can't see it, I can attach the save.
