### ISSUE TITLE
perfect crime

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3476]
after capturing a settler or worker, they can move in the same turn, which was not in Civ5.

**Comment by krushia** [comment]
It requires that the previous owner left unused movement points I think.

**Comment by ravignir** [comment]
they can't move in civ5 even if they have full MP before being captured.

**Comment by krushia** [comment]
Does this apply to great people too?

**Comment by ravignir** [comment]
You can't capture Great People in civ5 (except Great Prophet).
