### ISSUE TITLE
promotion unit list in the form of a tree

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3478]
this is to make it convenient to understand which promotions you need to choose in order to get to the desired one in the minimum number of levels. and it is faster than looking for the name of the required promo in the list.

I propose to make one common tree for all types of units, similar to a technology tree. gray out the inaccessible promotions for the unit. and in the promotion menu make the button "show unavailable promotions", hiding and showing them. promotions of other types of units are needed in order to understand which promotions can be obtained now, and which ones will become available / disappear after the unit is upgraded (!).

**Comment by b-1** [comment]
oh! there is the same mod for Civ5: 

https://forums.civfanatics.com/attachments/upload_2018-1-28_10-39-3-png.486556/

**Comment by yairm210** [comment]
I don't see this happening... if I had that sort of time I'd use it for something simpler
