### ISSUE TITLE
pillage of roads

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3479]
when you click on the "pillage" button, let the game suggest what to pillage: an improvement or a road, and writes how much HP the unit will receive.

**Comment by krushia** [comment]
How does pillaging a road make any sense? There is nothing there to take.

**Comment by b-1** [comment]
sense. this removes the bonus to the arrival speed of the opponent's support troops. this possibility is in Tsiv5.

HP. let the game offer two options:
- "pillage improvements +10HP";
- "pillage road +0HP".
and the player will choose what to do and in what order.

**Comment by yairm210** [comment]
If this is a Civ V feature add a comment to #663

**Comment by b-1** [comment]
vanilla is able to pillage not only improvements, but also roads, and after that leaves unfinished improvements. UnCiv does not know how to pillage roads as well as can leave improvements unfinished (and still does not know how to leave unfinished/pillaged a road and an improvement on one tile at the same time #3463).

but Civ5 does not offer to choose what to pillage/repair in the first place. and I propose to make the dialog box as feature in UnCiv.
