### ISSUE TITLE
ChineseFont download error

### ISSUE THREAD

**Issue by GaoSiming988** [yairm210/UnCiv#348]
hi @yairm210 , App crashed if chinese Font be downloaded, i have try it on my Androidphone(Oneplus5T, Android8.1) and Bluestacks(version4), and even Genymotion(Android 4.1 , Android7 and Android 7.1)

**Comment by yairm210** [comment]
That's VERY strange
I saw the crashes on Google play so I'm at least glad it's you so we can understand what's happening there

**Comment by yairm210** [comment]
I found the problem, and it is that I am an idiot.
I tell the game to check if the file exists in place A and if not download it to place A, but then I tell it to TAKE the font from place B. Where of course it doesn't exist.
Hope to fix this today and it'll enter 2.10.16, part of the teething process

Thank you for your patience :h

**Comment by GaoSiming988** [comment]
super, that is very kind of u :)

**Comment by yairm210** [comment]
You should be able to download 2.10.16 by now, can you check if Chinese now works?

**Comment by yairm210** [comment]
?

**Comment by yairm210** [comment]
Awesome, thanks :)
