### ISSUE TITLE
general's / admiral's visible area

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3482]
for convenience, when selecting a general / admiral, let the game draw his area of ​​action, or highlight those units that it affects.

**Comment by CIZUK** [comment]
What are these 'admirals' you're talking about?

**Comment by b-1** [comment]
a Great Person specialized in naval warfare. the Great Admiral is used similarly to the Great General - as a combat booster, but in sea warfare.
https://civilization.fandom.com/wiki/Great_Admiral_(Civ5)

**Comment by CIZUK** [comment]
Ah, so they're not in Unciv yet?

**Comment by yairm210** [comment]
As often happens, it's the visual part of this which is complicated.
Units already have the 'tiles they can move to' signified by a blue circle, ow would you show the 'affected tiles' as well?

**Comment by b-1** [comment]
https://drive.google.com/file/d/1NgLaAM7AcccQDpJQICPGKY7Tb5CNQXxl/view?usp=drivesdk

blue circles are not displayed on all tiles up to the second radius. hills, civilians, enemy units and lack of movement points prevent the general from moving two tiles. therefore the available marked cells only show the available moves.

I propose to highlight the area on which the general's ability "+ 15% combat strength" is applied. besides the fact that it does not take into account the remaining MP, it also does not affect water tiles (for the admiral, on the contrary, it does not affect land tiles) and affect mountains (for Carthage civilization). AND/OR highlight units under the effect.

**Comment by yairm210** [comment]
I really don't see a way - visually - that would make this look good.
