### ISSUE TITLE
ban list for "random nation" option

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3484]
make it so that when you click on a civilization in the list (which I would like to see as a list of icons as soon as possible), they are first selected, and when clicked again, they turn off? and when choosing an icon with a question mark (random nation), the list of disabled civilizations was taken into account.

**Comment by yairm210** [comment]
I can't see this working
How would this work, from a visual perspective? How would the screen look?

**Comment by b-1** [comment]
https://drive.google.com/file/d/1NZBVll8jdax__52GI-N6uUnLY7cJ2sFM/view?usp=drivesdk

1. the close button is not in the place where everyone is used to.
2. please do not remove the selected nation from the general list. due to the fact that the selected nation is under the pop-up window, you first scroll through the entire list several times before realizing that the desired nation has already been selected, and not unrealized. let the previously selected nation be better outlined in the second nation color.
3. better use the select button. an interesting design solution, but it is not obvious that you need to click on the large rectangle on the right after clicking on the small one on the left.
4. there should be a checkbox next to each nation. feature that I want to offer. if the checkbox is not checked, the nation is not added to the list from which the randomizer selects. sometimes you don’t want to think about choosing a nation when playing with friends, but you also don’t want someone to get stronger civilizations (which are usually banned in a multiplayer game in Civ5).
5. add a description of what the "random nation" does ("select one random civilization from the marked").
6. add to the header what this list and check marks mean. you can do: "select a nation | allow in random", you can do it inverted: "select a nation | ban" (if you think that the majority of target audiences understand what a ban is. I don't think so).

**Comment by b-1** [comment]
checkboxes can be made not in the form of checkboxes, but for example in the form of squares as high as a field in the list of civilizations, with a "v" pictogram that turns gray when pressed.

**Comment by yairm210** [comment]
Denied

**Comment by givehub99** [comment]
> 
> 
> make it so that when you click on a civilization in the list (which I would like to see as a list of icons as soon as possible), they are first selected, and when clicked again, they turn off? and when choosing an icon with a question mark (random nation), the list of disabled civilizations was taken into account.

my recommendation is just to make a mod that removes those nations from the game. if you need help with that, check with the discord server.
