### ISSUE TITLE
Viewing City State's stats

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3488]
We need some way of viewing info about City States, such as force, tech and culture.

**Comment by CIZUK** [comment]
Also, they should appear on the diplomacy screen

**Comment by yairm210** [comment]
They do appear in the diplomacy screen - and no, we don't need a way of viewing their information.

**Comment by CIZUK** [comment]
Sorry, I meant this diplomacy screen
![Screenshot_20201231-182949_UnCiv](https://user-images.githubusercontent.com/73200638/103421839-53eab380-4b96-11eb-9fb0-7104c0ebcd3d.jpg)
