### ISSUE TITLE
I think I'm just stupid, but let's go, yeah, scenarios just don't work for me

### ISSUE THREAD

**Issue by Bielbabel** [yairm210/Unciv#3492]
**Describe the bug**
I put nations to spawn in specific places,they just don't,they never do and just this tiles appear

![Screenshot_20210101-095944](https://user-images.githubusercontent.com/76627990/103439062-7de4ba00-4c18-11eb-9408-4ef0303c781e.png)
![Screenshot_20210101-100030](https://user-images.githubusercontent.com/76627990/103439064-82a96e00-4c18-11eb-8e62-403816db41f8.png)

**To Reproduce**
1. Create scenario
2. Place where the nations appear
3. Play it

If game data is required, please add from menu, save game, copy to clipboard, paste here

H4sIAAAAAAAAAL2dX4/bRpbFv4o/gAmo+Ffqt2QGzmSQIMF4BnlY7INia2LNyJIhqbMbBP7u0xJJp8U6p/gj1bsIkASN0qlise6te07duvz94/rTj+vj+uPmvDmeHn4/bTbvH0K9WFWLalWFqqo/vz5vd5vvtqfzw3/9/vP6tPn75nhcb/cPf96cNsfz6w/r09eH8/nw8bvNP89/2/66OT6cj4+bP/7+7G/n9qdvNuvz43Hz8GZ3OLx/9Wn39KfT59dJ8L9tf/nwHP3T4bQ9bw/7h9//9yELr397+tfn6fDPUS4g4fPsYUwdwV+2u93Nz8WvD8fN6TwyIjDrN085eYxze7pMx9P4D4/Hd5uHPx3Wu/FXkOWXF5k/+903h9378d9dfpabVxcvlOf4X+0eP273jx/TL6ddHOM9DMB/+vA0xfcsStHnj9cf+gU5+v5bU4FzFTUc6/7mrURL7a+P+192m5dd0HfNeHKBD1cYNNBbzKTfyuXLiBZfVlzaFcN23xzXp9NuvX9/0/jStohG+v36ePpADTDqqXvrwwmJ2lmTIy0DQryC3WdTUSffHx7356f/udOqsAciDbulMdUTZnliF7tZJv8fVmPf+1xjL7QZ/l/tYAWzz4JuP0W3/cyOEp4wygtGyXzBpW357EW//bR9tzkhr2ycUNSxcA3FtVfqbAhiPniOb4+HPXU9ZCRBjTgK0LLnQ/hm8xG4mvImBHpaamDY2mHG76P1l3/g/3mzOU6JICNvg5YwDbW06TijIA3hmrcvHG3J5VQH8xTYns7CQse9Rqlm0j3TMG79YbvjZrz9+Ol4+HXzcbM/P3y1f7d9+u+r4+PQyEq1/6bG83zx/eO43m+jMNr8urr8uhqdoEuzqJXwDu1oopbeJSLQYgJoQUFzCWoMcnyGWg9H8ILCU8HVWKdkWNjvZsTxdt4JBZv5wCf+5XA8bQD3L6T/03ug2L+hl9WOQT1HqXxibCDDFsIZkcVRqd4Ulhz/l+h5CBnNp4OEXrCa4KCqCYypGkQXf1qfz5EjTfUz98f15cc1G+Slbc1WXmqoUW/S60atrNetx4zNe+HxobQ++HkXbz9sNp+wS7755eMv6yObqFxOlHHSpF3rpknLMBj1lZkBrz2OrVbPD+vTFgqjT35k4qi6x6abHdsvckgttGDiok/X8Hnc9Pa8Pp63+1++O7xbX3786uv1z7/tDvvYwYNtRIZ+0hKJOtS676lKAfQ7N+Y3wbnVXDBLeccYQoa5wj/V7VY9OWJOjQZu/dErqodU7beYhUsksWPWr6UE9tX5sBsq7P7NlGNu23UMSVjNwteaEYGsubRr2OSLpXD5eUO2tPq+fmrVj7bXSy8jsswEW6lUxynqBhuXV9wZEoPpu9DzO8EOi3ZEd4whH87+T9s9cCf5YComEd4g59xstc2t0wK7/9iau8UkylW36Ud7xP1KeRZg0JQPow6qn2Utd77vMFiLnTpCJQFJCUU9KcIYyhaffCHXMx541Jin1oinAp8IbTqGHsQ+b7e7f9/jHZoJQYccDIj+muG7e/N4vMf7N4PoQrsmMw5xmIYnPlr4ImpoJkQNjYoaHOYtIVnvohDGBAI07m2kA1RRw/LScjlnmxRoF7AlXEPLuyKiqBcbEZGWNUWsJKIkP2AeyuHci0QTfiBfsk4L+Qg+YIFN29AkfqmU8eRs9GHC6MMVco43BC+ZjDYZOaFYQ+wskyKBpBrE0zwiVecF4hOirWTF1GhIHlRlo4zRydgkOqqGx0nf7t9t9qfxM2kpCet4Zi53z2qu+ctdkkVSjYqk1P6AdqTRqdTmvoSDaLe88cBvOdBguHzb9gAPBpavacpT/HaXE4Ig3zuJhJaMUiy1vUJ1aDkMjd5so0kwUUfk4xw8CYqWAyKr3rxdWFTKWF0ar9hcyVOqC8AKr/fVqFWZiYBDVB03bccsorujn3r4gG+fuDZUWdEMVvpdpWIbtLlWagAp6cuNluSzlRM6K4Yz+vV6//QPy74yWVVopvPpMz2Md+BCMrElGWWQvaTGSJJYuDuIQtGpy+K+VNFoF3fHZ6RhjmLkVJpm/gJxcgEFwzk5mEQvLIc7n0gS1Pzx+Y/MfQAXs6JDyyi/QAmZOmiFgYmT5oiSGKlRfAoyKXiZTfAmmfnbXw/H3+C+e9cpIvQx8cKAbn5FI+aVjJg9aJ7WNFIREXkjKxkyTzkQXUlF23RFczdX0qgMKEzOa0FJet7q9b05NqvWCc4Nw1b8dEusWLkNmF6ATrSaoBNlYXFd3wuy9V+aopad0ZCmqxZzdvy71D1x6XB55wAa/KhN11MymwB6ubrrNblrmrA/Hmwq8Wzq3I7FBdVwFiZoC2ViQMOQgi3Uop/Hma+/wD3lU3qSmbT3rNJwV+8hWrmzD0rmDwNOtGYymvHcwR3sZcMbDU+tbXfy/fx336+PP7v7llHs7hgEuz2QtZkZSEvWmZ+zGYJMJnURO9LMq6mauVSXdMKUdsKESPTntUmNxoXphApM0VyzobZ7z6GnDo51SALpgAw8gDkvRg/SzUnZQo6Nqi59APVyyVZXQJCN0HYMDzhcOOev1Iq+CGm4tixHgpwpkXnbdTkn60I+yxWPMpC289ijsCjt+uv7eEk7ACLcX1tSAb6Fha2vjafxCXLYdW05X7BcyH3+7f7wP4OGbegz7qSuDeN2CZsHmAuJmSKhaASrFnaGz9H2vUz2PLaRL/HENayfl5JsGzywmk6AJ5J1907mEbqqG0Ay3XPCiUc1YTT2ktDNeIy8KH5c4mkv+l5mDrMY2gHVJ/Po8fDBYH7nzAbzzHjfZrM7fD5KsxW4zu7BOkKQJFnfFo08uqNLriGpRKES8CadmWQyO8wdboA02pILiI4g3Vya2+6eHn4mWZuYF97eO5xaMUrfIHHnIfflQXWprLNPZGTKrNxIlzJMThCxm2ou8X2G79b/3gjGRaneSjGJGLOnMO4J95f5Wu9+OuzfP62AH3bvX71Zb88f/vmoYjISaAFyE8ZWs4lV2+JXyV1U9TbhkCfISkDS0+vqQglYunRCGEoKTP4N8t5+spNyTpSpg+uRQ97kMGZzsOHNXBPGJDuPOZzKUUu8V8zLurTZ9PVn/ZBjumOyS5iRnnhEml4TOoF25HKqW7xxHPH3x/3741oa9GKgGoyTxTYuzEe0uuiH19+FyNItGx2Xd9qHpY6+8+B3ikH090n6Sg+x8bMtNazdf+Om8Y7XEdEXL9LYyP494YSVFiEPrye8Q5vql3ovLx48Vni+yinz5S/F3pj2hLoXHVMlQy2mLO4cw2oPk7q3SpeCPu4jBkdc2V1L0nFlKKoETdVp73m0idxZi8Cc4qpg4l5PFGWxwkK+MlvVEVuUDSnvZjkSO35TW91k9sSU3N3W1XwcFX3h+0CN5MHm7iThy/q2grkSELUzhDPiJQJPZ6ap8hYu/qCHWaJzfWjmgsib47op6d2q51S55dsYEZ61UcI4obSxZKe6iHGis2nRiugMhL2yPLFHHK0Zl3gccMIfdIWjeBkEWffP7c66mqCejPpF+HfXJ7xDHUxe+ZSDS53cnujv9jKwyLT2qwBcR5WSsUdEVyH67Ty1x1qOGfFYQyojA7WIUUvJjNtAtpjIjK8/C+PFCmSXedSlEWHMFET+IEH5i9tojdFsmK0vu11E3WIrFXgtD7/rWmPHw8mkrYYvVSqtPu12bg2KpXyrlqYnVFFEyNF+Uk95onioNe6omr9g4m4r3G1pnm8qgaYSdexn5P7sCDRZHbleHebc4vrnV28e/7WNeTVNgxpbjhGLnmchuJeB+ZKbU1+kgZfL0JogO+lDX8rR47CmP4xPKt9xuNanfY/i6/zuGFDfUHV0mDTU5VZc0ut4BFTLeIx/EaLmIaGjuayQqeG+hKBHl+hVca0f3m3WIv2JcOvV8EBMVOwU8PIilSXBkeELRJ27qaObmHUpQHqo2bPGdMqN4snyAyfxkMkHFKgHll8ocF6sGD6YPJcSA5bMeJIDhVXMg6x5q+ano8bzxxRkfTzJl3TFPUGRZbH95JQAityVi55JivXdZzN2fIirb2UYVFL4SdetUtaJiw2EAtNcvQe6YZLdMhSe2cJbK6FPHWTMlRzNmiMeyfraaDpa9XHv15g5apdg5gCzkJhO8wnlRIWi9dQEP/T4s8yv5d7w1wnuXd4SWFZG0nLvl8l36Uj4+CSuhn3yNNuOhLPKRHEzn58dv5IJJLF5wUmsp6yvRDlziGC/nFHehJSiZKWv7jxmffYzRGBH1b5FU1fjXBz9vnniOC8xeZpNPwzGlmSI3oBguWKLkR0M26GJJkA9r8YJfFJ1iFFNfoAhwvmoPuuoMPyWZdwu5hL0knZWDuVzWNC+r0j1h4Adl0pzPDm+b8QoqC6naortE9beV8ZPS6+GCz//3Y+b9XE3muK61PxbukFDkEGYrAt2GEYMDr37u3+QEMPE1j55FrJioESa003HgiHTi89mbSAP7unEfcBdUXZajggAorfBMKWxixhTf3vLvNkpn+YL+qMvCWTs3HXR+D9aJ79P881xs3m3iXtnu2VU8xXXIArDklrs+wpdl8Sa5X3/5BxCj2X6iii4OEMI+oaOQSRkXWdGaYNYjRmEoKnlcPtTGcpm/IjGmw3cQZLbHP1tQgg5hYOPM/vQnVulZyzRxT3Hwy2BGLn5EA/5Sh0im0qMMWprpoFhFtGoLyyOCRPVnInO6UPk/CFC9BA4Z6GVJmA134Q0MbsecKtFkLzAlZ45LTQQwGU0bSK+jn+3pPiNHnDcsqGINUWsJaII/CqNKLY/baiW1U+eVm20Ar+gk1BQRGOTmqQixKAR4xcQ0ItCYOyN9yoDe4a4YYxokhPMPMcNY0SjT5u1EDd0VB1s4HqjjwFNxTgjrN2Qf8lj4x5qeWxhnAJo18hozd0Cfp6jGGeXaadIgstsqcJVQ7CjENoQbFw1BlF2XTdH7Fz6I9KOXaNzcf0daQVJ04fNkauy90JxSgXZMdWpgXkW5EejVQ8jYaTCHtlwDBUcfpkUH6vIIUgGHxOi9htnUbR2X7+U38sPklhUkHoxLB7NEpM6/DLpZxKPMP8DFKGrsjfikYXByw9P2x7q9IIUW7O8xyNIZnSByChhpotoE/B87uaqNf8GqJk7UqzSfIVBdmPY5CK5plyftFineTakDnypfUQ6Mm8Pagb9FdeXfH8oZelL1u89HZEz+f7EEthjy5vGP+d+bRjqOftB4iWQtJuq7RjuoQLTqCBRu4QK8vy5ZV1Wl9/iv6mgtA8yHbmEtVUG6ukiYcATvsCjXkhME7SSd7gaLsfYnZkzLDTgJR1voxHjlg1FNBZplIzJW2mGLU8bnkA0dqe5JkIsKKI2MoFoDExzdoQYKKK2JyVkgEa0QySxZExj6YUMQuh0UocTMgif01dBnJBB6Jw+X3BKBjixyHSYY5SLWBsxXoA01N8YM5Jr1C7GW0otxKgVUbsYT3/Ywjh+cgSni+E6sYLsTaa2lLq17hQMoonoa8ROwKDJ1Fn6sqOClxnk5hju5uNCUJ7LphzB98pA8rBa9VEpwUQ8BVoqNP5FWFDqqAdSB2aqXReJCWb500F+Zcr2Ry9c1EPR41K9jJQ7sT0TW6iVFVpEYq9doY+ZXkEXFBF7dc38XocIPGmQ6WcWEfjwAHX0DhG0DHp78wSVZCLUchMWzKgv9Dx2KGxmAsoMX6p7pc7PXRdIhnTXldkaDbUM1XxH1AzZMaA5sBVqRkuxxj5IKwZzpVzctm66kCne7oGbqSe6vf4RDc7ods100b/UHXRLFe4Q5bBzKH70ugm9AAUmotdI3BPFIkmTNj1Xx2feOghdjzO3iwWersXw0eQIrbICDxjHlrTVVsAGtZQv3GoroKU2dKutgJY1RTR2rMkkQjSGa9QUgmhs0agpBNGYolFTCGKgiAEhIjA2NKzzZEzo6dUUEq3qrBqnphByqe8NOjWFsANdEcSpKeQiuj7LcWoKIWU6NDRqCtJnGqjPLGVEbNwnaKc/7GncPYnt9VeA3B5F7CVghSYohUYg6lppTjohqV76wrpTS0BDk+/v1BGiv+jcBaeFAOHTSBOOvoKGzLWTsKah8kojn8Eg5pOjmNDIWTf46H03cmUYRLQmG6qKyIKhFpEYjizDYhGJcTfMrXSIxAE1zPV1iMRJQvG8QwQtg94/FCfBe1LQn7qyjBrZt9yK/TCBuwq6HpvHnC1wNDLWsfNBvDzORw84xT3ok2GPiZq2bIys7SsdQ3phgzEbienVctB9uyUhzApjVhizxJglns8CYxYYM8eYOX72gN97wJgLjLmgmCsKuaKI2Ii0DVlJA7TEFmQMyEgaBNGYj5E0CKIxHiNpEERjOkbSIIjGcIykgdY4XuIIEYGxoWGxJWNqSy9p0EQcmtnDRBJ9mclJGiTA1kVVnKRBSIDOEXWSBiF9+iTKSRqEWunw0UgaSCRZQpFkRUWSFYvDzQeI3T5EdzYmk8hvfTlRA1GpHMokul6eEzUI2yuxTCKrEwhEfXXCRXGgoUmGcLEmJShMJoGqBdsucLCOwOAzXBui2VvCeQ5LKozoL2UaRLQK9YdPDCKylCUVRmR5HItIzFneB7SIxOXAnL0Oka5HJIxQHTzQPaNf4kQY0R8n97SZ2g1TRvqP101OpAu6Rr6fC2pLLOvDlBZ0mEgV6QsLQExuUCgvWp88+3Ei62tpJ1naV97JrQVhLjFmgzGbFnOoun37bpj44QUd0k2Nh15hzApjlhizxJgFxiwwZo4xc4wZMGbAmAuMuaCY2LKwYWG7wmaFraqhiNiAsP1g88HWg40H2w42HWw52HC43eAljhARGBsalpoyqtDiDJ+MpvjgO10ZvdRlql45QQc0NBdnnaADGvY5ulDQAQ3xQVumD++coENopQ6kjaCDovgVDPfb/QXvRHRvYyJRgCKR/t6d29UJY9MfJ3CxB4mBdaVGFyGRSL3CIlEFRSJ938RFm4T16KwOFyZTlYOJRFCzYVsQ5hmcukBENHsrKhKtqEikvz1rENEqXFGRSFYotojEVGRJJotIzFlem7SIxOXAxMEOkbhFqNp3iHiFI5EI70Qt5gSzoXaDtuoOk1oOE4XMRyAdJjceJArpYpMek9oPE4VMHQmHOUHpoTbEwnGctJDl7eexwVK+tszjoj1MwFnRbtpdgUu1CHN5z9Ab3E1zTzc17qbGM1RhzApjlhizxJgFxiwwZo4xc4wZMGbAmNgAw4JiYmPDtoZNbUkRsVU1FBEbELYfbD7YerDxYNvBpoMtBxsOtxu8xBEiAmNDw+JbRjVrnPGV0ZQvfNEuozftcGmljNZWMmWtncQFGprb4U7iAg3NJ7+dxAUa9mewUOICDTEJyCix6I5Q8FaEWE3AslmAslmOZbMcymb6W5ku+iDxd4llM/k9EidyITZTQdlMlzZx8Sa9nMBkM3h3Cef8ZDSNCEtOGVWx2EZJWRMZWUvE0NCgbNZRO4hI3nBOPyOdy49mWURS9F4WCbeIpPqcrORlEckNbHiXtUMkCdAwkbRDJCdw8ByjQyQBD901+iWOrSau24uYdNcNNSW0f3eY1JhQlNFhUnNihRL7D9dCTG5RqKAjLsiamyKvDpNbFbpXgG//5PhGUd4loNyzZJ+s7b8//wcgIYoDf+sAAA==

**Expected behavior**
As i said before, i want to appear on the map alongside the other nations(i put their and my local of spawn),maybe I'm confused? I don't know,if there's a tutorial or something for me,please,tell...maybe I'm just stupid? I don't know what to exactly do.

**Comment by krushia** [comment]
Is this the same as your last bug report?

**Comment by Bielbabel** [comment]
Yes, i did it wrong?

**Comment by Bielbabel** [comment]
Please, tell me if I'm just being stupid or if is a bug, because i put their spawns and mine on one location, they just don't spawn there, they don't even appear in the map, they just disappear like me, I can't play scenarios that i made

**Comment by krushia** [comment]
okay, so the issue is that you need to add units to the map. The player starting locations don't automatically spawn default starting units if it is a scenario. However, if you instead save it as a normal map, any nations will spawn at the starting locations as you expect.

It is indeed very confusing. The map/scerario authoring process needs a lot of refinement in general, so don't feel stupid about it.

**Comment by krushia** [comment]
I hesitate to clarify further because I'm not entirely certain  myself, but I believe the following ways of making a custom game will all yield a slightly different set of rules.

1. Normal map with extended map editor off
2. Scenario with extended map editor off
3. Normal map with extended map editor on
4. Scenario with extended map editor on

And then Scenario maps made from any combination of the above by adding "Scenario" to the end of save name with extended map editor on.

**Comment by Bielbabel** [comment]
Thanks for the support, this was helpful, i will test the map now, thank you
