### ISSUE TITLE
trading technologies option

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3494]
add the new game option to trade technologies with other civilizations in the diplomacy window.

but let it work in such a way that you cannot completely teach another civilization your technology. that is, you cannot sell 100% of the studied technology, but only 66%, for example. and through diplomacy it is impossible to make progress in any technology more than this 66%. the rest will have to be researched by ourselves. it sounds logical, because in real life, you need time to master a new technology, and not take and use it right now.

then you can add a civilization to the game, for which this threshold will not be 66, but for example 75.

someday.

**Comment by yairm210** [comment]
No. This was a subject of much debate but not in Civ v - and so not in unciv.
