### ISSUE TITLE
new actions for units

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3496]
1. add "don't allow to go to the next turn if there are idle units" option. and the "next turn" button will circle all idle units. 
2. for unlooping that add "skip" (skip one turn) action for all type of units.
3. rework the switchable "sleep" (skip all turns) action. the unit no longer wakes up when nearby enemies.
4. add switchable "alert" (be on the alert. skip all turns until enemies are near) action with an eye icon. the unit wakes up when nearby enemies.
5. "fortify" button becomes switchable too. the unit wakes up (or not) when nearby enemies depending on the selected mode: "alert" (turns on by default) or "sleep".
6. in theory, all actions will fit on the left panel even at the minimum resolution, but I suggest making actions either a scrolling list with a displayed bar on the left  (#3495), or placing some similar actions in one row. eg.: "explore - automate (for workers) - stop automate/explore" or 'skip - sleep - alert - fortify" etc.

**Comment by krushia** [comment]
You really should take the time to produce conceptual illustrations before creating feature issues :)

**Comment by b-1** [comment]
is it really so hard to imagine a scrollbar to the left of the action bar if they all don't fit there?))

new actions. something like "give orders to all units before ending your turn" mode was in the original game. and every time it will be annoying to awaken great people in cities when the enemy is near.

and the fact that I suggested some actions can be placed to the right (and not just above) of the previous ones, then because there are exclusive actions. for example, a unit cannot be in auto exploring and sleep at the same time. and it would be nice to group this actions somehow. but mindlessly sculpting buttons into two or three columns is not an option. the scrollbar is clearer and the best way out.

and, yes. I can do conceptual illustrations;)

**Comment by yairm210** [comment]
This sounds... very specific to your playstyle. A lot of these options are actually detrimental to other players' playstyles, and the others don't have a large benefit.

**Comment by b-1** [comment]
the original game did not allow the turn to end if not all units were moving. when clicking on the "next turn" the camera flew to the non-walking unit. to leave it in the same place, he had one more action - "skip the move".

I just offered to return this mechanic. and make three buttons instead of two for clarity.

now, to go with all units, you need to flip through the map, find a unit, tap on it and only after that flip through all the others.
