### ISSUE TITLE
Bug #3341 is back

### ISSUE THREAD

**Issue by krushia** [yairm210/Unciv#3497]
Issue #3341 is back again in 3.12.4

**Comment by krushia** [comment]
Maybe from https://github.com/yairm210/Unciv/commit/fb743ade31b2c0f95f3272841f23a4329ef1d169#diff-2BDE7916D74C3F38AB1C828AB9018216 idk it's strange.

**Comment by yairm210** [comment]
Not reproducing for me - can you send a pic? Maybe it's in a specific language or resolution?

**Comment by krushia** [comment]
￼

**Comment by krushia** [comment]
bad
![Screenshot_20210103-141627_UnCiv](https://user-images.githubusercontent.com/2147138/103486855-f9886780-4dce-11eb-83b2-d2e35cc8a7ac.jpg)

good
![Screenshot_20210103-141632_UnCiv](https://user-images.githubusercontent.com/2147138/103486865-0d33ce00-4dcf-11eb-818d-e5f57b3a2bb4.jpg)

**Comment by krushia** [comment]
On a related note, the right pane doesn't adjust itself after moving the separator either.

after moving separator (from state shown in second pic from previous comment)
![Screenshot_20210103-143106_UnCiv](https://user-images.githubusercontent.com/2147138/103487074-8e3f9500-4dd0-11eb-9c9d-164d9717dc35.jpg)

Properly reflowed after hitting Manila's icon in left lane
![Screenshot_20210103-143112_UnCiv](https://user-images.githubusercontent.com/2147138/103487137-23db2480-4dd1-11eb-828f-7412d311fed6.jpg)


Dunno if this counts as the same bug or not.

**Comment by the-Arioch** [comment]
There is one more way to open this window - tapping the notification (below end-turn button).

This is how i do it mostly. And this also triggered this bug ( in .5 version from FDroid)
