### ISSUE TITLE
new game option of quantity and blacklist of natural wonders

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3499]
some wonders give a very strong boost, especially in duel mode. it would be nice to be able to disable some of them. and the choice of their number will help when playing with a non-standard number of players on a map of the selected size.

I think it makes no sense to propose to make a black list of natural wonders, as in the previous cases, for the "same reason"?) but the reason itself will sound here?)

if the reason is that you have more important gameplay moments that are not implemented, and you don't care about such trifles, then what do you say if I offer the same thing in the form of a code? I just thought it would be easier to introduce these little features to someone who knows the code completely, and will not start to understand it from the very beginning.

**Comment by yairm210** [comment]
If you add this as a PR, then sure, I don't see why not ;)
But I'm personally not going to implement this

A good place to start would be to look at the `NaturalWonderGenerator.spawnNaturalWonders()`
If you add an ArrayList of, say, allowedNaturalWonders to mapParameters, then you could use that to filter the natural wonders that will be spawned.

In the UI, what would happen is that in the MapParametersTable you would select/deselect options
The mapParameters set there eventually propogate to the tileMap.mapParameters

You can see that for instance the mapParameters.noNaturalWonders propogates all the way from the UI of MapParametersTable to the spawnNaturalWonders() function, so you can start based on that 

Hope that helps with the initial direction - you don't need to know the rest of the code for this I think, just those two places :)
