### ISSUE TITLE
extended camera move on an event click

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3500]
when moving from the list of events, let the camera move not only to the city and to the unit. I propose to expand a little the ability to click on the event:

1. sometimes you need the camera to move exactly to that tile (and not the city itself) to which your city expanded or the one that was captured by an enemy city near your borders.
2. when the game notifies of the entry into a new era or shows a message about the termination of trade agreements, let the diplomacy window open with this civilization. since a beginner player may not know the relationships between the names of civilizations, the names of their capitals, the names of the leaders, the schemes of colors and pictograms (in the message there is only the name of the nation, and in the list of diplomacy only icons familiar to experienced players). let the nation icon in the list blink.
3. and the "overview / diplomacy" tab opens on the conclusion of peace or a declaration of war between our civilization and another or only between others message, where the lines that have changed color are blinking.
4. let the game show a message when happiness becomes negative and for what reason. move the camera to the reason: either to the city that has grown, or to the captured city, or to the destroyed improvement on the luxury resource, etc.
5. when the construction of a unit is completed, when you click on an event, let the camera move not to the city, but the unit itself. because the unit may have already been moved out of the city. also let the unit be selected by clicking on the event. so that you don't have to click a second time on the same tile.
6. when building a building is completed, when you click on an event, let the city menu open on the "stats drilldown" tab, where the constructed building is blinking.
7. and when you click on the event about the start of construction of a new object, let the city menu also open, but on the "construction queue" tab, where a new construction element is also blinking.
8. add a blinking effect on a specific researched technology by moving from the list of events. also due to the fact that the player may not remember the names of all technologies in order not to look for it for a long time.
9. let the game report on the destruction of an enemy unit and the humiliation of your unit when smashing against an enemy THIS player's turn. just like the game gives a message about the discovered wonder of nature.
10. when the message about opening a new policy branch, let the policy window open and the desired branch blinks.
11. let the message "the wonder of the world has been built in faraway land" be sent to the appropriate page on the civilopedia so that the player can read what benefits the unknown player has received. and if a city with a miracle is known, then first (as it is) let the camera be transferred to this city, and when you click on the message again, it will go to civilopedia. do not forget about the blinking effect on the desired element in the left list. 
12. let a message be displayed that a new city of another civilization was founded on the territory explored by the player. sometimes you can not see it for the first few moves after its foundation.

there is also a visual bug. part of the event list is unavailable due to the tile description being drawn over it.

I hope the improvements I have proposed will make the event list more useful and speed up the game.

**Comment by yairm210** [comment]
This would require a serious change in the way we save such notifications between turns, and as such denied on cost/benefit reasons

**Comment by b-1** [comment]
really nothing from this list is unrealizable? well, the game takes the name of the building that was built as a variable, and the name of another nation that way. why can't she substitute them to show the desired building in the city or civilization in the diplomacy window. even the coordinates of the expansion tile cannot be passed to the notification?
