### ISSUE TITLE
Couple of "Issues"

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#3506]
Here are couple of things I decided to elaborate on.

Helicopter Gunship unit should not be able to take cities. It has it's own unit type (Helicopter Unit) in civ5 which is basically an air unit that can end a turn on a tile. It does receive additional damage from Anti-Air units like Fighters, Anti-Aircraft guns, which is not present in unciv.
![image](https://user-images.githubusercontent.com/30041793/103679821-a1e02c80-4f85-11eb-9e06-230df2bfc763.png)

Computers tech provides +10% science and +10% production in all cities. Where did that came from? There is nothing like that in civ5.

In Unciv, Great Persons points are accumulated per Empire, while they are accumalated per city in civ5 - except for Great Prophets and Generals/Admirals. It means having 4 Scientist Specialists in three cities will not grant you a Great Scientist faster than one city with 4 Scientists Specialists. It only matters when you want to get multiple scientists one after another (count only resets in a city which created the GP). This forces the players to have multiple cities, each focused on a different thing. This also makes you know where the GP will be born.

Strategic Resource quantity is really scarce in Unciv. In civ5 Strategic resources spawn in quantities choosen from the list of possible values (each resource has its own predefinied max/min value) : https://forums.civfanatics.com/threads/resource-quantity.416107/#post-10329758 According to what I've experienced playing civ5, linked values are correct (Each resources appears either in max value or min value, depending on the resource amount setting, i.e Iron might either appear in small stack of 2 or major stack of 6 on a map with resource amount set to standard).
Oil on water tiles always appears in only one stack variation - 4 for sparse/default and 6 for abundant settings.

Speaking of Luxuries, you almost always get a couple copies (usually 3) of the same luxury near your starting location, so each player has "its own" luxury to trade + sometimes you get 1 copy of another luxury for happiness. The "Starting Luxuries" don't usually appear anywhere else on the map.

**Comment by ravignir** [comment]
Another thing: In Civ5 when you found a city it automatically creates Road improvement on the same tile. This road is maintenance free (as long as the city is here) and stays there even when you raze the city (but then you will have to pay for it). Roads under cities are automatically upgraded to Railroads as soon as you get the tech that unlocks them.


![roads](https://user-images.githubusercontent.com/30041793/103752985-b87c9700-500a-11eb-8b97-e7d79a6bbec4.png)
![unciv](https://user-images.githubusercontent.com/30041793/103753170-fd083280-500a-11eb-9e16-73dac8578fe5.png)

Barbarians should not be able to fortify and heal. The only way Barbs heal in civ5 is through pillaging improvements.

Unhappiness is just another thing - in unciv the detrimental effects are laughable imo.
![unhappy](https://user-images.githubusercontent.com/30041793/103753885-e0b8c580-500b-11eb-840a-bbfe0af96a91.png)
![veryunhappy](https://user-images.githubusercontent.com/30041793/103754061-22497080-500c-11eb-8187-dc958ceacfc6.png)
![revolt](https://user-images.githubusercontent.com/30041793/103754174-4d33c480-500c-11eb-8000-1f0ac708c5c4.png)
![settler](https://user-images.githubusercontent.com/30041793/103754235-63da1b80-500c-11eb-950e-004ae4be9bee.png)
Settler's can't be trained if unhappiness is 10 or more.
In G&K and Vanilla:
![unhappygk](https://user-images.githubusercontent.com/30041793/103754497-b6b3d300-500c-11eb-811a-350ec3bba2ef.png)
![veryunhappygk](https://user-images.githubusercontent.com/30041793/103754658-ecf15280-500c-11eb-846b-6914f6d573f9.png)

the penalty is flat -50% production and -33% strength.

**Comment by ravignir** [comment]
This one will be controversial - and it will not pass if you poll it I guess:
"Bonus vs City" should not work when City attacks your unit, which makes siege unit really fragile.

**Comment by avdstaaij** [comment]
It looks like all items in this issue have been fixed or moved to #4697, so I believe this can be closed. This issue does contain more details about some items than #4697 though, so I suggest that a link to this issue is added there.
