### ISSUE TITLE
minimized list of units

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3510]
to the left of the window with a description of the selected unit, there is a button "close". let the "open" button remain in this corner after closing. let there be a number near the button, which means the number of units that still did not move.

now, to access this panel, you need to flip through the map and look for any unit to click. this is a non-obvious design decision that slows down the switching between units to select the correct order of their turns.

you can also add an option to the settings that allows / disables scrolling through all units instead of just those that did not go.

**Comment by b-1** [comment]
in Civ5, there were two more ways to get into this menu, besides finding your unit on the map and through the overview panel:

1. the game did not allow the end of the turn if some unit did not move. disappears due to the fact that some of the original actions disappear (#3496).
2. instead of a big science button, a list of units could be selected. I suggest makes something like this but separately. this will be the fastest way. also the most intuitive.

**Comment by yairm210** [comment]
I think that this would crowd Mobile to a horrifying degree. There's already way too much going on in the main screen.
