### ISSUE TITLE
Small typo in wiki

### ISSUE THREAD

**Issue by OnSive** [yairm210/Unciv#3516]
Under [Project structure and major classes - Major classes](https://github.com/yairm210/Unciv/wiki/Project-structure-and-major-classes#major-classes)
There are all UI elements listed and instead of `CityScreen` there's `CityScree`.

It's not urgent ;)

_Btw. I don't know if I could edit the wiki and propose a pull request - didn't find the functionality - so here's an issue._

**Comment by yairm210** [comment]
Done, thanks :)
