### ISSUE TITLE
happiness standard

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3524]
the only tab that allows you to adequately track your happiness is the "overview / stats". but this is only a summary value, not giving an understanding of which cities are good, and which are bad with happiness.

I think that one standard is needed here:
1. "overview / cities" and the top right menu of the city should have the same order of icons for convenience.
2. the icon of happiness is missing in the upper right menu of the city. now you have to open "stats drilldown / happiness" and scroll to the extreme bottom. because the number in "overview / cities" does not match the actual state of affairs.
3. the parameter must be able to be negative everywhere in the right menu of the city and in the "overview / cities", as in "stats drilldown / happiness". so that right after entering the city or "overview / cities" you can calculate how much luxury resources it /they needs. food, for example, can be negative and the game allows the population to shrink.

**Comment by SomeTroglodyte** [comment]
Just my 2-cents:
The 'missing icon' is commented out in source, presumably for aesthetic reasons. It would show the same number as the city overview. The 'not match' difference is a value that's the same for all your cities, so the value shown in overview is still meaningful and comparable. I'd tend to slightly favour having the 'drilldown' value everywhere as you suggest, but to me it would be a very minor concern.

**Comment by yairm210** [comment]
One problem here is that the main thing that *gives* you happiness is luxury resources, which are *global*, but the main thing that *takes away* happiness is *city population*, which is *per city*.
But I agree that per-city effect should probably be shown in the stats table.
Proper city happiness can be computed from city.cityStats.happinessList.values.sum()
