### ISSUE TITLE
Closing a popup causes application shutdown

### ISSUE THREAD

**Issue by wetorek** [yairm210/Unciv#3528]
**Describe the bug**
Closing a popup window with information using ESC key causes closing the whole application. The game is closed.

![unciv](https://user-images.githubusercontent.com/39585557/104513412-e60ba680-55ef-11eb-94e9-325a3006d3e6.png)
![unciv2](https://user-images.githubusercontent.com/39585557/104513415-e7d56a00-55ef-11eb-897c-da3f685f67e1.png)

**Comment by yairm210** [comment]
Doesn't crash for me - can you maybe send a saved game?

**Comment by yairm210** [comment]
Closing this as "not reproducible", if you have more info I'd be glad to reopen this
