### ISSUE TITLE
Switching between units is buggy

### ISSUE THREAD

**Issue by wetorek** [yairm210/Unciv#3529]
**description**
Switching using next unit and previous unit does not work properly.

In my case i have 4 units- 1 Warriors and 3 scouts.

Starting with warrior I can iterate through

warrior -> (next) -> scout1 -> scout2 -> scout3 -> scout1 -> scout2

In this case I never reach warrior. 

Starting with scouts i pick one of them and I can only iterate among scouts. 
![unciv-un-10-1](https://user-images.githubusercontent.com/39585557/104513660-46024d00-55f0-11eb-8fed-e8b04377ed40.png)
![unciv-un10-2](https://user-images.githubusercontent.com/39585557/104513665-47337a00-55f0-11eb-9b45-b1ad37dfc93a.png)
![unciv-un10-3](https://user-images.githubusercontent.com/39585557/104513666-47cc1080-55f0-11eb-872a-f68b4a346d58.png)
![unciv-un-10-4](https://user-images.githubusercontent.com/39585557/104513667-48fd3d80-55f0-11eb-887a-24ab72edce2a.png)

**Comment by b-1** [comment]
perhaps this is because the warrior spent all his MP.

**Comment by yairm210** [comment]
This is indeed not a bug, the outstation hours through idle units only
