### ISSUE TITLE
Free techs (granted from wonders and policies) bugs embarkation and unlocking new policies

### ISSUE THREAD

**Issue by philn3v** [yairm210/UnCiv#353]
For example if you select Optics as your free tech your units cannot embark.

If you select a tech upon entering a new era, policy tree will still be locked until you manually researched another tech into that era. Also note there isn't a notification of entering a new era with free tech.

**Comment by yairm210** [comment]
Fixed, will enter 2.10.16
Thanks, this actually highlighted a big flaw in dealing with free techs!
