### ISSUE TITLE
Creating a settler having a population of city equal to 1

### ISSUE THREAD

**Issue by wetorek** [yairm210/Unciv#3531]
**Describe the bug**
There is possibility to create a settler, when a city has only one citizen. It is impossible in an original game. 
>"To build new Settlers, a city must have at least 2 Citizens"

https://civilization.fandom.com/wiki/Settler_(Civ5)
![settler-1](https://user-images.githubusercontent.com/39585557/104514085-f96b4180-55f0-11eb-8b47-af0426bb8b20.png)
![settler-2](https://user-images.githubusercontent.com/39585557/104514088-fb350500-55f0-11eb-9c4b-3106b14c4675.png)

**Comment by yairm210** [comment]
Already solved in latest version, please upgrade
