### ISSUE TITLE
disable the menu

### ISSUE THREAD

**Issue by kkpolak** [yairm210/Unciv#3532]
menu turns off when the size of the window is changed

![image-2021-01-10-15-09-14-811](https://user-images.githubusercontent.com/61544338/104514046-e9ebf880-55f0-11eb-9cc7-1cfcee395432.png)
![image-2021-01-10-15-09-29-088](https://user-images.githubusercontent.com/61544338/104514052-ebb5bc00-55f0-11eb-85cf-5f84995d5c70.png)

**Comment by yairm210** [comment]
That's a feature, not a bug.
Generally of you open a menu to do something, once you've done it you want the menu closed
