### ISSUE TITLE
Sliders do not work correctly - map editor advanced settings

### ISSUE THREAD

**Issue by kamilsuchy** [yairm210/Unciv#3534]
**Describe the bug**
The sliders in advanced setting work with stops. This is an undesirable effect

**To Reproduce**
1. Launch the game
2. click on button "Map editor"
3. Click on "new map"
4. Click on "show advanced settings"
5. Slide sliders

**Comment by b-1** [comment]
the sliders remain in place when the vertical component (Y) changes with the movement of the finger. in theory, you do not need to pay attention to it and not flip the screen vertically if you hook the slider.

**Comment by yairm210** [comment]
Not a bug - this is the desired effect
Non-discreet quantities do not improve the map generation or the player enjoyment, in fact the opposite. If a player thinks there's a difference between 0.34 and 0.33 they may spend an inordinate amount of time trying to get it 'just right' when in fact it makes no difference.

**Comment by b-1** [comment]
here the question is that the slider undesirably comes off before you remove your finger. it has to be pulled several times in one direction.
