### ISSUE TITLE
Create a multiplayer game with the same players

### ISSUE THREAD

**Issue by kamilsuchy** [yairm210/Unciv#3535]
**Describe the bug**
We can create multiplayer game (two players)  whose ID is the same

![1 (4)](https://user-images.githubusercontent.com/44306803/104514719-fde42a00-55f1-11eb-9fba-5a44667cdf30.png)
![2 (4)](https://user-images.githubusercontent.com/44306803/104514722-ffaded80-55f1-11eb-9321-e4d9e3137c5e.png)

**Comment by yairm210** [comment]
I don't see a problem here. If I want to play 2 different users in a multiplayer game, what's wrong with that?

**Comment by yairm210** [comment]
Closing as "not a bug"
