### ISSUE TITLE
Double display of map names

### ISSUE THREAD

**Issue by wetorek** [yairm210/Unciv#3536]
**Describe the bug**
If we click the "download map" button twice or more, the map list will be displayed as many times as we clicked.
e.g. if we click the button 3 times, the list will be displayed 3 times and then we have to click 3 times on the "close" button
![Zrzut ekranu 2021-01-08 105349](https://user-images.githubusercontent.com/39585557/104515194-c2962b00-55f2-11eb-9cdc-7d6cd6f4a8c9.png)

**Comment by krushia** [comment]
This applies to all popups in general. For example you can open multiple options dialogs.

**Comment by yairm210** [comment]
A. This is solved globally by popups blocking what's in front of them
B. If you *do* somehow manage to force this by double tapping quickly (I didn't manage) then that's really your problem rather that the game's problem...
