### ISSUE TITLE
show tutorial every session

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3538]
show me the tutorial every time I start a new game. if I do not need it, I will turn off this option in the settings. but if I turn the option back on in the middle of the game, let the game show me all the clues that I didn't see in this session.

now the "show tutorial" option only works if I meet the required trigger for the first time at all. if I close the clue, I will never see it again. but what if I let a beginner play on my device? or what will happen if a mid-level player needs help where he has not yet reached in previous sessions, and he turned off the tutorial early so that it does not interfere at the beginning of the game?

**Comment by yairm210** [comment]
I totally disagree

A. All tutorials appear in civilopedia
B. For the one-in-a-thousand user that want to rerun the tutorial we subject all 999 others to the same fate?! That's just bad design

**Comment by b-1** [comment]
why then do you need an option "show tutorial" in the settings? if I saw all the tooltips once, then the option does not change anything =\ but it is, so it must change something. besides, the Civ5 had same "bad design". if you want to see turn it on, if you don't want to see turn it off. isn't she there for that?
