### ISSUE TITLE
Tech tree order bug

### ISSUE THREAD

**Issue by philn3v** [yairm210/UnCiv#354]
Hospital requires fertilization (instead of archaeology + scientific theory)
Scientific theory requires archaeology (instead of just architechure + economics)
I only recently noticed because the tree jumped weirdly when queueing techs. I believe this bug did not occur during the october versions.

**Comment by yairm210** [comment]
Both confirmed, they've been this way for quite a while, good thing you noticed!

**Comment by yairm210** [comment]
fixed, will enter 2.10.16!
