### ISSUE TITLE
Defeated civs not stacking properly in diplomacy screen

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#3548]
When civilizations and city-states are defeated, their icons don't stack in the diplomacy screen. Instead of lining up in two neat columns they stick out in one long row.

![Screenshot (46)](https://user-images.githubusercontent.com/58439827/104950545-1a7bbb80-597e-11eb-8c44-b8b89590a269.png)

Here some autosaves where you can get a good look at how the screen changes when you move more civilizations from living to dead. This game is using the following mods: The Undead, Resource Recyclers, and Difficulty_Sandbox
[Autosaves.zip](https://github.com/yairm210/Unciv/files/5831878/Autosaves.zip)

**Comment by yairm210** [comment]
Gah!
