### ISSUE TITLE
Shortcut key for Pasture

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#3560]
Most improvements have a shortcut key, Pastures don't seem to have one. Please add one. P is already taken for plantation, so what about A?

**Comment by yairm210** [comment]
Pasture is also a P. Since they're both resource-dependent, they can't be built together, so they can share the letter.

**Comment by krijnsent** [comment]
I see the issue is closed, but Pastures still don't have a shortcut key. It can be P, but can it please be added to the game?

**Comment by yairm210** [comment]
Is this not working for you? Please send game data

**Comment by krijnsent** [comment]
I think I found it: it seems to work in the normal game, where the text of the action also includes (P) to indicate that that is the shortcut. It stops working when I use the Civ5ExpansionMod: the text of the action than also changes and doesn't show the (P) anymore. Please close this issue, I'll file it there.
