### ISSUE TITLE
Upgrading ship of line

### ISSUE THREAD

**Issue by haro122** [yairm210/Unciv#3563]
**Describe the bug**
Unable to upgrade British ship o line to battleship

**To Reproduce**
1. After electronics researched
2. Click on ship o line in home waters
3. No option to upgrade to battleship

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Do you have Oil? Battleships require Oil

**Comment by haro122** [comment]
No, you are correct, no oil


Get Outlook for Android

**Comment by yairm210** [comment]
Cool, not a bug then ;)
