### ISSUE TITLE
Generated maps are similar.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#357]
Perlin generator's maps always have land & sea in similar positions. Maybe it needs improvement?

**Comment by yairm210** [comment]
Go for it!
I tried my hand at some things that I found online, not much came of it, tbh I was hoping someone who had already dealt with map generation would come along and help :)

**Comment by ninjatao** [comment]
Got it. Starting to learn perlin noise. I will try to generate maps like continents and pangaea, which I like best in origin civ games.

**Comment by ninjatao** [comment]
![figure_1](https://user-images.githubusercontent.com/6846049/50210468-308aac80-03b1-11e9-9d27-82bdd0c23f10.png)

Cellular automata seems to work to generate landscape. May combining this and divideIntoAreas() can solve this.

**Comment by ninjatao** [comment]
![figure_1](https://user-images.githubusercontent.com/6846049/50212438-0c7d9a00-03b6-11e9-8f58-17b3067db136.png)

A litter better version on map edges.

**Comment by yairm210** [comment]
Was this image generated from inside the game?

**Comment by yairm210** [comment]
Because if so, that's massively cool

**Comment by ninjatao** [comment]
Not yet, I was just trying to tune the algorithm with python.  😄
