### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by reiuyfan** [yairm210/Unciv#3578]
The mixture of blue and red makes the eyes uncomfortable and can't see the text
![Screenshot_20210205-073207](https://user-images.githubusercontent.com/52944146/106969011-00671900-6785-11eb-8a4b-184815fb2e6e.png)

**Comment by ravignir** [comment]
What about original civ5 colors?
"outerColor": [26,32,96],
"innerColor": [255,0,0],
![civ5c](https://user-images.githubusercontent.com/30041793/106970419-1527ba80-674d-11eb-9f59-4bc83dd5b821.png)

**Comment by reiuyfan** [comment]
> What about original civ5 colors?
> "outerColor": [26,32,96],
> "innerColor": [255,0,0],
> ![civ5c](https://user-images.githubusercontent.com/30041793/106970419-1527ba80-674d-11eb-9f59-4bc83dd5b821.png)

It's ok
