### ISSUE TITLE
Separate save files

### ISSUE THREAD

**Issue by slavdan1** [yairm210/Unciv#3583]
Have at least 2 or 3 save files for games. Its annoying when im playing a game and then go to a different game to experiment with a feature, play a couple of turns and then overrides my other game.

**Comment by ravignir** [comment]
I assume you meant autosave. In civ5 you can set the number of turns between autosaves and total number of autosaves before overwrite. It also creates initial autosave in civ5 on turn 0 before you move any units. I would like to have that option in unciv.

**Comment by yairm210** [comment]
Already exists :)
Load game - show autosaves
