### ISSUE TITLE
Cant load game

### ISSUE THREAD

**Issue by Narhsh** [yairm210/Unciv#3587]
**Describe the bug**

**To Reproduce**
1. Go to 'game main menu '
2. Click on '. Resume.'
3. Scroll down to '.. Simply play the game via the next then button'
4. See error; not enough memory to load map.

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
The game map is supposed to load once you press the next turn button.

**Screenshots**
[Screenshot_2021-02-09-22-30-03-671](https://user-images.githubusercontent.com/78533478/107424345-33fbc780-6b26-11eb-8013-034f80593e5f.jpeg)
]

**Additional context**
The occurrence is very random, and can be dealt with by simply pressing the next turn to it gives a turn where the map has loaded. This prevents me from playing in certain turns out the game.
Every option button (pause, resources, policy and tech) works just that the map does not load.

**Comment by yairm210** [comment]
If you reload the autosave, does this still happen?
Also, do you get a popup that says "Not enough memory on phone to load game!"?

**Comment by yairm210** [comment]
Closing this as "not reproducible, not enough information".

**Comment by Narhsh** [comment]
Apologies for the delayed reply.

Yes I do get the “Not enough memory on phone to load game” message.
