### ISSUE TITLE
Game ID not copying to clipboard

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3590]
When I try to start a new multiplayer game, I put in my User ID and another one. I can start the game but the game ID doesn't get copied to the clipboard.

**Comment by UniqueActive** [comment]
You should include some more information about how you are running Unciv, like your operating system and how you are running it. Otherwise nobody can test it properly :)

**Comment by CIZUK** [comment]
Sorry, it's an Android phone.
Does that help?

**Comment by yairm210** [comment]
Working 100% fine for me
Is this happening repeatedly for you? Have you tried creating a game with a smaller map?

**Comment by yairm210** [comment]
?

**Comment by CIZUK** [comment]
Sorry yes it was repeating but I haven't tested it recently.
I did it on the default, so probably the medium map

**Comment by yairm210** [comment]
I see that the game copy only happened after saving the game locally - on my desktop that took about 30 seconds!

Changed the order to popup first and save second so this is faster, should be good now :)
