### ISSUE TITLE
Can't open game after closing it. 

### ISSUE THREAD

**Issue by Arghadatta** [yairm210/Unciv#3598]
When I try to play again,it closes and Don't response and automatically closes.it oftenly happen when i try to play the game after opening the game for first time.but i got a solution.reset the game data.before i do that i save my game and do it.and it solves it.but i have to do it everytime i play.Please fix it!!

**Comment by yairm210** [comment]
What version are you on? What device?
Is this a problem with a specific game, or when you start a new game do you get the same problem?

**Comment by Arghadatta** [comment]
> What version are you on? What device?
> Is this a problem with a specific game, or when you start a new game do you get the same problem?
It fixed with an solution.but sometimes it does not respond and i have to open it after and it worked.i think it is a optimizing issue.BTW in my computer.not mobile.and in every game.but i debugged it with a string for my pc.you should fix it.thanks!!

**Comment by yairm210** [comment]
This sounds 100% like you just have a problem with your computer.
But send me the game info (save game - save to clipboard) and we'll see if there's anything we can improve

**Comment by Arghadatta** [comment]
Ok.Thanks for info.👍

**Comment by Arghadatta** [comment]
One more thing,why exe file don't work....???

**Comment by yairm210** [comment]
What operating system do you have? And what zip did you download?

**Comment by lishaoxia1985** [comment]
In android it also has this problem, when you use the menu "Exit game", and then you open the app the game shows unnormally.

**Comment by yairm210** [comment]
What do you mean by "unnormally"? I'm not encountering this problem

**Comment by lishaoxia1985** [comment]
you can test this in android: when it popups the window "do you want to exit the game" you choose the button "yes", and then you reopen the game, you will find this bug. i think it is because the game can't exit entirely when you touch the yes button.

**Comment by yairm210** [comment]
Ah, I see
I was closing it from the WorldScreen, where this doesn't happen
But if you close it from the MainMenuScreen then it does
I'll see what I can do

**Comment by Arghadatta** [comment]
> What operating system do you have? And what zip did you download?

Windows 7 32 Bit.I downloaded The win 7 32 bit zip

**Comment by Arghadatta** [comment]
Thanks....
