### ISSUE TITLE
Update within the game

### ISSUE THREAD

**Issue by LouisDeconinck** [yairm210/Unciv#3615]
I might be overlooking things, but nowhere within the game do I find the option to update to the most recent release.

Does this mean that every time a new version is released I have to re-download the game from itch.io? 

If this is the case, please add an in-game option to update the game to its most recent version.

**Comment by yairm210** [comment]
Itch.io's launcher has its own auto-update, which should update the game for you :)
Updating from within the game is not the correct way, since Android, Linux and Windows work very differently, and Google play and itch.io since those differences in their own way
