### ISSUE TITLE
Online multiplayer game gets stuck

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3616]
I had a started online game with my friend. We were playing without any problems but when my friend finished his turn, the game got stuck and couldn't let us play. We both were getting message 'Waiting for other players' for 10 minutes. I thought only that one game broke so I started a new one. It started normally, I finished my turn, my friend did, and.... nothing. We waited like 15 minutes but nothing happened. Not even the 'Loading last game state' pop-up didn't show. The 'Multiplayer' card says England (that's my friend) for me and Maid Empire (that's me, civilization from a mod) for my friend. Please fix it, we finally managed to start a game so we don't want this happening.

**Comment by John-Cass** [comment]
I'm seeing the same problem here, we tried removing all other non-human players in case the AI was stuck but same problem  -game hangs with neither of us able to play

**Comment by jahodovykolac** [comment]
Both of games fixed themselves, It's my turn now. No updates installed, hope it's not some long playing AI.

**Comment by jahodovykolac** [comment]
Well.. maybe it doesn't get stuck, but gets veeeery long. When it looked like it fixed itself, I made a turn, my friend did and we're waiting again! Looks like some AI takes 20 hours to play and I don't want to wait that long. Is there any way to see which AIs play between us? We are playing 2 with 37 random AIs.

**Comment by ArchDuque-Pancake** [comment]
My friends and I have a similar problem, but the difference is that we cannot "move" to the next turn unless we reloaded the game.

**Comment by jahodovykolac** [comment]
Oops, sorry for reopening, I was playing the wrong game. But I will leave this open because some people have the same problem.

**Comment by yairm210** [comment]
Solved in 3.13.3-patch2
