### ISSUE TITLE
multiplying windows

### ISSUE THREAD

**Issue by slavdan1** [yairm210/Unciv#3619]
double clicked the unciv app icon on the desktop, the window then started multiplying until the pc crashed due to the amount of windows opened.

**Comment by yairm210** [comment]
Wtf?
Never seen this happen anywhere
Are you sure you don't have macros on your computer or something?

**Comment by slavdan1** [comment]
I don't have any macros installed on my pc

**Comment by yairm210** [comment]
Did you try this with other versions of Unciv? Or is that the first version you tried?

**Comment by slavdan1** [comment]
its the first time

**Comment by yairm210** [comment]
This doesn't seem to have been recreated since, so I'm closing this issue
