### ISSUE TITLE
Game crash when trying to move GW Bomber to unexplored tiles

### ISSUE THREAD

**Issue by slavdan1** [yairm210/Unciv#3622]
![Screenshot (72)](https://user-images.githubusercontent.com/78725776/109326551-3f056600-784f-11eb-8cf8-0f9c5d4a5630.png)

not sure if this occurs with other air units

version 3.13.2

**Comment by yairm210** [comment]
I can't see in the code why this would happen, please send game info (save game - copy to clipboard)

**Comment by jahodovykolac** [comment]
Maybe this is happening because it shows the unknown tiles as moveable (I can move here) to instead of being target (could move to, but there's not a city) so the unit ends outside of any city
