### ISSUE TITLE
Can't rename multiplayer game

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3626]
This is simple: when I go Multiplayer -> tap the game -> Game settings, I write a new name, but I can't tap Save game. The button is inactive. In older versions it worked. Am I doing it wrong or is it a bug?

**Comment by yairm210** [comment]
Does this happen for every game name that you give? Or is it only for certain names/with certain characters?

**Comment by jahodovykolac** [comment]
It happens with any characters, even if I name it something like "test" it doesn't work.
