### ISSUE TITLE
Found city key doesn't match Civ V

### ISSUE THREAD

**Issue by davidhoward** [yairm210/Unciv#3634]
The hotkey for settlers' Found City action is currently bound to 'C'. In Civ V, it is bound to 'B'. Unless there is a good reason for this, I'd call it a bug.

**Comment by yairm210** [comment]
Why on earth would it be B? That makes very little sense.

**Comment by davidhoward** [comment]
I suspect it's a holdover from earlier games where the action was called 'Build City', and they didn't want to change the keybind for what's functionally the same action

**Comment by davidhoward** [comment]
That said it's not the biggest problem in the world, not sure how closely we're trying to clone here

**Comment by yairm210** [comment]
Yeah, I think we'll close this
