### ISSUE TITLE
Adding mod features and Civs into pre-existing maps

### ISSUE THREAD

**Issue by whatsupboy** [yairm210/Unciv#3636]
Since the whole map thing's being semi reworked by Yairm right now, thanks for putting in the work btw, and scenario editing has been scrubbed, It'd be really handy to have the option of editing non mod maps and adding mod features and spawn points for Civs.

**Comment by yairm210** [comment]
Already in the works :)

**Comment by whatsupboy** [comment]
Thank you, keep up the great work

**Comment by yairm210** [comment]
Done, will roll out next version :)
