### ISSUE TITLE
Civilopedia crash

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3645]
I mentioned this in #3631, because I thought it was caused by the missing image. But looks like it wasn't the case.
When I try to open Civilopedia, the game hangs for about 2 seconds and then crashes.
Version 3.13.4, Android

**Comment by jahodovykolac** [comment]
Also I don't know where is the problem, but Google Play is always one version late. When 3.13.4 was released, I could be only on 3.13.3patch-2. Now, when 3.13.5 is released, I'm able to update on 3.13.4

**Comment by yairm210** [comment]
Does not happen to me - maybe this is a result of mods you're using?
Try creating a game with no mods at all, did it still crash?

**Comment by jahodovykolac** [comment]
I found the problem - One mod I am using - Maid Empire, now requires Civ5ExpansionMod, which I don't use in the game. Maybe the creator of Maid Empire did some update, but when I created the game it didn't require Civ5ExpansionMod
