### ISSUE TITLE
Cannot download latest version via Google Play

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3652]
So I see the latest version is 3.13.5patch-1. I thought it is just one version late, but now I see it's a different problem. Google Play allows me to have only 3.13.4 and says it is the latest version. Is there some problem with releasing or is it a Google thing?
![20210305_141114](https://user-images.githubusercontent.com/79529669/110119952-b80b3d00-7dbc-11eb-89e8-f35d41c3af71.jpg)

Also idk why there is Google Comercials as developer.

**Comment by GGGuenni** [comment]
It's intentional. 
Copied from Discord faq:

> -Why don't I have the latest update available to download?
> 
> Versions are rolled out incrementally
> Each version starts by being rolled out to 10% of users, then to 30%, then to 100%.
> In between, the devs wait a day to see if there are any game-breaking bugs. If there are, they stop the rollout, fix the bug, upload a patched version and start over.
> This means that when the dev says a version is rolling out, that means it's immediately accessible to 10% of users.

**Comment by jahodovykolac** [comment]
Okay, I'll wait. Thanks for info!
