### ISSUE TITLE
Convert map to world wrapped map

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3665]
First - I know it's an experimental feature, I'm just giving a feedback.

The bug: When I try to create a new map in editor, I can tick the World Wrap option, but the created map isn't wrapped. (Idk if it will wrap when playing, didn't test it)

The feature: It would be cool if you could make already existing older maps wrapped, I made an I-hope-good map and I don't want to rebuild it wrapped.

Also I'm on 3.13.5patch-1 so I don't know if it's already fixed.

**Comment by GGGuenni** [comment]
Thanks for your feedback!
Yea I haven't implemented the visuals for the editor yet. When playing it should wrap. So it's not really a bug more a missing feature.

The problem with your request: Wrapped worlds generate differently than non wrapped. They are missing all tiles on the right edge. So changing an old map to support wrapped would involve modifying the existing tiles.
It's possible though. I will take a look at it.

**Comment by jahodovykolac** [comment]
I tested it now, it wraps when playing

**Comment by GGGuenni** [comment]
Since the "bug" part of this issue is going to be resolved with #3667, please rename this issue to "Convert map to world wrapped map" and change the label to "feature".

**Comment by jahodovykolac** [comment]
Maybe I'm dumb, but I don't see a way to change the label (also I'm on mobile)

**Comment by yairm210** [comment]
Resolved in #3667
