### ISSUE TITLE
Idk what's this

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3668]
This appeared when I started a game

![20210308_203202](https://user-images.githubusercontent.com/79529669/110372318-7396d000-804e-11eb-9581-c1998247d439.jpg)

(I mean the code or coordinates or whatever is it)
Maybe it has something to do with world wrap.
It appears when tapping on any tile

**Comment by yairm210** [comment]
Solved in patch-1. This was the remnants of a debug addition.
