### ISSUE TITLE
I missed when they built that Halicarnassus Pyramides of Artemis... again!

### ISSUE THREAD

**Issue by ArtySh0ck** [yairm210/Unciv#3696]
Would be cool if game notificates us when someone built a Wonder. I know notifications is, but its so same as other regular notifications... its too difficult to discern! Very easy to miss...

Maybe notifications about Wonders should be more different? With sound (like in civ-5), or with mark or label? Or maybe they should be on another place of screen? 

Thanks!

**Comment by yairm210** [comment]
How would you suggest we make notifications more distinct?

**Comment by ArtySh0ck** [comment]
maybe additional sound?
or notivicate on the center of screen?

actualy, would be good if we can see information about wonders already built, maybe in diplomacy tab? like in civ-5. maybe i miss something but for now i cant find tab where i can read about this.

thanks! u do i very beatyful game! we both, me and wife dont play firaxis civs more, we play unciv and we like it grows and getting better! thanks!!!

**Comment by yairm210** [comment]
Solved by adding distinct icons to all notifications :)
