### ISSUE TITLE
Skirmish generator

### ISSUE THREAD

**Issue by ArtySh0ck** [yairm210/Unciv#3697]
Would be good if map generator knows Skirmish template to generate with options like "no water", or "no rivers", "type of terrain: desert, snow, mountains, etc..."

thanks!

**Comment by yairm210** [comment]
I took my time to think about this, but I don't think that this is a highly requested topic, nor is it something that cannot be solved by either modding out unwanted terrains or just creating a map in the map editor, so this is a "No"
