### ISSUE TITLE
Random crash and empty game

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3703]
Game crashed when I was waiting on my turn, the 'Autosave' file couldn't load game, copying game data leaves only empty start...
H4sIAAAAAAAAAAMAAAAAAAAAAAA=

And yes, I know you have other more important things to do than trying to figure out why is there this bug. It happened only once so I probably shouldn't even post this... Feel free to close this if you want to.

**Comment by yairm210** [comment]
It's not that this isn't important, it's that there isn't enough information to actually do anything with it.
If you have the autosaves from previous turns and that also starts crashing then we have a way forward, but otherwise this isn't actionable

**Comment by jahodovykolac** [comment]
Well I tried playing from the last autosave and it was ok.
