### ISSUE TITLE
Loading game popup too short

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3705]
When loading a game, a 'Loading game' popup appears. But, always for the same time. When the game takes less than that time to load, it's okay, but most games take longer than that time to load. When it's medium, you have a short time between popup and loaded game where you can't do anything, so you know it's loading. But when it's big, there is some time in which you can do anything, so you don't know if it's loading or not.
I suggest it should disappear when the game is loaded, not for the same time.

**Comment by yairm210** [comment]
I guess this was in 2 different places, I thought you meant for multiplayer loading but now I see it's for regular loading games as well.
