### ISSUE TITLE
Builder automatic mode

### ISSUE THREAD

**Issue by Luyann** [yairm210/UnCiv#371]
A builder tried to build a farm in one culture land mark
Pd:I moved the builder.
Pd: I love the project

**Comment by Luyann** [comment]
https://drive.google.com/file/d/1PBJonIqbm7lFRj8ftt2cfalrC5ajslxA/view?usp=drivesdk

**Comment by yairm210** [comment]
I think I see the problem, I'll see what I can do
Thanks for contacting us!

**Comment by yairm210** [comment]
The code says the worker won't build an improvement if there's already an improvement there :\

Did the worker go there to build a farm after you made the landmark or before?

**Comment by zivvel** [comment]
Possibly related: if a worker is improving a tile, and it is moved away, the next worker to stop on that tile will automatically continue that improvement.

**Comment by yairm210** [comment]
That's a feature, and unrelated from what I checked

**Comment by yairm210** [comment]
Perry sure @ninjatao solved this already but not sure if it entered a released version

**Comment by ninjatao** [comment]
I think unfinished improvement can still replace great improvement in current version. Maybe we should add a option to stop unfinished improvement.
Another way to solve this is remove unfinished improvement on constructing a great improvement. Pushed a commit for that.

**Comment by yairm210** [comment]
Looks like this was dealt with then =)
Will enter 2.11.5

**Comment by ninjatao** [comment]
Found another problem about worker replaces great improvements. Please review the pr.
