### ISSUE TITLE
Fertilizer and Civil Service Techs Do Not Provide Extra Food

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#3713]
**Description**
As the title implies, the Technologies "Fertilizer" and "Civil Service" do not provide the +1 food that they are meant to provide on farms along fresh water.

**To Reproduce**
1. Simply build a farm on a tile beside fresh water like rivers.
2. Then have at least the Civil Service tech researched. You will then see how the farms were not at all boosted.

**Expected behavior**
Farms were supposed to provide +1 food upon researching the above mentioned technologies.

**Screenshots**
![Screenshot_20210319-020410_UnCiv](https://user-images.githubusercontent.com/61744611/111676392-132b3e00-8859-11eb-801c-c770bfa51269.jpg)
![Screenshot_20210319-020426_UnCiv](https://user-images.githubusercontent.com/61744611/111676444-20482d00-8859-11eb-971f-a0e55d3b5aea.jpg)
![Screenshot_20210319-020435_UnCiv](https://user-images.githubusercontent.com/61744611/111676493-30600c80-8859-11eb-93f8-5e722dde6a7b.jpg)
![Screenshot_20210319-020450_UnCiv](https://user-images.githubusercontent.com/61744611/111676536-3bb33800-8859-11eb-866d-f1e0d6cd0b67.jpg)
![Screenshot_20210319-020508_UnCiv](https://user-images.githubusercontent.com/61744611/111676745-73ba7b00-8859-11eb-80ae-120895588594.jpg)
![Screenshot_20210319-021402_Google Play Store](https://user-images.githubusercontent.com/61744611/111676796-7fa63d00-8859-11eb-879b-adb21369b171.jpg)

**Additional context**
Game version is 3.13.8, which as far as Google Play Store tells me at the time of writing this, is the latest version.

**Comment by GGGuenni** [comment]
Bug got introduced by changing "fresh water" to "Fresh water" in the TileImprovements.json in PR #3676.

**Comment by yairm210** [comment]
Gah!
Good catch! I missed that!

**Comment by yairm210** [comment]
Wait no, that was my fix
It SHOULD be Fresh water with a capital, since that's what appears in lakes and oasis
I'll see what's going on here

**Comment by bobabae** [comment]
Hello, new here but I believe the issue above is still not providing +1 food for farms along fresh water. Using latest version 3.13.8 (love what ya done with the game and have spent countless hours playing btw)

**Comment by RaynorST** [comment]
Does anyone know, if the problem is solved, when I download the new update?

**Comment by yairm210** [comment]
The problem is solved, you may be using a mod which has a similar problem
Latest versions are available from Google play, fdroid, and itch.io
