### ISSUE TITLE
Wonders and Tech Boost

### ISSUE THREAD

**Issue by WXrg911** [yairm210/Unciv#3719]
The image with huge wonder boost on tech is on standard speed. Singleplayer. With civ 5 expansion mod.

The other one is quick speed  with no mods. And multiplayer.

Actualy it might be cuz of the mod

![Screenshot_20210320-121856_UnCiv](https://user-images.githubusercontent.com/64699105/111858841-01d85380-8977-11eb-8b6c-2a1aeb9124d6.jpg)
![Screenshot_20210320-122228_UnCiv](https://user-images.githubusercontent.com/64699105/111858846-03a21700-8977-11eb-890d-ebe8f81dbaca.jpg)

**Comment by yairm210** [comment]
This is almost definitely a mod issue, since it had never happened in the base game.
