### ISSUE TITLE
Uranium not revealed?

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#372]
Got this comment from several people, need to check this

**Comment by ninjatao** [comment]
Uranium is revealed by "Atomic Theory" tech, which does not exist in game. >_<

**Comment by yairm210** [comment]
Welp

**Comment by Luyann** [comment]
And beacuse of that we can't build the power plant :P

**Comment by yairm210** [comment]
Changed to Nuclean Fission, entering 2.11.3
