### ISSUE TITLE
Fair AIs on hard difficulties 

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3727]
On Immortal difficulty, AIs spawn with 3 Warriors, one Scout, one Settler and one Worker. And on Deity, it's 2 Settlers and 2 Workers! But players always start with one Warrior and one Settler. I know it is meant to be very hard difficulties, but this is not hard, this is unfair. I think they should just play better, more declare wars (as they already do, on Emperor they declare war one time per game) and so on.

**Comment by yairm210** [comment]
"AI should be better" is not actionable.
Unless you have specific heuristics you suggest to name it better, this is not something I can actively work on.
