### ISSUE TITLE
Declaring war should reset the friendship boost from years of peace.

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3730]
When you declare war, you expect that they wouldn't like you anymore for years of peace. But even If you declare war, the civilisation still gives you points for years of peace. Even when the war ends, you still get the same friendship points, like the war never happened.

Also for #3727 (because I don't know where to say it, hope it's not annoying), yeah, "should be better" isn't very specific. Maybe it would be enough if they declared war more often (as they already do). Just if the start would be fair.

**Comment by yairm210** [comment]
No, it shouldn't. This is a deliberate design choice - years of good relations aren't immediately ruined by a single war.

**Comment by yairm210** [comment]
But I'll pool this to see the general feeling.

**Comment by jahodovykolac** [comment]
Maybe it should be continuous - like one war - decrease by a certain number, another wars - more decreasing
