### ISSUE TITLE
"Unresolved reference: unciv" on loading project on Windows

### ISSUE THREAD

**Issue by jgonyea** [yairm210/Unciv#3731]
**Describe the bug**
I'm attempting to build the application on Windows, but the Android studio is giving me an `Unresolved reference: unciv` error at the `unciv` portion of the following code in the build.gradle.kts file.:

```
 dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${com.unciv.build.BuildConfig.kotlinVersion}")
```

**To Reproduce**
1. Cloned project to D:\Documents\Unciv\
2. Checked out tag `3.13.10`
2. Opened Android studio, and pointed it at the above directory
3. Added a custom run task as described in the wiki
4. Intellisense throws me the above error

**Expected behavior**
No errors on loading the project

**Screenshots**
![image](https://user-images.githubusercontent.com/1057441/112092401-cce22180-8b6d-11eb-8c0c-d9b57b4d7d94.png)

**Additional context**
I'm very new to this building process, so I may very well have done something incorrectly.  I haven't attempted to build this on any other platform yet.

**Comment by yairm210** [comment]
I really don't know
Did you run gradle:build?

**Comment by jgonyea** [comment]
I've blown the project away and am starting from scratch again.  I'll report back later if it works or not.

**Comment by jgonyea** [comment]
The error didn't present itself this time, after checking out the 3.13.11 tag, and I was able to perform the desktop gradle build.  

Closing ticket.
