### ISSUE TITLE
World wrap ideas

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3733]
Only ideas, some may be hard to do (idk, not good at programming), I don't demand them

Idea 1: (mentioned in #3665) Map editor could be able to convert a non-wrapped map to a world wrapped map (and vice versa)
Idea 2: It would be cool if lands could generate on the wrap.

(Yeah I'm not very specific XD)

**Comment by yairm210** [comment]
1 is currently not an option - wrapped and non-wrapped maps are different in the number of columns they have
2 doesn't really give much benefit

**Comment by jahodovykolac** [comment]
Yes, I talked about the option 1 with GGGueni, it would include adding (or removing) ocean tiles on one of the edges
