### ISSUE TITLE
Reply to #3739

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3741]
First - I do have enough memory, I can hold even larger maps. If I load an older game with the same parameters, it works fine. I have problem only with newly created games.
Second - Isn't it weird that I wouldn't have enough memory one turn, and next time I would?

And yes I am on Android, no I don't use any mods.

**Comment by yairm210** [comment]
No, it isn't. The memory required depends on the number of objects in the game, and the number of objects grown over time as the game naturally progresses.
If you say that on previous games it worked, that is interesting. What have you changed? Did you change the number of civs, or city states? Try opening one of the old saves and creating a new game from within - it should retain all the parameters. Does that work?

Second - the comments are here for a reason... don't open another issue which is a continuation of another issue. We can continue the discussion in #3739.
