### ISSUE TITLE
Memory leaks very serious when you play the game for about 100 turns

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#3743]
Memory leaks very serious when you play the game for about 100 turns, and then the app will crash suddenly.
You can find this bugs:
Play the app for about 100 turns, and then you can check the memory usage of the app.

**Comment by ravignir** [comment]
The problem seem to be introduced with 3.13.11 update. The app does not empty memory, both VRAM and RAM.

**Comment by yairm210** [comment]
Good catch!
Problem solved, rolling out as 3.13.11-patch2
