### ISSUE TITLE
Multiplayer game stuck (I'm on turn 326 and my friend on 324)

### ISSUE THREAD

**Issue by hgcvm** [yairm210/Unciv#3756]
We're playing almost 10 months now and now, both of us are getting "Waiting for other player". He's on turn 324, and me on turn 326.

We're both on version 3.13.11. He's playing on Android and I'm playing on F-Droid version.

We have tried loading save games. When I load a save game (for example autosave turn 323 or any other save game), it loads that specific turn for a split second, and then jumps immediately back to turn 326.

What other information could I provide to resolve this issue? I could provide save games files or the game ID?

**Comment by yairm210** [comment]
Fixed in 3.13.12, please wait for the version rollout to reach you :)
