### ISSUE TITLE
Unciv disappeared from Google Play :/

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3762]
Soo... Unciv has disappeared from Google Play. I can't search for it, it's not in downloaded games, the link from readme.md doesn't work.

**Comment by jahodovykolac** [comment]
Tried on two devices, none of them works.

**Comment by skyace65** [comment]
I'm not seeing it either

**Comment by Bigrichman** [comment]
Same, it poofed off Google Play.

**Comment by jahodovykolac** [comment]
Okay, it's back again 😄
