### ISSUE TITLE
help about translation

### ISSUE THREAD

**Issue by subversive-eu** [yairm210/Unciv#3765]
Hi.

It's the first time i will try to pull request. I don't know how to do.

I have fork the Unciv repo, I do change in master/Unciv/android/assets/jsons/translations/French.properties

How to merge it in official repo by pull request ?

additionnal 

- for Aztecs  civilization cities are today/recent still in activity ? Do i have to put name of today ? or keep historical  name  of this civlizations ?

Thanks.

**Comment by jahodovykolac** [comment]
For the pull request part:
When you're at the file, tap edit (pencil) and edit what you want. When you're done, tap 'Propose changes' at the bottom. That will create a fork of Unciv on your profile. Then, you will see a box about creating PR. You will see a button 'Create a pull request'. And that's everything.

**Comment by subversive-eu** [comment]
@jahodovykolac  thx I hope i did it good.
