### ISSUE TITLE
(Android) time it takes to continue onto the next turn increases as you play

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3769]
**Describe the bug**
When you  play for around 250 to 300 tours, the time it takes to continue into the next tour increases a lot, to the point where it might take around 15-25+ seconds to just skip a turn
**To Reproduce**
Play for 300 turns with a few civilizations and a deck of city states on a large or medium map

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
the turn change delay is bound to increase but it in this case this is out of ordinary as it directly affects the quality of gameplay, to the point it is not fun to play anymore. i doubt if it is also the case for pc but for android it takes a lot of time, i have no idea if it is unoptimized for mobile
**Screenshots**
no screenshots
**Additional context**

**Comment by jahodovykolac** [comment]
That's normal, because civs have more units, more cities, more things to do, so it takes longer to calculate what they will do. You also take more time to do your turn when you have more progress, right?

**Comment by yairm210** [comment]
The turn length is dependent on the number of decisions that the AI needs to make, which in turn is directly affected by the number of units. The decision time scales linearly with the number of units, and therefore increases with the tunr number.
Specific changes to the decision making (to speed it up) are implemented when possible, but there's no trick to make things work as fast with 10 units as with 100.
