### ISSUE TITLE
New civilopedia style?

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3772]
I don't know, is this civilopedia style intentional? (The left bar not being round)
![Screenshot_20210410-165139_UnCiv](https://user-images.githubusercontent.com/79529669/114274502-efee4b80-9a1e-11eb-8c73-8f2ddc6e6eb9.jpg)

It happened after updating to 3.13.13.

**Comment by yairm210** [comment]
Yes.
