### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by turbocat2001** [yairm210/Unciv#3789]
I notice that the game has problems with fonts. They are always very ugly in both Windows and Linux. And on android everything is smoothed out and looks good. Is it possible in the future to make a choice of a custom font or is the problem in the game itself or the java machine?

**Comment by yairm210** [comment]
Because the size of good font files is around the same size as the entire game, the fonts are currently taken directly from the device itself.
Maybe in the future we could allow custom fonts, this isn't a common request at all

**Comment by turbocat2001** [comment]
Thanks. I would like to know which default font is used

**Comment by yairm210** [comment]
Windows 10's default should be Segoe UI
As for Linux, it completely depends on the OS, the version, customizations...

**Comment by yairm210** [comment]
After consideration, denied.
