### ISSUE TITLE
Egyptians (AI) walk on lakes (ground movement)

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#379]
I mean they don't bother embarking, just enter every lakelike the Red Sea.

**Comment by yairm210** [comment]
Fixed, will enter 2.11.3
Thanks!

**Comment by Am-per-Sand** [comment]
Now every AI enters lakes, only now they embark for the sake of appearance.

**Comment by yairm210** [comment]
See #410, #399
