### ISSUE TITLE
'It's your turn" doesn't seem to be working anymore for me

### ISSUE THREAD

**Issue by hgcvm** [yairm210/Unciv#3794]
**Describe the bug**
I'm not receiving the Android notification anymore when it's my turn. When I open the app, I sometimes see that I can play, and can then play my turn normally.

**To Reproduce**
1. Multiplayer opponent clicks 'next turn'
2. I'm not getting 'It's your turn'

I'm on version 3.13.13 Android 9.

I used to have this option working in the past. I think it stopped working when upgrading to 3.13.13 (via F-Droid), but I'm not 100% sure.
 
In the android notification settings, I have 'notifications on' for Unciv, I don't have any restrictions, nor did I change any settings in Android.

Is there any additional information I can provide to search the resolution to this problem? 
Thanks.

**Comment by yairm210** [comment]
Fixed by GGGueni in #3781, changes rolled out in 3.14.1 :)
