### ISSUE TITLE
Templated replacements for TileSetConfig

### ISSUE THREAD

**Issue by GGGuenni** [yairm210/Unciv#3801]
Sorry for the late reply. I'm currently a bit busy working on my bachelor thesis.
I created this issue because I didn't want to answer on a closed PR.

> Maybe we can add templated replacements, like "Hill+(resource)+(improvement): [ "Grassland", "Hill", "(resource)", "(improvement)" ]
That will both make sure we don't miss things and accommodate mods.

I thought about that and I really liked the idea. I discarded it because I thought it would make everything pretty complicated.
I currently have no clue where to start with templated replacements, to be honest, but I mean I can try.

**Comment by yairm210** [comment]
It's just an idea, there's plenty of other stuff to do, and none of this is time critical
Good luck on your thesis! :D

**Comment by yairm210** [comment]
I no longer think this is necessary, the current configuration handles the issues well
