### ISSUE TITLE
Mod translations don't appear in new game screen

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#3802]
I made translations for my mod, and they just don't appear.
I have seen the same with other mods that have also translation files, like ancient civs.

**Comment by SomeTroglodyte** [comment]
They *do* work, just not on the new game screen right after activating the mod. Haven't debugged any further.

**Comment by yairm210** [comment]
This is a result of the translation function taking the mods from the currently running game - and in the new game screen, there isn't one.
Can't think of a good clean fix right now.

**Comment by yairm210** [comment]
Resolved by #3802 :)
