### ISSUE TITLE
Multiple Nation Uniques

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#3804]
I request for the implementation of the hability for the game to support at least 2 Nation Unique. Because currently it doesn't work, it it, it just doesn't work, I don't know what I expected. So Yes, basically like civ 6.

An idea for this would be that the second unique is like "uniqueName2" and "uniques2" or something like that.

Tell me what you think about this!

**Comment by SomeTroglodyte** [comment]
Seems already possible. Have you looked at the Ancient Civilizations mod you mention in your other post? First nation - Sumeria -> 3 uniques. You get 1 title, 1 text wall, and as many effects as you want - not enough?

**Comment by ArchDuque-Pancake** [comment]
No, I know you can add multiple uniques, I have dome it myself.
I meant for separating different uniques, like civ6, to have to names for different uniques. Because for example,  Italy: "Italian Gastronomy: +2 food from every platation.  +2 movement for naval units", that is very ironic or confusing relating to the name.
So what I would like is to be able to give those 2 different uniques, a different name for each one.
![Screenshot_20210417-222337](https://user-images.githubusercontent.com/78449553/115133154-8f9a7380-9ff5-11eb-8079-443c9fc2c01c.png)

**Comment by yairm210** [comment]
The change to accommodate this would be too large and the value too small.
Closing as 'not in roadmap'.
