### ISSUE TITLE
Some buttons always look like inactive

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3814]
Pretty self-explaining
![Screenshot_20210419-134224_UnCiv](https://user-images.githubusercontent.com/79529669/115231041-653fd780-a115-11eb-9cc6-529e83d61b33.jpg)
![Screenshot_20210419-134239_UnCiv](https://user-images.githubusercontent.com/79529669/115231068-6c66e580-a115-11eb-8b8f-96bd404f2043.jpg)

On the second picture you can see the 'Show statistics' (Zobrazit statistiky) or 'Leave city' (Odejít z města) buttons for comparison

**Comment by yairm210** [comment]
That's how the buttons look in popups. This is quite different from inactive buttons, which are greyed out.
Not a bug as far as I'm concerned.
