### ISSUE TITLE
pretty awlful bug

### ISSUE THREAD

**Issue by lucasdark1236** [yairm210/Unciv#3816]
Civil Service unlocked but the farm doesn't not meet the requirements of +1 food if it on fresh water tile
PS: the desert farm have the petra buff

![Screenshot_20210418-011057](https://user-images.githubusercontent.com/70103922/115267461-c85c5900-a16b-11eb-9535-4b98bc0479b8.jpg)
![Screenshot_20210418-011050](https://user-images.githubusercontent.com/70103922/115267525-d90ccf00-a16b-11eb-8569-8f5ad2d822ae.jpg)

**Comment by yairm210** [comment]
Are there any mods active?

**Comment by yairm210** [comment]
Okay, yes, I see bison there.
This is a problem with the specific mod you're using, works fine in base game.

**Comment by yairm210** [comment]
Please open an issue in the github page of the mod
