### ISSUE TITLE
All Missiles Act Like Nuclear Missiles

### ISSUE THREAD

**Issue by TheRexYo** [yairm210/Unciv#3835]
In the Vanilla Civ5, there are missile-type units that do not act like nukes (Guide Missiles, for example). In Unciv, all missiles will work like Nuclear Missiles (creating fallout, one-shotting units and cities) regardless of what you give them for uniques. This is an issue for modders especially (since a one-use ranged unit isn't too uncommon of an idea), but it also applies to vanilla Civ5 behaviors, since (as I mentioned before) there are indeed Missile units that don't act like Nukes.

1) Create a new type of missile unit.
2) Give it the "Nuclear weapon" unique
3) Create another new type of missile unit.
4) DO NOT give it the "Nuclear weapon" unique. 
5) Observe - the second missile unit will act like a Nuclear Missile despite not being one, matching the behavior of the first one.

What I Expected to Happen:
- A missile without the "Nuclear Weapon" unique would work like the "Guided Missile" unit in vanilla Civ5. It would not create fallout, and would use its Ranged Strength to damage targets instead of killing them instantly.

Thanks for reading.

**Comment by SomeTroglodyte** [comment]
True. The unique only prevents construction when the global option forbids nukes. Battle.attack hard-codes UnitType.Missile to function nuke. Not sure how to deal with SpecificUnitAutomation.automateMissile or bottombar simulateNuke though. Also, one can find preparations to add the vanilla guided missiles - author could have plans for this. So, I'll not attempt this soon.

Should this move to #663?

**Comment by TheRexYo** [comment]
Perhaps the Missile class can be split into two types (kinda like WaterMelee and WaterRanged, which both count as 'Water' units); NuclearMissile (for Nukes) and BallisticMissile (for standard Missiles).

**Comment by TheRexYo** [comment]
I might be able to code this when I have time, but I doubt that's going to happen any time soon.

**Comment by TheRexYo** [comment]
I just implemented a potential fix on a private repository. I made it so that there are three types of missiles; Missile (the legacy missile for compatibility purposes; may be converted to its own standard missile type in the future), NuclearMissile (the replacement for Missile), and BallisticMissile (the non-nuclear missile type). So far, it seems to work, but I haven't tested Nukes out yet, just non-nuclear missiles. I'll get back to you if I get it working, probably in the form of a pull-request.

**Comment by yairm210** [comment]
I don't think there's a need to split missiles. All we need to do is make the Nuke function only happen from units with the 'nuclear weapon' unique.
IN FACT even the self destruct can be made into a unique so it'll be relevant for all attack types.

**Comment by TheRexYo** [comment]
So, despite you adding the code for Missiles not being nukes automatically, they're still all nukes. Has that been released yet, or is it only the SD unique?

**Comment by yairm210** [comment]
Only the self destruct. Otherwise this issue would have been closed ;)
