### ISSUE TITLE
Denmark greeting typo

### ISSUE THREAD

**Issue by RealGrouchy** [yairm210/Unciv#3837]
![Screenshot_20210416-163428_UnCiv](https://user-images.githubusercontent.com/61196433/116088061-82255f00-a66f-11eb-9d75-74236089c8ad.jpg)

Typo in greeting (I was playing as Polynesia): "Harad" --> "Harald"

**Comment by SomeTroglodyte** [comment]
In Nations.json, no other occurrences of the typo. "Translate" using English.properties or in-depth fix touching all translation files?

**Comment by yairm210** [comment]
I'll fix this across all instances
Thanks, good catch!
