### ISSUE TITLE
Bigger target on "next city" button in City view

### ISSUE THREAD

**Issue by RealGrouchy** [yairm210/Unciv#3838]
![Screenshot_20210425-043826_UnCiv~2](https://user-images.githubusercontent.com/61196433/116088853-40e17f00-a670-11eb-8583-d5466c7e3dc9.jpg)

When I am in the City screen, the buttons for next/previous city are only the little triangles at the ends of the city name bar. It often takes me two or three tries to hit it. I would prefer if the target for this button were the entire end of the bar (highlighted in white in the screenshot)

(I'm using a Samsung Galaxy Note 20.)

- RG>

**Comment by SomeTroglodyte** [comment]
Quick note:
```
val prevCityButton = Table() // so we get a wider clickable area than just the image itself
```
... the comment implies the intention is good.

The debug mode shows the following:
![City picker debug](https://user-images.githubusercontent.com/63000004/116127083-b62c6e80-a6c7-11eb-97bf-76e8b76c3857.png)
... and a click in the red square is not sufficient, you really need to hit the triangle's minimal bounding box. Clicking in the red square actually gets routed to the TileGroupMap's ScrollPane, which doesn't have a click handler. And replacing the Table() with Button(...) will make the entire red box clickable - while also changing size and visuals. A job for someone better than me.

**Comment by yairm210** [comment]
Huh
Maybe the table's .touchable isn't set to Touchable.enabled?

**Comment by SomeTroglodyte** [comment]
> Touchable.enabled?
Hit the nail on the head. It defaults to childrenonly, and enabled fixes this...

**Comment by SomeTroglodyte** [comment]
Offered #3840 though it's not my merit
