### ISSUE TITLE
Please fix latest tag so F-Droid can build it

### ISSUE THREAD

**Issue by jspricke** [yairm210/Unciv#3848]
The latest version 3.14.3-patch1 is tagged as 3.14.1-patch1:
https://github.com/yairm210/Unciv/commit/86fafd59db691057b5e177958f200aaa670bfca6
Can you please fix this?

**Comment by jahodovykolac** [comment]
It will be fixed in the next version.

**Comment by jspricke** [comment]
Should be enough to push a 3.14.3-patch1 tag, could you do that?

**Comment by yairm210** [comment]
We've pushed 3.14.4 :)
