### ISSUE TITLE
Ai evaluate peace treaty bug?

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#385]
As far as I can understand, evaluatePeaceCostForThem() returns a positive value if our strength is stronger than theirs, and a negative value otherwise.
So, maybe it should returns 1000 when enemy has no fighting unit?

fun evaluatePeaceCostForThem(): Int {
        val ourCombatStrength = Automation().evaluteCombatStrength(ourCivilization)
        val theirCombatStrength = Automation().evaluteCombatStrength(otherCivilization)
        if(ourCombatStrength==theirCombatStrength) return 0
        if(ourCombatStrength==0) return 1000
        if(theirCombatStrength==0) return -1000 // Chumps got no cities or units
        if(ourCombatStrength>theirCombatStrength){
            val absoluteAdvantage = ourCombatStrength-theirCombatStrength
            val percentageAdvantage = absoluteAdvantage / theirCombatStrength.toFloat()
            return (absoluteAdvantage*percentageAdvantage).toInt() * 10
        }
        else{
            val absoluteAdvantage = theirCombatStrength-ourCombatStrength
            val percentageAdvantage = absoluteAdvantage / ourCombatStrength.toFloat()
            return -(absoluteAdvantage*percentageAdvantage).toInt() * 10
        }
    }

**Comment by yairm210** [comment]
That's this line

if(theirCombatStrength==0) return -1000

No?

**Comment by ninjatao** [comment]
a positive value if our strength is stronger than theirs, and a negative value otherwise.

If so, when their strength == 0, should return 1000(instead of -1000), right?

**Comment by yairm210** [comment]
Hm, I think you're right and the church's are backwards
