### ISSUE TITLE
Display option buttons by the minimap do not change visible state after underlying option is changed via options screen

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#3854]
Look at the display yields button to the left of the minimap and remember its colour
Open the menu, go into the options screen, toggle the show tile yield option
Back on the world screen observe unchanged colour
Click on it - it will keep its colour and thus be back in sync

It's pretty clear why this is so - I'll work on it. There may soon be a third way to toggle those options, which is why I noticed this.

Tech speak / Question:
So the minimap holder needs to either poll the settings for changes (urgh) or be told about changes from outside. Would you tend to favour a simple syncoptions() (name debatable) api -or- something like setOption(yield/resources/worked, newvalue) so it does the rest of the work too and that would be reusable by other worldscreen code? Or both?

**Comment by yairm210** [comment]
I think that the button should update on WorldScreen.update().
It calls the minimapWrapper update, minimapWrapper update updates the minimap - AND YET the toggle icons are not affected by the update.

That's the source of the problem, and also the best fix for it.

**Comment by SomeTroglodyte** [comment]
Yup, your suggestion is another valid approach - updates stuff not in need of updating from time to time, but that's cheap enough. Will ponder whether any of the changes in the PR are worth keeping then...
