### ISSUE TITLE
Idea: World Wrap explanation popup

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3856]
**Is your feature request related to a problem? Please describe.**
The "World wrap" name is not so self-explaining (or maybe it is, I'm not an English person) and it's not so easy to translate to some languages

**Describe the solution you'd like**
An info popup in places where World Wrap is toggled. It would explain what exactly World Wrap does. And also it would make translating easier - the "World Wrap" name itself will be the same, but it would be explained in the popup.

**Describe alternatives you've considered**
Similar to the info popup in multiplayer screen.

If it's a bad idea, it's okay. Just a suggestion.

**Comment by yairm210** [comment]
I think not - it's both testable and google-able, and I don't see anywhere good to place this in the new game screen - there's not a lot of space there to start with
