### ISSUE TITLE
UI issue: garrison icon hides bombard target

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3863]
As seen in my screenshot, when I activate my city (Osaka) to select a bombard target, the icon for my garrisoned Samurai blocks me from being able to select the horseman one tile to the north of the city. I finally managed it by zooming in as far as possible, but I still had a very small target to hit, and accidentally selected the Samurai several times before actually making the bombardment.

![img1](https://user-images.githubusercontent.com/1423934/116800101-e18dcf80-aab2-11eb-8595-08dd1aa0c989.png)

**Comment by ArchDuque-Pancake** [comment]
Not that big of a problem, just select the city for bombarment, then click on an empty tile and the icon of the unit will be gone.

**Comment by foolishgrunt** [comment]
Okay, just tried it and that does work. I had thought that clicking an empty tile unselected the city, but looks like I was mistaken.

I'm fine with that as a workaround to keep the UI from having to be reworked.
