### ISSUE TITLE
AI thinks I kept an expansion promise that I broke

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3865]
***My apologies, I meant to report this months ago, but it slipped my mind again and again. Please close if this has been addressed in recent updates.***

Genghis asked me not to expand near him anymore, and I agreed. Then I expanded near him again, and the diplomacy screen showed that I had broken my promise. Then several turns later, I noticed that the diplomacy screen *also* showed that I had kept my promise.

If I had to guess, I would say that the game automatically triggered the "fulfilled promise" condition after the proper number of turns without first checking to see if I had broken the promise.

![img1](https://user-images.githubusercontent.com/1423934/116800740-b1492f80-aab8-11eb-838f-b7bee342c419.png)

**Comment by SomeTroglodyte** [comment]
@anybody - `NextTurnAutomation.onCitySettledNearBorders` line 538:
```
                diplomacyManager.setModifier(DiplomaticModifiers.BetrayedPromiseToNotSettleCitiesNearUs, -20f)
             +   diplomacyManager.removeFlag(DiplomacyFlags.AgreedToNotSettleNearUs)
```
**or** `DiplomacyManager.nextTurnFlags` line 402:
```                    DiplomacyFlags.AgreedToNotSettleNearUs.name -> {
             +           if (!hasModifier(DiplomaticModifiers.BetrayedPromiseToNotSettleCitiesNearUs))
                            addModifier(DiplomaticModifiers.FulfilledPromiseToNotSettleCitiesNearUs, 10f)
                    }
```
...??? Somebody familiar with the system evaluate this please.

**Comment by yairm210** [comment]
> @AnyBody - `NextTurnAutomation.onCitySettledNearBorders` line 538:
> 
> ```
>                 diplomacyManager.setModifier(DiplomaticModifiers.BetrayedPromiseToNotSettleCitiesNearUs, -20f)
>              +   diplomacyManager.removeFlag(DiplomacyFlags.AgreedToNotSettleNearUs)
> ```
> 
> **or** `DiplomacyManager.nextTurnFlags` line 402:
> 
> ```
>              +           if (!hasModifier(DiplomaticModifiers.BetrayedPromiseToNotSettleCitiesNearUs))
>                             addModifier(DiplomaticModifiers.FulfilledPromiseToNotSettleCitiesNearUs, 10f)
>                     }
> ```
> 
> ...??? Somebody familiar with the system evaluate this please.

The first :)

**Comment by SomeTroglodyte** [comment]
first is always best, kinda thought so :stuck_out_tongue_winking_eye: 
... but half-seriously: [someone else](https://en.wikipedia.org/wiki/Somebody_else%27s_problem) is welcome to do this as I have a hole where the picture on how to efficiently **test** the fix should be ... At least not today.

**Comment by SomeTroglodyte** [comment]
...Why can't Discord develop a _trustworthy_ client for such discussions? (Windows: Defender alarm it wants so install a system-wide protocol handler, Linux: not present in distro repositories -> the latter even more suspicious than the former)

.... waitaminute, I have the AVM's I could install the ~cr~ - ahem, app in, now that's an idea ...
