### ISSUE TITLE
Feature Idea: Ultimatums

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3868]
**Is your feature request related to a problem? Please describe.**

We have to declare wars when we want only one city of a civilization, or a resource of a civilization

**Describe the solution you'd like**
just like you give open borders as an offer in a trade request you should be able to offer a trade request with an ultimatum in it, demanding certain resource or city, or to force a civilization into declaring war on one another, you should also be able to offer other stuff alongside your ultimatum as to increase the chances of the opposing civilization to accept it. also an ultimatum should damage the relations between civilizations

**Describe alternatives you've considered**
N/A

**Additional context**
I would illustrate an example trade screen but i couldn't.

The offer for an ultimatum should have the color of declare war button, tinted more orange

**Comment by ravignir** [comment]
This should be under Demands as one-sided trade, just like it is in civ5.

**Comment by yairm210** [comment]
Please add as a comment to #663
