### ISSUE TITLE
Certain UI Elements not Pressable

### ISSUE THREAD

**Issue by BFUR64** [yairm210/Unciv#3882]
For some reason, I can't press certain UI Elements in my Android phone. Oppo A5s. Not a touchscreen problem I checked.
![IMG_20210506_133819](https://user-images.githubusercontent.com/78485623/117247149-5cb70300-ae70-11eb-8207-6134f339ec3f.jpg)
![IMG_20210506_133808](https://user-images.githubusercontent.com/78485623/117247288-91c35580-ae70-11eb-8ea7-a77bbcd7d64a.jpg)

**Comment by yairm210** [comment]
Fixed in 3.14.6-patch1
