### ISSUE TITLE
Settler Food to Production conversion

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#3883]
Food converts to Production at 1:1 rate in unciv and it should be much lower as in civ5:
https://civilization.fandom.com/wiki/Settler_(Civ5)

> Any surplus Food  in the city is converted into Production at a diminishing rate, with a point of  Production granted at the first, second, fourth, and eighth surplus Food  and every fourth Food  onward.

**Comment by yairm210** [comment]
This is extremely random, and would be difficult to convey to players in-game.
I also don't see the gameplay value in such a change.
More negatives that positives, denied.

**Comment by ravignir** [comment]
It is just quite easy to spam settlers right now, especially if you have good growth tiles - which creates quite an imbalance if someone starts in worse location, like tundra. Even 2:1 conversion rate would be better - and should be simple to understand.

**Comment by yairm210** [comment]
2:1 sounds fine
