### ISSUE TITLE
Feature to be able to command  **selected** workers to build/remove roads/railroads between tiles, city states-cities, cities-cities, city-civilization city

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3886]
# **Is your feature request related to a problem? Please describe.**
this feature does not solve a problem but is rather a quality of life feature, it is always frusturating when you need to manually connect a city of yours to a city state, it takes like 10 turns in which you have to manually command every worker to do one specific tile improvement, or in another example, i might have automatically build roads disabled, i for instance have few cities that are going to connect to other cities through harbors, i should be able to specifically command a group of workers to remove roads between these  two specific cities, or build roads between two cities if they are not already connected by harbor.

# **Describe the solution you'd like**
there should be a button when you press on a worker, just like automate button for instance, when you press that button, that worker gets added to a list ( there is only one list), when you have selected at least one worker, a button appears up from top left corner of the screen ( like the policies button ) when you press that button it should look like this with two buttons:
- Select Tiles to (build roads button, "**Build Roads**") or (remove roads button, "**Remove Roads**") between.

either one opens up a screen that lets you select point a and point b, and will command these workers to do that specific task unless the player has canceled their duty to build those roads ( like stop automation button ). After selecting point a to point b, you press apply, when that is pressed that list that i mentioned earlier gets cleared and those workers are assigned those duties. also since it gets cleared, you can command multiple groups of workers to do specific tasks in one turn

# **Describe alternatives you've considered**
N/A (?)

# **Additional context**
if this is too out of context for the civilization games genre, instead add this as a feature that is toggleable in the settings window just like automatically build roads option.

**Comment by AdityaMH** [comment]
This feature was added from option menu.

**Comment by logicminimal** [comment]
> This feature was added from option menu. 

if you mean workers replace improvements and workers build roads then you'd be wrong as what i meant was  to be able to command a group of workers to build a road between tile a and tile b

**Comment by yairm210** [comment]
This is already in the original list in #663
