### ISSUE TITLE
Please update translation template for Mod window

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#3888]
**Describe the bug**
Please add the following lines to the translation template:
Current mods = 
Downloadable mods = 
Next page = 
Open Github page = 
Enable as permanent visual mod = 
Disable as permanent visual mod = 
Installed = 
Downloaded! = 
Could not download mod = 

They are needed for the Mod window

**Comment by ArchDuque-Pancake** [comment]
Also, "change ruleset" for the map editor.
