### ISSUE TITLE
Map conversion popup

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3890]
**Is your feature request related to a problem? Please describe.**
I have a map created before this update. So, it has Hills as terrains. The editor is still old, it doesn't allow me to put Hills as terrain features, but I would like them in my map.

**Describe the solution you'd like**
When openening a map, a popup offering me conversion to HATF (hill as terrain feature).

**Describe alternatives you've considered**
A popup similar to editing map when setting an incompatible ruleset.

**Comment by yairm210** [comment]
I think that this is so niche that it's not worth the effort. Upgrade and you can place hills as you may so wish.

**Comment by jahodovykolac** [comment]
Okay, I wrote this when editor was still using old hills, now it's fixed.
