### ISSUE TITLE
Load game screen buttons are part of saved games list

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3892]
**Describe the bug**
The buttons like Delete save, Load from clipboard etc. are moving together with save files.

**To Reproduce**
1. Save some games or have a long list
2. Go to 'Load game'
3. The buttons are not on the top, they're in the middle of the list, moving together with the list.

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
The list is always on the same place.

**Screenshots**
![Screenshot_20210507-111411_UnCiv](https://user-images.githubusercontent.com/79529669/117427543-6f3f4400-af25-11eb-8ed1-0fad268d5c22.jpg)
![Screenshot_20210507-111417_UnCiv](https://user-images.githubusercontent.com/79529669/117427565-76fee880-af25-11eb-9478-59ff5b0eea1b.jpg)

**Additional context**
I saw it on 3.14.6-patch2, any Android

**Comment by SomeTroglodyte** [comment]
I've been itching to fix the missing padding between three of the widgets - so when i get around to that I might have a look. 

Of course, ModManager would have had the same problem and has patched its way around the single ScrollPane built into PickerScreen, so some system to allow all PickerScreens to have more control over their central area would be in order...

**Comment by SomeTroglodyte** [comment]
Other screens plural? I remember `ModManagementScreen` - what else? Point is, Save/Load need columns scrolling independently, not no scrolling at all - like `ModManagementScreen` does for  2 of its 3 columns. But if several `PickerScreen` subclasses need to disable features of their superclass, then the superclass should offer better features... Or we could do another layer of subclasses - PickerScreenBase, PickerScreenSingleColumn, PickerScreenTwoColumn, PickerScreenThreeColumn...

**Comment by yairm210** [comment]
If anything, all it needs is a function of disableScroll(), or maybe a boolean isScrollEnabled=true that can be set to false. An entire new class is overkill :)

**Comment by SomeTroglodyte** [comment]
Should have looked at the sources earlier - I ass-umed this screen didn't have a separate scrollpane for the existing saves, but it does -> you're absolutely right. And a helper in the parent class to 'set up' a multicolumn topTable for its clients is overkill.
