### ISSUE TITLE
Save to custom location: Not obvious to user it disables normal autosaves

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#3898]
The 'custom save location' feature on Android imHo does not follow the principle of least surprises.
- Once used on a game, autosaves stop working normally, by intentional design
- This distinction is not user-visible anywhere I can find
- autoSaveSingleThreaded now overwrites the set external file, creating the potential confusion that a file name indicates one turn number but contains another
- Manual saves still go to the normal location without reactivating the normal autosave feature

Having a "sync" and being able to import/export are (should be) two distinct concepts and you really can't assume which of these a user expects with the current display and wording - I for one would have expected the import/export variant.

We should reach a consensus - do we want a) sync, b) imp/exp or c) both

I've marked this as bug because even choice (a) would need work, namely to display the fact sync is active including the chosen path (even if it's barely human readable) on the save/load screens (at least load, that's where you're looking for history but won't find any)

As the original author has not contributed for a few months (hey in case you read this: great work!) - I think I understand the code enough to implement our choices, but some help / brainstorm might be welcome.

Choice a):
Suggestions for UI? Ideas how to make the URI (like `content://com.android.externalstorage.documents/document/primary%3ADownload%2FMyFile`) more palatable? Does Android API have a displayname function for that? Leave as is? Regex replace? Extract the package ID, translate via pm, add the part starting with first `%` ???

Choice b):
GameInfo.customSaveLocation: Ignore and leave empty, right? We'd need a new place to store the initial location hint (is that even implemented?) when re-opening the external picker -> game settings?

Choice c):
Even more questions...

**Comment by yairm210** [comment]
If I understand you correctly, I feel that sync would require a detect-changes-and-overwrite, and also that it could go both ways... neither of which are simple to implement, or - as you would - explain.
import/export sounds like the way to go.

**Comment by SomeTroglodyte** [comment]
True, I meant a kind of half-sync. What we got is: You have a cloud provider implementing the document interface (I'm not paying attention to my choice of words here, so the proper nomenclature may be wildly different) - You choose to save your game to that provider. Now, the autosave goes there, too. You could open the game any time on another device (using custom location) and the state would be very close to what the first device has. Full sync would mean the second box polling the save and auto-loading it similar to what multiplayer does, I would guess. Given how awfully slow the SAF is, I wouldn't recommend that.

So - we should plan to implement choice (b) then. Any coder willing to start please indicate here, can't promise some timeframe to do it myself...

**Comment by SomeTroglodyte** [comment]
Need help here. 

The 'standard' `GameSaver.saveGame()` now has 5 params. `gameInfo` and `GameName` - OK so far. Then the multiplayer flag. Then a Boolean `forcePrompt` and a `saveCompletionCallback` both of which _none_ of the callers use.

If `saveGame()` gets a `gameInfo` which contains a `customSaveLocation` (set whenever a game is custom saved _or_ loaded and never cleared - except for new games of course), and the platform reports custom location support, then the save is redirected to this location - silently as the forcePrompt param defaults to false and is never set. Even for multiplayer.

**Question**: Is the use of the save/load screens reliably disabled in multiplayer? In which case the redirection to custom location would be moot. If not - do players use this to bypass dropbox and set their own multiplayer cloud storage?

I would remove the custom location specific code from `saveGame()` altogether including the `forcePrompt` parameter. I would leave in the tracking - storing a custom location a game was saved to / loaded from at some time in GameInfo but never use it - maybe some day this helps someone. This would then take only a small change to autosave to make custom location support a pure import/export feature, and need zero change to the platform-specific `CustomSaveLocationHelper` implementations.

Am I overlooking something? Any **hints**? Pros/Cons to leaving custom location tracking in?
