### ISSUE TITLE
Enlarged mini-map button

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3911]
For Android, Big problem if i play on huge world. I can't see minimap clearly or selected area on minimap because too tiny.

**Comment by SomeTroglodyte** [comment]
Can be closed as fixed/improved in 3.14.9 (sorry again for not linking the PR)

**Comment by AdityaMH** [comment]
I mean button near minimap to enlarge minimap like show all tile status.
But for me, enough for this moment.
