### ISSUE TITLE
Create citadel crash

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3918]
**Describe the bug**
Create citadel will crashed only if the great general puts it around the water (lake, ocean, or coast).

**Comment by SomeTroglodyte** [comment]
Not enough info to reproduce. I _can_ build a citadel next to coast. Please demonstrate.

**Comment by AdityaMH** [comment]
New crash occurred.
https://youtu.be/Aymt9ctCAdk

This video will be deleted if problem solved

**Comment by AdityaMH** [comment]
[Mongolia -  286 turns.zip](https://github.com/yairm210/Unciv/files/6462629/Mongolia.-.286.turns.zip)

**Comment by SomeTroglodyte** [comment]
Aha! That's a bug in Civ5ExpansionMod - @k4zoo hasn't yet updated the Citadel's uniques to the current format.

You see - the option to build a citadel there shouldn't be on in the first place, but your mod-changed ruleset allows it.

Though I suppose we should harden `takeOverTilesAround` against the documented prerequisite that at least one tile in the target tile's neighbors is owned by the General's civ not being fulfilled... Will do. One of these days.

And as I said this has nothing to do with water, be it lake, ocean or coast.

**Comment by SomeTroglodyte** [comment]
PR 3923 hardens the take-tiles code against mods dropping the 'Can be built just outside your borders' unique for Citadels. Thanks @AdityaMH.

**Comment by SomeTroglodyte** [comment]
Also [submitted the unique change to the mod as PR #33](https://github.com/k4zoo/Civ5ExpansionMod/pull/33)

**Comment by AdityaMH** [comment]
Can't wait for release.

**Comment by AdityaMH** [comment]
Please don't close this issue. this bug still happen in latest version.
