### ISSUE TITLE
Civilopedia Descriptions

### ISSUE THREAD

**Issue by TheRexYo** [yairm210/Unciv#3920]
Currently, there is no way to add text to entries in the Civilopedia. This means that the flavor text (history, real world facts, strategies, etc.) present in vanilla Civilization games is nonexistent in Unciv.

It would be nice if the json entries for different assets (units, policies, techs, buildings, and so on) included a "description" string field for the main description and a "entries" array that stores string entries that can be opened as individual pages in the civilopedia, the latter of which is done mostly to keep pages from becoming too complex.

**Comment by ArchDuque-Pancake** [comment]
This is a good idea. I had thought that there could be a button that sends you to that info.
And even you could display the unit or improvement tile there.
![imagen](https://user-images.githubusercontent.com/78449553/117875737-23173b00-b268-11eb-8b51-41a35180d62d.png)

**Comment by AdityaMH** [comment]
And for newbie player, sometime they can't plantation a luxury resources inside jungle because need remove jungle first  or can't mining marble because need quarry.
This lack description can making newbie confused sometimes (expect ever play civ5).

**Comment by AdityaMH** [comment]
But not for android user, @SomeTroglodyte

**Comment by SomeTroglodyte** [comment]
![image](https://user-images.githubusercontent.com/63000004/118373832-20467e00-b5b9-11eb-80d4-8e1d99b50142.png)
The red star and the http link are only there to test if my invented markup and renderer can do it, but - yes, the links work.

**Comment by SomeTroglodyte** [comment]
Oh, and as a patch this is a whopping 43kB, so it's hard to check.
    **Reviewers and testers welcome...** 
Just check out the branch [SomeTroglodyte:Civilopedia-Flavour](https://github.com/SomeTroglodyte/Unciv/tree/Civilopedia-Flavour) from my repo in studio and go. I've already explained how that is done elsewhere (if you have Android Studio already set up).

**Comment by SomeTroglodyte** [comment]
How Nations could look like (code not pushed, uses leader portrait mod):
![image](https://user-images.githubusercontent.com/63000004/118397046-8501e700-b652-11eb-8679-2fd6709bbe81.png)

No, getting 'ruleset object' info out of a unique to enable linking it is not easy enough for now.

**Comment by AdityaMH** [comment]
I really like that. And don't forget about diplomacy screen add this if this real project. But all mod need update a lot after that, or that will be crash/blank without text.
Or another solution is using "if variable situation", if json not complete/null/invalid will be lead at default text.

**Comment by SomeTroglodyte** [comment]
No, mods won't crash if they don't have leader portraits. The feature is already in main `master`, used only on the diplomacy screen. Haven't seen it in action so far. Remember you can use 'permanent visual mod' on '[Unciv-leader-portrait-mod-example](https://github.com/yairm210/Unciv-leader-portrait-mod-example)' to get the images into an existing save.

**Comment by SomeTroglodyte** [comment]
[Got all of the 'pedia decorated](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Debug%20apk's/Unciv-debug-Civilopedia-Flavour-002.apk)... Not perfect, getting an image for terrain that doesn't spill out of its bounding box isn't trivial, and some minor stuff. Translations untested but certain some will break - when the "key" is defined with leading or trailing spaces I break them as those are a pita anyway.

A few samples:
![image](https://user-images.githubusercontent.com/63000004/118553580-c84a7b80-b760-11eb-9c30-9edf56eee4fe.png)
![image](https://user-images.githubusercontent.com/63000004/118553601-cf718980-b760-11eb-8173-85644d108257.png)

**Comment by SomeTroglodyte** [comment]
OK last one - if you follow my apk link there's a build 003 which links into civilopedia from the world screen in two places - one is clicking unit name bottom-left will first center the unit and when it's already centered - 'pedia page. Secont is most lines of the tile info center-right. Have fun. For sources - see #3943.

**Comment by SomeTroglodyte** [comment]
And here's how this code could render another old idea:
![image](https://user-images.githubusercontent.com/63000004/118723966-5476a480-b82e-11eb-809e-f4b665c7c0d9.png)
Pity libGdx scales for performance not quality, so this looks not so good on lower resolutions.

**Comment by AdityaMH** [comment]
> How Nations could look like (code not pushed, uses leader portrait mod):
> ![image](https://user-images.githubusercontent.com/63000004/118397046-8501e700-b652-11eb-8679-2fd6709bbe81.png)
> 
> No, getting 'ruleset object' info out of a unique to enable linking it is not easy enough for now.

![Screenshot_2021-05-30-16-34-54-964_com miui gallery](https://user-images.githubusercontent.com/33791472/120099348-23b73900-c165-11eb-880b-5ff4891e2b1b.png)
what do think about this.
I collecting leader face from google and then edit all their face. as unciv theme (civ game with pixel graphic).

I want this unciv have leader portait too, and place them on diplomacy screen, greeting screen, and civilopedia.

Not all leader are completed yet.

I'm will delete this after if unacceptable.

**Comment by SomeTroglodyte** [comment]
Well, having the portrait on the _greeting_ is somewhere on my list, they already appear in diplomacy, and the civilopedia WIP has them, we're getting there.

As for a complete set - you could try the scraper on [my demos page](https://github.com/SomeTroglodyte/Scratchpad/tree/master/Demos) - gives you everybody right from the fandom wiki.

**Comment by AdityaMH** [comment]
That's sure, will be illegal activity if patch them on this game to public.
But we talking about use to everyone.

> Well, having the portrait on the _greeting_ is somewhere on my list, they already appear in diplomacy, and the civilopedia WIP has them, we're getting there.
> 
> As for a complete set - you could try the scraper on [my demos page](https://github.com/SomeTroglodyte/Scratchpad/tree/master/Demos) - gives you everybody right from the fandom wiki.

It's say need phyton3?
So, we need additional third party (app like termux) or just move them to asset and set it as permanent visual mod.
And again, we need online to show picture too, because source from fandom?

**Comment by SomeTroglodyte** [comment]
Python is a normal resource on modern OS, and those still preferring python 2 should be castigated. I 'speak' bash and powahshell, but believe me, if you have to do the same things in both you'll prefer python, too... 

As for illegal, no. I simply reserved the right to _not_ check the validity of fandom's use of their sources myself, just assuming them. Scraping their publicly available images is certainly perfectly legal for personal uses as long as browsing their site is. Thus the script and not a premade mod. It doesn't do anything you couldn't do with your browser.

Yes, simply move the result as a mod. 'simply' means simple on desktop - on 'droid you'll need root or adb and the knowledge to use it. Or the chuzpah to upload the folder to a repo and mark it as mod.

And your last sentence - no idea what you mean.

**Comment by AdityaMH** [comment]
1. That means it can not be implemented into this game. 

2. You're right, I doubt the copyright issue in fandom. They posted pictures of a game for wiki, while Nintendo sue (free download content) website owners hundreds of millions of dollars for using a 1990 mario bros image in the header of its website.
So we are not exposed to copyright abuse as long as they are still using their images.

3. Ah, need rooting device. Better not.

4. I mean the picture came from a website not from a folder or application, so does it have to be online every play of this game?

**Comment by SomeTroglodyte** [comment]
3 - actually you need to copy the files to a place the game sees them. No idea whether you have write access to (storage)/Android/data/com.unciv.app without root, maybe maybe not, haven't had the need to know that in a while.
4 - No, a scraper = https://en.wikipedia.org/wiki/Web_scraping means you fetch a copy

**Comment by yairm210** [comment]
This is done
