### ISSUE TITLE
Some tiles don't look correct.

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3926]
I know that FantasyHex is being updated, just giving a feedback.
Grassland+Jungle/Forest+Fallout looks only like Grassland
Plains+Forest/Jungle+Fallout looks like Plains
Plains+Hill+Fallout+Silk looks like Plains+Hill+Silk
Plains+Forest+Fallout+Deer looks like Plains+Deer

So yeah it's mostly Fallout not showing and hiding Forest or Jungle.
I'll give some pictures if needed. Also I noticed that Fallout is not placeable in Map editor. Is that intentional?

**Comment by logicminimal** [comment]
also plains , tundra + hill is just gradslands + hill

**Comment by jahodovykolac** [comment]
Also Plains+Wheat+Farm looks like Desert+Wheat+Farm

**Comment by jahodovykolac** [comment]
> also plains , tundra + hill is just grasslands + hill
Are you sure you are on the version that adds Hills as terrain features?

**Comment by logicminimal** [comment]
> > also plains , tundra + hill is just grasslands + hill
> 
> 
> Are you sure you are on the version that adds Hills as terrain features?

turns out i was using an older version ov civ5expansion mod, will point thst out in the comment
