### ISSUE TITLE
Very old android versions - worth debugging?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#3927]
Running the game in a KitKat AVD (silly, and I have no idea what drove me to try - it even takes more disk space than the Oreo one):
- Mod manager runs into a problem because the openssl version can't cope with the upgraded minimum TLS demanded by github. 
     I can catch this (`catch (ex: SSLHandshakeException)`) but then what? Trying http (`return download(URL("http", url.host, url.file), action)`) just gives a 301 permanently moved - back to https.
- `CameraStageBaseScreen.closeAllPopups` crashes, a `.toList()` fixes the crash

No big magic, but before I debug everything I find - _is supporting Android 4.4 kitkat worth it_? Any input welcome.

If answers tend to yes, _only then_ I'll try to find out the actual android version levels where anything changes, and start implementing solutions. #1 would get a useful user message, #2 is trivial, ...

**Comment by yairm210** [comment]
Google no longer supports it, and most major things stopped supporting it 2 years ago... I see no point tbh

**Comment by SomeTroglodyte** [comment]
Still thinking - maybe just add a one-time warning? Otherwise, we could / should bump up the minimum API... In the meantime, until I manage to prybar my fingers  away from that nostalgic AVM I'll collect what I find right here. Do you still get mails if I just _edit_ a comment? No, wait, I'll move this data [to my own repo](https://github.com/SomeTroglodyte/Scratchpad/issues/1).
