### ISSUE TITLE
Make city centers automatically get a road once wheel has been researched

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3935]
**Is your feature request related to a problem? Please describe.**
i want to connect my capital to a city state but their city center has units in it and it does not have a road.

**Describe the solution you'd like**
either make city states have a road when they have researched the wheel or make it available for all civs and city states

**Comment by SomeTroglodyte** [comment]
I'm pretty sure I have seen this working properly lately. If you can reproduce and attach a saved game that would help. The save should be right after the last piece of road between your capital and theirs has been finished, not including the capital tiles themselves. The 'quest fulfilled' test would then run in the 'next turn' action and the notification and benefit should appear next turn, so it is important to have the save from _just_ before.

**Comment by logicminimal** [comment]
> I'm pretty sure I have seen this working properly lately. If you can reproduce and attach a saved game that would help. The save should be right after the last piece of road between your capital and theirs has been finished, not including the capital tiles themselves. The 'quest fulfilled' test would then run in the 'next turn' action and the notification and benefit should appear next turn, so it is important to have the save from _just_ before.

im using civ5expansion mod btw so that might be why

**Comment by yairm210** [comment]
This works properly (CityInfo.kt:415)
Please attach a saved game with a city state with no road and that has researched The Wheel
Otherwise I'll just assume that the City-states you tried to connect to haven't researched it
