### ISSUE TITLE
Swap unit position and link units feature.

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#3937]
I don't know if this is in civilization. But, it basically allows you to swap positions of the unit A, to the tile position of unit B.
I had thought this could be done in the game by thouching unit A, then unit B, this would make appear a little pop up, like the one that appears when Capturing a unit, giving you the option to swap their positions. When swaping positions, the movement tile cost will be applyed.

The other feature is to be able to link up a military unit, with a civilian unit. The process could be: You select the civilian unit, and then the military unit, then the pop up would appear, enabling you to link them.
When you have linked a unit, both units move to the same tile selected when moved. If, the military unit has more movement points than the civilian one, the unit will get unlinked, but the civil unit will move aproximatedly to the wished position, but still, lagging behind.
If the civilian unit has more movement points than the other unit, the civilian unit will not consume it all.

**Comment by SomeTroglodyte** [comment]
The swap idea would be a rule change, the "escort" idea would not. Changing rules - nah, unless you can show that the Original offered it.

For the other idea - with units of identical speed you can get that anyway, so I'd first declare it to always match speed to the lower common denominator. Still, I would envision quite a lot of code, and more properties to be persisted in saves - not worth it IMHO.

**Comment by ArchDuque-Pancake** [comment]
Yeah, I understand it would need a lot of work, but, I really think the swap feature is valuable, because when using a big army, or there is to little space, manoeuvering with units is very complicated and inefficient. I'll try to search for footage.

But I get that it may take too long, and if it doesn't get implemented, I'll understand.

**Comment by ArchDuque-Pancake** [comment]
Here!!! https://youtu.be/MXezgEWjglo
Minute: 0:25

**Comment by SomeTroglodyte** [comment]
There's a PR for swapping (#4049), and what you mean by linking is close to what multi-select might do when it's finished - and I'd say any other approach would be too complicated, so I think this could be closed?

**Comment by yairm210** [comment]
Closed in #4049
