### ISSUE TITLE
city tile not showing

### ISSUE THREAD

**Issue by slavdan1** [yairm210/Unciv#3939]
![Screenshot (116)](https://user-images.githubusercontent.com/78725776/118355140-7dfdaa80-b566-11eb-9fd3-c6ec5254842a.png)

**Comment by SomeTroglodyte** [comment]
Modded I'm guessing and mod outdated. Right? If not - save game copy please?

**Comment by yairm210** [comment]
Your mod is missing a "City center" improvement.
Either that, or your city was created in a relatively older version of Unciv, where the improvement wasn't automatically added to the city tiles :)
In either case, not a bug.
