### ISSUE TITLE
Add an undo button to the map editor

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3941]
i keep mispressing and it is really infuariating

**Comment by SomeTroglodyte** [comment]
Same arguments apply as for the Undo feature in the main game. Either too complex or too potentially memory intensive - IMHO.

**Comment by logicminimal** [comment]
> Same arguments apply as for the Undo feature in the main game. Either too complex or too potentially memory intensive - IMHO.

what if the game instead of caching the whole last 50 turns or something into the ram just cached the last 150~ tile changes to a cache file, would that work? it does not need to cache the entire play unlike in normal game, and when the player exits the map editor maybe the first 100 turns that are in the cache would be cleared as to preserve space? and it still would allow the player to undo in some way

**Comment by SomeTroglodyte** [comment]
"caching changes" - yup that's a way to say a _transaction_ logging system with arbitrary rollback capability. Complex. Stashing the whole App state and reading it back - easier, but doubles memory requirements for 1 level of undo, triples for 2 levels...

**Comment by yairm210** [comment]
The cost/benefit analysis of this is a definite "Nope"
