### ISSUE TITLE
Negative iron in Resources tab of Overview.

### ISSUE THREAD

**Issue by BlueManedHawk** [yairm210/Unciv#3944]
**Describe the bug**

After trading for Iron and using it, my iron usage is listed as `-1` once the deal ends.

**To Reproduce**

0.   Research to reveal Iron on the map.
1.   Trade to obtain Iron for twenty-five turns.
2.   Use the iron; in my, case, I constrcuted a frigate.
3.   Wait for the deal to end.
4.   Look at the Resources tab of Overview.

**Expected behavior**

I don't know, but instinct tells me it should not be this.

**Screenshots**

![Negtive Iron ~!@#$%^ *()`-=_+{}|: ? ;',](https://user-images.githubusercontent.com/50188776/118375549-3ee44f00-b590-11eb-85fa-0fa540089229.png)

**Additional context**

I had no iron in my borders.

**Comment by SomeTroglodyte** [comment]
I have known about this and always thought that's exactly as it should be. It tells you that you are using 1 iron but have none - which is _correct_. 

Question is, where is the penalty? I think Unciv doesn't punish you for this. You could help by researching how original Civ5 handled this?

**Comment by logicminimal** [comment]
> I have known about this and always thought that's exactly as it should be. It tells you that you are using 1 iron but have none - which is _correct_. 
> 
> Question is, where is the penalty? I think Unciv doesn't punish you for this. You could help by researching how original Civ5 handled this?

not the op but i found a wiki page on how this works: 

"_If a civilization loses access to some of the strategic resources they are currently using, and find themselves using more than they're producing or trading, then military units depending upon the resource in question will fight with a large combat penalty until the situation is remedied_" https://civilization.fandom.com/wiki/Resources_(Civ5)

"_you have more units that depend on a strategic resource than you have of that resource, you will suffer a significant combat penalty, see the "Strategic Resource Penalty" line item below:

https://i.stack.imgur.com/ygH52.jpg

strategic resource penalty

In this case, you will see a negative number on the top status bar by the strategic resource you are lacking. It does not matter how your strategic resources get into the negatives - you can have a trade deal expire, lose territory, or have an improvement pillaged, the effect is the same.

50% lost strength is a severe penalty - it makes these units worse than contemporary units that don't require resources (ie, it makes a Swordsman worse than a Spearman) and can even make the unit weaker than units of previous eras.

The quantity you are over doesn't seem to matter, either. You can be -1 or -5 with the same 50% penalty. I tested this just now on a hotseat game between two players that were running different difficulty levels. The difficulty level did not seem to impact it either. Further, I tried two different units, a Swordsman and a Roman Legion and both had the same penalty applied.

Another side effect of going into the negatives is that any unit you were building that depends on that resource will immediately cancel. When I reconnected the strategic resource, I was able to resume production where it left off.

I don't believe patch or DLC matters, but for the record this was in a game with all the current expansions/DLC (Civ5 Gold, Gods and Kings, Brave New World) available._" https://gaming.stackexchange.com/questions/148419/will-losing-a-strategic-resource-disband-units

The penalty seems to be -50% but as far as i remember from some random thread  on youtube or reddit it applies for all units requiring that resource, i think how it should be implemented is for only (lacking resource * -1 ) units to be affected by the penalty, not all

**Comment by SomeTroglodyte** [comment]
OK now we could go and check if the penalty is implemented, and if not, do it. thanks!

**Comment by yairm210** [comment]
It is implemented. There's no bug here.
In fact, in the "resources" overview tab you can see exactly where the -1 comes from, so I don't think there's any more work to be done in "explaining" either.
