### ISSUE TITLE
Menus sometimes immediately exit in Chrome OS

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#395]
From that point on, no matter what I click be it a city or a promotion menu, it will exit.

**Comment by yairm210** [comment]
Is this in Chrome OS?

**Comment by flecheapolinienne** [comment]
Yes

**Comment by yairm210** [comment]
Well, I haven't encountered it, and I have no idea why this would happen... So there's not much I can do about this

**Comment by flecheapolinienne** [comment]
Does not do it anymore
