### ISSUE TITLE
Heaps of praise

### ISSUE THREAD

**Issue by jmthackett** [yairm210/Unciv#3951]
Hello,

I was just playing this game (installed from Flathub on Arch Linux) and it is absolutely great. The prompt mentioned that you like to hear from players, and well, I am hooked. I'm going to lose days of my life to this game and am thoroughly enjoying it. 

So.. thank you!

**Comment by yairm210** [comment]
Wow! Thank you!! :D
This is the best issue I've gotten, I think ever, so thank YOU! ❤️

**Comment by SomeTroglodyte** [comment]
Indeed. Maybe you should leave this open so we can all add our view? As dev I would add: holy s*t what an accomplishment! And - coding hasn't been this much fun since... since... maybe hacking assemby as hex codes into that 4k RAM 6502 box?
