### ISSUE TITLE
Spaceship part production bonuses do not work

### ISSUE THREAD

**Issue by avdstaaij** [yairm210/Unciv#3952]
**Description**
The buildings and wonders that should boost production when constructing spaceship parts, i.e. Forge, Spaceship Factory and Hubble Space Telescope, do not provide this boost.

**To Reproduce**
1. Build a Forge, Spaceship Factory or Hubble Space Telescope in a city.
2. Observe how the production time for spaceship parts does not benefit from the spaceship part production boost.
3. (optional) Start building a spaceship part and observe how the city receives no spaceship part production boost in the stats drilldown.

I have included a minimal (hand-edited) game state displaying the issue (`.txt` to make GitHub accept it):
[SS-part-production-bonus.txt](https://github.com/yairm210/Unciv/files/6497101/SS-part-production-bonus.txt)
Simply buy a Forge or Spaceship Factory and observe how it does not boost spaceship part production.

**Expected behavior**
Forge, Spaceship Factory and Hubble Space Telescope boost the production of spaceship parts, as they describe.

**Cause**
I have already found the cause of the problem: the spaceship part-boosting uniques of Forge, Spaceship Factory and Hubble Space Telescope use the "+[amount]% Production when constructing [unitFilter] **units** [cityFilter]" format, but spaceship parts are currently buildings instead of units. I will post a PR fixing the problem shortly.

**Comment by yairm210** [comment]
Resolved by @avdstaaij himself :)
