### ISSUE TITLE
Game crashes on launch on latest two versions with pixel 4a 5g

### ISSUE THREAD

**Issue by Maxwelldoug** [yairm210/Unciv#3959]
**Describe the bug**

The game crashes on launch without even reaching the main menu

**To Reproduce**
1. Purchase a Pixel 4a 5g
2. Install the latest two versions of unciv
3. Launch the game
4. Screen flashes about half black, nothing on the other side
5. Crash

**Expected behavior**
The game should load.

**Comment by Mape6** [comment]
Duplicate of #3946

**Comment by Maxwelldoug** [comment]
Oh, sorry, didn't even see that one. I'll close this and contribute over there. Sorry!

**Comment by SomeTroglodyte** [comment]
"Purchase a Pixel" - nice humour :grinning:
