### ISSUE TITLE
Proactive - is `WorldScreen.canChangeState` actually doing what it's meant to do?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#3974]
Public val [`canChangeState`](https://github.com/yairm210/Unciv/blob/fd5125904ad2843b3328ed1fcf1d34c6be05933e/core/src/com/unciv/ui/worldscreen/WorldScreen.kt#L55) in `WorldScreen`, currently line 55 _looks_ like it it supposed to follow [isPlayersTurn](https://github.com/yairm210/Unciv/blob/fd5125904ad2843b3328ed1fcf1d34c6be05933e/core/src/com/unciv/ui/worldscreen/WorldScreen.kt#L52) - but it doesn't, does it? That val is assigned a value in the constructor, permanently, until the screen instance dies.

Just from the looks of it I'd expect 
```
    val canChangeState
        get() = isPlayersTurn && !viewingCiv.isSpectator()
```
to meet original intentions.

Usages: CityScreen, PolicyPickerScreen, PromotionPickerScreen, TechPickerScreen, WorldMapHolder.addTileOverlays, BattleTable, UnitActionsTable

No idea for the moment on how to get it to be (dynamically - spectator would be static for screen lifetime) false and thus how to test it - volunteers?

**Comment by yairm210** [comment]
This is correct.
When we load a new game state, where one of these have changed, we *always* create a new WorldScreen.
