### ISSUE TITLE
Autobuild railroad doesn't work too well.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#398]
Have added code enabling workers auto-connect cities once railroad is available, but it seems workers often stay idle when there are many cities to connect. I have no idea how to log & debug in this project. Any suggestions?

**Comment by yairm210** [comment]
To enter debug mode:
![image](https://user-images.githubusercontent.com/8366208/50682622-248d2480-1018-11e9-925f-ba5f89be8c49.png)

To add breakpoints on the line you want to stop at, click near the line number:
![image](https://user-images.githubusercontent.com/8366208/50682719-6fa73780-1018-11e9-89c6-c1e60397e1e3.png)


You can add `println("Testing testing 123")` for console logging

**Comment by ninjatao** [comment]
Finally I got log working! Thanks!
BTW, is there any way I can play through until railroad is enabled with release apk, and switch back to debug apk for breakpoints? Because debug apk is significantly slower.

**Comment by yairm210** [comment]
Absolutely, you can run it on release until it's at a good point and then switch to debug and keep playing from there
UnCivGame.superchargedForDebug is useful here, it makes the game go waaay faster precisely so you can get to a good point to start checking things out

**Comment by yairm210** [comment]
Resolved?
