### ISSUE TITLE
Dropbox storage full

### ISSUE THREAD

**Issue by martinblake** [yairm210/Unciv#3986]
Multiplayer game upload fails with exception:
```
Server returned HTTP response code: 409 for URL: https://content.dropboxapi.com/2/files/upload
{"error_summary": "path/insufficient_space/", "error": {".tag": "path", "reason": {".tag": "insufficient_space"}, "upload_session_id": "AAAAAAAAmnJJ4wbOUcLwog"}}
```
I followed this up by inserting before the upload:
```kotlin
val inputStream = dropboxApi("https://api.dropboxapi.com/2/users/get_space_usage")
val text = BufferedReader(InputStreamReader(inputStream)).readText()
println(text)
```
which outputs:
```
{"used": 2684361591, "allocation": {".tag": "individual", "allocated": 2684354560}}
```

**Comment by avdstaaij** [comment]
Can confirm, I just got the same results from the debugger.

Sidenote: the game does not seem to give any indication of a failure to upload. It simply resets the turn after pressing the next turn button. This seems quite problematic: I expect that many players will be very confused (as I was). From the code, it appears that a "Could not upload game!" notification was intended to appear, but for me it didn't.

**Comment by yairm210** [comment]
If any of you can get the delete function to work, we'll be able to solve this properly
The Dropbox website doesn't respond well to deleting even 100 files together, so 'get bunch of files, foreach delete' sounds like the way to go
(I saw there's a bulk delete but I couldn't even get the regular delete to work...)

**Comment by SomeTroglodyte** [comment]
Trying something...

**Comment by SomeTroglodyte** [comment]
Well, written in-game a tool might look like [this](https://github.com/SomeTroglodyte/Unciv/tree/Dropbox-cleanup)... Not limited to project admins, so not as PR - just (add my repo to remotes +) checkout my branch to test. Age limit hardcoded in MultiplayerScreen line 84. Seems to delete stuff... At least the json coming back from the delete api doesn't look like errors.

Sleep in there on purppose - I guess _s l o w_ is what DripBoxx needs.

**Comment by yairm210** [comment]
Fascinating. I used the exact same delete function with the exact same parameters and only got errors.
Wonder what that was all about.

**Comment by SomeTroglodyte** [comment]
Well, that's computers for you. I hope that helps - and just to be clear: I tested a little, but that's _your_ account, so I'm not going to let that thing run its course or decide on the best age limit.

**Comment by SomeTroglodyte** [comment]
New idea: Make the creation of a new multiplayer game delete a handful of the oldest if old enough - DDOS pattern but in this case maybe best? Currently the multiplayer game creation somehow already _is_ a DDOS as this issue demonstrates...

If 'yes' then questions - firing a max of three deletes without waiting for the response a good idea? Final decision on age limit? How to inform players of limited lifetime for stale games? Would wording like "Note: Multiplayer games that are not updated for six months are considered stale and candidates for automatic deletion." be OK? Where? Tutorial - toast - <u>multiplayer help button</u>?

**Comment by yairm210** [comment]
"creation of game attempts multiple deletes" is a lovely idea :)
I think for now "if game is more than 2 months old" is a good criteria

**Comment by yairm210** [comment]
Multiplayer help button is probably the place for it

**Comment by SomeTroglodyte** [comment]
OK, right after creating a branch for it I noticed how tired I am... Later.

**Comment by SomeTroglodyte** [comment]
Then there may be issues with a rate limit on the dripbox API that could be per auth token not per IP, that would be a major problem, needs investigation. Also, there's a PR open touching `Dropbox.kt`, so that would better be the base to branch on. #3983 separates Github code from Dropbox, yes.

**Comment by loomy** [comment]
How about giving an option to define another dropbox account to use?

so Users are still able to keep old games and play them after 2 months

**Comment by yairm210** [comment]
Hah, no. If we need to code extra solutions, the correct one is "standalone Unciv server for desktop".
Anyway, this issue is currently over.

**Comment by SomeTroglodyte** [comment]
Just FYI: I'm shelving the Code for automatically deleting stale files on each new-game: Dropbox support confirmed _in record time_ that the API has no way to return a limited number of the oldest files - I tried the search API - the only option would be to list the entirety using list_folder as we know it and filter that. And several roundtrips with a few tens of packets per trip does not fit the "distributed" idea I think.
