### ISSUE TITLE
[Android] MiniMap to big

### ISSUE THREAD

**Issue by Improver2000** [yairm210/Unciv#3995]
**Describe the bug**
The mini map fills 1/4 of the screen of 900x600 device even at the smallest minimap setting.
UnCiv 3.14.10 for Android.

**To Reproduce**
Start game and activate minimap. 

**Expected behavior**
Possibility to set a smaller minimal size as in prior versions. 

**Screenshots**

![Screenshot_20210526-152837_UnCiv](https://user-images.githubusercontent.com/65492926/119668044-1af9f680-be37-11eb-9a77-bf512a8ae30a.jpg)

ANYWAY: AWESOME GAME!!!! 🥇 👍

**Comment by AdityaMH** [comment]
You can choose minimap size by scrolling "show minimap" on options.
Issue closed.

**Comment by Improver2000** [comment]
> You can choose minimap size by scrolling "show minimap" on options.
> Issue closed.

Yes,  but even the smallest map is too big. This was different in the past. 

The screenshot IS the smallest minimap.

**Comment by AdityaMH** [comment]
I think we need change font-size (add font size setting (small, medium, large)) or change text upper minimap to left minimap instead.

**Comment by ravignir** [comment]
nah, it is a bug, because minimap does not scale well with resolution and it kinda remembers the last resolution.

**Comment by ravignir** [comment]
i had it cover my entire screen couple of time, single hex on the minimap was literally as big as the real one.

**Comment by yairm210** [comment]
I actually already solved this, but because of the hectic times lately, I haven't yet rolled out a new version
On it

**Comment by SomeTroglodyte** [comment]
And the "cover my entire screen" effect is due to the minimapSize setting changing meaning with a specific version update - sorry, but that's once at most per user (more only if you check out various versions from source). Choosing size from the options will set appropriate values and that's it.

**Comment by SomeTroglodyte** [comment]
>(Does anyone even read closed issues?)

No. 👀

With same outer size, 900x and max slider I get:
![image](https://user-images.githubusercontent.com/63000004/120014725-b1b6e680-bfe2-11eb-8bc9-37a281df3b64.png)
... showing it can't get much bigger without displacing the next turn button, the notifications are already mostly covered up ...
Please make sure you're testing with the latest code base, 3.14.11 minimum, and re-set the size slider at least once - even if it's already the position you think is right, move it.

**Comment by jahodovykolac** [comment]
Sorry, it was caused by small display of one of my devices, the bigger one with correct resolution doesn't have the problem
