### ISSUE TITLE
Let user choose border

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3996]
I know this very fool request, but still i want choose borders from original or mod because i want change tileset but not for borders.
Also, not connected and not bolded borders make me confused sometimes.

**Additional context**
p. s.: Only this border who never make me confused.
![IMG_20210526_211456](https://user-images.githubusercontent.com/33791472/119675681-73e18300-be67-11eb-9f07-377455016040.jpg)
Sorry just...

**Comment by yairm210** [comment]
... You could just make a border only mod that will override the existing mod.
