### ISSUE TITLE
Show damage text

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3997]
Please add small damage number, if user confirm attack other units and small heal number if wounded unit going to fortify/sleep. Just like other turn-based strategy games (maybe all turn-based games).
So, player will know damage overall if user attack maori warrior using wounded spearman.

**Comment by ravignir** [comment]
This is actually present in civ5:
![image2](https://user-images.githubusercontent.com/30041793/119681993-cf4d4a00-be42-11eb-8130-fe2476a71a89.png)
![obraz](https://user-images.githubusercontent.com/30041793/119682241-03c10600-be43-11eb-8dc8-20b344bc075f.png)
and whenever any unit heals/deals damage a number is displayed next to it, positive and green when it heals or negative and red when it is dealt damage.

**Comment by ravignir** [comment]
![obraz](https://user-images.githubusercontent.com/30041793/119682620-526ea000-be43-11eb-95b0-9313f67c7d5a.png)

**Comment by ravignir** [comment]
another thing, can we please have city strength always displayed? and when you click enemy unit, make it display its promotion icons.

**Comment by ravignir** [comment]
![obraz](https://user-images.githubusercontent.com/30041793/119683475-f7897880-be43-11eb-80a6-1e769b4f1742.png)

**Comment by avdstaaij** [comment]
Another thing: since damage involves a random factor, it would also be nice to have an option to display the possible damage range, though I'm not sure if the original game has this. The current behavior, where the predicted damage shown also involves the random factor, is certainly _not_ the best UI: it should at least be changed to show the average damage done.

**Comment by AdityaMH** [comment]
> Another thing: since damage involves a random factor, it would also be nice to have an option to display the possible damage range, though I'm not sure if the original game has this. The current behavior, where the predicted damage shown also involves the random factor, is certainly _not_ the best UI: it should at least be changed to show the average damage done.

I think will be better if show text "minor, decent, or dominant" victory like original civ5 (just show for melee battle). Damage range can be incorrect because critical hit can be more high than damage range.

**Comment by yairm210** [comment]
This is currently impossible, and making it possible is more trouble than it's worth.

**Comment by AdityaMH** [comment]
Wow, unciv now can create number text pop-up on above City-State scrolling. No doubt we can create show damage result.

**Comment by AdityaMH** [comment]
#5856
