### ISSUE TITLE
SFX/sound bug

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3998]
**Describe the bug**
Every unit if attack other unit/enemies just play sound "click.mp3" not metal unit play sound "metalhit.mp3" or cavalry unit play sound "horse.mp3", even horse.mp3 is very low to hear in external player.
And sometime just silent when doing action.

If this does not happen on pc/jar. Maybe this bug only on android.

**Comment by yairm210** [comment]
Not a bug, a known and documented missing feature.

**Comment by AdityaMH** [comment]
And now we missing sound for siege unit attack.
