### ISSUE TITLE
Apk launch crashs.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#400]
Got compiled apk crash on newest commit. Tried to revert to 0567eb442daf6b07b57095674ae5e4afa9c4f1a8 and worked fine. Is this my compiling problem or what?

--------- beginning of crash
01-05 22:42:05.293  1955  1955 E AndroidRuntime: FATAL EXCEPTION: main
01-05 22:42:05.293  1955  1955 E AndroidRuntime: Process: com.unciv.app, PID: 1955
01-05 22:42:05.293  1955  1955 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.unciv.app/com.unciv.app.AndroidLauncher}: java.lang.ClassNotFoundException: Didn't find class "com.unciv.app.AndroidLauncher" on path: DexPathList[[zip file "/data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/base.apk"],nativeLibraryDirectories=[/data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/lib/arm64, /data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7425)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unciv.app.AndroidLauncher" on path: DexPathList[[zip file "/data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/base.apk"],nativeLibraryDirectories=[/data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/lib/arm64, /data/app/com.unciv.app-H_qvaE9CxzjgKwNqJS-T4g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1178)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3082)
01-05 22:42:05.293  1955  1955 E AndroidRuntime: 	... 9 more
01-05 22:42:05.293  1435  1435 E HwSplitScreenArrowView:  onAnimationUpdate() View=com.android.systemui.statusbar.policy.HwSplitScreenArrowView{cf39929 G.E...... ......ID 0,0-1080,1920} not attached to window manager
01-05 22:42:05.294  1435  1907 D OpenGLRenderer:   HWUI Binary is  enabled
01-05 22:42:05.294  1435  1435 D HwCust  : Create obj success use class android.view.HwCustRenderThreadMonitorImpl
01-05 22:42:05.297 10379 10379 I ActivityThread: ActivityThread.handleConfigurationChanged , new config = {1.0 460mcc65535mnc [zh_CN_#Hans] ldltr sw360dp w597dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1793, 1080) nonFullScreen=0 suim:1 s.833}, compat = null

**Comment by yairm210** [comment]
Sometimes this error occurs and it just means you need to run it twice, I'm not sure why this happens
If running it several times doesn't work I'll check it out

**Comment by yairm210** [comment]
Seems to work for me, anything new?

**Comment by ninjatao** [comment]
Last time when this happened, it kept crashing even after I upgrade installed apk. I had to revert to previous commit, compile, delete the installed apk and re-install it.

**Comment by ninjatao** [comment]
How to reproduce for me:
1. Open the project with Android Studio for coding.
2. compile release version with gradle and sign the apk.
3. 100% crash
To get a runnable apk, I have to git clean -xdf the directory and then compile. But next time editing the code with Android Studio will make this happen again. That's a little inconvenient.
Any idea about this problem?
