### ISSUE TITLE
Parametrization of "Can build roads"

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4002]
As the title says, the current uniques that let´s a unit to build improvements are: "Can build improvements on tiles" and "Can construct roads"; which, get short at the time of modding (because sometimes letting a unit build everything is not wanted).
So the parameter I imagine could be like: "Can build [improvement]", that way the unit will only be able to buil, let's say Forts, and nothing else.

*Also, sorry if I'm being annoying with Issues, inspiration came again and can't let it go.

**Comment by yairm210** [comment]
Please add as a comment into #3242

**Comment by ArchDuque-Pancake** [comment]
Jaja yeah, I was doing that XD
