### ISSUE TITLE
Portait screen bug

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4003]
**Describe the bug**
Not bad if can play this game on portait mode. But i more want to play this game on reverse-landscape mode rather play on portait mode.
p. s.: Auto-rotation doesn't work on my phone.
![Screenshot_2021-05-27-05-30-22-725_com unciv app](https://user-images.githubusercontent.com/33791472/119765900-3e2bb100-bede-11eb-84f9-7484f4430c9d.png)

**Comment by SomeTroglodyte** [comment]
Well, no problem, turn the option we built for you off again, you'll get auto-rotation to only landscape or reverse landscape again. If your sensors are defective or blocked by software that's hardly an Unciv problem IMHO.

**Comment by AdityaMH** [comment]
Big company game can force app to activated auto-rotation sensor without go to setting to turn on the auto-rotation.
Another solution is let player choose screen rotation (portait, landscape, or, reverse-landscape) like ppsspp and retroarch.

And for portait can be fixed, only if resolution set to highest screen (but with super tiny text).

**Comment by yairm210** [comment]
This sounds super, super niche.
We're not a big game company, not are we here to fix OS level problems on specific devices with software solutions.
Denied.

**Comment by SomeTroglodyte** [comment]
These links demonstrate exactly what Unciv is doing ([source](https://github.com/yairm210/Unciv/blob/cf2be25c73610efee44274b4b61e3331065b6dd8/android/src/com/unciv/app/LimitOrientationsHelperAndroid.kt#L35)). What it is not doing is overstepping its bounds - meaning everything else is the domain of the OS or the user.
