### ISSUE TITLE
Cant bombard an enemy unit while i have a unit in the city center and it requires me to move the unit in the city center

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4005]

**Comment by AdityaMH** [comment]
Because unit icon blocking enemy position when want to bombard.
I think only one solution is change the ui, like this.
![1622119545179](https://user-images.githubusercontent.com/33791472/119828312-3f7fcc80-bf24-11eb-815d-8b55a7ef6cda.png)

And "warrior" text with "!", is only condition when city have 2 unit with same type and force player to move unit before end turn. So, don't need move automatically without no reason because city has unit inside.

**Comment by yairm210** [comment]
For this, we have "deselect unit, click bombardable unit, bombard".

**Comment by logicminimal** [comment]
> For this, we have "deselect unit, click bombardable unit, bombard".

not when the select unit in the city center is exactly where the enemy is, most often one tile above city center

**Comment by logicminimal** [comment]
> > For this, we have "deselect unit, click bombardable unit, bombard".
> 
> not when the select unit in the city center is exactly where the enemy is, most often one tile above city center, i know that i can deselect, it is just that i have to move an unit to be able to bombard ir

**Comment by AdityaMH** [comment]
My own unit icon blocking north city center area.
![Screenshot_2021-05-30-19-47-50-408_com unciv app](https://user-images.githubusercontent.com/33791472/120114771-e7a6c700-c1aa-11eb-8400-ba0d7acb488f.png)

**Comment by logicminimal** [comment]
> My own unit icon blocking north city center area.
> ![Screenshot_2021-05-30-19-47-50-408_com unciv app](https://user-images.githubusercontent.com/33791472/120114771-e7a6c700-c1aa-11eb-8400-ba0d7acb488f.png)
> 

@yairm210

**Comment by AdityaMH** [comment]
@SomeTroglodyte , we need change unit button position.

**Comment by SomeTroglodyte** [comment]
Not interested. I vaguely remember you have to pay attention sometimes when you want to bombard, but never had real trouble with it. Besides - that part of the UI was done by someone cleverer than me.

**Comment by jahodovykolac** [comment]
Just click on any tile - the unit button disappears - and then click the bombardable unit.

**Comment by AdityaMH** [comment]
> Just click on any tile - the unit button disappears - and then click the bombardable unit. I do it this way and it works.

For me, that didn't work. Click any tile will disappear bombard icon.

**Comment by AdityaMH** [comment]
#5856
