### ISSUE TITLE
AI: Never defend own city

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4007]
I'm trying to play on hard level, but why they never defend own city even never garrison a unit inside city?
They offer peace treaty even their strength much stronger than mine.

This making game easily to claim domination victory in every level rather than cultural or sciences victory, because too easy to capture enemy city.

Also, ai never offer friendship to player or other civilization to joint attack.

**Comment by yairm210** [comment]
The AI also focuses its units around cities that are under attack

**Comment by AdityaMH** [comment]
I'm sorry for late comment. But we can talk this later because my savedata just got erased. But as in the issue of #4014, AI only defends its city in peacetime, but when it is declaring war they deploy all troops without protecting the city in the slightest. They're just focused on conquering the city.
