### ISSUE TITLE
AI surrounds my cities with embarked ranged units without attacking and won't pillage with full health units

### ISSUE THREAD

**Issue by freddyhayward** [yairm210/Unciv#4014]
These might be intentional but the result is that you can be totally unharmed by vastly superior armies by targeting naval and melee units and making sure not to leave wounded units. The AI here could easily defeat me by pillaging my fishing boats with full-health units and sending in a few naval units.
[save](https://github.com/yairm210/Unciv/files/6564413/Embarked.zip)

![image](https://user-images.githubusercontent.com/13117753/120065599-75a08600-c0b5-11eb-8fa9-b75b69eceb41.png)

**Comment by SeventhM** [comment]
AI has changed considerably since. Closing as solved
