### ISSUE TITLE
Domination Victory according to Civ V rules 

### ISSUE THREAD

**Issue by whatsupboy** [yairm210/Unciv#4015]
Unciv's domination victory requires you to wipe out every civ in the game or atleast for you to be the only one left with cities. In a game with alot of civs and a large map, that is very tedious. 

Vanilla Civ V and the expansions focus on the capitols instead. In vanilla you have to be the last one left with your original capitol. In the expansions you have to own every original capital. 

I think going with either of the two would give clearer ways to go about winning and be more fun.

And if Unciv's domination victory is the more preferred would having both Civ V's and Unciv's victory types in the game be an option?

**Comment by ravignir** [comment]
I think all victory types need some overhaul:
[Spaceship](https://civilization.fandom.com/wiki/Spaceship_(Civ5)) parts should be units, than need to be transeferred to capital to conenct them to spaceship.
Completing 5 Policy branches should allow [Utopia Project](https://civilization.fandom.com/wiki/Utopia_Project_(Civ5))

**Comment by jahodovykolac** [comment]
Maybe you should put these to #663.

**Comment by logicminimal** [comment]
> I think all victory types need some overhaul:
> [Spaceship](https://civilization.fandom.com/wiki/Spaceship_(Civ5)) parts should be units, than need to be transeferred to capital to conenct them to spaceship.
> Completing 5 Policy branches should allow [Utopia Project](https://civilization.fandom.com/wiki/Utopia_Project_(Civ5))

agree

**Comment by yairm210** [comment]
All according to #663
