### ISSUE TITLE
Slight problems with 5Hex as permanent visual mod

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4016]
I believe these belong here even though I repro with this specific mod - or is there any other supplying a new tileset?

a) Glitch after deactivating from main screen
- Make sure 5Hex is installed and set as PVM and set as tileset in Options
- From main (not world) screen go to mod manager and deactivate PVM for 5Hex, close MM
I get a white background map with a few resources.
![image](https://user-images.githubusercontent.com/63000004/120085842-bca17200-c0db-11eb-8668-c1e080e59628.png)
(probably just a missing reset to FantasyHex - simple restart fixes)

b) Map editor using 5Hex widget sizing
- Make sure 5Hex is installed and set as PVM and set as tileset in Options
- Enter map editor
Terrain and features are OK, resources improvements are squashed - still work though.
![image](https://user-images.githubusercontent.com/63000004/120085810-911e8780-c0db-11eb-97a2-0f594257f734.png)
(likely scaling the terrain to the fixed widget size forces the same scaling to be applied to other images but they didn't grow due to 5Hex - something like that)

I'll probably solve these myself in time, but any help is welcome...

**Comment by SomeTroglodyte** [comment]
Solution for b): @ravignir  - the code makes itself dependent on the actual pixel dimensions of hexagon.png and what we see above is the effect of yours being 3-4 times smaller. Yes, the original is 277x240. But rather than fiddling with that I'd suggest you fiddle with your hexagon.png - roughly like this:
![Hexagon](https://user-images.githubusercontent.com/63000004/120247345-6cf5ae80-c273-11eb-9ed5-9efde6314281.png)
Will make the editor look like this:
![image](https://user-images.githubusercontent.com/63000004/120247330-61a28300-c273-11eb-9c8d-6d996bdb715c.png)
... but I scaled it a bit too small so the fog of war on an actual new game isn't that cute, but I'm sure you could fiddle it to perfection.

**Comment by ravignir** [comment]
![shouldbegoodnow](https://user-images.githubusercontent.com/30041793/120284726-d948d000-c2bc-11eb-9009-e9354db8bdf1.png)
I've made new Hexagon.png, apart from being bigger, it is also lighter in color.
