### ISSUE TITLE
Eiffel tower is basically useless 

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4017]
it unlocks in the late game so 3 culture and 5 happiness is pretty much useless. i think it is not worth 1250 production and it needs a bit of buffing, in the original game it provided tourism afaik, but in this game it is useless, also extra happiness from policies are useless

**Comment by ravignir** [comment]
![what](https://user-images.githubusercontent.com/30041793/120105995-902d3a80-c15b-11eb-98e5-3899aabe8a9c.png)

**Comment by logicminimal** [comment]
> ![what](https://user-images.githubusercontent.com/30041793/120105995-902d3a80-c15b-11eb-98e5-3899aabe8a9c.png)
> 

added the policy bonus to the issue

**Comment by yairm210** [comment]
This is an opinion piece. Which is fine, but as long as Eiffel tower is following Civ v rules, I don't see an issue.

**Comment by logicminimal** [comment]
> This is an opinion piece. Which is fine, but as long as Eiffel tower is following Civ v rules, I don't see an issue.

but it can't implement one of the key factors that makes this wonder usable, the tourism, it should be substituted with something else, policy one is not even great considering you have %50 excess happiness added to the culture policy, its 4 culture per turn, and this is late game (16 policies)
