### ISSUE TITLE
one issue and a question

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4018]
issue: production does not carry over

question: "_If there is a route involving only Railroads and Harbors from a city to its owner's Capital, that city receives a +25% Production bonus. The Capital itself can never receive this bonus._ " also is this implemented?

**Comment by yairm210** [comment]
A is already in #663
B is implemented

**Comment by ravignir** [comment]
ngl, i like the fact production does not carry over, it puts more emphasis on micromanagement.
