### ISSUE TITLE
Change Capital

### ISSUE THREAD

**Issue by Crit-Cee** [yairm210/UnCiv#403]
Add ability to build a Palace in a differebt city to move the capital.

**Comment by yairm210** [comment]
This isn't possible in the original game, and so I think this should come with some sort of penalty or cooldown if it's implemented - say, 5 turns with no culture gains or something

**Comment by yairm210** [comment]
I'm on the fence about implementing this.
On the one hand on I'm in favour of having the player be able to make his own decisions, on the other hand this isn't in the original and allowing you to move your capital changes a lot, see all the capital bonuses in the tradition branch...
For now, at least, I'm against, but I may revisit this decision later on

**Comment by ninjatao** [comment]
Original civ5 has a victory type that being last civ that keeps it origin capital. If capital can be moved, this type of victory makes less sense.
