### ISSUE TITLE
The game should compensate for the production wasted in certain situations

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4047]
Situation 1: A wonder providing a building you are halfway building it. for instance being at 30 production on the library just when you built great library

Situation 2: a wonder being built elsewhere when you have already invested in production to it

those should not be complex to implement in game right?

**Comment by xlenstra** [comment]
iirc you already get some gold for your wasted production

**Comment by ravignir** [comment]
> 
> 
> iirc you already get some gold for your wasted production

nope, you get gold only in civ5, and that gold is equal to production spend.
