### ISSUE TITLE
Waiting for other players

### ISSUE THREAD

**Issue by Rivenrus** [yairm210/Unciv#4063]
Single player game. I cannot pass through 246 turn. 'Waiting for other players' is permanent. I can watch statistics, cities and even save the game, but my save put me in 246 again. 

The save is attached here. 
[0403-0201.zip](https://github.com/yairm210/Unciv/files/6603693/0403-0201.zip)

**Comment by SomeTroglodyte** [comment]
No wonder with the load you've placed on the game. MapSize huge, 27 city states, 24 AI civs.

Here the next turn works perfectly OK, except it takes a full minute.

**Comment by yairm210** [comment]
Ok, 'overloaded map listing to large turn times' is a given, not a bug

**Comment by SomeTroglodyte** [comment]
@Rivenrus  - If turn time before turn 246 was ***much*** shorter, then please state so and provide a turn 245 save as well?
Also, have you looked (after a loooong coffee while waiting for turn 247) at load game - show autosaves - whether the autosave loads to turn 247?

**Comment by Rivenrus** [comment]
Turns before 246 lasted just for several seconds. I tried to wait 246 to go through, but I can't, it's too long. 

I've got readme note 7 and the last version of unciv. I don't know why, but there was only one save game in Android/data/unciv/saves folder. Where can I find auto saves?

**Comment by SomeTroglodyte** [comment]
Autosaves - there's a checkbox bottom of the right hand column of the load game screen
And only one save - you obviously overwrote the same file diligently over and over with two extra taps
'readme note 7' is that hardware? Probably [this](https://www.gsmarena.com/xiaomi_redmi_note_7-9513.php) - Should be _at worst_ 4 times slower than a Mi8 which takes close to 100 seconds (yes, your save - and the _next_ turn tekes about 12). So wait those minutes! This turn _does_ finish eventually on a) Linux in the debug environment, on b) hardware as stated above,  and c) in a relatively starved AVM (virtualized Android Oreo) - in not much longer time than (a).

While there might be something worth learning here I don't think it's worth the effort, sorry.

**Comment by Rivenrus** [comment]
Thanks a lot for explaining everything. I'll try somehow to wait until next turn to check the turn after it. The only reason to write here was that all previous turns were just a few seconds long.
