### ISSUE TITLE
Invisible Barbarian encampment with 2 hourglasses

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4066]
i am unable to provide a demonstration on how to replicate it but basically sometimes barbarian encampments lose their texture, and when you move onto that tile with an attack unit it does not capture the encampment despite it saying Barbarian Encampment - 2⏳, i am unable to provide a vanilla proof for rhis but i also encountered it in the game, also the workers can rebuild barbarian encampments if like automated

![Screenshot_20210606-192713_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/120932113-3994a300-c6fd-11eb-8ecd-14fd40e1da11.jpg)

i'm sure others have encountered it as well

**Comment by AdityaMH** [comment]
> ![Screenshot_20210606-192713_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/120932113-3994a300-c6fd-11eb-8ecd-14fd40e1da11.jpg)

What tileset you used?

**Comment by ravignir** [comment]
that is a mod problem...

**Comment by logicminimal** [comment]
> that is a mod problem...

i'm almost certain that i encountered it on other gameplays though

**Comment by logicminimal** [comment]
> > ![Screenshot_20210606-192713_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/120932113-3994a300-c6fd-11eb-8ecd-14fd40e1da11.jpg)
> 
> What tileset you used?

it is not a texture bug, it does not capture when a unit is moved onto an encampment tile

**Comment by ravignir** [comment]
as i said, it is a mod bug. Barbarian Encampments lack "Uncapturable" unique.

**Comment by jahodovykolac** [comment]
It was probably an encampment that got pillaged. Definitely a mod bug.

**Comment by yairm210** [comment]
As stated, not an mods are 100% compatible with base ruleset rules.
