### ISSUE TITLE
Some of social policies are different than in vanilla civ5

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4068]
https://civilization.fandom.com/wiki/Social_policies_(Civ5)

**Comment by yairm210** [comment]
I can't try and guess from the lists
Can you give specific examples?

**Comment by ravignir** [comment]
Tradition:
Oligarchy | Garrisoned units cost no maintenance and cities with a garrison gain **+100%** Ranged Combat Strength. 

Honor:
Warrior Code | +15%  Production when training Melee units **and a Great General appears outside the  Capital.**
Discipline | **+10%**  combat strength for melee units which have another military unit in an adjacent tile.
Professional Army | Gold cost of upgrading Military Units reduced by 33% **and+1 Happiness from every defensive building (Walls, Castle, Arsenal, Military Base).**

Commerce - this tree is almost completely different:
Trade Unions | Maintenance paid on Roads and Railroads reduced by 33%. **Harbors and Seaports gain +1  Gold.**
Naval Tradition | +1  Movement for Naval units and +1 sight range for naval combat units.
Mercantilism | Requires Trade Unions.
Merchant Navy | +3  Production in all coastal Cities. Requires Naval Tradition
Commerce Complete | +1 Gold Gold from every Specialist 

Rationalism: | Science gained from research agreements by 50% 
Scientific Revolution | Gives 2 free Technologies.

Freedom:
Universal Suffrage | Combat Strength of Cities increased by 33%.
Free Speech | 8 units are maintenance free.

**Comment by xlenstra** [comment]
Which version of the game should the policies follow? The vanilla or the Gods&Kings version?

**Comment by xlenstra** [comment]
> Which version of the game should the policies follow? The vanilla or the Gods&Kings version?

If someone (@yairm210?) can answer this question I'll look into it later this week

**Comment by yairm210** [comment]
I think this might be a good time to differentiate the Vanilla and G&K 'base rulesets'.
I'm wondering what the best way to do this would be, but in general I'm thinking a mod.
That would clear up all confusing conflicts between versions, AND give us a good starting point to evaluate future mods.

I think 'vanilla Unciv' should be G&K, since it's much more mature that Vanilla Civ V, but also without all the very weird stuff they added in BNW.
We don't have religion yet, but I think that G&K is still the goalpost.

**Comment by yairm210** [comment]
I can't remember wat was Faith-based in G&K policies, but that's obviously not going to be relevant now. nything else can be changed to suit G&K.

**Comment by ravignir** [comment]
sticking to G&K makes sense given most of the things in Unciv are already based on G&K (Basically anything related to combat, techs, building stats to name a few).
here are g&k pollicies:
![obraz](https://user-images.githubusercontent.com/30041793/121263453-ec0f6600-c8b5-11eb-8e51-d7b41704f666.png)

**Comment by logicminimal** [comment]
> I think this might be a good time to differentiate the Vanilla and G&K 'base rulesets'.
> I'm wondering what the best way to do this would be, but in general I'm thinking a mod.
> That would clear up all confusing conflicts between versions, AND give us a good starting point to evaluate future mods.
> 
> I think 'vanilla Unciv' should be G&K, since it's much more mature that Vanilla Civ V, but also without all the very weird stuff they added in BNW.
> We don't have religion yet, but I think that G&K is still the goalpost.

happy too see the game getting improvements but is modding tools for unciv even enough for implementing offical dlcs into the game? i think it should be hardcoded into the game, and the player must be able to enable it just like any other mod

**Comment by yairm210** [comment]
> > I think this might be a good time to differentiate the Vanilla and G&K 'base rulesets'.
> > I'm wondering what the best way to do this would be, but in general I'm thinking a mod.
> > That would clear up all confusing conflicts between versions, AND give us a good starting point to evaluate future mods.
> > I think 'vanilla Unciv' should be G&K, since it's much more mature that Vanilla Civ V, but also without all the very weird stuff they added in BNW.
> > We don't have religion yet, but I think that G&K is still the goalpost.
> 
> happy too see the game getting improvements but is modding tools for unciv even enough for implementing offical dlcs into the game? i think it should be hardcoded into the game, and the player must be able to enable it just like any other mod

That's taking the power away from modders to determine whether they're working like A or like B. Minimal hardcoding is the way to go.

**Comment by SomeTroglodyte** [comment]
> here are g&k policies

That's beautifully crafted - I'll keep a copy in my work folder. Hats off! [:tophat: :womans_hat:](https://en.wikipedia.org/wiki/Chapeau)

**Comment by ravignir** [comment]
https://forums.civfanatics.com/threads/educated-elite.415436/
Maybe this will help implementing Patronage' Educated Elite policy mechanics
