### ISSUE TITLE
Add pillaging terrain improvements

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#407]

**Comment by yairm210** [comment]
The only reason this was done before some of the other things on the list is because it was super easy to implement, don't expect wishes to always come true within 2 hours =D

**Comment by ninjatao** [comment]
Why only damaged units can pillage？

**Comment by yairm210** [comment]
Originally because it heals health,
But if you want to hurt your enemy then you're right, this should be available for unhurt units as well
