### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by Max1350** [yairm210/Unciv#4076]
**Describe the bug**
Small size map

**To Reproduce**
1. Go to menu
2. Click on continue
3. Scroll down eye to map

**Expected behavior**
Map is very small

**Screenshots**
![Screenshot_20210608-091716](https://user-images.githubusercontent.com/85543902/121133199-baa58480-c83a-11eb-8dde-ec771d9530ec.png)

**Additional context**

**Comment by yairm210** [comment]
Minimap size is configurable in the options menu
The scaling was changed and therefore older game data should lead to oddly scaled minimap

**Comment by Max1350** [comment]
But in the settings I already have a maximum, no matter how I twist the size does not change, except for a couple of pixels
