### ISSUE TITLE
[MODDING] A resource unique that makes the resource disappear when terrain feature is removed.

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4079]
I've have a Hardwood resource in REKmod that only appears in forests and is improved by lumber mill. I want it to disappear when a forest is removed. Can someone implement an unique that does exactly that?

**Comment by ArchDuque-Pancake** [comment]
Yes please

**Comment by yairm210** [comment]
Please put this in #3242 - and I'll pin that, since it should also be a "list of etc."
