### ISSUE TITLE
Reword the description for oligarchy

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4087]
no maintenance costs for units in cities mislead the player by making them think that it makes units within borders of the empire to cost no maintenance costs, change it to be in city center

**Comment by AdityaMH** [comment]
"no maintenance unit costs for every unit inside city".

**Comment by logicminimal** [comment]
> "no maintenance unit costs for every unit inside city".

that could also mean within city borders to the player, just like it did to me, i played this game for motnhs not knowing i wasted one policy

**Comment by AdityaMH** [comment]
> > "no maintenance unit costs for every unit inside city".
> 
> that could also mean within city borders to the player, just like it did to me, i played this game for motnhs not knowing i wasted one policy

Inside city and inside border is different.

**Comment by logicminimal** [comment]
> > > "no maintenance unit costs for every unit inside city".
> > 
> > that could also mean within city borders to the player, just like it did to me, i played this game for motnhs not knowing i wasted one policy
> 
> Inside city and inside border is different.

for you, i thought it meant city borders for months

**Comment by yairm210** [comment]
I think that the current wording is actually better than the suggested one.
