### ISSUE TITLE
Is this normal? (pledge to protect)

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4088]
now im just directly going to explain the situation

i pledged to protect a city state, with a friendly Civilization that i have declared friendship also doing the same, then i positioned my troops inside the city states border, but when i revoked pledge to protect and declared war that friendly civilization declared war on me, i thought it would not declare war on me for we were friends, is this intended?

**Comment by yairm210** [comment]
It pledged to protect a city state that you attacked.
So, yes.
