### ISSUE TITLE
Ability to copy maps from single player games

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4089]
sometimes you get a good map but you dont like the civilization you get, in order to solve this i suggest being able to save maps from single player games.

**Comment by yairm210** [comment]
No.

**Comment by logicminimal** [comment]
> No.

:(

**Comment by logicminimal** [comment]
> No.

already fixed with new worldgen seed update

**Comment by logicminimal** [comment]
> No.

already fixed with the new worldgen seed update
