### ISSUE TITLE
Rewrite line-of-sight rules

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#409]
Bug or rule?

**Comment by yairm210** [comment]
Sorry what?

**Comment by Am-per-Sand** [comment]
I can swear that my ground unit was an innocent victim of AI frigate bombardment from a port city situated 2 tiles away, behind a hill. Is it purposeful?

**Comment by yairm210** [comment]
It can indeed bombard 2 tiles away
But it shouldn't bee able to bombard over a hill, are you sure?

**Comment by Am-per-Sand** [comment]
War crime evidence
![screenshot_2019-01-08](https://user-images.githubusercontent.com/40436282/50846984-b5ddfd00-1370-11e9-831d-04ce02c5ca99.png)

**Comment by yairm210** [comment]
Ahhh I seeee
The city is on a hill, and that's why it can attack beyond a hill, just like a regular unit

**Comment by yairm210** [comment]
Okay so strange as this sounds, this is actually okay 
You see, ranged units that can't indirect attack, can only attack tiles that they can see themselves.
Tiles beyond a sight blocking tile,e.g. hills, are only viewable if they are taller than the sight blocking tile, e.g. mountains... 
Or a hill with a forest/jungle! Which is exactly where the camel is!
I agree that it's very odd, and it took me some looking at the code to figure out what's going on, but it's legit.

**Comment by zivvel** [comment]
So a boat on sea level can see over hills, into forest among more hills? This does not seem right.

Forest/jungle should make a tile block vision more than a bare hill, but it should not imply that your camels are visible ... because they are sitting on the treetops?

**Comment by yairm210** [comment]
I agree that non-land units should get sight blocked from everything

As for vision block, I think I need to rewrite the whole thing as per jungle+hill tiles, that is, hills+ shouldn't be visible behind hills

**Comment by yairm210** [comment]
I think this is resolved 
Okay so, if we're looking at a tile from a to c with b in the middle,
we have several scenarios:
1. a>b -  - I can see everything, b does not hide c
2. a==b
   2.1 a==b==0, all flat ground, no hiding
   2.2 a>0, b>=c - b hides c from view (say I am in a forest/jungle and b is a forest/jungle, or hill)
   2.3 a>0, c>b - c is tall enough I can see it over b!
3. a<b
   3.1 b>=c - b hides c
   3.2 b<c - c is tall enough I can see it over b!

This can all be summed up as "I can see c if a>b || c>b || b==0 "

In the case of a water unit, a is always considered to be 0,
  so even if it's docked in a city on a hill it doesn't get "hill sight bonuses"
