### ISSUE TITLE
Being able to move units right when you have bought them.

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4095]
now in unciv currently you have to wait 1 turn to be able to move the unit that you just currently bought, but in one civ video that i watched the player was able to buy units, reposition them then buy others, and by this way he was able to get likr 5 units in one turn. i dont know if this counts as a suggestion, but i think this should be implemented

**Comment by ravignir** [comment]
"Can move immediately once bought" unique. Landsknecht has it.

**Comment by ravignir** [comment]
From what I see it was added in BNW, and you were unable to move them immediately in G&K/Vanilla.

**Comment by yairm210** [comment]
Working as intended
