### ISSUE TITLE
The AI does not understand that it can't capture a city with ranged units

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4096]
![Screenshot_20210610-103913_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/121484751-338e1300-c9d8-11eb-92a4-cf8affba8ded.jpg)

**Comment by SomeTroglodyte** [comment]
"Enemy city Osininka" - so you're basically showing us the inverse of what the caption claims?

**Comment by xlenstra** [comment]
I think he is showing how the AI aztecs has surrounded the entire AI city of Osinka (Iraquois) with ranged units so that he (Songhai) can't get close enough to capture the city, and how the Aztecs also don't have any melee units nearby to capture it instead.

**Comment by logicminimal** [comment]
> I think he is showing how the AI aztecs has surrounded the entire AI city of Osinka (Iraquois) with ranged units so that he (Songhai) can't get close enough to capture the city, and how the Aztecs also don't have any melee units nearby to capture it instead.

exactly

**Comment by JackRainy** [comment]
Is it resolved by #6771 ?

**Comment by yairm210** [comment]
Should be, yes
