### ISSUE TITLE
Option to highlight units

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4097]
even if i disable resource indicators, in lste game i could barely spot my units. an example here:

![Screenshot_20210610-112414_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/121491185-6804cd80-c9de-11eb-8dcc-5d6791b7915b.jpg)

despite having pixel units on it is really hard to spot one from another as they look like tile improvements and they blend a bit with the tile they are on

**Comment by xlenstra** [comment]
You can always go to overview -> units and click the buttons of the units you want to select. Other option is that you change to the default tileset, leaving pixel units on. That way they should be better visible. imo they are visible enough on your screenshot that I don't think it necessary enough to change them.

**Comment by yairm210** [comment]
You can remove the improvement and resource display also on fantasyhex tileset, this seems entirely solvable within the current framework.

**Comment by logicminimal** [comment]
> You can remove the improvement and resource display also on fantasyhex tileset, this seems entirely solvable within the current framework.

not really when you are using mods and the default tileset has no textures for such resources etc. instead of highlighting even render prioritizing the unit icons and making them bigger would work
