### ISSUE TITLE
Make spaceship parts national wonders and limit amount of cities automatically building spaceship factories late game

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4098]
most often cities automatically build spaceship parts which other cities also happen to be building, in order to fix this i suggest making spaceship parts national wonders, also the ai should be less motivated to build spaceship factories, or should not ever automatically build them as they eat up a lot of resources late game and dont provide a proper improvement as spaceship parts getting built is a chaos by itself

**Comment by xlenstra** [comment]
Problem with making them national wonders, is that you need 3 boosters, and it should be possible to build these simultaneously. Only making the other parts national wonders also doesn't make any sense. I personally feel like we should keep the current decently working system until we implement the spaceship parts correctly as civilian units, with a maximum of how many can exist at once.

**Comment by jahodovykolac** [comment]
Maybe some unique like "Can be built X times?"

**Comment by logicminimal** [comment]
> Problem with making them national wonders, is that you need 3 boosters, and it should be possible to build these simultaneously. Only making the other parts national wonders also doesn't make any sense. I personally feel like we should keep the current decently working system until we implement the spaceship parts correctly as civilian units, with a maximum of how many can exist at once.

didnt know they needed to be built 3 times, but still, the ai builds a lot of spaceship factories while they could have just built spaceship parts

**Comment by logicminimal** [comment]
> Maybe some unique like "Can be built X times?"

there is the spaceship factory also, even the cities with 1/3 production of the capital try to build it as nothing else is left to build, i think the ai shouldnt be able to auto build spacechip factories

**Comment by SomeTroglodyte** [comment]
We'll need unit count limits for the GDR's too. But - I remember having a branch early 2020 with a version of the city construction queue that allowed queueing dependent stuff - e.g. you could queue university after library, you could move stuff around but never get U above L, buying L would remove U and so on. And it was clever enough to allow 3 boosters and _then_ stop you from queueing more. So the basic mechanics and rules must have already existed back then.

**Comment by logicminimal** [comment]
comment to bring this issue up

**Comment by SomeTroglodyte** [comment]
See #4697

**Comment by logicminimal** [comment]
> See #4697

closed

**Comment by logicminimal** [comment]
> See #4697

btw how do you make screenshots for your pull requests only show up when clicked? i cant seem to recreate this with markdown as i couldnt find any resources for it

**Comment by xlenstra** [comment]
```
<details> <summary> some line of text </summary>

Put what you want to hide here

</details>
```

<details> <summary> some line of text </summary>

Put what you want to hide here

</details>

**Comment by logicminimal** [comment]
> ```
> <details> <summary> some line of text </summary>
> 
> Put what you want to hide here
> 
> </details>
> ```
> 
> <details> <summary> some line of text </summary>
> 
> Put what you want to hide here
> 
> </details>

thanks!

**Comment by SomeTroglodyte** [comment]
Go to my profile, look for my 'Scratchpad' repository, the notes folder, there's instructions _somewhere_ in there. For future reference - if I pull something tricky-looking, chances are I've documented it there.

When you find it you'll probably also get the dirty details like - github absolutely needs the blank line after `</summary>` and any formatting inside needs to be html, not markdown...

**Comment by logicminimal** [comment]
> Go to my profile, look for my 'Scratchpad' repository, the notes folder, there's instructions _somewhere_ in there. For future reference - if I pull something tricky-looking, chances are I've documented it there.
> 
> When you find it you'll probably also get the dirty details like - github absolutely needs the blank line after `</summary>` and any formatting inside needs to be html, not markdown...

is there any way to use new lines in <details>?

like this
<details><summary>Something</summary> 
- line 1
- line 2
- line 3
+ line3
</details>

btw i checked stratchpad repo and i couldnt find anything about summary htmls?

again btw i really like the workable rings being moddable, like if there was a unique that allowed something like this it would be amazing
building: "Workable Tile Range [cityFilter] [amount]"
two things i would add on top of this is how many population can work inside workable territory (specialists are not impacted) like it would default to how many tiles there are in 3 rings of hexagons and the modders could do something like you can work up to 7 tiles away but you can't naturally get land and land is more expensive, also you can't assign more than 6 population/tiles [cityFilter]
another thing would be to being able to assign more than 1 pop inside a tile like i  civ 6
