### ISSUE TITLE
Aristocracy dosen't prove happiness boost

### ISSUE THREAD

**Issue by bobabae** [yairm210/Unciv#4109]
Aristocracy broken again? Have multiple cities with pop > 10. After enacting policy, I get the wonder production boost but no happiness boost.

**Comment by xlenstra** [comment]
I'll look into this somewhere in the following weeks

**Comment by ravignir** [comment]
The bug was introduced in 3.14.5 and it affects all +x stats from y population in z uniques.
+x growth in y is also not working, but that bug is even older.
