### ISSUE TITLE
City state tech

### ISSUE THREAD

**Issue by bobabae** [yairm210/Unciv#4110]
Noticed after a recent update that city state tech no longer matches the tech of most advanced player. 

For example, I have railroads and artillery but cs still have roads under city center and have been stuck on cannons for many turns now. I don't have a way to test, but maybe cs now only matches the tech of most advanced AI player.

**Comment by xlenstra** [comment]
Correct, this was changed. CS now only have techs that at least half of the nations in the game have

**Comment by yairm210** [comment]
Changed to fit Original Civ rules
