### ISSUE TITLE
Free speech and Universal suffrage don't work

### ISSUE THREAD

**Issue by comradeKozovod** [yairm210/Unciv#4122]
Free speech and universal suffrage in freedom branch don't work

**Comment by xlenstra** [comment]
Has been reported before, I'll look into this probably this week.

**Comment by logicminimal** [comment]
doesn't work for me as well

**Comment by xlenstra** [comment]
This problem was due to the uniques in the policies.json object not having square brackets around the cityFilter part. As they have now been replaced by different uniques in #4142 and the uniques themselves (with square brackets) do work, this issue can be closed.
