### ISSUE TITLE
Change the tile rendering layers order

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4125]
![obraz](https://user-images.githubusercontent.com/30041793/121803974-46a51b00-cc44-11eb-98e3-07bb3b6202c8.png)
basicaly render the units and borders on the tile they are currrently on and not on top of the entire map. So the borders/units will be partially covered by taller tiles.

**Comment by SomeTroglodyte** [comment]
I partially disagree regarding borders - seems like your suggestion would make them invisible on 3-5 edges in your example. 50% alpha in such cases might be ideal - but more complicated as you'd have to detect the case first...

Let's not forget the information disclosure issue - spilling graphic will reveal mountains, forest and other stuff that is behind fog-of-war, or is that one already solved?

**Comment by ravignir** [comment]
> 
> 
> I partially disagree regarding borders - seems like your suggestion would make them invisible on 3-5 edges in your example. 50% alpha in such cases might be ideal - but more complicated as you'd have to detect the case first...
Is this a big problem tho? the borders are visible on the minimap and you can easily say they are here, because their placement is quite logical.

> 
> Let's not forget the information disclosure issue - spilling graphic will reveal mountains, forest and other stuff that is behind fog-of-war, or is that one already solved?

if there is a fog of war, nothing on that tile is visible. 
![obraz](https://user-images.githubusercontent.com/30041793/121820707-9ad7eb80-cc94-11eb-91f2-b1c93b4c48a1.png)
![obraz](https://user-images.githubusercontent.com/30041793/121820717-a3302680-cc94-11eb-92e8-775e42f55010.png)

**Comment by SomeTroglodyte** [comment]
That looks good - I just _vaguely_ remember something else. Not even sure which tileset.

**Comment by yairm210** [comment]
Borders SHOULD be above all terrain.
As for units, I concede your point, but they're currently on an entirely different layer for performance reasons, and moving them would have a big performance cost... So not currently viable. My only suggestion is to make your mountains not cross over tiles...?

**Comment by ravignir** [comment]
what about the units?
