### ISSUE TITLE
Make excess production show in the city overview

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4126]
make it appear next to production, for instance if you have 15 production and 7 leftover production it should look as such

⚙️15(+7) characters inside the paranthesis should be tinted a different color with the paranthesis removed, or you could just keep the paranthesis and not apply the tint

**Comment by logicminimal** [comment]
i see that you have instead directly added it into city's production, but the problem is that it is often confusing so it might be better to seperate them #663

**Comment by yairm210** [comment]
I disagree. The leftover production is de-facto considered part of the next turn's production, and should be shown as such. Separating this into 2 numbers only makes things for confusing, not less.
