### ISSUE TITLE
Delete save games

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#413]
I would like to be able to delete a particular save game file from outside the game, ex. some file manager application. Currently I cannot find a path to savegames (folder?).

After reaching 19. century with the __Autosave__ and keeping 30+ number of savegames the game refused to start. Closes on start, i.e. exits to desktop. (Tried clearing the cache, restart the device, etc). Shortly before it started to take very long to start (to load the autosave) and sometimes selecting a savegame from the list resulted in exit to desktop.  Starting a new game and playing a turn (overwriting the autosave) helped.

There seems not to be an option to start a game on start screen with an autosave present. Any way to delete it while keeping other autosaves?

**Comment by Am-per-Sand** [comment]
Thanks for consolation. I would like to finish this game some day, to the end of the tech tree at least. I hope some future update will take me out of this bug.

**Comment by yairm210** [comment]
By next version (2.12.1), you should be able to enter the game with a huge autosave and it won't Application Not Responding at you =D
