### ISSUE TITLE
Some units are just overpowered.

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4134]
Submarines: They are not only invisible, but also invincible: Only another sub or destroyer can attack submarines, which makes the entire naval combat onesided -> basically the first player to lose their subs, loses the rest of their fleet. 

That is not how Subs work in Civ5: in civ5 enemy subs are also revealed whenever your unit borders them. Revealed subs can be attacked like if they were a regular naval unit.
![obraz](https://user-images.githubusercontent.com/30041793/121821048-a0363580-cc96-11eb-8776-ade6bf00cd1c.png)

Air units are also a bit OP, because they suffer no damage when they attack a target. In civ5 Air units are more like melee units with an ability to attack distant targets > https://civilization.fandom.com/wiki/Air_combat_(Civ5) <. Air units in civ5 take retaliation damage like a melee unit and they receive 4 XP per attack.

**Comment by jahodovykolac** [comment]
> Air units are also a bit OP, because they suffer no damage when they attack a target.

That's why Triplane-type units exist, they're weaker but can deal damage when someone attacks.

**Comment by ravignir** [comment]
Triplanes exist in civ5 as well and you can avoid them with air sweep. The point is air units should take retaliation damage like in civ5.

**Comment by yairm210** [comment]
Please stop reposting #663 issues...
