### ISSUE TITLE
Resource icons render below borders

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4140]
![Screenshot_20210614-070317_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/121837602-b1a33000-ccde-11eb-9c85-35bdfa70274e.jpg)

also i think something is off with yield icons that touch borders but i cant quite make it

**Comment by jahodovykolac** [comment]
I think this is intended. I know, it can look a bit wierd when it's covered but trust me - if it was the other way around, it would look horrible. Maybe that's even the thing that looks wrong on those yield icons, because the ARE overlaping the borders.

**Comment by yairm210** [comment]
This is valid.
