### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4144]
The screenshots in Google Play and Github should be updated to reflect the latest versions.

**Comment by yairm210** [comment]
Well give me new ones.

**Comment by sockybob** [comment]
Made some
![S10616-180002](https://user-images.githubusercontent.com/44141246/122243965-32278380-cecd-11eb-8f71-0e6644becb81.jpg)
![S10616-175414](https://user-images.githubusercontent.com/44141246/122244113-48354400-cecd-11eb-9a41-18dcc8482f9f.jpg)

**Comment by jahodovykolac** [comment]
The second one looks very good

**Comment by AdityaMH** [comment]
I want to share, but i don't know why. I can't upload via Chrome.

**Comment by jahodovykolac** [comment]
> I want to share, but i don't know why. I can't upload via Chrome.

Hmmm, I have the same problem for the last few days.

**Comment by logicminimal** [comment]
> Well give me new ones.

@yairm210 i think the screenshots should be voted on the discord if they are eligible

**Comment by SomeTroglodyte** [comment]
Second screenie is demonstrating a slight bug: IMHO being-razed cities shouldn't gain culture and shouldn't expand (just as they shouldn't build buildings - but they can under circumstances like legalism or overflow if I'm not out of date on that)...
