### ISSUE TITLE
Multiplayer game could not be downloaded 

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#4155]
**Describe the bug**
After updating to version 3.15.0 from Playstore, the game is unable to download my online multiplayer game. 
After starting a quickstart game, 
it is possible to download and play the multiplayer game. 
**To Reproduce**
1. Update to 3.15.0
2. Close the game completely
3. Open Unciv
4. Try to update multiplayer list 
5. Error occurs that the game could not be downloaded
6. Start a quickstart game without doing anything
7. Go back to main menu and update multiplayer list
8. Join and play the multiplayer game

**Expected behavior**
RFC1925: 2.1

Mods Civ5 Expansion and 5HexTiles are in use

**Comment by SomeTroglodyte** [comment]
> RFC1925

[Twelve Networking Truths](https://datatracker.ietf.org/doc/html/rfc1925)??? :wink:

**Comment by Mape6** [comment]
> > RFC1925
> 
> [Twelve Networking Truths](https://datatracker.ietf.org/doc/html/rfc1925)??? 😉

https://datatracker.ietf.org/doc/html/rfc1925#section-2 Point 1 😉
