### ISSUE TITLE
AIs are too weak even under high difficulty.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#416]
AIs can catch up in ancient ages, but rapidly fall behind in technology and production, which makes late-game very un-challenging. Here are something maybe we can do:

1. Make AIs trade technologies between themselves. This should make them more advanced in tech race, and is relatively easy to do.
2. Improve AI war strategy. AIs now tend to waste military units with very small-sized attacks, and left their city unguarded. This may be hard, because as far as I know, original civ5 AIs also suck at warfare.
3. If none of the above works, maybe increase AI bonus?

**Comment by Am-per-Sand** [comment]
That is true in most games - AI likes to storm a city with a single melee unit until it realizes it has been injured and withdraws, leaving a settler unguarded after its convoy had been weakened. 

However in one game AI had two quite developed cities just over a border. Quite early in game, around 0 AD it started sending pairs of catapults against my city and withdrew them once they got hit by my ranged unit from within city walls. So I never managed to completely destroy any of them.
When I created a mounted unit to finish off one siege unit before it runs away to its home city, catapults appeared accompanied by pikemen. So AI seems quite capable of capturing towns.

On the other hand it is quite difficult to capture a city, sometimes even with two siege units. Almost impossible when a ranged unit is based inside the city. Therefore I sometimes use 3 siege units. Would it be difficult to introduce to AI algorithms a limit against solitary raids against cities and demand they use at least two siege units every time?

**Comment by flecheapolinienne** [comment]
Knowing how hard good AI must be to program for Yair, I'm asking myself if it would be to introduce multiplayer instead, so we can play against one another and have many more hours of fun! I've heard multiplayer normally implies servers but maybe we could make do with some sorts of old school ad-hoc connection, being that the game is so light?

**Comment by yairm210** [comment]
The problem lies in how two phones find each other, and how you transfer data between them
If there's a way to do this without servers then for me it's vastly preferable

**Comment by reijin90** [comment]
> The problem lies in how two phones find each other, and how you transfer data between them
> If there's a way to do this without servers then for me it's vastly preferable

For Async multiplayer:
Maybe leveraging the Google Play Game Services API?
https://developers.google.com/games/services/common/concepts/turnbasedMultiplayer

This may sound dumb, but email/Google drive could be an option too. I remember some people in my office playing chess against eachother on a turn-by-turn basis, where they were sending the gamestate via email between eachother. 

"Real time" multiplayer will not be working without servers as we need to punch through NATs and Firewalls. Some sort of relay and probably a lobby is necessary (if we assume both parties trust eachother not to cheat).

**Comment by ninjatao** [comment]
AI now exchange techs between them. They will also use money to buy techs(from other AIs), buildings and units. This will make the game more challenging.
To do : AI war tactics improvement. Any suggestions? Maybe we make AI military units only move in groups?

**Comment by flecheapolinienne** [comment]
Considering it is basic strategy to do so as a player, having the AI move its troops in groups would be an awesome idea!

**Comment by Am-per-Sand** [comment]
In one of recent games an AI worker crossed my border during war and started improving my tiles. How kind. 
I followed this strategy: captured one of his workers and made them build roads in many tiles of AI territory. Managed to build some bypasses and junctions before one AI city busted this unit. Hope it drained AI budget a bit.

**Comment by ninjatao** [comment]
It seems that in oringin civ5 it is also possible to increase ai upkeep by building roads in their border. So maybe that won't be a problem.
