### ISSUE TITLE
Problem with Tradition Complete

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4165]
i got tradition complete when i had 3 cities and 1 tech away from engineering, i adopted oligarchy then i didnt get aqueducts in my cities, which is fine but when i researched engineering i did not get 3 aqueducts in my cities, this must be a bug right?

**Comment by ravignir** [comment]
you should get aqueducts even without engineering

**Comment by logicminimal** [comment]
when i checked about 40 turns later without building any aqueducts i found aqueducts in buildings tabs of my cities, but i dont remember getting an aqueduct built in x city message

**Comment by logicminimal** [comment]
> you should get aqueducts even without engineering

i guess not getting a built message is what made me skeptical, i am going to re-try this

**Comment by yairm210** [comment]
This works, yeah
