### ISSUE TITLE
Re-add requires translation tag for translation lines that have changed due to updates

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4169]
i dont know if this is already being done but if it is not then it is bad for both the game and translators

**Comment by AdityaMH** [comment]
I heard crowdin has free translation service (and of course, translated by fans member) for open-source project.

**Comment by logicminimal** [comment]
> I heard crowdin has free translation service (and of course, translated by fans member) for open-source project.

i think the current one is good enough

**Comment by yairm210** [comment]
Crowdin is much worse than the current one, actually, for a variety of reasons mentioned in another issue.
And changed lines are marked as requires translation.
