### ISSUE TITLE
Some visual ideas

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4171]
~In the New game screen, the No Ancient ruins, No Natural Wonders and World Wrap buttons are aligned on the left side, in the center it looked better.~
[For some reason I can't put an image here :/]

**Comment by SomeTroglodyte** [comment]
Disagree. I like them as they are better than individually centered. Instead I would:
- Have some padding between the check circle and the text - everywhere
- Left-Pad them a little _or_ wrap them and center the wrapper so the actual check circles _stay aligned_
- Do the same for Game Options -> barbarians..multiplayer
- Align the mod's checkboxes
- Set off the Base ruleset / Extension distinction more clearly
- Sort the mods to some predictable ordering
- And I forgot I wanted to add the leader portraits to the nation chooser

**Comment by jahodovykolac** [comment]
Okay, I will delete my idea and keep this issue for your ideas.

**Comment by yairm210** [comment]
I think this is closable, seems like the points have been addressed
