### ISSUE TITLE
Temple doesnt show up as a soon to be available building in philosophy

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4176]
![Screenshot_20210617-102335_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/122350790-32b82c80-cf56-11eb-9407-dac890ddc1c7.jpg)

playing as egypt on the most up to date version

**Comment by xlenstra** [comment]
This is because Egypt has a special building, the Burial tomb, which replaces the temple

**Comment by logicminimal** [comment]
> This is because Egypt has a special building, the Burial tomb, which replaces the temple

it should show up in philosophy though..

**Comment by xlenstra** [comment]
No, because Egypt can't build the temple anyway it is replaced with the Burial Tomb icon. This same thing happens for all buildings and units that replace other buildings and units for other nations.

**Comment by logicminimal** [comment]
> No, because Egypt can't build the temple anyway it is replaced with the Burial Tomb icon. This same thing happens for all buildings and units that replace other buildings and units for other nations.

well then thats a problem as well

**Comment by xlenstra** [comment]
Why should the temple be visible? Egypt is unable to build it anyway?

**Comment by logicminimal** [comment]
> Why should the temple be visible? Egypt is unable to build it anyway?

yes, but it would imply that buildings based on temple could be built

**Comment by xlenstra** [comment]
But the only building based on temples that Egypt can build is the burial tomb, and that is visible? So I don't see the problem here.

**Comment by logicminimal** [comment]
> But the only building based on temples that Egypt can build is the burial tomb, and that is visible? So I don't see the problem here.

what im saying is that the tech description should not remove the buildings that has been changed with a nation specific one
