### ISSUE TITLE
'Aristocracy' does not add happiness

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4177]
Aristocracy declared as providing
+ 15% production when construct Wonders (this is working well) 
+1 happiness in every city for every 10 citizen in the city - **this is not working**

**Comment by ravignir** [comment]
which version are you on?

**Comment by Bershcomp** [comment]
Catched this a week ago on latest one being in Google Play. Now on 3.15.0 I even can't load the game from yesterday save file and check

**Comment by xlenstra** [comment]
Temporarily create a new game, after that you should be able to open your old save. The aristocracy bug should be fixed in 3.15.0 and later.

**Comment by Bershcomp** [comment]
Yes, now I see it fixed. And also the create new game helped to load old save file
