### ISSUE TITLE
3.15.0 does not load games saved by previous release on android

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4179]
**Describe the bug**
3.15.0 refuses to load my saved games

**To Reproduce**
1. Download saved game
2. Try to load it on android
3. Get error message

If game data is required, please add from menu, save game, copy to clipboard, paste here
[Saved game](https://yadi.sk/d/KONGJWCBtzTMKg) 
**Expected behavior**
Expect game to load
**Screenshots**
[Screenshot is here](https://yadi.sk/i/po8ZJcYOVwYNXg)

**Comment by xlenstra** [comment]
Bug is known and fixed in 3.15.1, which should hit the play store in a few days

**Comment by xlenstra** [comment]
Easiest fix is to open up a new game, immediately close it, and after that you can load your old saves again

**Comment by Bershcomp** [comment]
This helped, thank you.

**Comment by Bershcomp** [comment]
Will this happen again with next update? For me to apply the same trick? Or will it be fixed?

**Comment by xlenstra** [comment]
It might happen again when you close the game and open it again, but you can always solve it in the same way.
Once 3.15.1 releases, this should be fixed.
