### ISSUE TITLE
Option to switch to old UI scaling

### ISSUE THREAD

**Issue by avdstaaij** [yairm210/Unciv#4185]
A while ago, the UI scaling logic was changed to be much sharper and less anti-aliased. I'm not sure when exactly this was done and whether it was intentional. Personally, I think the new scaling looks significantly worse, especially on the larger resolutions you'd use on desktop. I can see people preferring the new scaling though, so I would like to have an option to use the old scaling.

Here is a comparison of the old and new scaling (which may be of course be altered by whatever compression GitHub uses):
![unciv-scaling-comparison](https://user-images.githubusercontent.com/32672293/122485492-58d1e100-cfd7-11eb-98d8-c36bce1eb6c1.png)

**Comment by xlenstra** [comment]
If I'm not mistaken, this was changed in #4080

**Comment by avdstaaij** [comment]
Seems like this was unintentional, then.

**Comment by ArchDuque-Pancake** [comment]
I would prefer a middlepoint instead

**Comment by avdstaaij** [comment]
I don't think a middle point is possible, since the difference is essentially nearest neighbor filtering versus linear mipmap filtering. There is not really a continuous scale between the two.
