### ISSUE TITLE
Make the Promotion screen not go back to the top of the page when you promote an unit

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4189]
when you promote an unit the screen goes all the way up which is frusturating when you rapidly try to upgrade the units. this issue, obviously is not the most important thing and the people directly working on the game shouldnt tske their time to fix this but it would be cooled if someone just fixed this in their free time and merged it

**Comment by Mape6** [comment]
It's a good idea. The promotion screen should not came back after promotion but only if the unit don't have enough XP for another promotion. 
So for example if it is possible to give the unit 3 promotions, only after the third promotion the screen should not show up again. After the first and second the screen should still show up.
