### ISSUE TITLE
Gold wasted while upgrading mid-turn end.

### ISSUE THREAD

**Issue by Al-1ce** [yairm210/Unciv#4198]
**Describe the bug**
Upgrading a unit while waiting for a turn to end results in the gold being consumed, but the upgrades not being carried over.

**To Reproduce**
1. End Turn on a slow game (turn 600, large map)
2. Click on Warrior
3. Upgrade to Swordsmen
4. Turn ends, swordsmen convert back to the warrior, and the gold is still consumed.

**Expected behavior**
I would expect the upgraded units to remain upgraded, or at the least not being able to be upgraded when waiting for your turn to end.

**Additional context**
This also applies when purchasing a building in a city or purchasing a unit; the gold remains consumed once the turn is over and the unit does not spawn.

**Comment by yairm210** [comment]
This shouldn't be possible, since when you click 'next turn' all unit actions should be disabled. Can you send the autosave of the previous turn?

**Comment by Al-1ce** [comment]
> This shouldn't be possible, since when you click 'next turn' all unit actions should be disabled. Can you send the autosave of the previous turn?

I play on mobile, it hasn't happened to me on PC.

**Comment by yairm210** [comment]
This is probably solved by #4206
