### ISSUE TITLE
Suggestion for new ai behaviour

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4202]
![Screenshot_20210619-183704_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/122647570-69946b00-d12d-11eb-9d64-fada9b97a393.jpg)

if we exclude the fact that i am very late into the game and that i dont need any of those resources; if a city has a workboats improvable resource but it is landlocked then it should alert the nearest city for it to start building workboats -if they have direct sea access to that tile-. like the algorithm for it should be like this

1: get distance from those coastal cities to the resource tile

2: remove the cities that dont have a direct sea route that it can travel from

3: get the cities that are least busy as in building or training stuff

4: randomly pick a city to build a workboat, with their "business" greatly affecting the random city selectors bias

**Comment by jahodovykolac** [comment]
I think AIs should prefer coastal tiles in general. It's so annoying to conquer a city which is 1 tile from coast, so you can't build water units, nor buildings like harbour (or how is it called) so you have only one food from coast, but still you have access to it.

**Comment by logicminimal** [comment]
> I think AIs should prefer coastal tiles in general. It's so annoying to conquer a city which is 1 tile from coast, so you can't build water units, nor buildings like harbour (or how is it called) so you have only one food from coast, but still you have access to it.

yep, i wish there was a mod that let you build a building that connected cities 1 tiles away from the water to water

**Comment by ravignir** [comment]
> 
> 
> I think AIs should prefer coastal tiles in general. It's so annoying to conquer a city which is 1 tile from coast, so you can't build water units, nor buildings like harbour (or how is it called) so you have only one food from coast, but still you have access to it.

I disagree. Coastal cities tend to be more vulnerable to attack.

**Comment by jahodovykolac** [comment]
> Coastal cities tend to be more vulnerable to attack

Can I ask how? Sea units are almost the same strong as land units, they're just "faster", also land units get penalty when attacking from sea. I don't see a problem here.

**Comment by ravignir** [comment]
> > Coastal cities tend to be more vulnerable to attack
> 
> Can I ask how? Sea units are almost the same strong as land units, they're just "faster", also land units get penalty when attacking from sea. I don't see a problem here.

They are faster is enough. And they are less vulnerable to counter attacks.
