### ISSUE TITLE
AI pillages their own tiles.

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4203]
AI, and mostly city-states, pillage and destroy their own tiles very often to heal, or even just because. They pillage even their own luxuries and resources without much logic, as seen in the save files.

Save files (Latin american civs.0.9):

https://1drv.ms/u/s!AorYSegPgGoLgl9IpCDo2IZMd45K

**Comment by ravignir** [comment]
you can't pillage your own tiles in civ5

**Comment by ArchDuque-Pancake** [comment]
Nice
