### ISSUE TITLE
Overzealous usage of "Found City" sound

### ISSUE THREAD

**Issue by BlueManedHawk** [yairm210/Unciv#4209]
**Describe the bug**
The "Found City" sound (there may be other uses for it, but all the onomatopoeias I could think of were rude) plays seemingly randomly.

**To Reproduce**
I'm not quite sure.  The sound _appears_ to be playing randomly, but I recognize that it could be from undiscovered nations founding cities.

**Expected behavior**
This sound would only play when the player founds cities or does other particularly majestic things.

**Screenshots**
Not applicable.

**Additional context**
I'm on version `3.15.2-patch1`.

**Comment by AdityaMH** [comment]
This bug appear since 3.15.1

**Comment by logicminimal** [comment]
same here
