### ISSUE TITLE
city production menu wont load

### ISSUE THREAD

**Issue by foxymacko-real** [yairm210/Unciv#4213]
for some reason
i cannot view the city production menu, when i try to turn on "auto assign city production" the game crashes, 
![h](https://user-images.githubusercontent.com/79454795/122675399-85ede180-d1d9-11eb-880d-fbf3b503c4e2.png)

any idea why?

**Comment by foxymacko-real** [comment]
wont load, i waited for 10 minutes and nothing happend

**Comment by yairm210** [comment]
What version number?

**Comment by yairm210** [comment]
This should be solved in 3.15.2 IIRC
Please upgrade
