### ISSUE TITLE
A few issues and features

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4224]
# Issues:
- The player is unable to build Petra when directly in a desert and (maybe) coast

![Screenshot_20210621-160259_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/122766449-34f9ee00-d2aa-11eb-9997-4bab05f0dce1.jpg)

https://hastebin.com/raw/ovoviquyof

- Rail/roads dont appear automatically in city centers, which is problematic for many things, one guy on discord told me that they automatically connect etc but this does not seem to be the case, especially when routing your roads through city state borders that uses the city center roads. The AI does not understand that there is no road in city centers, so the road is never completed which is EXTREMELY problematic as you cant manually build roads in city centers of other civilizations.

![Screenshot_20210621-151720_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/122768536-5cea5100-d2ac-11eb-9231-fc26e51ede3e.jpg)

i had to manually build two roads to the south the city center just so it would conenct cities, the workers also built the same road route but it didnt work (as this issue) so they moved to this road route which i happened to fix. I am unable to provide a save file for this but i am sure you can just recreate this bug

-----------------------------------------------------------------
# Suggestions:
- Being able to ask another civ about moving their units, however opening this suggestion to a debate makes the way for the loyalty to the original game discussion. Now this mechanic is not found within the original game, and this game tries to absolutely stay loyal to the game, which is good in theory but the problem is the original civilization games are not bug or bad-mechanics free, and in my opinion unciv is a great opportunity to fix these bugs or bad mechanics found within the original game

![Screenshot_20210621-152321_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/122767569-7a6aeb00-d2ab-11eb-8d66-decaece247f9.jpg)

- Make city centers still show up despite having pixel improvements disabled.

- Make promotions screen's layout to be more like the policies one, as a list might be confusing at times ( Drill 2 found below drill 1, blitz found in between drill 3, accuracy 3 etc. )

i observed these issues in 3.15.2-patch1

**Comment by xlenstra** [comment]
> The player is unable to build Petra when directly in a desert and (maybe) coast

Fixed in 3.15.3, update should be available soon.

> Rail/roads dont appear automatically in city centers, which is problematic for many things, one guy on discord told me that they automatically connect etc but this does not seem to be the case, especially when routing your roads through city state borders that uses the city center roads. The AI does not understand that there is no road in city centers, so the road is never completed which is EXTREMELY problematic as you cant manually build roads in city centers of other civilizations.

Roads to indeed not connect through city centers of other civilizations, only through your own city centers. This behavior is the same in the original game, to my knowledge. 

> Being able to ask another civ about moving their units, however opening this suggestion to a debate makes the way for the loyalty to the original game discussion. Now this mechanic is not found within the original game, and this game tries to absolutely stay loyal to the game, which is good in theory but the problem is the original civilization games are not bug or bad-mechanics free, and in my opinion unciv is a great opportunity to fix these bugs or bad mechanics found within the original game

Isn't in the original game, so it's unlikely it's going to be added. UI for this could be difficult as well.

> Make promotions screen's layout to be more like the policies one, as a list might be confusing at times ( Drill 2 found below drill 1, blitz found in between drill 3, accuracy 3 etc. )

I like this idea. It will be difficult to implement, though, as some promotions can have multiple possible prerequisites, so the trees would have to be built automatically.

**Comment by logicminimal** [comment]
> > Rail/roads dont appear automatically in city centers, which is problematic for many things, one guy on discord told me that they automatically connect etc but this does not seem to be the case, especially when routing your roads through city state borders that uses the city center roads. The AI does not understand that there is no road in city centers, so the road is never completed which is EXTREMELY problematic as you cant manually build roads in city centers of other civilizations.
> 
> Roads to indeed not connect through city centers of other civilizations, only through your own city centers. This behavior is the same in the original game, to my knowledge. If automated workers do this, however, that is a bug.

The ai tries to employ city state city center roads while building road routes, whoch is problematic by itself, but another problem is that the cities **Don't** get a road in the city center

**Comment by yairm210** [comment]
The bugs reported are not bugs, and the suggestions (apart from the promotions which we'll have to see) are not accepted.

**Comment by logicminimal** [comment]
> The bugs reported are not bugs, and the suggestions (apart from the promotions which we'll have to see) are not accepted.

city states city centers not connecting roads, is however

**Comment by logicminimal** [comment]
also i have a found another bug about routing also

![Screenshot_20210626-181949_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123517761-796efa80-d6ab-11eb-979a-dad3983b67df.jpg)

the ai does not know what to do when a foreogn unit blocks their path of routing

**Comment by logicminimal** [comment]
> > Rail/roads dont appear automatically in city centers, which is problematic for many things, one guy on discord told me that they automatically connect etc but this does not seem to be the case, especially when routing your roads through city state borders that uses the city center roads. The AI does not understand that there is no road in city centers, so the road is never completed which is EXTREMELY problematic as you cant manually build roads in city centers of other civilizations.
> 
> Roads to indeed not connect through city centers of other civilizations, only through your own city centers. This behavior is the same in the original game, to my knowledge. If automated workers do this, however, that is a bug.

@yairm210 this seems like a kind of game breaking bug, should i open a separate issue about this?
