### ISSUE TITLE
Improvements do not show up

### ISSUE THREAD

**Issue by 7addva** [yairm210/Unciv#4229]
Improvements are non present on the improvements screen

When the improvement screen is opened, no improvements show up

(I tried to find my screenshot of it, but I had no luck. I will upload it when I find it)

**Comment by yairm210** [comment]
What version number?

**Comment by logicminimal** [comment]
> Improvements are non present on the improvements screen
> 
> When the improvement screen is opened, no improvements show up
> 
> (I tried to find my screenshot of it, but I had no luck. I will upload it when I find it)

bruh you probably havent researched the tech that is able to build improvementa on that tile yet

**Comment by 7addva** [comment]
Sorry, after updating, the issue is gone. Sorry for bothering you :)

**Comment by 7addva** [comment]
> > Improvements are non present on the improvements screen
> > 
> > When the improvement screen is opened, no improvements show up
> > 
> > (I tried to find my screenshot of it, but I had no luck. I will upload it when I find it)
> 
> bruh you probably havent researched the tech that is able to build improvementa on that tile yet

Yes I did, I checked that
