### ISSUE TITLE
War Chariot does not lose all movement on rough terrain

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4232]
![oaz](https://user-images.githubusercontent.com/30041793/122879869-ab91fc80-d339-11eb-8af8-593bb77a0165.png)
```
        if (unit.roughTerrainPenalty && to.getAllTerrains().any { it.rough || it.uniques.contains("Rough terrain") })
            return 4f + extraCost
```

**Comment by yairm210** [comment]
Sam or as #4139 please follow there

**Comment by xlenstra** [comment]
Is it though? The code implies that movement through rough terrain only costs 4 movement points, while the chariot archer has 5, so it seems like if it should cost all movement points to move through rough terrain it should be ```return 5f + extraCost```?

**Comment by ravignir** [comment]
^ yea.

**Comment by ravignir** [comment]
![a1](https://user-images.githubusercontent.com/30041793/122892859-0fbabd80-d346-11eb-8e6b-0fef40af8cc4.png)
same goes for Incan chariots - double movement in hills. Infinite movement cost divided by 2 is still infinity.
![b2](https://user-images.githubusercontent.com/30041793/122893413-9bcce500-d346-11eb-9e06-59cde2a34214.png)
this does not apply to Iroquois obviously as roads nullify movement penalty.
![c3](https://user-images.githubusercontent.com/30041793/122894384-6d033e80-d347-11eb-8aa6-f3523bbec0a2.png)

**Comment by ravignir** [comment]
What about this? Can you reopen this, because apart from rough terrain this issue is different from #4139? 
@yairm210

**Comment by xlenstra** [comment]
I'll create a PR to fix this this evening regardless

**Comment by ravignir** [comment]
will this be changing 4f to 100f or something different? :D

**Comment by xlenstra** [comment]
I was planning on changing it to 100f, which should also fix the inca problem, as 100/2 > 5

**Comment by ravignir** [comment]
it won't, because it is all IFs that seem to be mutually exclusive so Inca ability overwrites it to 1f.

**Comment by ravignir** [comment]
![x](https://user-images.githubusercontent.com/30041793/123061855-4ce98300-d40c-11eb-8eda-719e6afaf2e4.png)
yup, i've quickly compiled it and nothing changes for Inca

**Comment by ravignir** [comment]
`&& !(unit.roughTerrainPenalty && to.getAllTerrains().any { it.rough || it.uniques.contains("Rough terrain") })`
adding that to incas IF works, but that is wonky i guess :D

**Comment by ravignir** [comment]
AND i found another bug, gonna place it in different Issue because it is rather unrelated :D
