### ISSUE TITLE
can't build coastal buildings

### ISSUE THREAD

**Issue by Sklarface** [yairm210/Unciv#4235]
Not able to choose Lighthouse, Harbor or Seaport in city window once applicable advancements have been achieved.  Because of this benefits attributable to those buildings are also not available. Recent issue - last few days. Tried Force Stop, Uninstall/Reinstall, playing with various civilizations.

**Comment by xlenstra** [comment]
Fixed in 3.15.3, you should be able to update from the play store in a few days, on itch.io the new version can already be downloaded.

**Comment by yairm210** [comment]
Generally available from Play Store as well :)
