### ISSUE TITLE
Units ignore movement penalties when the tiles are not visible

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4241]
![a](https://user-images.githubusercontent.com/30041793/123066807-af448280-d410-11eb-963e-1937adac4bff.png)
![z](https://user-images.githubusercontent.com/30041793/123066873-bf5c6200-d410-11eb-8544-eb0ac4381621.png)
I think it is self explanatory, there should be no way for that Horseman to get there in a single turn.

**Comment by yairm210** [comment]
Please attach save info

**Comment by ravignir** [comment]
not sure why you need it, because it happens in any game (yes i attach different save to exaggerate the problem even more) : H4sIAAAAAAAAAO2d227juLKGXyUPIAIuneW7dPYcGphMZ3eyMBeNvlBsJRHGlrJluXu8grz7og62i7Hd/jJrXw4G6JFi6mexWMUii8Xiy6z8Vi7Kf+dtWVer6ZeX50W+KZq7zXMx/XW9zCvvsV7Mp5Jmni35e74spr8Ujf37xmuL2dP0ZTUri2pWfHr4LV+16d266VAiz/nva1929blYFXkzeyrm0y8/L8rHp9b7aVHM2qauytnK+/Tcdv+7bYt8eXFTfy8a73JWr1f9X6/q5X33WFfedVmV1aN3m1u67f9/mq9nPfXeZYfdbLyrddNYmjbeh3yxKIfvf1lXz/X3ucX8uWjarsX28bpo88XFlSW8B5rVVb0cKqtWbbOe7VBLS3+7bgrvsu1KXNw9FXXT4Vd/dl9a4p7z1cr7XFjuzYr8flFc3ORNu/J+rZtVcZ/P/rz4XM7HovdlVcwvLpulreipWFoCLdTHam6b15T5ti+8D5Yt/y4u/qibvo7bjs9t+bCv/eapXNSr+vlp0xOwbotmZZmzKNu82VzcDv3i3TRl1TXv4qYpLInXeWvrzEeelIv5yvtQ1ov6ceN9rmd/Fh0t17ltcdVx8qfq0T4UTUdAx4e8GIoO3VbOynbj/c+mypeWQd7nfJ433k3dtt2nl4/29/Wi59pH25RdQz6XD32/da3owX7Pv5WPQ5s/2z5t6nzu/b6eLaysXPxcrlbdD1f5oqg6eFtJWXdd1X96na/qylZmZaZYWIZsVl277pr8+bln9lP5LV/Y321dF388dWUuq3Jp+/zX9eo+r+b2pz+asu/9q04PLm6L5ltpudZLxmLddGwpHprysWgGCm8W+SBQl6tObutl1w+5VYhZsbZ/zxerUdjv6q24T7/c5m1hJbEtrIjU93X//XV9X1oxuctn/avVnq77du1e983uhKicddI0Nu33vKo7+Gpo/8/rjr8Xd/YvY7Ufq5umfuy6evqyr3bqy+T11XuuF7bP7OvLqq2bYn419M80nHj5vH5ui/nNtsSX38p7qyibr161XtqnTw+Xb0rIq/d/62LVXudVbtkzfXn1msJqtaVb/akbPYrq8nFf6a9953QEShbZAk2RtzdF/bwopi/jS2N79aa2cms/smTbHrFfbhSqFbyeyJdFPej+9OWvqRFvY/959cr5NIvnc//+YWIms4eZCYOwMLnMHsx94E+ydDKTJMi8qhvNPhSNFUfvoV5XnYJaMdgNcM/183oxwqtnv69/owcJS+e9Vab2Q6dRFsWSdpN3Q8FXr9x1yJsPrnOrVsVULA9m/YDV6gIfV/+yAnFbtFP7l8KbqZ/+d12si+mX4fuvr17x13NerXoqR4W77Rk9jQZCb9u8Z6Rnh72eaYpV3bPfPdtGvQyvsn39ayjxpuDw3BUan4bfgu634PWr992qeTG/G6tyIC0zVp+sLpVVvrjKn+04tehbZ38YOvSq635LuHRtWnRtuNuTPNbgkvzX1N9RoukbqgwOWtQ97r/bNzrsioS60VvM3WcaeSjiq28DxYZQPWv2+IpMTZrL0n3LNPPl1fb0y2CLM9nb4qYo7HD1jyn+xxT/Y4qJKR7s7BFjOfxwxlAG0aGhvGys2NSzJrdSbps7LzviTptN/782m6E/+f80m7Idv6zZ9KM0nKfZzDykUWrCB/vPfZHcm3gWZtF8LpN5MhvM5qWV3Wrlms1hLDplNW3Zej5apvQdJtT7pbEtaDY/MqW15bZVSTs0vh41lePvPzKW/mlrKWqEF2UphufRQvSjejQ8x2pUVxZBIlU+UpjB2+dIlZEDo3qciv/Oug4oVvgHs9S1Jh2fh9aMZE+6l2T8pXsZn/3+B9ma0AFNHITAKRk5JX1V756KWGGmbytOFUGpAx07b9tvUm3D/SP0Rc5nqUNfoCrLFBGZAt+iJWoOMIJlqtpYAydKeFyyHR7otkaq+kgXypzvRX0Sq1o0C2NFltuPvsOZiSbZYYxbZ+B85fAjUC/jc6r/7usJWLhr2lBLpOgP1Qehrs9hX6KJdEQt1t9oZoQHejx8EasyTu2OvDgSOHBlJ3mJZoSvXnzFCD2MaKZsmTX+KdPy5DsCESuOODCxprwH8McedShy5sCTfdWOZDjs06J4ZHwcIHUn6YY5Irb7QQ2gjmj4TvudxrhDiTPK6Nb4ir5AE67bv/vBqSB23pzuHNVMPQ8/iPPJqL875qlWajaMz/ob4wxb+gtHEsZ6Juon322DqB4XzaNtk52hWzNL88ftBvdN99eW4MAZS8XpLme5Fhy2JnG+inWrQ/3VrqHidM/koKW++kWcb1INvtNrp4hDmlM+1uV83QU7WjJtN+Jd9frP2c6aOO0dzdZWgDTLnGKB0wWRw2jnK3HGZkWly730sNGRg+A7FYcaT3FnlEhHOkfqYlVrqmv13XKJhs6UXG7bEKrujBw4p1jg8ORIRU5jnU515W3H88gBCRxqI4fNqdM7gZaG4Ahr/D3Tkj0v3a4ZzZUocexfUgfX5YvjdAjVR5kD7U6EVDc5w67LE99B0H0bOSSE+6YpMXEHiIkmM3KAOx6oLvAPVWVoivOD73yaqALbvznyJ06PJhpDkew0K1WdoSVHa6cDlI0Vu4x3HHKOSDiy6Wr5xIFw1DLdM1sNn7EiVo+x47OWcUfeHQHXA7uzZhEtG91LqPjtaIDDQacPnZFfy1mkK880Q3Ut4chc7YfbW0PNSV/R7whLNEJEqnLNNz0WRmrED/fPmiINY5zhw1HqVDFdOxe3PeAOOInuj9AZfRJnGIy8/SysI9iRn1DVGWgsRyciB3gchSPvTVcbByDT34xUO9bCeQl125yxOlMkB2+Y7OpCpLpTi02oCkWKDmdsGXkcK4brtakevozzots3fu72Q6A/cqzoVlu1cfZ1iwJFR6BrSFUXaB4ETs2h/iTTZOgG6lLbdoSHzXUbtW1HtjcSw4v2ezjdFmhu617fdfS+X31FnlYeh5V6FuY7xGl9GdutB0vt0TDaYhmHbePyYKLLOUzI9Edbn822M3Q3ahESRUKgelH3u0Na6jTNoSbT/avFcdsePaHScwuTHLZmK4XxAdeN7o7dfEr1s7Y6TgWpqtnpf1dOnW+0f2XfF9qiO5wQZ+QQ32mYs3HjOp72W1jaeyLa0DtsGUhNnGKZ7gxHakZKtf/Eaaq4Rt5xVe21yOgJmetVcb1U7gRavTiLRd2Q1MFxW+94BLT/zXUJOh4XpylvPHiJEnPXA6eHLtnXkzkEuDNIB9nRDXe94zYp3HdBuq/HlaH9+txpkGta9a5e/yJ7ZLdK18Opa3U6wvEHWqq/vn715uXDQ79ls5l2m0bdDl+5KK7z5+nLMn++yZt8WXR7TNOX3hl/vbmoiu8X9iev7QJ3rtartl569v22/Hcxfel2Jdarqe2o7+W8fZqGofdUdJt+U3/cBb8ubInlq7cqOgdx7IdhkMaBH0/iwRH+W7lqp19eluOW1r+qsp2+1N+rotntlvc4N3nV7eaNG9rX9bei98vHXt7746e3i6J49p6belmPvvvXV+8+XxV3RdPkZTW9Wdh/V5Ylz/WqPNjZPyzpNcWqXjezYvqpXHjl0kKPdV6V7eZiZp8sPd1GVufYt0zY7mu9qWIcDc6QcoqKN4XelPk0K/LqbX2o2edxdlvh5wqOLjfIa1JSDhEPKybEAZj9FvxZhhzpyaP8ILxlbEV96VP6t3OlcwXH6dARlXjKVx/q1o4An8tvVkH7TaBj1IBK/MNKTjKd4AnBI1CIrGOifJJ82NlYKUE5wlkoCViyCFmnhgotWdZ67MWLiFxAO2O7g3Cu4Li58PcUIICVBIeVnB6GQUEf4gnEE4JHoBBZVM0N0vNRodBIzBSUSriBKkN6CkoqoSqE5IeMGyaE7A2JKXm3wodUWLa+m3MFR/fN31P4EFYSHlZyejAFBQOI50M8H+IJxBOCR6AQWXRYM2hcGwcQImNwIoON1BEbeUqa0IAEhwjS81CTCFURJD+CA1IE2RvBaWcEuz8iU4V3D3ARFeZtfMq5gl25+O8OcBGsJDqs5LTxAAVDiBdAvADi+RDPh3gC8YTgEShEFh3GDRrHxwGTTmjh/BgNwEeWqycHTDq3gSMJGoDhkEgkCWo6oSqG5MdwAI4he2M4AMew+2O47ImheMZkKvjuAT2myrbdCjhXsCuXnCPzh9SASuLDSk4bS1AwgnghxAshXgDxAojnQzwf4gnEE4JHoBBZ1GwZZLdGA0EXLHD9gwwO9LTgVeWRRe1JA0HnrnDkRAYHmgAimXAkIlQlkPwEGpwEsjeBBieB3Z9Ag5NA8UzgsjuB6pOQqf67DVhCB4Ptbu65gl259ByZP6QGVJIcVnJ6cgAKxhAvgngRxAshXgjxAogXQDwf4vkQTyCeEDwChciiZtogOz0aRLoghetbZGCh55Bul5gj+yUnDSJ1vsCpPzKwcA1DLZSBJo9IOhwpCVUpJD+FBjaF7E2hgU1h96fQwKZQPFNoYFOoPil0+6RQvVOylHu3wU7pYLU9KnKu4HiM5O8Z7BRWkh5WcnoyBAomEC+GeDHEiyBeBPFCiBdCvADiBRDPh3g+xBOIJwSPQCGy6LTEoHnJOAGgDgfov0ATCugJpzubBm5t4m2NI7sqJycA1JkIl3ZoQgHXqNQiG2jiiebAkZxQlUHys9PcOBrWOWRz6KM6P1YPedWlI3kTuHlIB2B3BiciGRSbDE5EMijWGZyIZFDtMjgRyeCwkEF3ZQaHrYws8d89scnwILxLd3B2XN9GlkOVACUziphSxJQiJhQxoYgxRYwpYkQRI4oYUsSQIgYUMaCIPkX0KaJgEUeICIyRRmdwBk3hxrkS9UVB1xaae8FNIRrUYGBUAw1dM0di107OlehGKXRbo7kX9L9Tb4OB7gs6eTFwNsTUERsbbr8gIgpGn0Amb5O0QEQSMD+Bk6ldNhyEiOJXJlCVtpmLICKJsZnAKdUu+xVC5LMf4tWeEMfOu6dpu4xW5yndJQ45S2pvxd6hO1R5EGZGITOKmFLElCImFDGhiDFFjCliRBEjihhSxJAiBhQxoIg+RfSxjGMRR4gIjJGGZ6WGTUvH2R91REK/JppNwh1QGrFkYMgSDbk1MOYWx58dCX87OfujURBwjwbNJuFmE3UZmR/4rg6sBDskCqd3TMWxUeR2FiKi+SQ9BrlNDgMRyXwSHuPYp/pBiGg+iQ/AwMA4IzTUTmBkgREaqyBwq8II3fwQuKAfEcm2C7USKs3X+aK7hBRnq+8tMtcHhCkYc4IxJxQzo5AZRUwpYkoRE4qYUMSYIsYUMaKIEUUMKWJIEQOKGFBErDhcb7CII0QExkjDc2xDl6bYB2yoE5ju5Ru4mU+DDQ2MNqSnAww8HkDPvJkjh95OzmVpBC6MD0JzYxjoRLcrDdz/xF5AQx2LeGZp6GSVDRvYePP5AERk5NHZMc6FQg8lb3OYQ0QyO8anw+kxD4FRrUZonKzAMBkjNPBG4GbSiEhmxzgCiro8hG8WYtsj3AmF/Voqk/TZ6vu5CNcIhOljTMGYgjEnGHNCMTMKmVHElCKmFDGhiAlFjCliTBEjihhRxJAihhQRqw7WHKw4XG+wiCNEBMZIw+sLQ5flfNSjIymONjE03ITGDBsYNEwPNRl4qomeQjbwGDI+onbkhNzJeTw9OADD9dC6AMYd4r13Q7fzsT/XUBcxnlUbOlFnQxGeZPB5C0RE3KPJgLaZqSEibTVaGdDj1QJPk+1z8yNEtDKgAe8Cg7j2NzMgRLQyoFuNQs9aCHX4CA5MFGx9BG947+8JYZhccVjRXYrps9X3szCuEwgzwJg+xvQxpmBMwZgTjDmhmBmFzChiShFTiphQxIQixhQxpogRRYwoIlYerDtYdbDmYMXheoNFHCEiMEYaXlsZ6pLAuziGbuPg8d5QG4Jj+g0N6qfnMg08mEkTRxiYOYKmfzJH8j+dXMPQw8rwiBBaE8GzTjja19AAYhxBYmhQCvbjG7o1gFcUhi5S2PCGJ0N8fgUR+YyNsA8mYNrf24kQGQvpqohm+91dJIsQ0aqIHkURmj9NaHij0AQ0QjeZhZ5oF+ruEnwATLD9ERxYvL+/mmG+Y6lDNYdNI7APW90Jerb6fv7JtQJhhhgzwJgBxvQxpo8xBWMKxpxgzAnFzChkRhFTiphSxIQiJhQxpogxRcTqg7UHKw/WHaw6WHOw4nC9wSKOEBEYIw2vKw11x+DdO0O377hnjXrrsKUz1HriU+OGHhuneX8MTPxDExMamJkQZ3E6kkTq5PqN5oygBxxZFnF4XBPH6xt6BABHTRkaiIX3bwzdEsKrKUMXaGzIxJM2Pg+EiIh7NIXu9oJaiEi6GKYg2t91jBBZp9AVIb1wQehxMqEZuoUG9QpNcSo0vEBozjShzj7BSUYEWyDBh1cFn4cVfIxA8MkEwUFNguOkBG8zCN65UDfDnq2+n3lzvUCYEcYMMWaIMQOMGWBMH2P6GFMwpmDMCcacUMyMQmYUMaWIKUVMKGJCEbECYf3B6oO1BysP1h2sOlhzsOJwvcEijhARGCMNr6kNdUXhXVtDt21xbKyhwbHYn2qojxbbeEPnDTgnm6FJ2WhOXQOT6tKbAMyRqwBOrl1pfkKaSoddcAITA+GT4YYeNsfncww98oMjBQ0NPsT7doZuBeKVpKGLUzYM48kln69CRMQ9mu9e6B1bQhPoCr1lS2iaOYGJRkZEoirwuOeISPsarYZpKLvQC0SEBpYIzUgu1NUpOImnYBskODmU4HxTgo/pCz75L/jQkOBzSILD+ARHBgreXBK8X2VkWHIQMe7XHFwzEGaMMSOMGWHMEGOGGDPAmAHG9DGmjzEFYwrGnGDMCcXMKGRGEVOKmFJErEJYg7ACYf3B6oO1BysP1h2sOlhzsOJwvcEijhARGCMN+xMMdcPh3XpDt+txPLihAeE8YolGQWEvuqGeeTy7MXTGhLO9G5rund7VY+BlPThh/5H7Ak6v27EVonaNeQJgSjecBcP8KLHGrPxWLsq8OnV7xm3Rtoui8Wbrpimq9rr+Vizt/60m/OA6DXywz/zorOA50v6omz+PUOb/kLJj4bq/NPlqtciruVcu7bcjzlXZbi5m9snW0dT5/LbN2/Vq+jkvF93r0ekd3blirgy4h43dAIZ6FphtwrN4vjCAiIh79KYdobe3Cs1HL/T+VqE5ToXe4Co005TAE+ojIhmP4HmREZFKD3Jl0JgooZe1CfVUC77hRLAZFZw5W3AybsE5DAWnRRScUUVwkhbBZxwFH5sUHHkrOJhX8J6o4G1WI8NqkQhyv1zkuoEwE4wZY8wYY0YYM8KYIcYMMWaAMQOM6WNMH2MKxhSMOcGYE4qZUciMImIlwjqEVQhrEFYgrD9YfbD2YOXBuoNVB2sOVhyuN1jEESICY6RhZ5ChPlQcZmJonAk+xGHoKQ6cJsDQPAE4yNDQwEW8+WPohhKe1xk6V8SXABp6CyC91dkcudb5tNMF2yFq2ZgbB2a9x4lCDc09ilMWGZoFCR8gNvRMMg5pNzRKHgcaGBq7gD0IhjolmLnAk3U+/4eIiHv0zjuBt56MiKSLYe7pEZGIIcyCNyISVYE5KUZEos7wlNSISIYcGLs2IlJ5RF4Q6qcXfHOsYDsk+EYywZecCb4bQvB1E4Iz1QpOfis4d5TgdFSCTzQLPiQtONZccPi64J1wwZvrRoZlJhHlfp3JtQNhphgzwZgJxowxZowxI4wZYcwQY4YYM8CYAcb0MaaPMQVjCsacYMwJxcRqhLUIKxHWIaxCWIOwAmH9weqDtQcrD9YdrDpYc7DicL3BIo4QERgjDfuRDHW/4vAiQ+OL8MElQ08u4bQghuYF4cc36ZFQHFZraKgu3jEzdBcOz2gNnSVn2P+Twbn8O65fPnL/82l/Dd7doPslzAMEb3bBCaENzTGN07MZmvENJwwwNAcBPsZh6MkQHJ9haMgH9p4Y6pBhJggvKvg6BSIi7tF7agXe7TUiki6GtwyMiEQMYc7PEZGoCsxCMyISdYZnA0dEMuTAqMURkQyL0CU/ImIJRx4gbIkE33I/YlK9YR4gfIWp4NuPBF+oJDgfueAU54Kz5AlOvCc4f4HglAiCT1cIPrAhOHxAcESC8YdrDsnl8v01h1w9SNHBBHCnK8JMMWaCMROMGWPMGGNGGDPCmCHGDDFmgDEDjOljTB9jCsYUjIn1SLAeYTXCWoSVCOsQViGsQViBsP5g9cHag5UH6w5WHaw5WHG43mARR4gIjJGGfWiGup5xVJahYVn4sJ6hp/VwGiBD8wDhJLuGZtnFh7UNPQCO47ANje3G+6SG7r3iubyh64NxJwSbIrQ4Eez9Euj9ohf8GnpnML5qzNDby3Dif0PvEsCpKA3NbokThBiacwSf/DH0MBGOyzE01Ad7jgx1RjFDSRc/6CLTCWyDD2+N367QICJKdk2vxPThbTIjIsnIDfMbj4gkUxrMOjUiklPc8DzsiEiClGGw54hINtLgdsSISCY81GpsRRxrzTvUhuoNu5FrQu26j28T9/EN5T6+38/Hdwb6+NYJH99k4eN8oD7OMerjbCU+zoDi4+M4Pj7i4+OgEf8HgShfX73HfFnc5I39ty2a1fTleZFvuocv49Pd5rmY/rpe5pU3e6pXRXVVfpv+UjT2Dxtblfpbfzj89atXrZf3RfPpoTvC3R3bLlbTiVfVH/LmPm/KvFpN22ZdeKs2b9qyevypyac/r9t1U1wUTf7q2SdbJIy2R8tvejK2Vfb0fpxPE3kIJmkamkkchiaM89xkwSwwaTTP58EsTwo/ev0PnePIR6LwAAA=

**Comment by SomeTroglodyte** [comment]
[this line](https://github.com/yairm210/Unciv/blob/208ad1aa27e799acfe76c90f083f10d92e31bfb0/core/src/com/unciv/logic/map/UnitMovementAlgorithms.kt#L95) plus line 356 to me mean exactly that - the possible paths are planned with movement cost=1 for all undiscovered tiles, and then the best plan is just taken and intermediate steps ignored - and that's also why you won't discover farther tiles from a hill when passing over it with one long movement. That card house is too complicated for me.

**Comment by ravignir** [comment]
Solution: make it so undiscovered tiles cost full movement. Do not skip steps.

**Comment by SomeTroglodyte** [comment]
Not that easy. Changing L95 to cost=movement will ""fix"" this but also provoke weird fog of war behaviour and make your unit lose more movement than actually needed in other examples... I'm out.

**Comment by ravignir** [comment]
This should not be accurate depiction, this should be only a hint how an unit might move, not how it will move.
When it moves one tile, it checks the next tile to move into, then another one, until it has 0 movement left/reached its destination point. 

But yea, it will take some time to figure out how to do that efficiently i think.
