### ISSUE TITLE
Suggestion: Release versions as apks as well

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4242]
google play takes some considerable to update so it would be great if we could just download the apk from ghub

**Comment by AdityaMH** [comment]
And more faster update, just using https://appcenter.ms/ (always update our app per-commit not per-releases).
But also make our developer confused to catch bug.

**Comment by yairm210** [comment]
I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.

**Comment by sockybob** [comment]
> I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.

This is so stupid. What about those who know how to install apk and can't compile it themselves?

**Comment by logicminimal** [comment]
> > I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.
> 
> This is so stupid. What about those who know how to install apk and can't compile it themselves?

@yairm210 i think you can just put the apks in a zip so only people that know what they are doing can install the apks, that zip shouldnt be named anything like an app though, maybe some technical jargon thing?

**Comment by AdityaMH** [comment]
If i can compile that file myself on Android. Maybe i become first tester android pre-release, even can mod unciv myself for experimental, changing UI for example. lol.

**Comment by logicminimal** [comment]
> I love that idea.
> And more faster update, just using https://appcenter.ms/ (always update our app per-commit not per-releases).
> But also make our developer confused to catch bug.

i dont think if it is worth 40$

**Comment by AdityaMH** [comment]
> > I love that idea.
> > And more faster update, just using https://appcenter.ms/ (always update our app per-commit not per-releases).
> > But also make our developer confused to catch bug.
> 
> i dont think if it is worth 40$


I'm forgot about that bills. 😅

**Comment by logicminimal** [comment]
> I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.

plz dude

**Comment by logicminimal** [comment]
> I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.

what about releasing the apks on discord? i doubt if many people would disturb you, just make a rule about not dming the admins on how to install apks and if they do mute them for some hours

**Comment by logicminimal** [comment]
> I used to do that, and the number of emails and questions I got regarding 'how do I install the apk?' led me to understand that people don't know how to install apks. To much hassle.

pls atleast just release the apks on discord and mute people if they ask how to install the apk
