### ISSUE TITLE
Reintroduce previous application ID or whatever

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#425]
After this #393 I have two Unciv apps, the previous one with a savegame I would like to replay with new versions but impossible to upgrade from Google Store.
Is it possible one day to update (or install as a fresh one from Google Store) and have it installed over the original app?

**Comment by yairm210** [comment]
It's impossible to change the game ID back, because Google closed the previous app and you can't reregister the same ID on a new game.
The only thing you can do it copy-paste the game info into the new Unciv =(
