### ISSUE TITLE
A LOT of issues and features

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4257]
# Bugs i'm unsure about (needs testing)

- [ ] When you get pyramids work bonus, the work time for workers that have been working before adoption/construction stay the same unless it gets updated (probably also the case for that liberty policy as well)

- [ ] Extra production gained from, for instance temple or artemis should not carry over, as well as rome's % 25 production bonus

# Issues

- [ ] The player is able to pay the city state gold when at war with them
> I observed this while trying to steal a worker of a city state, i declared war, stole the worker, opened diplomacy screen, accidentally paid gold (influence is still -60) and negotiated peace and boom -250G

- [x] These aren't implemented (will reference this to #663):
> They do start with a Settler, who founds the city state on the same tile it spawned at the beginning of the game. Unlike the major civilizations, City-States don't have a military unit right at the beginning of the game. 

> Maritime neutral.png Maritime City-States share their considerable  Food resources with your cities. They give you +2 Food in the Capital at the Friends level, plus an additional +1 Food there and in all other cities of yours at the Allies level. The Food appears right at the city tile, and is thus subject to additional bonuses from Social Policies, We Love the King Day, etc.
If you aren't Friends or Allies with a City-State, you do not have permission to enter their territory with any military unit (you can enter freely with civilian units, such as Workers or Missionaries). In case you violate this rule, for any turn your units stay within the City-State's borders, your  Influence with them will diminish by 12 points. 

- [ ] the ai doesnt accept offers of 375 gold for a luxury resource in epic speed:
> i have tried even 300 gold while having declared friendships with the opposing civilization, this is broken

- [ ] The ai doesnt automatically assign population from 2f 1p tile to 3f 1p tile:
> ![Screenshot_20210624-161857_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123298371-1a7d7a00-d521-11eb-8182-4c77dd571062.jpg)
> the worker improved that tile with a lumber mill last turn so it has these yields

- [ ] City States dont care if you steal their lands:
> obvious enough

- [x] Petra provides 4Food 2Production on desert tile (literally gives better yields than a petra oasis)
> ![Screenshot_20210624-173257_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123298640-629c9c80-d521-11eb-82ae-267e5a4f5f90.jpg)
> https://hastebin.com/raw/apapumeciq

- [x] The AI doesn't accept you research agreement requests in epic speed. (probably also the case in anything other than standart) they need to Offer you a trade request to do a research agreement edit: i dont know if this was even a bug so im crossing it out
# Suggestions

- [x] Being able to trade not settling cities agreements between civs. rejected
> this is probably an instant reject but i think two civs should be able to trade promises of not settling cities near each other, also if a civ has a goal of settling a city near a civ it should demand more for a trade. (promise - promise just like open borders - open borders should be accepted by the ai if they dont have a goal of settling cities) also it shouldnt be for 100 turns, it should be how much open borders go for

- [x] show how many of what resources a cs has and what it gives to you currently
> Obvious enough. Just like in civ 5 this should be the case edit: not done yet will just link it to the city states megathread #4602

- [ ] when you use a great scientist make it so that it deals excess science to other techs, also the same should apply for researching agreements
> i hope this is implemented btw
_Quick: Total of last 5.36 turns of Science output
Standard: Total of last 8 turns of Science output
Epic: Total of last 12 turns of Science output
Marathon: Total of last 24 turns of Science output_

- [x] make how much science a tech requires and how much you have currently in status bar and techs
> on status bar: [current science/required science] (turnsleft) +scienceperturn
> on techs (currentscience/required science) like on policies. done, #4303

- [x] Make city states give you influence if you build an improvement in their land ( oil well on coast for instance ) edit: will link city state mega thread #4602
I observed these bugs in 3.15.3 (didnt hit the google play lottery :| )

**Comment by ravignir** [comment]
> when you use a great scientist make it so that it deals excess science to other techs, also the same should apply for researching agreements
this is already implemented
>Make city states give you influence if you build an improvement in their land ( oil well on coast for instance )
I observed these bugs in 3.15.3 (didnt hit the google play lottery :| )
You can give 200 gold to instantly improve any resource within CS border.

**Comment by logicminimal** [comment]
> > when you use a great scientist make it so that it deals excess science to other techs, also the same should apply for researching agreements
> this is already implemented
are you sure? i didnt really observe any turn decrease after these taking place, and if tech carry-over hasn't been implemented, then this hasn't as well

> You can give 200 gold to instantly improve any resource within CS border.
this hasnt been implemented right?

**Comment by ravignir** [comment]
> this hasnt been implemented right?
>
nope, not yet

**Comment by ravignir** [comment]
![1](https://user-images.githubusercontent.com/30041793/123420112-67ae2a00-d5bb-11eb-8690-42e061ff09ae.png)
![2](https://user-images.githubusercontent.com/30041793/123420129-6e3ca180-d5bb-11eb-9def-9771bcd36da1.png)

**Comment by logicminimal** [comment]
> ![1](https://user-images.githubusercontent.com/30041793/123420112-67ae2a00-d5bb-11eb-8690-42e061ff09ae.png)
> ![2](https://user-images.githubusercontent.com/30041793/123420129-6e3ca180-d5bb-11eb-9def-9771bcd36da1.png)
> 

tech boost for currently researched text is not a problem, the leftover getting dealt is

**Comment by ravignir** [comment]
yup, it should carry over to other techs (next tech you have in the queue, and/or if you do not have a tech in the queue, it should split the leftower tech evenly between all techs you can research)

**Comment by logicminimal** [comment]
> yup, it should carry over to other techs (next tech you have in the queue, and/or if you do not have a tech in the queue, it should split the leftower tech evenly between all techs you can research)

then the problem left is techs not showing science needed and accumulated, I'm crossing it out

**Comment by ravignir** [comment]
Nah I said it should, which implies it does not carry over in unciv and it does in civ5.

**Comment by logicminimal** [comment]
> Nah I said it should, which implies it does not carry over in unciv and it does in civ5.

well ok then

**Comment by xlenstra** [comment]
> Nah I said it should, which implies it does not carry over in unciv and it does in civ5.

I thought it was implemented? Recently I used a great scientist to finish a tech, and the turn after that I also produced ~4 turns of science according to the science tab on the top left.

**Comment by ravignir** [comment]
> > Nah I said it should, which implies it does not carry over in unciv and it does in civ5.
> 
> I thought it was implemented? Recently I used a great scientist to finish a tech, and the turn after that I also produced ~4 turns of science according to the science tab on the top left.

It was about Research Agreements that do not carry over in Unciv. Great Scientist tech boost works correctly.

**Comment by logicminimal** [comment]
aleo about the city Management not re assigning population, i propose an idea for it, the game just make the city re assign population when any yields change

**Comment by logicminimal** [comment]
closing this, might re use some of the issues here in my further issues
