### ISSUE TITLE
Observatory building disappeared from the list of City buildings and also became unavailable to put in queue

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4262]
**Describe the bug**
Observatories already built are now absent in the lists of existing city buildings. Also it is not in the list of possible buildings to build in the city yet not having it but having a mountain nearby

**To Reproduce**

See the Novgorod city in the file below - it has Observatory built before. 

See Yaroslavl where it should be available to assign into construction queue but in fact is absent for selection. 

Save file is here
https://yadi.sk/d/NVjsT5-uv5IVHQ

I play on Android 3.15.2-patch1

I see also the issue with coastal buildings, but it was declared as fixed in 3.15.3. Waiting for the latest version in Google Play

Thanks for much pleasure from the game.

**Comment by Bershcomp** [comment]
Just got 3.15.3 in Google Play. It is ok there

**Comment by logicminimal** [comment]
> Just got 3.15.3 in Google Play. It is ok there

bruh
