### ISSUE TITLE
Farms pixel improvement not visible for specific Android user

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4266]
![Screenshot_20210625-183742_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123449630-8aa10400-d5e4-11eb-8da5-7baf33f2be68.jpg)

3.15.4 dont think i need to provide a save file

**Comment by yairm210** [comment]
Working for me, this looks like a you problem. By which I mean, you probably have a visual mod or something.

**Comment by logicminimal** [comment]
> Working for me, this looks like a you problem. By which I mean, you probably have a visual mod or something.

![Screenshot_20210627-092324_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123534976-977b4000-d729-11eb-85fe-7c8993c0579c.jpg)

![Screenshot_20210627-092351_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123534984-a661f280-d729-11eb-8535-22362538f470.jpg)

![Screenshot_20210627-092337_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123534980-9ea24e00-d729-11eb-9131-0c091364a0a6.jpg)

Nope, something is definitely wrong

**Comment by AdityaMH** [comment]
Ever trying 5hex? and what mod you using?

**Comment by logicminimal** [comment]
> Ever trying 5hex? and what mod you using?

i am not using any mods, and it might or not work in 5hex, the problem here is that farms dont work in in uilt tilesets

**Comment by jahodovykolac** [comment]
My ~useless~ tips
- Try turning off and on pixel improvements
- Check for any enabled permanent visual mods (they don't need to be used in the game)
- Try 5Hex

**Comment by logicminimal** [comment]
> My ~useless~ tips
> - Try turning off and on pixel improvements
> - Check for any enabled permanent visual mods (they don't need to be used in the game)
> - Try 5Hex

everything is all normal and i dont like using 5hex

**Comment by jahodovykolac** [comment]
> everything is on all normal settings and i dont like using 5hex

I didn't mean normal using it, just for testing

**Comment by logicminimal** [comment]
so... anyone has any idea why this might be happening?

**Comment by jahodovykolac** [comment]
Can you try if it's only for farms? Also if it's one broken game or every one.

**Comment by logicminimal** [comment]
> Can you try if it's only for farms? Also, are you on mobile or PC?

mobile, only for farms

**Comment by jahodovykolac** [comment]
Looks like the file for farm image got corrupted or something. Because I don't know any way of accessing game files on mobile, I would suggest making a backup of your saves (copying the files, they're accessible: mobile storage/android/data/com.unciv.app/files/SaveFiles) and reinstalling.

**Comment by logicminimal** [comment]
@yairm210 just redownloaded the game, updated it to 3.15.6 from 3.15.5-1 and the problem still persists

![Screenshot_20210702-113853_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124247457-916ed000-db2a-11eb-96e7-42f0a5f4f2c6.jpg)

**Comment by yairm210** [comment]
That's because it's not a version problem, it's a *you* problem... this isn't happening to anyone else as far as I can tell.

**Comment by logicminimal** [comment]
> That's because it's not a version problem, it's a *you* problem... this isn't happening to anyone else as far as I can tell.

i've definitely seen that happen to someone else as well, its just that i cant point out who, you should make a poll on discord if people are also experiencing this problem as well

**Comment by AdityaMH** [comment]
![Screenshot_2021-07-02-17-55-01-031_com unciv app](https://user-images.githubusercontent.com/33791472/124264467-b54c0900-db5e-11eb-837e-74d94629fe4a.png)
What android version you used?

**Comment by SomeTroglodyte** [comment]
I'm pretty sure I've seen it as well, though I do _not_ know how to reproduce. A minimal save - start as small as possible, provide here as soon as issue visible - might help. Or a copy of the actual game.atlas used at the moment of seeing the issue. Which you can't access on mobile. I could - knowing precisely which apk is running with 100% certainty that I have the same one would do it.

>Looks like the file for farm image got corrupted or something

FYI: Mobile does not use the contents of the Images folders here, only the atlas and the corresponding packed png. There is no single Farm image at all, and as far as I can see that's intentional which leads to:

I _can_ repro a similar issue, Base+Farm+Resource will not work in (some? most? all?) cases because there is no single "Farm.png", no all-together-png or ruleVariants entry (checked from debugger, not cross-checked with the json). Only existing mods in test rig are unrelated - sounds and leader portraits. E.g. Plains+Farm+Incense or Desert+Farm+Silver will show the issue. ruleVariants for these mapping e.g. Desert+Farm+Silver to ["Desert+Farm", "Silver"] would certainly solve this... But I'd like to understand this case (no resource, so the Base+Farm png should be picked without a ruleVariants automatically) and #4362 before I do something about it.

**Comment by DonColasanti** [comment]
I experienced the problem too. I am running on a motoZ4. Most current f-droid version.

**Comment by logicminimal** [comment]
> I experienced the problem too. I am running on a motoZ4. Most current f-droid version.

@yairm210 i dont think if it this way for only a specific user (me)

**Comment by logicminimal** [comment]
@yairm210 it got fixed by itself for some reason on 3.15.11

modded and vanilla screenshots![Screenshot_20210715-083237_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/125734247-6c6f03cb-4648-4f37-bea3-304874fef990.jpg)

![Screenshot_20210715-083126_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/125734285-bdcfa823-8109-4d8e-a55b-00af21829b7f.jpg)

**Comment by AdityaMH** [comment]
If my folder mod "include" fantasyhex. That all farm become hidden. Weird thing.

**Comment by SomeTroglodyte** [comment]
Hey, that could well be the answer

**Comment by logicminimal** [comment]
@yairm210 its broken again lmao

![Screenshot_20210716-125625_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/125930005-ccbf7a0b-0d0a-4dd4-83e8-18ec16f1748c.jpg)

**Comment by xlenstra** [comment]
Try uninstalling any mods that provide their own fantasy hex tileset and restarting your game.

**Comment by logicminimal** [comment]
> Try uninstalling any mods that provide their own fantasy hex tileset and restarting your game.
i dont think if it is sustainable as any mod that provides a texture file wouldn't be able to be used if you want to keep farm textures

**Comment by AdityaMH** [comment]
> Try uninstalling any mods that provide their own fantasy hex tileset and restarting your game.

This fix "farm phantom" bug. But why?

**Comment by logicminimal** [comment]
> Try uninstalling any mods that provide their own fantasy hex tileset and restarting your game.

yep, it works that way however this isnt sustainable

**Comment by SomeTroglodyte** [comment]
Why? Probably because the layering algorithm needs all components in the same place. Good hint, someone will investigate when they're otherwise bored :laughing:

**Comment by SomeTroglodyte** [comment]
> If my folder mod "include" fantasyhex. That all farm become hidden. Weird thing.

Thanks for the trigger!

**Comment by AdityaMH** [comment]
Yesterday farm phantom, now lumber mill phanthom.
![Uploading IMG_20210726_033446.jpg…]()

**Comment by AdityaMH** [comment]
Yesterday farm phantom, now lumber mill phanthom.
![IMG_20210726_033446](https://user-images.githubusercontent.com/33791472/126912844-81708dea-d66b-49a0-a6a0-5066f42885f9.jpg)

**Comment by SomeTroglodyte** [comment]
Now this is a separate issue.
Seems to happen for Plains+Hill+Forest+Lumber mill and Tundra+Hill+Forest+Lumber mill because those have neither a ruleVariant nor an allTogether image nor does a 'Lumber mill.png' exist by itself. There's a 'HillForest+Lumber mill' png that looks completely unused that maybe would serve for a ruleVariant...

Well, 
```json
        "Plains+Hill+Forest+Lumber mill": ["Plains","HillForest+Lumber mill"],
        "Tundra+Hill+Forest+Lumber mill": ["Tundra","HillForest+Lumber mill"],
```
work well enough but that's not the whole ticket. Not my expertise really.

**Comment by logicminimal** [comment]
this one is fixed btw, but you might want to still keep it up due to @SomeTroglodyte's comment above, from what i understand they are basically the same problem

**Comment by SomeTroglodyte** [comment]
Nope, the fix 4553 prevents inappropriate tileset json from being active - e.g. DeCiv's json interfering when you aren't playing DeCiv.
The lumbermills look more like incomplete FantasyHex itself. Farms on desert hills likewise.
