### ISSUE TITLE
Petra is too op

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4268]
petra is able to turn a crippling desert city into a city that is better than the capitls in any way just with a wonder.

just check this save https://hastebin.com/raw/uqununapot

**Comment by xlenstra** [comment]
In 3.15.4 it gave double the yield it should, this is fixed in 3.15.5

**Comment by logicminimal** [comment]
> In 3.15.4 it gave double the yield it should, this is fixed in 3.15.5

oh great
