### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#4275]
Some strings are missing from translation files. Those are:
"Show experimental world wrap for maps" - from settings menu
"Enable portrait orientation" - from settings menu
"Author:" - from mods menu
"Size:" - from mods menu
"Load from custom location" - from saves menu
"Open terrain" - from civilopedia

Also there's some strings which is present in translation file but still not translated by some reason. Those are:
"Penalty vs City 33%"
"Our proposed trade is no longer relevant!" which is present as slightly different "Our proposed trade **request** is no longer relevant!"

I'll post more if i find.

**Comment by SomeTroglodyte** [comment]
Makes me wonder if a unit test could catch these - scan all literals in all .kt files, cut at first [{ or $, distinct, filter out obvious regexes, filter out all present in templates, scan and form a strategy to filter out all other non-translateables...

**Comment by SomeTroglodyte** [comment]
Looks like most if not all of these are my fault - thanks (on it)!

**Comment by SomeTroglodyte** [comment]
@sockybob - Penalty vs City - which language did you look at? This seems OK, but translations do only exist in a handful of langs - italian german turkish* czech korean russian spanish (*=currently whole language broken).

**Comment by SomeTroglodyte** [comment]
@yairm210  - the "Penalty vs City 33%" thing is a bug as the logic of `translateBonusOrPenalty` is completely unknown to `TranslationFileWriter`. Or am I missing something obvious?

If I were to fix this I'd add a `isUnique: Boolean` parameter to `submitString`, provided by `field.name == "uniques"` at the call site, then if that is set in the else branch of `if (parameters.any())` call a `translateBonusOrPenaltyTemplate` function in the `Translations.Companion` that would map """(Bonus|Penalty) vs (.*) (\d*)%""" to """\1 vs \[\2\]""" ... or something like that. But that code is quite un-transparent to me, you're the expert, so I'd prefer you do it - or at least your input.

Also - that special-casing in submitString just above `-> "cityFilter"` - doesn't this mean all such filters need parallel code here and all the match-filter implementations need a big fat comment that new features need to update the TranslationFileWriter as well?

**Comment by yairm210** [comment]
Bonus/Penalty is really old and inefficient, removed (finally) in aeceead
