### ISSUE TITLE
Give tiles with negative yields inverted yield icon colors

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4276]
there are tiles with -1 gold -1 food -1 production but they dont even show up, they should show up in their inverted color or with some different texture

**Comment by yairm210** [comment]
There's no such thing as negative yields in the game. If you have an example of such a tile, I'd like to see that, because that's a bug.

**Comment by logicminimal** [comment]
> There's no such thing as negative yields in the game. If you have an example of such a tile, I'd like to see that, because that's a bug.

it might not be in the base game but there are many edamples in mods

**Comment by sockybob** [comment]
> There's no such thing as negative yields in the game. If you have an example of such a tile, I'd like to see that, because that's a bug.

What about fallout tile?

**Comment by yairm210** [comment]
Even when some tile improvements\terrains *reduce* yields, in the final calculation you can't have negative yields.

**Comment by logicminimal** [comment]
> Even when some tile improvements\terrains *reduce* yields, in the final calculation you can't have negative yields.

im just describing what i have seen on deciv redux mod, you can try for yourself. just assign a population to a tile that has negative yields

**Comment by jahodovykolac** [comment]
You can have negative yields with fallout (I just realised - Fallout doesn't reduce Production)
![Screenshot_20210629-121758_UnCiv](https://user-images.githubusercontent.com/79529669/123781100-1f04b280-d8d4-11eb-94ad-a8994ac0a499.jpg)

**Comment by logicminimal** [comment]
> Even when some tile improvements\terrains *reduce* yields, in the final calculation you can't have negative yields.

then that is a problem as well, i suggest re-opening the issue

**Comment by jahodovykolac** [comment]
I will open a new one with two fallout issues.

**Comment by logicminimal** [comment]
#4300

**Comment by will-ca** [comment]
...Negative yields are actually a really cool idea? I could see living next to a volcano decreasing happiness but generating a lot of science, for example, or a natural wonder that costs of gold and production but creates a lot of culture when it's being worked. It's kinda like having a togglable UA— Each player could spawn with a number of special tiles that let them very heavily focus a single stat, with cool lore about how they're space colonists that landed on different parts of the moon or something.
