### ISSUE TITLE
Alliances/ideologies ideas

### ISSUE THREAD

**Issue by JSchu72** [yairm210/Unciv#4278]
What if the diplomacy system had alliances, where civs agree that if one civ is attacked, they may request their allies to declare war on the aggressor as agreed upon in the alliance (if a civ asks you to declare war and you say no then you get a diplomatic penalty and it breaks the alliance)? You could even do a coalition alliances with more than 2 civs.

Also what if civs reacted to one another based on choices in the culture tree, such as if 2 civs who choose Rationalism get along better than one that chooses Rationalism and one that chooses Piety?

**Comment by yairm210** [comment]
Not a Civ V mechanic, and thus not in the roadmap.

https://github.com/yairm210/Unciv/blob/master/README.md#why-not-this-is-its-own-game-why-not-add-features-that-werent-in-civ-v
