### ISSUE TITLE
A minor problem about workers that has some considerable outcome

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4294]
when an automated worker moves to a (for instance) rough tile, it loses all their movement points, now that is okay but when the next turn comes the worker is idle, i can make the worker work manually, which in the next turn (if a road requires 3 turns) will leave 2 turns left for a road, but if i instead left it to the ai the ai would wait until end of the turn, in the beginning of the next turn it would start working that tile, which will leave it will 3 turns of labor left but if i manually made that worker work a tile it would have been 2

lets demonstrate it like this:
- Without AI intervention
ending of turn 1: the worker cant do anything as it has lodt all their movement points 
ending of turn 2: ai is staying idle at the hill
ending of turn 3: the ai just started working on a road, road has 3 turns left

- With AI intervention
ending of turn 1: the worker cant do anything as it has lost all their movement points 
ending of turn 2: ai commanded manually to work on road
ending of turn 3: the continues working on a road, road has 2 turns left

**Comment by yairm210** [comment]
Um, no? This isn't how it works.
Automated workers start building improvements *at end-of-turn*, not at start-of-turn, so even if the AI works on the road at the end of turn 2, on turn 3 you'll still see 2 turns left.
