### ISSUE TITLE
Unit production bug

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4299]
My caravel got cancelled and gone because every on coast near Munich city was placed another military unit.
Save files:
[Germany -  282 turns.zip](https://github.com/yairm210/Unciv/files/6733305/Germany.-.282.turns.zip)

* Just remove ".zip" part

**Comment by yairm210** [comment]
Not a bug. You can't create units if you don't have anywhere to put them.

**Comment by AdityaMH** [comment]
This making waste my time alot to create unit for nothing.
In civ5, if new unit was created, that was put on city center whatever that city center have garrison unit and need to move one of them manually or disband for gold manually.
but in unciv, they just put that unit automatically.
if they no place to put army, new unit will got cancel with waste production.
