### ISSUE TITLE
Civilizations don't have their bonuses properly set

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4302]
Babylon seems fine

Greece doesn't have this stat set:
Influence with them and the units will heal as if they were on friendly territory.

China seems fine

Egypt seems fine

England seems fine

france seems fine

russia seems fine

rome seems fine

arabia seems fine

america seems fine

japan seems fine

india seems fine

ottomans:
- Gods & Kings and Brave New World:
    All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships.
    Pay only one-third the usual cost for naval unit maintenance.

korea seems fine

iroquois seems fine IF city Connections also mean trade routes (vanilla/gnk)

persia seems fine

polynesia seems fine

Siam: Father governs children also provides a faith bonus of % 50 (dont forget this when you implement religion), also units gifted by militaristic city states have a +10xp bonus but this is hidden

spain: ~~only culture and happiness yields from natural wonders are doubled, not all~~ seems fine

Songhai uses vanilla stats while it must use bnw/gnk stats which are:

- Gods & Kings and Brave New World:
   Receive triple 20xGold5.png Gold from Barbarian encampments and pillaging Cities.
    Land units gain the War Canoes and Amphibious promotions, strengthening them while embarked.

mongolia seems fine

Aztecs, probably misimplemented: 
https://www.reddit.com/r/civ/comments/1hp7t3/how_is_the_aztec_culture_bonus_calculated_if_you/

" _ For the Aztec bonus, you get culture equal to the combat strength of the unit. Note that for ranged units, that is their melee strength which is lower than the ranged strength (except for gatling guns and machine guns). _ 

_ For the Honor opener, you get the same, but only for barbarians. This effect stacks with the Aztec bonus, so killing barbarians with the Aztecs and Honor opener gives you double the unit strength in culture. _

_ The 8 probably means you killed a warrior unit. Either a barbarian without the honor opener or an enemy warrior unit. The 16 is probably a warrior barbarian with the honor opener. The 20 is probably a spearmen with the honor opener. _ "

incans:
- Units ignore terrain costs when moving into any tile with Hills.
No maintenance costs for improvements in Hills; half cost elsewhere.

in the game it was implemented as:
no maintenance cost for improvements on hills (which is right)
-%50 maintenance costs on roads/railroads

it isnt limited to rail/roads, it includes all improvements

Denmark: in the wiki it says that the danish gets a bonus of not losing any movement points when disembarking, in unciv it includes embarkation as well

i only checked civ bonuses, loyalty of buildings and units to the original game is unknown

source: civ fandom for most

**Comment by ravignir** [comment]
>ottomans:

-    Gods & Kings and Brave New World:
     All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships.
     Pay only one-third the usual cost for naval unit maintenance.
>
yes, this should be changed. Whiel we are at it, embarkation should also be a promotion.

> spain: only culture and happiness yields from natural wonders are doubled, not all
>
where did you get that from? 

>it isnt limited to rail/roads, it includes all improvements
>
which is correct because roads and railroads are the only improvements that have maintenance cost.

>Denmark: in the wiki it says that the danish gets a bonus of not losing any movement points when disembarking, in unciv it includes embarkation as well
>
yup. An important thing to point out is the fact they pay exactly 0 movement to disembark (moving from sea to land consumes no movement, so an unit with 2 MP can disembark and then move two times).

>source: civ fandom for most
>
that is not a reliable source, there are some errors on the wiki

**Comment by logicminimal** [comment]
> >ottomans:
> 
> -    Gods & Kings and Brave New World:
>      All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships.
>      Pay only one-third the usual cost for naval unit maintenance.
> >
> yes, this should be changed. While we are at it, embarkation should also be a promotion.
> 
> > spain: only culture and happiness yields from natural wonders are doubled, not all
> >
> where did you get that from? 
> > wiki, in unciv it saus all yields are doubled while on wiki only happiness + culture

> which is correct because roads and railroads are the only improvements that have maintenance cost.
> 
> > what about mods

**Comment by ravignir** [comment]
> 
> 
> > * Gods & Kings and Brave New World:
> >   All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships.
> >   Pay only one-third the usual cost for naval unit maintenance.
> >   yes, this should be changed. While we are at it, embarkation should also be a promotion.
> > 
> > > spain: only culture and happiness yields from natural wonders are doubled, not all
> > 
> > 
> > where did you get that from?
> 
> wiki, in unciv it says all yields are doubled while on wiki only happiness + culture
> 
![z](https://user-images.githubusercontent.com/30041793/123836931-8d646780-d90a-11eb-9789-4609eccac2b0.png)
I think you may need glasses. 
> what about mods
>
you can't add maintenance cost to improvements anyway afaik.

**Comment by logicminimal** [comment]
> > 
> > 
> > > * Gods & Kings and Brave New World:
> > >   All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships.
> > >   Pay only one-third the usual cost for naval unit maintenance.
> > >   yes, this should be changed. While we are at it, embarkation should also be a promotion.
> > > 
> > > > spain: only culture and happiness yields from natural wonders are doubled, not all
> > > 
> > > 
> > > where did you get that from?
> > 
> > wiki, in unciv it says all yields are doubled while on wiki only happiness + culture
> > 
> ![z](https://user-images.githubusercontent.com/30041793/123836931-8d646780-d90a-11eb-9789-4609eccac2b0.png)
> I think you may need glasses. 
i misread that, probably
> > what about mods
> >
> you can't add maintenance cost to improvements anyway afaik.

new issue time (jk)

**Comment by logicminimal** [comment]
yairm why did you close this
