### ISSUE TITLE
Quote of Sun Tzu for Stealth

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#4326]
@xlenstra Added Stealth with the quote:
Be extremely subtle, even to the point of formlessness, be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent' state.

The original quote from [here](https://www.goodreads.com/work/quotes/3200649) is:
Be extremely subtle even to the point of formlessness. Be extremely mysterious even to the point of soundlessness. Thereby you can be the director of the opponent'_s_ fate.

Should we change that to the "original" quote?

**Comment by xlenstra** [comment]
Actually, @avdstaaij was the one to add the Stealth tech (all credit to him!). I just checked the base game, and the quote is correct there, so I suppose this should be changed

**Comment by Mape6** [comment]
Thanks for clarification. Sure @avdstaaij added Stealth to techs.

**Comment by avdstaaij** [comment]
I just copy-pasted the quote from [the wiki](https://civilization.fandom.com/wiki/Stealth_(Civ5)), which is known to contain mistakes. I suppose this is another one of them.

**Comment by SomeTroglodyte** [comment]
Imagine proofreading every single `Nation.startIntro` because you know they were copied from the wiki (if in doubt, check the _screenshots_ in the wiki).

**Comment by ravignir** [comment]
Imagine there was an online civilopedia of civ5 (which was relatively reliable), but it is no longer a thing...

**Comment by yairm210** [comment]
Resolved

**Comment by SomeTroglodyte** [comment]
> which was relatively reliable

URL? Could we scrape it from the wayback machine?

**Comment by ravignir** [comment]
I don't think you can. The way wyback machine works is just way too unreliable. That civilopedia came in 3 version, that is vanilla and both expansions: 

http://www.dndjunkie.com/civilopedia/
http://www.dndjunkie.com/civilopedia/godsandkings/
http://www.dndjunkie.com/civilopedia/vanilla

**Comment by xlenstra** [comment]
It's definitely there, don't know if it cached every single page though.

https://web.archive.org/web/20141129110736/http://www.dndjunkie.com/civilopedia/godsandkings

**Comment by SomeTroglodyte** [comment]
Well, a 2014 snapshot may be less complete than a [2019 snapshot](http://web.archive.org/web/20190908044615/http://www.dndjunkie.com/civilopedia/godsandkings/CONCEPT_HOME.aspx) ... replacing the timestamp with a `*` is often a valuable tool with archive.org. Now to find a scraping extension that still works in palemoon... (I'm not actually 100% serious, online is fine enough)
