### ISSUE TITLE
Atomic Bomb doesn't work properly

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4327]
![Screenshot_20210701-123537_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124102418-05e13a80-da69-11eb-92bc-3f5b4df759cf.jpg)

i used an atomic bomb on the tile that i have selected on the screenshot, bug instead of creating fallout or damaging nearby tiles it just worked as a highly powerful guided missile, doesnt work like it should from what i seen in civ fandom 3.15.5-patch1

**Comment by xlenstra** [comment]
Already fixed in the next version, #4324
