### ISSUE TITLE
Promotion picker screen will not open under certain circumstances

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4330]
**Describe the bug**
Tapping unit promotions in the unit table will not open the promotion picker screen if you closed it right before

**To Reproduce**
1. Select any unit which has at least one promotion
2. Tap the promotion icon (not the "promote"-action, the icons for already granted promotions)
3. The promotion picker screen will open
4. Close the promotion picker screen
5. Tap the promotion icon again
6. Note that now suddenly the civilopedia is opened instead of the promotion picker screen

**Comment by logicminimal** [comment]
having the same bug as well

**Comment by SomeTroglodyte** [comment]
I already noticed but didn't get around to it - the civilopedia will open if the unit's tile is perfectly centered on the map, due to some touchable area confusion, definitely my bad.

**Comment by SomeTroglodyte** [comment]
Background: The map centering onClick of the UnitTable is listening on the entire bottom left box including it's close button, and some subcells have their own onClicks. So, for the promotions "click" the map centering triggers first, then the promotions handler. I thought the centering code to be limited to the name cell and added the "Help" jump conditionally if the centering has nothing to do - wrong. It actually needs its own onClick on Icon+Name so these need to be grouped first. And then why would the centering code respect a selected unit but not a selected city?

OK, that fix is in the wrong branch, will need to shelve and backport...
