### ISSUE TITLE
The game accidentally spoils that there is an enemy in a non visible tile

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4340]
![Screenshot_20210702-122030_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124253321-93d42880-db30-11eb-9fa7-e965051270ca.jpg)

![Screenshot_20210702-122033_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124253460-b6fed800-db30-11eb-969c-9f82a3218dee.jpg)

![Screenshot_20210702-122039_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124253529-ca11a800-db30-11eb-8f0d-23b433b5c772.jpg)

as you can see

**Comment by ravignir** [comment]
You are quite late to discover that hidden knowledge :D

**Comment by logicminimal** [comment]
> You are quite late to discover that hidden knowledge :D

i knew this for months, just that just reported it

**Comment by yairm210** [comment]
No longer the case :)
