### ISSUE TITLE
Option to spread resources, elevations, bonuses, vegatation over a map

### ISSUE THREAD

**Issue by ajustsomebody** [yairm210/Unciv#4343]
Let's say that i have a map like this

![Screenshot_20210702-155103_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124277351-9e50eb00-db4d-11eb-8388-7dcd680a9b4d.jpg)

there should be a button that spreads resources, elevation, bonuses, vegatation, rare features, coastal extension etc, (you should be able to choose which, for instance you might want to only spread resources if you are already done with elevation) this would be especially useful for maps that only consist of terrain like country or continent maps, as you cant manually properly spread resources over the map

**Comment by ravignir** [comment]
+1, civ5 has such option in the map editor

**Comment by logicminimal** [comment]
> +1, civ5 has such option in the map editor

great that this didnt get instantly rejected

**Comment by ArchDuque-Pancake** [comment]
+2
I have an idea for this, depending on how maps are generated.
You could have a random "template" of, lets say silver, when you click on the button for resources, the game would take the template and place it all over the map, the game would see if a silver cant be placed in coast, so it will just not place it, and where silver could be placed, it places it.

Hopefully you understand me.

**Comment by ArchDuque-Pancake** [comment]
This template would have spread resouce/s.

**Comment by will-ca** [comment]
This would be a sensible example Python script for me to include in #5608.

Bonus of doing it that way: User wouldn't be constrained to hard-coded spread functions. Random, jittered, blue noise, voronoi, clustered, Mandelbrot, could supply their own, etc.

**Comment by yairm210** [comment]
Exists in new map editor
