### ISSUE TITLE
'Custom Map' tab doesnt appear automaticly

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4345]
When you download a map-mod (a mod that has maps in it) and you dont have any previous maps in the map editor, the maps from the mod wont appear because the 'Custom Map' tab in New game screen doesnt appear.
It will only appear until you create a new map, then it will enavle to choose the maps.

This just happened today to mape in the discord in mod discussion.

Steps to reproduce:
1. Open Unciv without ever making a new mao, basically open unciv as it was the first time.
2. Download a map-mod, example, Great Community maps
3. Create new game, try to use a custom map
4. See failure
5. Go to map maker and make a new map
6. Sace the map
7. Go again to new game screen
8. See all the maps there

**Comment by SomeTroglodyte** [comment]
Gracias. In this case, I immediately knew what you meant.
