### ISSUE TITLE
Default and Perlin should be more different

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#4348]
Currently there's 6 map generation type. I think "Default" used to have more sea. It had sea surrounding the whole map, and in the land at the same time. It looks like pangaea torn into pieces. Water is highly likely to be linked as 1 body, Easy to across sea, easy to sail, army and navy both are effective. It was my favorite.
But now default can have lands at the edges of the map. it looks quite same with Perlin.
Why did it change? Is it possible to turn it back?

**Comment by yairm210** [comment]
You now have water level options which should resolve this
And even if not, this is just not an interesting issue
