### ISSUE TITLE
Problems with map gen

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4352]
i dont know if these are in built maps, or generation types but 4 corners (and probably most others) dont generate according to the original game

https://forums.civfanatics.com/threads/all-maps-with-screenshots.515352/

**Comment by AdityaMH** [comment]
So what main problem about map gen? 
If you want new brand map gen. Just request about new feature.

**Comment by logicminimal** [comment]
> So what main problem about map gen? 
> If you want new brand map gen. Just request about new feature.

some gens/inbuilt maps are missing

**Comment by yairm210** [comment]
This is a 'wontfix'.
