### ISSUE TITLE
Civilopedia should sort using alphabet with non-english letters

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4353]
Currently, Civilopedia lists by English alphabet, and then it puts other letters, which is annoying. 'Č' goes after C, but it's after Z.
On the other side, I don't know if all computer alphabets don't sort like that.

**Comment by SomeTroglodyte** [comment]
Good catch.
Since the Civilopedia is an ongoing project anyway, I'll look into that sometime soonish. Should be simple - unless it's not due to us sorting before tr() but due to standard libraries collation issues.

**Comment by jahodovykolac** [comment]
Thanks 😄

**Comment by SomeTroglodyte** [comment]
No thank _you_ 
a) for a learning experience (in .net you get hit with culture everywhere by default and need to jump through hoops to get culture invariant, kotlin chose the other way round - even worse, default sort is binary, no collation at all...)
    ... and
b) for investigating further and telling us what _other_ sorting in Unciv might need the same treatment.
