### ISSUE TITLE
Expending all MPs without closing a previously created swap button and then using the button crashes the game

### ISSUE THREAD

**Issue by avdstaaij** [yairm210/Unciv#4354]
This bug was reported on Discord by Pugz#7682:
> If you select a unit and select another unit for it to swap with, then cause the first unit to use all of its movement points without deselecting the second unit by making it explore (automation would probably work too), it will allow you to swap with the second unit while having no movement points and crash the game.

I will probably look into this when I have the time to do so. Of course, anyone else is free to fix as well.

**Comment by SomeTroglodyte** [comment]
No, but maybe I'll look for a nicer Sound effect for swish-swap now :notes:

**Comment by avdstaaij** [comment]
I see someone found my comment :)

**Comment by SomeTroglodyte** [comment]
... and what does that say about me? Nothing nice ... Wrong life focus and so on ... :zombie:
