### ISSUE TITLE
Barbarians should develop

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#436]
In original game they start out with warriors but later get archers, galleys and brutes, even horsemen iirc
Not sure exactly when, but say after every Civ has the required tech then barbs can start spawning them I think

**Comment by ninjatao** [comment]
Do you have a trustful barbarian unit list?

**Comment by yairm210** [comment]
https://civilization.fandom.com/wiki/Barbarian_(Civ5)

... Okay then, I must have confused the Civ IV and V rules, because apparently barbarians scale in strength through the ages

**Comment by yairm210** [comment]
Good thing you asked!

**Comment by yairm210** [comment]
Resolved by @ninjatao
