### ISSUE TITLE
Forest on Tundra Hills not displayed

### ISSUE THREAD

**Issue by PangXH842** [yairm210/Unciv#4362]
![Screenshot_20210704_094714](https://user-images.githubusercontent.com/80996300/124370689-f6523380-dcac-11eb-8f13-4fcbb7918113.jpg)

In short, everything else about forest on tundra hills is normal (as in I can cut it down and build lumber mills as usual), except that it's not displayed on the map. This can be very misleading, especially when I'm playing as Iroquois.

**Comment by logicminimal** [comment]
are you playing modded?

**Comment by PangXH842** [comment]
No, it's just the base game, and I'm using all the default settings.

**Comment by yairm210** [comment]
What version are you on? (number) 
What device?

**Comment by PangXH842** [comment]
Version 3.15.7, Honor 20 Lite (HRY-LX1T).

**Comment by SomeTroglodyte** [comment]
Current codebase, map editor only - confirmed. 5Hex - works. Maybe I can understand all that quickly maybe not. 

(10 min later)
Copying TundraForest.png to TundraJungle.png and regenerating the atlas **_fixes_** this for Tundra+Hill+Forest and Tundra+Hill+Forest+Sheep but **_not_** for Tundra+Hill+Forest+Deer or Tundra+Hill+Forest+Furs - _**I have no idea why, that "TundraJungle" string is nowhere in the whole project!**_
