### ISSUE TITLE
Privateer capture while defending message 

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4374]
Resulting to-do list, moved from discussion below:
- [x] Icons on capture should show capturing unit - war - victim.
- [x] Any destroy message for the same battle should be suppressed.
- [x] Capture active only on attack (thanks @ravignir ).
- [x] `plunderFromDamage` - mention 'ingame civilopedia', and maybe this issue as sources
- [x] `plunderFromDamage` calls - make offensive only or defensive/offensive controlled by unique
- [x] toInt() earlier so plunder message won't show fractional Gold
- [x] Test thoroughly
- [ ] Update wiki in case #4698 gets merged

![image](https://user-images.githubusercontent.com/63000004/124398111-3b5d8080-dd14-11eb-84b0-b10424e49651.png)

... that was one and the same Trireme.

Question: Does Civ5 allow Privateers to capture while defending?
To-do: Check that message. Defender wins - so far OK. But if it results in capture the word 'kill' isn't appropriate and we should consider special-casing this. Of course only if the answer above is 'yes'.

**Comment by yairm210** [comment]
The answer seems to be "yes", and indeed, in such cases the 'destroyed' should not be shown.
But another point this raises is the icons, the capture should show the same icons as the fake 'destroyed' notification

**Comment by SomeTroglodyte** [comment]
... and the success rate for "may capture" seems to be 100%. Not that I have yet checked any sources...

**Comment by xlenstra** [comment]
> ... and the success rate for "may capture" seems to be 100%. Not that I have yet checked any sources...

The succes rate depends on the ratio between the strengths of the unit, and should capped between 10% and 80%. Exact calculation is more complicated, but something like that

**Comment by SomeTroglodyte** [comment]
That explains it - 1 promotion Privateer against 0 promotion Triremes...
A Privateer bombarded by a city gives the message "Your P plundered 0 gold from C"...
_Got_ to stop playtesting now!

**Comment by xlenstra** [comment]
> A Privateer bombarded by a city gives the message "Your P plundered 0 gold from C"...

That should have been fixed by #4370, If I'm not mistaken... are you playing on the latest version?

**Comment by SomeTroglodyte** [comment]
> are you playing on the latest version?

I just pulled master maybe half an hour before that first post - but yes, #4370 may not have made it at that point.

**Comment by ravignir** [comment]
Question: Does Civ5 allow Privateers to capture while defending?

They don't unless I was really unlucky and none of my 30 triremes got captured by an English Privateer.

**Comment by SomeTroglodyte** [comment]
Note to self - Summary so far:
- Icons on capture should show capturing unit - war - victim.
- Any destroy message for the same battle should be suppressed.
- Capture active only on attack (thanks @ravignir ).

New points:
- plunder message showing fractional Gold is not very tasty. (quoting Boxxy)
- plunder active for non-privateers - check sources
- plunder active when defending - check sources
- `plunderFromDamage` -> check author -> @xlenstra - Hi Xander, you must have used some sources and most likely I have just missed them in some discussion?

**Comment by xlenstra** [comment]
The source I used for implementing the "capture defeated units" unique was the following:
https://forums.civfanatics.com/threads/prize-ships-for-land-units.650196/
This includes a section of code (hidden behind a spoiler tag) of the calculation for how likely the capture is.
From that I just assumed the rest of the details, so I have no idea if the capture is disabled while defending (based on ravignir's test I would say it is)

About the plunderFromDamage: I implemented it without much thought based on the description of the ingame civilopedia, and then for some reason implemented it both offensive and defensive without any source to back this up. In my opinion it should only be offensive now that I think more about it, or this should be part of the unique itself.

**Comment by SomeTroglodyte** [comment]
:+1: always thorough. So for 'source I used for implementing the "capture defeated units"' we'd just make sure this is in a source comment - when we have reason to touch the place anyway.

And 'ingame civilopedia' is a perfectly acceptable source :smile_cat:  - so I'll update that note above, then someone, possibly me, anybody welcome, when stung by inspiration to work on this, could use it as to-do list.

**Comment by SomeTroglodyte** [comment]
Stuff I noticed while coding:
- The unit 'captured' by a Privateer has nothing common with the defeated unit except the BaseUnit name, it's created from scratch with always zero promotions, 0 XP and 50% health. That's fine - but while we're at it: @ravignir - does this match Civ5?
- The "plundered" Gold is magicked from thin air, and not subtracted from the victim's reserves. Same question.

**Comment by ravignir** [comment]
> 
> 
> Stuff I noticed while coding:
> 
>     * The unit 'captured' by a Privateer has nothing common with the defeated unit except the BaseUnit name, it's created from scratch with always zero promotions, 0 XP and 50% health. That's fine - but while we're at it: @ravignir - does this match Civ5?
> 
>     * The "plundered" Gold is magicked from thin air, and not subtracted from the victim's reserves. Same question.

yes and yes.
