### ISSUE TITLE
Improvement ideas 

### ISSUE THREAD

**Issue by Spawny1** [yairm210/Unciv#4375]
First, I love your game and I want to thank you for this work.
Secondly, I think that some points need improvement. This points are : 
-the ennemys are much too agressive in early game. 
-when we play in one huge map the civilisations are way too close.
- although in one huge map, the barbarians are not much.
- although in one huge map, the ruins are non-existent.

Sorry for my english, I speak french. Good bye and although thanks.

**Comment by logicminimal** [comment]
> First, I love your game and I want to thank you for this work.
> Secondly, I think that some points need improvement. This points are : 
> -the ennemys are much too agressive in early game. 
> -when we play in one huge map the civilisations are way too close.
> - although in one huge map, the barbarians are not much.
> - although in one huge map, the ruins are non-existent.
> 
> Sorry for my english, I speak french. Good bye and although thanks.

yep, barbarians dont work like they do in the original game, as yairm said in this thread of minr, dont know about ruins though, maybe you set it too low or it doesn't scale up with map size

**Comment by jahodovykolac** [comment]
> -the ennemys are much too agressive in early game.

Agree. You hardly survive the first 30 turns defending against 3 civs, but in the late game they're peaceful.

**Comment by AdityaMH** [comment]
Because everytime you weakling, WAR IS SOLUTION! 😅

**Comment by saud2410** [comment]
Unciv AI judges you only with forces, unless you declare freindship with them. Good trade means nothing.

**Comment by logicminimal** [comment]
> Unciv AI judges you only with forces, unless you declare freindship with them. Good trade means nothing.

yep that is a HUGE problem in this game

**Comment by SimonCeder** [comment]
I agree that civs spawning close together is a problem.

**Comment by yairm210** [comment]
All of these points have been addressed at one point or another
