### ISSUE TITLE
'Naval Tradation' Policy does not create a Great Admiral

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#4385]
Fairly self explanatory - I selected 'Naval Tradation' as a policy, but no Great Admiral appeared.

**Comment by xlenstra** [comment]
This is, as currently Great Admirals aren't implemented in the game. As they likely won't be for the foreseeable future, this tooltip will soon be removed to avoid confusion

**Comment by logicminimal** [comment]
> This is, as currently Great Admirals aren't implemented in the game. As they likely won't be for the foreseeable future, this tooltip will soon be removed to avoid confusion

what about just giving out generals for time being

**Comment by yairm210** [comment]
Closing as "not relevant"
