### ISSUE TITLE
Scout's promotions 'Scouting II & III' have the requirements mixed up

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#4386]
If you select 'Scouting I' it unlocks 'Scouting III' and 'Scouting II' will only be unlocked with 'Scouting II', i.e. you can't get it.

**Comment by xlenstra** [comment]
Thanks for your report, this has been fixed in the version currently rolling out

**Comment by saud2410** [comment]
The issue is fixed on 3.15.8. It will be available after .9 release.
