### ISSUE TITLE
Allow different translation for "Railroad tech" and "Railroad tracks"

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4390]
In german, "Railroad" is currently translated as "Schienen" meaning the pair of iron rails on the ground a train might move on. For the technology, this is not really appropriate on the level of "slightly grating my nerves", it should be "Eisenbahn".

Easiest would be to leave the tracks (which are hardcoded everywhere) as they are and rename the tech to "Railroading", "Railroad tech", "_railroad_tech_key" or "a8a98dc2-69ab-4394-8ea3-3c28cff6cc14", and translate that to "Railroad" in English.properties.

Anyone with a better idea? Or pro/con votes?

**Comment by Mape6** [comment]
As far as I can remember and I also checked that against dict.cc: "rails" is the english translation for "Schienen".
"Eisenbahn" ist translated to railway (british english) and railroad (american english). So from my point of view, we can stay with "railroad" as the tech name.
Instead "Remove Railroad" should be redesigned to "Remove Rails".

**Comment by SomeTroglodyte** [comment]
...The name for the improvement is also Railroad, that's the point, not the removal action?
And don't you agree that "Schienen" in the tech tree looks weird? I mean the crux of that progress is not (only) in the ability to forge those steel bars and screw them to sleepers but the combination with wheels, engines and so forth to create trains?

**Comment by Mape6** [comment]
I meant that the improvement "Railroad" should be renamed to "Rails" and the tech can stay with "Railroad". Because Railroad is "Eisenbahn" and thats a tech for me and Rails is "Schienen" which can be built on tiles.

**Comment by SomeTroglodyte** [comment]
Yes but renaming the improvement has much more complicated technical ramifications. That's why I used the word "Easiest", sorry for not being clearer on that.

**Comment by Mape6** [comment]
If it's easier, I would go with your suggestion "Railroading".
Maybe some other one knows in which files the improvement needs to be changed because it would be the cleaner way for me.

**Comment by SomeTroglodyte** [comment]
Maybe we should wait with the perfect wording until the "less hardcoding more generalized uniques" progress makes this easy...

Hardcoding locations of the improvement, as reference to any of our friends who might want to tackle a 'generalize' task (we're closer than a while ago) - not counting `RoadStatus.Railroad.name` uses:
```
MapEditorOptionsTable.setImprovements
CityInfo.tryUpdateRoadStatus
CityStats.getStatPercentBonusesFromRailroad
CityStats.isConnectedToCapital
CapitalConnectionsFinder.harborFromRailroad
CapitalConnectionsFinder.checkHarbor
MapUnit.workOnImprovement
TileInfo.canImprovementBeBuiltHere
        (oh:  `improvement.name != RoadStatus.Railroad.name && improvement.name != RoadStatus.Railroad.name`  why didn't I see that last time)
TileImprovement.matchesFilter
TileSetStrings.railroad
```
... not too horrible, except full moddability wouldn't even have that RoadStatus enum.

**Comment by yairm210** [comment]
Roads are special in Civ. Therefore so are Railroads.
If you want *full* moddability that'll looks something like a "Road level [amount]" unique, but that will be a lot of change to existing states.
Civ connects so many things to the road network that I'm not sure if this is even generalizable tbh.

**Comment by yairm210** [comment]
If you're looks for *easiest* fix I think it's probably "Railoads" for tech and "Railroad" for improvement.

**Comment by SomeTroglodyte** [comment]
You're referring to the way toilets in trains used to dump their contents directly onto the tracks? Plus some music? Rai-loads?

**Comment by SomeTroglodyte** [comment]
Sorry for that. My inner Imp :imp: ...

> not sure if this is even generalizable
Is that a challenge? Nah, sorry again. I can actually envision the architecture, and doing a Call To Power mod with maglevs, but... I'm not sure I'll live long enough.

**Comment by SomeTroglodyte** [comment]
So, it's decided then. "Railroads" tech - I'm not starting an implementation yet, I'll post here if I do, any volunteers wishing to tackle it please notify here, too.
