### ISSUE TITLE
Weird Bug I encountered

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#4392]
For some weird reason, whenever I launch a mod that I made, the game won't launch (PC Version). But works perfectly fine on the mobile app, it's only a specific mod, other mods works perfectly fine in desktop. Because of it, I can't develop a new atlas and game.png files for my mod.

**To Reproduce**
- You just attach my mod in the mod files and just launch the desktop app. I'll edit it and try to attach the files here, probably in a reply

**Expected behavior**
The game won't simply launch

**Additional context**
I'm using a windows 7 os.

**Comment by NoviceCoder2000** [comment]
Repository of the mod that I'm currently working on.

https://github.com/NoviceCoder2000/Wars-Mod

**Comment by SomeTroglodyte** [comment]
Strange. Browser opens that link, Unciv says 404 Not found...
Alternate query to see what a normal listing with the topic would return (third one): https://api.github.com/search/repositories?q=Unciv%20Wars%20World
Default branch is not 'master' but 'main' which the "direct url input" button can't handle. We could maybe test for a given URL including the '.zip' extension and if so take it as is and not guess the branch.

So that's a marginal issue with downloading that from Unciv directly, now understood. Next test...

**Comment by SomeTroglodyte** [comment]
Next marginal issue now understood: Exceptions from checkModLinks in ModCheckBoxTable are 'flattened' to that "The mod you selected is incompatible" toast, even if it contains useful information.

In your mod's case that is **"Building (Black Cannon) must either have an explicit cost or reference an existing tech"**

However, at that point I have already a valid atlas generated. Those LeaderIcons - too large for that much unsharpness ;)

Still open: Why does Options-Check Mods not show that error?

**Comment by SomeTroglodyte** [comment]
Conclusion: I can _not_ reproduce "The game won't simply launch" with the current codebase, but thank you por pointing us to those other details concerning mod download and error display.

I'll assume your jar is way outdated. If you're _sure_ it's up-to-date please provide console output. Launch the jar directly from a cmd window using `java -jar Unciv.jar`.

**Comment by NoviceCoder2000** [comment]
Yes, I think the jar is outdated considering I can't update my java.

considering inputting the command in the prompt only results to "unable to access jarfile"

**Comment by NoviceCoder2000** [comment]
Thanks for the help @SomeTroglodyte but after adding an atlas and jpeg file the game worked for me once again. I'm still unsure over how and why that happened, but I think this issue is resolved now.
