### ISSUE TITLE
Misspelled city names

### ISSUE THREAD

**Issue by SimonCeder** [yairm210/Unciv#4394]
Some city names seem to be misspelled.
For example "Onoondaga" instead of "Onondaga" and "Tunsbers" instead of "Tunsberg".

Can this be fixed with a simple edit to Nations.json? What will that do to the translation files? I would have just done it but unsure how the text is generated.

**Comment by Mape6** [comment]
Unfortunelty I don't know what happens to existing translations, too.
So it will be the best and safest way, if you change the things within the nations.json and within all translation files.

**Comment by yairm210** [comment]
I'll change those globally, in all translation files as well
Tell me if there are any others

**Comment by SomeTroglodyte** [comment]
I remember scanning **all** of the city names once, looking tons of them up in wikipedia and the like, fixing some _for the german translation only_ and not on the source. sorry sorry sorry!

Yup they're still there:
```
Onoondaga = Onondaga
Tunsbers = Tunsberg
```

**Comment by SimonCeder** [comment]
Found a couple more:
Diyabakir should  Diyarbakir or Diyarbakır
Ayutthuya should be Ayutthaya

And if we're doing German umlauts:
Dusseldorf should be Düsseldorf
Saarbrucken should be Saarbrücken

**Comment by SomeTroglodyte** [comment]
Yeah I remember - Leaving Dussel-dorf as is was tongue-in-cheek mean (Dussel=moron) and Saarbrucken the one oversight. You'll probably still find the comments on some buried PR...

**Comment by AdityaMH** [comment]
How about New York (America) and New York (England) 12th city?
Also 12th American city become "New New York"

**Comment by logicminimal** [comment]
> Found a couple more:
> Diyabakir should Diyarbakir or Diyarbakır
> Ayutthuya should be Ayutthaya
> 
> And if we're doing German umlauts:
> Dusseldorf should be Düsseldorf
> Saarbrucken should be Saarbrücken

Diyabakir should be Diyarbakır (or Diyarbakir if you can't use Turkish characters)
Mugia should be Muğla (again, Turkish charscters)
Afyonkarhisar should be Afyonkarahisar
Artuin should be Artvin
Eskisheir should be Eskişehir
Marsin should be Mersin

who came up with those wrong city names
