### ISSUE TITLE
Canceling the repair of the plundered improvement removes the improvement

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#4395]
After canceling the repair of the plundered improvement it seem to disappear from a tile and building that improvement again requires same amount of turns as if it wasn't built. Same happens if you try to build a road on it.

**Comment by yairm210** [comment]
Yup, that's what cancelling repair does. Not a bug.

**Comment by sockybob** [comment]
> Yup, that's what cancelling repair does. Not a bug.

But in civilization 5 it doesn't works like that

**Comment by logicminimal** [comment]
> Yup, that's what cancelling repair does. Not a bug.

shouldnt it just stop improving the specified improvement and not reset it to 0 turns spent building it?
