### ISSUE TITLE
Temples disappeared from the game - but partly. Not sure is this a bug or feature? 3.15.7

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4407]
**Describe the bug*

Temples built in cities are now not displayed, but counted in culture calculation. 

Organized Religion policy still promises +1 happiness from every temple, but does not do it after update to 3.15.7 Happiness reduced by about 20 points

Theocracy policy based on temples looks still giving +10% gold from temples built but I am not completely sure. 

Will temples be fixed or completely removed? 

**To Reproduce**
See save file 
https://yadi.sk/d/6fUGY6xJN-JuEA

**Expected behavior**
I expect Temples available and working near as before or temples completely removed but with somehow compensating about 20 happiness disappearing with temples removal.

**Comment by xlenstra** [comment]
Temples were replaced by amphitheaters, so you should not have lost your culture gain because of that.
This was as with the features of religion currently rolling out, the temple will start providing faith instead of culture.
When this change happened, it was forgotten to update these policies. This is fixed, but this fix has not been implemented yet, and so it will likely only be fixed starting from version 3.15.9 or 3.15.10.

**Comment by Bershcomp** [comment]
Got it.
 
How to get existing temples in savefile replaced by Amphitheaters? I see it replaced in construction queue but not in City Buildings — neither temple nor amphitheater is displayed now in the city with temple built before.
  
>Среда, 7 июля 2021, 12:21 +03:00 от Xander Lenstra ***@***.***>:
> 
> 
>Temples were replaced by amphitheaters, so you should not have lost your culture gain because of that.
>This was as with the features of religion currently rolling out, the temple will start providing faith instead of culture.
>When this change happened, it was forgotten to update these policies. This is fixed, but this fix has not been implemented yet, and so it will likely only be fixed starting from version 3.15.9 or 3.15.10.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Даниил Лебедев

**Comment by SomeTroglodyte** [comment]
> How to get existing temples in savefile replaced

Easy. Start a new game.
Sorry for the bluntness - the long answer is: Compatibility code that recognizes outdates savegames and patches them on load is done often in Unciv. But it's a significant effort and essentially an effort 'for the trashcan' as it will not live for more than a couple months. So, no guarantee this is done every time - or that's the way I see it. Fixing a save yourself is currently still possible using a text editor with search and replace - easy on PC, on Android you could use the "custom save location" feature to reach the file with an editor. So - starting over is easiest. Or accept the challenge and rebuild those Amphitheatres normally.

**Comment by xlenstra** [comment]
If you have a singleplayer game, it should actually be replaced without any problems as we implemented an automatic replace. Multiplayer games will likely be broken, unless you happen to update all in the same turn. This is due to the games with older versions suddenly finding an unknown building 'amphitheater', and trashing it because they have no idea what it is.

**Comment by Bershcomp** [comment]
I have single player game, the savefile URL is above. 
So looks like notepad++ is my way to update savefile. 
Such a surprises are happening on Android unexpectedly due to app is by default on autoupdate without any request to confirm it. Looks like I should better turn default autoupdate off and do updates between end game and start new game. 
The challenge will be to play with happiness reduced from 24 to 3 until Organized Religion policy is fixed

--
Отправлено из Mail.ru для Android среда, 07 июля 2021г., 13:48 +03:00 от Xander Lenstra  ***@***.*** :

**Comment by Bershcomp** [comment]
Temples are not auto replaced in city buildings window. Neither temple nor amphitheater is present there, but culture gain is ok

**Comment by xlenstra** [comment]
Are you sure? I just looked trough your save file and it looked like there were amphitheaters in your cities, and opening the save file in the game showed me the same thing. Note that they are classified as "specialist buildings", and therefore not in the list of buildings, but in the list of specialist buildings, which is higher in your stats drilldown

**Comment by Bershcomp** [comment]
After save - exit - relaunch- - load it started to display amphitheaters. Look ok now.
