### ISSUE TITLE
About settlers

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4408]
Is this implemented?

"__While a city is producing Settlers, population growth is paused. This prevents a city from growing during Settler production but also prevents it from starving. Any surplus  Food in the city is converted into  Production at a diminishing rate, with a point of  Production granted at the first, second, fourth, and eighth surplus  Food and every fourth  Food onward.[1] This conversion process helps reduce the negative impact of Settler production in cities with more excess  Food, so that it is not always optimal to produce a Settler in a city with the most  Production and least excess  Food.__"

also when i settled a city in the future era i got 5 population when i settled it, is this how it is implemented in civ 5? i couldn't find anything about cities starting with more than 1 population

**Comment by ravignir** [comment]
Yairm said no to this for whatever reason. 

Whatever reason means: food to conversion is too complicated for players to understand and preventing city from starving makes no sense in his opinion.

**Comment by xlenstra** [comment]
> also when i settled a city in the future era i got 5 population when i settled it, is this how it is implemented in civ 5? i couldn't find anything about cities starting with more than 1 population

This is implemented in 3.15.8

> While a city is producing [...] least excess Food

The current implementation converts excess food to production on a 1-to-1 ratio, so 10 excess food is 10 extra production for settlers.

**Comment by logicminimal** [comment]
> Yairm said no to this for whatever reason. 
> 
> Whatever reason means: food to conversion is too complicated for players to understand and preventing city from starving makes no sense in his opinion.

1:1 seems too high compared to the original game though,
"Not exactly 4:1 theres a ramp up conversion price making it potentially best in early game


-    food overflow/hammers
-    1/1
-    2-3/2
-    4-6/3
-    7/4

    +1h per 4 food beyond 7 (so at 11 15 19 etc)"

**Comment by yairm210** [comment]
I have no problem changing the ratio, but it should be linear, and specified in a unique.
I'm closing this since, as indeed stated, the main point is one that I disagree with strongly. "My city is starving, maybe I should construct a settler, that will solve my problem" - statements dreamed up by the utterly Deranged.

**Comment by logicminimal** [comment]
> I have no problem changing the ratio, but it should be linear, and specified in a unique.
> I'm closing this since, as indeed stated, the main point is one that I disagree with strongly. "My city is starving, maybe I should construct a settler, that will solve my problem" - statements dreamed up by the utterly Deranged.

what about just disabling no starvation while production
