### ISSUE TITLE
A weird diplomatic situation

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4409]
![Screenshot_20210707-141124_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/124749805-5e16b180-df2d-11eb-8fc5-622475519b70.jpg)

I nuked arabia before i met them which is  due to the me starting in future era, then when i met arabia there were no diplomatic problems, it was at 0 just as i normally encountered them, this shouldn't be the case

**Comment by logicminimal** [comment]
inb4 wontfix

**Comment by yairm210** [comment]
I didn't know about this, but this makes sense to me actually. They didn't know you, so they don't blame you.
