### ISSUE TITLE
F-Droid description explaining required Permissions

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4410]
I'd welcome an updated F-Droid description, specifically the passage "Internet permissions required in order to download large font files, especially for Chinese, which, if included by default, would more than double (!) the app size.".

Additionally, F-Droid has a language system (which I hate - I want my app descriptions in english, no matter what my current keyboard layout is), and I'd like to clarify whether we want to do anything to support that.

The existing text seems outdated since [2019-10-26](https://github.com/yairm210/Unciv/commit/8151476806361881f031cfe4512e03966f6e6e99#diff-695e13f8f3443ff30420298646fba0394691678550e0c9f445c344f465822b91).

Tasks
- [x] Clarify actual fact basis for the listed permissions - please comment
- [x] Find a nice wording consensus - suggestions here
- [x] Get it into F-Droid's [yml](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.unciv.app.yml) ~~(would I have PR permissions there?)~~ being processed
- [x] "Do we want to support F-Droid translations" - no feedback so far means 'no'. This would be fastlane.
- [x] Decide how to deal with [fastlane](https://gitlab.com/snippets/1895688) - or Triple-T - but not here, new isssue.

"Fact documentation" template:
- "have full network access" - I would mention mod download plus multiplayer as reason (custom save location I'm 90% sure does not need those even if some cloud location is chosen, opening links in browser definitely doesn't, and I can think of no other usecases - input welcome).
- "prevent phone from sleeping" - multiplayer
- "view network connections" - multiplayer
- "run at startup" - multiplayer
- "run foreground service" - multiplayer

Draft for new description:
```
The 'have full network access' permission is required for user-initiated downloads and the multiplayer feature. All other listed permissions are included automatically by the API used to implement multiplayer turn notifications.
Network permissions are used to list mods, download mods, download music and to upload/download multiplayer games.
No other internet communication is initiated by Unciv.
```

**Comment by yairm210** [comment]
You can indeed pr the change in the yml yourself

**Comment by SomeTroglodyte** [comment]
Yes, a github account can be used on gitlab, I just woudn't be surprised F-Droid sets rules of conduct I might be blissfully unaware of. Or the yml at that location might be an auto-generated copy assembled from parts. Good to know.

So - all coders - please help out completing that template. I might go offline for a few days, but I'll be back next week - or go ahead and do it without me.

**Comment by SomeTroglodyte** [comment]
WIP... Task "Clarify actual fact basis for the listed permissions":

- android.permission.INTERNET - the only explicit one in `AndroidManifest.xml`, obvious what for
- android.permission.WAKE_LOCK - AndroidApplicationConfiguration.useWakelock is off and it's not explicit, so where does this come from ?????
- android.permission.ACCESS_NETWORK_STATE
- android.permission.RECEIVE_BOOT_COMPLETED
- android.permission.FOREGROUND_SERVICE

No `com.google.android` string in project -> no GMS or play specific API's

Reference issues: #3325, #2045. I see no reason not to trust lyrjie's analysis, but I ran the proof anyway: Castrating MultiplayerTurnCheckWorker until it's an empty shell, remove unused imports, rebuild project, build apk, analyze -> clean.

So the 'fact basis' will remain: only user-initiated download and multiplayer turn checker.

**Comment by SomeTroglodyte** [comment]
WIP: List exhaustively which downloads Unciv does?
- Music
- Opening Mod Manager - mod listing
- Download mods
- ~~Download maps is gone~~ - verified since 3.15.4

Confirmed to be exhaustive by code inspection - all usages of `java.net.URL.openConnection` (DropBox.kt and GitHub.kt) and walk call chains. No calls to `Gdx.net.sendHttpRequest` or `Gdx.net.newClientSocket`.

**Comment by SomeTroglodyte** [comment]
WIP: My line "The multiplayer turn checker will connect to discord servers" - isn't that BS because Discord is a desktop-only feature? Need to verify.

**Comment by SomeTroglodyte** [comment]
Draft in initial post updated - unless someone objects, that's my final best shot and goes up in a few days.

**Comment by SomeTroglodyte** [comment]
So - do we want to go ['fastlane'](https://gitlab.com/snippets/1895688)? If we had that, we could patch the description right here in this repo if I'm not mistaken? Too much work?

**Comment by SomeTroglodyte** [comment]
The [Draft PR over on gitlab fdroiddata is here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9415).

**Comment by SomeTroglodyte** [comment]
Removed Draft marker from the PR.

**Comment by SomeTroglodyte** [comment]
[F-Droid has now picked up Version 3.15.15](https://f-droid.org/en/packages/com.unciv.app/) and finally included the description changes.
