### ISSUE TITLE
a (probably) major bug and a really minor bug

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4411]
1: when you nuke a city, (dont know if you specifically have to aim for the city center but) the city center gets destroyed, and i am almost certain that it will cause some problems, this probably only applies to capitals (and unrazeable cities like soon to be implemented holy cities) while a normal city would get destroyed capitals dont but they still lose their city center improvement

2 (the minor bug): when you nuke a city the city gets destroyed, that is fine but its civilization icon on the minimap does not disappear from the map until you progress onto the next turn

**Comment by yairm210** [comment]
Good catch!

**Comment by SomeTroglodyte** [comment]
@yairm210  - independent of fixing the nuke code:
- Idea - Would we want a safety net 'just in case' in the load game code, like: build two Set<Vector2>, one all cities, the other all tiles with the improvement, then do A-B and add the improvement and B-A and remove?
- Would we want to tie the special rules for city center yields to the improvement, complete with moddability and uniques?
- If yes to the second - could be used to easily fix the fountain of youth to original rules. "Provides yield without a worker" "Cannot be assigned a worker" (those maybe just 1 unique, or explicit stats, or..)...

**Comment by logicminimal** [comment]
also i think the second one is caused due to unciv not updating stats (or atleast stats in the UI) when something happens mid turn, for instance, getting a luxury resource just when you are at -1 happiness (due to another civ proposing so, as trade offers from you require proceeding into the next turn) and therefore so the growth until next turn stays the same until the next turn which shouldn't be the case

also city production doesnt re assign when yields change or it expands manually (and probably automatically)

**Comment by logicminimal** [comment]
@yairm210 is it time to close it?
