### ISSUE TITLE
Friend attacks protected citystate, I  take diplomatic hit

### ISSUE THREAD

**Issue by freddyhayward** [yairm210/Unciv#4422]
**To Reproduce**
1. Load [this](https://github.com/yairm210/Unciv/files/6781911/Friendship-vs-Protection.zip)
2. Click 'next turn'

**Expected behavior**
1. I should not be forced to honour the pledge.
2. If I must be forced, I should at least be notified about it.
3. Honouring the pledge should not result in a diplomatic penalty, especially not with my other friends

**Screenshots**
![image](https://user-images.githubusercontent.com/13117753/124870962-cbe2dc00-e006-11eb-86de-d73d9d9ed49b.png)
![image](https://user-images.githubusercontent.com/13117753/124871027-e026d900-e006-11eb-8d5e-2d4ed44d0060.png)
![image](https://user-images.githubusercontent.com/13117753/124871079-f03eb880-e006-11eb-8837-c225652fd742.png)

**Comment by yairm210** [comment]
Protection no longer works this way
