### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by Jasonbrowns** [yairm210/Unciv#4425]
**Describe the bug**
Any unit with logistics or blitz does not get a second attack ever. Stopped working on the July 4th update

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xlenstra** [comment]
Thanks for your report, this is a known bug that was fixed in the update that is currently rolling out. If you still have problems after updating to version 3.15.9, feel free to make a new issue.

**Comment by Jasonbrowns** [comment]
Thanks. Any timeline on the new update being available?

**Comment by xlenstra** [comment]
You should be able to update in a day or two. Not all users receive updates at the same time so game breaking bugs are caught earlier like this.

**Comment by Jasonbrowns** [comment]
Thanks for everything
