### ISSUE TITLE
Show starting speech only when it exists

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4438]
**Is your feature request related to a problem? Please describe.**
When playing a modded civilization older than starting speech, it shows only TBD TBD

**Describe the solution you'd like**
The speech window would not show up if mod doesn't contain the speech text.

**Comment by SomeTroglodyte** [comment]
What's a speech window? As far as I know Unciv has no speech recognition or -output.

**Comment by xlenstra** [comment]
I believe he means the large wall of flavor text that appears when starting a new game, describing the civ: "Oh, Julius Caesar, emperor of Rome blah blah blah will you create an empire that will stand the test of time?" etc.

**Comment by jahodovykolac** [comment]
Yes, I mean this thing, I don't know how is it called.

**Comment by yairm210** [comment]
This is already the case in code - this seems to be a mod issue.
I see for example that Medieval Civilizations and Ancient Civilizations mods have this, please contact the author of the mod you're using

**Comment by SomeTroglodyte** [comment]
Well, it _is_ filtered on `it.nation.startIntroPart1.isNotEmpty()`, so I wonder how it could ever pop up a non-existing Start Intro... GameStarter.kt Line 80

**Comment by jahodovykolac** [comment]
This is how it can pop up.

![Screenshot_20210713-115018_UnCiv](https://user-images.githubusercontent.com/79529669/125431690-7b1b35fb-b697-43c0-98c7-062774de5b70.jpg)

~Also, I don't understand how these things work, but just a thought, couldn't it be caused by "part 1" being specified there?~ nope a stupid idea

**Comment by SomeTroglodyte** [comment]
Ah, literal "TBD" -> definitely a mod error. The mod _does_ contain "speech text", and it _is_ "TBD", twice - so you see how your original "Describe the solution you'd like" doesn't really apply. Unless we special case the "TBD" string and then - where do we stop? "WIP"? "Not yet ready"? Analogous strings in the modder's native tongue? No thanks.

**Comment by jahodovykolac** [comment]
Ok, thanks for explaining :)
