### ISSUE TITLE
a minor bug

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4441]
![Screenshot_20210709-171616_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/125091899-7cb9ab80-e0d9-11eb-8838-d89f74df4c3b.jpg)

i had like 400 gold at the start of the turn, i got two research agreement requests from 2 civs, i accepted the first one, i had like 60 gold left but i was able to accept the second one as well and therefore minus gold

**Comment by yairm210** [comment]
Please write the bug description in the title. "A minor bug" is very uninformative.

**Comment by yairm210** [comment]
Can you send the save file of the turn this happened?

**Comment by yairm210** [comment]
Actually, I just checked, and even when gold goes negative as a result of trade that's OK
So not a bug, it seems

**Comment by logicminimal** [comment]
> Actually, I just checked, and even when gold goes negative as a result of trade that's OK
> So not a bug, it seems

probably not what would happen in the original game thougg
