### ISSUE TITLE
Issues with desktop right-click to move

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4460]
On desktop, you can rightclick after selecting a unit to quickly move or attack with it. However, there are a few bugs that can happen when doing this. Most of these are, because not all necessary checks are made when using this.

- [x] Spectators can move any unit they want by doing this
- [x] Carriers can preform ranged attacks by doing this
- [x] Attacking with an air unit and then rightclicking on any tile will cause an "I can't go there!" exception and remove the air unit from play
- [ ] You can move units while it is not your turn in multiplayer
- [ ] Probably more, but those are the ones I know from the top of my head

**Comment by SomeTroglodyte** [comment]
We have right-click?? 👀 😮

**Comment by yairm210** [comment]
@Azzurite I think this can be closed as "resolved"?

**Comment by SeventhM** [comment]
Concerns raised in OP seems to be addressed. Closing as solved
