### ISSUE TITLE
More than 9 city-states is shown as "…"

### ISSUE THREAD

**Issue by BlueManedHawk** [yairm210/Unciv#4463]
**Describe the bug**
When selecting the number of city-states for a game, selecting more than 9 leads to the number being displayed as "…".

**To Reproduce**
0. Open the menu for making a new game.
1. Select a number of city-states more than 9.

**Expected behavior**
The number would show up as a number.

**Screenshots**
![9 city states…](https://user-images.githubusercontent.com/50188776/125165059-43c61900-e163-11eb-9713-a33d185e471f.png)
!["…"  city-states!](https://user-images.githubusercontent.com/50188776/125165060-47f23680-e163-11eb-875b-d05b075169c5.png)

**Additional context**
None.

**Comment by SomeTroglodyte** [comment]
I have the newgame screen on my to-do list. I'll probably notice this when I get around to it... (If you check the commit history and find 'ExpanderTab' - those were triggered by trying to improve that screen)
