### ISSUE TITLE
AI magic settlers

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#448]
They can construct any improvement in one turn only.

**Comment by yairm210** [comment]
....settlers????

**Comment by yairm210** [comment]
Where did you see this?
I've followed them around and they do nothing of the sort.

**Comment by Am-per-Sand** [comment]
Sorry I mean workers. I observed it only on the tiles previously pillaged, which may be the reason for this.

**Comment by yairm210** [comment]
Pillaged tiles are indeed restored after 2 turns - I figure this is the cause
Close the issue if this answers your doubts
