### ISSUE TITLE
a very minor bug

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4484]
when you get the settler bonus of liberty before having settled any cities (in later starting eras as you cant do that in normal gameplay) no settler appears, i suggest, if this wont be a wontfix, spawning the settler just right next to the  first settler spawned is a good idea

edit: not even the free great general bonus of honor works, this is more than a minor bug if someone wants to bruteforce one policy tree when they have just started

**Comment by ravignir** [comment]
Just disallow picking policies when you have no cities like in civ5.

**Comment by logicminimal** [comment]
> Just disallow picking policies when you have no cities like in civ5.

that works too, though i would like them to be enabled for no city challenge purposes
