### ISSUE TITLE
Is this bug or feature? Farms started to cost 33 turns to build in 3.15.10 instead of 12 in 3.15.8

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4498]
**Describe the bug**
In 3.15.8 farms cost 12 turns to build. Marathon, having Pyramids (-25%) and Citizenship (-25%) 
In 3.15.10 cost raised to 33 turns for newly starting farms. The ones already started has old cost. 

**To Reproduce
Check workers building farms near Novosibirsk in this game
https://yadi.sk/d/cUvtbr9bhrQCEA

Part of them (started farms in 3.15.8)has 6 turns and less to end, part has about 30 turns to end - they started in 3.15.10

Is this bug or feature? Or costs were updated?

**Comment by xlenstra** [comment]
Thanks for your report, this is a known bug that should be fixed in version 3.15.11 which is currently rolling out.
