### ISSUE TITLE
Roads connect across rivers without Engineering

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4504]
![Screenshot_20210713-144950_UnCiv](https://user-images.githubusercontent.com/79529669/125454464-18ae4daf-7b53-467d-bc97-b7d0a0fdcd78.jpg)

As you can see here, Engineering is being researched, but road from Rotterdam goes still across the river on the right (turned off pixel improvements for better visibility).

**Comment by freddyhayward** [comment]
Are you sure this is a bug? I thought engineering was about unit movement, not city connections.

**Comment by yairm210** [comment]
As @freddyhayward said, not a bug

**Comment by jahodovykolac** [comment]
I am not talking about cities. I'm talking about a road being there. Also I noticed the road isn't there, it just looks like there is, it still consumes all movement points.

**Comment by freddyhayward** [comment]
That is all intentional. Engineering is only supposed to affect movement points. The road is there and it affects city connections.

**Comment by jahodovykolac** [comment]
Oh, that's how it works. Thanks for explaining.
