### ISSUE TITLE
Promotion bugs

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#4508]
Ranged/Siege Promotion "Accuracy I" and  Melee/Mounted/Armor Promotion "Shock I" are different in original game, but now their effect are both "+[15]% Strength in [Open terrain]"
In original game, "Accuracy I" is:
if our Ranged/Siege unit attacks the enemy unit which is in Open terrain, our Ranged/Siege unit +[15]% Strength
Compare with "Accuracy I", "Shock I" is:
if our Melee/Mounted/Armor unit is in Open terrain, and then it attacks the enemy unit, our Melee/Mounted/Armor unit +[15]% Strength

**Comment by ravignir** [comment]
Yup.
Accuracy works only when attacking and Shock works both when attacking and defending

**Comment by ravignir** [comment]
![oz](https://user-images.githubusercontent.com/30041793/125505139-11325ca8-3160-4957-a461-e53dd206c4ca.png)
And contrary to what you may think: accuracy also applies to non-ranged attacks. (Knights upgraded from Chariot Archers, with both Shock and Accuracy)

**Comment by lishaoxia1985** [comment]
@ravignir You can look at the picture which you give:
the basic strength is 20, the calculated is 29 = 20*1.45, it means that only the one 45% is valid in fact.

**Comment by ravignir** [comment]
Oh, you are right. I am blind. So the additional +45% is a visual bug in civ5
