### ISSUE TITLE
Citizenship and The Pyramids INCREASE, not decrease, tile improvement construction time

### ISSUE THREAD

**Issue by PangXH842** [yairm210/Unciv#4511]
Before:
![Screenshot_20210714_083656_com unciv app](https://user-images.githubusercontent.com/80996300/125542835-5e47b8c7-b716-4ed9-9e26-4f0b843fb9c0.jpg)

Applying Citizenship social policy:
![Screenshot_20210714_083710_com unciv app](https://user-images.githubusercontent.com/80996300/125542840-9504c48e-6f0d-48c5-ade2-11dbffa672b1.jpg)

After:
![Screenshot_20210714_083719_com unciv app](https://user-images.githubusercontent.com/80996300/125542850-1d140d91-822e-49fa-bed5-11c429a1e6cf.jpg)

In my last game, I noticed something different as well, when I suddenly need to spend 9 turns(epic speed) instead of 3 to build a single road. The default time to finish a road is 6 if I remember correctly. I had both citizenship and the Pyramids in that game.

My last game is completely unmodded, and in this game I'm trying out the ph Bonifacio mod.

**Comment by ArchDuque-Pancake** [comment]
Solved in 3.15.11
