### ISSUE TITLE
Worker times

### ISSUE THREAD

**Issue by Jasonbrowns** [yairm210/Unciv#4514]
**Describe the bug**
Any policy or wonder that reduces worker time actually is increasing it by the percentage

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xlenstra** [comment]
Thanks for your report. This is a known bug that should be fixed in version 3.15.11 currently rolling out.
