### ISSUE TITLE
Polder has no pixel improvement image

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4528]
Please give polder a pixel improvement image like for other improvements, it's hard to find it.

**Comment by SomeTroglodyte** [comment]
You mean as "Pixel Improvement" in FantasyHex? True. But 5Hex has one.
@ravignir - is there a useable attribution if "we" scale down and steal yours? :wink: :stuck_out_tongue:

**Comment by SomeTroglodyte** [comment]
![Polder](https://user-images.githubusercontent.com/63000004/125828547-170b990f-8025-4fcb-973e-dc2e61a40e13.png)
... like this ...

**Comment by SomeTroglodyte** [comment]
I honestly didn't know they can look like this... Wow.
![polder](https://s.hdnux.com/photos/31/01/33/6559430/3/rawImage.jpg)

**Comment by ravignir** [comment]
But there is one:
https://github.com/yairm210/Unciv/blob/d0df571ca561e9bfa53890816d80545dac87c84a/android/Images/TileSets/FantasyHex/Tiles/Polder.png

**Comment by jahodovykolac** [comment]
That link leads to an almost a year old version, it's not there now, probably got deleted when Netherlands wasn't in the game yet.

**Comment by SomeTroglodyte** [comment]
Hey that one's even got a windmill instead of a barn!!!
