### ISSUE TITLE
Distinction between local and global happiness

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4541]
is it implemented?

**Comment by ArchDuque-Pancake** [comment]
Yes it is, look in the city screen
You should have had to look first before making an issue.

**Comment by logicminimal** [comment]
> Yes it is, look in the city screen
> You should have had to look first before making an issue.

do not close this yet, some of the buildings and policies only deal out local happiness, which considering i sometimes get up to 80 happiness in a game, is now implemented

**Comment by xlenstra** [comment]
It is somewhat implemented. There is a difference between global and local happiness in that cities have their own happiness, but modifiers on these are indeed not implemented. If I am not mistaken there is also a cap on the amount of local happiness a city can have, depending on its population, which is also not implemented to my knowledge.

That being said: this belongs in #663.

**Comment by AdityaMH** [comment]
It is civ6 feature? If for mod good idea, but for base game, too far from roadmap.

**Comment by ravignir** [comment]
that is civ5 feature

**Comment by logicminimal** [comment]
> It is somewhat implemented. There is a difference between global and local happiness in that cities have their own happiness, but modifiers on these are indeed not implemented. If I am not mistaken there is also a cap on the amount of local happiness a city can have, depending on its population, which is also not implemented to my knowledge.
> 
> That being said: this belongs in #663.

you already references it by mentioning 663, should i post it on 663 anyway?

**Comment by yairm210** [comment]
This is a conscious decision based on the fact that local and global happiness is extremely confusing to most players, and it doesn't add anything meaningful to the gameplay.
