### ISSUE TITLE
Align positioning of Close Buttons

### ISSUE THREAD

**Issue by mnbpdx** [yairm210/Unciv#4551]
Hey there folks! Love the app, hoping to contribute, looking for a good first thing to work on.

### Is your feature request related to a problem? Please describe.

I've noticed that the position of the `Close` buttons on various screens isn't consistent. 

- On the Technology and Policy screens, the `Close` button is in the **bottom left**.
- On the Overview screen, its in the **top right** inside the scrolling table
- On the Diplomacy screen, its in the **top left**.

This is totally not a big deal, but seemed like it might be an easy first issue for me to tackle, if folks were interested in rearranging those.

### Describe the solution you'd like

Right now, it seems like the obvious choice would be moving all of those to the **bottom left**, to align with the Technology and Policy screens.

Not sure how many screens this would affect, or if it would be necessary/wanted at all. Let me know what y'all think.

### Additional context

Here's the current state of the Tech screen, which I'm proposing every other screen align to:
<img width="1792" alt="Untitled" src="https://user-images.githubusercontent.com/19321892/126046600-f62d2de2-faf7-43be-a833-7e572c27895f.png">

**Comment by yairm210** [comment]
Moving this in the diplomacy screen shouldn't be a problem, but in the overview (and civilopedia) the buttons are in a different context, of "choosing a tab". Moving only the button doesn't make much sense, and I'm not sure about moving the entire team picker, I feel it's more intuitive for the tab picker to be in the top than on the bottom.
@SomeTroglodyte thoughts on tab picker location?

**Comment by SomeTroglodyte** [comment]
I've noticed the discrepancy, too, long ago. Maybe a motivation to push keyboard support - always `Escape`... :wink:  Still, I haven't yet gotten either a clever intuition or taken the time to properly think about it. One argument would be - desktop users would have a bias towards top right from other apps, 'droid apps I can compare tend to have a comparable arrow-left in the top left if at all...

Also to consider: Special case "floating big X" used by Player picker; Close in the "tab switchers" is already a special case 'cuz it doesn't scroll with the rest (if I'm not mistaken),... Also, the bottom right corner seems to me to be the most unbalanced corner, as it widely diverges from being mostly dead space on many screens to being the center of attention... No idea how to harmonize all that. Maybe no close button anywhere? Desktop = ESC / Droid = builtin Back? Nah, would block the road to ios...

Maybe lower left everywhere is the cheapest option, and make it a floating button on diplo pedia and overview alike?

**Comment by alextfish** [comment]
I would certainly like it if I could close the Overview without having to scroll that tiny top bar all the way to the right. `Escape` doesn't help since I'm on Android... though I haven't actually tried the hardware Back button. That'll be awesome if it does work - but I'm generally terrified of hitting that in games because in some games it just closes/kills the entire game, sometimes without even saving.
