### ISSUE TITLE
Automatic city production on multiplayer, even if its disabled

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#4554]
I have expirienced this only i multiplayer so far. As seen in the screen shots, production is disabled but cities continue to auto build things.
![bug1](https://user-images.githubusercontent.com/78449553/126052768-7e52483b-0e51-4bc2-97a5-2488004b86c8.PNG)
![bug2](https://user-images.githubusercontent.com/78449553/126052770-3583b629-a1b4-494e-8694-0ebfea6fda67.PNG)

**Comment by SomeTroglodyte** [comment]
Who even knows about Leticia? 

The code using that option seems perfectly sound. Testing this to repro could take hours - or you prepare and fork over game and player ID - which you shouldn't really.

**Comment by ArchDuque-Pancake** [comment]
I'm yet to confirm if this has been fixed, but lasta week I encountered someelse with the same problem.

**Comment by xlenstra** [comment]
The problem exists because the person in turn order before you has enabled 'automatically choose new productions'. Productions in cities are updated at the end of the previous persons turn, and so the new productions are chosen using the settings of someone else.

**Comment by ArchDuque-Pancake** [comment]
Ahhh ya.
It makes sence,

**Comment by Caballero-Arepa** [comment]
> Who even knows about Leticia?
Almost no one yeah xD

Anyway, I don't think this is a problem anymore
