### ISSUE TITLE
Some texture packs dont work when enaled as permanent

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4558]
"Normal" texture packs as 5hex or lynxro tilesets work fine when enabled as "Permanent audiovisual mod"; but others, such as Civ Styles Set or Nation Color Army don't work when enabled as permanent, they only work when enabled on new game screen.

**Comment by ravignir** [comment]
because they are not just visual mods.

**Comment by ravignir** [comment]
also Nation Color Army works fine. Civ Styles Set does not because it edits the nations.json

**Comment by SomeTroglodyte** [comment]
Nothing new. I had planned somewhere to introduce mandatory compatibility declaration, so most mods wouldn't even offer the 'permanent visual' switch..

**Comment by AdityaMH** [comment]
> "Normal" texture packs as 5hex or lynxro tilesets work fine when enabled as "Permanent audiovisual mod"; but others, such as Civ Styles Set or Nation Color Army don't work when enabled as permanent, they only work when enabled on new game screen.

I know your problem.
Reason that didn't work because missing "game.png" and "game.atlas" file. 🤣

**Comment by SomeTroglodyte** [comment]
As far as I am concerned anything not bothering to commit to the promise to be an "unciv-mod" - no repo with the appropriate topic - doesn't exist as mod and thus this issue is meaningless. Except for 5hex, none of the names you mentioned are actually _mods_ in that sense.

**Comment by AdityaMH** [comment]
Can we close this issue now?

**Comment by AdityaMH** [comment]
> Nothing new. I had planned somewhere to introduce mandatory compatibility declaration, so most mods wouldn't even offer the 'permanent visual' switch..

And you know, lynxro now is gone nowhere from github. So you wouldn't letting lynxro to offer "enable audiovisual permanent" switch?

**Comment by yairm210** [comment]
Mods that don't act as mods will indeed not work. No bugs here.
