### ISSUE TITLE
Pantheons don't spread to other cities or don't appear in other cities

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4561]
![Screenshot_20210719-121503_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126135736-c8b6e79b-2f64-470d-b9ba-4db54a135057.jpg)

i selected desert folklore then settled a city on desert but that city doesn't have desert folklore

**Comment by ravignir** [comment]
But that is how it works in civ5. It takes some time for your religion to spread.

**Comment by logicminimal** [comment]
> But that is how it works in civ5. It takes some time for your religion to spread.

![Screenshot_20210719-131147_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126144562-649d234c-ad07-498b-9984-3fc0e5bc3475.jpg)

t146 and the pantheon still hasnt spred yet, also when do i get a religion?

**Comment by AdityaMH** [comment]
t146 and the pantheon still hasnt spred yet, also when do i get a religion?

You can't spread religion to other cities if you don't have great prophet.

also to found a religion need consume great prophet.
wait until great prophet appear.

**Comment by logicminimal** [comment]
actually i was tslking sbout religious pressure through trade routes etc, is that implemented or do you directly need s gp/missionary to spread religion?

**Comment by xlenstra** [comment]
That is not yet implemented.

**Comment by logicminimal** [comment]
should i keep this thread to be closed when this gets implemented?

**Comment by xlenstra** [comment]
No, that is not necessary
