### ISSUE TITLE
Unique "Can only be built on Coastal tiles" deprecation?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4563]
***Is*** that unique deprecated in favour of "Can only be built on [tileFilter] tiles"?

If yes:
- `TileImprovementConstructionTests.coastalImprovementsCanBeBuilt` - add `[]`
- `TileInfo.canImprovementBeBuiltHere` - remove line or comment as deprecated
- Moai definition - add `[]`
- template.properties - remove

If no: should it be?

**Comment by yairm210** [comment]
Yes.
