### ISSUE TITLE
Some problems about conquering civilizations really early

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4565]
so i was playing huns on one city challenge starting on classical era so i got 2 battering rams on turn 0 and decided to invade china without settling my city and here is the problem, china doesnt disappear

![Screenshot_20210719-154617_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126162211-97e6f5f5-9ce1-4087-9721-ab0284080c38.jpg)

edit: as you can see i conquered polynesia as well but it didnt say polynesia has been destroyed

![Screenshot_20210719-155320_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126162675-a73cc767-e07e-4f71-bef6-77c6e9d29987.jpg)
also apparently i have stolen a worker from polynesia while conquering their capital

edit2: also when i settle my capital after conquering everyone they dont disappear as in the civilization has been destroyed so i guess civilizations being destroyed dont carry over until you settle your capital

edit3: also the ghost units of the civilizations that got their capital destroyed dont attack

![Screenshot_20210719-160157_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126163732-271ddbb5-7fd4-44a7-bebe-463b165b46e8.jpg)

![Screenshot_20210719-160204_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126163787-9dc6a2ee-dc44-49c9-8499-0b9e4b53ae5a.jpg)

edit4: however, the domination victory seems to work properly as i tried to 1v1 another civ without settling a city

edit5: when i destroy all the ghost units of that kind of a civilization nothing happens, they dont move i think but they heal 10 hp per turn

edit6: i think it was in 3.15.12-patch1

**Comment by yairm210** [comment]
Can you send the save file of the turn before?
Load game - show autosaves

**Comment by logicminimal** [comment]
> Can you send the save file of the turn before?
> Save game - show autosaves

uhh i guess this seems to have been fixed in 3.15.13? did anyone patch this? i am unable to replicate the problem in 3.15.12-patch1 but you can easily replicate it in that version, play as huns (for early battering rams) start on classical mode, dont settle your city and just conquer a city with your units, this doesnt necessarily has to be huns but i just use them cause they basically start with catapuls when starting, also in 3.15.3 when i tried to replicate it the bug was fixed and the first city that i conquered on turn 4 became my capital and even after i settled my settler attilas court was not the capital

**Comment by yairm210** [comment]
Okay, if it's replicable in that version but not in latest, seems to have been resolved :)

**Comment by logicminimal** [comment]
> Okay, if it's replicable in that version but not in latest, seems to have been resolved :)

there are 2 problems however

1: you can't raze atillas court despite it showing up as a normal city but you can trade it away somehow
2: there is probably a problem of distinction between original capital snd currentciv, for instance i conwuered london without settling my first city so that city happens to be my first capital while it is also the first capital of england, what if someone tries to liberate it? it will probably cause bugs

**Comment by xlenstra** [comment]
> > Okay, if it's replicable in that version but not in latest, seems to have been resolved :)
> 
> there are 2 problems however
> 
> 1: you can't raze atillas court despite it showing up as a normal city but you can trade it away somehow

This is expected behaviour. Atilla's court is an original capital (founded by a first settler) but not a capital, so it cannot be razed, but it can be traded away.

> 2: there is probably a problem of distinction between original capital snd currentciv, for instance i conwuered london without settling my first city so that city happens to be my first capital while it is also the first capital of england, what if someone tries to liberate it? it will probably cause bugs. 

Then we'll deal with those if they happen. 

> id suggest only giving the starter dealt settlers the ability to construct capitals but what if you have lost that settler and you have already conquered a City/Capital of another civilization?

How it currently is implemented, is that the first city you settle, will be an 'original capital', which can never be razed. I don't know what you mean with the rest of this sentence.

**Comment by logicminimal** [comment]
@yairm210 @xlenstra i tested specifically for the liberstion bug and i have found another one

i tried playing with 3 civs, rome babylon and rome, huns invade babylon without settling their City and rome liberates it. the outcome is this:
![Screenshot_20210723-184813_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126807965-ded8d678-03db-4235-bb5b-36961f49db7d.jpg)

when its the babylons turn it seems as such that the war doesn't end when a civilization destroys another one, as i have seen on diplomacu screen while on the babylons turn and I was able to give huns gold and peace treaty but when it is the huns turn it doesnt show up as it said that our peace proposal was rejected. i am able to declare war while playing babylon (and send demands) and the other party gets the war message. the problem seems to be thst i can open the diplomacy screen while on the turn of a dead civilization and i was still technically at war with them. the way i was able to open diplomacies screen and obviously i didnt show up there so it didnt show as i was at war with huns in diplomacy screen
