### ISSUE TITLE
City states meeting gold bonus does not apply if you have encountered them before they have settled their city

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4579]
the problem is as obvious as explained on the title.

step1: meet a city state that hasnt settler their city
step2: no gold bonus
step3: city state settles their city
step4: still no bonus

also another question, do citystates just make you get x amount of gold when you meet them or do they take it from their treasury and give it to you

edit: also city states seem to ignore ancient ruins or directly the ai players ignore it, also from what i remember from the wiki the ancient ruins is instantly used when a city expands onto it but as you can see on the example this is not the case

![Screenshot_20210720-142647_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126316518-7f4d3dd9-23a7-4e47-bd97-7f1ab9c872fe.jpg)

**Comment by yairm210** [comment]
All AI settle as soon as possible, resolving this issue.
