### ISSUE TITLE
Belief "Religious Idols" should use "Gold Ore"

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4589]
![image](https://user-images.githubusercontent.com/63000004/126408543-3db2bbe1-3383-43b2-a1cd-3c1a8169da3c.png)
from a WIP: The detail that "Gold" is not linked shows it's not a TileResource

**Comment by yairm210** [comment]
Nice catch, and even nicer second-level effect of the autolinking
