### ISSUE TITLE
Huns name borrowing is probably wrong

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4593]
![Screenshot_20210721-090816_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126439986-69b3ff1b-f362-4e83-9dbc-85a988f92d7f.jpg)

i think in the original game it borrowed names from civilizations that didnt exist in the current game but in this one it borrowed one from ottomans (yalova) and one from probably polynesians which exist in the current game, though it is right for choosing names from the end of the names list (like not borrowing istanbul but instead some smaller city name)

**Comment by ravignir** [comment]
Nope, it picks a random city name from the list of civs in the game. The way it currently works is correct.
If there is something that is off, it is the fact, city names can't be duplicated, so if you borrow New York, Americans won't have it.

**Comment by logicminimal** [comment]
> Nope, it picks a random city name from the list of civs in the game. The way it currently works is correct.
> If there is something that is off, it is the fact, city names can't be duplicated, so if you borrow New York, Americans won't have it.

wasn't it the civs outside the game?
