### ISSUE TITLE
Gradle wrapper

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4603]
- /gradle/wrapper/gradle-wrapper.jar has a sha256 of 96f793a18e056c23ffeec67c1f3bb8eccff5a4a407fc9ceac183527e7eedf4b6, [which means it's 6.2.2](https://gradle.org/release-checksums/)
- /gradle/wrapper/gradle-wrapper.properties lists `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip`

Why are these diverging version numbers not a problem? Or is it?

**Comment by yairm210** [comment]
Not a problem.
This seems too auto update when you upgrade, I think that the discrepancy is from when we were messing around with the game version and fdroid, and we changed some things manually to try and get things to work

**Comment by SomeTroglodyte** [comment]
Yeah, a 'wrapper' and an 'engine' having a minor delta sounds like it can be perfectly OK except knowing how far that delta can go can be tricky.
So let's try to get them to match when we go to some gradle 7 version (which I already had building Unciv just fine - except gradle deprecation warnings - again)... If having them match comes easy.
