### ISSUE TITLE
Mini-map Rework

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4611]
I think we all know about this but this hasn´t benn adressed yet.

The current minimap is at "medium" size when the slidder is at the maximum reach. This, at first glance, isn't a problem, but, there is 2 main problems:
- 1°: To new players the mini-map is super mini, making those new players confused.
- 2°: When making screen shots on the mini-map, it is not big enough for a decent quality. I remerber that one of the purposes for an expandable minimap was for to be bigger in one of it stages.

So, I propose that in the last two "stages" of the slidder, those two would be a little bigger than usual. That way, the default size of the map would be bigger, this way, *possibly*, solving two problems in one.

**Comment by SomeTroglodyte** [comment]
<details><summary>OK, let's collect some data...</summary>

![image](https://user-images.githubusercontent.com/63000004/126816522-12473aeb-2d84-4390-9e45-f05ae084fd3c.png)
The setting value is 1 here. Desirable _minimum_ percieved size - I'd say one hex of those shown.
![image](https://user-images.githubusercontent.com/63000004/126817003-e9a7a8f9-805b-46ce-9ea5-d0c34fe640cb.png)
Value 10. This could be the default perceived size. Maximum I'd say half the screen, 2.5 times that.

Resizing the window - unsurprisingly, but needs mentioning - changes no relative size, the border stays between the two Crossbowman "s"'s.

![image](https://user-images.githubusercontent.com/63000004/126817684-46cb90af-6e66-4468-83a3-1ba22bd350db.png)
![image](https://user-images.githubusercontent.com/63000004/126819867-4d790359-1d68-419d-92c6-87f50de8c8d0.png)

So the perceived size, relative to the screen, increases slightly from min res to max res, as the allowd range of the setting goes up to 25. We might want to compensate that and make max setting somehow mean same screen percentage in all resolutions.

An outlandish aspect ratio might look like this:
![image](https://user-images.githubusercontent.com/63000004/126818303-20ae183f-5cf6-4cae-8a80-d6e59344f71d.png)
That's Gdx starting to scale down, but the relative size between tile info and minimap stays the same, so I'd say we needn't do anything for extreme aspect ratios.
</details>

So, the both the meaning and the maximum value of the setting varies with resolution, the setting scales linearly to minimap size, the default is 1, and actual window size doesn't matter.

To-do:
- [ ] Compensate resolution so the same setting means same screen percentage independent of resolution setting
- [ ] Constant slider maximum, no longer depending on chosen resolution
- [x] Use the new `UncivSlider` widget
- [x] Look into the value display, see if a mapped "display name" for each setting is easy to do. Minimap size telling you it's set to "1" is not too useful. Show a percentage?
- [ ] Let minimum size be 2x-3x of what it means now - maybe 10% screen width
- [ ] Let default (initial) size mean about 20% screen width in 4:3 aspect ratio
- [ ] Let the last few steps have a larger effect, and the point where it accelerates mean about 30% screen width
- [ ] Let maximum setting mean 50% screen width
- [x] Don't change Slider so the non-linear distribution is reflected in its knob positions - unless that's easier than custom labels per position. The original Slider has something in this direction, but it's masked in `UncivSlider`.

(The checkboxes refer to a local branch here - please be _very_ patient. Or ask to take over, then I could give you a patch. And a "sorry" to those having expressed mostly the same issue earlier.)

**Comment by SomeTroglodyte** [comment]
How about...

https://user-images.githubusercontent.com/63000004/126891119-ef3615b9-3985-44a9-8841-c19e56e77f5c.mp4

**Comment by logicminimal** [comment]
> How about...
> 
> https://user-images.githubusercontent.com/63000004/126891119-ef3615b9-3985-44a9-8841-c19e56e77f5c.mp4
> 
> 

looks great, as such the problem was probably that the minimap slider made the minimap scale with the slider value which in turn didnt update when the resolution was changed or didnt scale properly at the first point

**Comment by ArchDuque-Pancake** [comment]
Das ist very good!!
Thats perfect.

**Comment by SomeTroglodyte** [comment]
Merci beaucoup
