### ISSUE TITLE
Problem about settling cities

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4615]
![Screenshot_20210723-083124_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126740955-63fa7f42-9d5b-4d38-a2f7-9abb04766971.jpg)

in the original game you are able to settle cities 3 tiles away (city center included) from each other if the city that happens to be potentially blocking the settlement of that city and the city you are trying to settle are seperated by water

https://www.reddit.com/r/civ/comments/76xt35/civ5_shouldnt_cities_have_to_be_at_least_4_tiles/

**Comment by yairm210** [comment]
I'm closing this because I'm fed up with you not naming issues in a meaningful way.
I've told you multiple times.
