### ISSUE TITLE
Store metadata - Fastlane / Triple-T

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4618]
Follow-up to #4410 - that one as a one-shot will show results soon. This one is meant to pro-actively clear up policy for metadata integration with 'store interfaces' (if that's an appropriate label).

#### References 
- [Fastlane file structure](https://gitlab.com/-/snippets/1895688)
- [Triple-T file structure](https://gitlab.com/-/snippets/1901490) (by F-Droid)

#### To do
- [ ] What does exist? Does Unciv to G00 Ply Str already use Triple-T?
- [ ] If yes, could that be tweaked so F-Droid could tap it too?
- [ ] Other stores than F and G - how is their metadata maintained?
- [ ] What would we like to support? F, T, or none?
- [ ] If not none - could we imagine a way to get language-specific descriptions automatically integrated while still having their words done by our usual translation contributors?
- [ ] If a plan to support internationalized metadata is feasible - would we want to?

**Comment by yairm210** [comment]
I don't use any kind of file structure for release metadata.
I tried it, and it felt extremely cumbersome. It was more extra work every release than was actually helpful.
Personally, I'm not going to change the current release methodology, which is "bump version in config file, add release notes in changelog.md, tag and push commit version, build and upload apk".
The only 'extra' step that could benefit from automation at this point is building and uploading the apk to GP, and if this is at no extra per-version cost, that's great! But practically, the last time I tried this it was actually worse.

**Comment by yairm210** [comment]
What is nice, is that I already have an extremely structured changelog, which can be (easily?) auto-split into per-release files.
If this serves a clear purpose, and is Github Action-able (what isn't), then awesome :)

**Comment by yairm210** [comment]
As for *game* metadata - game description, images, etc, there is no central hub, but from my experience every platform has its own shenanigans (image sizes, text length, other random stuff) so you really need to create indivvisual images for each platform anyway... see /extraImages.

**Comment by yairm210** [comment]
So, this is not going anywhere.
As already stated, a change to the toolchain with a clear benefit is welcome, without - unwelcome.
All processes must be run from within the Github Actions.

**Comment by SomeTroglodyte** [comment]
:+1: Accepted. We've learned a few things. I'll revisit when the flea bites me - until then this is the backup of those reference links, and of the general way to go about it (one effort for a framework, after that 99% automatic, no more).
