### ISSUE TITLE
Make the game store the settings maps mods and others in a file and not in the games own app data

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4624]
This could help a lot when someone has to uninstall then reinstall unciv or move their saves and settings into another device, i think it shouldn't be deleted when the game gets uninstalled and it should be able to be moved like a normal file so it wouldn't cause any problems in case of a device change or game uninstall

**Comment by ravignir** [comment]
But what if I want to uninstall unciv because i'm running out of space?

**Comment by logicminimal** [comment]
> But what if I want to uninstall unciv because i'm running out of space?

you can delete the save files or just the game can just store them in the sd card at the first point

**Comment by SomeTroglodyte** [comment]
_Old_ discussion. The distribution between internal and external (in Gdx terms) is well thought out, and you get the exact same behaviour from other games. Nevertheless, there even was a PR early 2020 for a full zipped backup/restore I think, but that got lost.

With inclusion of the "custom save location" feature, however, the usecase is marginal anyway. I do it all the time - preserve the one save I still want using clipboard or custom save, reinstall, change signing key, whatever, redo settings in 15 s and get back the save in another 15 seconds. Not even worth using root rights for.

> uninstall unciv because i'm running out of space

good one! :rofl:  Unciv complete with all existing mods and 1 month worth of saves is close to just _one_ photograph on modern devices.

**Comment by logicminimal** [comment]
> _Old_ discussion. The distribution between internal and external (in Gdx terms) is well thought out, and you get the exact same behaviour from other games. Nevertheless, there even was a PR early 2020 for a full zipped backup/restore I think, but that got lost.
> 
> With inclusion of the "custom save location" feature, however, the usecase is marginal anyway. I do it all the time - preserve the one save I still want using clipboard or custom save, reinstall, change signing key, whatever, redo settings in 15 s and get back the save in another 15 seconds. Not even worth using root rights for.
> 
> > uninstall unciv because i'm running out of space
> 
> good one! :rofl:  Unciv complete with all existing mods and 1 month worth of saves is close to just _one_ photograph on modern devices.

..so do you think if it is a positive thing for the game for it to be implemented?

**Comment by yairm210** [comment]
No.
Benefit is nearly non existent, complexity cost is high.
This would be detrimental to the game as a whole.
