### ISSUE TITLE
Discussion on intercepting atomic bombers

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4629]
Question: Should atomic bombers be intercepted? And if so, what squares could the interception take place on?

In the original game atomic bombers couldn't be intercepted, but this was noted as a bug that was never fixed, so when updating nukes I made it possible.
Current implementation: (Battle.kt : 484)
```Kotlin
for (hitUnit in hitTiles.map { it.getUnits() }.flatten()) {
    tryDeclareWar(hitUnit.civInfo)
    if (attacker.getUnitType().isAirUnit() && !attacker.isDefeated()) {
        tryInterceptAirAttack(attacker, MapUnitCombatant(hitUnit))
    }
}
```
This code will make it so all nations whose units are hit by the blast will try to intercept the nuke. However, due to the signature of the `tryInterceptAirAttack` function, they try to intercept on the hex of the unit that was hit, instead of on the hex on which the nuke was dropped. As we loop over all hit tiles, this might also cause the same unit to try to intercept the atomic bomber multiple times when multiple units of the same nation are hit. Furthermore, there are no checks preventing interceptions from the nation dropping the bomb.

Assuming we want to allow interceptions at all, this last problem is easily solvable, but the others require a change of how the `tryInterceptAirAttack` function works. I currently don't have the time to solve any of these problems, so if someone has an opinion on what should happen, feel free to implement it that way.

**Comment by logicminimal** [comment]
my vote is on that the nations that has been affected with the nuke's damage and therefore have declared or will declare war and/or a civilization that is already at war with the civilization should be able to to intercept the nuke if they have an intercepting unit that has that exact tile that the nuke has bombed in it's range (**this part is purely for modding capabilities and not required**:and if that intercepter has a unique called caninterceptnuclear) and each intercepter should only intercept when the nuke hits it and it is a nuclear/area damage unit

also shouldnt this apply to destroy on attack units like guided missile to some extend?

**Comment by yairm210** [comment]
Looks like we should convert `tryInterceptAirAttack(attacker: MapUnitCombatant, defender: ICombatant)` to `tryInterceptAirAttack(attacker: MapUnitCombatant, attackedTile:TileInfo, interceptingCiv:CivilizationInfo)`
And then have one loop BEFORE the units are hit where every potentially-hit civ tries to intercept
