### ISSUE TITLE
City science calculation

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#463]
Live example:
`Population: 10, Library(+1 per 2 pop), University (+50%), National College (+3, +50%)`

`Buildings:8`
`Tile yields:2`
`Population:10`
`(Total: 20)`

Is this correct? Looks like percentages are not applied.

**Comment by yairm210** [comment]
The city screen displays that the city is earning only 20 per turn?

**Comment by yairm210** [comment]
In the yield?
Because the drilldown is indeed without percentages (for now)

**Comment by Am-per-Sand** [comment]
> without percentages (for now)
Then it seems correct (for now)
![science](https://user-images.githubusercontent.com/40436282/53041778-1b9bc980-3485-11e9-9a42-42959f848f9a.png)

**Comment by yairm210** [comment]
Oh wow, that's a pretty old version of the app
Upgrade recommended =D
