### ISSUE TITLE
Idea: Small icons instead of empty image

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4633]
**Is your feature request related to a problem? Please describe.**
Some mods have resources, buildings etc. without images and the white squares (in circles - even worse) are not pretty.

**Describe the solution you'd like**
There would be icons made for empty images.

**Describe alternatives you've considered**
For example a small grey house as a building, a person as a unit etc.

**Comment by SomeTroglodyte** [comment]
1. The only thing Unciv should do regarding faulty mods is _identify_ and _warn/block_
2. Thanks for the idea, I might make 'missing image' a garish purple instead of a tame white
3. Even so you should still have provided specific steps to reproduce

**Comment by jahodovykolac** [comment]
By 'reproduce' do you mean reproduce problem or solution?
If problem - load a mod missing images, for example LOTR Unciv, look in Civilopedia and there you see the white squares.
If solution - sorry, I'm not good at these things, I was just thinking that where it loads a white square, it loads something different

**Comment by SomeTroglodyte** [comment]
> for example LOTR

There you go. Without such a tiny detail it sounds as if you expect us to download all of the mods and scan them one by one... 

Still no promises, though. I quickly looked at the mod consistency code whether adding an appropriate atlas check would be straightforward (so you'd get warnings when selecting the mod on new game screen) and - nah, it's complex, maybe later. "garish purple" - for _all_ missing images - would be easier.

**Comment by yairm210** [comment]
Yeah, I'm actually against this.
I want mods to be good. And good mods have unique images.
If I offer a cop-out image I lessen the chance of that.
