### ISSUE TITLE
Great People Stats Typo

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#4636]
It's all Great Scientists.

![Screenshot_20210725-105215_UnCiv](https://user-images.githubusercontent.com/61744611/126903688-6bf15141-4da7-43dd-920c-120e90279761.jpg)

Extra detail: other Great Persons can still spawn, it's just that they're all labelled as "Great Scientist" except for Generals.

**Comment by TheEXAM** [comment]
Game version by the way is 3.15.13, the latest available in Play Store.

**Comment by SomeTroglodyte** [comment]
Go to Unciv [top page](https://github.com/yairm210/Unciv), click on ["nnn commits"](https://github.com/yairm210/Unciv/commits/master), Ctrl-F "scientist" and you'll see 'xlenstra' caught that 4 days ago :+1:
