### ISSUE TITLE
Siege units visibility

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#464]
Compare a trebuchet visibility of the city on its own and expanded +1 tile when a knight moves in.

![t1](https://user-images.githubusercontent.com/40436282/53186372-2a0ef000-3601-11e9-9cbe-acfc4b124912.png)

![t2](https://user-images.githubusercontent.com/40436282/53186385-3004d100-3601-11e9-87b5-2f9111ed30ba.png)

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/53187665-4f552b80-360c-11e9-8030-747f24b4b561.png)


Working as intended
