### ISSUE TITLE
Order of actions in turn sequence

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#465]
I was convinced that new buildings and units are created at the beginning of the player's turn. But an example of current messages log:
`A Great General has been born!`
`An enemy Crossbowman has destroyed our Great General`

Makes me suspect a new player's unit is created, then the enemies take their turn and then the player can move. The effect is visible above: A player may have no chance to use a new unit – hide it, fortify, send to suicidal attack, leave forgotten or whatever before enemy takes their chance to act.

**Comment by yairm210** [comment]
Good point!
I'll move the great general generation to the beginning of the player's turn

**Comment by Am-per-Sand** [comment]
...& all civilian & military units.

**Comment by yairm210** [comment]
Fixed in 563bbaf, thanks!
