### ISSUE TITLE
Helpful game suggestion

### ISSUE THREAD

**Issue by Done226** [yairm210/Unciv#4653]
The game has its own characteristics of civ5, but the game needs to create more interesting functions than it does, instead of imitating it constantly
Here are some suggestions.
1. It is suggested that the data upload speed of multiplayer game server can be optimized, because it can attract more players to join unciv.
2. The multiplayer game can also be added to the LAN function, so that friends can play face-to-face multiplayer games and improve the game playability
3.Interface, so as the number of online users and the number of observers.
The above suggestions are just wishes.I just provide help words. Where there is a will, there is a way

**Comment by ArchDuque-Pancake** [comment]
The thing is, Yair already knows this, but he need precise suggestions, because saying "Improve UI" won't help him.

**Comment by AcridBrimistic** [comment]
The game has no official servers at all and instead uses Dropbox to pass around save-games.  If it is slow, there is more likely a problem with your own Internet rather than a fault of Unciv's or Dropbox's.  I can't really understand the rest of the text, possibly because it is translated.  You can write in Mandarin if you'd like and I'll get a friend to translate it.

**Comment by logicminimal** [comment]
> The game has its own characteristics of civ5, but the game needs to create more interesting functions than it does, instead of imitating it constantly
> Here are some suggestions.
> 
> 1. It is suggested that the data upload speed of multiplayer game server can be optimized, because it can attract more players to join unciv.
> 2. The multiplayer game can also be added to the LAN function, so that friends can play face-to-face multiplayer games and improve the game playability
>    3.Interface, so as the number of online users and the number of observers.
>    The above suggestions are just wishes.I just provide help words. Where there is a will, there is a way

1: unciv can't do anything about it as it uses other servers as hosts
2: i think this is implemented?
3: if you have any suggestions about the interface i highly recommend you to illustrate it then suggest it for someone to implement it then do a pull request on it

**Comment by yairm210** [comment]
Unfortunately as others have said, none of these suggestions are actionable.
