### ISSUE TITLE
Civilopedia Unique parameter autolinking cannot react to ruleset change

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4656]
Another note to self, though anybody is welcome to patch...

As the title says. That auto-mapping is done in `FormattedLine.Companion` using a cache map initialized `by lazy` from the current ruleset. Consequences are:
- Will crash if the engine is used from main menu before any game was loaded (currently not possible to demonstrate)
- If I start with DeCiv then load a vanilla game, the cache will be primed for DeCiv and will miss vanilla names for the rest of the session. This is visible but easily overlooked.

Possible approach: Drop the nice lazy and implement caching more traditionally. Let the 'CivilopediaText' modules receive a notification when the ruleset changes like ImageGetter gets (Or, monitor a ruleset change by comparing hashes on every access - no thanks). Manage cache rebuild using that.

- [x] Find and document a path to demonstrate the problem, screenshot undesired result
- [x] Evaluate alternate approaches
    - [x] `fun invalidateCache` with enough hooks
    - [x] remember identity of active ruleset instance, compare with `===` ???
    - [x] remember some hash of GameParameters.mods and GameParameters.baseRuleset ???
- [x] implement - option 2 seems enough
- [ ] test and screenshot how reproducible symptom is fixed

**Comment by AdityaMH** [comment]
If you want add civilopedia to main menu. My suggestion is just add ruleset mod menu above and refreshed every changing mod selection. Also make it hidden when game was loaded.

**Comment by SomeTroglodyte** [comment]
> civilopedia to main menu

Nope, not what I said. "engine", not the screen.

**Comment by AdityaMH** [comment]
>if the engine is used from main menu

What benefit using "that engine" from main menu?

**Comment by SomeTroglodyte** [comment]
Way to reproduce:
- From main menu, load or start a game with vanilla. no mods, religion enabled
- Go into Civilopedia, look at Great Prophet -> Holy site _is_ linked
![image](https://user-images.githubusercontent.com/63000004/127752297-564250ea-83b8-4857-8f64-84b82818feb1.png)

- Quit Unciv and restart
- From main menu, load or start a game with DeCiv redux
- Go into Civilopedia, Promotions, Accuracy
- Load or start a game with vanilla. no mods, religion enabled
- Go into Civilopedia, look at Great Prophet -> Holy site is _not_ linked
![image](https://user-images.githubusercontent.com/63000004/127752300-6a905e33-9b4e-4280-982f-e679a2e135f9.png)
