### ISSUE TITLE
Remove white frames on city screen

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#466]
yuck :stuck_out_tongue_closed_eyes:

**Comment by yairm210** [comment]
Ok, now I understand what you ean - you mean the white borders, right?
I personally think it looks much better with them, than without them

Compare

![image](https://user-images.githubusercontent.com/8366208/53297955-ebf71380-382e-11e9-8150-65337a05ecfc.png)

To

![image](https://user-images.githubusercontent.com/8366208/53297973-18ab2b00-382f-11e9-966c-84950117e425.png)

**Comment by yairm210** [comment]
Well, closing this if no one else has anything to add

**Comment by Am-per-Sand** [comment]
Thanks for visual comparison. I don't have much to say on graphic style or taste, just was missing the main map look – where the frames have no border and are slightly transparent. Below a version with dimmed borders.

![borders](https://user-images.githubusercontent.com/40436282/53749675-29e7dd80-3ea8-11e9-99e4-1e572ed73a2e.png)

May be it appeals to someone. Slight dropShadow might also work.
