### ISSUE TITLE
Immortal tank

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4662]
**Describe the bug**
This tank seems to be either immortal or undead :)

If game data is required, please add from menu, save game, copy to clipboard, paste here
[Save file here](https://pastebin.com/n1JEQNqy) 

**Screenshots**
![Screenshot_20210728-122610_UnCiv](https://user-images.githubusercontent.com/79529669/127307963-a5439641-14a2-4703-b5b9-abf21ceb0f1a.jpg)
(I forgot to highlight the tank after changing language - it's the one on the lower oasis and has -34 HP)

**Additional context**
Mods - resourceplus and Resource recyclers, don't think it has to do something with it.
Also it isn't healing, and I can normally destroy it.
Version 3.15.15

**Comment by yairm210** [comment]
Can't reach the pastebin file.
What have you done with the tank that leads you to this conclusion?

**Comment by SomeTroglodyte** [comment]
Ignoring the 404 and possible reasons, we could discuss more checks on game load, where deprecation-upgrade code runs: health<=0 -> destroy...

**Comment by jahodovykolac** [comment]
> Can't reach the pastebin file.
> Ignoring the 404

Oh damn, I probably messed up something.

> we could discuss more checks on game load, where deprecation-upgrade code runs: health<=0 -> destroy...

Well that's unfortunate. Closing this for not reproduceable.

> What have you done with the tank that leads you to this conclusion?

I found it like this, photographed it and destroyed it :)
