### ISSUE TITLE
AI diplomacy ideas

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4668]
(More can come when I or somebody comes up with something)

- [x] Do AIs have relationships? It doesn't seem like it: A Civ spams me with nukes - nothing happens, nobody declares war. I use two nukes - I get -50 points which will probably result in war.
- [x] AIs could make trade offers with cities, when they're rich to expand or in situations like this:
![Screenshot_20210728-221515_UnCiv](https://user-images.githubusercontent.com/79529669/127389779-a3102925-4aea-4c3f-9592-619c23a2bab2.jpg)
(Here America or others would buy Smolensk and/or Yekaterinburg, or Russia would sell these - they're split away from mainland)
![Screenshot_20210728-221530_UnCiv](https://user-images.githubusercontent.com/79529669/127390119-a5ee690d-eec5-44e4-84bc-5a137b8d37d0.jpg)
(Here Siam would buy Smolensk and/or Orenburg to connect their cities)
- [ ] Allied Civs would gift units (to help strenghten me) instead of declaring war on me when I have really bad army.
- [ ] AI civs can declare friendship betwean each other (maybe they can but I haven't seen it for the whole time playing Unciv)
- [ ] AIs don't always reject asking for not settling near us (they always did to me - now I do the same for them hehe)
- [ ] AIs should tolerate doing something in self-defense, e.g. using nukes when the enemy just spams you with them.

**Comment by logicminimal** [comment]
the diplomacy might be the least implemented feature in the game, time will fix this

**Comment by yairm210** [comment]
A. Yes, AI have relationship levels between each other. Yes, it's affected by things like nuclear weapons.
B. Interesting idea, do PEOPLE usually buy/sell cities?
C. Would YOU gift a unit to a weaker civ you're allied with? I wouldn't. Therefore I won't make the AI do it.

**Comment by logicminimal** [comment]
> A. Yes, AI have relationship levels between each other. Yes, it's affected by things like nuclear weapons.
> B. Interesting idea, do PEOPLE usually buy/sell cities?
> C. Would YOU gift a unit to a weaker civ you're allied with? I wouldn't. Therefore I won't make the AI do it.

out of context but how much of the diplomacy do you think si implemented in unciv compared to civ 5 yairm?

**Comment by yairm210** [comment]
Definitely most of it.
It's not that Unciv is so behind, as much as it is that people expect more diplomacy options than appear in Civ V...

**Comment by yairm210** [comment]
I reiterate my point about Diplomacy.
The AI's goal is not to make your life easier. The AI's goal is to win.
The more the AI is aligned to this goal, the more 'player-like' it will seem to other players.
I think the whole 'relationship bar' that means you can tell how 'friendly' an AI is to you is a silly concept from the get go.

**Comment by yairm210** [comment]
What AI demands are missing?

**Comment by yairm210** [comment]
And what do you mean that it doesn't accept research agreements? Can you send a save file?

**Comment by yairm210** [comment]
By 'most of it' I mean:

```kotlin

enum class DiplomacyFlags{
    DeclinedLuxExchange,
    DeclinedPeace,
    DeclinedResearchAgreement,
    DeclaredWar,
    DeclarationOfFriendship,
    ResearchAgreement,
    Denunceation,
    BorderConflict,
    SettledCitiesNearUs,
    AgreedToNotSettleNearUs,
    IgnoreThemSettlingNearUs,
    ProvideMilitaryUnit,
    EverBeenFriends
}

enum class DiplomaticModifiers{
    DeclaredWarOnUs,
    WarMongerer,
    CapturedOurCities,
    DeclaredFriendshipWithOurEnemies,
    BetrayedDeclarationOfFriendship,
    Denunciation,
    DenouncedOurAllies,
    RefusedToNotSettleCitiesNearUs,
    BetrayedPromiseToNotSettleCitiesNearUs,
    UnacceptableDemands,
    UsedNuclearWeapons,
    StealingTerritory,

    YearsOfPeace,
    SharedEnemy,
    LiberatedCity,
    DeclarationOfFriendship,
    DeclaredFriendshipWithOurAllies,
    DenouncedOurEnemies,
    OpenBorders,
    FulfilledPromiseToNotSettleCitiesNearUs,
    GaveUsUnits
}
```

**Comment by logicminimal** [comment]
@yairm210 i think i'll do a bit of research on the diplomacy of civ 5 and see what is implemented and what isnt, thanks for your answer. btw ill try to reproduce the time when the ai doesnt accept research agreements

**Comment by jahodovykolac** [comment]
> A. Yes, AI have relationship levels between each other. Yes, it's affected by things like nuclear weapons.
> B. Interesting idea, do PEOPLE usually buy/sell cities?
> C. Would YOU gift a unit to a weaker civ you're allied with? I wouldn't. Therefore I won't make the AI do it.

A. Ok, crossed that out
B. I personally do, and it's good to have your cities connected
C. Yes, I would, that's what allies are for (not being like "Hey I like you but you're weak bye"), not just research agreements. But it's ok, I can cross that out

**Comment by Interdice** [comment]
I made some pull requests that has the AI value bordered and surrounded cities more and has the AI value distant cities less. I Also wrote a function to find bordered civs

**Comment by jahodovykolac** [comment]
Nice :D
(Also adding one thing onto the list)

**Comment by yairm210** [comment]
Closing as part of our cleanup
