### ISSUE TITLE
Buildings gifted from policies once a city is settled has conflicts with settler buildings

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4671]
say you are in the Renaissance era and you settle another city, that city should start with a monument and a granary, but the problem is that i think building gifts from policies are given before insta buildings in cities which causes this problem: the city starts with a monument and a granary once built, i have the legalism policy so that means i will get an extra building when settling the city but while settler buildings should be calculated first it isn't so i got a monument instead of an amphitheater. but atleast that monument was maintenance free.

steps to reproduce the save:
1: start in renaissance era
2: settle your first city instantly then get the legalism policy
3: settle another city
4: you have a monument instead of an amphitheater

save: https://hastebin.com/raw/giyeholabe

**Comment by yairm210** [comment]
Nice catch!

**Comment by logicminimal** [comment]
> Nice catch!

thanks!

**Comment by logicminimal** [comment]
thanks!
