### ISSUE TITLE
Warn players when buildings cannot be built together

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#4690]
Put warnings in the building's description, and in Civilopedia, when buildings cannot be built together. The Solar Plant and Nuclear Plant, for instance, give the player no warning that you have to choose one or the other. Some kind of notification would be appreciated.

**Comment by yairm210** [comment]
Good catch!
The 'special parameters' they have should be converted to uniques.

**Comment by SomeTroglodyte** [comment]
Indeed, I missed that. `cannotBeBuiltWith`, `hurryCostModifier` and `quote` are the only direct attributes of Building with no expression in Civilopedia, and the other two - could be argued are OK to not turn up...

**Comment by SomeTroglodyte** [comment]
Which in turn points to certain "Rejection reasons" not being translateable...
