### ISSUE TITLE
Add display option of a window with building civilopedia in the city screen

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#470]
* selectable from buildings list directly above
* if device screen size permits to fit it there:

![ciciv](https://user-images.githubusercontent.com/40436282/53289148-7b021e00-3792-11e9-9c20-3c2f3a79400f.png)

May be useful for the players that forget what the building does after the have built it

**Comment by yairm210** [comment]
Great minds think alike!
I was actually going to implement this soon, so I would have a place to put the 'sell building' button
