### ISSUE TITLE
Maps in mods dont appear in Map Editor

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4705]
Currently when downloading maps via mods, they dont show up in the Map Editor automaticly.

Is this intended behaviour? I dont think so. By having this, editing for personal use or tweaks would be easier and shorter.

**Comment by SomeTroglodyte** [comment]
Yes I think you should edit only your own maps. Modders can copy them as needed locally, and making them do so is good to promote 'switching you brain to _on_ mode'.

But thanks for bringing to our attention the map editor loader is buggy (doesn't handle bad maps gracefully).

**Comment by ArchDuque-Pancake** [comment]
Ah ok, true. I'll close this then.
