### ISSUE TITLE
Losing your starter settler shouldn't make you lose the game

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4707]
as ravignir says you need to lose all your units (all military+settler units im guessing) to lose the game if you havent settled a city. in the current version of the game losing your settler is enough which mustn't be, as you have a chance to upgrade your warrior get units from barbarian encampments and get a city

more information: say in a scenario you capture a city before settling your first settler and you lose that city, you dont lose as you have your special settler startersettler unique

lot more information: if you settle your first city normally then get a settler then get all your cities conquered you lose as you lost all your cities and your only settler isn't a special settler

**Comment by yairm210** [comment]
This is inconsistent.
Either you lose by losing all cities, or you lose by losing all cities and settlers.
There's no such thing a special settler.

**Comment by logicminimal** [comment]
> This is inconsistent.
> Either you lose by losing all cities, or you lose by losing all cities and settlers.
> There's no such thing a special settler.

in civ 5 tgere is, just ask @ravignir

**Comment by yairm210** [comment]
This sounds like a "wontfix" to me.
I'm not going to make certain units 'special' versions of their kind.

**Comment by ravignir** [comment]
This ain't a wontfix. There is no special settler.
Lose condition just changes from:
- lose all your units (until you control any original capital)
- lose all your cities (activates when you control any original capital).

**Comment by ravignir** [comment]
I've made such tests to determine that:
- disband a settler right after the start (game still continues).
- capture another civs non-capital city while still having a settler, then let the AI retake it (game still continues)
- capture another civs capital city while still having a settler, then let the AI retake it (game is lost)

**Comment by SomeTroglodyte** [comment]
> Lose condition just changes from...

Do I understand that correctly:
- If I've never founded my original capital myself and have never conquered any original capital, then it's irrelevant whether I own a city (which would be my capital automatically, including Palace, but it wouldn't be an _original_ capital) or not, if my unit count is zero, I lose. I have any unit, any type, even a worker, then I'm still in the game.
- Once I have ever controlled any original capital, my units are irrelevant for determining loss condition, only losing my last city counts, even if I have the map covered in settlers.

Therefore, what a Settler is (in a mod or Conquistador or...) or how many I have never matters at all.

**Comment by ravignir** [comment]
> > Lose condition just changes from...
> 
> Do I understand that correctly:
> 
> * If I've never founded my original capital myself and have never conquered any original capital, then it's irrelevant whether I own a city (which would be my capital automatically, including Palace, but it wouldn't be an _original_ capital) or not, if my unit count is zero, I lose. I have any unit, any type, even a worker, then I'm still in the game.
> * Once I have ever controlled any original capital, my units are irrelevant for determining loss condition, only losing my last city counts, even if I have the map covered in settlers.
> 
> Therefore, what a Settler is (in a mod or Conquistador or...) or how many I have never matters at all.

Exactly like that.

**Comment by SomeTroglodyte** [comment]
People, I find that logic so unintuitive, I'd not be disappointed if our chief doesn't wish to follow, but it's tested and PR'ed anyway.

What has become of that "require complete defeat" option I remember from other 4x games - which determines whether settlers matter when you lose your last city, planet, whatever...
