### ISSUE TITLE
Hill deprecation shows crash loophole in `getLastTerrain()`

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4709]
- Find an old map that has used an old Civ5ExpansionMod and that way has BaseTerrain Hill and TerrainFeature 'Desert Hill'
- Load it with current code and current mods
- The loader thread crashes, leaving the game in an unrecoverable state, stack trace fingers `isImpassible()`

The actual cause is that in `getLastTerrain()`, the assumption is made that `terrainFeatures.isNotEmpty()` means `getTerrainFeatures()` isn't empty either, which is not the case when some feature string is missing from the ruleset - that function uses `.mapNotNull` - uh-huh, obvious.

Proposed approach, completely untested:
- `val terrainFeatureObjects: List<Terrain> by lazy { terrainFeatures.mapNotNull { ruleset.terrains[it] } }` and use where appropriate, including returning it directly from `getTerrainFeatures()`

Comments, critique, lambasting, ridicule, the stocks, anything?

Note: Map loader UI needing more robustness in case its sub-thread crashes is a completely different story.

**Comment by yairm210** [comment]
So is this resolved with latest PR?
