### ISSUE TITLE
City-states revealed by finding a crudely-drawn map in the ruins aren't immediately added to the Diplomacy screen

### ISSUE THREAD

**Issue by BlueManedHawk** [yairm210/Unciv#4720]
**Describe the bug**
See title.  They are added the turn after.

**To Reproduce**
Find a crudely-drawn map in the ruins and hope it reveals a city-state.

**Expected behavior**
The city-state would be added to the diplomacy screen immediately.

**Screenshots**
null

**Additional context**
null

**Comment by logicminimal** [comment]
@ravignir is this thecsse in the original game?

**Comment by ravignir** [comment]
> @ravignir is this the case in the original game?

Not a bug. Works as intended.

**Comment by logicminimal** [comment]
the problem he says he's having is that the city state isnt added to the diplomacy screen right when that city state gets revealed, it should function as if you met them and thst they are added to the diplomacy screen next turn

**Comment by ravignir** [comment]
But you don't met them. You only know when they are. They don't know you exist.

**Comment by logicminimal** [comment]
> But you don't met them. You only know when they are. They don't know you exist.

then the player shouldnt ever meet them in this case, the same way you can see coloured territories of x civilization but you havent met them

**Comment by yairm210** [comment]
Working as intended.
