### ISSUE TITLE
Changes to local mod files should be updated without a game restart requirement

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4725]
i think there should be an option for local mods where they are updated in-game when any of the files change in the mod files, this is especially useful as you need to actively work on jsons and have to restart unciv every time you do it.

**Comment by ArchDuque-Pancake** [comment]
Yeah, it is annoying to have to reopen unciv to update a mod.
But I don't know if its possible to add.

**Comment by xlenstra** [comment]
While this is not impossible, I feel like the time it will cost to implement this will be longer than the total amount of time it saves modders

**Comment by logicminimal** [comment]
> While this is not impossible, I feel like the time it will cost to implement this will be longer than the total amount of time it saves modders

the maybe the game should restart when any of the files change if the player isn't currently in a game, enabled with an option of vourse. this isnt a great way but most certainly better than nothing, however i think it would be horrible for this to be in the game forever

**Comment by yairm210** [comment]
This is not cost effective at all. Denied.

**Comment by logicminimal** [comment]
> This is not cost effective at all. Denied.

outside of accepting this or not, do you think that it  would be too hard to implement? wouldnt there be a half working quick fix like uninstalling and installing the mod through the code when any of the files are changed?
