### ISSUE TITLE
For the map climate overhaul

### ISSUE THREAD

**Issue by Done226** [yairm210/Unciv#4727]
The plain terrain on the map is too dense, and often produces large areas lacking resources

1
![Screenshot_2021-08-02-21-56-39-31_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/88042771/127873243-6d649bba-93a6-403f-a2c9-a82015d28d21.jpg)
Too many plains have led to a decrease in food

The distribution ratio should be adjusted moderately

**Comment by ArchDuque-Pancake** [comment]
Well, it is like that both in real life and in Civ 5

**Comment by yairm210** [comment]
I don't consider this a bug, but @ravignir - do you think this is a problem?

**Comment by logicminimal** [comment]
> I don't consider this a bug, but @ravignir - do you think this is a problem?

my opinion is that this is seen as a problem because there are not as many map generation variables as there is in civ 5 (f.i world age with older meaning more hills)

**Comment by yairm210** [comment]
No, he's saying that the current default map generation is worse, and if that's rue it needs to be addressed.
Also, he says that the new generation has more plains which means less food - map age won't help with that.

**Comment by SomeTroglodyte** [comment]
Wouldn't this be OK if we just changed the defaults for the advanced sliders a little? Someone fiddle with them until a map feels as if it had equivalent food/resource supply as a default Civ5 map, then PR's these values or tells us here?

**Comment by logicminimal** [comment]
> Wouldn't this be OK if we just changed the defaults for the advanced sliders a little? Someone fiddle with them until a map feels as if it had equivalent food/resource supply as a default Civ5 map, then PR's these values or tells us here?

@ravignir can u do this?

**Comment by ravignir** [comment]
![z](https://user-images.githubusercontent.com/30041793/127925035-c1108aaa-1e76-47a3-a5a9-3f83503410f7.png)
here is a chart of climate overhaul and a thing that does not look less nice, but should provide more grasslands outside equatorial area.

**Comment by AdityaMH** [comment]
Where i can change humidity. On advanced setting just only temperature.

**Comment by AdityaMH** [comment]
Climate overhaul was ravignir made is not bad too.
But making desert land (archipelago) little impossible here.
I think better solutions it's just change default advance setting for beginner.

And add information pop up about "what going happen, if somene scroll something" on advanced setting.

**Comment by logicminimal** [comment]
there are way too many plains, i can confirm this is a problem and too few deserts

**Comment by ravignir** [comment]
It can be closed, i think #4746
