### ISSUE TITLE
Ui scaling/sharper graphics 

### ISSUE THREAD

**Issue by Dalcinrafa** [yairm210/Unciv#4735]
Whenever selecting a higher resolution, the ui scales down drastically. However, when using the stardard resolution, things are not sharp enough in my eyes. A ui scale slider perhaps could solve that? Maybe even for accessibility purposes.

**Comment by logicminimal** [comment]
i have the sane issue, thanks for opening a thread for ir

**Comment by azymohliad** [comment]
Came here for the same feature request :) Unciv runs great on the [Pinephone](https://www.pine64.org/pinephone/) (the flatpak version), but in order for the UI to be the reasonable size for the mobile screen I had to set the lowest resolution (750x500). It would be great if it was possible to set native HD resolution and scale the UI.

**Comment by yairm210** [comment]
Since solved
