### ISSUE TITLE
Replace "Cannot enter ocean tiles until Astronomy" with global unique "Enables units to enter ocean tiles"

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#4738]
In order to give modders more flexibility, I propose that we deprecate the unit unique "Cannot enter ocean tiles until Astronomy" and the global unique "Enables embarked units to enter ocean tiles" in favor a single unique that will enable all units, whether they be embarked Land units or native Water units, to enter ocean tiles. This would enable modders to specify any tech they wanted to determine when units can enter ocean tiles.

If you want a unit to never be able to enter ocean tiles, just attach the unique "Cannot enter ocean tiles" to it. This unique would need to override the global unique, ensuring that units like the Trireme can never leave the coast. If you want a unit to not be able to enter coasts until a certain time, you wouldn't need any unique on that unit at all. Just let the global unique do the work. (Incidentally, Polynesia's Wayfinding unique would need to override all uniques related to entering ocean tiles, just as it does now.)

If I actually knew Kotlin, I'd code this myself, but I don't know Kotlin, so I'm asking for help to make this a reality.

**Comment by logicminimal** [comment]
something like this?

[unitFilter] units can't enter [tileFilter] tiles without [tech]?

can enter [tileFilter] tiles
can't enter [tileFilter] tiles

etc?

**Comment by logicminimal** [comment]
if somebody implements this please implement policy just like [tech] in it

**Comment by SpacedOutChicken** [comment]
Not quite. I was thinking of a civ-wide unique that can be embedded in the tech tree: "Enables units to enter ocean tiles". Before that, no units at all can enter ocean tiles; no boats, no embarked units, nothing. But once you get that unique, everyone can go deep sea swimming except for ones that specifically have the "Cannot enter ocean tiles" unique. Under this system, the Work Boats would not have a unique at all, because they wouldn't need it.

The code for movement has a lot of hard-coded features in it for the sake of optimization, so I don't think uniques with tile filters will work. There's a reason that "Double movement through forest and jungle" specifically says forest and jungle instead of allowing the player to choose where double movement kicks in.

**Comment by yairm210** [comment]
@xlenstra I think this is closable with the latest conditionals?

**Comment by xlenstra** [comment]
I'd say that while not the original idea, conditionals allow for the same freedoms as having a unique allowing all existing units to enter ocean tiles

**Comment by SpacedOutChicken** [comment]
I agree with xlenstra. The new system with conditionals, while not exactly what I asked for, does everything I wanted. I am satisfied.
