### ISSUE TITLE
I got settler from an ancient ruin on king difficulty

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4741]
![Screenshot_20210803-144202_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/128009667-892b9460-48de-4e18-a2b9-1296a744eed3.jpg)
![Screenshot_20210803-144210_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/128009714-5b5c43d1-5a62-4a6b-93f7-1b8e29509960.jpg)

edit: i also got a worker on another game

**Comment by xlenstra** [comment]
This is already on the list of missing features from civ 5
