### ISSUE TITLE
Can't changing undiscovered tiles

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4749]
When i'm trying to remove CrosshatchHexagon.png with add transparent CrosshatchHexagon.png on my own mod and change Hexagon.png , but the result:

![IMG_20210730_142217](https://user-images.githubusercontent.com/33791472/127732621-8bb69b67-6267-4497-af34-33c5c191fa96.jpg)
Very dark from original image.

This bug only happen when triggered with "fantasyhex" folder.

**Comment by ravignir** [comment]
i think you need json file for your tileset, with such lines:
"unexploredTileColor": {"r":1,"g":1,"b":1,"a":1},
"fogOfWarColor": {"r":0,"g":0,"b":0,"a":1},

r -red, g-green, b- blue, a-alpha

**Comment by AdityaMH** [comment]
> i think you need json file for your tileset, with such lines:
> "unexploredTileColor": {"r":1,"g":1,"b":1,"a":1},
> "fogOfWarColor": {"r":0,"g":0,"b":0,"a":1},
> 
> r -red, g-green, b- blue, a-alpha

I'm also add this but didn't work.

**Comment by AdityaMH** [comment]
Unsolved
