### ISSUE TITLE
Civilopedia - rfc for wrap-up or Phase X

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4765]
### Project "Spruced up Civilopedia" nearly finished
I originally planned to go from phase 9 (#4737) to phase 10 and end it there, merging in the rest of the stashed code from the start. But - there's almost none left, some of that debatable, and new ideas have cropped up. So - I'll publish my remaining notes here and invite collaboration, I'm sure I will regret this :smirk_cat: . Some of these are already y'all's ideas, thanks!

#### Rules
- My PR Phase 10 will be very limited, no big leaps. Therefore many of the points here should be seen as invitation to use the system yourselves in your own PR's
- I repeat: The checkboxes are not meant to be all implemented by myself.
- I will not respond to each post (if any) in detail, but will take each into consideration. If it's clearly imaginable, concise, and I like it, I will edit it into a checkbox up here in this post.
- Pros/Cons referring to existing checkboxes welcome, their aggregate trend might make it into this list.
- Boxes get checked when they're specific enough, and I am convinced they're desirable, not when any implementation has any progress, or when technical feasibility is assured.

#### Purely visual optimizations
- [x] Decide where the first Tabstop should go - 3 icons worth + padding as it is now, 2 icons + padding (I'd tend to this), or...? (indent=1 is necessary to make uniques lists align when some of them autolink some not - the current indent already has had several complaints)
- [ ] Display pixel unit sprites on their page yes/no? Respecting mods (5Hex)?
- [x] Eras have colours in their json...
- [x] Align terrain icons properly

#### Purely technical stuff
- [x] Lint
- [x] Make sure approach to Listing 0/1/many of a prerequisite/whatever is consistent
- [x] Link from UnitTable is broken if a city is selected right after a unit -> go to Nation instead, or?
- [x] Difficulties - move to FormattedLine with next to no formatting or leave as is
- [ ] Tutorials - rewrite json to provide CivilopediaText - or not. Adapt code. Use linking abilities.
- [x] Clean up unused code - if Difficulties and Tutorials move to FormattedLine then a lot in the CivilopediaScreen code is dead
- [x] See if the repeated categoryToEntries code can't be made into a loop
- [x] See if I want to use the renderer in the newgame nation picker to save code duplication and for side benefits
- [ ] Update mod consistency checker to check for FormattedLine validity

#### Content
- [ ] More useful information - ideas?
- [ ] Instead of a (not trivial) browser-like "Back" button make sure you will almost always find a link back if you came from another page (e.g. Library -> Paper maker and back) - example follows.
- [x] Unit "Upgrades from" - technically similar to Tech "Leads to"
- [ ] Merge Promotion levels (e.g. Cover I, II) into 1 page - IMHO relatively complex (if done mod-safe) with mediocre gain
- [x] Display Policies -> sorted by Branch then name? A page per branch (please no)? Are links _to_ them useful somewhere?
- [x] Display the Barbarians as Nation for some flavour text? Or are they already well covered in tutorials?
- [x] Display City States in Nations category
- [ ] Would we want to see which mod, if any, a specific object comes from?

#### UI outside Civilopedia Screen
- [ ] More links from outside (tech researched alert?)
- [ ] Leverage ability to link _to_ Tutorials (or Difficulties, though I guess none needed to those, but the ability exists) - where, why...

**Comment by ArchDuque-Pancake** [comment]
What about showing the FH sprite of units in a bigger scale?

**Comment by ravignir** [comment]
> 
> 
> What about showing the FH sprite of units in a bigger scale?

i was about to suggest that :)

**Comment by ravignir** [comment]
- display quote for techs/wonders in civilopedia.
- policies should be a part of civilopedia (policy tree info and required policies/prerequisite to).
- add city states to civilopedia.

**Comment by ravignir** [comment]
Regarding city states: their type and benefits for befriending/allying with them.

**Comment by SomeTroglodyte** [comment]
... the obvious, which is not much. Colour. No nation icon. No leader portrait.

We *could* enter tons of flavour text for all of the objects, then the CS would be less boring in the nations category, but - tons of work I'm not partial to, and aggravating the copied-verbatim issue we already skim around. I only activated the `startIntroPart`s because someone had already entered them, including typos the upstream copycats introduced...

**Comment by ravignir** [comment]
>We could enter tons of flavour text for all of the objects, then the CS would be less boring in the nations category, but - tons of work I'm not partial to,
>
Yup, that is what civ 5 does with histrocial info for almost any object but it indeed looks like a lot of work for not that much of a benefit.

**Comment by SomeTroglodyte** [comment]
> a lot of work

...Now relatively easily moddable... OH! _Documentation_! OH! Terrain icons!

**Comment by SomeTroglodyte** [comment]
[Documentation for modders is done](https://github.com/yairm210/Unciv/wiki/JSON-files-for-mods#civilopedia-text)

**Comment by AdityaMH** [comment]
Building color each civ and cs

**Comment by will-ca** [comment]
> Yup, that is what civ 5 does with historical info for almost any object but it indeed looks like a lot of work for not that much of a benefit.

Well, Wikipedia's GFDL/CC-licensed, with not only the article text and article lead but also a "short description" tag that they use for search results. Could even get all the languages at once.

**Comment by SomeTroglodyte** [comment]
> Wikipedia's

? Do you mean wikipedia has copies of the C5 descriptions somewhere or do you mean scrape & display normal wikipedia hit texts ? Hmmm. That could get horribly long, lose much due to loss of formatting - but yea, sounds possible. Another thing I'd pull out python for if I weren't ...distracted...
