### ISSUE TITLE
Can't launch the game on windows 64bit

### ISSUE THREAD

**Issue by Zakaria-ouertani** [yairm210/Unciv#4766]
Steps to reproduce
1) Download latest 64bit version from GitHub
2) Run Unciv.exe
3) Window pops up and immediately closes
(Unciv.jar does the same thing)

I tried running both 64 and 32 bit versions

**Comment by SomeTroglodyte** [comment]
Not enough info. There's been at least 10 different "windows 64bit", not counting emulations or the w10 major upgrades. The package even runs on Wine!
What do `ver`and `java -version` run from a dosbox say?

**Comment by Zakaria-ouertani** [comment]
> Not enough info. There's been at least 10 different "windows 64bit", not counting emulations or the w10 major upgrades. The package even runs on Wine!
> What do `ver`and `java -version` run from a dosbox say?

Oh nah sorry forget about it the problem is from my computer (it's way too bad)
