### ISSUE TITLE
City states' resources subtract wrongly

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4769]
![Screenshot_2021-08-05-12-17-27](https://user-images.githubusercontent.com/79529669/128335586-a7606d75-0c06-4b59-a0a3-2932b0a51db1.png)

**Comment by logicminimal** [comment]
one thing id add, do negative resources also get shared with the player, effectuvely taking away their resources?

**Comment by yairm210** [comment]
@jahodovykolac that's an acceptable case.
The real issue this raises is - do city states give allies *all strategic resources* in their territory, or only *unused* ones?

**Comment by logicminimal** [comment]
@ravignir

**Comment by ravignir** [comment]
> 
> The real issue this raises is - do city states give allies _all strategic resources_ in their territory, or only _unused_ ones?
>
They do give a copy of them (basically they resources double and you gain half of them).

**Comment by logicminimal** [comment]
> > 
> > The real issue this raises is - do city states give allies _all strategic resources_ in their territory, or only _unused_ ones?
> >
> They do give a copy of them (basically they resources double and you gain half of them).
> 

what are "them", the all they have within their borders or ones they currently have for spare

**Comment by ravignir** [comment]
Resources they give to players are copies of their existing resources.
Let's say AI has Whales. If you ally them, their single Whales tile will provide two Whales resources, one of which you will be granted.

**Comment by logicminimal** [comment]
> Resources they give to players are copies of their existing resources.
> Let's say AI has Whales. If you ally them, their single Whales tile will provide two Whales resources, one of which you will be granted.

i am talking about strategic resources

**Comment by ravignir** [comment]
No, I just used luxury as an example because it is more translatable to unciv. In civ5 Startegic resources appear in various quantities, so if I said 4 horses become 8, it would not make sense in unciv.

**Comment by logicminimal** [comment]
> No, I just used luxury as an example because it is more translatable to unciv. In civ5 Startegic resources appear in various quantities, so if I said 4 horses become 8, it would not make sense in unciv.

u should have just said that all strategic resources are given an extra to that civ whether its used or not

**Comment by jahodovykolac** [comment]
> that's an acceptable case.

Okay, I just thought it would look cleaner when it would show just 1 Horse, not 2 Horses and -1 Horse.
And by the way, I tested, in Unciv CS give copies of only unused resources, but we probably want to know how it is in Civ5.
