### ISSUE TITLE
Settings window gets wider when a string is too long and you can only see a bit of that long string

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4770]
Settings window gets wider when a string is too long and you can only see a bit of that long string

![Screenshot_20210805-160041_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/128354226-ad17ce09-8296-4ed4-9ccd-cf630240eee5.jpg)

My proposal would be to share those strings over in paragraphs like

```
for this string you should cut this in 
half and append it to the next line
```

Also when you play unciv like this

![Screenshot_20210805-161602_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/128356348-0c23453e-9942-48f1-a5f8-be8231c41fa6.jpg)

the options menu isnt scaled properly, so i cant do anything in it. even when i choose the portrait mode before doing multitasking it is still the same

**Comment by yairm210** [comment]
Return the issue title to what it was

**Comment by logicminimal** [comment]
> Return the issue title to what it was

done

**Comment by yairm210** [comment]
Yeah, this is such a strange edge case it's not worth solving programatically. Just add a \n to the translated text.

**Comment by logicminimal** [comment]
> Yeah, this is such a strange edge case it's not worth solving programatically. Just add a \n to the translated text.

this isnt necessarily about the text itselfz the problem is that the buttons don't re position themselves when the resolution is too low and the strings make that window wider, contributing to that problem
