### ISSUE TITLE
Unit gifting requests

### ISSUE THREAD

**Issue by ajustsomebody** [yairm210/Unciv#4781]
1: you shouldnt need your unit to be in that civs tile to gift it, u can just gift them in diplomacy window and it will take 3 turns for it to get there (dont know if you can cancel a gift during those 3 turns)

2: u should be able to gift units to other civs ( this doesn't give any relation boosts in civ 5 but i think thats a bad mechanic )

**Comment by logicminimal** [comment]
i really hope this doesnt get ignored as it is kind of a major thing in mp

**Comment by will-ca** [comment]
Quickly looking at the `UnitActions` code, it does seem like gifting to other major players is supported. Was this changed recently, or was it originally planned but never fully enabled?

**Comment by yairm210** [comment]
Closing due to lack of interest

**Comment by Bzzztt** [comment]
This seems like a significant missing feature- I think it's worth keeping open
