### ISSUE TITLE
Add more option about screen rotation

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4790]
Since got denied about sensorable orientation.
my suggestion is add more option orientation in-game. (default (SCREEN_ORIENTATION_USER) portait, landscape, reverse-landscape)

Like this:
![IMG_20210807_084433](https://user-images.githubusercontent.com/33791472/128584200-1910ca0c-de8b-40d0-b157-d7c30d33650a.jpg)

**Comment by yairm210** [comment]
I'm against this, as discussed in a separate pr
Following the user already provides the user with control over the direction of the screen
The less config options in game, the better

**Comment by AdityaMH** [comment]
> The less config options in game, the better

I don't think you know about what i mean.
