### ISSUE TITLE
Do not upgrade units straightaway to their most recent version.

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4792]
Make it impossible to update an archer to Machine Gun in one turn with one tap. I am playing Korea, I have Catapults and I can't upgrade them to Hwacha beecause they just become Cannons. And Hwacha's are better than cannons in certain situations. Same can be said about some other units.
Also: that is how it works in civ5. You can only upgrade once per turn and gradually.

**Comment by AdityaMH** [comment]
But upgrade an unit one by one make upgrade price mooore higher than usual.

**Comment by logicminimal** [comment]
> But upgrade an unit one by one make upgrade price mooore higher than usual.

i guess that's how it is in civ 5

**Comment by logicminimal** [comment]
i have one suggestion to add, a unit should be able to upgrade into more than 1 units for moddability

**Comment by ArchDuque-Pancake** [comment]
But this was decided by a poll...

**Comment by ravignir** [comment]
there should be at least an option to upgrade gradually.

**Comment by logicminimal** [comment]
> But this was decided by a poll...

what about just being able to choose which one it will upgrade onto

like if you are upgrading a warrior there should be a list

swordsman (123Gold)
longswordsman(123Gold)
Musketman (123Gold)
rifleman (123Gold)
gw infantry (123Gold)
etc (123Gold)
etc(123Gold)

**Comment by SomeTroglodyte** [comment]
If ravignir says you _need_ several turns in Civ5 for multi-step upgrades, then (apart from implicitly trusting their statements) that's a rule difference, and should be addressed. I am (now) all for the U button only doing one step. Choice would be a rule change and thus "not now". Volunteer coders? I'd rather fix half the key bindings hidden thanks to the 'More Button' first.

**Comment by yairm210** [comment]
This was polled and decided upon.
If anyone wants to code a modOptions for this they're welcome to PR it, but this is a "working as intended" for me.
