### ISSUE TITLE
Bonus from strategic resource not kicking in for Russia

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#4802]
Russia's unique is not working. It's not getting any production bonus from strategic resources. I think it's because there's a typo in the unique. [Strategic Resource] should be replaced by [Strategic resource].

**Comment by logicminimal** [comment]
another typo causing disasters :•D

**Comment by SomeTroglodyte** [comment]
Looks accurately observed. I know you can PR that...

**Comment by SpacedOutChicken** [comment]
I think xlenstra is already on the case.
