### ISSUE TITLE
Great Engineer Production Boost provides too much production

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4823]
You can use a single Great Engineer to basically build 2 Wonders in the earlier stages of the game. In civ5, Great Engineer Production boost is capped so it provides at most (Remaining building cost - 1) Production. It can be used to hurry non-wonder buildings as well.

**Comment by logicminimal** [comment]
there goes my strat of getting a wonder down to 1 turns left in a hoghly populated city any getting every building i wanted in total of 2 turns o7

**Comment by ravignir** [comment]
Great Engineer bonus should be capped at: "remaining production" -1

**Comment by logicminimal** [comment]
> Great Engineer bonus should be capped at: "remaining production" -1 

i would rather want this current way it works to be toggleable in game creation screen

**Comment by yairm210** [comment]
A. Pinging never helps
B. Imma poll this

**Comment by logicminimal** [comment]
> A. Pinging never helps
> B. Imma poll this

can u add a third option which allows it to be toggleable, defaulted to -1 one though

**Comment by yairm210** [comment]
No.
No toggles unless absolutely necessary.

**Comment by xlenstra** [comment]
I propose a hybrid solution, adding both a unique for the current implementation and one that is capped. The poll will then decide which of these should be the one used in the base game, but this gives modders the option to decide for themselves.

**Comment by yairm210** [comment]
That's fine

**Comment by xlenstra** [comment]
> That's fine

Regarding the wording in your poll, "capped at current production" sounds more like the current production in the city rather than the current production boost from the engineer, which may confuse users

**Comment by logicminimal** [comment]
> This is really dumb you can use a single engineer to build even three wonders (if you start with the most expensive one)

    what if the wonder is at 1 or a really small amount of production left?

**Comment by ravignir** [comment]
Why would you use an engineer then?
If you expect to get engineer: build other things instead of wonders or save your great engineer for another wonder.

**Comment by logicminimal** [comment]
> Why would you use an engineer then?
> If you expect to get engineer: build other things instead of wonders or save your great engineer for another wonder.

one could do so without noticing, my suggestion would be to if the current wonder construction takes more than 2 turns currently it should be able to use an engineer there, if it has 1 turns left it shouldnt be able to use the engineer

**Comment by ravignir** [comment]
> > Why would you use an engineer then?
> > If you expect to get engineer: build other things instead of wonders or save your great engineer for another wonder.
> 
> one could do so without noticing, my suggestion would be to if the current wonder construction takes more than 2 turns currently it should be able to use an engineer there, if it has 1 turns left it shouldnt be able to use the engineer
>

If you like to have all things automated, I suggest playing idle clicker games instead.

But if you really want that, cap the boost at the cost of current wonder production (instead of remaining production like in civ5). 

The current value is 300+30*population in a city - which is lazy value, blame civ5 for the fact engineeers in early game provide much more production than wonders require and not enough in the late game.

**Comment by ravignir** [comment]
>  It can be used to hurry non-wonder buildings as well.
>
https://user-images.githubusercontent.com/30041793/130024570-713e98dd-6599-4154-bd89-628bfe6e61e0.mp4

just make it impossible, it really hurts the game balance (3 wonders):
https://user-images.githubusercontent.com/30041793/130023670-aaf97db8-3b93-4b96-8d75-4ea32a10ffa1.mp4
