### ISSUE TITLE
GreatProphets from finishing the piety line doesn't work

### ISSUE THREAD

**Issue by Jinmjjjhrf** [yairm210/Unciv#4832]
**Describe the bug**
Great Prophets doesn't say which Pantheon they're from, can't spread faith, found religion, or even create holy site.

**To Reproduce**
1. Complete piety tree
2. See error

**Expected behavior**
Receive a new great prophet to spread my religion.

**Comment by xlenstra** [comment]
Note that this is specific to mods, as you can't get great prophets in the base game from finishing the piety tree. Regardless, I'll look into this later.

**Comment by ravignir** [comment]
Not yet, but that thing exists in G&K civ5.

**Comment by yairm210** [comment]
IIRC this works correctly now

**Comment by yairm210** [comment]
Closing as 'no longer relevant'
