### ISSUE TITLE
Harbor effect details

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#484]
Harbour should establish trades routes over water.

Between all cities at the shore line? At the moment only the cities at the same single body of water are connected, no matter how large or small it is. In other words, if you can't reach a city by boat from the harbour, this city will not be connected.

Sounds fair, but in some maps it will look sorry when a capital is at the small body of water and another cities at the large ocean.

**Comment by yairm210** [comment]
I understand what you're saying, but if it can't be reached by boat, I don''t think it should be connected via harbor.
Both choices will make certain situations seem strange, but connecting all harbors to each other is the stranger choice, in this dilemma
