### ISSUE TITLE
Crashes on patch 3.16.2-patch1

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4842]
Based on the discord it seems like there are multiple users on multiple devices unable to open the game after updating to the patch released yesterday.
One user posted the following stacktraces, which do not seem to include anything related to unciv:
![image](https://user-images.githubusercontent.com/71121390/129175508-9fcf48d6-4f4f-4178-9320-40bde3fb6018.png)
![image](https://user-images.githubusercontent.com/71121390/129175523-3c09b5d5-2c08-44f8-a1a6-f43072a43974.png)

I have no prolems running it on desktop or on android emulator, so I don't know what the problem could be.
Anyone else have any ideas?

**Comment by AdityaMH** [comment]
Libgdx.so and gdx problem?

**Comment by yairm210** [comment]
This is the first release I've made from my new Ubuntu, after moving from Windows, so this is probably a result of that.
It could be something to do with the JDK that changed, or with residual files in Windows that make this work.
In any case, I have some work ahead of me.
I think I'll just release the next version directly without a patch.

**Comment by yairm210** [comment]
But wait, Fdroid builds from scratch every release, so it can't be residuals.
Hmm.

**Comment by touhidurrr** [comment]
Maybe check every changes made in version 3.16.2-patch1 (lol)

**Comment by touhidurrr** [comment]
> Based on the discord it seems like there are multiple users on multiple devices unable to open the game after updating to the patch released yesterday.
> One user posted the following stacktraces, which do not seem to include anything related to unciv:
> ![image](https://user-images.githubusercontent.com/71121390/129175508-9fcf48d6-4f4f-4178-9320-40bde3fb6018.png)
> ![image](https://user-images.githubusercontent.com/71121390/129175523-3c09b5d5-2c08-44f8-a1a6-f43072a43974.png)
> 
> I have no prolems running it on desktop or on android emulator, so I don't know what the problem could be.
> Anyone else have any ideas?

Lol, typically the last lines contains the actual trace of the error encountered. So the stack is useless (mostly)

**Comment by Mape6** [comment]
The Screenshots above are from my Pixel 4a and I have the Playstore version.

**Comment by SomeTroglodyte** [comment]
I'll run a debug on hardware...

**Comment by SomeTroglodyte** [comment]
Nope, can't repro on hardware, neither an adb-deployed debug build nor the current play store version.
Any telling statistics on Android major version and architecture?

**Comment by yairm210** [comment]
Summary: I have NO IDEA what this could be.
Tagged version runs fine on my Android, as does current version.
That means the APKs are generated fine, and they run fine.
I honestly don't have any direction to go on.
For now I'll just hope really hard that this was a one-off and upload a new apk.

**Comment by SomeTroglodyte** [comment]
Hey that stack trace is clear - facepalm - one needs only look: loading libgdx.so "for Target: Linux 32-bit" - there is no longer a Gdx for stone-age 32-bit Linuxes, right? And that means that's not Android at all unless it's a really weird mix, right?

**Comment by Mape6** [comment]
That's strange. Because my Snapdragon 730G should support 64 Bit applications. And I'm on Android 11 with latest Security Patch. (05. August)

**Comment by SomeTroglodyte** [comment]
You're not by chance able to run a `adb shell getprop ro.product.cpu.abi`? Or - when was the last System update and does the full build number tell us something?

**Comment by Mape6** [comment]
I will post the output of the command later today.
The last Update was beginning last week with the new Security patch. See Screenshot. 
![Screenshot_20210812-191305](https://user-images.githubusercontent.com/77325495/129239686-146b905e-7774-4a5f-83d1-fc1dac31d44d.png)

**Comment by SomeTroglodyte** [comment]
As I feared - the lineageOS build number strings are a bit more verbose... getprop ro.product.cpu.abilist, please, too. My phone _does_ list two fallback 32-bit architectures even though its main arch is arm64-v8a - maybe the upstream ROM builders are starting to drop that by now?
