### ISSUE TITLE
Some unitFilters accept "city" as value while others don't

### ISSUE THREAD

**Issue by avdstaaij** [yairm210/Unciv#4855]
For some uniques, `"city"` is a possible value of `[unitFilter]`. For example, in `"+[Strength] vs [unitFilter]"`. However, this value isn't listed in the wiki, and not all `[unitFilter]` uniques check for it. For example, `"[unitFilter] Units adjacent to this city heal [amount] HP per turn when healing"` and `"Cannot be carried by [unitFilter] units"` do not work with `"city"` even though they conceivably could. There are also various uniques, like `"+[amount] Movement for all [unitFilter] units"`, which do not even make sense with `"city"`. It's not about whether the unique contains the word "units" either. For example, `"[amount]% Strength when defending vs [unitFilter] units"` contains "units" but _does_ work with the `"city"` value. These inconsistencies make it hard for modders (and contributors) to understand when `"city"`is supported.

Possible solutions:
- List `"city"` as a possible `[unitFilter]` value in the wiki and clarify which `[unitFilter]`'s support it and which ones don't.
- List `"city"` as a possible `[unitFilter]` value in the wiki and support it for all `[unitFilter]`'s that could reasonably apply to cities.
- Adopt a more generic `[combatantFilter]` for uniques that support `"city"`.

**Comment by yairm210** [comment]
Solved with new unique system
