### ISSUE TITLE
I can't open the game without it crashing on android

### ISSUE THREAD

**Issue by shenny1** [yairm210/Unciv#4856]
**Describe the bug**
Can't open game

**To Reproduce**
go to open app

**Expected behavior**
The game/app would open

**Comment by xlenstra** [comment]
What version of the app does it say you have in the play store? If it is 3.16.2-patch1, this is a known bug that is fixed in version 3.16.3 currently rolling out.

**Comment by yairm210** [comment]
Since the mentioned version is known to be problematic and was fixed, I'm using this as resolved unless we receive an indication otherwise
