### ISSUE TITLE
Make special ressources scarcer

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#486]
Ressources like horses, iron, coal, oil and uranium should be much scarcer, and go scarcer the more advanced they are.

They could also spawn more at the middle point between civs capitals to encourage competition.

**Comment by flecheapolinienne** [comment]
Sorry to reopen this, but it now seems maybe strategic ressources are a bit **too** scarce... I just played a game where there is no coal to be found nowhere on the map yet, and I'm in 1805 AD with maybe 75% of the map uncovered...

**Comment by yairm210** [comment]
Hm
Natural resources are completely random, which may not be what we want
Perhaps for every given number of tiles there should be a certain number of resources, which are then randomly distributed
