### ISSUE TITLE
3.16.4 will not Autosave

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4867]
Massive stacktrace output on the console.

Investigating, more info soon.

Some `kotlin.SynchronizedLazyImpl` in the json serializer... Yup, that would do it.
pressureFromAdjacentCities$delegate

I'll have to come up with a permanent solution... That must be detectable in a unit test. The last time I've seen this is not too long ago, I think it was ... me ... whodunnit, but maybe locally only.

**Comment by logicminimal** [comment]
aand there goes 3.16.4-patch1
