### ISSUE TITLE
The workers (or basically any unit that requires time to build anything) stolen from other civs dont stop improving

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4878]
When you steal a worker from another civ and dont route it to anywhere else, if that worker was working before it got captured will continue on to work that tile, and will also actually build it

steps to reproduce:
1: find a worker improving something
2: steal it
3: the worker still continues to work that tile unless you make it move out of that tile (automation still directs that worker to continue working on the tile it is, and potentially directing it to other foreign civ tiles to work them)

**Comment by SomeTroglodyte** [comment]
Old hat. A tile improvement time requirement, once the improvement has been started, is a property of the tile and not the worker. Always was. I vote wontfix.

**Comment by yairm210** [comment]
Same. Always has been.

**Comment by logicminimal** [comment]
@ravignir is it this way in civ 5?

**Comment by logicminimal** [comment]
this is a bug

**Comment by logicminimal** [comment]
> Old hat. A tile improvement time requirement, once the improvement has been started, is a property of the tile and not the worker. Always was. I vote wontfix.

but you commented this same thing on the other issue as well

**Comment by ravignir** [comment]
results are a bit weird: 
https://user-images.githubusercontent.com/30041793/129679030-99ade86d-5eff-4135-959c-c594678b2d21.mp4

another thing is civ5 does not let you improve resources with other improvements. Wheat tiles can only be improved by farms, horses only pasture, coal - only mines, deers only camps, and bananas - only plantations.

with strategic resources it is weird, cuz you can improve them with other improvement as long as you don't see them.

**Comment by ravignir** [comment]
probably improvement is 20 turns, worker base speed is 1 turn . With liberty policy it goes up to 1.25. With pyramids it goes to 1.5625 for new workers and 1.5 to already working workers.

**Comment by ravignir** [comment]
so this thing probably works different in unciv, in unciv improvement time gets decreased instead of worker speed incresing.

**Comment by ravignir** [comment]
math in unciv seems to be a little bit off. in civ5:

quick game speed: plantation\farm\mine\trading post\camp\lumber mill are 4 turns. pasture\fort\quarry are 5 turns, oil well is 6 turns.
standard game speed: plantation is 5 turns, farm\mine\trading post\camp\lumber mill are 6 turns. pasture\fort\quarry are 7 turns, oil well is 8 turns.
epic game speed: plantation is 8 turns, farm\mine\trading post\camp\lumber mill are 10 turns. pasture\fort\quarry are 11 turns, oil well is 13 turns.
marathon game speed: plantation is 17 turns, farm\mine\trading post\camp\lumber mill are 20 turns. pasture\fort\quarry are 23 turns, oil well is 26 turns.

So i guess:
standard speeds are 6.0, 7.0, 8.0, 9.0 (each -1 in reality)

**Comment by logicminimal** [comment]
@yairm210 so will you re open this?

**Comment by xlenstra** [comment]
So I've looked into the publicly available source code, and from there it looks like everything you have said is correct, Ravignir.
The game values stored in civ5builds.xml are actually 600, 700, 800 and 900 on standard speed, and I think (but can't get this out of the source code clearly) that the -1 comes from the worker already working on the tile this turn and thus preventing a visual off-by-one-error.

**Comment by logicminimal** [comment]
> So I've looked into the publicly available source code, and from there it looks like everything you have said is correct, Ravignir.
> The game values stored in civ5builds.xml are actually 600, 700, 800 and 900 on standard speed, and I think (but can't get this out of the source code clearly) that the -1 comes from the worker already working on the tile this turn and thus preventing a visual off-by-one-error.
> 
> This is, however, a different issue from the one this issue is about so I propose opening a new issue on this
> 

does #4879 count?

**Comment by xlenstra** [comment]
> > So I've looked into the publicly available source code, and from there it looks like everything you have said is correct, Ravignir.
> > The game values stored in civ5builds.xml are actually 600, 700, 800 and 900 on standard speed, and I think (but can't get this out of the source code clearly) that the -1 comes from the worker already working on the tile this turn and thus preventing a visual off-by-one-error.
> > This is, however, a different issue from the one this issue is about so I propose opening a new issue on this
> 
> does #4879 count?

No, because that issue about speed bonuses not applying to workers once they have started building something, while Ravignirs post is about the total time it should normally take to build them.
