### ISSUE TITLE
Getting a work speed bonus amidst working something doesnt reduce time

### ISSUE THREAD

**Issue by ajustsomebody** [yairm210/Unciv#4879]
Getting a work speed bonus amidst working something doesnt reduce time, even when you work a tile>get policy>get that worker out of that tile>get back that worker into that tile and continue working it, it still consumes 20-21 turns on marathon while it should have been lowered to 16. this is only the case for things that have a bit of progress of improvement, say for a hill tile next to fresh water, you can work a farm there and when you get that liberty policy the farm will still have 20 turns left while the not touched mine will have 16 turns left. this is fixed with pressing remove improvement order but no one can do that manually for every worker.

**Comment by SomeTroglodyte** [comment]
Old hat. A tile improvement time requirement, once the improvement has been started, is a property of the tile and not the worker. Always was. I vote wontfix.

**Comment by ravignir** [comment]
I explained how it works in civ5 - with a video - in #4878.
