### ISSUE TITLE
Missionaries Cannot Spread Their Religion

### ISSUE THREAD

**Issue by Dark-04** [yairm210/Unciv#4901]
**Version**
3.16.3
**Describe the bug**
The button " Spread (Religion) " does not appear

**To Reproduce**
1. Found a religion
2. Create a missionary
3. Send the missionary to a possessed city unconverted

**Screenshots**

/storage/emulated/0/Pictures/Capture d'écrans/Capture d'écrans_20210818-191433.png

**Comment by xlenstra** [comment]
Thanks for your report! This bug should be fixed in 3.16.4, which your device should update to in a few days at most. If your bug persists in that version, do please create a new bug report.
