### ISSUE TITLE
The game crashes when i upgrade a swordsman to a longswordsman then do literally anything

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4922]
save: http://hastebin.com/raw/gupoyidivu

version: 3.16.4-patch2 (1 version prior to 3.16.5)

how to reproduce the problem:
1: upgrade a swordsman (preferably the one in cuzco)
2: press overview or upgrade another swordsman
crash

**Comment by xlenstra** [comment]
Unable to reproduce on my phone and on desktop, but a similar problem has been noted by a user on discord

**Comment by logicminimal** [comment]
> Unable to reproduce on my phone and on desktop, but a similar problem has been noted by a user on discord

yairm if you are reading this ill send the event log with code swordsmanbug

**Comment by logicminimal** [comment]
yep even if i pass a turn and replicate the steps to reproduce it is still broken, rip save

**Comment by xlenstra** [comment]
If you by chance have a stacktrace/logs of what went wrong, do send them here, that would help a lot

**Comment by logicminimal** [comment]
posted on #bugs @xlenstra

**Comment by SomeTroglodyte** [comment]
There's no Swordsman _in_ Cuzco in that game, but it's another of those `UninitializedPropertyAccessException` - `UnitPromotions.unit` is lateinit, public, and no code in the class itself sets it.

I vote for a new convention:
- lateinit is only allowed if _all_ of the following are met:
    - The variable is private
    - It is initialized inside the class in a constructor or a `setTransients` function, no other writes allowed
    - It has comments documenting where exactly the initialization occurs and why it is guaranteed to occur in time
