### ISSUE TITLE
When the open borders agreement stopped, my submarine was moved from the sea into the lake not connected to the sea

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4923]
**Platform**
Android 

**Version**
3.16.3

**Describe the bug**
Submarine was in neighbours aquatory when open borders treaty was on. After open borders is finished, submarine was automatically moved out of the borders, which is expected. But in result it was placed to the lake which is not connected to the sea

![Screenshot_2021-08-20-12-37-07-129_com unciv app](https://user-images.githubusercontent.com/86048557/130214654-38fe65c9-bc3f-4d39-897b-bea472a7bc82.jpg)
![Screenshot_2021-08-20-12-47-08-897_com unciv app](https://user-images.githubusercontent.com/86048557/130215011-d28dff8f-3b6e-4377-b660-ffbcd24754d2.jpg)

```

```
</details>

**Expected behavior**

Submarine is placed to sea instead of lake

**Comment by logicminimal** [comment]
this is actually probably how it is intended to work but id vote for change how this works

**Comment by ArchDuque-Pancake** [comment]
I would suggest a notification of: ¡Our Open Borders agreement with [civ] are about to end!.

And also for an oportunnity to renew those open borders before they end.

**Comment by logicminimal** [comment]
> And also for an oportunnity to renew those open borders before they end.

this could work also but i still think we need to make deported units land in somewhere good

**Comment by Bershcomp** [comment]
At the next turn I was lucky to escape from this situation. Open Borders with Denmark also finished, so my submarine jumped to the nearest sea tile in my aquatory - the one at upper left corner
![Screenshot_2021-08-20-17-33-06-595_com unciv app](https://user-images.githubusercontent.com/86048557/130249457-6f933289-8888-44e4-b013-6873d9ed1722.jpg)

**Comment by Bershcomp** [comment]
Two steps before near Cusco... 
![Screenshot_2021-08-20-17-37-02-318_com unciv app](https://user-images.githubusercontent.com/86048557/130250112-80079882-89df-4318-8855-38158b8706e7.jpg)

**Comment by Bershcomp** [comment]
I suggest deported sea units to land into the sea tile (or even lake tile) where it is possible to build a go-to route to go there usual way

**Comment by ArchDuque-Pancake** [comment]
Easiest fix, I think, is to not let ships tp to lakes, only sea

**Comment by logicminimal** [comment]
> Easiest fix, I think, is to not let ships tp to lakes, only sea

ships can get into lakes in civ5, the lakes is group of sea tiles that are smaller than 10 and are grouped together

**Comment by ArchDuque-Pancake** [comment]
Yes I now.

What I said was that, when teleporting, the game avoids telepoting water units to lakes

**Comment by Bershcomp** [comment]
> Yes I now.
> 
> What I said was that, when teleporting, the game avoids telepoting water units to lakes

This will not prevent ships jumping from one water to another over the land - jump may happen from sea to sea

**Comment by ArchDuque-Pancake** [comment]
I know, but its more likely in general that oceans are connected, and almost always lakes are not connected to the sea.
So, what do you prefer? Your ship to be teleported to other ocean, or to a lake and be useless for ever?

**Comment by logicminimal** [comment]
> I know, but its more likely in general that oceans are connected, and almost always lakes are not connected to the sea.
always
if it is comnected to a sea then it is not a lake

**Comment by Bershcomp** [comment]
And also one sea may be not connected to another sea or connected through the aquatory of the foreign civilization with not open borders

**Comment by Bershcomp** [comment]
> always
> if it is comnected to a sea then it is not a lake

The opposite example. Lake is connected with sea. Through the city, but it is connected

![Screenshot_2021-08-20-23-58-32-367_com unciv app](https://user-images.githubusercontent.com/86048557/130292721-8a7bb651-459c-416d-b4be-b15792a11f3b.jpg)

**Comment by AdityaMH** [comment]
To fix it:
1. Teleport it to nearest /adjacent tiles.
2. add notification 5, uh i mean 1 turns before ended.

**Comment by logicminimal** [comment]
i would do it if i knew to code for the project :/

**Comment by JackRainy** [comment]
> Submarine was in neighbours aquatory when open borders treaty was on. After open borders is finished, submarine was automatically moved out of the borders, which is expected. But in result it was placed to the lake which is not connected to the sea

That's an absolutely expected behaviour while it has been русский военный корабль.
Jokes aside, I have a fix for that in PR #6698 .
