### ISSUE TITLE
AI cities have the same name multiple times

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#493]

**Comment by yairm210** [comment]
Under what circumstances does this happen?

**Comment by flecheapolinienne** [comment]
Nothing in particular, I dont think... 
![screenshot 2019-03-02 at 17 41 11](https://user-images.githubusercontent.com/45007481/53688482-9d57e680-3d12-11e9-90aa-1ac3a7f2eb4a.png)

**Comment by Am-per-Sand** [comment]
May be this happens for the same reason:
- found a city
- change its name to anything not in the cities lists
- found another one
- see it receive the name you changed previously

**Comment by yairm210** [comment]
> May be this happens for the same reason:
> 
> * found a city
> * change its name to anything not in the cities lists
> * found another one
> * see it receive the name you changed previously

This only happens in really old versions, this was fixed quite a while ago

@flecheapolinienne what version are you using?

**Comment by ninjatao** [comment]
I believe it is caused by save & load error, refreshing city name index. It will also cause eliminated civs displayed in diplomacy screen.

**Comment by yairm210** [comment]
Probably solved by @ninjatao, if encountered after 2.13.13 reopen this
