### ISSUE TITLE
Suggestion: add an option to locate json errors on mods

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4934]
the explanation is clear enough, hope doesnt get tagged wontfix

edit: i think there are json linting tools, can we integrate it into the game?

**Comment by ravignir** [comment]
It will be taged isfix, just get a pc and run command prompt.

**Comment by logicminimal** [comment]
> It will be tagged isfix, just get a pc and run command prompt.

?

**Comment by ravignir** [comment]
You run unciv through command prompt: locate to unciv directory, run:

>java -jar unciv.jar
>

You need to have JRE installed obviously. If there are errors it will display "error when loading myModName" and the line in which the error occurs. It displays one error at a time tho.

**Comment by logicminimal** [comment]
> You run unciv through command prompt: locate to unciv directory, run:
> 
> >java -jar unciv.jar
> >
> 
> You need to have JRE installed obviously. If there are errors it will display "error when loading myModName" and the line in which the error occurs. It displays one error at a time tho.

then its better, if that already exists in game we can just add a log in game that shows exactly these, no need to make something specific to pc just so

**Comment by yairm210** [comment]
Already exists in game.
I think I put it in options - check mod errors

**Comment by logicminimal** [comment]
> Already exists in game.
> I think I put it in options - check mod errors

nope. when jsons are broken the mod doesnt even show up in installed mods. (actually, an euroka moment: could that deleting mods completely breaks local modding thing be caused by something that makes the jsons malfunction) when i try to locate mod errors with my installed from mod browser mod that doesnt show up it shows no problems found. definitely not solved

**Comment by yairm210** [comment]
If the json is broken then we can't locate errors since it's unreadable.
The solvable parts are solved.

**Comment by logicminimal** [comment]
> If the json is broken then we can't locate errors since it's unreadable.
> The solvable parts are solved.

im talking about most of the time missing a comma, missing a paranthesis (any kind) etc

**Comment by yairm210** [comment]
Exactly
That's not something we can find through code, since the code assumes a *valid* json to be able to read it.

**Comment by ravignir** [comment]
And these can be found when you run the game via the command prompt.

**Comment by logicminimal** [comment]
> And these can be found when you run the game via the command prompt.

so it should be integrated right into the game as it probably wouldnt require extra code other than ui
