### ISSUE TITLE
Promotions are not granted upon upgrade

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#4947]
When you upgrade an unit to an upgraded version which has free promotions, these are not added to your unit after an upgrade. 

Example: chu-ko-nu upgraded from composite bowman does not have logistics.

Version: 3.16.4p2

H4sIAAAAAAAAAOV9XZPbRpLtX+m7z4QvC9/oN1kzY/uGNdJampgb4dADmkSrOWaTvSRbtkah/74ggUKdAjLBA7K9LzvjsNlkIasqKzMr82RW4eti9Xm1Xv27PKy2m/3tr1/rv/9ePla335e7u3K3Kjf7WfXH03q7q5YfVuvq2OSP2yCefbkNom+z4+f8+DltPpv58Y+s+SM7fk6az+nxc9x8jo6f8+ZzAe2NgR9SeDiBhzPoLceH5/BwQ6mALnJsVWArMwdibSen6YVtqxh7SQfEEngkhwmmMI8I5mH7MxkMJe6PN8EhWuYm2HmKM8kGM0HWRTAsXJsY55HidHPsscAebScFPmOQRTgX403ZGyVw8vRIAoM3IfwRAYuQqSHMMIPvC+zMNB1EXQenEXkMRZp2cEm/gxwGgSyMsLMQ+Rm7qaXIQI9NKXSByx/jmAxyOcGhW1oZDDHr8wP7QGGNgceojQXOopNWg0PJgT3FQPR8At7oLYsGA0Ze44JkKBVzj3DoGBzjUAz+gf0hg9F2oZDETkiSbx9nn7brZbV59am2e1/3h6MR/LF8elptqv3+Nk7rCXzaVeXhXbV9Wle3X9s/dvvt5t12tTnUD337Nnso93/9XO3e/r6plm93q0+rTbl+XT6tDuX69r5c76vZ03a9WqyOfXyb/ddztT+8KTflp2p3/HtXretHthv86nm12cPfh2rxcPv1+O/9L9W+KneLh2p5++vr2qAfds+Lo2Wf/WVXPpY35WZ5825bHXZfZq/LdbVZlrvZ26fDarGfvSkPD9Vj2X6uZ1C3+XG721d35eK3m19Wy9Xm0+zNanP8z1839SSqanf8/GF3Ysin2fe77ebf1c0/t7vfjn++L+tt5fj7Q/3dQ1WtZ6+O4zr2/LzbVZvFl9m77eFw/OLVZvVYrm9+fN7f1QOsv/jnbnU4Pvvq0261eF4fnnfV7KeafEf83cNqvd1vnx6+fPw2+7xa1CvzxTGkXsJFTaBqtrPDF2REzeO759X68H39r+OU6jZvtpvnx2pzmL0r1+Wimv39tBfWA3q9Xa+rT1X9/VO1u3lT/lbtPs4WQOw/n6vn6vbXv28PDzWp+rfTzA7Y30/7f+yr3fvqcFt/U6/0brtsfnhbi8T9evv7UeKOg3x/KE/yctxt6023bnH7tZ37+5Pg3Ya1LtxvnzfHYb9efb59XXdazlbL2zLK79MiyYNleFcF8V11FxTLxASRMVkWV8t5ni9mq31f9k4DWm8Xp+ne1lJvrcLmtP9Xq38dWf20fXpet03gc+Qks/5+V+tDPdB6/Mfltj/cbO9v6r9/rnm4WYZZPZ91WevNv8rP5XfrcvPpu582h/q33exzua75GM3n3+q1O3ReBlgp8Dci923orAXsCLD7Rs7mwUYY976N3cew1vnfayFDZwf6BiJt3x8bYZsgY3+mLBlWlkysyNKyKu/zIr0L7qOkCGJznwZ31bII5lF8X2bzu4WJS09orKd1Epr3D/WyPpQrT2rut9tl221U4C/xy8tQ7MuQ2zRC8DZgLwGPE7wj3KrAkwztx+4buyl+nNW83bxa/Nfz6qSpPRly/UEnwoimCtMPu9rm1fbyzxWqSBcqTYiyapGEeVV7PGUtRMtqHtylpgzu86WJ0iS7y5Y9IToxw7RS9MNzvbD/ftg+a2IUzmf/w6aoG2D3uZWO9j9zZxian9vPBppGzsuwlAx+7ktRMbBEJho+1vb8sX662fReH52Qo67NbCjXrMswinPWEOwiGNnQWdbGREJAB0Ff2rlNWedl553Xexpg5jgDHr/VwSOBlpHhsbWJuzGE7sECHjTwYAQPOqMed0MbGPog8QacdgPO3IBzN/XETd01DWBGdhqxm0YzshhGlsJn6KcAMgbIREAmgUdb7mXdDHJvrpGjnDjKqSOcObo5kG1mEDemDQULFrv51TjbZRyPQH7C7mPYNW09ctShtJt8MwLTrVLU8dvNsB0HBqqwFUMsm7uZz93MQzfz2Ilg6mbejAECigKaGGgSOf43H50KgLaE3VgiRzJxJEEYQI6c1LdMijrWQRzcmBcnvq1j0vEkRGem4w4Ihg1M5y7aCd3wXLh6GmnmRgryUjgutFN1o3TrH7ixgxo7UUFrCvLeTs2NfWhiXcenb4HJsaMDagMu4tCEp/5QfLsOSlU4lW4+g2Fx0ovKY4fovgIJQ6opfM7gs2MriAEoUEMOmp4+FkBh3n0dzuFra2ock8H4OLGBL+1kClCUAjQCdds47hin/tg6AlsW9cacudYx0EtdazsV0zOmyHscSg6foSNgWepahI5luBZF920B1AA4sFNLYPIgWjkMJO8NJHE94sxCIA6whB1sDpxI3GhxfQ2MCzQugiGCojZUcvgMY0wd8RCIx0AxdU/acUXAxRn41FHHx6Dva9uPCcwjd/MIBqxx65W5gTm/2s7/1A2ukVMeu5nnbkYBPmrcqkcwqgSa5MBSR8VJWcMt5ApOMwYisLrIudwNCz5C/ACyBRKaQlsXsjhhdkMOYD1gsk6oAsBPUZDn0AVEVRhgYRsDIlsAGRBZ1ycO37aAxvB10NdHp90BCKbtPXdL0LolEO1Br8ePzjmFhiEQgIfcMwGSR51x0MVJeEAsAaQ+kQSlB6nImiGBOkBAaUXJaYP7PTDuaSefYGOdHQpAr4F7oGBWGvKO1da596PaxmvMHStcY4i7jfMarAJkvgLE8K0jAcF4506CLEPYcKThQhsvkAKjgL2AcCbu69DBCSDhiaMM9qPlUYgq0D1ov/M1JXFPJyidbguFSTjyp99tO99CwTo5G44YllUgjEEcEt7l6joRB9AtcNFF4HSuY6r9DQIjMHepW2z3LBDEtenmnYJUZG4h3X6CdgT8O4B4Cjfewg1vGK/jRu7ikqZXSGQCvgS4Tub4k7mu7cI3Spi5bhwbbCjmekn6UwZha8WiW1fY02CLhPRf+0QMc4uAzy6abLpy47KL0kzAWZkAbGB4+rH9zTEAsFqQKScamFuDBKprkDs+zN2SgpvqYj9rPea+qqJSOkPvwjTkrxOKwvXrYl1reF0DWBSUF6AOUXs7g84F7HTebbYAjYCjgohCp9bhzHveip2jFQCxwD5nn4YlznpMQDmB4MZuVE5yYHAoT7A4OHn4uugehH3Agf3tJgqwO+gRqB+kB1I34+ZpCE2sXMROLgxATQ4P6a8R7PxuLE7RsYusIwVygZ44mBgXz1lmAn4FWeyGMrAQcaei40jScQG4lDguuVDVAVvtLGFdDCBVTSzsjFEA8uQMl93pAdZyfl3RzblwUwZEBew35L/Rk+5DXtibU9PGxThOAbQcnEVnq9BVbFXCLS8kj9zu6L50A3WL5HQn68aOY5zDYkHob520bgfsenc2IwAE0nUTAOuhwMMtPxawYC9ufAWMD2APL0wEKwaeBCIPuCoY7LpVcSIHlh4gE8BkAOvJ3aRAnR3HXVPARlCfAWmybEavMgX9jx1jnN3HWAQRP4fFeQB+6NgFJQYNaWARWJ+aRU1ZwW0c5159web58a7avb3/wX1nZv2igyK5uubglOfZlIfnXbn+53azrJ895pSeN4ebvz3/a/VxttkeVverRVcSVi6aDEyTM1lsH7973ixWn79bbz+tFt9hAdl3H6rFw6um4uBYj3BKP7wpFw/14Hdfvs1WixPFYyrpp+PH//t+sao2i2rWtflYP/fH4fY/bCHDMXHzq/v1pp7YTT2CeuqHavl//qPm64TR/dymnNoR2gwUpnh8OOujMOTXTSLVDvTXLlvVDO6UHVtWy5vVYX9zt90d2VuP8+PsaV1+qXYfvjxVtz8+P5YbqPpoFrklfBuH0QVlIPXsD68ftvtq80v1e7lb1mO+31XVUZhmxw922LZcZNum99oVOIpa8+nt/c81qfzD8+447zCdSf98nL1guckPx9SmqzrpVvt/Z/2JmMF9Xx0O62N2d7V5t9t+OiY5e1TbFrXxmtu88G0Yf6MLAhI/l/tDLTK1Xq7qX+7SOFyEiyBZxvdBbO7yoF6SIqgW+XKemawM7+dMdUnQJgJOKd5X9epv9lp+1+AP4cund8N+eteO7WtbKgbVYVDxBrV+XaWf/S+4Fy6JETgXKCjgqdYZGZaaBOgdtn1eWBQgitHPq7vd6TdVjNoWx02VFp25JjqVCedJdJcG6fIuCuLqbhEUyf0iiEy0WC7KYxmA8WXE2Bx0U07yVO4OpVpMYv6nqwDc8NwfMf7hlQxbLAdLnw3moTFUCjAOb5t5fyT98oBYkJ5IHYSlMSgTCLsygXbdhGpvBx65zJVXAg79RqgdnccWwNdAA1TFeZLdvJuEnYVRGxXz2O1VnUoV6AZwRq8EHUvTDUKGLWHjDSHyhuC80X65wUhBugcCtp2EXiex1wkW7Q7KFgLXeeDcy8DVMARQxOBV0kMZAzzY9ukxrWPBfMgdf4ESaOjVo9sZgUnrtMS3cliIDiXKoZtAgyciVNk2gzliTa9X2u4ttFfnLpX1h37hM9aUh15Js6ekWEPv4EKvzj7vLUSMw/LKwr0a/w6+wbLnwOHSAZQ69Krvvfrx9nk7YCxfh5DGq613UU/g8s24F0LhQsdYLDrHAn7fIAEe6BXM+6X3SNITzwRppsBrXA+gONzcDdadQxo0cJlSdAugeMEuD1bBY/TQM/lQuOD7Dj0p8ey2tVNIEI7SGOi1GwGsH/4eeHbGDrHwzGmBmpwgBc/D8YYIh1rQVoQeydT7yzuvADz2zG03XOCy8cjMvb8MDAqWufsaWIxNA3+g/l8o3v4BhpZHw2Yd8UaZcu+vAqlnSCL2qKf4VOifvUDT7hln78CDd3CoGwWegRIWpvAGG0E7lzTunvDTrp64Jd4Q8KEchwNlFLMOg2mH4o9fOmPSjtLzqGw/UERhf0HD6nHKX1fPSPlL6flQOAfjz9tb5BS78h1/z/3rOJR4Sx7B2KHkof3BP12FsGbo8RtXUjhkB0UOtkfM1Hv+Z48yBDhIWDp/11LGUfpr55J83Q/5QJalw3x+cUEEw4QSJNsLFnaAEudej764Ql7dpfebZKjf0qWeTZtgRx0HffBOHnrKDg9448a5+qMbFlX0zuvh4SY8rwelEr2je/hD/5SmJ6fesbDM688tAGQ1XepYKIsYVlpA3VCAtRBQNeHLLSTLux9c2YB/0M90XvqXYb0EAMcBfsZTed5BvAJ6gcRmBwz35dBjFi4uTsFl97DYB4YFeVJgOIi4/Zh5NjADC+aKI6BOIsCSiACqJvzINUI+Y4Fubx5egQNWNUR91raLCsIaAR1PJl0S2ecskk5wbMOCAigzgJjArxHBs7zwGUpZIENhJRnqGwJLzqlOBuYOS+A8XQTXG9ckxKlCCG7QDUu8jprE2KAUQS5bCGIceob2F00vbMgScAE1BgHWHpj+6ereUHExnKqDwIPgAdshXdQJGSw2eMSgJUrFAp7a7nXTrn+vR/EktysLgAqBnguBsgLRFVYWyAe7oRzA1QBAsh8jI6gX8A5+uwfFMgG3++D56cC3thA0eYuNE/MW3gu5wMYjQgD6DsIEIgPBNRxvhkPECAcBmxod9Py7zs0KUfq8o+fGw5u8ZcAaBIg/e2OEXK2rDEBIxoeGhBPsHhgMJQSB59wZRKUCV35gCSODLC08I942K2DkaPqckEF0CNPAs/093nlsdcVMyAP7NIAxrsIASheg7sBSz2DArlIHbRVsJoDYFDgqVBYDE/EE1tWnYNElYFFgskGKobigRbyQPSiswBGAMkA1AcjA4KrtCybk3UxhfCn3gvfO0qe4VGjKEYbA/RXhHZAjN2I3Db82we8RD/ZjOONHth6O0YvRfPfekfPBL8sRD/FNUeQBXHIlBr0bKfDSCrj+AW+FAEEFTUFGuQojBJDEWw3sjH2420PYQtgU4EyUhwN6XPYRXctMvBkBSxssBcQxQENAi3qL5O0f/mi60ocwScavVgiNVObwQ7WpduW6rXOo4+w/ofjBZeXL5fbpUC3f2S9+/XG72e5mb3efys3q39Xy5pc2rTT7Z7nbrba7m9fb5bGUYbMsD9XN2/ubH6vyc7WZvVtVhy8fZ7a+41WPbjLz8/8mKl4m//+vmiXHjHW1mz1vVod/PH3alUtXASDm+/OZ9/82z/9Tly68/fru4ct+tdjfRum3YRHAm+pwvDihJnhMk//vuIGi4cKHreXD7a8ti8TagO4Q9rtTPUh7OHe5ur8/dfTltk3kzz6Vj9VPtaqEi+X8LiyCZZWnQVwvYHAXZWGtZ3mU30XmbrGITm3flTWDq8NRoL8q5N4/VfUi/efzavFbJ42v2xxvLYjztkblVLdwEiV3qrtfvVLrdT2V/aHcHfn01115+6ZarqrPNRdrFW2Spm/Kp9uvj+UTjqz+832tPLdfH6rVp4fDbVg0qd7j08+Ps1pAV8/746m931fLw8NtXBvA/XHQJg2L1ORZEdb/1Bx/fKq7OS7LX/847KrH6mQ25t8lxel/aTOAn1f7Qz2Xu3Jffah2u3K1uf1hV+7363qR6wng9/VqrE4FCfuVS0a31vDQtPlbdeqw5s7/e958Wh8V6RyJdpceEPhxtV6ffbzpvG6/fd4tqtt/7Gqz8/zYe6qbj/fgxX3+QT8qdfzHFHYpBFrP6fxAG7+q1+7n8rdKWkWGoJEISqsSKiya/a024/sDsbAaBVKkRC5Lz582tvrDkCOG4XC/jbZk5GoN+hwTART917WZ3m64h60LO+APuTido9/1/tPn7bF28ay5aKNYjheDdvpSDWn+pd5pdoeBWEizJqVC6kVsxszPYi9XiigrVsEUubrCMjJTp9Y/mqALkThBhSirsJG2QLSO2OiQ6q8J/iYMLUbt241o/mPt4dUuyJd/1O7t7deTI/Fu9Vt1rK7d1t7/ztY0Pe22j9u2wu3/v6vjs28D3sVXGvU/OvSSk9oX6M+w/bUJgY6nf6k954sXv1mfS10a9lHRLMjWUGONZA6nuCKyJzJiW8i2tErb8pvL1ZQRDkqC4mtHYitsuK5ewDYxu0fc2+nrKLE8cOttK2DIYQo7tgXVqP4aJI0gaqGobk6v1s+Pq80gblC4MehDE0uvj1OUvuf2qOTyDbjLb1wuGyE7RyMujmJbL55Tj4+Up8lNwPT30fcPVfV0Oev7W8hPm0W12Ve8IWWdU23dB2Z/xLheZz5ET0rRl+vggbbU8HxDScD4Xhh5SRQDP6GXftT2vo7ZOAFJJviuCWvcE15oukpeUmr0WVzsGdlBDDZjyci3KRhqVG02xsXS5REPZLenQSdCy6TXg7gbqHvVoAdF01KSswICFE1gV5P5P08znEAznDB8DVZrkymX66e5chBK/+Q2l17kkRhtv5+yayVnHDwNVRhooiIFZGQbibHLSBTMbph6zP0CIX74UlGjuyjvKvvIbJakVori/Kbc7R+IwaST4iFtABPAq3TCFplOCFxTRdJYRtiTNyRE0x7Wrtl0WN1/uQltMuzN9vMxiXOoVa89+VeVOwfjtDkoH8U5HVHszyW+EDa2JzauULlUiQT4iDCdYu8kAm09xvmWTbUGOySmZcpSTFiKbeWU8yfLdd92CyY5FskrTkV2pVMx6Ee3/WxXatxL9hVK6zDmVVwxMCP1JQW5TCNmzVQ3SNaxDkT0Cj5uXbnHkB2MO6rCEHywxOIQkeiJyDmTaNwZWT3W9rO1sq/Lx6ehuxBduNmPQGQMWGtrYsFul2vSH2ACwSnbbHu4jmrLapmkYLTX1J5kuyCotifeuLlMcC+yCe5FNiEIzyZ4yFl/q5ei2rF+SK89Y/FCW17YjeiH6nF/jTeR9aLqt6s16aWpjkF6GRwo0WuLTamZNBWu7CCZlm0J5cWjT9mO0ukd9fzdw6Fc/Lb/8LDaHwvs6g2sjkDXh4fbPG8c3R+3T3X7ajRdWfT83K5Ie9QqKB7VYNqaD8Xwpz0R4Vnuq3COaIJcRf3OJ9gAey/EpZ5PyMq0ubIj05vk0axwaA3FRV68NW8sO2ejeKfITHeTR52asG/0plTyMI5gxCaJ7EmGfjHfdA/Lm/Dq8OVmUX+qXbWBM3fcHbfl8lja+by//aX+SDmRYq2GwOz6q/rp42NDXy66MAafgNhPgTjs1RWXirm9OUB8XinXGHE9roWNWIVVhjBh0zYCaHuly2Auc0H0MbLrqo4oHEcY9J7PSrna5eQ6vYdy//2xh8efq/vDL6vPtadwOsfQfQ/f9YfJFl7ZA5oX7OXCRPMJWXHRcWreQbh77lwjeB8xukd918geRr5SrC5OddghMImznIJPLEWqpb2z44XS/s1FHaxcD1oKFHOWYtafSR3r3DGJy/Z00nXBATPE9qjlJawWfO6E7TbpdSsUSKrJVnzueDPozdsdwdG436NY+yF1GomT0t15ad14+DzsT3FCuo8cpH2TCtXYsHRZkrpgT3JDzIQgK+gHINf5+DKSrfng2QviKfZ0/8VmXawMGEm+XpO3jielkq5Ntr3ePp56r26+3/4+lnTrbbZywYocVyS8KyJnFGWyKR8y2DvWLtMfiH3gMOSb1aYabluqT3q6wHP/YfsTBFIRt2dOzZx7sVq5Px1gHOzY6I2LVTsyJwsedCE8108PU1xayskoJBC/3TH+hBFNWR6FoyNSo4jmMDjoD3w4yEHAfHWEUUj6J+3N9pKfiUyiJtdewXSxx1eIduyMvPQHIJrr9Xa7vHk6CSg9kOTFUPpiQiCj7P4FG8sUve1aPq2qhiwS7DflrEahAPUyDZX3+VkvV8Qt7W0bBGRqr/642DXorkK80twcSUwvCs3V3t+W+xUj5O1tGlNSmFJ3tMeZif21A8Nd8tXmeB/C4eZ0rYIQElLrm471Noz3KJqJJjK8cMdyZ0qsx00gomlGU2R+9EwwzwW9OIYWPvMiXZozXY47au0Ixr20Act72n3GtWNSCvY+TxdaHz3f8QSDluK5OIbFgf6t3D0OI8tBUKtFltNB9HMOtb1jbdymaoElWUtibxu7KrBMx8Ej/XADe1jN3lPlCQsf+lGHFlPF55uimnLBiVbdQYaZw6TC86dSKKUaK7BlNNLeTe6DXWdUUncHxADmnEJeFzNdd7MKbcV5t0zZyppXSJWbBlRRMJT2niW1jKOmzUII3aXeA6h2AqwQk5OeGHVOCIrclfGUtbo6FG3v058cJp+VVXuBP7U16F6kfSPBxWGqfUvCxbiGzrZras7tKzbON7XvqRjF51U1FiNRxeeaK5Ukk24ism+S4bvML9nz3ItiuD1ipP+JnpUey75ImgHeFDDGFcky2YvIyR1pJCgn61+792G6bftptaiEjAM/gmLKANrXCbDJ4OuYk4udjcbgE+qIacrpFMqpSFmPrC+7Oq173TMdVDNN475wSYZPj7GltRbhlus3u2jK+oXq6Ni65HCgdbKzPAakqrc3UEtjBiO4riqJ63ecyb7D2WbxXj3Xq1YeKi2J5zmgYupO9j8HgbSDPc4nq7SKV9Y7D7XNhj5+OCF3L9cWaxE5mR+Xj5vptZWkOyEfvtdTqxMuAxi6anpqlQz45RMVMtlMSgRrSU82YfR6W+4FpNq/26dcM3fU2LccTLQAvs5u2vcploeb9s7i0cjwz8lJkuWxXbg5Ofwf+luMA+NZ2w+75/v7teRnXeJuXpJ/MtodredihdHSc3d3fzeiKSfqpI3KjFUWMHZZvgj1+rjbjMbdwhio+yz7Fw6xLpMZ3HzUAGOTfIp+TD2WfTbaDVBTs79GvnNqAuRiplzyIfpN9oDt9CyomXJ6YzRgpA4Cm0kJ39H+yJ3e0OV8HWWmVsXY93e9XMA9kdiH581yV/Yo2VdGnG9r7Ju8OplRLngR+zF8P/b9dqQNFbvr3rFwkVkeww6Yk8jubYCXx+4F3Vkus1bDA/hRjQIF012nAX7wsssTpDIfRmAGir3JC0w30Rg/EbWL5SlqUMQ1bkQ00CClkPyFwAhqLRRrJTohIU1VsU0ainCNKPR5OlaQIxb5/rV5a/vF9+l8++aN5kq55vGXYAjArNa1NPDwgV/IRB9a0sSIyhfal7Beq7famQdywPI5bR18YMAP++qy62xu8gIJmCm3HLbvzuLRCuEwLr/LXXX3iz1od7GU5hPyiBrAcQWwIpb8aull+oxum4zmPfGXPUpqX69HTOtqP4nbUaa8rEC0q1NejWDfI39lb9quysXR7bsaLw9eR+8Zvr6gwYQ9SOKCZIXOO+biVyNeG6XTlOzUWJ0uv07iHVwXzZu4GXTqGmV/QkKJPrhmtPLCCfdg0LWMZtLRxVDEJEYswrVFu2booLFXxRubGrwS4ZmYoxRBgybkwWTC21X/gjIJsGjfks3DLUxbE/JUDU/V8FTnMlW1rI69/6uQ6Q7PShdTqOYy1ZFbL7yLHVa1iRGyE7wyd+/8vnRfs++jvXhfTOn1SqcwNhloxbQ7QkYQEXYI8ShvJ2Gn8ZR+I7XfUbmg8A6eqnoEnpaWKbmfadCNbKTUC7KopmagnFfdNjaFUVIBByksFkTqX2Rxha8tAlhjCMk1ccSgREdKxImQg3JASMNBrjvmNbje4sr3ncQjyAwP8NiL+q5zYhLFoyTnYt9vjQjbby+AqV+X7MumoDuZFnJMqXi87s1BgXal0aTMjQj88M6EdtJ50oG0tpydKcKQ6QqgkFx8PwbfcAh8W/RwLkKceJht8ILR4zGoi47OBEZ8sankC0fnoiCth6s8Avve9pHQRdxj6JfUmTMvnhw9tNf2Q72dd8o7MURZkt/A0ffNpla/jL07kh/W9W+DNFNerqaK2kyqQNF6Y67IbGnSZw6vWgd2R9IlPntJUNlEIxv3lDMZdOWqiSQ8SKc5aKrCGPOXRdsV31DtfnhTzUv0P7Bvav9eScIX/lzICJ7Ur3JgnmwCXtbcSLM5xbkDrHlkmPHFAf77zfZ3gZVc5+Gg87897/o75rCHsOlh/GbsEayMGVyDlbH3arZwGdm8QcxY2sUU0kXLmivcz3ywKKIjI/AsF6el42VM00yb0DRgrH/nKQmTsWuUTFLZEVCM7XCajRhBw64jEUSj45gEzsl2Qy8EGmHVdYjWxOO75PUyRuUUe6mO0QY3lufqh3Ei5yTk68zr2bWb4mm0TYovRTxx2FApBFOBrUmv7J54B7gKdLFvwfYzZ9M2Xw3TmlocrIFaV1QtBckItnZeFuSXd2j2Pe/7rTw4Rb/fZ8Zd4yzfCz2StroK8bJ3yV28Ss2ldmSSjy5o0rAj1j+SD5BIVMVjKVqmeQhBSCTDcahj4OsOARSJaovQDNj36rBl+De02VInRCMjvo1ajJXtq6871VJqgCV2918rKvhcmiutvtSUvzYmVlCkSae9tCt5TPcaNRJKvBjtaF7TccFlU6Z9OQg10e7O/Ztqsygfn45f9sqPtSuFy0P59Lw+TLq838SSyVGu4FqL7x9p55f0sh2kYFx1dEp+m/W0a1rNmSPCFO/frX6rXKm3/EqpZFZ7EnfV7u39O/eDwVa//mVXz/zmp4+9RWonOvE9PRe73UasWx41EBNTZVRZ2Vg6kMJ8YhpuG/XSWHxLufBR7W9g9oU3FBjlwguV6MSDLXqX1PGwuF8eMOXo0AjadlnFgUiwwQJ6xml42GEIa50AANaZG5mLRkJZkeFA4mYgPHx44W3GCnbI9RyOzpVBSUO+M9N2xuKGHkOG7xsaqbgjL2NoIET+iILUYzFYOyHOFx4s+jOUj1ZIXeaDLgVQfKRq75pQJ5P5q2GOE7Vo9Fgi02n6cp0mqmpMuGss6a/yte/mCHTrNKkAiBYCIUKKpuhY1OeA6H8LvYRyLzKQxbQLzEBv3lXlbt3H5IVwT+zh7aIq0aWmhssNVcmwaGifl/tZ7R/Oi4BSRK0sA9Owy9RdGpwHg+whuTqKryX0IPtvw4b8heNBe+M4pQqphgbKmis4ec17tM6OP9N8e3EpRrC6/gtrSeSOhQPZt7q1r1a4thxsEHEKiiff0KlBcYwqGxFF6BsP6x8x4JM9vDWm8xL9UIL5BPpyoZFEUSxoUuCyIcInURSBtWHD89b4D8kaS4SkDqX1TkiU8tQwHF8dlT7DzAnvfm2p9uMyJuUnB/fNu6muPWmUTIHBFdc9GQfA/tybqMXXRJlkgKeNRHHMnYEjU+cKypKrDadpj6dfEpnqgT13C6ARX8KuU9UyXRdDx4m03er9D5rqs6LwJmtz5uORnhQ/t1ezTg1KbY/4pFBMpPbInose6ZoCsJI+gPUiaBN1+q8tMLm6s2uygE08PDABQyToFA5jQemwpFnf6iS78dNiYDQUCC71VufpaUrVHptcUEC3AWNGQDfGJ4xEolrWU6Cp4mYUUWN5Ms2jaDA0jhfzQRfaaU4aE26wNSQ5pRhVuUyD423R71kwYco1qFwHOc3ZTJVnujoh68+Gr80IFEOhAWes3gnMSwYSJEbv4o6YsKoQDzoZ2jMN72LnJsQRtKWI+ksl3qQr9KDYjWFL2WpIsQ9LUbYSErZFNGI7pEKzQIbdtEo2L8e/K+84rjMg2/BSAy7gli81GDZUMncagEVE5taLYwEsIqy1L/abfk100L7pb8LRtAGYdeYt7lqmggfbhhPOxZBiBMliCu2KKfBYIcFjGmY12T8I2nfMnFdY+bJdDcFiQBf5Gh8NsyIaKifWNMyKaGgrqEjMimioIEgicEWiYNROwCxxyqJgjRmYagpPj9H3m6UN588cnVB6oQoe0z4qxsRFJpVkcfgeuvE3lrXv7evXNUxAiUIOJWpeSjDIL19zrtu0L0W4OH1smrsHz786aMINUKmGcfHnQbUj+nwVgLE3B5CjkJGhlMa7Riu7ufo5MZekd1YMRJZTGBLp6tyLKyLOtA96sWcFlbcrqX2Ek2NLo9ysrHYxMGMDrMPSpFAr+RyWSvPMsRUFaKLSZkoth7RxNcEz4wGdYuRBQ3EzpGmmIk0dLhs0VYAxD0wXjlyKJen0qGNx1MJCRy3JMyidUl026GGkuoxgTHgpYwzNGEMv51ymqWJcDNGCplnQ7M3tCl5uMnN2/IoqCiSz/lJOO4wl9J0OJFXwOUeuqGfrrwVzoWi2XDFCGSBak2VFVtEpoqWsuCoaRbQMabPLUpS1VEKjiEZsh1SIFHBAmUWjmA1OLlyTF06oBtMQJ6KhLdcmESel4eaoTeX6n9vNssmfl4eb78vdblXtbn6pqnsBkmJjQDWbKJu2C8aj+HyK/WEaZgOEjKvFOxlX77mJoZqCXbGX3eZXAmVFE4tMTDIWUqyjgVuSCWfLCu0bjscTExrsRVkGQwJpIQ2kibdXa7AXBaRFJJAW00BaTAJpcmGTBnsxQFpKA2kiriVQpDYxZjvJuA5tcENSpI7cZn3YjMqCnB6jQLOMlAwjvrdSpchUPGaSOqgUJYCKPSGcSaqs9sRUD4hn3lWK2bkEixSGtKW6operHHpQB8DgT6bNrXQjnXJPq9pzMb5zypBZxkNM3f588bZq5Hd2qzPiIKX2RV40UQpEUq/CnigOBBBl7O1CZ44yCSCEvcFo8qPGni4aRy/0aSVT02UmI/1/2wPVtInhBzonGNVTqE40tN0zNDOaZirT1GAzimZC00xEmjpQlo8vrlI2lo+Dntp9FMIUFNAsv0RcQ5pLIc15I9NUD2JSROc80XmfGwJQr4Jo+biHM+B90XZ26eakqKiGpnnTmnD9ocBSRZHlyJNaJFqN0/5UuIoXRaXlAhVqxDFLMWYpKjqr4GUMRUVFFbyMUibahFMUKWLc0GgkL+CgPIuXMbslW/ymnE/V8DKiob0okJNXpqFSca5UVnrFZ2RRoZJx1ACuMyeWhvQVD1dJHgwbDinmrYPO2WT/ZZZMqFuIqJiy0RSjgJagGHMxetJ2SkbV5Fd8axs6g06ENKQVkpCWfA22BkAxkJZ865IGQDGQVkJDWuLROg2AoiAtsfBJccU5SItEmLh9ho48+GCGpEhxLyf5fGpIrXDOglg5J1wtRUYMc04BWorM0eKcU9KWInUsJe+B5YJnrnbApOHFQlmVIhP2NOkLliJ1r9Rge+HiE0NvYE0PFJCUs9usyWkcyb7ufvpFGO1b384jO/ZdclNLOox8/bU+i/NFTcZeejO5usRetCM2Fd8t/n59PB37Im8WtwOfgCMxG7Zc8qHTpJo2kTmhhaeWTEPbPUMzp2lmNM2MppnSNFOaZiLT1KAxKXsrJjw0L4rrK6bHH9E0I5pmSNMMaZpGpqkCYcOcBw2MMQOfswNX9E3OzZupoUygqJ5cZ0ANmFY8Wu9otaO1TlE6BbxiKCqqpYBXDEVFsRTwiqGoqJUCXlFaRRtEiiJFjBsaDasFLOxNl8oFbK2ccthUA6+IhvbGOBK8IhraGww4nWIaKqXsit4zDZVcqWKbmIaKJ67YT6ZhIccLisFnGjabDaWlcy5uavZIOq3EAAryC+K1PZ/BtSIa1xJfxqahUFS0Lt7EraFQFKKQkLhWSuNa4sE4DYWikBmxKknxzTlci4SZuC2IDkX46IakSHGvYHGtgsW1ChbXKlhcq2BxLfHtFypFRlXEy/pUikwRlniUWqXIAFlN/eoVcVdB2lVTsAAXm98w7G5iRZ9BtApyz7M0WX2itvCWJqtRVN6tpcnqFIdZKa+h0/jJqxV1q2xB40nKZTva3CeARMx2XpDet6VJJelPnlFISP2pJdPQ2nHGLytomjlNM6dpZjTNjKaZ0jRTmmZC00xomjFNM6ZpRjTNiKYZyjQVfIujaWiahqZJ65Gh9YhWI1qLaCWidYhWIVqDaAWi9YdWH1p7aOWhdYdWHVpzFMWRwRpOxmkRpyhSxLih0dhawIFrFsFiy9zYujkOE2NPpNp730gEi2hoX+5AIlhEQ3txAolgEQ2V+nsNwSIa2rwviWARDWlfPmDjgzZdQm9FFCpmaFTMkKhYSKNiIYmKRTQqFpGomPyaNc1HYpz9hEbFxOu5NQyLwiPE25c0DIvCTMSTbxqGRdcrsUEoh4qRIBW3UbLBDzOyJp6ihkaiYm2ERlJkVrihSLQMxfeqqhSJlqH4egiVItEyJK/raykyNxXMSVQsnJO2KSRLW1uKTIKNTFO0FBmHh901rIjTWjNBbVi9oTbrliarOZRL0dJkdYdyfFqa0s3nwr3iWk+8UjFNwzmLiYX2kmySJq9Y1CmJOYuJhcpBLI0mr1zHpvUqna4kvI2Kb/8N40ehqRFPAQA=

**Comment by logicminimal** [comment]
also while we are at it, i think there should be a unqiue for promotions with name "loses promotion when the unit upgrades to a specific unit that doesnt automatically get it when freshly trained" 

which means blitz for cho no ku would only work for cho no kus, and it would lose it once upgraded and with this unique we can turn 33% forest jungle fight bonus for aztecs into a promotion this way

**Comment by ravignir** [comment]
That is why uniques exists. Uniques are not kept on the upgrade while promotions are. Another thing is some uniques should be made into promotions - one example is scout's "ignores terrain costs" which is kept on upgrade in civ5 or the jaguar's bonuses you have mentioned.

**Comment by logicminimal** [comment]
> That is why uniques exist. Uniques are not kept on the upgrade while promotions are. Another thing is some uniques should be made into promotions - one example is scout's "ignores terrain costs" which is kept on upgrade in civ5 or the jaguar's bonuses you have mentioned.

yep this is exactly what i said
