### ISSUE TITLE
Upgrade bug

### ISSUE THREAD

**Issue by Gettergg** [yairm210/Unciv#4952]
https://user-images.githubusercontent.com/89348826/130360066-c3c38fc3-25a9-417a-8ab6-f040678ddf87.mp4

**Comment by AdityaMH** [comment]
No bug description?

**Comment by xlenstra** [comment]
The problem is a crash after upgrading a unit? Which version are you on? This is most likely fixed in 3.16.6

**Comment by logicminimal** [comment]
> The problem is a crash after upgrading a unit? Which version are you on? This is most likely fixed in 3.16.6

seems like it is the problem i has

**Comment by yairm210** [comment]
Fixed in latest version
