### ISSUE TITLE
Crash when capturing a city

### ISSUE THREAD

**Issue by Dark-04** [yairm210/Unciv#4955]
**Version**
3.16.4-patch2
**Describe the bug**
When you capture a town and choose to raze / annex / transform it into a puppet town, the game crashes.

**To Reproduce**
1. Capture a city
2. Press annex / puppet / raze

**Comment by xlenstra** [comment]
Thanks for your report. This is a known bug, fixed in 3.16.6. You should be able to update in a few days.
