### ISSUE TITLE
Unciv stucks on first civ trying to play with several civs for a single player in multiplayer

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#4960]
Nobody was responding on Discord so I added an Issue here.

**Platform**
Android 11

**Version**
3.16.4-patch2

**Describe the bug**
Unciv stucks on first civ if you try to play with 2 civs in multiplayer.

**To Reproduce**
Just try to create a new multiplayer game with you having 2 random civs and start playing it. The game stucks when you press next move.

**Expected behavior**
When your first civs turn ends you wait for other players in the 2nd civs screen. Or when your the game shows the 2nd civ when that civs turn appear.

**Discord Discussion ScreenShots**
![on bugs channel](https://user-images.githubusercontent.com/46617994/130381576-d1ef3890-888c-4a62-94cf-aa720b74735e.jpg)

**Comment by touhidurrr** [comment]
@yairm210 in which version the update will rollout?

**Comment by xlenstra** [comment]
3.16.18
