### ISSUE TITLE
The stats of some things don't update properly until the next turn

### ISSUE THREAD

**Issue by ajustsomebody** [yairm210/Unciv#4963]
like when you capture a barbarian encampment then get culture food bonuses from a city state, you technically get all those benefits but it doesnt show up unless you open up overview, also growth in cities dont show up normslly most of the time, like due to poor happiness etc and will stay that way for happiness changes until the next turn. i can create a list of exact problems that i have encountered if anyone is willing to fix this. this is mostly due to mid turn stuff

List:

- [x] * Building a great improvement on a luxury, happiness doesnt update
- [x] * declaring war on a city state or lowering your influence on a city state with any means, therefore losing your gifted luxuries
- [x] * cutting a trade short (building something on the luxury/resource mid turn through anything
- [x] * somehow getting a resource to provide itself mid turn (manually expanding into a tile with a pasture)
- [x] * city growth that shows up right beside city name when not at the city window etc dont update when there is a difference in happiness
- [x] * doing a trade mid turn (current this is accepting a trade offer but it might expand into being able to trade in turn as this is how it is in the original game)
- [x] * Allying a city-state with luxuries you don't have
- [x] * Reassigning population in cities
- [x] * Conquering a city
- [x] * Annexing a previously puppeted city
- [x] * Spreading/removing religion ("[Stats] [in cities following this religion]")
- [x] * Choosing a free tech or policy that increases tile yields (e.g. Fertilizer)
- [x] * Using a great engineer to finish a construction early
- [x] * Disbanding units, selling buildings (increases gold/turn)
- [x] * Finding population in ancient ruins (increases population -> increases unhappiness -> "[amount]% [Stat] while the empire is happy"
- [ ] * Moving a military unit in/out of a city ("[Stats] [in all cities with a garrison]")
- [x] * Trade-routes (maybe only for Carthage founding a city #6904)?
- [x] * Start golden age mid-turn (for example using Great General), it updates only for capital

**Comment by yairm210** [comment]
A list would indeed help :)

**Comment by logicminimal** [comment]
> A list would indeed help :)

will do it tmr

**Comment by logicminimal** [comment]
Those are from what i remember and are not tested as i couldn't find time to

Most of those are mid turn resource differences:
* Building a great improvement on a luxury, happiness doesnt update
* declaring war on a city state or lowering your influence on a city state with any means, therefore losing your gifted luxuries
* cutting a trade short
* somehow getting a resource to provide itself mid turn (manually expanding into a tile with a pasture)
* city growth that shows up right beside city name when not at the city window etc dont update when there is a difference in happiness
* doing a trade mid turn (current this is accepting a trade offer but it might expand into being able to trade in turn as this is how it is in the original game)

**Comment by xlenstra** [comment]
To add to this list (also untested, so they might update already):
- Allying a city-state with luxuries you don't have
- Reassigning population in cities
- Conquering a city
- Annexing a previously puppeted city
- Spreading/removing religion ("[Stats] [in cities following this religion]")
- Choosing a free tech or policy that increases tile yields (e.g. Fertilizer)
- Using a great engineer to finish a construction early
- Disbanding units, selling buildings (increases gold/turn)
- Finding population in ancient ruins (increases population -> increases unhappiness -> "[amount]% [Stat] while the empire is happy"
- Moving a military unit in/out of a city ("[Stats] [in all cities with a garrison]")

**Comment by yairm210** [comment]
Nice catch with the population increase! We can add that to the addPopulation function :)

**Comment by yairm210** [comment]
All tech and policy finishing already triggers a recalculation of stats, but worth a check

**Comment by logicminimal** [comment]
maintenance for units eapecially, they almost never update mid turn when i make them move in or out of the city center
