### ISSUE TITLE
a major bug in unit rng prone to taking advantage of

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4964]
the rng for unit attacks chsnges every time you press your unit then your enemy, you can see hoe much damage it will do say in the first one you get 3 extra damage and the enemy gets 1 extra, you press on the enemy again and now you get 0 extra damage and the enemy is absolutely destroyed.

how to replicate:
1: press on a unit of yours
2: press on an unit that you can attack
3: press on that enemy unit repetitively
4: see that the foreseen hp's after attack change to however you want

**Comment by ravignir** [comment]
Nope. The visual just shows the approximate damage dealt, not the actual roll.

**Comment by ravignir** [comment]
You did not even care to check if that is the case, otherwise you would not report.

**Comment by logicminimal** [comment]
> You did not even care to check if that is the case, otherwise you would not report an imaginary bug

i did try it a few times and it seemed like a bug
