### ISSUE TITLE
Religion: city conversion notification on every load

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#4968]
While playing with religion enabled, every time I load a save file, I get a notification that my cities have converted to a new religion - regardless of how many turns ago the conversion occurred. Per Civ5 behavior, and per most common understandings of what a "notification" is, the notification should only appear on the first turn after the conversion happens.
![Screenshot_20210822-200627_UnCiv](https://user-images.githubusercontent.com/1423934/130471963-e6cc1ac7-c259-4748-8aad-024c99cde0a8.png)

**Comment by xlenstra** [comment]
Thanks for your report. This is a known bug that should be fixed starting from version 3.16.6. If you do have this problem in 3.16.6 or a later version, do please open a new issue.
