### ISSUE TITLE
Receive unique warrior replacement from ruins rather than warrior

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#4969]
I'm just going from memory here, but I believe that in Civ5, races such as Aztecs/Polynesians/etc received their unique warrior replacements from ruins reward, rather than the basic warrior unit. I find that to be the preferable behavior, since otherwise these races would be receiving a unit inferior to that which they could build themselves.

![Screenshot_20210813-171823_UnCiv](https://user-images.githubusercontent.com/1423934/130472362-da68609a-7179-4da8-a038-890032e5e2ee.png)

**Comment by ravignir** [comment]
First: update the game since warrior was removed from ruins reward pool.
Second: that reward does not exist in civ5 so your memory tricked you :D

**Comment by foolishgrunt** [comment]
Interesting.

I took that screenshot a little over a week ago and have upgraded since then, but did not see anything in the release notes. Since I always update promptly, this would have been taken in version 3.16.3. When was this reward removed?

**Comment by xlenstra** [comment]
The reward was removed in version 3.16.2, so your screenshot is probably older than you think :)
Update note that included this was 'ruins now have their own file', which, arguably, isn't very clear on this.

**Comment by ravignir** [comment]
3.16.2, which was released rwo weeks ago.
