### ISSUE TITLE
MacOS itch.io desktop app can't launch game

### ISSUE THREAD

**Issue by Alex25820** [yairm210/Unciv#4970]
**Platform**
MacOS Big Sur 11.5.2

**Version**
3.16.6 downloaded from itch.io desktop app

**Describe the bug**
When pressing "Launch" in the itch.io desktop app, Unciv doesn't launch properly. I believe itch tries to launch the `Unciv` "terminal application" found in: `unciv/Contents/MacOS/` and not the Unciv.jar file which can be found in: `unciv/Contents/Resources/`. This leads to the game not opening. 

When opening the `Unciv` "terminal application" manually the terminal window opens _(this window dose not open when launching the game through the itch.io desktop app)_ and the following error is displayed:
`Packing textures - 85ms`
`Error in LSRegisterURL: -10811`
`WARNING: An illegal reflective access operation has occurred`
`WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/unciv/Contents/Resources/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)`
`WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3`
`WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations`
`WARNING: All illegal access operations will be denied in a future release`

If I instead open the `Unciv.jar` file manually the game launches properly.

**To Reproduce**
1. Install Unciv on macOS through the itch.io desktop app.
2. Press the "Launch" button.
4. Game doesn't launch properly.

**Expected behavior**
The itch.io desktop app opens the game.

**Screenshots**
A screenshot of the terminal when launching the "terminal application" manual:
![Terminal Screenshot](https://user-images.githubusercontent.com/50142558/130479429-5e5af0e8-fd4e-4acd-b916-738744b90dfd.png)

**Comment by yairm210** [comment]
Thanks!
This is the first version I've tried reaching a MacOS version, and as you can tell this is completely new for me
The illegal operation is expected, the LSRegisterUrl is not.

**Comment by Alex25820** [comment]
If you need any more help feel free to tell me, I'm happy to help. 😃

**Comment by yairm210** [comment]
It should be launching the executable and not the .jar, though.
The bundle contains a packed mini-jre to avoid java dependency in the client side

**Comment by yairm210** [comment]
I think I'll cut my losses on this one and remove the Mac release
I have no way of testing this, and the jar works just as well for savvy Mac users

**Comment by Alex25820** [comment]
Did a bit of searching and this is the little information that I could find on the specific error `LSRegisterURL: -10811`.

[Apple official error code meaning](https://developer.apple.com/documentation/coreservices/3074489-anonymous/klsnotanapplicationerr/)
[GitHub issue with similar problem 1](https://github.com/XorTroll/Goldleaf/issues/571)
[GitHub issue with similar problem 2](https://github.com/discord/discord-rpc/issues/170)

If you want me to test anything on my mac, just hit me up.
