### ISSUE TITLE
It is possible to add twice the same National Wonder to the city construction queue 

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#4977]
**Platform**
Android

**Version**
3.16.4-patch2

**Describe the bug*
It is possible to add twice the same National Wonder to the construction queue of the same city

**To Reproduce**
1. Open the [Savefile](https://disk.yandex.ru/d/EBa9kbDwZQW7lQ) , go to Moscow
2. Quickly enough double tap on the plus sign near Ironworks or Hermitage
3. See two examples of both in the queue

**Expected behavior* Only single example of NationalWonder to be in construction queue

**Screenshots**
![Screenshot_2021-08-23-20-02-15-533_com unciv app](https://user-images.githubusercontent.com/86048557/130520120-c30bfbe9-c39a-4fc2-823b-e8e37c0514c6.jpg)

**Comment by logicminimal** [comment]
you just press that button really fast, this only affects the game visually

**Comment by Bershcomp** [comment]
I will keep both Hermitage in the queue and see what happen after I finish first Hermitage.

**Comment by logicminimal** [comment]
> I will keep both Hermitage in the queue and see what happen after I finish first Hermitage.

the other one disappears from thr queque

**Comment by ravignir** [comment]
another one of fast tap bugs and the least severe of all of them. Anyway were they fixed?
- when you are about to pick a policy you can pick any policy if you tap it at the same time on it and on adopt policy button (already picked policy can also be picked). 
- when you are about to choose a free tech, you can tap them in a similar way (but that is really inconsistent).

**Comment by logicminimal** [comment]
> another one of fast tap bugs and the least severe of all of them. Anyway were they fixed?
> - when you are about to pick a policy you can pick any policy if you tap it at the same time on it and on adopt policy button (already picked policy can also be picked). 
> - when you are about to choose a free tech, you can tap them in a similar way (but that is really inconsistent).
> 

yep i tried this bug and its hilarious
![Screenshot_20210824-142733_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/130608746-52f976b4-274e-4559-8d4f-d08d43467f3c.jpg)
