### ISSUE TITLE
Have the AI's units pillage player's tiles when at war

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#498]
Another idea to make the AI stronger and the game more challenging! Cheers!

**Comment by yairm210** [comment]
The harder game modes make the AI stronger, but making it smarter is very difficult...

**Comment by flecheapolinienne** [comment]
Just today I read on the Civ subreddit about how bad the AI is, even in Civilization VI. I couldn't help but reminisce about one of the best strategy game I ever played, Heroes of Might and Magic III. The game came out in 1999 and the AI's strategic abilities was incredible, making the many campaigns that came out for the title incredibly challenging and fun, providing many hours of gameplay (it happens pretty frequently that a player has to lose and regain cities multiple times in ordre to win a game). Have you ever played the game? If not, there was a couple years back a pretty sizeable community still modding and playing the game, maybe there is something to be learned there about that game's fantastic AI?

**Comment by ninjatao** [comment]
Maybe we give harder AIs more combat units? Currently AIs will cap at 2*city combatants, then build every available building before continue to build units. Which means almost never.

**Comment by flecheapolinienne** [comment]
The matter isn't really of how many combat units the AIs have, but of how they use them. Example: in my latest game, France, which was much more advanced than me in terms of Tech and had less but bigger cities that had built almost all the wonders declared war on me. It started sending frigates to bombard one of my isolated cities and a couple of riflemen but had them retreat much too quickly under light damage. A couple turns later, it started sending many units in waves across the water, but having already built many frigates myself, I was able to destroy them all on the spot or have them turn back when damaged. That was the biggest factor in the AI being incapable of invading my lands, another being that it didn't send them the way of my closest cities (maybe because it didn't see them?)

So, to sum up: 1. The AI only sends its troops to cities it sees and doesn't explore enough to find the closest cities to attack 2. It doesn't escort its troops when they are at their weakest on water with warships 3. It's too quick to send them back home because they're hurt when it should try and push as much as it could through enemy fire in order to submerge and capture a city in the fastest way possible 3b. When troops are hurt and pulled back, it sometimes let them exposed out in the open as easy prey. Hurt units should always be put behind city walls or on some tile with defensive bonus, removed from attacker's reach.

These are the behaviours that, if changed, could make the AI a ferociously dangerous opponent. I know the hard part is to figure out how to put them into effect...  Let's just say I'd be more than happy to pay a coffee to the both of you for all the hard work lol

**Comment by ninjatao** [comment]
I have never engaged such epic battles. I always produce 3~4 crossbows and 3~4 trebuchets ASAP. They can beat any AI with the help of 1 horseman(or even pikeman), up to Emperor difficulty. So as far as I see, main problem is AI unit number.

**Comment by Am-per-Sand** [comment]
I'd like to test it how AI would employ this strategy – though they like to send a lot of weak units whereas I like to keep a few elite ones and let AI bleed out against my walls.

Nevertheless I think barbarians should pillage more. My suggestion is from 1 time each 10 turns on the easiest difficulty level to 5 times each 10 turns on the hardest.

**Comment by yairm210** [comment]
Done by @ninjatao
