### ISSUE TITLE
Road building UI for Workers

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#4981]
Hi. In Unciv we all know that worker automation might make the workers make roads to connect cities. But the question is when? From my experience they do it totally Randomly wasting a lot of moves. Sometimes they work one or two tiles, leave it behind and then do some other job, making the building of roads much time consuming and inefficient.

So, what is the alternative? Stop worker automation and build roads manually. But that's a pain also. You have to select each tile and then build roads.

So, solution? UI or Option for building roads. I saw this mechanism in Freeciv. The intregrated a road building feature with the movement UI! Just select your worker, select another tile. And then two options will appear. One 'Move to the tile', Two 'Connect the Tile with roads' saving a lot of human time at once! The good part of these feature is when you are calculation most efficient path to move between two tiles, you are actually calculating most efficient path of connecting two tiles with roads also.

I suggest this to be added in Unciv also. It would make the GamePlay a lot easier. Since many players like to do everything manually instead of automation.

**Comment by yairm210** [comment]
This feature is implementation hell.
We've tried to do this twice already and could not reach a state where it was working well.
You're welcome to try as well.

What this actually contains:
- "create road to to tile x" as long term unit action
-  shortest road is not shortest unit movement, don't build roads around forests/jungles/hills but through them
- what do you do if one of the tiles is already occupied?
- how do you visualize to the player what time the unit is building a road to?

The actual UI is the trivial part

**Comment by touhidurrr** [comment]
> This feature is implementation hell.
> We've tried to do this twice already and could not reach a state where it was working well.
> You're welcome to try as well.
> 
> What this actually contains:
> 
> * "create road to to tile x" as long term unit action
> * shortest road is not shortest unit movement, don't build roads around forests/jungles/hills but through them
> * what do you do if one of the tiles is already occupied?
> * how do you visualize to the player what time the unit is building a road to?
> 
> The actual UI is the trivial part

My recommendations to avoid a possible implementation hell is to add an option called 'Build Roads' on the worker. Clicking Build roads and then clicking another tile will show a connect road icon like the movement icon. Then if the user likes the path in between he/she can start building the road.

**About shortest movement path is not shortest road path:**
What does roads does actually? Removes the movement cost by half? The. Assume between 2 tiles there is 3 possible paths with cost 11, 12 and 13. Now the cost of moving with roads will be 5.5, 6 or 6.5. So either 6 or 7.
Now the shortest movement algo will choose the 11 cost path which should also take 6 turns via roads. So why is it that both paths are not equal? I can't understand it.

**About what will the worker do if something comes between:**
The worker will just stop building roads so that the player can decide what to do next.

**Comment by touhidurrr** [comment]
Also this a feature request. I am not an Android Developer.

**Comment by logicminimal** [comment]
> This feature is implementation hell.
> We've tried to do this twice already and could not reach a state where it was working well.
> You're welcome to try as well.
> 
> What this actually contains:
> - "create road to to tile x" as long term unit action
> -  shortest road is not shortest unit movement, don't build roads around forests/jungles/hills but through them
> - what do you do if one of the tiles is already occupied?
> - how do you visualize to the player what time the unit is building a road to?
> 
> The actual UI is the trivial part

why dont we just copy civ 5

**Comment by ravignir** [comment]
i had such idea:
there would be an additional worker button that would allow buildings multiple roads
![p](https://user-images.githubusercontent.com/30041793/130574895-b3956c83-1eba-4d65-a9a4-6cb583dbb0f0.png)
it would open such screen
![o](https://user-images.githubusercontent.com/30041793/130575064-4a6d9442-44ee-4d83-b97c-818a9591b222.png)
user would just select add tiles/remove options to tap/click the tiles to put them on the list and once all is set, they would select  start roads construction button.

**Comment by logicminimal** [comment]
> i had such idea:
> there would be an additional worker button that would allow buildings multiple roads
> ![p](https://user-images.githubusercontent.com/30041793/130574895-b3956c83-1eba-4d65-a9a4-6cb583dbb0f0.png)
> it would open such screen
> ![o](https://user-images.githubusercontent.com/30041793/130575064-4a6d9442-44ee-4d83-b97c-818a9591b222.png)
> user would just select add tiles/remove options to tap/click the tiles to put them on the list and once all is set, they would select  start roads construction button.
> 

not automatic but surely better than nothing, also if we generalise this we can make this work with improvements as well

**Comment by will-ca** [comment]
Two options:
* Store planned improvements per tile. So long as there are any planned improvements, automated workers will prioritize those. Messy, but potentially powerful.
* Store planned actions per unit. More predictable and more like Civ V.

Either way, separate routing logic from automation logic.

**Comment by AdityaMH** [comment]
#5856
