### ISSUE TITLE
Sometimes the game crashes when upgrading a unit

### ISSUE THREAD

**Issue by adeliosteve** [yairm210/Unciv#4984]
**Platform**
Mobile

**Version**
3.16.7

**Describe the bug**
Sometimes some units crash the game when upgraded if a worker is constructing in that same tile

**To Reproduce**
1. Go to 'an unit that is a tile with a worker constructing'
2. Click on 'the unit'
3. Scroll down to 'Upgrade to'

**Expected behavior**
The unit crashed the game

**Screenshots**

**Additional context**
it will continously do that until the units moved into a diffrent tile or the worker finished

**Comment by adeliosteve** [comment]
This is a rare Bug it sometimes work sometimes dont.
only happened to me twice only

**Comment by logicminimal** [comment]
by any chance u can send the stacktrace?

**Comment by xlenstra** [comment]
Do you have a save file where this sometimes happens?

**Comment by yairm210** [comment]
We can't work on this without anything to go on... If this returns please ping again, for now I'm closing this as "unworkable, not reproducable"
