### ISSUE TITLE
Barbarian's "missing ressource"?

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#499]
![screenshot 2019-03-03 at 16 07 52](https://user-images.githubusercontent.com/45007481/53701804-ab6b3d00-3dce-11e9-80f1-8ccf09143dc1.png)
What is up with barbarian units incurring a 25% malus due to their "missing ressource"? Is it a feature?

**Comment by ninjatao** [comment]
Nice point. Barbarian should totally ignore strategy resources.

**Comment by ninjatao** [comment]
By the way, why are unit names of "Frigate" displayed in French and English at the same time?
