### ISSUE TITLE
Unknown crashes in Unciv in armv7l Android

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#5022]
I tried installing Unciv on a Raspberry Pi 3B+ with LineageOS (with Android 10 installed.) I could install and run almost all well known Andorid Apps from Play Store on it like WhatsApp or Discord. They worked without any problem. However, only Unciv installed from Google Play Store kept crashing freezing the entire OS. It felt like it was crashing in loop.

Also I tried to install the Github version first but it wouldn't even install for some reason.

CPU-Z showed the architecture was armv7l.

**Comment by yairm210** [comment]
Isn't this just #4943 again?

**Comment by touhidurrr** [comment]
> Isn't this just #4943 again?

No, this time the Crash happend on an Android installed armv7l kernel running device but not a Linux installed armv7l kerne; running device. Too simply put this times crash is on Android not on Linux. So, a libGDX armv7l Android issue but not a libGDX armv7l Linux-32 issue.

**Comment by yairm210** [comment]
I'm sure, they're the same. The APK problem is probably because it's unsigned.

**Comment by SomeTroglodyte** [comment]
And no, nobody "forgot" to include the arm-specific binaries in the apk. There's a gdx binary for armeabi-v7a and one for arm64-v8a (plus x98 and x86_64). Note no verbatim 'armv7l'. Whether armc7l is compatible with one of the supported architectures or not is not really our responsibility. As far as I can tell, the libgdx project promises Raspi support for the next version only, and then only for desktop. Lastly, I'd say without relevant logcat output this is too imprecise to guess much.

**Comment by touhidurrr** [comment]
`armeabi-v7a` just some 32-bit instruction sets. all `ARMv7` type processors supports this. Then the crash might be for some other reasons.

Also Raspberry Pi uses ARM based CPUs same as Android phone. It's nothing new. ARM CPUs are just designed to run on low power. Typically Mobile Phones.

Also, The Play Store downloaded app did open but crashed after I installed 5 Hex Tileset. I will try to see if there is any way to get the error logs. But the device freezes making it impossible.

**Comment by SomeTroglodyte** [comment]
Tried any other [Gdx based apps](https://libgdx.com/showcase/)?

**Comment by kenwud** [comment]
sorry for being kind of unspecific. updated the app via fdroid today after seeing the notification to update the app for a few weeks and now it crashes when I try to launch the game. on Redmi 9 most recent update. it was working fine til I updated it

**Comment by touhidurrr** [comment]
> sorry for being kind of unspecific. updated the app via fdroid today after seeing the notification to update the app for a few weeks and now it crashes whe

Not related to this issue probably. See https://github.com/yairm210/Unciv/issues/5785. F-Droid latest is currently 3.18.9. Wait for the next version and it should be fixed.

**Comment by yairm210** [comment]
I think this is closable, no?
