### ISSUE TITLE
Repetitive city state bonus text on 3.16.10

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5037]
![Screenshot_20210831-074857_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/131443884-7a997a20-70c2-4ffa-b8ed-e232e344b320.jpg)

![Screenshot_20210831-074901_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/131443898-3253d823-e881-4b34-b2d3-9224cca2802a.jpg)

![Screenshot_20210831-074907_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/131443911-65534e0f-872e-427f-8506-99640ea3c6bd.jpg)

how did this even slip?

**Comment by xlenstra** [comment]
Not only is the text repetitive, but also the effects are. If you ally a cultural city-state early on, you can win a culture victory in the medieval era with this. I can look into this later, first I'm still doing some work on religion. If anyone looks into it in the meantime, fine by me.

**Comment by SimonCeder** [comment]
It's a bug in `canGiveStat`, I'll PR a fix in a moment. It depends on what other civs are in the game which is why I didn't spot it right away, but still..
my bad (facepalm)
