### ISSUE TITLE
Fdroid release does not start on Android 12 beta

### ISSUE THREAD

**Issue by iuliandita** [yairm210/Unciv#5044]
**Platform**
Android 12 beta

**Version**
3.16.6 fdroid

**Describe the bug**
Game crashes on start

**To Reproduce**
1. Tap app
2. Does not start...

**Expected behavior**
Game starts?

**Screenshots**

**Additional context**
I cleared cache and data, no improvement.
I also tried downloading the APK from GitHub (newer versions) but they all fail to install: "app not installed as package appears to be invalid".
Downgrading the fdroid release fails with: "failed to install due to unknown error".

**Comment by SomeTroglodyte** [comment]
You can't expect us to support beta environments...
Are you able to install shattered or mindroid, or any other Gdx-based app?

**Comment by iuliandita** [comment]
I didn't mean it like that, I am not complaining :)
It was working just fine until about a week ago, but I got a couple of Android patches since then...

Shattered works just fine.

**Comment by SomeTroglodyte** [comment]
OK, S now is officially crap in my book. @iuliandita , thanks for the heads-up, your info looked like a bit insufficient but actually just firing up an emulator for S was enough to repro.

```
    Process: com.unciv.app, PID: 8160
    java.lang.IllegalArgumentException: com.unciv.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

The only `PendingIntent` we do ourselves is in the maudit `MultiplayerTurnCheckWorker` - not my turf. If I were to solve this, my first approach would be to remove multiplayer entirely, so perhaps better not. ... - No, removing all code from that doesn't help. It's not _our_ `PendingIntent` then. A breakpoint on AndroidLauncher.onCreate fires, but at that point the thread force-stopping Unciv has already fired, too, so it's pointless to debug - happens before our first line of code, or am I missing something?

You can't even shut down S with the power button - _what_ were they thinking? I'm out.

**Comment by SomeTroglodyte** [comment]
@yairm210  `targetSdk = 30` in the android gradle script would indeed do it. However, Play Store would kick us out for that sooner or later as I understand it - well, it's unhealthy anyway. Not finding any PendingIntent, the proper fix must have something to do with androidx versions, and at that point I'm stopping.

**Comment by yairm210** [comment]
"eventually" sounds like enough time for them to solve the problem at its core. If this is good enough as a temporary fix, then I'm in favor.

**Comment by will-ca** [comment]
In the days immediately following this issue, there was apparently a deluge of commentary on StackOverflow about it something to do with `androidx` and `targetSdk` versions:

https://stackoverflow.com/questions/69034879/how-to-resolve-this-error-the-mincompilesdk-31-specified-in-a-dependencys-aar

My observations: AndroidX 1.7 works with SDK 31, and AndroidX 1.6 works with SDK 30, I think.
