### ISSUE TITLE
City conquest screen doesn't scroll.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5046]
**Version**
Play Store, 3.16.7

**Describe the bug**
The city conquest options ("Annex", "Raze", "Puppet", "Liberate") don't scroll for me.

In Landscape orientation on a small phone, much of the text was clipped, although the main buttons were still visible.

**To Reproduce**
1. Conquer a city.

**Expected behavior**
Scroll view, like in the rest of the UI.

**Comment by SomeTroglodyte** [comment]
Define small phone - and what ""resolution"" setting did you use? (If there was no ScrollPane used this _might_ be clear enough in code but it would be good to know what limits you expect)

**Comment by yairm210** [comment]
Can you attach a save file so we can test this?
