### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by IAmMrXsss** [yairm210/Unciv#5049]
I Need More Flies Of Mod (like Buildings.json,Nations.json)To Make Mods Plz
Your Game's Fans Is Waiting For My Mod
Plz
I Need Flies Like:Victory Type,Tutorials,More Great Point(Like Food Great Point)

**Comment by IAmMrXsss** [comment]
hmmmmmmm..
Too Earl  LoL

**Comment by yairm210** [comment]
You can have and great person points that you want, they're completely moddable
As for the others, they'll come when they come
