### ISSUE TITLE
Implement diplomatic warmongerer rating for civs according to behavior

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#506]
AI shouldn't accept to sign a peace treaty if...
1. Preceding peace agreement has already been violated less than X turns before
2. Player is at war with one (two?) other civs
3. X player's units with less than Y life points are killeable by the AI in 1 turn

Maybe implement one per difficulty level? Number 1. should definitely be the way the AI goes at any level of difficulty.

**Comment by ninjatao** [comment]
I believe original civ games have a War-Score system for that.
