### ISSUE TITLE
City State Diplomacy GUI is too wide to read, when-friends/when-allies info grows too long

### ISSUE THREAD

**Issue by Pxtl** [yairm210/Unciv#5079]
**Platform**
Android 11 on a Pixel 4a

**Version**
v3.16.10 from the Play Store

**Describe the bug**
The city-state diplomacy GUI is super wide - you have to horizonally scroll endlessly to see the actual UI.  I think the "when-friends/when-allies" listing is too long is the cause.

**To Reproduce**
1. Start a game that includes city-states
2. Contact a city-state
3. Open diplomacy pane

**Expected behavior**
Display the city-state diplomacy without horizontal scrolling.

**Screenshots**
![Screenshot_20210903-140005](https://user-images.githubusercontent.com/5386926/132048265-563b034d-29f8-49d6-8014-50e056ad7aed.png)

**Additional context**
I attempted to open a saved game but the issue was gone after reloading.  I think something is concatenating onto when-friends/when-allies endlessly, it looked very very duplicated.

**Comment by SimonCeder** [comment]
fixed in 3.16.11
