### ISSUE TITLE
Missing Italian translations

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#508]
MISSING ITALIAN TRANSLATIONS

-Turn (for main screen at top left, e.g. turn 234)
-Replacable Parts (Technology)
-Combined Arms (Technology)
-Coast (Terrain)
-Ocean (Terrain)
-Description for Oligarchy
-Description for Collective Rule
-Description for Wagon Trains
-Freedom should be Autonomia, you didn't translate it
-You didn't, in fact, updated any Italian translation I have memory of

**Comment by yairm210** [comment]
Freedom and Turn already worked
Wagon Trains doesn't exist in this version
The rest were corrected
Replacable parts is actually a spelling error...correcting t is a huge hassle, so patched it for now...
... everything you add enters a version, but the versions have rollout schedules so I can stop the rollout if there are serious bugs, you don't get in the very next day
