### ISSUE TITLE
Can't create map

### ISSUE THREAD

**Issue by SuperCiuper** [yairm210/Unciv#5080]
**Platform**
Windows 11, 64bit

**Version**
From this github through itch.io (downloaded zip), version 3.16.11

**Describe the bug**
I cannot create rectangular map of custom size that changes height. I put value of 1000 in width, there was info that this is too much so it was spread to width and height (149, 97) and this settings worked. Looks like only changing height by hand breaks this tool 

**To Reproduce**
1. Go to map editor, rectangular, custom size, change height
4. See map not being made

**Expected behavior**
Well I want to create a map of my size. Now it can be done by typing huge values in width that will be transfered to height without changing it manually

**Comment by SomeTroglodyte** [comment]
"See map not being made" was not very clear - you get a message that the map could not be created. But I found the cause. Thanks for telling us!
