### ISSUE TITLE
Coders please: Bad starting locations and New map hangs

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5085]
Starts like this one should not happen:
![image](https://user-images.githubusercontent.com/63000004/132093387-1b3d3bdb-d761-428b-bbd4-7fa61db52939.png)

It's on Snow, and GameStarter line 365 says Snow isn't even considered. Needs investigation.

It's way closer to the edge than the distance between the Civ's, and that's explained by `GameStarter.vectorIsAtLeastNTilesAwayFromEdge` being hilariously wrong for rectangular and/or wrapped maps.

While something like `return tileMap.getTilesInDistance(vector, n).count() >= HexMath.getNumberOfTilesInHexagon(n)` is perfectly exact, it increases `GameStarter.addCivStartingUnits` time by about factor 20. So - any input on the correct math for this? (The resulting maps/civ distributions _do_ look _waaaay_ better with this code)

Also - the river generator _can_ run in an endless loop, I've seen it repeatedly. `RiverGenerator` line 54 typically has 3 `possibleCoordinates` in such a loop - while I would expect a nice algorithm to only ever have two here (three edges meet, and one is the direction I'm coming from - I can only continue in two directions). Is the original creator of this code still around please? Otherwise I'd PR a simple step counter with a max - that works indeed to prevent these hangs. Any qualified input welcome.

**Comment by ravignir** [comment]
> Also - the river generator _can_ run in an endless loop, I've seen it repeatedly. `RiverGenerator` line 54 typically has 3 `possibleCoordinates` in such a loop - while I would expect a nice algorithm to only ever have two here (three edges meet, and one is the direction I'm coming from - I can only continue in two directions). Is the original creator of this code still around please? Otherwise I'd PR a simple step counter with a max - that works indeed to prevent these hangs. Any qualified input welcome.
>
I think it was yairm himself.

**Comment by SomeTroglodyte** [comment]
git blame says so too - only I had some vague recollection on some code-level discussion about the rivers... Anyway, the river gen is not wrap-aware, namely in its own `getAdjacentTiles` and in `RiverCoordinate.getAdjacentPositions().filter...`, and that may already be enough explanation why it may loop.

My puzzlement "expect a nice algorithm to only ever have two" stems from me thinking in terms of the edges, while the generator deals in vertices. I still don't see any "direction I'm coming from", but that may be just fog-of-war...

**Comment by yairm210** [comment]
River generation was from before there was wraparound
About the 'endless loop', I considered it, but since rivers always halead towards the nearest water this is not a practical problem, and I really liked the "branches" of rivers that resulted from the back and forth :)

**Comment by SomeTroglodyte** [comment]
Yeah, I was doing Archipelago with more mountains and lower water line, and it didn't finish in a quarter of an hour, so I set a breakpoint and then could see it cycle through 7 or 8 positions in a loop.

I've got the two 'adjacent' routines wrap-aware, and that plus an upper limit of a few hundred loop iterations had no more hangs - of course, but I couldn't see any rivers not reaching water either (not via visual, specific breakpoint). So far so good.

But I'd also like to fix that distance from edge function and so far haven't gotten far.  Distance to equator is more or less average of x and y, but the non-wrapped rectangular maps and wrapped hexagonal ones still need a little 'eureka'.

To think I started on this _only_ because the run time of the "starting unit placement" can surely be cut in half...

Another question: GameStarter determines landmasses, and the minimum city distance rule could use that data. Another serializable field on TileInfo `landmassIndex` or somesuch? At least +20% savegame size... Unless we start compressing them same as maps.

**Comment by SomeTroglodyte** [comment]
Update: Got `HexMath.getDistanceFromEdge` done, efficiently. Did you know Int.div(Int) rounds _inconsistently_, direction changes depending on sign? I couldn't even find official documentation on that decision, had to use the debugger to make sure... Mad world (<sup><sub>Tears for Fears version</sub></sup>).
