### ISSUE TITLE
Uniques - some problems and possible solutions - input requested

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5091]
While the current system with uniques, placeholders and filters allows a lot of freedom for modders, in some areas it still has some problems. This issue will first give an overview of the most major problems with uniques, for modders, users and developers, and then proposes a vision of uniques where these problems will be solved.

Coders, what do you think? Mod makers, would this change be a major improvement to moddability? Do you expect to use this heavily if it were added?

### Problems with uniques

So, first, what problems are there with the current uniques?
- Combining filters is not possible. While this has been tried for `unitFilter`, by allowing `[{military} {water}]` as a unit filter, it was quickly discovered that the space in between the partial filters is depended on language. Thus, this could not become a general solution.
- A lot of uniques are very similar both in wording and effect, but every single unique needs to be checked independently. This was for example noticed for battle uniques in #4777, were @avdstaaij proposed a combined naming scheme for these.
- Uniques are strings. While this is great for storing in `.json` files and for modders, doing continuous string comparisons all over the code base will eventually add up to performance loss. Additionally, typos and miscapitalization might go unnoticed, possibly introducing hard to find bugs where certain uniques do not seem to work for no reason whatsoever. This point has been discussed before in a comment in #4890.
- Detecting the source of a unique is difficult. There are multiple places where we would like the source of a unique, for example when determining stat bonuses in the city screen, or combat bonuses for a unit. An example of this would be the `Haka War Dance` unique, which provides `-10% Strength to adjacent enemy units`. In the olden days where uniques had no placeholders, we could just use this unique and call the modifier 'haka war dance', which was descriptive. However, because in mods an entirely different source might provide this unique, this name would only create confusion. It was thus replaced with the less descriptive "Adjacent enemy units", which, although correct, is not clear to a user. Why only these adjacent enemy units? Why only here?
- Continuing the last point for determining where the stats from cities come from: in `CityStats.kt` there are a lot of functions whose only purpose is to check for a specific set of uniques of a specific object for matching uniques, and only add those stats to a `StatList` with a given tag. This means, that if a new source of stats is added, you have to test for this type in multiple functions and somehow get access to all uniques from that source. And some of these sources are combined for no reason whatsoever, such as `getGrowthBonusFromPoliciesAndWonders()`. It would seem all of this could be much simplified if uniques somehow were able to keep track of their source themselves.

### Proposed solutions

So, what is my vision for what uniques should become? There are multiple problems here, and so the solution consists of multiple parts:
- Uniques should be able to keep track of their source themselves. This can for example be done, by initializing a member variable of a unique in the `lazy` of the `uniqueObjects` of each class with uniques. As this source then stays with the unique wherever it goes, this source can than easily be queried as needed.
- Uniques should be allowed to have optional parts, which could be denoted by putting them between `<` and `>`. This would unify uniques like `[sigedAmount]% Strength` and `[signedAmount]% Strength <for [unitFilter] units>`. Only the base unique should still be saved in the `Unique` object, which would be `[]% Strength` for both of these uniques. `Unique`'s should also have a `List` (or possibly `HashSet`) of all optional parts. My personal idea for how these should be implemented can be found below. Another advantage of these optional parts, is allowing for things that are currently impossible, such as temporary uniques. The base game only supports a single temporary unique, the autocracy finisher. By making `<for [amount] turns>` an optional part of a unique, and checking uniques for having that optional part, any unique can become temporary, increasing moddability.
- The `uniqueObjects` should not contain a string of the unique, but a value of an extraordinary large Enum, containing every possible unique supported in the game. During checking mod links, every unique should be compared with this Enum, and uniques not in the enum can be shown as errors, hopefully reducing typo's. In the code themselves, we will also only have to compare to this Enum, effectively making this Enum the only determining factor in what text is what unique. This would also simplify the unique deprecation process, by simply temporarily mapping to distinct unique strings onto the same enum value. Combining this proposal with the 'optional parts' proposal, we would only need the base unique in the Enum, which would somewhat reduce the amount of values required.
- Combining filters is less interconnected with the other solutions, but as it is useful for moddability, I still wanted to include it in this proposal. Basic idea: we continue on the road we have started, with the `[{filter}{filter}]` for combining different filters, but we ask in a translation file the "word separator character", and when translating uniques put these between adjacent `}` and `{`. 

### Effect on mod makers
For mod makers especially the optional parts would result in a lot more flexability, allowing combinations of parts of uniques we would never thought to implement to still function, such as `[+1 Gold] from every [Artist] <for [10] turns>` or `[+25]% <Melee> Strength <when [attacking]> <vs [{all} {Amored} {enemy}] units> <during the [Industrial era]> <on [Bonus resource] tiles> <after adopting the [Entrepreneurship] policy>` etc. Do note that in these examples, the placing of each of the parts between `<>` shouldn't matter, so you could also write `<for 10 turns> [+1 Gold] from every [Artist]` or `[+1 Gold] <for 10 turns> from every [Artist]` and all these would function the same (this is due to us removing all these optional parts when determining the base unique). Nesting optional parts would sadly be impossible.

### Implementation
Adding in this functionality would come with its own hurdles. For example, `getPlaceholderText()` should learn that it should remove all text in between `<>` as well as those characters themselves and exactly one space character (in languages that have that) to avoid having two spaces in a row, and at least my regex skills are not leet enough to do that. 

I would propose saving the optional parts of uniques as uniques themselves, to allow easy access to their parameters and text without parameters.

It would also require teaching the `.tr()` function to also translate the parts between `<>`, but that shouldn't be the most difficult.

Adding in these new functionalities would require a overhaul of a large amount of the code related to checking for uniques, most notably the `Unique` class itself. My first draft for the class would look something like this:

```Kotlin
class Unique(val text: String) {
    val baseEnum = Uniques.Undefined
    val placeholderText = text.getPlaceholderText()
    val params = text.getPlaceholderParameters()
    val stats: Stats by lazy {
        val firstStatParam = params.firstOrNull { Stats.isStats(it) }
        if (firstStatParam == null) Stats() // So badly-defined stats don't crash the entire game
        else Stats.parse(firstStatParam)
    }
    val optionalParts = List<Unique>()
    var source: String = ""
}
```

Another point that needs to be changed would be that we somehow need to allow for almost any optional part imaginable to be checked for any unique imaginable, which might prove difficult, though I do have an idea on how to do this already.

I would like to credit avdstaaij for priming me with the ideas for optional parts after a cursory reading of #4777. On close inspection I have since noticed that this idea was actually named in his proposal, though I did not notice it at the time.

**Comment by yairm210** [comment]
This is a super interesting suggestion!
I also think it's very doable!
The only problem I can forsee is with spaces before the <> and Chinese, but if you have a "spacing character" that can be an empty string as you suggested, that problem should be solved as well :)

**Comment by xlenstra** [comment]
I had some free time, so I decided the best use of it would be to go through the entire list of uniques we have on the wiki, and break these up into base parts and optional parts. During these, I've also reworded a few to make them more consistent. In the end, I've generated the list of base uniques and optional parts below, which should be able to handle any unique we currently have:

<details> <summary> Full list (warning, over 300 lines) </summary>

Base Uniques:

## Global & Local Stat uniques

[amount]% [stat]
[amount]% growth
[amount]% food is carried over after population increases

[stats] -- Will add these stats to the base value in all cities, unless modified of course
[stats] from every specialist
[stats] from every [object] -- object is `buildingFilter`, `tileFilter`, `resourceFilter`, `specialist name`, "Trade Route", "specialist", "Social Policies Adopted", "Techs Researched" or "population"
[amount]% [stat] from every [object] -- Fully implementing this one will be fun
[amount]% stats from every [object]

[amount]% science from research agreements
[amount]% maintenance cost of roads

[amount]% unhappiness from population
[amount]% unhappiness from specialists
[amount]% unhappiness from cities
[amount]% food consumption by specialists

[stats] when a city adopts this religion for the first time
[stats] for each global city following this religion
[amount]% [stat] from every follower
[stats] from every global follower



## Global unit-affecting uniques

Newly-trained [unitFilter] units gain the [promotionName] promotion -- This unitFilter can also accept 'relevant'.
Newly-trained [unitFilter] units gain [amount] Experience
Newly-trained [unitFilter] units can [unitAction] [amount] extra times
[amount] units cost no maintenance
[amount]% Combat Bonuses provided by [unitFilter] units -- Modifies the bonuses provided by other uniques. This one will be difficult to implement.


Units fight as though they were at full strength even when damaged
Units pay only 1 movement point to embark and disembark -- Can be generalized but performance
[unitFilter] units pay no movement cost to pillage -- Can be generalized but performance

Great General provides double combat bonus -- It is clear that this can be generalized to "[+100]% Combat bonus provided by [unitFilter] units", but can that be split up further?



## Global and unit uniques affecting units

[amount] Movement
[amount] Sight
[amount] additional attacks per turn
[amount] Range
[amount] Interceptions
[amount]% Strength
[amount]% Experience gain from combat
[amount]% unit maintenance costs
[amount]% tile improvement construction time
[amount]% upgrade cost

When spreading religion to a city, gain [amount] times the followers of other religions as [stat]
Earn [amount]% of killed [unitFilter] unit's [param1] as [param2] -- param1 is "Strength" or "Cost", param2 is a global stat
Earn [amount]% of damage done to [unitFilter] units as [param2]




## Unit uniques affecting themselves

Can be purchased with [Stat]
Can be purchased for [amount] [Stat]


### Civilian-only

Can build [improvementFilter] improvements
May create improvements on water resources -- generalization pending on complete redesign of the system of building improvements
Can found a new city
Can undertake a trade mission with a City-State, giving [stats] and [amount] influence
Can start a [amount]-turn golden age
Can hurry research
Can speed up construction of a wonder
Can speed up construction of a building
Can construct [improvement]
Can found a religion
Can enhance a religion  


### Movement

-- From here, not generalized due to preformance
Double movement in coast
Ignores terrain cost
Ignores Zone of Control
Cannot enter ocean tiles until Astronomy
Can enter ice tiles
\-\-

Can move immediately once bought
Can move after attacking
No movement cost to pillage
Can paradrop up to [amount] tiles
Can transfer movement to [unitFilter] units
Can enter foreign tiles without open borders
Can enter foreign tiles without open borders, but loses [amount] religious strength each turn it ends there


### Healing

[amount] HP when healing
All adjacent units heal [amount] extra HP when healing
Heals [amount] HP when it kills [unitFilter] units
Can heal outside of friendly territory


### Combat

Can only attack [unitFilter] units
Can only attack [tileFilter] tiles -- Maybe these two could be combined?

No defensive terrain bonus
Eliminates combat penalty for attacking over a river
Eliminates combat penalty for attacking from the sea

[amount]% chance to withdraw before being melee attacked
[amount]% chance to intercept air attacks

Self-destructs when attacking
Must set up to ranged attack
Ranged attacks may be performed over obstacles
Cannot be intercepted


### Other

Can see invisible [unitFilter] units
Invisible to others
Invisible to non-adjacent [unitFilter] units -- If the unitFilter doesn't increase performance

Can carry [amount] [unitFilter] units
Can carry [amount] extra [unitFilter] units
Cannot be carried by [unitFilter] units

Nuclear weapon of Strength [amount]
Blast radius [amount]

May capture killed [unitFilter] units

Religious unit
Can [unitAction] [amount] times
Takes your religion over the one in their birth city
Removes other religions when spreading religion
Prevents spreading of religion to the city it is next to



## Global uniques affecting City-States

[amount]% City-State influence degration
[amount]% City-State influence recovery
[amount]% City-State influence degration for other civiliations
[amount]% City-State influence recovery for other civiliations

[amount]% more influence from gold gifts to City-States
Resting point for Influence with City-States [amount]
Resting point for Influence with City-States following this religion [amount]

City-States provide [Stat] equal to [amount]% of what they produce for themselves
City-States gift [amount]% more resources
[amount]% Happiness from Luxury resources gifted by City-States
[amount]% [stat] gifted by City-States
[amount]% turns between military units gifted by City-States -- I'm still on the fence about this wording
[amount] influence when gifting [unitFilter] units to City-States



## Other Global uniques

May buy [buildingFilter] buildings for [amount] [stat]
May buy [unitFilter] units for [amount] [stat]
[amount]% [stat] cost of purchasing [unitFilter] units
[amount]% [stat] cost of purchasing [buildingFilter] buildings

[amount]% cost of researching technologies
[amount]% cost of adopting policies
[amount]% increase in policy cost per city
[amount]% culture cost of acquiring tiles
[amount]% gold cost of acquiring tiles

[amount]% Strength from defensive buildings
[amount]% population loss from nuclear attacks
Upon capturing a city, receive [amount] times its [Stat] production as [param1] -- Param1 is a global stat; This can probably be parameterized, but I don't see how right now
Cities are razed [amount] times as fast

[amount]% length of golden ages
[amount]% [greatPersonFilter] point generation -- "greatPersonFilter" should accept 'great person' as 'all' and names of great people types as only that

[amount]% production of [resourceName]
[amount]% of the happiness from a trading the last copy of a luxury away is retained 

Immediately creates the cheapest available [stat] building in each of your first [amount] cities for free
Immediately creates a [buildingName] in each of your first [amount] cities for free

Indicates the capital city
Connects trade routes over water
"Borrows" city names from other civilization in the game


## City uniques -- Can be provided by buildings or religion. Only contains uniques that can only apply to a specific city

[amount]% Gold when this city is captured
Removes extra unhappines from annexing this city
Provides [amount] extra copies of each luxury resource near this city
[amount] HP per turn when healing for all adjacent [unitFilter] units


## Construction-only uniques

Cannot be purchased
Cost increases by [amount] per owned city
Unbuildable

### Buildings-only uniques

Unsellable
Triggers a global alert upon build start
Triggers a global alert upon completion
Destroyed when the city is captured
Never destroyed when the city is captured
Not displayed as an available construction without [resourceOrBuilding]

### Construction condition uniques -- These mostly can't use optional parameters

Consumes [amount] [resourceName]
Must be on [terrainFilter]
Must not be on [terrainFilter]
Must be next to [tileFilter]
Must not be next to [tileFilter]
Must have an owned [tileFilter] withtin [amount] tiles
Requires a [buildingName] in all cities -- Cannot be city-filtered
Can only be built [cityFilter]
Obsolete with [techName]
Requires [constructionName]


## Tile, Terrain & Improvement-only uniques

Tile provides yield without assigned population
Indestructable

### Improvement-only uniques

Obsolete with [techName]
Costs [amount] gold per turn when in your territory
Can be built outside your borders
Great Improvement
Cannot be built on [tileFilter] tiles
Provides a random bonus when entered

### Terrain-only uniques

[amount] Strength for cities built on this terrain
Occurs at temperatures between [amount] and [amount] and humidity between [amount] and [amount]
Grants [stats] to the first civilization to discover it
[amount] Sight
Has an elevation of [amount] for visibility calculations
Blocks line-of-sight from tiles at the same elevation
Resistant to nukes
Can be destroyed by nukes



## Internally functioning uniques

Hidden when religion is disabled
Hidden after generating a Great Prophet
Hidden when [victoryType] victory is disabled
Hidden until [amount] social policy branches have been completed
Doing so will consume this opportunity to choose a Promotion







Optional Parts:

\<[cityFilter]>
\<in cities with at least [amount] specialists>
\<in cities with at least [amount] population>
\<in cities where this religion has at least [amount] followers> -- Yes, these are technically all cityFilters, but because they require a parameter, they cannot be put inside a parameter, so making them optional parts is the easiest way out
\<in a random city>

\<when constructing [unitFilter] units>
\<when construction [buildingFilter] buildings>

\<with [techOrPolicyName]>
\<without [techOrPolicyName]>
\<starting from the [eraName]>
\<up to the [eraName]>

\<[amount]> -- For example, "[stats] per <[amount]> population <[cityFilter]>" for libraries. Divides the "stats" by "amount" to apply its effect
\<up to [amount]%> -- This one will be fun to implement

\<while the empire is happy>
\<when not at war>
\<when at war>

\<on [tileFilter] tiles>
\<fighting in [tileFilter] tiles>
\<on [tileFilter] tiles without [tileFilter]>
\<for each adjacent [tileFilter]>
\<within [amount] tiles of a [tileFilter]>

\<for [unitFilter] units>
\<for [unitFilter] units which have a [unitFilter] unit in an adjacent tile>
\<for [unitFilter] units within [amount <= 5] tiles>
\<when stacked with [unitFilter] units>
\<for [cityFilter] cities>
\<vs [unitFilter] units>
\<when embarked>
\<when attacking>
\<when defending>
\<when intercepting>

\<[relationshipFilter]>
\<[reliationshipFilter] and friendlier>
\<[reliationshipFilter] and unfriendlier>
\<when at war with a common enemy>
\<for both parties after signing a declaration of friendship>

\<at an increasing price ([amount])>
\<(not modified by game speed)> -- If omitted, all stats are unique stats are multiplied by `gameParamters.gameSpeed.modifier`
\<if it hasn't used other actions yet>
\<for [amount] turns>


\<when killed within [amount <= 5] tiles of a city following this religion\> -- This should be more generalized somehow


These next parts will be included for mod makers to improve grammer and have no effect whatsoever:
\<,\>
\<and\>
\<if\>


</details>

**Comment by SomeTroglodyte** [comment]
Overwhelmed. Sorry, no capacity right now to even read this in a concentrated fashion.

You know I had _nightmares_ about these uniques lately? Wake up sweating and thinking 'a fundamental problem with current uniques is not only separation of function and display, but also of identity.' Meaning a unique should be identifiable out of context, otherwise bugs, hard maintainability and such stuff. My dreamstate had a very clear idea of a structure - extensible without us writing new code. Of course, trying to write it down was another matter entirely. I'll read this later and very likely find a lot of parallels.

**Comment by yairm210** [comment]
Conditionals have been go for a while :)

**Comment by xlenstra** [comment]
The only thing here that isn't implemented yet is the double filters `[{filter}{filter}]`, but it seems we have moved to having multiple uniques if we want this to be the case
