### ISSUE TITLE
The worker acts weird

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5098]
http://hastebin.com/raw/xodukogame

![Screenshot_20210905-200232_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/132135239-d1281c71-d1bd-4e8a-b57d-f3819cd4a195.jpg)

when you automate the worker i selected on the screenshot it goes two tiles south then in its other automated move it goes 2 tiles north again. i think this is a small symptom of a huge underlying problem

**Comment by will-ca** [comment]
It might be because you're about to get Calendar? Although, I don't see anything obvious that could be improved due to that.

**Comment by logicminimal** [comment]
> It might be because you're about to get Calendar? Although, I don't see anything obvious that could be improved due to that.

it happened in previous turns as well.

**Comment by xlenstra** [comment]
My guess is that the workers are trying to go to the same tile, and since there is a worker on that tile already, the order worker just kinda walks around it hoping that he will eventually go away. Still a bug, though

**Comment by logicminimal** [comment]
> My guess is that the workers are trying to go to the same tile, and since there is a worker on that tile already, the order worker just kinda walks around it hoping that he will eventually go away. Still a bug, though

i think it happened before that second worker appeared but i might be wrong as i dont remeber %99 of that game

**Comment by xlenstra** [comment]
So I finally decided to fully look into this, but the hastebin link has gone out of date.
Any chance you can copy+paste the save file here again?

**Comment by logicminimal** [comment]
> 
> 
> So I finally decided to fully look into this, but the hastebin link has gone out of date.
> Any chance you can copy+paste the save file here again?

will, cant do it now tho

**Comment by logicminimal** [comment]
> 
> 
> So, any save file to replicate this? We've since found some problems in the movement algorithms, so if not I'll declare this solved by other means

i guess i cant reproduce this exact thing but there is also a bug that made captured workers continue their work like they havent changed civilizations at all
