### ISSUE TITLE
"Adopt free policy" forces to pick a policy

### ISSUE THREAD

**Issue by i2324561w2** [yairm210/Unciv#5099]
**Platform**
Windows10x64

**Version**
3.16.11.

**Describe the bug**
I'm not so sure about what happened and I don't even know if it's intended, but I had "Adopt free policy" but every possible policy already taken, I entered the Renaissance era: I was forced to pick Freedom but I wanted a branch incompatible with Freedom.

**Expected behavior**
I would like to close the Policy choice panel, even at the cost of discarding the gifted policy.

Thank you.

**Comment by yairm210** [comment]
Not a bug, this is how free policies and techs work :)

**Comment by logicminimal** [comment]
> Not a bug, this is how free policies and techs work :)

i think there were policy and tech saving options in civ5? also the main problem about this is even if you dont pass the turn you cant get back to the game screen which causes a lot of negative stuff as you need to check stuff to adopt or research stuff

**Comment by AdityaMH** [comment]
Force to adopt free policy is not bug, but not forcing to pick unit promotion is bug (maybe intentional) or this was added on civ5 and civ5m but not in unciv.
