### ISSUE TITLE
ive thought of 2 uniques:

### ISSUE THREAD

**Issue by kingkarna1** [yairm210/Unciv#5101]
"[unitfilter] can fight when embarked" and also "cannot enter [tilefilter] until [techfilter or policyfilter]"

**Comment by xlenstra** [comment]
As these are modding requests, please put them in #3242 where we collect these kinds of modding requests

**Comment by kingkarna1** [comment]
how to do this? i thought i did it correctly?

**Comment by xlenstra** [comment]
We combine these modding requests into a single issue on GitHub, which was the link I sent you, not in separate issues. If you request on this page: #3242, we'll look into it in the future

**Comment by kingkarna1** [comment]
thx
