### ISSUE TITLE
Crash due to default starting era not existing

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5111]
The default for GameParameters.startingEra is "Ancient Era", and that _can_ be still active in a running game, without mods.
The new calls `ruleSet.eras[startingEra]!!` in some ~7 places crash because the ruleset does not have such an era.

Pushing a PR changing the default to match the actual name would be straightforward - but why wasn't all this not programmed defensively in the first place? I can't shake the feeling that something else was intended with #4809

**Comment by xlenstra** [comment]
> I can't shake the feeling that something else was intended with #4809

Nope, just me not checking my capitalization good enough :)
I'll push a PR to fix this momentarily

**Comment by SomeTroglodyte** [comment]
I'd still prefer `?.`..`?:` to `!!` in most cases involving any case of external (relative to the current scope) input. Even a guaranteed non-null where the reason is 10 lines away can very quickly be broken by some other team member coming along and not seeing the trap... Still, better than thoughtless lateinit's :roll_eyes: :grin: :laughing:
