### ISSUE TITLE
Feature Suggetion: Google Play Games or Google OAuth login

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#5115]
Why not consider allowing players to Login via Google Play Games or a Google OAuth instead of a randomly generated User ID?
It should not be that hard to making it compatible with current Ids also.

**Comment by logicminimal** [comment]
you could link your google play games account into some id without much work but i dont think if it is worth the time

**Comment by touhidurrr** [comment]
> you could link your google play games account into some id without much work but i dont think if it is worth the time

Loggin in Via Google Play Games will restore all you multipliayer games and Game Data.
Also you can also do cool UI tweaks like showing the avatars of people in a Multiplayer game.

**Comment by logicminimal** [comment]
> Also you can also do cool UI tweaks like showing the avatars of people in a Multiplayer game.

i personally wouldnt want this, too un-uncivy imo

**Comment by SomeTroglodyte** [comment]
- This is open source, and despite AOSP G00gle is FOSS-inimical, G Play games especially so

**Comment by touhidurrr** [comment]
Then How about Github, Google, Yahoo ... multiple login methods?
And an Unciv Id maybe.
The problem is it would need some kind of server handling logins.

**Comment by touhidurrr** [comment]
> > Also you can also do cool UI tweaks like showing the avatars of people in a Multiplayer game.
> 
> i personally wouldnt want this, too un-uncivy imo

It's not like Unciv cannot evolve.

**Comment by logicminimal** [comment]
> Then How about Github, Google, Yahoo ... multiple login methods?
> And an Unciv Id maybe.
> The problem is it would need some kind of server handling logins.

noooope we absolutely dont need this

**Comment by xlenstra** [comment]
What do you want to gain when logging in? 
More security so that you can't use other peoples accounts? For that we need some kind of server to check login details and send back the requested data, which needs to run somewhere and that is not free. I'm not interested in burning my own money for a free app, sorry.

Easier user interface so users don't need to hassle with user ID's? Could work, but would either require us storing login details somewhere, which again requires a server, or us handing over power to other apps. G00gle, not open-source, I have no interest in selling the data of our users to them. GitHub, almost nobody has that so wouldn't really add anything, same goes for Yahoo.

I don't see how logging in can be done safely in a useful way as-is.

**Comment by logicminimal** [comment]
> What do you want to gain when logging in? 
> More security so that you can't use other peoples accounts? For that we need some kind of server to check login details and send back the requested data, which needs to run somewhere and that is not free. I'm not interested in burning my own money for a free app, sorry.
> 
> Easier user interface so users don't need to hassle with user ID's? Could work, but would either require us storing login details somewhere, which again requires a server, or us handing over power to other apps. G00gle, not open-source, I have no interest in selling the data of our users to them. GitHub, almost nobody has that so wouldn't really add anything, same goes for Yahoo.
> 
> I don't see how logging in can be done safely in a useful way as-is.

by the way, is the player id cometely random? is there a premeasure to check for matching ids before giving a player one?

**Comment by xlenstra** [comment]
> > What do you want to gain when logging in?
> > More security so that you can't use other peoples accounts? For that we need some kind of server to check login details and send back the requested data, which needs to run somewhere and that is not free. I'm not interested in burning my own money for a free app, sorry.
> > Easier user interface so users don't need to hassle with user ID's? Could work, but would either require us storing login details somewhere, which again requires a server, or us handing over power to other apps. G00gle, not open-source, I have no interest in selling the data of our users to them. GitHub, almost nobody has that so wouldn't really add anything, same goes for Yahoo.
> > I don't see how logging in can be done safely in a useful way as-is.
> 
> by the way, is the player id cometely random? is there a premeasure to check for matching ids before giving a player one?

As far as I know, it is as random as you can reasonably expect from a computer. Due to its length, the probability of generating two exactly the same ID's is almost 0, and even if it happened, it wouldn't matter as ID's are only checked when joining a multiplayer game

**Comment by SomeTroglodyte** [comment]
Just look up how UUID's work, same here

**Comment by touhidurrr** [comment]
> What do you want to gain when logging in?
> More security so that you can't use other peoples accounts? For that we need some kind of server to check login details and send back the requested data, which needs to run somewhere and that is not free. I'm not interested in burning my own money for a free app, sorry.
> 
> Easier user interface so users don't need to hassle with user ID's? Could work, but would either require us storing login details somewhere, which again requires a server, or us handing over power to other apps. G00gle, not open-source, I have no interest in selling the data of our users to them. GitHub, almost nobody has that so wouldn't really add anything, same goes for Yahoo.
> 
> I don't see how logging in can be done safely in a useful way as-is.

I was just talking about alternatives. There is free services like Cloudflare Workers that Allows upto 100K free requests per day and a free KV Database that allow's the abiltiy to store upto 1B kv pairs each of 25 MB. Or Heroku maybe. I doesn't has any limits. People doesn't login everyday. So the traffic might not be that big.

An alternative of Using too much Web Traffic is to use it only for login and then the fetched data can be passed as it is now.

The point of logins is the abilty to backup data somewhere without any hassle. It's not like Using Icons from OAuth services will bother anyones privacy. And the current system is not that secure either and pretending someone else is very easy. Also its not like there is any rule that Open Source softwares cannot use OAuth.

Login has more effect on multiplayer game experience than it actually looks. I play Unciv Multiplayer regularly so I can tell how many times I have lost game data with the current system.

I am actually amazed that why nobody here doesn't sees any usefulness in it.

**Comment by SomeTroglodyte** [comment]
Well, now you've convinced me. You're welcome to implement it.

**Comment by yairm210** [comment]
Closing as "wontfix". 9 months in and nothing has happened, we don't feel that anything needs to happen -> nothing will happen in the future,
