### ISSUE TITLE
Bug: Notifications does not work properly

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#5116]
**Platform**
Android 10 and Android 11, arm64

**Version**
3.15.x to 3.16.x (too many to list)

**Describe the bug**
Notifications does not work properly. The Game notifies players to join the game regardless of it's their turn or not.

**To Reproduce**
Just exit a Multiplayer Game and wait for Notifications. You will get it always regardless if it is your turn or not

**Comments**
I reported this on Discord before. But maybe developers forgets but if there is no Issue about it. There is always the desire to close issues yourself when there is an Issue maybe. Chats are easy to forget.

**Comment by touhidurrr** [comment]
For those who might ask I was getting this before and after I updated my Android version. And its not encountered on a Virtual Environment. Nowadays all new Android Devices are arm64 based. I encountered it on Realme 3 Pro.

**Comment by yairm210** [comment]
I checked the code now, it's actually the part I know least in Unciv because it's all Android
The logic *seems* sound. It should only notify when either
A. You pause a game, it's multiplayer, and it's your turn
B. Of the multiplayer games saved in the folder, one of them has your ID as the current ID.

So my first question is - what do you mean by "exit a multiplayer game"? What exactly are you doing?
Second question, to @GGGuenni - how can I debug this code?

**Comment by GGGuenni** [comment]
Uh that's tough
Debugging that is really hard
As I've just finished my bachelor degree today, I will be back to work on Unciv tomorrow, though, so I can take a look at it 😁

Definitely need more info though
@touhidurrr do you get "normal" notifications? Or do you get multiple notifications at once? I heard of some occurrences of that but could not reproduce it. And you made sure there is really no game in the multiplayer list where it's your turn? Even when the game is maybe already over? I should definitely add the name of the first game found to the notification. That would probably help with debugging.

**Comment by yairm210** [comment]
Congrats! 🥳

**Comment by touhidurrr** [comment]
> I checked the code now, it's actually the part I know least in Unciv because it's all Android The logic _seems_ sound. It should only notify when either A. You pause a game, it's multiplayer, and it's your turn B. Of the multiplayer games saved in the folder, one of them has your ID as the current ID.

Maybe this is the problem. Normally you expect to get the notification of the game you are playing. Not all of them. Maybe we need a 'Get Notifications' making / joining a multiplayer game?

**Comment by GGGuenni** [comment]
> Congrats! 🥳

Thanks 😁

> Maybe this is the problem. Normally you expect to get the notification of the game you are playing. Not all of them. Maybe we need a 'Get Notifications' making / joining a multiplayer game?

So you had old games in the multiplayer list so there is not really a bug? Disabling notifications per game would be a possibility but you can also just delete all games you don't play anymore in the game settings.
The reason we traverse all games in the list and not just the one running is that you can play more than one game at once. I'm currently, for example,  playing three multiplayer games at once and want notifications for each of them.

**Comment by touhidurrr** [comment]
> Disabling notifications per game would be a possibility but you can also just delete all games you don't play anymore in the game settings.

Games can continue 250+ turns and several days easily. So, deleting all previous games is not possible. Also even after a game ends you might be wanting to keep the save as a momento. Things like that.

**Comment by yairm210** [comment]
So maybe disable notifications for games where someone has won

**Comment by GGGuenni** [comment]
> So maybe disable notifications for games where someone has won

Would be the easy way to go but also quite limited.

If that's ok, I would prefer to go the long way and implement a button in the game settings to be able to turn off notifications for every game separately. Auto-disable for a won game could be implemented additionally.
It will probably be asked for again in the future anyway so I can better do it now instead of doing it two times.

**Comment by jahodovykolac** [comment]
On the topic of broken notifications, after updating to 3.17.4, I receive notification like 15 minutes after opening the game. It says:
**An error has occured**
Multiplayer turn notifier service terminated.
It's not appearing when I turn off notifications, but that's not a good solution.

**Comment by GGGuenni** [comment]
> On the topic of broken notifications, after updating to 3.17.4, I receive notification like 15 minutes after opening the game. It says:
> **An error has occured**
> Multiplayer turn notifier service terminated.
> It's not appearing when I turn off notifications, but that's not a good solution.
> Also I have the same problem this issue is about

The error notification should contain a button that says something like "Copy trace log". Could you please post this trace log here?

**Comment by jahodovykolac** [comment]
> The error notification should contain a button that says something like "Copy trace log". Could you please post this trace log here?

Yes, it does contain it. I'll send it tomorrow. Also it only appears when I leave the app running in the background

**Comment by GGGuenni** [comment]
> java.lang.NullPointerException at com.unciv.ui.worldscreen.mainmenu.DropBox.downloadFile(DropBox.kt:72) at com.unciv.ui.worldscreen.mainmenu.DropBox.downloadFileAsString(DropBox.kt:76) at com.unciv.ui.worldscreen.mainmenu.OnlineMultiplayer.tryDownloadGameUninitialized(DropBox.kt:132) at com.unciv.app.MultiplayerTurnCheckWorker.doWork(MultiplayerTurnCheckWorker.kt:241) at androidx.work.Worker$1.run(Worker.java:86) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:818)

That basically means you can't connect/have an unstable connection to Dropbox, or the game you are asking for is not uploaded, and you literally can't download the game. 
Do you maybe have a really old game in the Multiplayer list, which probably got deleted earlier this year?
We currently do not (can we even? idk) distinguish between failed dropbox connection and a game that is not available, which is why both result in the notification worker being stoped.

**Comment by jahodovykolac** [comment]
Yes, one of the old games started suddenly saying 'Could not download game!', but as @touhidurrr says, it should be handled and not create a notification for a normal user that doesn't understand a thing about this.

**Comment by yairm210** [comment]
I think this is solved :)
