### ISSUE TITLE
Mod menu won't scroll properly

### ISSUE THREAD

**Issue by Alex25820** [yairm210/Unciv#5117]
**Platform** 
MacOS Big Sur 11.5.2

**Version**
3.16.12 downloaded JAR from GitHub.

**Describe the bug**
When attempting to scroll the mod list (Downloadable mods) using the mousepad or scroll wheel nothing happens. In order to scroll the menu you have to left-click (and hold) the menu whilst moving the mouse.

**To Reproduce**
1. Press the Mods button on the menu screen.
2. Wait for the mod list to load.
3. Attempt to scroll using mousepad or scroll wheel, nothing happens.

**Expected behavior**
The mod list scrolls up or down when scrolling on the mousepad or scroll wheel. (When doing the same action in game the game view zooms either in or out if this information helps.)

**Comment by SomeTroglodyte** [comment]
Yup, they're standard Gdx ScrollPanes not the AutoScrollPane I did ages ago. Maybe when I get around to reformat it for portrait. Still, you should know while certainly many contributors play more on desktop than an actual mobile, focus is on touchscreens. Not a bug, a nice feature request I'd say. Don't worry, unless I get fed up with the project entirely I won't forget.
