### ISSUE TITLE
Feature Suggestion: Update button, Mod search and Mod Sort

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#5118]
Describing each feature ...

**Update Button on Downloaded Mods:** If Update is available for a Downloaded mod a Button for Updating the Mod should appear. Cuurently only `Delete [Mod Name]` button appears. If you want to update it however you have to find it from the long list of Mods which can be intriguing sometimes.

**Mod search:** Exactly what it says. A search field to search Mods from the list.

**Mod Sort**: Sort Mods in ascending & descending order by Alphabetically or Update date.

**Comment by SomeTroglodyte** [comment]
1 - No. It's not too intuitive, I know, but you need both delete and update, so you get delete when the left column is selected and update when the same mod in the middle column is selected. They even scroll into view when needed. Might change with a total overhaul, not before.
2 - Thought of it
3 - Thought of it long ago
