### ISSUE TITLE
Do we want a zoomable Tech tree?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5127]
On a scale from BS to must-have - what's this:

https://user-images.githubusercontent.com/63000004/132259218-ebf23ff5-2278-4748-97a8-999bd7e5f954.mp4

**Comment by xlenstra** [comment]
As long as this doesn't use the scroll wheel on desktop it doesn't hurt. It looks kinda cool fully zoomed out, and checking icons on smaller screens by zooming in might also be useful

**Comment by SomeTroglodyte** [comment]
Of course the wheel zooms - same widget as main map. Must be a facepalm-level blindness that I don't see why that would be bad? Right now the wheel scrolls the thing a few units up and down mostly, not even left or right. What the trivial patch can't do is to zoom while keeping the place under the mouse centered - the worldscreen doesn't either, but there it's OK.

**Comment by xlenstra** [comment]
True, I guess scrolling for zooming does make sense. I would prefer it if the scroll wheel scrolls sideways, as that is most often what you want to do in the tree anyway, and is already the behaviour shown so when playing at large resolutions (1920x1280 for example). Just my two cents

**Comment by SomeTroglodyte** [comment]
Ah yes the default ScrollPane scrolls sideways if there is not enough content to scroll vertically. But that depends on window, world resolution - and tech tree size. Anyway, shutting down for a day.

**Comment by SimonCeder** [comment]
On desktop I'd normally expect wheel to scroll horizontally, shift+wheel to scroll vertically, and ctrl+wheel to zoom.

**Comment by yairm210** [comment]
Looks good!

**Comment by SomeTroglodyte** [comment]
Ouch! Now i'm obliged to polish this to perfection...

@Simon - actually that sounds very specific to some office package. I'd expect the wheel to go vertical - as a generic prejudice. With Ctrl, yes, that seems quite universal. I'll think about it. You know there's wheels that also go sideways? Wonder if that can be caught with Gdx...

**Comment by SimonCeder** [comment]
Woops, I meant wheel to scroll vertically, and shift+wheel to scroll horizontally, of course. You see that in plenty of programs that have horizontal scroll bars, most text and image editors for example.

**Comment by yairm210** [comment]
> Ouch! Now i'm obliged to polish this to perfection...

Absolutely not, i'd much rather we close some of the existing 100+ issues than open new ones 😅

**Comment by SomeTroglodyte** [comment]
Those 100+ are really off-putting, aren't they? Go look at the repo for notepad++ for some relief. I would have no problem to abuse collaborator rights and go mass-close lots of them with snarky remarks, but then I might damage our reputation... (I imagine me taking a screenshot of this repo, gimping a movie of it where the issue counter rapidly but nonlinearly drops to zero and below, with my suggestion of `Remove Heresy.mp3` as soundtrack)

Anyway, this one has served its purpose.

> Woops ... most text and image editors

Yup, Gimp too. Learned something!
