### ISSUE TITLE
My city unlimitedly keep increasing 1 pop/turn

### ISSUE THREAD

**Issue by Eganburg** [yairm210/Unciv#5135]
**Version**
3.16.10

My city keep increasing 1 population per turn, I don't know why this happen. (also it doesn't show characters anymore, just character's symbols).

![Screenshot_20210908_115844_com unciv app](https://user-images.githubusercontent.com/61727125/132449489-6c445881-0dcd-45e2-817e-f0c11a266d65.jpg)

**Comment by xlenstra** [comment]
This is very likely the 3.16.10 city-state bug. Check if you're friends with a maritime city state, providing you with 20 billion food/turn in your capital.
Fixed in 3.16.11.
