### ISSUE TITLE
Unit's name becomes "instanceName" when unit has been renamed to anything

### ISSUE THREAD

**Issue by navyblue44** [yairm210/Unciv#5139]
**Platform**
Operating system type, major version, architecture (64/32 bit).
- Windows 10 Build 2004 (64-bit)
- Android 8.1.0 (64-bit ~~architecture unsure~~)

**Version**
Where you got the game and the exact version number.
- 3.16.12, from this GitHub repository on PC and from Google Play Store on Android

**Describe the bug**
- Renaming any unit that can be renamed doesn't really rename it -- rather, it is renamed to "instanceName" regardless of what was inputted. (As an example, renaming a Warrior to "test" *should* rename it to "test", but instead it is renamed to "instanceName")

**To Reproduce**
1. Start any game
2. Select any unit that can be promoted
3. Attempt to rename selected unit to any name except "instanceName"
4. Bug happens

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
- None; this happened on both devices in both generated and custom maps

**Expected behavior**
- It *should not* be "instanceName" unless if it was intended to be renamed as "instanceName"

**Screenshots**

**Additional context**

**Comment by SomeTroglodyte** [comment]
![image](https://user-images.githubusercontent.com/63000004/132516706-f51ece40-fe15-49ba-8996-c28bd49aa118.png)

**Comment by SomeTroglodyte** [comment]
By the way, the names are not lost, you just need the next version to see them again.
