### ISSUE TITLE
Civ issues (a Civ should be defeated ONLY when it loses their last city)

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#514]
A Civilization should be considered defeated it they lose all their cities, just like in the original Civilization games.

**Comment by yairm210** [comment]
Isn't it already thus?

**Comment by ninjatao** [comment]
There is one corner case: If civ has a settler when last city is conquered, it is not defeated. Then you can capture the settler to wipe out the civ. BUT in this case, no "XXX is defeated!" info is poped up.
This problem existed one month ago. I'm not sure if it still exists.

**Comment by yairm210** [comment]
Gotcha

**Comment by yairm210** [comment]
@smashfanful please change the name of the issue to be more meaningful

**Comment by Smashfanful** [comment]
> @Smashfanful please change the name of the issue to be more meaningful

Done so.

**Comment by Smashfanful** [comment]
> There is one corner case: If civ has a settler when last city is conquered, it is not defeated. Then you can capture the settler to wipe out the civ. BUT in this case, no "XXX is defeated!" info is poped up.
> This problem existed one month ago. I'm not sure if it still exists.

It still exists, I thought there was such a message when there were still units, so it felt like I had to conquer all cities AND destroy all units.
