### ISSUE TITLE
City states keep ascending to godhood.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5143]
**Platform**
Android

**Version**
3.16.10

**Describe the bug**
Every turn, city state ally yields seem to increase.

This seems to happen with any save I load.

Loading a new save from the menu doesn't fix it. The city states still have obscene yields.

Closing the app and restarting it does reset it. Yields return to their correct values then and begin increasing anew, so it doesn't seem to be tied to any particular save files.

**To Reproduce**
1. Play a couple turns.
2. Check city state yields.

**Expected behavior**
City states should not be indefinitely powerful juggernauts of culture, agriculture, and happiness.

**Screenshots**
![Screenshot_20210906-114814](https://user-images.githubusercontent.com/37680486/132561249-513af16c-328b-4f2d-bec4-8e39088166e5.png)
![Screenshot_20210906-114801](https://user-images.githubusercontent.com/37680486/132561255-df3b1167-e7d9-4cf9-abef-7561fe3657fb.png)
![Screenshot_20210906-114843](https://user-images.githubusercontent.com/37680486/132561262-1801fd34-fd85-43d1-a5ca-5411a90caa4f.png)
![Screenshot_20210906-114735](https://user-images.githubusercontent.com/37680486/132561263-45f801bc-68d6-45c1-b86b-9406ee88c43a.png)

This leads to... Interesting yields of culture and happiness.

![Screenshot_20210906-114718](https://user-images.githubusercontent.com/37680486/132561265-d99195d5-8573-47dd-b4d5-e3f6dc006e88.png)
![Screenshot_20210906-114709](https://user-images.githubusercontent.com/37680486/132561267-61f3cbfa-874a-41c1-9a12-96f418579b39.png)

Military unit gifts seem to behave normally even when allied though, even though they're also listed repeatedly.

**Additional context**

This originally happened in a game where I abused quick taps to get incompatible social policy trees, but it has also happened in every game since then, even by playing normally.

![Screenshot_20210906-114917](https://user-images.githubusercontent.com/37680486/132561260-c8ffb75c-f558-4722-82dc-78a81e83662b.png)

**Comment by xlenstra** [comment]
Known bug, fixed in 3.16.11
