### ISSUE TITLE
No religion points...

### ISSUE THREAD

**Issue by Computadoralibre** [yairm210/Unciv#5145]
Religion is part of culture, it shouldn't have different points in its simulator. 

That's an error from the creators of civ5 religion points mechanics make no sense from the point of state.

**Comment by HeavyTank-1** [comment]
Culture is often defined by religion, and being such different mechanics in the game, they should be separated.

**Comment by yairm210** [comment]
It sounds like you disagree with the Civ V mechanic itself.
Unciv is sticking with Civ V mechanics, as this is the primary goal of the project.
