### ISSUE TITLE
Icon for Enhancer Beliefs sought

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5152]
Civilopedia decorates beliefs by their types. An image for Enhancer Beliefs is needed. Suggestions:
![image](https://user-images.githubusercontent.com/63000004/132604269-5467713d-f433-4df0-a0da-d3db78fedd53.png)

(Yes I know Hamlet is not about religion, but it's cute, ain't it?)
Any one of these to prefer? Some better suggestion (with attribution)?

**Comment by SimonCeder** [comment]
Nr 3 seems good, goes well with the Founder icon.
