### ISSUE TITLE
Completing Exploration Policy gets 3 Great Admiral units in lake tiles not connected to sea.

### ISSUE THREAD

**Issue by stixZman** [yairm210/Unciv#5157]
**Platform**
Android

**Version**
PlayStore 3.6.12

**Describe the bug**
When completing Exploration Policy, one of the rewards is to get 3 Great Admiral units. In the game from the attached screenshot, the capital has a few lake tiles not connected to the sea so these units are a complete waste. In this case, it is posible to create a temporary city in the desert tile to get the Great Admirals out of the lake, but it is desirable that they spawn only in coast or ocen tiles to avoid this situation.

**To Reproduce**
Complete Exploration Policy with the capital next to lake tiles not connected to sea.

**Expected behavior**
Spawn naval units only in coast or ocean tiles

**Screenshots**
![great_admiral_bug](https://user-images.githubusercontent.com/54929928/132670128-8d24514d-eacd-4479-836a-c9f09203d22c.png)

**Comment by navyblue44** [comment]
I see you used RekMOD. Pretty sure Great Admiral isn't part of vanilla UnCiv.

**Comment by logicminimal** [comment]
> I see you used RekMOD. Pretty sure the Great Admiral units and the Exploration policy isn't part of vanilla UnCiv.

there are great admirals in civ 5 though

**Comment by yairm210** [comment]
This is a rekMod bug, but one that can't be fixed from within rekMod.
Interesting.

**Comment by SomeTroglodyte** [comment]
I see it as one of the nicer - because trickier - challenges of the game, same as subs getting marooned in lakes after razing the city they were in. I vote we `wontfix` instead of letting the `placeUnitNearTile` or somesuch code avoid lake for water units - which might be surprisingly simple.

**Comment by yairm210** [comment]
Fair enough.
