### ISSUE TITLE
Can you let ai Hit less City state

### ISSUE THREAD

**Issue by dnddnbdodjd** [yairm210/Unciv#5162]

**Comment by logicminimal** [comment]
no

**Comment by yairm210** [comment]
I'm entirely unsure what this is about. Explain?

**Comment by dnddnbdodjd** [comment]
> 我完全不确定这是关于什么的。解释？

I just think ai beat City state tendency Too high

**Comment by yairm210** [comment]
I see
The AI already has a modifier to do this less often, maybe it's not high enough. I'll poll this.
