### ISSUE TITLE
Mod is preventing the game to work. 

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#5167]
**Platform**
Windows 7 / 64 bit

**Version**
3.16.13-patch1

**Describe the bug**
The title says it all. The mod won't let the game to boot up. Idk how or why, I tried troubleshooting the problem, but I cannot find and figure out why the problem exists. This mod is a mod that I made btw.

[Wars Mod.zip](https://github.com/yairm210/Unciv/files/7141531/Wars.Mod.zip)

**To Reproduce**
1. Download the mod that I made and put it in the mod files.
2. Boot up the game.

**Expected behavior**
The game won't simply start.

**Additional context**
Strangely enough, this problem does not occur on mobile.

**Comment by SomeTroglodyte** [comment]
> This mod is a mod that I made

Ha! Sounds like you're shooting yourself in the feet - but seriously, I'll take a look. The game should lambast and ridicule you for silly mistakes, not fail... I could bet your era file is bad.

**Comment by SomeTroglodyte** [comment]
Immediately obvious detail - got Images but no atlas. I've still got that documentation to-do somewhere. And yup, no era file.

```
Exception loading mod 'Wars Mod':
  Unable to convert value to required type: 208 0 (java.lang.Integer)
Serialization trace:
innerColor (com.unciv.models.ruleset.Nation)
  (Source file Json.java line 1167)
```

So, yes, your "foot" thingy. But - that's from a session where our part works "perfectly", namely it loads the mod, catches the error, logs it to the console, then _ignores_ the mod. No crash...

So - could be the W7 factor. You're running the exe from the x64 package? Tried running the jar with you own JRE instead? As far as I know, the bundled exe/jre won't output console logs, which can be very useful when modding, but running `java -jar Unciv.jar` will.

**Comment by SomeTroglodyte** [comment]
OK, I can say this:
- Your mod will _not_ crash the packaged exe Unciv once it includes the proper atlas files and they're current relative to the png's in the Images folder.
- Your mod will not crash the jar run from a system-installed JRE, which allows atlas generation. 
- It will then be invisible _at least_ until you fix that non-number. And fix the eras.
- It is not a W7 issue.

@yairm210  can't we do something so the exe doesn't completely suppress console output?

**Comment by yairm210** [comment]
I'll be honest, the executable wrapper for the jar is a bit voodoo for me.
I know what it does - namely run a jvm with the packed jre files, and run the Unciv jar on that jvm.
But I have no idea how it does that.
The [Packr magicians](https://github.com/libgdx/packr/issues/104) say to use the latest version of Packr, which I'm currently using for the Linux builds but not for the Windows 64 builds. We'll try that, then

**Comment by SomeTroglodyte** [comment]
It would be OK to ignore that if there were some command line option to reinstate logging... After all, Windoze won't be an issue much longer, in the 25th century it will be forgotten and good riddance. And - there is! Thanks for the link :wink:

So `Unciv.exe --cli --console --verbose` now tells us -> `Exception in ImagePacker: C:\Users\***...***\jre\bin\jpeg.dll: Can't find dependent libraries` - but killing that dll as we don't need jpeg support at that point won't work, it insists on it being available...

**Comment by SomeTroglodyte** [comment]
Now where the Freak is depends64.exe in a current M$ Vitzuahl Schtudioh? Not that I really believe the linking of that dll will really tell us what it expects.

**Comment by NoviceCoder2000** [comment]
Ok I see, I'll fix it when I have the time.

**Comment by SomeTroglodyte** [comment]
Yes, confirmed. It will pack the missing atlas for this mod, and have console output without those options.

@NoviceCoder2000  - with that new release you can see that message "208 0 is not a number" (and any future similar problems) more easily, just run the exe from a command prompt.

**Comment by NoviceCoder2000** [comment]
Ok got it.
