### ISSUE TITLE
Generate translation files generates empty files.

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#5168]
I tried on 2 different devices, always ending up with he same result. Clicking generate translation files in the main menu generates translation files, but they are empty. Furthermore, it removes all strings from already existing files.
![z](https://user-images.githubusercontent.com/30041793/132820131-2fbd700e-6281-475c-bc21-cd814f7dbba6.png)

**Comment by SomeTroglodyte** [comment]
Is that button even _supposed to_ work for mods...? I vote we move it to the "secret" page for starters.

**Comment by yairm210** [comment]
It is supposed to work for mods. This is a bug.

**Comment by SomeTroglodyte** [comment]
Confirmed. Additionally, it shouldn't create a translations folder for mods that don't already have one.

Side note: @ravignir , the system to separate textures into several atlases should work in mods, too - at least the packer. Not sure about the loader, might check later. Rekmod surely could use it.

**Comment by SomeTroglodyte** [comment]
So far: This cannot ever have worked - is the superficial prejudiced impression. 

First it looks for the mod's jsons in the wrong folder. Then it arrives at TranslationFileWriter line 82 and does nothing because `linesFromTemplates` is _always_ empty thanks to line 64. And line 183 (I remember moving that - but it was always the vanilla ruleset) says the unique params will be named without knowledge of the actual mod itself, so in a total overhaul mod it would probably name most unique params "[param]"...

Anyone remember a version where this actually worked as can be expected? I'd like to read the diff...

**Comment by ravignir** [comment]
I actually reported it over a year ago on discord. All I can say is it was not working on 3.10.4.

**Comment by yairm210** [comment]
We could just remove this if it looks like it never worked

**Comment by SomeTroglodyte** [comment]
Oh my. Multiple bugs before `readAllLanguagesTranslation` would even read mods correctly - e.g. one language completely overwriting the last or `createTranslations` using `containsKey` on vanilla instead of the mod...

But nevertheless I _do_ get the feeling this can be done in a few hours.

**Comment by SomeTroglodyte** [comment]
Getting close. Questions:
- I now do write the completionPercentages for mods - I'd wiki that they're for the modder's reading only and can be removed for publication. As a tool category 'why not it's free' -> :+1: or :-1:?
- Only texts actually used in the mod are written, and no language is written unless the file already exists and has at least one `x = ` line.
- For texts that have no translation in the mod's translation files but *do* in the base game, the base translation is copied with a comment indicating that. These are in case the modder wants a different translation. Problem: The _next_ run doesn't distinguish and treats it as normal removing the comment. Alternatives: Do not write the line at all, even the 'requires translation', if it exists in base (unless already translated). Or: re-write the 'copied' comment if found but still identical to base.

<details><summary>Example</summary>

```

#################### Lines from Buildings ####################

Holodeck = Holodeck

 # Requires translation!
[amount]% of food is carried over after population increases = 
Breeders = Bruttanks


#################### Lines from Nations ####################

Aliens = Aliens
Zyxxyz = Zyxxyz
Resistance is futile! Prepare to be assimilated! = Widerstand ist zwecklos! Assimilation ist unvermeidbar!
You want to play? Very funny! = Der Kleine will spielen? Wie drollig!
 # Requires translation!
How is it possible that those Apes hurt us? The galactic senate will take care of them. = 
 # Requires translation!
As superior galactic entities, you are not worthy of our attention. = 
 # Requires translation!
We bestow you the honor of this trade offer. = 
How are you doing? = Wie steht's?
What do you want now? = Was denn nu schon wieder?
Brainiacs = Eierköpfe
 # Requires translation!
[stats] in capital = 
 # Requires translation!
[stats] in all cities = 
 # Requires translation!
+[amount]% Production when constructing [unitType] units = 
 # Copied from Vanilla translations:
Double quantity of [resource] produced = Doppelte Menge von [resource] produziert
 # Copied from Vanilla translations:
[unitType] units gain the [promotion] promotion = [unitType] Einheiten erhalten die [promotion] Beförderung
 # Copied from Vanilla translations:
[stats] from every [tileImprovement] = Alle [tileImprovement] geben [stats]
We come in peace! = Wir kommen in Frieden!
This is an overpowered joke nation. Set Phasers to Obliterate!! = Dies ist eine überkandidelte Spaß-Nation. Phaser auf Obliteration einstellen und loszappen!
The Hive = Das Nest
Q'Throczan = Q'Throczan
Q'Chovex = Q'Chovex
Q'Imphet = Q'Imphet
Q'Omphead = Q'Omphead
Q'Grecoks = Q'Grecoks
Q'Vrelzieks = Q'Vrelzieks
Q'Vronens = Q'Vronens
Q'Aerlae = Q'Aerlae
Q'Phulnoith = Q'Phulnoith
Q'Creved = Q'Kreprt
Q'Xirqen = Q'Xirqen
Q'Gax = Q'Gax
Q'Threqals = Q'Threqals
Q'Bhilmuk = Q'Bhilmuk
Q'Mazea = Q'Mazea
Q'Zomirs = Q'Zomirs
Q'Drorkrex = Q'Drorkrex
Q'Honkrath = Q'Honkrath
Q'Zulgra = Q'Zulgra
Q'Vahars = Q'Vahars
Q'Crindith = Q'Crindith
Q'Raavraes = Q'Raavraes
Q'Bhoknais = Q'Bhoknais
Qho'Qru = Qho'Qru
Q'Dateatz = Q'Dateatz
Q'Elnad = Q'Elnad
Q'Izien = Q'Izien
Qol'Ell = Qol'Ell
Q'Dhihien = Q'Dhihien
Q'Naquiel = Q'Naquiel
Q'Ugneon = Q'Ugneon
Q'Straquks = Q'Straquks
Q'Nulptr = Q'Nulptr
Q'Ohfahl = Q'Ghuelle


#################### Lines from TileImprovements ####################

 # Requires translation!
Cannot be built on bonus resource = 
 # Copied from Vanilla translations:
Cannot be built on [tileFilter] tiles = Kann nicht auf [tileFilter]-Feldern gebaut werden
 # Copied from Vanilla translations:
[stats] once [tech] is discovered = [stats] sobald [tech] entdeckt wird
Penguin Hatchery = Pinguin-Brutstätte


#################### Lines from UnitPromotions ####################

Cold heart = Kaltes Herz
 # Copied from Vanilla translations:
+[amount]% Strength in [tileFilter] = +[amount]% Stärke in [tileFilter]
 # Copied from Vanilla translations:
Double movement in Snow, Tundra and Hills = Doppelte Bewegung in Schnee, Tundra und Hügeln


#################### Lines from Units ####################

Phasers = Strahlenschütze
 # Copied from Vanilla translations:
Ranged = Fernkampf
```
</details>
