### ISSUE TITLE
One specific extension mod incorrectly considered "deprecated" by the game

### ISSUE THREAD

**Issue by navyblue44** [yairm210/Unciv#5170]
**Platform**
Operating system type, major version, architecture (64/32 bit).
- Windows 10 Build 2004 (64-bit)

**Version**
Where you got the game and the exact version number.
- 3.16.13-patch1, from this GitHub repository

**Describe the bug**
- The game incorrectly assumed that [this](https://www.github.com/shannaurelle/ph-bonifacio-unciv/) specific extension mod is "deprecated", evident by the brick red "Deprecated until update conforms to current requirements" text, and thus is not visible and cannot be downloaded from the list (but can be downloaded via URL) if it hasn't been downloaded before in the device.

**To Reproduce**
1. Because the mod cannot be downloaded via selecting it from the mod manager, copy the mod's repository link and download it via URL
2. Select the downloaded mod ("ph bonifacio unciv")
3. The brick red text happened to exist *in an extension mod, not a base ruleset mod*

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
- None

**Expected behavior**
- If anything, the mod should be visible in the downloadable mods list and that brick red text shouldn't even exist

**Screenshots**
![2021-09-10 17_12_35-Unciv](https://user-images.githubusercontent.com/33913874/132843271-1a158558-35a0-4692-aad8-68231398f6ad.png)

**Additional context**
- The repository itself is labelled as "deprecated" by the game, as tested with a separate repository with the same files as the original. The separate repository is visible in the mod list, while the original repository isn't. (The separate repository was deleted shortly after testing.)

**Comment by navyblue44** [comment]
(ignore the multiple iterations of the mod and a certain "RekMOD_beta" lol)

**Comment by xlenstra** [comment]
My bad, sorry for that. I kinda hurried when adding mods to this list and just looked at the last update date, and basing it solely on that. I've since gone through the list again and removed all extension mods, donor should be playable once again in 3.16.14

**Comment by xlenstra** [comment]
> My bad, sorry for that. I kinda hurried when adding mods to this list and just looked at the last update date, and basing it solely on that. I've since gone through the list again and removed all extension mods, so it should be playable once again in 3.16.14
