### ISSUE TITLE
City state icons show up as blank plain cs colors in the latest version named windows something

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5172]
signed apk on android

**Comment by AdityaMH** [comment]
Reported on discord, before.

**Comment by SimonCeder** [comment]
It's because the game.atlas is outdated in that release. Which is strange because I thought those files were always regenerated for each release. But perhaps not this one since it's something of an extra inbetween release.

**Comment by logicminimal** [comment]
closing this as it happened just because the atlas didnt update itself, will be fixed in the next version hopefully
