### ISSUE TITLE
All names I have given to my military units during the game are now displayed as "instanceName"

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#5174]
**Platform**
Android

**Version**
3.16.12

**Describe the bug**
All specific honor names I given to my units in promotions are now displayed as "instanceName"

**To Reproduce**
See screenshot

**Expected behavior**
To see original names given to units in honor

**Screenshots**
![Screenshot_2021-09-10-19-40-13-637_com unciv app](https://user-images.githubusercontent.com/86048557/132888251-b4c5781c-902f-43f5-a786-0ca2d65309a6.jpg)

**Comment by xlenstra** [comment]
Thanks for your report. This is a known bug, which will be fixed in 3.16.13
