### ISSUE TITLE
Can I Add Great Works?

### ISSUE THREAD

**Issue by Interdice** [yairm210/Unciv#5181]
I know it is part of BNW, but great works are incredibly important to civ 5. This seems like a challenge to add to the game and in a few weeks i will have quite a bit of time on my hands so i might be able to add it.

**Comment by logicminimal** [comment]
go ahead, we can just disable it in vanilla until we get bnw and some mods might extensively use it.

**Comment by ravignir** [comment]
but great works require tourism. I guess that might be as tricky to develop as religion if not more.

**Comment by xlenstra** [comment]
Though we're in principle aiming for G&K, I won't stop you from implementing anything you want. A few notes though:
- As we're aiming for G&K (for now), this should be disabled unless activated by a mod. The easiest way to do that is to check for a unique in the mod options
- Keep in mind moddability, it should be easy for mod makers to provide great work slots to different wonders/buildings, or have certain improvements/buildings/units provide great works. Using uniques might be the easiest way to accomplish this
- The UI should be intuitive and mobile-friendly
- Keep PR's small: don't implement everything in a single massive PR with 2000 changed lines, as that will be almost impossible to review
- The entire system for great people will be overhauled at some point in the future to allow for more moddability, details of what will change can be found in a comment by Yair in #4265. Although you don't have implement all these notes, do try to make it relatively easy for additional great writers/artists/musicians to be converted to this system when this is implemented.

**Comment by Interdice** [comment]
@ravignir I can't guarantee i will do it but I will try. 

@xlenstra i will keep what you said in mind. BTW, are you saying the end user has to download an external mod to be able to use the great work features?

**Comment by xlenstra** [comment]
> @xlenstra i will keep what you said in mind. BTW, are you saying the end user has to download an external mod to be able to enable use the great work features?

Yes, as we're currently aiming for G&K and not for BNW. Later, when we're done enough with G&K we'll change this up, but as we would still like to allow for G&K to be run we would then need a unique to disable it. For now, a unique to enable it for mods is the way to go.

**Comment by yairm210** [comment]
If possible, please close existing issues rather than add features... But I won't stop you either. Remember to document this mechanic in the wiki!
