### ISSUE TITLE
Exclude specific buildings from autobuild?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5183]
**Is your feature request related to a problem? Please describe.**
> same with spaceship factories, i cant build a damn rocket artilerry because my cities with low prod decide to construct space age factories in villages
https://github.com/yairm210/Unciv/issues/4697#issuecomment-917428943

**Describe the solution you'd like**
Maybe a list, per-save and per-city, of buildings and units that are prohibited from autobuild.

Maybe a game setting to not autobuild anything that consumes resources.

**Additional context**
This isn't Civ V, but neither is auto-production AFAIK.

Beware effect on AI behaviour. Similar: #5113

**Comment by yairm210** [comment]
Copy of #3296
