### ISSUE TITLE
CN Tower does not provide free Broadcast Tower to cities despite this is declared in this wonder description in civilopedia

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#5185]
**Platform**
Android

**Version**
Google Play, 3.16.12

**Describe the bug**

The CN Tower wonder is declared as giving free Broadcast Tower to all cities, but is not doing so

**To Reproduce**
1) load the savefile [from here](https://disk.yandex.ru/d/hudcMrHhwJQJew) 
2) find Murmansk city in Russia, it has CN Tower built
3) find Tver city nearby Murmansk, it still has Broadcast Tower in construction queue and does not have it in the list of city buildings already built in the city.  Also there are several other cities wo Broadcast Tower

**Expected behavior*
CN tower should do what is declared as a feature of this Wonder

**Comment by SomeTroglodyte** [comment]
yandex.ru? No thanks, don't trust them.

**Comment by SomeTroglodyte** [comment]
Note the turn where the CN was _completed_ is relevant for the version number here, not the version you're playing now and using to look for BT's. I suspect you built the CN way before the last update - could that be true? The _current_ code looks OK on first glance - if it were fundamentally bad, free Libraries Lighthouses Gardens Amphitheaters Walls Mosques Castles or Spaceship Factories wouldn't work either. But - it's a one-time trigger, therefore see above.

@ X: What does `// Filtered by the way uniques our found` mean? Sounds very Bork, or Yoda, and eludes me completely.

**Comment by Bershcomp** [comment]
> yandex.ru? No thanks, don't trust them.

Who are those "them" who you do not trust? 
The link I provided is to the savefile on my cloud storage in disk.yandex.ru
You may trust me that my link is save to download and explore. 
Yes, it is very probably that CN was built before the current version where I realised that the issue exists. I will try to find the savefile with one step before CN built. And will retest that save with current version. 

If this hypotesis is proved, there will be another question to the code design.From your answer I suspect that the moment of CN is finished is the event that triggers to add BTs to the cities. Am I correct that the initiation of the game on load from the savefile does not review again the dependencies between Wonders and it's consequences so BTs are not triggered to appear by the CN-containing savefile load event? For example, all temples were replaced by amphiteaters when I loaded savefile after update to the version where amphiteaters were first time introduced. So the world was rebuilt on the savefile load and rebuilt with new rules applied.

**Comment by xlenstra** [comment]
> @ X: What does `// Filtered by the way uniques our found` mean? Sounds very Bork, or Yoda, and eludes me completely.

My first instinct is that it should read `// Filtered by the way uniques are found`, but I'll check in the code to make sure

**Comment by logicminimal** [comment]
normally the cn tower doesnt gove away free broadcast towers, it provides a broadcast tpwer in all your cities if u have the cn tower, which means all of the free ones will get lost and transferred to the conqueror when your coty with the tower gets conquered

**Comment by SomeTroglodyte** [comment]
I do not allow code from third parties to run on my box or browser unless i can check why that code is needed and trustworthy - and want to. And why should I want to on a site I can't read or even find the imprint?

Another thing: The one-time character of the unique also means newly founded cities do not get the benefit. No idea whether that conforms to the original rules or not. If not - *then* we have a bug.

> game on load

If some game data needs update due to Unciv updates, we usually have compatibility code in place for a few versions. Converting Temples to Amphitheaters was such a case.

**Comment by Bershcomp** [comment]
> normally the cn tower doesnt gove away free broadcast towers, it provides a broadcast tpwer in all your cities if u have the ..... 

Should CN be reflected in the all cities as free BT in the city's building list? Or there should be just an effect of BT applied to the city, but no BT in the list? 
Should CN still allow to add BT to the construction queue in those cities?

**Comment by Bershcomp** [comment]
> I do not allow code from third parties to run on my box or browser... 

Ok, what way to get my savefile would you prefer? 


> Another thing: The one-time character of the unique also means newly founded cities do not get the benefit.

If it works this way then civilopedia needs correction. Now it say "..to all cities", but the workway you described better fits the formula " to all existing cities".
Anyway, Tver in my example existed even before the city where CN was built

**Comment by logicminimal** [comment]
> > I do not allow code from third parties to run on my box or browser... 
> 
> Ok, what way to get my savefile would you prefer? 

hastebin

> 
> 
> > Another thing: The one-time character of the unique also means newly founded cities do not get the benefit.
> 
> If it works this way then civilopedia needs correction. Now it say "..to all cities", but the workway you described better fits the formula " to all existing cities".
> Anyway, Tver in my example existed even before the city where CN was built
> 

in civ 5 it isnt a gift bonus to all cities but you just get bc towers in all your cities when you are the one with access to the cn tower, you lose it, you lose the free towers

**Comment by logicminimal** [comment]
> I do not allow code from third parties to run on my box or browser unless i can check why that code is needed and trustworthy - and want to. And why should I want to on a site I can't read or even find the imprint?

isn't it just the save file?

**Comment by xlenstra** [comment]
At this point it might be worthwhile to create a `CivConstructions` class, for effects like these that provide bonuses to all current and future cities, and may also be removed. This class could then also contain the `cultureBuildingsAdded` and `specificBuildingsAdded` and functions related to them currently residing in the `PolicyManager` class, as well as the `boughtConstructionsWithGloballyIncreasingPrice` in the `CivilizationInfo` class, which could then also be renamed and refactored into a `Counter`. I'd love to work on this, but currently don't have the time, so anyone else is free to pick this up

**Comment by Bershcomp** [comment]
Retested it with current version on the savefile where CN is finishing on the next step. 
Bug exists. 
Neither BT building appeared in the city (Tver is the one I was checking it in) nor culture multiplier of BT was applied to the city culture. The "CN test - Russia - 1070 turns" savefile is in this cloud folder
https://disk.yandex.ru/d/suNWIunXjclLow

Direct link to the file
https://disk.yandex.ru/d/ojlmL4vSQTEGFA

**Comment by xlenstra** [comment]
> At this point it might be worthwhile to create a `CivConstructions` class, for effects like these that provide bonuses to all current and future cities, and may also be removed. This class could then also contain the `cultureBuildingsAdded` and `specificBuildingsAdded` and functions related to them currently residing in the `PolicyManager` class, as well as the `boughtConstructionsWithGloballyIncreasingPrice` in the `CivilizationInfo` class, which could then also be renamed and refactored into a `Counter`. I'd love to work on this, but currently don't have the time, so anyone else is free to pick this up

On second thought, I do have some time, so I'll do this which will simultaneously solve this issue as well
