### ISSUE TITLE
Implementation of stat icons next to correspondent texts

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#5188]
I see there are already some examples in-game (![Screenshot_20210911-223458_UnCiv.png](https://user-images.githubusercontent.com/78449553/132971196-8a7cedbd-680a-4dda-b04c-85974d5e1f09.png)

So it would be nice to have it for everything else. (I guess there could be a detector for the word and it automatically adds the emoji, idk)

This, as in the original game, makes knowing what the text is about easier.

![Screenshot_20210911-223821_Google.png](https://user-images.githubusercontent.com/78449553/132971243-d73c77bd-1c5c-4128-90bd-51662d291367.png)

**Comment by ArchDuque-Pancake** [comment]
Forgot, I think where this should be is at city constrution screen and civilopedia

**Comment by SomeTroglodyte** [comment]
You can already use most (those needing only one codepoint in UCS-16, that is, their U- hexcode is 4 digits) unicode symbols in your own translations or mods if you want, they'll be pulled from the system's font on demand, so whether they're displayed or not depends on the system.

The special emojis we build from our textures are listed [here in Fonts.kt](https://github.com/yairm210/Unciv/blob/70c3b4bd6504dcdcda13937f17fae570117562b7/core/src/com/unciv/ui/utils/Fonts.kt#L157) - they should also be no problem in translations and mods.

> detector for the word automatically adds the emoji

No, I would argue against - there _will_ be cases we don't want decorated that way.

For other cases where code change is needed, please take your time and be specific - where exactly - and sort by importance?

**Comment by ArchDuque-Pancake** [comment]
Ok, so if I wanted to do that via traslantions, how exactly can I put the game emojis (production, cultulre, etc)?

> For other cases where code change is needed, please take your time and be specific - where exactly - and sort by importance?

If I understand correctly, here would be cases where I think stat icons should be added:

- Buildings descriptions (in city construction screen and civilopedia)
![Screenshot_20210912-082250_UnCiv.png](https://user-images.githubusercontent.com/78449553/132989643-00286d00-3955-4da8-87f3-18cad789ae10.png)

- Civilopedia descriptions: Buildings, wonders, terrains, tile improvements, resources, nations, tutorials and polices.![Screenshot_20210912-082925_UnCiv.png](https://user-images.githubusercontent.com/78449553/132989787-9bec667a-332c-405a-835c-8a134ce18fc4.png)

-City State diplomacy screen, to indicate what they give
![Screenshot_20210912-082831_UnCiv.png](https://user-images.githubusercontent.com/78449553/132989805-ceea1149-a7cd-4229-b957-46c30f172232.png)


-Policy picker screen descriptions
![Screenshot_20210912-083129_UnCiv.png](https://user-images.githubusercontent.com/78449553/132989813-a38078dc-e94f-49f0-bb36-4e61b9abe180.png)

- New game screen, nation picker.
![Screenshot_20210912-084045_UnCiv.png](https://user-images.githubusercontent.com/78449553/132989878-f85d60c6-d98b-44ea-b13a-7f312a454c3e.png)


Those are the places that I think it would help ilustrating better the texts. In some cases, text is short, but you get more juice out of this with long texts that some wouldnt like to read.
Altough reading is great, sometimes the text becomes very monotone and becomes hard to read. By adding some little 'sparkles'  medium to big texts will become nicer to read.

Sorry before hand if anything :)

**Comment by xlenstra** [comment]
> Ok, so if I wanted to do that via traslantions, how exactly can I put the game emojis (production, cultulre, etc)?
> ('fonts.gold'????)

On the bottom of the linked file, there are some characters, like ➡, ⁂, ☮ and ⏳. Putting any of these into text either for translations or for game objects will display the icon of that stat when that text is loaded ingame. ⁂ will be converted to an apple when displayed, ☮ for faith, etc.

**Comment by SomeTroglodyte** [comment]
> Buildings descriptions (city construction)

`getDescription()`, ultimately Uniques and `Stats.toString()` as below - Alternatively, call the CivilopediaText system from the city screen... I already considered the latter and decided against, but it was a close dice throw.

> Civilopedia descriptions: Buildings, wonders, terrains, tile improvements

`Stats.toString()` - as I see it, just changing the function could do it without breaking any translations. (?? can't be _that_ easy can it ??)

> City State diplomacy screen, to indicate what they give

Uniques. Changing the json... Would that break saves and require a deprecation round or not? At the moment I'm not sure. If bad, using a display 'adapter' routine that reconstructs the unique string from the fully parsed object might do it...

> Policy picker screen descriptions

Uniques again, nothing else

> New game screen, nation picker

Same... actually, not only. These are also lacking the leader portraits, and I have stashed code replacing the whole thing with CivilopediaText which worked well enough. I just wasn't sure about cost/risk/usefulness balance, and other things were more important... If I dig that out, or not, reduced to the already stated sources.

> 'sparkles'

Exactamente. Such stuff isn't useful per se, but can keep a player less bored, just maybe meaning less uninstalls. Our whole society is built on such cheap illusions after all...

Slight Problem: The non-font glyphs will not accept a color readily and might look bad when in text colored to a nation's colors. Needs testing.

Re 'via translations': I meant that as a way to try the effect - if it's good and would benefit all players, of course the other side needs it first, no sense in PR'ing such a change. Just to clarify.

So, what do you think, Xander? Two places and they're everywhere? Worth a try? Did I miss some aspect?

**Comment by xlenstra** [comment]
> `getDescription()`, ultimately Uniques and `Stats.toString()` 

> So, what do you think, Xander? Two places and they're everywhere? Worth a try? Did I miss some aspect?

While they are only at two places, I don't feel like it is that simple. The `Stats.toString()` should be simple enough, assuming we don't parse the output of that again somewhere else. Putting them in `Uniques` is more difficult though, since they often have a stat as param, so for these cases we also have to add it to `Stat.ToString()` (or whatever we use to display them, `Stat.name`? Can we even change that?). Then there are still a few uniques that don't allow stats as param and there they should be added.

Then the question is still how the translations will handle these. Adding these to uniques will immediately invalidate all existing translations, though that can be solved by some regex-replacing. Adding them to stat params or generated Stats will also likely require translations with and without icon to be added.

All in all, should be doable, though maybe not as easy as adding it only in those two spots.

**Comment by SomeTroglodyte** [comment]
> parse the output of that again

Good thinking. That would be definitely an anti-pattern. Such quirks have no place in clean code, so +1 to this as a detector of bad code???? :wink: 

> have a stat as param
Ugh. Those `grant [amount] [stat] ...` uniques always irritate me, as [stats] is a perfectly fine system - I think it's mostly done to avoid the mandatory sign. I'd ignore those as a first step.

> `Stat.ToString()` ...ahem, 't'... OK, for an enum that auto-defaults to name afaik, but I see no reason not to implement it as `name + character` (ouch, I should have chosen `symbol`for that property name) - pardon, `character + name`.

Don't even allow yourself to think of an enum name as having display qualities. Anti-pattern! It's a coding key foremost, abusing as display name might be OK in simple cases but never adapting an enum name to suit display... Uh, just saying, my personal prejudice.

> invalidate all existing translations

I thought that would mostly leave the placeholderText identical, and the part inside [] is translated piecemeal anyway... Sure, if we insert the symbols in json, Stats.isStat and .parse need to learn to ignore them (maybe by appending both name and toString() to the regex builder), then... wait a minute, I forgot how a "grants [stats]" unique translates when [stats] is e.g. "+1 Production, +1 Gold"... Anyway, I believe little code changes can allow all translations to stay as they are. We'll see if and when we try it.

**Comment by yairm210** [comment]
I've been thinking about this for quite a while now
Actually, it's super easy
Barely an inconvenience

In String.tr():

```kotlin
    val stat = Stat.values().firstOrNull { it.name==this }
    if (stat!=null) return stat.character.toString()
```

Result:
![image](https://user-images.githubusercontent.com/8366208/132997713-1fa4cd07-920b-41dc-afe7-07df0e2a2dbc.png)


The only place where it doesn't look good is where we color the text: to a dark color:
![image](https://user-images.githubusercontent.com/8366208/132997608-ce577896-85aa-4585-a33b-75e728fa3bd5.png)

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/132997772-8bc9f7b6-e204-4244-a208-21ff45c13b6d.png)

**Comment by SomeTroglodyte** [comment]
> color the text: to a dark color

As expected (Ctrl-F "colored to a nation's colors"). We might need something more selective... But I'm toying with something completely different today, I'll keep out of it mostly.

**Comment by yairm210** [comment]
I think the correct answer is "don't color text". The nation text has needed a UI rehaul anyway - see the Korean color clash.

**Comment by ArchDuque-Pancake** [comment]
> ![image](https://user-images.githubusercontent.com/8366208/132997772-8bc9f7b6-e204-4244-a208-21ff45c13b6d.png)

That's nice! But I see a problem which may be the reason why in Civ V you have both the icon and the word.

I remember some users asking what where gear and apple icons for. So, new players may be lost on what the icons mean without the word.

So in my opinion, it would be better if it was "⚙ production", instead of just the icon or the word.
![Screenshot_20210911-223821_Google.png](https://user-images.githubusercontent.com/78449553/132999850-45fd4e60-0511-4b77-87ec-b05a3fbc6f1c.png)

**Comment by SomeTroglodyte** [comment]
Actually, just one line already does almost everything perfectly
(Stat): `override fun toString() = character + name.tr()`
Most small changes that become advisable look like this: (Remove tr() in Stats.toString, "{${stat.name}}" -> "$stat", "{Gold}" -> "${Stat.Gold}", key.name.tr() -> key.toString() (where key is Stat))
.. They add the symbol where toString was circumvented, e.g. maintenance. I haven't found a single place where a regression needed fixing, and no indication these are parsed back anywhere. This should be cheaper performance-wise than an extra firstOrNull in each tr() call.

<details><summary>But at least one place starts to look _too_ garishly colourful:</summary>

![image](https://user-images.githubusercontent.com/63000004/133164352-ea15cceb-d009-494d-8111-a03bbc9e5392.png)
</details>

**Comment by yairm210** [comment]
I think that looks good, actually :)

**Comment by yairm210** [comment]
By the way, this EXACT evolution can be seen in pro 4X series :)
In Civ III and IV icons were without text. This lead to "fan" naming conventions like "hammers" and "shields".
In Civ V and VI, all terms are icons + text.

In Endless Legend, Amplitude's first 4X,  there are icons only.
In Humankind, Amplitude's second 4X, icons + text.

In short, I feel that seasoned 4X devs opt for "both". Within this research, I did notice that all icons + text were icon + *space* + text, so I would opt for spaces as well.

**Comment by SomeTroglodyte** [comment]
Maybe use Xander's Spaces®, you know, the `" " = " "` line...

**Comment by yairm210** [comment]
Indeed

**Comment by ArchDuque-Pancake** [comment]
Results on adding the icons on translations:

![imagen](https://user-images.githubusercontent.com/78449553/133305062-791eacfb-e935-47ba-8e9f-f2c5688581c3.png)
![imagen](https://user-images.githubusercontent.com/78449553/133305120-39194c87-9125-45b5-af23-28d59f04c79c.png)
![imagen](https://user-images.githubusercontent.com/78449553/133305343-6344ed66-8080-4919-84b4-fb568c6e0740.png)
And..
![imagen](https://user-images.githubusercontent.com/78449553/133305900-af9f5722-3704-4c55-8a54-ec0f5b48e168.png)

**Comment by SomeTroglodyte** [comment]
I'll unshelve and production-ready-test the Stat.toString() approach soon. So, patience. Not today perhaps, my muscles and eyes ache a bit.

**Comment by yairm210** [comment]
The Stat.toString() has a major disadvantage against using .tr() in that unique parameters ("+[] for [Culture] buildings", or "[+15]% [Culture] [in all cities]" for example) won't get the juicy icon
