### ISSUE TITLE
UI request: Move the 'reset game settings' button far away from the 'accept game settings' button to avoid misclicks

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5197]
On the new game start screen, a 'reset to defaults' button was added to restore the default settings.
This button is, however, placed directly above the 'start new game' button.
This might result in unfortunate misclicks, and at least two users in our discord have expressed discomfort with this arrangement.
Would it be possible to move this button to the middle of the bar, or at least create more distance between the buttons?

**Comment by SomeTroglodyte** [comment]
The originally intended padding was buggy, which is fixed - maybe in #5190? And moving it entirely somewhere else - it's not specific to one of the columns, so nowhere on the topTable, and down below the center is occupied by the unused descriptionLabel. Well, maybe kill and replace that cell...

Ideas: make it font size 12?
YesNoPopup "are you sure"?
Bind enter key to start so you don't need to approach the dangerous corner with the mouse anymore?
Pack a whole bunch of anti-fast-food subliminal messages into Unciv so the average Unciv user obesity decreases and with it the fat-finger factor?
Move the 'reset game settings' button far away from the pointer in a mouseover listener (actually ClickListener.enter) to avoid misclicks?

It also needs a kind of summary for mod selection - like a count of activated entries in the expander headers.

In landscape there's still the annoyance that the left and right (center too but that mostly doesn't need to) columns do not scroll with the wheel. I forgot the reason, but that reason might be moot - could have been a listener conflict with the blocked PickerScreen.scrollPane which should be solved by now...

So, that screen still needs a little bit of work anyway.

**Comment by SomeTroglodyte** [comment]
Interim workaround: After accidentally hitting reset, immediately close and re-enter the screen.
