### ISSUE TITLE
Piety update crashes game

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5199]
CityStats.getStatPercentBonusesFromUniques:
```kotlin
            for (unique in uniques.filter { it.placeholderText == "+[]% Production when constructing [] buildings" }) {
                val stat = Stat.valueOf(unique.params[1])
```
One can immediately see this will crash when fed "+[100]% Production when constructing [Shrine] buildings", "+[100]% Production when constructing [Temple] buildings"

Compare "Police State": "+[100]% Production when constructing [Courthouse]"

Actually, feeding "user input" (mods) to Enum.valueOf is an invitation for DOS attacks. Not that we can help it when we have directly deserialized enums, but in unique params that's too easy. :nerd_face: 

From my shelf:
```kotlin
inline fun <reified T: Enum<T>> enumValueOfOrNull(name: String?): T? {
    if (name == null) return null
    return try {
        enumValueOf<T>(name)
    } catch (ex: IllegalArgumentException) {
        println("Could not parse\"$name\" as ${T::class.java.simpleName}.")
        null
    }
}
```
And in Stat.Companion choose one of:
```kotlin
        fun valueOfOrNull(name: String) = enumValueOfOrNull<Stat>(name)
        fun safeValueOf(name: String, default: Stat = Gold) = enumValueOfOrNull(name) ?: default
```

**Comment by SomeTroglodyte** [comment]
Oops, direct linking doesn't work like in Azure DevOps... No matter.

**Comment by xlenstra** [comment]
I probably should have tested that 😅
For now I've fixed the policy, although something like this does look useful for the future
