### ISSUE TITLE
New game nation picker alternatives

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5211]
<details><summary>Some screenshots:</summary>

![image](https://user-images.githubusercontent.com/63000004/133161006-d9ee81ed-d40e-4ad8-a68b-4280e3a2f4de.png)
![image](https://user-images.githubusercontent.com/63000004/133161020-5406239e-c473-4614-8eb9-4b86e74e63dc.png)
![image](https://user-images.githubusercontent.com/63000004/133161042-f5b826fd-384f-4981-b84e-3d71475fc202.png)
![image](https://user-images.githubusercontent.com/63000004/133161079-8d167eca-0c09-4b01-a969-cb07bf161971.png)
![image](https://user-images.githubusercontent.com/63000004/133161094-911c9ea4-13a2-4f3b-b529-e6f9553d408c.png)
![image](https://user-images.githubusercontent.com/63000004/133161113-7c1af047-6a4b-4c37-b74c-1da2db12ad8f.png)

</details>

These were all done with [the result of this script](LeaderPortraitScraper.py) as perm visual mod, and varying code tweaks.

Which variant?

**Comment by AdityaMH** [comment]
I choose this
> ![image](https://user-images.githubusercontent.com/63000004/133161042-f5b826fd-384f-4981-b84e-3d71475fc202.png)

**Comment by SimonCeder** [comment]
Last one

**Comment by yairm210** [comment]
Numbers 1,2,3 all leave the hard-on-the-eyes combinations, and make icons-within-text impossible for dark-colored inner color.

4 and 5 are improvements, but if the inner color is blue (dark blue, no Greece blue) then the leader name will probably be hard to read.

Therefore I opt for 6 as well.

**Comment by yairm210** [comment]
The text wrapping is an issue we should address, though. 6 is good for the colors, but the text wrapping from 5 is important.

**Comment by SomeTroglodyte** [comment]
No, 4 and 5 map title color to white if the luminance of that nation color is <50%, but I agree I tend to the last one, too. Wrap code is the same in 6 as before. Leave the unit/terrain/etc icons in (that part is the point where existing branch is just a hack yet)? I'd say yes, but the 'cleaner' look also has its charms.

**Comment by ravignir** [comment]
what about 6, but adding a border to that dark blue color?
![z](https://user-images.githubusercontent.com/30041793/133223566-b565dacc-dcd1-4db9-8b68-a8580cb3af04.png)

**Comment by AdityaMH** [comment]
Last one looks ugly for me

**Comment by xlenstra** [comment]
I prefer the last one as well, and have no strong preference for including Ravignir's addition or not

**Comment by SomeTroglodyte** [comment]
> 1 and 2 is no different from original

Look again.  Portrait, different text geometry, possibly even more details because it's re-using the Civilopedia renderer, only with icons suppressed.

> what about 6, but adding a border to that dark blue color

Quick gimp-ing! Not really sure. Actually, I don't even know why my second border is 10f and not 5f wide - if I don't find that quickly, that alone would be reason enough to save the 10f for your extra border...

Surprised nobody saw the Title is not perfectly centered on #6.. Easier to see with rav's edit.

I say that's an almost-consensus. We'll keep the idea of an extra border in mind, could be shoehorned in later. PR shortly.

... now how do we get a complete set of portraits into the game in a more robust fashion?

**Comment by ravignir** [comment]
Just a random thought, very much disconnected from the topic: maybe for avoid type of start biases, use tile images that have red `X` on them?

**Comment by SomeTroglodyte** [comment]
Red X marks the spot? Genius inspiration there, Guybrush. So simple I would never have thought of it. Map editor already knows how to...

**Comment by yairm210** [comment]
I also implemented a red X for the "Obsolete by" unique. Maybe ImageGetter should get a new function...?

**Comment by SomeTroglodyte** [comment]
Visuals balanced and kludges cleaned, but too late to test properly. Need a time turner.

**Comment by AdityaMH** [comment]
> Look again. Portrait, different text geometry, possibly even more details because it's re-using the Civilopedia renderer, only with icons suppressed.


For me, this good if add icon.
I will choose 1 and 2 with icon.
