### ISSUE TITLE
Automated worker needs attention every turn in 3.16.13-patch

### ISSUE THREAD

**Issue by kklasmeier** [yairm210/Unciv#5212]
**Platform**
Android 10

**Version**
3.16.13-patch1

**Describe the bug**
After automating a worker, the app now requires you to automate the worker every turn

**To Reproduce**
1. Start new game using defaults
2. Create a worker
3 set the worker to Automate
4. Choose next turn

After the turn ends focus is returned to the worker again every turn where u need to automate it again.
``

**Expected behavior**
Worker should stay automated until it is turned off

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Already solved in 3.16.14 :)

**Comment by kklasmeier** [comment]
When does version3.16.14 come out for Android?

**Comment by xlenstra** [comment]
Versions are rolled out in batches, after release 10% immediately gets access, 30% gets access after a day and 100% after two days. This might change in the near future, but for now this is how it works. Since version 3.16.13 was released 2-3 days ago, you should be able to update within a day.
