### ISSUE TITLE
Make strategic ressources more valuable

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#522]
In keeping with #486, the scarcity of strategic ressources should have Ais value them higher than a generic 50 gold in trading.

**Comment by yairm210** [comment]
https://www.reddit.com/r/civ/comments/1go7i9/luxury_and_strategic_resource_pricing/

50 is pretty standard and a simple number

**Comment by flecheapolinienne** [comment]
I originally created the issue because of the way strategic ressources are so easy to buy from any AI at any point in time, even when one would guess it should hold onto it... So the price is maybe not the issue as much as AI's willingness to trade them.

**Comment by yairm210** [comment]
Aha, that's a good point
And perhaps deserves an issue
But with a name that reflects its meaning
