### ISSUE TITLE
The message about entering new era is corrupt

### ISSUE THREAD

**Issue by Bershcomp** [yairm210/Unciv#5227]
**Platform*
Android, google play

**Version**
3.16.13-patch1

**Describe the bug**
The message "India has entered the Classical era" contains the code variable instead of "Classical Era"

**To Reproduce**
1. Load savefile https://disk.yandex.ru/d/7FA0eO_oZslPpg
2. End turn, go to next turn
3. See message

**Expected behavior**
The message to contain the era name instead of the code piece with class property name

**Screenshots**
![Screenshot_2021-09-15-10-40-54-131_com unciv app](https://user-images.githubusercontent.com/86048557/133392558-79957cc8-2ba5-43df-b854-aafc7d95dd3d.jpg)

**Comment by xlenstra** [comment]
Thanks for your report, this is a known bug that is fixed in 3.16.14z which should be available on the Google play store very soon. If the problem persists after updating, please do open a new issue.

**Comment by Bershcomp** [comment]
Is there any list of known bugs to view before I do the bug report?

**Comment by xlenstra** [comment]
Most of the time these fixes can be found in the changelog: https://github.com/yairm210/Unciv/blob/master/changelog.md
Sometimes the messages are a bit cryptic, so if you're unsure if a bug is fixed, just make an issue for it anyway. Worst case we close it immediately
