### ISSUE TITLE
Troop Pathfinding should avoid City State Borders

### ISSUE THREAD

**Issue by EclipsePlays** [yairm210/Unciv#5228]
**Is your feature request related to a problem? Please describe.**
It's sometimes worrying when troops that are ordered to move to a tile very far away (more than 2 moves to complete), and have a city state in the way, they will still go inside the city state border, and will cost you some influence. 

**Describe the solution you'd like.**
Troop Pathfinding should now avoid city state borders. That's all.

**Comment by AdityaMH** [comment]
Same as #4107

**Comment by xlenstra** [comment]
Not quite, as both #4107 and #1814 specifically note 'exploration', while this issue is more about multi-turn movement, which are implemented completely differently

**Comment by EclipsePlays** [comment]
y e s

**Comment by logicminimal** [comment]
except for greece and while passing thru friendly/allied city states

**Comment by yairm210** [comment]
This is the same as #1814 in my book.
Same problem, and when they'll be a solution it'll be the same solution
