### ISSUE TITLE
Confirm Button when choosing Civilizations

### ISSUE THREAD

**Issue by EclipsePlays** [yairm210/Unciv#5229]
**The Problem**:
For new players they sometimes seem to get trapped when choosing civilizations. 

**The Solution:**
Add a confirm button on the right most side of the panel. 

~~just a little QoL~~

**Comment by EclipsePlays** [comment]
Yes, tapping on all panels work, but a confirm button is more recognizable.

**Comment by SomeTroglodyte** [comment]
Trapped? Both ESC and Android back button will "free" you from the evil trap. My vote: Easy enough as is.

**Comment by AdityaMH** [comment]
Major problem on Android is not about that.
but they force me to confirm civilization while my phone "almost" going to stand by.
so, by add confirm button. I can read civilization description without scaried about sleeping screen.

**Comment by EclipsePlays** [comment]
> Trapped? Both ESC and Android back button will "free" you from the evil trap. 

> There's a big fat "X" well outside the picker proper to the left that closes without changing anything. 

Say you want to play India then pick "X". 

Will revert you back to a random civ.

*just, why not a confirm button, tapping on the right panel is a little confusing*
