### ISSUE TITLE
All city-states

### ISSUE THREAD

**Issue by dnddnbdodjd** [yairm210/Unciv#5233]
(Militaristic)Alamaty
(Mercantile)Antananarivo(BNW)
(Mercantile)Antewerp(G&K)
(Militaristic)Belgrade
(Cultured)Bogota
(Cultured)Bratislava（BNW）
(Cultured)Brussels
(Cultured)Bucharest
(Militaristic)Budapest
(Cultured)Buenos Aires (BNW)
(Maritime)byblos(BNW)
(Mercantile)Cahokia(G&K)
(Maritime)Cape Town
(Mercantile)Colombo(G&K)
(Militaristic)vanilla(G&K✘)Dubin
(Militaristic)vanilla(G&K✘)Edinburgh
(Cultured)Florence
(Cultured)vanilla(Religious)G&K Geneva
(Maritime)vanilla(Mercantile)G&K Genoa
(Militaristic)Hanoi
(Maritime)vanilla(G&K✘)Helsinki
(Mercantile)Hong Kong(G&K)
(Religious)Ife(BNW)
(Maritime)G&K(​BNW✘)Jakarta
(Religious)Jerusalem(G&K)
(Cultured)Kabul(BNW)
(Cultured)vanilla(Religious)BNW Kathmandu
(Cultured)Kiev(BNW)
(Cultured)Kuala Lumpur
(Cultured)Kyzyl(BNW)
(Religious)La Venta(G&K)
(Cultured)vanilla(Religious)G&K Lhasa
(Maritime)G&K(​BNW✘)Lisbon
(Mercantile)Malacca(BNW)
(Maritime)Manila(G&K)
(Mercantile)G&K(​BNW✘)Marrakech
(Militaristic)M'banza-kongo(BNW)
(Mercantile)Melbourne(BNW)
(Cultured)Milan(G&K)
(Maritime)Mogadisu(BNW)
(Maritime)Mombasa(G&K)
(Cultured)Monaco
(Maritime)Ormus(BNW)
(Maritime)Panama City(BNW)
(Cultured)Prague(G&K)
(Maritime)Quebec City
(Maritime)Riga(BNW)
(Maritime)vanilla(​BNW✘)Rio De Janeiro
(Mercantile)Samarkand(BNW)
(Militaristic)Sidon
(Maritime)vanilla(Mercantile)G&K Singapore
(Militaristic)Sofia(BNW)
(Maritime)vanilla(G&K✘)Stockholm
(Maritime)Sydney
(Militaristic)vanilla(Mercantile)G&K Tyre
(Maritime)Ur(BNW)
(Maritime)Vancouver(BNW)
(Militaristic)Valletta(G&K)
(Religious)Vantican City(G&K)
(Maritime)vanilla(​BNW✘)Venice
(Cultured)vanilla(G&K✘)Vienna
(Mercantile)Vilnius
(Cultured)vanilla(​BNW✘)Warsarw
(Maritime)Wellingtionn
(Religious)Wittenberg(G&K)
(Cultured)Yerevan(G&K)
(Mercantile)Zanzibar(G&K)
(Mercantile)Zurich(G&K)

**Comment by yairm210** [comment]
#4602
