### ISSUE TITLE
Having an AI declare War on another player should be risky and be set to a limited duration!

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#524]
There could be a chance every time you make the transaction that the player in question discovers it and declare war on you. The base probability could go up with difficulty levels.

Also, wars should be set to a limited duration like 10 turns for 500$, 20 for 1500$, 30 for 3000$

All of this because it is now too easy to just play every AI against each other in order win on the long term...

**Comment by yairm210** [comment]
The root problem here is that the AIs don't optimally negotiate peace with each other, so if they agree to go to war they will never un-war...

**Comment by flecheapolinienne** [comment]
Yeah I get that, but is there really a need for them to "negotiate" peace between them anyway? Let's just have a simple heuristic like the one I offered, no? Anyways, thanks for taking the time to consider it :)

**Comment by flecheapolinienne** [comment]
Just to clarify... I meant "Having an AI declare War on another AI **by way of trade (paying it to do so)** should be risky and be set to a limited duration"

**Comment by ninjatao** [comment]
Maybe we need war weariness to encourage long term wars. Make AIs negotiate peace considering military strength and war weariness seems reasonable.
