### ISSUE TITLE
Add Open Borders agreements to trade

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#525]
Is it possible to do so in the original Civ?

**Comment by Smashfanful** [comment]
It is. After discovering a certain tech (I don't remember exactly) you could ask for free land passing for at least 40 turns.

**Comment by ninjatao** [comment]
Original civ has "Open Border" diplomacy option, which requires Civil Services.
https://civilization.fandom.com/wiki/Diplomacy_(Civ5)

**Comment by flecheapolinienne** [comment]
Reading the page, I found this interesting rule:  "...military and civilian units will actually be able to use it as their own territory, which means you/they can use the road network for fast movement, and that your/their **units may heal in that territory as if it were your own.**" Is that implemented in Unciv? This would make it still a bit more challenging yet to invade AIs :)
