### ISSUE TITLE
Lumber Mill Buff

### ISSUE THREAD

**Issue by EclipsePlays** [yairm210/Unciv#5254]
**Is your feature request related to a problem? Please describe.**
It seems that lumber mills are underrated in this game, despite lumber in real life is crucial for production and construction. 

That's because forests and jungles don't actually add the tile yield of their base tile, they replace it with a new tile yield,which is a bit odd when forests are situated on hills. 

**Describe the solution you'd like**

Forests on plains, grassland, and tundras won't change, but *forests on hills should be given +1 Production*. 

That means if we upgrade the forest in hill tile, it will have a tile yield of **+3 production, and +1 food**. 

Which means lumber mills are actually better than mines on hills, because they negate the food consumption of the worked tile itself. 

As a turning point though, they will *no longer have +1 Production once Scientific Theory has been researched*. 

**Optional Alternatives**

- Lumber mills get +1 production when there are 2 adjacent lumber mills, capped at +2 production. 

- Lumber mill's +1 production boost will be moved from Scientific Theory to Civil Service.

**Comment by ArchDuque-Pancake** [comment]
Lumber mills get really great at scientific theory, specially on flat terrain.

**Comment by EclipsePlays** [comment]
Actually they're nothing compared to Farms with Fertiliser researched (considering that Scientific theory is also in the same era as Fertilizer). 

+3 Production, +1 Food vs +4 Food...

**Comment by ArchDuque-Pancake** [comment]
Yes but lumber mills are for productiom, not food. The 1 food is just a nice extra.

Lumber mills can be better than mines until chemistry, where mines get 4 production. But until then, they are great if you want production and not have to worry about food.

I think any tile above 4 yield, is a great or op tile.

**Comment by logicminimal** [comment]
u can make an unciv mod

**Comment by xlenstra** [comment]
Point is that you need a balance between production and food in cities. Too much food and building things takes ages, too little food and you never get enough production to work all your production tiles. Forests provide a balancing factor, giving both a bit of food and a bit of production, they can be improved to provide a lot of production and some food in hilly areas, or provide production at all in flatter areas. Hills are often clustered, and as such aren't always there to provide production to cities, with forests taking over there role.

Regardless, the base game will be kept similar to civ 5, so, as Logiciminimal says, you're welcome to make a re-balance mod for unciv, but this will not be added to the main game.

**Comment by yairm210** [comment]
As stated by others, A. Unciv is aiming to be Civ V compliant, and B. you can [mod this yourself ](https://github.com/yairm210/Unciv/wiki/Mods) :)
