### ISSUE TITLE
Austria is Missing Buildings

### ISSUE THREAD

**Issue by mathwhiz1212** [yairm210/Unciv#5256]
Austria is missing the Pentagon and the building that comes with the railroad research in v3.16.14 on Android 8. It's a very nice game, but this was annoying.

**Comment by xlenstra** [comment]
Wonders can only be built by a single civilization. If you're not fast enough, someone else will have built them instead of you.

If you don't think that that is what happened, please provide a save file and we'll look into your problem

**Comment by SomeTroglodyte** [comment]
@xlenstra - say, OP motivation seems clear enough, but - other than the one-turn notification, we have no UI for wonder status, right? Does the original have one, and how roughly would it look? Do we internally even have the data which wonders built in other nations the player knows about / knows exactly where? Is it so that when the Civ is known, the city is known? Or intersect city tile with explored tiles? Others are "in a far away land" then...

**Comment by xlenstra** [comment]
The original had a detailed diplomacy overview screen, which contained for each civ the wonders they had build, though not in which cities they were build.
Screenies copied from gogle images:
![image](https://user-images.githubusercontent.com/71121390/134136241-c78cf188-712c-415e-98c7-85b31abcf3f2.png)
![image](https://user-images.githubusercontent.com/71121390/134136358-7883c662-3dfa-4868-831a-7c2032a39d30.png)

**Comment by SomeTroglodyte** [comment]
How about...
![image](https://user-images.githubusercontent.com/63000004/134230216-96af2ca9-f53a-432a-85cb-7ac952ef062c.png)
[(branch here)](https://github.com/SomeTroglodyte/Unciv/tree/Wonder-Overview)?

**Comment by yairm210** [comment]
Looks good to me :)

**Comment by logicminimal** [comment]
> How about...
> ![image](https://user-images.githubusercontent.com/63000004/134230216-96af2ca9-f53a-432a-85cb-7ac952ef062c.png)
> [(branch here)](https://github.com/SomeTroglodyte/Unciv/tree/Wonder-Overview)?

i think the non built ones shouldnt clutter the window

**Comment by SomeTroglodyte** [comment]
> Looks good to me :)

Now _where_ did I park that branch... ... ... 

In the meantime, any better suggestion instead of the star (which I took out of sheer laziness) for the category button? White copy of Pyramids???
