### ISSUE TITLE
Culture penalty for cities shouldnt count when they expand culturally

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5257]
This means that every city but the Capital will be left to expand on its own, using its normal Culture score (minus the penalty for being a Puppet).

https://civilization.fandom.com/wiki/Venetian_(Civ5)

**Comment by xlenstra** [comment]
I don't understand what you are talking about. The culture each city generates is already used only for expansion of that specific city. 

What culture penalty shouldn't count? 

The sentence you wrote is a literal copy+paste of how, as a result of being unable to buy tiles for puppet cities, Venice is unable to get tiles other than through natural border expansion. What does that have to do with the title?

**Comment by xlenstra** [comment]
I'm still confused
