### ISSUE TITLE
Runtime error from json.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#526]
03-07 13:50:04.507 28249 28282 E AndroidRuntime: FATAL EXCEPTION: GLThread 560
 03-07 13:50:04.507 28249 28282 E AndroidRuntime: Process: com.unciv.app, PID: 28249
 03-07 13:50:04.507 28249 28282 E AndroidRuntime: java.lang.ExceptionInInitializerError
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    at com.unciv.UnCivGame.create(UnCivGame.kt:30)
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    at com.badlogic.gdx.backends.android.AndroidGraphics.                                 onSurfaceChanged(AndroidGraphics.java:311)
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
 03-07 13:50:04.507 28249 28282 E AndroidRuntime: Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line     1743 near: ow":{
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:        Italian:"Neve"
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    }
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    }
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    *ERROR*"Coast":{
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:        Italian:"Costa"
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    }
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    "Ocean":{
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:        Italian:"Oceano"
 03-07 13:50:04.507 28249 28282 E AndroidRuntime:    }

**Comment by ninjatao** [comment]
commit 6a833ae89a906401d51e6f3f20b91557eaa63ebb

**Comment by yairm210** [comment]
These happen all the time from little changes in the translation file, the serializer even take you where the error is so it's no biggie
