### ISSUE TITLE
Great Person gifts from City States do not result in what the Notification promises

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5306]
Steps to reproduce the behavior (:
1. Play as non-Mongolia, acquire Patronage complete, ally all the CS
2. Wait for "Sydney gave us a Khan as a gift!"
3. Click the notification twice
4. See it's a Great General - or it's entirely missing

![image](https://user-images.githubusercontent.com/63000004/134572099-9d2cbc2d-55fb-4812-b783-dce5959dd071.png)

Yes - that's the only Great General/equivalent in the Civ, either both messages refer to the same unit creation, or the GG and the Khan were independent, and the Khan disappeared.

Will debug myself in time unless I forget...

**Comment by SomeTroglodyte** [comment]
Doesn't easily repro, but the code is clear.
- All Great Persons, including unique ones, except religious if rel disabled, are candidates
- Random choice without weighting
- calls `CivilizationInfo.addUnit` which calls getEquivalentUnit(), which converts the Khan to a GG
- addUnit generates a notification for "been born"
- giveGreatPersonToPatron generates another notification for giftedUnit instead of placedUnit

A fix is easy but how _should_ it behave? If we fix the notifications only, there's a strong bias to Generals. Should Khans and other nation-specifics be giftable to recipients they don't "belong" to? What should the probability distribution be?

**Comment by SimonCeder** [comment]
Khans should be giftable according to various civ forums. I'll look into the weighting.

**Comment by SimonCeder** [comment]
Civ V behavior: All Great People *except ones that can found religions* are eligible with a flat probability distribution. Khans should not be converted to Generals.
So we should remove the condition from
`if (!civInfo.gameInfo.isReligionEnabled()) giftableUnits = giftableUnits.filterNot { it.uniques.contains("Hidden when religion is disabled")}`
as well as prevent the game from converting Khans to Generals in this particular case.

Note that City-States can give unique military units as well, though that's currently through `placeUnitNearTile()` which is unique unit-safe. It would be better to use `addUnit()` consistently. Maybe add an optional `sic: Boolean = false`?

**Comment by SomeTroglodyte** [comment]
- Currently: (Khan+General) have together twice the probability compared with other GP, as each has a 'slot'
- Currently: Both get converted - Mongols get Khan instead of General, other nations the other way round.

If I understand you correctly -rewording-, we should
- Leave random choice as is (removing Prophets first)
- Prevent *any* civ-equivalent conversion
- Prevent the double notifications (born+gifted)

Not going to code that today, maybe not even the weekend.

**Comment by SimonCeder** [comment]
Looking at the blame, it seems this is a regression introduced by #5267. Changing the line back to placeUnitNearTile as well as filter out prophets should do it.
