### ISSUE TITLE
Is this Caravel?

### ISSUE THREAD

**Issue by dnddnbdodjd** [yairm210/Unciv#5317]
![IMG_20210926_012222](https://user-images.githubusercontent.com/84761886/134780598-7658cd82-6215-4411-bb62-a95a88d5c5a0.jpg)
![Caravela_de_armada_of_Joao_Serrao](https://user-images.githubusercontent.com/84761886/134780601-455ec512-b84e-446f-afca-37f344083c16.jpg)

**Comment by touhidurrr** [comment]
Looks similar to me.

**Comment by ArchDuque-Pancake** [comment]
¿Whats the problem? Why did you open an issue just for this?

**Comment by yairm210** [comment]
If you have a better image (white-on-transparent 100px by 100px) you're welcome to submit it :)

**Comment by dnddnbdodjd** [comment]
> 如果您有更好的图片（透明白色 100 像素 x 100 像素），欢迎提交:)

https://thenounproject.com/search/?q=Caravel&i=1626301

**Comment by touhidurrr** [comment]
I was skimming through my old notifications that I hadn't read and found this one. @yairm210, it seems like a new icon was suggested by @ghost. Was this added?

**Comment by yairm210** [comment]
Not sure, but you can pr it

**Comment by yairm210** [comment]
/Android/assets/images

**Comment by touhidurrr** [comment]
> /Android/assets/images

but i can't see any such folder.
https://github.com/yairm210/Unciv/tree/master/android/assets
where?

**Comment by xlenstra** [comment]
Should be `/android/Images.Construction/UnitIcons`

**Comment by touhidurrr** [comment]
> Should be `/android/Images.Construction/UnitIcons`

😐 who would have thought that Construction == Units.
Bad naming sense 100%.

**Rationale:** A person who was trying to find it for the first time couldn't succeed even after half an hour of extensive searching. (lol)

**Comment by xlenstra** [comment]
The rational is that that folder contains all things that can be constructed in cities, i.e. buildings and units

**Comment by will-ca** [comment]
> > Should be `/android/Images.Construction/UnitIcons`
> 
> neutral_face who would have thought that Construction == Units. Bad naming sense 100%.
> 
> **Rationale:** A person who was trying to find it for the first time couldn't succeed even after half an hour of extensive searching. (lol)

Most file browsers have recursive filename searches.

E.G. Type "Caravel" and it will show up within five seconds:

https://github.com/yairm210/Unciv/find/master

**Comment by touhidurrr** [comment]
> > > Should be `/android/Images.Construction/UnitIcons`
> > 
> > neutral_face who would have thought that Construction == Units. Bad naming sense 100%.
> > 
> > **Rationale:** A person who was trying to find it for the first time couldn't succeed even after half an hour of extensive searching. (lol)
> 
> Most file browsers have recursive filename searches.
> 
> E.G. Type "Caravel" and it will show up within five seconds:
> 
> https://github.com/yairm210/Unciv/find/master

Lol It's actually my first time seeing this feature. 🤣

**Comment by SomeTroglodyte** [comment]
> Bad naming sense 100%.

Thanks! 
Actually, the atlas code doesn't care how you name after the dot, and renames can be PR'ed. So rename it to `Images.Hello_tohidurr_look_here`, you'll get an appropriately named new atlas, commit that one too into your PR, enjoy.

> couldn't succeed even after half an hour

But the lesson learned might be invaluable.

> Most file browsers have recursive filename searches

Or Studio's shift-shift, or Studio's ctrl-shift-F (since .atlas files are text - unless you exclude them from the search)... The world is full of little wonders!  :fireworks:
