### ISSUE TITLE
Starting bias for civilizations

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#533]
A feature from Civ5 is the fact that some Civilizations have a bias that makes them start upon a terrain, while others have a bias that make them avoid a certain terrain as a starting location. My idea is this: Arabia's starting bias should be Desert; Babylon's starting bias should avoid Tundra; Egypt's starting bias should avoid Jungle and Forest; England, Japan and Greece's starting bias should be Coast; and Russia's starting bias should be Tundra. I'm not saying to implement that now, of course, that'd take too much time.

**Comment by yairm210** [comment]
All civs already have defined starting biases, documented in the wiki
We could start adding that info to the nations json, which would make future implementation easier

**Comment by Smashfanful** [comment]
That sounds good for me.
