### ISSUE TITLE
About the icon

### ISSUE THREAD

**Issue by dnddnbdodjd** [yairm210/Unciv#5337]
More like the Great Mosque of Djenne
https://thenounproject.com/search/?q=Great+Mosque+of+Djenne&i=1678222
![af6d4aedb874220edd3356e8ade48dc57884daed](https://user-images.githubusercontent.com/84761886/134924066-5b183470-566d-4abf-91e5-fe8b4aa393fa.jpg)
More like the Caravel
https://thenounproject.com/search/?q=Caravel&i=1626301

**Comment by yairm210** [comment]
A. For images we try to avoid lineart add much as possible, so the mosque I'm not sure about
B. For the caravel, sure why not. I'm not going to do this, but you can pr it yourself.
Rules are: white image, 100*100px, credits in the credits.md page.

**Comment by dnddnbdodjd** [comment]
> A. For images we try to avoid lineart add much as possible, so the mosque I'm not sure about
> B. For the caravel, sure why not. I'm not going to do this, but you can pr it yourself.
> Rules are: white image, 100*100px, credits in the credits.md page.

![Uploading 1626301-200_gaitubao_100x100.png…]()

**Comment by dnddnbdodjd** [comment]
> 规则是：白色图片，100*100px，credits.md页面中的credits。

![1626301-200_gaitubao_100x100](https://user-images.githubusercontent.com/84761886/134932960-b1c2e3be-d388-41a4-9853-a6a96d36004d.png)
