### ISSUE TITLE
Fallout Bug(?) on Map Editor

### ISSUE THREAD

**Issue by Tyretes** [yairm210/Unciv#5353]
You cannot place Fallout on map editor. This issue has last for a long time.

**Comment by SomeTroglodyte** [comment]
True. `MapEditorOptionsTable.addTerrainOptions` - onClick - line 336 will do nothing as Fallout's occursOn is empty. 

I'm not touching that code with a 10-foot pole (though I might get out the [12-foot](http://butt.church/view.php?comic=4623) pole some day), I'd probably be unable to stick to just fixing its problems, more likely I'd rewrite it from scratch...

**Comment by SomeTroglodyte** [comment]
Actually, since all plaecment of TerrainFeatures by the map _generator_ is hardcoded (Ice, Flood plains, Forest, Jungle) or controlled by uniques (Hill,Oasis,Marsh,Atoll) - filling the attribute should pose no problems..
```json
,
		// For map editor only - the generator won't place it without code or enabling uniques
		"occursOn": ["Grassland","Plains","Desert","Tundra","Snow","Forest","Jungle","Hill","Flood plains","Marsh","Oasis"]
```

... anybody see problems?

**Comment by jahodovykolac** [comment]
Yes, I've already pointed that out in #(give me a minute). There are also 2 more fallout issues on the topic of this.
