### ISSUE TITLE
city Attack prompt

### ISSUE THREAD

**Issue by FriedrichWilhelm123** [yairm210/Unciv#5360]
![Screenshot_2021-09-30-17-05-01-30](https://user-images.githubusercontent.com/90401287/135423561-080c7bfe-b698-457f-a433-3e8e01cf73b8.jpg)

**Comment by SomeTroglodyte** [comment]
Guesswork is fine. I'll guess, then - I guess I'll not guess at all.

**Comment by FriedrichWilhelm123** [comment]
> Guesswork is fine. I'll guess, then - I guess I'll not guess at all.

Enemy enters the city attack limits,There will be red dots on the city.

**Comment by AdityaMH** [comment]
> Guesswork is fine. I'll guess, then - I guess I'll not guess at all.

When someone want this feature a lot but you can't imagine how t̶o̶ c̶o̶d̶i̶n̶g̶. 😆

**Comment by will-ca** [comment]
IMO a notification in the news ticker would be the best way to do this.

"Your city London can bombard an enemy!"
