### ISSUE TITLE
New game from freshly saved map broken - continentSizes has a bad type

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#5372]
Running current master under Android Studio using adoptopenjdk 16 as _run configuration_ JVM ("OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)"), starting a debug session - not jar, not run without debugger.

1. Set a breakpoint on the return line of GameStarter.getCandidateLand, start debugging
2. New game, generated map, any settings, create game -> breakpoint is hit
3. Inspect tileMap.continentSizes and candidateContinents. continentSizes contains java Integer keys and values; candidateContinents contains integers - as declared by explicit typing in both cases
4. Go to map editor, create a fresh generated map, save, and make a new game from it -> breakpoint is hit again
5. Inspect tileMap.continentSizes and candidateContinents. continentSizes now has String keys, and candidateContinents is a set of Strings. Continent 0 is likely contained in the set, but Alt-F8 `0 in candidateContinents` evaluates to false. Even better, candidateContinents.first() gives an exception about type conversion.
6. Turn off save maps compressed, re-save the map, and open in a text editor. Look at continentSizes.

Example:
```
 ,{position:{x:-49,y:-7},baseTerrain:Snow,terrainFeatures:[Hill],continent:0}],continentSizes:{44:1,45:1,46:3,47:2,48:6,49:4,50:2,51:3,52:10,53:1,10:15,54:2,11:12,55:1,12:5,56:1,13:40,57:1,14:44,58:1,15:8,59:3,16:45,17:70,18:1,19:71,0:494,1:532,2:278,3:55,4:18,5:37,6:86,7:21,8:27,9:17,60:2,61:2,62:1,63:1,20:21,64:1,21:23,65:1,22:12,66:1,23:19,67:1,24:19,68:1,25:31,69:1,26:3,27:1,28:7,29:2,70:1,71:1,72:1,30:5,31:7,32:2,33:14,34:1,35:1,36:5,37:3,38:1,39:4,40:3,41:10,42:6,43:1},startingLocations:[{position:{x:1},nation:Celts}]}
```
Aha - Int to Int in a json object, not in a json array. json says object fields have string names and compliant json must quote them, only our serializer is set to simplify... So it becomes almost understandable the deserializer parses this into a `Map<String,Int>` and fools the JVM to accept that for a `Map<Int,Int>` destination... The madness continues as the data type violating the declared type is propagated into a fresh `HashSet<Int>` which under the hood now is actually a `HashSet<String>` and no `contains` call can ever return true...

Java is seriously broken.

What to do? I'm stumped. Obviously, change the type of continentSizes so roundtrip serialization/deserialization won't trip this madness - maybe _declare_ it a Map<String,Int>? But can that stay compatible?

<details><summary>This replacement for the function actually works:</summary>

```kotlin
    private fun getCandidateLand(
        civCount: Int,
        tileMap: TileMap,
        startScores: HashMap<TileInfo, Float>
    ): Map<TileInfo, Float> {
        if (tileMap.continentSizes.isEmpty()) tileMap.assignContinents()

        if (tileMap.continentSizes.isEmpty()) return mapOf()  // water only map
        val orderedContinents: List<Map.Entry<Int, Int>> =
            if (0 in tileMap.continentSizes) {
                tileMap.continentSizes.asSequence().sortedByDescending { it.value }.toList()
            } else {
                // broken deserialization
                @Suppress("UNCHECKED_CAST", "CAST_NEVER_SUCCEEDS")
                val fixedSizes = tileMap.continentSizes.map { it.key as String to it.value }.map { it.first.toInt() to it.second }.toMap()
                fixedSizes.asSequence().sortedByDescending { it.value }.toList()
            }

        // We want to  distribute starting locations fairly, and thus not place anybody on a small island
        // - unless necessary. Old code would only consider landmasses >= 20 tiles.
        // Instead, take continents until >=75% total area or everybody can get their own island
        val totalArea = tileMap.continentSizes.values.sum()
        var candidateArea = 0
        val candidateContinents = HashSet<Int>()
        for ((index, continentSize) in orderedContinents.withIndex()) {
            candidateArea += continentSize.value
            candidateContinents.add(continentSize.key)
            if (candidateArea * 4 >= totalArea * 3) break
            if (index >= civCount) break
        }

        return startScores.filter { it.key.getContinent() in candidateContinents }
    }
```
</details>

Can't remember seeing something as perverted in computing since tinysquishy introduced that new cardinality estimator in SQL Server 2014...

**Comment by SimonCeder** [comment]
The easy "fix" is to turn continent data into a transient, as we discussed it's currently not guaranteed to be accurate on loaded maps anyway.

**Comment by SomeTroglodyte** [comment]
`@Transient` prevents serialization - but will it prevent deserialization? Yes, it will. Maybe that's best - or there's a way to deserialize correctly we haven't yet thought of. Pity `Gdx.Json.setSerializer` is so hard to use.

**Comment by SomeTroglodyte** [comment]
OK, but we want continentSizes to be valid during gameplay for the minimum city distance rule (yet to be implemented - or else with the current state our games would crash).
If we make that map transient, it will need to be regenerated on _every_ game load. Not yet measured.
I also just checked - the data left by map editor is non-empty and definitely not matching the edited map, but the initial generator run. This also goes for the continent numbers on the tiles.

| what | how it is | how it should be |
|--------|------------|-----------------------|
| Persisted continent numbers per tile on a map editor map | invalid | valid or uninitialized? |
| Persisted continent sizes on a map editor map | invalid & broken | valid or uninitialized? |
| Persisted continent numbers per tile on a saved game from generator | valid but broken deserialization | valid or uninitialized? |
| Persisted continent sizes on a saved game from generator | valid | valid |

Any more dev voices, opinions, tips?

**Comment by SimonCeder** [comment]
I measured the continent assigning code in the original PR #5198, it was 3 ms on a huge pangaea. The code has been altered since but I don't expect it to be much slower.

**Comment by SomeTroglodyte** [comment]
I've not done much since, a few experiments. Having the continent size data properly persisted with backwards compatibility would mean deprecating the field and introduce a new one. Size data is not needed during normal gameplay (I erroneously tested under the unreflected assumption it is), it's for starting locations only. So yes best to drop it, and pass it another way from map generator to game starter - or not and group/count the tile continent indexes. Map editor should clear continent indexes and size data. Any tilemap load should check tile continent data and if missing run assignContinents.

Updated and fixed the table in the post above (had the broken deserialization label in a wrong cell).
