### ISSUE TITLE
Clearing jungle does not cause a production boost

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#5377]
Clearing a forest does. Civ5 provides a production boost for both.

Tested this morning on version 3.17.3

**Comment by xlenstra** [comment]
My testing in civ 5 did not show this to be true, and neither is it mentioned on the fandom. Are you certain?

**Comment by foolishgrunt** [comment]
https://civilization.fandom.com/wiki/Jungle_(Civ5)
"Production Production bonus to the closest city when cut down."

My personal recollection was that jungle provided also provided the production boost. Knowing I may have been mistaken, I checked on there for confirmation. Of course, it is possible that we're *both* wrong.

**Comment by xlenstra** [comment]
The fandom also seems to agree with my side (Unlike a forest, does not provide a one-time Production bonus to the closest city when cut down), so if you don't mind I'm closing this. You're free to make a mod that implements this behavior, though.
