### ISSUE TITLE
Byzantium's unique ability doesn't work

### ISSUE THREAD

**Issue by not-navyblue** [yairm210/Unciv#5402]
**Platform**
Operating system type, major version, architecture (64/32 bit).
- Windows 10 Build 2004, 64-bit
- Android 8.1, 64-bit

**Version**
Where you got the game and the exact version number.
- 3.17.4, both from this GitHub repository

**Describe the bug**
- Title is self-explanatory; Byzantium's unique ability, "Patriarchate of Constantinople," should allow 1 additional belief of any type, whether it's a founder or follower (or even enhancer) belief, when founding a religion. However, founding a religion as Byzantium doesn't show any sort of field that allows any kind of belief to be selected.

**To Reproduce**
1. Start a game as Byzantium
2. Gain enough Faith for a Pantheon and Great Prophet
3. Found a religion
4. The ability just doesn't work

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

**Expected behavior**
- A "Choose any belief!" (or any equivalent) should show up below the "Choose a Follower belief!" button.

**Screenshots**

**Additional context**

**Comment by xlenstra** [comment]
I thought I tested that, but I'll look into it later today
