### ISSUE TITLE
Pentagon doesn't work?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5424]
**Platform**
Android

**Version**
Any version up to now.

**Describe the bug**
The Pentagon never seems to work for me.

**To Reproduce**
1. Check how much an old unit costs to upgrade.
2. Build the Pentagon.
3. Check how much the same unit costs to upgrade.

**Expected behavior**
Already built units should cost less to upgrade after having built the Pentagon.

**Comment by Tyretes** [comment]
which version, really..
this issue 'should' have been fixed on 3.17.4..

**Comment by will-ca** [comment]
Sorry, I didn't pay enough attention to say for certain whethered it'd happened in my latest game in 3.17.4. I thought it did, but I'm not sure. If it was supposed to be fixed, then it probably was. Closing this issue. Sorry for the trouble. Will open a new one, and keep a save from right before, if it happens again.
