### ISSUE TITLE
Add the option to disable camera moving

### ISSUE THREAD

**Issue by ghost** [yairm210/Unciv#5430]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm moving a lot of units, for example, to the border with enemy state. So it is very annoying when every time I should moving my camera back to the border from each unit.

**Describe the solution you'd like**
Add the option in the settings to disable camera moving after tapping to the "Next unit" button.

**Comment by yairm210** [comment]
I understand what you're going for, but I don't see a way to do this that won't impact regular gameplay as well
