### ISSUE TITLE
Created Maps unusable

### ISSUE THREAD

**Issue by ZFGJerky** [yairm210/Unciv#5444]
**Platform**
Android 11

**Version**
Google Play Store, version 3.17.4

**Describe the bug**
I cannot use any maps I create, at first I thought it was the edits I was doing, but I then created a new map and saved it and still cannot play that map. Everytime I try to start a game with created map I get a message saying that there's too many players, except all of the maps are on huge and I even tried it with myself, 1 AI and no city states.

**To Reproduce**
1. Go to map editor 
2. Create new map
3. Change nothing and save 
4. Try to start game with new map
5. Error will pop up

**Comment by SomeTroglodyte** [comment]
Already solved.

**Comment by SomeTroglodyte** [comment]
...in #5403

**Comment by SomeTroglodyte** [comment]
Maybe because your code source is behind the actual code base? Please compare the PR merge time and the changelog - should be in 3.17.5.

**Comment by ZFGJerky** [comment]
I have 3.17.6 now, and it works fine now. Don't know it didn't work for me
in 3.17.5. Thank you.
