### ISSUE TITLE
City growth - tile to grow to

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#5469]
**Version**
3.17.6

**Describe the bug**
When the land around a city expands, the game makes some illogical choices. My guess is that it has to do with what gets taken into account:
- Playing as Canada, a lake is 3f3g1c, but the city auto-expands to an oasis, 3f1g
- With a religion God of the Sea & a lighthouse, the city expands to a cattle, 3f, instead of the atoll, 3f2p.
So I guess that neither country specials nor religion gets taken into account when the city expands?

**Expected behavior**
Expand to the tile with the highest total yields, including religion & country specials.

**Comment by yairm210** [comment]
We choose times for potential more than for direct yield since that gives far more value over time
