### ISSUE TITLE
Wrong naval vision radius.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5473]
**Platform**
Android

**Version**
Play Store, 3.17.6

**Describe the bug**
I'm not sure what the right values are, but I'm pretty sure Missile Cruisers are supposed to have more than `0` and Nuclear Submarines are supposed to have more than `1` base sight radius.

**To Reproduce**
1. Load a save with late game naval units.
2. Optionally have the Great Lighthouse or the Commerce Social Policy tree.

**Screenshots**
![Screenshot_20211012-204751](https://user-images.githubusercontent.com/37680486/137064583-837c1bf7-e4a5-4126-9ef7-22cfcf889614.png)
![Screenshot_20211012-204712](https://user-images.githubusercontent.com/37680486/137064597-c6eeb8b7-6e86-4da3-bf31-07a61ddb1eee.png)
![Screenshot_20211012-204732](https://user-images.githubusercontent.com/37680486/137064599-694c3426-0aed-43cf-9500-4bd1a7c3ffa5.png)

**Additional context**
Not sure if the Great Lighthouse and social policy are broken, the base radius is broken, or both.

**Comment by yairm210** [comment]
Solved in 3.17.7

**Comment by will-ca** [comment]
@yairm210 On 3.17.8, I've got the Great Lighthouse and Naval Tradition, but my triremes still only have 3 vision. Shouldn't it be 4?

![image](https://user-images.githubusercontent.com/37680486/137573216-96fbd81e-0751-4d53-b2d0-4921a7b55322.png)
![image](https://user-images.githubusercontent.com/37680486/137573239-e7119ad9-5abc-4bae-bffd-afbcbf62a2fe.png)
![image](https://user-images.githubusercontent.com/37680486/137573241-b1cd8663-0fef-4519-b11b-a40785c99bc8.png)

**Comment by will-ca** [comment]
@yairm210 Also the wrong movement, by my count. Is 5, should be 6.

**Comment by logicminimal** [comment]
also, say, when we implement great admirals, what will happen if the player has no borders to any kind of sea?

**Comment by yairm210** [comment]
Can you add a savefile? This looks like it should work

**Comment by yairm210** [comment]
base64

**Comment by yairm210** [comment]
This probably affected quite a few other things, so nice catch!
