### ISSUE TITLE
Maya's prophets are broken

### ISSUE THREAD

**Issue by Kleznam** [yairm210/Unciv#5498]
If you complete a long count and you choose a great prophet you will only be able to create a holy site, I rember this bug from the past, But I think xlenstra fixed it, As there was only 1 other religion and I wasn't able to found one sus.

**Comment by SomeTroglodyte** [comment]
While testing the Maya I *did* found a religion with the LC-gotten first prophet. I just had to wait a little to get a pantheon first, and move the nasty guy back into the capital.

**Comment by Kleznam** [comment]
Hmm

**Comment by Kleznam** [comment]
Iam sorry but I didn't have time the couple days before two play tests I was busy,but Maya's prophets work fine. Sorry xlenstra.

**Comment by ravignir** [comment]
> While testing the Maya I _did_ found a religion with the LC-gotten first prophet. I just had to wait a little to get a pantheon first, and move the nasty guy back into the capital.

That should not happen. If you get a prophet and there are still religion slots, you should be able to found a religion regardless of having a pantheon. In that case, you choose a pantheon belief when founding a religion.
