### ISSUE TITLE
HOW CAN I  GET  a  APK?

### ISSUE THREAD

**Issue by suncityhunter** [yairm210/UnCiv#550]
love this game ,but  how can i  get a apk setup file?

**Comment by yairm210** [comment]
Not sure I understand the question
You mean how can you build an apk from Android studio?

**Comment by Smashfanful** [comment]
Maybe you could get it from an internet site (I won't tell anyone because I'm already haunted by fear of copyright)

**Comment by yairm210** [comment]
Yeah, there are tons of apk mirroring sites if that's what you're after

**Comment by yairm210** [comment]
So... is that it?
If not, explain and reopen
