### ISSUE TITLE
Natural wonders may spawn too close to one another

### ISSUE THREAD

**Issue by Jundavr** [yairm210/Unciv#5526]
I've had many games where natural wonders spawn too close to one another. Things like Uluru 3 tiles away from Barringer Crater or Mt Fuji 2 tiles away from El Dorado. 

I suggest making it so that there's a minimum distance between a NW and another, and this distance is dependant on the size of the world map (maybe 1/4 the radius?)

**Comment by yairm210** [comment]
@SimonCeder should this be considered solved with your new map division? I don't remember if your agreed natural wonders or not

**Comment by SimonCeder** [comment]
It will be by part 4 or something, not currently. The correct minimum distance seems to be map height / 5.

**Comment by SeventhM** [comment]
Can someone confirm this is a problem? I don't think I've noticed this as a problem, and this issue is so old that I'm pretty sure this would've been addressed by then

**Comment by yairm210** [comment]
Solved by a6e61c12
