### ISSUE TITLE
Tileset visual/layering bug

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#5555]
**Platform**
Previous version: Android N
Causing bug: Android 10

**Version**
3.17.11

**Describe the bug**
After update my Android version. My tileset (Pix5 Tileset)(farm, forest, plains+jungle, jungle+trading post) become didn't work.
my previous android version never causing this.

**Screenshots**
![IMG_20211025_185519](https://user-images.githubusercontent.com/33791472/138691674-309fa23f-6395-4ce1-8956-d7c7efe8cc0a.jpg)

**Additional context**
My json was correct, but still didn't work.
And also this issue going happen because folder include name "fantasyhex".

**Comment by AdityaMH** [comment]
This work perfectly if i separate my tileset from "FantasyHex" thing.

But, this would be happen if mod tileset separated from FantasyHex:
![pix5](https://cdn.discordapp.com/attachments/633733497277775884/903169865823703160/IMG_20211028_133420.jpg)
![5hex](https://cdn.discordapp.com/attachments/633733497277775884/904484825497497620/IMG_20211101_043812.jpg)

**Comment by AdityaMH** [comment]
After, resetting my game data (i mean mod data). This bug gone, and back to normal again. Why?
![IMG_20211101_150146](https://user-images.githubusercontent.com/33791472/139640980-8b8629c1-ed62-4913-8759-78aad515b4ee.jpg)

**Comment by yairm210** [comment]
I think this may have to do with which tileset config the game reads first... Since there's the base game one and the mod one, they may overwrite each other

**Comment by AdityaMH** [comment]
New update causing tile improvment from rekmod or other mod like deciv going to blank.
If i'm using other tileset.
