### ISSUE TITLE
Add various starting options

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#559]
For example:
-No barbarians
-Only one city per civilization
-Game speed/pace (as in how many years will take one turn)
-Starting Age (Ancient, Medieval, Industrial and Future Era)

**Comment by Am-per-Sand** [comment]
If my vote counts in setting project priorities I vote for the following order (most wanted first):

1. 1 city
1. speed change

No ruins, barbarians, smelly marshes or whatever deletions seem most straightforward to be introduced, right...?
