### ISSUE TITLE
I dont know

### ISSUE THREAD

**Issue by Domina585** [yairm210/Unciv#5598]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Jundavr** [comment]
Nannngnnndjdhshssnnwmwjsbsnsn

**Comment by AdityaMH** [comment]
It's this a joke?

**Comment by Jundavr** [comment]
Just some random spamming. I was bored so I replied with some nonsense
