### ISSUE TITLE
LWJGL and JDK version shenanigans? (JDK version for build incompatible with running? LWJGL version basically unsupported, incompatible with newer JDK?)

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5601]
**Platform**
```bash
$ uname -a
Linux Hostname 5.4.150-1-MANJARO #1 SMP PREEMPT Thu Sep 30 16:13:54 UTC 2021 x86_64 GNU/Linux
```

**Version**
`Git` master.

**Describe the bug**

Following the instructions on the wiki:

https://github.com/yairm210/Unciv/wiki/Building-locally-without-Android-Studio

Build requires JDK11. However, running apparently requires JDK8, as JDK11 crashes. Thus, it seems I have to switch my Java environment between building and running.

It seems that the version of LWJGL used with GDX here is incompatible with JDK11?

Results with JDK11:

```bash
$ ./gradlew desktop:run && ./gradlew desktop:dist
> Task :desktop:run
Packing textures - 92ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/SomeUser/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

BUILD SUCCESSFUL in 1s
5 actionable tasks: 1 executed, 4 up-to-date

BUILD SUCCESSFUL in 931ms
5 actionable tasks: 5 up-to-date
```

```bash
$ java -jar desktop/build/libs/Unciv.jar 
Packing textures - 42ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/SomeDir/Unciv/desktop/build/libs/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

It all works fine if I use JDK11 when building, but then switch to JDK8 to run `Unciv.jar`.

Apparently, this is due to outdated guidelines/boilerplate/tools from GDX, that create projects with LWJGL2 instead of LWJGL3 as a dependency:

https://stackoverflow.com/questions/66580495/libgdx-keeps-giving-me-this-error-error-bad-logic-games-how-do-i-fix-this

At a glance, there does seem to be have been a consensus at LibGDX for a while that the LWJGL3 backend is ready to be the default (and is required for Java versions above 8):

https://github.com/libgdx/libgdx/issues/3673

https://github.com/libgdx/libgdx/issues/4927

Seems to have been finally switched over in July:

https://github.com/libgdx/libgdx/issues/6426 (This issue also reports a number of problems with LWJGL2 and how they're solved by switching to 3.)

https://github.com/libgdx/libgdx/pull/6463

Changing to `.gdx:gdx-backend-lwjgl3` in `build.gradle.kts` did let me avoid the above warnings while running with JDK11.

(It still crashed anyway because it "`Couldn't initialize audio,`" and ran into a `NoSuchMethodError` when trying to start OpenAL. But I think that's another issue.)

**Additional context**

Not totally sure if there's an actionable issue here. Did look through old issues and recent PRs, found #1370 from almost two years ago. Does seem on GDX's end that LWJGL2 is basically unsupported now, and certainly no longer the focus going forwards.

**Comment by yairm210** [comment]
Are you using OpenJDK 11? If so, that's probably the cause. 
I had some problems and then moved to AdoptOpenJDK 11 and the problems disappeared

**Comment by SomeTroglodyte** [comment]
That 'Inconsistency detected by ld.so' is old news. Ubuntu ships the same buggy jdk's (plural as 11 from ubuntu's repos fails same as 14 from ubuntu's repos, but using 11 or 14 from adopt works just fine). My [notes on that](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Getting-Started.md#java-jdk) are seven months old by now. And it's not _OpenJDK_ per se, if you build from their sources yourself you're OK too AFAIK, it's more like some Linux distros bungling the build.

**Comment by SimonCeder** [comment]
Manjaro's default openjdk11 gives the same error but seems to run fine so vOv
