### ISSUE TITLE
The Unciv Wiki Should Have Saves for Debugging Purposes

### ISSUE THREAD

**Issue by Interdice** [yairm210/Unciv#5607]
I am developing an AI for Missionaries and Inquisitors, but I have to play for some time to get up to that part. It is not too bad now but when developing features which are in the late game stages, development might take an unnecessarily long time.

So I propose a section in the wiki dedicated to saves in various parts of unciv with various different settings

**Comment by xlenstra** [comment]
If you need this, you can enable the "supercharged" variable. That will increase all yield thousandfold, so you can speed through the early game. Alternatively, editing your save to give yourself 1000000 faith and all the techs isn't that much work.

**Comment by Interdice** [comment]
@xlenstra 

sure I will try that
