### ISSUE TITLE
Crashes after first turn

### ISSUE THREAD

**Issue by CornelWoolrich** [yairm210/Unciv#5609]
**Platform**
Android 4.2.2.

**Version**
Play market 3.17.11.

**Describe the bug**
Crashe after first turn no matter do and despite on game settings.
<details><summary></summary>

[Save file.zip](https://github.com/yairm210/Unciv/files/7450745/Save.file.zip)

**Comment by xlenstra** [comment]
Save file appears to be missing

**Comment by CornelWoolrich** [comment]
> Save file appears to be missing

Now it is there. Sorry.

**Comment by yairm210** [comment]
Works for me
Can you test this with the recent version? If it fails, specify new version tested

**Comment by CornelWoolrich** [comment]
> Works for me Can you test this with the recent version? If it fails, specify new version tested

I tested app with the recent version, still the same, crashes after first turn.

**Comment by yairm210** [comment]
Very odd
I have no idea what could be causing this
Can you I'll let a new game and run, like, 30 turns on auto "next turn" to see if you encounter this ina different game?

**Comment by CornelWoolrich** [comment]
> Very odd I have no idea what could be causing this Can you I'll let a new game and run, like, 30 turns on auto "next turn" to see if you encounter this ina different game?

Okey, lets go.

**Comment by SimonCeder** [comment]
I was also unable to replicate on either 3.17.11 or latest.

**Comment by yairm210** [comment]
Unable to replicate from multiple team members, I'm closing this for now. If something else pops up we can reinvestigate this.
