### ISSUE TITLE
marble

### ISSUE THREAD

**Issue by FriedrichWilhelm123** [yairm210/Unciv#5616]
No increase in production capacity
![Screenshot_2021-10-31-11-00-43-42](https://user-images.githubusercontent.com/90401287/139565282-a3d89884-8607-4afa-9a05-048af47c73a7.jpg)
![Screenshot_2021-10-31-11-01-17-97](https://user-images.githubusercontent.com/90401287/139565285-e7127399-7e40-4231-b6d2-4eefb69d70b6.jpg)

**Comment by AdityaMH** [comment]
Read more carefully

**Comment by FriedrichWilhelm123** [comment]
![Screenshot_2021-10-31-13-22-06-81](https://user-images.githubusercontent.com/90401287/139569194-d95726e8-3f4a-4c49-99a9-eb91587bedf4.jpg)
"uniques": ["[+15]% Production when constructing [All] wonders [in all cities]"]Can't take effect
