### ISSUE TITLE
Add remaining Units, Building and Special Abilities for civs

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#563]
While we wait for city-states (which I think they won't come for another three months), I say we add some special ability for Greece (and perhaps Arabia). This is my idea:

GREECE (HELLENIC LEAGUE - as in Civ V):
All Cultural and Scientific buildings give +1 Culture, and +1 Science from Scientific Buildings.

ARABIA (TRADE CARAVANS):
+1 Gold from each Trade Route. Oil resource provide double quantity.

**Comment by yairm210** [comment]
I'm changing this to be more generic

**Comment by Am-per-Sand** [comment]
#123 :unamused:

**Comment by yairm210** [comment]
Remaining units is not a Civ-dependent thing, and now that units up until the modern era have been dealt with I'll close it and open a specific issue for Air units

**Comment by yairm210** [comment]
Done all we can for now.
We're still missing

- [ ] Greek unique - requires city states
- [ ] American B17 - requires air units
- [ ] Japanese Zero - requires air units

**Comment by SoraDevin** [comment]
Missing aircraft carriers too
