### ISSUE TITLE
Mysterious crash in DeCiv Redux

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#5645]
Subowicz's game is crashing unexpectedly. It first occurred in version 3.17.13, but I've been able to reproduce the bug in 3.17.14.

Original crash report: https://drive.google.com/file/d/18IRwdTXsFE6AuFDNBfucEDZwHt0E9YyC/view
Save file: https://drive.google.com/file/d/18cH0jxwWz-nMHfhzl2zf2ZWrhUXsbW_y/view

**Comment by xlenstra** [comment]
The problem appears to be that you have a land unit (militia) that can upgrade to a water unit (jet boat). When the AI tries to upgrade one of these units, it sometimes does so in a spot where there is no water anywhere nearby, crashing the game.

**Comment by yairm210** [comment]
Resolved in 367e0b9
