### ISSUE TITLE
no built buildings in the city screen, built wonders instead

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#565]

**Comment by Am-per-Sand** [comment]
Is it this one?
https://github.com/yairm210/UnCiv/commit/67eb3a86e0d32563c7c9dfd51c1afcadb1fba4ee#diff-b3dfcb069cc180624172cd4f2756b2db

**Comment by yairm210** [comment]
A. Good catch
B. Good catch by ninjatao ahead of you ;)
