### ISSUE TITLE
Add Air units

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#566]
The biggest complexity here is the UI - where to put the air units on the map

**Comment by ninjatao** [comment]
Normally aircrafts station in cities. Maybe we put show them on city button, and pop extra button for unit selection when city button is clicked?

**Comment by Am-per-Sand** [comment]
Another approach to consider:

**Air units toggling button** above the similar one that toggles tiles currently used by the player's cities. (It was used in _Panzer General_ ages ago) When pressed, hides (or fades) ground and naval units and displays only air units. In cluttering circumstances Overview->Units could solve doubts and find hard-to-spot units.

**Comment by yairm210** [comment]
This is finally done!
