### ISSUE TITLE
Use KotlinX instead of GDX for JSONs?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5664]
Neither a bug report nor a feature request.

AFAICT, the GDX JSON tools used by `JsonParser.kt` work by creating new instances of classes, with zero arguments, and then assigning values to their members from the JSON file.

It was also designed only for Java, I believe, and does not support Kotlin-specific idioms/features.

This seems to create several limitations:

* No support for data classes.
* Requires default initializers for all properties. (Adds noise to code, leaves room for silent failure if the `.JSON` fails to define some required value.)
* No support for immutable `val` properties. (Again, creates unnecessary room for silent failures.)
* No/poor support for deserializing into interfaces/arg-requiring constructors. (E.G. `Map<>`, probably `List<>` and `Array<>`.)
* Ugly `SomeClass::class.java` syntax.

For the IPC protocol in #5608, I decided to go with the official KotlinX serialization library as standards compliance is more important there, and it's been great for (de)serializing objects with known structure.

KotlinX also describes itself as supporting a "lenient" deserialization mode, which looks like it should be largely compatible with the "Javascript" and "Minimal"-style unquoted JSON files currently parsed with GDX (and you can write custom deserializers too, though I found it a bit painful to do so):

https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md

Might it be a good idea to switch JsonParser to use the official KotlinX JSON tools instead of GDX?

### Comparisons

KotlinX:

```Kotlin
data class TileSpec(
	val tileYield: Map<String, Int>,
	val someList: List<String>,
	val immutableNumber: Int
)

val tileSpec = Json().decodeFromString<TileSpec>(jsonString)
```

GDX:

```Kotlin
class TileSpec() {
	var tileYield = HashMap<String, Int>()
	var someList = ArrayList<String>()
	var immutableNumber = 0
}

val tileSpec = Json().fromJson(TileSpec::class.java, jsonString)
```

IMO the biggest thing is (apparently) being forced to use mutables. Most stuff that gets loaded from JSONS is probably also stuff that shouldn't ever change.

---

Some of much of this may just be incorrect usage on my part, but I'm not sure how much if any.

**Comment by yairm210** [comment]
An important factor here is the library size.
Unciv is specifically aimed at the lower end of devices, and the compiled apk currently stands at around 8MB
How large is the kotlinx library you intend to use?

**Comment by will-ca** [comment]
@yairm210 Oh, hm. Right. I hadn't thought about that. I definitely have noticed how Unciv performs better on my slow phone than Civ V performs even on my laptop, and I do appreciate that as an impressive technical achievement worth upholding.

Not sure how big `kotlinx.serialization` is, and apparently the devs haven't measured it themselves, but they say it doesn't bring in any external dependencies other than the standard library:

https://github.com/Kotlin/kotlinx.serialization/issues/150

The repository's apparently around 100k lines, of which 29k are Kotlin code and the rest are mostly JSON:

https://codetabs.com/count-loc/count-loc-online.html

Don't know if the .JSONS are needed, or part of tests or something. ...Can't imagine why you'd need 100k lines of JSON to define a format spec, though.

It also includes encoders for at least five different types of serialization formats, I think, of which only one is JSON. Not sure if Gradle can separate out the stuff that's not needed.

For reference:

Unciv itself was ~60k LoC of Kotlin, and many more of `.properties` files (220k, apparently), before it grew past that online counter's 500MB limit, which `wc -l` agrees with.

Not sure how big GDX is. The repository's too big for the online tool, and also too big for me to want to download it just to estimate its size.

My working tree for #4788 currently compiles into a `.jar` for Desktop that's `29,446,931` bytes. The Git master compiles into `25,683,278`. The difference includes `kotlinx.serialization`, but also `kotlin.reflect.full`, as well as the (relatively insignificant) amount of code in that PR itself. So... Not negligible, but not disastrous either it seems IMO.

(…8MB? Really? Wow. Pretty sure a lot of games have sound files that are bigger than that. What's the difference in structure between the APK and the JAR?)

**Comment by yairm210** [comment]
I assume the size difference is because the jar contains os-specific fits for Mac windows and Linux, as well as support for different architectures?
It also has several libraries that I felt fine putting there because of the relative lack of resource constraints, like the image packing and the discord rpc lib

**Comment by yairm210** [comment]
So yeah, this is a no-go in the core project from a cost benefit perspective

**Comment by logicminimal** [comment]
> So yeah, this is a no-go in the core project from a cost benefit perspective

is the problem the size?

**Comment by will-ca** [comment]
@logicminimal He said "cost-benefit", so... The benefit's also fairly small, just some minor syntactic and semantic QoL improvments. And in addition to the size, a lot of (if not most of) the existing classes would also have to be changed to make use of it, so the cost is pretty major if you're not rounding your available resources up to `∞`.
