### ISSUE TITLE
move automated units should redirect you to the automated units when you press it, not after you press it then press next unit

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5672]
dont know if this is in the original game but iirc it is in civ vi

**Comment by logicminimal** [comment]
actually, according to further observations of mine, the game automatically moves thrm, whivh should be manual

**Comment by yairm210** [comment]
No.
This automatically moves those units so no manual work is needed.

**Comment by logicminimal** [comment]
> No.
> This automatically moves those units so no manual work is needed.

but this is literally what was already done before this button was added? the difference is that they werent moved mid turn, but at the end of the turn, %95 of the time the units already lose all their mp so you already cant even move them, which kind of obseletes this functionality?

**Comment by xlenstra** [comment]
This functionality is for the 5% of units that still had movement points left.

**Comment by logicminimal** [comment]
> This functionality is for the 5% of units that still had movement points left.

but... those will already move in the end turn. we should just copy whatever cov 5 or civ 6 does

**Comment by xlenstra** [comment]
What civ 5 does, is you press 'next turn', then it moves the units, and then, if any of those units still have movement left, you regain control of your turn to move your units.

What unciv does, is you press 'move automated units', then it moves the units, and then, if any of those units still have movement left, you can still move those units. If you're done, you can press 'next turn'.

This way, when you press 'next turn', you always know what is happening, and aren't surprised with the next turn not actually starting.


This entire discussion has already been had multiple times in issues and PR's referencing that this feature from civ 5 was missing.

**Comment by xlenstra** [comment]
> > This functionality is for the 5% of units that still had movement points left.
> 
> but... those will already move in the end turn. we should just copy whatever civ 5 or civ 6 does

Also, they will not move at the end of the turn, the entire point is that units that _don't_ spend all their movement at the end of the turn can still be controlled to spend the last few movement points

**Comment by logicminimal** [comment]
> What civ 5 does, is you press 'next turn', then it moves the units, and then, if any of those units still have movement left, you regain control of your turn to move your units.
> 
> What unciv does, is you press 'move automated units', then it moves the units, and then, if any of those units still have movement left, you can still move those units. If you're done, you can press 'next turn'.
> 
> This way, when you press 'next turn', you always know what is happening, and aren't surprised with the next turn not actually starting.
> 
> 
> This entire discussion has already been had multiple times in issues and PR's referencing that this feature from civ 5 was missing.

so unciv still redirects you to units that still have mp even after move automated units?

**Comment by xlenstra** [comment]
> > What civ 5 does, is you press 'next turn', then it moves the units, and then, if any of those units still have movement left, you regain control of your turn to move your units.
> > What unciv does, is you press 'move automated units', then it moves the units, and then, if any of those units still have movement left, you can still move those units. If you're done, you can press 'next turn'.
> > This way, when you press 'next turn', you always know what is happening, and aren't surprised with the next turn not actually starting.
> > This entire discussion has already been had multiple times in issues and PR's referencing that this feature from civ 5 was missing.
> 
> so unciv still redirects you to units that still have mp even after move automated units?

That is the entire idea of the feature; if you order a unit to move to a square but it still has mp left when it arrives, you should still be able to give it a new order this turn.

**Comment by logicminimal** [comment]
> > > What civ 5 does, is you press 'next turn', then it moves the units, and then, if any of those units still have movement left, you regain control of your turn to move your units.
> > > What unciv does, is you press 'move automated units', then it moves the units, and then, if any of those units still have movement left, you can still move those units. If you're done, you can press 'next turn'.
> > > This way, when you press 'next turn', you always know what is happening, and aren't surprised with the next turn not actually starting.
> > > This entire discussion has already been had multiple times in issues and PR's referencing that this feature from civ 5 was missing.
> > 
> > so unciv still redirects you to units that still have mp even after move automated units?
> 
> That is the entire idea of the feature; if you order a unit to move to a square but it still has mp left when it arrives, you should still be able to give it a new order this turn.

oooh i get it now
