### ISSUE TITLE
add an option to enable attacking the related subject unit when under thr control of that unit's zoc

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5673]
this is more of a reminder for me to implement this as a mechanic that could be used by mods (most often mods that change only a single thing like a certainechanic, which wouldnt go well with generic mods) but if someone else wishes to implement this, they are welcome

**Comment by yairm210** [comment]
Reminders to yourself for *non-canonical* functionality should not be in Unciv issues

**Comment by logicminimal** [comment]
> Reminders to yourself for *non-canonical* functionality should not be in Unciv issues

i guess ur right
