### ISSUE TITLE
Honor policy's adjacency bonus should only be calculated for the unit's future position right before the attack call, not the current position

### ISSUE THREAD

**Issue by ajustsomebody** [yairm210/Unciv#5674]
![Screenshot_20211114-194339_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/141690107-3f784c50-c979-4688-b049-c5df0f7f117b.jpg)

**Comment by yairm210** [comment]
Please attach save file

**Comment by xlenstra** [comment]
This is actually true for more effects, such as great general boosts iirc

**Comment by logicminimal** [comment]
> Please attach save file

https://www.toptal.com/developers/hastebin/raw/bigofikawe

(rip hastebin)

**Comment by SeventhM** [comment]
Can someone confirm if this is still an issue?
