### ISSUE TITLE
the autosaves iirc are saved at the end of the turn, start of the new turn in civ games (atleast for civ 6)

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5675]
unlike the turn start one implemented in unciv

**Comment by yairm210** [comment]
No need for 2 autosaves each turn

**Comment by logicminimal** [comment]
> No need for 2 autosaves each turn

2 autosaves arent being held for each turn, it goes a bit as this;

end turn, calculate stuff, next turn commences, save the game

what you think is end turn, save the game, calculate stuff, next turn commences then save the game

**Comment by xlenstra** [comment]
Currently, autosaves are made throughout the turn. If you spent a lot of time moving lots of units, your progress is auto-saved throughout your turn anyway. The only reason I can think of that you'd want to have an auto-save at the end of the turn, is that your game crashes halfway through and you lose a lot of progress. That is already solved by this method, so no reason to make additional auto-saves at the end of each turn.

Additionally, if you only have auto-saves at the end of a turn, the AI still need to do their turn when loading back in, which in some cases takes a long time. Having it at the start means you can jump right back in where you left of.

I see no reason to change this behaviour either.
