### ISSUE TITLE
Moddable Culture Bomb Unique

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv#5678]
In Civ5 Vanilla Great Artists have an ability called Culture Bomb which worked similarly as the Great General's citadel able to expand and steal borders, minus the tile improvement.

I wondered if we can make this moddable. We can have 2 separate uniques, one as unit ability (in case for Vanilla Great Artist), another as tile improvement unique (In case for G&K Citadel).
Example as follows:
As unit ability, `[Can use culture bomb]`.
As tile improvement unique, `[Annexes adjacent territory]`.

So this is my request, can this unique made moddable like that?
Thanks for reading.

**Comment by logicminimal** [comment]
also, someone wishes to implement this, there surely are some mods that could benefit from this, like pastures providing culture bombs with poland in civ 6 (iirc)

**Comment by yairm210** [comment]
Please add to #3242 which exists for this purpose
