### ISSUE TITLE
`isMinifyEnabled = false`?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5691]
While thinking about the impact that #5608 would have on APK size following notes about size in #5664, I found out about the `minifyEnabled` Gradle build setting:

> Code shrinking with R8 is enabled by default when you set the minifyEnabled property to true. Code shrinking (also known as tree shaking), is the process of removing code that R8 determines is not required at runtime.

https://developer.android.com/studio/build/shrink-code#shrink-code

It doesn't seem to be turned on currently in the Android Gradle script:

https://github.com/yairm210/Unciv/blob/422bb588142383b47dfddc21e9888b0ed5337034/android/build.gradle.kts#L52-L58

Git Blame seems to show the off state as a default setting that was likely inherited from boilerplate without any particular intent:

https://github.com/yairm210/Unciv/blame/master/android/build.gradle.kts#L29-L57

Would this be worth enabling and setting up? Surely not all of LibGDX is used at some point in Unciv.

In the context of #5608, I was looking at unused class removal because I use the `kotlinx.serialization` library but I'm not sure I use it fully, plus `kotlin.reflect.full`.

(That said, I could also see asking for this to be turned on biting me in the back if it ends up removing classes that I need to be able to access with reflection from the scripting API but which aren't usually used.)

**Comment by yairm210** [comment]
I don't have any particular reason not to enable this
If it works then why not
