### ISSUE TITLE
Closing Civilopedia should send you back to whatever you where looking at before opening it

### ISSUE THREAD

**Issue by forteller** [yairm210/Unciv#5692]
Not exactly sure if this is a bug report or a feature request, but it feels like a bug.

**Describe the bug**
When you close Civilopedia, you expect to go back to where you where, whether that's the Tech tree, a city, or whatever. But what happens now is that you get sent back to the map, and you have to click back in to the tech tree or city, etc.

Would love to see this fixed. Thank you so much for an amazing game!

**Comment by will-ca** [comment]
Only works for hardware back button, not graphical "Close" button.

`previousScreen` is used only in `onBackButtonClicked`:

https://github.com/yairm210/Unciv/blob/bdeccb87e827b3aad1a17ed8171f493ac79092a9/core/src/com/unciv/ui/civilopedia/CivilopediaScreen.kt#L172

`onBackButtonClicked` only affects keypress dispatcher:

https://github.com/yairm210/Unciv/blob/bdeccb87e827b3aad1a17ed8171f493ac79092a9/core/src/com/unciv/ui/utils/BaseScreen.kt#L107-L109

Graphical button still goes to `worldScreen`:

https://github.com/yairm210/Unciv/blob/bdeccb87e827b3aad1a17ed8171f493ac79092a9/core/src/com/unciv/ui/civilopedia/CivilopediaScreen.kt#L240-L244

Easy to miss, straightforwards fix. But I'm going to try to unify all "go back to previous screen" behaviour in a simple interface instead.

(Also, should only one of those be calling `dispose()`? I guess it's probably not mandatory.)
