### ISSUE TITLE
Citizen Production Focus

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#5700]
**Is your feature request related to a problem? Please describe.**
In Civ5 you can Focus your citizens to maximize a particular production stat.

**Describe the solution you'd like**
Adding the ability to focus production towards a particular production stat.
Respect locked workers to tiles.
Civ5 handled Specialists as either Manual or Automated. No locking.
Button to reset all locks and switch back to default.
This likely needs to be a second panel in the City Management screen in the upper-right that can swap between specialist management and selecting production focus. Or adding a drop-down menu. Or could interact with the city's total production icons.

**Additional context**
See screenshot here (particularly upper right):
https://www.carlsguides.com/strategy/civilization5/cities/citizensworkingtiles.php

**Comment by SomeTroglodyte** [comment]
I have repeatedly considered this as I remembered the "governors" from Civ 4 (or maybe even before that), but I never had 5, so it's nice to see those screenshots.

**Comment by xlenstra** [comment]
Already requested in #4697, closing as a duplicate.
