### ISSUE TITLE
Helicopter Gunship issues

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#5703]
**Platform**
Android

**Version**
Latest version

**Describe the bug**
Embarked movement number of moves is incorrect

**To Reproduce**
Steps to reproduce the behaviour:
1. Build Helicopter Gunship with available XP
2. Upgrade with Mobility 1
3. Enter sea tile
4. Embarked movement is 6, when it should be either 4 (like other embarked units) or 7/8 (like the upgrades allow).
Not sure which of the two is right, but 6 must be wrong.

**Comment by yairm210** [comment]
Can you add a save file? Code shows that it should have embarked movement + bonus movement, so if you say it had 6 then it probably has 2 extra movement, I assume

**Comment by yairm210** [comment]
...
Code seems fine, so unless proven otherwise, I'm going to assume it's fine

**Comment by xlenstra** [comment]
I think the problem was that the sight boosts also affected embarked units, so the +2 vision he had normally on his helicopter was also active when embarked. If I recall correctly, this technically differs from the behaviour of the original game, where embarked units always had 1 vision
