### ISSUE TITLE
City states with identical colours.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5721]
**Version**
Git master.

**Describe the bug**
Writing a colourblindness tester, I've found three sets of city states that have either completely identical or very similar colours:

```python3
>>> testNations(minprevalence=0.5)
Kuala Lumpur and Edinburgh may be hard to tell apart with Normal_Vision. (Difference: 0.0)
Kuala Lumpur and Valletta may be hard to tell apart with Normal_Vision. (Difference: 0.0)
Belgrade and Dublin may be hard to tell apart with Normal_Vision. (Difference: 0.0)
Edinburgh and Valletta may be hard to tell apart with Normal_Vision. (Difference: 0.0)
Cahokia and Jerusalem may be hard to tell apart with Normal_Vision. (Difference: 0.0703970853264033)
Found 5 potentially problematic pairings.
```

Since there are hundreds of possible pairings over dozens of city states, this is actually quite good.

Still, they should probably be changed.

**Comment by SomeTroglodyte** [comment]
Edinburgh and Dublin should be out ("Will not be chosen for new games" unique - might be time to treat that as a deprecation that can be removed) as they're now in Celt's city list. I vaguely remember choosing Valletta (definitely) and Belgrade (? did I? Yup, those tongue-in-cheek texts sound like mine) as direct replacements. And the religious CS were originally all white if I remember correctly, so them still being close isn't that surprising. Some CS replacements should probably be reverted for the new Vanilla ruleset...

**Comment by yairm210** [comment]
Until this is solved (disclosure - I'm not planning on dealing with this), let's merge all relevant information into a single issue
I think #5722 's title is more apt for what we're going for
