### ISSUE TITLE
Add Section/Divisions in Civilopedia

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#5726]
**Suggestion**
I don't know if this was suggested here in Github before but I think it's good if we add a proper division within the editing in Civilopedia, just to make it look more organized. Take the picture below for example, there's a section for quote, info, etc.

**Additional context**

![image](https://user-images.githubusercontent.com/83058051/143833734-0a429ef6-4f49-45f8-9d34-74fd864e0c42.png)

**Comment by SomeTroglodyte** [comment]
Really? Firaxis published that factual error (Aztec _not_ Maya) and such an embarrassing typo (it's does not stand for it is down there)? Or is that a modded wonder?

**Comment by NoviceCoder2000** [comment]
I am not sure since I never have played it. But just to clarify, what I meant to state is to have a bit of a similar UI design like this in the civilopedia screen.

**Comment by yairm210** [comment]
I thought about this and the answer is no.
The current Civilopedia looks good enough, and changing the textflow-based view to a location-based view means a lot less flexibility and a lot more annoyance.
