### ISSUE TITLE
Broken at API Level 17.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5737]
**Platform**
Android Studio/AVD-emulated Nexus 4 with `"Jelly Bean" API Level 17 x86 Android 4.2 (Google APIs)` image.

**Version**
Git master, within one or two commits.

**Describe the bug**
I suppose that officially, API Level 17 is supported by the `minSdk` value.

However, the game doesn't seem to actually work in an emulator at API Level 17:

![image](https://user-images.githubusercontent.com/37680486/144161965-850fde94-95af-473b-93c8-8dfdbb543908.png)

```
W/System.err: java.lang.NumberFormatException: Invalid int: "+3"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parse(Integer.java:375)
        at java.lang.Integer.parseInt(Integer.java:366)
        at java.lang.Integer.parseInt(Integer.java:332)
        at com.unciv.logic.map.TileInfo.getTileFertility(TileInfo.kt:367)
        at com.unciv.logic.map.mapgenerator.MapRegions.generateRegions(MapRegions.kt:84)
        at com.unciv.logic.map.mapgenerator.MapGenerator$generateMap$10.invoke(MapGenerator.kt:85)
        at com.unciv.logic.map.mapgenerator.MapGenerator$generateMap$10.invoke(MapGenerator.kt:84)
        at com.unciv.logic.map.mapgenerator.MapGenerator.runAndMeasure(MapGenerator.kt:107)
        at com.unciv.logic.map.mapgenerator.MapGenerator.generateMap(MapGenerator.kt:84)
        at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:54)
        at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:51)
        at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:127)
        at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:51)
        at com.unciv.ui.newgamescreen.NewGameScreen.newGameThread(NewGameScreen.kt:196)
        at com.unciv.ui.newgamescreen.NewGameScreen.access$newGameThread(NewGameScreen.kt:24)
        at com.unciv.ui.newgamescreen.NewGameScreen$3$4.invoke(NewGameScreen.kt:130)
        at com.unciv.ui.newgamescreen.NewGameScreen$3$4.invoke(NewGameScreen.kt:128)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

See: #3927. A slightly newer version of Android had further game-breaking errors. The decision was to not waste time supporting it.

That said, if there's no plans to support versions this far back, then IMO the `minSdk` should be bumped up to the minimum version that *is* actively supported, so that 1. Users won't be frustrated by downloading a broken app (…Though I suppose such users may be largely theoretical.) and 2. New code can have free reign to use features that work for all supported versions.

**Comment by yairm210** [comment]
Ok
What's the minimum that does support this?

**Comment by will-ca** [comment]
According to StackOverflow and the Java docs, this crash with `parseInt` is due to a limitation of Java 6¹(!) as compared to Java 7:

https://stackoverflow.com/questions/10685906/integer-parseint-in-java-exception-when-comes-first/10685943#10685943

It's not too clear to me, but I *think* that might mean the required (Java 7) behaviour was added in API Level 19:

https://stackoverflow.com/questions/20480090/does-android-support-jdk-6-or-7/22303654#22303654

As API Level 19 corresponds to KitKat, that would also explain why SomeTroglodyte didn't seem to encounter this issue in #3927.

That said, bumping the API level up to 19 would still leave unresolved the two bugs in #3927. Another approach could be to specify the minimum level that's *worth* supporting, and then try clicking all the buttons/playing through a quick game at that level to verify that everything's working or fix things as needed.

(I finally caved and installed AS the other day so I could more easily check that my CLI branch still builds and runs on Android. I've gone with three AVDs: The newest recommended by Google (30), the oldest recommended by Google with the Play Store (24), and the Unciv `minSdk` (17). FWIW, 24 seems to work alright (though leaving 11% of devices unsupported).)

If 19 isn't supported, then I suppose the next one up is 21, which also feels to me like the oldest "modern" Android, which seems to be a common-ish target for other projects from some Googling, and after which unsupported devices seem to start increasing exponentially. 17 leaves 0.2% of devices unsupported, 21 leaves 2%, and 24 leaves 11%.

But all the "bugs" found so far also seem like they could all be fixed in less than an hour, so that's also an option and I would probably try to PR it if given the go-ahead. A `.toList()` and `.trimStart()` would fix both the game-breaking crashes, and a shared "Not supported in your Android version." popup would probably be enough to work around any non-game-breaking issues that pop up. But the question is whether supporting the 1%-2% of affected ancient devices (which may not have hardware able to support a decent gaming experience even if the software works, and the user demographic of which may be further uninterested in this app) is worth messing with existing code and placing restrictions on new code.

Hm. @yairm210 Do you have access to any install, play time, or launch count statistics through Google Play? Presumably there'd be a hard cutoff somewhere in the Android version/API Level distribution, below which the number of users is basically zero, due to the app simply not working below that version.

---

¹ I think that's the version that was the shiny standard JDK when I played Minecraft…

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/144580827-79ffd960-e169-4762-b411-6b5ce67a9b03.png)

![image](https://user-images.githubusercontent.com/8366208/144580985-4ddea906-674d-4d0a-b849-34d26019a612.png)

Android 6 AND BELOW - 3%
Android 7 - 4%
Android 8 - 3% 

Android 7 is sdk version 24
So basically we can go to 24, losing the bottom 3% of our users
Sounds legit to me

**Comment by will-ca** [comment]
3% sounds way less to my ears than 1/30, even though they're the same number. On the Discord alone, it looks like that might mean as many as 150 people stop being able to play Unciv all of a sudden.

The actual numbers may be way less, as presumably regular players would also slant towards newer tech. Also, I'm a total backwards compatibility freak, so I'm generally not going to agree with cutting off 11% of technically active devices, but keep in mind that is partly just me being crazy.

Opened #5744 , which may present an alternative by enabling ~~conic patches~~ ~~patched conics~~ some kind of compiler-level "PolyFill" or something for Java 8 on lower API levels. If it's accepted, I'll test at 21— If that works, then I think that means there won't be any additional maintanence burden from supporting 21 instead of 24, since most of the relevant Java 8 features are shimmed at compile time anyway.

**Comment by yairm210** [comment]
In my opinion most of the java 8 functionality comes from Kotlin anyway, napping the java 7 vs 8 really not that big a deal.

**Comment by will-ca** [comment]
I'm not qualified to comment on whether shimming Java 8 would be worth it, but you're probably right. I'm a bit surprised at how few API level version problems I actually ran into or found, despite coding basically blindly with no or little reference to API level (and the single one I did run into is probably more the fault of Java than of Android).

**Comment by touhidurrr** [comment]
> ![image](https://user-images.githubusercontent.com/8366208/144580827-79ffd960-e169-4762-b411-6b5ce67a9b03.png)
> 
> ![image](https://user-images.githubusercontent.com/8366208/144580985-4ddea906-674d-4d0a-b849-34d26019a612.png)
> 
> Android 6 AND BELOW - 3% Android 7 - 4% Android 8 - 3%
> 
> Android 7 is sdk version 24 So basically we can go to 24, losing the bottom 3% of our users Sounds legit to me

@yairm210, if the Java 8 APIs that you are planning to implement on Unciv is in the following list, you might not need to require a higher Android API version in the first place.
https://developer.android.com/studio/write/java8-support-table
https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by touhidurrr** [comment]
I personally do not think that requiring more that Android 4.2 or at most 5.0 is a good idea.

**Comment by will-ca** [comment]
@touhidurrr See the PR linked above. Raising the API level was decided to be preferable to shimming. Given how complicated the systems involved are, and having not yet myself encountered any API level concerns that would be solved by desugaring, I think that's certainly an understandable position from the perspective of stability.

Personally I think 21 would be a good target, with the bias that I have a device that's a bit close to 24.

@yairm210 FWIW, API level 21 seems to be fine. Nothing crashed with holding the spacebar down, running reflective scripting API tests (which indirectly trigger much of the normal core code), or increasing `simulateUntilTurnForDebug` in ~100-turn increments until victory— Did get some warnings about audio, but meh.

**Comment by yairm210** [comment]
Okay
21 it is then
We can always advance later if necessary :)

**Comment by touhidurrr** [comment]
Ok, I checked the convo in https://github.com/yairm210/Unciv/pull/5744, I would like to quote some statements from there and this convo, Pardon my intrusive behavior, lol.

> I'd rather raise the api level directly to 24 than try and shim in missing java 8 functionality for the bottom 3% of devices, many of which may not even be played at all (by yairm210 in https://github.com/yairm210/Unciv/pull/5744)

Now, what do higher versions in any programming language mean? As far as I see, most of the time Higher language versions typically mean deprecating some part of the internal Methods, Classes, and Libraries, etc., and introducing new methods and Classes to replace them. Breaking changes that require seriously considering higher Language versions are seldomly made. So, higher API versions, what does it offer? Some method classes and stuff? if that's the only thing they offer and we have options to include those functionalities even without requiring higher API versions `(like desugaring)` then why not just use them? Especially when according to @will-ca in his pr, desugaring would only increase APK size like 396 Bytes. I don't think that unreasonable.
> Given how complicated the systems involved are, and having not yet encountered any API level concerns that would be solved by desugaring, I think that's certainly an understandable position from the perspective of stability. (by will-ca)

What do you exactly mean by `having not yet myself encountered any API level concerns that would be solved by desugaring`? Would desugaring solve the bugs or not? if it solves them then why not?

**Conclusion:** I don't see any benefit in requiring higher API levels if desugaring solves that. As, I only see higher API levels as just adding some more java libraries, nothing more. I may be wrong but I think this topic needs more discussions in case you are thinking of raising API levels, that's all.

**Comment by will-ca** [comment]
It's Java. A programming language with such a corporate reputation seems to have put a lot of emphasis on backwards compatibility. The problem isn't losing old features; It's new features not being supported on old platforms.

Those are kB, not B. But either way, level 24 would have been 3% of users versus 3% APK size increase. (Though *active* users may well be far less.)

I agree with Yairm210 in that the gain from desugaring would be minimal, since Kotlin already provides a lot of the most useful functionality that might come from newer Java versions.

IMO the real cost of desugaring isn't APK size, but complexity. Using Google's desugaring tools means inheriting all the *bugs* in Google's desugaring tools, which means having a significantly longer and messier list of Things That Can Go Wrong. Do you know how to write a bytecode-to-bytecode compiler? Maybe you do, but I don't, and I don't think most people do, so I don't think we'd have much initial success trying to fix any problems that pop up because of one. Plus, the transformation probably messes with stack traces or something.

Just recently, a change to a build setting that was also made at my suggestion [completely stopped the game from running](https://github.com/yairm210/Unciv/commit/72d16dbcd47d4666e2b2ceed776e99a0e41d5a5f), and may apparently made it into a release build. The advertised functionality was also simple— "Turn this flag on and get smaller APK sizes"— But the implementation is of course more complicated and left a lot more to go wrong.

I mean that in the Kotlin code I've written, I was surprised that I never really ran into any issues with API level, despite not even running any checks for it until I was well into it. I don't know if desugaring would solve the existing bugs. It wouldn't at 21, because there don't seem to be any API level issues at 21. Everything below that is poorly supported by desugaring (requires `multiDex`), very deprecated by Google (last updated 2014), not currently part of the player base (since it already doesn't work), probably not used by the type of people that would be interested in the game even if they could run it, and, in the case of the bug in this issue, may not even be fixed by desugaring (since it's a change in a method's behaviour, rather than the addition of a new method).

Also, in practice, 21 wouldn't even *be* an API level bump. See the initial comment and the issue linked in it. Everything below 21 already has game-breaking bugs, so the effective minimum API level and the minimum device support of everyone that is currently able to play this game is already API 21.  We would just be updating the build script to reflect the existing practical reality.
