### ISSUE TITLE
Civilopedia Entry on Rivers and Fresh Water

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#5739]
**Is your feature request related to a problem? Please describe.**
Currently no entry about Rivers and Fresh Water

**Describe the solution you'd like**
Clear indication on how the mechanics of Rivers work and how Fresh Water works. Especially since they are crucial to several basic mechanics and specific buildings.

**Comment by SomeTroglodyte** [comment]
Rivers do not correspond to a ruleset object and therefore so not appear in Civilopedia.
We could create a tutorial for rivers and/or fresh water, and having links to e.g. oases or lakes in that tutorial, or links from ruleset object entries to that tutorial should be no big deal. Hmmm... Oops, we never converted the tutorials to full FormattedLine format, so linking from a tut would be a little more work than linking to.
OR we could hardcode adding one or two "faked" terrain entries to the Civilopedia terrain list. Uglier code, but maybe nicer for the user?

Either way, someone would need to start out formulating the explanation text, and I'm too lazy these days.

**Comment by itanasi** [comment]
Yeah, best for the user would be "faked" terrain entries for Rivers. That's how Civ5 seems to handle it in their Civilopedia. Figuring out a way to make it a true ruleset object would obviously be the better solution. Even though it's a weird in-between hex object and has it's own special code set.

A general Tutorial about Fresh Water would also be helpful to explain the mechanisms associated with it. And then link any other mentions of Fresh Water to the Tutorial entry. For example, I believe cities on the same River should count as "Connected" as if by roads (or they were in Civ5 if I'm remembering correctly). But that's not mentioned anywhere.

**Comment by yairm210** [comment]
Closing as 'not in roadmap' as part of our cleanup
