### ISSUE TITLE
Recycling Center Improvement

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#5745]
**Is your feature request related to a problem? Please describe.**
Recycling Centers are limited to 5 per Civ. To maintain this, you cannot build or enqueue more than 5. And when you obtain new cities, if it would put you over the limit, they are destroyed in the new city.
However, this is sub-optimal. Perhaps a better solution would be to check first the build queues for any Recycling Centers and remove the one with the least amount of hammers committed (and refund in Gold).

**Describe the solution you'd like**
Change new city logic to add a step to check if there are Queued Recycling Centers, order by number of hammers already committed, and destroy (and refund in Gold) the one with least hammers before destroying built ones in the new city.

**Describe alternatives you've considered**
Leave behavior as is

**Additional context**
I have no idea how Civ5 handled this

**Comment by SomeTroglodyte** [comment]
Really, the limit counts both built and in-progress??? IMHO it should work the same as other can't-continue-constructions situations like lost wonder race; and the count leading to destroying buildings should count only actually existing ones...

**Comment by itanasi** [comment]
I did that so that you don't queue up say 6 of them, and then once your 5th is built you get rebated the progress on your 6th.

Wonders can work this way because you can't self-sabotage by building 2 Wonders at the same time and beat yourself to the limit of 1.

But the idea of you gaining your last one via a new city, so then perhaps rebate an in-progress one came from thinking of the Wonder races.

**Comment by yairm210** [comment]
Closing due to lack of interest
