### ISSUE TITLE
Domination Victory Inaccurate

### ISSUE THREAD

**Issue by Interdice** [yairm210/Unciv#5767]
**Platform**
Operating system type, major version, architecture (64/32 bit).
Android 11, 64 bit

**Version**
Where you got the game and the exact version number.
I got the game from the play store. 3.18.5-patch1

**Describe the bug**
For a domination victory you only need to invade the capitals. In this game you need to capture every city that is not a city state.

**Comment by xlenstra** [comment]
Intentional, see the discussion in #4041.

**Comment by xlenstra** [comment]
Duplicate of #2005
