### ISSUE TITLE
Unable to capture civilian units

### ISSUE THREAD

**Issue by PangXH842** [yairm210/Unciv#5772]
**Platform**
Android

**Version**
3.18.7

**Describe the bug**
![Screenshot_20211208_085356_com unciv app](https://user-images.githubusercontent.com/80996300/145129248-ba1fa1fe-083a-453a-ab82-61ccc1fbed18.jpg)
I can't capture the Persian settler in this screenshot. Before that, I was unable to capture a worker from The Netherlands as well. 

**To Reproduce**
1. Move melee units near a civ's borders
2. Wait until their worker/settler is exposed
3. Try to capture it

**Expected behavior**
Can't move melee unit to capture the civilian unit.

**Screenshots**
See above

**Additional context**
I was able to capture a ruin worker from The Netherlands at the beginning of the game, but I think the game updated halfway through.

**Comment by yairm210** [comment]
Solved in 3.18.8 :)
