### ISSUE TITLE
translations : 

### ISSUE THREAD

**Issue by satorope** [yairm210/Unciv#5773]
**Platform**
Windows 10 64bit

**Version**
3.18.8

**Describe the bug**
I started translating into Japanese.
There is no translation data of a greeting sentence displayed when starting a game by selecting India.

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xlenstra** [comment]
Seems to me it is on line 5237?

**Comment by satorope** [comment]
I didn't realize it was far away.
