### ISSUE TITLE
Slower researches

### ISSUE THREAD

**Issue by Golden542** [yairm210/Unciv#5780]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i enter in the modern era and the researches start to go faster than the buildings and units

**Describe the solution you'd like**
You could make an option in the new game menu that progressively slows down research while keeping production the same

**Describe alternatives you've considered**
You could slowly increase the required research points to unlock the new technologies, with different increasing values to choose, like in the game speed settings
(I don't know if the population growth will be able to stay the same due to the increased duration of the game)

**Additional context**
Im producing giant death robots and theyre using canons, and if i build the national college ill almost have finished all the researches before finishing it
Even my friend is disapointed with how faster the research progress is going
(Sorry about the bad english, im brazilian)

**Comment by ravignir** [comment]
But research costs do increase. You just have a nice science output and bad production.

**Comment by yairm210** [comment]
A. We're not going to change the production to science ratios
B. It does sound like you have low production if you're getting to this point
