### ISSUE TITLE
Upgrades to the city "Governor"

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#579]
You know, the AI that automatically selects what to build next in a city. It would be much less annoying with those two minor upgrades:

1. It should go back to the unit/building that was under construction before you bought something else. Now, instead of reverting, it tries its hand at building something new...
2. Once a more technologically advanced unit of a certain type is available, it should not try to build less advanced unit. E.g.: once you can build caravels, it shouldn't try and start building triremes... or once you can build knights, let's not go and try building riders..

**Comment by yairm210** [comment]
Point 2 is actually already implemented, did you encounter such situations?

**Comment by flecheapolinienne** [comment]
yes, absolutely. both examples are (rodees and triremes) are occurences I routinely encountered

**Comment by yairm210** [comment]
Very odd indeed, since Caravels can only be trained with Astronomy, and Triremes become *obsolete* with Astronomy...

**Comment by flecheapolinienne** [comment]
sorry if I didn't make sense, I meant Galléasse (which is obviously not called caravel in english lol). But I am 100% sure of the problem of poor unit choice by the governor.
