### ISSUE TITLE
version 3.18.9 installed from F-Droid crashes on Windows Subsystem for Android 

### ISSUE THREAD

**Issue by timkur** [yairm210/Unciv#5794]
Hey folks,

I tried running UnCiv on WSA, and the app crashes on launch with the below stack trace. However, if I build the code manually and install it, everything launches. Is there something missing from the package currently in F-Droid (the implementation for com.badlogic.gdx.graphics.g2d.BitmapFont?) Or is WSA doing something wrong?

Thanks!

Tim

12-14 10:12:19.997 12916 12942 E AndroidRuntime: FATAL EXCEPTION: GLThread 938
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Process: com.unciv.app, PID: 12916
12-14 10:12:19.997 12916 12942 E AndroidRuntime: p0.r: Error reading file: Skin.json
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n.T(Unknown Source:30)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at c2.f$b.d(Unknown Source:138)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at t0.l.e(Unknown Source:95)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at c0.l.onSurfaceChanged(Unknown Source:28)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Caused by: p0.r: Error reading file: Skin.json
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at com.badlogic.gdx.utils.d.e(Unknown Source:35)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n.T(Unknown Source:6)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	... 5 more
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Caused by: p0.r: 
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n$b.c(Unknown Source:31)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n$b.a(Unknown Source:0)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at com.badlogic.gdx.utils.d.p(Unknown Source:156)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n$a.p(Unknown Source:27)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at com.badlogic.gdx.utils.d.e(Unknown Source:10)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	... 6 more
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Caused by: q0.e: Class not found: com.badlogic.gdx.graphics.g2d.BitmapFont
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at q0.b.a(Unknown Source:25)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at n0.n$b.c(Unknown Source:18)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	... 10 more
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.BitmapFont
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:379)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	at q0.b.a(Unknown Source:0)
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	... 11 more
12-14 10:12:19.997 12916 12942 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.BitmapFont
12-14 10:12:19.997 12916 12942 E AndroidRuntime: 	... 15 more
12-14 10:12:19.998   208  1956 I am_crash: [12916,0,com.unciv.app,847822404,java.lang.ClassNotFoundException,com.badlogic.gdx.graphics.g2d.BitmapFont,Class.java,-2]

**Comment by xlenstra** [comment]
Hey!

Version 3.18.9 was bugged and should have been replaced with version 3.18.9-patch1, which should work. As Fdroid builds the code themselves every so often automatically (iirc), they probably haven't yet noticed this new release and thus you cannot download it from them. This should be resolved automatically in a few days.

In the meantime, you can try building the code yourself, or using one of the downloads we provide in our releases.

**Comment by timkur** [comment]
Sounds good. Thanks! That would explain why, if I build it myself, it runs properly. :)

Thanks!

Tim
