### ISSUE TITLE
I Want To Be Able To "Link" Units Together

### ISSUE THREAD

**Issue by Interdice** [yairm210/Unciv#5795]
I haven't played civ 5 before but in civ 6 you can "link" civilian and military units together to protect them from enemy units. I have lost way to many settlers and builders due to a lack of this feature.

I will code it myself

**Comment by AdityaMH** [comment]
#3242

**Comment by Interdice** [comment]
> #3242 

This isn't a modding request

**Comment by AdityaMH** [comment]
> This isn't a modding request
But this civ6 feature

**Comment by Interdice** [comment]
> > This isn't a modding request
> 
> But this civ6 feature

Does it matter? It is not a game play change. 

Besides is there something wrong with making the game easier to play

**Comment by AdityaMH** [comment]
> Does it matter? It is not a game play change.
> 
> Besides is there something wrong with making the game easier to play

![Uh...](https://cdn.discordapp.com/attachments/618434079741968404/924930180974280784/IMG_20211227_142350.jpg)

**Comment by Interdice** [comment]
> > Does it matter? It is not a game play change.
> > 
> > Besides is there something wrong with making the game easier to play
> 
> ![Uh...](https://cdn.discordapp.com/attachments/618434079741968404/924930180974280784/IMG_20211227_142350.jpg)

Since I am taking no resources from the game I think I will code it anyway.

Have a fine day.

**Comment by xlenstra** [comment]
To add to this; the main reason the 'please don't request features from Civ VI' note exists, is that we won't code it. If you open a feature request for it and say you code it yourself, that's entirely different, and you're free to spend your time doing that.

**Comment by yairm210** [comment]
Closing this, since it seems to be a RFC for a non Civ V feature
You can still PR this of course
