### ISSUE TITLE
Musketman liberated a City State and got knocked into the sea

### ISSUE THREAD

**Issue by Mykro** [yairm210/Unciv#5798]
3.18.8 on Android 

My musketman captured a city state back from Mongolia. I chose to return the city to its original owner, so the borders went up and the musketman got dumped offshore and unable to move.  I even tried setting it to "Explore" and several turns later it hadn't gone anywhere.  Ended up having to disband the unit.

![Screenshot_20211215-082907-297](https://user-images.githubusercontent.com/1117944/146142424-d0afc5cf-0da3-4b07-87c2-0cffec8978eb.png)

**Comment by xlenstra** [comment]
Can you provide a save file for this? Had you already researched Astronomy?
If not, it apppears your musketman is trapped there as it cannot ender the borders of Siam. Setting it to explore or moving it yourself then both don't work as it simply has no tiles to move to. The easy solution for this is trading for open borders with Siam, after which you can move your musketman as if nothing happened

**Comment by yairm210** [comment]
I see, interesting
This could occur on land tiles as well which makes it extra tricky, and in other situations

I think that the teleport requires a general rethink, and since it's relatively rare we can afford to take more time to reach a decision
 - get all cities in contiguous enemy border
 - find closest city of ours with getClosestCities
 - try dropping unit near closest city, with priority to land tiles if land unit

**Comment by will-ca** [comment]
Flood fill from each city into a Set until all cities in the set, and then pick the nearest tile in the set?

Cache for the turn, since usually there's more than one unit to teleport.

**Comment by heipizhu4** [comment]
I wonder what happens in Civ V. Can anyone give it a test?[My PC can't run CivV. It's too big:( ]

**Comment by 0avsz** [comment]
![Imagepipe_0](https://user-images.githubusercontent.com/103357381/162610239-745c6d2c-7765-4b6a-98ad-4e9984e70121.jpg)
![Imagepipe_1](https://user-images.githubusercontent.com/103357381/162610245-b77517f7-fea2-4ea9-bb90-7f3f03adba92.jpg)

Military units stack on top of enemy civilian units after liberating or trading a city without killing them.

**Comment by yairm210** [comment]
Should be solved by #6698
