### ISSUE TITLE
It looks like the AI is not trying to build wonders anymore...

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#580]
It's been like 2 or 3 games in a row and the AI is never building wonders anymore... Can anyone confirm that?

**Comment by Am-per-Sand** [comment]
Yes, I play much more relaxed now. Previously I used to stop eating after having seen that AI had finished the Pyramids just two turns earlier than I could have.

**Comment by ninjatao** [comment]
Right. Now AIs focus more on army building to avoid be beaten up too easily. But Wonder racing is such an interesting part in civ games that it should be preserved. Will fix that.

**Comment by yairm210** [comment]
Resolved by the recent changes to the construction choice mechanism
