### ISSUE TITLE
Can you destroy wonders and build them somewhere else?

### ISSUE THREAD

**Issue by Bigrichman** [yairm210/Unciv#5809]
I tried to build the Brandenburg Gate to make the most of my units, sadly another civ built it before me. Is it possible currently for me to destroy it in the city, or out right destroy the city itself and build the wonder somewhere else?

**Comment by yairm210** [comment]
Nope

**Comment by xlenstra** [comment]
These types of gameplay questions are better served in our discord, as github is used mainly for tracking bugs and feautures that are to be implemented.
As an answer, you can capture the city, bringing the wonder under your control and giving you the bonus it provides.
