### ISSUE TITLE
Impact of marble on turns to complete production

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#581]
Marble adds 15% Production when building Ancient/Classical Era wonders (all wonders in vanilla Civilization V and Gods & Kings) in the city where it is worked. 

```
    private fun getStatPercentBonusesFromMarble(): Stats {
        val stats = Stats()
        val construction = cityInfo.cityConstructions.getCurrentConstruction()
        if (construction is Building
                && construction.isWonder
                && cityInfo.civInfo.hasResource("Marble"))
            stats.production += 15f
        return stats
}
```
As `stats.production` gets boosted, the _displayed_ boost refers to all production not only wonders - when you click on a wonder in production list (the _actual_ boost refers to wonders only as it disappears when production choice shifts off wonders). 

I have no knowledge of the city screen code to suggest how to limit change of turns-to-complete number to wonders only and  leave the number for other production types unchanged. :sunglasses:

**Comment by yairm210** [comment]
... Damn, you're right
This means that 'turns to completion' calculation just got a lot more complex...

**Comment by ninjatao** [comment]
That means calculating each "turns to completion" considering every single bonus. 😄
