### ISSUE TITLE
Map - Map editor vs "new game" map

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#5839]
**Platform**
Windows 10

**Version**
3.18.11 patch-1

**Describe the bug**
Maps created in the map editor have different amount of (luxury) resources than the ones created through "start new game". See those two examples, both set to default settings, no mods. The only 2 options I changed are "Resource settings" to "Abundant" and the bar of "Resource richness" all the way to 50 (max).
This bug probably started appearing when the "Resource Setting" & regions were introduced.
Notice the massive difference in the amount of luxuries between the map editor (image 2) and the one created through the "start new game".  My hunch is that the "start new game" maps somehow defaults back to the standard settings when creating the map.

![image](https://user-images.githubusercontent.com/21982451/147081366-9dd07fc9-11bd-494a-a2c1-782d7b0914c4.png)
![image](https://user-images.githubusercontent.com/21982451/147081384-900a24c6-5d54-47c6-81fd-b22aabe0f872.png)

**Comment by JackRainy** [comment]
I can confirm from the code: map editor and the "new game" uses different logic of the map generation (see the `MapGenerator.kt lines 82-98`).
While the map editor calls `MapGenerator.kt - spreadResources()` method which takes `mapParameters.resourceRichness` into account, the "new game" uses the `MapRegions` approach with own logic, which absolutely ignores the mentioned property.

**Comment by JackRainy** [comment]
@SimonCeder, as an author of the PR #5690, do you have any ideas how to fix that?

**Comment by jahodovykolac** [comment]
Can you post a picture of a new game playing spectator? Because at the beginning you normally see no strategic resources, because they're not found yet.

**Comment by HaneulCheong** [comment]
Can confirm the issue still persists in 3.19.13.

**Comment by krijnsent** [comment]
Yeah, I'm still here :-). How do you mean it's a matter of presentation? The amount of luxuries per map is different for a created new map through the main menu vs a created new map in the Map Editor (with the same settings). I would harmonize them (=make them the same).

So I guess it's the easiest to use the ones from "start new game" in the map editor and add some "editor-specific" ones on top of that in the map editor. In that way, the only changes need to be in the map editor, not in the "start game" flow. Given the amount of bonus resources in my example, that could e.g. be "excessive-no regionality" or something like that (because that is what is happening behind the screens I guess).
