### ISSUE TITLE
Aztec icon copyright.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5853]
The Aztecs' icon doesn't seem to be in Credits.md.

Commit history:

https://github.com/yairm210/Unciv/commits/master/android/Images/NationIcons/Aztecs.png

From the PR it looks like there was probably explicit author agreement for its use, but without any specific license or ongoing verifiability.

> Aztecs by Séan https://discord.com/channels/586194543280390151/633733497277775884/727255962754351104

**Comment by yairm210** [comment]
?
