### ISSUE TITLE
UI Request and Suggestion

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#5856]
There have been a lot of various suggestion from g̶i̶t̶h̶u̶b̶ discord to extend the gameplay in various ways.
Usually they're from UI issue, UE, UX development suggestions and have very little effect on the general playerbase, and they're kind of clogging up the issues.

So this is an issue to consolidate all those suggestion, as comments to this issue.

*need to get pinned

**Comment by AdityaMH** [comment]
Add secondary mini-map size slider (max is default), for mini-map size toggle button be placed on left mini-map.
Also add minimap toggle button for change primary/secondary minimap size.

**Comment by AdityaMH** [comment]
Add option to change big icon only (hide notification) and small icon with long text.

![long text bug](https://cdn.discordapp.com/attachments/588357826758574106/923182243097247774/IMG_20211222_184726.jpg)

**Comment by AdityaMH** [comment]
Hide bombard notification if bombard was unavailable/used.

**Comment by AdityaMH** [comment]
Add leader portait for upper-left Civ name.

**Comment by AdityaMH** [comment]
![IMG_20220228_050329](https://user-images.githubusercontent.com/33791472/155901859-61775567-000c-49bd-a9be-8936f4703806.jpg)

**Comment by AdityaMH** [comment]
![IMG_20220407_143154](https://user-images.githubusercontent.com/33791472/162144958-415c70ef-b4d9-446a-9f90-cad51edcb456.jpg)

**Comment by AdityaMH** [comment]
#6144

**Comment by AdityaMH** [comment]
![image](https://cdn.discordapp.com/attachments/618434980636393492/972121181983498290/Untitled61.png)

**Comment by AdityaMH** [comment]
Also add "dot" on left text if unclicked.
![image](https://cdn.discordapp.com/attachments/618434980636393492/972295479142543431/color_bullet_notif.png)

**Comment by AdityaMH** [comment]
![IMG_20220508_054403](https://user-images.githubusercontent.com/33791472/167274355-742e5a1a-401c-48e9-a0f2-48480cf0bced.jpg)

**Comment by xlenstra** [comment]
I'm pretty sure that would lead the minimap and policy button to overlap on lower resolutions

**Comment by AdityaMH** [comment]
Maybe make it only 2 row, instead 3 or 4.

"Pick tech - next turn/unit (or icon only);
Policy - Diplomacy"
