### ISSUE TITLE
Great Prophet bug if no religion to spread or create

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#5859]
**Platform**
Android 10

**Version**
3.18.12

**Describe the bug**
> Every turn, that great prophet always stay there. Not moving.
> Only happen when that great prophet (carthage) has no religion *maybe because no space for build "Holy site"?.

![Great Prophet](https://cdn.discordapp.com/attachments/586194543716859916/924706022055084062/IMG_20211226_152213.jpg)

[Save Data](https://cdn.discordapp.com/attachments/588357826758574106/924917218750386196/Arabia_-_158_turns)

**Comment by yairm210** [comment]
Why do you consider this a bug? What would you expect to happen?

**Comment by AdityaMH** [comment]
That (carthage) great prophet just don't do anything (not moving or create holy site, or just idle at own base) every ~~day~~ turn.
Block my tile from medieval until industrial era (now),
this very disgusting.

**Comment by yairm210** [comment]
I think staying put is actually the correct choice in this kind of situation.
I mean, why send a unique unit to do a Scout' work? Especially since it can't defend itself, and it could come in handy in the future?
Not a bug as far as I'm concerned.

**Comment by AdityaMH** [comment]
This can't called bug if that prophet stay on their tile.
But this different.
@ravignir
