### ISSUE TITLE
Multiplayer sync via filesystem?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5866]
Hm. Most popular network protocols that users regularly set up themselves have some kind of wrapper/virtual filesystem that exposes the server as a user-space directory.

So why not allow users to run multiplayer games via "folders" on their device? I think this would basically mean automatic support for SSH, FTP, Google Drive, NextCloud, SyncThing, Bonjour/Avahi, RDP, and basically every protocol ever, with no barriers for users to set up their own home or cloud servers running whatever system they want. 

I haven't looked at this part of the code. But since DropBox already exposes a filesystem-like interface, I cautiously assume code reuse may be plentiful and extra maintenance burden minimal. Not sure how filesystem access works on Android. But supporting nearly every protocol that will ever exist with such a relatively minor change (if it is indeed minor) is probably worth it IMO even if limited to desktop.

**Comment by refola** [comment]
This looks like a simpler fix for #2679 than was suggested at the time. I expect there'd need to be a folder watching service for next turn notification, but dealing with files sounds much easier (Android `sdcardfs` mangling notwithstanding) if someone's up to implementing it.

**Comment by yairm210** [comment]
Dropping this due to lack of interest. You can already save games to folders and create your own servers so if you want anything else, that's it of scope for me
