### ISSUE TITLE
Horseman attack & move exception.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#587]
--------- beginning of crash
 03-18 13:09:00.849 24417 24451 E AndroidRuntime: FATAL EXCEPTION: GLThread 1167
 03-18 13:09:00.849 24417 24451 E AndroidRuntime: Process: com.unciv.app, PID: 24417
 03-18 13:09:00.849 24417 24451 E AndroidRuntime: com.unciv.logic.map.MapUnit$moveToTile$YouCantGetThereFromHereException
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.logic.map.MapUnit.moveToTile(MapUnit.kt:357)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.logic.battle.Battle.postBattleAction(Battle.kt:94)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.logic.battle.Battle.attack(Battle.kt:59)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:27)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$2.      invoke(BattleTable.kt:154)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$2.      invoke(BattleTable.kt:19)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.                 clicked(CameraStageBaseScreen.kt:133)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.                  touchUp(ClickListener.java:88)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.   java:59)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:350)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.badlogic.gdx.backends.android.AndroidInput.                       processEvents(AndroidInput.java:394)
 03-18 13:09:00.849 24417 24451 E AndroidRuntime:    at com.badlogic.gdx.backends.android.AndroidGraphics.                    onDrawFrame(AndroidGraphics.java:493)

**Comment by ninjatao** [comment]
Exception thrown when horseman kills enemy xbow and moves to that tile. In fact, the horseman should not be able to attack the xbow at all. Because it spends all movement points to the adjacent tile.
![Screenshot_20190318-131421](https://user-images.githubusercontent.com/6846049/54508268-5576c780-4980-11e9-9357-f4e4c09d4ce6.jpg)

**Comment by yairm210** [comment]
I'm pretty sure I fixed this in my latest commit around an hour and a half ago

**Comment by yairm210** [comment]
If not, that saved game you have is good data, please save it

**Comment by ninjatao** [comment]
Lost the save...Closing until happening again ;)
