### ISSUE TITLE
Increasing the collaborator pool

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#5877]
Hey all,
One of the limitations of Unciv's development process is that there's a limiting factor - me.
With my impending fatherhood, this is a good time to address the problem at its source.

We currently have 2 collaborators - @SomeTroglodyte and @xlenstra, I sent invites to @SimonCeder and @will-ca and there are others who've made considerable contributions but who haven't been active lately that if they're interested I'll add them as well - @JackRainy @ninjatao @GGGuenni @r3versi 

Currently, in practice, I'm the only one who accepts PRs, but in my opinion any PR that's acceptable by at least 2 of said collaborators is mergeable.

The Gitlab Actions setup ensures that any of this group can rollout a new version by adding the changelog entry and adding a tag to the commit.

The only thing I'm not sure about how to truly open-source is the Google Play account, since that's not directly connected to Github, but if necessary we can change the incremental rollouts to a 100% rollout to solve that. I hope to find a way to give you all permission to the account itself since the crash logs there are important data.

Here's hoping for a move towards a truly open game :)

I'd be glad to hear your thoughts on the subject!

**Comment by SomeTroglodyte** [comment]
Hmm. Maybe a get-together to build trust and learn mindsets? I could host - if you all organize your own transport to Toulouse...
:partying_face: 🌳🏊

Or maybe that's not the Sign Of The Times 🦠😷

**Comment by xlenstra** [comment]
Toulouse is only 14h by train from me... I think a virtual get-together might be easier (though less fun) for most of us if we go that route :)

On the google play -- maybe create a new google play account for unciv that all collaborators receive the login details of? In the (very) long term that might also allow for other apps to be uploaded, e.g. a stand-alone mod editor for mobile or unciv 6.

**Comment by SomeTroglodyte** [comment]
I'm sure sharing g00kl accounts is against their TOS - after all, their business model is selling out personal details.

**Comment by yairm210** [comment]
Apparently I can share the 'developer account' with other people's Google accounts, which would require you sending me your Google account name

**Comment by itanasi** [comment]
If you tied the developer account to your personal Google Account then I wouldn't recommend switching it to a group account. So might need to figure out how to do that transition first.

Also, congratulations to our new benevolent overlords

**Comment by GGGuenni** [comment]
It would be a **HUGE** honor to be a collaborator for this project! Sadly I can not guarantee to really be active PR-wise :( More than a PR here and there will probably not be possible. But I will keep reading everything and put my two cents in more often if that is desired

**Comment by will-ca** [comment]
Oh my god! First of all, congratulations!

Secondly: I hugely appreciate the offer, and if there's an open-source game project that I'm going to be a part of, I would probably want this to be the one. I'm in a generation where many of my peers bonded over Civ V in grade school days. But as my complete fumbling of the border images issue over the last half-hour shows, I still have a lot to learn in terms of both the codebase and the workflow. I'll try to continue contributing code and reviews where I feel I'm able, but I think I should self-limit to mostly observing for the most part for now.

**Comment by yairm210** [comment]
So to test this, I'm not going to merge ANY PRs in the following weeks, and then we'll see how well the system works and if it needs tweaks :)

So the (informal) rules are:
If you're the first collaborator and you approve, add "approve changes"
If you're the second collaborator, i.e. PR already has one 'approved changes', and you also approve, merge the PR :)

**Comment by JackRainy** [comment]
Thank you a lot for the invitation! That's an honor for me, since I am still a fun of the Game.
Even while I do not contribute with new commits so far, I look through the issue list from time to time for easy-fixes or known issues, 'cause I can't devote enough time for something bigger due to family reasons at the moment.

**Comment by SimonCeder** [comment]
I'll echo the sentiment that the offer is greatly appreciated, though the spare time I have varies wildly so I'll not commit to any particular schedule.
@will-ca I would try not to feel too bad about fumbles, I've definitely broken the game once or twice if that helps.

**Comment by itanasi** [comment]
@SimonCeder I mean, have you really done development until you've broken the master production?

**Comment by yairm210** [comment]
https://github.com/yairm210/Unciv/wiki/From-code-to-deployment

Better documentation for the steps I actually take when releasing, if you have any questions I'll edit the wiki until it answers all of them :)

**Comment by yairm210** [comment]
Request sent :)

**Comment by JackRainy** [comment]
Thank you, accepted :)
P.S> And of course, wish you a happy fatherhood
P.P.S> Take a nap enough, while you can :D

**Comment by yairm210** [comment]
Closing this as the message has been received by the intended audience :)

**Comment by yairm210** [comment]
@Azzurite added to the core team :D
Brief overview of what this means:

- We currently require 2 acceptance votes for PRs to be merged - so if you think it's good add an 'accepted' review, if there is one already merge it in. Nothing makes me happier than arguing that people have name a PR and it's been merged without me knowing if its existence :)

- All releases are done via automation, so you can for all practical purposes release a new version. If for example a change opens the game to a new audience (like the M1 via libgdx upgrade), or the latest version had a serious bug and it was patched, you can add a tag to trigger the build and deploy.

That's basically all it entails at the moment. Of course, if you have any other ideas, you're more than welcome :)
