### ISSUE TITLE
Strength 1 Nukes with benefits over Strength 2

### ISSUE THREAD

**Issue by Pugz4Life** [yairm210/Unciv#5888]
Strength 1 nukes have some seemingly out-of-place benefits over nukes of strength 2.

~~Nukes of strength 1 will destroy cities below 5 population if the unique `"Population loss from nuclear attacks []% []"` is not applied, while nukes of strength 2 will not.~~
Similarly, nukes of strength 2 will be prevented from decreasing population below 5 if the unique is applied, while nukes of strength 1 will not.

I'd imagine that these were supposed be reversed, as I doubt a strength 2 nuke was supposed be worse at destroying things than a strength 1 nuke.

#### Application of population damage:
in `nukeStrength1Effect()` https://github.com/yairm210/Unciv/blob/1f153cc86e5bc1fa3f6773c7e015cd4dceb84dd1/core/src/com/unciv/logic/battle/Battle.kt#L704-L710
in `nukeStrength2Effect()` 
https://github.com/yairm210/Unciv/blob/1f153cc86e5bc1fa3f6773c7e015cd4dceb84dd1/core/src/com/unciv/logic/battle/Battle.kt#L774-L777

**Comment by xlenstra** [comment]
In the function for strength 2 nukes, cities with less than 5 pop are always destroyed, as can be seen on lines 763-765 of this file.

The other problem does still stand, and it seems the source I originally used to implement this behaviour also differs from the source code. I'll recode it so it matches the original game better, and simultaneously fix a bug where bomb shelter seemingly did not work for strength 2 nukes

**Comment by Pugz4Life** [comment]
Ah, ok. I was only looking from after the section where population damage was calculated.

Also spotted another issue. The current game applies a diplomatic penalty between the civ that used the nuke and all civs in the game (Lines 665-669 in the old file, lines 661-665 in the new one). According to [https://forums.civfanatics.com/resources/unit-guide-modern-future-units-g-k.25628/](https://forums.civfanatics.com/resources/unit-guide-modern-future-units-g-k.25628/#12) (a source mentioned on line 678/673), that is what happened in Civ IV; in Civ V it only applies the diplomatic penalty between the attacker and the civs that got hit by the nuke.
