### ISSUE TITLE
Suffix Bug Name for Music Track (Android only?)

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#5891]
**Platform**
Android 10

**Version**
3.18.13

**Describe the bug**
I'm trying to make music mod with suffix name
`[CivName] - [SongName] - [Conditional].[FileFormat]`

But really didn't work for me

I'm trying to make music name include `Main Menu`, America and Aztecs (also with `Peace` and `War`) but when playing as Aztecs music player keep playing randomly also America, or Main Menu.

Here my investigation:
`Main Menu` - Worked
`Ambient` - (Random even has another suffix name like civ name) when app minimized
`Theme`/`Peace` - (Keep random playlist) Only occur when Technology researched and at peace (after track end still keep playing random track) and diplomacy screen (sometime playing `War` song for selected civ).
`War` - (Keep random playlist) Only occur when Technology researched and at peace after track end still keep playing random track and diplomacy screen.

**Comment by SomeTroglodyte** [comment]
I can't interpret this to any degree of meaningful precision, as I'm a bit distracted.
- Setting MusicController.consoleLog to true and testing with your actual data, reading the console log might help most.
- I _had_ written some documentation, though I can't find it at the moment...
```kotlin
    /**
     * Chooses and plays a music track using an adaptable approach - for details see the wiki.
     * Called without parameters it will choose a new ambient music track and start playing it with fade-in/out.
     * Will do nothing when no music files exist or the master volume is zero.
     * 
     * @param prefix file name prefix, meant to represent **Context** - in most cases a Civ name
     * @param suffix file name suffix, meant to represent **Mood** - e.g. Peace, War, Theme, Defeat, Ambient
     * (Ambient is the default when a track ends and exists so War Peace and the others are not chosen in that case)
     * @param flags a set of optional flags to tune the choice and playback.
     * @return `true` = success, `false` = no match, no playback change
     */
    fun chooseTrack (
        prefix: String = "",
        suffix: String = "Ambient", 
        flags: EnumSet<MusicTrackChooserFlags> = EnumSet.noneOf(MusicTrackChooserFlags::class.java)
    ): Boolean {
```
... yes sounds like there should be some more description ...

**Comment by AdityaMH** [comment]
I think i need to re-write my result.
Condition: "If you play as civ A but no A civ on world screen."
If mod contain "Ambient", will play as "Ambient", if no "Ambient" inside mod. Will play music randomly.

Condition: "If you play as civ A but warring civ B"
"Will playing music "B - War" at first, but after track end. Become randomly again. Idk if mod contain "Ambient".

**Comment by AdityaMH** [comment]
Also i can't change music from sound setting if mod contain "Ambient".

**Comment by SomeTroglodyte** [comment]
The missing dox are now in #6197. I'm pretty sure some/most your observations match, and at least "Become randomly again" is intended that way, to avoid boredom. Clicking the "currently playing" label looks like it uses non-optimal flags, but I would need to invest more brain power than I have free at the moment to remember whether there was a reason. No technology-dependent trigger is implemented, so those observations must be by chance.

FYI - Prefixes / Suffixes need no specific separator, using them is purely decorative (but still recommended). Known suffixes are in an enum `MusicMood` - [see source!](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/audio/MusicMood.kt)

Specific suggestions how to tweak the triggers to maximize effect are of course welcome.

**Comment by AdityaMH** [comment]
I will close this since inconsistent music can be fixed by add ~~music~~/sfx including "Ambient".

idk why, but "Built" and "Researched" didn't work to me, maybe need specific building/tech?

**Comment by SomeTroglodyte** [comment]
>  "Built" and "Researched" didn't work to me

Yup, they're marked as 'Not Implemented' in the new wiki parts
