### ISSUE TITLE
Dropbox has run out of space (again)

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5901]
Same issue as #3986, basically.

Checking the allocated space on the [dropbox API tester](https://dropbox.github.io/dropbox-api-v2-explorer/#users_get_space_usage), yields:
```
{
  "used": 2684366459,
  "allocation": {
    ".tag": "individual",
    "allocated": 2684354560
  }
}
```
i.e., we're using more space than we have been allocated

**Comment by yairm210** [comment]
I'm pretty sure we can create a github action as a cron job, to delete old saves every X amount of time
We can add args to the desktop runner to do so sorts of things, I think that's a nice extendable solution :)

**Comment by xlenstra** [comment]
My knowledge of github actions and how to work with them isn't very good, so for now I've solved it with the python script below. I'm in favour of keeping this open as we do need some kind of solution like that.

<details> <summary> Python script: </summary>

Requires `pip3 install dropbox` to work.
This will download all deleted files, in case something does go wrong. Due to the likely large number of files that will be downloaded, I'd advise to run this script from inside an empty folder.

```python
LAST_YEAR_TO_REMOVE = 2021
LAST_MONTH_TO_REMOVE = 1
LAST_DAY_TO_REMOVE = 1
LAST_HOUR_TO_REMOVE = 12

import dropbox
dbx = dropbox.Dropbox("LTdBbopPUQ0AAAAAAAACxh4_Qd1eVMM7IBK3ULV3BgxzWZDMfhmgFbuUNF_rXQWb")

for entry in dbx.files_list_folder('/MultiplayerGames').entries:
    print("Found file {0}".format(entry.name))
    metadata = dbx.files_download_to_file(entry.name, "/MultiplayerGames/{0}".format(entry.name))
    print("Downloaded file {0}".format(entry.name))
    if (metadata.client_modified.year <= LAST_YEAR_TO_REMOVE
        and metadata.server_modified.year <= LAST_YEAR_TO_REMOVE
        and metadata.client_modified.month <= LAST_MONTH_TO_REMOVE
        and metadata.server_modified.month <= LAST_MONTH_TO_REMOVE
        and metadata.client_modified.day <= LAST_DAY_TO_REMOVE
        and metadata.server_modified.day <= LAST_DAY_TO_REMOVE
        and metadata.client_modified.hour <= LAST_HOUR_TO_REMOVE
        and metadata.server_modified.hour <= LAST_HOUR_TO_REMOVE
        and entry.name != ""
    ):
        dbx.files_delete("/MultiplayerGames/{0}".format(entry.name))
        print("Deleted file {0}".format(entry.name))
    else:
        break
```
</details>

**Comment by will-ca** [comment]
> My knowledge of github actions and how to work with them isn't very good, so for now I've solved it with the python script below. I'm in favour of keeping this open as we do need some kind of solution like that.

Perfect. This script can actually go in a GH Action.

**Comment by xlenstra** [comment]
> EDIT: Is that a DropBox security key/token exposed in the script?

Yes, but it's already exposed in the kotlin code if you know where to look, so it's not really a secret at this point

**Comment by SomeTroglodyte** [comment]
Didn't I have a branch months ago that would distribute the deletion load to the players? Like everyone who creates a new MP runs a little snippet that deletes the oldest 10 files? [*]

Anyway, together with the "libre" discussion priority should be to create alternatives, so anybody who wants to can run their own backend. Classic WebDAV maybe, which one can easily buy from providers or serve from NextCloud?

[*] Kept it as patch in case anyone wants a read:
[Automatic_DropBox_cleanup_on_newgame1.patch.zip](https://github.com/yairm210/Unciv/files/7809803/Automatic_DropBox_cleanup_on_newgame1.patch.zip)

**Comment by xlenstra** [comment]
Alternatively, as we already use it for mods anyway, maybe we could somehow use a github repo for storing the save files. Not sure how difficult that would be and if they impose rate limitations, but it's probably more libre than dropbox.

**Comment by SomeTroglodyte** [comment]
"probably more libre than dropbox" :rofl: :+1: (love the idea but honestly - all the overhead with commits and history wouldn't really fit. And the rate limits as I remember for queries surely exist for commits, too, and will likely be just a tad too restrictive for fast games - queries was 10/minute afaik, and that's not a sliding window but hard minute-length boxes)

**Comment by yairm210** [comment]
Default server is now UncivServer.xyz so I guess we can treat this one as 'deprecated'
