### ISSUE TITLE
The method tr() makes the Color Markup Language is invalid

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#5902]
For example, if you set labelStyle.font.data.markupEnabled = true and add("[RED]✘[]".toLabel()), the app will show "RED✘", it should show a red color of "✘".
That's because the method tr() tackles with "[]" in the string "[RED]✘[]" at first.

**Comment by will-ca** [comment]
> [Square ones take precedence over curly ones, and **nesting works only with a single level of curly nested inside one level of square**.](https://github.com/yairm210/Unciv/wiki/Translating)

This seems as much a side effect of the implementation as deliberate behaviour, but you can thus escape CML tags by using double brackets:

E.G.: `"[[RED]]".tr()`.

(As I tested in Python branch: `apiHelpers.Jvm.functionByQualClassAndName['com.unciv.models.translations.TranslationsKt']['tr']("[[RED]]Test[[]]")`.)

Suggested solution: We say this behaviour is a fully official spec and intended use, and then we don't even have to change any code.

…That said, I don't think we should be including markup tags in any translation templates in the first place?

**Comment by yairm210** [comment]
We weren't intending to use the color markup at all, so this is not a bug
This only becomes relevant when attempting to find solutions to other bugs
