### ISSUE TITLE
Здравствуйте,  я не совсем понимаю баг это или нет, но: Каждый раз когда я встречаю цивилизацию "Ацтеки" то они постоянно начинают со мной враждовать. Отношения при этом с ними нейтральные. Так происходит постоянно, каждый раз.

### ISSUE THREAD

**Issue by matvejsalnikov** [yairm210/Unciv#5905]
**Platform**
Operating system type, major version, architecture (64/32 bit).
Telephone: VIVO 1680
**Version**
3.18.13

**Describe the bug**
Здравствуйте, я не совсем понимаю баг это или нет, но: Каждый раз когда я встречаю цивилизацию "Ацтеки" то они постоянно начинают со мной враждовать. Отношения при этом с ними нейтральные. Так происходит постоянно, каждый раз.

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
The AI declares war on you if it thinks your military is weak - the Aztecs are a military Civilization which makes this more likely.
The way to stop this is to train more military units :)
