### ISSUE TITLE
Water level?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5909]
From the Discord:

"-0.10"

![Screenshot_20220104_115946_com unciv app](https://user-images.githubusercontent.com/37680486/148010259-c6d3397d-8069-4418-b9c1-d6fb530f91f0.jpg)

"Normal level"

![Screenshot_20220104_115841_com unciv app](https://user-images.githubusercontent.com/37680486/148010270-37ac412c-bf8b-4e43-9be5-ea7957b39b7e.jpg)

"+0.10"

![Screenshot_20220104_115914_com unciv app](https://user-images.githubusercontent.com/37680486/148010274-36d94096-b4a0-4ea2-b4bd-c2b4bff16eba.jpg)

**Expected behaviour**: Higher water levels should produce maps with more water.

**Comment by yairm210** [comment]
Okay...? And the bug is...?

**Comment by will-ca** [comment]
> Okay...? And the bug is...?

Ah, sorry. Edited.

Though having just tried it more thoroughly, only the "Default" map type ignores the setting… Closing.
