### ISSUE TITLE
(RFC?) CrashScreen save file privacy?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5953]
#5810 added automatic inclusion of the most recent GameInfo state in CrashScreen crash reports. Example reports: #5938, #5944

I considered at the time whether to add a warning/explicit message that the generated report contains save data.

For:
- Save files can theoretically contain sensitive data. Maybe someone named their cities in honour of their private keys, or settled them at tile coordinates encoding their date of birth and bank details? Hey, Idk. More feasible: Compromising potentially sensitive personal secrets or offensive content meant to stay between friends (E.G. "outing").

Against:
- Save files *probably* shouldn't contain sensitive data in the first place.
- Nothing is sent automatically. The user has to explicitly copy and share the error report.
- The error report clearly marks the save file section, twice, with tags, and in bold. That may already be plenty visible.
- Error screens are often puzzling enough as an end user. Adding instructions to scroll down and delete the big block of Base64 on a screen that already has four or five different things to say may just increase user friction without improving privacy.

Possible resolutions:
1. Current situation is fine and this whole question is paranoid. Maintain status quo.
2. Add another line saying "This report contains your latest save file. Scroll down and delete it before posting if you do not wish to share it". Unnecessary?
3. Remove save file from automatically generated report. Loses what may be a big benefit of displaying the CrashScreen to the player (I.E. crowd-sourced reproducers for Heisenbugs).
4. Add a checkbox for "Include save file in report". Increased code complexity.

Reading this back, I'm thinking Option 1.

**Comment by xlenstra** [comment]
I'm also in favour of option 1. If we start getting complaints (which I don't expect), we can always implement option 4
