### ISSUE TITLE
Map generation: Hill and Mountain being on the same tile 

### ISSUE THREAD

**Issue by Ruochun** [yairm210/Unciv#5957]
**Platform**
Android 11

**Version**
3.18.1

**Describe the bug**
Map generation: Hill and Mountain being on the same tile (with resource on it) within the border of a city-state

**To Reproduce**
This happened inside the border of Tyre city-state.
<details><summary>db82694b-367d-405e-be56-248c9e6ca491</summary>

```

```
</details>

**Expected behavior**
A tile should not contain both Mountain and Hill.

**Screenshots**
![Screenshot_20220110-132936_UnCiv](https://user-images.githubusercontent.com/24469442/149199917-c4c23cc5-6915-461b-971b-46f5c1e7c111.jpg)
![Screenshot_20220112-121715_UnCiv](https://user-images.githubusercontent.com/24469442/149199954-8bc5929e-f259-417a-ac36-e058c7aa19dd.jpg)

**Additional context**
It seems Tyre also keeps trying to send Workers to this tile to improve it. It was able to do so, but the Worker dies on that tile in 2 turns, so it has been trying all game but no good result comes out.

**Comment by xlenstra** [comment]
Should be fixed for version 3.18.17 already: https://github.com/yairm210/Unciv/pull/5946
