### ISSUE TITLE
Unciv crashes when trying to buy work boats

### ISSUE THREAD

**Issue by Throlo** [yairm210/Unciv#5961]
I'm playing with denmark and when i try to buy a work boats the game crashes. 
I can buy other units normally.

Device: SM-A515F
Unciv: 3.18.16

**Comment by xlenstra** [comment]
Fixed in 3.18.16-patch1, you should be able to update your game

**Comment by Throlo** [comment]
Sorry, i have downloaded Unciv from F-droid. Thanks for the help!
