### ISSUE TITLE
RFC: Moddable expressions?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5962]
So, moddable constants were recently added to Unciv in #5921. That hints at a logical next step: Moddable expressions?

One morning earlier this week I went slightly mad and spent some time writing the start of a mini-parser/compiler thingy with the aim of being able to evaluate mod-supplied algebraic expressions safely and performantly.

The idea is/was to turn expression strings into JIT-friendly expression trees with statically typed Enums/lambdas for operations and statically typed accessors for constants.

Full implementation of this mini-language with KDocs and such would probably be around the mid-hundreds of LoC range. Currently at 170 I believe, with most of the structure laid out. Most of that is in the parser. So the logic's fairly simple.

Thoughts?

**Comment by yairm210** [comment]
I am most concerned with the user-facing aspect of these.
It's relatively simple to create a parser that e.g. you can input complex conditions (and, or, cross-effects), and extremely difficult to make it clear to the users what's going on, *especially* when you realize that half of your players aren't even playing in English.

**Comment by will-ca** [comment]
I was thinking mostly of modding relatively simple internal formulae like unit maintenance, tech cost, city tile purchase cost etc. For that, I think documentation for modders would still be a concern, but I'm not sure I see why it would be a prohibitively bigger problem than the documentation for Uniques, JSONS, and ModConstants.

Closing as it would probably be further off (and I'm less ready to work on it) than I'd imagined.
