### ISSUE TITLE
Game mechanic capitalization?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5963]
Capitalization of named game mechanics appears to be somewhat inconsistent:

|**Term**|**Capitalized**|**Total**|
|---|---|---|
|<ul><li>[ ] `" Barbarian"`</li></ul>|15|26|
|<ul><li>[ ] `"Barbarian Camp"`</li></ul>|2|5|
|<ul><li>[ ] `"Barbarian Encampment"`</li></ul>|0|4|
|<ul><li>[ ] `"City State"`</li></ul>|7|8|
|<ul><li>[ ] `"City-State"`</li></ul>|28|36|
|<ul><li>[ ] `" Culture"`</li></ul>|7|29|
|<ul><li>[ ] `" Faith"`</li></ul>|13|19|
|<ul><li>[ ] `" Gold"`</li></ul>|29|73|
|<ul><li>[ ] `"Golden Age"`</li></ul>|9|19|
|<ul><li>[ ] `" Great"`</li></ul>|29|133|
|<ul><li>[ ] `"Great Artist"`</li></ul>|1|1|
|<ul><li>[ ] `"Great Engineer"`</li></ul>|1|1|
|<ul><li>[ ] `"Great General"`</li></ul>|4|4|
|<ul><li>[ ] `"Great Improvement"`</li></ul>|3|3|
|<ul><li>[ ] `"Great Merchant"`</li></ul>|2|2|
|<ul><li>[ ] `"Great People"`</li></ul>|4|5|
|<ul><li>[ ] `"Great Person"`</li></ul>|11|15|
|<ul><li>[ ] `"Great Prophet"`</li></ul>|5|16|
|<ul><li>[ ] `"Great Scientist"`</li></ul>|1|1|
|<ul><li>[ ] `" Happiness"`</li></ul>|4|25|
|<ul><li>[ ] `" Influence"`</li></ul>|18|31|
|<ul><li>[ ] `" Pantheon"`</li></ul>|6|13|
|<ul><li>[ ] `"Peace Treaty"`</li></ul>|2|2|
|<ul><li>[ ] `" Polic"`</li></ul>|11|41|
|<ul><li>[ ] `"Social Polic"`</li></ul>|6|10|
|<ul><li>[ ] `" Production"`</li></ul>|12|30|
|<ul><li>[ ] `" Railroad"`</li></ul>|6|7|
|<ul><li>[ ] `" Religion"`</li></ul>|15|96|
|<ul><li>[ ] `"Enhanced Religion"`</li></ul>|0|2|
|<ul><li>[ ] `"Research Agreement"`</li></ul>|2|5|
|<ul><li>[ ] `"Luxury Resource"`</li></ul>|3|17|
|<ul><li>[ ] `"Strategic Resource"`</li></ul>|2|11|
|<ul><li>[ ] `" Road"`</li></ul>|4|15|
|<ul><li>[ ] `" Science"`</li></ul>|7|19|
|<ul><li>[ ] `"Set Up"`</li></ul>|2|9|
|<ul><li>[ ] `" Strength"`</li></ul>|17|37|
|<ul><li>[ ] `" Unhappiness"`</li></ul>|2|19|
|<ul><li>[ ] `"Cultural Victory"`</li></ul>|2|4|
|<ul><li>[ ] `"Diplomatic Victory"`</li></ul>|2|5|
|<ul><li>[ ] `"Domination Victory"`</li></ul>|1|2|
|<ul><li>[ ] `"Science Victory"`</li></ul>|1|2|
|<ul><li>[ ] `"Scientific Victory"`</li></ul>|0|3|
|<ul><li>[ ] `"We Love The King Day"`</li></ul>|6|6|
|<ul><li>[ ] `"National Wonder"`</li></ul>|3|3|
|<ul><li>[ ] `"Natural Wonder"`</li></ul>|9|9|
|<ul><li>[ ] `"World Wonder"`</li></ul>|0|1|

Numbers are the totals from searching in `English.properties`. The capitalized form is as shown in the table; The total is found by converting both the search term and text to lower-case. Single-word search strings have a space at the start to avoid counting cases where capitalization is due to the start of the string; Spaces immediately following periods in the search text are also collapsed to aid that goal.

**The numbers are only a rough representation as sometimes a term can be lower-case most of the time but Title Case in specific contexts.** I did manually check most of them, and tried to include only names that either have their own legitimately inconsistent capitalizations or are comparable to but inconsistent with other names, though.

---

Python counting script:
<details>

```python3
with open("English.properties") as texts, open("Names") as names:
	searchtext = texts.read().replace('. ', '.')
	namelines = names.readlines()
	sortsignificance = {}
	for name in namelines:
		for word in name.split():
			sortsignificance[word] = sortsignificance.get(word, 0) + 1
	namelines = sorted(namelines, key=lambda name: sorted(name.split(), key=lambda word: -sortsignificance[word]))
	print('\n'.join(line
		for lines in (
			("|**Term**|**Capitalized**|**Total**|",
			"|---|---|---|"),
			(f"|`\"{name}\"`|{searchtext.count(name)}|{searchtext.lower().count(name.lower())}|" for l in namelines for name in [l.rstrip('\n')])
		) for line in lines
	))
```
</details>

`Names`:
<details>

```
Golden Age
Luxury Resource
Social Polic
Research Agreement
Enhanced Religion
Natural Wonder
National Wonder
World Wonder
Strategic Resource
City State
City-State
Great Person
Great People
Great Merchant
Great Engineer
Great Scientist
Great Prophet
Great Artist
Great General
Great Improvement
Barbarian Camp
Barbarian Encampment
Peace Treaty
Cultural Victory
Science Victory
Scientific Victory
Domination Victory
Diplomatic Victory
Set Up
We Love The King Day
 Happiness
 Unhappiness
 Road
 Railroad
 Religion
 Pantheon
 Science
 Production
 Gold
 Faith
 Culture
 Barbarian
 Great
 Polic
 Strength
 Influence
```
</details>

Bash command to find consecutive pairs of capitalized words:

```bash
$ grep -o -e ' [A-Z][a-z]* [A-Z][a-z]*' English.properties | sort -u
```

**Comment by yairm210** [comment]
All non-game-state and non-mod instances can be replaced with ctrl r - since they appear in the translation files the same way, this doesn't affect gameplay.
Any instances where the string is saved in the mod or in the game state, this will require deprecation, and frankly I don't think it's worth it.

**Comment by yairm210** [comment]
I do wish you would help deal with some of the problems you raise yourself though
This is like the sixth issue you've raised and I'm not sure you've actually dealt with any 🙃

**Comment by will-ca** [comment]
> I do wish you would help deal with some of the problems you raise yourself though
> This is like the sixth issue you've raised and I'm not sure you've actually dealt with any :upside_down_face:

Ah sorry… Yes, that is an area where I definitely feel I may have been underperforming. TL;DR: I know, it's not you it's me, please feel free to ignore, put on the backburner, close, or just assign to me.

I have a bit of a tendency to get sucked into projects beyond the point that is healthy for me personally.. Have been trying to limit that, but so far I've accidentally restricted code contributions more than I've restricted issues. In my defence, I have been patching and stabilizing a tile blending script over on the 5Hex repository this week, and I have… literally dozens more notes and checkboxes in my "Unciv" Google Keep label for mostly PRs I've yet to finish and a couple rare crashes I've yet to diagnose, so I've also been overwhelming my own private to-do list…

**Comment by yairm210** [comment]
I'm closing this
When we find such problems we'll deal with them locally, this issue has raised the awareness it set out to
