### ISSUE TITLE
Destroy option no respond & can't function in the city menu

### ISSUE THREAD

**Issue by Xsanszzz123** [yairm210/Unciv#5971]
**Platform**
Operating system type, major version, architecture (64/32 bit).
Android
**Version**
Where you got the game and the exact version number.
Play store,3.18.16
**Describe the bug**
Destroy city option can't function in city menu
**To Reproduce**
1. Go to 'City menu'
2. Click on 'Destroy city' 
3.See error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
'Destroy city' should function properly like usual
**Screenshots**
![Screenshot_20220115-085548](https://user-images.githubusercontent.com/97769290/149602509-ff4d7624-1226-4546-8b6b-4f43c36cee32.png)

**Additional context**

**Comment by xlenstra** [comment]
I'm confused at what exactly your problem is. Is it that the 'raze city' button isn't working? This is as original capitals of nations cannot be razed

**Comment by Xsanszzz123** [comment]
Yes

**Comment by Xsanszzz123** [comment]
You can see the razed city option is unavailable

**Comment by Xsanszzz123** [comment]
> You can see the razed city option is unavailable

**Comment by Xsanszzz123** [comment]
Sorry,first time using github

**Comment by Xsanszzz123** [comment]
Yes,Here the screenshot

Xander Lenstra ***@***.***> 于 2022年1月15日周六 上午8:32写道：
