### ISSUE TITLE
Caravels looks like Frigates and Frigates like Caravels

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#598]
or not?

#597

**Comment by yairm210** [comment]
I'm confused
If they look similar, how will swapping their icons help?

**Comment by Am-per-Sand** [comment]
It is a minor issue. Important for ex. to me as a player. Will not help much. 
In my opinion a caravel looks like: [https://commons.wikimedia.org/wiki/Category:Caravels](https://commons.wikimedia.org/wiki/Category:Caravels)
and frigate like [https://commons.wikimedia.org/wiki/Category:Sailing_frigates](https://commons.wikimedia.org/wiki/Category:Sailing_frigates) and current icons look exactly like mistaken with each other.

Share my opinion or disagree. Worth considering and discussing IMO.

**Comment by yairm210** [comment]
Resolved by #597
