### ISSUE TITLE
Dead city-state not showing up in defeated civilizations

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#5983]
The city-state of Ghost Mountain got destroyed, but it's not listed as one of the defeated civilizations. I've attached the save file and the mod I'm working on.
[DeadCityState.zip](https://github.com/yairm210/Unciv/files/7876356/DeadCityState.zip)
s

**Comment by yairm210** [comment]
This is because you didn't know that city-state before it was destroyed
But this is a good question - should unknown civs *become* known when they're destroyed?
@ravignir ?

**Comment by yairm210** [comment]
Okay
I'm considering this "not a bug" then
For me this looks like 'working as intended'
