### ISSUE TITLE
Please tell me how to add the company icon.

### ISSUE THREAD

**Issue by MGLSIDE** [yairm210/Unciv#5984]

**Comment by MGLSIDE** [comment]
@yairm210

**Comment by yairm210** [comment]
What have you done so far?
Have you seen how it's done in existing mods?
Have you gone through https://github.com/yairm210/Unciv/wiki/Mods#more-on-images-and-the-texture-atlas ?

**Comment by MGLSIDE** [comment]
My author, David, the example mods you made all have problems. Directly unavailable on 3.18.11.

**Comment by yairm210** [comment]
That's an older version, what about 3.18.17?

**Comment by MGLSIDE** [comment]
> That's an older version, what about 3.18.17?

I haven't tried.

**Comment by yairm210** [comment]
That sounds like the first step then :)

**Comment by MGLSIDE** [comment]
> That sounds like the first step then :)

Well, I'll give it a try.

**Comment by MGLSIDE** [comment]
> That sounds like the first step then :)

Author: What are you doing?

**Comment by MGLSIDE** [comment]
> That sounds like the first step then :)

Why? The requiredBuildingInAllCities attribute is not available.

**Comment by yairm210** [comment]
That's right, it's been replaced with the corresponding Unique
That should also appear as a warning in options - mods

**Comment by MGLSIDE** [comment]
> That's right, it's been replaced with the corresponding Unique
> That should also appear as a warning in options - mods
Author: Can you make an icon to add a sample module?

**Comment by MGLSIDE** [comment]
Can you add an icon to add the sample module?

**Comment by yairm210** [comment]
https://github.com/ravignir/RekMOD/tree/master/Images
This contains good examples of many things
I think it's much better than my old "example mod", I'll change the documentation accordingly

**Comment by MGLSIDE** [comment]
> https://github.com/ravignir/RekMOD/tree/master/Images
> This contains good examples of many things
> I think it's much better than my old "example mod", I'll change the documentation accordingly
What does this X and y mean?![IMG_20220119_135653.jpg](https://user-images.githubusercontent.com/79357075/150072677-ae14af71-4182-4e97-8160-f2836c001000.jpg)

**Comment by yairm210** [comment]
That's not something you should worry about, that just says where inside the giant png fine the smaller individual images are located
The larger png is compiled automatically from the smaller ones when running on desktop

**Comment by MGLSIDE** [comment]
Can I not add the smaller image to the larger image?

**Comment by MGLSIDE** [comment]
> That's not something you should worry about, that just says where inside the giant png fine the smaller individual images are located
> The larger png is compiled automatically from the smaller ones when running on desktop
Does Android also automatically compile from small images to large ones?

**Comment by MGLSIDE** [comment]
Does Android also automatically compile from small images to large ones?

**Comment by yairm210** [comment]
Nope, it doesn't have the required libraries

**Comment by MGLSIDE** [comment]
> Nope, it doesn't have the required librariIs it possible not to add larger images to the Android version of the mod?

**Comment by yairm210** [comment]
Once the images are packed once, they're available everywhere in their packed format

**Comment by MGLSIDE** [comment]
> Nope, it doesn't have the required libraries

I don't have a tool to view the pixel coordinates in the image, so I can't add larger images.

**Comment by MGLSIDE** [comment]
> Once the images are packed once, they're available everywhere in their packed format

Again, so I don't have a way to label the position of a small image in a large image.

**Comment by yairm210** [comment]
Closing this, since this is a discussion and not an issue
Discussions should be done on Discord where there are more people who can help :)
