### ISSUE TITLE
As warning on battle table when attacking barbarians with a unit with 30 xp

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#5985]
This is something that comes up a lot on discord, which means it's not presented clearly to users.
A simple "units with more than (amount) xp will not gain xp from attacking barbarians" should suffice

**Comment by xlenstra** [comment]
Maybe an easier solution is to always show how much XP attacking would earn in the battle table, and then put that line somewhere in the tutorials section?

**Comment by yairm210** [comment]
Hmmm also a good point

**Comment by alexban011** [comment]
shouldn't this be closed ?
