### ISSUE TITLE
Buildings in City screen not showing

### ISSUE THREAD

**Issue by Crit-Cee** [yairm210/UnCiv#600]
Ever since adding the ability to sell buildings, I see a section for the buildings, but it's only a copy of the Wonders and shows no non-specialist buildings. I have not been able to try out selling building because of this.

**Comment by Am-per-Sand** [comment]
#565 
Update!

**Comment by yairm210** [comment]
Indeed, you're using an out of date version

**Comment by Crit-Cee** [comment]
As of like todays update. Cause I've been keeping my app up to date. But yes, after todays update, it is fixed. Also, the new tilesets look amazing.
