### ISSUE TITLE
Kremlin wonder bugged

### ISSUE THREAD

**Issue by tcrundall** [yairm210/Unciv#6021]
The Kremlin wonder is supposed to boost city defensive buildings by 25%.

In reality it increased the total defence of my cities by about 600%.

This is has happened every time since I started paying attention, for both my player and the AI.

Case example:
Berlin: size 17, walls, castle --> strength 50
after Kremlin constructed (in Edinburgh)
Berlin strength went to 338.

![Screenshot_20220123-144806](https://user-images.githubusercontent.com/8383244/150681830-f5fc57d7-842e-4c6d-be66-5ed209bc71cf.png)

![Screenshot_20220123-144859](https://user-images.githubusercontent.com/8383244/150681827-3a6be908-a372-45b3-822e-d8d7e88ad965.png)

![Screenshot_20220123-144904](https://user-images.githubusercontent.com/8383244/150681829-598f7676-7391-4f4a-9b79-a1b1dcf5b311.png)

**Comment by xlenstra** [comment]
Known bug, fixed in 3.19.0
