### ISSUE TITLE
Add "Raze City" choice when you conquer a city

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#606]
In Civ V, whenever you conquer a city, you're presented the choice of either keeping the cities, and thus their bonuses, or burn it to the ground, erasing it from existence. The only exception is the Capital, which can never be destroyed. I would like to know if that was possible to add this feature or if it was useless in this Android game.

**Comment by ozyxcv** [comment]
Although the game doesn't prompt this choice you are able to raze any city, even capitols, in the game. Just look in the captured city menu and you should see the option
