### ISSUE TITLE
Huge maps is not loading.

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#6064]
**Platform**
Bluboo Xtouch from 2015
Android 5.1
RAM memory 3 GB

**Version**
Play Store (Google)
3.18.19

**Describe the bug**
Huge maps don't load on multiplayer games, crashing or been so slow to play. However, on singleplayer it's more playable but work slow and break the execution frequently.

**To Reproduce**
Joining to multiplayer or singleplayer game with a huge map.
(In singleplayer you would need to finish some turns.)

--------- ---------- ----------

It could be produced by not enough RAM?

**Comment by yairm210** [comment]
If it's only huge maps, then yes, this is a RAM problem
Also, if you are playing on world wrap maps, then try playing on non-wrap maps. 
Nothing else we can do to help :)
