### ISSUE TITLE
Game suddenly loads much slower

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6065]
**Platform**
Android 5.1.1

**Version**
3.19.1, Google Play

**Describe the bug**
The game just doesn't load. The smiley appears, spins, and then stays there.

**Expected behavior**
The game loads :)

**Additional context**
It started happening just when I updated.

Edit: It actually does load, but it takes like 1 minute instead of 5 seconds, which may be normal.

**Comment by yairm210** [comment]
I didn't encounter such problems with 3.19.1 at all
In the latest versions (3.19.2) we made large improvements to the loading times, so please check again :)

**Comment by will-ca** [comment]
Someone on Reddit reports it being stuck for two hours:

https://www.reddit.com/r/Unciv/comments/sgzpbe/game_stuck_like_this_for_2_hoursi_even_tried/

**Comment by yairm210** [comment]
For me it's near instantaneous
What mods do you have downloaded? Maybe it's taking time to parse the mods

**Comment by yairm210** [comment]
Okaaaaay I think I found the source of the problem...
When displaying uniques to mod makers we added a functionality to show possible misspellings, This doesn't affect new games, OR loading the rulesets, and yet the code is still run on both occasions, which slows things down.

**Comment by yairm210** [comment]
Resolved in 3c30a5697fa4ffaf558dcacb1264c9b630f9d3f7

**Comment by will-ca** [comment]
> When displaying uniques to mod makers we added a functionality to show possible misspellings, This doesn't affect new games, OR loading the rulesets, and yet the code is still run on both occasions, which slows things down.

Oh, oops?

And I thought I was being paranoid by wanting the edit distance estimate to run in linear time…
