### ISSUE TITLE
Resource allocation should allocate set amounts of each strategic resource

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#610]
I made 3 games, on small, medium and large map, and on each I could make a bath of oil but I was begging for coal and aluminium, that are more useful than oil.
I understand that some resources are rare but not that much.
Let the choice of the resources spawn rate at the begining of new games, like in the original game, could be a nice solution.

**Comment by Am-per-Sand** [comment]
#486 - it was bad :grimacing:

**Comment by B5656** [comment]
Yes, I saw this Issue, but it's not exactly the same, I proposed to make an option when you launched the game to let the player choice if there will have a lot of strategic resources or just a few.

**Comment by Am-per-Sand** [comment]
...this issue is a side-effect of fixing the one I referenced

> let the player choice if there will have a lot of strategic resources or just a few.

I'd rather like to choose it within the difficulty level, not separately

**Comment by Smashfanful** [comment]
Yeah, speaking of strategic resources, there is also a lack of Iron and Horses in every map I played (even Huge maps).
