### ISSUE TITLE
Unciv not detecting Mod Updates properly

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6106]
So, even after 5 hours of this Pull Request https://github.com/ravignir/RekMOD/pull/45 merged in RekMOD repo, Unciv Android still doesn’t show any updates. So, I was interested in how it works and why it takes so long to update. I saw a Mods folder in Unciv's Dropbox so I guess  It's probably it is there where the List is stored?

**Comment by xlenstra** [comment]
Actually, we don't use dropbox for mods; I'm not sure what mods even are saved there if any. When we ask for mods, we directly query github for all repositories with a topic that includes `unciv-mod`. This returns the list [here](https://github.com/topics/unciv-mod), from which we then extract the names and load those into unciv.
I'm able to update REKMod on my PC without any problem, so this is probably a problem with your device. Have you tried deleting REKMod and re-installing it?

**Comment by touhidurrr** [comment]
> Actually, we don't use dropbox for mods; I'm not sure what mods even are saved there if any. When we ask for mods, we directly query github for all repositories with a topic that includes `unciv-mod`. This returns the list [here](https://github.com/topics/unciv-mod), from which we then extract the names and load those into unciv. I'm able to update REKMod on my PC without any problem, so this is probably a problem with your device. Have you tried deleting REKMod and re-installing it?

Re Installing it works. But it doesn’t show that any update is available. Not sure why. I am not re installing this time to see how much longer it takes to display the info (or whether it shows it at all).

**Comment by xlenstra** [comment]
That is 5Hex-Tileset and not rekmod?

**Comment by touhidurrr** [comment]
> That is 5Hex-Tileset and not rekmod?

Oh my bad. 😅 So, maybe there is error on the codes?

**Comment by touhidurrr** [comment]
Ok I think I have tracked the bug here. The Github API endpoint we are using here should be:
https://api.github.com/search/repositories?q=topic:unciv-mod&sort=stars&order=desc
which returns this result:
![Screenshot_2022-02-03-21-11-25-56_d073e7407281f7a2d9df7c9f755e6603](https://user-images.githubusercontent.com/46617994/152370599-7be28389-51d2-4df3-9a20-cdcd3589f752.jpg)
I think Unciv is most probably using the value from `updated_at`, I think we would need `pushed_at` maybe? Note sure.
Also @xlenstra maybe this issue needs a bug tag.

**Comment by yairm210** [comment]
https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at#15922637

Oh.
So we should really be using pushed_at instead.

**Comment by touhidurrr** [comment]
> https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at#15922637
> 
> Oh. So we should really be using pushed_at instead.

I do not think that the information provided here is correct. Cause in our case `updated_at` is more than 10 days older than `pushed_at` which can never happen if `update_at` tracks any changes made within the repository including `push` events. A rare API error is also unlikely because 2 pull requests were merged into RekMOD after the date recorded in `updated_at`. It's highly unlikely that both was ignored for some reason cause Unciv did not show any RekMOD updates when the previous pull request was merged also. J had to re install see the changes. So, I think `updated_at` might just be the changes made in the Repository Object like tags, details etcetra. I know that this theory has many loopholes also I don't know what else it can be.

So, In the end if `pushed_at` satisfies our needs better then we should just use it instead. Cause one thing is sure that the time when the last commit was made is recorded in `pushed_at` properly. I tried to search more info about it but failed. So, `pushed_at` seems better than `updated_at` anyways.

**Comment by yairm210** [comment]
No, look at the TOP part of his comment, that's the real info. The lower part he himself says is wrong.
pushed at is when the actual contents changes, updated at is when the metadata changed, and we don't care about that

**Comment by touhidurrr** [comment]
> No, look at the TOP part of his comment, that's the real info. The lower part he himself says is wrong. pushed at is when the actual contents changes, updated at is when the metadata changed, and we don't care about that

Yeah. We should use `pushed_at` after all. Anyways, yesterday I saw the related codes and decided that I couldn’t make a pr for 3 reasons, me being inexperienced in Kotlin, the codebase parsing the returned JSON into a repo object which in turn is used in the rest of the code and too many references of the parsed updated at variable and I wouldn’t know which part of the codebase would be broken if I make a pr.

So, someone should fix this quickly as it seems like a big bug cause it means the users of Unciv were getting late updates ever since the Mods exist (lol).

**Comment by touhidurrr** [comment]
Also, lol I have found a trick to manually trigger an update.
If I just start the RekMOD repo and remove that star, an update is triggered. 🤣
