### ISSUE TITLE
Barb camp - capture missionary in camp bug

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#6111]
**Platform**
Windows
**Version**
3.19.5 - playing Gods&Kings

**Describe the bug**
Barb camp with a swordsman & a missionary - attack to kill swordsman, attack (with boat) to capture missionary. Barb camp at that point still exists with my missionary in it. Next turn: barb unit spawned, so is on the same tile as my missionary... Looks really weird. Either a) the capture of the unit captures the camp or b) the captured unit is kicked out to another tile?
![image](https://user-images.githubusercontent.com/21982451/152685865-c9a27b33-afdc-46d3-a513-8600d9e658b2.png)

**Comment by xlenstra** [comment]
Can you send the save file of this game?

**Comment by yairm210** [comment]
The base problem here is 'attacking with melee to capture a unit and yet not entering the tile'. Melee units that can't enter the tile shouldn't be able to capture units there...

**Comment by krijnsent** [comment]
> The base problem here is 'attacking with melee to capture a unit and yet not entering the tile'. Melee units that can't enter the tile shouldn't be able to capture units there...

That would put an end to those pesky barbarians robbing me of my workers with their boats :-)! 👍
