### ISSUE TITLE
Don't make unique's unusable as soon as deprecated

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6122]
Self-explanatory. My advice is to keep them for at least a month or 2 weeks before they stop working. The reason, situations like this:
![Deprecation Problem](https://user-images.githubusercontent.com/46617994/152818090-aaceca18-193c-4548-a503-36d1eac5facc.jpg)
So, fixing mods too quick makes most of the users face problems with it. And too Slow makes even more. 😂

**Comment by touhidurrr** [comment]
> I was under the impression that for a few versions they are marked for depreciation first. It's up to the modders to notice and adjust before they're deactivated

I was too. But people are complaining instantly after an update is rolled out. So, I guess it is not?

**Comment by yairm210** [comment]
This is already the case.
Uniques still work for a couple of months, but we start warning in the options menu immediately.
After they stop working, we start warning in the new game screen.
If people are complaining instantly then that probably means we fully removed a unique that was deprecated a long time ago.

**Comment by touhidurrr** [comment]
> deprecated

So you mean we should make / merge pr's some versions later?

**Comment by yairm210** [comment]
No
The complaints were because of problems that existed for a long time but were not solved
And you don't need to PR deprecation, we do that ourselves :)

**Comment by touhidurrr** [comment]
> And you don't need to PR deprecation, we do that ourselves :)

This doesn’t make sense. I think you didn’t understand what I was trying to say. Unciv updates doesn’t roll out in play store at the same time it does in Github. So, in the meantime  if we fix any new deprecation warning it would make problems for those with lower version. Cause Unciv doesn’t contain a future prediction that can automatically tell what uniques you would be updating later. Newer updates will still show errors on older versions.

**Comment by yairm210** [comment]
Ahhh I see
That is a real problem
I can't think of an easy way to solve the discrepancy :/

**Comment by xlenstra** [comment]
Best thing I can think of is having mods set a minimum version and only allowing updates when the game is at least as new as that. Old games will still have the old version locally with (mostly) functional uniques.
Problem still remains for new installs but unless we start caching mods for different versions I dont see an easy way to handle it in that case

**Comment by touhidurrr** [comment]
> Best thing I can think of is having mods set a minimum version and only allowing updates when the game is at least as new as that. Old games will still have the old version locally with (mostly) functional uniques. Problem still remains for new installs but unless we start caching mods for different versions I dont see an easy way to handle it in that case

That looks kinda complicated.
