### ISSUE TITLE
More performance testing!

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#6137]
Welcome to another exciting episode of performance improvements!
This time - "next turn while at war!"

Initial performance test (for 40 seconds, couldn't be bothered to wait it out):
![image](https://user-images.githubusercontent.com/8366208/153388851-0904c661-b0ec-40bb-84c6-04bb1090d21c.png)

A. isMovementAffectedByZoneOFControl is WILD, most of the overhead seems to be from iterating some arraylist?
B. ChooseMilitaryUnit seems to also take far longer than necessary, that's 10 whole seconds, what is going on there? Could this be a 'each city tries to make decisions when the answers are the same civ-wide'?
C. All military units try to move towards the enemy city, IIRC we check which of our cities is closest to an enemy city and then charge the enemy city. Perhaps a better way to do it is, if my city is closer than the enemy city AND I'm not in between the cities (i.e. my distance to enemy city > my city distance to enemy city) then instead I head towards my city, that should reduce some of the movement time to make it more manageable

**Comment by Omar200812** [comment]
I think its B. 10 second is very late for this code but this is due to the number of troops

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/153404405-ec12ac99-6cb6-4d24-8494-8a3ec8260163.png)
Okay! Instead of a micro-improvement, a macro-improvement! Only consider ZOC in the *current* turn when pathfinding, because units could move around later!
That basically gets rid of this high-performance obstacle entirely!

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/153410264-9f63a63e-1bd3-41df-a19d-05788fdc090d.png)
After many improvements to the addMilitaryUnitChoice it's calmed down a lot, and now we've gotten to a new contender, a getMatchingUniques in the *nuxtTurn* function itself?! That's odd

**Comment by yairm210** [comment]
More lazies for pathfinding improvements and we're now shoring up on Hashmap.put as our main source of time spent, which means we're basically done here and it's time to move on to the next goal - don't head towards the enemy city if you can head towards our city instead!

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/153418512-31dce199-820a-4678-ae23-1c61e1a660b5.png)

The new 'choose city to attack' seems to cut down the time of that function considerably, it should also help the AI feel more challenging as now it focuses its attacks on a certain area instead of attacking wherever is closest to the current unit

**Comment by yairm210** [comment]
We're now back the 'good old' timewasters - building.getStats, tileInfo.getTileStats, getLastTerrain, all extremely fun functions that we'll need to get to.

But for now I'm willing to call this a day and a job well done.

**Comment by yairm210** [comment]
For documentation purposes:
A - solved by 86450c54ebefe76a2f6eab08b5900f1ee4f0f17e
B - solved by 8ee2a34a4dfd65a36f348586bf99971fed923a3e
C - solved by 87e2764733d7c55abd49811ba81ff39f38d990e4

Also 505a78182c640238ce13b35589203150819e2b68 for more pathfinding performance
