### ISSUE TITLE
pillaged water tiles bug

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#614]
I don't know the originally expected way of recreating an improvement on a pillaged water tile:
a. must send and sacrifice a new work boat as if a tile had never been improved
b. must send a workboat and sleep there for two turns - like on land tiles

Now neither of the above works correctly (the a. with a description [improvement] in 2 turns). I vote for b. if there's still a choice. :dolphin:

**Comment by yairm210** [comment]
Hm.
http://well-of-souls.com/civ/civ5_improvements.html says that naval improvements are destroyed when pillaged, and I can't find any other sources, so I'll believe him for now.
