### ISSUE TITLE
I can't play with custom map, it crashes

### ISSUE THREAD

**Issue by binuball** [yairm210/Unciv#6142]
**Platform**
Android 7.0
Ram 4GB

**Version**
From Play Store, version 3.19.5

**Describe the bug**
I can't play a game with custom map I made.

**To Reproduce**
1. Start new game
2. Map Options
3. Map type
4. Click Custom
5. game CRASHES

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xlenstra** [comment]
Can you include the map you made that results in the crash? Or, if possible, all maps that you have installed?
If you try and open a map in the map editor, does the crash also occur? If so, only on one map? Which one? On all maps? When does it happen? When you load the map, or when you choose a map to load?

**Comment by binuball** [comment]
> Can you include the map you made that results in the crash? Or, if possible, all maps that you have installed? If you try and open a map in the map editor, does the crash also occur? If so, only on one map? Which one? On all maps? When does it happen? When you load the map, or when you choose a map to load?

1. I want to open custom map, so I press 'custom' button and before choose box appears, it crashes.
2. There are no problem about map editor at all. Like load, make new, save maps.

**Comment by xlenstra** [comment]
Does the crash screen show up or does the app just close?

**Comment by binuball** [comment]
It shows error screen under < 0.5s.
I've captured the screen and this is what I saw.

An unrecoverable error has occurred in Unciv:

**Platform:** Android
**Version:** 3.19.5
**Rulesets:** [Civ V- Gods & Kings, Civ V Vanilla, Civ5ExpansionMod, Unciv IV mod, 5Hex-Tileset-master]
**Last Screen:** `com.unciv.ui.newgamesscreen.NewGameScreen`

-----------------

Device Model: SM-N920S
API Level: 24

-----------------

**Message:**
```
java.lang.RuntimeException: Actor: TranslatedSelectBox
  at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
  at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
  at com.badlogic.adx.scenes.scene2d.utils.Sellection.fireChangeEvent(Selection.iava:225)
```


If this keeps happening, you can try disabling mods.
You can also report this on the issue tracker.

**Comment by SomeTroglodyte** [comment]
> com.badlogic.**a**dx.scenes. 

Looks like typed not copied - please provide if possible the rest of the stack trace, specifically the first few lines in any Unciv namespace. Also, as it is very likely that trace will finger `MapOptionsTable.fillMapFileSelectBox`, I concur with Xander - we'd need the entire set of your maps, including those provided by mods.

**Comment by yairm210** [comment]
With new crash screen this should be investigatable if you want to try
If not I'll close it as "not relevant", much water has passed under the bridge since
