### ISSUE TITLE
Any letters in the game are not showing

### ISSUE THREAD

**Issue by binuball** [yairm210/Unciv#6143]
**Platform**
WIndows 10, 64 bit

**Version**
Version 3.19.7

**Describe the bug**
I can't see any letter on the game. So it means I couldn't play the game.
Please take a look in the screenshots.

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/66934926/153535919-fe28641e-0f5f-49c1-a16c-2686e829042e.png)
![image](https://user-images.githubusercontent.com/66934926/153535932-32a4483f-09b1-4f03-a5a8-b830b9938038.png)

**Additional context**

**Comment by AdityaMH** [comment]
What language you used?

**Comment by xlenstra** [comment]
Is the problem resolved when you restart the game?

**Comment by binuball** [comment]
> What language you used?

It's not depend on what language I used.

**Comment by binuball** [comment]
This is my `GameSettings.json` file.

{language:Korean,tutorialTasksCompleted:[Open the options table],userId:65a59f4f-aca4-4c29-b681-3e367d03f9ea,windowState:{width:1920,height:1017}}

I can't see letters on either version 3.10.8 or 3.11.1, 3.14.15 which I've played well in past.

**Comment by yairm210** [comment]
Does your device have Korean characters installed? The only reason I can think of is if it doesn't

**Comment by binuball** [comment]
If you mean font, yes, it has many korean fonts.

**Comment by SomeTroglodyte** [comment]
From "It's not depend on what language I used" the only explanation I see is that `NativeFontDesktop.getCharPixmap` is misbehaving in binuball's case and either only delivers Pixmap's of height 0 or only transparent pixels...

(Warning: I don't trust Windoze > 7, or Oracle)... Is this running under the packr-controlled 'release' Java runtime or under the system's? Try tweaking the os, java or os-java interface somehow (update !os, try running the jar from a current adoptopen jdk >= 11, run from a fresh user profile, look for console output, yada yada yada)...

**Comment by yairm210** [comment]
Closing as "cannot investigate". Sorry we can't help, but there's really no way we can replicate this :/
