### ISSUE TITLE
Where are Great Merchant & Engineer from automatic spawn ?

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#615]
I finished 3 games and I never get Great Merchant nor Great Engineer from automatic spawn (due to Great Person city point), even with the social policie Libery.
Is their spawn disabled ?

**Comment by yairm210** [comment]
No, their spawn is dependant on the great person points you accumulate from wonders and specialists.
If you take all your cities and max out the number of production specialists, you'll definitely get a great engineer
The great person points info is shown in overview -> stats

**Comment by B5656** [comment]
@yairm210 I looked stats on my games, and I saw that points needs for make Great Person are the same for the 4, so, when a Great Person born it reset point of his type and it increase the amount of points needed for every Great Person, it's perhaps what it should do, but shouldn't it be independant from each other ?

**Comment by yairm210** [comment]
That's the way it is in original Civ :shrug:

**Comment by B5656** [comment]
Okay then :shrug:
