### ISSUE TITLE
"Earn [amount]% of the damage done to [mapUnitFilter] units as [plunderableStat]" earning far too much plunder

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6152]
If you have units that can plunder from all units, and you successfully kill a unit in one shot, you may end up causing too much damage and thereby plundering too much stuff from the target. In one case, attacking an embarked unit (with a defense of zero) caused me to earn over two hundred million of plunderable stat from one kill.

I've uploaded the mods I was using. To set up the situation, go to "before too much damage" save file, and use the archer to target the embarked raider. Attacking the defenseless raider will reap you huge rewards.
![Screenshot (95)](https://user-images.githubusercontent.com/58439827/153724458-677e0317-8915-441e-b4a7-a3945f2ef5c1.png)
[TooMuchPlunder.zip](https://github.com/yairm210/Unciv/files/8054307/TooMuchPlunder.zip)

**Comment by yairm210** [comment]
Resolved 🙂
