### ISSUE TITLE
"Discovering" future tech breaks game

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#616]
If you use a great scientist to discover future tech you wil not be able to advance to the next turn as the game will prompt you to "pick a tech!", which is impossible.

**Comment by yairm210** [comment]
Good catch, Future Tech is very weird in that it can be researched after it has been researched, which is a lot of fun.
Hope to deal with this soon.

**Comment by yairm210** [comment]
Closed by @ninjatao
