### ISSUE TITLE
AI's prophets often camp in players' territory.

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6167]
**Platform**
Android 10

**Version**
3.19.7, Google play

**Describe the bug**
AI's Great prophets often go to player's land and stay there, probably because they have nothing to do. But they block resources sometimes and that's annoying.

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>
(No save file because Github doesn't allow it, the message is too long.)

**Expected behavior**
If they don't have anything to do, they go back to their land.

**Screenshots**
![Screenshot_20220215-104606_UnCiv](https://user-images.githubusercontent.com/79529669/154037014-6a853375-c36f-4e3e-bf29-095c754c503d.jpg)
![Screenshot_20220215-104553_UnCiv](https://user-images.githubusercontent.com/79529669/154037037-5fc3508b-93ca-49ce-9ba0-48f110704880.jpg)

**Additional context**

**Comment by AdityaMH** [comment]
Also great prophet ability just to found religion, not to spread religion or create holy site (i'm never seen other civ build holy site)

**Comment by yairm210** [comment]
Closing this, as it's already listed in #4290

**Comment by xlenstra** [comment]
As far as I'm aware, prophets should try to found or enhance a religion, and if that is already done, try to spread it. If all known cities already follow the religion, the AI doesn't know what to do with them, and just leaves them idling. This isn't necessarily listed in #4290, though

**Comment by jahodovykolac** [comment]
Probably the simplest solution is to make them sit in own territory (also go back if the land owner changes) or make them build Oraclesq
