### ISSUE TITLE
Add map editor creation and edit options

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#617]
1. there is no option to remove or place ancient ruins

2. as far as I can tell you can only edit the one map. Would it be possible to create a new map or perhaps even randomize a new create-a-map? The ability to choose the map size would be nice as well

**Comment by yairm210** [comment]
I took the easy option in 089f8ac, by having the Map Editor button automatically open the CURRENT MAP for editing, thus all the map creation options are shared between the game and the map editor =)
Good enough, gets the job done
