### ISSUE TITLE
Random damage calculation

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#6175]
**Platform**
Linux/Flatpak

**Version**
3.19.7

**To Reproduce**
![Unciv-reporte](https://user-images.githubusercontent.com/77393537/154167794-09d4a9d8-038d-4f36-8ea9-a8fb14a0d71a.gif)

**Expected behavior**
Damage calculation should be the same on the same situation with the same units and tile parameters.

**Comment by yairm210** [comment]
No. The damage itself is random, therefore the display is random.

**Comment by Erz3** [comment]
But it should be calculate just one time.
