### ISSUE TITLE
Music keeps playing even after pressing 'home' button

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6178]
**Platform**
Android 10, Android 5.1

**Version**
3.19.8 and some earlier

**Describe the bug**
Music is still playing even if app is minimized using 'home' button.

**To Reproduce**
1. Open app
2. Press home button
3. Wait a while
4. Music is playing

**Expected behavior**
Music is paused until opening the app.

**Additional context**
I already reported this in #5438, but that was closed because of old android 5.1.

**Comment by SomeTroglodyte** [comment]
- Oreo 8.0 AVD - ~~No repro, pauses just fine.~~ see below
- Q 10.0 AVD - ~~pauses just fine.~~ ditto
- LOS 16.1 Hardware - pauses just fine but _after configured delay_ plays a new song. Swiping Unciv out of the app history stops music.

**Comment by jahodovykolac** [comment]
Still happening on 3.19.11
