### ISSUE TITLE
Petra is unavailable on single desert

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#6186]
3.19.9 apk
on Android 11, no mods

[Greece - 1 turns.zip](https://github.com/yairm210/Unciv/files/8094504/Greece.-.1.turns.zip)
ZIP contains 2 jsons; medieval era and information era.

Currently, Petra is unavailable on single desert.
Below shows Greece - 1 turns medieval.json.
![Screenshot_20220218-110507_UnCiv](https://user-images.githubusercontent.com/64586749/154626485-f1a106ef-2dec-406f-ad98-e8f6b73c1849.jpg)

I made a new game on a custom map in which Greece starts on a single desert.
I started from Medieval and Information era, and both Petra and solar plant is unavailable on a single desert.
But according to Civ wiki, they are available "near or on the desert."
[Petra](https://civilization.fandom.com/wiki/Petra_(Civ5)) : ...City must be built on or next to desert
[Solar Plant](https://civilization.fandom.com/wiki/Solar_Plant_(Civ5)) : ...However, it can only be constructed in a city which is on or adjacent to a desert tile.

**Comment by SomeTroglodyte** [comment]
Other uses of the `MustBeNextTo` unique use tile filters 'Coast', 'Fresh water', or 'Mountain'. As far as I can guess, those would not be affected, as cities cannot be built on Coast or Mountain; and a single Fresh water tile without any of its neighbors also being freshwatered is impossible - is it (= are Gardens affected and can't be built on the only Oasis in a riverless desert - I don't think so)?

Any negative side effects or negative political implications to change the Unique to _mean_ 'next to or on' without deprecating it or changing its wording?

Both implemetations (building and improvement) rely on `TileInfo.isAdjacentTo` which uses `neighbors` - and those do not include the center tile. `isAdjacentTo` in turn is used only by this Unique and the `ChangesTerrain` Unique. For the latter, changing the meaning of `isAdjacentTo` could be detrimental as I see it. Could - not in the present rulesets as those use only 'River' as tilefilter which takes a different path within `isAdjacentTo`.

Clean and simple might be to create a `TileInfo: fun isAdjacentToOrOn(terrainFilter: String) = isAdjacentTo(terrainFilter) || matchesFilter(terrainFilter)` and use that for `MustBeNextTo` but not `ChangesTerrain`? ...????

Umm... @  Unciv-Experts: Why doesn't `isAdjacentToFreshwater` recurse over the entire map?

**Comment by xlenstra** [comment]
> Umm... @ Unciv-Experts: Why doesn't isAdjacentToFreshwater recurse over the entire map?

This seems to be a result of `isAdjacentToFreshwater` checking for `Fresh water` (note the small "w"), while `matchesTerrainFilter` checks for `Fresh Water` (with a capital 'w'). I don't know why this is, but this seems to narrowly avoid infinite recursion using misspelling

**Comment by SomeTroglodyte** [comment]
Wow. Didn't see that. Now I'm stumped on how to go about this thoroughly and cleanly... 🤦🙈

**Comment by SomeTroglodyte** [comment]
Some collected statistics:
#### lower case
- "Fresh water" `UniqueType.FreshWater` (Lakes, Oasis)
- "Fresh water" filter used by `UniqueType.MustBeNextTo` (Garden, Floating Gardens)
- "Fresh water" filter used by `UniqueType.ImprovementStatsOnTile` (Farm, Terrace farm)
- "Fresh water" terrainFilter recognized by `TileInfo.isAdjacentTo` - using upper case variant would pass it to `matchesTerrainFilter` for all neighbors - consequences would need a Big Think
- "Fresh water" filter passed to `TileInfo.matchesTerrainFilter` in `isAdjacentToFreshwater`
- "Fresh water" hardcoded into `TileInfo.getImprovementStats`, tests `isAdjacentToFreshwater`, **alarming comment!**
- "Fresh water" element of `TranslationFileWriter.generateStringsFromJSONs.tileFilterMap`
#### upper case
- "Fresh Water" tileFilter in conditional `UniqueType.ConditionalInTiles`, `ConditionalInTilesAnd`, `ConditionalInTilesNot` (resource "Generate" uniques only)
- "Fresh Water" filter recognized by `TileInfo.matchesTerrainFilter` - testing `isAdjacentToFreshwater` - (function also recognizes uniques, and through those the lowercase variant)
- "Fresh Water" element of `UniqueParameterType.TerrainFilter.knownValues`
#### other
- "Can also be built on tiles adjacent to fresh water" - `UniqueType.ImprovementBuildableByFreshWater` (Farm)
- "non-fresh water" filter used by `UniqueType.ImprovementStatsOnTile` (Farm, Terrace farm)
- "non-fresh water" hardcoded into `TileInfo.getImprovementStats`, tests `isAdjacentToFreshwater`

We need to differentiate more clearly the tile unique marking a source of fresh water and the test "has access to fresh water". Currently, the former is lower case and the latter is upper case - with some muddying from the arising confusion already crept into code.

At the moment I'd plead for some renames, to remove "access to fresh water" functionality from isAdjacentTo entirely, split it into two (6-tile test w/o center for terrain conversion, 7-tile test for Petra&Solar); replace the now nonfunctional MustBeNextTo unique used by Gardens with a clearer "must have access to fresh water" unique; declare the 2-word "Fresh water" string to mean a filter for "has access to fresh water", deprecate all "Fresh Water", and rename the Oasis/Lakes unique to "Source of fresh water" - which could also deterministically and unequivocally be tileFilter'ed on. 

Just a tentative card house for the moment, no brain cells invested yet into considering existing mods.
