### ISSUE TITLE
Add a warning icon when an already built building/wonder has no more the required building in all cities

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#6188]
**Is your feature request related to a problem? Please describe.**
Currently, there's no visual indicator when an already built building/wonder (requiring a particular building to be built in all others cities) doesn't fill any more the requirement.
For example, the National Treasury that needs a Market built in all cities. If the player founds a new city (that has not yet a Market), the National Treasury bonus is no more awarded. 

_Here, nothing changes on the stats drilldown, and the player has to remember which buildings has to be built in the new city, to fulfill each building/wonder requirements, and get back their bonus:_
![bonus_alert](https://user-images.githubusercontent.com/11946570/154749609-99ecd0fb-c158-4b31-961c-56f4535e8781.png)
_Except if it clicks all buildings/wonders to remember which ones needs a particular building elsewhere:_
![bonus_alert2](https://user-images.githubusercontent.com/11946570/154749948-cd011188-050a-425e-a450-3cfa55fd995f.png)

**Describe the solution you'd like**
As soon a building/wonder requirement for bonus is broken (mainly when founding a new city, or conquering one), a warning icon appears next to the building/wonder name:

_In a wink, the player can see which building/wonder doesn't provide its bonus:_
![bonus_alert3](https://user-images.githubusercontent.com/11946570/154750390-707d7d36-a474-46fa-85b9-550b613062b0.png)

**Describe alternatives you've considered**
Or simply desaturate the building/wonder slot that does not meet its requirement and does not provide its bonus:

![bonus_alert4](https://user-images.githubusercontent.com/11946570/154751781-a8d10a52-4fde-488f-b9da-e2d8225485bc.png)

-----------------------
Thanks for reading.

**Comment by yairm210** [comment]
This results from a misunderstanding of the requirements
They only apply to *building* the wonder, once it's built the affect applies constantly

**Comment by Ouaz** [comment]
Oh, ok, but then `[building] required : [cityname]` should be removed in the statistics drilldown when the wonder is already built, and that a new city is added to the empire, because it's misleading:

![bonus_alert2](https://user-images.githubusercontent.com/11946570/154749948-cd011188-050a-425e-a450-3cfa55fd995f.png)
_National Treasury already build in the Capital, Neapolis newly founded but appears as a Market requirement in the statistics drilldown._

On the other hand, it was a funny coincidence, because the turn after I founded a new city, I lost -1 culture and about -6 gold (as I gain a few from other things), so I thought it was the +8 gold +1 culture lost from the National Treasury. :sweat_smile:
