### ISSUE TITLE
Double defensive bonus on hill tiles.

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#6189]
**Platform**
Android 11 (F-Droid)
Linux (Flatpak)

**Version**
3.19.7

**Describe the bug**
Individually, forests/jungle and hills tiles give a 25% defensive bonus to terrain units, but also I can improve it building a fort on those tiles to reach 75%. However, when a forest/jungle has been generated on a hill, defensive bonus is just 25% and should be 50%.

**Expected behavior**
Forests/jungles generated on a hill, should provide a double defensive bonus. (Also, if I have built a fort on a hill with a forest/jungle, should I get a 100% defensive bonus)

**Comment by Erz3** [comment]
After the last update (3.19.11), tile defensive bonuses are break in my online match.

I have been testing on new offline games with and without mods and there are no problems.

Is there any solution or is it definitely broken?

https://user-images.githubusercontent.com/77393537/155418270-e008bc4f-adfe-43d9-81cd-abc4f4825de9.mp4

**Comment by xlenstra** [comment]
It's very likely the same problem as 3.19.11-patch1 was released for. Can you check whether that version fixes your issue?

**Comment by Erz3** [comment]
I have got 3.19.11 on Flatpak.

**Comment by Erz3** [comment]
Now on Flatpak, 3.19.12 version, work everything fine.

¡Great work!
