### ISSUE TITLE
minimum distance between capital

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#619]
As you can see on the image below (medium map, 5 IA) capitals spawned really too close, so 50% were never used in the game, wouldn't it be better to make a minimum distance between capitals when the game start ?
![capitalSpawn3](https://user-images.githubusercontent.com/40295529/55316130-06479100-546e-11e9-81da-219ea97ebb3f.png)

**Comment by yairm210** [comment]
When placing settlers, I space them far apart
As for capital cities, that depends on where the settlers decide to settle, I don't want to limit their options
But wow, that's pretty crazy, maybe I'll do over three seller location code
