### ISSUE TITLE
"Convert gold to science" slider causes AI to go bankrupt

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6192]
Ever since adding the "Can convert gold to science with sliders" to Smoky Skies Redux, AI civilizations have started going bankrupt late in the game, which they were not doing before. I believe that they are converting too much gold into science, and the AI is not smart enough to realize that it doesn't have to go into debt.

Ideally, I'd like the AI to be able to recognize when it's losing money and adjust its science conversion accordingly, but in the short term, I have a simple solution: set the default level of gold-to-science to zero.

**Comment by SomeTroglodyte** [comment]
Might be easier to check out if there were a save & explicit info whether the mod used matches its repo 100% or is modified

**Comment by SpacedOutChicken** [comment]
I've attached a mod with the slider enabled here, along with a saved game from that mod. Just 18 turns in, the AIs are all deep in debt with no end in sight.
[Debt.zip](https://github.com/yairm210/Unciv/files/8121374/Debt.zip)

**Comment by SomeTroglodyte** [comment]
Thx. I might look into it if I _fail_ to get my priorities straight...

**Comment by SomeTroglodyte** [comment]
Just 'thinking' aloud:
- The AI never checks the `convertGoldToScience` 'Unique'
- The AI never touches `TechManager.goldPercentConvertedToScience`
- The default is 0.6f for all civs. The var is saved, so changing the default could potentially annoy someone.
- stack from where the value is applied: CityStats.updateFinalStatList - CityStats.update - 33 call sites, I pick CityInfo.startTurn - CivilizationInfo.startTurn - GameInfo.nextTurn
- So where would we hook in an AI routine for that percentage? At the point where the 'slider' is used during nextTurn, neither the initial treasury at the start of this AI's turn nor the final treasury at the end of switchTurn are known to any degree of approximation, and the value changes for each city called. Deciding a percentage ad hoc, per city, right before it is used seems to depend on too many random or inscrutable factors. So - at the start of the AI's turn, just after any existing `updateStatsForNextTurn` call, and do some logic from that gold surplus estimate, and maybe era...

**Comment by SomeTroglodyte** [comment]
With that PR, income stabilizes somewhat _after_ one turn, right after loading it seems to base the displayed stats on the saved (=default) conversion rate, but that's fine by me.
