### ISSUE TITLE
Polynesian naval units can no longer enter oceans immediately

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6202]
The new format for the Polynesian unique takes away an ability they had before: the ability for all naval units, even Triremes and such, to immediately enter ocean tiles. I suggest going back to the old unique, or creating a new unique for overriding the "Cannot enter ocean tiles" unique.

**Comment by SomeTroglodyte** [comment]
```kotlin
        if (tile.isWater && unit.baseUnit.isLandUnit()) {
            if (!unit.civInfo.tech.unitsCanEmbark) return false
            if (tile.isOcean && !unit.civInfo.tech.embarkedUnitsCanEnterOcean)
                return false
        }
        if (tile.isOcean && !unit.civInfo.tech.wayfinding) { // Apparently all Polynesian naval units can enter oceans
            if (unit.cannotEnterOceanTiles) return false
        }
```
... unitsCanEmbark and embarkedUnitsCanEnterOcean are the new uniques and do exactly as promised, while wayfinding is the old one (the code caching it will also set the first two if found). It's clear what exactly is lost here. I'd say deprecate EmbarkedUnitsMayEnterOcean right after creating it, and do a UnitsMayEnterOcean with unit filter and conditional support - then Polynesia can do "Enables [All] units to enter ocean tiles", and a mod aiming at current behaviour can do "Enables [embarked] units to enter ocean tiles" - or similar  ...?

**Comment by SomeTroglodyte** [comment]
... Polynesia's can embark immediately fails, too, as at the time the unique is evaluated the era is not initialized and thus the conditional set in json fails ... wrong call order in TechManager.setTransients, notwithstanding that the conditional is redundant as it's meant to be always true???
