### ISSUE TITLE
Not so invisible submarine

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#623]
As you can see below, if you are using a military unit, or a city, and then select a ocean tile where there is a submarine, the fight screen tell you than there is a submarine. With this bug you can know where they are submarine near you.
![submarine](https://user-images.githubusercontent.com/40295529/55318411-01391080-5473-11e9-9979-31d6332f5a0d.png)
![submarine1](https://user-images.githubusercontent.com/40295529/55318417-04340100-5473-11e9-8c97-0f0ebafbc217.png)

**Comment by ninjatao** [comment]
For units, I have no idea what can be done for this. You cannot move your units to tile that contains an enemy submarine anyway.
But for cities, yes it should not indicate existence of submarines.

**Comment by yairm210** [comment]
Solved by @ninjatao
