### ISSUE TITLE
Terrain features not overriding stats

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6234]
**Platform**
Android 10

**Version**
3.19.11, Google play

**Describe the bug**
Terrain features like hills, forests or jungles don't override stats anymore, even though Civilopedia says otherwise.

**To Reproduce**
1. Play a game
2. Find a hill, forest or jungle
3. Look on stats
4. Stats are the same as base terrain

**Expected behavior**
Terrain features override stats, for example forest on grasslands yields 1 food and 1 production, not 2 food.

**Screenshots** 
![Screenshot_20220226-115203_UnCiv](https://user-images.githubusercontent.com/79529669/155840713-2a25b027-e94c-40df-8472-353b863289da.jpg)

**Comment by SomeTroglodyte** [comment]
3.19.11-patch1 already fixed this.
