### ISSUE TITLE
Oasis not giving the 3 food, 1 gold.

### ISSUE THREAD

**Issue by Bigrichman** [yairm210/Unciv#6235]
**Platform**
Android phone, 8.1.0

**Version**
Google play store,  3.19.11

**Describe the bug**
After starting a new game, the Oasis Tiles give the food and gold, but after the next turn, the food and gold go poof from all of the oasis tiles.

**To Reproduce**
1. Tap/Click Start game
2. Hit next turn if you can see Oasis's
3. Tap/Click the Oasis tile
4. Oasis shows no food or gold

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
The Oasis Tiles giving me food and gold.

**Screenshots**
![20220226_084746](https://user-images.githubusercontent.com/39731418/155845597-8ef24493-2d33-4a41-b4c6-bbec0a0e5f24.jpg)

**Additional context**

**Comment by Ouaz** [comment]
Fixed in 3.19.12, but not yet released on GS.

**Comment by SomeTroglodyte** [comment]
I don't see where 3.19.12 fixes this, at least not in the changelog, but #6230 had to fix the terrain features transient not being set, which sounds suspiciously like this "go poof" here.

**Comment by SomeTroglodyte** [comment]
> I don't see where 3.19.12 fixes this...

I was actually very much wrong, 3.19.11-patch1 already fixed this.
