### ISSUE TITLE
The AI cannot found new cities with non-civillian settlers

### ISSUE THREAD

**Issue by HaneulCheong** [yairm210/Unciv#6237]
**Platform**
Windows 64 bit

**Version**
3.19.12 GitHub

**Describe the bug**
Apparently the AI wouldn't found a single city when the base game's settler is altered as a melee unit. I'm afraid this bug is perhaps affecting the AI's use of Conquistadors.

**To Reproduce**
1. Edit the base game's [Units.jsons](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/Civ%20V%20-%20Gods%20%26%20Kings/Units.json) or Create a mod with the following code included as './jsons/Units.json':
```json
[
    {
        "name": "Settler",
        "unitType": "Sword",
        "movement": 2,
        "strength": 5,
        "cost": 106,
        "uniques": [
            "Founds a new city",
            "Excess Food converted to Production when under construction",
            "Requires at least [2] population"
        ],
        "hurryCostModifier": 20,
        "attackSound": "nonmetalhit"
    }
]
```
2. Start a new game as a spectator.
3. AI nations' settlers would wander around fighting barbarians instead of founding their capital.

**Expected behavior**
The AI should be able to decide when to fight and when to found a city when non-civilian-unit-type settlers are given.

**Additional context**
I found this bug while trying to help someone create (presumably) their very first mod.

**Comment by SeventhM** [comment]
Closed as solved
