### ISSUE TITLE
incorrect targeting of Crossbowman

### ISSUE THREAD

**Issue by ultradian** [yairm210/Unciv#6239]
**Platform**
Fire OS 7.3.1.2

**Version**
3.19.11 Google Play Store 

**Describe the bug**
From the screenshot, the selected Crossbowman is targeting a Mohawk warrior that is 3 hexes to the left and a Crossbowman two below. They are unable to target the one two to the right, as if they are located on the map one hex to the left.  This is a regular map without wraparound.

I tried to include a savegame, but it said that it was too big and wouldn't let submit.
<details><summary>Saved game</summary>

```
The Netherlands -  215 turns crossbow shot.txt

```
</details>

**Screen
![Screenshot_20220224-142142](https://user-images.githubusercontent.com/14141325/155864324-67b31f6b-6d33-4b60-bcbc-4756fc4d6567.png)
shots**

**Additional context**
hex maps are complicated!

**Comment by itanasi** [comment]
So the Crossbow to the Right belongs to Milan, and you are currently their Ally (eg not at War). So you can't target that unit. So this is working as expected. I loaded your save, declared War on Milan, and can now target it
![image](https://user-images.githubusercontent.com/44038014/155868508-6f12bec6-f4c7-4ce7-9aea-05f536fdb8bb.png)

**Comment by ultradian** [comment]
Ok. I think I just wasn't seeing it clearly with the colors being similar.  Sorry! Will close. I just starting playing this without a previous exposure to Civ5 and really enjoy it, but have a challenge learning some of the game mechanics. Amazing job on a complex game.  I think that due to my lack of experience, I expected targeting to be based on the range of targets (fixed at two), and not what can be hit while including a move (which is much more helpful to display).  I'm still not used to it automatically moving to places I didn't expect during attack sequences.
