### ISSUE TITLE
Maintenance cost for each unit

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#6264]
**Describe the solution you'd like**
Please, I need to know how many gold a military unit cost me. It's really important to know maintenance cost for each unit.

**Additional context**
Now I can check the total cost per turn, but I also need to know the individual amount for each unit.

**Comment by itanasi** [comment]
The maintenance for units isn't different per unit. It's based on total number of units relative to how many you get for free and then multiplied by a cost per Era.

**Comment by Erz3** [comment]
Okay, so you mean there are free units with no maintenance cost and others with an extra cost for Era.

That is what I need to know exactly: witch specific units are free and what is the extra cost per Era.

**Comment by jahodovykolac** [comment]
There aren't specific free units, there are things like the policy that gives you 8 free units. Maybe there are always some free units but I'm not so sure about that.

**Comment by itanasi** [comment]
By default the first 3 units are free. But you can do things like get the Policy that all garrisoned units are free as well. And uniques that reduces coats for specific units.

Exact equation you can see here: 
https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/logic/civilization/CivInfoStats.kt

**Comment by Erz3** [comment]
> By default the first 3 units are free. But you can do things like get the Policy that all garrisoned units are free as well. And uniques that reduces coats for specific units.
> 

Would it be so difficult to show the exact maintenance cost per unit on this panel?

![image](https://user-images.githubusercontent.com/77393537/156674607-eb9c356d-e843-4dbc-9f32-90802a72a382.png)

For example, I need to know which of them (units) could be the best option to stay in a city after getting the Military Caste policy.

**Comment by Erz3** [comment]
Ok, I get it.

Thanks you both for your time and your polite replies. You are doing a great job.

I will help you any way I can because I love this proyect.

**Comment by yairm210** [comment]
Closing as "knowledge issue"
