### ISSUE TITLE
Mohawk Warrior should keep its Forest+J bonus on upgrade

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6281]
[This link](https://steamcommunity.com/sharedfiles/filedetails/?id=233028579) suggests that the Mohawk Warrior's +33% in Jungle/Forest should be implemented as Promotion, not direct Unique. It also suggests the "does not need Iron" unique should have a quirk - namely you can't upgrade Warriors to it with zero Iron though it won't be consumed. Haven't tested Unciv's behaviour on the latter.

**Comment by ravignir** [comment]
Yes, +33% combat bonus is a promotion.

>It also suggests the "does not need Iron" unique should have a quirk - namely you can't upgrade Warriors to it with zero Iron though it won't be consumed.
>
you don't need iron to upgrade to mohawk warrior

**Comment by yairm210** [comment]
That's a silly quirk, and sounds like a Civ V bug. Doesn't consume iron means didn't require iron.

**Comment by ravignir** [comment]
anyway: if you upgrade jaguar to mohawk warrior,  +33% bonus in forests/jungle stack.
![az](https://user-images.githubusercontent.com/30041793/156924057-fbe18c6f-d3b8-4a32-a29a-9db727941c0f.png)

**Comment by SomeTroglodyte** [comment]
While that link sounds like well-researched I welcome the stance we don't want the same quirk. Will test sometime.

> stack

Right, read that in the same research too - so two different promotions. The vampiric trait of the Jaguar doesn't inherit?

**Comment by ravignir** [comment]
That "vampiric" trait does inherit.

**Comment by ravignir** [comment]
i think i will go over all existing units and list things that inherit.

**Comment by SomeTroglodyte** [comment]
> list things that inherit

:eyes:  Monumental task - optional inclusions: Checkmark md formatting to indicate already properly implemented; things that shouldn't inherit...

**Comment by ravignir** [comment]
Well, apparently it was not as monumental tasks as one would think, includes BNW, i omitted things that are correctly implemented, so the list only includes things that should be considered promotions:

Pathfinder:
Native Tongue

Persian Immortal:
Double Healing 

Jaguar:
Heals 25 after killing an unit
+33% bonus in forests/jungles (stacks)

Kris Swordsman:
Mystic Blade

Mohawk Warrior:
+33% bonus in forests/jungles (stacks)

Conquistador:
Embarkation Defense Bonus

Janissary:
+50 HP when kills an unit (only non barbarian units count) (kind of stacks with jaguar ability)
25% bonus when attacking

Minuteman:
Golden age points from victories (apparently completely missing in unciv - does not stack)

Sipahi:
No movement costs to pillage 

Winged Hussars:
Heavy Charge

Cossack:
Wounded bonus

Comnache Rider:
Full Moon Striker

Berber Cavalry:
Homeland Guardian
Desert Warrior

Hussar:
Flanking Bonus

Nau:
Exotic Cargo

Norwegian Ski Infantry:
Bonus/double movement in hills, snow, tundra

Hakkapeliitta
Great general bonus
Transfer movement to great general

Pracinha:
Golden age points from victories (apparently completely missing in unciv - does not stack)

Zero:
Bonus vs fighters 33%

**Comment by ravignir** [comment]
there is also a bug when you upgrade jaguar to janissary, it suddenly loses ability to heal 25 HP when killing barbs, but heals 75 HP when killing other units.

**Comment by ravignir** [comment]
one extra thing: Privateer's/Sea Beggar's ability to capture enemy ships should be a promotion

**Comment by SomeTroglodyte** [comment]
> includes BNW

I hope those are easily recognizable... And we should probably KISS and make all of these one specific "<unitname> ability" promotion re-using the icon. Ignore "not stack" as the Pracinha is as of yet only one sprite in FantasyHex.

**Comment by SomeTroglodyte** [comment]
| Unit | Van | G&K | BNW | ability | works | is promotion | should be |
|---|---|---|---|---|---|---|---|
| Pathfinder | [ ] | [ ] | [x] | Native Tongue | [ ] | [ ] | [ ] |
| Persian Immortal | [x] | [x] | [ ] | Double Healing | [x] | [ ] | [x] |
| Jaguar | [x] | [x] | [ ] | Heals 25 after killing an unit | [x] | [ ] | [x] |
| Jaguar | [x] | [x] | [ ] | +33% bonus in forests/jungles (stacks) | [x] | [ ] | [x] |
| Kris Swordsman | [ ] | [ ] | [x] | Mystic Blade | [ ] | [ ] | [ ] |
| Mohawk Warrior | [x] | [x] | [ ] | +33% bonus in forests/jungles (stacks) | [x] | [ ] | [x] |
| Conquistador | [x] | [x] | [ ] | Embarkation Defense Bonus | [x] | [ ] | [x] |
| Janissary | [x] | [x] | [ ] | +50 HP when kills an unit (only non barbarian units count) (kind of stacks with jaguar ability) | no barb filter | [ ] | [x] |
| Janissary | [x] | [x] | [ ] | 25% bonus when attacking | [x] | [ ] | [x] |
| Minuteman | [ ] | [ ] | [x] | Golden age points from victories (apparently completely missing in unciv - does not stack) | [ ] | [ ] | [ ] |
| Sipahi | [x] | [x] | [ ] | No movement costs to pillage | [x] | [ ] | [x] |
| Winged Hussar | [ ] | [ ] | [x] | Heavy Charge | [ ] | [ ] | [ ] |
| Cossack | [x] | [x] | [ ] | Wounded bonus | [x] | [ ] | [x] |
| Comanche Riders | [ ] | [ ] | [x] | Full Moon Striker | [ ] | [ ] | [ ] |
| Berber Cavalry | [ ] | [ ] | [x] | Homeland Guardian | [ ] | [ ] | [ ] |
| Berber Cavalry | [ ] | [ ] | [x] | Desert Warrior | [ ] | [ ] | [ ] |
| Hussar | [ ] | [x] | [ ] | Flanking Bonus | [x] | [ ] | [x] |
| Nau | [ ] | [ ] | [x] | Exotic Cargo | [ ] | [ ] | [ ] |
| Norwegian Ski Infantry | [x] | [x] | [ ] | Bonus/double movement in hills, snow, tundra | [x] | [ ] | [x] |
| Hakkapeliitta | [ ] | [x] | [ ] | Great general bonus | [x] | [ ] | [x] |
| Hakkapeliitta | [ ] | [x] | [ ] | Transfer movement to great general | [x] | [ ] | [x] |
| Pracinha | [ ] | [ ] | [x] | Golden age points from victories (apparently completely missing in unciv - does not stack) | [ ] | [ ] | [ ] |
| Zero | [x] | [x] | [ ] | Bonus vs fighters 33% | [x] | [ ] | [x] |

### comments
Minuteman Golden Age bonus is BNW only according to fandom, thus Unciv is so far correct - *but* fandom says ignore terrain cost is a promotion too, and that's from vanilla
Persian Immortal is implemented as +10, which is correct according to fandom, and the "double" misleading.
