### ISSUE TITLE
"[+1 Gold] <after discovering [Flight]>" applying globally instead of locally 

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6284]
This unique is causing bonuses to apply in all cities instead of just the one city where the Mughal Fort is being built. It's affecting both Android and Windows, on 3.19.13 and 3.19.14.

**Comment by SomeTroglodyte** [comment]
The standard issue template not only helps understanding (clear enough in this case), but testing...

**Comment by SpacedOutChicken** [comment]
For what it's worth, I saw in the UniqueType page that the "[stats]" unique does not have UniqueTarget.Building as an option. I think this means that when it's not applied to an improvement, it applies globally. Would adding UniqueTarget.Building to this unique type allow it to apply locally?

**Comment by yairm210** [comment]
No

**Comment by yairm210** [comment]
We want wonders to be able to add stats globally

**Comment by SomeTroglodyte** [comment]
I think type targets are for ruleset checking primarily, and unique application is up to code - which _could_ use the targets if it wished so - not that I know of any existing, but I have missed much of that development.

**Comment by SpacedOutChicken** [comment]
For what it's worth, my solution in DeCiv was to use "[stats] [in this city] <after discovering [tech]>". For wonders, doing "[stats] [in all cities]" would achieve the desired effect while being easier to understand.

**Comment by yairm210** [comment]
> I think type targets are for ruleset checking primarily, and unique application is up to code - which _could_ use the targets if it wished so - not that I know of any existing, but I have missed much of that development.

Correct! 
We want building uniques to be a direct superset of Global uniques, NOT to have special overrides

**Comment by SomeTroglodyte** [comment]
... which is exactly what the already linked PR does?
