### ISSUE TITLE
leap upgrade unit when intermediary technology is missing

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#629]
`gettingDirectUpgradeUnit` #586 makes it impossible to upgrade a Knight to a Modern Tank when Military Science has not been researched. 😕

**Comment by yairm210** [comment]
I see the problem, but this is a symptom of the incomplete tech tree we currently have... Normally units upgrade to units further along the tech tree
The current tech tree is incomplete, mainly because of the lack of air units, which is why we have the weird hybrid we have now...

**Comment by Am-per-Sand** [comment]
> Normally units upgrade to units further along the tech tree

Do they?
```
fun getUnitToUpgradeTo(): BaseUnit {
        var unit = baseUnit()

        // Go up the upgrade tree until you find the last one which is buildable
        while (unit.upgradesTo!=null && civInfo.tech.isResearched(unit.getDirectUpgradeUnit(civInfo).requiredTech!!))
            unit = unit.getDirectUpgradeUnit(civInfo)
return unit
```

How - if `&& civInfo.tech.isResearched` every time is checked? How is it possible to  upgrade a Knight to a Modern Tank without a technology for Cavalry?

**Comment by yairm210** [comment]
In order to make tanks you need to have military science, which is the tech for infantry...

**Comment by Am-per-Sand** [comment]
You are right that tech tree is incomplete.
But the reason for the case I have mentioned is that 

- now Modern Armour requires Plastics, which is independent from the military branch
- in vanilla Civ5 Modern Armour requires Lasers, which is in the military branch, so you can't research it without technologies for previous mounted and armoured units.

Well, I'll close it for now, it will solve automatically with the tech tree development...
