### ISSUE TITLE
The lastest Battletable is too wide and covers other tables.


### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#6293]
1. The lastest Battletable is too wide and covers other tables. i think the original table is a better one.
2. Adding white border on tileinfotable is a bad idea, becuase the minimap has a white border.

**Comment by yairm210** [comment]
1. This is intentional
2. So?

**Comment by SomeTroglodyte** [comment]
The battle table started annoying me, too. Maybe look into avoid displaying it when meaningless (e.g. ranged attacks over distances >> range, or city bombards city) and auto-hiding e.g. when scrolling away by more than x units?

**Comment by yairm210** [comment]
I'm closing this as 'not a problem'
