### ISSUE TITLE
Multiplayer Online

### ISSUE THREAD

**Issue by Luyann** [yairm210/UnCiv#630]
Make a multiplayer online feature, run by player made servers. It will take a lot of job, but i will let the idea fly.

**Comment by Luyann** [comment]
The game have a lot of things to do first, but when the game is stable, think about this

**Comment by yairm210** [comment]
Absolutely, this is one of the must often-requested features there are.
Also, it's the most technically difficult feature - I literally have no idea how I'm going to implement this.

**Comment by sulai** [comment]
Maybe multiplayer could be added in a step-by-step manner:
1. Hot seat: local game only, no networking involved
2. Play by mail (or whatever messenger you can send attachments with). It's basically almost a hot seat game, just you'll send the save game to your buddy/buddies.
3. Set up a server that basically sends/receives saved games.

This would allow for synchronized games, so it's played one player after another. Playing simultaneous is vastly more complicated, requiring not only real networking, but also solving conflicting simultaneous moves and problematic player actions, like quickly moving units just before a turn ends, and just when the new turn starts - effectively allowing them to "rush in" using two turns worth of movement.

So simultaneous networking is out of reach for now I think. Implementing Hot Seat will take a lot of effort, but far more doable.

**Comment by yairm210** [comment]
OKAY this is finally DONE
