### ISSUE TITLE
Now that the minimap doesn't show nation icon makes that distinguishing who owns the hex is a hard work

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#6310]
![YueR.jpg](https://user-images.githubusercontent.com/49801619/157353296-e8c5ecea-a95c-4fcf-9ac1-96cfe200fd10.jpg)
Look at the picture, now the icon border color is red, so the occupied hex color is, that makes the minimap looks very bad.
In original branch, the nation icon border color is different with the occupied hex color.

**Comment by SomeTroglodyte** [comment]
It's [this commit](https://github.com/yairm210/Unciv/commit/6a070358eba27eea7e7d793b3b569c023e049dd8). Think simply swapping inner and outer color would help?

**Comment by lishaoxia1985** [comment]
@SomeTroglodyte i think showing the nation icon is much better.

**Comment by yairm210** [comment]
The reason we don't show the icon is for performance reasons, as detailed in the commit

**Comment by yairm210** [comment]
A solution to this would be to add the nation icons on a separate layer, above the circle, agree completing all the circles

**Comment by yairm210** [comment]
This is solved with the new minimap.
