### ISSUE TITLE
Better handling of `Deprecated` warnings

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6328]
This is about compiler and IDE warnings again. The situation is good, but we have a huge amount of warnings on a clean build, all about deprecations. That's okay so far.

But here's an idea:

- All code to update save games goes into one module (implemented, maybe do a check pass to find functions not conforming to that pattern - or wait and see below)
- All checking code goes into a dedicated module (out of Ruleset)
- All implementations of deprecated items goes into another dedicated module.

Now, ideally ***all*** deprecation warnings for ***uses*** of deprecated stuff should only occur in those files; and the ***declarations***  should be easily distinguishable. Now we mark those three objects `@Suppress("DEPRECATION")` and a build output becomes much more readable...

Comments? Worth it?

**Comment by yairm210** [comment]
I for one think this is a non-issue, and not worth fussing over in any case

**Comment by SomeTroglodyte** [comment]
OK... but makes potentially helpful warnings hard to find???

**Comment by yairm210** [comment]
I think we can add a suppress deprecation on the uniquetype, since all unique deprecations are either A. known if warning or B. breaking if error

**Comment by SomeTroglodyte** [comment]
OK, the number isn't that bad anyways.
