### ISSUE TITLE
Unable to build/buy settlers

### ISSUE THREAD

**Issue by Bigrichman** [yairm210/Unciv#6335]
**Platform**
Android phone, 8.1.0 version

**Version**
Google play store,  3.19.15 game version

**Describe the bug**
Settler is no longer showing up in units I can build/buy.

**To Reproduce**
Idk how, just noticed it when I was in the modern era trying to get more oil and the AI is still producing settlers when I can't

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Settlers should show up in the unit list to be bought/built.

**Screenshots**

**Additional context**

**Comment by SomeTroglodyte** [comment]
Insufficient data. From that, I can only wildly guess and start a new game to the modern era - Settlers are offered. Another start in the atomic era - Settlers are offered. So?

**Comment by ravignir** [comment]
my guess is negative happiness (-10 or less)

**Comment by Bigrichman** [comment]
I'll try to finagle how to fix it and I'll get back with what I find out.

**Comment by Bigrichman** [comment]
Ok, I didn't know that under -10 happiness, Settlers wouldn't appear. Though thank you for a hint to what was happening.

**Comment by SomeTroglodyte** [comment]
> my guess is negative happiness (-10 or less)

Quite possible - `CannotBuildUnits` with `ConditionalBelowHappiness`... Maybe not remove a Unit from the list when the Unique suppressing it has any Conditional, but make it deep red and disabled???

**Comment by itanasi** [comment]
Perhaps using the disabled button and red text similar to all the other ways we block buildings/units
