### ISSUE TITLE
RFC: Empire Overview rework

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6353]
I'm re-doing the `EmpireOverviewScreen` with an extensible architecture.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/63000004/158287368-dadc6ba6-abd8-462e-a7e0-7d8a89c00d9a.png)
</details>

That's my current state, with the following workitem list:
* [x] Architecture using TabbedPager and Inheritance for individual pages
* [x] Switching pages keeps scroll and choices
* [x] Resize keeps scroll and choices
* [x] Re-open keeps choices (e.g. city sort)
* [x] Unit supply less intrusive in portrait
* [x] Key Tooltip missing (widget responsibility)
* [ ] Lighter background
* [x] Stats GPP vertically unaligned with other headers due to icon instead of font symbol (before too)
* [x] Score should have an Icon (before too)
* [x] Wrap Stats blocks (dynamic on screen resize)
* [x] Unit button should select even garrisoned units (before too)
* [x] Labels were meant left-aligned (before too)
* [x] GPP first header cell missing
* [x] Separator between tabbing header and content
* [x] Religion re-select from persisted omits padding
* [x] Bottom padding on content
* [x] Fix regression: Unit Supply right-align values
* [x] Test Unit Supply with _deficit_

This is to give Y'all a chance to comment, vote against solving individual items from the list, whatnot.

**Comment by yairm210** [comment]
So far looks good :)

**Comment by Ouaz** [comment]
By the way, maybe it's a silly question: in the Stats screen, there's all possible stats, but the Culture one, which is missing.

Is there a particular reason for it?

![stats_culture](https://user-images.githubusercontent.com/11946570/158434035-070888a1-ce01-4fef-93ed-17794aa95c67.png)

**Comment by SomeTroglodyte** [comment]
> but the Culture one, which is missing

Faith, too. I hear ya. This was originally meant to focus on architecture, not improving things, but it's getting beyond that anyway.

`@`All: I have trouble getting behind the reason `WorldMapHolder.setCenterPosition(unit, selectUnit = true)` fails to actually select garrisoned units. Someone remember some history of that `selectUnit` parameter and why skipping that `UnitTable.citySelected` call isn't enough? I'll find it by looking for the code that moves the city button and backtrack from there, but it might take quite some while.
