### ISSUE TITLE
Fallout can be created on city tiles, but cannot be removed

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6355]
**Platform**
Android 10

**Version**
3.19.16, Google Play

**Describe the bug**
Nukes can create fallout on city tiles, but it cannot be removed, because it's on city tile.

**Expected behavior**
Fallout isn't created on city tiles. 

**Screenshots**
![Screenshot_20220315-123902_UnCiv](https://user-images.githubusercontent.com/79529669/158370680-53e68ec1-2692-4aeb-a12c-a0811f9c5b92.jpg)

**Comment by SomeTroglodyte** [comment]
Still no reaction? Well, seems unclear how to reproduce. If you had a save from just before that fallout was created...
