### ISSUE TITLE
Different resource finding

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6357]
**Platform**
Android 10

**Version**
3.19.16, Google Play

**Describe the bug**
When founding a new resource from a tech, the notification doesn't show resources too far or on enemy land. But when you tap the resource in the overview, it shows resources from the whole map.

**To Reproduce**
1. Research a tech revealing a resource, see the number
2. Click on 'Overview' and 'Resources'
3. Tap the same resource's icon
4. The number is higher because it shows the resource from the whole map.

**Expected behavior**
The search from the overview screen searches only your and near unclaimed land.

**Screenshots**
![Screenshot_20220315-124316_UnCiv](https://user-images.githubusercontent.com/79529669/158440225-8a967200-4f0e-4018-a8df-3d6dab422187.jpg)
Here you can see aluminium in The Huns' land.

**Comment by yairm210** [comment]
Not a bug, this is expected behavior.
