### ISSUE TITLE
Request: (Collapse all / Expand all) toggle button for the city Stats drilldown

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#6373]
**Is your feature request related to a problem? Please describe.**
As a game progresses, the city stats drilldown column becomes very long, and it is very unconvenient to have to scroll the whole list to check particular items in the middle or at the bottom of the list. Or to close all stats one by one each time a save is loaded, to make easier to pick the desired one afterwards.

**Describe the solution you'd like**
Add a [Collapse all / Expand all] toggle button above the Stats drilldown. This way, it would be easier to access the desired city stats in two clicks.

![collapse_all_button](https://user-images.githubusercontent.com/11946570/159070621-e68eabdc-31fd-450f-a9e2-cd236043d399.png) ![expand_all_button](https://user-images.githubusercontent.com/11946570/159070656-65d3983a-96f3-44fb-9233-e8b879748d9d.png)

**Describe alternatives you've considered**
Make the collapsed Stats drilldown the default display, but:
- The list is short at the beginning of a game, so no need to collapse it.
- Some players may not like that. ^^

Thanks for reading!

**Comment by SomeTroglodyte** [comment]
... and when some are expanded some are collapsed we'd get _two_ buttons? :grin: You know, once I hoped we'd persist the open/close states of these across runs, then your usecase wouldn't weigh so much. But yes I get it...

But now you screenshotted it I notice the little discrepancy thanks to that aggressive Stat iconizing - the expanders without icon stand out a little. Do we have icons for "specialist buildings" as opposed to other buildings?

**Comment by Ouaz** [comment]
> ... and when some are expanded some are collapsed we'd get _two_ buttons? :grin:

Haha, I didn't think of that case. But actually... why not? haha :
![two_buttons_haha](https://user-images.githubusercontent.com/11946570/159142612-312bc2d9-cf42-43a3-a3a5-97ff07702599.png)

So, even if some stats are collapsed, and others expanded, the player chooses what he wants to do. :grin:

**Comment by Ouaz** [comment]
Tested it, works wondefully! Thank you!
