### ISSUE TITLE
Custom desktop font?

### ISSUE THREAD

**Issue by HAHH9527** [yairm210/Unciv#6376]
My friend complained to me that the font was not clear.
![image](https://user-images.githubusercontent.com/27153191/159105198-e1de4a3b-5e71-4a50-81ca-b830c7babf2e.png)
![image](https://user-images.githubusercontent.com/27153191/159105212-4ae0df8e-274c-420d-bf48-ea7636c06fd2.png)

So we can add a custom font setting in desktop.
Even if this setting is not displayed.

One of my idea:
```patch
Index: desktop/src/com/unciv/app/desktop/NativeFontDesktop.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/desktop/src/com/unciv/app/desktop/NativeFontDesktop.kt b/desktop/src/com/unciv/app/desktop/NativeFontDesktop.kt
--- a/desktop/src/com/unciv/app/desktop/NativeFontDesktop.kt	(revision fef993d5dca34f871f7a45a585cae7a73be77d6b)
+++ b/desktop/src/com/unciv/app/desktop/NativeFontDesktop.kt	(date 1647660638627)
@@ -1,6 +1,10 @@
 package com.unciv.app.desktop
 
+import com.badlogic.gdx.files.FileHandle
 import com.badlogic.gdx.graphics.Pixmap
+import com.unciv.JsonParser
+import com.unciv.logic.GameSaver
+import com.unciv.models.metadata.GameSettings
 import com.unciv.ui.utils.NativeFontImplementation
 import java.awt.*
 import java.awt.image.BufferedImage
@@ -8,7 +12,11 @@
 
 class NativeFontDesktop(private val size: Int) : NativeFontImplementation {
     private val font by lazy {
-        Font("", Font.PLAIN, size)
+        val settings = JsonParser().getFromJson(
+            GameSettings::class.java,
+            FileHandle(GameSaver.settingsFileName)
+        )
+        Font(settings.desktopFontFamily, Font.PLAIN, size)
     }
     private val metric by lazy {
         val bi = BufferedImage(1, 1, BufferedImage.TYPE_4BYTE_ABGR)
Index: core/src/com/unciv/models/metadata/GameSettings.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/models/metadata/GameSettings.kt b/core/src/com/unciv/models/metadata/GameSettings.kt
--- a/core/src/com/unciv/models/metadata/GameSettings.kt	(revision fef993d5dca34f871f7a45a585cae7a73be77d6b)
+++ b/core/src/com/unciv/models/metadata/GameSettings.kt	(date 1647660638622)
@@ -19,6 +19,7 @@
     var checkForDueUnits: Boolean = true
     var singleTapMove: Boolean = false
     var language: String = "English"
+    var desktopFontFamily: String = ""
     @Transient
     var locale: Locale? = null
     var resolution: String = "900x600" // Auto-detecting resolution was a BAD IDEA since it needs to be based on DPI AND resolution.
```

----------
## Preview font change by `黑体` with Simplified-Chinese
![image](https://user-images.githubusercontent.com/27153191/159105399-90a6d6aa-7c84-4015-9b1f-d7a7fbfdc354.png)
![image](https://user-images.githubusercontent.com/27153191/159105422-20ffc3e8-cf59-44c3-83b8-963bcccc42bd.png)

**Comment by HAHH9527** [comment]
Window maximized

## Font is default
![image](https://user-images.githubusercontent.com/27153191/159105599-f0fde39c-371c-4aaf-9f2f-c7cf478ea526.png)

## Font is `黑体`
![image](https://user-images.githubusercontent.com/27153191/159105560-00781f4a-a328-4b1b-8e77-27daca36ad9b.png)

**Comment by A7103** [comment]
waww LGTM, i need it !

**Comment by HAHH9527** [comment]
If you want get font list can use this code.
```java
jshell> import java.awt.GraphicsEnvironment;

jshell> GraphicsEnvironment grapEnv = GraphicsEnvironment.getLocalGraphicsEnvironment()
grapEnv ==> sun.awt.Win32GraphicsEnvironment@1c6b6478

jshell> String[] fontNameList = grapEnv.getAvailableFontFamilyNames();
fontNameList ==> String[149] { "Arial", "Arial Black", "Arial Narr ... , "���� Light", "����", "����" }

jshell> for(String fontName : fontNameList){
   ...>                  System.out.println(fontName);
   ...>         }
Arial
Arial Black
Arial Narrow
Bahnschrift
BERNIER Regular
Book Antiqua
Bookman Old Style
Bookshelf Symbol 7
Calibri
Calibri Light
Cambria
Cambria Math
Candara
Candara Light
...
```

**Comment by SKNM3** [comment]
Japanese translation has the same problem, I think it will fixes that as well.

**Comment by franciank** [comment]
感謝します！助かったwwww

**Comment by HAHH9527** [comment]
Other custom font issues
#3789
#2824
#2488

**Comment by SomeTroglodyte** [comment]
Pity Java awt is a relatively undesirable dependency here. Or are we already? Anybody find a `getAvailableFontFamilyNames` alternative in Gdx? And, "LGTM" - that's Lengiprotransmost, the company that built that Amur bridge, right? Also, that options page wouldn't be wrong in that PR if done as dropdown select including an entry for the current default.

**Comment by A7103** [comment]
> Pity Java awt is a relatively undesirable dependency here. Or are we already? Anybody find a `getAvailableFontFamilyNames` alternative in Gdx? And, "LGTM" - that's Lengiprotransmost, the company that built that Amur bridge, right? Also, that options page wouldn't be wrong in that PR if done as dropdown select including an entry for the current default.

@SomeTroglodyte  Not, `LGTM` mean Look Good To Me, usually used for code review. 


BTW (By The Way) Isn't the project using the awt library?
![image](https://user-images.githubusercontent.com/50233445/159118430-ea02afae-fb11-449c-84c8-2eed415acaa0.png)

**Comment by A7103** [comment]
I'm not a Kotlin developer, so my opinion on using awt is for **reference only**

**Comment by HAHH9527** [comment]
In windows, if system don't have `desktopFontFamily` value's font.
`Font(settings.desktopFontFamily, Font.PLAIN, size)` same as `Font("", Font.PLAIN, size)`

I don't have linux/macos desktop device, if anyone would like to test that would be much appreciated.

**Comment by SomeTroglodyte** [comment]
> `LGTM` mean Look Good To Me

:laughing:  If I can g00gle the bridge, I can duckduck that too

> BTW (By The Way), Isn't the project using the awt dependency ?

OK, **sorry**, didn't check. A second windowing/graphics library in parallel - well, probably that's why I remember it's not without effort (e.g. needing that headless define). But awt is actually the very core of NativeFontDesktop (and the Custom Save Location Selector, which is Swing)... So if we were to use `java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames`, then that should stay in the desktop specific code.

**Comment by SomeTroglodyte** [comment]
> if system don't have `desktopFontFamily` value's font.

Linux (Mint 20.3 = Ubuntu 20.04): `Font("~€§³anuahgnfdbxiasdgnfxiasnfysnhfdsadhfls 隶书 skdlnfxakluhm", Font.PLAIN, size)` works just fine.

**Comment by SomeTroglodyte** [comment]
If we give the users that power, they can shoot themselves in their knees:
![image](https://user-images.githubusercontent.com/63000004/159128917-718790fd-d77f-4f6e-9dbc-6ad9f584134a.png)
... there's even less readable fonts, of course (think WingDings).

**Comment by HAHH9527** [comment]
The user can choose the font that he thinks is the best.
Some questionable fonts, users actively avoid them.
We can add default font options `""`  (empty string).

**Comment by HAHH9527** [comment]
If users want choose less readable fonts, this should probably be their power too.

**Comment by SomeTroglodyte** [comment]
I see no way to change the font while the app is running. At least not one requiring less than 100 code lines... Can you? That screenie up there is from a branch that simply does `ToastPopup("You need to restart the game for this change to take effect.", previousScreen)`...

**Comment by SomeTroglodyte** [comment]
![image](https://user-images.githubusercontent.com/63000004/159132944-715375c5-5f01-4258-aacb-e976d785eda6.png)

Selecting "DancingScript-Regular" on an AVD... Problem: Slows startup down a little, and on older than Q there's no get-font-listing, so only "serif" / "sans-serif" / "mono" will do anything.

**Comment by SomeTroglodyte** [comment]
So - if you want to see that code, it's [here](https://github.com/SomeTroglodyte/Unciv/tree/Font-control) - you can use git->manage remotes, git fetch, checkout and then diff branches if you want, use and pilfer away, no attibution needed.

**Comment by HAHH9527** [comment]
@SomeTroglodyte 
But, I don't want change Android device's font. Not at all.
Android user can change system's font to change game's font.

![image](https://user-images.githubusercontent.com/27153191/159147185-192e153f-3878-4104-96ad-63588d026528.png)
![image](https://user-images.githubusercontent.com/27153191/159147219-b599c8cb-c39f-495c-8d6c-dbb900f7d16a.png)
![image](https://user-images.githubusercontent.com/27153191/159147289-3d54416f-7cdb-4066-a2bc-6e11fec52be3.png)

**Comment by SKNM3** [comment]
I tried and its really good,the text in game are much more easier to read,works fine on Windows and Ubuntu.

**Comment by SomeTroglodyte** [comment]
> change font in Android device, they can change system's font to change game's font

I admit I never had any impulse to do that or even look at the possibilities. Might still be nice to allow them the sans/serif alternative? That works w/ the OS out of the box. Nobody wants to run a game with a serif font while the system uses sans? OK, possibly. Also, LOS doesn't have font system control (only a 'Font size' in the settings), but the fonts are there nevertheless. (Yup I love the Mi hardware but definitely not their bloatware)

**Comment by HAHH9527** [comment]
In fact, most fonts don't have non-ASCII text.
![image](https://user-images.githubusercontent.com/27153191/159171268-5a01c61d-9b2f-442d-9117-e3397504a8c3.png)
![image](https://user-images.githubusercontent.com/27153191/159171252-f068822d-7f61-4247-a90f-9b0f701fec6e.png)

**Comment by HAHH9527** [comment]
On Android some font will generate an error.
![image](https://user-images.githubusercontent.com/27153191/159172383-026692bf-1198-46df-9542-77d39e3d22b3.png)

**Comment by SomeTroglodyte** [comment]
Well, your observations support the notion all that font enumeration for Android >= Q makes little sense, stay with serif/sans end of story. But was phun to try.

**Comment by HaneulCheong** [comment]
So...only for Desktop if I'm understanding everything correctly? Would still be glad to see this implemented since Windows default Korean font straight up *sucks*.

**Comment by HAHH9527** [comment]
> So...only for Desktop if I'm understanding everything correctly? Would still be glad to see this implemented since Windows default Korean font straight up _sucks_.

This support all desktop device and Android.
