### ISSUE TITLE
How can I gift units to City State?

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#6378]
Hi, everyone

In my match there are an enemy civilization in war against a City State that need military units.

I would like to gift them some units but I don't see any option.

Could you help me, please?

![Screenshot_2022-03-19-06-45-06-92_5b83b50424e447777d9855d9701553df.jpg](https://user-images.githubusercontent.com/77393537/159111188-732e1ade-cc6f-435c-b3ea-1d9342aff3a1.jpg)

**Comment by jahodovykolac** [comment]
I think you need to go with them on the city states' land, then a 'Gift unit' button will appear

**Comment by xlenstra** [comment]
Gameplay questions can best be asked in our discord, that will often lead to the quickest response. But what jahodovykolac has said is correct in this case.
