### ISSUE TITLE
DeCiv crashing unexpectedly

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6383]
Attached is the saved game. The game wouldn't let me copy the crash report.
[The.Patriots.-.85.turns.zip](https://github.com/yairm210/Unciv/files/8310615/The.Patriots.-.85.turns.zip)

HanuelChong has analyzed the situation here: https://github.com/SpacedOutChicken/DeCiv-Redux/issues/48

They believe that what's happening is that a city-state is attempting to gift a unit, but it has no unit it can give as a gift.

**Comment by HaneulCheong** [comment]
Yeah, basically, it seems the game crashes when no unit is available to be gifted by a city-state. Possible quick solution would be catching the `NoSuchElementException` and printing some sort of warning log while ignoring it in game. There could be a better solution, but this is what comes to my mind right now.

**Comment by SomeTroglodyte** [comment]
Nah, that .random() in line 98 of giveMilitaryUnitToPatron is the probable culprit. Make it a `.randomOrNull() ?: return`, done. But I'd probably make that multiline statement readable first.
