### ISSUE TITLE
Request: Better mod page for players who need translation

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6385]
Some players who don't know English well sometimes feel confused before downloading mods because they are not sure whether it's translated.
So how about adding something like this.
![image](https://user-images.githubusercontent.com/100454479/159160842-67af69e5-e4a6-4569-b599-962e284ed2a8.png)

**Comment by SomeTroglodyte** [comment]
That could be displayed _after_ installing the mod, before it's too much extra net round-trips. I had code a while ago that fetched files per-mod for splash screen-like images. That ran after (actually threaded parallel with dynamic queue prioritization) the query, but the whole thing was _way_ complicated and I forgot where the code went. You could watch the extra images slowly trickling in, and it could hit github's rate limit quickly. Fetching the completion percentages would be mostly the same, the files being smaller wouldn't make much difference.

**Comment by yairm210** [comment]
Can't think of a way of doing this without hitting the problems SoneTrog specified
