### ISSUE TITLE
His empire?

### ISSUE THREAD

**Issue by arbitrary-dev** [yairm210/Unciv#6388]
https://github.com/yairm210/Unciv/blob/22477c1ccb78e3516a8f232c659187fa344e16a8/android/assets/jsons/translations/English.properties#L4494

**Comment by xlenstra** [comment]
The `her` refers to Germany, which, according to wikipedia can be refered to as female:
https://en.wikipedia.org/wiki/Gender_in_English#Metaphorical_gender

**Comment by arbitrary-dev** [comment]
Damn liberals with their feminitives 😄

**Comment by arbitrary-dev** [comment]
Ok, it's in game as well.

![image](https://user-images.githubusercontent.com/6984946/159278111-25de2fd8-6b70-41b4-9b01-35eb47d1729b.png)
