### ISSUE TITLE
Ranged units not obeying line of sight or elevation rules

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#6395]
**Platform**
Windows 10 x64, Version 21H1, Up to date as of 3/20/2022

**Version**
Itch.io launcher. Version 3.19.18

**Describe the bug**
Ranged units can attack enemy targets without line of sight and from lower elevation when not adjacent to target. For example, Crossbowmen can attack through Forests to a unit on the other side of the Forest.

**To Reproduce**
1. Start a new game
2. Build ranged units
3. Attack enemy units through rough terrain

<details><summary>Saved game</summary>

```
[China -  234 turns.txt](https://github.com/yairm210/Unciv/files/8313366/China.-.234.turns.txt)

```
</details>

**Expected behavior**
Ranged units, other than Artillery or ones with the Indirect Fire promotion, may not fire through rough terrain such as Hills or Forests or to units at a higher elevation unless they are on an adjacent tile.

**Screenshots**
![01](https://user-images.githubusercontent.com/56904240/159211223-034e9f9f-b538-4617-a356-a93d426e0df0.jpg)
The Roman Trebuchet and Crossbowman should not be able to attack the Spanish Tercio which is fortified on a Hill. Both Roman units are on flat ground, while the Tercio is on higher elevation and there are Forests and Hills between them.

![02](https://user-images.githubusercontent.com/56904240/159211309-d82ce31d-d1c6-4924-807b-a8deb7e2f358.png)
With the map and scenario recreated in the Civ V WorldBuilder, the Roman Trebuchet cannot attack the Spanish Tercio. Note that the map has been rotated 90 degrees, since the hexes in Unciv are rotated 90 degrees compared to Civ V.

![03](https://user-images.githubusercontent.com/56904240/159211383-b92ee13f-2259-4843-912f-bd3598cd6ff3.png)
In the same Civ V custom map as before, the Roman Crossbowman also cannot attack the Spanish Tercio.

**Comment by xlenstra** [comment]
On the list of missing civ V features (#4679), as "Forests and jungles should block the view of hills but not of mountains"

**Comment by yairm210** [comment]
Closing as "appears in another PR"
