### ISSUE TITLE
Cut trade

### ISSUE THREAD

**Issue by thienan20** [yairm210/Unciv#6397]
I would like to cut trade with other countries without declear war

**Comment by yairm210** [comment]
That's not how trade works in civ v.

**Comment by thienan20** [comment]
But the ai countries can cut trade although the last turn of trade isn't end

Vào 0:21, Th 3, 22 thg 3, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by thienan20** [comment]
Are there any situation ai have to cut trade? Ex: run out of resources used
to trade

Vào 0:47, Th 3, 22 thg 3, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by yairm210** [comment]
You can also run out of resources, but that's not really a decision you make to cut the trade
Your resource city gets taken over for example
You *could* cheat this and build a different improvement over your resource, but again, there's no "stop trade" button
