### ISSUE TITLE
Place uranium 

### ISSUE THREAD

**Issue by thienan20** [yairm210/Unciv#6398]
In the latest version, i can only place uranium on marsh tile. I can't place uranium on any tile else. Why?
![Screenshot_20220321_215953](https://user-images.githubusercontent.com/102043829/159289689-effa02b4-8212-4063-afdb-b622e9cfb0fc.jpg)

**Comment by yairm210** [comment]
Untrue. Works on marsh, forest, tundra, and snow, as specified in civilopedia.

**Comment by thienan20** [comment]
Tiles and terrains can't place uranium i just found
Grassland + hill = can't
Plains + hill = can't
Desert + hill = can't
Grassland = can't (old version can)
Plains = can't (old version can)
Desert = can't (old version can)
These tiles and terrains need jungle or forest so we can place uranium on
these tiles and terrains.

Tiles and terrains can place uranium
Tundra = can
Tundra + hill = can
Tundra + forest = can
Tundra + hill + forest = can
Snow = can
Snow + hill = can
Marsh = can

Vào 0:21, Th 3, 22 thg 3, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by yairm210** [comment]
The question is, how does it work in Civ V.,

**Comment by thienan20** [comment]
Before I updated to latest version 3.19.16, uranium can be found on all
tiles, terrains except
Desert + oasis
Desert + flood plains
Fallout.



Vào 2:02, Th 3, 22 thg 3, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by yairm210** [comment]
That's not the question I asked though

**Comment by xlenstra** [comment]
If I can read the game files correctly, it can appear on the following terrains:
- Grass
- Plains
- Desert
- Tundra
- Snow
And on the following features:
- None
- Forest
- Jungle
- Marsh

**Comment by ravignir** [comment]
According to civ5 in-game civilopedia it can appear on pretty much eveything but oases and flood plains. BUT I don't recall finding uranium on any desert tile or any hill tile in my civ5 games ever.

**Comment by thienan20** [comment]
> According to civ5 in-game civilopedia it can appear on pretty much eveything but oases and flood plains. BUT I don't recall finding uranium on any desert tile or any hill tile in my civ5 games ever.

It can found on desert
![Uploading Screenshot_20220322_145003.jpg…]()

**Comment by yairm210** [comment]
Closing this for lack of interest
