### ISSUE TITLE
No game update to Russians?

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#6423]
There is no update in play market since March, 14, although has been 2 new versions posted here  
That's a pity

**Comment by Ouaz** [comment]
No, no, it's just 4.00 is bugged and won't be rolled out to everybody I think, and 4.00-patch1 is on Github only. :-)

For my part, I switched to Github release a while ago, and I manually update Unciv each time, because the development is pretty active anyway.

**Comment by yairm210** [comment]
4.0.0-patch1 is currently rolled out to 100% of users
Versions follow a rollout pattern, there's no special treatment of any language or geographical area
