### ISSUE TITLE
Some new Wonders

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#643]
I think we need to add some new Wonders...
- [x] Big Ben
- [x] Brandeburg Gate
- [ ] Mausoleum of Halicarnassus
- [ ] Statue of Zeus
- [ ] Temple of Artemis
- [ ] Petra
- [ ] Heroic Epic
- [ ] National Treasury

**Comment by Am-per-Sand** [comment]
- [ ] Petra

**Comment by Smashfanful** [comment]
@Am-per-Sand Thanks. Forgot about that

**Comment by yairm210** [comment]
Prora is a BNW wonder - removed

**Comment by Smashfanful** [comment]
@yairm210 Ok

**Comment by Am-per-Sand** [comment]
@yairm210 why is bnw wonder to be removed?

**Comment by yairm210** [comment]
Because I'm aiming unciv to be a G&K version before branching off to other versions, and we're very far from that now

**Comment by yairm210** [comment]
Moved to #663
