### ISSUE TITLE
The ruleset checker discards all warnings

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6430]
`Ruleset.checkModLinks` calls checkUniques with the `UniqueComplianceErrorSeverity` `RulesetInvariant` and `RulesetSpecific` levels, but never with `WarningOnly`. Thus, problems like: The mapUnitFilter parameter type doesn't _know_ that 'Barbarian' is a working MapUnit filter, and therefore there should be a warning _somewhere_; - are reported _nowhere_. Not console, not unit test `baseRulesetHasNoBugs`, not 'Mod Problems' tab of Options screen.

Ideas:
- Make `checkUniques` parameter `severityToReport` an `EnumSet<UniqueType.UniqueComplianceErrorSeverity>`, pass down and test `in` instead of ==, then ask for warnings on all more detailed calls. Con: Java lib, not very kotlin-y
- Remove and upgrade where used
- ??????

**Comment by SomeTroglodyte** [comment]
With all warnings forced to errors:
```
Carrier's unique "Can carry [2] [Aircraft] units" contains parameter Aircraft, which does not fit parameter type mapUnitFilter !
Floating Gardens's unique "Must be next to [Fresh water]" contains parameter Fresh water, which does not fit parameter type terrainFilter !
Garden's unique "Must be next to [Fresh water]" contains parameter Fresh water, which does not fit parameter type terrainFilter !
Forge's unique "[+15]% Production when constructing [Spaceship part] units [in this city]" contains parameter Spaceship part, which does not fit parameter type baseUnitFilter !
Alhambra's unique "All newly-trained [relevant] units [in this city] receive the [Drill I] promotion" contains parameter relevant, which does not fit parameter type baseUnitFilter !
Hubble Space Telescope's unique "[+25]% Production when constructing [Spaceship part] units [in this city]" contains parameter Spaceship part, which does not fit parameter type baseUnitFilter !
Spaceship Factory's unique "[+50]% Production when constructing [Spaceship part] units [in this city]" contains parameter Spaceship part, which does not fit parameter type baseUnitFilter !
Farm's unique "[+1 Food] from [Fresh water] tiles <after discovering [Civil Service]>" contains parameter Fresh water, which does not fit parameter type tileFilter !
Terrace farm's unique "[+1 Food] from [Fresh water] tiles <after discovering [Civil Service]>" contains parameter Fresh water, which does not fit parameter type tileFilter !
Holy Warriors's unique "May buy [{Military} {Land}] units with [Faith] for [2] times their normal Production cost <before the [Industrial era]>" contains parameter {Military} {Land}, which does not fit parameter type baseUnitFilter !
Sovereignty's unique "[+1 Gold] from all [Science] buildings" contains parameter Science, which does not fit parameter type buildingFilter !
Autocracy Complete's unique "May buy [Great Admiral] units for [1000] [Faith] [in all cities in which the majority religion is a major religion] at an increasing price ([500]) <starting from the [Industrial era]>" contains parameter Great Admiral, which does not fit parameter type baseUnitFilter !
Coastal Raider I's unique "Earn [33]% of the damage done to [City] units as [Gold]" contains parameter City, which does not fit parameter type mapUnitFilter !
Coastal Raider II's unique "Earn [33]% of the damage done to [City] units as [Gold]" contains parameter City, which does not fit parameter type mapUnitFilter !
Coastal Raider III's unique "Earn [33]% of the damage done to [City] units as [Gold]" contains parameter City, which does not fit parameter type mapUnitFilter !
Flight Deck I's unique "Can carry [1] extra [Aircraft] units" contains parameter Aircraft, which does not fit parameter type mapUnitFilter !
Flight Deck II's unique "Can carry [1] extra [Aircraft] units" contains parameter Aircraft, which does not fit parameter type mapUnitFilter !
Flight Deck III's unique "Can carry [1] extra [Aircraft] units" contains parameter Aircraft, which does not fit parameter type mapUnitFilter !
```
Some of that is surely missing knowledge in the `UniqueParameterType` definitions, but some seem actual json errors. Do Farms increase yield properly at Civil Service not just if they're next to an oasis or lake (which "Fresh water" tests), but also when bordering a River (which wouild need the "Fresh Water" test)...??????

**Comment by SomeTroglodyte** [comment]
As checklist, to make it easier to see which I treated in #6433 or #6438:

1. * [ ] Aircraft, which does not fit parameter type mapUnitFilter
2. * [ ] relevant, which does not fit parameter type baseUnitFilter
3. * [ ] Fresh water, which does not fit parameter type terrainFilter
4. * [ ] Spaceship part, which does not fit parameter type baseUnitFilter
5. * [ ] {Military} {Land}, which does not fit parameter type baseUnitFilter (that's only supported by mapUnitFilter)
6. * [ ] Science, which does not fit parameter type buildingFilter
7. * [ ] Great Admiral, which does not fit parameter type baseUnitFilter
8. * [ ] City, which does not fit parameter type mapUnitFilter

Nope, none had an effect on translations, none fixed yet. Some came close, I saw the problem right there, but I limited myself in that work to translations. So, please use the checklist when any of you fixes one.

In some cases, we should actually research whether the unique works properly, in some cases the way to go is obvious.
1. Filter works same as 4 - but what's wrong with UnitType that such a Unique was needed???
2. Fix UnitTypeFilter to use only _one_ knownValues set
3. This I already mentioned elsewhere. I suspect these do in fact not work quite properly.
4. The filter works via `return uniques.contains(filter)` - how to teach _that_ to UniqueParameterType???
5. ??? Tricky. Buying happens before the unit exists, so using mapUnitFilter would be perverse... Review matchesFilter function
6. ~~Review matchesFilter function~~ Filter scans all Stat names, so those should go into buildingFilter
7. Create the unit or remove the unique
8. Use combatantFilter instead

**Comment by yairm210** [comment]
Added in the latest version that *all* unique parameters are typechecked. We've improved the parameter checks as well, so we only allow e.g. unit filters if we see that that unit filter exists in some unit or promotion.
