### ISSUE TITLE
The options popup now sends a packet to G00gle

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6455]
1. `OptionsPopup` will call `getIpAddress` on opening (not on switching to the multiplayer tab), and thus send a packet to `8.8.8.8` which belongs to the big one. While the host is a DNS resolver and probably won't even listen on the used port, I'm not sure I am comfortable about this - mostly harmless, sure, but also avoidable.
2. The IP offered for copy and paste is the public one, and I'd prefer not to encourage people to expose their boxes to DOS attacks on _our_ super-hardened code. Also, it will react to connectivity, potentially giving the public in one second and the home net the next. This could also be done in a controlled manner preferring the home net but potentially listing the public address as well.
3. There might be people on boxes with zero IPv4 adresses configures, pure IPv6. What then? I'm pretty sure UncivServer can run on IPv6 selectively if needed or will listen on IPv6 too if any interface has one, and our client could connect to IPv6 notation, but - do we plan for this? Ensure the textbox will grow to accomodate the long-ish v6 notations? At the moment, it won't even accommodate '200.200.200.200' completely.

<details><summary>sample code:</summary>

```kotlin
    fun getIpAddress(preferLocal: Boolean = false): String? {
        return NetworkInterface.getNetworkInterfaces().asSequence()
            .filter { it.isUp && !it.isLoopback }
            .flatMap { networkInterface ->
                networkInterface.inetAddresses.asSequence()
                .map { address ->
                    val sort = (if (address is Inet4Address) 0 else 2) +
                            (if (networkInterface.isPointToPoint == preferLocal) 1 else 0)
                    address.hostAddress to sort
                }
            }.sortedBy { it.second }
            .map { it.first }
            .firstOrNull()
    }
```
</details>
... would produce identical results on my box without sending a packet, would easily allow preferring the home net, or offering a SelectBox to choose ...
<br/><br/>
Opinions???

**Comment by Mape6** [comment]
Regarding point 1: From my point of view, its buildin in Android that the packet went to 8.8.8.8. Unfortunately Google has hardcoded that DNS resolver for some reason. Especially if you enable Private DNS the quad8 is preffered. For me it would be interesting what was asked in the packet?

Another proposal: What about integrating cloud services as alternative to the hardcoded Dropbox? With options like GDrive, Dropbox, Nextcloud, OneDrive and so on the users could choose by them selfs where they want to store their MP games.
Especially for me Nextcloud would be very cool 😁

**Comment by yairm210** [comment]
> Regarding point 1: From my point of view, its buildin in Android that the packet went to 8.8.8.8. Unfortunately Google has hardcoded that DNS resolver for some reason. Especially if you enable Private DNS the quad8 is preffered. For me it would be interesting what was asked in the packet?
> 
> Another proposal: What about integrating cloud services as alternative to the hardcoded Dropbox? With options like GDrive, Dropbox, Nextcloud, OneDrive and so on the users could choose by them selfs where they want to store their MP games. Especially for me Nextcloud would be very cool 😁

Sounds ghastly to code. Granting *other people* access to *your* cloud account so you can play games together? I think you're vastly underestimating how long it would take to implement something like that

**Comment by yairm210** [comment]
It'll be different code for each provisos, different authentication processes, etc

**Comment by Mape6** [comment]
It would be much work to integrate different Cloud services, sure.
I would create a seperate Nextcloud account for my Unciv MP games. Thats not a big deal from my point of view.
As SomeTroglodyte already mentioned, it could be a security risk to make the Unciv server reachable from the internet. Thats why I thought about other web servers/services, that could serve the same features, that are needed by Unciv, that are already on the market and are reliable and security proofed.

**Comment by SomeTroglodyte** [comment]
... outdated
