### ISSUE TITLE
Options menu crashes Android S if...

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6456]
**Platform**
Android S AVD, "G00gle APIs" x86_64 revision 9 system image, wipe data before test (but don't forget to re-remove the horrible Assistant from the power button if you do that)

**Version**
current master

**To Reproduce**
Set resolution to x700 or less, turn on enable portrait, turn AVD to portrait, re-open Options.
Orientation changes to landscape and the options popup is re-rendered, then the game crashes. Logs show our crashhandlers are trying but failing, the process gets killed by the OS anyway. Last exception seen: RulesetCache.getVanillaRuleset() on an empty RulesetCache -> null pointer.

Tested on L, O, Q and R: All do that re-orientation thingy just fine.

Possible approaches:
- Hand the API level out of the activity context and tell BaseScreen to skip the re-orientation when it's 31 (S) or higher
- Remove re-orientation altogether (but not the portrait feature). Some option tabs are a bit ugly at minimum resolution and portrait, but bearable (and could be mitigated by fiddling, that Advanced tab has gotten an aesthetical nightmare anyway)

<br/>
Opinions???

**Comment by yairm210** [comment]
Why does orientation change to Landscape when opening Options?

**Comment by SomeTroglodyte** [comment]
Originally, I think, that was for some previous geometry of the options popup. Back then with insufficient space at low resolutions the thing became closer to unusable as it is now?

With an AVD, resolution set to 750x500, portrait enabled, and the forced reorientation code removed the worst page looks like this:
![image](https://user-images.githubusercontent.com/63000004/160879844-4b6f07f5-1b13-4d42-9b61-261a5dc9722b.png)
