### ISSUE TITLE
Strange observation concerning UncivServer

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6458]
**Platform**
You know I'm running Mint 20.3... This mentions running in the debugger, so
Android Studio about says:
```
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-37-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.tooltip.initialDelay=590
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)
Current Desktop: X-Cinnamon
```
Gradle Java is: `OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)`
Run Java is: `OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)`

**Version**
Current master

**Describe the bug**
I run the game in the Debugger as always, with unchanged run configuration. Large map, not huge, world wrap, max zoom setting = 2. One-click moves are off. Selecting a unit, selecting a destination, waiting for the move icon to show up and then clicking it takes around 6 (Six) seconds. Also, remember we have horrible kludges wrapping Char(Int) and Char.code calls (#6391, #6419, #6435).

Now remove UncivServer <details><summary>as follows:</summary>

```patch
Index: build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle.kts b/build.gradle.kts
--- a/build.gradle.kts	(revision 5ab44dd945af96a46e97e5a48e2ecec3f691c597)
+++ b/build.gradle.kts	(date 1648589933302)
@@ -70,13 +70,6 @@
         }
 
         "implementation"("com.github.MinnDevelopment:java-discord-rpc:v2.0.1")
-
-        // For server-side
-
-        "implementation"("io.ktor:ktor-server-core:1.6.8")
-        "implementation"("io.ktor:ktor-server-netty:1.6.8")
-        "implementation"("ch.qos.logback:logback-classic:1.2.5")
-        "implementation"("com.github.ajalt.clikt:clikt:3.4.0")
     }
 
 }
Index: core/src/com/unciv/ui/utils/KeyPressDispatcher.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/utils/KeyPressDispatcher.kt b/core/src/com/unciv/ui/utils/KeyPressDispatcher.kt
--- a/core/src/com/unciv/ui/utils/KeyPressDispatcher.kt	(revision 5ab44dd945af96a46e97e5a48e2ecec3f691c597)
+++ b/core/src/com/unciv/ui/utils/KeyPressDispatcher.kt	(date 1648589410441)
@@ -64,14 +64,14 @@
         val UNKNOWN = KeyCharAndCode(Input.Keys.UNKNOWN)
 
         // Kludges because we got crashes: java.lang.NoSuchMethodError: 'int kotlin.CharCodeKt.access$getCode$p(char)'  
-        fun Char.toCode() =
-            try { code } catch (ex: Throwable) { null }
-                ?: try { @Suppress("DEPRECATION") toInt() } catch (ex: Throwable) { null }
-                ?: 0
-        fun Int.makeChar() =
-            try { Char(this) } catch (ex: Throwable) { null }
-                ?: try { toChar() } catch (ex: Throwable) { null }
-                ?: Char.MIN_VALUE
+        fun Char.toCode() = this.code
+//            try { code } catch (ex: Throwable) { null }
+//                ?: try { @Suppress("DEPRECATION") toInt() } catch (ex: Throwable) { null }
+//                ?: 0
+        fun Int.makeChar() = Char(this)
+//            try { Char(this) } catch (ex: Throwable) { null }
+//                ?: try { toChar() } catch (ex: Throwable) { null }
+//                ?: Char.MIN_VALUE
 
         /** mini-factory for control codes - case insensitive */
         fun ctrl(letter: Char) = KeyCharAndCode((letter.toCode() and 31).makeChar(),0)
Index: desktop/src/com/unciv/app/desktop/UncivServer.kt
===================================================================
diff --git a/desktop/src/com/unciv/app/desktop/UncivServer.kt b/desktop/src/com/unciv/app/desktop/UncivServer.kt
deleted file mode 100644
--- a/desktop/src/com/unciv/app/desktop/UncivServer.kt	(revision 5ab44dd945af96a46e97e5a48e2ecec3f691c597)
+++ /dev/null	(revision 5ab44dd945af96a46e97e5a48e2ecec3f691c597)
@@ -1,76 +0,0 @@
-package com.unciv.app.desktop
-
-import com.github.ajalt.clikt.core.CliktCommand
-import com.github.ajalt.clikt.parameters.options.default
-import com.github.ajalt.clikt.parameters.options.option
-import com.github.ajalt.clikt.parameters.types.int
-import com.github.ajalt.clikt.parameters.types.restrictTo
-import io.ktor.application.*
-import io.ktor.response.*
-import io.ktor.routing.*
-import io.ktor.server.engine.*
-import io.ktor.server.netty.*
-import io.ktor.utils.io.jvm.javaio.*
-import kotlinx.coroutines.Dispatchers
-import kotlinx.coroutines.withContext
-import java.io.File
-
-
-internal object UncivServer {
-    @JvmStatic
-    fun main(args: Array<String>) = UncivServerRunner().main(args)
-}
-
-private class UncivServerRunner : CliktCommand() {
-    private val port by option(
-        "-p", "-port",
-        envvar = "UncivServerPort",
-        help = "Server port"
-    ).int().restrictTo(1024..49151).default(8080)
-
-    private val folder by option(
-        "-f", "-folder",
-        envvar = "UncivServerFolder",
-        help = "Multiplayer file's folder"
-    ).default("MultiplayerFiles")
-
-    override fun run() {
-        serverRun(port, folder)
-    }
-
-    private fun serverRun(serverPort: Int, fileFolderName: String) {
-        echo("Starting UncivServer for ${File(fileFolderName).absolutePath} on port $serverPort")
-        embeddedServer(Netty, port = serverPort) {
-            routing {
-                get("/isalive") {
-                    call.respondText("true")
-                }
-                put("/files/{fileName}") {
-                    val fileName = call.parameters["fileName"] ?: throw Exception("No fileName!")
-                    withContext(Dispatchers.IO) {
-                        val recievedBytes =
-                            call.request.receiveChannel().toInputStream().readAllBytes()
-                        val textString = String(recievedBytes)
-                        println("Recieved text: $textString")
-                        File(fileFolderName, fileName).writeText(textString)
-                    }
-                }
-                get("/files/{fileName}") {
-                    val fileName = call.parameters["fileName"] ?: throw Exception("No fileName!")
-                    println("Get file: $fileName")
-                    val file = File(fileFolderName, fileName)
-                    if (!file.exists()) throw Exception("File does not exist!")
-                    val fileText = file.readText()
-                    println("Text read: $fileText")
-                    call.respondText(fileText)
-                }
-                delete("/files/{fileName}") {
-                    val fileName = call.parameters["fileName"] ?: throw Exception("No fileName!")
-                    val file = File(fileFolderName, fileName)
-                    if (!file.exists()) throw Exception("File does not exist!")
-                    file.delete()
-                }
-            }
-        }.start(wait = true)
-    }
-}
\ No newline at end of file
```
</details>
... then *Build/clean* and re-run debug. Moving a unit is as snappy as ever (limited by my body not the game). Also note the patch deactivates the Char kludges and ctrl-O, ctrl-L, ctrl-S work just fine.

I suspected loader/statics issues when that Char issue came up, but that removing the Server also speeds up my game is a surprise.

**Comment by yairm210** [comment]
Huh
I can only assume that there's a background process that constantly polls the TCP port to see if any new messages have arrived, but that's odd since I thought the OS sends data to the listening port on an interrupt
No clue tbh

**Comment by SomeTroglodyte** [comment]
Don't you have these slow-downs too when running from Studio? If so, please try it. It's just a little change, the important bit is to clean-build or maybe even additionally 'invalidate caches'. And I don't think it's network - the server _is not running_ when we debug a normal game run. Combined with the Char quirk observation I'd say the double static main functions's somehow provoke some allergies in the class loader, and maybe the GC is affected. No, I don't understand that part of the kotlin/jvm system. Still, how can cutting essentially dead code show such extreme consequences?

**Comment by SomeTroglodyte** [comment]
OK:
- Modifying the signatures of class or function does not help
- Refactoring it into a separate package does not help
- Refactoring it into a separate _module_ does help perfectly

I got a branch that can:
- debug UncivServer
- debug Unciv _without_ the ctrl kludges, _no_ NoSuchMethodError, _no_ slowdown
- `./gradlew :server:dist` then `java -jar server/build/libs/UncivServer.jar` and connect to that using the home net IP from a debugger-run Unciv

Pity Studio does not allow two debuggers in parallel.

Anyone else in favour?

**Comment by SomeTroglodyte** [comment]
There - a PR just to show how far that could go. Not very polished. Still, the Char thing makes me suspect if we leave as is with the kludges, the weird effect behind all this will sooner or later affect some other standard library functionality.

**Comment by SomeTroglodyte** [comment]
Any input on this?
- Who is currently still running Unciv at times in the Studio debugger, or at least set up to do so?
- Can those devs please confirm the crass slowdowns whenever WorldScreen updates (the debugger itself is also markedly more sluggish on tooltips or watches or alt-F8 evaluations)? Or state clearly they _can_ debug at normal speeds?
- Those that _have_ the slowdowns: Please confirm that just checking the #6468 branch out and running a clean build solves these slowdowns?

@yairm210 , @xlenstra , @SimonCeder , @itanasi , @will-ca , @GGGuenni , @HaneulCheong ? Anybody?

Because if it isn't just me, I say we have proof of a serious underlying architecture problem, possibly triggered by having two main() functions in one project, and then must go either the #6468 route or try whether making the server a non-main part of Unciv itself (think Options-Multiplayer: 'Start server' button, 'Server status' label, 'Start server automatically' checkbox) also alleviates the issues.

**Comment by itanasi** [comment]
Sorry, evenings haven't really been free unfortunately

**Comment by GGGuenni** [comment]
> Large map, world wrap, max zoom setting = 2. One-click moves are off.

For me, starting Unciv on the master branch in the debugger with these settings does not give me a very noticeable slowdown.
Running on a Pixel 4 Api24 AVD with 1536 MB RAM assigned.

Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry: external.system.auto.import.disabled=true, ide.instant.shutdown=false

**Comment by SomeTroglodyte** [comment]
Thanks, I meant of course a 'desktop' run config, AVD's are fine for me, too. (That's the thing - _normally_ debugging using desktop should be quite a bit more fluid). Btw - that '11.0.11+9...' is the JRE bundled with Studio. Gradle and run configs can choose other JRE/JDK, and that might be significant, though I have tried most permutations of all currently available Linux x64 JDK's on Adoptium to no avail.
And 'haven't really been free unfortunately' - :+1: I should be prioritizing RL too! That I escape here is a weakness.

**Comment by GGGuenni** [comment]
Just tested with a 'desktop' run config and doesn't seem too slow as well. ~500ms each for selecting and move icon showing up when playing on huge world wrap. Normal when playing on large world wrap.

**Comment by SomeTroglodyte** [comment]
So no repro on Windoze. Fits the general impression that only Linux users had the Char crashes, too. The JRE it runs under is an 11 level as well, I assume.
![image](https://user-images.githubusercontent.com/63000004/161424332-df3829a5-c701-46e2-ba67-e4628d31d7a8.png)
