### ISSUE TITLE
Add barbarian encampments

### ISSUE THREAD

**Issue by Uncivman** [yairm210/UnCiv#646]
This tribes or clans can either join your empire peacefully or wage war with you 
But they only have one capital and they are natives to the map

**Comment by Smashfanful** [comment]
They could be superfluous, as this project is supposed to be the mobile version of Civilization V, and there should be city-states, not tribes/clans.

**Comment by Am-per-Sand** [comment]
Barbarians have different programme in each issue of Civ games.

Do you mean [Barbarian encampents](https://civilization.fandom.com/wiki/Barbarian_(Civ5)#Behavior_and_Activities) from Civ5?

**Comment by Uncivman** [comment]
Not exactly i mean but that would be nice

**Comment by yairm210** [comment]
As said above, in Civ V there are no "small tribes", but there are barbarian encampments.
Changing the issue name to reflect that.
