### ISSUE TITLE
Can't enter game

### ISSUE THREAD

**Issue by Etonaware** [yairm210/Unciv#6465]
**Platform**
Operating system type: 11
major version: 4 maybe?
architecture: 64 bit/aarch64

**Version**
4.0.0-patch1

**Describe the bug**
I found this game on playstore then downloaded it, but after entering the game I can't press anything then the game exits by itself

**Comment by yairm210** [comment]
4.0.2

**Comment by Etonaware** [comment]
> 4.0.2

I've updated unciv to version 4.0.2
but still can't enter the game
I tried several ways:

~Clear cache
~Clear app data
~Restart phone

**Comment by yairm210** [comment]
Closing as 'unactionable' - there's no way of telling what's going on so we can't solve the problem, if it even still exists
