### ISSUE TITLE
Add "how to build and serve the wiki locally" to the wiki

### ISSUE THREAD

**Issue by HaneulCheong** [yairm210/Unciv#6467]
**Is your feature request related to a problem? Please describe.**
It seems [Python Markdown](https://python-markdown.github.io/) (the backend of [MkDocs](https://www.mkdocs.org/), the engine our wiki is using) has rather strict syntax rules compared to other markdown rendering engines such as GitHub file viewer. Problem is, [the current wiki](https://yairm210.github.io/Unciv/) is remotely served through GitHub actions as far as I can tell and thus it's really hard to predict the actual webpage outcome, which presumably lead to broken links, lists, tables and all sorts of mess previously. Hopefully #6453 could fix most of them for now, but we need a more fundamental solution.

**Describe the solution you'd like**
Add a chapter or even a page describing how to build and serve the wiki locally somewhere in the wiki so people can preview their additions.

**Describe alternatives you've considered**
-   Rejecting MkDocs and embracing the default GitHub wiki again?
-   Include an actual Python venv with the mkdocs package installed in the repo?
-   I don't know just adding a chapter or a page seems easier, at least for me.

**Additional context**
-   I opened this issue since I thought this should probably be consulted with other collaborators.
-   This should be useful if we decide to do this: https://www.mkdocs.org/getting-started/
-   Also, here's how the wiki looks like as of 4.0.2:
    ![The current broken wiki](https://user-images.githubusercontent.com/96629218/160676590-26a594b1-9afe-44ab-b526-4c2a7d449bd5.png)

**Comment by SomeTroglodyte** [comment]
Go on, teach _me_ how to get wiki changes previewed (because I have _no_ idea) and then I can answer that question :smile_cat:  - in other words good idea but I wouldn't be able to write it.

**Comment by yairm210** [comment]
You can run the mkdocs locally, I've done this and it works, they have documentation, I'll try and find it

**Comment by HaneulCheong** [comment]
> * This should be useful if we decide to do this: https://www.mkdocs.org/getting-started/

I followed this guide.

**Comment by HaneulCheong** [comment]
Stale
