### ISSUE TITLE
Unciv server does not work with Android app of Unciv

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#6469]
**Platform**
Unciv server runs on a Raspi in my home network
Unciv app runs on Android 12 (Pixel 4a) and is connect to Wifi within the same IP network as the Raspi.
Unciv app runs on Windows 10 and is connect to LAN within the same IP network as the Raspi and WiFi

**Version**
4.0.2

**Describe the bug**
I started the Unciv server on the raspi with Java 11.
On Windows 10: I did the connection check and it was successful. I can create a new game and play as usual with my own Unciv server.
On Android: I did the connection check and it fails.
I entered the same server IP on Windows and Android. But unfortunately Android can not connect to the server.

I dont have any idea how to get the error messages from Unciv app on Android. Any suggestion?

**Comment by SomeTroglodyte** [comment]
> Any suggestion

I mentioned that somewhere earlier these past months... You need root or _at least_ working debug access on the device and adb connectivity from a PC. Install MatLog Libre from FDroid (com.pluscubed.matloglibre), and it will tell you what adb command you need to execute. Then go looking for the needle in the heystack - Android spends more time logging than doing meaningful stuff - with luck filtering on 'Unciv' does it.

No, in this case you won't see the relevant info with the 'Unciv' filter:
`System.out I Cleartext http traffic to 192.168.x.x not permitted`

So, _sabotage_ again.
