### ISSUE TITLE
City names with prefixes should be translatable

### ISSUE THREAD

**Issue by HaneulCheong** [yairm210/Unciv#6474]
**Is your feature request related to a problem? Please describe.**
City names with (what I call) overflow prefixes such as "New Rome" cannot be translated as of now, even after the rework done in 4.0.3.

**Describe the solution you'd like**
There are several different ways to implement this feature, which is why I thought the whole thing should be consulted with other collaborators.

For instance we could implement a new internal name format for city names such as:

-   `"{New }{Rome}"` (New&nbsp; = New&nbsp;)
    -   Straight forward to translators
    -   Ugly
-   `"{New}{Rome}"` (New = New&nbsp;)
    -   Pretty
    -   Confusing to translators
-   `"{New} {Rome}"` (New = New)
    -   Straight forward to everybody
    -   Cannot accommodate languages without spaces

**Describe alternatives you've considered**
We can always scrap the whole prefix mechanic and fallback to the Civ 5's way of dealing this: borrowing city names from absent nations if all names are consumed.

**Additional context**
This bug thingy was found in #6439.

**Comment by yairm210** [comment]
Alternate city naming:
New [cityName] = 
Neo [cityName] = 

That way we can accomodate languages without spaces AND have nice translations

**Comment by HaneulCheong** [comment]
> New [cityName] =
> Neo [cityName] =

So this is the language of Gods I guess... Jokes aside, I'll do some tests then bring the result soon.

**Comment by yairm210** [comment]
SomeTrog is right, I didn't think that through, it's actually not a great idea

**Comment by SomeTroglodyte** [comment]
No, all ideas are good while we're missing the 'eureka' moment...

**Comment by yairm210** [comment]
Been possible for a while with nested translations
