### ISSUE TITLE
Can submarines not attack other submarines?

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#648]
One of the users left this in a review, and it looks like he's serious

**Comment by ninjatao** [comment]
That's strange. Submarines have "Can attack submarines" just like destroyers. If a destroyer can attack submarine, there seems no reason why a submarine cannot.
Anyway I will try.

**Comment by yairm210** [comment]
He says that destroyers can't either

**Comment by yairm210** [comment]
Solved by @ninjatao
