### ISSUE TITLE
Distribute idle workers evenly throughout the country

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#6481]
I've noticed that when there's nothing for my workers to do, they all just stop, often all in one part of the country.
It would be more useful if idle workers distance themselves from other workers so that when there is something to do, such as a new resource is discovered or the territory expands, there will already be a worker close by that can respond quickly.

**Comment by xlenstra** [comment]
Easiest solution would be to try to send all of them to an empty city center probably

**Comment by yairm210** [comment]
That's what workers do now, they try and find an empty city center if they really have nothing else to do
