### ISSUE TITLE
Defence goddess belief doesn't work

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#6488]
**Platform**
Android 12

**Version**
Download here 4.0.3

**Describe the bug**
I choose the pantheon belief "defence goddess" (+30% damage of city when attack), but it is not displayed in attack overview (is it really work?). It can be seen in attached screenshot

![Screenshot_20220404-233430](https://user-images.githubusercontent.com/19261897/161628762-af0a01c3-f5af-4ad0-805a-92f95867df7b.png)

**Comment by yairm210** [comment]
What mods are you using?
