### ISSUE TITLE
Cloudflare Blocks the default Java 8 User Agent of Unciv, so Use a Custom One

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6490]
**Platform**
In any platform that uses Java 8
Windows (since it ships with Java 8 by default)
Linux & Mac (if Uses Java 8)
Android 11 was unaffected

If Java 11 or more is manually installed in Windows, then this doesn’t occur. A behaviour observed by @ravignir.

**Version**
4.0.3

**Describe the bug**
Cloudflare, a mojor web security service that almost all of the major sites on the Internet uses, by default blocks the `User-Agent` starting with `Java/1.` for some reason.
Since windows reports `User-Agent: Java/1.X.X_XXX` it blocks all incoming requests from Windows PCs too.
It happens even if the securuty is disabled for a website (lol) and cannot be fixed easily. I personal tried to fix this for `https://uncivserver.xyz` and all my attempts for this has failed. But I could at least find the root of the problem.

Since Cloudflare blocks it many other Antivirus or Firewall or Security services might block this also. Cause many doesn’t think that Java 8 is secure.

Thus I suggest that any requests from Unciv uses a custom user agent `Unciv/${version_number}` in any request made from Unciv so that the issue doesn’t persist. Such User Agents are completely fine on Cloudflare's site.

**To Reproduce**
```sh
> curl -A "Unciv/4.0.4-future" -X GET https://uncivserver.xyz/isalive
true
> curl -A "Java/2." -X GET https://uncivserver.xyz/isalive
true
> curl -A "Java/1." -X GET https://uncivserver.xyz/isalive
error code: 1010
> curl -A "Java/1.8.0_232" -X GET https://uncivserver.xyz/isalive
error code: 1010
```

Note that `1.8.0_232` is the version packed with Unciv in Windows. In reality any UA that starts with `Java/1.` is blocked. I even tried Disabling Security, Adding firewall rules to strictly allow any UA with `Java` in it any many more stuff but nothing worked.

**Comment by touhidurrr** [comment]
**Edit:** I fixed this by Using a custom header modification rule on Server Side so the `curl` requests Won't reproduce the issue anymore. But I still think that this need to be resolved by custom headers.

**Comment by yairm210** [comment]
This sounds like a cloudflare problem to be honest

**Comment by touhidurrr** [comment]
> This sounds like a cloudflare problem to be honest

But if Unciv sends a Header by default anyways. Why not use a custom one?

**Comment by SomeTroglodyte** [comment]
> sounds like a cloudflare problem

Obviously, but - the bit where you could strip user agent server-side - that one proves is't not generally clusterflare DOS protection, in which case you server wouldn't even see anything, but that cloudfog service framework you're using?

> It looks better

To that I can say aye. And since we haven't got enough easter eggs, hide something really weird in there...

**Comment by touhidurrr** [comment]
> Obviously, but - the bit where you could strip user agent server-side - that one proves is't not generally clusterflare DOS protection

It's not like that. I didn’t remove it from server side but used an **HTTP Request Header Modification rule** which kicks in much prior to DDOS I think. Cloudflare has orders for which services. I can't remember the exact order though and will put it when I find it somewhere. As for now see this screenshot.

![Screenshot_2022-04-06-20-03-13-77_d073e7407281f7a2d9df7c9f755e6603](https://user-images.githubusercontent.com/46617994/161992939-8b867ade-b959-4458-9a4f-417040d62b45.jpg)
