### ISSUE TITLE
Multiplayer turn notifier service crashes too frequently

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6502]
**Platform**
Android 11

**Version**
4.0.3 - 4.0.4

**Describe the bug**
It crashes like 10 times per day when playing frequently.
The screenshot was taken when I was talking about this in `#developers` chat. Ironically it crashed when I was starting to type about it.

**Screenshots**
![Screenshot_2022-04-07-22-45-57-97_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/46617994/162255693-bfbd5ca8-ed69-4c09-9d7d-d94168946b6f.jpg)

**StackTrace**
```kt
kotlin.UninitializedPropertyAccessException: lateinit property Current has not been initialized
	at com.unciv.UncivGame$Companion.getCurrent(UncivGame.kt:222)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.<init>(Multiplayer.kt:67)
	at com.unciv.app.MultiplayerTurnCheckWorker.doWork(MultiplayerTurnCheckWorker.kt:252)
	at androidx.work.Worker$1.run(Worker.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by SomeTroglodyte** [comment]
My uneducated guess - that worker may be active when the Unciv game itself is not initialized, so accessing the settings in the OnlineMultiplayer constructor getting to be a problem is not that surprising. How about replacing Kultiplayer.kt line 67 with `        val settings = if (UncivGame.isCurrentInitialized()) UncivGame.Current.settings
            else GameSettings.getSettingsForPlatformLaunchers(Gdx.files.localStoragePath)
`?
That's not really clean (Gdx.files.localStoragePath guarantees a path separator at the end and getSettingsForPlatformLaunchers adds another one, and who am I to know whether Gdx.files is initialized in that context when UncivGame isn't), and untested (haven't got the how) - but maybe the experts can build on the idea?
