### ISSUE TITLE
Improvement-building unique reorg

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#6509]
Problem: improvement building is kind of messy.

In the base game we have 4 types of improvement-constructing units:
- Slowly build all land improvements - workers - "Can build [Land] improvements on tiles"
- Slowly build specific improvement - legion - "Can build [Fort] improvements on tiles"
- Instantly build & consume for water improvements - work boats - "May create improvements on water resources"
- Instantly build and consume for unique improvement - great people - "Can construct [Manufactory]"

Restrictions:
 - Separation between slow- and instant-build improvements to disallow workers from constructing e.g. Manufactory - currently done by having turnsToImprovement be 0

Problems:
- Work boats unique is very restrictive
- Modders confused why "Can build [Water] improvements on tiles" isn't working (it's because they have turnsToImprovement=0, which is changeable)
- "Can build" vs "Can construct" - unclear that one consumes the unit

Question: How do Samurai construct fishing boats in Civ V? If it's either "instantaneous by consuming" or "slowly" then we have a built in solution, but if it's "instantaneously no consuming" then we have a problem.

Suggestion:
 - "Can construct []" -> "Can be consumed to instantly build [] improvements", this would fit both fishing boats AND great people

**Comment by yairm210** [comment]
Using the "by consuming this unit" unique is a great idea! But the "instantly" doesn't feel like a conditional to me, since it only changes one unique, sounds like we should just have 2 uniques

**Comment by SomeTroglodyte** [comment]
I always disliked the abuse of that turnsToImprovement==0 as behavioral flag. Then there is the tidbit that TileImprovement has several semantically quite different kinds of instances - those that will leave something in TileInfo.improvement, those that will leave something in TileInfo.roadStatus, some remove stuff from one of three fields of TileInfo, and some go into TileInfo.improvement but should only be placed there by a map generator... Did I get all distinctions? No. Fallout is yet slightly different.

Then imagine the eco warrior mod needing a unit that can plant trees... Or a unit that removes fallout instantly via sacrifice. Or a unit that builds a road instantly, no sacrifice, it only loses all movement. Or a unit that can build an Academy in 20 turns or instantly through sacrifice, free to choose. All possible IMHO with not too radical changes.

We need only 1 or 2 uniques for all that. Whether turns/sacrifice is distinguished via 2 UniqueTypes, via parameter or via conditional does not make much of a difference for code quality or maintainability methinks. 2 uniques would leave a bit more freedom for nice wording (build/construct I agree is unclear. consuming? sacrifice? settle down? convert into? death by consumption already exists...)

I think a _clear_ and _immediate_ categorization that will e.g. answer in just 1 bytecode primitive whether something goes in TileInfo.improvement or not would be the first thing to think about. Decouple turnsToImprovement so it means _only_ turn count and nothing more (meaning when a unit is allowed to build it without sacrifice it would be created instantly but the unit would lose movement - OK, that's another hidden hardcoded behaviour difference, so maybe just forbid it).

What the unit is allowed to build should be exclusively a matter of its improvementFilter parameter. It could learn to allow a list to prettify certain mods, but repeated uniques would work too. But to support the Vanilla Worker it would need the capability to filter on all the Improvements the Worker normally has while excluding what normally are Great Improvements, ruins, barb camps, etc. - _without_ looking at turnsToImprovement. Idea - improvement categories as uniques on the improvement side, like already existing as "Great Improvement". Technically no problem, just what name would we use? Or - a non-unique field, maybe a type enum, that could also serve to eliminate all those `Constants.remove + lastTerrain.name` or `startsWith(Constants.remove)`?

> doesn't show them ("<>")

Remember github does html-polluted markdown, so if your <> disappear `&lt;&gt;` would work too - like this: &lt;&gt; (you can see the difference if you are allowed to edit my post - or DIY)
