### ISSUE TITLE
Clicking on a City-state name in CS menu the focus goes to CS on a map

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#6510]
I think it will be very helpfull, because, for example, it sometimes wants to give a gold to CS, but if it very far away from you, there is a big chance that smbdy would conquer it, and your gift would be useless, and many other reasons

**Comment by xlenstra** [comment]
Alternatively, the original had a button 'go to city-state on map' in the diplomacy overview, which would close the overview and scroll the world map to that location

**Comment by yairm210** [comment]
I think a "go to capital" button could be added to all nations, not just city states

**Comment by Timur512** [comment]
> Alternatively, the original had a button 'go to city-state on map' in the diplomacy overview, which would close the overview and scroll the world map to that location

It should be so





> I think a "go to capital" button could be added to all nations, not just city states

It also my be added

And I wanted to add, when CS is being defeated, a notification appears, but it is not clickable, and I always want to see where those  CS was located. So, it will be good to make clickable this notification
