### ISSUE TITLE
Unit Grouping

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6522]
On Play Store I say people complaining the game being slow at late game because you have to move each unit manually and you cannot send moving commands like attack that unit together or move to that location together etc.

**My suggestion is (as I saw on FreeCiv + my own ideas):**

1. When an unit is tapped another option **select** would appear
2. Pressing select, some other options would apper, they are
    2.0: *Select Manually*
    2.1: *All units of this type*
    2.2: *All units within this city* (if in a owned city)
    2.3: *All units outside of cities* (if not in a owned city)
    2.4: *All Melee Units*
    2.5: *All Ranged Units*
    2.6: *All worker Units*
    2.7: *All Units* (Yes all Units that you own)

*Behaviour or **Select Manually**:*
Lets you select the units you want manually. When this option is selected a little button **End Selection** & **Add Selection** appears on the bottom left corner of the map.

**Add Selection** lets you see the selection menu options again to select more units.

**End Selection** will keep all the units you have Selected highlighted so that you can move them together in a group like a single unit.

The client will remember unit groups. And what any unit group was tasked with doing.

That's all.

**Comment by SomeTroglodyte** [comment]
Multi-select exists, but what you desire sounds like - 100 to 500 man-hours of work.

**Comment by touhidurrr** [comment]
> Multi-select exists, but what you desir sounds like - 100 to 500 man-hours of work.

I don’t Fthink so.
For now just simple loop can be implemented. Like for selection of ranged units:
```py
selection_group = []
for unit in unitsList:
  if unit.type == 'ranged':
    selection_group.add(unit)
```
And sending commands to units can be as simple as this:
```py
for unit in selection_group:
  do_work(unit)
```

**Note:** Can't write Kotlin myself.

**Comment by touhidurrr** [comment]
> Multi-select exists
It exists in Unciv!!!
Is it also for Android??

**Comment by touhidurrr** [comment]
Can I get some attention in this Pull Request? One of the main reasons Unciv feels boring is because in late game you have too many stuff to do every turn. Which is an issue.
I used to play FreeCiv and this feature of the game made managing units much less time consuming. Can maintainers reconsider implementing this feature for this reason?

**Comment by tuvus** [comment]
I have looked at multi-select a little. It is a good foundation, however the problem is how should the units actually act?

My idea is that the player would click on a tile and create an move, attack move, defend command. This however, requires extra methods in unit automation that aren't simple. 
These commands are really important for a higher level AI that I have been looking into though.

**Comment by touhidurrr** [comment]
@tuvus maybe play freeciv a little and take some inspiration from there. In case if you have not played it yet.

**Comment by touhidurrr** [comment]
Maybe for beginners, a simple logic would be, not thinking of groups as groups Internally and purely visual.
After you command a group to do something, it can just be a loop that tried to command each unit to do the same thing. That's all.
