### ISSUE TITLE
Replacement text for uniques not showing up in nation picking screen

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#6527]
When choosing which civilization to play, the replacementTextForUniques is not kicking in. It's still working in Civilopedia and the Tech screen, but not the nation picking screen.

This can be seen by playing the latest version of RekMOD and choosing Canada. The Combat Engineer has the replacement text of "Can construct Roads, Railroads, Forts and remove: Forest, Marsh and Jungle tiles", but this isn't showing up on the picker screen.
![Screenshot (97)](https://user-images.githubusercontent.com/58439827/162655408-fb19a3a8-1826-4297-9564-c88d19f4c7b0.png)

**Comment by zhan313** [comment]
The replacement unique text only work for nation iirc

**Comment by SpacedOutChicken** [comment]
There is a replacement text for national uniques, which is showing up everywhere just fine. There are also replacement texts for units and buildings, and I think those replacement texts should also show up everywhere.

**Comment by SpacedOutChicken** [comment]
In the tech screen in Civilopedia, you can see that the uniques have been replaced. 
![Screenshot_20220410-220045_UnCiv](https://user-images.githubusercontent.com/58439827/162668055-b008048b-3de3-4cf0-9fd4-1531a0d1286f.jpg)
