### ISSUE TITLE
Air Recon

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6528]
All Fighter type units (Triplane, Fighter/Zero, Jet Fighter) should have the Air Recon ability that gives 6 tile vision.

**Comment by SpacedOutChicken** [comment]
They do all have the air recon ability. The Fighter unit type has it built in. It just doesn't show up in Civilopedia.

**Comment by xlenstra** [comment]
It's currently implemented as two uniques, `["[+4] Sight", "Can see over obstacles"]`, but combined those should have the same effect as the Air Recon ability.
