### ISSUE TITLE
Reset Movement when Captured

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6534]
Currently when a unit is Captured and it was moving to a target tile, it maintains that Movement order.

Perhaps be helpful to cancel that Movement Order upon capture

**Comment by itanasi** [comment]
Come to think of it, perhaps we should stop all actions? Cancel Fortify/Sleep. Stop Automation/Exploration. Can't think of an action that should continue. Right now if doing a Tile Improvement that's not even an Action. That's based on the TileInfo and Workers automatically work on it if they are on the tile.

**Comment by AdityaMH** [comment]
If unit on exploration command but healing state. That will be fortified forever even fully healed.
Need to cancel fortified for solving bug.

**Comment by itanasi** [comment]
> If unit on exploration command but healing state. That will be fortified forever even fully healed. Need to cancel fortified for solving bug.

The action variable handles all of that. So by clearing it (setting to null) you remove Fortify, Sleeping, Automation, Explore, Move, and Siege
