### ISSUE TITLE
Cover working for City Bombardment

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6540]
letstalkaboutdune on Discord tested and proved that Cover defense benefit doesn't apply to City Attacks.

That seems...weird. Perhaps not a bug since as Written the Unique provides defense from Ranged Units.

But the spirit of the Unique should help defend against Ramged Attacks from Units, Cities, and Air units.

**Comment by itanasi** [comment]
ravignir checked and Cover only works for Melee units, not Ranged/Artillery when dealing with City Bombardments

**Comment by itanasi** [comment]
Not working on Artillery:
![image](https://user-images.githubusercontent.com/44038014/163315418-83af6aaf-a178-442e-b876-2ac7770e6261.png)

Works for Melee
![image](https://user-images.githubusercontent.com/44038014/163315477-b87d45d2-6620-4987-b295-4ed9e11c5816.png)

Not on Ranged
![image](https://user-images.githubusercontent.com/44038014/163315499-94d3dbce-45c7-41db-bd20-a9018c967ae2.png)

**Comment by xlenstra** [comment]
I vote to close this as WAI, specifically excluding city ranged attacks on ranged units feels overly specific and will probably only cause confusion

**Comment by yairm210** [comment]
Agree
