### ISSUE TITLE
City distance rule is being violated

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#6541]
![Screenshot_20220413-204703_UnCiv](https://user-images.githubusercontent.com/73200638/163259867-e470592c-4bec-4bfd-a816-7e60e2a4c11e.jpg)
As you can see, Japan have placed a city within three tiles of mine.

**Comment by ArchDuque-Pancake** [comment]
They are on a different continent, and when they are in different continents, they can be 1 tile closer.
