### ISSUE TITLE
Game crashes on pi4b 8gb, 64bit raspian bullseye

### ISSUE THREAD

**Issue by Daggerfellar** [yairm210/Unciv#6549]
**Platform**
Raspian, Bullseye, Pi4b (64 bit).

**Version**
Pi-Apps version 4.0.5

**Describe the bug**
game keeps crashing after a few turns, sometimes after one turn

**To Reproduce**
every 1-7 turns the game just crashes

**Expected behavior**
the game to not crash

edit:

im going to try updating to version 4.0.6 and report back in a little bit. 

updating erased my saves :/

**Comment by yairm210** [comment]
What was the problem?
