### ISSUE TITLE
Air Sweep Implementation

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6553]
Thread to document and discuss Air Sweep.

Mentioned in #4697

Some specs based on Civ 5 code/behaviors:
- Should draw an Interception if available on the tile
- Land Units deal 0 Damage, get 2 XP
- Air Units Intercept and do Air Combat as if Melee. Except it's using Ranged Attack Strengths. 5XP to both attacker and defender
- Should count as an Attack

UI: Separate mode? Make all tiles in Range clickable, and if tile has a Unit give an Air Sweep option?

**Comment by xlenstra** [comment]
I'd make the UI a togglable unit action (similar to paratrooping) and then draw a crosshair on all tiles in range (except maybe friendly units? Not sure). Otherwise, sounds good
