### ISSUE TITLE
Wrong link in F-Droid

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6556]
**Describe the bug**
I went to F-Droid and found a wrong link.

**To Reproduce**
1. Go to F-Droid
2. Scroll down to 
![image](https://user-images.githubusercontent.com/100454479/163701562-b98a47a6-9b05-447b-a25a-0348b2240479.png)
3. Click on 'translation'
It went to
![image](https://user-images.githubusercontent.com/100454479/163701601-38c44f67-e8b3-4f5d-a1d5-e92d49c74e22.png)

**Expected behavior**
It should go to the new wiki, instead of the old version.

**Comment by yairm210** [comment]
Posted a PR to resolve this
