### ISSUE TITLE
Activate Piety production bonus

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#656]
#655

**Comment by Am-per-Sand** [comment]
54fc81f

**Comment by Crit-Cee** [comment]
What was this? Saw it in the update log but not seeing it in the Piety policy branch in game.

**Comment by Am-per-Sand** [comment]
@Crit-Cee : It was only for the part of the city screen – the one that gives you insight into calculation of the city stats. Here it is summarized: [/core/src/com/unciv/ui/cityscreen/CityScreen.kt](https://github.com/yairm210/UnCiv/blob/master/core/src/com/unciv/ui/cityscreen/CityScreen.kt)

**Comment by Crit-Cee** [comment]
Ah. Thanks.
