### ISSUE TITLE
tileFilter and terrainFilter no longer reading uniques

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#6575]
**Platform**
Android

**Version**
Github 4.0.8

**Describe the bug**
Previous to 4.0.8, the tileFilter and terrainFilter parameters can parse 'custom' uniques on a resource or improvement (e.g. "Flora" resources), making it easier to group resources together and call them by their group. But, in 4.0.8, both tileFilter and terrainFilter no longer check the uniques of resources and tile improvements on a tile, making it quite tedious to mod resource specific buildings.
For example, let's say I added the "Flora" unique on Wheat, Banana, and Dyes. I also added a Botany Lab building with the unique "[+1 Food] on [Flora] tiles [in this city]", with the intention of making Wheat, Banana, and Dye tiles in that city have +1 more food. Before 4.0.8 this works with only one unique, which is "[+1 Food] on [Flora] tiles [in this city]", but after 4.0.8 I have to write three uniques, one for wach resource.
Please fix to before 4.0.8 behavior, or at least allow tileFilter and terrainFilter to look inside uniques of resources and improvements on its tile.

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
They still do parse custom uniques, but now you would get an error message - I'll remove that since I never thought that someone would use the uniques *of the resource* for this, I only considered terrains :)

**Comment by yairm210** [comment]
Resolved in https://github.com/yairm210/Unciv/commit/bd41630f8492003f55d01ff2d667141a71696a07
