### ISSUE TITLE
Autofix URLs from user input at `Options` > `Multiplayer` >  `Server address`

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6583]
So, I have a Multiplayer Server with the URL `https://uncivserver.xyz`.
Some people tries to connect to the server with the URL `https://uncivserver.xyz/` (with a trailing `/`) and says that it is not working.
Some might even input unnecessary spaces ?

I actually tried to fix this from server side using the following logic:
1. If the URL Path contains Repeated `/` than replace them with a single `/`
2. Remove all whitespaces from Request Path

On Commit: https://github.com/touhidurrr/UncivServer.xyz/commit/257b209be79d85d93ebae2fd3fe1cbf4f6e9147e

But for some reason this kind Autofix attempt from server side doesn't work. (Maybe beacuse of some kind of Clientside logic)
More specifically this did work for `GET //isalive` but not on `GET //files/:fileName` and `PUT //files/:fileName` for some reason **from Unciv**.
If you try to test it yourself by visiting URLs like:

- https://uncivserver.xyz///files/startup or
- https://uncivserver.xyz////files//////startup

You would find that it does indeed work so I would assume that this autofix attempt didn't work for some clientside logic maybe.

Anyways, since this kind of typos are quite common, I suggest URLs should be automatically formatted from Client Side instead.
The Fixes I suggest are:
1. Remove any whitespaces from the URLs
2. Remove Repeated `/` characters (Cause if the client sends urls like `https://example.com//isalive` it's probably a mistake)

**Comment by SomeTroglodyte** [comment]
I'd vote _against_ this as I am evil :smiling_imp: and think Darwin :man_teacher: was right, _let_ them shoot :gun: their own kneecaps :kneeling_person: out if they're that ~~censored~~!

**Comment by touhidurrr** [comment]
> I'd vote _against_ this as I am evil 😈 and think Darwin 👨‍🏫 was right, _let_ them shoot 🔫 their own kneecaps 🧎 out if they're that ~censored~!

Personally I think that if Unciv tries to fetch urls like `https://example.com//isalive` It's really just a typo. So, users getting confused for such silly things is unwanted.

**Comment by touhidurrr** [comment]
And so I learnt some Kotlin and opened a pr myself
didn't know Kotlin had native support for Regex
