### ISSUE TITLE
Add Contients map type.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#659]

**Comment by ninjatao** [comment]
![Figure_1](https://user-images.githubusercontent.com/6846049/56360952-b233ff00-6218-11e9-8874-f810734d6e15.png)
Algorithm almost ready. Will try some polishing before implement.

**Comment by yairm210** [comment]
Oooooh!!!

**Comment by Smashfanful** [comment]
How did you do that (the one in the image)?

**Comment by ninjatao** [comment]
I was tuning the generator in Python.

**Comment by Smashfanful** [comment]
Ok, thanks
