### ISSUE TITLE
Import & Export Game Settings

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6597]
It would be cool if I could move all of my settings from Android to PC (and vice versa) with a JSON file of some sort that includes: my user id, my mods name / links, options, multiplayer games ids etc.

That's all.

**Comment by SomeTroglodyte** [comment]
About the 42th time something like this is asked.
- For a true migration you'd need a few more files, and that is the scope of _backup software_.
- nerds can use Studio's device file explorer, or adb, or local root file explorers + mtp just fine.
- non-nerds will need to use the custom save location feature to export their favourite save, move that, and redo settings and mods on the other end. Can be done in under 5 minutes.
- Look at #2517 if you want - was the same direction but got ditched.

**Comment by yairm210** [comment]
Closing due to lack of interest. You're free to work on this yourself of course but as for me this is out of scope.
