### ISSUE TITLE
Exposing some parts of Unciv as CLI

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6602]
It would be cool if some things like creating a new Game can be executed from Command Line like how we start UncivServer. That way custom servers like UncivServer.xyz can create games themselves maybe from Discord Bots also.

So, basically widen the limits of Unciv.

**Comment by yairm210** [comment]
This is both extremely vague and not in the roadmap. I have no problem with anything you would add but this doesn't deserve an issue.
