### ISSUE TITLE
Map editor scroll issue

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#6610]
OS: Android 12

Device: SM-G970N (2280x1080 screen)

ver: 4.0.9, APK from github

video: https://youtu.be/PNMUO2ns8mk

Description: If i select custom size on map editor, expansion leads to scroll bug.

**To Reproduce**
1. Open map editor.
2. Click 'Generate'.
3. Select 'Custom' on World Size.
4. See error.

**Expected behavior**
- If you select custom size, side menu expands, and scroll doesn't work. Thus you can't click 'Create' button.
- If you wanna generate custom-sized map, you must scroll down before choosing 'Custom'.

**Additional context**
Portrait orientation is useless because... 🤦

<details>
<summary>(See more)</summary>

![Screenshot_20220426-093510_UnCiv](https://user-images.githubusercontent.com/64586749/165198293-48b6c08c-e4fe-4b40-96fd-bd685977e98a.jpg)
</details>

**Comment by SomeTroglodyte** [comment]
That Editor was never meant for portrait. The old one wouldn't have been any better at that low resolution. It's actually not that bad at x700 or x800. That this growth of the contained widgets isn't propagated to containers is not uncommon, might be easy to catch. Maybe.

**Comment by SomeTroglodyte** [comment]
No it's _not_ easy to catch at all. I experimented for hours and while the Expander just below does recalculate geometry just fine I can't get the extra rows for custom dimensions to also force its enclosing ScrollPane to take the space - it goes to the next one. Meaning you _can_ scroll the button into view by dragging the New/Partial header. Yes, ugly. And I'm still stumped.
