### ISSUE TITLE
Broken link in uniques.md

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6618]
**Describe the bug**
The link is broken in uniques.md

**To Reproduce**
1. Go to ['here'](https://yairm210.github.io/Unciv/Modders/uniques/)
2. Click on the link shown in the screenshot.
![image](https://user-images.githubusercontent.com/100454479/165316320-159eb141-ef48-4d7e-926b-7bbf4c336950.png)
3. See the familiar broken 404, which is dicussed in #6521 

**Expected behavior**
It should go tohttps://yairm210.github.io/Unciv/Modders/Unique-parameters/, instead of
https://yairm210.github.io/Unciv/Modders/unique parameters

(Seriously, there is indeed a space in the link)
![image](https://user-images.githubusercontent.com/100454479/165319343-30241669-b598-4ba6-b59a-0f5ce5105e50.png)

Not sure whether it is caused by the uniques docs makeover,,
If it is not, then a simple PR can solve it.

**Comment by yairm210** [comment]
That's a typo, nice catch 🪝
