### ISSUE TITLE
Crash on launch with certain Mods

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6619]
Modchecker runs into an infinite loop, a regression that must be caused by me with #6516. You can get it on game launch or by running "Locate Mod Errors" after freshly installing the Mod. The Mod in question uses "{Military}{Land}" instead of the documented "{Military} {Land}", which with a little thought is _plain and obvious_ that it will break the recursion used in `BaseUnitFilter.getErrorSeverity`. I had a gut feeling back then that `split("} {")` is bad but didn't set a `todo` immediately and then forgot to check later...

We (I) will need to ensure immunity against such trifles.

Devs: I'd tend to not only harden the helper, but in the process maybe also allow that syntax. I'll also look to make sure nested or unmatched braces lead to a RulesetInvariant error. Also - a regex could be the easiest way to do the split safely - too expensive?

**Comment by yairm210** [comment]
Regex is acceptable, as long as we only run it when necessary

**Comment by SomeTroglodyte** [comment]
I fear I might not have the energy in the next hours to pursue this. For reference -> [DW8030/Civ6-mod#5](https://github.com/DW8030/Civ6-mod/pull/5)

**Comment by yairm210** [comment]
This was solved... sometime ago, don't remember exactly when
