### ISSUE TITLE
Missing features from Civ V

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#663]
As a GRAND POLICY CHANGE, we're changing our goal from Vanilla Civ V to G&K Civ V.

The items in this issue are still relevant,

- [x] Aircraft Carriers
- [x] Civilization Rankings (Richest, Strongest, Most Fertile, Largest, Happiest, Most Productive)
- [x] No Ancient Ruins starting option
- [x] Owned Cities need a growth bar, to see in how many turns the City will grow
- [x] Random Civ choice in the Civ select window
- [ ] Diplomatic Victory
- [ ] Peace request, denunciation and friendship request quotes
- [ ] Civ timeline for momentous events
- [x] City build queue
- [ ] Unique denunciation quotes (?)
- [ ] When about to promote an unity, you can change their name
- [ ] Missing wonders - Petra, United Nations
- [x] Civilizations - Aztecs, Mongols, Incas, Danish, etc.
- [x] Forts and Citadels
- [x] Research agreements
- [ ] Civ Teams on new game
- [ ] Cities requiring a resource and consequent "Hail the King" celebrations
- [ ] A Civ can ask another Civ to make peace with a third Civ
- [x] Policy Branch: Order
- [x] Policy Branch: Patronage
- [ ] "Build road to" action for workers
- [ ] Achievements (Google Play exclusive)

**City states**

 - [x] Cities owned by City-States should have an Influence bar to see what are their relations with you.
 - [x] Should give gold when first met
 - [x] City-states with good relations with you may give you resources
 - [x] Personalities
 - [x] Quests

**Comment by Am-per-Sand** [comment]
what is _Allow Policy accumulation_?

BTW - on immortal and deity on small maps never can find any ruins

**Comment by Smashfanful** [comment]
@Am-per-Sand _Allow Policy accumulation_ allows to accumulate Culture points over the minimum limit for a new policy, without forcing you to choose one.

**Comment by Am-per-Sand** [comment]
That's funny - what can a player use such overload of points for?

**Comment by yairm210** [comment]
This is a mix of a few things.
First is #559 
Second is civ rankings
Third is 'policy accumulation' which from your description already exists so I'm not sure what you want
Please move all game starting options to 559
And call this "add civ rankings"

**Comment by amunizp** [comment]
So Spain is only missing natural wonder? According to #703 ?

**Comment by r3versi** [comment]
All vanilla NW are in game and so is Spain

**Comment by amunizp** [comment]
I am on 3.4.4 from f-droid and I can't see it as an option when starting a new game.

**Comment by yairm210** [comment]
Update to a more recent release =)

**Comment by juanantonioao** [comment]
Hello, I'm noob here. I've never played Civ V (I only played Civ IV) but I'm sure this feature is present on the game, and it's not in UnCiv.

When I start to create parts of the ship, there's no written anywhere how many parts I need. There are four kind of parts I have to build, but I can't know how many of them I must build to win. It's not in the Civilopedia, it's not in the description of the building... The worst is I start to build as many parts as I can, and when I reach the limit (a limit I can't know) production is interrupted in all the other cities, losing all the turns I've spent on building that part.

I think it should be pointed anywhere how many parts can you build. Even better: when you are building the max parts you can, game should not allow you to build more.

In adition, I'm junior developer and maybe I could add that feature by myself, but I don't know if I'm gonna have enough time.

**Comment by busymaestro** [comment]
I would really enjoy the addition of the brave new world pack civs, such as Poland, the Zulus, the Maya, Carthage and the huns. I feel that this would bring a lot to the game.

**Comment by yairm210** [comment]
@busymaestro That's not in the scope of this issue, and will not happen until we finish the Vanilla features.

**Comment by Rodri3003** [comment]
What about changing the police state policy, in original Civ V it was not the maintenance of the city borders once it is conquered; it was a +3 on happiness from each courthouse and build Courthouses in half the usual time. This wouldd be (in my opinion) a good implementation in Unciv since conquering cities in the actual version of the game is horrible because they never maintein their borders and feels a bit bad when you have to pay in order to recover the lost tiles.

**Comment by YonniF** [comment]
I believe you don't settlers or workers from ancient ruins in higher levels of civ V but you do unciv. Not a major issue but a small discrepancy.

**Comment by asilano** [comment]
In vanilla Civ 5, you can order a worker to construct an improvement on a Forest/Jungle/Marsh tile that first requires removal of the terrain feature (eg Build Plantation on a Forest tile with Spices; Build Farm on a Plains/Jungle tile). The worker then does the clear first, followed by the build.

This would especially make it clearer how to improve resources on forest/jungle tiles.

**Comment by RealGrouchy** [comment]
I am really missing the "make me an offer" option in diplomacy. Having to wait a turn to see if an offer is accepted (and then forgetting what I offered) makes it not worth bothering trying to trade, this would make it a lot easier to figure out what an acceptable trade might be.

**Comment by asilano** [comment]
(Unless I'm missing something) you can't see what's already been built in a city. Aside from general usefulness, there are two specific cases it's important to have:

* Without it, you can't destroy a building if you need to save Maintenance costs
* You can't see which cities have wonders in them, which is important for the Reformation policy in Piety (+33% culture in cities with wonders)

**Comment by yairm210** [comment]
@asilano that's in 'stats drilldown'

**Comment by MarcinMich** [comment]
Wanted to create a new issye but I guess it was indeed in Civ 5 vanilla.

Shouldn't chopping down a forest give a production boost?

**Comment by LeGend172** [comment]
Air Sweep action by Fighters/Jet Fighters

**Comment by u-ndefine** [comment]
There should be a [time victory](https://civilization.fandom.com/wiki/Victory_(Civ5)#Time_Victory) in Unciv, unfortunately, I don't know how Civ5 computes it.

**Comment by g-whiz** [comment]
> That's funny - what can a player use such overload of points for?

It's useful when you're researching a tech that advances the era. That way you can wait til a new branch is unlocked without wasting culture points.

**Comment by wbrawner** [comment]
I think there's a missing action for military units: Alert. Alert is like fortify except the unit wakes up when an enemy unit comes within attack range.

**Comment by foolishgrunt** [comment]
![Screenshot_20200628-102632_UnCiv](https://user-images.githubusercontent.com/1423934/85954271-11b49100-b92b-11ea-8b19-50fc88da825b.png)
![Screenshot_20200628-102734_UnCiv](https://user-images.githubusercontent.com/1423934/85954280-1b3df900-b92b-11ea-90fa-78196b27165c.png)
It appears that clearing a forest does not provide a production boost to the closest city.

I've attached screenshots of the last turn before clearing a forest and the first turn after clearing it - the production turn counter in the city only changed by 1, the same as if no forest had been cleared. (I apologize for not providing exact readings from the production status meter, but I have not yet found where that is on the city screen.)

**Comment by foolishgrunt** [comment]
Zones of control appear to not be implemented.

**Comment by halloamigos** [comment]
A few other missing options in diplomacy/trade:

1. Broker peace between warring AI

2. Enter custom amounts of an item during trades

3. Gifting units to city states and civs

(All of these are in civ v)

**Comment by refola** [comment]
Offshore Platforms should be unlocked with Refrigeration [per Vanilla, G&K, and BNW](https://civilization.fandom.com/wiki/Refrigeration_(Civ5)). Currently work boats build Oil Wells when Biology is researched, despite them being invalid for water tiles.

Coastal oil is the unique resource which can be seen before the improvement for it is unlocked. Thus I suspect this is more complicated than simply changing some data files.

**Comment by halloamigos** [comment]
**Missing unit ability** • Roman legion fort construction

This is a unique ability for the legion unit and I would very much appreciate for it to be added in unciv

![Screenshot_20200731-115351_Chrome](https://user-images.githubusercontent.com/64375454/89058531-118e2380-d325-11ea-8159-77bba123c344.jpg)

**Comment by saud2410** [comment]
Instant "Razing city" on capturing should not annex the city.
Strategic resources' number per tile should be vary, not fixed as 2.

I'm afraid they might not be Civ 5 Vanila feature. I cannot find whether they are GnK of BNW, and they are related to war and domination victory. Domination is meant to be difficult, but imao not this way.

**Comment by ravignir** [comment]
#2952 
![htd6uvipwhgy](https://user-images.githubusercontent.com/30041793/89718580-ee681180-d9bf-11ea-9ffb-c65e088333c9.jpg)
Make peace with is in civ5 (it can be either a city state or civilization). Also appears in demands screen.

**Comment by halloamigos** [comment]
**Missing feature**: Map wraparound on east-west axis

**Comment by draco305** [comment]
The [Marine unit](https://civilization.fandom.com/wiki/Marine_(Civ5)) is missing as well as the amphibious promotion and the attack penalty when crossing a river.
The danish Berserk unit has this ability but not as promotion.

**Comment by samyelias** [comment]
Another missing feature is the unit supply cap in Civ V vanilla.

For every unit you have over the supply cap, your production in all cities is penalized by 10%, up to a 70% penalty max.

The supply cap is calculated as described here: https://old.reddit.com/r/civ/comments/1lhvsd/supply_is_required_for_unit_maintenance_too_along/

**Comment by samyelias** [comment]
Also, is there any reason the map sizes are much smaller than the Civ5 equivalents? For example, rectangular Large in Unciv is 66x43, but that's actually the Small size in regular Civ5: https://civilization.fandom.com/wiki/Map_(Civ5)

**Comment by flecheapolinienne** [comment]
Citadel should connect the ressource they are built upon, as per Civ 5 (see https://civilization.fandom.com/wiki/Citadel_(Civ5)

**Comment by kasterra** [comment]
Missing feature : Korean's Ability : Receive a tech boost each time a scientific building/Wonder is built in the Korean capital

**Comment by b-1** [comment]
#3479 
when you click on the "pillage" button, let the game suggest what to pillage: an improvement or a road, and writes how much HP the unit will receive. 

HP. let the game offer two options:
- "pillage improvements +10HP" (or another in-game data);
- "pillage road +0HP".
and the player will choose what to do and in what order.

sense. this removes the bonus to the arrival speed of the opponent's support troops. this possibility is in Civ5.

**Comment by ravignir** [comment]
> 
> 
> #3479
> when you click on the "pillage" button, let the game suggest what to pillage: an improvement or a road, and writes how much HP the unit will receive.
> 
> HP. let the game offer two options:
> 
>     * "pillage improvements +10HP" (or another in-game data);
> 
>     * "pillage road +0HP".
>       and the player will choose what to do and in what order.
> 
> 
> sense. this removes the bonus to the arrival speed of the opponent's support troops. this possibility is in Civ5.

This is wrong. You can not choose which improvement to pillage ((rail)roads are always pillaged last) and it always heals by 25 HP. It also provides some gold - it is random and I was unable to find the exact values, altho from my 50 pillages sample size it was always between 5 to 30 (regardless of era and game speed). 
Pillaging (rail)roads does not grant any gold and does not heal your units.

https://user-images.githubusercontent.com/30041793/103346704-1a7e4f00-4a95-11eb-9d8e-9b9930d2f7d5.mp4

**Comment by b-1** [comment]
vanilla is able to pillage not only improvements, but also roads, and after that leaves unfinished improvements. UnCiv does not know how to pillage roads as well as can leave improvements unfinished (and still does not know how to leave unfinished/pillaged a road and an improvement on one tile at the same time #3463).

but Civ5 does not offer to choose what to pillage/repair in the first place. and I propose to make the dialog box as feature in UnCiv.

**Comment by jaxankey** [comment]
> **Missing feature**: Map wraparound on east-west axis

Two thoughts on this:

- There is no perfect mapping of a globe onto a flat surface, so you could also have an option to tile the hexagonal world in all directions. Though the "poles" have a strange meaning in this case. :)
- One "easy" solution might be to actual create the repeated map tiles in the "wrap" directions, and then, if the map view location lands outside the original tiles, immediately snap it to the same location in the original tiles. This could happen at the end of a drag for sure, or maybe even at each step (every frame does this quick math).

**Comment by xPMo** [comment]
Might I suggest this issue be pinned? I sought out the repo primarily to see the progress, I imagine others would as well.

**Comment by davidhoward** [comment]
I'm planning on taking a look at "Peace request, denunciation and friendship request quotes". Do we have an authoritative source for such quotes?

**Comment by davidhoward** [comment]
Nit: Petra appears to be a G&K wonder, maybe doesn't belong in this list

**Comment by SomeTroglodyte** [comment]
Citadels should be buildable just outside your borders but are not. The code snippet `tile.neighbors.any { it.getOwner() == unit.civInfo }` in `UnitActions.getImprovementConstructionActions()` should handle this but is trumped by `getOwner() != civInfo && !improvement.hasUnique("Can be built outside your borders") -> false` in `TileInfo.canBuildImprovement()` as the Citadel does not have that unique.

I'd PR this quickly but am unsure as to policy/approach: more hardcoding or less? Give the Citadel a new unique for this purpose?

**Comment by ERROR1025-iop** [comment]
Set "Player and AI" &&"Player and Player" trading technology in MOD "Difficulty"

**Comment by ERROR1025-iop** [comment]
Add a building that can do this:
When the production is completed in the city, the excess capacity will be used for the next project

**Comment by ravignir** [comment]
Why a building tho? It is a standard feature of civ5.

**Comment by xlenstra** [comment]
Swapping tiles between cities of the same empire? It is currently possible to work tiles owned by another city, but not to swap these to other cities.
I am currently in a diplomatic position where I want to acquire a few tiles of a neighboring human player as a trade for me not going to war with them, and as this is in civ V we assumed it would also be possible in unciv, but sadly it is not. Our solution was to temporarliy hand over the city to me, so I can add the tiles to another city of mine, and then give back the city, but this is apparently not possible.

**Comment by yairm210** [comment]
I'm absolutely sure that 'trading for tiles' was not in Civ V.

**Comment by xlenstra** [comment]
Trading for tiles between your own cities was defintely in Civ V

**Comment by xPMo** [comment]
> Swapping tiles between your own cities was defintely in Civ V

Yes. But your comment mentioned trading with _another player_ as a feature of Civ V:

>  I want to acquire a few tiles of a neighboring human player as a trade for me not going to war with them, and **as this is in civ V**

Tile trading would be an incredibly complex UX problem to solve (which is probably why Civ V didn't even try).  I don't even know what that interface would look like.

**Comment by xlenstra** [comment]
I might have worded that poorly. What i meant to say was that using this mechanic of trading tiles between your own cities that is available in civ V, it would be possible to simulate this transaction of tiles by temporarily trading a city between us. This was meant as an example for what would be possible using this mechanic that is currently impossible.

**Comment by SomeTroglodyte** [comment]
... and swapping tiles between your own cities was intentionally removed in Unciv for good reason (see #2588).

**Comment by logicminimal** [comment]
I dont know if i am posting this feature request to the right place but the player really should be able to choose which tile their city will expand onto, i dont know if it exists in any of the original civ games as i haven't played those before

**Comment by ravignir** [comment]
> 
> 
> I dont know if i am posting this feature request to the right place but the player really should be able to choose which tile their city will expand onto, i dont know if it exists in any of the original civ games as i haven't played those before

nope, it is not in original game. The city automatically chooses the tile it expands to (and you know it beforehand). That's why you can buy tiles with gold if you want to expand manually.

**Comment by foolishgrunt** [comment]
Regarding national wonders:
In the same spot on the on the production selection list where UnCiv currently says "Requires a [Market] in all cities" Civ5 lists the cities which are missing the [Market]. This makes it much easier to see at a glance how much prep work is required before I can build this wonder.

(BTW, if this info is provided anywhere else in UnCiv, I'd be grateful if somebody could point me to it. Because right now I have to manually scroll and open each city individually to remind myself if I've built the [Market] there already.)

**Comment by ravignir** [comment]
Yes, but only if there are less than 4 cities without the required building.

**Comment by logicminimal** [comment]
> > I dont know if i am posting this feature request to the right place but the player really should be able to choose which tile their city will expand onto, i dont know if it exists in any of the original civ games as i haven't played those before
> 
> nope, it is not in original game. The city automatically chooses the tile it expands to (and you know it beforehand). That's why you can buy tiles with gold if you want to expand manually.

it's kind of a problem when you already maxed out all the tiles that you could purchase, especially in one city challange :/

**Comment by logicminimal** [comment]
## **Feature idea: Ultimatums**

**Is your feature request related to a problem? Please describe.**

We have to declare wars when we want only one city of a civilization, or a resource of a civilization

**Describe the solution you'd like**
just like you give open borders as an offer in a trade request you should be able to offer a trade request with an ultimatum in it, demanding certain resource or city, or to force a civilization into declaring war on one another, you should also be able to offer other stuff alongside your ultimatum as to increase the chances of the opposing civilization to accept it. also an ultimatum should damage the relations between civilizations

**Describe alternatives you've considered**
N/A

**Additional context**
I would illustrate an example trade screen but i couldn't.

The offer for an ultimatum should have the color of declare war button, tinted more orange

**Comment by xPMo** [comment]
> Feature idea: Ultimatums #3868

I see you copied your comment, but wrt #663, we should focus on the vanilla implementation.

> This should be under Demands as one-sided trade, just like it is in civ5.

It's been some time since I made a demand in Civ, but iirc way it works in Civ V is that a one-way trade can be proposed as a normal trade (which I interpret as "asking for help") or a demand (for tribute).  if a demand is rejected, the player is immediately given the option of declaring war, denouncing the other Civ, or doing nothing ("You'll pay for this in time.").  I am certain that Civ V does not give any way to provide your response beforehand.

I also am not sure whether there are diplomatic modifiers for declaring war despite having received tribute, or for taking no action in response to a rejected tribute.

**Comment by ravignir** [comment]
Just to clarify: There is no war in civ5. There is just nothing more to it than onesided trade. Except it is more threatening and you will receive diplomatic penalty.

**Comment by ravignir** [comment]
Demand Tribute from City States; Giving more gold to CS as a single gift provides more influence. Influence gained from gold gifts to CS decays over time: Here is a spreadsheet I prepared: https://docs.google.com/spreadsheets/d/1sbVFDvUvEObnN-P1K8j4KBtjwcvkbKk_U6Mh5nYnxIY/edit?usp=sharing

**Comment by logicminimal** [comment]
> > Feature idea: Ultimatums #3868
> 
> I see you copied your comment, but wrt #663, we should focus on the vanilla implementation.
> 
> > This should be under Demands as one-sided trade, just like it is in civ5.
> 
> It's been some time since I made a demand in Civ. In Civ V a one-way trade can be proposed as a normal trade (which I interpret as "asking for help") or a demand for tribute.  IIRC, if a demand is rejected, the player is immediately given the option of declaring war, denouncing the other Civ (if available), or doing nothing ("You'll pay for this in time.").  I am certain that Civ V does not give any way to provide your response beforehand.
> 
> I also am not sure whether there are diplomatic modifiers for declaring war despite having received tribute, or for taking no action in response to a rejected tribute.
> 

@yairm210 by the way, i have an idea on how to implement this feature, it seems rather simple as someone who doesnt know about the code of the game, simply just add an option to declare war on the civilization you are trading with, just like how you can demand money to declare war on civilization

like:

Mongolia's trade offer:
Declare war on [opposing party in trade](greece in this case)

Greece's trade offer:
gold(500)

**Comment by ravignir** [comment]
I've just played Germany no city challenge in civ5 and i've noticed unciv lacks Unit supply mechanic:
https://forums.civfanatics.com/threads/unit-supply-how-does-it-work.394722/

**Comment by samyelias** [comment]
> I've just played Germany no city challenge in civ5 and i've noticed unciv lacks Unit supply mechanic:
> https://forums.civfanatics.com/threads/unit-supply-how-does-it-work.394722/
> Base supply is 5.

Yeah I mentioned this earlier as well: https://github.com/yairm210/Unciv/issues/663#issuecomment-687903762

Kind of an invisible mechanic, but a faithful copy of Civ V should have it as it does have an effect.

**Comment by logicminimal** [comment]
proper demands, like one in civ5 where it is basically a one sided trade

**Comment by jahodovykolac** [comment]
Renaming units and city states' personalities are implemented now, so you can tick them off

**Comment by ravignir** [comment]
- Ranged units should be able to have a special action that allows them to capture civilians (in civ5 capturing a civilian happens automatically when an unit moves to a tile and it does not consume any additional movement/does not prevent the unit from attacking).
 - Great Persons should be uncapturable - regarding G&K expansion: Inquisitors are uncapturable while Great Prophets are capturable. Religious unit keep their respective religion on capture.
 - Zone of Control mechanic.
 - When you capture a civilian that was not originally yours, you should have an option to return the control of it to their last owner (actually second last owner, like you/nation who captured/ >Nation who controlled the civilian before it was captured<).
 - Barbarians capture civilians and escort them to the nearest encampment. If no encampment is free, they will just try to have that unit always protected by military barb unit. Settlers captured by barbs stay settlers, they will turn into workers when they are recaptured by different civ than their owner unless that civ decides to return that unit.
 - Cities should not be able to bombard while they are in resistance.
 - Recaptured cities should immediately return under player's control and should be able to bombard on the same turn with no resistance. If capital is recaptured, it should become the capital again.
  - Capturing a city should destroy all of the existing non-wonder culture buildings in that city. (and there is a random chance to destroy additional buildings, but i don't know the percentage value)
  - Nukes should create fallout in random tiles, not in all tiles. ~50% to create a fallout and pillage an improvement on a non forest/jungle tile. ~25% chance  in jungle/forest tiles (this permamently removes jungle/forests).

**Comment by logicminimal** [comment]
> Renaming units and city states' personalities are implemented now, so you can tick them off

    we love the king day is needed

**Comment by avdstaaij** [comment]
According to https://civilization.fandom.com/wiki/Movement_(Civ5), the original game has three different unit layers: land military, sea military and civilian. A tile can contain a unit of all three types simultaneously, and embarked land units can occupy the same tile as a sea vessel. Unciv currently only has two layers: military and civilian.

Petra has been enabled in #4092, so it can be removed from the "Missing wonders" item.

**Comment by logicminimal** [comment]
https://github.com/yairm210/Unciv/issues/2851

**Comment by logicminimal** [comment]
https://github.com/yairm210/Unciv/issues/2851, https://github.com/yairm210/Unciv/issues/1925

these two are a must at this point

**Comment by logicminimal** [comment]
#1925

**Comment by logicminimal** [comment]
pillaging does not provide gold

**Comment by logicminimal** [comment]
Conquering only provides gold, wasnt this different in the original game?

**Comment by logicminimal** [comment]
"You can revoke protection of a City-State at any time once 10 turns since your declaration of protection have passed. (In vanilla, doing this results in a penalty where you cannot pledge to protect the same City-State for a short period of time.)" the player can pledge or revoke protection anytime they want

also many city state stuff are not implemented https://civilization.fandom.com/wiki/City-state_(Civ5)

**Comment by xlenstra** [comment]
Currently, both the rate at which city borders naturally expand, and which tiles they expand to do not follow Civ V behavior.
The source for the rate of border expansion is given in the code as:
https://www.reddit.com/r/civ/comments/58rxkk/how_in_gods_name_do_borders_expand_in_civ_vi/
Which is for civ 6 and not civ 5.
Futhermore, currently which tiles are chosen is determined first by distance to the capital, and then by resources/yield. In the original game this was different, see:
https://www.reddit.com/r/civ/comments/4o4o6j/civ_v_border_expansion_algorithm/
This was already noted in #3059, but this fix for this issue only implemented parts of the original behavior.

BTW, should this type of thing (misimplemented behaviour) also be posted in this thread, or should it be its own issue?

**Comment by SomeTroglodyte** [comment]
For cultural expansion, [this wiki entry](https://civilization.fandom.com/wiki/Mathematics_of_Civilization_V) gives a believable formula which is indeed differing from `6 * (max(0, tilesClaimed()) + 1.4813).pow(1.3)`...

**Comment by logicminimal** [comment]
Make policies give leaders titles

https://civilization.fandom.com/wiki/Social_policies_(Civ5)

**Comment by SomeTroglodyte** [comment]
From the [Warrior wiki](https://civilization.fandom.com/wiki/Warrior_(Civ5)): "Notably, a Warrior will upgrade into a Spearman if it receives a unit upgrade from an Ancient Ruins". So are we missing a whole 'Ruins give Upgrades' (not only XP) feature? Using different upgrade paths than normal upgrades through tech?

**Comment by logicminimal** [comment]
> From the [Warrior wiki](https://civilization.fandom.com/wiki/Warrior_(Civ5)): "Notably, a Warrior will upgrade into a Spearman if it receives a unit upgrade from an Ancient Ruins". So are we missing a whole 'Ruins give Upgrades' (not only XP) feature? Using different upgrade paths than normal upgrades through tech?

also,

"_    A crudely drawn map of the surroundings of the ruins: Reveals most of the tiles nearby. Note that the center of the revealed space is not the ruins tile, but somewhere 3-4 tiles away in a random direction.
    Evidence of Barbarian activity: Reveals location of one or more nearby Barbarian encampments.
    Secrets of the ancients: Gives you a free Ancient Era technology. Note that you can only receive a technology that is available to research at the time you visit the ruins; in other words, all prerequisites for the technology must be met already. You can't, for example, get Writing if you haven't researched Pottery yet.
    Survivors, which join the civilization: Adds 1 Population to any one of your cities.
    Advanced weaponry: Gives a free upgrade to the unit used to activate the ruins.
        Warrior upgrades to Spearman, and then up the chain.
        Scout upgrades to Archer, and then up the chain.
        Pathfinder upgrades to Composite Bowman, and then up the chain.
    Gold treasure: You receive 50-100 Gold.
    Cultural artifacts: You receive 20 Culture.
    Religious artifacts: You receive 30-40 Faith.
    An ancient prophecy: You receive 80 Faith. Note that the civilization must have founded a Pantheon before this reward becomes possible and that it stops occurring after you've founded a religion.

On the easier difficulties, two additional awards are possible:

    A Settler to settle another city.
    A Worker to build improvements to terrain.

If the game pace is set on Marathon, the amount of Culture and Faith found is greatly increased, but not the Gold. _"

some seem to be missing, also when religion gets implemented faith ones should be included as well

**Comment by logicminimal** [comment]
diplomacy is barely implemented

Gnk luxury resources haven't been implemented

**Comment by logicminimal** [comment]
you can strike out city state gold

**Comment by ravignir** [comment]
You can settle cities 1 tile closer in civ5, if they are on different landmass.

**Comment by ravignir** [comment]
https://user-images.githubusercontent.com/30041793/126754718-26d15615-8131-45de-a3c8-aa377ef71a23.mp4

**Comment by SomeTroglodyte** [comment]
Pity there's no preparation to distinguish 'landmasses' yet in our code. Not a huge challenge, but balancing memory use, serialization or transient, and performance - hmmm...

**Comment by logicminimal** [comment]
> Pity there's no preparation to distinguish 'landmasses' yet in our code. Not a huge challenge, but balancing memory use, serialization or transient, and performance - hmmm...

i think they can be pre-calculated when the map is generated unless there are destroyable tiles that could be implemented

**Comment by yairm210** [comment]
Deprecated in favor of #4697
