### ISSUE TITLE
Can't load saved map

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#6635]
**Platform**
All

**Version**
4.0.10

**Describe the bug**
I can't load saved map from map editor

![image](https://media.discordapp.net/attachments/588357826758574106/969119468917780480/IMG_20220428_140856.jpg)

**Comment by SomeTroglodyte** [comment]
Button is disabled if you have 4.0.9 and no maps in your maps folder, or if you have the latest and no maps either in your own maps folder or any mod. I haven't consciously checked the internal/external conundrum on Android, though. So - where do you expect a map should be loadable?

**Comment by heipizhu4** [comment]
Interesting, I haven't saved any maps or download any mods with maps.
![image](https://user-images.githubusercontent.com/100454479/165760669-5d148093-d97a-49f8-8a73-c0d426d79a55.png)

PS: Found another non-user-friendly feature: The edit-units button is usually disabled, and a few friends of mine have asked me how to use it.

**Comment by AdityaMH** [comment]
Previous version is work well.
and actually,  i have map inside folder.
![IMG_20220428_211007](https://user-images.githubusercontent.com/33791472/165772012-7bfc2c4e-374e-4279-9419-802bd6c6bc25.jpg)

**Comment by SomeTroglodyte** [comment]
> units button is usually disabled

Not 'usually', _always_ as the feature is not implemented, same as the old editor. I wasn't sure when I'd try to reinvent that, so I placed the button to see if it looks good in its place, no more. Yeah, I could disable the code for it for a while...

> and actually, i have map inside folder

Now _that's_ proof something _is_ fishy! Thanks.
