### ISSUE TITLE
Game shows 'Can't download Game' error when actually an error when parsing the game data occurs

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6648]
**Platform**
Android 11

**Version**
4.0.10, 4.0.10-patch1

**Describe the bug**
I was trying to join a Multiplayer Game made with a Mod that I hadn’t downloaded yet. The Game showed the Error 'Couldn't Download Game' when I was trying to join the game.

This is very confusing as if anything goes wrong when handling the game data, the Client will always show 'Couldn't Download Game' regardless of the error.

Thus I suggest that for any error which is not a network error, the Client should show a peoper copy error ui with stacktrace.

Also if a game is made without a Base Ruleset that the user doesn’t have, the Client should show a proper error. Something like 'The game was made with a Mod you don't have'.

**To Reproduce**
Make an Online Multiplayer Game with a Base Ruleset Mod.
Delete the Mod.
Try to join the game.

**Comment by SomeTroglodyte** [comment]
Hehe, just like NanoSofter apps - hide useful info behind nondescriptive blahblah, then aggravate by passing to machine translations.

Seriously, if one expects an exception less than 0.1% of passes through some section of code, such a catchall is a time-saver.
Now we know mod discrepancies are a common occurrence and can adapt (what we can't is prevent game incompatibilities arising from different players in the same game having different versions of the same mod including breaking changes - not enough data).

Both addMultiplayerGame and joinMultiplayerGame do not use GameInfoPreview to check mod presence or do anything with a caught exception. But since multiplayer doesn't interest me I'll pass - I have no setup to test on.

**Comment by SomeTroglodyte** [comment]
@GGGuenni  - as local MP guru -
<details><summary>How about... (patch format, minimal band-aid):</summary>

```patch
Index: core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt b/core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt
--- a/core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt	(revision 4d6058a9d45e6c2109c9a990a4f21bb5eed7154e)
+++ b/core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt	(date 1651450579949)
@@ -8,6 +8,7 @@
 import com.unciv.ui.pickerscreens.PickerScreen
 import com.unciv.ui.utils.*
 import com.unciv.logic.multiplayer.OnlineMultiplayer
+import com.unciv.models.ruleset.RulesetCache
 import com.unciv.ui.crashhandling.crashHandlingThread
 import com.unciv.ui.crashhandling.postCrashHandlingRunnable
 import com.unciv.ui.images.ImageGetter
@@ -155,7 +156,13 @@
                 else
                     GameSaver.saveGame(gamePreview, gameName)
 
-                postCrashHandlingRunnable { reloadGameListUI() }
+                postCrashHandlingRunnable {
+                    val mods = sequenceOf(gamePreview.gameParameters.baseRuleset) + gamePreview.gameParameters.mods.asSequence()
+                    val missingMods = mods.filterNot { it.isEmpty() || it in RulesetCache }
+                    if (missingMods.any())
+                        ToastPopup("Missing mods: [${missingMods.joinToString("\n", limit = 32)}]", this, 5000L)
+                    reloadGameListUI()
+                }
             } catch (ex: FileNotFoundException) {
                 // Game is so old that a preview could not be found on dropbox lets try the real gameInfo instead
                 try {

```
</details>

**Comment by touhidurrr** [comment]
Should I close this? I saw that recently Unciv shows some additional debug info if I am not wrong.

**Comment by yairm210** [comment]
I'm pretty sure it does, let's close this
