### ISSUE TITLE
Some problem about ruins

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#668]
Some user of the game complained that he played some games on Immortal and Deity difficulties on small maps, and he didn't find any ruins in any game. You guys know what seems to be the problem?

**Comment by Am-per-Sand** [comment]
May be because ruins are rare (_theoretically about_ once per 100 tiles) and random, so on small map you usually get only a few or none and if it's not close to your start, AI scouts always scent it from away and may get first?

**Comment by yairm210** [comment]
It indeed sounds like a randomness issue.
I can assure that ruins spawn with no regards to difficulty level, and they do spawn in small maps, so Am-per-sand's theory sounds correct to me.

In general one of the things I've found is that people say they want random, but what they actually want is even distribution - I may do this with the ruins the way I did with the strategic resources
