### ISSUE TITLE
Can't enter custom map seed in editor after first generate

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#6681]
**To Reproduce**

1. Go to map editor
2. Enter custom RNG seed
3. Generate
  * This works correctly
4. Press generate again
  * This forcibly changes the map seed, making it impossible to generate a map with a custom seed

@SomeTroglodyte it's caused by your commit 996c58e1fb2c68015f4a945450b1706065342e20 by https://github.com/yairm210/Unciv/blob/cec9975b4d0d7dbfa8a709e0d502547d9dc828da/core/src/com/unciv/ui/mapeditor/MapEditorGenerateTab.kt#L56

**Comment by SomeTroglodyte** [comment]
Done on purpose, but I see your point. Any better idea how to prevent repeated generate clicks to always produce identical results? Memory is weak, but maybe a TextArea onChange could reset that "feature"... Go ahead, you can code, right?

**Comment by yairm210** [comment]
After consideration, categorizing as "not a bug". This feature is 'generate map from seed', and that works. If someone clicks 'generate' again after the first one, then chances are they aren't looking to generate from seed, and if they are they can do that.
