### ISSUE TITLE
Can't load map

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#6685]
**Platform**
Android 11

**Version**
4.0.10 patch1

**Describe the bug**
Can't not load map in map editor

![Screenshot_20220504_043931](https://user-images.githubusercontent.com/89069988/166571599-4e8574ab-d23c-49ed-9fec-84b0837c0f2f.jpg)

**Comment by AdityaMH** [comment]
Fix in 4.0.11
