### ISSUE TITLE
Steal sea

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#6686]
I have played Freeciv, civilization (nds version), unciv and i don't see any unit can steal sea. If we have a unit can steal sea we can make a better border on sea. I like editing the border on sea to make it look better and i know there are a lot of people like me. Everytime i see the sea border don't look better i feel uncomfortable and i want to fix it but because the game doesn't have a unit can steal sea so i have to play it all over again. In real life there are some nation can steal sea by using a fleet or protect the sea by build something. Example vietnamese built DK1 to protect their sea against china. Please make a unit can steal sea.

![589eec13-2de2-44e9-9319-d691ec620068](https://user-images.githubusercontent.com/89069988/166574871-f1aaf8a5-e0af-41fd-8467-a7ecda19c146.jpg)

**Comment by heipizhu4** [comment]
This issue should to https://github.com/yairm210/Unciv/issues/3242

**Comment by heipizhu4** [comment]
I've put your issue there, so this issue should be closed. Remember to put these kind of features there next time.

**Comment by heipizhu4** [comment]
> Example vietnamese built DK1 to protect their sea against china.

And please don't mention politcal issues. We still want Chinese players contributing to this project, don't we?

**Comment by saud2410** [comment]
> And please don't mention politcal issues. We still want Chinese players contributing to this project, don't we?

Woah that sounds quite cowardly. I agree that political issue is better avoided. But the reason should not be worry about Chinese. Territory issue between China and Vietnam exists, and imao he didn't sided anybody.

**Comment by heipizhu4** [comment]
@saud2410 I agree with you. So shall we close the issue now?

**Comment by yairm210** [comment]
Unciv is being built by the Civ V spec, which doesn't have this feature. As per our policy - denied for base game.
Should be moddable once #6680 is complete.
