### ISSUE TITLE
Unciv runs at ~5% normal speed when running under the Android Studio debugger

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6699]
You know my rig and OS (hexcore hyperthreaded nuc11 running Mint 20.3).. That's unchanged for over a year. At some point the game slowed down drastically when (Shift-F9) run from Studio, but not when run as jar. Slowdowns on AVD's with debugger connected are also severe. More details in #6468.

I asked a month ago: "Is nobody experiencing the same extreme slowdowns?" - please, I must know the good old "is it just me" question. If it is, that's something I can work with. If it's not, then _UncivServer has to go_ ... into its own executable.

I just merged #6468 into my WIP #6687, and (after a clean build) speed immediately went up by a subjective two orders of magnitude.

**Comment by yairm210** [comment]
Now that there are so many other alternatives to the Kotlin server, I agree. It's unnecessary.

**Comment by xlenstra** [comment]
I have some slowdowns, such as it taking ~2 seconds to select/move a warrior on a large map, but they're not nearly as severe as what you're describing. They also happen regardless of whether I'm in normal or debug mode.
I'm fine with UncivServer being moved to its own executable if that solves the problem for you regardless.

**Comment by SomeTroglodyte** [comment]
> test and fix

Better not. Build environment is the focus, not functionality. But such fixing could get easier.

**Comment by touhidurrr** [comment]
also you can try
```
sudo apt purge --autoremove <any android studio package>
sudo rm rf /usr/<any android studio subfolder>
```
And try reinstalling Android Studio again.
Hopefully that might help.

**Comment by touhidurrr** [comment]
also you can try
```
sudo apt purge --autoremove <any android studio package>
sudo rm rf /usr/<any android studio subfolder>
```
And try reinstalling Android Studio again.
Hopefully that might help.

**Comment by yairm210** [comment]
Maybe we can get rid of it entirely, given the alternatives.
It would be good to have a clear doc of what functions it needs to implement but tbh that could be an OpenAPI spec, it doesn't even need to run

**Comment by SomeTroglodyte** [comment]
>OpenAPI

So we're a RESTful webservice client? Good idea, let's implement the IFileStorage client side for webservices :smile: :+1:

> get rid

:game_die: 🎰 🍀

**Comment by touhidurrr** [comment]
> IFileStorage
I would hope that you guys would hyperlink some docs when you pop up new things like this so that others can know what actually are you guys talking about, sigh.

**Comment by yairm210** [comment]
@SomeTroglodyte 
https://github.com/yairm210/Unciv/blob/822ce5e041240fddf1394006c95b2d69c1d6c50f/core/src/com/unciv/logic/multiplayer/Multiplayer.kt#L25
What is this if not what you requested?
