### ISSUE TITLE
Can't create new Multiplayer Games from Desktop

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6709]
**Platform**
Raspberry Pi OS armhf (32-bit linux arm)

**Version**
4.0.12, 4.0.13

**Describe the bug**
After #6679 i cannot create new games from Desktop in the first place!!!
The Client shows no network error regardless of my internet being turned on or off. It cannot detect network in my Raspberry Pi. Not sure if other Desktops are affected too or not.

**To Reproduce**
Try to create any Online Multiplayer Game from a custom server in Desktop client.

**Comment by Mape6** [comment]
I tested the same procedure on a Windows 10 client with Unciv Version 4.0.13 in a network where you need to go through a proxy to get to the internet.
The Unciv app seems not to use the proxy, that is confiured in the system settings, to check the internet availability.

What do you think if Unciv would ping the configured server from Multiplayer options menu instead of 8.8.8.8? Only if Dropbox is used for Multiplayer, then use 8.8.8.8?

**Comment by alexban011** [comment]
Hmm, are you using a VPN?

**Comment by touhidurrr** [comment]
> in a network where you need to go through a proxy to get to the internet.
The Unciv app seems not to use the proxy, that is confiured in the system settings, to check the internet availability.

I was using my Mobile Hotspot to connect to the Internet from Raspberry Pi. My mobile was in turn using 1.1.1.1 warp app to tunnel its dns queries Cloudflare. Pi should have it's own dns resolver. Dunno which one exactly is being considered as a Proxy. Using 1.1.1.1 warp app or using Wi-Fi.

Are you saying that this only happens to you when you are using a VPN @Mape6 ?

**Comment by alexban011** [comment]
if you have the possibility of compiling the code please try the fix at #6711

**Comment by touhidurrr** [comment]
Ok I checked it again. The issue persists even without any kind of proxy even in 4.0.13 @alexban011

**Comment by alexban011** [comment]
> Ok I checked it again. The issue persists even without any kind of proxy even in 4.0.13 @alexban011

by "4.0.13" you mean the code from #6715 ? So that fix doesn't work for you?
Linux is still the OS we're talking about right?
