### ISSUE TITLE
QoL - Friends list for remembering player IDs

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6716]
**Is your feature request related to a problem? Please describe.**
Every time you want to start a game with friends you need to get their player IDs and paste them in

**Describe the solution you'd like**
Have a way of adding the friends in a list and in NewGameScreen when adding player IDs there can be an option to add from friends list. Easiest way I can think of is to give the user who adds their friend the option to name them, so that we (the code) don't have to keep track of player names and IDs 
To make it clear: When adding a friend you set their name and their player ID. 

In addition the friends list can also remember:
- how many games you've played with X
- how many wins/losses

What do you think ?

**Comment by itanasi** [comment]
Having a friends list with alias+User ID sounds like a nice feature. Dunno about tracking number of games or your record against them though without something like server enforcement. And considering the current state or the server don't forsee that any time soon

**Comment by alexban011** [comment]
> Dunno about tracking number of games or your record against them though without something like server enforcement. 

I was thinking of storing this locally and when you get the victory screen the game checks if the players are in your friends list and if they are it increases the numbers. I don't think this requires a server.

**Comment by touhidurrr** [comment]
> And considering the current state or the server don't forsee that any time soon
We can do a lazy implementation like uploading Users/username files to the server and fetch info from it?
Doesn't look that complicated.
If this feature looks clean to others even I can implement this I guess.
Or it just look out of place?

**Comment by alexban011** [comment]
> So basically you want a friends tab in Multiplayer & Autocomplete in New Game Screen when a friends name is typed i would guess.

Yes, but instead of typing the name it could have a button to display a list of friends and then select the friend you want to add and the game would autocomplete the ID

**Comment by touhidurrr** [comment]
> I don't think uploading to the server is even necessary. I was thinking of creating a file locally which keeps track of this.

Basically saying this cause the topic of Implement this on serverside appeared. To see what others think of this....

**Comment by itanasi** [comment]
I would keep it local and not serversode so that you can easily migrate your friends between servers. There's very little value for the server to host such a list imo except if we wanted to enforce win/loss rankings

**Comment by touhidurrr** [comment]
> win/loss rankings

Imagine a Win / Loss ranking in Unciv implemented on top of Dropbox. 🤣
Dropbox Error 429 x 10 😂

**Comment by alexban011** [comment]
> > win/loss rankings
> 
> Imagine a Win / Loss ranking in Unciv implemented on top of Dropbox. 🤣
> Dropbox Error 429 x 10 😂

Yeah, thats why I was suggesting keeping it local. Even the ranking can be local as it won't really matter if its 100% accurate. I think the only way for it to lose track of the score is when you reinstall the game and/or maybe if you leave the game 1 turn before the other player wins? Unless the game downloads the match even if its not loaded, which I think it might. (Haven't looked at that code yet)
