### ISSUE TITLE
Uniques of Great Peoples and some other units are Not Working

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#6719]
**Platform**
Windows 10 Home 21H2 64 bit

**Version**
4.0.13 from Itch.io

**Describe the bug**
Great People can't perform certain unique actions. For example, Great Prophet can't Spread Religion, and Great General doesn't give +15% combat bonus to units within 2 tiles.

**To Reproduce**
1. Load any existing game (new or old doesn't seem to matter)
2. Generate a Great Person
3. Observe that they can't perform unique actions or give unique bonuses

Saved game data attached shows Great Prophet that can't Spread Religion while in a city.

[The Maya -  119 turns.txt](https://github.com/yairm210/Unciv/files/8645766/The.Maya.-.119.turns.txt)

**Expected behavior**
Great People can provide the appropriate bonuses and actions.

**Comment by xlenstra** [comment]
A few tests seem to show that all great people can preform their actions as normal, except for great prophet and great general.

**Comment by JackRainy** [comment]
It seems the issue is caused by `b258b34c89b7f97aca1ee4506ac857e9f42aa358` :
> Use a UniqueMap to have hashmap finding instead of array iteration and string comparison for MapUnit getUnique(string) - see #6695

**Comment by JackRainy** [comment]
The problem seems to be more critical than expected.
My investigation has shown that all of these uniques _may not_ work after the mentioned commit since they cannot be found in the `UniqueType.values()` list:
```
Fighter: [100]% chance to intercept air attacks
Anti-Aircraft Gun: [100]% chance to intercept air attacks
Destroyer: [40]% chance to intercept air attacks
Zero: [100]% chance to intercept air attacks
Paratrooper: May Paradrop up to [5] tiles from inside friendly territory
Atomic Bomb: Nuclear weapon of Strength [1]
Mobile SAM: [100]% chance to intercept air attacks
Nuclear Missile: Nuclear weapon of Strength [2]
Missile Cruiser: [100]% chance to intercept air attacks
Jet Fighter: [100]% chance to intercept air attacks
Stealth Bomber: Damage taken from interception reduced by [100]%
Great Artist: Can start an [8]-turn golden age
Great Artist: Great Person - [Culture]
Great Scientist: Can hurry technology research
Great Scientist: Great Person - [Science]
Great Merchant: Can undertake a trade mission with City-State, giving a large sum of gold and [30] Influence
Great Merchant: Great Person - [Gold]
Great Engineer: Can speed up construction of a building
Great Engineer: Great Person - [Production]
Great Prophet: Can construct [Holy site] if it hasn't used other actions yet
Great Prophet: Can [Spread Religion] [4] times
Great Prophet: Removes other religions when spreading religion
Great Prophet: Great Person - [Faith]
Great Prophet: Takes your religion over the one in their birth city
Great General: Can start an [8]-turn golden age
Great General: Bonus for units in 2 tile radius 15%
Great General: Great Person - [War]
Khan: Can start an [8]-turn golden age
Khan: Bonus for units in 2 tile radius 15%
Khan: Great Person - [War]
Missionary: Can [Spread Religion] [2] times
Inquisitor: Prevents spreading of religion to the city it is next to
Inquisitor: Can [Remove Foreign religions from your own cities] [1] times
```

For example, besides `Great Prophet` and `Great General`, `Paratrooper` also cannot paradrop now.
If some of them (luckily) are still working, e.g. `Great Artist: Can start an [8]-turn golden age`, it is just because there is another mechanism used for that.
