### ISSUE TITLE
Option to grant independence to former city-state acquired through trade agreement

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#6722]
I finally gained the upper hand in my 150-turn war, and used the opportunity to extract some territorial concessions from my foe. In this case, I asked for control of a city-state that he had captured, and he agreed. My intent was to "turn it loose" - that is, grant its independence, however it went straight to my control without giving me the option of what to do with it.

My memory has proven fallible numerous times, but I believe civ5 allowed me the option of "turning a city-state loose" that I had gained control of by way of a trade agreement. I'm also fairly certain that had I conquered this former city-state by force, I would have had this option, so it seems reasonable to allow this same option with trade agreements.

![Screenshot_20220507-183132_UnCiv](https://user-images.githubusercontent.com/1423934/167278243-052dd721-9d14-41b5-bea4-955cb6f8a091.png)

**Comment by JackRainy** [comment]
Do you have a saved game to reproduce that easily?

**Comment by foolishgrunt** [comment]
Unfortunately I didn't think to keep the save before playing on.
