### ISSUE TITLE
Great Prophet Cannot be Consumed

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#6736]
As seen in the following pictures, the Great Prophet has neither of both of its unique actions; Spread Religion and Create Holy Site. I don't know if the issue also exists in other Great Persons, but it is likely.

![Screenshot_20220510-022241_UnCiv](https://user-images.githubusercontent.com/61744611/167474742-8d25ca0c-7882-4c3f-ba0d-e23467b6ffb4.jpg)
![Screenshot_20220510-022249_UnCiv](https://user-images.githubusercontent.com/61744611/167474755-ac0cf495-a8b3-4c90-8075-e18e2f7b5db5.jpg)

Version is 4.0.13. Latest according to Play Store. This bug only occurred following the update; it never happened before.

**Comment by itanasi** [comment]
Fixed in 4.0.14
