### ISSUE TITLE
Great Prophet Cannot be Consumed

### ISSUE THREAD

**Issue by TheEXAM** [yairm210/Unciv#6737]
As you can see in the following screenshots, the Great Prophet has none of its unique actions, Spread Religion and Create Holy Site.

![Screenshot_20220510-022241_UnCiv](https://user-images.githubusercontent.com/61744611/167477150-c07f46e1-3abb-47e5-a084-2c05f1cf2c97.jpg)
![Screenshot_20220510-022249_UnCiv](https://user-images.githubusercontent.com/61744611/167477154-386a225b-517b-4961-892f-e1fd68f2b1d6.jpg)

Version is 4.0.13, latest in Play Store. This bug never occurred before the update.

**Comment by Ouaz** [comment]
This bug is fixed in 4.0.14 (#6721). 4.0.14 should be released very soon on PlayStore.
