### ISSUE TITLE
Warning: Chipmunk woes

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#6760]
Let's collect and help each other...

Annoyances upgrading to Android Studio Chipmunk 2021.2.1:
- New spam asking for permission to spy - twice, one for sudo, one for normal
- 'desktop' run configuration breaks. Edit -> Under "Use classpath for module" select Unciv.desktop.main instead of Unciv.desktop.
- It seems to auto-optimize imports even with "Settings - Editor - General - Auto Import - Kotlin - Optimize imports on the fly" off and "Settings - Version Control - Commit - Before Commit - Optimize imports" off. Bumblebee didn't.
- Turn off "Open Diff as Editor Tab" under Settings - advanced - version control! Otherwise right-click - "show diff" from e.g. the git pane will crash. Edit: Actually, Show Diff in different ways is a catastrophe, that switch **doesn't really help much**. Haven't found a solution. Some crash, some show up wrong, some are empty but OK if one chooses "Show Diff in new Window" instead - which has its own problems.
- If you get a "Kotlin not configured" message, do not follow the suggestion. Do a build clean, and invalidate caches and restart instead. As always, give it time to finish indexing _and_ do its automatic gradle sync.
- This may not be absolutely necessary, but I do the clean + invalidate cycle every time I see a "A project sync may be necessary for the IDE to work properly" message, too.
- After the Chipmunk upgrade I had my first ever runtime crash due to compilation errors. Yes, a source file was outdated and nevertheless not recompiled. If in doubt, clear your $HOME/.gradle (please if you know the win %localappdata% (probably) path add it to this). Selective cleaning might save download bandwidth (a full clear of this will download >2G) and still help: either leave wrapper/dists + cache/jars* + cache/modules* or clear only cache/build-cache* and cache/transforms*, I'm never sure what is too much or not enough.

**Comment by SomeTroglodyte** [comment]
Not for me - but it seems soeone should clean up debug println()'s in there...
<details>

![image](https://user-images.githubusercontent.com/63000004/169164211-2c8df558-e140-42d5-9221-75225f865348.png)

```
Executing tasks: [:tests:test] in project /home/alice/Work/Unciv

> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :tests:processResources NO-SOURCE
> Task :tests:processTestResources NO-SOURCE
> Task :core:compileKotlin UP-TO-DATE
> Task :core:compileJava NO-SOURCE
> Task :core:processResources NO-SOURCE
> Task :core:classes UP-TO-DATE
> Task :core:inspectClassesForKotlinIC UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :tests:compileKotlin NO-SOURCE
> Task :tests:compileJava NO-SOURCE
> Task :tests:classes UP-TO-DATE
> Task :tests:compileTestKotlin
w: /home/alice/Work/Unciv/tests/src/com/unciv/testing/TranslationTests.kt: (173, 29): Variable 'translation' is never used
w: /home/alice/Work/Unciv/tests/src/com/unciv/uniques/GlobalUniquesTests.kt: (201, 13): Variable 'cityInfo' is never used
> Task :tests:compileTestJava
> Task :tests:testClasses
> Task :tests:test
[] and []
Translation writer took 208ms for Civ V - Vanilla
90.0
true
{Population=, Buildings=, Tile yields=+1 ⚙Production, +2 ⁂Food, Specialists=, Trade routes=-1 ¤Gold, +30 ⍾Science, City-States=, Maintenance=}
{Population=, Buildings=+30 ⍾Science, Tile yields=+1 ⚙Production, +2 ⁂Food, Specialists=, Trade routes=, City-States=, Maintenance=}
BUILD SUCCESSFUL in 41s
12 actionable tasks: 3 executed, 9 up-to-date

Build Analyzer results available
00:13:09: Task execution finished ':tests:test --tests "com.unciv.*"'.
```
</details>

**Comment by OptimizedForDensity** [comment]
Thanks for the info. I think I figured out a way around it. For whatever reason, running tests with the argument "com.unciv.*" doesn't work but running individual folders (e.g., "com.unciv.testing.*") works.

**Comment by SomeTroglodyte** [comment]
As I showed, com.unciv.\* works for me. Any logs/exact errors?

**Comment by GGGuenni** [comment]
After updating to chipmunk, I now get a `Kotlin not configured` message. Configuring Kotlin (Tested with all versions between 1.6.0 and 1.7.0 Beta) results in errors and modified gradle files.
![error](https://user-images.githubusercontent.com/24532072/169491914-1f6582c6-4cdd-458a-b719-24865d42a64a.PNG)

<details>
<summary>Modified gradle files</summary>
<be>

```Patch
diff --git a/android/build.gradle.kts b/android/build.gradle.kts
index 08ed1917a..46af4b5e2 100644
--- a/android/build.gradle.kts
+++ b/android/build.gradle.kts
@@ -1,10 +1,15 @@
 import com.unciv.build.BuildConfig
 import java.util.*
 
+val kotlin_version: String by extra
+
 plugins {
     id("com.android.application")
     id("kotlin-android")
 }
+apply {
+    plugin("kotlin-android")
+}
 
 android {
     compileSdk = 30
@@ -127,4 +132,9 @@ dependencies {
     //   run `./gradlew build --scan` to see details
     implementation("androidx.core:core-ktx:1.6.0")
     implementation("androidx.work:work-runtime-ktx:2.6.0")
+    implementation("androidx.core:core-ktx:+")
+    implementation(kotlinModule("stdlib-jdk7", kotlin_version))
 }
+repositories {
+    mavenCentral()
+}
\ No newline at end of file
diff --git a/build.gradle.kts b/build.gradle.kts
index 67b38c7b7..eb0102ddb 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -10,6 +10,8 @@ configurations.all { resolutionStrategy {
 
 buildscript {
 
+    var kotlin_version: String by extra
+    kotlin_version = "1.6.0"
     repositories {
         // Chinese mirrors for quicker loading for chinese devs - uncomment if you're chinese
         // maven{ url = uri("https://maven.aliyun.com/repository/public") }
@@ -29,6 +31,7 @@ buildscript {
 
         // This is for wrapping the .jar file into a standalone executable
         classpath("com.github.anuken:packr:-SNAPSHOT")
+        classpath(kotlinModule("gradle-plugin", kotlin_version))
     }
 }
 ```

</details>

**Comment by SomeTroglodyte** [comment]
Hmmm.... Should have tried invalidate caches before letting the wizard muck old stuff up. I think that rings a bell, but can't remember clearly. I _might_ have had the same and _automatically_, immediately and without thinking did the Gates on AS.

**Comment by GGGuenni** [comment]
Yea invalidate caches was the obvious way to go I didn't think of... Thanks!

**Comment by SomeTroglodyte** [comment]
> obvious

So it _did_ help... Will list in post 1. Fyi - I got into the habit, whenever there's a prompt to _manually_ gradle-sync, then do build-clean + invalidate instead. Not that build-clean actually does what its name says. Or, OK, it doesn't do what a M$ Visual Studio with a M$ project type would do. Semantics. But it doesn't clear the compiler's cache, and I would expect it to. Ah - another point for the list. And the issue label is wrong -what was I thinking... This isn't an _Unciv_ bug...

**Comment by SomeTroglodyte** [comment]
@OptimizedForDensity  - any update? As I showed, com.unciv.* works for me. Any logs/exact errors? Also - to tun all tests, you chould of course just _omit_ the `--tests` parameter, does that work? If we figure this out we should update the wiki.

**Comment by SomeTroglodyte** [comment]
> "Repair IDE" button in the "File" 

Nope haven't got that - and just learned that Mint blocks screenshots while a menu is open. Alt-Tab too. DOS.

> loses focus

Doesn't sound familiar. Unless you run AS in a VM and leave the VM frame with the Mouse...

**Comment by alexban011** [comment]
> run AS in a VM 

I don't. Maybe its a wayland issue?
https://stackoverflow.com/questions/31698041/cant-edit-files-in-android-studio
Looks like its an ancient issue, so not related to Chipmunk, but that fix doesn't work for me

**Comment by SomeTroglodyte** [comment]
That link is six years old. There _was_ something quite similar, but far more annoying up to BumbleBee, and that is finally fixed (Hangs you didn't notice right away. Typing still worked for a while in that state, but no saving, no menus, no closing the IDE... Didn't react to soft 'End process' either, needed a hard SIGKILL. For me almost guaranteed if leaving Studio open uninterrupted for a week. Gone as I said.)

**Comment by alexban011** [comment]
I just found out that if I minimize Studio and then bring it back on the screen fixes the issue. Weird, but better than closing it and reopening. 
Also I should throw this in here: If I put the pc on sleep with Studio opened, when it wakes up I can't push anymore until I restart Studio

**Comment by itanasi** [comment]
Just got this one when trying to push a branch I created locally. Any ideas?
![image](https://user-images.githubusercontent.com/44038014/170630285-6c52e3b8-d32c-4201-808c-a41a02df22a0.png)

**Comment by alexban011** [comment]
> Just got this one when trying to push a branch I created locally.

This happens to me if I put the pc on sleep and then turn it back on. Can't push until i restart..

**Comment by SomeTroglodyte** [comment]
Perhaps those devs getting that on 'doze should batch themselves a `pushd %LocalAppData%\Google\ && del /S /Q "intellij-git-*.sh"` and park that somewhere readily accessible?

**Comment by alexban011** [comment]
Am I the only one getting really bad memory leaks ? 

![image](https://user-images.githubusercontent.com/21990802/174417415-a01e762b-6df8-4aef-b6e3-9dbcc8b43311.png)

**Comment by yairm210** [comment]
Closing this, since I assume by now everyone has moved to the new version
