### ISSUE TITLE
Better issue page

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6764]
> **BEFORE creating (delete this in the actual issue)**
> 
> Is your feature a gameplay feature from Civ VI, or from BNW? If so, don't open it in the first place - see Roadmap
> 
> Is your feature a gameplay feature from Vanilla Civ V or from G&K? If so, it should go in #4697 - post a comment there!
> 
> Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!
> 
> Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!
> 
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Triggered by lots of not-so-good issues, like #6408 and #6483. I didn't delete the 'delete this in the actual issue' thing because that's the thing I want to change. You know, not everyone enjoys reading these kinds of long articles.

So I went to other projects for ideas for example, osu!(a rythem game)
![image](https://user-images.githubusercontent.com/100454479/167876175-6a6c41e8-2d8c-4368-8707-abaed055fe09.png)

And I found this idea great. How about letting 
```
Is your feature a gameplay feature from Civ VI, or from BNW? If so, don't open it in the first place - see Roadmap

Is your feature a gameplay feature from Vanilla Civ V or from G&K? If so, it should go in https://github.com/yairm210/Unciv/issues/4697 - post a comment there!

Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!
```
into a selectable thing so new issue reporters will be able to go to the right place?

**Comment by yairm210** [comment]
Oh, nice!
