### ISSUE TITLE
failed to load VM runtime library

### ISSUE THREAD

**Issue by BundyBlue** [yairm210/Unciv#6776]
**Platform**
Ubuntu 20.04.4 LTS

**Version**
4.0.15-patch1

**Describe the bug**
AMD64 version trying to access wrong directory.
jre/lib/i386/server/libjvm.so: cannot open shared object file: No such file or directory
Error: failed to load VM runtime library!

Should be: jre/lib/amd64/server/libjvm.so

**To Reproduce**
1. in a terminal run ./Unciv
2. See error

**Expected behavior**
I expect Unciv to run

**Screenshots**
N/A

**Comment by yairm210** [comment]
What distribution medium are you getting your doors from? GitHub, itch flathub?

**Comment by yairm210** [comment]
Unciv-Linux64.zip working perfectly for me on Ubuntu 20.04.4 LTS

![image](https://user-images.githubusercontent.com/8366208/168005181-e1828f58-d3ab-466d-b51c-a37bcbb3f25e.png)

**Comment by BundyBlue** [comment]
Hi, itch. It's installing the i386 version instead of amd64.

**Comment by BundyBlue** [comment]
I see the problem now. Itch downloaded unciv-linux32.zip.

**Comment by BundyBlue** [comment]
OK, itch now gives me 2 options under manage so installed 64bit - all good.
OMG - dumb user error.
