### ISSUE TITLE
Unique Great Tile Improvement replacement not working

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#6777]
**Platform**
idk, this was reported to me via Alpha Frontier's github issues forum. Assumed both Mobile and PC versions apply.

**Version**
Assumedly latest.

**Describe the bug**
In Alpha Frontier, one of the nations has a replacement for the Academy Tile Improvement named Biodome City. Problem is, the Great Scientist of that city still builds Academy instead of Biodome City.

**To Reproduce**
1. Download Alpha Frontier
2. Play as Somatek Biomedical
3. Proceed until acquiring Great Scientist
4. GS will only make Academy and not its replacement, Biodome City

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Replacement improvements actually get built instead of their regular one - I suspect this is also an issue with non-Great Improvements too.

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
This makes perfect sense, add great scientist explicitly creates an academy. This is not subject to change.
You'll need to override the great scientist with another unit that creates the special improvement.

**Comment by carriontrooper** [comment]
ah, alrighty then. Fixed in my mod too.
