### ISSUE TITLE
Feature request: Separate Tileset and Unit Sprite Selection

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#6784]
**Problem:**
Currently, a tileset contains both terrain/tile graphics as well as unit graphics. I would like to be able to separate these in order to mix and match to my taste. For example, I like the Hexarealm terrain/tiles graphics but want different unit sprites. I currently can't achieve this without copying the entirety of Hexarealm to a new mod which also contains my unit sprites.

**Proposed solution:**
A drop-down menu for both tilesets (meaning the terrain, features, tile improvements, etc.) and unit sprites (meaning the civilian and combat units that move around the map).

![Tileset and Sprite Selection](https://user-images.githubusercontent.com/56904240/168128438-6209cffa-5fb0-4027-910d-0a9516ec8b86.png)

**Comment by SomeTroglodyte** [comment]
Interesting.
- Images sourced from different mods can and will override one another. Problem: Order is only half-deterministic. Base always has lowest precedence, then permanent visual, then game-specific mods. The latter are deterministic but in a non-transparent way: Order of selection, the last selected wins. Perm v. are unpredictable and may even change order on save-quit-relaunch-load. Is that an actionable problem - or could a controlled overriding order be useful?
- So your example isn't really a problem as HexaRealm is base now so you can reliably override.
- In a path like TileSets/<set>/Units/* or TileSets/<set>/Tiles/* it's thinkable and not too complicated to have differing <set> parts for the two - but isn't the precedence approach maybe better?
- Would a _voluntary_ ModOptions.visualPrecedence field work? Built-ins get 0, 5Hex sets 5, and if you define 10, your graphics win reliably, if you define 2 you'd only fill any gaps in 5Hex (still assuming all selected via perm visual not on newgame)? Trust modders to cooperate?

**Comment by letstalkaboutdune** [comment]
Interesting, but probably not that important anymore (at least for my use case) now that HexaRealm is part of the base. I'm not sure if others are also making sprite sets and users might want to change between several set of unit sprites while keeping the tiles from HexaRealm, FantasyHex, or others. 

[This other issue I created](https://github.com/yairm210/Unciv/issues/6838) about giving the user more customization control over unit icons would be much more helpful and probably easier to implement.
