### ISSUE TITLE
Feature request: Embark Strength Listed in Civilopedia

### ISSUE THREAD

**Issue by OptimizedForDensity** [yairm210/Unciv#6785]
It would be nice if the embarkation civilopedia entry listed the embark strength for each era since otherwise you would need to look into the json files to see what its values are.

**Comment by SomeTroglodyte** [comment]
Would be technically easier if we already had an Eras category. Adding one... Straightforward, and an Era entry has quite a lot of data by now, though most refers to starting in that Era, which I wouldn't necessarily want to display. name, color, researchAgreementCost, 
 baseUnitBuyCost, embarkDefense, CS boni, uniques... Would that look good? Or does the category buttons scroller get too crowded?

**Comment by OptimizedForDensity** [comment]
That's probably a better idea to list all the era-dependent information instead of just embark strength, and it could probably go next to the difficulties category that's already in the civilopedia.

**Comment by SomeTroglodyte** [comment]
<details><summary>How about...</summary>

![image](https://user-images.githubusercontent.com/63000004/168158709-3e8e397a-3085-4d75-b9cc-b7d61bc64546.png)
</details>

**Comment by OptimizedForDensity** [comment]
It looks good!

**Comment by SomeTroglodyte** [comment]
> [OptimizedForDensity](https://github.com/OptimizedForDensity) commented [23 minutes ago](https://github.com/yairm210/Unciv/issues/6785#issuecomment-1125456068)
> [SomeTroglodyte](https://github.com/SomeTroglodyte) commented [22 minutes ago](https://github.com/yairm210/Unciv/issues/6785#issuecomment-1125456777)

Look how fast I coded that :racehorse: :rocket: :mountain_biking_man:
