### ISSUE TITLE
Add City States.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#680]
- [x] Add city state type civs

- [x] Make city states not expanding by any means

- [x] Add influence between player and city states

- [x] City states give bonus according to their types, Cultured

- [x] City states give bonus according to their types, Maritime

- [x] City states give bonus according to their types, Mercantile

- [ ] City states give bonus according to their types, Militaristic

- [ ] Ability to liberate city states for huge influence bonus

**Comment by yairm210** [comment]
This is not yet ready for Player consumption.

Minimum requirements:

- [ ] Unique popup when encountering a city state ( currently 
![image](https://user-images.githubusercontent.com/8366208/56982271-98d07280-6b89-11e9-85be-a35f1ced431c.png) , direction is to 
![image](https://user-images.githubusercontent.com/8366208/56982362-d3d2a600-6b89-11e9-9f20-209b68570fda.png), obviously more basic than that though
)

- [ ] "Gift gold" button in DiplomacyScreen.getDiplomacyTable
- [ ] "Capitol" sign to mark city states on map (a la 
![image](https://user-images.githubusercontent.com/8366208/56982577-4f345780-6b8a-11e9-80d6-89b5c110d96a.png) , I think https://thenounproject.com/search/?q=capitol&i=125525 looks good)

**Comment by yairm210** [comment]
Future goals (not minimum requirements but simple enough):

- Influence should decrease when declaring war on them
- Should be able to move through their tiles but lose Influence per turn for doing so (-12), makes a unique AlertPopup
 - Effect of being friendly should increase by Era, and influence per gold donation (in orig it's always 250, 500 or 1000) should decrease by Era (starts at 1/10 IIRC and goes down, not sure on how much it goes down)
- They SHOULD NOT be able to build Wonders!

**Comment by ninjatao** [comment]
Minimum requirements done.

**Comment by yairm210** [comment]
You don't seem to get a unique popup when encountering a city state

**Comment by ninjatao** [comment]
For now maybe city-state encountering popup only shows its type?

**Comment by yairm210** [comment]
It's unclear from the city-state diplomacy screen what you'll get if you pay them enough, and how much imfluence you'll get from paying them - confusing for those that don't know

**Comment by yairm210** [comment]
After a bunch of changes I feel it's ready now
I'll move the improvements to a separate issue
