### ISSUE TITLE
F-droid not updating?

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6804]
**Describe the bug**
I decided to download unciv on my phone, but it only updated to 4.0.13. It shouldn'take that long to update.
So I went to github and found this:
![image](https://user-images.githubusercontent.com/100454479/168426213-2676c748-24c2-4603-bb94-1fcaece8eddc.png)

**Expected behavior**
F-droid should be able to update regularly.

**Comment by yairm210** [comment]
F droid is updating.
We don't control its update schedule.

**Comment by SomeTroglodyte** [comment]
Yes, even after you can see in their yml that they picked up the release tag, it'll take days. Take it up with them if you want. Do notify _us_ if it gets, say, two weeks or more behind, if you would, thank you.

But an extra thank you for the tip that the button graphic is broken "img.shields.io" redirects to "https://camo.githubusercontent.com/***" strange thing. Does that service have documentation? Hmmm...

F-Droid is lying, their API indeed lists zero packages: https://f-droid.org/api/v1/packages/com.unciv.app

**Comment by SomeTroglodyte** [comment]
For the curious: This has moved forward to [this diff](https://gitlab.com/fdroid/fdroid-website/-/merge_requests/812/diffs)

**Comment by SomeTroglodyte** [comment]
... And now the F-Droid API json is fine, [but the shield didn't update](https://github.com/badges/shields/issues/7977) ...

**Comment by SomeTroglodyte** [comment]
... After some enjoyable exchanges I'm confident that small badge will resume properly updating soon. Nice to see people cooperating without much fuss!

**Comment by SomeTroglodyte** [comment]
[The badge ![badge](https://img.shields.io/f-droid/v/com.unciv.app)](https://img.shields.io/f-droid/v/com.unciv.app) is now fine. F-Droid builds being by now three releases behind is another matter entirely. They have successfully built 709 (4.0.15-patch2), the metadata yml _is_ current at 710, but public is still at 706. That's just the way F-Droid ticks.
