### ISSUE TITLE
"Autocracy Complete" policy unit attack bonus does not work

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#6832]
Completing the Autocracy policy branch is supposed to give `[+25]% Strength <when attacking> <for [Military] units> <for [30] turns>`.

It has been reported on Discord by Sullien#8946 and MissValerie#4629 that this bonus either does not work or doesn't show up in the battle screen on 4.1.0. I have not investigated this.

Also just a note: I think Civ 5 changes the turn amount depending on what has been used as `GameSpeed`, so probably also for this..

**Comment by SomeTroglodyte** [comment]
Um, dumb question - if I increase the deprecation severity of a unique now, then after it's public the user updates to that code, then loads a game with a mod containing that error-deprecated unique... What kind of warning if any will they get??? I know creating new games is covered, but continuing one - must be.

**Comment by SomeTroglodyte** [comment]
Info to OP and anybody else listening - this will not magically fix saved games where the bonus from Autocracy Complete has already been missed. Only games _getting_ Autocracy Complete with the fix in will improve.
