### ISSUE TITLE
Feature request: Render map units on top of cultural borders

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#6837]
**Problem:**
Unit sprites render beneath city cultural borders, blocking units from view. See the Archer in the example below.

![Example](https://user-images.githubusercontent.com/56904240/168669344-b8c5d27e-6936-4021-9ab8-4c2d42b4e64d.png)

**Proposed solution:**
Render units on top of the cultural borders so they are not blocked from view.

**Comment by SomeTroglodyte** [comment]
<details><summary>Screenie</summary>

![image](https://user-images.githubusercontent.com/63000004/170588762-320cddc2-c34f-465a-a0bd-fab8ecd29091.png)
</details>
Not sure about perf impact though. What exactly was your screenie made with?

**Comment by letstalkaboutdune** [comment]
> 

It was made a couple builds back, using my unit sprite set AbsoluteUnits (available in game as of yesterday).
