### ISSUE TITLE
Religion founder's belief "Ceremonial Burial" does not work

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#6868]
**Version**
4.1.1

As reported by Vsynk#7904, the +1 happiness per global city followed does not work.

**Comment by SomeTroglodyte** [comment]
Wrong. It _**does**_ work, but it's not displayed in the top bar immediately after founding.
Topbar right after founding:
![image](https://user-images.githubusercontent.com/63000004/169608507-5fffe70a-1765-4a1f-95be-2098cfb53c8c.png)
Overview:
![image](https://user-images.githubusercontent.com/63000004/169608443-bd367c46-d202-4c14-ae51-1b27fac430d6.png)
