### ISSUE TITLE
Specific Civ Placement on Map Editor

### ISSUE THREAD

**Issue by NickNoSkills** [yairm210/UnCiv#687]
I am currently working on a map of the real world, and it would be annoying to have civs spawn in random areas, so it would be nice if we could set specific civs to spawn in a specific tile that can be set in the map editor, so, for example, Russia does not spawn in Africa.

**Comment by yairm210** [comment]
Interesting
Not trivial and also not really prioritized, so I won't be doing this soon, but this will be done eventually :)
