### ISSUE TITLE
some question about language

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/UnCiv#689]
I have some problems:
1.the basic resource and the luxury resource both have a resource named"Gold", it is very confused,I advise the basic resource named"gold" and the luxury one named "Gold".Although there is no problem in English. 
2.there is a command called "construct improvement" including "Remove Forest",The sentence does not read smoothly in English.
3.the road or railway can't be removed.
4.When I play game by myself,it's very good,with the meantime,playing with AI often make it collapses. I think diploma system have some problems. 
5.the font in chinese used in this game is 10M,can we change this with droidsanfallback.ttf(3m)?using the system font is also a good choice. second,we don't need read the entire traslations.json for font,we only read some usually font for freetype drawing. at last,we can change language except civilization wiki,please solve it. 
I'm a Chinese, and not programmer, so my English is not good. If my words are wrong,please pardon me.Thank you.

**Comment by yairm210** [comment]
1. You are correct, I can think of a solution even though I don't like it very much I see this is a problem that needs to be solved 
2. I'll check it out
3. Correct, this is an open issue
4. I'm working on the diplomacy system, but making an AI that can beat human players is super hard on such a complex game :/
5. Absolutely, can you send a link to the font?
Fallback to the default is not an option with the given framework from what I've gathered

Didn't get your last point?

**Comment by lishaoxia1985** [comment]
@yairm210 thank you very much. I have another problem. 
1.in playing the game time the app downs the font,we must do CRC, not to do this may lead to  that app can't run if font can't be downloaded or the font file is not as same as the original one. the  best method is put the font file in game package,it's my suggestions,but the app volume may enlarge. 
2.when we touch the setting screen's"hide"or"show"button,the language will be changed. 
3.about font library,i have a method but I can't do it. the method is that:
   before compile the apps according to all files's content in file folder"json" we create a font libary file,this files include all characters which we use in the game. but we must use command tools create it because the translatinon files(not only translation.json,there are other files about language)  often update. I'm not a programmer,but I think you can do this.

**Comment by yairm210** [comment]
I think almost everything (except the very first point, Gold resource vs Gold for buying things in translation) have since been answered and/or resolved, so I'm closing this
