### ISSUE TITLE
The latest version has a black screen on Xiaomi's Android 10.

### ISSUE THREAD

**Issue by MGLSIDE** [yairm210/Unciv#6892]
Unable to enter

**Comment by SomeTroglodyte** [comment]
Now this is as unhelpful as it can get. How are we supposed to reproduce? I have Xiaomi hardware here, but they're all system-wiped and Miui-free.

We would need system logs. There's at least two ways to get them without rooting your OS, but for both you would need a PC and be able to allow debugging from that PC (which is in AOSP but some OEMs may hide it).
1. Big: Install Android Studio, clone project and stuff, connect to your phone, enable debugging, start debugger, look at Logcat tab.
2. Small: get yourself a working adb on the PC, install [MatLog](https://f-droid.org/de/packages/com.pluscubed.matloglibre/) and follow directions. It will tell you how to grant a _specific_ log access permission to it using adb.

**Comment by heipizhu4** [comment]
Just fore more information, my friend reported that GIONEE S10B, android 7 cannot install 4.1.0 but is able to install and run 4.0.15. No system log can be collected, though.

**Comment by yairm210** [comment]
Unreproducible, no further reports of this sort were made.
