### ISSUE TITLE
The game crashes when trying to liberate Zazinbar

### ISSUE THREAD

**Issue by angelss197200** [yairm210/Unciv#6897]
it happens in arch linux and android 11

https://mega.nz/file/BYRnnaAS#pQNGTnnhnaEurzs1Ryvr48R6xB_bLkkX6n_JE0sm6Fs

**Comment by yairm210** [comment]
We have a bug template *specifically* so we can get detailed information.
If you can't be bothered to fill in basic data then I can't be bothered to deal with this bug. 👿

**Comment by angelss197200** [comment]
ok
i just did it this way because the app closes in android and i can copy the error in plasma
