### ISSUE TITLE
Make sure a civ always has a capital

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#6910]
In #6844 there are a bunch of exceptions because a dead civ that is liberated does not get a capital (at the correct time?). The fix implemented in #6889 checks for a civ not having a capital and handles it properly.

However, #6889 didn't fix the source of the problem, that the capital does not exist even though the civ has cities. So this should probably be fixed, at which point you don't have to check both for any city existing *and* a capital existing.

**Comment by SomeTroglodyte** [comment]
... or like I said - plan supporting a mod where Palace destruction and the race to recover before the lacking Palace boni do you in is part of the challenge? That would mean all calls need to be hardened, the move capital code needs to be moddable (Palace.uniques += "Automatically moved when conquered" or ModOptions or...), and the move must silently ignore when it's not able to clean up an old capital....

**Comment by yairm210** [comment]
I think that with SeventhM's changes we can close this as no longer relevant
