### ISSUE TITLE
Multiplayer Status Display

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#6914]
Introducing...

## A new multiplayer status display for multiplayer games

![image](https://user-images.githubusercontent.com/2777158/169715387-2f918260-a339-4cbe-b402-41438ec2619e.png)

These are the features:

### Update indicator

Instead of this ugly, control-removing overlay:

![image](https://user-images.githubusercontent.com/2777158/169715431-9826938d-9de8-4075-8335-4208d7b3d7aa.png)

the multiplayer button simply changes like this for the duration of the update.

https://user-images.githubusercontent.com/2777158/169715612-efe30699-e3de-4e0e-ae21-7e87f439220e.mp4

No full screen overlay, you can still look at whatever you want!

### Automatically check for your current turn in other games in the background

In addition to checking if your current game updated, we now also check for all other games! If another game updated, this is how it'll look like:

https://user-images.githubusercontent.com/2777158/169716733-c6880dba-55ef-4557-8adc-c8f3a136dfcd.mp4

If there is more than one game, it'll show you that as well:

![image](https://user-images.githubusercontent.com/2777158/169716752-4059c641-010d-4164-a51b-e5e09895569c.png)

### Check the status and load other games ingame

If you press this button, this is what will greet you:

![image](https://user-images.githubusercontent.com/2777158/169716837-b8e7f5c5-c079-4b7b-abe7-42fd5bd87b72.png)

A list of your multiplayer games and their current status! And you can directly load into another multiplayer game from here, too!

### Settings

![image](https://user-images.githubusercontent.com/2777158/169719580-b5cf3d60-6325-4c48-9d35-fbd4c9a53206.png)

You can configure to show this button in singleplayer games as well! By default, it'll be hidden in singleplayer games. You can also set how often you want to update everything.

**That's it! Please add any feedback below or write me `@Azzurite#2004` in Discord :)**

**Comment by touhidurrr** [comment]
Also for more than 2, I suggest you make it look like somthing like android notifs.
Put the number of active games inside a circle and make its color something flashy maybe.

**Comment by touhidurrr** [comment]
![example image](https://gadgetstouse.com/wp-content/uploads/2021/04/Remove-Red-Number-Notifications-from-App-Icons-on-iPhone-2.jpg?ezimgfmt=ng%3Awebp%2Fngcb2%2Frs%3Adevice%2Frscb2-1)

I was talking about these. Numbers inside colorful border.
