### ISSUE TITLE
Some menu screen buttons make a louder, diffrent sound

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6927]
**Platform**
Arch linux 5.17.9-arch1-1
Android 11 - Samsung A52s

**Version**
4.1.0 

**Describe the bug**
The new game and world editor buttons make a louder and diffrent sound than the rest of the buttons.

**To Reproduce**
1. Go to 'main menu'
2. Click on 'new game/world editor'
3. Listen to the sound

**Expected behavior**
The sound should be the same as for the other buttons 

It kinda sounds as if its trying(and succeding) to play the sound multiple times

**Comment by alexban011** [comment]
Yeah. Looks like its playing the "slider.mp3" sound, but twice

**Comment by SomeTroglodyte** [comment]
Could well be. The UncivSlider was built to be silent for the _initial_ value set. If that regressed, those would be the screens.

**Comment by alexban011** [comment]
Yeah, looks like if I remove the sliders from the screen it doesn't play the sounds. It definitely plays the sounds when the sliders are created.

I have found the solution: Just put the initial value as a parameter when the slider gets created. 

I'll do it tomorrow cause I tested this on the nextTurnConfirmation branch cause I'm lazy

**Comment by SomeTroglodyte** [comment]
> Just put the initial value as a parameter when the slider gets created.

That's what I meant - every _other_ programmatic value change is a slide, only the constructor one should stay silent. I broke that rule myself in Map Editor??? Embarrassing.
