### ISSUE TITLE
I request the following merge...

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#693]
I kindly request the merge of the following pull request: https://github.com/yairm210/UnCiv/pull/607

**Comment by yairm210** [comment]
There's a reason I didn't merge it, that's because I prefer to add them when I implement the promotions, rather have them waiting in a merge request than be 'dead json' in a file

**Comment by Smashfanful** [comment]
Ok, sorry about bothering you. Guess I'll close the pull request, then.

**Comment by yairm210** [comment]
No, I want it open, so I can see that there's still stuff to do for it =)
