### ISSUE TITLE
Citizen management issues

### ISSUE THREAD

**Issue by OptimizedForDensity** [yairm210/Unciv#6939]
**Platform**
Android and Linux

**Version**
4.1.2-patch1

**Describe the bug**
2 related issues
* Spectators can reassign citizen focus in cities (for example, switch from food focus to gold focus and avoid growth)
* Players can reassign citizens in puppeted cities while in Civ 5 these cities are switched to gold focus and are unable to be changed until annexed (https://civilization.fandom.com/wiki/Conquered_cities_(Civ5)#Puppet_cities, https://www.carlsguides.com/strategy/civilization5/war/annex-puppet-raze.php)

**To Reproduce**
1. Start a game as a spectator
2. Change the focus of a city

For the second issue
1. Puppet a city
2. Change the focus of the puppet

**Expected behavior**
* City focus should not change in either case
* Puppeted cities should be locked into gold focus

**Comment by alexban011** [comment]
> Spectators can reassign citizen focus in cities 

they can also move units around (including barbarians)

**Comment by itanasi** [comment]
This shouldn't be closed yet. You can still affect Puppeted Cities
