### ISSUE TITLE
Question: Why are some lategame winconditions not triggering (vs AI)

### ISSUE THREAD

**Issue by ThiloteE** [yairm210/Unciv#6949]
I am turn 533 and won by time victory.

I wonder what the requirements for other win conditions are. Going by ingame Civilopedia, of course, I also could win by eradicating my last opponents militarily, but I don't want to :D

- I researched the tech, but can't build United Nations. I am currently neutrally aligned and in allied relationship with last civilizations on the map.
- I have Spaceship factories all over the place, but there is no unit or building that is called "spaceship part" for me to build
- Completing 5 social policy trees did not trigger the win either.

**Comment by ThiloteE** [comment]
**Info:**

Android 10
F-droid, version 4.1.1-patch2

**Comment by alexban011** [comment]
> I have Spaceship factories all over the place, but there is no unit or building that is called "spaceship part" for me to build

I think you have to build the SS parts in the city where you built the apollo program (could be wrong though). They should appear as either Units or Buildings, can't remember 

> Completing 5 social policy trees did not trigger the win either.

You need to build the Utopia Project, which you get after finishing 5 policy trees

**Comment by yairm210** [comment]
Without a save file it's impossible to know what happened, but this sounds like you just didn't meet the requirements.
It's possible you didn't even allow those soon conditions

**Comment by SomeTroglodyte** [comment]
> need to build these in the capital

Nope, and you don't need SP factories either. You build them as units, e.g. the SS Engine, move them into the capital hex, and use the unit action add to spaceship. Can be disabled at new game. Mods redeclaring them as buildings might still work, or might not.

**Comment by ThiloteE** [comment]
Thank you for the feedback. Maybe I had it deactivated at the start, don't remember.

Here two save files:

[Mongolia - 494 turns.txt](https://github.com/yairm210/Unciv/files/8785561/Mongolia.-.494.turns.txt)
[Mongolia - 534 turns.txt](https://github.com/yairm210/Unciv/files/8785562/Mongolia.-.534.turns.txt)

To clarify: I don't see spaceship parts like the SS Engine in the list of units. I went through all the cities and none can build them. Same for United Nations and the Utopia Project.

**Comment by alexban011** [comment]
I believe you didn't enable any victory other than the time victory

**Comment by ThiloteE** [comment]
Alright. Thanks. Closing this for the time being. Going to play another game and see if I can reproduce. Might take a few weeks though haha :D

**Comment by SomeTroglodyte** [comment]
The victoryTypes aren't mentioned in Json gameParameters (`gameParameters:{difficulty:Chieftain,players:[{playerType:Human},{},{},{}]}`), so they should be default, which is - none???? NewGame shouldn' even allow a game start like this - must be ages old, older than #6161.
But I see a bug: Mongolia has a 'Build United Nations' quest going, which it shouldn't with no diplo victory allowed.

**Comment by ThiloteE** [comment]
I tried a new game. Am currently on 4.1.3, but I think I started with 4.1.2

All works well.
- I managed to build United nations and got voted world leader, which triggered the win.
- I played on; AI managed cultural victory; No win/loss was triggered from that.
- I played on; I succeeded in finishing the Apollo Programm (was able to build SS units). No additional win/loss was triggered from that. (At least I think I finished it before AI managed cultural victory, but I am not sure).


- I played on; At one point I checked `victory status` and now it also shows detailed statistics in `Our status` and `Global status`, which in my past game was just empty space :) It shows I have lost the game, even though I won it. I guess AI Culture was overwriting my prior win-status.


Anyway, this issue is definitely **SOLVED** in later versions of the game :)

**Comment by SomeTroglodyte** [comment]
Yes, "just another turn mode" should store the victory in saved game state and suppress any further victory triggers, that's been on my list for a long time. But then again you're not _supposed_ to really play on. Good to hear Diplomatic victory works, I have a doubt on that on some list as well, but not checked for some time... :+1:

**Comment by olmo42** [comment]
Hello unciv community,
I still have similar issues as @ThiloteE wrote back then.

I did the "Globalization" research but there is no United Nations available to build. Same for the Utopia project after competing five policy trees.

Currently I am on version 4.4.15-patch1 from F-Droid on Android 13.

I cannot figure out how to upload the Savegame, but I checked the values that were discussed above: 

createdWithVersion:4.1.4-patch1

gameParameters:{difficulty:Chieftain,players:[{playerType:Human},{},{},{}]}

AFAIR this is the first game I started in Unciv using the Quickstart button in the main menu. Could this be somehow related to the non working victory conditions?

**Comment by yairm210** [comment]
Upload game by copying to clipboard in load game - copy to clipboard
I don't remember if diplomatic victory is enabled by default, I'll check later

**Comment by olmo42** [comment]
Let's see if posting per email and attaching the savegame JSON file works.

Copy to clipboard results in a pretty long cryptic looking string. Should I post this as a comment?


Am 20. Februar 2023 16:15:46 MEZ schrieb Yair Morgenstern ***@***.***>:

**Comment by olmo42** [comment]
I switched to PC now to upload the file and I might have figured out why this did not work in my Android browser. (Githib does not accept .json file extension but unfortunatelly there was no message about that on Android for me.)

So hopefully here is my corresponding savegame: [The Netherlands - 312 turns.json.txt](https://github.com/yairm210/Unciv/files/10787054/The.Netherlands.-.312.turns.json.txt) Maybe you can figure out any relations about those victory conditions.

**Comment by olmo42** [comment]
Hey, thanks. Cultural victory worked and I was also able to build the UN! 👍

I tried to spread the religion of the Flying Spaghettimonster, but it didn't work that well, as I did not really get all the religion game mechanics yet. 😕
