### ISSUE TITLE
Feature request: possibility to zoom in and out slightly in tech screen

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6950]
It would be nice to be able to zoom a little bit out in the tech screen to see more at once 

Min zoom would be the current zoom
Max zoom would let you see all techs on the vertical axis 
(or the other way around if it looks good)

What do you think?

**Comment by yairm210** [comment]
Tried this so many times...

**Comment by SomeTroglodyte** [comment]
#5182 if you need inspiration.. Or de-spiration.

**Comment by alexban011** [comment]
yeah.. the issue still happens, maybe I'll try it some other time, but I'll close the issue
