### ISSUE TITLE
Feature request: Citizen Management Improvements

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6955]
List of TODOs that I didn't get around to:
- [ ] Make resource weights (see Stats.applyRankingWeights()) JSON-able to give modders access and future BNW support
- [x] Make ScrollPane to support smaller resolutions, or ExpanderTab. Integrate with StatsTable
- [ ] AI usage of Focuses
- [ ] More speed improvements
- [ ] Great Person Focus

**Comment by joendter** [comment]
would be nice to be able to modify the weights of the different ressources manually ingame as well, to create custom focus presets

**Comment by SeventhM** [comment]
I'll unstale with a comment, but I'm not sure if this should get a label to avoid stalling. Also, I'm not entirely sure on some of these (AI stuff should probably get its own separate issue, great person focus is probably a whole subject in its own right, etc.)

**Comment by itanasi** [comment]
I think main quick change would be JSON support.
GPP Focus should be folded into the GPP-per-City overhaul
