### ISSUE TITLE
Feature request: more music 

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6958]
The current music is really nice but its only 1 song. Is there a reason why we don't have more?

**Comment by yairm210** [comment]
I think the current music from non-mods should be removed in fact, mods do a mich better job overall

**Comment by SomeTroglodyte** [comment]
> current music should be removed

Had the idea too - But wouldn't that leave some new customers a little stranded on the Options-Sounds tab?

**Comment by SomeTroglodyte** [comment]
Go ahead. Brainstorm away.

Maybe a dedicated unciv-music repo "topic"??? Or the ability to search for mods having both "unciv.mod" and "music"? Ideas how to legally lead people to [scraper tools like these](https://github.com/SomeTroglodyte/Scratchpad#demos)? (for one of those there was already an [intrepid](https://github.com/ArchDuque-Pancake/Civ-V-Leader-portraits) to publish the result ignoring licensing uncertainties - which is OK, it's on him)
