### ISSUE TITLE
UI issue: main menu world is too small for large resolution

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6959]
If you select the highest resolution the world in the main menu is a couple tiles short on the x axis

![Screenshot_20220526-162604_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/170496865-d85de754-4479-4a74-96ef-2d0aca43152b.jpg)

Proposed solution: increase the size by a couple of tiles

**Comment by yairm210** [comment]
I think it looks fine as it is.
This background nap already takes up enough RAM as is.
I'll wait for other opinions though.

**Comment by SomeTroglodyte** [comment]
The calculation how much is needed can perhaps be improved... I thought to look into it - not worth it I decided back then.

**Comment by SomeTroglodyte** [comment]
Solved
