### ISSUE TITLE
Citizen Managment focus issue/question

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6964]
**Platform**
Android 11

**Version**
4.1.2

**Describe the bug**
In the screenshot below, production focus is selected
![Screenshot_20220526-180854_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/170522120-2638b69b-e542-4677-9864-d4876380571c.jpg)

But in the screenshot below I can get a higher production
![Screenshot_20220526-180912_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/170522354-9cf4f591-6a3c-48e4-bd87-dcfa08d472a0.jpg)

Aditionally in the screenshot below I can get even higher production, but with population loss
![Screenshot_20220526-180921_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/170522457-7c1979b2-1524-4dec-970b-ebee69261361.jpg)

Shouldn't it automatically put the citizens like in the second/third screenshot?

@itanasi

**Comment by yairm210** [comment]
Looks like a non-issue to me, unless you can figure it a way to get the optimal solution without checking every single combination
