### ISSUE TITLE
Feature request: tooltip to tell the player why a button is disabled

### ISSUE THREAD

**Issue by ofetios** [yairm210/Unciv#7002]
First of all I don't know if this is really possible, but

Some buttons are disabled but the user doesn't immediately know why its like that.

My suggestion:
~~Make .disable() into .disable(reason: String = "", screen: Basescreen) which creates a ToastPopup with the text in the reason variable.~~

Opinions?

**Comment by SomeTroglodyte** [comment]
You'll see - that will spam your screen full of toasts. You'll be out of butter and marmalade in no time.

Imo that should be, if at all, done on the level of the individual button in question - any you didn't name any. I... can't think of an example. Empire Overview pages maybe - but those are _obvious_...

**Comment by sockybob** [comment]
Maybe it would be better to display the tooltip/toast/etc when user tries to press the disabled button

**Comment by alexban011** [comment]
> Maybe it would be better to display the tooltip/toast/etc when user tries to press the disabled button

Thats what I meant but forgot to mention :)

**Comment by alexban011** [comment]
> You'll see - that will spam your screen full of toasts. You'll be out of butter and marmalade in no time.
> 
> Imo that should be, if at all, done on the level of the individual button in question - any you didn't name any. I... can't think of an example. Empire Overview pages maybe - but those are _obvious_...

Actually yeah my suggestion won't work. Forgot that disable() isn't called when the button is pressed

**Comment by SeventhM** [comment]
Closing as vague. Many things tell you why they aren't possible now. And using Toasts for this is simply not a good option here. Should probably be reopened with more details
