### ISSUE TITLE
Command 'wait' is not translatable

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#7019]
**Version**
4.0.12 - current version

**Describe the bug**
The command 'wait' implemmented in #6896  isn't able to translate.

**To Reproduce**
Go to [template.properties](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/template.properties)  and search `Wait = ` and you'll know it's not translatable.

**Additional context**
Already made a simple attempt in #7006, and it failed (as expected).

**Comment by Mape6** [comment]
Maybe your branch is too old. 4.0.12 is not the current version. Unciv is already at 4.1.5
What if you create a new branch with a fresh pull from Unciv master and then create the PR?

**Comment by Mape6** [comment]
I created a new PR, lets wait what happens
#7021

**Comment by JackRainy** [comment]
Closed by #7021
