### ISSUE TITLE
Feature request: Happiness related ideas

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#7022]
Make Happiness/Unhappiness icon change depending on how much of either you have;
![zz](https://user-images.githubusercontent.com/30041793/171205356-4a1d03d0-0ac2-4767-81f8-f13932ba0966.png)
maybe a special one when during a golden age

separate luxury resources from resource tab and add more info on current unhappines/happiness, list currently applied penalties/bonuses caused by the level of happiness in an empire. Maybe specify which city demands which luxury resource and display available ways to get them (resource X is owned by city state Y, resource X can be traded from civ Z).

**Comment by SomeTroglodyte** [comment]
Nice icons, I'm all for them. Got creditable sources compatible with our license? Or if you painted yourself either vector or 100x100 antialiased or at least 400x400 ones (plus the linkable license agreement in form of "I hereby place these in the public domain" or somesuch :smiling_imp: )?

More lists - what I've seen lately makes that smell like tedious _work_. There's a little on Empire Overview for happiness _source_ but not effect, and what's in City left side Info is incomplete...

Resources - I had the idea to make most cells in the Empire Overview Resources clickable - and one on the WLTK- column would do something akin to your idea... Maybe someday.

**Comment by ravignir** [comment]
> Nice icons, I'm all for them. Got creditable sources compatible with our license? Or if you painted yourself either vector or 100x100 antialiased or at least 400x400 ones (plus the linkable license agreement in form of "I hereby place these in the public domain" or somesuch 😈 )?
> 
> More lists - what I've seen lately makes that smell like tedious _work_. There's a little on Empire Overview for happiness _source_ but not effect, and what's in City left side Info is incomplete...
> 
> Resources - I had the idea to make most cells in the Empire Overview Resources clickable - and one on the WLTK- column would do something akin to your idea... Maybe someday.

these icons are just worth 5 minutes of MS Paint - to visualise my idea XD
I am going to make vector ones, i think.

**Comment by yairm210** [comment]
Closing as 'not in roadmap' as part of our cleanup
If anyone wants to do this fine, but I'm not planning on it
