### ISSUE TITLE
Crash when liberating citystates

### ISSUE THREAD

**Issue by sinister-crow** [yairm210/Unciv#7029]
My game crashes when I try to liberate a captured citystate from the AI. Single player, Android 12, Xiaomi device, MIUI 13.0.6.0.

![IMG_20220531_215551](https://user-images.githubusercontent.com/88876054/171273947-5235c6c5-3e9a-4cbc-8d56-6278254232b9.jpg)

**Comment by sinister-crow** [comment]
4.1.1-patch2

**Comment by alexban011** [comment]
yes, very likely already fixed in #6889
