### ISSUE TITLE
Civilizations to do

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#703]
- [ ] Aztecs - Needs Rivers
- [ ] Danish - Needs Snow
- [x] Germans
- [ ] Incas
- [X] Indian
- [x] Iroquois
- [x] Koreans
- [ ] Mongols
- [x] Persians
- [x] Polynesians
- [x] Siamese
- [ ] Songhai - Needs icon for Mandekalu Cavalry and Mud Pyramid Mosque
- [ ] Spanish - Needs Natural Wonders
- [x] Turks/Ottomans

**Comment by B5656** [comment]
I just give more informations / complete your list :

- [ ] Aztecs :
-Killing an enemy unit grants a one-time Culture bonus equal to the Strength of the killed unit (Does not apply to Cities)
Unique unit : Jaguar (replaces Warrior)
Unique building : Floating gardens (replaces Water mill)
https://civilization.fandom.com/wiki/Aztec_(Civ5)

- [ ] Danish :
-Embarked Units receive +1 Movement (even when disembarking)
-Disembarkation does not incur a Movement penalty
-Melee Units have no Movement cost to pillage Improvements
Unique units : Berserker (replaces Longswordsman) 
Norwegian ski infantry (replaces Rifleman)
Unique building : None
https://civilization.fandom.com/wiki/Danish_(Civ5)

- [ ] Germans :
-Land Unit maintenance costs are reduced by 25%
-Defeating a Barbarian Unit within an Encampment has a 67% chance of converting the unit to your side and providing a reward of 25 Gold
Unique unit :  Landsknecht (replaces Pikeman)
Panzer (replaces Tank)
Unique building : Hanse (replaces Bank)
https://civilization.fandom.com/wiki/German_(Civ5)
  
- [ ] Incas :
-All units ignore movement costs when moving on to any Hill tile
-Roads and railroads built on Hills have no Maintenance cost
-Roads and railroads not built on Hills have half the normal Maintenance cost
Unique unit : Slinger (replaces Archer)
Unique building : None
Unique improvement : Terrace farm
https://civilization.fandom.com/wiki/Incan_(Civ5)

- [ ] Indian :
-Unhappiness from Cities is doubled
-Unhappiness from Population is halved
Unique unit :  War elephant (replaces Chariot archer)
Unique building : Mughal fort (replaces Castle)
https://civilization.fandom.com/wiki/Indian_(Civ5)

- [ ] Irochese :
-Forest and Jungle tiles within friendly territories provide a movement bonus equal to that of a Road
-Upon discovering The Wheel, Forest and Jungle tiles within friendly territories serve as if they had a Road built on them when determining Trade Routes
Unique unit : Mohawk warrior (replaces Swordsman)
Unique building : Longhouse (replaces Workshop)
https://civilization.fandom.com/wiki/Iroquois_(Civ5)

- [ ] Koreans :
-Specialists provide +2 Science
-Great Person Tile Improvements provide +2 Science
-Completing a scientific Building or Wonder at your Capital grants a tech boost (Equal to Research Agreement tech boost, affected by modifiers)
Unique unit : Hwach'a (replaces Trebuchet)
Turtle ship (replaces Caravel)
Unique building : None
https://civilization.fandom.com/wiki/Korean_(Civ5)

- [ ] Mongols :
-Military Units receive +30% combat bonus against City-States and their Units
-Mounted Units receive +1 Movement
Unique unit : Keshik (replaces Knight)
Khan (replaces Great General)
Unique building : None
https://civilization.fandom.com/wiki/Mongolian_(Civ5)

- [ ] Persians :
-Golden Ages last 50% longer
-During a Golden Age, all Units have +1 Movement and +10% combat bonus when attacking (Movement bonus also applies to civilian units)
Unique unit : Immortal (replaces Spearman)
Unique building : Satrap's court (replaces Bank)
https://civilization.fandom.com/wiki/Persian_(Civ5)
  
- [ ] Polynesians :
-Units can immediately Embark over Coasts and Oceans
-Embarked Units receive +1 Sight
-Moais in your own territory provide +10% combat bonus to nearby friendly Units (Multiple Moais don't stack, and this bonus does not stack with the Maori Warrior bonus either)
Unique unit : Maori warrior (replaces Warrior)
Unique building : None
Unique improvement :  Moai
https://civilization.fandom.com/wiki/Polynesian_(Civ5)
  
- [ ] Siamese :
NEED CITY-STATES
-Food and Culture from City-States are increased by 50%
Unique unit :  Naresuan's elephant (replaces Knight)
Unique building :  Wat (replaces University)
https://civilization.fandom.com/wiki/Siamese_(Civ5)

- [ ] Songhai :
-Receive three times as much Gold when capturing a City or clearing a Barbarian Encampment
Vanilla:
-Embarked Units can defend themselves
Updated in GodsKings :
-All Land Units start with the "Amphibious" and "War Canoes" promotions
Unique unit : Mandekalu cavalry (replaces Knight)
Unique building : Mud pyramid mosque (replaces Temple)
https://civilization.fandom.com/wiki/Songhai_(Civ5)

- [ ] Turks/Ottomans :
-Naval Unit maintenance costs are reduced by 67%
Vanilla:
-Moving adjacent to a Barbarian Naval Unit has a 50% chance of converting it to your side and providing a reward of 25 Gold
Updated in GodsKings :
-All Melee Naval Units start with the "Prize Ships" promotion
Unique unit : Janissary (replaces Musketman)
Sipahi (replaces Lancer)
Unique building : None
https://civilization.fandom.com/wiki/Ottoman_(Civ5)

source : https://civilization.fandom.com/wiki/Unique_ability_(Civ5)

**Comment by Smashfanful** [comment]
I had in mind something like that. The fact is, for the Ski Infantry we need Snow, and that's not been implemented yet. Unique units and buildings are marked in their respective jsons as yet to be implemented.

**Comment by Am-per-Sand** [comment]
* [ ]  Germany
   * [x] Landsknecht #711
   * [x] Panzer #711
   * [ ] Hanse #711
      * [x] icon
      * [x] properties
      * [ ] [production from trade routes bonus](https://civilization.fandom.com/wiki/Hanse_(Civ5)) (City states && trade-routes required, but could be introduced without these two, without conflict IMO)
   * [ ] Furor Teutonicus
      * [ ] -25% upkeep of land military
      * [ ] barbarian recruit unique

@Smashfanful please update your [post](https://github.com/yairm210/UnCiv/issues/703#issue-440452361)

**Comment by Smashfanful** [comment]
There is also Ethiopia:
-20% Combat Bonus when fighting a Civilization with more Cities than Ethiopia (Spirit of Adwa)
Unique unit:
-Mehal Safari (Replaces Rifleman)
Unique building:
-Stele (Replaces Monument)
https://civilization.fandom.com/wiki/Ethiopian_(Civ5)

**Comment by Smashfanful** [comment]
> There is also Ethiopia:
> -20% Combat Bonus when fighting a Civilization with more Cities than Ethiopia (Spirit of Adwa)
> Unique unit:
> -Mehal Safari (Replaces Rifleman)
> Unique building:
> -Stele (Replaces Monument)
> https://civilization.fandom.com/wiki/Ethiopian_(Civ5)

I just realized that Ethiopia was actually introduces in Gods & Kings, not as a DLC as I thought.

**Comment by Smashfanful** [comment]
> I just give more informations / complete your list :
> 
> * [ ]  Aztecs :
>   -Killing an enemy unit grants a one-time Culture bonus equal to the Strength of the killed unit (Does not apply to Cities)
>   Unique unit : Jaguar (replaces Warrior)
>   Unique building : Floating gardens (replaces Water mill)
>   https://civilization.fandom.com/wiki/Aztec_(Civ5)
> * [ ]  Danish :
>   -Embarked Units receive +1 Movement (even when disembarking)
>   -Disembarkation does not incur a Movement penalty
>   -Melee Units have no Movement cost to pillage Improvements
>   Unique units : Berserker (replaces Longswordsman) 
>   Norwegian ski infantry (replaces Rifleman)
>   Unique building : None
>   https://civilization.fandom.com/wiki/Danish_(Civ5)
> * [ ]  Germans :
>   -Land Unit maintenance costs are reduced by 25%
>   -Defeating a Barbarian Unit within an Encampment has a 67% chance of converting the unit to your side and providing a reward of 25 Gold
>   Unique unit :  Landsknecht (replaces Pikeman)
>   Panzer (replaces Tank)
>   Unique building : Hanse (replaces Bank)
>   https://civilization.fandom.com/wiki/German_(Civ5)
> * [ ]  Incas :
>   -All units ignore movement costs when moving on to any Hill tile
>   -Roads and railroads built on Hills have no Maintenance cost
>   -Roads and railroads not built on Hills have half the normal Maintenance cost
>   Unique unit : Slinger (replaces Archer)
>   Unique building : None
>   Unique improvement : Terrace farm
>   https://civilization.fandom.com/wiki/Incan_(Civ5)
> * [x]  Indian :
>   -Unhappiness from Cities is doubled
>   -Unhappiness from Population is halved
>   Unique unit :  War elephant (replaces Chariot archer)
>   Unique building : Mughal fort (replaces Castle)
>   https://civilization.fandom.com/wiki/Indian_(Civ5)
> * [ ]  Irochese :
>   -Forest and Jungle tiles within friendly territories provide a movement bonus equal to that of a Road
>   -Upon discovering The Wheel, Forest and Jungle tiles within friendly territories serve as if they had a Road built on them when determining Trade Routes
>   Unique unit : Mohawk warrior (replaces Swordsman)
>   Unique building : Longhouse (replaces Workshop)
>   https://civilization.fandom.com/wiki/Iroquois_(Civ5)
> * [ ]  Koreans :
>   -Specialists provide +2 Science
>   -Great Person Tile Improvements provide +2 Science
>   -Completing a scientific Building or Wonder at your Capital grants a tech boost (Equal to Research Agreement tech boost, affected by modifiers)
>   Unique unit : Hwach'a (replaces Trebuchet)
>   Turtle ship (replaces Caravel)
>   Unique building : None
>   https://civilization.fandom.com/wiki/Korean_(Civ5)
> * [ ]  Mongols :
>   -Military Units receive +30% combat bonus against City-States and their Units
>   -Mounted Units receive +1 Movement
>   Unique unit : Keshik (replaces Knight)
>   Khan (replaces Great General)
>   Unique building : None
>   https://civilization.fandom.com/wiki/Mongolian_(Civ5)
> * [ ]  Persians :
>   -Golden Ages last 50% longer
>   -During a Golden Age, all Units have +1 Movement and +10% combat bonus when attacking (Movement bonus also applies to civilian units)
>   Unique unit : Immortal (replaces Spearman)
>   Unique building : Satrap's court (replaces Bank)
>   https://civilization.fandom.com/wiki/Persian_(Civ5)
> * [ ]  Polynesians :
>   -Units can immediately Embark over Coasts and Oceans
>   -Embarked Units receive +1 Sight
>   -Moais in your own territory provide +10% combat bonus to nearby friendly Units (Multiple Moais don't stack, and this bonus does not stack with the Maori Warrior bonus either)
>   Unique unit : Maori warrior (replaces Warrior)
>   Unique building : None
>   Unique improvement :  Moai
>   https://civilization.fandom.com/wiki/Polynesian_(Civ5)
> * [ ]  Siamese :
>   NEED CITY-STATES
>   -Food and Culture from City-States are increased by 50%
>   Unique unit :  Naresuan's elephant (replaces Knight)
>   Unique building :  Wat (replaces University)
>   https://civilization.fandom.com/wiki/Siamese_(Civ5)
> * [ ]  Songhai :
>   -Receive three times as much Gold when capturing a City or clearing a Barbarian Encampment
>   Vanilla:
>   -Embarked Units can defend themselves
>   Updated in GodsKings :
>   -All Land Units start with the "Amphibious" and "War Canoes" promotions
>   Unique unit : Mandekalu cavalry (replaces Knight)
>   Unique building : Mud pyramid mosque (replaces Temple)
>   https://civilization.fandom.com/wiki/Songhai_(Civ5)
> * [ ]  Turks/Ottomans :
>   -Naval Unit maintenance costs are reduced by 67%
>   Vanilla:
>   -Moving adjacent to a Barbarian Naval Unit has a 50% chance of converting it to your side and providing a reward of 25 Gold
>   Updated in GodsKings :
>   -All Melee Naval Units start with the "Prize Ships" promotion
>   Unique unit : Janissary (replaces Musketman)
>   Sipahi (replaces Lancer)
>   Unique building : None
>   https://civilization.fandom.com/wiki/Ottoman_(Civ5)
> 
> source : https://civilization.fandom.com/wiki/Unique_ability_(Civ5)

And the Germans are done! :grinning:

**Comment by Smashfanful** [comment]
Ottomans - Done!
Koreans - Done!
Iroquois - Done!
Persians - Done!

**Comment by Smashfanful** [comment]
At long last, the Polynesians have been released, too! :D

**Comment by Smashfanful** [comment]
And the Siamese are finally here!

**Comment by yairm210** [comment]
Moved to #663
