### ISSUE TITLE
entering a custom server is difficult

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7046]
**Platform**
Android 

**Version**
4.1.6

**Describe the bug**
By default the server adress field has "https://..." text, but deleting the https:// is not possible because after deleting '/' the game inserts it back. When copying and pasting a game server, if its like "https://myawesomeuncivserver.blabla" it will append it to the https:// that is already there and you obviously can't connect to the server.

**To Reproduce**
1. Go to 'Options > Multiplayer'
2. Insert a mp server
3. See error

Workaround:
Set the field to Dropbox with the reset to dropbox button, delete and then insert the link.
OR
copy the link without https://

The issue is known but still not fixed, and now with Dropbox not working (at the time of writing this issue at least) this is an even bigger problem. https://github.com/yairm210/Unciv/pull/6772#issuecomment-1125280201

<details>
<summary>about the unrelated dropbox issue</summary>

Looks like dropbox is working but you can't play online when connected to Adaway vpn but 1.1.1.1 works... 🤔 Don't think there is anything we can do about this adaway issue. (non-root btw, so vpn)
</details>

**Comment by SomeTroglodyte** [comment]
I remember - my Widget treated that fine, but in the end I accepted that the way I subclassed and hacked TextField was too uncouth. Gdx' philosophy of making everything private and closed and final _plus_ the slightly off way they chose to have listeners instantiated and added in that particular widget just made a straightforward approach impossible. 

But you should be able to Ctrl-A or longpress select all and then paste? 1 step shorter than via Dripbox. And didn't clicking the label do it too?

**Comment by alexban011** [comment]
I can't longpress on my phone cause it pulls the keyboard as soon as I click the textfield and the keyboard takes up ~60% of the screen

**Comment by SomeTroglodyte** [comment]
> keyboard takes up ~60% of the screen

:rofl:  📵
