### ISSUE TITLE
Feature request: Name for multiplayer games when starting the game

### ISSUE THREAD

**Issue by ofetios** [yairm210/Unciv#7052]
It would be nice to have names for the multiplayer games so that we don't get notifications like this:
![WhatsApp Image 2022-06-02 at 22 06 00]()

<img src=https://user-images.githubusercontent.com/21990802/171718943-99cf5d54-de20-4826-ae40-c8a275cb933f.jpeg width="700" height="200">

and instead of getting the game id it would show the name of the game

**Comment by Mape6** [comment]
That's already possible. Just edit you MP game and set a name.

**Comment by alexban011** [comment]
> That's already possible. Just edit you MP game and set a name. 

I meant to have an option to name the save when creating it, but since we can edit it, it might be easy to implement. I'll see

**Comment by SomeTroglodyte** [comment]
> already possible

But maybe limited to that one local screen? I don't know - can you share it as suggested name with your co-conspirators? Is that specific notification picking it up? I doubt that, but it's not my turf.

**Comment by SeventhM** [comment]
Closing as wontfix given how old it it is and how simple the workaround is, but if someone wants to reopen or work on this, feel free
