### ISSUE TITLE
Redirected PUT requests fails on Online Multiplayer

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#7058]
**Platform**
Android 5.1.1 (Tester @touhidurrr)
Android 8.0.0 (Tester @letstalkaboutdune)
Android 12 (Tester @alexban011)

**Version**
4.1.5 - 4.1.6

**Describe the bug**
If a multiplayer server url redirects to another url then put requests shows failure and create new game doesn’t work.
For tests: current state of https://uncivserver.xyz/

**Comment by alexban011** [comment]
I can't reproduce. After entering the server I can create a new game no problem.

**Comment by touhidurrr** [comment]
> I can't reproduce. After entering the server I can create a new game no problem.
This being on 4.1.6 btw

I updated to 4.1.6 and the problem persists. Are you sure you used `https://uncivserver.xyz` as multiplayer server?

**Comment by touhidurrr** [comment]
Ok. I asked @letstalkaboutdune to test also. He said that he didn’t face any issue on PC but encountered "Couldn’t upload the game" error on Android.
Thus we can assume that it is an Android only issue.

**Comment by touhidurrr** [comment]
Also @yairm210, attention ping.

**Comment by alexban011** [comment]
Ah yes. Looks like its an android problem. Don't have time (and skill probably) right now to look into this

**Comment by alexban011** [comment]
Does the site that uncivserver.xyz redirects to use https or http?

**Comment by touhidurrr** [comment]
> Are both of your servers using https?

Yes

**Comment by touhidurrr** [comment]
I think we need to manually handle protocol  anyways. Once for https redirect if happens, and once for any other redirect. These two.
More than these two redirects are common.
Another logical idea is if the multiplayerServerUrl redirects to another url, then save that url as multiplayerServerUrl. I saw feeder (an open source rss reader for android) doing this. Automatically changing urls after redirects.

**Comment by alexban011** [comment]
> I think we need to manually handle protocol anyways. 

Rewriting the net api sounds like a lot of work work little return.

**Comment by touhidurrr** [comment]
> Rewriting the net api sounds like a lot of work work little return.

Sigh. I looked into solutions online before proposing this. It's not that much work as it seems. You only need to check and handle if the headers have status 301 or 302 or there is html redirection promt. While checking the status is easy the rest is already automatically detected by java.url

Also it's just Standardisation. Handling redirects.

**Comment by touhidurrr** [comment]
> a lot of work work little return.

Also this implementation will give you the ability to move your api endpoint as you wish without affecting users negatively. Having to move api endpoints with redirection is not that uncommon.

**Comment by alexban011** [comment]
> this stuff is not working on Android for some weird reason. 

which is why I think its a gdx/java issue and anything we do would be just a workaround. We should wait and see what others have to say about this

**Comment by touhidurrr** [comment]
> which is why I think its a gdx issue and anything we do would be just a workaround.

From what I read in code, Unciv is using java.net to make requests. It's not a Gdx issue. You may have misunderstood something and mistook the issue.

**Comment by alexban011** [comment]
~~well from what I read its using com.badlogic.gdx.Net. Saving and loading is done through SimpleHttp which is using gdx.Net~~
Well looks like only the method is taken from gdx.net. But still, I'm not sure this is an issue on our end

**Comment by touhidurrr** [comment]
> Well looks like only the method is taken from gdx.net

Lol. Maybe I misread then. Can you markup the lines?

**Comment by alexban011** [comment]
> Lol. Maybe I misread then. Can you markup the lines? Just for reference.

Sorry, I meant to say java.net. I edited the comment

**Comment by alexban011** [comment]
> Lol. Maybe I misread then. Can you markup the lines? Just for reference.

No, I wasn't clear enough. I edited the comment

**Comment by touhidurrr** [comment]
> But still, I don't think this is an issue on our end, especially since the Desktop version works.

Whether it is a problem on unciv's end or not i think saving new api url on `multiplayerServer` if redirected is a good idea. This would save network time rather than handling redirects every time separately.

**Comment by touhidurrr** [comment]
> > But still, I don't think this is an issue on our end, especially since the Desktop version works.
> 
> Whether it is a problem on unciv's end or not i think saving new api url on `multiplayerServer` if redirected is a good idea. This would save network time rather than handling redirects every time separately.

@Azzurite after your massive changes, I cannot think of any way to implement this. Care to drop into this convo? Maybe @GGGuenni also.

**Comment by touhidurrr** [comment]
> I don't really understand the issue here. Can't you just tell your users to use a new URL?

Well I wanted to make Unciv recognise redirects to make it futureproof.
Also I originally wanted to implement Unciv saving redirected Endpoint in settings.multiplayer.server so that users doesn’t need to worry about endpoint shift and it is handled automatically. I saw an Open Source RSS reader Feeder do this. It automatically changed my rss url when the origin server redirected it to another origin host.

**Comment by yairm210** [comment]
Because if that *is* the issue then I'll close this as "wontfix".
The reason that functionality is disabled is because of security problems with such a redirect, I can't claim to be a security expert but if the pros decided it's bad then I don't want it in my game

**Comment by touhidurrr** [comment]
> Are you switching protocols?
Looks like auto-redirect doesn't work when redirecting from https to http or vice versa - [here](https://stackoverflow.com/questions/1884230/httpurlconnection-doesnt-follow-redirect-from-http-to-https)

I know. But I am not switching protocols.
https://uncivserver.xyz/stuff currently redirects to https://uncivserver.herokuapp.com/stuff
And so I thought it must be handled manually.

**Comment by yairm210** [comment]
https://stackoverflow.com/questions/15057329/how-to-get-redirected-url-and-content-using-httpurlconnection#15057346

Looks like it's just a boolean that we need to enable

**Comment by touhidurrr** [comment]
> So it's an Android specific bug?

Yes.
