### ISSUE TITLE
Feature request: Wiki page with a list of deliberate mechanic differences between Unciv and Civ 5

### ISSUE THREAD

**Issue by OptimizedForDensity** [yairm210/Unciv#7075]
There are a few differences in mechanics between Unciv and Civ 5 (e.g., naval melee ships can attack land units) that may be surprising to some players who might think that they're encountering a bug. It would be nice to have a centralized document where all of these sorts of gameplay mechanic changes are listed with maybe some rationale behind the changes (or a link to relevant discussion in an issue thread/PR).

**Comment by yairm210** [comment]
Since done, forgot this was an open issue tbh
