### ISSUE TITLE
Cs influence decreas -2 per turn on all characters

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#7110]
I mean on all characters of CS, freindly or unfreindly, aggressive, and so on, influence decreases -2 per turn
I observe it on a many patches for about 6 month 
It doesn't depends on of a version, and mods

So in real Civ5 the decreason number depended on a CS character, -0,5 on a friendly till -2 on a most avgresive (I don't know how this character calls in english version)

**Comment by yairm210** [comment]
That means you've been aggressively attacking city states...
It decreases as per Civ V, [1](https://civilization.fandom.com/wiki/City-state_(Civ5)#Relations_and_Influence) for regular city-states, 1.5 for aggressive
If you have any sources to contest the wiki then sure, but from what I see it's -1 per turn

**Comment by Timur512** [comment]
I will check it out, wouldn't attack CS, and after getting influence i will see gow it decreases

But is it was really in Civ 5? 
After stealing couple workers from cs )) influence on ALL of them decreasing so dramaticly?
And additionaly normal state of influence on some of them is stable on -20
This is big punishment

**Comment by Timur512** [comment]
And where is my topic about suggestion declare peace with CS only after 10 turns after declare war?

**Comment by yairm210** [comment]
Already solved

And yes, if you bully city-states they will not like you
Big surprise

**Comment by Timur512** [comment]
Ok)

**Comment by yairm210** [comment]
Considering this resolved unless new information surfaces
