### ISSUE TITLE
Last Update 

### ISSUE THREAD

**Issue by Max1350** [yairm210/Unciv#7128]
**Platform**
Android 11, architecture 64 bit

**Version**
Play Market , 4.1.8 

**Describe the bug**
after the last update, the game does not start at all, it crashes every second, I reinstalled it, cleared the cache, nothing helped.
**To Reproduce**
Tap to game icon :|
**Expected behavior**
A clear and concise description of what you expected to happen - Login to the game and play :|

**Comment by alexban011** [comment]
have you tried 4.1.9?

**Comment by Max1350** [comment]
> have you tried [4.1.9](https://github.com/yairm210/Unciv/releases/tag/4.1.9)?

In the play store it says that the latest version is 4.1.8

**Comment by Max1350** [comment]
> have you tried [4.1.9](https://github.com/yairm210/Unciv/releases/tag/4.1.9)?
I'm waiting for updates in the market more than ever

**Comment by alexban011** [comment]
> I'm waiting for updates in the market more than ever

Well you can download it from the link I mentioned. But it won't update automatically and you'd need to uninstall it to update it again from the store. You could still give it a go to test if it even fixes anything for you

**Comment by Max1350** [comment]
> > I'm waiting for updates in the market more than ever
> 
> Well you can download it from the link I mentioned. But it won't update automatically and you'd need to uninstall it to update it again from the store. You could still give it a go to test if it even fixes anything for you

Uhhhhhh ,maybe,i wait update:)
