### ISSUE TITLE
Uniques with `with [50]% chances` isn't translatable.

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#7152]
**Platform**
All

**Version**
4.0.18 (actually the bug exists for a very long time)

**Describe the bug**
Uniques with `with [50]% chances` isn't translatable.

**To Reproduce**
1. Go to any language that has already translated `When defeating a [mapUnitFilter] unit, earn [amount] Gold and recruit it` and `with [amount]% chance` (As far as I tested, most 99% translation can test this bug)
2. Go to civilopedia-nations-The Ottamans
3. Find this line untranslated:
![image](https://user-images.githubusercontent.com/100454479/173333692-bf7d6a64-9bf4-4f6e-8fab-91c32363ee01.png)

**Expected behavior**
It should be translated.

**Comment by heipizhu4** [comment]
Just had another test, it may be caused by `{}` inside the unique. Hope to be fixed soon.

**Comment by alexban011** [comment]
> caused by {}

I think it should be fine with the {}

**Comment by yairm210** [comment]
Not a bug, they appear in different places.
"with [amount]% chance" is a conditional that can be attached to any unique, so it's translated separately.

Search for "chance" and you'll find it

Working example from Italian:
![image](https://user-images.githubusercontent.com/8366208/173405550-13562c26-486c-49f0-a1af-75f4d08601a2.png)

**Comment by heipizhu4** [comment]
> Not a bug, they appear in different places. "with [amount]% chance" is a conditional that can be attached to any unique, so it's translated separately.
> 
> Search for "chance" and you'll find it
> 
> Working example from Italian: ![image](https://user-images.githubusercontent.com/8366208/173405550-13562c26-486c-49f0-a1af-75f4d08601a2.png)

Thanks for reply, but how can we explain this?
![image](https://user-images.githubusercontent.com/100454479/173406746-6786f075-716c-458c-887d-7928342a568d.png)
(No more reply from me until tommorow at a time earlier from not, too sleepy)
