### ISSUE TITLE
"[stats] from every [tileFilter/specialist/buildingFilter]" issue

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#7158]
**Platform**
No idea, reported to me via Alpha Frontier bugs

**Version**
Assumedly latest

**Describe the bug**
The unique "[stats] from every [tileFilter/specialist/buildingFilter]", when put on a building in a city, looks for all [tileFilter/specialist/buildingFilter] in all cities of the empire instead of only the city it's on

**To Reproduce**
1. Play Alpha frontier
2. Build a building with "Virtual" uniques in two cities
3. Build the "Remote Fabricator" building in one of them
4. Remote Fabricator has +2 production boost instead of the expected +1 production boost

**Expected behavior**
Either developing a new unique, "[stats] from every [tileFilter/specialist/buildingFilter] [cityFilter]", or a new conditional "<[cityfilter]>" to make sure the effect works for individual cities. (the previous "[stats] from every [tileFilter/specialist/buildingFilter]" could stay as a global unique)

**Screenshots**
see: https://github.com/carriontrooper/Alpha-Frontier/issues/34

**Additional context**
Initially reported here: https://github.com/carriontrooper/Alpha-Frontier/issues/34

**Comment by yairm210** [comment]
Working as intended, if you want a per-city version that's a feature request
