### ISSUE TITLE
Feature request: Decrease the number of turns required for training units and building non-wonders

### ISSUE THREAD

**Issue by calrissian-tendra** [yairm210/Unciv#7164]
This isn't really a problem, but more of a realism issue; on the marathon time scale, each turn lasts five years, and training any unit takes well more than ten turns, which means that particular unit is more than fifty years old when it's finished. That seems a little unrealistic to me. It might be neede for game balance, but I don't think so. If the time needed to train one unit of any kind (even advanced high tech units) were redeuced to one turn, except settlers, which would require two turns, and each unit consumed at least one unnassigned population unit, I think the issue would be largely fixed. Additionally, the amount of time required to build non-wonders should also be drastically reduced, as it should not take 50+ years to build a monument or a granary.

**Comment by Tyretes** [comment]
wtf.

**Comment by MindaugasRumsa51** [comment]
unit is not 1 warrior, but like a legion
train a legion takes time
only cannon fodder can be trained fast

**Comment by heipizhu4** [comment]
Why not make a mod yourself? It shouldn't be that hard after #6856 is merged.

**Comment by alexban011** [comment]
What about the beginning when 40 years pass in a turn and it takes like 9 turns to make a settler? :)

**Comment by shannaurelle** [comment]
> What about the beginning when 40 years pass in a turn and it takes like 9 turns to make a settler? :)

It just means those people lived a darn long life (there are books which gives some evidence of this) and it took 360 years to settle down and make enough people to consider as settlers :>

**Comment by yairm210** [comment]
We're sticking to Civ V rules, which means the answer to this request is a definitive "No".
As others have said, however, this can be modded in a variety of ways :)

**Comment by calrissian-tendra** [comment]
I think I'll try my hand at modding when it gets merged. It'll be my first modding attempt, so I hope all goes well.
