### ISSUE TITLE
Locate mods error

### ISSUE THREAD

**Issue by Filipinoguy173** [yairm210/Unciv#7176]
**Platform**
Android Operating system,A12,Idk

**Version**
I got it from google play and its Version 4.1.8

**Describe the bug**
Idk if its a bug but when I enter the Locate Mod errors,it shows me something and it crashes

**To Reproduce**
1. Go to 'Options
2. Click on 'Locate mod errors'
3. See Error
</details>

**Expected behavior**
When I press on the Locate mod error,it freezes for a little bit,and it shows me of the error,and it crash

**Screenshots**
I am very sorry,like I said,it keeps crashing....so no creenshots

**Additional context**
I do not know what to say about it

**Comment by alexban011** [comment]
> it shows me something and it crashes

.. and... what does it show? after it crashes copy the crash log and paste it here

**Comment by heipizhu4** [comment]
> > it shows me something and it crashes
> 
> .. and... what does it show? after it crashes copy the crash log and paste it here

Or can you upload the mods you imported on github so others can replicate the bug?

**Comment by Filipinoguy173** [comment]
Well,got some good news,I finally got that screenshot,after 20 attempts
![Uploading Screenshot_20220625-151026_One UI Home.jpg…]()

**Comment by Filipinoguy173** [comment]
Well here is my mostly used mods:
Deciv redux
Civ6 mod
Unciv Bucketeer units mod
Civ5expanded mod
Alpha frontier
Son of war
Extra buildings
Mod Land
Sandbox difficulty

**Comment by alexban011** [comment]
You need to wait a bit for the picture to upload

**Comment by yairm210** [comment]
Not reproducable, not enough data to work on... I'm closing this until more data is attatched
