### ISSUE TITLE
Android app hangs on smiley face screen

### ISSUE THREAD

**Issue by SomeMichael** [yairm210/Unciv#7178]
**Platform**
Android 12, Samsung A52 5G

**Version**
4.1.8

**Describe the bug**
Similar behavior as in #2552, but :

**To Reproduce**
1. Open the game
2. Play the game
3. Exit the game
4. Open the game again
Smiley face never vanishes

**Expected behavior**
Game starts

**Additional context**
After forcefully stopping the app in app settings all works fine again

**Comment by yairm210** [comment]
This doesn't give enough context to actually solve the problem :/\

How long between when you close and enter the game? Android differentiates between "kill app" and "pause app"
Does this happen if there are no other apps open? (maybe it's a memory problem?_
Does this happen all the time, sometimes, or was this a one-off?

**Comment by SomeMichael** [comment]
Thanks for the fast response! Here are the requested details

> How long between when you close and enter the game? Android differentiates between "kill app" and "pause app"

It happens immediatly as well as hours later.

> Does this happen if there are no other apps open? (maybe it's a memory problem?

It always happens. 100% reproducible. Just checked it also with all other apps closed
> Does this happen all the time, sometimes, or was this a one-off?

All the time

**Comment by 7eter** [comment]
happens for me too sometimes. However after closing the app from the opend app overview and reopening it - everything works fine again.

**Comment by tortuosit** [comment]
Same here. Android 10, Mate 20X. Unciv Portrait mode. Can also close it via Android, start again, then it runs.

**Comment by tortuosit** [comment]
It most of the time happens. And the 2nd try always works (like reported by 7eter)

**Comment by yairm210** [comment]
Hopefully resolved in 4.1.18 :)

**Comment by AdityaMH** [comment]
This only happen, if file from folder com.unciv.app was changed, or deleted.
To solve just restart unciv again.

**Comment by tortuosit** [comment]
Not resolved in 4.1.18 unfortunately.
Started Unciv -> Exit via Android "Back". "Do you want to exit the game" "Exit"
Start Unciv again. Hangs.

**Comment by tortuosit** [comment]
> Hopefully resolved in 4.1.18 :)

Not resolved in 4.1.18 unfortunately.
- Started Unciv -> Exit via Android "Back". "Do you want to exit the game" "Exit"
- Start Unciv again -> Hangs.

**Comment by SomeMichael** [comment]
Sorry, but I have to confirm that.
This bug seams to be a a really nasty one …

----------------------------------------

13.07.2022 12:16:30 Tortuosit ***@***.***>:

> Hopefully resolved in 4.1.18 :)
> 
> Not resolved in 4.1.18 unfortunately.
> 
* > Started Unciv -> Exit via Android "Back". "Do you want to exit the game" "Exit"
* > Start Unciv again -> Hangs.

**Comment by SomeMichael** [comment]
> 

Sure, if it is possible without adb stuff. I set up TooHotToday#4724 on Discord

**Comment by yairm210** [comment]
Is this still occurring? Or was it solved by #7655?

**Comment by SomeMichael** [comment]
Yes, it seams to be solved👍 many thanks!
