### ISSUE TITLE
3 Bugs on nuking a city

### ISSUE THREAD

**Issue by HydroSpaceTurbine** [yairm210/Unciv#7188]
**Platform**
Android 10

**Version**
4.1.11

**Describe the bug**
1.) A nuked city can assign its population on specialists even if its population number goes negative, possibly filling the entire specialist slots.

2.) Population locked on tiles doesn't automatically get removed.

3.) Some Fallout tile yields doesn't get reduced to 0

**To Reproduce**
1. Create a game
2. Reach Atomic Bomb/Nuclear Missile
3. Nuke your own city (or if possible have other player nuke your city)
4. Keep assigning population to Specialist Slots till it fill up
5. Notice the unremoved locked population on tiles
6. Notice some tile yields are inconsistent either the base yield (unimproved) or 0

**Expected behavior**
1.) Population on a nuked city should not go below negative when assigning to Specialist Slots
2.) A nuked city's population assigned on tiles should automatically get removed according to the city's number of population
3.) Consistency on fallout tile yields. Fallout tile yields should be reduced to 0.

**Screenshots**
https://media.discordapp.net/attachments/588357826758574106/986758095516622848/Screenshot_2022-06-16-06-21-02-68.jpg

**Comment by JackRainy** [comment]
Do you have a saved game?

**Comment by OptimizedForDensity** [comment]
Are those tiles filled with fallout or were their improvements just destroyed? It looks like the improvements were destroyed. Otherwise, I can't replicate bug 3 and the other 2 bugs should be fixed.

**Comment by itanasi** [comment]
Made a Nuke Save File to test. Nuking myself on Master shows the fix working
[KoreaNuke.txt](https://github.com/yairm210/Unciv/files/9075944/KoreaNuke.txt)

**Comment by itanasi** [comment]
@yairm210  closable?
