### ISSUE TITLE
Explorers doesn’t collect ruin with world wrap on

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#7199]
**Platform**
Android 11

**Version**
4.1.11

**Describe the bug**
![Screenshot_2022-06-18-02-42-52-51_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/46617994/174400145-35bf460c-55c9-4fba-b506-904dcd084db5.jpg)
As you can see the explorer didn’t take the path to the ruins.

**Game Data**
[Korea.json.txt](https://github.com/yairm210/Unciv/files/8931302/Korea.json.txt)

**Comment by AlexCaesel** [comment]
This happens too with the initial soldier?

**Comment by touhidurrr** [comment]
closed because of #7285 & #7314
