### ISSUE TITLE
[low priority] Tell the player what cities require a certain building 

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7201]
Some building require you to have certain buildings in all of your cities, and when trying to build them you only get a message telling you that you don't have say the Library built in every city. 

It would be nice to get a list of cities where you need to build those instead of getting a red warning only.

**Comment by zhan313** [comment]
National wonder? Already implemented

**Comment by alexban011** [comment]
> National wonder? Already implemented

Really ? Where can I see this?

**Comment by Timur512** [comment]
In construction description of a National Wonder u can see in what cities there is not required building
