### ISSUE TITLE
[Android] Options Crash 

### ISSUE THREAD

**Issue by Sendillian** [yairm210/Unciv#7208]
Since the last update (June 14) the game now crashes every time one trys to open the in-game options. 
I have tried to no avail: 
-Clearing the game cache
-clearing the game data
-a full reinstall of the game

I am led now to think it is an issue from the update.

**Comment by alexban011** [comment]
already fixed in 4.1.11. I'm assuming you got the game from Google Play, right?

<sub>Impressive issue format dodging</sub>

**Comment by Sendillian** [comment]
That is correct

**Comment by yairm210** [comment]
Already resolved

**Comment by alexban011** [comment]
Google Play updates are a little slower. If you want to fix it now you can download the game from <a href="https://github.com/yairm210/Unciv/releases/tag/4.1.11">here<.a>, but that would require uninstalling the GP version first.

**Comment by Sendillian** [comment]
Thanks all for the info and quick responses.

**Comment by alexban011** [comment]
Also, forgot to mention, if you install from github you won't be able to update through Google Play, only from github
