### ISSUE TITLE
Bazzar missing

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#721]
Hi, I'm playing as Babylon, and now I can't build a bazzar, only market.
And thanks for this great game

**Comment by Smashfanful** [comment]
Babylon can't build Bazaars, only Arabs. That is called "unique building" per civilization.

**Comment by yairm210** [comment]
Babylon don't have a bazaar, you're thinking of Arabia, who do have it
https://civilization.fandom.com/wiki/Babylonian_(Civ5)

**Comment by amirberner** [comment]
Yes, played Babylon and played it like I'm playing the Arabs, shame on me🤣
Great game, and it keeps getting better, thank you for that

בתאריך יום ד׳, 8 במאי 2019, 13:30, מאת Smashfanful ‏<
notifications@github.com>:
