### ISSUE TITLE
multiplayer status button in singleplayer games option can't be enabled

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7213]
**Platform**
Android 12 & Desktop

**Version**
4.1.11 & built from souce

**Describe the bug**
Enabling the status button in singleplayer doesn't actually change the setting.

**To Reproduce**
1. Go to settings and enable the MP status button in SP
2. exit the options
3. open the options again or join a SP game

**Comment by Ouaz** [comment]
I confirm.

Weird, but starting 4.1.11, I had the Multiplayer Status button displayed:
![multibutton](https://user-images.githubusercontent.com/11946570/174463735-4b5da918-6337-471b-a703-9910e0736489.png)

Unticking the checkbox from Options does nothing, as it seems the change is not saved (opening Options again, the checkbox is is ticked)

I opened `GameSettings.json` and there was a parameter `statusButtonInSinglePlayer:true`. I set it to `false`, then started Unciv. The multi status button in SP is not displayed anymore.

Once I dit that, everytime I close Unciv, `statusButtonInSinglePlayer` is erased from the `GameSettings.json`.

If I manually add again `statusButtonInSinglePlayer:true` and then start Unciv, the multi status button is displayed again.
