### ISSUE TITLE
Mods menu crash

### ISSUE THREAD

**Issue by Huymnsel** [yairm210/Unciv#7214]
**Platform**
Android 10

**Version**
Google Play Store version 4.1.9

**Describe the bug**
Crashes a few seconds after opening the mods manager from main menu

**To Reproduce**
1. Open game
2. Click on 'Mods'
3. Wait a few seconds
4. Crashes

```

```
</details>

**Expected behavior**
Game fully crashes and throws me to home menu

**Screenshots**
![IMG_20220619_08084320](https://user-images.githubusercontent.com/107736312/174461796-b1f7b72e-2082-4a63-9a37-f2fbb109d665.jpg)

**Additional context**
After the screenshot it just throws me to my home screen so I can't
open the issue tracker

**Comment by yairm210** [comment]
Solved in recent versions
