### ISSUE TITLE
Game crashes when I press settings

### ISSUE THREAD

**Issue by hxd2772** [yairm210/Unciv#7215]
**Android, 8.1, 64 bit.**

**Version**
Play store, v4.1.10

**Describe the bug**
The game crashes any time I go into settings

**To Reproduce**
1. Go to '... Button or Menu'
2. Click on 'Options'

**Expected behavior**
I wanted to go into the options menu.

**Screenshots**

**Additional context**
This game is fantastic! My favorite mobile game!

**Comment by alexban011** [comment]
already resolved in 4.1.11

**Comment by hxd2772** [comment]
How do I update it since play store says v4.1.10 is the latest version

**Comment by alexban011** [comment]
Google play updates are a little slower. You can download the game from <a href="https://github.com/yairm210/Unciv/releases/tag/4.1.11">here</a> but that would require you to uninstall the game from GP and then install this one.

Note: Automatic updates from GP won't work after this, so you'll have to update manually from here.

**Comment by hxd2772** [comment]
OK thanks, how long does it take for new release to come to play store?

**Comment by alexban011** [comment]
Well it depends, I noticed its about 3 days, so it might update today or tomorrow, but can't tell for sure.

**Comment by hxd2772** [comment]
Thank you, I will wait for gp version to update!😀
