### ISSUE TITLE
Can't paste URLs in `Mods` > `Download mod from URL` in Android

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#7219]
**Platform**
Android 11

**Version**
4.1.11

**Describe the bug**
![Screenshot_2022-06-19-22-20-45-25_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/46617994/174490711-ca646f0b-a353-41d0-8155-a3eeeb5d36fa.jpg)

Copy - Paste doesn't work in this box. Which is really frustating.

**Comment by yairm210** [comment]
Is this solved by #7211?

**Comment by Kuldebar** [comment]
Yes, I play on Chromebook/ Android and mapseeds (map editor generate) and url's (mods) can't be pasted in. 🤥
