### ISSUE TITLE
Unciv Server Container on Docker hub

### ISSUE THREAD

**Issue by BramvdnHeuvel** [yairm210/Unciv#7228]
I want to run an Unciv server for me and my friends.

Right now, I can download `UncivServer.jar` from the releases and create my own Docker container, but that can take a lot of work if I have to redo that every update.

Ideally, I'd like to see some version control on a website like [Docker Hub](https://hub.docker.com) where I can find and download the latest Unciv server version, already containerized and ready to be deployed.

**Comment by SeventhM** [comment]
@yairm210 Closing as wontfix. Github has releases that goes back, and OP seems to have found their own solution. Though, Idk if you want to reopen this at some point
