### ISSUE TITLE
Hydro Plant consuming not translates

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7236]
version 4.1.12-patch1
![hydroplant](https://user-images.githubusercontent.com/107413099/174655319-fd509122-9bea-4350-a248-5f03c72e5d4c.jpg)

**Comment by MindaugasRumsa51** [comment]
(version 4.0.15 - the same)

**Comment by Ouaz** [comment]
It has been reported in the issue dedicated to untranslated/untranslatable stuff.
https://github.com/yairm210/Unciv/issues/6131#issuecomment-1157135330

If you find another ones, feel free to post there, so everything is reported at the same place.

**Comment by yairm210** [comment]
Not the place, we have a different thread for these problems
