### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#724]
I kindly request the merging of the following pull request https://github.com/yairm210/UnCiv/pull/723, in hopes you didn't forget about it

**Comment by yairm210** [comment]
A. If I forgot about a pull request, the place to remind me is in that pull request.
Issues is not to be used for all messages, there's a place that every message needs to go.

B. This is a pull request that you created just 5 hours ago, which is a really short amount of time. If a week had gone by, then maybe. But 5 hours? Some patience, please.
