### ISSUE TITLE
Legalism should give Egyptians burial tombs, not temples

### ISSUE THREAD

**Issue by bgainor** [yairm210/UnCiv#727]
The Legalism social policy immediately grants the cheapest unbuilt culture building to a civ's first four cities. In the case of the Egyptians, this might result in building temples, even though Egyptians shouldn't be able to have them.

**Comment by bgainor** [comment]
Side note: I discovered this bug when playing for a cultural victory, and ended up with a ton of cities having both temples and burial tombs! (Especially when you take #726 into account)

**Comment by Am-per-Sand** [comment]
> . In the case of the Egyptians, this might result in building temples, even though Egyptians shouldn't be able to have them

Can you remember the order: you had a burial tomb in the city first and then you received a free temple, not the other way round?

**Comment by bgainor** [comment]
The case I had was where I got free temples from legalism, then built burial tombs on top of them. I can try testing the other way, too.

**Comment by bgainor** [comment]
Just tested it the other way around, and cities with burial tombs get temples on adopting legalism. I didn't have acoustics researched yet, so I don't know whether they would have gotten opera houses in that case

**Comment by yairm210** [comment]
Done =)
