### ISSUE TITLE
Feature request: mod categories

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7280]
Sorting the mods by name date and status isn't extremely useful when searching for specific mods.

I suggest more mod tags like `tileset`, `maps`, `audio`, `ruleset`, `units`, `buildings` etc so we can filter them by tag

**Comment by yairm210** [comment]
If we do this, it should be with Github tags like unciv-mod-tileset, unciv-mod-audio etc.
We add the available tags in the wiki and notify in the Discord group.
Each mod owner is then responsible for tagging his mod correctly.
