### ISSUE TITLE
Changing the server address crashes.

### ISSUE THREAD

**Issue by infernostars** [yairm210/Unciv#7295]
**Platform**
Arch Linux, 64 bit

**Version**
itch.io 4.1.13-patch2
**Describe the bug**
When trying to change the server address, the game crashes.
**To Reproduce**
1. Go to options -> multiplayer
2. Try changing the address
3. Game crashes

**Expected behavior**
Changing the address works.

**Comment by yairm210** [comment]
Cannot reproduce - is this still happening? For your, for anyone?
