### ISSUE TITLE
there is a gap on the top bar

### ISSUE THREAD

**Issue by uwumonarch** [yairm210/Unciv#7299]
**Platform**
Android .redmi 5a.lolipop

**Version**
4.1.13 patch 2

**Describe the bug**
At the top of the blue top bar there is a gap whereas in the previous version there was no 

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
I hope in the next version there are no annoying little bugs like this

**Screenshots**
![Screenshot_2022-06-22-20-24-57-176_com.unciv.app.jpg](https://user-images.githubusercontent.com/108036723/175754033-18e352eb-2c26-418e-ba38-2f394f61c60e.jpg)

**Additional context**

**Comment by ArchDuque-Pancake** [comment]
I confirm, we have been expierencing this as well, its annoying.

**Comment by Ouaz** [comment]
On Android, the gap above the top bar appears when starting a new game (or loading a save), then it disappears after a few turns.
I didn't find (or didn't search actually ^^) which action (open a sub-menu or whatever) removes it.

**Comment by Ouaz** [comment]
I think this has been fixed with this commit? https://github.com/yairm210/Unciv/commit/76920d1307af74b8f721b4b9c9ea696a486b86c5

**Comment by yairm210** [comment]
Indeed
