### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by least-mouse** [yairm210/Unciv#7307]
**Platform**
Fedora 36 64-bit

**Version**
unciv version 4.1.14

**Describe the bug**
it crashes on launch. attaching the log. [hs_err_pid15005.log](https://github.com/yairm210/Unciv/files/8985545/hs_err_pid15005.log)

**To Reproduce**
1. launch unciv

**Expected behavior**
the game starts

**Additional context**
my laptop is really old (t400 from 2008) so that might be the problem. if it is, sorry.

**Comment by yairm210** [comment]
Looks like Java itself crashed when trying to run`sun.font.FreetypeFontScaler.getGlyphAdvanceNative`
So... this looks like an AdoptOpenJDK bug, actually
I see you're on `11.0.11+9`, maybe try upgrading to `jdk-11.0.15+10`? Not sure what to tell you, Fedora isn't specifically specified in any AdoptOpenJDK documentation so it should be a regular Linux build

**Comment by yairm210** [comment]
Closing for out-of-scope
Sorry
Updating the jdk is the best bet
