### ISSUE TITLE
On Mac OS catalina the program lists every save file twice

### ISSUE THREAD

**Issue by qchenac** [yairm210/Unciv#7312]
**Platform**
Mac os catalina 10.15.7 
Java version: openjdk version "18.0.1.1" 2022-04-22
Java 8 update 333

**Version**
4.1.14

**Describe the bug**
As showed in the below screenshot, In the game every save is listed twice but going to the save folder there is only just one corresponding save file as it normally should be.

**To Reproduce**
It happens as long as manual save or auto save all the time.

<details><summary>H4sIAAAAAAAA/+1dW5PbtpL+K37bF9El3kW9Oc7JpSreeDM+m4eUHzgSZ4YnGmlWF8ezLv/3BW8iSH4NNACOTx62knJpJBLdaACN7v4ajS+b8lO5K/83P5eH/Wn9x5enXf5cHD88PxXrny6P+X5xf9ht19lCPPef+WOx/i6/fd4d9otzsXlYfzltymK/KX69+yU/nVcfLseqjWhR/bfs/vtYP3v6rTgV+XHzUGzXf7y5P5aby+58ORbtrx8O3e/i1335mO9e/XQ53eb77fG5feTn/fvj4f5YnE7rL+NH1n7w9evi6bArBUPi99P5cCy2bxsS6/Brxf5b0cHz8bJpevrl6+J/LsXp/C7f5/fFsfr7WOzKe/Gj9FXV+WL/5r5v86f86ancV0z4sfj9WOTn98XhaVdUj38qN+KhZ7nNS7k/SX8/HQ+fy8fy/Lz+8uGhEB0QrPyQHxc3h/39Q16uvy9P53x/Xrx9KPd5/cubx0IIK1+/3R1ORdWRc9XDP77sDpt60NZfPq/DxfPai74uyu16c7fMNmGYeGl8G3lREGy9LF2lXposl9tim975Rb7YyyN5d7jst+X+/m356fpdJ4qa5cPTZdeSujsctje1HNZJzcvzSKq3l3J3/k78U7Uo2Hyf7/KNGOTyOnijF242h8u5luXmcjwW+7P8+8+nf56K401xXotvisVG+um/LsWlWP9Rv/7x66L4/JTvTzWP7cRq2RRjfy53tcR6OYmPQfUxrj9G1cew/hj234b9t9Hotejrx8Vfh+OfxfbDtenrD+Xp16OQ3T7fvc2fynO+a3i/2+X3ou+X/Xl7+EtwKab74XLcFN8XYpEJNpdfxbvN4L6tJpVg3a96tat60ZOpWQl6BpuP/ojBUOb1+jEZ98sffRv1H5OxZCQZ+L2QJCnGI86kb6UWpG8rYe2E2rgpiv3Pj2JhfCoexfiLARTfntabw+Pry16s29f/Oh32r3/KTw/v8qf/LqoVFizEg8d6HQyGtXnzX/mn/PUu39+/vhEP7e8Xn/KdmCtvxWx9tREvFsevH8WUechP//hUHH/9a19s4ZCdD+Jjq0N+OBzFxDwLhXGqptSXWismV63YLlI3rfiu3FfcVnrh94ei2C3eH86C2efFWNstNPqzag+rzeaXf4e2DIOZtGWnIVtV1ehFWn8SGtNLqznjL2ududou0220zL0oLWIvKjZLLwuy1PO3cZitQvF3tG105u9iFooxOo/UZjf8vdp8qgQupHlqOO9+eHW4eyX+/qW4L/bbIF1PZuzPYo6JzrdTNlgKtTDUwNLnYB4N/ONRCLyZFEjDtj+zdWwv2eqPVf2H3/yRVH9kzedU/iGVfkimry+Bvp02lomnLk9boTrFSi//txB9q5expUIOeQrZq5XPquFDUrNere78RiF6fjL4K5R49yO5w34sy2XwXDxt4vpWJL/lB/JrDeVQkmcqNd61EEg/pFIv/KXUPd+XGw4GHIQDDoadj2UWWoYiuf1Mbr9rMpMpB4Pmw0Hz0aD5WG5e2svaGRfJs6xtIZbJRhLZSGJuMDADoQ46NBilwdCGkogH4zUQz2D1xONXEoniSl4igSSzqyiWA0k3wo3lt+QOoHWZTYeqayCZyEyePQPJDhiN5JZj6anB8pf1wmDurqSnEmnqrqQXUolENuB9ORDFYLmMFlYnwmgggVjmum1zICpZbWUSe8MJHgwIhwPC0YDwYLSWUh9XkuTkSSH3/drB5YCqP6AaDKiGMlVZK6+mfQ0GrYeD1qNB67HQpO7WVu+Dtpu9ztqK/y7WVvjtrS3/haytoX3V/dX5qO3fCi+1mifC4kqXSbHaru684jYJvSgJbr08izbe3TZYbbLtNl4FSWNx/ZgfBqZWN/bfzkOd2T7qpNB6T+0yqpa73/tffu9Itd9Go9dCwgcVb9r6oEEs5ulgxCr10trI+baINlkSeGLYEk8Yy4GXpWnshVEW3d5tsjgOVs2IfTg83h6EiC5w3IRY9m82/3MpK8EEnGGM4DCSw/XusL/UfqQPh6v7eThe8gB1nW6F3ijASrm26i++fhn3XybDl6DJ2rbxcWJXBoSj386CuJ8Ffv+tJ32uW+4decl6aR+oVHmw7J9Nx3MqvHbK77/0pM81E3Hfwqr/KAmj56EVRjUl077dSGo3Gk/8pGcy7pmMe2phL++oZ8fvP3ryZ+npuGczGcl1eZWPxNCqX2fJlUb15fWLoGNwIMzJtPCvX6Yj+UlLeSVPm2sDvQaQ5LeUuikNZ9STSPqPkvz6CIzE2NU+GE3juG9Cnkl+/3U2VF/9nJQ0WtrzGI6mRiqrsf69sGkq7F/vmcr6t6W5IPHRTyHZpZGWTTtYkqj6WbAaLWxptQedRPqJFfRCknR1NJwt0jzpfJj+Wy8c0g8kzSGNtrRKpU73Myer2cqkJqVxliTWxwBr2fQiGu0vQb9m296Hi1G3/eZ9fxaLThiLnUlX2xNqgy7++xh00Tc36IJsRrChM+YQ8NCZcorQWWPiJ7VZsE02m+hO2HDhJhZmwV229bJglXnFJkrv0jhNk8xv4Yai/Fc1PrJR0Iz6/0fNZKF+kV3MRfdH92PnUA7/SOXHUxQtGzj//XMzxsuWY+Px6s+KaRLd5sXdJrzzNvHtVliPt6GXLePcS9Ik9pMgjtNl1EyTm4e8MRSn82RgOvoc0xGPtd50TCxNR9mFDySJyxEq2cWWYw3R5F0EM3UtfdSNh5ggLDvTk0MS8mc5hDeIqSXy/AO/DCaj1OdMIhFOxOINYitNSyuJuCywpUxBwqSGMbhkIlYvmj414DaW2pIJ+lJTsdyUHMDy5ZiMnw0Wrbxm5WijHGwk1nXPpLzWpcjkIDAZXDnpOQpk7oIBd5nUsaXUmmTOeUFjM3iBHH/yB0HVVJKbLCtfanIQLO0NYa/jtbcaPcl3uLISSlTlz+0PqfRDKvc0bJuXINH2sxz1DGURhYteNF4fH5suz2vnemdoGO0N5I5I0Oeg7U69SzKRjPThSguWUj/ldToAHbrY/fSX0UbRE5HlF8pvDGQSyq+vpNfleHknOV/6w5/8MBCNLDMpCjJct0HvqnnyxJaxksGq7f2YGhuawV4NrvZqZ0/9P+JLxyBDN5NVZaVO02PUoUe/y04QtsjtZru9y+LQ2wZbYbJubu+8fFvcickWB7fLZS6+LRpb5I3Y2Xf5f5xeiW32eB5YJNfx/zfEIVezWJxXkVSfpUSPFp9rPkvpGy34IT0jvxsAW6X/xTIeGfEgWF9KdGnQiFTiLJY4bnsiIUa+lDqTSa9KKSwDIfjSq1Lyy0CAy3HzmfRMaw9Uz/j9x6D/2PajfSe7Pld/DPqPUf+xGxUJ7fSlJB1fSvmRQFUZeu2U+UpqbSWN8apnY9WzserZaMWW9s+l/XOp1GoqtSrPNClvqYuiJEMZxX0HMukd6eFBu5J85HHsJrb0VSRJLJG+DyTpyTPKl8SXDNZA/zmSOEz7PoT9x6TnL5QIRdLnQGIs7UUur8dYkmrotsl9XNzmR/F/mTfqf1ve3dV7zvP6+0Lor1p3vMuf1l8e86f3+VFoSLFXiUfPVbLo98VdLp5diN9uhDO5/nLMt+XlVPX1r3J7flhH0eKhKO8fzusga9Tru0I88fi1eqVb+af1m1uhZCsVvz/8Vu0NbeZfs/x/L88P/y1oVroteu2/FrI+FZVWSOIk9FN/mcVCoLWOe18cvysPj8Ub8WYlq8f889uD2Jz/8flcNMoxXhS74lOtrv/x+emwrxy/5es0Epvo41NxzCsJiaePVVZatZ8tX68Wn4r74ly/8lu5eWi/DuLFMRfSLOpXTtIvodgemo5JX8aLv0Rfjh8exG8PlVnhLV8vW9X8i9jFhE67zU/Fh+J4zMv9uuZajPLT4VSOQjBfF7oH/WYJqR+bNvXrpsj3o2c41HStfGYx3bodwwfF9nY67cS2UO1957IZrdGLQaNydK+FUJoBYExMhfqvbmiFpXU+7HYfgZStX6dIdzNn/UN5ehi94cirfri7cLV+sAJGU5ZDyZ4qPtX+VYbCANoXCnJet0XidiaifZcfTw8fFQ2GjZ6ejpJiGgZKHth9CSxI+4C06ayCr6tmMSQ4eibUTy9y9aJOMp5DUwpPa94c1fbys5PoQ4IL5uut32w686/j+k/hdohd/PrFm8fKnl9HmrVBqoQJQWGkCAPFjOJkfofKHcV8eXudkSc3+H4n/j0p3ooae9loZYY2hMIpoXeVkMQHYXqJTua73w/7rXC5fzts/qzglR/LW/HlWTjUOgUV2Slz2G/mFPUB3ZF6eXvMb4FeiHTLmGh49Iz2kVYLcZY6pSqRFnLY5z1gDOlUchc4Y+g+R63DEKh+XFqgm8FtBLqlF0bE2y+8SKlc+iman8871cYdTWcGY/ufrNIIzEStxvA6b9LorbhxrnkSwo1P5stPpZguGikhmlolOhP9cEq/061QX5rKNGDK1AeNW1iL/pQc1JIkJdPNkxg9A++FozxYyr8/LeekZRnaHNkf+h3MA5YS6gVDvf1a7iYGE1qlDHuWMznhEKt0bcz092Kqq6A9ju6OqYEB7XF295hWvoSm6SfA4empOGq0LWfux2CRtDxcif3+INhQ7QfdCQvmotdpzaSJeFqvsxiww9qedO/g7RO/pRvBm4eieNJsXbhlclzwVmbH3pvd5bHcTz0nf6nZ7hKD7c50jALHieHbEPUJouNNj5z/9OaW6NW1eudWrEnWXt2f+3ba1BiKBsXM9JreI0NjOlvcwIEfzfyfDsdTcRrP+1Dn4DO2XrQfUeuDucdpJ+bnycSEzTB9o4S5oybMHTWhdlTm7EuYO21C77TqbUgdSEAzNqE3VDUpjqmU2DgJ14OOpjqkei91UA0JoDvT7pgQrEFTgOy6eSwvntId78p6/YHNiBm5jPRc8mwHi0kTTmkrbQDMp9oG4Iy8bzz51CZAqlOPc5FjkOqrsViZBQyzA0UjHCx6TxGoeCx35Tk/Pv9zX57XXw5/7YvjtbTQoc1K+HXwbVtd43gsD8euEtC7riJMsMjrTKf1D4fjubx7rrLEHg/VN3WiQpUXfmp+Kuss58f2xXfF46GpEjO1W6ojHPDbj1Ue1+RrQmqlVLdGqi+jQxodjDMU3WPNEhBdNKGLHGWVocMwFZDloZmQiw4N0niuDqFpuDsqzQNTdZc6InYpkBuLKAerT8E4z7TBp0zLLrWx7NLpshrvjz8f68pm5B4eQEZM7b50qhbR+sTEZouyNnxwXIlUue2YbwtdmQ5TBVW9t+JO0JXFoHAaT+jGrUJeK8YAxEqBGZONp2SZQS+LQYtsiIXzdjgkedDY74kW655pJgTETDCKcc3Ei+/Ci/HKY60AZNa7aCBg2pMIO6n4+KljVAQT2ZfG+l0F4GQ6M5MRfkB5LGxzknyPFF6MrMrRVv9L/mdxQkpSj40Lod3uVPRQcMplqlFBMaXBaGW/eY5WI2cnctaiaE93sXRXNpJaMS3dFZgLrMY5NuxK6aaZW3MrvXmrD1JNbM6V5epfWdq4K0vkYzVVsXx6fNuWNQqcQNXKZkeTgOB8ouuVGN211J2Oseq5jLs0UHs9k++L/Lgbq+kVs/0UtG+KUKc0LRR+6kq0DsNP3beD8NMwuqQJJl0LJkJXIqvjSU2N9Xxvyk91ng5Fw8wY7Bih+UPf67baNptNCoBJx07fi6kipnYTmftwkKs7B4HGZWJM42vByBldJg7ZyIasUXYAXhM6X0r31pJYE11NtuEc7L4l14T0+Y83j08P5W15uJw+amdiWxcL2MXTaRiSwuDDHQFXNmOvgDMXfJvGfaJxrvOF6RmDEQwVPafL6ZE+p8pKRkgSyzNhokkokYbVPsiIIT0re3/v5nKfK3EEkAcL1LTeZocu2cgmJF0yvQc4yXqGLpkNoAESBUxsuzEfKPDNcTGho8ZAP6x8G4/yqMaGHkODqe07sCKzKW1o3WV0z9jWXcZ04jIzh15r4WfTSUXTNZ59LqemMgI3hJxZ+HQZL2DUtK9XPNrTDhmhRtVYWzazR5cxPbpMuRsZb4kZExvIwDZs4khqMoqluui2MZq6BZcG+srpti1kgAParcWU9H4tReGbOptd7TAMCS+n3lyKutwqYyp54XjItzdnIfLT+jfxUYdkcySfIDY4WikhZ5dSTcRqeuZ6IgZ8fF+ciiOYpL/mp/L00UK8GJYjRk/tSBryqvMwCR50Csg649x86K40Pxwvd3e7Quk1B4bTgwPwcWY3PndvyAgjB8Z30snG4017mhzloPCk2akb0OW09rRb53Mu9xfAv0gOttmZHkjPJB3SGU0nDxxnoY5OjQ1G0qFkgAPQgWQ7og/56bvD+Xx4/KW4O/9WfhL7cne3oMrRZBjU0KG0cWypPCku0kfjWi4HIpiwmsL50wAYnAJDSKdNbVpOQ47IZGs4MylxPNmmRcYxcp1R7y+ZPmxD0WKG+svpilBQINeOuc7xl4SXqjYHGz4sgEd/ydNx3rUanBUFlxMZ14qHVpSd0pKWYJdsDU12oKduhIMZXssVmo79tSyxtYvbXZChoIxOb/cXhMkvfrjst8dcJxENOc5x7gxRtzViMsCTwsfWRP8Qwq3afFZc6qmCusaN5Zw+T6yaT0Dz9v5YPOewxjRrfJwtmpOjiMER8gYyFYch4nA+5DYEPLPcv0DNl8bh1Je9mwRhCQeUUUBPA0eRKnLiWY4emnoCvLUIPWe9oenmGbeOoSns6zFBZavEaPYs9UCiNOknznhy0QNHF0k/UZ+PO/bjfqtqykqOnPQDx7kDNSLYTueMpzU8cFzYICAFfU/S7kYisvCLwZEbFwDWMGXSdPYzMzcRoMjzX43zgKEPOYOnjpxbGHh7AdIssjxnv7PcHQ13VmVQbg1Rnyx0yvWZUJ1AJ48YVLqy4GhOH51ZpsS71qh3hZJ9Vj2XK0UbL515psTz0WEWtrEPyXJwYh/la7mRZSXBodi9uWvNiupBgw/Pq+vFQfKjN/vDX/aAgt/dbOm4zsZNtNEA193N9y3Ys0SubzaHy5lMCP35fn84Fq9aqq82h9NZnxl6jRoQIZRgCmz3l5pbiNM0/tDsqFC8w3K6P1b3FLz6rsL2i+Or34ri7ltnCFwzAWA0CAgyQ3Lk210/HnbbV78edZk+YwKK2FEAtZgmOGRsfLWCMrX0UkCsnXRXat8XhbKMcmJFOaEpW4wREVbSwEa6YG4MeKR2obELQ4SVZsztiwB3VAmLUE1cEwuyuYQCbloURXSihJPNzzlRYpve3+6QKFI1VTtoO4VlVaRTJT/kx0d4pGSpkivcdhH+jLZQZp6LdoGxWFBJxHj5wMAeMz42Q2ARZtjwAmUvm/uDDsy4nAAGB1XIoJpFgQUPVFggg2dk0G7OYJlDZBAG0YwzUlySqD1Qh9Y1zGZTyVNZJMYydPbS4T5wBJkMoBmXnwd592Q2hXl4DiVhGLup5lktKNIFI2IzXB4w2V8woSlDjG6gG3EY4U3yBgqux0zegYEosTJemFcs6SNO5JUm6lwE2xtUfKrYniYDwbDmnz62B4qdKCQ9enKM42rvJmAXhrQqO+mDxMyxL6eLE/mYFU2rxM6lDUBl6mZHjifBm1kjOBC2fBGpOZ1DQZA4e0mysj/86yXYk7iiQl61Q4je0VoblJSsGsPjyLqwyEdU9WlMPkWAEzNDsb5RW4Tr3sTq2Gf4iH6xdVTGpbZC1LjFT7Acmftoqqb8EnZ2aj3piWiZTaFv5oRpQ18h3Ks0sS4mhUg9Any7IwJEJ5wS6U8WUw/pLn3xW4MDTlChoeAM0laWZUmJCBGDCaTRNCU66JnFDKqqBkAX/TEKZumCQhYxTbi1zlRM1mOmwJmXfrQ48KaJD9kcDVPXmjHwC0FZGTKARAao5gwgkUTIPRfGjcg4lIFswJUDhAqfu0ouqM5rn+sEw0FzJqeBem9k6Ed/EovKKzKcS1RBBJOD65ZXdWmVEzqDQ+YTWcSznG4cb41/Ip5lsT1QFyFzubE5JMexuX1wS6lTYVl0PSocVrMrjo1nl+F1xq7ZD9SNTZivF0vh9MHVCTj4pL60wSHB0WeW1W1ZGD1pn5AFak4pem54xxykxgq7oSPL+sAAMw+9bR6H0jTN4xiXRcQFwYWsiM9S+Q5BSPMWpuSDd2x76nRMDqU+8Ln5pllS12Q8QgyBS93Om6KyO1+GJfyLyaTx/CYaEZlNtTrygN6xnmqjxqhwXggIE9Py501BgEimvQ0cifomPfQBsVq7M4ktETHzGk72HGQ0A6rYe0ZRxaFTBva84g+bKlRqAdCl1PLQRjb5mfecC0fsliiRDYgLjrP4+huUm201FgrbTq/5ioHsuFYDkbk4as3a+EOal1kYmMsD54oV27aImK9Ra0rXRVlMCily7jwmAsUzyRRpfUYwGVNXRI9NZw6MhruFjvXAxzjihyPJc8Wz1cmnusjwXGET21PjsCicVeQbxoo5p3HU9dfHAdg5g8cOZ43Q3V6ud7+MmlMFj2e84Ahc4suPsrBq8sGI8syXxM2XhmlWktZoOlrkSYJCui65nbCG0jikc5PvVBEdD1Vs0oWFJoygo6sU4o0OyloG1yd8oLRAkg8qCRG5mWYRcYcwooci00Yem82VXRwPqvHzXy5yHQExw9B9pIqgu+xxDQsu4Am4SVebLdKStSm2Bm5aw+FS27vcfHCVAI4uozsN7IPaVP1Idn4wqmhpHOwG1UkUncfBbnPjHxzrUFDFMXDX1egzUwNaJhzzRpFtSWptaOOyQpS+EQUUO3fK0kVnDLWxf3jSkdVbdS4qRcksg9Xzm2hQDN4yn/h1oMWqKao38/AVUXxdpwOouafOaQ4Re8owN8zwNwlzzyOLwJEXH/FiXhYCbUlGIXEXDpZuMshcGcgoCeDguAOlFdlTZeJ8iujOtDOlfOFj0yAxZ04TV+eA/lBPGu6TSD86BqJHrc2U44QU5rivmkuLQwIoePtQ7scIa/OdC+TbBm9xoDyeoqtQfTPj1KyKkbhpbeQcv8Y2eJFyJ62kFxQBUvGQD2MWFMHweZYCDpnbIRpE/ZR/O35WCwtG86fgmafAMoyVFjwS8Pe80rI2wCG4EE5lhE4wONR3gKkfbliEBSIya+lfDzlwFBffat/oMB+EgIALl0wvHhpc6EJGpjWgiMNNNuMBVd/+az6k4EZfB+5SGwjHsrIpD9pR3/StQUAY70Gow+bWUnDd3nwHDuD9Cmo1YIj9oYsfJpsCRiyM9iWDUDYovMlse3KFB4Y4XupsAqiWQEMiBM5CrSoYBOHgLwgYUAbvzOtR2JdXBiExRpdiIyhFfwqnjcMxKVvULmspcAqJxKbwnpYqZ0aCK4dniji0TNjZ8MbFRMFNVzjwju7Osk44AqXOzfAWVKFdn48PikYpOjsXwAJOGiqoGh8yIHNRlDEzHyXOOHURYiQWoXRot7qE+Gc6lQBvO6G1LTcrAFa7NIoPo+P/Q7yAlWhD9diwyAhKX3UTuVVjU63aBGITs97UAVf0jnVvDBmIKQbswaCI5MN8gUUUe3o0ylAQIaBkUcNrpn4HfG4UuJT60nFQRqtBo9DxOyM0ilGgvkGdXOSdcUllFCWMLzGeXHFbTFGLtrtgSo0NhoRMrRekirpOWYSgXqJ2erewMRqVTCORUCXayh+pSkubnICv5mkcwleWMiAOW5jOLaRcrc8mQD1r6yogRWt93gNq3dnvTofwklrVTyx0mk8musZTgEaomjaNzkNAWkcWnWDVRcmbGuEGQXKofrpTPqjwN3WyTHdkw/iEISx8pSeGyl4RrgRM3XIDQOarAQ6dpxmzeZGjZ988hCI4pZMg6DAjJpLaYCJ8KabTUIIKbODUaHIt88yHWLTHFzIlQGK+RDIVbqJtDgMXNngKuhnahRF0F5Z9RBVcwcVtDGMRmrMjNnn4ZAllZgQGFZuxlxiocdO5EWgT/fBQvPrpIkgN99Hr1/zrNrQGfndgASIm06oQ8HwDzoo3vmZjJhWDDneQMT02KATgFghdGF84oIxvOUzgxAgf4sbaOBKYip9xgCUB8wqOWjJdSrOhNAkXKkpMoSItVTtsSJsGBy5+dWQUt6Zhwc7L1t3ETXCY4CU9KQwtFsKrd8VJyzwLXkJVI3myYR3UQceLraEdkDaj6BTPevSRWawNG0MrXEkBIT96Cmo4H0Vl0YVoTGIuwA+qLG0LTsDa1pbBcbL6i56BWbAeH6XJMxlQvzVVIk0EOZ2F7TqAjBQIM7ifkLxw0+CxJE1bVMNP8YwSiyn29PgXr9huA3A5jEloQiwExEzQnQARM7+6woEDn+ZANWMiiHM58LFEfEALdEkNMMazGE9m3BZXqMWZ7NMVlwmowJwgMM4RZqiqiGWBdJAREgk1jtbeQrrF8fiTKQtI+bDvFR4ldhJIkSlLSEXNBbJB9WU7FZEmM8sXQNywihiwFgFoXF9Bi7GgjTAu3aTBCI9DpAGeG3u54ibk8WGIzuDIojsA6KGidRPsJ4F4zgtlXqMj+4T6VV3HrENkLM7xQB/M9dwHsxZDd2P5bLRT4OeqEJWXg3ZWUzfetcyV6ekXSc3A0okWly5Ys8A7RjLHxR51Sxy97YNwFPPgikG8258G2Mh7LAkQSIekcA4koLL4xpXEmEX4Yb2j2Y6wgBJMHRMoK4uH1tgcDxTGAQQtAC6DzlaoBcLdBOeCZcCxERI/GAMNAIc2oAygEDiDrase6qcUR1ukFoiNCQtcACe1AnBSCsDhxilSU2BHyw0uozZpTV9LLCXhnl7+mpscW5YwzMONvEHGZoN30H3j1hgDuIJqNpgOXZflxOhM/mnL2ctEf3xwbBijNugcs0P4moUUoSwmtzA1srMVtGc6XZRSGJO2qWlQOqWhJwOVaH/nCeKGg7DbX69KUZ0Hg2LcgkAxMA8GhQpHuQnGDJry0XEENwZmOTrj+U3Yex6dU4e5ESjOxAlSkhedZJF2ZYcWkxlFkAButDM9RgyYnzpEZK9KnFG0kgLneIyBEW3wOuvXO7zORTCh8+wIHGUQOC4Kn6Z/HVxU1cCn6BLwHMNAaeA5TpsZatKw4l3mOnRQtRkygVQauwgi/xYAjvQ9qKdsESh4oE2tuIjbgNwEjDSXzkMjAD39xmFZGUx9Oq+vC7awOqjXQpsIbVxNokVIo86Uk0dgkrPsi6QaxqjjLDSR4sVuiMO6YlUz1GpMQN8+/VirsDgpHwhutT016CEMFo0EPKvogvig84r2gbkxJggLgb7cdbseKg5qIB0MaTrc5TbFMO3KXukU05hxWAmDiYHyUFaYDeoMe/KKkMDYA+voEYqAOMyP1dz464oZF8rMwNdWHc51m1TGC5w1VvOM10bVDXKMcF8JhrrHaH0CIlW7GwENmF7fa04XzYVKBTR4ao31vUAdhm68IOg6LS8NLwifH3lW3Ff+jYHS9vgQhIkj8rpl3mjaXLjMYAh9P88uqrrU5xuPS4zF0Nbkwyi28Z6M6gWSx7bMQPKx62tTRBediCOBVxr51q1bR0UI0Gcow9Hm8kv+Z3GaxoPNs2xSGAeeCcHtItSc/pHoNz+LZUVh4YjYSx1mXIG1xNiCVyTWrSVmVzxTG1SqG3e7C4JgeJ4LbcB1k1yJGZe7BIWdDUNlLWUDkPpaQZxLwgdVHpyQJUMwByRG6k/8taQQhm03JaCToqngCb0lFx4c0OeOG67SnAuoXpFAtV5xqWtm6irpUrxAJcoTYsPVTLUzVySWbZ1AhK5nImsgwMugXGanaRHMjCGeeYpBkmetmHgbPAemPXnaAF5IBSlYrRGu0Tsm0OCKJGopNgde0hl5SQEv5kdv5+ElceQlRrwYwMexI/3IkX7kOC9CA/oKCN+BgwBxwG+gAfAd6PskfQjZMx7sIHsXqS7JeaU0tWz0HKnmMGBvVAZdiaYMKmpDZJ+TIQk1mwrLdxgWb0bVRWouDOMbV60nNRNG5xlPIl1jJD2obDSzk1QvRMiNeZnUuLiXb3UtYQavEau/R/eI4b6zrWiIoLOSiGfccFnKwl5PqKMvbvMPJhK80F0hHsosoEH1OQ7PoUPcJmkKiduKMlo/XSoBhOynta9hoWYXNA/VcHbG6pmo0CToc1Pu/tRi9/MlFsCLIqwhEXSFBbexMWewrpIzrm93mHESPB0zC9P++UCvsUJBRxZsBQ3jT865Aw4hscwqmWHOnAIcVDSw1umUCF1WASedwVemM+jyBRg5wY0flsL5xcdnAm1yAie7LaSTFXj2gxWYGNIJC1NEGev6OQutWtYBnggTXZA2f8ICuOKNrWjVeXaTDqFaoipaxiiLh0qhkge6xnDk3CeLXU7+ImxWXXlchxgxEt8mePNIv2Fge/TQGBnWJSFOiU6ZJQgDGU1w6VGGO6SGsW33SZBxMe+MxLzt0dyMwroR8Ze64zEDKszSfc2mmpUHHswDzoDrfG3xW3SlsANXs9SYbLmap14lqFnjxNU8Jwip/FM29ovSZ1lI1MhAxZFnaEg7dNUN585InJu7g2Uz4t8Z8tigLZxRiLe+ea6unAu6zkjoWjeyM523zkjsWscAUU6coDCfqrOrp0v1fD5l53IUF57o1O1sQe23BiNtgcyk+snxgxa6gEOrMaaQtjPB3VmUVo6UUkSJcyKeKUoaPjclmjgSjRFRQ5zcRdKRI/3IkX6I6Bug1KGj/AOD/tPVql0k4DtKwKfoY/Qc91WZp4Z0FH383XAFkUoJouTjJ02LWpGKCaLfsCvGexDSS3Q9ajg+IJ7Pec6jtQvALpy2IVqPAEiHxTvUDLw7Dlnt0ysfIIm8BcZtES1ZxmWc+qbdBhHC2STwzUltURQRUY2hxz3DDsuHk7OJ8yC8Y9cFwUEX6/KSTBzOWBuDYDFwXCjNM/GKZozMoltb9NKCNbucSyYzPE6Y+Q3DoSjf3BzI4wReUXSBvHTCHBs0CC8uKfgPgnAvV3a6bp+TiBgowUCL+FjAxAhDGiN0731IYIcQf7O8fxtDbRzUL6ZRP13X3+wuj+V+WtxrWMbbCcGu2ZsLMUTX5mHsBNzWR+NkIadFUKsWzkR0EJA4MUlhaKpEWogK0fiR+hY0sBNwohNO7l4dsOHw38SAGEeRmhAQu0UGYFU/qI6yEiGrv0cN8Qb0Q50C96cvp0vFEs1oRMBYdvWDs+BWLc1Z2grADcxOXM3SVkDdPKBxANDVBw4csGpwodImmnUTUHlGnO7NkjgcICsLuqcBNPhcqDKszI6qA1bV0HKwnTsejE9oNpTnKSzc8sBwKhqq88BYLVVjj6rhwfD2ypYYekuVKKFMxV8C99lNFqgxHQPzAFsBvBDQZQFaQe8UX/NUH6QPWJktVh2S/3FxEiaJ+PP+l8Mmb2yLP0Rj98LueJ8fxb+CnjA3tuXdXbm57M7P6++L8vy8OD0VxXb9TjxyfjjsF0+7/Ll68I8vm4fDqdi/LT+tv8tvn3fX3z48PxXrny6PtW7r//+4EK7HbXH89a66i6S6f0T0abnYH77Lj7f5scwFQ7V7sb9sdkV+/L3InwST/9jntzvBwF2+OxViKeyE9XTYd9/WL3wqN+fD8bmiK/j6/iCcnLqDi5tNKTpfiv4s3ooeVXdDf1w85p8/VLfTi+W6FKNxrj+H3UGc93UXrj1qv61euKnE96EUVpqfxEnop/4qWAmrvhLgz1vxpR+HSZJ6eRSEXpSmqXcb3W69bRgvg9swvE3C+Ov/AbzdJvMvcwEA</summary>
</details>

**Expected behavior**
As in the android version saving game just normally, every save should be shown only once.
**Screenshots**
<img width="364" alt="Screen Shot 2022-06-26 at 13 53 20" src="https://user-images.githubusercontent.com/1908759/175801486-38e957b1-62a6-432c-baa6-c2f4a5a2f74c.png">
<img width="445" alt="Screen Shot 2022-06-26 at 13 53 58" src="https://user-images.githubusercontent.com/1908759/175801490-c70f1c31-4e95-474b-89a8-ff457621e607.png">

**Additional context**

Bellow is the terminal message, it shows an error but still playable. I don't know if it matters.
`Error in LSRegisterURL: -10811
2022-06-26 13:44:07.376 java[2053:107508] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.`

**Comment by yairm210** [comment]
In that case, I'm willing to regard this as resolved. Worst case we didcover it isn't she reopen it
