### ISSUE TITLE
New diplomatic system bugs

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#732]
I found 2 problems with the new diplomatic system : 
-the most problematic : when you reload the app it reset your diplomatic relationship.
-dying civilisations become spartiate, before, when you was near to destroy a civilisation she was ready to give you everything to survive, now, because you have a lot of negative relationship points, she still want the peace but just for few gold

**Comment by yairm210** [comment]
The first problem has been solved and is rolling it in the latest version :)
The second is indeed problematic, well need to have fear outweigh the 'cost' of bad relations
