### ISSUE TITLE
Cost of trade luxury

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#7328]
During the eras the cost of luxury stay the same (same the strategic resourses)
I think it gives player a "bad" advantage

At the start eras 3 gold per turn is rather costable, but during the eras it became more and more laughable
I say g per turn because I always pay gpt, its more profitable
So, I suggest to increase cost of luxury resourses by 1 gold per era, and it is stay laughable I think, but at first we must see how it would implement and playeble

So, 3 gpt in Ancient ers, 4 at Antique, and so on
So adjust must be in cash and strategic resourses ( in this I can't say the amount of adjustance)

So, it's stay one more aspect
The cost of last luxury resource
Now it is 6 gpt, I suggest to increase it +2 gpt during era

I just laugh when AI have about 400-500 gpt, and it agree when I take his last luxury resource by 6 gpt
Its unfair

May be its better to bind the cost of luxury to the number of capital and gpt of AI, but its harder I think

**Comment by alexban011** [comment]
In civ 5 resources have a fixed cost, regardless of era

**Comment by Timur512** [comment]
It is not civ5, though it is base on it
I think it is something like a bug, in common sense when u have 500 gpt, sell a luxury by 3 gpt, which makes your foe more stronger, it is nonsense

**Comment by heipizhu4** [comment]
> it is nonsense

Hey, why not sign declaration of friendship so you can sell at a more reasonable price? Besides, you should sell something that you don't want, so it is a win-win.

**Comment by Timur512** [comment]
I didn't know that declaration of friendship reduce the cost of resources
`Besides, you should sell something that you don't want, so it is a win-win.`
I change resources at the beginning and in the middle of the game, at the end I often have 400+ gpt, so it unreasonable to sell goods so cheap

By the way, my idea works to another site: so player could sell his resourses at the end of the game with increase price

**Comment by SeventhM** [comment]
Closed as solved as of #10370. This should be reopened as a new issue or have a new comment if it is still relevant
