### ISSUE TITLE
Is the official server running?

### ISSUE THREAD

**Issue by Erz3** [yairm210/Unciv#7354]
I have been two days with problems to continue playing with my friend because I can't connect with our match on the official proyect server.

Client version: 4.0.6
OS: multiplatform

**Comment by OptimizedForDensity** [comment]
4.0.6 is fairly out of date so you and your friend should definitely update. The official server is Dropbox which has some rate limiters for the account but there is another server you can use and also tools to host a private server https://github.com/yairm210/Unciv/blob/master/docs/Other/Multiplayer.md.
