### ISSUE TITLE
Gatling gun without Gunpowder

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7363]
"name": "Gatling Gun",
		"unitType": "Ranged Gunpowder",

can be obtained without Gunpowder technology

maybe needed:
"uniques": ["Only available <after discovering [Gunpowder]>"]

**Comment by ravignir** [comment]
you can also get battleships and missile cruisers without sailing. Not a bug, just something dumb XD

**Comment by MindaugasRumsa51** [comment]
this can be fixed adding Navigation requirement to Scientific Theory, not to Archeology

**Comment by MindaugasRumsa51** [comment]
see - vanilla do not have such bug:

"name": "Scientific Theory",
				"row": 4,
				"prerequisites": ["Navigation","Acoustics","Economics"],

**Comment by OptimizedForDensity** [comment]
I think these changes are better suited for a mod since the tech prerequisites are correct according to their Civ 5 Gods & Kings values.

**Comment by yairm210** [comment]
As Optimized says, we're going by Civ V rules in the official rulesets

**Comment by MindaugasRumsa51** [comment]
those are last such bugs or there are more?
and yes, waiting for "fixing mod"
