### ISSUE TITLE
Issues with diplomatic features

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#740]
1. Friendship Declarations
      a. Will never be declined, even directly after a war (or before, in the case of aggressive civs who are planning to declare war on you) you can always declare friendship. 
      b. Friendships and their diplomatic bonuses will persist during a war. You will also retain "Ally" status while at war, and your "years of peace" bonus score is similarly unaffected (and in fact will continue to grow).
      c. No diplomatic penalties or infamy for betraying friendships other than the generic warmongering penalty. 
2. Open Borders
     a. A.I. will accept proposals for open borders while at war. 
     b. friendly A.I. will pillage your work-boat improvements to repair their units. Have not noticed this on land yet. 
3. Trade
     a. A.I. will propose trading a luxury resource to you for only 1 gold per turn
     b. Enemy A.I. will accept trades for their luxury and even strategic resources. This is especially game breaking if their economy is poor as they will trade strategic resources for very low sums. For example I declared war on a Civ with low GPT as they were already fighting other civs, and soon after they agreed to sell me iron and other resources for 50 gold each (the minimum).

**Comment by ozyxcv** [comment]
Sorry for the wall of text but I thought it would be be best to include all of this in one go rather than posting multiple times. I hope this helps!

**Comment by yairm210** [comment]
First off, thanks, this is super helpful1
As you no doubt noticed the diplomacy is now in its initial phases, and will definitely improve over time =)

1.a well hey, if you're still in such good relations with them after the war, then why not? This is how Europe was for several hundred years =)
1.b Good point, diplomatic relation with civ you're at war with should ALWAYS be set to Enemy, thanks!
1.c Is planned, will be added =)
2.a This will be solved with 1.b, and ALSO would be solved with having you not be able to trade during war as per Civ V without including peace treaty - planned!
2.b ...fascinating, I'll check why this happens
3.a What?!?! Luxes are supposed to be 300 minimum, that's 10 gpt! Definite bug!
3.b This is going to be hard to check, I think... how do you know when a civ "needs" a resource and when it doesn't?
Still, we'll see what we can do, a simple check is to have the civ always leave itself 3 (or 5) instances of every strategic resource it can currently use to train troops with when at war

**Comment by ozyxcv** [comment]
thanks for the quick response!
In regard to 1.a, I understand your point but at the same time when you implement 1.c I believe warlike civs will be at a disadvantage if they are incapable of rejecting offers of friendship. Players could simply declare a friendship with a civ that will soon attack and that civ will be forced into incurring the greater diplomatic penalty for betraying a friendship. Admittedly I haven't played Civ V for quite some time but if I recall correctly warlike civs would reject friendship proposals for that very reason!

As for 3.b, I think a simple fix for one aspect would be including only the option to ask for peace while trading with an enemy civ. I believe that is how it was in Civ V but I might be wrong about that. 
About the greater issue of buying resources for low sums from struggling civs (who are not your enemy),  I am not too sure about that. Once again I think even in Civ V you could get favorable deals for resources from civs in need of gold, so there's nothing necessarily wrong with it. Perhaps you could make it so the A.I. values their own strategic resources more if they are at war? Ideally this would mean that era-specific resources are valued more highly during their relevant era, for instance Greece would be less willing to trade their horses in 1000ce than in 2000ce when they no longer need them, though I understand how that would be tough to implement.

P.S. I'm attaching screenshots of 3.a to this comment so you can at least see the issue, I would include a copy of the game data but it is a massive wall of text! I'm not too sure how we're supposed to share that. 

![Screenshot_20190511-145220_UnCiv](https://user-images.githubusercontent.com/49125947/57574616-f1153900-7401-11e9-9e99-2adc9544101c.jpg)

![Screenshot_20190511-145232_UnCiv](https://user-images.githubusercontent.com/49125947/57574618-fa060a80-7401-11e9-88b8-1e9e65f1c650.jpg)

**Comment by yairm210** [comment]
Ahaha, now I see what you meant with the luxes...
No, what she's offering is whales for gold LUXURY, lux-for-lux trade
I agree that having a luxury called "Gold" makes this confusing, I'm sure there's a way to make this more understandable...

**Comment by yairm210** [comment]
Just implemented "no trading in war without peace deal", so that's already a load off =)

**Comment by ozyxcv** [comment]
Oh gosh I'm obviously not too bright, but hey at least there's nothing to fix there after all! And wonderful, I think that is a perfect and simple fix for the issue. Keep up the great work! :)

**Comment by yairm210** [comment]
Remaining problems:

 - 1.c.
 - 2.b.

I'll make a separate issue for each one, now that the main mass had been resolved
