### ISSUE TITLE
2 ui problems

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7409]
1. unit overview screen - cant' use units if you do not know what means small line above, cause this window not scrolable
![ui_problem1_1](https://user-images.githubusercontent.com/107413099/178093301-75fae7bf-fd3b-4cf3-8cf9-5d541a9af935.jpg)
 simple solution via translation:
![ui_problem1_2](https://user-images.githubusercontent.com/107413099/178093352-4369cee9-7b44-4fe8-8e8a-7bb667fa7a19.jpg)

2. trade window do not shows button text
![ui_problem2_1](https://user-images.githubusercontent.com/107413099/178093404-9f8109a8-1385-4223-8a17-dbbb003c3039.jpg)
 how personaly i could "fix" it:
![ui_problem2_2](https://user-images.githubusercontent.com/107413099/178093435-338f7757-c4ec-4c44-8b9d-5d11f1aee926.jpg)

**Comment by MindaugasRumsa51** [comment]
resolution 750x500, font default, size max

**Comment by xlenstra** [comment]
I'm not sure what the problem is in the first screenshot. I'm pretty certain there is nothing above the supply box?
For the second screenshot, your problem is that the 'propose deal' button is (partially) hidden on lower resolutions, correct?

**Comment by MindaugasRumsa51** [comment]
1st: i can't scroll to "unit supply" button cause window not scrollable
when i changed long text to short in translation, then "unit supply" button available

2nd yes

**Comment by alexban011** [comment]
>  is (partially) hidden on lower resolutions

and on max font size. I think this only happens when the fontsize is on 1.5f

**Comment by yairm210** [comment]
Checked this now, even on max font and min resolution didn't replicate
