### ISSUE TITLE
Nation colors switched upon kill

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#7419]
**Platform**
Win 10 64-bit

**Version**
4.1.17 (Build 735) from Itch.io launcher

**Describe the bug**
When a melee unit kills an enemy unit and moves into its tile, the attacking unit will erroneously take the nation colors of the defeated unit (temporarily, until the next turn).

**Before kill:**
<img width="444" alt="Before Kill" src="https://user-images.githubusercontent.com/56904240/178156637-66950b40-4737-41eb-ace6-572406190345.png">

**After kill:**
<img width="428" alt="After Kill" src="https://user-images.githubusercontent.com/56904240/178156651-d640e5d8-89ff-4604-8899-3bd97249d0af.png">

**To Reproduce**
1. Kill any enemy unit with a melee unit
2. See the error in color handling (note: requires a tileset with nation colors such as Hexarealm+AbsoluteUnits or 5Hex)

**Save game (before kill)**
[Color_test_before_kill.txt](https://github.com/yairm210/Unciv/files/9079586/Color_test_before_kill.txt)

**Comment by OptimizedForDensity** [comment]
There seems to be a related issue where if you select one of the warriors two tiles away from Tyre then have it move and attack in the same action it won't flash red from taking damage.
