### ISSUE TITLE
Hexarealm as default tileset + github discussion page

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7434]
I have some suggestions, one is for the game and the other for its development.

1. Could we make the Hexarealm the default tileset? I like the current default tileset but most people like higher resolution graphics and I think it would be beneficial for the initial UX to have Hexarealm as the default tileset.

2. I'd like if the github discussion page would be opened. Sometimes I have some questions or want to ask for opinions (of devs, not the community) and the discord #developers channel doesn't really do the job since the message is usually lost after a couple hours/days and some aren't even on discord/don't read the messages.

**Comment by letstalkaboutdune** [comment]
> if HR is gonna be the default tileset, i propose FH will still be an option you can choose. its mainly because FH are more performance friendly for those of us with low-end devices.

I don't see any reason to remove FH even if a new default is selected. Some users will always prefer it, and having the choice is always better.

**Comment by heipizhu4** [comment]
The problem is, if we do change it, lots of old mods will be unusable (eg. Deciv, Alpha-Frontier). So can we auto-switch to FH when using mods?

**Comment by heipizhu4** [comment]
Sorry, I didn't expain myself clearly. I mean, if a new player download some huge mods like Deciv or Alpha-frontier and that player have completely no idea to switch between tileset, these mods will look terrible. 

Possible solution: Shall we inform players to switch the tilesets before running mods?

**Comment by alexban011** [comment]
I mean... most people don't play with mods so it wouldn't really be a problem imo.
