### ISSUE TITLE
Ai offer debt as trade

### ISSUE THREAD

**Issue by Nonz3ro** [yairm210/Unciv#7438]
I'm trading with Mongolia for open boarders and in their counter offer they are trading -15 gold.

![Screenshot_20220712-131035_UnCiv](https://user-images.githubusercontent.com/109172847/178583527-755217d6-fddc-4b59-80c5-c7f3ab11bd45.jpg)
![Screenshot_20220712-130002_UnCiv](https://user-images.githubusercontent.com/109172847/178583529-3f55e764-9021-4ad4-b13e-0f84956e7bae.jpg)

[Bugged Trade.txt](https://github.com/yairm210/Unciv/files/9103780/Bugged.Trade.txt)

Save file as .txt ^

**Comment by Nonz3ro** [comment]
Couldn't add save file it passed the character limit

**Comment by letstalkaboutdune** [comment]
> Couldn't add save file it passed the character limit

You can save it as a text file and upload that as a file instead of text.
