### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by Why-not-now** [yairm210/Unciv#7449]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
itch.io v4.1.18

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest version of unciv on itch.io
2. Unzip the file
3. Double click .exe file
4. Game does not start up

**Expected behaviour**
Unciv starts up

**Comment by yairm210** [comment]
What operating system are you using?

**Comment by OptimizedForDensity** [comment]
Looks like some version of Windows since they mentioned .exe

**Comment by Why-not-now** [comment]
Oops, I accidentally reset bug report but windows 10 x64

**Comment by Why-not-now** [comment]
No file were created

**Comment by Why-not-now** [comment]
On v4.1.19, it still does not work

**Comment by Why-not-now** [comment]
Closed because bug was of a different issue than originally thought
