### ISSUE TITLE
NextTurn button rotates among unmoved units, forcing more clicks.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#745]
Now I have to sleep or fortify all units before clicking NextTurn. Takes a lot more time and clicks. Maybe it should spilt into another button?

**Comment by yairm210** [comment]
You don't have to sleep or fortify, you can just pass on and it won't return to the previous units
That's how Civ VI works, I know
Honestly don't remember the Civ V setting
But you can disable it in the options so I think that's fine,

**Comment by ninjatao** [comment]
So there is option for that. That makes it reasonable. Thanks!
