### ISSUE TITLE
Folder with images named `Image` in parent directory of unciv main folder loads `image` folder

### ISSUE THREAD

**Issue by Why-not-now** [yairm210/Unciv#7474]
**Platform**
Windows 10 64 bits

**Version**
itch.io v4.1.19

**Describe the bug**
When a directory of this order
```
parent folder\
    Images\
        image.png
    unciv\  # unzipped game folder
        ...
```
The program tries to load `.\parent folder\Images\image.png` (naming and capitalisation matters)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a directory as below
![image](https://user-images.githubusercontent.com/81090788/179388001-c661da36-4d19-4fcc-8c63-501df495a002.png)

a) directly open the file
2a. Double click the .exe files
3a. No error occurs, but the game does not load if images are invalid

b) using a command prompt to open the file
2b. On command prompt, go to the unzipped unciv file
3b. Use the command java -jar Unciv.jar to try to open the file
![image](https://user-images.githubusercontent.com/81090788/179387982-bf658e7e-fa54-4966-bdd8-bd88082fd78e.png)

**Expected behaviour**
The game should not attempt to open the `Images` file.

**Comment by yairm210** [comment]
Accessing the images folder is intended behavior for development purposes.
Doing so while running from a .jar file is not, we'll need to check that condition.

**Comment by yairm210** [comment]
This was resolved a while back, not sure why it wasn't closed
