### ISSUE TITLE
Copyright of texts

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#7479]
The texts of every introduction, “May the blessings of heaven be upon you...” are protected by copyright. I think they are better removed. No one read that anyway.

**Comment by ArchDuque-Pancake** [comment]
I actually do read them :(

**Comment by letstalkaboutdune** [comment]
I volunteer to help with this. They don't need to be an essay, just 2-3 sentences at most. Perhaps most important is an equivalent for the part repeated for every civ: 

_"Can you build a civilization that will stand the test of time?"_

Maybe something like: 

_"Will you forge an empire that lasts through the ages of history?"_

**Comment by alexban011** [comment]
Can they copyright such texts ? (Or to be more specific: Did they actually claim ownership over those texts?)

**Comment by yairm210** [comment]
Any text they write is automatically copyrighted as part of the larger work. Whether they claim ownership might be interesting from a "will they do something" perspective (answer: no, they've been cool with worse things), but from a "can they do something" perspective the answer is "yes", and we want to be clean :)

**Comment by letstalkaboutdune** [comment]
I think it would be pretty manageable to get new text in there, especially if it follows a template. Something like:

"Oh <adjective> <name of Civ leader>, you <famous accomplishment during their reign>. But <describe the fall of their empire>. Now you have a chance to re-write history. Will you forge an empire that lasts through the ages?"

**Comment by saud2410** [comment]
I think not every civ would have "call-ups-downs-ask" intro. There can be call-downs-ups-ask pattern too. tho it's a matter of sequence.
