### ISSUE TITLE
Feature request: Support for unit sprite variants when carrying other units

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#7482]
This is along similar lines to #7476 in terms of making the game information more graphical. I want the dev team to see both requests at the same time so they can be as efficient with implementation/code reuse as possible.

I request that a unit (such as a Carrier) support different sprites depending on how many other units (such as planes) are docked on it. In the case of a Carrier up to 5 planes are possible, meaning 6 sprites (empty, 1, 2, 3, 4, 5).

Example of empty Carrier:
![image](https://user-images.githubusercontent.com/56904240/179613507-4d46025f-757c-4a09-8a2d-e7ce8aa3d865.png)

Example of fully loaded Carrier with 5 planes:
![image](https://user-images.githubusercontent.com/56904240/179614259-0fc97cde-809b-41db-aec6-46ec82a658b3.png)

.zip file with empty and full Carrier sprite variations for use in dev/testing:
[Carrier_Example.zip](https://github.com/yairm210/Unciv/files/9135685/Carrier_Example.zip)

(Edited to remove request for damaged unit sprite variants)

**Comment by yairm210** [comment]
I disagree with damaged units.
There are far too many variants as-is, each additional layer makes it more challenging to create new units, both for base game and for mods.

**Comment by letstalkaboutdune** [comment]
That's also true. Well I'll let you guys sort it out. I'd be happy with just Carrier-type functionality being supported, as I have plenty of sprites to design as it is.

**Comment by yairm210** [comment]
@Azzurite That's kind of naive.
We want our base tilesets to have some sort of standard, as it would look strange of only part of the united have damaged images.
What we could do is simply not allow them in our base tilesets, but who's going to stand guard?
In either case I can easily see such issues piling up

**Comment by yairm210** [comment]
This is about managing player expectation and experience, and imo having only some units have damaged variants is a worse experience than having none.

But that's just like, my opinion, man

**Comment by letstalkaboutdune** [comment]
Since I'm requesting it, you can count on a complete set for my unit sprites if this gets implemented. For other tilesets like FH there will probably be no damaged units created, but as long as the code simply pulls the default sprites in that case it's no harm done.

**Comment by letstalkaboutdune** [comment]
> > it would look strange of only part of the united have damaged images [...] who's going to stand guard
> 
> If that's really important we could simply add a small code check that checks if all units have damaged variants, and if not, then shows none. So damaged variants are only shown when all units have them.

That would make designing the sprite set very hard, as I frequently make edits after checking in-game and like to release updates in batches. I ask that you not implement this "all or nothing" check.

**Comment by itanasi** [comment]
Personally from an opportunity cost perspective, there's much more important things than damaged unit sprites. Feels very low priority.

**Comment by letstalkaboutdune** [comment]
> Personally from an opportunity cost perspective, there's much more important things than damaged unit sprites. Feels very low priority. Especially since we'd also need to hash out what counts as "damaged". 99 HP is technically hurt, but I don't think you want to show a weakened unit sprite.

This is pretty simple, the game already checks HP to assign an HP bar color of green, yellow, or red. I would plan to use the same levels which I believe are around 67 and 33 HP, resulting in 3 sprites: Healthy, Moderately Damaged, and Critically Damaged.
