### ISSUE TITLE
Problems with cultural/domination victory

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#751]
cultural: I have never seen the AI win a cultural victory. Even civs like Egypt or France who could run away with a cultural victory on high difficulties will virtually always build very wide and hurt themselves by placing too many cities and attacking their neighbors constantly. Maybe this is just my experience but it doesn't seem possible for it to happen

domination: although technically impossible for the player to see the AI win a domination victory, I believe because of the too-many-cities issue I mentioned before combined with needing to capture *all* cities, that domination victories are a bit tedious for both the player and AI. (Have you considered changing the requirement to just capturing all capitals, like in civ v?).

For these reasons it seems that every game I play on prince/king difficulty on a larger map ends the same four ways: with me being destroyed, me winning, the AI winning a space victory, or the game crashing after too many 3 minute long wait times per turn after the year 2000. 

P.S. the ability to resurrect previously dominated civs by returning their cities would be nice, as well as being able to choose which civs are included in a match.

**Comment by yairm210** [comment]
Hm
I see your point on all counts
There are two main underlying issues:
A. AI is NOT victory-oriented, it doesn't act differently if it's closer to a scientific or domination victory, instead it just does whatever
Apparently that's not good enough for cultural victory, which requires focused effort
B. Domination victory should be reduced to 'be only civ with control of original capital' - definitely doable, requires us to save info on original capitals and not allow razing for them

**Comment by yairm210** [comment]
This was a tough one, but...

![image](https://user-images.githubusercontent.com/8366208/59432025-03163d00-8def-11e9-9b24-a7dbac8b6559.png)
