### ISSUE TITLE
Notifications Tab in empire overview

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7529]
problem, when scrolling - window do not remember scrollY

i tried create PR: https://github.com/yairm210/Unciv/pull/7499
but i really do not know how to work with this github

**Comment by MindaugasRumsa51** [comment]
Ouaz, thanks for help

**Comment by Ouaz** [comment]
Actually, I was wrong ^^, I've been mislead by the fail icon being only on the branch merge commit:

![image](https://user-images.githubusercontent.com/11946570/181368621-e7f16278-bb59-42fe-a993-05b895bf2da4.png)

But it seems something is wrong with your code in `NotificationsOverviewTable.kt` (#7536)
