### ISSUE TITLE
Automated science and Mods

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7530]
when you have mod with two (or more) different technology paths, you will never learn all techs.
problem is here:
ConstructionAutomation.kt  line:
   val allTechsAreResearched = civInfo.tech.getNumberOfTechsResearched() >= civInfo.gameInfo.ruleSet.technologies.size

i would change it to line:
val allTechsAreResearched = (civInfo.tech.era.eraNumber + 1) >= civInfo.gameInfo.ruleSet.eras.size

but i not sure about correctness of such change

**Comment by yairm210** [comment]
Your change would not solve the problem, there could still be unresearched techs in previous eras.
What we *could* do is change it to "available the to research = 0"
