### ISSUE TITLE
The latest `Unciv.jar` still reports version 4.1.22

### ISSUE THREAD

**Issue by Thyrum** [yairm210/Unciv#7554]
**Platform**
Linux

**Version**
The `Unciv.jar` file in the `4.2.0` release on Github.

**Describe the bug**
The jar reports version `4.1.22 (Build 743)` under the "About" section in the settings but it is distributed as part of release `4.2.0`.

**To Reproduce**
Download [this](https://github.com/yairm210/Unciv/releases/download/4.2.0/Unciv.jar) file and look at the version (options -> about).

**Expected behavior**
Report version `4.2.0`.

**Screenshots**
![image](https://user-images.githubusercontent.com/25480466/181777081-f803b79a-36c3-4deb-9818-46c0a3f11b17.png)

**Comment by yairm210** [comment]
Yes, will be obviously fixed in next version, nothing we can do about the current version
