### ISSUE TITLE
Feature request: LeaderBoards, ScoreBoards

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#7562]
The proposal is simple: to add worldwide LeaderBoards.
That everybody see, who get the highest scores
Divide this boards to pve, pvp, and maybe with mods.

Also, when I wrote this post, an additional idea came. 
May be in future, to hold some championships, and that a functionality of a game could realize this. I mean to implement in the game tools, that would allow to join or hold some championships

**Comment by yairm210** [comment]
Worldwide boards of any kind indicates a place to store this info, version parity, no gamebreaking mods, and above all no way to cheat the system, all of which is currently unavailable.
