### ISSUE TITLE
Bug in text

### ISSUE THREAD

**Issue by pyotr71** [yairm210/Unciv#7563]
I found a text error that appears on the combat screen (Jaguar unit)

**Screenshots**

![ability](https://user-images.githubusercontent.com/18636457/181937021-c821f2cb-f778-4dab-8ab1-127067088b8d.png)

**Comment by OptimizedForDensity** [comment]
This is a fun Regex nested brackets problem (`squareBraceRegex` applied to `[[Jaguar] ability]` yields `[[Jaguar]`) that I believe can't be solved through Regex.

**Comment by pyotr71** [comment]
Thanks!
