### ISSUE TITLE
Delete one "Consumes ..." lines of city screen

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#7565]
If a unit or building consumes resource, you can see `Consumes [amount] [resource]` line in the city screen. But if you don't have any of it, you can see the line in red AND white both...?

I think only 1 line is enough for noting it.

What if the line changes its color depending on the resorce?
- while i have resource, only white line is shown.
- while i have no resorce, only red line is shown.

![Screenshot_20220731-162353_UnCiv](https://user-images.githubusercontent.com/64586749/182019256-e7d92218-8487-4dbf-a96d-af6a79f063fa.jpg)

**Comment by xlenstra** [comment]
If I'm not mistaken, the red line only shows up if you don't have that resource. Should be an easy change to hide the white line in that case

**Comment by kasradzenika** [comment]
I think white line should stay shown but the red text should change to something meaningful. 

Scenario: the unit consumes 2 iron but u only have 1

white text: "Consumes 2 Iron"
red text: "You lack 1 Iron"

I think this is more clear

**Comment by saud2410** [comment]
@xlenstra That leads exactly same result i wanted :)

@kasradzenika This would be also great. Imao the problem is "2 same lines are unnecessary to show status of strateguc resource".
