### ISSUE TITLE
Add river on civilopedia

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#7596]
**Please consider adding river and its description on civilopedia - terrain.**

All terrains are documented except river.

Yeah, they spawn between tiles, not on them.

But i think... it would be good to have it.

River also consists map.

And iirc we don't have explanation about movement cost of crossing river; expending all cost.

**Comment by AdityaMH** [comment]
Instead river, add fresh water info in civlopedia also can be better.

**Comment by OptimizedForDensity** [comment]
Since rivers are not a tile technically, having them split between a "Fresh Water" (or something similar) section and a "Unit Movement" section might be better.

**Comment by saud2410** [comment]
@AdityaMH I don't think my suggestion is the best answer. But fresh water is category including river, lake and oasis. If `fresh water` would be made there also needs rough terrain and open terrain i think. River does need its own document.

@OptimizedForDensity Would it be really hard to make `river`? Is it possible to make exception on civilopedia? I can't say "we must have it" cuz i'm not the one who actually make it. I'm just asking possibility.

**Comment by saud2410** [comment]
It would also work just making "River" document in pedia-tutorials category. But when BNW comes to Unciv, river would have different unique per ruleset, which means river would have uniques. I think `river` needs separated article not only because of its mv cost.
