### ISSUE TITLE
Buildings work after required resource is gone

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7607]
*Either a resource or a tile improvement as requirement for the building to be build.

It happens that the building continues to provide its yield and bonuses after the resource is no longer aviable to the player.
Example: I have my Factory, but while in a war my only source of Coal is pillaged. During the time that the Coal is destroyed, my factory is still working, not having any 'maluses' for not having the resource.

This also happens with for example the Stable, after the Pasture is Destroyed I still get the production bonus.

What should occour?

That the building may stop giving it's attributes until the source is reestablished.

What if you have 20 factories, and you suddenly got only 8 Coal? There would be only 12 cities where the Factory is affected (randomly chosen), and the other 8 are untouched and continue as normal.

PS: I know this structure as I wrote it now may be confusing, so I'll re-arrange it later.

**Comment by ravignir** [comment]
Not a bug. Works exactly the same way as it does in civ5.

**Comment by Caballero-Arepa** [comment]
Is that so? Because that is very abusable. I can trade some Coal for a few turns, build my factories and after that I dont need the Coal. Basically I can have buildings without actually having the required resource in my hands.

If yes, then at least a unique for that. Idk, maybe <without [resource]>

**Comment by yairm210** [comment]
Not a bug, working as intended
