### ISSUE TITLE
Image folder missing after extracting .apk data on windows 10

### ISSUE THREAD

**Issue by Error3825** [yairm210/Unciv#7616]
**Platform**
Galaxy A53 5G, Android, 12, could not find architecture info.

**Version**
UnCiv 4.2.1 (I got it from google play)

**Describe the bug**
After transferring a copy of the .apk file (copied using file explorer +) file to my laptop and extracting the data using 7-zip I noticed that the image folder was missing and thus I could not create a working civilization.

**To Reproduce**
1. backup the .apk using file explorer + on an android device
2. using a usb cable transfer the copied .apk to your computer
3. use 7-zip or default zip proggram to extract the files
4. image file should be missing

**Expected behavior**
I expected all the necesery files to be availabe, yet the image folder was missing

**Screenshots**
![image](https://user-images.githubusercontent.com/110694644/183151464-2c1db526-25af-4392-b968-a35a8246c2c9.png)

**Additional context**
I may have done something wrong along the way but I couldnt find what concidering most if not all other files/folders were there.

**Comment by itanasi** [comment]
Why are you unpacking the Android apk instead of just installing the Windows version?

**Comment by Error3825** [comment]
> 
Well I wanted to use the android version because then I could acces the game almost anytime, but I cant access my computer that often. And I tought that there is no way for me to make the pc version compactible with mobile (correct me if im wrong)

**Comment by xlenstra** [comment]
We release pc version and android version at the same time and they should be compatible in every way as far as I'm aware

**Comment by Error3825** [comment]
> We release pc version and android version at the same time and they should be compatible in every way as far as I'm aware

Thank you, this helps a lot.
