### ISSUE TITLE
Feature request: New start screen logo

### ISSUE THREAD

**Issue by pyotr71** [yairm210/Unciv#7625]
I propose to change the game's startup logo.
The old one is funny, but looks like for a 5 year old child ...
![Load_Screen_old](https://user-images.githubusercontent.com/18636457/183242170-6370f177-2824-4dee-b248-6a8ae7aa54c5.png)

Maybe something like this (with a game icon):
![Load_Screen_new](https://user-images.githubusercontent.com/18636457/183242221-96106688-2c38-4e32-a7a1-f908ee4198db.png)

Or with additional text...
![Load_Screen_new_2](https://user-images.githubusercontent.com/18636457/183242248-fc5c75fe-49f1-47dc-9b30-356794ed4ed4.png)

**Comment by AdityaMH** [comment]
I like current one. new one look not good to me.

**Comment by heipizhu4** [comment]
Finally find something that needs a discussion page. How about a community vote?

**Comment by Ouaz** [comment]
I like the idea. It's more common to have the game logo as "loading" logo when launching a game.

As this logo may rotate when the game takes a bit of time to load, I would just remove the "Unciv" text below, and keep the Unciv logo alone.

**Comment by pyotr71** [comment]
![Only_icon](https://user-images.githubusercontent.com/18636457/183261204-a2e2d0ec-6eb7-480d-8ba1-d1dcc24522ab.png)

??

**Comment by alexban011** [comment]
> the simplest is the best

I agree with this one, but I do like the normal happiness logo

**Comment by Caballero-Arepa** [comment]
> I propose to change the game's startup logo.
> The old one is funny, but looks like for a 5 year old child ...

I agree, the starting logo should be changed.
Maybe the logo can fade in, and then fade out to reveal the menu. While it fades out, the game loads the background image (which imo it should be a pre-set image (or images), rather than a generated world)

**Comment by yairm210** [comment]
A generated world is the only way to go, due to
- image size
- tilesets

And also it's much cooler that you get something different each time
