### ISSUE TITLE
Clicking "Resume" causing icons to fail

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#7633]
Windows 10, 64-bit; game version 4.2.2
The bug also appeared on Android 12; game version 4.2.1 (build 744)

When you leave a game by selecting the main menu, but then click Resume to get back into the game you just left, the icons fail to load. It doesn't apply to the base game, but it affects all mods.

To reproduce: 
1. Open up a game with a mod in play
2. Open the menu and select Main Menu
3. From the Main Menu, click resume to go back to the game you just left
4. All icons from mods will now be replaced by squares

![Screenshot (142)](https://user-images.githubusercontent.com/58439827/183277129-ea579b6c-8cd2-42d8-add6-5b1b5604eb58.png)

**Comment by xlenstra** [comment]
This is likley fixed with #7613, so I'm closing this issue. If the problem persists after the next version has been released, please tell us and I'll reopen this issue
