### ISSUE TITLE
Feature request: Automated action to notify authors of merge conflicts

### ISSUE THREAD

**Issue by OptimizedForDensity** [yairm210/Unciv#7637]
It looks like there's an action to automatically comment/add/remove labels on PRs if a conflict exists. This could be a good way to notify authors that there's a conflict as soon as it happens since the green build successful checkmark is not removed once the repo updates creating a merge conflict.
https://github.com/marketplace/actions/label-conflicting-pull-requests

**Comment by JackRainy** [comment]
The fun fact: this functionality is already built-in GitHub but unfortunately, I did not find a way to activate it.
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/managing-your-scheduled-reminders#managing-scheduled-reminders-for-your-personal-account
![Your PR has merge conflicts](https://docs.github.com/assets/cb-56185/images/help/settings/scheduled-reminders-real-time-alerts-personal.png)


The problem with the conflicts and the Pull Requests - they are (a kind of) incompatible:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
```
Workflows will not run on pull_request activity if the pull request has a merge conflict.
The merge conflict must be resolved first.
```
Most probably, [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) is more applicable here, however, it brings some security risks.

**Comment by yairm210** [comment]
@JackRainy A Github *app* should not be limited by the restrictions in a Github *action*.
And if it requires special configuration per user, then chances are the translators won't go to the trouble of enabling it, even if they are aware of it.
A GitHub app signs like a good idea

**Comment by yairm210** [comment]
But the action Density linked to claims to get the job done...?
I assume they know what they're talking about, so it's worth a shot, and if we *can* do it with actions that's preferable

**Comment by yairm210** [comment]
Done :D
