### ISSUE TITLE
Infinite Recently Paid Tribute Bug

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#7645]
https://www.reddit.com/r/Unciv/comments/wjpcs2/recently_paid_tribute_bug_waiting_for_over_75/

**Platform**
Bluestacks X Android Emulation

**Version**
4.2.1

**Describe the bug**
Over 200 turns, can't demand tribute from Tyre City State

**To Reproduce**
1. Continue 150 turns, and always see the Recently Paid Tribute penalty

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>
[Bug_Demand_Tribute.txt](https://github.com/yairm210/Unciv/files/9306121/Bug_Demand_Tribute.txt)

```

```
</details>

**Expected behavior**
Expecting malus to drop after only 20 turns

**Screenshots**
![image](https://user-images.githubusercontent.com/44038014/184065770-e20a45ba-c3d4-4cbf-b82a-7d824d9edcd2.png)

**Comment by yairm210** [comment]
The game save cannot be loaded - it looks like this is only a small part of the base64 encoded game save

**Comment by xlenstra** [comment]
Note that if another player or AI demanded tribute, the -110 modifier is also applied
