### ISSUE TITLE
Translation for mods doesn't work

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#7647]
**Platform**
All

**Version**
4.2.3

**Describe the bug**
Sometimes a translation for mod doesn't show up in the mod.

**To Reproduce**
1. Download and run any mods that are already translated into your language (try Difficulty_Sandbox, that's the mod which is most widely translated).
2. Enter the game and you will find the translation line existed don't work.

**Expected behavior**
The lines should work. 

**Screenshots**

![image](https://user-images.githubusercontent.com/100454479/184147355-7e9e7185-b813-44f7-801a-ec39333f53a9.png)

**Additional context**
In fact, if you reboot unciv or try something like swiching between rulesets may temporarily solve this issue, but we should still make these translations work at the first time players play.

**Comment by amfauzn** [comment]
this is the same issue with audiovisual mod, apparently the only solution is to restart unciv

**Comment by heipizhu4** [comment]
> this is the same issue with audiovisual mod, apparently the only solution is to restart unciv

So is it possible to add a button or a popup window to tell them a restart is required?
