### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by wiki-me** [yairm210/Unciv#7648]
**Is your feature request related to a problem? Please describe.**

The game is hard to find, also it's kind of hard to assess if it's worth playing (especially the desktop version). 

**Describe the solution you'd like**
Add the game to [steam](https://store.steampowered.com/)

Why I think it will be beneficial:

* it is very popular and it's website has a lot of visitors (Alexa ranks it as the 314 most popular website on the internet).

* Seeing a lot of good reviews can really tip the scales and make me (and probably others) take a chance on trying a game (it's basically [social proof](https://en.wikipedia.org/wiki/Social_proof)), it could lead to more exposure which will mean more developers and more feedback (former developer of naev [said](https://www.reddit.com/r/opensourcegames/comments/tcwkr6/naikari_020_open_source_space_trading_and/i0kb8dd/) it brought new developers).

* Steam is the only software review system that i know of (besides gog.com) which is able to rank games only based on \"recent reviews\", so if a game starts badly and keeps getting developed and becomes good the old review don\'t prevent it from getting a good rating, this is especially good for open source games that can have a very long history of development (being developed for more then a 15 years is common).

* Another nice feature of steam is that you can find reviews for players that played more then a certain number of hours , some games can be half done and a review after three hours of play time might not reflect problems, a review after say 30h indicates you can pour some time into it without the game failing (and you will have to wait for a newer version and maybe play it until the point you reached before because save files are not always compatible with future versions).

* Some FOSS projects on steam have a price (for example the game [Mindustry](https://store.steampowered.com/app/1127400/Mindustry/) ). Maybe you could use that for funding and paying freelancers to create graphics and sound (iirc this is what shattered pixel dungeon does). 

* early feedback can be useful, there is a saying that if you are not embarrassed when releasing the software then you released it too late, steam can mark a game as early access (like *[*supertux*](https://store.steampowered.com/app/1572920/SuperTux/)* does) so there is no danger of disappointing players because the game isn't fully polished.

**Describe alternatives you've considered**
Maybe just add it to gog.com, it has some of the benefits (A "frequent reviews" feature, and it is somewhat popular but not like steam so it won't provide the same exposure).

**Comment by yairm210** [comment]
Already tried this. Applied for Steam, they didn't get back to me. Don't think there's much else I can do at this point :/

**Comment by alexban011** [comment]
Well since the greenlight thing dissappeared I'm guessing Valve needs to check every game by themselves which is gonna make this process take a lot of time. 

Lets just be patient and I hope this company will finally do it's job ffs

:D

**Comment by wiki-me** [comment]
> Already tried this. Applied for Steam, they didn't get back to me. Don't think there's much else I can do at this point :/

Was it before or after the green light thing? I don't think there should be a reason they wouldn't reply, it's basically free money for them (the 100 dollar fee), If a long time has passed i think we could try again, it probably just somehow fell through the cracks (some employee saw it and forgot).

We could request other community members will open issues asking them to contact you, Asking for advice on [r/steam](https://www.reddit.com/r/Steam/) or [r/steamsupport](https://www.reddit.com/r/steamsupport/) could also be helpful.

Also gog.com is an option which has some of the benefits of steam.

**Comment by yairm210** [comment]
I'm working on getting this approved

**Comment by wiki-me** [comment]
> I'm working on getting this approved

Can you reopen the issue?  some people might be interested in helping, and there is less of a chance of that happening if the issue is closed (they might assume it was rejected).

**Comment by alexban011** [comment]
> some people might be interested in helping

I don't see how people could help. We just need to be patient.

**Comment by wiki-me** [comment]
> I don't see how people could help. We just need to be patient.

Who knows? maybe someone will have a clever idea? or just volunteer to administer the steam page or help with the packaging, i also tend to think tools should be used as intended , github issues should be "open" for issues that are being worked on and that somehow could be better. why keep it closed?

But who am i to judge? do what you think is best for the project.
