### ISSUE TITLE
Feature request: Update Developers Building-Localy page 

### ISSUE THREAD

**Issue by nacro711072** [yairm210/Unciv#7666]
For the latest version on master branch (appCodeNumber = 748), **compileSdk** has been already updated to 32. But on the developer page [Binding_localy](https://yairm210.github.io/Unciv/Developers/Building-Locally/), it still for android 11 (31) which help developer to solve initial sync issue.

In my opinion, may tell developer, what the version of SDK tools should be downloaded corresponding with SDK version.

f.g: 
- open **build.gradle.kts** (:android:main) file
- find `compileSdk` and `buildToolsVersion` to see what the version should download.
- If `compileSdk = 11` and `buildToolsVersion = 30.0.3`, you should download **Android 11 SDK** and **30.0.2 SDK tools**, etc.

For the android 11: 
- Click "SDK Platforms"
- Click "Android 11.0 (R)"
- Click "SDK Tools"
- Select "Show Package Details" in the bottom right
- Choose version 30.0.3 under "Android SDK Build-Tools "
- Click "Apply"

**Comment by itanasi** [comment]
Are we finally converted? Thought there was still a few things getting worked out. I agree should update the documentations. You can actually make a PR yourself for the text chamges aince it's all in Github
