### ISSUE TITLE
'Disable religion' is missing?

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#7671]
**Platform**
Desktop Windows

**Version**
4.1.2

**Describe the bug**
The 'Disable religion' button is missing

**To Reproduce**
1. Go to Start new game screen
2. See error

**Expected behavior**
It should be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/100454479/184809106-a264cc94-5330-4dfe-b269-76946b07748e.png)

**Comment by yairm210** [comment]
This config option was removed as it is part of the ruleset definitions now
