### ISSUE TITLE
Error label exceeds popup border

### ISSUE THREAD

**Issue by CrispyXYZ** [yairm210/Unciv#7678]
**Platform**
Android 10, arm64-v8a

**Version**
github release v4.2.4

**Describe the bug**
The error label should be displayed below the OK and close button, but in fact after them.

**To Reproduce**
1. start a game
2. open city screen
3. click the name of the city to edit it
4. leave blank and click OK button

**Expected behavior**
The error label should be displayed below the OK and close button.

**Screenshots**
![Screenshot_20220819_171946_com unciv clone](https://user-images.githubusercontent.com/64761703/185591346-4fbb1644-3673-4d4b-84e4-806f773935e6.jpg)
![Screenshot_20220819_174601_com unciv app](https://user-images.githubusercontent.com/64761703/185595413-470c34c2-4c9f-4f83-8b37-a40814b95def.jpg)

**Comment by huckdogg** [comment]
This has been corrected in PR #7676
