### ISSUE TITLE
Help me see why this happens, thanks! （uncivserver）

### ISSUE THREAD

**Issue by xk730** [yairm210/Unciv#7710]
**![image](https://user-images.githubusercontent.com/40309144/186688397-02001553-d85a-485d-91ed-ff06ef451db6.png)

**Comment by heipizhu4** [comment]
That should be in the bug label, I guess.

**Comment by nacro711072** [comment]
@xk730 

1. you should provide more information (Unciv release version, java version, window OS version, etc.)
2. For me, it works fine with the latest version v4.2.6 on Windows 11. (openJDK 11.0.12)

Check your java version and download the latest release file `UncuvServer.jar` again, and it may solve your problem.

ps: use command `java --version` to check java version, the minimum version of java should be 8.

**Comment by xk730** [comment]
> @xk730
> 
> 1. you should provide more information (Unciv release version, java version, window OS version, etc.)
> 2. For me, it works fine with the latest version v4.2.6 on Windows 11. (openJDK 11.0.12)
> 
> Check your java version and download the latest release file `UncuvServer.jar` again, and it may solve your problem.
> 
> ps: use command `java --version` to check java version, the minimum version of java should be 8.

thanks！I LL try you suggestion
