### ISSUE TITLE
Feature request: an option to deactivate the loading dialog box (annoying flash at the end of each round)

### ISSUE THREAD

**Issue by LeoBoudet** [yairm210/Unciv#7712]
**Is your feature request related to a problem? Please describe.**
Since the last update, there is a "loading" dialog box that appears at the end of each round. Since I play on small maps, the loading time is very short and the appearing of the dialog box generates an ultra-fast flashing that bothers me a lot (I am a bit light-sensitive, maybe that's why).

**Describe the solution you'd like**
An option to deactivate the loading dialog box.

**Describe alternatives you've considered**
I tried both modes of game (Vanilla and Gods & Kings) and both have the same behavior regarding the dialog box.

---

Thank you for the amazing development. I hope you will take my request into account as I stopped playing the game since the last update.

**Comment by yairm210** [comment]
That loading box is necessary to tell the player that the current 'screen' is not clickable, which allows us to require less memory.
The only solution I can think of is to have it fade in over, say, a second so it's less annoying and not noticeable on very fast transitions

**Comment by LeoBoudet** [comment]
I noticed that the entire screen is flashing. Probably if only the dialog box was concerned by the visual effects it would be smoother for the eyes. A fade in could be good too.
