### ISSUE TITLE
AI and embarked construction woes

### ISSUE THREAD

**Issue by carriontrooper** [yairm210/Unciv#7713]
**Platform**
Android, but I suspect other platforms too

**Version**
4.2.5 patch 1 from github

**Describe the bug**
When there is a land unit that can make improvements on water (vanilla Samurai, Alpha Frontier constructors), the AI will not use them to make improvements on water. Maybe because they're in embark mode? Idk why.

**To Reproduce**
1. Play Alpha Frontier
2. Start game as spectator, have one of the nations be Free Waverunners (since they're sea-oriented)
3. Proceed to watch them develop
4. They never make water improvements

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
AI can and will make improvements using embarked units that can build them.

**Screenshots**

**Additional context**
Was reported in the Alpha Frontier issues.

**Comment by SpacedOutChicken** [comment]
There are at least two issues here.
First: embarked units can't build improvements. You can give a land unit the "Can build [Water] improvements on tiles" unique, but it won't work. It works for water units, but not embarked land units.
Second: the AI can't handle the Constructor unit's dual functions. The Constructor unit can build land improvements, but it can also construct water improvements via the "May create improvements on water resources" unique, and this one actually works. Trouble is, the AI never uses it. You can wait for a thousand turns and the AI will never send a Constructor out into the water to improve the resources there.

**Comment by SpacedOutChicken** [comment]
I should mention that I've tinkered with this in the past, and this is what I found out: https://www.reddit.com/r/Unciv/comments/orm78y/experimenting_with_water_improvements_a_report/

**Comment by SeventhM** [comment]
Closing as Solved as per #9690. Please comment requesting it be reopened if there is still issues in this regards
