### ISSUE TITLE
Feature request: have land count as an obstacle for "Can only attack [Water] tiles"

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#7726]
A curious feature of the "Can only attack [Water] tiles" is that it doesn't check if the water tiles in question are continuous, or even if they connect at all. A submarine on one side of a land divide can fire on a boat on the other side of the divide even if there is no realistic way for a torpedo to get from here to there. This is because the game isn't checking the path; it's just checking to see if the end destination is a water tile.

For more realism, it would be good to have a chunk of land count as an obstacle, similar to the way that hills and forest count as obstacles to ranged units in normal circumstances.

**Comment by yairm210** [comment]
No - ranged attacks are ranged. If you want, you can imagine that they fire missiles info the air.

**Comment by SpacedOutChicken** [comment]
Understood, and sorry if my request came off as rude.

**Comment by yairm210** [comment]
It did not, I just wanted to make my position clear :)

**Comment by Ouaz** [comment]
Devs are like that. They answer as they code: short and simple. :yum:
But it never meant to be a rude answer (well, most of the time :grin: )
