### ISSUE TITLE
I probably messed a mod up

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#7730]
**Platform**
Android 10

**Version**
4.2.3

**Describe the bug**
When I clicked autoupdate mod uniques in a mod with the cross image, the mod check started throwing an exception and the mod disappeared from the check and the download menu, so I can't delete it.
(Also sorry for the bug label, I didn't find a better one and I don't have Discord)

**To Reproduce**
In the mod check menu in settings, I clicked autoupdate mod uniques for Civ5Mod (I'm not a native English speaker, so I didn't exactly know what it does). 

**Expected behavior**
It doesn't do anything

**Screenshots**
![Screenshot_20220831-182446_UnCiv](https://user-images.githubusercontent.com/79529669/187732754-b1c85453-caf0-4070-bac3-776ca7ccb48d.jpg)

**Additional context**
I know, I shouldn't press random buttons :/

**Comment by Eclipse-H-Afton** [comment]
show me what u did

**Comment by xlenstra** [comment]
This button shouldn't just throw random errors. There is probably an incorrect update for one of the uniques. Do you have any idea what mod you updated and/or can you send a zip of this mod?

**Comment by jahodovykolac** [comment]
> show me what u did

I pressed the 'Autoupdate mod uniques' button, when you click on the screen from screenshot on a mod with warnings will have this button



> This button shouldn't just throw random errors. There is probably an incorrect update for one of the uniques. Do you have any idea what mod you updated and/or can you send a zip of this mod?

The mod is Civ5ExpansionMod (pretty deprecated one). I'm on mobile so I don't know where to find downloaded mods.

Also it now shows this error every time it runs a check

**Comment by xlenstra** [comment]
You probably updated uniques of the Civ5ExpansionMod, but one of those updates breaks the mod. As the mod is _severely_ outdated, we don't support it and have even removed it from our internal mod download page, and updating its uniques probably does result in crashes. In this case, the mod still uses an older version of uniques for promotions, called 'effects', which doesn't support multiple effects. Updating it changes one of these uniques to two uniques, which normally is fine, but causes a crash here. Do note that this update is only applied locally, that is, on your phone, so no one else should have a problem with the mod if they still have it.

As this file is downloaded via unciv, it is saved internally on your phone, and thus unless you have rooted your phone, you can't access the files of this mod. The warning itself should be harmless, but it is likely impossible to continue playing games with this mod enabled. As far as I'm aware, there are only two ways to remove this warning. 

The first is to manually redownload Civ5ExpansionMod by copying the link to its github (https://github.com/k4zoo/Civ5ExpansionMod) and using the 'download mod from URL' option. If I'm not mistaken, this should overwrite your local files with the original files from before you updated uniques.

The second is to uninstall unciv and then reinstall it. This should remove all internal files including the mod. If you go this route, please back-up your user ID and save files (save files can be found in `Internal Storage/Android/data/com.unciv.app/files/SaveFiles`).

**Comment by jahodovykolac** [comment]
The first method worked, thanks!
