### ISSUE TITLE
Renaming Units as Spectator

### ISSUE THREAD

**Issue by RealBamboolord** [yairm210/Unciv#7732]
**Platform**
Android

**Version**
Google Play, version 4.2.5 (Build 749)

**Describe the bug**
You can rename units as a spectator (if you are an active player). 

**To Reproduce**
1. Start a new game and set your human civ to spectator
2. Click on any unit, then on its name
3. A rename screen should pop up, so you type in any name and press "OK"

</details>

**Expected behavior**
Renaming other civs units should not be possible as spectator (maybe make this a feature and disable it for other human's civs)

**Screenshots**

**Additional context**
Bug is created due to new (re)naming mechanics

**Comment by RealBamboolord** [comment]
![Uploading Screenshot_20220831-210858_UnCiv.jpg…]()

**Comment by RealBamboolord** [comment]
![Uploading Screenshot_20220831-210918_UnCiv.jpg…]()

**Comment by RealBamboolord** [comment]
![Uploading Screenshot_20220831-210923_UnCiv.jpg…]()

**Comment by RealBamboolord** [comment]
![Uploading Screenshot_20220831-211022_UnCiv.jpg…]()

**Comment by xlenstra** [comment]
Note that if you send a message containing a picture before it finished uploading, it will still say 'Uploading [screenshot_name]'. This is what happened here, so I can't see your screenshots. Regardless, I probably know what happened and I'll fix this

**Comment by RealBamboolord** [comment]
Sorry for the screenshot issue. Didnt know that was the case
