### ISSUE TITLE
Feature request: Auto-select korean post-position letters

### ISSUE THREAD

**Issue by Highseekerz** [yairm210/Unciv#7733]
**Is your feature request related to a problem? Please describe.**
Korean languages have a post-postion letters to make a sentence.
'나' means i, '사과' means apple, '먹었다' means eat
You should translate "I eat apple" to "나는 사과를 먹었다" not "나 사과 먹었다"
These '는' '를' are post-postion letters to be added and it has rules that should be changed by post letters
If you translate "Teacher eat apple", it should be "선생님은 사과를 먹었다(선생님 means teacher)" not "선생님는 사과를 먹었다"
So we're translating like this
"[A] eat [B]" would be [A]은(는) [B]을(를) 먹었다.

**Describe the solution you'd like**
I have no skills with programming but i've found a utility that auto select post-position letters for korean languages
https://github.com/inkyfox/KoreanPostPositionUtil
I hope this will help

**Describe alternatives you've considered**

**Additional context**

**Comment by xlenstra** [comment]
For context, multiple languages have these kind of problems. For example, Germany uses grammatical cases for many words, meaning that `der Man`(the man) and `den Man` (the man) mean different things, and cannot be used interchangeably. `der Man` means that the man is subject of the sentence, while `den Man` means it is the object. 

Languages are complicated, and many other languages have these semi-random changes in different places, making it very difficult to create correct translations to those languages. While it is very hard but probably not impossible to solve these problems, it often means writing language-specific code for languages none of us developers speak, or taking code we cannot check from some other source, as you suggest. In this case, the code itself is written in Korean, so I cannot read or understand what is happening, and as such I wouldn't feel conformable integrating it into our codebase.

**Comment by yairm210** [comment]
Actually, closing due to lack of interest.
If any Korean devs want to work on this they're welcome, but out if scope for me.
