### ISSUE TITLE
Feature request: Avoid accidental nuke

### ISSUE THREAD

**Issue by vincemolnar** [yairm210/Unciv#7740]
**Problem:**

Most of the times an AI player declares war on me, it's because they nuke another player or city state and my tile is in the blasting radius. This immediately starts a war, even if we are otherwise allied. 

**Solution:**

The AI should consider the blasting radius and the resulting DoW when choosing locations to nuke. Maybe sometimes it's still worth it, but there should be a huge negative bias if the accidental target is a friend.

**Comment by JackRainy** [comment]
Also, AI does not care of own units using the nukes. I would expect it "evacuating" own units from the blasting radius before the nuke is in action.

**Comment by RealBamboolord** [comment]
They literally sometimes obliterate their army and people to kill one weakened enemy unit

**Comment by Eclipse-H-Afton** [comment]
tell GitHub to stop emailing me
