### ISSUE TITLE
mod Hexagon.png bug?

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7741]
i had createt mod: https://github.com/MindaugasRumsa51/potato-terrains

downloaded it in-game
but even i selected "permanent audiovisual"
and selected mod in "new game screen"

Hexagon.png and CrosshatchHexagon.png had not changed - old ones used

----
unciv version 4.2.2 build 745

**Comment by yairm210** [comment]
This looks like a mod problem -  the image and jsons folders should be at the root level, not nested 1 level deep
