### ISSUE TITLE
Continents map type needs more land tiles / reveal map?

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#775]
In comparison with the other map types, Continents has far fewer land tiles and is often mostly deep ocean tiles. In my experience this severely restricts how many total civs you can play with on Continents since the AI tend to expand quickly.

This brings me to my second issue, I wanted to count tiles or at the very least overlay screenshots of Continents with the others maps to demonstrate this issue, but without an in-game "reveal all" function (or the ability to zoom out in the map editor), this would have required fully exploring the map over multiple games on the different maps types.. So for this issue and from a QOL standpoint either of those features would be quite nice.

**Comment by yairm210** [comment]
As for the first issue, @ninjatao is probably more qualified to answer than I am
As for the second... I see your point, I'll see if zooming out completely is a viable option

**Comment by ninjatao** [comment]
Yes, continents does have fewer land tiles than other map types. This is because it needs more water tiles to make both continents not too ugly. ^_^
In fact, continents maps spilt the map into two parts, and generate one continent in each part. So there will be almost twice as many water tiles as pangaea. Let's discuss further if you have better ideas on this, I am not quite experienced on map-generators.

**Comment by ozyxcv** [comment]
Oh gosh I'm not experienced with map-generators either, but I suppose my idea was just to make the continents a bit wider if possible? I'm including an example of a continents map from civ v, I don't think the land masses need to be as close as these are but something nearer to this rather than the huge ocean divide we get now would be nice. 

![egsRzYK](https://user-images.githubusercontent.com/49125947/58029451-38768600-7ae2-11e9-894c-aa30fd9ee5eb.jpg)

**Comment by ozyxcv** [comment]
You know maybe this isn't as big of an issue as I imagined! I just created a few new continents maps and the ocean isn't nearly as wide as I thought it was before :') thanks for responding though

**Comment by ozyxcv** [comment]
whoops didn't mean to do that ... I'll leave now '-'

**Comment by yairm210** [comment]
I think we'll close this issue then 😄

**Comment by ninjatao** [comment]
Cool. In original civ games the maps are actually rectangle-shaped instead of hexagon-shaped. This makes it easier to put two continents side by side. Maybe we can try this later.
