### ISSUE TITLE
Future tech repeat research over and over 

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7754]
Like the title, i want to say that the future tech (the last tech in tech tree) keep researching all over again after it done of research. Please make it stop

**Comment by Skekdog** [comment]
not a bug

**Comment by Thienanbad** [comment]
But nobody change that

Vào 23:38, Th 4, 7 thg 9, 2022 Skekdog ***@***.***> đã viết:

**Comment by xlenstra** [comment]
Not a bug. Researching this tech does increase your score and so it has a function.

**Comment by Thienanbad** [comment]
But it repeat research the tech after it finished. Can you do something to
make it research one time like other tech before it

Vào 23:50, Th 4, 7 thg 9, 2022 Xander Lenstra ***@***.***> đã
viết:

**Comment by yairm210** [comment]
What you're asking for is a change of the functionality of the game away from Civ V implementation, and so the answer is "if it's important enough to you you can create a mod to do that". We're sticking with Civ V implementation.

**Comment by Thienanbad** [comment]
Can you make a switch to turn on/off tech notification in options tab? So
users can choose to turn on/off the tech notification. The tech
notification popup will be decided by the the users

Vào 3:21, Th 5, 8 thg 9, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by yairm210** [comment]
Will not. I don't add features for single users, and you're the only one who seems to have this issue.
