### ISSUE TITLE
Feature request: Make a unique loading picture

### ISSUE THREAD

**Issue by xk730** [yairm210/Unciv#7761]
``我看到 yairm 最终决定更改进入游戏时的动画。因此我有个小建议：我们是否需要一个可以转动的开机专属贴图？（他的风格就像这样，当然大概图案是以一个像素版地球为背景，上面贴上unciv的logo，地球四周分布着unciv的单位——当转起来时，单位就像在跑来跑去）
I saw that yairm finally decided to change the animation when entering the game. So I have a little suggestion: do we need a bootable exclusive map? (his style is like this. 
![banner](https://user-images.githubusercontent.com/40309144/189038274-f918aaa4-086c-4f81-83ef-652b5d4ce464.png)

Of course, the pattern is probably based on a pixel version of the earth, with the logo of unciv pasted on it. Unciv units are distributed around the earth - when it rotates, the units seem to run around.)
![ungl](https://user-images.githubusercontent.com/40309144/189038190-1fcf881c-a9b9-46ca-a67c-8c77096a07b1.png)

**Comment by xk730** [comment]
If necessary, we will start to try this, but it may take some time

**Comment by yairm210** [comment]
Nope, current is fine
