### ISSUE TITLE
Feature request: auto open border

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7777]
When a civ is destroyed and we liberate ít, it will auto open border so our army won't be kicked out and we don't have to spend few turns to make trade offer after liberated

**Comment by Caballero-Arepa** [comment]
I agree

**Comment by yairm210** [comment]
This is a redo of #2947 - since that one is old I'll close it

**Comment by Thienanbad** [comment]
> This is a redo of #2947 - since that one is old I'll close it

Can you accept this featured, it is necessary when liberate a nation it help our units not to be transported to enemy land

**Comment by yairm210** [comment]
I don't understand what you want
I didn't close this issue, so it's accepted
If you're asking if I'm planning on working on it, no, I have other priorities

**Comment by Thienanbad** [comment]
Then when you planning to do it?

Vào 23:25, Th 5, 6 thg 10, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by Thienanbad** [comment]
Oke man, I will wait. I hope you will do it soon. It's very important
mechanic for the game.

Vào 2:21, Th 6, 7 thg 10, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by SeventhM** [comment]
Closed as Solved as per #10150
