### ISSUE TITLE
Too many workers

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#778]
Playing in deity. In the mid to later stages of the game, the ai builds ridiculous amount of workers who just sit idly on my borders.
Same thing happens for me, when after I build something, the city always starts to build a new worker, even if all my tiles are already upgraded and I have a railroad network everywhere.

**Comment by yairm210** [comment]
Hm
The AI checks workers needed as a relation between the number of cities and the number of workers
But after 5 cities you don't really need extra workers, so I think I'll cap the number of cities that are counted towards 'worker necessity' at 5, that should solve it
