### ISSUE TITLE
Science/Happiness Points from City-States not showing after Loading

### ISSUE THREAD

**Issue by CodeKatta** [yairm210/Unciv#7781]
**Platform**
Android 12 (One UI 4.1)

**Version**
4.2.7 f-droid

**Describe the bug**
If you adopt the policies 'Scholasticism' resp. 'Cultural Diplomacy' (Patronage) the points for 'Science' resp. 'Happiness' you receive from city-states do not show in the green research box (top left) and research tree resp. next to the happy face at the top of the screen **but only after you load a saved game**.
In the 'Stats'-screen the value for 'Happiness' is correct. If you enter a 'City'-screen and exit again or hit 'Next Turn' the correct value is displayed as it should. Wrt 'Science' you will probably notice that you need one fewer turn (or even less for higher techs in the research tree).

As far as I can tell , however, the game engine seems to use the correct values. It's probably just a display issue.

**Comment by xlenstra** [comment]
This is probably a result of the order in which stats for civs are determined. As we probably determine `statsForNextTurn` for major civs first, the stats for city-states still have their default value of 0, which is added by the Scholasticism policy. Then afterwards the city-state stats for next turn are determined. Before the turn ends, we recalculate all those stats to make sure our values are correct, so you should indeed just get the correct amount of stats.

Should be a relatively easy fix (just change the order in which stats are determined when loading a game), but I don't have the time to test that the above is correct and implement it.

**Comment by nacro711072** [comment]
I will take a look.

**Comment by yairm210** [comment]
Solved by #7793
