### ISSUE TITLE
Can't play my turn

### ISSUE THREAD

**Issue by RalerCrab** [yairm210/Unciv#7788]
**Platform**
Android version 10 and also Windows 10 Home x64 bits.

**Version**
PlayStore Version: 4.2.5 (buld 749).
Browser (https://yairm210.itch.io/unciv) Version: 4.2.5 (buld 749).

**Describe the bug**
I can't receive my turn in a multiplayer game of 2 players.

**To Reproduce**
1. Go to 'create multiplayer game and play a game with another person'
2. Click on 'Press Next turn until the game don't allow you to continue playing'
3. Scroll down to 'Multiplayer games menu and load the game that has a exclamation mark on it, when press on the game it shows "Current turn: (Your civilization) since x time". Then press "Join game"'
4. In game it's impossible to play your turn and the notification indicates "Waiting for (the other civlization)"

<details><summary>Saved game</summary>

```
My personal ID (Celts):
690d25a3-e190-43ea-b4e4-da4a1f0fcd10

Game ID:
2199adea-e7e7-4dbf-9d25-1bbcbf2beeaa

Friend's ID (Inca):
d7c86001-8f8a-4342-9a80-95f8e1d3c9f1
```

**Screenshots**
![2022-09-12 153633](https://user-images.githubusercontent.com/113314106/189668606-db73d986-872d-46e7-b205-1171d8f58f8a.png)
![2022-09-12 153548](https://user-images.githubusercontent.com/113314106/189668650-2355156e-982c-4a86-8c18-bf44561b4266.png)

**Additional context**
The other player had played his turn days ago, and sometimes in his tablet (Android) the game required to play same turn more than one time.

This happened to us (same players) in an earlier version (last version before textures improvement) of the game (i pressumed that it was an isolated problem due to playing diferent versions on the computer and in the movile phones) and we create a new game but this time i will ask for help here.

Thank you in any case, 

My best wishes.

**Comment by GGGuenni** [comment]
I've reset your game to Turn 165 | current player: Inca
Please remove the game from your multiplayer games list and add it again

Also please let me know if this fixes your problem

**Comment by RalerCrab** [comment]
The situation is near the same, now the issue turned into "File could not be found on the multiplayer server" from Celts perspective after Incas played the turn two times.

I'm trying to adapt a dedicated server (https://yairm210.github.io/Unciv/Other/Multiplayer/#hosting-a-multiplayer-server) from my computer and try to continue same game from there, it will be my last attempt. It will will take my time to learn how.

Thanks for the help, i hope that eventually the bug will repeat itself and also found.

Sorry to bother you.

**Comment by Hoernla** [comment]
Got it in both my games, can I be of any help? Version 4.2.8 by now (started in 4.2.6)

**Comment by RalerCrab** [comment]
@GGGuenni 

It's difficult to reproduce, and not clear the situation which triggers the bug.

However, the game could go on again this last time. We both chaged to the community server mentioned. It's working very well as i used to be before the "300 seconds" restriction.

> So two times the same turn and it did not update? <

In fact the game let Incas play the turn one more time. This turn let us to change the hosting for the game.

@Hoernla 

I suggest you to do the same as i did.

The increasing number of players in the standar multiplayer server is probably related to this kind of problems somehow.

For now i will close this issue beacuse it's working for me.

Thank you for the help.

**Comment by Hoernla** [comment]
Game 1: d5890572-b7bb-4ad0-858e-8bc276481c90
I play Englad, move my scout and then click "next turn" (doesn't matter if I move the scout beforehands). I am told that it is now Denmark's turn (as it should be), but as soon as the game "refreshes", I am back at the start of my turn.

Game 2: 1fa452b5-d8a1-4d94-a4bd-82c3af4cdb0c
In this case, the Mongol's can't finish their turn to allow me, France, to continue.

I will try to follow your ideas.

**Comment by xlenstra** [comment]
Sounds like the dropbox is full again, when I'm home I'll start removing
old saves again.
But we're getting to the point where I can't remove old saves faster than
they're created

**Comment by Hoernla** [comment]
Would it be in the mid-term possible to add a second drop box for this purpose and divide the games upon them?

**Comment by Hoernla** [comment]
it works again, both games - thank you
