### ISSUE TITLE
AI has an obsession

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7792]
We have found that the AI has absurd obsesion with certain unit.

The case happened when doing an AI only match with all latam civs, and for some reason, some reason, Venezuela just straight up only and exclusively built "Mixed Militias".

Just that, it didnt build any other unit, and even well deep into the industrial era, it still did not made any other unit.

The obsesion was so big, that Ven. had a large amount of this explorers, and subsequely, got conquered as easy as butter.

![Screenshot_20220912-214726_Gallery.png](https://user-images.githubusercontent.com/78449553/189796637-52fdd789-1d32-4cac-b494-7dffc6990763.png)

This seems to not be the only case, from what I heard, Atlas from Deciv also has an obsesion with the particular unit and shows the same behaviour.

Unfortunately, I dont have anymore that save file, but this happens nearly every single game.
If needed, I may work to get another save file.

Ps: This extraordinary conduct also causes more lag, with such much units on the ground, the bot couldn't leave them quiet, so it made a bunch of lag.

**Comment by RealBamboolord** [comment]
It probably has something to do with the units being able to build tile improvements
