### ISSUE TITLE
QoL request: prevent the scrolling position of the notification list to be reset, when clicking a notification

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#7814]
**Is your feature request related to a problem? Please describe.**

When the notification list is scrolled down, if clicking a notification, the scrolling position is reset to the top.
Unconvenient when the notification is pretty long (during war for example), and one has to scroll down again each time, to display again "out-of-view" notifications,  click one of them, but the scrolling position is reset to the top again.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/11946570/190707080-2fa04c57-24fd-477f-ad4d-d1cbeaaf0399.png">
</details>

**Describe the solution you'd like**
The scrolling position of the notification list is memorized, even when/after clicking a notification.

**Additional context**
This QoL fix has been implemented for the notification log in the Overview menu (https://github.com/yairm210/Unciv/commit/89979748a12cf5238a1a79e957894cebbf453392), but not for the notification list on the main screen.

Thanks for reading.

**Comment by vincemolnar** [comment]
This would be really great!

**Comment by Ouaz** [comment]
This has not been closed... but tis QoL has been added a few weeks ago, the list scrolling position is now kept when clicking a notification.

**Comment by yairm210** [comment]
Closing this issue
