### ISSUE TITLE
Gay

### ISSUE THREAD

**Issue by nancho84** [yairm210/Unciv#7816]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Tyretes** [comment]
h.

**Comment by yairm210** [comment]
That's certainly one way of coming out that I didn't expect

**Comment by not-navyblue** [comment]
lmao
