### ISSUE TITLE
Feature request: Minimaps Should Only Encompass Explored Areas

### ISSUE THREAD

**Issue by groggone** [yairm210/Unciv#7817]
Have the minimap not encompass the whole map and only showing what the player has explored just like most Civ games (Civ V included)
The Image embedded is a demonstration of the feature request, notice how the minimap on the bottom right only shows parts of the map explored by the player? This is what i'm talking about
![Demonstration](https://user-images.githubusercontent.com/97829937/190904418-4be11695-cd75-4516-a88b-3e21dc51313c.png)

**Comment by alexban011** [comment]
![image](https://user-images.githubusercontent.com/21990802/201342383-f28dae0e-edf3-4066-b4aa-c54510baf10c.png)

but it does?
