### ISSUE TITLE
Barbarians no longer attack

### ISSUE THREAD

**Issue by CodeKatta** [yairm210/Unciv#7832]
Platform
Android 12 (One UI 4.1)

Version
4.2.9 f-droid

Describe the bug
Since version 4.2.9 barbarians just ignore any non-barbarian units. I even tried placing a worker/settler/missionary next to them but they just sat in their camps or roamed around without capturing them which they did without fail in previous versions. I also loaded a much older game where I knew that a unit got attacked by a barbarian archer (because I placed it there for that very purpose) but there it was just the same.
However, they still pillage, though.

(On a side note: especially for testing purposes a (Next Turn)-button would come in quite handy, so you don't have to go through all your units to get the 'next turn'-option. Maybe a small red button just to the right of the (Next Unit/Next Turn)-button which you can toggle on/off like the zoom-buttons.)

**Comment by yairm210** [comment]
Options - gameplay - check for issue units is what you're looking for

**Comment by yairm210** [comment]
I'm not encountering this at all - can you attach a save file?

**Comment by yairm210** [comment]
Solved :D
