### ISSUE TITLE
"Will not be displayed in Civilopedia" is not working

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7846]
![imagen](https://user-images.githubusercontent.com/78449553/191629682-24e9a6ad-469a-4527-94cd-2644992aecb6.png)
![imagen](https://user-images.githubusercontent.com/78449553/191629750-b02147f8-64c8-487e-b5d4-9fa6be637575.png)

It kinda works, but it doesn't.
When trying to search the item it indeed isn't displayed. But the problem is that it can be seen both from the select nation [when starting a new game] and from the nation info.
I don't think this is intended, if it is actually intended bahaviour, then I'll convert this to a suggestion to add "Will not be displayed on nation info", or smth like thatso it doesn't appear when selecting a nation.

**Comment by yairm210** [comment]
This is probably a improvement only issue, yes?
