### ISSUE TITLE
Review about TODO comment of "offerDeclarationOfFriendship" in NextTurnAutomation.kt

### ISSUE THREAD

**Issue by supertom-spec** [yairm210/Unciv#7847]
```kotlin
@Suppress("unused")  //todo: Work in Progress?
private fun offerDeclarationOfFriendship(civInfo: CivilizationInfo) {
```
Above code indicates that this function is not used -- at least not used by the AI. I am not sure whether AI will offer friendship actively  in current version, but the call of the function was commented in `automateCivMoves()` at line 63.

Review the git log, comment `42e16ec` (2020/1/24) first introduction `offerDeclarationOfFriendship()`, I am not sure when this was commented, but in comment `7481683` (2020/2/4) the call of the function has already been commented.

**Comment by yairm210** [comment]
Unused code is not a bug. "AIs should offer DOF" is a feature request for the G&K list at #4697
