### ISSUE TITLE
Poland win in 1180 b.c  - cultural type

### ISSUE THREAD

**Issue by Eddiri** [yairm210/Unciv#7851]
**Platform**
4.2.8

**Version**
Where you got the game and the exact version number.

**Describe the bug**
I think that's impossible to win type.

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
You provide no information on what the problem is, no way to reproduce, no saved game
This is not a bug report, this is an empty comment

**Comment by Eddiri** [comment]
I'm sorry,but i couldn't attach the screenshots.
Edoardo

________________________________
Da: Yair Morgenstern ***@***.***>
Inviato: venerdì 23 settembre 2022, 13:18
A: yairm210/Unciv ***@***.***>
Cc: Eddiri ***@***.***>; Author ***@***.***>
Oggetto: Re: [yairm210/Unciv] Poland win in 1180 b.c  - cultural type (Issue #7851)


Closed #7851<https://github.com/yairm210/Unciv/issues/7851> as completed.

**Comment by MindaugasRumsa51** [comment]
one can create mod where poland will win cultural 4000 BC

poland is not in official unciv yet
