### ISSUE TITLE
building caravans and cargo ships with `"Double quantity of [Trade Route] produced"` bonus consumes 2 trade routes instead of 1

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#7852]
**Platform**
Windows 10 Home 64bit

**Version**
4.2.9

**Mods**
RekMOD

**Describe the bug**
> pick venice, get animal husbandry and build trade route 1 - then you should have 2 trade routes count avaible - train one caravan, deploy it in any way you want - now you have 0

> and it's not when building - when you build they consume one and when you DEPLOY the trade route (food,production,gold) it consumes one as intended and the consumption of caravan/cargo ship hangs in air

> also try it yourself - get animal husbandry, produce 2 caravans and THEN deploy them into food/production/gold
you should have -2 trade routes

Quote by `Charumu#9534`

**To Reproduce**
> pick venice, get animal husbandry and build trade route 1 - then you should have 2 trade routes count avaible - train one caravan, deploy it in any way you want - now you have 0

> and it's not when building - when you build they consume one and when you DEPLOY the trade route (food,production,gold) it consumes one as intended and the consumption of caravan/cargo ship hangs in air

> also try it yourself - get animal husbandry, produce 2 caravans and THEN deploy them into food/production/gold
you should have -2 trade routes

Quote by `Charumu#9534`

**Comment by MindaugasRumsa51** [comment]
venice is in unciv potato or in some mods

official unciv have no venice yet

**Comment by touhidurrr** [comment]
> venice is in unciv potato or in some mods
>
> official unciv have no venice yet

fixed before you commented. This issue is with an unique, not the official rulesets. can be reproduced with RekMOD.

**Comment by yairm210** [comment]
The problem is with the ruleset. Double production only applies to "Provides [amount] [resource]" and not to "Consumes [amount] [resource]" but the ruleset for some reason has all trade routes with "Provides [-1] [Trade Route]" instead of "Consumes"
