### ISSUE TITLE
Feature request: Victory status button 

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7854]
While we are playing sometime we need to check other civ status and we use victory status tab to do it so i recommend the Victory status tab should be move to next to overview tab or some where to access easier

**Comment by xlenstra** [comment]
Duplicate of #3417

**Comment by Thienanbad** [comment]
#3417 is from 2020 and now the Victory status tab still not access easier

Vào 17:21, Th 7, 24 thg 9, 2022 Xander Lenstra ***@***.***>
đã viết:

**Comment by yairm210** [comment]
It doesn't matter from how long ago it is, it doesn't magically not become a duplicate because it's been a while.
