### ISSUE TITLE
Crash next turn

### ISSUE THREAD

**Issue by Dark0-04** [yairm210/Unciv#7863]
**Platform**
android 10

**Version**
4.2.10

**Describe the bug**
When loading in the next round, the game crashes. I use the mod Deciv Redux and the game crashes when going from turn 344 to turn 345

**Expected behavior**
The game should not crash

Ps: I don't know why, but when I try to copy the save data, it doesn't work

**Comment by Dark0-04** [comment]
I don't know how to upload a save file but when I try to copy it, I have this:
![Capture d'écrans_20220926-193854](https://user-images.githubusercontent.com/104214100/192344119-7742a10c-da68-42e1-8160-442682ee7361.png)
![Capture d'écrans_20220926-193838](https://user-images.githubusercontent.com/104214100/192344148-31b9ed70-00b1-487e-b413-518a43cb680d.png)

**Comment by Dark0-04** [comment]
Hello

I don't know how to upload a save file but when I try to copy it, I have
this:
[image: Capture d'écrans_20220926-193854]
<https://user-images.githubusercontent.com/104214100/192344119-7742a10c-da68-42e1-8160-442682ee7361.png>
[image: Capture d'écrans_20220926-193838]
<https://user-images.githubusercontent.com/104214100/192344148-31b9ed70-00b1-487e-b413-518a43cb680d.png>

Le lun. 26 sept. 2022 à 17:56, Xander Lenstra ***@***.***> a
écrit :

**Comment by yairm210** [comment]
This is unactionable... We don't know what happened, you can't provide a save, we can't actually solve this if we can't tell what's happening

**Comment by Dark0-04** [comment]
When I try to load the game, it says this: 
![Capture d'écrans_20221031-021544](https://user-images.githubusercontent.com/104214100/198912811-2aa67cb3-a349-4f2c-8b37-c717c3e160de.png)
I doubt it can get you any further but I prefer to say it

**Comment by Dark0-04** [comment]
When I try to load the game, it says this:
[image: Capture d'écrans_20221031-021544]
<https://user-images.githubusercontent.com/104214100/198912811-2aa67cb3-a349-4f2c-8b37-c717c3e160de.png>
I doubt it can get you any further but I prefer to say it

Le jeu. 6 oct. 2022 à 21:35, Yair Morgenstern ***@***.***> a
écrit :

**Comment by yairm210** [comment]
Your mod removed one of the terrains that was used to create the map, so you can't load that map anymore
Not much I can do about that
