### ISSUE TITLE
Selecting a city to bombard enemies

### ISSUE THREAD

**Issue by bonezinger** [yairm210/UnCiv#787]
**The problem:**
Selecting a city to bombard an enemy unit within range can be difficult, especially if the city has a unit in its hex.

**Reproducing the problem:**
Leave a unit sleeping in a city.
Wait for an enemy to get near.
Try to select the city without going into its detailed window.

**Suggestion/Solution:**
If the current unit is either a great person or worker, OR if no unit or city is selected (as seen in the lower left box), clicking on the enemy unit should immediately select the city nearest to the enemy and show the combat box.

**Comment by yairm210** [comment]
A. Great username ;)
B. Good idea, an it should be simple to implement! Thanks!

**Comment by yairm210** [comment]
Okay, that's hands-down our fastest request-to-implementation to date!
Will enter the next version =)
