### ISSUE TITLE
Feature request: Relationship color 

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7870]
Remake the relationship color bcs they make confuse for players. Such as very bad relationship and war relationship have almost similar color so I always mistake when look at diplomatic tab, the friend relationship and Ally too

**Comment by Ouaz** [comment]
For reference:

Too similar colors:

- Friend and Ally colors
- Neutral and Competitor colors
- War and Unforgivable

![diplo_color](https://user-images.githubusercontent.com/11946570/192591251-9082ce3b-085d-4087-b54b-94902a29a999.png)

**Comment by Thienanbad** [comment]
Some are too similar although some darker some lighter but it still hard to
recognize easily. We need to change color so when we open diplomatic tab we
can recognize in a second

Vào 0:10, Th 4, 28 thg 9, 2022 Ouaz ***@***.***> đã viết:

**Comment by yairm210** [comment]
Okay, which colors do you suggest?

**Comment by Thienanbad** [comment]
I dkn because there are too many relationship type but colors aren't enough
to use. Maybe we should ask community on discord to decide what color for
what relationship type.

Vào 1:12, Th 5, 29 thg 9, 2022 Yair Morgenstern ***@***.***>
đã viết:

**Comment by letstalkaboutdune** [comment]
How about this, which provides better color identification? Ally/Afraid/Friend/Neutral/War should be the same as the colors already used elsewhere in the game.

![Colors_edited](https://user-images.githubusercontent.com/56904240/192935185-44f052fd-ca1f-418a-90e8-8340e1809c47.png)

**Comment by Thienanbad** [comment]
I like this one.

Vào 10:56, Th 5, 29 thg 9, 2022 letstalkaboutdune ***@***.***>
đã viết:

**Comment by Thienanbad** [comment]
> How about this, which provides better color identification? Ally/Afraid/Friend/Neutral/War should be the same as the colors already used elsewhere in the game.
> 
> ![Colors_edited](https://user-images.githubusercontent.com/56904240/192935185-44f052fd-ca1f-418a-90e8-8340e1809c47.png)

Competitor should be brown

**Comment by letstalkaboutdune** [comment]
Competitor is brown though.

**Comment by Thienanbad** [comment]
Too similar with the orange

Vào 0:13, Th 6, 30 thg 9, 2022 letstalkaboutdune ***@***.***>
đã viết:

**Comment by letstalkaboutdune** [comment]
Fair enough, the exact hue can be adjusted if/when it gets implemented.

**Comment by Ouaz** [comment]
Good color choices overall. But I would switch some of them (to have a more "gradual" color progression) and change the white to grey (white is too bright, and jarring):

![diplo_color](https://user-images.githubusercontent.com/11946570/193129794-b8cce80d-c4ec-4489-955f-0bb8426a53ce.png)

![diplo_color_gradient](https://user-images.githubusercontent.com/11946570/193129830-75445d9f-cafc-42d0-af9e-738b0e69de8a.png)

**Comment by Thienanbad** [comment]
White is fine for neutral. No need to change neutral

Vào 2:59, Th 6, 30 thg 9, 2022 Ouaz ***@***.***> đã viết:

**Comment by jmuchemb** [comment]
What about dash lines ?

**Comment by nephele-gh** [comment]
> White is fine for neutral. No need to change neutral

Hi,
I'd like to say that the proposed white because of it's brightness makes the line appear bigger, which to on a glance seems to signify significance, but neutral is not that signigicant.

I am kind of missing a hover info in this screen like the infoaddict mod of civ v provided, where the indivual relationships from a civ to another are listed for the specific hovered civ. I think that would make this graphic clearer aswell.

**Comment by yairm210** [comment]
This was improved recently, I think it's good enough to close this
