### ISSUE TITLE
Diplomacy suggestions

### ISSUE THREAD

**Issue by bonezinger** [yairm210/UnCiv#788]
Some suggestions regarding diplomacy:
- Limit the Neutral gain to a total of 30, since it's currently possible to reach +150 standing with another civ doing nothing.
- Have civs suggest the same trade once it's about to end (like luxury trades): ie, on turn 30 after a trade, offers the trade: player pays 200 gold, gets one luxury.
- Make successful trades give cumulative reputation with the other faction (+1, +2, +3...), up to a max of +5 per successful trade. Give once per turn if multiple trades happen in the same turn. (_I know this isn't how civ 5 works, but it makes sense and should make partners less likely to betray one another_)
- Declaring war/being declared war upon should immediately reset the Neutral gain (_Years of peace have strengthened the relation_)
- Declaring war/being declared war upon should break any friendship announcements. (_We have signed a public declaration of friendship_)
- Declaring war on a friend (rep > 50) makes all other civs even more wary of you. The text could be _You betrayed a friend of yours!_ and the penalty -15 or -30, if the reputation was > 100, lasting 20 and 30 turns, respectively.
- War should immediately cancel any and all trade agreements between the two civs (_Not sure if this one's already the case, but if it isn't, it should be_)
- Have a civ that's thinking on declaring war on you demand gifts a few turns before the declaration. Paying the gifts might delay the war.
- Founding a city close (6 or less hexes away) to another civ's should give a negative impact (-10) that lasts for 20 turns or more.
- Make civs ask for help fighting a war, especially if they're losing or have a smaller military. IE: England is getting beaten by Japan. England asks friends (rep > 40) for help, offering whatever it has (gold, tech, luxuries) for the other civ to declare war on Japan.

**Comment by yairm210** [comment]
> Limit the Neutral gain to a total of 30, since it's currently possible to reach +150 standing with another civ doing nothing.

Good idea!

> Declaring war on a friend (rep > 50) makes all other civs even more wary of you. The text could be You betrayed a friend of yours! and the penalty -15 or -30, if the reputation was > 100, lasting 20 and 30 turns, respectively.

Already implemented, after declaration of friendship =)

> War should immediately cancel any and all trade agreements between the two civs (Not sure if this one's already the case, but if it isn't, it should be)

Already done =)

> Declaring war/being declared war upon should immediately reset the Neutral gain (Years of peace have strengthened the relation)

Disagree - we had years of peace, your declaration of war now doesn't undo that

> Declaring war/being declared war upon should break any friendship announcements. (We have signed a public declaration of friendship)

Already done =)

The rest are slightly more difficult to implement

**Comment by Smashfanful** [comment]
Don't forget denouncing someone: in the original Civ V there's the diplomatic option where you can also denounce another leader because you don't trust them (and of course it could happen to you as well), which is easier against a warmonger or a way too ambitious leader.
So in that case there should be things like:
_You have denouced us in front of the world!_
_We have denounced you, for we trust you not._
_You have denounced a friend of us!_
_You have denounced an enemy of us._

**Comment by yairm210** [comment]
Denouncements are on the menu, they have almost the exact same logic as DoF but with negative instead of positive

**Comment by yairm210** [comment]
Merged to #831
