### ISSUE TITLE
Hello I would like to suggest to add a mechanic to the "politiscs tree"? The feather at the top left. Any way, I think that it would make more intersting if we would separate theocracy from liberty. What do I mean by that? I think that if we needed to decide between the tow, it would impact tha game in choosing other politics, for exemple if we take theocracy when we would take piety it would give an tiny extra buff but if we decide to take liberty it would give an negative effect and depending on the next politics you would take it would give or take buffs. A nother one because why not. If the peopel are angry with your role citys would revolt and become independent and depending on the politics that you choose they would take others but theres a thing they wont become independent if you say so, so they'll fight you until they get theier freedom creating a new nation. This would make the game more intersting and you would want to make your status with the people more important.

### ISSUE THREAD

**Issue by gbbBranco** [yairm210/Unciv#7882]
**BEFORE creating (delete this in the actual issue)**

Is your feature a gameplay feature from Civ VI, or from BNW? If so, don't open it in the first place - see Roadmap

Is your feature a gameplay feature from Vanilla Civ V or from G&K? If so, it should go in https://github.com/yairm210/Unciv/issues/4697 - post a comment there!

Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!

Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xlenstra** [comment]
Not in Civ V

**Comment by gbbBranco** [comment]
I am sorry I did not understand. What do you mean by "Not in Civ V"?

Xander Lenstra ***@***.***> escreveu no dia domingo,
2/10/2022 à(s) 11:41:

**Comment by xlenstra** [comment]
Unciv is meant as a remake of the game Civilization V, as can be read in our [ReadMe](https://github.com/yairm210/Unciv/blob/master/README.md). There you can also read in our FAQ that we only implement features originally part of Civ V and our reasoning for that.

**Comment by gbbBranco** [comment]
Thank you for the explanation and sorry for bodering.

Xander Lenstra ***@***.***> escreveu no dia segunda,
3/10/2022 à(s) 23:59:
