### ISSUE TITLE
The currently working on units/building are not updated in the city tab from overview menu after change the queue in city

### ISSUE THREAD

**Issue by PhilipPurwoko** [yairm210/Unciv#7889]
**Platform**
MIUI Global 12.0.12 Stable
Redmi 9A
Android 10

**Version**
 Version 4.2.8

**Describe the bug**
The currently working on units/building are not updated in the city tab from overview menu after change the queue in city

**To Reproduce**
1. Go to overview --> city
2. I can see what currently city working on. Example a Barcelona is currently working on a Lancer
3. So I click at the city name from the shown list (Barcelona) and I cancel Lancer and now I want to make a Bank
4. I press the exit city and go back to the city list
5. The City does not updated its current working object or units
6. But if I close the overview tab and open it again, then it is updated as it should be

**Expected behavior**
If I update It should be updated as soon after I update the queue in the city

**Comment by oliv3r** [comment]
Confirming this on F-Droid build Version 4.2.13 (757)  as well.
