### ISSUE TITLE
[Mod] Feature request: Transform Units

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#7904]
For modders.

Provide Uniques and Action to allow one unit to Transform into another one. Providing modders the ability to support things like deploying a watch tower, or having transforming units that can deal with different situations.

New Unique "Can Transform to [unitName] <for [X] [resource]>" for Units where resource could be Gold or Faith (Culture?)
New Action button "Transform to [unitName] <for [X] [resource]>" if
* unit has above Unique (otherwise don't show)
* target unit is unlocked via Research (otherwise don't show)
* Unit has not used any Movement (otherwise gray out)
* Resource, if required, is available to spend (otherwise gray out)
Using Transform should consume all Movement Points left

**Comment by yairm210** [comment]
Merge this into #3242 we have enough tickets as it is...
