### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by Siphoin** [yairm210/Unciv#7925]
Hello dear developers, I would like the music player to be improved in the game. What is the point? I decided to put my music in the music folder, but it does not work correctly. Firstly, the first track (not original) is not played and you have to click in the settings menu to play. Secondly, it does not resume after the end (no repeat). Thirdly, there is no queue of music if there are more than one track. I would be happy if this was fixed in the new release! Thanks. Sorry for the crooked English.

**Comment by alexban011** [comment]
@yairm210

I think this should either be closed because the music wasn't added correctly 

OR

we could add a criteria which just plays random music from the folder regardless if the user named the files correctly


What do you think?

**Comment by yairm210** [comment]
Closing then
