### ISSUE TITLE
Enemy AI seems to ignore city distance rules

### ISSUE THREAD

**Issue by Scarabytes** [yairm210/Unciv#7931]
**Platform**
Android

**Version**
4.2.12 (Build 756) from Google Play

**Describe the bug**
The enemy AI seems to be able to settle in places that are closer than three tiles to other factions' city borders.

**To Reproduce**
Since it's based on the randomness of enemy AI, I don't know how to reproduce it. I've attached both a save and a screenshot, hope that helps. 
<details>
[save.txt](https://github.com/yairm210/Unciv/files/9818611/save.txt)
</details>

**Expected behavior**
Truro was founded the previous turn and is definitely closer than three tiles to the border of Lhasa. I would have expected the AI to be unable to settle there, since I as a player wouldn't have been able to. (By the way, that rule needs to be explained more clearly! Maybe even add an overlay to show where one can still settle?)

**Screenshots**
![index](https://user-images.githubusercontent.com/39307101/196641962-5d91dcd1-6aec-476f-96d2-6094bb1ee299.jpeg)

**Comment by Thienanbad** [comment]
You wrong. 3 tiles from city not border

**Comment by Thienanbad** [comment]
> **Platform** Android
> 
> **Version** 4.2.12 (Build 756) from Google Play
> 
> **Describe the bug** The enemy AI seems to be able to settle in places that are closer than three tiles to other factions' city borders.
> 
> **To Reproduce** Since it's based on the randomness of enemy AI, I don't know how to reproduce it. I've attached both a save and a screenshot, hope that helps.
> 
> **Expected behavior** Truro was founded the previous turn and is definitely closer than three tiles to the border of Lhasa. I would have expected the AI to be unable to settle there, since I as a player wouldn't have been able to. (By the way, that rule needs to be explained more clearly! Maybe even add an overlay to show where one can still settle?)
> 
> **Screenshots** ![index](https://user-images.githubusercontent.com/39307101/196641962-5d91dcd1-6aec-476f-96d2-6094bb1ee299.jpeg)

3 tiles between 2 cities not 2 borders. If you count you will see from truro to lhasa are 3 tiles. 
Close issue

**Comment by yairm210** [comment]
Not a bug
