### ISSUE TITLE
Temple of Artemis production bonus for constructing ranged units misimplemented

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#7934]
According to civilization 5 code temple of artemis gives production bonus only for constructing UNITCOMBAT_ARCHER type units
```
<Building_UnitCombatProductionModifiers>
	<Row>
		<BuildingType>BUILDING_TEMPLE_ARTEMIS</BuildingType>
		<UnitCombatType>UNITCOMBAT_ARCHER</UnitCombatType>
		<Modifier>15</Modifier>
	</Row>
</Building_UnitCombatProductionModifiers>
```
which doesn't include every ranged unit, like naval ranged units for example. While in unciv it gives bonus for constructing all ranged units.

**Comment by yairm210** [comment]
IF you're correct then this should be changed, however I'm not convinced that you are.
https://civilization.fandom.com/wiki/Temple_of_Artemis_(Civ5) disagrees with you on this.
But there's a simple way to check =- do you have Civ V? Can you check this?
@ravignir maybe you have time?

**Comment by ravignir** [comment]
Archer type unit in civ5 basically includes all land ranged units, that are neither aircraft or siege - in other words archers and their upgrades + chariots and some other unique units. @sockybob is right. On top of that +15% production bonus applies only to a city with ToA.
