### ISSUE TITLE
Fallout ontop of Citadel shows underlaying tile

### ISSUE THREAD

**Issue by oliv3r** [yairm210/Unciv#7935]
**Platform**
Android, 12, 32-bit

**Version**
F-Droid 4.2.13

**Describe the bug**
After nuking a capital city (carthage), fallout was placed on some tiles, including a Desert Hill with a citadel on top of it. The citadel's tile was rendered however as a Desert Hill (again), and I _think_ the 100% damage reduction was also not counted, but not 100% sure on that. After removing fallout, the tile was functioning normally again.

**To Reproduce**
1. Place citadel in fallout region of a city to be nuked
2. Nuke city
3. Unsee citadel
4. Remove fallout
5. See citadel

<details><summary>Saved game</summary>

```
N/A
```
</details>

**Expected behavior**
I would expect that the citadel be at least rendered normally (with fallout on top) it also should still somewhat function? Potentially even protect units.

**Comment by yairm210** [comment]
Please provide a game save with the nuked citadel
Load game - show autosaves - copy to clipboard - paste here

**Comment by oliv3r** [comment]
I'll nuke things again :)

**Comment by yairm210** [comment]
Looks fine to me :/
Nuking a Citadel has the same effect as pillaging it, so it won't provide the bonuses until fixed

**Comment by yairm210** [comment]
(Just like any other improvement)

**Comment by oliv3r** [comment]
It was just a graphical thing, you no longer saw the citadel, just the underlying tile with radiation on top. The citadel was 'camouflaged' :p but cleaning up the fallout, revealed it again!

**Comment by yairm210** [comment]
Does this still happen for you? Because I could not replicate

**Comment by yairm210** [comment]
Closing because I cannot replicate and no answer was forthcoming
If this still happens we can reopen
