### ISSUE TITLE
Problem with ui (?)

### ISSUE THREAD

**Issue by BlueBerrySans365** [yairm210/Unciv#7938]
**Platform**
Windows 7 x64

**Version**
Every version. (right now using 4.2.13 version)

**Describe the bug**
I can see nothing in game. Even flags in language settings

**To Reproduce**
1. Just run it

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game (Not added)</summary>

```

```
</details>

**Expected behavior**
To see at least something like sprites. I can't see even random map on background of main menu.

**Screenshots**
![uncivscreen](https://user-images.githubusercontent.com/46006335/197263006-1b1ce3da-6e26-4528-aacb-39024a670f09.PNG)

**Additional context**
Machine runs on AMD Turion 64 X2 TL-66 (2300 MHz / Two Cores) and 4GB DDR2.

**Comment by yairm210** [comment]
Whoa, that's pretty crazy, looks like the options screen, main menu and language picker are all trying to render on top of each other. This should be literally impossible since screens don't interact with each other at all, and yet.
This is what you get when you run the game straight out of the box?
Can you try deleting the GameSettings.json and see if it changes anything?

**Comment by BlueBerrySans365** [comment]
> This is what you get when you run the game straight out of the box?
Yep
> Can you try deleting the GameSettings.json and see if it changes anything?
Same thing, nothing changed

**Comment by yairm210** [comment]
I hate to say this, but there's nothing I can really do. No device I have ever seen has had this, and nothing in the code anywhere suggests that this could happen, so I'm closing this as "unactionable" 
Sorry :(

**Comment by BlueBerrySans365** [comment]
Welp, maybe problem in gpu?
