### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by ArwQues** [yairm210/Unciv#7939]
It's not very convenient that button "next unit" and "move automated units" are in one place. Some time you want to go to next unit, but instead of that you can only move automated units, and system many times move units in directions I don't want them to move. It would be better if that button was optional so player need to click it to be able to go to next turn.

**Comment by yairm210** [comment]
I have no idea what you're trying to say.
The 'move automated units' only appears once you have no manual units left to move.
If you don't like the way the AI moves units then you can un-automate them.
And I don't understand which button you want to be 'optional'? 'Check for idle units' is optional, there's an optional 'confirm next turn' for if you don't want to accidentally go to the next turn, both in Menu > Options > Gameplay.

**Comment by Overfloo1710** [comment]
el agregar minas terrestres y marítimas al igual que trincheras mejoraría bastante la partida igual que trasportes para las unidades a pie como los marines eso seria todo saludos desde la comunidad hispano hablante

**Comment by yairm210** [comment]
Closing - first suggestion solved by options, second out of scope, not in Civ V
