### ISSUE TITLE
Not possible anymore to convert production to gold after researching Guilds

### ISSUE THREAD

**Issue by mg979** [yairm210/Unciv#7947]
**Platform**
Linux 64bit

**Version**
4.2.14

**Describe the bug**
Not possible to convert production to gold after researching Guilds

**Additional context**
It worked fine in 4.2.12:

![221024_020844](https://user-images.githubusercontent.com/26169924/197425127-98877c7e-ef3d-4629-b81f-309daa278992.png)

Tested in the same saved game too.

Other kinds of production conversion may be affected (I think I saw others in another game, but never with 4.2.14).

**Comment by yairm210** [comment]
Already solved, will roll out in 4.2.15
