### ISSUE TITLE
Cross-platform Save?

### ISSUE THREAD

**Issue by archerindigo** [yairm210/Unciv#7953]
Hi, does the game support cross-platform save? Seems I can't simply copy the save from Android and load it on Windows.

Here's the save: [uniciv_save.txt](https://github.com/yairm210/Unciv/files/9853192/uniciv_save.txt)

Both Android and Windows versions don't have any mod installed.

Edit:
- If I use "Save to custom location", the json file generated works
- The save uploaded above was generated by clicking "Save to Clipboard"

**Comment by yairm210** [comment]
Maybe this is a difference in Unciv versions between devices, Unciv does have cross-platform save, I use it all the time
I'll need more data to see if this is really a bug, please try matching device versions and if you still can't tell me what the exact version is

**Comment by archerindigo** [comment]
It seems to be a version problem after all. The version on Android was 4.2.13 and on Windows is 4.2.14. I just upgraded the version on Android and the save copied from clipboard can be used on both sides.
