### ISSUE TITLE
Show wrong relationship in global politic

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7956]
![Screenshot_20221025_042657](https://user-images.githubusercontent.com/89069988/197633469-118351e5-f64f-4c56-a0da-f5c276a0af2b.jpg)
![Screenshot_20221025_042639](https://user-images.githubusercontent.com/89069988/197633475-89dd25b4-ed67-4c6f-93bd-1f32e33cc5e9.jpg)

**Comment by yairm210** [comment]
No bug, you're not reading correctly.
That's *declaration of friendship* and not status, you can tell because it has "x turns"
