### ISSUE TITLE
Gold production

### ISSUE THREAD

**Issue by Kmueller1716** [yairm210/Unciv#7957]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**
Even after research of guilds is completed, cannot switch city's production to hold

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nacro711072** [comment]
Please update your version to 4.1.15, it should be solved now.
#7947
