### ISSUE TITLE
Unable to proceed to next turn after puppeting a city with no construstion

### ISSUE THREAD

**Issue by loveaabb** [yairm210/Unciv#7962]
**Platform**
Windows 11

**Version**
4.2.15

**Describe the bug**
Puppeted city has no construction, making the game prompting you to choose a construction. However you cannot decide a puppeted city's construction

**To Reproduce**
1. Play as Austria
2. acquire enough gold to make Diplomatic Marriage with a city-state
3. It is a chance that you may encounter the bug

<details><summary>Saved game</summary>

[Austria - 289 turns.zip](https://github.com/yairm210/Unciv/files/9868060/Austria.-.289.turns.zip)

</details>

**Expected behavior**
Be able to proceed to next turn (show "next turn" instead of "Pick Construction")

**Screenshot**
![puppetingBUg](https://user-images.githubusercontent.com/30974194/197993289-239f0643-c699-4eb4-b41e-6f48a51e2a19.png)

**Comment by loveaabb** [comment]
looks like quit and reloading the save solves this....
but it doesnt seems to be expected

**Comment by yairm210** [comment]
Can you send the saved game of *before* actually taking over the city state, if you haven't already?

**Comment by loveaabb** [comment]
> Can you send the saved game of _before_ actually taking over the city state, if you haven't already?

[Austria - 289 turns.zip](https://github.com/yairm210/Unciv/files/9874549/Austria.-.289.turns.zip)

make diplomatic marriage and puppet city-state Florence (on the top of the map) triggers the bug
