### ISSUE TITLE
Feature request: Start at domination victory

### ISSUE THREAD

**Issue by kenta2** [yairm210/Unciv#7966]
It would be nice to be able to start a new game with one human player and zero AI civilizations, that is, start the game as if playing "One more turn..." after Domination Victory.  Among other things, this would allow learning the mechanics of the game in a peaceful environment, such as interactions with city states and the tech tree.

Hopefully not a difficult feature to implement.

**Comment by loveaabb** [comment]
controlling 2 human civ can be a workaround

**Comment by yairm210** [comment]
Your can hotseat multiplayer, or just create a game with an AI to learn with.
There's no reason to add a dedicated option to this extremely niche request that can be fulfilled by other means
