### ISSUE TITLE
Clicking "continue" doesn't do anything and I am stuck.

### ISSUE THREAD

**Issue by obdz** [yairm210/Unciv#7967]
**Platfrom**
Android, P (9), arm64-v8a

**Version**
4.2.14 (Build 758)

**Describe the bug**
I just won in the UN elections. But I am stuck at the voting results screen. When I click "continue" nothing happens.

**To Reproduce**
1. Just load the savegame and the election results will be displayed and you will be stuck at that screen.

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

*The copied save game is too long to put in this comment. [This link contains the copied save game.](https://justpaste.it/8cdnr)*

**Expected behavior**
Clicking on continue will return me to the map.

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Please upgrade to 4.2.15 where this problem is resolved
