### ISSUE TITLE
fix/remove broken music song on android

### ISSUE THREAD

**Issue by ringprince** [yairm210/Unciv#7968]
Hi, 

due (I think) to an internet connection issue while downloading the (one) music song I ended up with an incomplete song, which is very annoying.

How do I fix this?

I guess the easiest would be to delete the incomplete version and re-download.  Where is that music stored and how do I delete it?

I am using the android version.

Thanks in advance!

**Comment by Ouaz** [comment]
On android, you don't have access to the Unciv app files (mods folder, music folder, etc), except the save files (in Android/data/com.unciv.app/files/SaveFiles)

I don't know if it'd work, but you can try to delete Unciv data (on your android device, go to Settings > Apps > Unciv > Storage > Delete Data button.

Do a backup of for you saves files first.

On my device, Unciv app is 37.59Mb, + 47.64Mb of data. I think this includes all mods, downloaded music and save files. So clearing the data will erase everything, except the core game of course. Then import your save backup and redownload the music and mods (if you had some).

Or you could simply re-install Unciv (I think it would give basically the same result than erasing the game data).

**Comment by ringprince** [comment]
Sorry for the long silence.  This worked well - thank you!
