### ISSUE TITLE
Feature request: Starting Bias

### ISSUE THREAD

**Issue by obdz** [yairm210/Unciv#7969]
**Is your feature request related to a problem? Please describe.**
I read that starting bias is already implemented in this game. However, as Arabia I always start in non desert tiles. Desert tiles would be so far away from my starting position. I only played Arabia so I don't know about other civs.

**Describe the solution you'd like**
To be starting in position with my civ's starting bias.

**Comment by RpixPro** [comment]
maybe add feature like "must start at" that is absolute.
