### ISSUE TITLE
A problem with siege units

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#797]
Okay, let's picture the scene: you have a siege unit that has a Great General "beneath" them. Let's say that you have finally managed to obliterate the health bar of an enemy city and you then manage to capture the city itself. Now, when I want to move the siege unit, I can't, for some reason. I can still move the Great General but not the siege unit, which stands still no matter what. I try to deselect the Great General, I try to save the game and reload it again, I even close the game and turn it on again. The result, horever, is always the same: the siege unit is stuck. The only option left is to leave it where it stands as a bastion against enemy units, and sell them when they have outlived their purpose.

**Comment by yairm210** [comment]
Thanks for this!
Fixed by @sulai

**Comment by Smashfanful** [comment]
I wanted to notice you that this actually happens once you mount a siege unit, but I guess you know it already...
