### ISSUE TITLE
Feature request: Enhance Resolution of graphic set

### ISSUE THREAD

**Issue by Mannshoch** [yairm210/Unciv#7975]
**Is your feature request related to a problem? Please describe.**
The pixel style sometimes makes it difficult to distinguish units from the background and other units. Also, with a higher resolution, certain representations such as the arrows to the next movements could be smaller but still more visible.
I had to train a bit to find my way around the very rough display and have fun with it. 

The very minimalistic graphics are too boring.

All in all, unciv is rather unpleasant to play on the tablet.

Translated with www.DeepL.com/Translator (free version)

**Describe the solution you'd like**
Higher Graphic resolution

**Describe alternatives you've considered**
Minimalistic ui

**Comment by yairm210** [comment]
For performance reasons, we cannot include high resolution graphics, although mods can do what they want.

I recommend:
- use hexarealm tileset (options - graphics - tileset)
- Absolute Units mod

If this isn't enough you'll have to make your own mod

**Comment by Mannshoch** [comment]
Thanks for the hint for the Addon. I don't know what you do other than other Games with fancy high resolution and animatins, but Higher Resolution is important. At least I propose to add a higher Image set default to the Android app. May you could add a performance warning to this.
