### ISSUE TITLE
Layout for Promotions

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7985]
Currently, this is how the promotion screen looks like: ![Unciv_2022-11-03-07-29-57.jpg](https://user-images.githubusercontent.com/78449553/199831366-842e1456-ad41-4170-8f85-5e027a249499.jpg)
A long list with all the promotions that you have to scroll trough ![20221103_073114.jpg](https://user-images.githubusercontent.com/78449553/199831460-7551f445-e9d7-4778-83d8-cf118236d11e.jpg)

This can be better.
By having the possibility to arrange the promotions, just like tech and policy screens, you can have a way nicer view of the promotions.

You can arrange them in a way that kinda follows the prerequisite paths and gives some space to intuition.

This also fixes the problem that the scroll gets reset everytime you select a new promotion (when you have xp for plenty).

Something like this, which I arranged in 5 minutes and isnt good, but just to ilustratre...![190 sin título_20221103122419.png](https://user-images.githubusercontent.com/78449553/199832464-4d5b04c1-2609-47b9-9e9e-4f39293ffd33.png)

**Comment by RealBamboolord** [comment]
I think I will need that for an upcoming mod I've planned

**Comment by RealBamboolord** [comment]
@Caballero-Arepa Yairm is doing it 😃

**Comment by Caballero-Arepa** [comment]
@RealBamboolord Great!!
