### ISSUE TITLE
Downloading Mods via link causes error

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7989]
Simple, when you use a link to download a mod, it will add "main" to the mod's name and therefore, the problems that that causes.

![imagen](https://user-images.githubusercontent.com/78449553/200149207-1e96cc0b-c05e-4df3-bd9e-5cea6745011e.png)

The problems it causes:
- Cannot join multiplayer games
- Cannot update the mod

**Comment by RealBamboolord** [comment]
Yes, that also annoyed me before

**Comment by RealBamboolord** [comment]
On PC its fine, as you can manually change the mods name, but on Android, there is no way to access the mod data to manually change the name
