### ISSUE TITLE
F-Droid can't build - missing de.richsource.gradle.plugins:gwt-gradle-plugin:0.6

### ISSUE THREAD

**Issue by licaon-kter** [yairm210/Unciv#7994]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3290348038#L322

Albeit it build fine in the past, odd...

**Comment by yairm210** [comment]
Looks like a one-off, since https://plugins.gradle.org/m2/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom does actually return a result.
Run this again :)
