### ISSUE TITLE
Feature request: Replay mode

### ISSUE THREAD

**Issue by Ccokone** [yairm210/Unciv#8007]
If unciv support replay, i would do like this:

add a setting for replay flag

in the replay mode:

	every action will be save in a file, like actions.text.

	create new game file per 5 turns. (it is "key frame", 5 just a setting)

	each game will create their directory.

playback:

	choose directory

	execute every action

The above are my thoughts, but i do not know how to refresh screen(UI), What do you think?

**Comment by yairm210** [comment]
Modelling every action into a replayable set of actions is such a large project that it's unfeasable. There are simple *too many* different actions one can take that change the game's state.

**Comment by Ccokone** [comment]
> Modelling every action into a replayable set of actions is such a large project that it's unfeasable. There are simple _too many_ different actions one can take that change the game's state.

Thank you
