### ISSUE TITLE
(Unreleased fix for android) Modded promotions no longer work

### ISSUE THREAD

**Issue by Penguinplus123** [yairm210/Unciv#8010]
This is on version 4.2.18
Android, from playstore.
Any mod that adds promotions is no longer allowed to be used. According to the error, it is because they are the same position. This version claimed fixing this, but this problem never existed before???
This update seems to have made a problem it was trying to fix, which is ironically never one that existed. Please fix.

**Comment by Penguinplus123** [comment]
It seems that in a version currently unreleased for Android, this is fixed.

**Comment by yairm210** [comment]
Fully released on Google play

**Comment by Penguinplus123** [comment]
Thx!
