### ISSUE TITLE
City-state is able to puppet another city-state

### ISSUE THREAD

**Issue by KrulesExGamer** [yairm210/Unciv#8016]
**Platform**
Linux, Pop!OS 22.04, 64 bit.

**Version**
4.2.20 (Build 764)

**Describe the bug**
Allied city-state (Hellsand) was able to puppet enemy city-state (Corelia) after last hitting it.

**To Reproduce**
1. Have an allied city-state helping you invade another city-state
2. Get enemy city-state to low health.
3. Let units from allied city-state get last hit.
4. Enemy city-state should be puppeted by allied city-state.

<details><summary>Saved game</summary>

```
```
</details>

**Expected behavior**
The enemy city-state should not be puppeted by another city-state as it says in civilopedia they can't conquer other cities.

**Screenshots**
![image](https://user-images.githubusercontent.com/57680132/202174305-c2422460-8f07-4f2d-8d85-efb856a2d75f.png)

**Additional context**
I'm using the mods Fantasia and Barbarian XP Farm.

**Comment by yairm210** [comment]
They can conquer other cities. This sounds like a civilopedia problem.
