### ISSUE TITLE
Healing in friendly/allied territory does not grant +20HP/turn anymore. Embarked units do not heal at all. Naval units do not heal in friendly waters.

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#8017]
**Platform**
Windows and Android

**Version**
4.2.20

**Describe the bug**
- It seems wounded units put in a friendly/allied territory (including city-states) do not heal +20HP per turn (but only +10HP, like in enemy or neutral territory).
- Additionally, Embarked units do not heal anywhere (neither in owned or friendly/allied waters), and Naval Units only heal in owned waters (no healing at all in friendly/allied waters)

**To Reproduce**

**A) Land unit in an allied city-state only heals +10HP/turn instead of +20**
![land_units_heal](https://user-images.githubusercontent.com/11946570/202282264-778f81b9-2ab6-4b37-ac27-20df9b11b4fe.png)
1. Load this save [heal_land_allied_bug.zip](https://github.com/yairm210/Unciv/files/10025303/heal_land_allied_bug.zip)
2. Go to Genoa city state (allied with the player)
3. Select the Horseman with 50HP left (inactive since 1 turn).
4. Press Next Turn. The Horseman heals only by +10HP instead of 20HP.

**B) Naval unit in allied city-state waters does not heal at all**
![naval_unit_heal](https://user-images.githubusercontent.com/11946570/202283734-61bbdf3c-a2fc-4d87-991f-703564b83378.png)
1. Load this save [heal_naval_allied_bug.zip](https://github.com/yairm210/Unciv/files/10025355/heal_naval_allied_bug.zip)
2. Go to Genoa city state (allied with the player)
3. Select the Ironclad with 78HP left (inactive since 1 turn).
4. Press Next Turn. The Ironclad doesn't heal at all.

**C) Embarked unit in any friendly waters (owned or allied) does not heal at all**
![embarked_unit_heal_1](https://user-images.githubusercontent.com/11946570/202285493-d40ace44-1310-4f2e-955f-5f0f1eab7b1d.png) ![embarked_unit_heal_2](https://user-images.githubusercontent.com/11946570/202285516-f7e6449c-dbd4-49d4-8ec5-c661dd79ed35.png)
1. Load this save [heal_embarked_any_bug.zip](https://github.com/yairm210/Unciv/files/10025396/heal_embarked_any_bug.zip)
2a. Go to Genoa city state (allied with the player)
3a. Select the embarked Artillery with 45HP left (inactive since 1 turn).
4a. Press Next Turn. The embarked Artillery doesn't heal at all.
2b. Go to Hippo Regius (owned city)
3b. Select the embarked Great War Infantry with 79 HP left (inactive since 1 turn)
4b. Press Next Turn. The embarked Great War Infantry doesn't heal at all.

**Expected behavior**

> **Civ 5 healing behaviour (from [Civ 5 wiki](https://civilization.fandom.com/wiki/Combat_(Civ5)#Healing_Damage))**
> To heal damage, a unit must remain inactive for a turn. The amount of damage that a unit heals depends upon the unit's location.
> 
> - In a city: A unit heals 25 HP per turn.
> -  **_In friendly territory (including friendly or allied city-states, and also civilizations with whom you have an Open Borders treaty): 20 HP per turn._**
> - In neutral or enemy territory: 10 HP per turn.
> - **_Naval units cannot heal unless in friendly territory, where they heal 20 HP per turn. Earning the Supply promotion allows healing outside friendly territory._**

**Additional context**
I'm almost sure the +20HP healing for land units in allied territory (including city-states) was working in previous version. Also almost sure that embarked units were healed in owned waters at least.

**Comment by Caballero-Arepa** [comment]
I think I have encounteres this bug too.

And even perhaps on mods. I'll have to check.

**Comment by yairm210** [comment]
Resolved A and B, which resulted from the same problem
C is As Intended - land units should not heal while embarked

**Comment by Ouaz** [comment]
> C is As Intended - land units should not heal while embarked

Ok, I wasn't sure about that one!

Thanks!
