### ISSUE TITLE
Free policy: no policy available to adopt gets me stuck at “Pick a policy”

### ISSUE THREAD

**Issue by felf** [yairm210/Unciv#8021]
**Platform**
Android

**Version**
4.2.13

**Describe the bug**
I built a structure(?) that grants me a free policy. But I have policy unlocked policy available. So once I click the “Pick a policy” button, I cannot adopt one in the dialog and the “Close” button is also disabled. So I leave it with Android’s back button. but the “Pick a policy” button does not go away, leaving me no way to end the turn.

**To Reproduce**
- Have no policy available to pick.
- Get a free policy granted

**Expected behavior**
If there is nothing to be picked, the “Pick a policy” button should not appear.

**Comment by yairm210** [comment]
Please attach a save file

**Comment by yairm210** [comment]
Checked the code and this is already the case.
I assume that you only picked policy branches so far, and not the sub-policies, that is - the icons

**Comment by felf** [comment]
You’re right – I was able to select a sub-policy. I hadn’t noticed those because when I looked at the screen for the very first time, they were disabled, of course.
