### ISSUE TITLE
Feature request:  Hello, I just downloaded github. I apologize if I wrote in the wrong place. I want the local multiplayer to be added to the game. So that several players who take turns making moves can play on the same device. Thanks in advance.  

### ISSUE THREAD

**Issue by 0klerk0** [yairm210/Unciv#8022]
**BEFORE creating (delete this in the actual issue)**

Is your feature a gameplay feature from Civ VI, or from BNW? If so, don't open it in the first place - see Roadmap

Is your feature a gameplay feature from Vanilla Civ V or from G&K? If so, it should go in https://github.com/yairm210/Unciv/issues/4697 - post a comment there!

Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!

Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Caballero-Arepa** [comment]
You already can have multiple human players on the same device.

Just change their civs to "human" and there will be multiple players on the same device.

**Comment by yairm210** [comment]
What you want is called "hotseat multiplayer" and as stated, you can simply set several civs to be 'human' and everything will work :)
