### ISSUE TITLE
Heal Instantly doesn't work

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#803]
Am I the only one that has noticed that the "Heal Instantly" Promotion doesn't work?

**Comment by ozyxcv** [comment]
I've also noticed this before but I'm having trouble recreating it at the moment

**Comment by yairm210** [comment]
The functionality worked fine, it's just that the unit icon didn't update with the new health so by looking at the health bar it looked like nothing happened.
Now updates health in unit icon.
