### ISSUE TITLE
clicking on any tile causes lagging on Android when in the late game

### ISSUE THREAD

**Issue by CrispyXYZ** [yairm210/Unciv#8036]
**Platform**
| Platform | Lagging occurs? |
| --- | --- |
| Android aarch64(arm-v8) | Yes |
| Ubuntu 22.04 x86_64 | No |
| Others | Not tested |

**Version**
≥ GitHub 4.3.0-arbitrary-city-state-uniques

**Describe the bug**
In the late game, clicking on any tile causes lagging.

**To Reproduce**
1.Start a new gane on Android with default options but set *Starting Era* to *Future era*.
2. play for over 20 turns.
3. lagging occurs gradually.

**Expected behavior**
lagging would reduce or not occur.

**Screenshots**
Comparison between v4.3.0(v4.2.21) and v4.3.1:

https://user-images.githubusercontent.com/64761703/202943544-10fb2e61-ce90-49ee-865e-b8ac78e81406.mp4

**Comment by yairm210** [comment]
That entire commit was basically redone in the latest version, so I'll set distribution to 100% so you can check it out

**Comment by yairm210** [comment]
By which I mean 4.3.2

**Comment by CrispyXYZ** [comment]
Unfortunately, lagging did not disappear as I just tested in 4.3.2.

**Comment by yairm210** [comment]
I'll check this out then
