### ISSUE TITLE
Cannot give Work Boats as a gift to City-States

### ISSUE THREAD

**Issue by i2324561w2** [yairm210/Unciv#8041]
I don't know if it's intended, but it could help them, especially if the city is not next to coast and they can't build them.

**Comment by yairm210** [comment]
In general you cannot gift units in water.
@ravignir I don't recall if this is a Civ V limitation or something we added?

**Comment by ravignir** [comment]
> In general you cannot gift units in water. @ravignir I don't recall if this is a Civ V limitation or something we added?

you should be able to gift embarked units. 

> I don't know if it's intended, but it could help them, especially if the city is not next to coast and they can't build them.

You cannot gift Work Boats because they are a civilian unit. Civilian units can only be gifted to major civs. Sweden can gift Great People to City-States tho.
