### ISSUE TITLE
Infinite recursion in moveToTile? 

### ISSUE THREAD

**Issue by vincemolnar** [yairm210/Unciv#8044]
I'm getting a StackOverflowException caused by way too many recursions on https://github.com/yairm210/Unciv/blob/551c6c562e1ec62083f6c7c77805729dbaf18669/core/src/com/unciv/logic/map/UnitMovementAlgorithms.kt#L555

I'm using the latest version on Android with Deciv Redux. Here is the full stack trace:

11-23 00:03:34.040 28094 24491 E AndroidRuntime: java.lang.StackOverflowError: stack size 1043KB
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequencesKt___SequencesKt.any(Unknown Source:2)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.city.CityInfo.getMatchingUniquesWithNonLocalEffects(CityInfo.kt:970)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.civilization.CivilizationInfo$getMatchingUniques$1$2.invoke(CivilizationInfo.kt:456)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.civilization.CivilizationInfo$getMatchingUniques$1$2.invoke(CivilizationInfo.kt:456)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:170)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:90)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.civilization.CivilizationInfo$getMatchingUniques$1.invokeSuspend(CivilizationInfo.kt:454)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:170)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:90)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit$getMatchingUniques$1.invokeSuspend(MapUnit.kt:281)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit.getVisibilityRange(MapUnit.kt:402)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit.updateVisibleTiles(MapUnit.kt:421)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit.updateVisibleTiles$default(MapUnit.kt:415)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit.moveThroughTile(MapUnit.kt:1016)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.MapUnit.putInTile(MapUnit.kt:1029)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:533)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:555)
11-23 00:03:34.040 28094 24491 E AndroidRuntime: 	at 
[...] com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:555)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile$default(UnitMovementAlgorithms.kt:441)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.battle.Battle.movePreparingAttack(Battle.kt:54)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:43)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:30)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:16)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:254)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:223)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:887)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:85)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:277)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:592)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$wZEPzfc3ap1lx3h-gfSjlNGDZEw(Unknown Source:0)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-23 00:03:34.051 28094 24491 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)

**Comment by yairm210** [comment]
Looks interesting! Please attach a savefile, and tell me which unit you moved where to trigger this

**Comment by vincemolnar** [comment]
[recursion-crash-savegame.txt](https://github.com/yairm210/Unciv/files/10077597/recursion-crash-savegame.txt)
This has been copied to the clipboard and pasted into a text file. The crash happens after clicking "next turn", and it's most probably a unit of New Africa.

**Comment by yairm210** [comment]
Thanks! :D
