### ISSUE TITLE
Feature request: Disable Wonders checkbox in New Game Setup

### ISSUE THREAD

**Issue by FiretronP75** [yairm210/Unciv#8057]
**Is your feature request related to a problem? Please describe.**
It is difficult to disable Wonders using mods, because each wonder must be listed and thus kept up to date with current wonder lists of base, expansion, or mods that add Wonders.

**Describe the solution you'd like**
A checkbox in the game setup to disable Wonders, just like there is for Disable Natural Wonders.

**Describe alternatives you've considered**
A "Disable wonders" in the "uniques" of ModOptions.json similar to "Disable religion".

**Comment by RpixPro** [comment]
i think it must say "Disable building wonders" to not confuse with natural wonder
