### ISSUE TITLE
Feature request: Disable Religion checkbox in New Game Setup

### ISSUE THREAD

**Issue by FiretronP75** [yairm210/Unciv#8058]
**Describe the solution you'd like**
A checkbox in the game setup to disable Religion, just like there is for Disable Natural Wonders and like there is in the Advance Setup screen of Civ5.

**Describe alternatives you've considered**
A "Disable religion" in the "uniques" of ModOptions.json is already available, but it requires a mod. It would be more convenient for users to have common disabling type options without a mod.
Another alternative is to use Vanilla, and with no modes that add religions or pantheons. But then you miss out on any other features provided by expansions and mods.

**Comment by yairm210** [comment]
This existed before, but we decided against it precisely because you can mod it in and it's a very niche and not often requested feature.

**Comment by jmuchemb** [comment]
It looks like I should published what I've done (see https://github.com/yairm210/Unciv/pull/7606#issuecomment-1325762714 and https://github.com/yairm210/Unciv/issues/8047#issuecomment-1325714153). However, since I rebuild Unciv with other changes, it's simpler for me to have the ruleset built-in.

**Comment by FiretronP75** [comment]
I can see why the GUI option was removed. But please keep the ruleset option forever for those who need it. Aside from the rule being available in Civ5, it is a huge head start to making no religion mods. And some aspects probably couldn't be removed by  modding alone without this option.
