### ISSUE TITLE
Feature request: Default Save Location

### ISSUE THREAD

**Issue by FiretronP75** [yairm210/Unciv#8059]
**Is your feature request related to a problem? Please describe.**
Can't sync autosaves between devices.

**Describe the solution you'd like**
Option to specify default save location.

**Describe alternatives you've considered**
Option on Android to save to shared storage (i.e. Documents folder)
Document the save locations of each OS, and how to access them if they are in protected phone storage.

**Comment by yairm210** [comment]
You can do this, In save folder, "Save to custom location".

**Comment by FiretronP75** [comment]
Oh it keeps the autosaves with the main save?

**Comment by itanasi** [comment]
Also, you can grab an app to view the Android internal file systems. I personally use FV File Explorer, but there's lots of options. Silly that Google locked things down

**Comment by yairm210** [comment]
Huh
I was certain it did work
Well then
