### ISSUE TITLE
City states improvements

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#806]
- [x] Militaristic city-states
- [x] Ability to liberate city states for huge influence bonus
- [ ] Allies when above 60 influence and having the largest influence of all major civs

Orig. in #680

**Comment by ninjatao** [comment]
What bonus does allies status should provide?

**Comment by Smashfanful** [comment]
For starters, you get the access to the City-State's luxury and strategic resources, permanent vision of the City-State's territory, and they declare war on any civilization you are at war with. Note that a single City-States may only have one Ally at a time. If more than one Civilization has more than 60 Influence points with them, they will ally themselves with one that has the most influence with them.

**Comment by Smashfanful** [comment]
Since Militaristic City-States have been added, then you can check the first thing in the issue

**Comment by yairm210** [comment]
Last point finished by @ninjatao =D
