### ISSUE TITLE
Feature request: Chatting in multiplayer game

### ISSUE THREAD

**Issue by CrispyXYZ** [yairm210/Unciv#8063]
It's annoying to switch to chatting app to chat with friends I play with. So I think there should be a chatting system as shown below:

**How to input message? (alternatives below)**
* Add an input field below the diplomacy and policy buttons. But this may trigger shortcut keys by mistake.
* Add a button to open a dialog to input the message.

**How to process messsges? (alternatives below)**
* Store them in game save file so that another client will receive them when next turn.
* Upload to server as a file named `<uuid>_Messages` stored as base64 of compressed json or raw json. So client can fetch messages when updating status. note the json can be like this:`[{message:"foo", timestamp:<number>},...]`

**How to display messages? (alternatives below)**
* as a notification
* in a popup window
* below the input field/button

**Comment by yairm210** [comment]
Sorry boyo, no way jose am I going to build a chat app on top of what is essentially a FTP service.
If anyone else wants to try their hand at this then great, but this is so far off the roadmap it's like in another country
