### ISSUE TITLE
Always crashing after a few turns

### ISSUE THREAD

**Issue by TheSecond77** [yairm210/Unciv#8069]
**Platform**
Windows 10 64

**Version**
Got it on itch.io, I believe it's the newest one

**Describe the bug**
The game always show the error screen after a few turns

**To Reproduce**
1. I'm just playing it

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
4.3.4 (released yesterday) had a crashing bug that was resolved around 2 hours ago in 4.3.4-patch1, so if you're on 4.3.4, simply updating should solve it :)
If that's not the case, please notify so we can look into it

**Comment by TheSecond77** [comment]
thank you
