### ISSUE TITLE
Feature request: Rally Point

### ISSUE THREAD

**Issue by FiretronP75** [yairm210/Unciv#8070]
**Is your feature request related to a problem? Please describe.**
It is annoying when you need units to head North but they are placed to the South and vice versa.

**Describe the solution you'd like**
Choose the unit spawn location for a city. Of course if that space gets occupied, it will be overridden.

**Describe alternatives you've considered**
In Civ 5, new units temporarily stack in the city. I'm sure that is on the todo list. But I think this feature would be a nice workaround until then.

**Comment by yairm210** [comment]
Closing this as 'not in roadmap'
