### ISSUE TITLE
Undo Last Unit Move OR Confirm Move Unit

### ISSUE THREAD

**Issue by nickpdemarco** [yairm210/Unciv#8077]
It’s easy to misclick on touch devices and that can be a bummer on this game. Undo (without a stack, just last move unit) might be game breaking, and hard to implement, but a way to select-then-confirm a unit’s move would be a nice quality of life improvement. 

But that’s a naive off-the-cuff solution to the general problem of easy misclicks. Curious if other people have this problem / ideas.

**Comment by Caballero-Arepa** [comment]
There is already a confirm move unit button...

**Comment by ravignir** [comment]
![Screenshot_20221203-085156_Unciv](https://user-images.githubusercontent.com/30041793/205430851-9f04bc63-7f63-4b75-bbc5-288b83556d76.jpg)

**Comment by ravignir** [comment]
Maybe you have "Move units with a single tap" enabled under Gameplay in main menu?

**Comment by nickpdemarco** [comment]
Oh I had no idea! Sorry for the obvious question, and thanks for pointing out that option.
