### ISSUE TITLE
Put AI land military to sleep during peace

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#808]
Slow performance during AI move is no surprise and further slow down with development of the game is not either. However I have noticed that after pacifying AI civs (reducing their military power and number of cities) AI turn is again almost as fast as during first turns.

So maybe :
* if AI player is not at war with anyone
&&
* if there is _not much_* land to explore

AI player  should put its military land units to sleep till the moment it gets into a war with anyone? Would it make AI turn take less time?

_* roughly calculated by some fast function_

**Comment by yairm210** [comment]
Performance of next turn is one of those things I've gone over dozens of times, each time I find some other small thing to improve
I'll go over it again and see if I can save some checks that are only relevant when the Civ is at war

**Comment by Am-per-Sand** [comment]
I have raised this point after wondering if this
```
// else, go to a random space
        explore(unit,unitDistanceToTiles)
// if both failed, then... there aren't any reachable tiles. Which is possible.
```
is worth just wandering around 🙄

**Comment by yairm210** [comment]
I'm looking for a game that has a really long wait time so I can analyze why

If you have one, please put it in a details tag, 

<details><summary>like so</summary>
Saved game data goes here
</details>

**Comment by yairm210** [comment]
You were certainly correct that there was a lot of useless moving around for NO REASON - I removed that and added in a couple of other performance improvements while I was at it and this seemed to help a lot - b9cf404
