### ISSUE TITLE
[Desktop][Windows] Resolution

### ISSUE THREAD

**Issue by natrius** [yairm210/Unciv#8090]
I think the resoltion is fitted for Smartphone and not for Desktop. I downloaded directly from https://github.com/yairm210/Unciv/releases/tag/4.3.5 then windows64 zip to try. 

These are the resolutions i got. 
![grafik](https://user-images.githubusercontent.com/7243447/205630135-7b9bb267-d9ab-4b93-821a-8f04c07b2239.png)

What do i expect, for example? 768x1024, 1280x720, 1366×768, 1440x900, 1920x1080, 1920x1200, 3440x1440 for example. Like from https://w3codemasters.in/most-common-screen-resolutions-for-responsive-web-design/

**Comment by yairm210** [comment]
These are *virtual* resolutions that are then mapped to the actual resolution of your screen. 
But you're absolutely right that the numbers are confusing, and should be replaces with text - 'tiny' 'small' etc, so it's not confusing.

**Comment by natrius** [comment]
Yepp, that sounds better :)
