### ISSUE TITLE
[Desktop][Windows] Gamescreen too big for monitor?

### ISSUE THREAD

**Issue by natrius** [yairm210/Unciv#8091]
**Platform**
Windows 10, 64bit

**Version**
https://github.com/yairm210/Unciv/releases/tag/4.3.5

**Describe the bug**
My screen is 3440x1440, In the settings i got 1500x1000 set and the game-screen is to big. 
Top-right corner 
![grafik](https://user-images.githubusercontent.com/7243447/205631463-c90754b7-6d15-4d7a-ab32-8ea7671d9500.png)

Bottom-left corner of my screen
![grafik](https://user-images.githubusercontent.com/7243447/205631517-b82ee786-93a8-4382-85bb-345b97e12b52.png)

**To Reproduce**
1. Download 64bit windows
2. start

**Expected behavior**
The game filling out the whole screen and not more of it.

**Comment by yairm210** [comment]
Rereading now obviously that's not what's going on (using the built-in zoom on Ubuntu does not reproduce this problem either)
My guess is your *screen size* includes the area of the left-side bar, and thus you're missing a little bit off each side
What happens if you put the bar on the bottom, delete the gamesettings.json, and restart? Do you get 'a bit off the top and bottom' missing?

**Comment by natrius** [comment]
Well, it gets cut of at the bottom. It seems to take the whole monitor (including taskbar) 

bottom-left
![grafik](https://user-images.githubusercontent.com/7243447/205690007-99f2096f-a999-4cd3-b0ad-7959fe3ba11b.png)

top-left
![grafik](https://user-images.githubusercontent.com/7243447/205690115-773c908b-ea47-494f-b528-aecf8ec28954.png)

and top-right (because it was there before
![grafik](https://user-images.githubusercontent.com/7243447/205690192-110607b2-4b79-4c18-9d12-4f61bbeedc01.png)

**Comment by yairm210** [comment]
So then [this](https://community.oracle.com/tech/developers/discussion/1301728/need-help-windows-screen-size-excluding-size-of-taskbar) should be a good solution
I'll roll this out in 4.3.6 and I'll wait for your input if that solved it :)

**Comment by natrius** [comment]
It reads like with this setting you could even create a Dropdown where its possible to choose "Full-Screen" and "Windowed" or something like that :D (not really needed, just a thought)

**Comment by yairm210** [comment]
No, those are 2 different things
Here "screen size" is so that we can size things to appear readable on your screen
What you're thinking of is "window size" and we don't need an internal setting for that, users can decide what size of window they want it to be using their native OS

**Comment by natrius** [comment]
Looking better. But for some reason its missing something on the bottom. But i'm now on another screen right now. 

Top-Right
![image](https://user-images.githubusercontent.com/7243447/205892302-b1c28483-6ad5-4c08-95ce-5b40a61836d5.png)

Bottom-Left
![image](https://user-images.githubusercontent.com/7243447/205892363-fe59f615-f001-447c-86d3-06806d07d778.png)

Imo thats something i can ignore, the bottom-stuff. Now on a 1920x1200 screen. Can test on the 3440x1440 in the evening again.

**Comment by yairm210** [comment]
Hmmm if you move the window does it have its own mini-bar on the top? Maybe that's the 'missing' area?

**Comment by natrius** [comment]
*lol* I missed completely its started as window :D For some reason now on the second startup its now completely at the bottom and shows a bit of the mini-bar on top. 
Top-Left
![image](https://user-images.githubusercontent.com/7243447/205904260-cdedb719-12f0-4442-bb87-1e30a8714d35.png)

And if i doubleclick on the bar the windows gets fullscreen (minus Windows-Taskbar of course). 
So it seems the windows has a tiny bit too much height?

**Comment by yairm210** [comment]
Sounds to me like Windows OS tried to place the new window *without the bar* exactly in the middle, whereas Ubuntu tries to place the new window *with the bar* exactly in the middle.
Not sure what that missing space is, and can't guess 🙃 
I'm closing this as fixed
