### ISSUE TITLE
Feature request: Update UI for each AI civ that does its turn

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#8099]
The further into the game one gets, and especially with more [computer] opponents, hitting Next Turn grinds. Wouldn't it be smarter, and far more lively, to update the field per each opponent turn completion, rather than the aggregate of everything done? Applying this to an auto-spectator feature would be cool to watch too.

btw contributor devs, great work on this game. :D

**Comment by AdityaMH** [comment]
Also you can't see animation in spectators mode

**Comment by yairm210** [comment]
What devilry is this?!

**Comment by hackedpassword** [comment]
The proposed demo is a legit UX improvement.

**Comment by AdityaMH** [comment]
> demo
>  Peek.2023-05-17.21-10.mp4





> The proposed demo is a legit UX improvement.

actually no, it's just bar progress. ~~you still can see your unit or enemy unit disappear with no reason.~~

**Comment by yairm210** [comment]
... And? That's still an improvement, he's right

**Comment by yairm210** [comment]
No I meant black magic, and it's definitely better than the "no info whatsoever" we have now
I assume it updates every time we finish automating a civilization?

**Comment by AdityaMH** [comment]
> Just using one image "currently we have" and create ai moving/attacking cinematic by code. like player battle we have.
revival 2 (j2me), civ 3 mobile (j2me), civ5 mobile low screen (128x128) using that method.

**Comment by hackedpassword** [comment]
Render state change per civ upon New Turn
#3242

**Comment by AdityaMH** [comment]
![Image](https://github.com/user-attachments/assets/8c676308-beba-4059-ae36-779760d6c888)
