### ISSUE TITLE
Some issues I noticed

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#811]
- [x] We all know that building roads is a speciality not only for workers, but also for Roman Legionaries. Horewer, it seems exhagerated for them to build them on water tiles, such as lakes, coasts and oceans.
- [ ] If you declare a Friendship Treaty, or Declaration of Friendship, then their territory is ally/friendly to yours, which means you could upgrade your units or give them to your ally/friend when those units are in their territory (that, or just needs the Border-free Rights.
- [ ] There should also be the option of force another nation to make peace with another one. For example, if Egypt declares war on Babylon, then Arabia can interviene and force both Babylon and Egypt to make peace with each others.
- [ ] Also, should barbarian units appear in lakes?
- [ ] You also forgot to tell the players that Spaceship Factories require Aluminium

**Comment by yairm210** [comment]
1. Fixed
2. https://civilization.fandom.com/wiki/Diplomacy_(Civ5)#Research_Agreement has it at Civil Service
3. Feature, but a good point
4. Not in original civ iirc
5. They are explicitly not added there, https://github.com/yairm210/UnCiv/blob/2066978ca0074910e61fdc7f164cdcb178b11918/core/src/com/unciv/logic/GameInfo.kt#L112
6. ? It appears there, don't understand

**Comment by ninjatao** [comment]
Open border is unlocked by writing in civ 4, not 5.
