### ISSUE TITLE
can't load existing multiplayer game / can't start new multiplayer game 

### ISSUE THREAD

**Issue by pixxpix** [yairm210/Unciv#8117]
**Platform**
Android 12

**Version**
4.3.7-patch1

**Describe the bug**
can't load existing multiplayer games since last 2 patches, see error screenshot "Screenshot_20221211-092936_Unciv"

can't start new multiplayer , when i do i get the error "cant upload game"

**Screenshots**
![Screenshot_20221211-092936_Unciv](https://user-images.githubusercontent.com/96768823/206894976-2cdc6aba-c201-4fc2-bb78-3718c16e9961.jpg)

**Comment by yairm210** [comment]
Interesting, what's your multiplayer server? Check in options -> multiplayer
If it ends with a "/" then remove that "/" and it probably should be fine

**Comment by pixxpix** [comment]
Yeeeeah, it works :))) u made my day!
