### ISSUE TITLE
cannot instal 32bit version

### ISSUE THREAD

**Issue by Chitty400** [yairm210/Unciv#8122]

**Comment by Ouaz** [comment]
Support for 32bit version has been dropped since Unciv 4.2.12. This version is pretty outdated (unciv updates are very frequent, with numerous improvements and bug fixes).

**Comment by Chitty400** [comment]
i tried to download 32bit version in itch.io 
and the "unciv.exe" does not open :c @Ouaz

**Comment by yairm210** [comment]
We no longer support 32-bit, the installs on itch.io are there to allow players who can still run them to do so, but we're not supporting them
