### ISSUE TITLE
Promoting a unit with air units on board makes air units disappear

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8126]
In the DeCiv Redux mod, you can upgrade the Carrier to a Heavy Carrier, which can hold more Air units. Unfortunately, if there are any air units on board the carrier when you upgrade the Carrier, upgrading causes the onboard units to disappear.

I've attached a save file with a Carrier ready for upgrading. You'll see the onboard unit disappear as soon as you do.
[Boat ready to promote.txt](https://github.com/yairm210/Unciv/files/10222992/Boat.ready.to.promote.txt)

**Comment by nacro711072** [comment]
When starting upgrade, the Carrier unit will be destroyed, and all transported units should be destroyed as well 
( See `UnitActions.getUpgradeAction(UnitActions.kt:449)` and `MapUnit.destroy(MapUnit.kt:920)` ).

To avoid transported unit disappear, i have two opinions:
A: The upgrade action should be disabled (Gray button) if any Air unit on the Carrier, you need to move them out. 
B: Carrier can upgrade directly, all onboard units will not disappear.

**Comment by yairm210** [comment]
In that case it's Realism vs User Confusion
I think it's better to have the user less confused for why he can't upgrade, so let's go with B
