### ISSUE TITLE
Option to generate resources on custom maps *when making a new game*

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#8134]
You have a custom map that you like, and so you want to play with it in Multiplayer.
The problem, the person that makes the game has access to the map and thus see where all the resources are.

This, evidently, is a problem, as it gives the player the advantage of knowing where the resources are and it is unfair.

So, ideally there would be an option to generate the resurces when making the game, with the civs and all, and this way you get two benefits:
- Both players dont know where the resources are.
- You can have custom maps with custom values of resource generation (abundant, strategic balance, etc)

I dont know if its feasible, hopefully it is.
Bonus points if Ruins are included as well.

**Comment by yairm210** [comment]
Sounds feasible! :D

**Comment by yairm210** [comment]
Closing as 'not in roadmap' as part of our cleanup
