### ISSUE TITLE
Feature request:  
Selectable generic icons to choose from for modded techs, buildings and units, etc

### ISSUE THREAD

**Issue by Kuldebar** [yairm210/Unciv#8158]
Basically just have a generic "type" icon for certain game elements that would otherwise be blank/empty/white circle.

This mostly a modding related request that would use a generic icon for a mod lacking custom graphic.

Or a graphic toolbox to select from - similar to emoji's but organized by type?

Sorry if this ridiculous suggestion but as a novice Android modder the atlas.png and game.png are scary.

**Comment by yairm210** [comment]
What do we have?
- buildings
- units
- techs
- resources
- policies

So one "fallback" image for each

**Comment by Kuldebar** [comment]
Yes! A fallback icon for type. I noticed my modded Techs are depicted as a reddish brown square currently in game, maybe a lightbulb placeholder instead?
