### ISSUE TITLE
City-States quests

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#816]
I was thinking, in a future update, about the City-States quests, which could include...

- [ ] Destroy a nearby Barbarian camp
- [ ] Kill Barbarian units near their lands (can be done at all times, even when they don't call for it)
- [ ] Acquire a Great Person of a certain kind
- [ ] Construct a particular World Wonder
- [ ] Find a particular civilization's lands (this happens when you have already discovered/met the civ in question, but haven't revealed any tile part of its territory)
- [ ] Build a road to their city (only if they're close enough to a city of yours)
- [ ] Donate money to support a Public Works project (Gold gifts are more effective for 30 turns, and although it's not a real quest, it's still very important)
- [ ] Help in a war against another Civ (by killing the enemy civ's units anywhere on the map)
- [ ] Destroy another City-State (by conquering it)

**Comment by Smashfanful** [comment]
Done

**Comment by faulless** [comment]
but you need a reward for those quests //
except for great person

example 
Aquire a warrior unit for completing a 1) Destroy a nearby barbarian camp
win a amount of gold
trade with them their luxury resoures, strategic, etc 
open borders 
task//
 help them to reaquire their city (if they lost a war)

**Comment by yairm210** [comment]
That's not the way it works in Civ V - you get Influence with the city state for completing quests, and that influence gets you bonuses depending on that city state's type (culture, happiness, etc.)

**Comment by Smashfanful** [comment]
Exactly

**Comment by yairm210** [comment]
A. Unciv is supposed to be a Civ clone - literally. There will be time for original mechanics after we've completed the original ones.
B. Doesn't sound like a problem to me, sounds like the AI is successfully blocking you within the rules ;)

**Comment by faulless** [comment]
a ok thanks

**Comment by yairm210** [comment]
Moved to #663
