### ISSUE TITLE
Map is not revealed when moving a unit (in sight range)

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#8161]
**Platform**
Windows

**Version**
4.3.9

**Describe the bug**
When a moving a unit, hidden tiles (not yet discovered) in unit sight range, are not revealed.
The tiles are only revealed at the start of the next turn.

<details>
<summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/11946570/208211148-2ddc0912-701d-4ae6-9168-f194094d2dd7.png">

<img src="https://user-images.githubusercontent.com/11946570/208211186-0bcbec02-adcf-40b4-8bac-3678b2b87ffe.png">
</details>

**To Reproduce**
Just start a new game and move the Settler or Warrior units. Who seem to be both blind. :rofl: 

**Expected behavior**
Hidden tiles are revealed right after the unit movement, if in sight range.

**Comment by jmuchemb** [comment]
See also #8150.

**Comment by RpixPro** [comment]
and also, the explored tiles reveals when you change tileset
