### ISSUE TITLE
Feature request: request for a new unique

### ISSUE THREAD

**Issue by IAmMrX1** [yairm210/Unciv#8164]
request for a new unique for **Building** that:
1._"Gain [stats] from [tileFilter] tiles [cityFilter]"_(e.g "Gain [+1 Gold] from every [Forest] [in this citiy]")
please note that it is different from this:
2._"[stats] from [tileFilter] tiles [cityFilter]"_ (e.g "[+1 Gold, +2 Production] from [Farm] tiles [in all cities]")

The difference of them is: the code 1. in my imagination will provide stats to the building.For example,If there are three forest tiles in this city,the building will have 3 gold with it.
In the same situation but with code 2. ,this building will provide 1 gold for the forest tiles.The result of it is the forest tile have 1 more gold.
They are very different,you know.I wish to hear from u soon.

**Comment by yairm210** [comment]
This should go in #3242
