### ISSUE TITLE
Feature request: Politics relation 2-sided

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#8182]
4.3.10 apk, Android

It would be good if relation is shown on both sides in overview-Politics.
I didn't chekced other situation such as friendship or a war between 2 civs without me.
If it's 1-sided like now, player have to scroll up and down.
We have diagram but politics could be more polished.

![one-sided](https://user-images.githubusercontent.com/64586749/208366287-e367b917-086d-43be-8b18-3b039cbb5dbe.jpg)

edit: imma just delete details tag :)

**Comment by alexban011** [comment]
I'm not quite sure I understand the issue. Show the `Relations` part next to the civ image? I don't see how that would help with the scrolling issue

**Comment by saud2410** [comment]
@alexban011   You can see on the screenshot that the war relation is showed only on the row of Greece. I think if i'm doing war with some civ, "war with OO" massage should be on both civ.

I'm really good with the shape of current politics. The reason i mentioned "scroll up & down" is that there might be many civs in one game.

**Comment by alexban011** [comment]
Ahhh right makes sense

**Comment by nacro711072** [comment]
I think it should be a bug.

I remember on the older version, when two civ are fighting, war message will be displayed on each side in dialog.
