### ISSUE TITLE
Bug Report (Modding): upgradesTo skipped over all upgrades straight to the final one when upgrading via era instead of technology

### ISSUE THREAD

**Issue by AceHank** [yairm210/Unciv#8197]
**Platform**
Windows 10 64bit

**Version**
4.3.11-patch1

**Describe the bug**
If there are more than one upgrades, for example, I have a unit with 2 upgrades, 

Sun Obelisk->Sun Obelisk II (only available during/starting in Classical era)->Sun Obelisk III (only available during/starting in Medieval era)

After reaching Classical era, the unit will upgrade straight into SO III bypassing SO II even when it's not Medieval era.

**Expected behavior**
Upgrades should be only to the unit available in current era

**Screenshots**
Code looks like this:
![image](https://user-images.githubusercontent.com/20128080/208899470-cbdebeda-c83f-48cf-a9c0-04279bcd5904.png)

Currently turn 30 and just entered Classical era but I can upgrade straight into SO III which should be in Medieval
![image](https://user-images.githubusercontent.com/20128080/208899651-740ccb5f-d43d-495a-8d22-9fe00de96fd2.png)

**Additional context**
This isn't the case when I upgrade via Tech instead. This happens with or without Unbuildable unique. This happens also even when the final upgrade is in much advanced era such as Information era.

Thank you as always!

**Comment by yairm210** [comment]
You realize that having "during x era" means that if you pass that era then you won't be able to go up the upgrade tree, yes?
Since see can't make that unit, that's where we'll stop checking
So you probably want "starting from" instead

**Comment by AceHank** [comment]
Yes I realize, I only use it in example for testing. It's the same case even when I use "starting from x era".

**Comment by yairm210** [comment]
Should be solved by 74279329
If not, holler :)
