### ISSUE TITLE
Can't upgrade frigate to battleship

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#8209]
I downgraded Unciv and could upgrade the unit. Looks like related 74279329858d066d3026c3611e7478a2085deded: any change of behavior I should know?

**Comment by yairm210** [comment]
The "which unit can this one upgrade to" system was a mess, so I basically rewrote it from scratch

Rules are thus:
- ruins and 'free upgrade' only upgrade 1 step up from the current unit
- when upgrading a unit as a regular action, we check the entire upgrade path of the unit, and take the last available one - available defined as 'you have researched the tech and there's no "only available when" unique disabling it'


Send me the save file :)

**Comment by yairm210** [comment]
Solved :)
