### ISSUE TITLE
Military unit unselectable

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#8227]
Ver: Unciv 4.3.12 patch-2
OS: Android12(.apk) & Win10(Windows 64)
File: [Autosave-Babylon-11.zip](https://github.com/yairm210/Unciv/files/10299454/Autosave-Babylon-11.zip)
Video: https://youtu.be/PzjEOdrnYb8

**Description**
Military unit cannot be selected if there's great person under it.

**To Reproduce**
1. Download and unzip file above.
2. Press 'Next turn' to go Babylon 12 turns.
3. Check that you can select warrior with worker.
4. Put away worker to move great scientist under the warrior
5. See error

**Expected behavior**
Same as description above

**Additional context**
I have another savefile which i'm playing right now.
However it requires many mods so i made mod-free sample.
And i didn't examined many other combinations like workboat & navy or spaceship parts.

**Comment by jmuchemb** [comment]
Already reported in the PR that broke this. Should be fixed with #8226.
