### ISSUE TITLE
Feature request: Unifying version name

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#8237]
Please unify version name of in-game and github, like using build number on github release.
Or make some easy method to check the build.

We can see current version on settings.
And once it also showed patch number if it's modified minor version.
But now we can see only version and build number, and it's not intuitive.

**Comment by yairm210** [comment]
I don't understand
Pics?

**Comment by saud2410** [comment]
In-game:
![ingame version](https://user-images.githubusercontent.com/64586749/209563003-0cbab4c2-270f-49c6-9217-85b51221a8a9.jpg)

Github:
![github release](https://user-images.githubusercontent.com/64586749/209563113-fd47f1ba-ef74-403c-8b2a-359820be7a9b.jpg)

I think their numbering should be same, either using build number or 'patch' thing.

**Comment by yairm210** [comment]
Uh, yeah, that means you don't have the patch3 version yet

**Comment by yairm210** [comment]
Not a bug

**Comment by letstalkaboutdune** [comment]
> Uh, yeah, that means you don't have the patch3 version yet

Are you sure? I just downloaded patch3 and it also says build 782 for me.

![Screenshot_20221226-101646_Unciv](https://user-images.githubusercontent.com/56904240/209574646-b1aa5b53-16f2-41eb-913e-2f87144c487d.jpg)

**Comment by yairm210** [comment]
*huh*
That's interesting, if you're sure if it I'll look into it

**Comment by letstalkaboutdune** [comment]
I just tried again from github to make sure, and still see 782. I think it's at least worth a double check.

**Comment by saud2410** [comment]
Wow i didn't noticed different patches have same build number.
So what's the meaning of showing "(Build 782)"?
I thought it can differentiate patches.

**Comment by yairm210** [comment]
Different patches have different build numbers, that's what's confusing - this number is probably generated when we generate the version changelog and doesn't come from the source

**Comment by yairm210** [comment]
Oh yes that seems to be it

**Comment by saud2410** [comment]
As i said, any possible way would be good — as long as i can tell clearly what exact major/minor version i'm using, on both in-game and github.

**Comment by touhidurrr** [comment]
good catch. imagine users frustration not being able to know if something is fixed or not. i always knew this behaviour, but somehow missed that it can be a bug. which is kind of funny. i thought it was because some kind of conflict in version naming scheme of android or something.

I think latest released notes with patch release notes

**Comment by yairm210** [comment]
Sounds like the solution is "patch notes"

**Comment by touhidurrr** [comment]
probably

**Comment by touhidurrr** [comment]
Is this issue still up? I thought @yairm210 fixed it. But maybe not the patch note.

**Comment by SeventhM** [comment]
Closing as Solved?
