### ISSUE TITLE
remove `gameId` property for multiplayer games? 

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#8243]
I wonder if this property even has any uses. If it is removed, I can rename games without editing the game's content by just renaming it.

Also, is what @ravignir saying here is how the game works?
![image](https://user-images.githubusercontent.com/46617994/209723975-482ebd48-cbeb-47a3-8c71-288d4b281803.png)

**Comment by touhidurrr** [comment]
![Screenshot_2022-12-28-03-47-27-06_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/46617994/209725332-5a80ac84-e75e-4569-827e-c071d59301e6.jpg)

**Comment by yairm210** [comment]
The game id is what recognizes the game on the server as being the "same game", so it's critical
The internal save is updated when we get a new version from the server
Is there anything else in this issue? Or is it closable?
