### ISSUE TITLE
Feature request: Next unit slide to next round

### ISSUE THREAD

**Issue by Mannshoch** [yairm210/Unciv#8279]
**Is your feature request related to a problem? Please describe.**
I use the setting to have the next unit option on top right. Sometime I have to deactivate this settings because I wish to jump some rounds.

**Describe the solution you'd like**
It would be nice If I had the possibility to slide the button to get the next round.

**Describe alternatives you've considered**
The button blow left. Its also an Working. This button hat the Problem, that the Arrows move depending on the Length of the Unit name.

**Additional context**
On desktop, may add a dropdown arrow to replace the slide action

**Comment by yairm210** [comment]
Closing this as 'not in roadmap' - the technical implementation of listening to slide is extremely non-trivial, and this doesn't seem to be worth the effort

**Comment by Mannshoch** [comment]
![unciv](https://user-images.githubusercontent.com/7795891/226570628-622e5241-15e8-47fc-8b80-b6d459bcfa78.gif)
