### ISSUE TITLE
Crash: Need help

### ISSUE THREAD

**Issue by Wanzittt** [yairm210/Unciv#8281]
**Platform:** Android
**Version:** 4.3.14 (Build 787)
**Rulesets:** [FR A-1.2, jsons, Unciv-leader-portrait-mod-example-main, Civ V - Vanilla, Art of battle, Community Maps, Civ V - Gods & Kings, art of ballte]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: RMX2173
API Level: 31

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.CapitalConnectionsFinder.<init>(CapitalConnectionsFinder.kt:24)
	at com.unciv.logic.civilization.CivInfoTransientUpdater.updateCitiesConnectedToCapital(CivInfoTransientUpdater.kt:158)
	at com.unciv.logic.civilization.CivilizationInfo.initialSetCitiesConnectedToCapitalTransients(CivilizationInfo.kt:908)
	at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:518)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:608)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
**Save Mods:**
```
[art of battle]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1bT2/byBX/KkZOLUC54j+R4i3rxE2KtePG7uYQ+DCmxjJ3KVIlKcdeQ0CBtGiLLgr00ku3ty62PWSxl0UDFEW/zDpNv0XfDCmRFh/NNxRzWyBwaOrN77158/78Zka+OWMJ/AtYlHo3S80PLoMw+JxlQQwvXt74QRbw4uF6D95lycLPP7w5WwRh9hH8mATRFGTe/epf77747bsvvvrf67+fan5F+OcLvuAg8Oar2998d7rUeDqHt2zKhUp+NQfl8Lv45TxeRAJuL7j0jrVg4o1cYzx0zfOB6fLJwLJ0f+ByyxmMdNtyXdfUbTbRgvRZEkyDiIV7bB5kLPRAM9fC2JcT8W6uPEu79uylFrEZ975/++b2b9+sbdXm8XwRFpJLLeEhYOXPWRDK2a/Hw5MJT5Z8suFpJJ+s9Ttr/c6+M8Jeni7BKdKdewlnGZ94unD3hlPlEhwKK49LNx0w8TMpvBXGCZ+c3LHMWusxN3Qbdz411u9yOf3Ok7F+stZyxnpW5hpltOGH0R0/lLN3KrNfydlrOWf9zlmPwPxazgN8qE3jEBw3HMoHHj2ccum0qXDpEY/noYypC5Y+vuTJs1cRn+ChwdLsmPPo6WyexJd8xqPMu/Hhber58Wx3EcEq7H6axtHuE5ZeHLD5J9zP4sTQQDCRGVENinzgp+yS7YYsmu4eg0w01S5ZCGG/B5mz48M4nixPIfijOAvOA3+dYszPI29TexhPA3+3mpC7AuqhFBeRdF3G9VILfIl2nLHsqXj8yVEST/KoOtUyfpV5D17EyWc74JmdNGMJxN9OHO2scvIBuHYesmuenFzPufdkMWMR5EUY+GKyN+lFvAgnz+Y8OhLvro8C/zOIR+HKpQYevApm0p597zCOuHYo/1tqv1zwNKsE7yq1qq8WQZRWfs+4f+HdiJ/pc55ylvgXkCkv33/3z9uv/3AqP05P4tVH3svbt3+9/cu/v3/7x3ff/Pndt3+6/fJbcPFlIBbruoQVa3RPqu0TU21Q5sFgVD6WmTAok3Fg3hXIE2lQ5uNgVA7Ry0ejhK88FgJ2iWmXAnb5xiof9VKhXcLbpUX9pNM5C1N+X+wsZX2dPwx5kgk3ZkLoWITgU8iluMiSBzICy0g6/lAhpB4dh9ToEE6trurALRdw9WxVZIzN50rk3Hl2y1Ud5MVyoFfG6hV5iT+u6B1X3lcWf4Vjb+JX7Xcq8nbFzupz1Z5KIILeH6Irjy5o+4skgQZwJKcBjX0SnEMHWIRgCnCR/775vTaFQHs68Zhvub7PxwNm+qOB5Y/OB2zojge2qzNuD5nOzwwpe8QS+AktRfAwlvLnC4hCnnkw7534fOeMhWHGET0zdnWySCC+dRuWJVr4IczgBWdziPnHETsLYS65z6PF7AwW5Vz0HNFVwNnDYiGEnzeXBFae8upUS+ccdABiNGHJRJO9CJrl44R5uQ9XHhSjREeDdY5kx9T2YCaLhIXao3gGQSL74KMA0nAGz752Esy4dvv27fuvf/3+9Ze3v/vHaU7goHt7NzM2r/rMzynYiyC7+AReiAZs7Zq7urXzI8lodxzX+TF4a34cfA5BesGD6UUGTssJ5EkQXWsJmwQLcORQexVMsgvPMEVvP2TSxBdxNBGKJNlIxYz1kWNYY9cENuvY2qs4CScvErAs76ErN3wcr4nBqTT+4yDNwN1ijU94krAg8n6aAFEAnjERHBsGCe4yhLiUn+5zYYBw3JMgDMEDhKHzOA1WPDlPZH25MfAAeHkGD3dkddllFFVIdJq1iFJEIWQVZGjjhKjKWmDIRrfhyKJpIGD70E3STBGuoOi9Lj6G97NFNA25onF6j8ZJu1TUN6vWcE+3uwdPDXwcNLWP4iyLZx/z8+x5cFmw5fL9c1FR8A/W72prQ8tLNUdd4SveIbaNnHX2Ezx5ohC9HVS2cQ8j2TF2ZOO+CymJjKlasVYba/V0MjrqMzrq01F9hCw1+00VZStwCzoXnW0CersEpaRe76UBzxRKfqkOwlapazUdNAUdgQbkKanMPVYlQHnaDY0MD1CqFbVYeQQUPsmaR1n5Pk9tVHEikcRsInZYsP1QjBMT1VqZpDyhYtEvokCcoeVbnYNVNba1Cey/8i3FrHh5wGdxfoh2s+llS2yXJMfOj2fFUe1/XmtxsS0sZqDFxf9Q9WfxasO+vHf9tvKB0eaDewq51VtH1Lusv95gQkcSVlOvUkKrSE02bcfOsJpywJL04oNX/j5LY+MeoSOtN/rrTKgDiqKqtKCUsrPFRvHKo0Tq3fJKItdWh7aZV+4O7crqd3tndWk7FkZGSa2qC4W183NENXXFdVdzfaf6hqK4uteo3O1oM+iCGUuu8T6oD+mNsLjTWTVCeUNDbYF1nHvc0raKZpfFMGtae61jyvYYxQ1Zp82U3WNV17sYgk245cRBrX3JxeppgVYXEVvvvTb6T21dOlIxOj0gBiOxwnVmFuZ9RKAzUyruI9V6GN7CKI2vNqitmndpG337y

**Comment by yairm210** [comment]
Your game isn't loading for me, are you sure that's the entire save file?

**Comment by Wanzittt** [comment]
> Your game isn't loading for me, are you sure that's the entire save file?

Hi~  I am sure that is the entire save file. Because i  directly copyed the file without revising. 
It's a mod save file and the mod is made by me.But i recently have some trouble: the game will flash back(have error and can not continue to play) after the city is found then enter next turn.
I tried to find the error but i failed.So i want to get help from github.
Maybe you can tell me what file is wrong.
Thanks a lot.
(Forgive my English level.）

**Comment by yairm210** [comment]
The data you uploaded for the file is only part of the entire file
You can try entering the 'load game' screen, clicking on the game, "copy to clipboard", and paste here, and see if that works

**Comment by Wanzittt** [comment]
H4sIAAAAAAAAAOVdTY8kx3H9KwudbKBK6Kzv6htFk5IMLUloaetA7KE5U7vbQE/3uLuH5GqxJ9mwDesn+CoIPvAomDf/GVHmz3B1VdayZyuy6sXraMOAAYHa2Z3MiPyoyMj3IiLffLnat/9br7aH5Zu30c36q/Vm/dvVcb1r/+KLN+3PH7Z/Ou4fbvq/6n/nk9Vds/w4ag737V+uXjZPV6f/7k//2nxzv9ntm9vP15vm1MM3y9gV0etlXL2Nuh+y0w+5/yE5/ZCd/1Cc/1rpf0hHPwwd5Odd5+cdFOdtslHX1bnQ/Lzr7Ly3R0KLt8+jl7vN7dItFt0fmu0HL5tuUl7um9Xxs2Z3v2lOP75aHT76qtl/+vW2uf10v3653q42H67u18fVZvlitTk00f1m9brZf/76vln+4uFutY3ud5v1zbrv7R8emsPxbFL3zabtY7c9/6uH9fZw9vOxuXm1fHP67+HXzaFZ7W9eNbfLL374039+/8d/e/42+mp9c9ztX//Yoh3Y1Oo+A1fXLdqZcYtumur2j3X3J+dOf+v6P5+m2CX9nxc//n39Y8P+V9Kzpv2vV+86rM/6cz/+cnXWx+Jxu+G3F4/7SM4Enve3+N9a2/vd/cP9B5tmfzxN4PH0S8+Oq/3xl9vjfhd9tdo8NMuf/KTV5v/AJvgE/cS7b8XPrf/Bf0bl+Q/F+a9V43951ObRrxXnXafn/5Kfd5Cf/0t6/i/pedePfsj/f6788+jmYb9vtsfPOp1bc367fvFiffOwOb5e/vm7b//723+NXrab4Je3y9xlWXq7uonTzOVxtiqyuCpfJPHti+Ymv02SJE1vut/9bLVv/3ts9u14v1wdml8/tDukOS7bQT7ZvXjy5ep43DSCnLvVN58/7Nu91y7BIto+3GzaEfymWd23+/Gj7erLTTuWfoK3D3dftivw4sP18XU7ecd2Zhd+1k+T+v78t+uM/NXz6HDftDLaHre3q/1tdDity3r78qP9atnP4TCDp1atpO+/++6HP/7jD7/79+//5T/a6T22n8LT1f3yzd3q/nwSbk4bqLn9zfr46u/bv2jXcJn9NP2pK5781c8e1pvbJ2W9+Ot2+Pftou0e9jdt18+O+7bJy/XNk5+tNqvtTXP652fr37Y78FWzfvnquEzqaHv6Op82t+uHu2i/av/vsEwW0dfr2+OrZdZ+RYfTaFxRpklVJYsiLcuo228/b7bNqfvbt++G+KvdzXDcP+/G8av14dhO5Wn9Pm/2+9V6u/z5fnU4tMrcRje7bduo3TXttB/7f/24HeLD/jQpv1hvNu1kPGr6N+0G2B8ftbvfHdYnicvuZO2+wbfvtZIFnjfsjPbbsQ5/+7B9uWne12Kuv04HbEDzXbnTF9sv5/LDbsvrRwcq0367rR2YmN33J3ZuOTp3KNEvx6ndqBm09qNWM2NykiRgfRNhSj9uj7HDUTWphPBe59hgW8T9rtevjjD2p6v94ZV2P0kdcV9cv2VGY5lVIAp8qsRStt11bn2qn9BTu1Ez6NtKjcxMP38jHWYNAjlgpxbGyDnJAHcq+NERH2vcWxgzPYJblv1w4iRw9snfALCbiUmSFoodUMpYgpR0HFLp/ICEqc+3rIcT5mWt7+73u6+au9NPH2zb+8L2+KTz8B/1d+pu1NucDgOkYWR00k4HdOkF5bChxok4ddjHls0dtJCRxEeJmSJ0DeaMqnpShE0DGk/GLogHBWgkGWOd2BrrVOdfIIaSc9lMtss31DeUBY4XSnxoPk+dReykZowNz6LALYAYV8b4Xhn7TeUeo7bQ/NRXTh1ko1bYOo2aQWctOlrsi5Z64y4MiTgTM62SgArUjZ5RwEnrANyZJaVZgMVoAoJnM7c74tDRzJom40teLN7ywHOMOU/TwHnKqR80//RxmnHHqdXnRxjBnLnd5NYTlwfWlTODueFZmkfytf8CzbRHc6661aAn9sX3kMKz1mab4NSh1J88Tmiqpe44W5F3yjE+lZ0OmaQDaDVjrfIpKSwRhWFHE7764NmpHrXrtXj3ZTx71TT3NldjdB/M9GPSjfdULN0+4uxhYZQ4MbaIqbFbJALwoD/CuEWZqVs0nO6XHQ+iYwEcAsTwiTZF9JgJVXznc9fRQoR+Z6arYBjKgtwvBcMPFaLrMtOqkEBhZEVFywAIU9/nC0s72IXslEq1T41KIwUKRoGiU4B0I4mGuSQPcqW0I8vIkaWiMMBhUg8rYSQlgR3DOcqOXEZntW/7QFYzKEc7m87iHgMSRy7g5FK3SQrtiz3cx5x8oCM1e7MEv0CSHLB05BgkPWfihuKcCRzqbbfa2YgLAvRRm7ZRg6e7h+2x/cPo9CPcRB8dq29YMo5WySxpybAwpWYDA44F43yVjPNVMs5XGXK+YML+fRXUEE05BdEEKMC57dIFeFdKTU6NRm2gjaltVUqSUKdcK6xghpWLkjDPspo7fSA6Uaty1ks2uUCmjAIpuagJs1cTUpgj19VJ8uZ8SnQ5ZvrRzo13py29c6k33mNkQV07HDulHNeUAxnlMDfQ9yPa5aETnGeMCChRhoYQv5Bxc2wDSHuX0CxoijFUku1gx1MFhsPgO5VuskWPu+JuGr1sFGWeOa2qnlW9ziW01zTkRHM+XUX60tVUQAivCmEHe1VCSCevyug4gbxjbatKAtcgSShEBczgKUU3rq1Me5+PTK7jqCFwuxi1gW4X2lYlI6kQJWHHnLQgF1zecmbQOTPojJGUTYyYumhoFUgNFUjIZU/IT8eFPmDOIDhGDYUGMzcTrQ2Qb19IGiRzP1SzGnGI1rgoGJuKfYkVwS94doz+yiNGKINXEDxsFLmCEL5PYXsREklrDO9VZNeC1xPtJUnpt4NeAAF/m3kvjNmuI5P0894Ps8qI79ViLkT11IUoYLDEG1nNMAW17vMKCkYyAMeCcesyc77UDG9Qi9YUkKS+rNRT9AAxVPUdpvZ3GPOIxF4fBhypSRQ37qodxaeKSDbg6FDdibUgkiIT3y4wnZQy1aQySi0qUQuIBRs3A656J72vF0Wn1ajwGpmokFMq5OICQHdBdbPsiguQUhql6Og1mdZqLRL2U3SyOLDgj7qdfmzcuFT3XuRCqL16epbRiOiPRf4RCM/T30nFoD6QdDKK1I/JtA9VXi4Y7mnXXTEFjBPa9ZHGVt35MBzucoiG7yB3RpaoscsG8JctwkNn6qYtLMpQMRZyEWDprEuHeB+Y1NCIfvNaoL2Jd8euC3UWQS+YKfG0CHzgIiuMqaGNcetaqcsT9LK0zbpWatyyl0UmsCEaqQ/QXiN1TPaCvJv24iRPg6ko58vzGuLAXkHJF+MTHXuvdWRTPn/Y3u5X4cH5Ksj0PR5F4AY9uurdq+3fbdfH5Rtf3vXpMGV5dOf/+LS52+1PRWm/eDO20O5UGrarL/qX3//zX37/hz9/9+33//W7aOfr3Z6K3+6Xz6Kd//92Se52px4OXTnh8xHdtcocV/vXsjqtNK0+3/7h+3/6E6qJ2BMJY2gP55oVV1HiKlEchkhoK4SWoiwMa9A2KyhZOSUrp2RllKyMkpVSslJKVkLJGoqqj2zWp6vD+sBVBmZLA+t014+WmNUA9IHMgxV2mUzBFGQ4hxgqgEAFofBhDhyO+/hsu1N/eIHCKMyYzJTMRXYdBBOsa4cw5W/iIoBqUKssZ86AsIEdelGx6EUVQC/YValZCKM2hTDoO3d8OSzw2ONWW1fUx56VLOEx89LFeUNk6autc+XWxYKemCwt4+4cw5Y7RyENZEUVL47M70WU0kMSwfxq/jR1joIi5Ex3RJaWbPCy1LlDVEThO3GjlhACQPFkg7eInhUzmviXrtzo+58bgX+9SSvNcdKcKA1HTPA4tDlNhuekrpRBUSvVRRAHOufETo9K1AODIvDHJRCMgkrNEnYsglFQtQj0snJRFoZRaJtl1LhSWRZwGxRXn+FyA2YOgS64B2yYz85dYFxmgQwrt16xKBDyofeOGewqCZ6b7G5ShNMBYJw6sShOJZdFZAzlxHoEmSBLARiWFfJWkYBIChYiKQhvu2RhkDIAgzCsWcWiIH2S5ZV8mmC8NL0hmLDtgXgnXUhltDlyodPHdshgAnCs2FV4NjP94jNfovUarijam3zoCRAqbEN+iARRwaimkFdBC7m4RMJOMFlq7CSRsJP5HUVFaSQUJCLX4ZgzHcZl/6gkPceEXnpZajSETvOU80ohLIFCQwJRypBACpYOMKCzuEd/Axp9vXOKdlcgbatBS7W0hJPmOGlOlIZjOmwsm0vNMuG0TkgtDhmrPUIMt/KjtSuxO9YCwVzUIy4oWQUlK6dk5ZSsjJKVvb9p7TLR4oBdQqJHrDZWwFgBIQtqveOAqQLy95WyqC+WGNEANZkB0AMEZeGzBg5LsOwZFdOEQzxgLVx1Sp8vLmKXgYJhPHLlRsT4jRqJ/csFzkE0hWg3WR6ULB6gdfwrFtSpAqAOmStMYTpiijkSaa7m52OfkWDHdXM4TeiBZhaeIAAaEdUA/FI89mf2hFOfIOJLpPNiKEzGPyPHeDIBbIh6gtmlgQ0rRqROSaZmGw04wxZB/ZGL9TwxWZJRY6J4nVjnZ/bzomoKOep9CEelrbpQtCld9MbJRYkRPZQBvbAyanxH9qNgeXp8R45uB0EadTpPkKcmI3ICbPmz7e7riVb93XJkDOaU7y6Xo1YzslJOVirKAtEstbSkl2b5LTpOE2evycJrMoNkQdFMrHcZi2OSQfEZRWo/Q9eAOKqgquz0V+KsDXpclm3ncbYMSbf7xCe5fXLNdLuxQlK+XVAVuSs9hmj18H0hqxC884bXeRpQ1A4yp2QFjD4CKEoTKrpyGIRoVpcs1aw2lrCmnZ/gyUG/zK5eWSduh1nIUW3KOfM/wKiWudQhSFnTI5YKPoQCXs4CyeGBSJIbnF+CfH3qJN9A0SvwbQY1JJprIFEwIIysWY1XKAChTcvLnn/F0hTz1N5gKw3uirhe2ut6HcIZGAVq

**Comment by yairm210** [comment]
This is still much, much smaller than the text of a saved game
It looks like it's getting cut off - maybe you can send me the file to yairm210@hotmail.com

**Comment by Wanzittt** [comment]
> This is still much, much smaller than the text of a saved game
> It looks like it's getting cut off - maybe you can send me the file to yairm210@hotmail.com

Thanks for your help,i have sovled problem.
In fact it is a small problem,but find it is a  little difficult.Why not try explain why Exception happened and tell us how to sovle it in wiki .For example,tell us wha

**Comment by Wanzittt** [comment]
> This is still much, much smaller than the text of a saved game
> It looks like it's getting cut off - maybe you can send me the file to yairm210@hotmail.com

Thanks for your help,i have sovled problem.
In fact it is a small problem,but find it is a  little difficult.Why not try explain why Exception happened and tell us how to sovle it in wiki.I think that will help more mod.

**Comment by yairm210** [comment]
You tell me why it happened, I don't know what the mood problem was

**Comment by Wanzittt** [comment]
> You tell me why it happened, I don't know what the mod problem was

I found that road and railroad can not be deleted.And they must have "techRequired"(but it is "Default none" in wiki)
Maybe you just need to tell us what things is in connection with the Exception.
Like NullPointerException is in connection with road and so on.

**Comment by yairm210** [comment]
I have no problem making a road-less and railroad-less mod? What seems to be the problem?

**Comment by yairm210** [comment]
Found and solved the other problem, of roads/railroads with no required tech
