### ISSUE TITLE
Feature request: A close button on desktop version.

### ISSUE THREAD

**Issue by cocowcs50** [yairm210/Unciv#8282]
Hello, I might be very dumb but I did not see it anywhere.
It could be nice to have a simple button to close the game on Windows, like on the main menu. I can use only my mouse for everything in the game which is very nice except to close it where I need to ALT+F4.
This is a very minor request so no hurry. Keep up your awesome work.
Thanks.

**Comment by yairm210** [comment]
Options - exit should do it
