### ISSUE TITLE
Policy Screen Crashes with screen size set to Tiny

### ISSUE THREAD

**Issue by bex-dk** [yairm210/Unciv#8294]
Running on Android. Reproduced it myself on both a phone and a tablet.

Version:

![Screenshot_20230102_163208_com unciv app](https://user-images.githubusercontent.com/121815505/210258731-233df415-5e5f-4f43-b2d7-6b9a282aee69.jpg)

Display settings:

![Screenshot_20230102_172142_com unciv app](https://user-images.githubusercontent.com/121815505/210258767-09c5ff5f-bd01-4d41-8f83-e38f7cc5e54e.jpg)

When entering the policy screen, whether from the prompt to choose a new policy or directly from the feather icon in a progressed game, the game freezes and eventually I get a "not responding" pop-up from Android.

Problem duplicated on a working clean install by copying display settings.

Workaround: Change Display size to SMALL. Policy screen then works without error in either activation.

**Comment by yairm210** [comment]
Resolved by #8280
