### ISSUE TITLE
City states

### ISSUE THREAD

**Issue by DaneelGavin** [yairm210/UnCiv#830]
Thanks for adding city states and on creating a decent android version of civ.
After starting on continents large, 4 city states 1 enemy a few crashes occurred.
On initing trade with the enemy civ china, giving them an intro to Florence was fine. Recieving an intro from china to Rio crashes game.

Milan offered me a trade of luxury goods, asking to renogotiate crashed. 

Thank the savegods no games were harmed. If needed, happy to upload saves

**Comment by yairm210** [comment]
Introduction to Rio - known and fixed
City states offering trades - I didn't know about that, and I'll fix it immediately, thanks!

**Comment by DaneelGavin** [comment]
Thanks to you for such quick reply. ♡♡
