### ISSUE TITLE
AI founds cities too close

### ISSUE THREAD

**Issue by uuoooh** [yairm210/Unciv#8301]
**Platform**
Android 11

**Version**
F-droid 4.3.9-patch 1
No mods

**Describe the bug**
While observing AI-only games discovered multiple instances of AI founding cities with only 2 tiles between them.

**To Reproduce**
1. Start new game as spectator
2. Skip game until most of the map is covered by cities
3. Watch AI managing to squeeze cities in between.

**Expected behavior**
All cities having at least 3 tiles in between

**Screenshots**
![Screenshot_20230104-064036](https://user-images.githubusercontent.com/121904910/210448362-a6f22636-6880-47f6-b24e-66394335c22e.jpg)
![Screenshot_20230104-065259](https://user-images.githubusercontent.com/121904910/210448372-ad153236-431c-4d77-a7e0-1b20e6f59d81.jpg)
![Screenshot_20230104-065323](https://user-images.githubusercontent.com/121904910/210448377-5ddefe00-2f6e-4a9a-8726-2ab48fe6515c.jpg)

**Additional context**
Doubt it matters but it was Prince difficulty, Marathon speed, Large map. I checked previous issues and havent found duplicates, though it may already be fixed.

**Comment by uuoooh** [comment]
Updated to 4.3.14. The issue persists. Tiny map, quick speed, otherwise same settings.
![Screenshot_20230104-082905](https://user-images.githubusercontent.com/121904910/210458409-b4fb082c-f68c-45e2-85aa-aa31af467131.jpg)

**Comment by yairm210** [comment]
Cities across water only need 2 tiles between them, not a bug
Where do you think we can make this clearer?

**Comment by uuoooh** [comment]
Here for example. Or in some other tutorial passage dedicated to cities.

What do you mean by "across water"? Some cities pictured are not across water from each other. Look at the first screenshot, check out Kano and its southern neighbors
![Screenshot_20230105-140507](https://user-images.githubusercontent.com/121904910/210705922-bea81f31-86b0-4242-95d4-ce1f4a5265d5.jpg)

**Comment by yairm210** [comment]
All in all, this is a Civ V mechanic that is working as it should.
I'll try to improve documentation.

**Comment by ravignir** [comment]
> 
should not work with mountains tho, these still count as a land tile.
