### ISSUE TITLE
Feature request: More Desktop friendly builder UI

### ISSUE THREAD

**Issue by joendter** [yairm210/Unciv#8304]
**Is your feature request related to a problem? Please describe.**
Making a builder start building an improvement on a tile takes 3 clicks. In theory you could do it with 2 key presses if you were to memorize the hotkeys...
3 Clicks in of itself aren't terrible, but they're on completely different parts of the screen. I can imagine this works great for touchscreen devices but not so much for desktop devices. On a touchscreen device you can quickly click on any part of the screen with low accuracy. A mouse enables a lot more accuracy at the cost of taking longer to get from one side of the screen to the other.

Looking at civ 6, you can just build improvements with a single click. (not counting selecting the builder ofc since you always spam next idle unit anyways.) This system hardly works for touchscreen devices, but works great for desktop devices in my opinion.

**Describe the solution you'd like**
Add an option for civ-6-esk builder menu. 
![image](https://user-images.githubusercontent.com/71767955/210513792-1fe68c66-b245-4862-a8e6-bba59dbc093a.png)
just have a grid of the improvement icons there, and if you hover over any icon you get more info about the improvement, if you leftclick it you start to build it and if you rightclick it you get taken to the civilopedia page.

**Comment by vegeta1k95** [comment]
On mobile there is no left and right clicks, nor the mouse cursor to hover with.
