### ISSUE TITLE
UI saying "Working..." forever

### ISSUE THREAD

**Issue by Germuop** [yairm210/Unciv#8323]
When I press "Next Turn"  it says "Working..." and never loads. Even left it for 30mins and was still saying "Working...", not trying wait for it to load that long, thats if it evens loads; I play this game whenever I can, I'm having withdrawals dawg, please fix this soon.

**Comment by nacro711072** [comment]
Please provide a game save.

**Comment by Germuop** [comment]
[Uploading Israel - 445 turns.json…]()

**Comment by Germuop** [comment]
Let me know if that was it.

**Comment by nacro711072** [comment]
> Uploading Israel - 445 turns.json…

I think that is right.

But if you send a comment containing a file/picture before it finish uploading, it will only display with 'Uploading [file_name]'. Please wait a second until upload complete, otherwise we can't see your file.

**Comment by Germuop** [comment]
I'm trying to put it in, but it's just not doin man.

**Comment by Germuop** [comment]
[Uploading Israel - 445 turns.json…]()
I've waited for a bit for it change from 'Uploading [file_name]'. Could you give me an email I could attempt to send to?

**Comment by yairm210** [comment]
yairm210@hotmail.com

**Comment by yairm210** [comment]
Not a bug, just a gigantic game, about 3-4 times the size of a regular game, so it takes a while
