### ISSUE TITLE
Map Generation Type new game option reset to Default

### ISSUE THREAD

**Issue by Skekdog** [yairm210/Unciv#8324]
**Platform**
Android 11

**Version**
4.3.17 GitHub

**Describe the bug**
Unlike other map generation options, Map Generation Type does not save when a new game is started. It always is set to default when pressing New Game button.

**To Reproduce**
1. Click new game
2. Change Map Generation Type
3. Start new game
4. Go to new game screen, and see Map Generation type get reset to Default

**Expected behavior**
The Map Generation Type option persist between the new game screens.

**Comment by nacro711072** [comment]
May broken from this PR:  #8271
`MapParameters.type` had been modified as other value.
