### ISSUE TITLE
Feature request: Gameplay: Holy Wars

### ISSUE THREAD

**Issue by Germuop** [yairm210/Unciv#8346]
I feel there should be involvment from religions. Holy Wars should be part of that. Just a suggestion since I think it'd make the game have different ways to progress. Also a religious victory would be cool. Like when more than 70 or so percent of the total population in game, you will win.

**Comment by yairm210** [comment]
Not a Civ V feature, so as per our guidelines we won't be adding it
https://github.com/yairm210/Unciv#will-you-implement-feature
