### ISSUE TITLE
Feature request: Add playtime in session to discord integration

### ISSUE THREAD

**Issue by joendter** [yairm210/Unciv#8351]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/71767955/211414621-571fdb03-1c0c-48b5-9028-e19f1a9b9bab.png)
current discord integration only shows turn of player and civ.
I want to laugh at ppl with 2d playtime though :(

**Describe the solution you'd like**
Add "playing unciv for `time`"

**Comment by yairm210** [comment]
Unlike "playing" which is basically Unciv advertising on Discord, this feature doesn't contribute anything, and is much more of a privacy issue than just 'playing the game'.
Disagree.
