### ISSUE TITLE
Feature request: Map Editor overlay image

### ISSUE THREAD

**Issue by DistendedDev** [yairm210/Unciv#8357]
**Is your feature request related to a problem? Please describe.**
Creating maps for real life places is very tedious and slow. It is very hard to maintain the right scale and shapes. 

**Describe the solution you'd like**
There should be a button that lets you select an image to overlay on top of the map. The image moves with the map. This can speed up the process of creating maps, allowing me to convert real terrain to hexagons easily. 

**Describe alternatives you've considered**
I've seen some projects that would generate a civ map directly from an image. But I think its too complicated and don't need to be in the base game.

**Comment by yairm210** [comment]
Sounds like black magic levels of complicated, can hardly imagine what this would look like
Definitely not in the roadmap
