### ISSUE TITLE
Feature request: Store non-essential data locally, instead of sending it to the server

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#8363]
**Is your feature request related to a problem? Please describe.**
The notification log is sent every turn to the server, which means I had to limit the maximum log turns to 5-15 (arbitrary numbers). 

**Describe the solution you'd like**
Store the notification log to a separate file which isn't sent to the server. Once the player resigns / the game finishes the file can be deleted.

**Additional context**
I could give this a go but before actually implementing this I'd like to know if I even should try this. That is if you know any disadvantages this could bring.
The advantage is that we can increase the maximum notification log to whatever the user wants. 
The main issue with the notification log pointed by touhidurrr was the 15 turn limit. Storing this sort of data locally without actually bothering to send it over the internet would make it possible to increase the turn limit without increasing the game file size. 

There might be more data that can be just stored locally instead of sending it to the server, but rn I can only think of the notif log.

**Comment by yairm210** [comment]
Sure, other people don't need to know your notifications history

**Comment by yairm210** [comment]
Are you planning on working on this?
In any case, I'm closing this issue
