### ISSUE TITLE
Feature request: Don't cross-overwrite autosave when closing games

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#8367]
![atsv](https://user-images.githubusercontent.com/64586749/212160346-8ab30809-14c3-4271-970f-99474cad7fc7.jpg)

We have 4 kinds of savefiles;
1. **_Autosave-(nation)-X_** : Named & saved by unciv
2. **_Autosave_** : Named & saved by unciv
3. **_Quicksave_** : Named by unciv, saved by player
4. **_Nation - X turns_** : Named & saved by player

Type 1 is generated when i press "next turn" button, containing the situation at the very beginning.
And type 2 is generated somewhat randomly and regularly.
If i load a file, do something(= change type2 autosave), then shut off game, 1 becomes same with 2.
Why there should be 2 same files? I hope number 1 doesn't change.

**Comment by yairm210** [comment]
Number 1 is for the start of the turn, for reproducibility of bugs and if you made a mistake and want to start over
Number 2 is for returning to the game after making some changes so you don't lose all your progress in the turn it you get a call, or your phone dies, etc
Number 1 should not be the same as 2, this sounds like a mistake

**Comment by saud2410** [comment]
Let me explain again. I use No.1 autosave a lot, to start again whole turn. But if i shut down game while i'm actaully changed something(say unit position, declaring war, buying building, etc.), the intermediate situation is saved in not only no.2 but also no.1. If you really want reproducibility, it should not happen.

**Comment by saud2410** [comment]
Wait... i tried to reproduce symptom but it doesn't overwrites no.1 save, the starting information!
But now there's another problem; game makes autosave of older savefiles.

For example, i played Maya until 99 turns straight, saving every single turn before pressing next turn.
So there are 100 of no.4 savefile(t0 ~ t99), 10? of no.1 savefile(t90 ~ t99), 1 of no.2 savefile(t99).
If i load t5 savefile `Maya - 5 turns` then shut down, game makes `Autosave-Maya-5` but it's same with `Maya - 5 turns`.
It was definitely different when i was playing until t5 but now it's t99.
`Autosave-Maya-5` is once removed then generated again, and it's same with file saved by player.
What's the point of having autosave when there is already same & stable savefile?
And worse thing is, 9~10 autosaves should be 9~10 so `Autosave-Maya-90` will be removed.

**Comment by Gualdimar** [comment]
I can confirm that when you exit the game, two save files are overwritten: "Autosave" and the last one "Autosave-[nation]-[turns]"

**Comment by Gualdimar** [comment]
files.autoSave function creates "Autosave" and makes a copy of it with the name "Autosave-[nation]-[turns]" every time it is called(onPause, onDispose, ...). 
but the "Autosave-[nation]-[turns]" file should be created only at the beginning of a new turn.
