### ISSUE TITLE
[Suggestion] Invert numbers order for final strength comparison

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#8368]
Based on 5094fc8.

By convention (strategy games,  RPG), when displaying a range of the remaining health after attack damage, the higher value is listed first, then the lowest, if the HP bar decreases from left to right (like in Unciv).

Here's a comparison:

A - current implementation: it shows 100 -> [lowest - highest] range.
_It's a bit counter-intuitive._

B - suggested order:  100 -> [highest - lowest] range. 
_More consistent, as everything decreases from left to right (HP bar, HP values)_

![output](https://user-images.githubusercontent.com/11946570/212178169-3e3664a9-e8a7-45de-9ee8-f86d09d563cc.png)

Thanks for reading.

EDIT: I add this here, because it seems people didn't understand what the numbers represent.
![HP_decrease_bar_values](https://user-images.githubusercontent.com/11946570/212199638-143d5c12-6b71-4edd-aefb-3b60cf3577b8.png)

**Comment by yairm210** [comment]
Polled on Discord
On Sunday we'll see the results

**Comment by FiretronP75** [comment]
Is the red actually showing minimum damage? I would expect to show the middle of the possible range, unless the minimum is much more likely to happen than the middle of the possible range.

**Comment by Ouaz** [comment]
> Is the red actually showing minimum damage? I would expect to show the middle of the possible range, unless the minimum is much more likely to happen than the middle of the possible range.

The red stops at the middle of the range.
For the Gatling Gun, it is at 70.

I wrote 76 on the 2nd mockup, to make obvious that the numbers below the health bar represent the remaining health value (some people on the Discord poll missed that point), and the "direction" should be the same (everything decrease from left to right, bar and numbers).

**Comment by alexban011** [comment]
Kind of off-topic but it would be nice to be able to also see the range in the health bar. Something like this

![damageIndicator](https://user-images.githubusercontent.com/21990802/212403038-192e2eb7-e0d8-4260-9af2-26a94328e2af.png)

**Comment by FiretronP75** [comment]
I think it is on topic. And I agree.

```
already | sure | maybe  | sure
missing | dmg  |  dmg   | remaining
----------------------------------------------------------
 black  | red  | orange | green OR yellow OR orange OR red
                          (maybe make this segment always green, just in combat chart?)
```

**Comment by yairm210** [comment]
Oh, interesting!

So far we've had 4 suggestions total in this platform -crossing subject, so let's give a current status:
- reverse numbers - denied by poll
- show damage numbers instead of final health - denied by poll (my 'average player' intuition pump is still running strong)
- reverse direction of health bar - I think dune's second suggestion of "street fighter" style, depleting towards the center, is the Best Choice, but we'll see what the masses say ;)
- different colors for certain and uncertain damage - *great idea!!* And we'll implement it!

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/212488329-68581200-dc33-4042-acf8-c9ae373cc56f.png)
For continuous rendering, only the definite damage part flashes
