### ISSUE TITLE
Himeji Castle gives combat strength to boats

### ISSUE THREAD

**Issue by N1cc3** [yairm210/Unciv#8374]
**Platform**
Android 12

**Version**
Play store v4.3.20

**Describe the bug**
When fighting an enemy boat e.g. Frigate while they have Himeji Castle built, they gain +15% combat strength even though tooltip says it gives only when fighting in Friendly Land tiles. So either it works wrong or tooltip is wrong.

**To Reproduce**
See description

**Expected behavior**
Either 1. Naval unit should not get +15% bonus or 2. Tooltip should say "Friendly tiles" not "Friendly Land tiles".

**Screenshots**
![Screenshot_20230113_213213_Unciv](https://user-images.githubusercontent.com/6773629/212403280-0d7dfea5-4a6a-4dbf-bfdb-57e56c6390db.jpg)

**Comment by yairm210** [comment]
Water is considered "friendly land", land as in Area not as in Not Water
But technically this is the same as Friendly so I'll change for readability
