### ISSUE TITLE
happiness > 0 but 2 cities grow as if happiness < 0

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#8375]
1. load [happiness.gz](https://github.com/yairm210/Unciv/files/10415218/happiness.gz) (zipped because to big to copy-paste)
2. global happiness is 2 (actually 3 with a no-religion mod I'm playing but it doesn't matter)
3. the world screen shows that Boston would grow to 4 citizens in 74 turns, as if it was +1 food
4. enter the city and notice that it's actually +2 food
5. exit the city and now the city plate shows 37 turns, as expected
6. next turn
7. food in Boston increased from 16 to 17

Similar issue for New York. No issue for the capital.

**Comment by yairm210** [comment]
What an unusual case this was and what a drilldown was required to figure out what was going on!
This happens because you have the Fountain of Youth providing enough happiness *as tile yield* to get you out of **un**happiness
I would never have been able to replicate this given the description
