### ISSUE TITLE
Starting culture doesn't work

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#8378]
I've noticed that regardless of starting era, the starting culture is always 0, even though in Eras.json there are non zero values for all eras besides the ancient era

Debugging shows that the culture is added when creating the game but after the game loads it will be reset to 0

**Comment by yairm210** [comment]
Interesting!
At what point did you measure and found it reset?

**Comment by alexban011** [comment]
Ok so when starting the game debugging showed 200 stored culture but the game shows this

![cultureIssue2](https://user-images.githubusercontent.com/21990802/212496244-11897643-5cbb-462a-b1d7-e341c6ed8c0b.png)

BUT the culture is indeed there, it just can't be used

![cultureIssue](https://user-images.githubusercontent.com/21990802/212496270-0d3d7500-3508-4846-b42d-667e6bdb511d.png)
