### ISSUE TITLE
"Consumes [amount] [resource]" not working on promotions

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8383]
Windows 10 64-bit, itch.io version 4.4.0 (also seen on earlier versions)

The "Consumes [amount] [resource]" unique is not kicking in when applied to a unit promotion. Giving a unit that promotion will not consume any of the specified resource.

This file contains a simple mod that includes a "Consumes [1] [Horses]" promotion, and a saved game with a unit that has that promotion.
[ModPlusGameSave.zip](https://github.com/yairm210/Unciv/files/10420912/ModPlusGameSave.zip)

**Comment by yairm210** [comment]
This is a feature request, and a modding feature request at that. Into #3242 it goes
