### ISSUE TITLE
"[stats] whenever a Great Person is expended" not working

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8387]
Windows 10, 64 bit, itch.io 4.4.0

The "[+50 Faith] whenever a Great Person is expended" belief doesn't appear to be kicking in. I can expend Great Prophets and Great Scientists and I don't get any faith boost. The "Provides a sum of gold each time you spend a Great Person" is still working just fine, so the Mausoleum still provides Gold, but I'm not getting Faith.

The saved game features a Great Scientist ready to be expended.
[BeforeExpending.zip](https://github.com/yairm210/Unciv/files/10421351/BeforeExpending.zip)

**Comment by yairm210** [comment]
Looks like you have no such uniques
What exactly here is supposed to be providing the Faith unique?

**Comment by SpacedOutChicken** [comment]
It's in the base game, as part of the Reliquary Enhancer belief.
