### ISSUE TITLE
rollback to 1-movement-point-siege-set-up

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#839]
I have nothing against [setting up a siege unit consume the turn](https://github.com/yairm210/UnCiv/commit/c11915c978213400b66d648d841b0ccb73b4cc77#diff-6b61355763aba0a12c75de261820cf62), event though originally it required [1 movement point](https://www.carlsguides.com/strategy/civilization5/units/siege.php).

The problem is that it significantly changes balance of power during the siege. In early turns, city capture becomes more difficult. May be there is a way to keep current changes and roll back to
1-movement-point-siege-set-up?

**Comment by yairm210** [comment]
You're right, this wasn't supposed to happen, good catch!
