### ISSUE TITLE
Translation Not Working on "Our influence with City-States..."

### ISSUE THREAD

**Issue by iamlibertybell** [yairm210/Unciv#8403]
**Platform**
Linux 64bit

**Version**
4.4.1 (798)

**Describe the bug**
"[civName] has adopted the Patronage policy Our influence with City-States has started dropping faster!" show in English when the other CIV adopted the Patronage. Those sentence have been translated.

**To Reproduce**
1. Play the Game
2. Wait the other CIV finish Patronage policy
3. See error

**Screenshots**

![CIVbug](https://user-images.githubusercontent.com/72909724/213075316-598cb32e-fe52-4808-8cb0-68d35b2962ec.png)

**Comment by yairm210** [comment]
Please attach a save file of the turn before this occured

**Comment by yairm210** [comment]
I'm like 90% sure I solved the problem but I'll need a save file to confirm

**Comment by iamlibertybell** [comment]
Tt has been overwritten by after a lot of next turn. I will try to make a new one ASAP.

**Comment by iamlibertybell** [comment]
[Autosave-Germany-306.zip](https://github.com/yairm210/Unciv/files/10452373/Autosave-Germany-306.zip)
