### ISSUE TITLE
GPs don't spawn for some nations while GPP overflow

### ISSUE THREAD

**Issue by trexxet** [yairm210/Unciv#8412]
**Platform**
Android 11

**Version**
4.4.2 (799)

**Describe the bug**
This happened while playing hotseat against myself - **some** nations have their GPP overflowed and yet GPs do not spawn. Some GPs still do (e.g. Great Prophet in Egypt) and some nations have their GPs spawned correctly. I don't know how to reproduce it neither why this happens not to all nations.

Game save: 
[Egypt - 359 turns.txt](https://github.com/yairm210/Unciv/files/10448668/Egypt.-.359.turns.txt)

**Screenshots**
![photo_2023-01-18_17-15-02](https://user-images.githubusercontent.com/4649497/213242371-69d5c58b-6395-40f4-b096-428548bb8f0d.jpg)
![photo_2023-01-18_19-23-21](https://user-images.githubusercontent.com/4649497/213242404-e59af0af-5b24-4c4f-a629-8414e69bf49e.jpg)

**Additional context**
Mods in save:
5Hex Tileset
Ancient Civilizations
Brave New World
Civ 5 - G&K
Civ V - Vanilla
Community Maps
Future Expansion
Medieval Civilizations

**Comment by yairm210** [comment]
Same issue as #8405, solved, will enter next version
