### ISSUE TITLE
Great People not spawning

### ISSUE THREAD

**Issue by N1cc3** [yairm210/Unciv#8421]
**Platform**
Android 12

**Version**
Play store v4.4.1

**Describe the bug**
It seems Great People should have already spawned but they aren't spawning.

**To Reproduce**
Load saved game given below and check if great people should spawn. The counters are over the limit already.still none spawn on the next turn. 
Saved game too big for copy paste so json here: https://drive.google.com/file/d/1s4935rMC78MS39cLgRIQiCzyClQKeYiw/view?usp=drivesdk

**Expected behavior**
Great people should spawn or some explanation why they aren't should be provided.

**Screenshots**
![Screenshot_20230119_141515_Unciv](https://user-images.githubusercontent.com/6773629/213446452-5784c3e6-ad56-4ce7-9390-0907a94a49a3.jpg)
![Screenshot_20230119_141550_Unciv](https://user-images.githubusercontent.com/6773629/213446474-fe2122cd-77a6-4256-9679-bb8433895a73.jpg)

**Comment by alexban011** [comment]
we need access to the file. Just drag and drop it in here in a comment and github should upload it as a file

**Comment by N1cc3** [comment]
Sorry messed up the access rights, now the file is accessible!

**Comment by yairm210** [comment]
Same as #8405
