### ISSUE TITLE
Game doesn't align popups correctly after rotating the screen

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#8443]
**Platform**
Android 13

**Version**
Google Play, version 4.3.12

**Describe the bug**
If the game has been rotated to Portrait mode and then to landscape, popups like Exit game are not positioned correctly, sometimes even completely outside the screen.

**To Reproduce**
1. Rotate to Portrait mode
2. Rotate back to Landscape mode
3. Press Back button
4. The popup is in the left upper corner or even out of the screen.

**Expected behavior**
Popups are in the middle of the screen

**Additional context**
1. Maybe it has already been reported, then sorry
2. Happens on both small and large resolutions
3. Happens also the other way around, when turning from landscape to portrait. Then the popups are in the bottom right corner.

**Comment by yairm210** [comment]
Can you attach a game where this happens?

**Comment by yairm210** [comment]
I've tried and failed to replicate this
Please tell me which screen you're seeing this in

**Comment by jahodovykolac** [comment]
![Screenshot_20230123_075046_Unciv](https://user-images.githubusercontent.com/79529669/213980939-2d1d5247-b393-41d4-abac-8ddb7f6a6566.jpg)

In this screenshot, I opened the game in portrait mode, but then rotated to landscape. I opened the exit pop up, which is the blue line in top left.
It also gets fixed after switching to another app and then back, without rotating the screen.

**Comment by yairm210** [comment]
What is the popup though?

**Comment by yairm210** [comment]
Because I tried this with the options menu and it doesn't happen

**Comment by jahodovykolac** [comment]
It is the Exit popup. It also happens with the options. They are visible, but heavily misaligned.

**Comment by jahodovykolac** [comment]
I would also like to say that it isn't an issue with my phone, it was happening already on my previous one.

**Comment by CrispyXYZ** [comment]
This also happens on my phone (Android 10 and 7.1). I've noticed that it always happens on all popups, after rotating in almost all screens, except `WorldScreen`.

**Comment by CrispyXYZ** [comment]
I tried adding a button to manually reload screen with `game.replaceCurrentScreen(MainMenuScreen())`, then it works.

https://user-images.githubusercontent.com/64761703/215324701-3c42d122-6ced-4a67-94fa-9a9a8374350f.mp4
