### ISSUE TITLE
Can't build Courthouse after stopping razing city

### ISSUE THREAD

**Issue by trexxet** [yairm210/Unciv#8456]
**Platform**
Android 11

**Version**
4.4.4 (801)

**Describe the bug**
Capture a city, let it burn for 1 turn, stop razing it and see no Courthourse to build.

Can't add save file (the game crashes when I try to save to custom location; the phone dies when I try to paste the text save; gonna open issues for these).

**Additional context**
Mods in save:
5Hex Tileset
Ancient Civilizations
Brave New World
Civ 5 - G&K
Civ V - Vanilla
Community Maps
Future Expansion
Medieval Civilizations

**Comment by yairm210** [comment]
Haven't been able to replicate this in base game
And how can you have BNW and vanilla and G&K in the same one? They're all base rulesets!
Checked the code and razing does nothing except for activate 'is razing' which when you disable disables properly, so I can't make any logical sense of what you're describing

**Comment by trexxet** [comment]
Whoops, BNW just hangs in mods list - I forgot to turn it on and using the G&K ruleset.
Haven't checked the code, but I suppose that building courthouse becomes avaliable if city is annexed and not razed. So if I choose to raze the city and then stop it, there are no courthouse to build. Also, this may be some mod's issue (maybe FE).

**Comment by yairm210** [comment]
No, whether a city is being razed or not does not matter to whether you can can build a courthouse
Only whether it's annexed or not

And clicking 'raze' annexes
Which us what makes this nature very little sense unless it's a mod thing

**Comment by yairm210** [comment]
Listen, I double-checked the code and what you're describing seems impossible
I'm not sure what you actually encountered, but without a save file, there's no way I can recreate this
Closing this as "cannot reproduce" but if you manage to recreate this please tell me and we'll reopen it
