### ISSUE TITLE
Game crashes when saving to custom location

### ISSUE THREAD

**Issue by trexxet** [yairm210/Unciv#8457]
**Platform**
Android 11, API 30

**Version**
4.4.4 (801)

**Describe the bug**
`Permission denied: opening provider com.android.providers.downloads.DownloadStorageProvider from ..... requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs`

**Additional context**
Can't copy the full crash log - my phone dies when I try to paste it anywhere (seems like the GBoard tries to show a quick paste button with large text...)

**Comment by trexxet** [comment]
Seems related to #7177; [this](https://github.com/yairm210/Unciv/issues/7177#issuecomment-1368872602) log looks the same.

**Comment by yairm210** [comment]
Solved in 04cb4bd2
Thanks for the push to try this once again :)
