### ISSUE TITLE
Allied City-States producing way too much science

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8461]
Windows 10 64-bit, version 4.4.5

Using DeCiv Redux mod, but I believe that the error is in the base game.

When selecting the "Educated Elite" policy with the `"Allied City-States provide [Science] equal to [25]% of what they produce for themselves"` unique, city-states start providing too much science. Every time you open up the Overview menu to see the science, the amount of science provided by the city-states increases, rising into the billions.
[Atlas_-_213_turns.txt](https://github.com/yairm210/Unciv/files/10486333/Atlas_-_213_turns.txt)

**Comment by SpacedOutChicken** [comment]
Hat tip to Silent S on Discord for bringing this to my attention.

**Comment by Green-Sky** [comment]
I just had the same issue.

[china_science_bug.txt](https://github.com/yairm210/Unciv/files/10493872/china_science_bug.txt)
