### ISSUE TITLE
Culture overflow (from City-States?)

### ISSUE THREAD

**Issue by omega-particle** [yairm210/Unciv#8462]
**Platform**
Android 12
 
**Version**
Google play store 4.4.4 build 801.

**Describe the bug**
I'm at mid-late game, and open up my save file, and s3e that I have +2.147B culture, which seems to be coming from "City-States" as opposed to CityState which is giving me 26 culture. However, on my policies screen, I'm at _negative_2B culture per turn. 

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

I tried pasting in but it's too big; GitHub doesn't accept the comment. I don't seem to be able to attach the save file (JSON).

**Expected behaviour**
I should have a few thousand culture per turn, and be able to pick new policies.

**Screenshots**
![Screenshot_20230124-061651](https://user-images.githubusercontent.com/123441790/214224983-237adfa3-fbfe-4604-9f9d-699226372105.png)
![Screenshot_20230123-221417](https://user-images.githubusercontent.com/123441790/214225007-9079e1aa-f4fb-4c63-a7c2-e027c445b15c.png)

**Additional context**

**Comment by omega-particle** [comment]
![Screenshot_20230124-064634](https://user-images.githubusercontent.com/123441790/214228857-fb511e18-e709-451c-9563-75be321f005a.png)

**Comment by yairm210** [comment]
Same as #8461
Please attach a save file
