### ISSUE TITLE
Crash when using blacklist nations feature w/ Epic of Fantasy mod

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#8465]
**Platforms:** Win10x64 and Android 13

**Version:** 4.4.5, installedfrom GitHub.

**Description:** This is related to the blacklist nations from the random pool feature added by @alexban011 in #8430. Only allowing mod nations in the random pool results in a crash. Doing the opposite - blacklisting all base game nations - seems to work.

**Note:** crash seems limited to the `Epic of Fantasy` mod. I tried `Medieval Civilizations` and `Latin American_Civs` and they worked without crashing.

**To Reproduce:**
1.  Open the `Start New Game` screen
2. Enable the extension mod `Epic of Fantasy` that adds new nations
3. Enable the `Random nations pool` option and only select nations from the mod
4. Choose `Random` as the nation for one or more players
5. Click `Start game!`
6. Unciv will crash

Crash report: [Crash_only_mod_civs_allowed.txt](https://github.com/yairm210/Unciv/files/10492435/Crash_only_mod_civs_allowed.txt)

**Comment by letstalkaboutdune** [comment]
Other feedback on this feature:

1. When selecting the `Random nations pool` option for the first time, the entire `Advanced Settings` section collapses. This makes it difficult to use the feature or know if it's working.
2. The settings of `Random nations pool` are not preserved when in a game and selecting the `Start New Game` option, like other settings are.
3. Some column labeling would be very helpful, with some examples below.

In the "positive definition" case of only allowing certain nations to the pool:
![Random_pool_allowed](https://user-images.githubusercontent.com/56904240/214377391-a2db9466-bf3c-4266-b52f-b4852e234301.png)

In the "negative definition" case of only banning certain nations from the pool:
![Random_pool_banned](https://user-images.githubusercontent.com/56904240/214377420-8b36f5d1-d632-48fc-86ff-8af8ac85ae8e.png)

**Comment by alexban011** [comment]
> When selecting the Random nations pool option for the first time, the entire Advanced Settings

This happens because I'm updating that part of the screen. This can be fixed

**Comment by letstalkaboutdune** [comment]
> Yep again, labels and maybe just get rid of the blacklist option and add a button in the popup to toggle between all civs. Might be more intuitive to the users. So the lables would be: `available civs` and `banned civs` and the user would be able to toggle all at once with a button

I agree that removing the separate "blacklist" radio button and having the one picker window handle both the banning and allowing is a good idea. With clear labeling of each column, and the button to either ban all or allow all, as you've said. Much more elegant and easy to understand!

**Comment by yairm210** [comment]
Is this still crashing? If so that's a problem we need to fix
