### ISSUE TITLE
Feature request: better and unique AI

### ISSUE THREAD

**Issue by Wanzittt** [yairm210/Unciv#8466]
In the CIV,leaders are characteristic.For example,Gandhi will more like to keep peace.But we just use "Neutral, Cultural, Diplomatic, Domination or Scientific".

**Describe the solution you'd like**
I think we should have more things to ai set.Such as:
Austria :
1.when you attack city-state that they protect or become their friends,they will attack you.(if your and their enemy's force is lower than their force's 200%)
2.More willing to protect city-state(Close-range priority) and be friends(like complete their task) .And will choose belief that about city-state.(like papal  primacy)
(I wanted to write more, but I think I'd better give some typical examples.)
Korea: will sign research agreements with country which scientific output is higher than theirs 80%
America: will like to control more oil.(like war)
English: will discover tech about sea frist.(my mean is every tech will have a point,and ai will discover tech that have higher point.)
Mongolia: 
1.will attack nations that force is lower than theirs 75% and is closest.
2.will try to have highest force

**Describe alternatives you've considered**

**Additional context**

**Comment by Wanzittt** [comment]
errr

**Comment by Wanzittt** [comment]
errr...I seem to have accidentally pressed the release button.

**Comment by Wanzittt** [comment]
let me write it there.
Also,it will be able to use in mod.
maybe we need a AIset.json file?
we need to have something like uniques:
will war
must war(it can use on Mongolia）
will sign research argeement
will sign open borders argeement
(can set tect/policy point,like
"tect/policy name": [amount]     )
will choose [belief] frist
More willing to build [building name]

Condition:
<when enemy's force/[stat] is higher/lower than ours [amount]%>
<when nation's relationship is higher/lower [amount]>
<if enemy is city-state>


(It may not be perfect, but I can only think of so much now.)

**Comment by yairm210** [comment]
It sounds like you want a whole bunch of unique options for customizing AI behavior.
That's a modding request and therefore belongs to #3242 
Also, I am not planning on doing this
