### ISSUE TITLE
Feature request: Multiplayer Game

### ISSUE THREAD

**Issue by tenumn** [yairm210/Unciv#8476]
The operation of multiplayer game is complicated, why not make display server online room and LAN game

**Comment by saownj** [comment]
需要局域网联机或本机联机，这样有很多优点

**Comment by saownj** [comment]
建议加入团队模式，

**Comment by saownj** [comment]
城市的防御，有待改进，建议围墙需要建造并且可以升级，

**Comment by tenumn** [comment]
> 需要局域网联机或本机联机，这样有很多优点

建议说英语，他们未必能看懂中文。

**Comment by yairm210** [comment]
This request is way out of scope for this project, so the answer is no

**Comment by tenumn** [comment]
> This request is way out of scope for this project, so the answer is no

But multiplayer games are really troublesome.

**Comment by yairm210** [comment]
I understand that
But the amount of work required to do what you want is  simply not feasible

**Comment by tenumn** [comment]
> I understand that But the amount of work required to do what you want is simply not feasible

Is there no way to improve it?

**Comment by yairm210** [comment]
What you're suggesting *here* is not an improvement. It's to completely remake the entire thing from scratch.
If you have a suggestion for how to improve the existing system I'd like to hear it
