### ISSUE TITLE
Hills appearing on terrain types that shouldn't allow hills

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8477]
Windows 10, itch.io version 4.4.6

In DeCiv Redux, Hill tiles are allowed to appear on specified terrain types, and Fissure tiles are not included among them. In spite of this, when you generate a map, you can still see Hill tiles forming on top of Fissure tiles. How can we prevent this?

**Comment by RealBamboolord** [comment]
The problem is that Hill/mountain distribution is done prior to biome distributions

**Comment by RealBamboolord** [comment]
In map generation

**Comment by RealBamboolord** [comment]
So we need a function in code that would remove unwanted hills after biome generation

**Comment by RealBamboolord** [comment]
So it's rather a feature request than a bug

**Comment by SpacedOutChicken** [comment]
I'll close the bug report, then, and repost this as a feature request #8480.
