### ISSUE TITLE
Feature request: Password validation in Unciv 

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#8482]
Can Unciv send some kind of password Header so that I can do validation for it.

And Users can set passwords per hostname (like uncivserver.xyz). Cause it will be bad if the password of one server gets sent to another one. and people log that.

Suggest thread in Discord: https://canary.discord.com/channels/586194543280390151/1068889614900809768/1068889614900809768

**Comment by yairm210** [comment]
How do you see this working from a technical perspective?
When does the server get the password for each user?

**Comment by touhidurrr** [comment]
> How do you see this working from a technical perspective? When does the server get the password for each user?

The workflow will be like this:
From Client side There will be an optional field to add Password. After enabling that, the client will just send the password in a password header. passwords will be saved in a map where hostname is the keyword.

On server side. I will parse game data and check of the current player id has any password associated with them. Of no then ignore. If yes than validate password header.

And users can set passwords with UncivGames Democracy Bot.

**Comment by touhidurrr** [comment]
@yairm210 did you forget about this

**Comment by yairm210** [comment]
No, but also this isn't high on my list of priorities
