### ISSUE TITLE
Feature request: Tutorials.json for mods

### ISSUE THREAD

**Issue by IAmMrX1** [yairm210/Unciv#8500]
Now,it's hard to write down something (like info,tutorial) in mods;Maybe we should allow editing the Tutorials.json
i noticed that some tutorials triggered with players'actions;it may be hard,but i think editing the tutorials in the Civilopedia is easy to implement

And:
I had tried to modify the _translation file_ and  _Civilopedia test_,the result of them were not so good.

**Comment by yairm210** [comment]
You can change the tutorials.json in mods? What exactly is the problem you're encountering?

**Comment by yairm210** [comment]
Closing because I don't see a problem and no answer was forthcoming
If there is still a problem we can reopen
