### ISSUE TITLE
Citizen icons changing colors when units are selected

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#8503]
**Platform**
Windows x64 and Android 13

**Version**
GitHub, 4.4.7

**Describe the bug**
Citizen / worked tile icons change color to a bright green when units are selected.

**To Reproduce**
1. Start or join a game
2. Select any unit
3. Observe the citizen icons changing color

Before:
![1](https://user-images.githubusercontent.com/56904240/215547926-035e6a95-fc77-44a0-a938-268032a02a86.png)

After:
![2](https://user-images.githubusercontent.com/56904240/215547928-5c18c298-6cea-4f3d-b0a3-d78ecc0d35f3.png)

**Comment by yairm210** [comment]
@vegeta1k95 sounds like a side effect of your change?

**Comment by Gualdimar** [comment]
@yairm210 I confirm on the clean 4.4.7 jar version:
![3_1](https://user-images.githubusercontent.com/1225948/215554584-fa9ba7eb-515c-4d07-ad87-bf4e293ef0f7.jpg)
![3_2](https://user-images.githubusercontent.com/1225948/215554599-b9f71116-5af7-4300-97a9-f70f082f6ee8.jpg)

but not when choosing a worker:
![3_3](https://user-images.githubusercontent.com/1225948/215554714-f1ce224e-5293-4c89-b249-8e1552f631cc.jpg)

**Comment by vegeta1k95** [comment]
Fix when I come home
