### ISSUE TITLE
TECHNOLOGY WITH PATRONAGE

### ISSUE THREAD

**Issue by Yennykates** [yairm210/Unciv#8507]
Android phone. Been using same one for over a year of play.

Version 4.4.5 from playstore

When completing patronage's scholasticism, technology produced jumps around wildly when ending turns. Technology shown isn't what's produced either, so something that shows 4 turns to develope might actually take 10...or just 1

**To Reproduce**
1. Select scholasticism as policy.
2. Ally with multiple city states, at least 3.
3. Watch technology production.

![Screenshot_2023-01-30-19-14-46-15_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/124009690/215634277-ada16df5-d0ec-48c1-9b03-72a7ffc60fa1.jpg)

**Additional context**
This last game, it took four turns with three city states. In others, its happened immediately. Not sure if it's a time frame or tech level that causes it. Screenshot attached is renaissance.

**Comment by OptimizedForDensity** [comment]
This was fixed in version 4.4.6 which was released a few days ago (changelog with the bug fix here https://github.com/yairm210/Unciv/releases/tag/4.4.6) so be sure to update your app.

**Comment by Yennykates** [comment]
Play store only has 4.4.5. is there another place I should go to?

![Screenshot_2023-01-31-02-24-53-07_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/124009690/215706961-371800b3-2f8a-4ceb-97ad-7fb13ae16a32.jpg)

**Comment by OptimizedForDensity** [comment]
Play Store rolls out the update to people gradually so sometimes you get the update the day it's released and other times you get it a few days later. You can download the .apk file from the releases page here https://github.com/yairm210/Unciv/releases which will always have the latest copy.
