### ISSUE TITLE
Changing tileset or unitset doesn't take effect until exiting and reopening the app.

### ISSUE THREAD

**Issue by ryg-git** [yairm210/Unciv#8515]
**Platform**
Operating system type, major version, architecture (64/32 bit).

Android, 13, Arm 64.

**Version**
Where you got the game and the exact version number.

I built the game from source code, Version 4.4.7.

**Describe the bug**

When user changes the `Tileset` or `Unitset` from main menu the changes are reflected on main menu screen (in case of tile set) but they do not affect the world screen, user has to exit the app and reopen to see the changes on world screen. 

**To Reproduce**

1. Go to `Options` button in main menu.
2. Go to `Display` section of the `Options`.
3. Change the `Tileset` and/or `Unitset`.
4. Go to world screen/resume the game.
5. Check that the `Tileset` and/or `Unitset` is not changed.

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
`Tileset` and `Unitset` should change in game when user changes them in `Options` menu.

**Screenshots**

**Additional context**

**Comment by Gualdimar** [comment]
a small addition:
if you open Options from the World screen, everything works as expected without restarting.
but if you from the World screen go to the Main menu and then to Options you need to reload the save file to see the changes

my game version: Github jar 4.4.7 on Windows
