### ISSUE TITLE
UI issue: new "at war" indicator not compatible with some nation colors, plus interaction with unit icon opacity

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#8521]
The new indication of enemy units at war is not suitable for all nation color combinations. For example, the black and red of Barbarians, the blue and red of Korea, or the black and reddish/orange of some city-states make the glowing red stroke hard to see.

In this example, it's clear to see I'm at war with China, but not so much with Lhasa:
![example1](https://user-images.githubusercontent.com/56904240/215841605-1a39b133-832f-4501-955f-361f2436a8a8.jpg)

In this example, the "at war" indication blends into the Barbarian icon:
![example2](https://user-images.githubusercontent.com/56904240/215841794-fd11cb4f-de15-4f3c-8642-9f42a13c2c39.jpg)

It also looks like the "at war" indicator is a solid, filled object. That means if unit icon opacity < 100% is used, the nation colors of the icon will blend with the red tint of the war indicator, resulting in color confusion.
![opacity_example](https://user-images.githubusercontent.com/56904240/215842089-cb3b5efb-3311-4842-a41c-753533ba98c0.png)

The previous solution of placing a red circle on tiles containing enemies was a clean and option-agnostic implementation. The nation colors and unit icon opacity don't matter here.
![old_version](https://user-images.githubusercontent.com/56904240/215847421-0ebb69cb-785c-4a87-80ba-29ed0b309010.png)

If the current implementation of adding a red stroke+glow to the unit icons must be kept, then I propose adding an additional stroke of white before the red, in order to provide high contrast and better visibility. Please see below for a comparison. **Note:** the "at war" indicator should also be changed from a solid/filled object to an outline only to prevent blending with the unit icon when at < 100% opacity.

![proposal](https://user-images.githubusercontent.com/56904240/215854559-a961de82-5d70-4b13-a7e8-9ee8593b2f35.png)

**Comment by letstalkaboutdune** [comment]
Proposal with red unit sprite outlines instead of changes to the unit icon:

![proposal_outlines](https://user-images.githubusercontent.com/56904240/215883218-32b61fec-18a7-4c54-aca9-5b4f44ebb593.png)

**Comment by yairm210** [comment]
This is still a problem

**Comment by AdityaMH** [comment]
> Concept with red unit sprite outlines instead of changes to the unit icon. I'm not calling it a "proposal" because I don't think it's an improvement.
> 
> ![proposal_outlines](https://user-images.githubusercontent.com/56904240/215883218-32b61fec-18a7-4c54-aca9-5b4f44ebb593.png)

I will choose this, since some player turn off unit icon.

**Comment by vegeta1k95** [comment]
This was settled with the #8629. So can close for now
