### ISSUE TITLE
"Unbuildable <if [buildingFilter] is constructed>" not working

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8539]
I tried adding "<if [buildingFilter] is constructed>" as a conditional to the "Unbuildable" unique. It didn't work; even if the named building is built, the targeted building or unique is still buildable.

I've attached a small mod which includes a building with a "Unbuildable <if [Monument] is constructed>" unique. Build a Monument and you'll see that you can still build the modded building.
[UnbuildableBeingBuilt.zip](https://github.com/yairm210/Unciv/files/10565194/UnbuildableBeingBuilt.zip)

**Comment by zhan313** [comment]
Theres unique only available in cities without.... 
No need to make another unique with same effect

**Comment by SpacedOutChicken** [comment]
That effect isn't empire-wide. I want an effect such that building one
building anywhere prevents the construction of another building everywhere.

**Comment by SpacedOutChicken** [comment]
Before I tried using this unique, Iwas going to request a new conditional: "Only available <if [buildingFilter] is not constructed>". I had hoped that using this existing unique would give the same effect.

**Comment by zhan313** [comment]
> That effect isn't empire-wide. I want an effect such that building one building anywhere prevents the construction of another building everywhere.

Understandable
