### ISSUE TITLE
no description of unavailable promotions

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#854]
hmmm... which one should I choose??? 🙈

**Comment by yairm210** [comment]
Sorry what
Printscreen please

**Comment by Am-per-Sand** [comment]
Use your imagination:

1. gather 10xp
1. Press Promote
1. You will have the promotion screen with the choice of 2-3 buttons lit up among other ones dimmed
1. If you have fingers precise enough you can read at the bottom descriptions of the lit up ones
1. Dimmed buttons are off so no decription to display

**Comment by DaneelGavin** [comment]
Its not a bug per-se, at the moment promotions need to be available to read description and requirements. Need to be able to see requirements of unavailable promo's to know how to proceed.

Kinda like national wonders which require all cities have x building to be selected. On attempting to select,  some info would help. (Popup ....To build Circus maximus you require colosseum at : Rome, Antium.)

**Comment by Am-per-Sand** [comment]
> On attempting to select, some info would help. (Popup ....To build Circus maximus you require colosseum at : Rome, Antium.)

Offtop: The Factory fixed this one (thnx goodness they didnot include any city lists... :flushed:)

**Comment by DaneelGavin** [comment]
Yeah, had probs yesterday thanks to lack of coal. Was fun to fix

**Comment by yairm210** [comment]
No, I agree with @Am-per-Sand - there shouldn't be any knowledge that is hidden from the player if it's important to the decision-making process
