### ISSUE TITLE
Ballista incapable of ranged?

### ISSUE THREAD

**Issue by DaneelGavin** [yairm210/UnCiv#855]
After issuing set up order, ballista cant hit units 2 tiles away..

Save file follows, 
H4sIAAAAAAAAAN1dW3PbOLL+Kzr7TKbEq0i9OZ7N5VQyccWek91K5YGREIs1EqmiqCQel//7giRANIEG2ZSztVvnZYZWQFwajUb39zXAx03+Pd/nf2V1Xhan9efHTV7nTDw8XPPf6uq86f7x8es539cv+X+2eXHPy9xk+2zDnNdVVmTVg/O+LM4HVtTOy6yqss2fJ+duxxY3D1V2yLfdH68rltWLd/n9rt6V5xNzwOObrLjn9S5eZ9WWFV35D7yePXPu2OG4bwp/rXhDX5zNuap4Q7B7609l9efiZZnVJycvbqryvmKnkzaAuyqv2IGt/aWjiq/98OnJaYZ7Wzd/Pj457OcxK05NrY+b874+V+y2Liu2XYfhk7MvN6201o8/177zsHaDJ6fIeK0fywNzjuXxvBf//q0st+JFL/HgP3mRczqyTZ7t81Pb5JNT5/tW7j/XQVOp/+TIx7B9lE3xR0/71VOPoXoN/AoqAzWAx66A2z7H/FnU1BcKVd2hM/zVU4++qjDq3o5UH6KnL84PLnS2vRMjxarEhwZ67msFwNB8fWhqPANJ9n3tO9h3WfWV/0FYAYbqA33mM1+wHSvupf7ievsmu8+zxW153OXZiOaCxdMugrW3ih347jpJ6GocDNU4EnJq1fiqqPPzwarI3lCRgxFFbqtdtWKNlIRjNSmhNj9J+7hSZUPt15UqG6t6QWUr1QSoIVI1hOoRNAw6GarHxFDZQZfjqd6DLoOBBGiXQY9AP/GBiC4TdbTXTams1+W+PJ3OJ6isYxp6xxpzXtZ1triqDg92JZUt8UWkvbP2g0S2v/aWZEWN46Gidis6FZp6fT5kVou7igZ6urTqaT8xXeXi2VfP8GfZ/qP4nywJn/n4VNn2D/WjJ2e8n3jXU0rgdobbQ/TONXoha07MppFW+vHgHe8bvlCnPmX7/QlXn5f8n7jQR4zbO3bfFPSdWz7q7emQFetw5cj3uOZLh2LtR2TV4SZux7J9veP7ezRQohRu2p+y046PidvqgSKB53jEwsmq+GOiVi1Xtn47StXPKdikltqLATLloHyCtpPqTQaD5r/wOjt37rrZORqZ8L+//977Ktv8uC8P2eZh/Xh1YFW+ydaP4rc637wvt/m3nFV8zL+xzT6rWnF8+Paqylmx5VI7rv34ReT8k2XV6cO3G8Z9wXWcvuA2Ki++7c+s4H97TlnvWHUtmhXNPLXztm/mCWh4OBxkZwzdRBlGtxvZSo1SPDaarKxvZyRdYIjdWEkK1AdKgAKgG9ATgytPTa1YXSlYwx5Yqe2z6pkYRqT1xtgBgNkHZV1QOFFtd0JJYOOpklACBKCGCkUUgyEksMq0H2Wi6otgiQj0K1RT0dXohX0fgSsHhNO8FoLuQRF3JaBuR7r2g3eA99mNI4LSiEG9qeqEGp5wAgOlUF4/Clgd2JiBCR5s2AkoHqkOgkc3GY5mINBYDThWPZVW3dcULoajhLuJ56lhrNTgkn5EsHJPjVNpnzI7pistthpfdSpU1YG5h9rR1SJCC88wajFYaEBXPFV3oOYJxAjdlAT9LMDOCp9O9RL4+ivVSyByqG7ATwRTCHUsVL0BCqS0Rvx71M9B/5ZaAapzZkgFPJAEtA1HD4qIHVxJFkRDYGkG4MWBGwOcgXZIgeo9GKgUNeiKiPSkji6HEyJ6PfCL4B8r1dOlalWtkHaK4Gihugb9Y6AmAIhddg3IUzx3dYmp94EAhTBDIMxGNz0wYDOC9sUgQJVq6LGaUdACbN9TMojUFAVqQsCjB8L1wVgG3h50QKTUAyD1qB9SK1/gNvhK14HUQNg1rE5MhpoStTP6akqg0gn9D0EtcFeU1YN4CYw46fudaD0EuAcIreBsprAVAFqkSvJyEoRkQBdXUC2U5gIZ+mCMA/BjpXoKX+8LDiJQ0YKnZCfFqH5xob4OUBo31MUpao2BMFagE62eekBlPTX9IJJOVO8NMAXYrq6ZFDYD7Dh4FM24od7FgXLBXRQ4IB7QcNBd0EegrbCOFDakrAiwJ6C6VM3dCtQRgf5BmUM3JgYCEO8mQP4pUDrZqLKTSugA3wAAANBzgIf5oJkUNCOnWa13N9TFAjxOgIKARQQMsZDQCgwHvOjC3xM4nylUhlB1ZgU6nOiaDx7dJiK+L/dbHgAu2wdWXN3zuOGRh6FfWfXh22v1m+ec2gjwTXY85gWPNtdhunR4ZFic3rFv9auyuu6i1P6dxoDdNyHSDSuPe7Z+bP94zQpWZfubMi943JfKEtWpLMRvMuJc+6uud3HsHKtyKwLfhPdkk3dhEJ+3Y/sSb/539rN+DVrgY+Ry2vXd5UMuyprHXpselc+6Gh95GMYLbMrDi3PBQ7kX+/I+37yAGP6LdyLSvWpf6QPfQbzKo/xNycOv9WPGxXXfiLrmnVr/7bMKh78sdtlpcV+VP4r/+Rufil/VBaGMwy5Uqgt/L9jhYdHE+IvPv7Mfi3/yqLjrS1bX2YZHyIvyXC0+X++yKi/rxVW14QHml1/aRZ/exZtdvs+2bN9AsFg3JYrx6zvYRviWHl4VC9Z28vN1VmdHrqYTffviHPfZA6vuHo5s/eZ8yBo4ZJ9vGi7oMduWx5ptb+QPn68q/lq5qbLNg/OO3TfQyMG5q7Jt3nb2fVlkfFYenGv+91+saLAC5yM7VuzEl107jobLYVX98MWRK/hKayQWy/harLFwyW2SWE//l2/4vz00+E/NNrv1Y/Pf09seX1o/3uweTvnmtPa9VVfm9JE33vSKbdef37M62y+us1PNdb0hmrgQ7xtgVMFSznW2Z8U2q5wPx5rX5LzP6h1rgZHmmRuBFkk9HPlMOu/zoqno7w2BxVjVPL+syuIvtmhopubP24xPbdfW4tOOsb3T6S2vozVGXJA3ZV03P1wV+YH37s359DUrtg22VuVtP6/uq1xYHOctr76vvNHB8lQed1yc7VjvSjna9WchCee2blp9fS6O5Y8tq5xrPho+i9UDV6LvnTzfZ0V2z6oW43qUSNHLrPrKV1pWnKYMr28YXn/pY5Z1aESfBrbPB3o3Md9wRoFsEBnoIrUOWXCfcpnc7fLTHd841lwrmHMxLuoIotQgccYZTcFWTtOZUaiTp2svpbNBXgqg0nQAlTb7VguTSktsA0nH+EzhSUMPAjgBEEdwoS/q6861B6EBEMLI6Bt3HXwEWYWFfLNDoBnpfTz9clicPLu8hxfN5HIwkwLUaSfzZXnS8W5AnPg+/JdwZGIVUKRi5LiP94QL2fuUyndU8IAKN/3+N/EGMm0xUjoArTaz9IuXroWzLasTa/bIaSosiB1ZmkuWPpNqIqPhRMqIup1J6H1YGVv4D/7YOvXVUlOwC0QI/OEjWCNg8YHFCpAjEP4BaAmbZb3qECEywp7IEIwC5DIabsNCZAy4itXSecnqirs9WxvB4Qbei4i7AsdmarYfztV1t0W40ZL//imr+Dzz7YNvIDzy7yphW/7zh+IPXshbvUhW3Dp922f3XEHORb3l3nRHp/Dtbtt1gxcYcCRN91GCJBgsNwBWKkpA8RoA90yULGHcCQ3fsg/3EJ4D8E7zeRPAgHRWd9nH2wCE9YDpVaF3rBrWWY9JskSxHNFQWICYSYEqL0EX4R4FRgG6DoBbWXqpKmxfhNuRD0yh2s8U/6GM5iyuQy0USJoAmmYOGzPCj7hTBEmkVrQCrCPVG6U2ajsAdmQFtHKpepuoWlOolUslHSOxAxItAyoEPAOqA2dI2tbV8GPgcUg2X0+YIrAZkDUZUCgKU1NbqM6/TNIskBWx8CZRPxYgNoPcgPTHgEhBtl3ImkwxLJAzCYZSBToV9WURigNSH5Du0Hw3Za8MDkQkQJi8C2BYcAoGZkuY7AkkR3TOJHiCBImFFIG4PVTfCKrLTMpE03iIwiOUSM+YDPZuQK4MGA5IoAxokTnMB4FywWiWnwTKxAPtIsyJWMYwN2aQgWPQJANCxRm4SWAFjVImwE/Skm6koEHGCLQeAiEGBDMkfpRREH1SSgwEbvAjkGFJhuKG/AIsnKqacdLkYQiQg50ags80/qQPGy8hTeRMaV7p0EBDvYv76pUDA+yaCl0gcWKyJZMUCaQ/gFuscxxw1QDwH6poBHoPjIfBZqTDRkBmCHD6RD/VfAHyZy4PoaTft6wUX1vC0O2Tnla7DwKjBp0xZZPSXnFVdo3qtOozcEI8xRyqvV3Op6f3AM4+sOtKExThpLw14CFCJ9JV+zpUFOCzgiSEgccZgMGDDoFtdIhTyM4p8UCmC9gvD+gjr06yK6k3H+QLouU0fRIEGH8i6ZF4jB1Jlk9jWPSbsigrByLSPP6q8rJaXJdbplBpO9IcaUhzENiBx28VY3cNvMiV0wCdBxjBKnEkCO01aawTIPRs7LlFFb5mmz8XH/MGwsBAaD74ZpZmoNEG+CxR6SkQ2o48o2Brj6vctLRDl494z8PfGx6GH1jdRus8bP/WNvawvt7l7Fud5YWza8iJ3yUZ0rz3xTlkx1c8TG7D531e13u2OP1ofv3IJ/98apYu/6PlNppyTlEqVLsDiKRuNNROoxNeB4y8z47rx+bhHVcvHoR/zU6sTW3Oi/V1yaeOa+Yp76EZsbL40oIFP2xYS6fIgo2l0oqYdbmdYzxRVc+b6gW5WPPiNCwpKWGt6Jt8v3c67ikr/ijyev3IhdU8XI3SVbzQi47QenFbN+omqCpBcmXnuoVfykJm2jY4T+WUPwo538eqPJQCMOO9yg/8h++shc24MrNB76XF5CutPFfcZjQ2aVo6HibF9w0U0+jSsOgSlw9Sa7f7RwShi/hWK/gbXyNVjdTpExqXSbBaybszX6+ZVrR3quuu1CtuVxsTx+0sO9XTbXXbSgDE/iHfT74mICVSuUkV7/yJvv1PO24bTwRtl9Hd5EqTYUrfxKv8tNPeel3xFbDnFnGgpDe8qsYODjrb+AB9Va2R1nuLLHYvIs5+gloYdPwi9uz78pJb3yI76arwv+fifs8mGxZ+x7TKiDh/esyJ0E3MHA2WkHCQ+oHwuqZ1UCajYLWPGhoZ/PbNNbvc5Gh6nG9Mi6wTTzI6Apqk2DIRolqVeFA2xMp2XYWCasbTMIzdEUtYg4TfxoZujsdDh4PZOxGITgtThqazjJXroZqNrnjg7L3KqoOxQAaNc8cqq7u8o7vyLZBkMD0SgWkTh+x5UwbSfLMLa4nLKJ0u2GdvjgifsPgIuzwihRQVF65zBKkGhB3BJqoxTTIMhtGXd9mfbLi4Yto8mXpgil8faBe7zzNYkjcZVzeb9TLMHL6vGmurh02Gi2u6txJ6mSEVhcbMNOWBvk/RBNrRG6T1RdDwgFbbCiuGK2oPFI7tv5hDK5Gz/r32QPS0psRUB0IQXdQQyfCaLOOVXAjFZcYcr46cJRRcYRsvPlfmysEcKpoWmRbKEn0aW65l8yRszYK4pbnY8MWUOMU+bnuxHkdowDwSPhFiCFdAzLPsjCvIxZnbjI/pl+E1Dxyy3x6Y4fej+oytsoAq2qRzgWlKSHFuZEo4aV+fhF0kvk+zAoKS14T2PquosSH/RaS6Gq4FFpVVZbZt0oLOp/VH/jgtnBWKAqjOHPJ9XmfVQ4fodOflRS6wwGBk6gyEYf5x05okI0CgicIWFxlTaNs+SWY/wtUCnwfDxZR0zZiLaaymFNMc62IheqLmWrGIxWgZ3W6lj6Sv831ZbhfHdv+hq74Zb6EG0sSHrvbnQ16cD9MSWFIRBQoK2mUZ0YynMTRkc44nfE0TpTAl/yE75dOeMbrTWvxEY4SIS08KqeWR8cuwoJDSFZUGM8ch1qOYOSgKYYHKJLa50bKLN2DTasrmtiIG4D4tZnXRAMESey41z5xvDDVh3oWXNS+eEgD03IAxxCKU2ahUdInPKZPtBjvE/A1aXqJAKBniLpYF7yHspgkRXEtQJ8KKMy2n5pG4Bwe6ZbjN999ZRdnldCDgjyorcmO7QV6lLF7Ms7bBTQSb7duRVdNHImIjFr9S5rjpfuXEmGlB3gqnu+asRpmU1vfvhmXVnuaQiHRBEvDtY1vTPEl6unJ+yg3YYhrJDPUJIdEILk5a4XKJzM2sQZzHDZWV5JsOKVPi8vBwV97WckQ3KrrpIijvClMIO194MVUq0nWmxywzti5gND3MnuBjmbSQFoaPwmm7Mu13Ns2JEr4jUchqvo+CEv4WipoyXf19EfOgHS9AN3/caAVYn237xIRLY4FbKJ5mTPZCvJDoN3jELBa0GJV0V9mucxVyRetdnyOqrdkLwyexn1I8A1xNlWCGaTsipeq9FJXv/McTeQBj+pEd+I+LTkiIV7dCUDFUwBin6tGMisiYJy77kLYZWMLMyX0NM60JzWVU50fmxlUxEXWxo8zTnn04jq7ZuBBir+iAvGuilsTdXN5kM8vo6xwAYp1REE2eapoWU6q18Jod9Bk3vLYEk+zs7Ib+gMu4s4ktTX/azC319UKDfdD4ygIOEml5V7r/lwW2hpRI+QvyMMHY8HHI90LM0RrMGRjCSFRqzKBRJxaFO9OcsAXcovLVKyJgtkJ5QMsmbFRIyGXxtLHSIsCECGVK1IiaOkaac8/AEYjbyhSEoSsWOXc2nfLqcONtKItJkBIzoPD0MJuTaJa0RnIU1SMg6Mgik0eu9L3PzgRZYjUKo5Ki9hKXI6G+kEiMyVM6lA1WHjNUfDjj/ivFMxjZrxH5EmvojzvN7481aqMYPM9HcUsTEzRrwyM2AgfkURNJ5H2BtN3c1JBZGF9/XH4CLh0jSFcXJ9V75BkTp+6Im8aY/f2vDxThVFnix8a/HPBKKRYxXuKAqkPRY5bWFreYUQYKBIx4Ts+I8E1BY2kd1qAcQ1OMkwMd9IaJNiSSJQR/hhjR4mEXyV+Sd5pM279pLDyhNSqvWBio1YWgQn8xw2zy2tfmk5ZnhiPayGmx/0Zr0nrjJDuiTsUPHPULI9lwJKigMWWShpgZC4eXLh95/Q1t60tJeWC490c5woG6FeYKJXgeLuVEgi1/N6aZdCINaOjWOEVnPR0I9ydLnpVFJSkpTybaScSzI6LL7spLVi6zfyLgnUjMtwVmJAdZnqIg2XWKTOWlQhTBYtOOAJj2IA6PhClLxfOJjK2HcoRWd56wQ8qLHahu83jykZWtJNGmMcrZYfOS0LADN0Jtq8V8T2MWBl+OHMWwDWxy1pAOoCqJxvtYmCtv8hiEuTQAgJIw7AUoCYmTBvTlT+NsiXlY8lKl8bQXi0kl8FQxuh5tm/zkMUFs1fmo9UQ0IyWuiRC1NRaEh5A+h+K9NnRf8jqjG7CJFQrY+hkBPxFSIYy3s5gkhTboCLrnjyCZKAWhp5IiIPcYF4vAlOjmaDXXZE+Q4n16FqDczPbWM2Bud4wdaQE/msUzJ0JQt8GNzSspUGsDq+5KanHdzkh8NTxR8u+J+m5ZvfjjKO8pll8OtPTpHzd88cubW27UP3iw1OerDe9qtnlYvP3ypJ1sMX1RjD+znBAdp4fxyZe3/+nJWRMGaRa4aSSY0VJB+xiSmCjrTu4mI4d7p1RJ3H0ce50idB+IHFEDvs9ieqDP91K3h5SMSXP60xGvjraE5dWul6TDGmeaLxuEa1B91HwFEyyVWnzZ/oinU2Mepbwz7sJ9GM2zG2GRCb7liroXr1AYdHYeRkSafAp4hfvJxpCxoFbcOX0ZWuDhRsZ+0C8atbO4T0xJTUSTUS2LnRSPGAgcpbcBFTzxPNQRtyWRub8IwtIQFwJ8ZU2ipfj88nrDC85EUy5eo+kdHqGMuHOUkUVYufl5WOIGTUIKpJ0CsQiBtnXJS0Hnn6uS8N9Fvg7CU/V3Q48niNj3MALQjAQDthwIS9gwnS45cRjZFgFSEn+Mw86oo4b3k+qjBWRn3TccMv2KECR6tKx2ElZFhCRi1MRboCmKPngRCk1ZXI1Ew4huj/mGeF+D1dZS7Bya12a5jCqdZ5KJOTz4kROrSSaJ3gJeWDNnKP3E4TiLD0DwFWJ9WRJxmSVuZ6i3KC1R6NZmXyg+T0Qbr/yIxLgZshtqk3Wck4gfGHHWLyL35M3qc7wj83g0BUuXQReBSjCjM1TY+EkkD91YxsDUicvarAzCs67v8McbxUMbEl8nvhAzRbNi9CkG6+H+PjUX3dfNBGmslLuAo4spSQpAbQRCxFSEmDhLxEMyKw2jpd3HRrzcwg3RgN5CY1ASZAPyJkO146748gEJx39murB3QdK4K9PNqVgA4Wa7GJXiiOdFLSu+hDJ+HnUkxw9hOmipMy7u7ZtCCrUeknx9EGyaJxhE4hgSbMYEtA4Pym15IRQWM6LPF34tun1rJabzGk6BBYRfaXPR+fRET5Po4Bnz1X+jaPxeDfz685BopkSwS1q02HRhgFVEisZ700fQqf7DO/NcbDwXzgpFP+9i9ZF7KgzrYaJ5tPvXXDT7a8TDJGgANWMHvbaj7SJtBT/nKoY5ESCe4zobDyEwVTr8gbeMdJHoPdDv/qIeASZ4Qsat2zPSi/GPUQxtwyXnZOYAmvLDdHO9VflJnUuyEWekbxgriBiXRs9G7dH8GwJfMBGxWKycrkU4a207YEAAIUhZE0Qopf/w45CHI61SCoUjPjVFidEs2Qnzry/3SUwUgveMECOUvDE0l9LMuNFPDndJ+kMB0bI3vFADNFHyHQ9PJ0Esm6Uj37VPwfU9+soc7lrd17FP/cexvV+ftEO7ZDY0tkJdaS+yWelE9Ee9oXf6aKANpMY1mRhw+bpVwYRw4SclPKqTHaN2wMYzE+KAdJo/sH2uigJyxBpkR+Yj3RXZsbYkflB8zIiGhtnifpJLF6KOgp0docbaxE/IuCtS7EgcTYJiQpYcaQIs4uGX3qOnbJ4HgsW66aDOdErl7Dzq8Xj18euZ58hGslNNtb7khhwCN2FxTij3lHr4kWmbu/OcSzc1HxvfJjCOQXxzXM+em149lIMkqYMxzzbQbbZ7L7+pMv9eE2NfpdvpeAaCThi6/MItNXvVCBYhsPe22LDixOanXyZYZ+3xumEcMFBKftZ35tR46IcRELeTfJVggm8zpk4Tz5yRj29RTReVghNfor/cRaAgqignKEb4bz7/f50djsauCp2Vt9/L6oHCANjXCzEPRl6DNjMZSp7apCAqBjBC2hPDcX0hXU4JRYpmqZlf/kI/D2QfPy3rhHrHOC0pIaBCxgFKa6CMJXFhhvouRLwcypXXKBDNIuE8BPF0IZVfQYN7i3WhXGWJfkHOcvXX7E+9uiiiZXG3LkVZiddGEWmzsWMz87/Mg2xE6JcdbB7RRGA8awiRbt7mfFyIeI97pMFwM+6HQywFel47IHJ8wvJdeleja244KF2KEyPGCrXfKU7RhRSXz4jVvfgYTILaYqulpDMV9PiM5BUlImCgjHIMlzARHjuzP4judCBufqikhzxEhyYiIiCuj/rjtpiTeCLEfkc59YvC3d3Bo7cUICdq0VCU5P7esiYVZ8L/HcIoU6cQLKkBz7rZR2rj/Ag41jfPztm5JCx5mLxDw5pxNgAxiZyJS0rE+P98T53ADHwEM7j4HnPDc0A3LitCQIjgUxQzNVatkaGKLHUbIosv+GmDutLM8uyVvBpZyYZHOBNBpV1Fh+axIcgH+bodeVKSRipQogbhulDPh4xePqkrFrSBt+f7zMjpsOc20c+ozf60NTopVq+TIkPy2U6D9yPvDF4ghnrBmTpjecV6/ED0h1OSmpKzBj07Mm3YHv1sKtkDnZ0YPjvTJ0aNnPW0GPVry+5kiu9IsnM8bqptl3CTjk6gFzzbnQlKVIR+vMmWOEH+chv107EmmId6YZOtJjRAp+vc7ICHigsgH4ebTVqMZSabXt+EXzDzjlvqLTWX3jUSpP+RC2y8+Hk32Oi+JeUyEPQACB2a8ef6e65Ef2bDRgnqhuIu3WAvMMMadNC+xnaQb9V0xbn/2Te7efhtmZZ4k3x6Ygb2Yh6HJFFwVHvtEs+W2U7fUT6Ymor4h2IpcXtM+SSg110caJpNyvDMgyJiNxmaI3mIPhTJc7usyst6cVVtdvaIFMufCzVclrg3kdJELMpJ/OgDKW2BmBmCfpNy7CypoTaEGAn/sgQiuyXVvxfJq7SIgeIIoslZFoCQ8pUG/CMnFm5wBndGybpCTl7NSboifpkY+8a7MP4znSA0fcA26STwPyY7xJ6AlIl1EoJU9CASzq+RIpQlGstgHbz4+ylSspTDI+gUWBNW+LR+Eccd+XLwnv4FCJXK8h7JAAA=

**Comment by DaneelGavin** [comment]
One ballista can hit philadelphia, yet the other two ballistae cant hit new york

**Comment by yairm210** [comment]
Printscreen please
My guess is that for the ones that can't hit, there's an obstacle in the way (hills, forest, mountain, jungle)

**Comment by Am-per-Sand** [comment]
sori mista mee fona 2 weeka 4 yo sava but ballista is not ranched
#464

**Comment by DaneelGavin** [comment]
O.o sorry not a bug then. Ranged not as op as I thought. Srry again
