### ISSUE TITLE
Modifying the BuildQueue when its not your turn removes it.

### ISSUE THREAD

**Issue by Green-Sky** [yairm210/Unciv#8571]
**Platform**
Ubuntu, Android

**Version**
4.4.9, 4.4.5

**Describe the bug**
In a multiplayer game. When you select an entry in the Build and try to modify it, it deletes it.
Nothing should happen

**To Reproduce**
1. go to city screen
2. click entry in build queue (anywhere, the first click does only select it)
3. click prio(up/down) or delete
4. its not gone

**Expected behavior**
Nothing should happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/2938071/216771021-c12eb295-f317-4418-a6bf-e50b4bd61e62.png)

![image](https://user-images.githubusercontent.com/2938071/216770981-880e4a0a-1aad-4e77-a165-0724f3092218.png)

![image](https://user-images.githubusercontent.com/2938071/216770996-d95db9a4-4ba0-4e0c-8358-029c54656547.png)

![image](https://user-images.githubusercontent.com/2938071/216771010-7298ebe7-b498-44b7-b98a-ce3b34933477.png)

**Additional context**
This might not be a major bug, since you are not the one writing to the save -> when its your turn its back to normal again.

**Comment by yairm210** [comment]
This does not happen to me, when in a multiplayer game and it's someone else's turn, the "change item" buttons simply do not appear
![image](https://user-images.githubusercontent.com/8366208/216850593-42b50615-7f40-49ed-8940-0289ec48e60c.png)

What exactly are you doing?

**Comment by yairm210** [comment]
Ohhhh in the *queue* gotcha

Fixed
![image](https://user-images.githubusercontent.com/8366208/216850859-60fd5316-54ca-446b-b05c-1b6c8292df4d.png)
