### ISSUE TITLE
Freeze/Crash during "Next Turn" 

### ISSUE THREAD

**Issue by tiint** [yairm210/Unciv#8574]
**Platform**
Android: MotoG Stylus, OS 11
Operating system type, major version, architecture (64/32 bit).

**Version**
Google Play Store v 4.4.7 (build 804)

**Describe the bug**
Game freezes and eventually crashes while processing the turns for the AI players. This seemed to start a couple updates back.

**To Reproduce**
Unsure as to what triggers it.

1. Play game as usual, but eventually…
2. Tap [Next Turn]
3. Wait
4. Wait
5. Wonder why it's taking so much longer
6. Wait
7. Wonder if the game froze
8. Map can't be moved, Hamburger menu won't open, units on screen cannot be selected
9. Wait
10. Black screen
11. Close app **:'(**

**Comment by vegeta1k95** [comment]
Save game? Happens still after reload?

**Comment by tiint** [comment]
Auto-save is on. It will happen after reload, but not immediately. Could happen after 2 turns or 20 turns.

**Comment by vegeta1k95** [comment]
Seems like Our of Memory issue or something, can't really do anything about such inconsistent crashes, unless there is a memory leak.

**Comment by yairm210** [comment]
There is no way for us to reproduce this, at all :/
I wish we could help, but this is simply Not Actionable
