### ISSUE TITLE
The displayed mod size is incorrect

### ISSUE THREAD

**Issue by Gualdimar** [yairm210/Unciv#8575]
The displayed mod size on the mod manager screen does not correspond to reality.
For example, 5Hex Tileset zipped - 6021 Kb, unzipped - 6052 Kb, Unciv shows - 96511 Kb

The first time I saw it, I wasn't sure my phone would handle a mod that was several times the size of the game itself)

**Comment by vegeta1k95** [comment]
AFAIK it shows the size of github repo, because GitHub API returns it as such. Not just source code size.

**Comment by Gualdimar** [comment]
then, imho, it's useless and only confusing for the average player

**Comment by yairm210** [comment]
This looks like a serious problem with the Github API
The question is what do we do with this.

We have 2 options:
- Display incorrect size
- Don't display size at all

I'm honestly not sure which is worse, both are pretty bad options.

I'd like to hear if you think we have other options here.

**Comment by Gualdimar** [comment]
if we want to show the size before downloading, the only thing that came to my mind is to get a list of files with sizes, then sum them all
`https://api.github.com/repos/ravignir/5Hex-Tileset/git/trees/master?recursive=1`

or show the size after downloading...

**Comment by yairm210** [comment]
We can't have an API call for every mod in the list of mods, that's ridiculous
Maybe only when the user clicks on the mod do we try to do that
In any case size after downloading is not the problem we're trying to solve, we want the player to know what he's taking

**Comment by Gualdimar** [comment]
Or the player clicks on a mod in the list, reads the description, decides whether he needs it,
clicks the download button, a confirmation window pops up with text "Do you want to download xxx KB?"
unciv makes an API request only after the download button is clicked

**Comment by vegeta1k95** [comment]
Should be (partially) solved by #8648. Closing for now.
