### ISSUE TITLE
Feature request: Seperate Next Unity and Next Turn buttons

### ISSUE THREAD

**Issue by JakeDevs** [yairm210/Unciv#8595]
This would be much more convenient than spamming the Next Unit button until your next turn, especially when you have expanded  quite a bit.

**Comment by yairm210** [comment]
What are you suggesting, though? What's the problem and what's the solution?

**Comment by JakeDevs** [comment]
> What are you suggesting, though? What's the problem and what's the solution?

Put simply, separate the next unit and next turn buttons into 2 buttons so you don't have to spam the next unit button to get to your next turn. It gets very annoying to do when you have a lot of units.

**Comment by yairm210** [comment]
What you're looking for is to disable Options - Check for idle units
