### ISSUE TITLE
CityScreen tile resources mismatch/leak from neighboring city

### ISSUE THREAD

**Issue by Green-Sky** [yairm210/Unciv#8618]
**Platform**
ubuntu

**Version**
4.4.12, 4.4.11

**Describe the bug**
On the City screen.
The resource icons on tiles close to a (same civ) neighboring city show different quantities what should be.
furthermore, the tile details from clicking on the tile give the correct quantity.
(see screenshot for example)

**Saved game**
[cityscreen_res_mismatch1.txt](https://github.com/yairm210/Unciv/files/10680149/cityscreen_res_mismatch1.txt)

**Expected behavior**
I think the number in the details is correct?

**Screenshots**

![image](https://user-images.githubusercontent.com/2938071/217387726-4f0cc6c2-33f7-4ec1-a2e2-7ce1d223dcd9.png)

**Additional Context**
it is not my turn.

**Comment by vegeta1k95** [comment]
Easy fix, wait for PR

**Comment by vegeta1k95** [comment]
Fixed by #[c2c03d8](https://github.com/yairm210/Unciv/commit/c2c03d82021828f89dfe1c0bc54b66b21c4b1725)
