### ISSUE TITLE
Crash on every move

### ISSUE THREAD

**Issue by 7em1** [yairm210/Unciv#8644]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vegeta1k95** [comment]
Need information. Please fill the issue request properly.

**Comment by yairm210** [comment]
There's no substance to this issue.
If you have more information we can reopen.
For now I'll say try upgrading, chances are that will solve your issue.
