### ISSUE TITLE
Guruship belief doesn't work

### ISSUE THREAD

**Issue by Shim-Panze** [yairm210/Unciv#8647]
**Platform**
Android 8.1.0

**Version**
Downloaded apk from GitHub, version 4.4.7 (Build 804)

**Describe the bug**
The guruship belief seems to not do anything.

**To Reproduce**
1. Make religion with guruship belief
2. Assign specialist in town that adopted belief
3. Production doesn't change accordingly

**Expected behavior**
Assigning any specialist in a city that has the guruship belief should increase production by 2, it doesn't happen.

**Additional context**
I was playing Byzantium when this happened, but guruship was not the extra free belief from the civ ability.

**Comment by yairm210** [comment]
Please attach a save file

**Comment by Shim-Panze** [comment]
[Byzantium - 236 turns.txt](https://github.com/yairm210/Unciv/files/10706516/Byzantium.-.236.turns.txt)
