### ISSUE TITLE
Diplomatic Victory project

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#865]
- [ ] Globalization Tech (it needs Ecology and Computers, and leads to Future Tech)
- [ ] United Nations Wonder (needs Globalization)
- [ ] One vote per Civilization
- [ ] Two votes for the Civilization who built the UN
- [ ] If you liberate a City-State, they'll always vote for you
- [ ] If the same City-State is liberated more than once, it will support their latest liberator
- [ ] You may also ask other Civs to vote for you
- [ ] Diplomatic Victory, achievable by having the majoriity vote in the World Leader Election

**Comment by yairm210** [comment]
Moved to #663
