### ISSUE TITLE
Error when air sweeping with triplane

### ISSUE THREAD

**Issue by Tyber37** [yairm210/Unciv#8651]
ANDROID

Game from play market
Version 4.4.11

When trying to perform an air sweep with a triplane in a city an error pops up

**To Reproduce**
1. Go to city production
2. Click on triplane
3. When it is built, press "air sweep"

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by N1cc3** [comment]
Apparently already fixed but version not yet available via Google Play as discussed in #8650.

**Comment by alexban011** [comment]
Google play updates come a little slower, but you should get it in about 2 days at most from now

**Comment by vegeta1k95** [comment]
Update to 4.4.13
