### ISSUE TITLE
Prevent city states from producing/gaining settlers

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#866]
Too many games I start next to multiple city states who quickly settle 2 or 3 cities of their own very close to me. This combined with the rapid growth of their capitols means they're taking far too much land for how much you would expect in Civ V. Please restrict their ability to produce or capture settlers through ruins (or however else this might be happening) 
![Screenshot_20190609-103518_UnCiv](https://user-images.githubusercontent.com/49125947/59161048-fddd8900-8aa2-11e9-9f62-b05decbaf018.jpg)

**Comment by yairm210** [comment]
Okay, they already can't produce settlers themselves but I hadn't thought of the ruins, good point!
