### ISSUE TITLE
Unciv website

### ISSUE THREAD

**Issue by JakPit23** [yairm210/Unciv#8665]
**Is your feature request related to a problem? Please describe.**
When I started playing Unciv, I couldn't understand all of the features. I've played original CivV and I am good at playing (or I think it about myself). But this game is slightly different. Not harder, not easier, but different.

**Describe the solution you'd like**
I would like website for this game, like some basic information, FAQ, Civilipedia and some other things maybe.

**Describe alternatives you've considered**

**Additional context**
If it's good I would like to do it by myself. I know pretty much about creating websites.

**Comment by yairm210** [comment]
Sounds like a player guide in the existing docs to me
Interesting

**Comment by Weverak** [comment]
I don't see it in the docs. Where can I found it?

**Comment by yairm210** [comment]
No, I meant that this is something we can add to the docs

**Comment by Weverak** [comment]
Oh, I see. Maybe I could do it, but there's lot of things.

**Comment by MayeulC** [comment]
Going by the title of this issue, an actual landing page for the website at https://yairm210.github.io/Unciv/ would be nice too :)

**Comment by yairm210** [comment]
> Going by the title of this issue, an actual landing page for the website at https://yairm210.github.io/Unciv/ would be nice too :)

By which you mean...? What would you expect to see?

**Comment by MayeulC** [comment]
Basically, most of what the GitHub Readme says, but catering less to developers, and more towards users.

Less developer information (a github link/icon should be enough). The idea being that new users or users looking for information on Unciv shouldn't be familiar with github. 

Examples:
* Battle for Wesnoth https://www.wesnoth.org/ I like the landing page for this one
* Mindustry https://mindustrygame.github.io/ maybe a bit too terse to my liking
* SuperTux https://www.supertux.org/index.html More focused on blog posts, like these other websites:
  * SuperTuxKart https://supertuxkart.net/Main_Page
  * 0ad https://play0ad.com/
  * Freeciv http://freeciv.org/
  * OpenMW https://openmw.org/en/
* Thrive https://revolutionarygamesstudio.com/ Video front-and-center, I am not sure about using the name of the studio as the domain name

Such generic info could be removed from the repository's README too, to make more space for developer-specific info.

The Mindustry wiki is fairly complete, with a lot of info generated automatically, from what I know. It could be a good example for what @Weverak asked here, I think?

**Comment by Weverak** [comment]
Yeah, it's something like that

**Comment by Diztend** [comment]
Could we add the civilopedia to the Unciv Wiki?

**Comment by yairm210** [comment]
Someone would need to convert the civilopedia text to markdown files, I'm not planning on doing so, you can if you want

**Comment by MayeulC** [comment]
Hmm, if this was Gitlab, I would convert the json files to md as part of the CI, before the actual "pages" generation. I wonder if something like that is doable with the current CI? (I am not sure where/how the website is managed).

This could also be hosted on a separate repository and subdomain.

**Comment by yairm210** [comment]
Absolutely doable
The method we currently use is to generate the md data for e.g. uniques as part of the app, since it already knows all the data format etc, but I'm not against moving that out to a different format as well

**Comment by poVoq** [comment]
A website would be also nice for subscribing via RSS feed to news. Right now I do this via the Github release page, but with the constant "patch" releases it is really spammy.

Nice might be also a home on the Fediverse (Mastodon etc.) for following updates.

**Comment by yairm210** [comment]
@poVoq Github provides that: https://github.com/yairm210/Unciv/commits/master/changelog.md.atom

**Comment by poVoq** [comment]
That's even less descriptive than the release.atom feed as the feed just includes the version number it seems.

Obviously a website would imply some sort of news page outlining major releases, but I understand that this might be too much work to do.

(Alternatively maybe you could not tag but not mark the patches as releases? I doubt many people update their game though these patch releases anyway.)

**Comment by MayeulC** [comment]
> Alternatively maybe you could only tag but not mark the patches as releases? I doubt many people update their game though these patch releases anyway.

These at least trigger flatpak auto-updates within a few hours, so users may actually, depending on how they handle their flatpak updates (probably automatically, or with a desktop notification in most cases).

**Comment by yairm210** [comment]
The point of patch releases is to solve crashes, so they do
They are proper releases from every perspective

**Comment by SeventhM** [comment]
So... My viewpoint on this: I'm more than willing to leave this open. Even remove the stale label. But I have 2 major hangups:
1. This sorta assumes that people wouldn't be willing to go to the github page as a landing page. And even if you argue this is a fair enough claim, We can always just add a page to the Wiki that copies most of our Readme
2. Most of the info for unciv is the same as the info you could find from the Civ V wikia, or from the civilopedia in-game. This is very different from a game like Mindusty (which I've played before), which while similar to Factorio in some ways, is its own separate game with its own rules. So there kinda isn't really anything to put on a landing page besides locations to download the game and information on how to contribute/mod. I guess this isn't too different from some the examples given here, but it again makes me wonder how necessary this is

**Comment by yairm210** [comment]
I'd say this is a no-go. I'll clean up the "front page" of the wiki to make it act more like a main website front page, but I don't think we need any other site things. Again, we can discuss PRs, but this is not on roadmap
