### ISSUE TITLE
Taskbar overlaps the game window

### ISSUE THREAD

**Issue by Gualdimar** [yairm210/Unciv#8687]
@vegeta1k95 after PR #8679 with Screen Window: Windowed taskbar in windows overlaps the game window

![22_2](https://user-images.githubusercontent.com/1225948/219697148-5d0d63f2-418b-4828-af5a-e4f972f37c4d.jpg)

**Comment by vegeta1k95** [comment]
Fixed by https://github.com/yairm210/Unciv/commit/ec2be2cecaff39315930896b0141607560db4cb4
Just minimize/maximize/resize your window once to update old settings and it should be fine from now on.

**Comment by Gualdimar** [comment]
@vegeta1k95 now I have free space between the taskbar and the game window
I run the game in an empty folder without any settings files. clean installation.
