### ISSUE TITLE
Can't bombard tile above city with garrison

### ISSUE THREAD

**Issue by RealGrouchy** [yairm210/Unciv#8689]
Maybe I'm missing something obvious, but if I'm on a hex grid, there is an odd number of units in my city, and there is an enemy unit on the tile directly above my city, I cannot for the life of me get the city to bombard that enemy, because the unit selection icon blocks the entire tile.

**Comment by yairm210** [comment]
You can unselect the city, and just click on the tile above the city.
The city will automatically be selected and you can bombard.
Do you have a suggestion for how you would want this to work?

**Comment by yairm210** [comment]
Guess not...
