### ISSUE TITLE
UI/Screen bug when using experimental rendering improvements.

### ISSUE THREAD

**Issue by Marcos6226** [yairm210/Unciv#8704]
**Platform**
Android version 5.1.1

**Version**
Play Store version 4.4.15 (build 813)

**Describe the bug**
When the **experimental rendering improvements** option is activated it can cause a bug that makes the UI/Screen basically go all blue with a dark gray rectangle in the middle (check screenshots below) and blocks any further action from the user other than restarting (closing and opening) the game. I have seen it happens after some inputs from the user like pressing some very specific buttons, or if you overload your RAM memory (although I did not tested this method).

**To Reproduce**
1. Go to Options and activate the **Experimental rendering improvements.** After that go to **locate mod errors option** (necessary to have a third-party mod installed. Recommend Brave new world mod as it shows a yellow warning necessary to reproduce this bug.)
2. Click on any mod that shows any yellow warning sign (maybe red too but I didn't tested that).
3. See error

<details><summary>Last error txt file</summary>

```
[lasterror.txt](https://github.com/yairm210/Unciv/files/10778052/lasterror.txt)

```
</details>

**Expected behavior**
Expected it to open the tab normally as it happens when you do not have the **experimental rendering improvements option** activated.

**Screenshots**

![Screenshot_2023-02-19-18-45-32](https://user-images.githubusercontent.com/49823690/219977440-20665372-fb13-497f-9d30-41dd93ec8df3.png)
Screen after bug is activated.

![Screenshot_2023-02-19-18-45-06](https://user-images.githubusercontent.com/49823690/219977442-6f2365e2-35b1-44ea-b4cd-ac2097f4d5b3.png)
Screen when the Experimental Rendering Improvements is disabled. (Notice that I can open the mod info screen normally)

**Additional context**
If necessary I can try to reproduce this bug on my desktop (windows 11) for alternative system bug confirmation. (Too busy to do it right now).

**Comment by vegeta1k95** [comment]
This is fixed in build 814
Use newest version: 4.4.16
