### ISSUE TITLE
literally NO mods work for me

### ISSUE THREAD

**Issue by kingkarna1** [yairm210/Unciv#8717]
Model: A509DL CPU: MT6762 Android version: 11 Build: vl8X
Google play: 4.4.15-patch1

I attempted to use multiple mods one by one, all cause the game screen to go brown.

i download a mod, then start the game with a mod enabled, after first turn, the brown screen appears.
![Screenshot (130)](https://user-images.githubusercontent.com/87745085/220419946-65309890-f203-4394-a1fc-608d6cf857f2.png)

looks like this:

**Comment by vegeta1k95** [comment]
Are you using "Experimental rendering improvements" option? (`Display` tab)

**Comment by kingkarna1** [comment]
yes, ill try it without

**Comment by vegeta1k95** [comment]
Wait for new version: 4.4.16 and higher, and try that option again.
Supposedly it got fixed.
