### ISSUE TITLE
Is Building.canBePurchasedWithStat() faulty?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8731]
That `return` in [line 3854 of Building.kt](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/ruleset/Building.kt#L385) can't be right. Why does that even compile? Can anybody please check out whether this can be seen in-game? Something purchasable when it shouldn't be?

**Comment by yairm210** [comment]
I agree we can lose the 'return' but that looks fine to me.
Check building-specific logic for buying, if none of the uniques for buying buildings exists - default to the general construction check for purchasing with stat. What's the problem?
