### ISSUE TITLE
Feature request: [Desktop] Enter key end turn

### ISSUE THREAD

**Issue by HydrolienF** [yairm210/Unciv#8787]
**Is your feature request related to a problem? Please describe.**
No realy a problem by I'm use to press Enter to end my turn in 4X game.

**Describe the solution you'd like**
I think it would be better if pressing Enter can click the upper rigth action as "End turn", "Select Science" etc.

**Describe alternatives you've considered**
I' could be an other key, but I think enter is the most common used for that.

**Additional context**
![Capture d’écran 2023-03-02 115420](https://user-images.githubusercontent.com/71718798/222408748-509019cb-de8f-43da-9049-937030a70476.png)

**Comment by yairm210** [comment]
> Un de ces jours... we might do configurable key bindings...?

No :)

**Comment by yairm210** [comment]
As stated, this option exists

**Comment by HydrolienF** [comment]
> You can already do this with the space bar.
> 
> Also, check the help(F1->Keyboard) for other keyboard shortcuts

Tanks a lot. I will check f1 before asking for more things that are already in the game.
