### ISSUE TITLE
Shall we show Terrain.overrideStats in Civilopedia?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8793]
IMHO necessary to be able to trace how the game calculates yields...

Question is - How exactly / **wording** / better ideas???
![image](https://user-images.githubusercontent.com/63000004/222507015-1f095d04-3842-43b7-bd1d-0a21cf24c85a.png)

Aside to coders: Looking at the usages of the field, my brain fired some interjections - comments?
- `TileStatFunctions.getTileStats` line 21 to 41 could use `allTerrains` and be just one loop - would then process natural wonder before features - maybe even a good thing?
- `getTileStartYield` does largely the same as `getTileStats(null,null)` except for the city center check and it ignores nat wonders - better unify, and allow scoring nat wonders, probably meaning the GameStarter would start preferring start locations near nat wonders instead of avoiding them - if those wonders were heavy in food/prod/gold???
- by the same argument, shouldn't gamestart scoring take `NullifyYields` and/or `TileProvidesYieldWithoutPopulation` into account?

**Comment by yairm210** [comment]
First option looks best to me
Unifying similar functions is always good, good idea, and 'yes' to taking things into account
