### ISSUE TITLE
can't trade city state city to other civilization 

### ISSUE THREAD

**Issue by Abf30** [yairm210/Unciv#8824]
**Platform**
android, 4.5.1(build 823), architecture (64/32 bit).

**Version**
option〉about

**Describe the bug**
When trade a city-state with other civilization,an unrecoverable error has occurred in Unciv.

**To Reproduce**
1. Go to 'trade page'
2. Click on 'our trade offer〉(a city-state)'
3.Click on next offer the trade
4. Click on next turn
5.see error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
I captured a city state,i want to give it to another civilization and declare war then i can capture the city state again and liberating their city to increase influence.But when I trade city state city whith other civilization the erroe happened.

**Screenshots**

**Additional context**
I have try it in another game,it also happened.It only happens with ai.

**Comment by yairm210** [comment]
Please attach a saved game

**Comment by yairm210** [comment]
Solved in 4.5.2, please upgrade :)

**Comment by Abf30** [comment]
Thank a lot for fix bug！Also for good free game！
