### ISSUE TITLE
Feature request: In-Game Chats

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#8828]
The idea is simple. Connect via WebSocket and Broadcast messages. Rooms will be named with Game ID and messages will be displayed by civName.

Since we want to use WebSocket for everything, maybe something like web can implement something like subscribegame: gameId. For now we will only use this for chats but it can be later used for updating game stats, lobby and more.

issue references: #8817

**Comment by yairm210** [comment]
This is part of the long process of renewing multiplayer. Please don't open every single aspect of that as a different issue.
