### ISSUE TITLE
Civilization icons

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#883]
You what I've noticed missing? Civilization symbols, you know, the ones on the "so-called-shield"? These ones.
I think that Egyptians should take either the Ankh or the Eye of Horus, the Crown of Saint Edward should be for the English, the laurel wreath for the Romans, the double-headed eagle for the Russians, star and crescent for the Arabians, Lamassu for the Babylonians, etc...

**Comment by yairm210** [comment]
Excellent, gather them

**Comment by Smashfanful** [comment]
Do I have to draw them?

**Comment by yairm210** [comment]
Search for them on thenounproject

**Comment by Smashfanful** [comment]
The what?

**Comment by yairm210** [comment]
https://thenounproject.com

**Comment by Smashfanful** [comment]
Thanks
