### ISSUE TITLE
Game doesn't want to open, both from the itch.io launcher and the exe

### ISSUE THREAD

**Issue by VachaArraniry** [yairm210/Unciv#8845]
**Platform**
Windows 10 Pro 64bit

**Version**
Got the game from Itch.io. Game just auto updated to version vtest-prerelease-2

**Describe the bug**
After the recent update i wasn't able to launch the game at all, every time i open it whether it be straight from the exe or from the Itch.io launcher, it will always close immediately after opening.

I've tried re-installing a couple times and changing the version to another version from today, it didn't work.

**To Reproduce**
Opening the game from anywhere

<details><summary>Game not opening</summary>

```

```
</details>

**Expected behavior**
Expected to open like always, i already have 121 hours on the game

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
We're currently undergoing some pipeline changes, this is an unfortunate but necessary part of upgrading our infrastructure, should be up and running soon

**Comment by yairm210** [comment]
Solved, back to normal
