### ISSUE TITLE
Disbanding units doesn't give gold

### ISSUE THREAD

**Issue by mistermano** [yairm210/UnCiv#885]
Disbanding units within your territory does not give any gold, despite the prompt stating how much gold you should get back.

Steps to reproduce:
1 - Leave a unit inside a city's territory
2 - Disband it (the prompt will say you'll get 15 gold for a worker, for instance)
3 - No gold added

I also want to note that if you disband with the unit in a city tile, you will get the money.

**Comment by yairm210** [comment]
Solved, will enter 2.17.9
Thanks!
