### ISSUE TITLE
resolution to screenSize migration is incorrect

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8863]
Question to coders:

`GameSettings.screenSize` replaces `GameSettings.resolution`, but the code in `doMigrations` might never be called since `isMigrationNecessary` doesn't check anything. Also, the default should now be `var resolution: String = ""`, and `GameSettingsMigrations` seems to handle `version` incorrectly - checks for 2 but sets 1.

Do we even care about this or should we let it phase out with the next round of deprecation kills?

**Comment by yairm210** [comment]
I personally don't care, we can deprecate this in next version
