### ISSUE TITLE
Future Tech ugly when researched *and* researching

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8865]
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/63000004/224497106-44a751b8-fd0b-4e6c-8e38-a687bf4565cf.png)
</details>

White text on warm-bright yellow isn't that sexy.

I suppose something like this...
```kotlin
            if (techName == Constants.futureTech && civTech.isResearched(techName)) {
                val textColor = if (techName == selectedTech?.name) Color.BLACK else Color.WHITE
                techButton.text.color = textColor.cpy()
                techButton.turns.color = textColor.cpy()
            }
```
... in TechPickerScreen.setButtonsInfo might solve that, but - is that the right approach? @vegeta1k95 : you were there recently?  @GGGuenni  : Skinnability??

**Comment by yairm210** [comment]
Sounds to me more like we need a separate color from completed "continually researchable" techs. Maybe an orangier flavor?
