### ISSUE TITLE
Option to puppet for traded cities

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#8876]
If you gain a city as part of a trading deal, it cannot be made a puppet. Is this intentional for some reason or is this just missing? If the latter, I'd like to work on this.

**Comment by yairm210** [comment]
Yes, puppeting is for captured cities, to offset the extra unhappiness
Traded cities should not generate that extra unhappiness, if they do that should be fixed
However, users have requested the ability to return cities traded to you too their rightful owner, as can be done when captured

**Comment by WhoIsJohannes** [comment]
Yes, this matches my experience from playing. You'll need to build / buy a
courthouse pretty fast to not take a huge hit on happiness. So this is a
bug, right?

Il lun 13 mar 2023, 10:30 SomeTroglodyte ***@***.***> ha
scritto:

**Comment by yairm210** [comment]
Our definition of 'bug' for these cases is 'differs from Civ V', so we need to answer the question - does it?

**Comment by WhoIsJohannes** [comment]
ChatGPT thinks Civ 5 behaves the same way (ie. traded cities behave like annexed), but can't provide me a reference. The best I can find is this:

https://www.carlsguides.com/strategy/civilization5/happiness.php

**Comment by yairm210** [comment]
So that's settled then
Barring further info of course
