### ISSUE TITLE
Dynamic mini-map getting stuck on last player in hotseat

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8892]
Windows 10 64-bit, itch.io version 4.5.7

When switching between players in a hotseat game, the mini-map gets stuck on whoever the last player was, showing their cities instead of the current player's cities.

You can see in this shot that the map is showing the green territory of Arabia instead of showing American colors.

![Screenshot (160)](https://user-images.githubusercontent.com/58439827/224873173-d6b39a8a-2784-471b-afa1-07c639e4c5d8.png)

**Comment by Gualdimar** [comment]
Noted

**Comment by Gualdimar** [comment]
@SomeTroglodyte, thank you very much for your help, you saved my time for debugging.

> * Why is minimap deciding between selected and viewing according to fow?

As I understand it, `fogOfWar` can only be false in spectator mode. If it is flase - all tiles are visible on the minimap, else the minimap will show tiles visible only to `selectedCiv`

> Uh... `updateSelectedCiv()` has a when{} with a non-Unit return value that's discarded - in other words, the else branch does nothing but looks like it's meant to

Good catch, the spectator mode is much more useful now)
