### ISSUE TITLE
Feature request: make certain UniqueTarget.Ruins explicitly available to non-Ruins options

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8897]
The Bucketeer's [Warfare Expanded Lite](https://github.com/GeneralWadaling/Warfare-Expanded-Lite/blob/main/jsons/UnitPromotions.json) mod features a promotion with the `"This Unit upgrades for free including special upgrades"` unique. The list of unique types says that this is a ruins unique, implying that it won't work if applied to things besides ruins. But this is not the case; the unique works successfully when applied to a promotion. I think that it ought to say so.

There are other uniques that also work on things besides ruins. `"Reveal up to [amount/'all'] [tileFilter] within a [amount] tile radius"` works when applied to a building, for example. It ought to say so.

**Comment by yairm210** [comment]
You're right, those are both triggerables under the new trigger rules
