### ISSUE TITLE
"Upon being defeated" not working on defeated civilian units

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8899]
Windows 10 64-bit, itch.io version 4.5.7

Civilian units with a "upon being defeated" triggerable unique don't trigger that unique, even when they're destroyed. I made a civilian unit with the `"Uncapturable"` and `"Empire enters a [8]-turn Golden Age <upon being defeated>"` uniques, but nothing happens when the unit dies.

The attached mod contains the civilian unit I described, and also a military unit that does trigger the effects when it dies.
[SuicideUnit.zip](https://github.com/yairm210/Unciv/files/10972873/SuicideUnit.zip)

**Comment by yairm210** [comment]
It's not supposed to work on Civilian units, so not a bug
Sounds like a feature request but I don't know why you would want this
What's the use case?

**Comment by SpacedOutChicken** [comment]
The idea was that if the civilian unit ever got destroyed, a new unit would pop up to instantly replace it.

**Comment by yairm210** [comment]
That's *very* niche
I guess it can be worked in though
