### ISSUE TITLE
Can't build plantations on jungle or forest (dyes, bananas)

### ISSUE THREAD

**Issue by HeavyMetalFFT** [yairm210/UnCiv#890]
In the (un)civilopedia, bananas are listed as occurring in jungle, and dyes are listed as occurring in jungles and forests.  Both are listed as being improved by a plantation.  Yet plantations cannot be built in jungle or forest terrains, meaning that bananas and dyes cannot be improved very well.  This in particular means that the happiness benefit from working dyes cannot ever be realized.  I suggest that plantations be buildable for jungles with bananas, and that dyes be improved by a trading post rather than a plantation.

**Comment by yairm210** [comment]
This is the way it is in original civ as well - you need to remove the forest before you can build the plantation!
Not a bug

**Comment by HeavyMetalFFT** [comment]
Thanks - never played the original v5, so this was helpful!

**Comment by DaneelGavin** [comment]
> Thanks - never played the original v5, so this was helpful!

Ditto, all the civs upto 4, played to death.

**Comment by alextfish** [comment]
I see! I came here to report this bug as well (I never played Civ 5 either). Could this issue perhaps be reopened with the task of improving the in-game documentation on this instead? If the help for Bananas and Dyes could mention that you have to remove the jungle first, then I'd've done that centuries ago, not just shrugged and thought "Oh well, it's a free game, there's bound to be some bugs" and carried on!

**Comment by asilano** [comment]
This would explain why I'm having trouble improving the Spices in my forest hex.

However, in original Civ 5, you could give the order to build a Plantation on a Forest/Jungle with appropriate resource, and the worker would remove the trees first, then get on with the plantation. However, I guess that's technically an enhancement request, so I'll open a new issue.

(Hi, @alextfish 👋 )
