### ISSUE TITLE
"upon being defeated" and "by consuming this unit" violating "Limited to [amount] per Civilization"

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8901]
Windows 10 64-bit, itch.io version 4.5.7

I gave a unit the uniques of `"Free [SS Cockpit] appears <upon being defeated>"` and `"Free [SS Cockpit] appears <by consuming this unit>"`. Both uniques allowed for the generation of SS Cockpit units in spite of the usual limit of 1 per civilization. By consuming or destroying the unit I mentioned, I could generate an unlimited number of SS Cockpit units.

This little mod contains the unit I mentioned. With it, you can have all the SS Cockpits you want.
[InstantSpaceship.zip](https://github.com/yairm210/Unciv/files/10973353/InstantSpaceship.zip)

**Comment by yairm210** [comment]
Actually all triggers for free units would have this problem, this is a general problem with the triggerable and not with the trigger itself
