### ISSUE TITLE
Desktop: Saved window size has almost zero usefulness

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8931]
**Platform**
Both a Linux, in my case Mint 20.3 cinnamon, and a Windowz, in my case 10 21H2

**Version**
Pretty fresh from master, 828 = 4.5.5

**Steps to reproduce**
- Set a desktop Unciv (both OS) to Windowed mode
- Resize to something recognizable, smaller than the screen, but different from 640x480
- Leave the game cleanly

- Restart the game on Linux
    -> will be windowed+maximized filling the screen (excluding taskbar), saved **size is lost** (windowmanager "restore" will not restore it)
    Understandable: `config.setMaximized(true)` in DesktopLauncher.main and method used nowhere else
- Restart it on Windoz 10
    -> will have the size you left it at, but revert to 640x480 the moment you move it. Yes, **size _jumps_** the moment you drag the title bar.
    `(Gdx.graphics as Lwjgl3Graphics).window.config.windowWidth`/windowHeight contains that 640x480 value before and after the setWindowedMode call, but patching it in-memory just before the first drag has no effect. However, the same steps on Linux show the same values there.

**Quick and dirty**
- Comment out the setMaximized call and after loading the settings, call setWindowedMode(settings.windowState.width, settings.windowState.height) _on the config_ we're preparing there. Yes there is a difference between Graphics.setWindowedMode and Lwjgl3ApplicationConfiguration.setWindowedMode.
- Repeat steps above
- Both seem to react identically and more or less fine. The stored size amounts to something on Linux and no size jumps on Doze.
- The values passed to config.setWindowedMode in launcher.main will turn up in that debug watch formula above
- So does that mean Graphics.setWindowedMode fails to pass the new values down to the Lwjgl3Window but bypasses it and _does_ pass the size to the GLFW window the Lwjgl3Window is proxying...??? :see_no_evil: 

**Suggestion**
Ditch windowState _or_ ditch setMaximized(true) (_or_ read the complete solution over in closed PR's :speak_no_evil: )

**Comment by yairm210** [comment]
That's an interesting point... maybe it really is useless and all people really want is fullscreen
Sounds like a poll

**Comment by Gualdimar** [comment]
> That's an interesting point... maybe it really is useless and all people really want is fullscreen Sounds like a poll

For such users, there is a "fullscreen" setting in options. We can simply set it to be default.

**Comment by Gualdimar** [comment]
> So y'all have <=27"..

Yup, but instead I have 2 monitors☺
For debuggin I use windowed, for playing - borderless. 

But we are not considering removing the Screen Mode option, only changing its default value, right? Right?😟

If I remember correctly, setMaximized(true) was added to fix a bug that was later fixed in another way, so now it can be removed.
