### ISSUE TITLE
Incomplete notification text

### ISSUE THREAD

**Issue by balazsszalab** [yairm210/Unciv#8944]
The line bellow is displayed without any context what the event was:
due to our [unitName] being promoted = 
It should be part of a sentence, right?
See the picture
![scrnsht](https://user-images.githubusercontent.com/24574626/226054778-db915e6e-d445-4c9d-9ec0-4a3c23df715a.png)
I am not sure what happened before, but I think I have choose instant healing instead of a promotion. I hope this helps.

**Comment by yairm210** [comment]
What mod are you using? What uniques does that unit have in the mod?

**Comment by yairm210** [comment]
It's the first line in the second category

**Comment by yairm210** [comment]
Can you attach the saved game prior to picking the promotion? Load - show autosaves

**Comment by balazsszalab** [comment]
> What mod are you using? What uniques does that unit have in the mod?

Civ V - Gods & Kings

It was an Archer unit.

**Comment by balazsszalab** [comment]
> Can you attach the saved game prior to picking the promotion? Load - show autosaves

Sorry, I enjoyed playing and the oldest autosave is already from a few hours later. :D

**Comment by balazsszalab** [comment]
> > first line in the second category
> 
> Sorry, blind - the Troglodyte only knows one Hungarian word - "Barlang" - and it's too dark in there to read those pixels.

:) I wondered if I should apologise for having the screenshot in Hungarian, but I felt it would be lame, because the issue is not related to the actual language. Anyway, it is awsome that you recognised my language and you know something in Hungarian!

**Comment by balazsszalab** [comment]
> Can you attach the saved game prior to picking the promotion? Load - show autosaves

[Autosave-Carthage-225.zip](https://github.com/yairm210/Unciv/files/11010060/Autosave-Carthage-225.zip)

If I pick Instant Heal for the Knight which can be promoted, I can reproduce the issue.

**Comment by balazsszalab** [comment]
> Yup, I know Hungarians are cool and have nice Terrain and nice Terrain Uniques and [Natural Wonders](https://github.com/SomeTroglodyte/Aggtelek) - in Unciv terms...
> 
> Anyway, maybe `doDirectPromotionEffects` should be skipped if `UniqueType.SkipPromotion` - but my brain also hangs on the `none` in line 93 - shouldn't it search for triggerable not avoid? Also, there's 15 UniqueTypes with that target, and none sounds like promotions. Haven't yet understood or even tried to, but likely there's some tiny cog missing in the engine here? Just my superficial impression from searching in the sources for that string.

I am honored ;) I installed the mod, started a new game. What was the first natural wonder my warrior encountered in the second round? Yes, Aggtelek.
