### ISSUE TITLE
Do we want Language-dependent formatting?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#8954]
Currently, we display e.g. fractional movement points - or percentages in some stats breakdowns - using the system's locale. We _could_ use the Locale we can get from the user-selected language instead. Additionally, we could allow for non-latin Locales to come with different ways to show percentages (not necessarily using the `%` symbol) - there's an API for that in Java.

Options:
1) Ignore
2) Unify - keep using default Locale, but through a single API - either String.format (majority) or DecimalFormat (2 or 3 places)
3) Unify to String.format and supply the locale - that function has another overload allowing that.
4) Unify to NumberFormat.get*Instance - with caching the instance as long as language doesn't change, that should even be a teensy little bit faster. I tried this and it's easy enough. Advantage: No tricks needed to specify we want from 0 to N decimals omitting trailing zeroes... I wish I knew a Culture with different percentage formatting conventions to test the `NumberFormat.getPercentInstance` variant...

**Comment by yairm210** [comment]
I'm for 'ignore' for now... This sounds like another 'no one asked for this' translation thing

**Comment by yairm210** [comment]
We already have 130 open issues, no need to open ones that don't really exist 🙃
