### ISSUE TITLE
Feature request: New Country and improvement

### ISSUE THREAD

**Issue by Oleksandr0118** [yairm210/Unciv#8960]
Hello! Your game is very cool, but I have a few wishes, please add the country of Ukraine, and the Cossacks were not in Russia. In the history, the Cossacks were in Ukraine. Thank you!🇺🇦

**Comment by Skekdog** [comment]
The gams is based on Civilization V which does not have Ukraine as a nation.

However, you, or someone else, could make a mod for this.

**Comment by Oleksandr0118** [comment]
Ok, thanks
