### ISSUE TITLE
Religion allows to enter Overview as another player

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#8966]
If you click another player's city and then click on the religion symbol at the top left, you enter the overview as them. The city tab will show their cities (you can even enter their cities seeing production etc), the unit tab will show their units (you can also click on the unit and very bad things will happen if you haven't discovered the position yet).

Main problem is leaking information which might be especially bad for Multiplayer games. But in general this is broken quite bad, a little bit in a funny way.

**Comment by WhoIsJohannes** [comment]
Okay, it's actually worse than that. I can manage another players city entirety with this. Probably could even raze it.

**Comment by Gualdimar** [comment]
Oh, my. Nice😁
