### ISSUE TITLE
Display error when gifting units

### ISSUE THREAD

**Issue by Yennykates** [yairm210/Unciv#8977]
Version 4.5.10

Gifting units results in odd fog of war display. Same game as my previous find.
![Screenshot_2023-03-20-21-19-13-36_5b83b50424e447777d9855d9701553df](https://user-images.githubusercontent.com/124009690/226504276-4d46dbe9-ec09-4b87-9a63-f4317579404e.jpg)

**Comment by yairm210** [comment]
We made a shift from saving explored tiles in civ to the tile, we did not plan a system such as you're describing due to complexity. 
@Yennykates Which unit did you gift to who? We need to be able to replicate this

**Comment by Gualdimar** [comment]
fixed in #8974
after gifting a unit, the selected civ was not updated correctly. the screenshot shows that the selected civ = Hanoi
