### ISSUE TITLE
(Modded) game suddently crashes

### ISSUE THREAD

**Issue by A1y0sh4** [yairm210/Unciv#8996]
**Platform**
Windows (Desktop), latest update, 64 bit

**Version**
4.5.7-patch1 (Build 831), I downloaded it here (https://yairm210.itch.io/unciv)

**Describe the bug**
The game suddently crashes. It happened in a modded game where I was the spectator (I was doing some testing with my mod https://github.com/A1y0sh4/The-Great-Unciv-Rework)

**To Reproduce**
1. Simulate the game
2. Click on 'Next turn'
3. Wait
4. Game crashes

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```
[lasterror.txt](https://github.com/yairm210/Unciv/files/11041582/lasterror.txt)

```
</details>

**Expected behavior**
The game should keep running normally, without crashing or giving error messages

**Screenshots**

**Additional context**
I was using The Great Unciv Rework mod and also Thin Bubbly Borders

**Comment by yairm210** [comment]
Please attach saved game

**Comment by A1y0sh4** [comment]
> Please attach saved game

Is it this one?
[Crash - Spettatore - 132 turni.zip](https://github.com/yairm210/Unciv/files/11043228/Crash.-.Spettatore.-.132.turni.zip)
Anyway, I have updated my mod and I think to have found and fixed the error (altough I'm not sure. I hope that you would still find this file useful and not a waste of time)

**Comment by yairm210** [comment]
For me the saved game doesn't crash, so I'm not sure what to do with this issue... @A1y0sh4 still relevant?

**Comment by yairm210** [comment]
That's a good point, spectators shouldn't affect the game by definition.
I think that we can simply avoid their startTurn and endTurn doing *anything* and solve all such problem in one swell foop.
