### ISSUE TITLE
Can't use windowed mode

### ISSUE THREAD

**Issue by Gualdimar** [yairm210/Unciv#9001]
In the latest version I can't switch to windowed mode, nothing happens.
Full screen and borderless work fine.
@SomeTroglodyte, maybe related to #8973?

**Comment by Gualdimar** [comment]
Ahhhh, the windowed mode works, it's just that my borderless mode takes up the entire visible area on the screen and the frame does not fit (it used to work due to ` setMaximized(true)`). 
Maybe add some kind of check and, if the frame does not fit on the screen when selecting windowed mode, reduce the window size?

**Comment by Gualdimar** [comment]
> OK, so what do we do?

I would do something like this
```
onSceenModeChange(){
    if (screenMode == windowed && windowsSize == screenSize - taskbar)
        windows.setMaximized(true)
   else if (screenMode == borderless && windows.maximized == true)
        windowsSize = screenSize - taskbar
}
```

**Comment by Gualdimar** [comment]
> Can you confirm?

Sorry, there's a lot going on, I don't have enough time for this project now.
I hope I can find some free time soon...

**Comment by yairm210** [comment]
@Gualdimar do you still have this problem? I can't seem to replicate

**Comment by Gualdimar** [comment]
4.6.7 the problem still exists.
my screen resolution is 1680*1050 and the game creates the following settings file:
```{language:Ukrainian,screenSize:Large,tutorialTasksCompleted:[Open the options table],windowState:{width:1680,height:1010},multiplayer:{userId:3a243f20-8803-481d-b1f8-0e693f17a248},version:1}```
windowed mode by default, but I don't see the frame, switching modes does not change anything.

**Comment by Gualdimar** [comment]
> Steps, on a Windows 10 (not so on Ubuntu) box:

For me, it's enough to delete the GameSettings.json file and launch the game.
