### ISSUE TITLE
My game play isn't normal

### ISSUE THREAD

**Issue by Kimdwac** [yairm210/Unciv#9013]
**Platform**
Google play,(64/32 bit).

**Version**
4.5.11.

**Describe the bug**
![Screenshot_20230324-070533](https://user-images.githubusercontent.com/128753215/227375400-ecf8d0ff-9cc4-44c8-a940-b6874ab712be.png)
![Screenshot_20230324-070540](https://user-images.githubusercontent.com/128753215/227375406-4fce3c0f-0d9e-488b-a951-59de7ec57ada.png)

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**
![Screenshot_20230324-070533](https://user-images.githubusercontent.com/128753215/227375603-3d9ff6a5-b935-46a7-bf6e-0d76a77b203b.png)

**Additional context**
Sorry, I'm not good at English

**Comment by yairm210** [comment]
Update to 4.5.11-patch1
