### ISSUE TITLE
Feature request: License of AbsoluteUnits tileset

### ISSUE THREAD

**Issue by bits122** [yairm210/Unciv#9030]
**Is your feature request related to a problem? Please describe.**
I looked through credits.md and couldn't find any information on the license of the AbsoluteUnits tileset

**Describe the solution you'd like**
The license should be mentioned in credits.md

**Describe alternatives you've considered**
I also tried to look for it in the repo for AbsoluteUnits but couldnt find ~~it~~ the license there either.

**Comment by letstalkaboutdune** [comment]
> Sorry I worded that incorrectly I meant I couldnt find the license in AbsoluteUnits repo

Hi, I guess i haven't specified a license. Perhaps i should. Did you want to use the sprites for something?

**Comment by letstalkaboutdune** [comment]
> Definitely you should. More attention than your average mod. And explicitly stating it's your handiwork and maybe even tools used might be good. And should you choose a lic more restrictive than ours here, don't forget the core game needs to react.
> 
> By the way - excellent work.

Thank you! I'll probably use some kind of Creative Commons license. When I decide and implement in my repo I'll probably just PR an update to Credits.md as well.
