### ISSUE TITLE
Sources of quotes + help with Prophet Muhammad quote

### ISSUE THREAD

**Issue by balazsszalab** [yairm210/Unciv#9036]
Hi,

I suspect that the quote associated to Kremlin is made up:
'The Law is a fortress on a hill that armies cannot take or floods wash away.' - The Prophet Muhammed

Please, help me find the exact source of this quote if its genuine or if its a strong paraphrase of something else. However, if its fake, I suggest to replace the quote with another one.

I understand that quotes are the same as in Civ V games, but I do my best to find the exact English sources of them before translation. I do this for two reasons. First, I make sure that the quote is authentic. Second, I look for translated versions of the original in my own language. (I respect the work of translators before me and use their sentences if available. Besides that, those translations are more reliable and well written.) I translate only the missing quotes.

I could translate it with ease, but, as a man of science, I refuse to actively spread unverified information. I will skip translating this quote for now but keep working on the rest in order to enhance the already great gaming experience for the Hungarian audience of Unciv.

Thank you for considering my suggestion.

p.s.
I checked the sources bellow for keywords from the quote:
The Holy Quran at https://www.alislam.org/quran/Holy-Quran-English.pdf
The Hadith at https://www.holybooks.com/wp-content/uploads/The-Complete-Hadith.pdf

I have found that fake quotes were also noticed by several Civ fans at https://www.reddit.com/r/civ/comments/5fab7c/one_of_the_quotes_for_cartography_is_totally_fake/

I have also found an interesting note on this exact quote at https://www.reddit.com/r/civ/comments/y0nli/whats_up_with_the_quotes_for_the_alhambra_and_the/

**Comment by balazsszalab** [comment]
Regarding your first idea, in what form do you think these should be shared?
Regarding your third idea, there are so many quotes that it would take a long time to replace them all in English and to translate them into other languages. The majority is quite good, accurate and authentic by the way, I would keep them if you ask me.

**Comment by yairm210** [comment]
I'm in favor of keeping *all"* the quotes, even the fake ones. If we want to replace any we can poll those replacements individually.

**Comment by balazsszalab** [comment]
This website bellow is built around this problem. Seems great, I think it will be useful to identify candidates for replacement later.
https://quoteinvestigator.com/2020/08/19/plan-time/#f+438238+1+1

The link above will navigate you to the results of the research about Civ's Big Ben quote. It is very likely that this is another example for bad quote attribution. Suggested authors saying similar things are named in the article as well.
