### ISSUE TITLE
RFC: Unit Upgrade Tooltip?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9039]
![image](https://user-images.githubusercontent.com/63000004/227772436-15d9012d-6431-4829-be82-af90174de06c.png)

The Upgrade icon in Unit Overview has the exact same tooltip, and you can imagine it's more useful there, and no duplication of info.
Now this thing has quirks, and ironing them out may get tricky. Is this even **worth it?** What would _you_ replace that duplicate text with? "Key U: Upgrade" or...?

![image](https://user-images.githubusercontent.com/63000004/227772770-3b33e69c-e6e2-4fa6-bb41-81dbc7e93593.png)

**Comment by AdityaMH** [comment]
Look useful, but how about android user?
Also "tile info (right-bottom screen)" should doing same like that.

**Comment by yairm210** [comment]
We have a long click listener, right? Can we get this on long click so it will be available on Android out is this only for hover?

**Comment by yairm210** [comment]
The Civilopedia *does* know things that are nation-specific, I don't remember in what situations but it does crop up

**Comment by yairm210** [comment]
Whether or not it *should* is a subject for discussion I think, I'm not leaning either way
