### ISSUE TITLE
Regressions with Notifications

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9045]
<details><summary>Click between</summary>

See [NotificationsScroll lines 105, 106 comment](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/NotificationsScroll.kt#L105) - it was intended that the notifications log area would cover the underlying map for clicks entirely. Now you can select tiles - where the Category headers are. Or activate City buttons:

https://user-images.githubusercontent.com/63000004/227808990-d6b7aca2-2ce6-491b-a7ec-55987fbd0595.mp4

</details>

<details><summary>Scroll under TileInfo</summary>

Back then I invested effort to make the Notifications continue _under_ the TileInfo Table, and then ensuring one could scroll up far enough to read them all.. Gone. Thing is, situations like this:
![image](https://user-images.githubusercontent.com/63000004/227809021-d17a2370-4c47-493f-962d-7fa0af84dfb6.png)
...were not prevented by the old code, but were visually far less jarring. And it was a cool feature! My only mistake was - I should have let it go on to the buttom, behind the minimap too.

Pulled 4.4.0 jar from old releases:

https://user-images.githubusercontent.com/63000004/227809062-8a4a6c41-57f2-49b6-a4d6-969d8cbbecf2.mp4

Current master 4.5.13 compiled:

https://user-images.githubusercontent.com/63000004/227809083-4cd7f67f-295d-4115-bfa6-62e7a1835a91.mp4

</details>

<details><summary>Black Stat icon</summary>

Automatically inserted icons for Stats were an issue for quite some time, later circumvented (actually a kludge but it works nicely) - same can't be said for the Production category:
![image](https://user-images.githubusercontent.com/63000004/227809106-0b4ac69a-da9a-49fd-bad9-9932dd689afd.png)

</details>

So, do we want to do anything about any of these?

**Comment by Gualdimar** [comment]
> the Notifications continue _under_ the TileInfo Table

> I should have let it go on to the buttom, behind the minimap too.

Can you explain the point of this if you still can't read the notification until you scroll through the notification?
When I'm playing on my phone, sometimes I want to hide notifications altogether so that they don't take up space on the screen.
