### ISSUE TITLE
City-states use settlers

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#905]
AI must have found some hack around 135 of [`BaseUnit.kt`](core/src/com/unciv/models/gamebasics/unit/BaseUnit.kt) and sends settlers from city-states – 2.17.8

If not from production or ruins, may be captured?

**Comment by yairm210** [comment]
Known and fixed, the problem comes from them being able to pick policies, and there's a policy that gives you a seller
Discussed in the Discord ;)
