### ISSUE TITLE
No ocean generated on Archipelago map type.

### ISSUE THREAD

**Issue by Chek94** [yairm210/Unciv#9054]
**Platform**
Fair warning, the device this bug was encountered on frequently overheats and causes weird behaviour, most commonly crashing.
Latest Debian 11 at time of posting on the amd64 architecture, kernel version 5.10.0-21-amd64.
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)

**Version**
Bug encoutered in version 4.5.13 (Build 838)

**Describe the bug**
No ocean tiles are generated on the Archipelago map type.

**To Reproduce**
Generate an Archipelago-type map under any configuration.

**Expected behavior**
Ocean tiles expected.

**Screenshots**
![archipelago](https://user-images.githubusercontent.com/23719830/228061313-9d5356b4-2a7b-4953-abee-d757fb7c3973.png)

**Additional context**
Suspicion that bug was introduced by commit 7bc28c4 reintroducing the Perlin map type. Commit removes static increase of variable waterThreshold in method createArchipelago and lowers from 10 to 15 the default parameter scale of method getRidgedPerlinNoise also called from method createArchipelago. Both methods located at core/src/com/unciv/logic/map/mapgenerator/MapLandmassGenerator.kt. I could not be bothered to reinstall build tools to test a fix myself, so this is speculation only.

**Comment by yairm210** [comment]
Yes this is a big, that threshold removal was not intended to stay
Good catch!
