### ISSUE TITLE
AI not buying city tiles

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9059]
Is this an oversight or was it intentional to not make the AI do this? I personally do it a lot to secure luxuries or resources or just to grab land if another city is nearby.

**Comment by yairm210** [comment]
Not intentional, but also not a bug since it's not expected behavior

**Comment by WhoIsJohannes** [comment]
Why not? Can I add it? I think the AI would play better if it could do that.

**Comment by yairm210** [comment]
Sure, go for it
We just didn't think of it tbh :)

**Comment by WhoIsJohannes** [comment]
https://github.com/yairm210/Unciv/pull/9065
