### ISSUE TITLE
Feature request: MOD request: In Game Editor

### ISSUE THREAD

**Issue by toaddie49** [yairm210/Unciv#9064]
I dont know if there is a MOD request forum but here is where I found to post it

The old IGE from the 4-6 Civs was a big help testing MOD clusters for compatibility and stress testing memory loads in sandbox difficulty which I found and implored for now

The ability to actively modify terrain and resources for fixed map layouts was unrivalled when restarting map editors everytime you needed to field test got annoying

I dont MOD but I love seeing how tall I can make games through features added by MODs, but they often conflict and require starting whole games over on occassion and IGE could vastly improve my proccess

**Comment by SeventhM** [comment]
Closed as Solved/Unnecessary thanks to the console
