### ISSUE TITLE
Enable multiple plural noun forms in translations

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/Unciv#907]
The grammar phenomenon is well described here:  https://en.wikipedia.org/wiki/Polish_grammar#Numbers_and_quantifiers
It is present for all Slavic languages: (Russian, Polish, Bulgarian, etc..)
So when you grasp it, it becomes necessary to display _turns_ in the correct form, ex. in Russian

Currently it is displayed:
|
------------ | -------------
1 turn| 1 ход
2-∞  turns| 2-∞ ходов

Whereas correctly it should be:
|
------------ | -------------
| 1 turn | 1 ход |
2-4 turns | 2-4 ходa
5-21 turns | 5-21 ходов
22-24 turns | 22-24 ходa
25-31 turns | 25-31 ходов
32-34 turns | 32-34 ходa
..∞| 

 the function to get the correct form of a noun following a number as in ex above is simple: 
`turnsInPlural(n)=>n%10>1&&n%10<5&& (n<5||n>21) ? turns2-4 : turns5-21 ;`
and in a corresponding json ex.
```
"turn":{ // for e.g. "1 turn" to technology
		Italian:"turno"
		Simplified_Chinese:"回合"
		Portuguese:"Turno"
		French:"tour"
		Russian:"Ход"
		Polish:"tura"
},
"turns2-4":{ // for e.g. turns to technology
		Italian:"turni"
		Russian:"Ходa"
		Polish:"tury"
		French:"Tours"
		Romanian:"Runde"
		German:"Runden"
		Dutch:"Beurten"
		Spanish:"turnos"
		Simplified_Chinese:"回合"
		Portuguese:"turnos"
		Japanese:"回る"
}
"turns5-21":{ // for e.g. turns to technology
		Italian:"turni"
		Russian:"Ходов"
		Polish:"tur"
		French:"Tours"
		Romanian:"Runde"
		German:"Runden"
		Dutch:"Beurten"
		Spanish:"turnos"
		Simplified_Chinese:"回合"
		Portuguese:"turnos"
		Japanese:"回る"
}
```

without the noun differentiation above all is 100% comprehensible but sounds gibberish.

BTW is thereany other translated string, also being a separate noun or an expression finished with a noun, that is counted like _turns_?

**Comment by Iver88** [comment]
Your solution is completly compatible with czech language as well. We have 1 tah, 2-4 tahy a for higher numbers "tahů". I'll add this functionality in free time.

**Comment by Am-per-Sand** [comment]
Would be great if you could work some cross-language solution. Especially that, for ex., Baltic languages have a separate noun form for 11-19 (https://en.wikipedia.org/wiki/Lithuanian_grammar#Noun_modification_by_numeral). No idea how it works outside european languages, but may be even (more) different.

**Comment by Iver88** [comment]
Ok. It becomes more complicated right now. So I suggest one of these approaches: 

1. Do global support for plural in language files. Something like Turn[1] = Tah, Turn[1-4] = Tahy… And same method for gramathical cases. Advantage - simple, disadvantage - need constant updates.
2. Do global support for plural in language files using PO for example. No need for inventing of wheel. Advantage - robust, disadvantage - huge access to source code.

I am for 2nd approach. What you think @yairm210?

**Comment by yairm210** [comment]
In the end I replaced all "turn/turns" with an *icon* for turns.
That way we can avoid this problem entirely, without making a mess in the translation formats :)
If there are any other words that need similar pluralization, tell me and we'll try to iconize them as well
