### ISSUE TITLE
Empire science shrinks on shrinking treasury

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#908]
Is it possible to disclose somewhere (or fix if it has not been intended) how much total empire science level is reduced when total gold output is negative?

Now empire science equals summarized city science only when empire gains at least 0 gold each turn. As soon when gold gets expended more than accumulated, empire science gets reduced. Even more with every negative item of gold per turn. If not a bug, may be it would be possible to present this calculation on the empire stats screen?

**Comment by yairm210** [comment]
For every -1 gold, the empire also gets -1 science.
But you're right, this should appear somewhere.
