### ISSUE TITLE
AI very stupid in war

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9085]
The AI will just continue play as normal when they're at war and if their force is destroyed, they just happily hand over all of their cities (except for the capital) to reach a peace treaty.

I suggest to change the following (and I'm planning to start working on this soon):

- The AI should never give up more than 10% of their cities (or more than 1 if leq 5, no more than 2 if leq 20) to reach a peace treaty no matter the imbalance of force.
- once force becomes too low, the AI should go into full survival mode and start producing military units in all cities even cancelling existing build tasks and spend gold on military units
- this is a longer shot: if force is not in favor of AI then AI should withdraw and stick around their own cities, move ranged units into the city (and leave them there)

**Comment by WhoIsJohannes** [comment]
Potentially, but can't it simply be a "is in survial mode" flag that gets set if:

- The player is at war
- One of the other civs at war with has a military force 50% stronger than my own

THEN

- Go into survival mode for at least 10 turns
- Switch production of all cities to a military unit that takes leq 10 turns to complete.
- Buy ranged units in cities that are being attacked (proxy -> in cities that aren't at 100% health) -> This might need the AI to move out a unit that is currently in the city first, but I doubt it's worth the extra effort and can always come later.

**Comment by WhoIsJohannes** [comment]
Thanks for the insights! That sounds like a really cool approach. I think
I'll limit my changes to the things that feel buggy then and won't try to
make bigger overhauls other than following this path. I still think we can
go ahead with:

- Avoiding to trade exorbitant amounts if military force is near
non-existent (this feels like a bug to me, because if you trade away
everything you own including your cities, it's basically a slow suicide, so
no way this ends up being a smart deal)
- Switching your production to military once you're seeing a significant
decline in your military force and end up being much weaker than your
opponent seems reasonable, too and doesn't interfere with the Tactical AI
if I'm not mistaken.

Am Mo., 3. Apr. 2023 um 20:12 Uhr schrieb vegeta1k95 <
***@***.***>:

**Comment by WhoIsJohannes** [comment]
https://github.com/yairm210/Unciv/pull/9109
https://github.com/yairm210/Unciv/pull/9096

**Comment by WhoIsJohannes** [comment]
@vegeta1k95 So I finally got around to looking at the TacticalAI. While it looks really good and comprehensive, the main class alone has 10kLOC. This seems like a monumental task to port to Kotlin. I can't even estimate how many dependencies need to be ported as well. Did you already have any roadmap laid out or was there a particular process you were planning to follow to get this done? This seems far from trivial and probably so far 5% of the work was done. I don't mean to belittle your effort, just want to understand how and if we can actually complete this.

**Comment by qwerrtlo** [comment]
y

**Comment by SeventhM** [comment]
So, 2 questions:
1. Is this still relevant? Is the goal still to use Vox Populi as a reference? Genuine question
2. How much of this is necessary to copy Vox Populi? How much of this *can* we copy Vox Populi? How much of this would ccopying Vox Populi not work with how Unciv is otherwise built. If no one is actually working on this, I doubt someone new is going to go over the code and be able to port over all of the logic and dependencies, especially with any differences (intentional or otherwise) Unciv has from Civ 5

**Comment by tuvus** [comment]
>The AI should never give up more than 10% of their cities (or more than 1 if leq 5, no more than 2 if leq 20) to reach a peace treaty no matter the imbalance of force.

This should be fixed in #10370.

I agree with your last point and will see when I get around to it.

For now, I am going to close this since it is clearly stale, you can open a new issue with more up to date goals if you want.
