### ISSUE TITLE
Why translate city sound file names?

### ISSUE THREAD

**Issue by balazsszalab** [yairm210/Unciv#9086]
# Requires translation!
cityAncient =

etc.

These texts are not shown on the UI anywhere. At least I did not find them.
I found request #7163 where sound file names are corresponding to these texts.
What is the purpose of translating these anyway? Shouldn't they be removed from the translation template?

**Comment by Caballero-Arepa** [comment]
Those are the tags for the city music.

Idk if they are necesary to translate indeed

**Comment by Ouaz** [comment]
I think they do not need to be translated, but you have to if you want a 100% completion rate (in the options) for your language.
At least as long as these entries are in the translation files.
