### ISSUE TITLE
Tileset and Unitset names of default setup

### ISSUE THREAD

**Issue by usernamesimsisnotavailable** [yairm210/Unciv#9089]
I just love this game. Thank you.

Back then as a new user i was a bit confused wat were the default Tileset and Unitset. I tryed out some of them and i always get back to HexaRealm tileset and AbsouluteUnits. Big like to creators of them.

It is possible to "rename" those two into something like "UncivTileset" and "UncivUnits"?

It would make the game look more "complete" 

iI thik thowse 2 are preset on installation. I play the game on android and linux with the same settings of Tileset and Unitset.

Bg.

**Comment by yairm210** [comment]
Those are the names that the creators of the tilesets gave them, so we're not going to change their names :)
These names are also required for mods which add to these tilesets/unitsets to work correctly, so we can't change them without breaking a lot of things
