### ISSUE TITLE
Change Polgárőr to Városőr

### ISSUE THREAD

**Issue by d4f5409d** [yairm210/Unciv#9092]
**Platform**
-

**Version**
Latest

**Describe the bug**
The current translation doesn't mean what it meant to be in hungarian

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Please open a PR with the desired change as per https://yairm210.github.io/Unciv/Other/Translating/ - we don't track translation problems in Issues in this repo :)
