### ISSUE TITLE
Ranged unit can't attack city

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9097]
Digged through the code a bit and can't find the reason and now wondering if I'm missing some game mechanic here that makes this intentional?

Why can't the highlighted corssbow not attack the enemy city? I'm starting to wonder if this is somehow related to movable tiles being mixed up with tiles within range.

https://drive.google.com/file/d/131ygjzNj0GiEZUZLEe9NDis4-efeAzd6/view?usp=sharing

**Comment by yairm210** [comment]
Looks like you're in the middle of waiting for someone else's turn, so of course you can't attack...?

**Comment by yairm210** [comment]
To your left is a hill, to your right is a forest - no line of sight

**Comment by WhoIsJohannes** [comment]
Feel free to change this to a low prio feature request or close it, I don't know how to add the label (not sure I can).

**Comment by yairm210** [comment]
I'm considering this a 'wontfix' because I don't have a good *visual* solution for this problem...
If we don't get a good suggestion within a week I'll close this issue
