### ISSUE TITLE
Movement related improvements

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9105]
I have a few ideas how to improve movement, but before I dive in I'd like to discuss and I also have a few questions:

- Do we currently consider that things might become impassable once the initial shortest path has been established? E.g. if a city is founded, a non-open-border civ expands their borders etc.

In general I'd like to introduce penalties for certain paths to avoid the following two problems:

- AI embarking units all the time when they're basically sitting ducks for enemy planes and ships to be destroyed with one hit. Of course it's not always possible to avoid embarkation, but depending on the scientific progress of the other civs at war with, one should apply a hefty disadvantage to such paths.
- Units walking through unfriendly city states. Again this isn't always possible to avoid, but it should be avoided if the resulting path isn't significantly longer.

Most of this seems to be in UnitMovement#getShortest path. There's already some sort of disadvantage for embarkation, but I think it only works for paths that have the same length, so in practice it rarely applies.

**Comment by yairm210** [comment]
A. The shortest route is rebuilt every turn, we don't save it, because it can change for any one of a hundred reasons
B. Hefty disadvantage to water routes - even if they're faster? Not sure about that at all, maybe if there's a one turn difference

**Comment by WhoIsJohannes** [comment]
B. I had this situation many times where the AI embarks most of their units
and it's a single hit to kill for my city who are bombarding, airplanes or
naval units. I'm playing inner sea a lot, so maybe that's why they tend to
take those routes. My thought was something like accept 3 times longer
route if enemy has plains or ships close to the route.

Il lun 3 apr 2023, 18:43 Yair Morgenstern ***@***.***> ha
scritto:

**Comment by yairm210** [comment]
I don't play inner sea but I can see why that would require different tactics, but for a regular map that sounds pretty crazy
What we can do is A/B test this - put it behind a flag that players can turn on/off in options, have players try it out and see what they say

**Comment by WhoIsJohannes** [comment]
Even on a regular map, embarking units if there is a land connection (even
if significantly longer) feels like a terrible idea if the enemy can just
shoot them down on the water like sitting ducks, no?

Unless we activate this by default, I doubt a lot of people would actually
go and try and then again other than word of mouth we don't really have any
system in place to measure things, right?

That kind of brings me back to the simulation... I got it running
eventually, but it was awfully slow. I think a 1:1 on a Tiny map took like
3 minutes to simulate on my rather powerful machine. Any idea why it's so
slow? Could I disable the copying of the gameState maybe each turn? If we
get that to work we could actually automatically test which AI performes
better on average.

Am Mo., 3. Apr. 2023 um 20:38 Uhr schrieb Yair Morgenstern <
***@***.***>:

**Comment by WhoIsJohannes** [comment]
Found an old report reg explorers moving through city states:

https://github.com/yairm210/Unciv/issues/1814

**Comment by WhoIsJohannes** [comment]
That is true, running in debug mode is very slow, but I was talking about
the headless / UI less simulation. It doesn't use the debugger. I had to
hack the code into the desktop launcher as I couldn't get the console
launcher to work though, not sure if anybody else is still using it.

Il mar 4 apr 2023, 11:30 SomeTroglodyte ***@***.***> ha
scritto:
