### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9124]
Hello,

the current version of UnCiv is 4.5.16 according to GitHub, but on F-Droid only 4.5.10 is released. An update via GitHub is also not possible without a new installation due to the different signatures. Is it possible to update the F-Droid version?

**Comment by yairm210** [comment]
Looking at the latest build
https://monitor.f-droid.org/builds/build
It seems that it built 4.5.15 successfully
https://monitor.f-droid.org/builds/log/com.unciv.app/840#site-footer

So I'm not sure why it isn't available...
I don't control the f-droid release directly, all I can do is update the metadata, which is already updated
https://gitlab.com/fdroid/fdroiddata/-/blob/97fa5f0414e38f72b676f0ed6003ced4f10a6773/metadata/com.unciv.app.yml

**Comment by licaon-kter** [comment]
Was built in the current ongoing cycle... yes :) https://monitor.f-droid.org/builds/running

@marek22k https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by marek22k** [comment]
Well, but between two days and two weeks is already a difference. 4.5.10 was released two weeks ago. But nice to hear that there will be a new release soon!

**Comment by licaon-kter** [comment]
Previous cycle was delayed by some networking issues after the build stage.

We'll see how this one goes :shrug:
