### ISSUE TITLE
Feature request: Ability to import mod from a ZIP file or non-GitHub Repo / Enable download mods on IPv6-only devices

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9132]
Hello,

I would like to import a mod into UnCiv which is not on GitHub. When I enter the URL, "Invalid URL" appears. I can't copy any data to the Android/data directory (I guess because of Android 13). How can I download a mod and import it to UnCiv without it being on GutHub?

Is it possible to import a ZIP file?

(This feature request differs from #9123 in that I want to manually import the mod here.)

**Comment by yairm210** [comment]
I'm marking this as "won't fix" since it's a deprioritized issue.
If within the next year no one starts working on this I'll close the issue

**Comment by marek22k** [comment]
> We get Author and mod name from the repo so that would need replacements

Author Name could be taken from the ModOptions.json? And if this is invalid, you could reject the mod.

> We trust a zip to contain a subfolder named same as the repo

This could also be checked and if it is not the case, it could be rejected as invalid.

> The mod I tested with was badly bugged - came with a modOptions.json that was not loadable - and getting any sanity checks / exception messages back into the UI would need some more kludges

Couldn't you display a message like it is currently for non-GitHub URLs?

**Comment by SeventhM** [comment]
Since this is a mobile related question only, is it possible to establish a folder at <internal storage>/Unciv/Mods ? I'm sure this will probably require an extra permission, but it'll allow using the same system that Desktop uses to accept local mods.

**Comment by marek22k** [comment]
Another advantage of having an option to download mods from non-GitHub sources (regardless of whether ZIP or from Codeberg) is that IPv6-only devices can also download mods. Unfortunately, GitHub is IPv4-only. So for people who want to download mods on IPv6-only networks, this is currently impossible.
(I thought an extra issue titled "Failed to download mods on IPv6-only device" was a duplicate. Hence my post here)

**Comment by marek22k** [comment]
Please do not clone. @github-actions

**Comment by SeventhM** [comment]
Ngl, when I passed by this issue a while ago I somewhat wasn't paying attention and though it was more about accessing a mod outside of the Android/data folder in general. The idea of accepting any zip seems like it could be a pain all on its own, though
> As patch

Idk if OP would be open to this suggestion, but what of there was a way to just import zips? Not zip urls. Just zips that were already downloaded. Because that seems like something that could be much safer and easier for validation checking

**Comment by marek22k** [comment]
Bump

**Comment by The-Talik** [comment]
This seems stale, but this feature would be really nice.  Case example, is that I wanted to make a mod for just myself, and it seems there's no way to do that without publishing it to github, which muddies the mod portal with tons of stale, undescribed mods.

**Comment by yairm210** [comment]
I'm pretty sure that if you give a URL of a zip file it will download - is that not the case?

**Comment by marek22k** [comment]
> I remember this issue, but not the entirety of its title - "IPv6-only devices" is interesting, as IIRC there should be nothing blocking that.

Since GitHub does not support IPv6 and the mods are downloaded from GitHub - or am I missing something here?

```
$ nslookup github.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	github.com
Address: 140.82.121.3
```

**Comment by The-Talik** [comment]
> I'm pretty sure that if you give a URL of a zip file it will download - is that not the case?

It did not work for me.  My mod was super simple, so maybe it was missing something, or an issue around folder naming convention?  The same set of files worked in github.
Zip link (did not work): http://mezr.com/temp/TalRekMOD.zip
Github (worked): https://github.com/The-Talik/TalRekMOD

> Also, at a certain point what's the difference to unzipping yourself

In my case, I wasn't really looking to create a mod, just making some minor tweaks to my starting nation.  Unzipping yourself on a phone is a pain.

**Comment by The-Talik** [comment]
Try the url I posted with https, and it still won't download.  I used the proper url when I originally tested.  Just tested again to be sure, and couldn't get it to work.
But at the end of the day, I agree that some error messaging could go a long way to making this less of a problem.  Right now I don't see any indicator as to whether it was even successful or not, and if not, certainly no reason given.

**Comment by yairm210** [comment]
@SomeTroglodyte is there a reason to not allow redirects? The way you phrased it sounds like it's not a technical limitation

**Comment by marek22k** [comment]
It doesn't work for me either. No error message was displayed, only something (unsolicited and unasked for) was copied to my clipboard:
```
java.lang.NullPointerException
	at com.unciv.ui.screens.modmanager.ModManagementScreen$tryDownloadPage$1.invokeSuspend(ModManagementScreen.kt:283)
	at com.unciv.ui.screens.modmanager.ModManagementScreen$tryDownloadPage$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.modmanager.ModManagementScreen$tryDownloadPage$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.$r8$lambda$L3K1aau81hhVdGYYei_E7yWI2wU(Unknown Source:0)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1117)
```
URL was `https://codeberg.org/mark22k/UnCiv-Extra-Wonders/archive/main.zip`.
URL doesn't seems to be a redirect:
```
$curl -v https://codeberg.org/mark22k/UnCiv-Extra-Wonders/archive/main.zip
* Host codeberg.org:443 was resolved.
* IPv6: 2a01:584:31::1
* IPv4: 62.176.231.184
*   Trying [2a01:584:31::1]:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=codeberg.org
*  start date: Jan 31 22:11:57 2025 GMT
*  expire date: May  1 22:11:56 2025 GMT
*  subjectAltName: host "codeberg.org" matched cert's "codeberg.org"
*  issuer: C=US; O=Let's Encrypt; CN=E5
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to codeberg.org (2a01:584:31::1) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://codeberg.org/mark22k/UnCiv-Extra-Wonders/archive/main.zip
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: codeberg.org]
* [HTTP/2] [1] [:path: /mark22k/UnCiv-Extra-Wonders/archive/main.zip]
* [HTTP/2] [1] [user-agent: curl/8.12.1]
* [HTTP/2] [1] [accept: */*]
> GET /mark22k/UnCiv-Extra-Wonders/archive/main.zip HTTP/2
> Host: codeberg.org
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 200 
< accept-ranges: bytes
< access-control-expose-headers: Content-Disposition
< cache-control: private, max-age=300
< content-disposition: attachment; filename="UnCiv-Extra-Wonders-main.zip"; filename*=UTF-8''UnCiv-Extra-Wonders-main.zip
< content-length: 46166
< content-type: application/octet-stream
< last-modified: Tue, 25 Mar 2025 21:03:58 GMT
< link: <https://codeberg.org/api/v1/repos/mark22k/UnCiv-Extra-Wonders/archive/dbf5d5d39b45215c51dd3e372edd8e1769b0a3e6.tar.gz?rev=dbf5d5d39b45215c51dd3e372edd8e1769b0a3e6>; rel="immutable"
< no-gzip-compression: 1
< set-cookie: i_like_gitea=d7047798a5ef36f7; Path=/; HttpOnly; Secure; SameSite=Lax; Secure; SameSite=Lax
< set-cookie: _csrf=5vd0xyBO1ajqzKSiAek4o2neXm86MTc0MjkzNjg3MjY1NDg1NjcyOA; Path=/; Max-Age=86400; HttpOnly; Secure; SameSite=Lax; Secure; SameSite=Lax
< date: Tue, 25 Mar 2025 21:07:52 GMT
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< permissions-policy: interest-cohort=()
< x-frame-options: sameorigin
< x-content-type-options: nosniff
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell curl 
Warning: to output it to your terminal anyway, or consider "--output <FILE>" to 
Warning: save to a file.
* client returned ERROR on write of 484 bytes
* Connection #0 to host codeberg.org left intact
```

**Comment by marek22k** [comment]
Perhaps the issue could be reopened while the problem persists? (I can't do that as I haven't closed it).

**Comment by marek22k** [comment]
Correction: In my opinion, the issue can be closed successfully (currently closed as not planned). I just tried it and I was able to download a mod.
