### ISSUE TITLE
Can`t pass my turn to another player

### ISSUE THREAD

**Issue by V-tanke-gorel** [yairm210/Unciv#9169]
**Platform**
multiplatform(PC 64x/Android)

**Version**
try many different version(4.5.7patch1/4.5.13./4.5.16./4.6.0)

**Describe the bug**
Have multiplayer game with my friends on Dropbox
game ID: f95efbe6-eb76-465e-bbce-ecf20b65c33f
the player on Germany(ID: 246a78e9-f8ac-4e5f-a337-d44e50652e07 ) cannot pass a move to the next player(england ID: 0823ffa9-eda4-4e49-98db-d228a895d117)
When he click on next turn button the move seemed to be passed, but in fact it was not, and the other players waiting Germany

**Screenshots**

![photo_5_2023-04-11_15-48-18](https://user-images.githubusercontent.com/130439173/231166982-c3bf44f9-ad44-4780-a435-4da16679cf14.jpg)
![photo_1_2023-04-11_15-48-18](https://user-images.githubusercontent.com/130439173/231167018-a6ec6abb-7f87-4a5f-a376-bf7b0ce0d1ca.jpg)
![photo_2_2023-04-11_15-48-18](https://user-images.githubusercontent.com/130439173/231167029-fc54f6e1-4555-4002-9219-fd08c2fd0f89.jpg)
![photo_3_2023-04-11_15-48-18](https://user-images.githubusercontent.com/130439173/231167041-cca8842b-f8a2-4205-88a2-39e8d472880f.jpg)
![photo_4_2023-04-11_15-48-18](https://user-images.githubusercontent.com/130439173/231167046-9a32818f-6952-4c7b-bd2e-be139b982162.jpg)

**Comment by yairm210** [comment]
Game could not be found on server
What server are you using? (Options > Multiplayer > Server address)

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/231806527-57c8f4c9-e8cb-4a89-86f3-aa45a7ba131f.png)

This is the root cause
My advice is to move to the official server, uncivserver.xyz, I'll see what I can do for Dropbox but we're basically not using it anymore

**Comment by V-tanke-gorel** [comment]
Yes, now it`s working. Great thanks to you. 
I have one more questions. Can we relocate this game on official server

[Carthage - 96 turns.zip](https://github.com/yairm210/Unciv/files/11224629/Carthage.-.96.turns.zip)
