### ISSUE TITLE
Tileset changes back to HexaRealm every session 

### ISSUE THREAD

**Issue by ZGinner** [yairm210/Unciv#9177]
Android, version 4.6.0 (Build 845)

If you select any tileset other than HexaRealm, the change is discarded when you restart the app.

1. Change tileset to FantasyHex or Minimal
2. Restart app
3. Tileset changes back to HexaRealm

**Comment by Caballero-Arepa** [comment]
It happens to me as well.

I have Civ 6 tiles on, marked as permanent audiovisual, and when I close and open the app it goes back to Hexarealm.

The settings stick over the restart, and so I can change it back in the settings.

It only happens with tiles, with units it doesnt.

**Comment by Caballero-Arepa** [comment]
Hmmm, I think both is true, as it only started to happen after I installed the mod.

Idk, would have to test later, and if it happens on PC

**Comment by yairm210** [comment]
Tested on Android for both internal tilesets and mod tilesets (specifically FantasyHex and Civ6)
