### ISSUE TITLE
Bismark's English script has a German spelling mistake

### ISSUE THREAD

**Issue by balazsszalab** [yairm210/Unciv#9186]
'Guten tag.' should be written as 'Guten Tag!'.
German nouns begin with capital letter and the usage of exclamation mark is more widespread in German.

**Comment by Ouaz** [comment]
May I add that there's a misspelling for `Atilla's Court`. Should be `Attila's Court`.

Definitely two gamebreaking bugs! :rofl:

**Comment by balazsszalab** [comment]
OK, that response felt more rude than funny. I am cofused now whether my report were welcomed or not.
In case you are welcoming spelling related observations, but my approach of reporting it was improper, please, show me the proper way.
1. I don't insist using the 'bug' label for reporting issues in the translation template, but it is certainly not a 'feature'.
2. I decided to keep my reasoning as short as possible. I thought you had to read a lot of bug reports anyway, so I'll keep mine short and easy to process. Should I strive to avoid seeming too pedantic?

I stand by both statements I made earlier: I. 'German nouns begin with capital letter' and II. 'the usage of exclamation mark is more widespread in German' compared to English. I didn't state that Germans are keen on using exclamation marks.

I think your game is the best open source Android game and I am motivated to help you improve it. You have a better idea how popular your game is, but I bet it is very popular. Many kids and adults are interacting with it and they are learning not only strategic thinking but cultural references and linguistic patterns too. That is why I think it is a good idea to draw you attention to such nuances. At the same time, I respect your creative freedom.

**Comment by Ouaz** [comment]
Ha ha, thank you for taking time to post a report. But we simply like to be sarcastic around here. ^^

And, for my part, I'm very nitpicky too about typos, misspellings, or whatever's wrong with in-game texts (like the inversed HP in current battle table... _wink_ _wink_ _wink_)

So, you report is welcome!

Like someone said : "_It's the little details that are vital_".

**Comment by Ouaz** [comment]
<details>
<summary>My OCD syndrom doesn't like that</summary>
<img src="https://user-images.githubusercontent.com/11946570/232255549-f9151fc9-4c85-42fb-9337-39b572445a71.png">
</details>

:see_no_evil:

**Comment by Ouaz** [comment]
<details>
<summary>Here we go again :laughing: </summary>
It's the direction that matters, not the reading or the "say" of it.

If these numbers were a part of the health bar (like in any videogame), it would be ordered A-B-C, to keep logic and consistency with what the bar shows just above.

Actually, there was a huge discussion about that on Discord, and even poll. _Statu Quo_ has won. (~60/40)

People who lost has just to live with it (and their OCD syndrom :rofl: ).
</details>

I put everything into spoiler tags, because I don't want to be scolded again, because I speak oft that... again. :grin:

**Comment by Ouaz** [comment]
> But I still can't visualize what exactly you'd be happy with!

**Currently:**
![current](https://user-images.githubusercontent.com/11946570/232338777-72958d8b-2a1b-459f-af29-6a731171acc3.png)


**1st suggestion: HP numbers on/off setting** (simplest fix ^^)
A setting in Display > Interface:  `[ ] Show HP numbers in battle table`. If unchecked, no numbers, so people with OCD are happy again.
<img src="https://user-images.githubusercontent.com/11946570/232338841-8da980e9-d04c-4a2e-bd3c-5cc5ccd29c27.png">


**2nd suggestion: Detailed data**
As people finds  `100 -> 83-74` is not a logic way to write the HP (despite the bar above showing exactly that), detailed data is used instead, and vertically for direct comparison:
![detailed_hp](https://user-images.githubusercontent.com/11946570/232343249-8a5e6242-0f2d-4984-9a6c-a57e43ed6b7a.png)


**3rd suggestion: Big Bang overhaul** (designed by @letstalkaboutdune )
![big_bang](https://user-images.githubusercontent.com/11946570/232341913-5d2b1316-6bd1-46a9-8a55-e8ba059f135b.png)
- Vertical HP bars for direct comparison.
- Simplified text bonus for better readability and more compact battle table.
- Bonus texts are linked to their corresponding Civilopedia artices if the player needs more information.

The 1st suggestion would make my day, if the other ones are to much a hassle to implement. :smiley:
