### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by Filius-Patris** [yairm210/UnCiv#919]
I'm in the process of submitting `com.unciv.app` to the F-Droid repository, as I have already discussed with yairm210 via Email. Progress is to see [here](https://gitlab.com/fdroid/rfp/issues/1027) (help is also appreciated).

I am opening this issue for the following reasons:
 - To publicly get the approval of @yairm210 (please confirm my efforts in a comment).
 - To cite all relevant PRs
 - Annotate that F-Droid submission is WIP
 - Get help from others, who know this project better

**Comment by Filius-Patris** [comment]
One suggested improvement was made by the F-Droid bot [here](https://gitlab.com/fdroid/rfp/issues/1027#note_187318632):
add the distributionSha256Sum property.

A corresponding PR is already issued: #918

**Comment by yairm210** [comment]
Confirmed

**Comment by Filius-Patris** [comment]
One problem that's in the way is that the version number is always one behind the git tag.
I'd submit a PR, but I'm struggling with git, so If sombody's gonna be faster... Thanks ^^

**Comment by yairm210** [comment]
The git tag is the latest version, that's rolling out.
Since the releases are back-to-back, this means that you're usually accessing the previous version, because the latest one hasn't reached you.

**Comment by yairm210** [comment]
Is this done? Is the issue closable?

**Comment by Filius-Patris** [comment]
Nope, sorry.

However since they have a seemingly long pause, I'll close the issue and reopen it on further activity over at F-Droid.

**Comment by Filius-Patris** [comment]
So it seems to have been added to the F-Droid repository by [fdroiddata@42da13ee](https://gitlab.com/fdroid/fdroiddata/commit/42da13eeac4a4b99e1e517158d46ecad0b2045a3). I don't know how long it takes to be availible for end users, but I'm confident.

**Comment by Filius-Patris** [comment]
I just downloaded and installed Unic via F-Droid!

https://f-droid.org/en/packages/com.unciv.app

**Comment by yairm210** [comment]
Cool! :)

**Comment by licaon-kter** [comment]
@yairm210 Currently the autoupdating is broken, versionName/Code are always oen version behind, any reason not to update build.gradle versionName/Code first and then Tag an actual release?

Eg. Tag 3.1.12 builds an APK with version 3.1.11
`ERROR: Could not build app com.unciv.app: Unexpected version/version code in output; APK: '3.1.11' / '316',  Expected: '3.1.12' / '317'`

**Comment by yairm210** [comment]
Okay, if that's the problem I'll be more careful about that =)

**Comment by licaon-kter** [comment]
@yairm210 Still and issue. Eg. You've tagged 3.6.15 but since [you don't have static version*](https://github.com/yairm210/Unciv/blob/master/android/build.gradle#L24) we can't use that to pick up new releases, we need to pick them up from [elsewhere](https://github.com/yairm210/Unciv/blob/master/build.gradle#L36) where the version is more or less one step ahead, and no corresponding tag to build.

**Comment by yairm210** [comment]
About the non-static version I understand. Is it just the number or also the name that you need to be static?

About 'no tag', not sure what you mean.
![image](https://user-images.githubusercontent.com/8366208/78540177-6e0c8680-77fc-11ea-8852-14974b068aa4.png)
I've been very careful to always have a special commit for the version incrementation, marked by its own tag. Do you need the tag to come on a commit *after* the version incrementation?

**Comment by licaon-kter** [comment]
> About 'no tag', not sure what you mean.

F-Droid reads 3.7.0 since your `build.gradle` says so. No tag for that _yet_.

The problem is that you modify the version ahead of time. The ideal situation would be that you modify version* _when_ you Tag a release.

**Comment by yairm210** [comment]
Okay, gotcha
So basically from now on - 
- Create local commit
- Tag that commit locally
- Push commit and tag together
