### ISSUE TITLE
Pixel glitches with RulestObject-as-text

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9194]
Your new `Fonts.getPixmapFromActor` shows some marginal glitches.

![image](https://user-images.githubusercontent.com/63000004/232209072-a3d47c32-dcdd-432a-b5ee-e2a7175c7fd3.png)

What should be transparent seems to copy some random pixels, and the most interesting thing is they're not the same for both renders in this screenshot. I'd assume the function is run only once per Actor and the result stays cached in the font? Maybe that's a hint...
http://docs.gl/gl4/glReadPixels speaks of undefined pixel values, though lwjgl3's version is more specific: `If any of these pixels lies outside of the window allocated to the current GL context, or outside of the image attached to the currently bound read framebuffer object, then the values obtained for those pixels are undefined. When READ_FRAMEBUFFER_BINDING is zero, values are also undefined for individual pixels that are not owned by the current context.` - well, _that_ FrameBuffer isn't bound. And simply binding it **_does_** seem to help... Though I don't understand why that does not thoroughly jumble the screen right after the RulesetObject `Char`s are done...

With `frameBuffer.bind()` call:
![image](https://user-images.githubusercontent.com/63000004/232227148-215f723c-8bba-4eee-9702-2505cea5097a.png)

The following double tinting, however, is certainly unrelated and simply ye ol'e 'why we have ColorMarkupLabel' issue:
![image](https://user-images.githubusercontent.com/63000004/232209328-a8378c05-94a6-433f-a2bd-06d63a15f5fc.png)

The following observation merits thinking about: We pull a part of a TextureRegion loaded using an atlas, draw it onto a screen-sized FrameBuffer, then read out those pixels, swap them one by one, lastly store and pack them into another TextureRegion (in NativeBitmapFontData.getGlyph)... Which prompts 1½ thoughts: Why not copy directly? Or _use_ directly? Is scaling to ORIGINAL_FONT_SIZE the only added value? Smells like a lot of optimization potential.

And - will we get a Mod with >8192 ruleset objects?? Now that the limit exits, Murphy will surely start modding :zany_face:

**Comment by yairm210** [comment]
So then bind sounds good :)

The reason for not using txtures directly is that almost all objects in Unciv aren't displayed directly as tectures - instead we take an image, color it perhaps, wrap it in a circle (maybe colored), sometimes wrap *that* in a circle, and *that's* the final image
If we want all of that to be rendered so it's always the same visual cue for the user, it's much easier to take the built Group and render that than it is to try and rebuild the same Group using texture copies

**Comment by yairm210** [comment]
The framebuffer *is* bound though... frameBuffer.begin() calls bind() as its first action 😕

**Comment by yairm210** [comment]
Do you still see this happening? Maybe it was solved with the disposal?

**Comment by yairm210** [comment]
I did once, but no more, hence the uncertainty
If within, say, 2 weeks there are no reports, I'll consider this closed
