### ISSUE TITLE
[Suggestion] Icons display in notifications 

### ISSUE THREAD

**Issue by Ouaz** [yairm210/Unciv#9197]
Now that SomeTroglodyte added notification categories on the world map (units, war, etc.), and that now, there is also icons before object names, maybe how/which icons are displayed in the notifications could be modified.

Currently, we have icons before each object in the notifications (that looks very good imo), plus the old summary on the right (`iconA` x `notif. type icon` x `iconB`).
My suggestion is to keep icons before each object in the line (Me think its makes things tidy and neat), and only keep the `notif. type icon` on the right (samurai helmet for combat, skull for death, research icon for researched tech, etc.).

As I think Yairm will call for a democratic choice, here's the mockups:

Current:
![a_current](https://user-images.githubusercontent.com/11946570/232254856-063baa5e-1332-4e38-b2bc-c2c96488552d.png)

Suggestion:
![b_suggest](https://user-images.githubusercontent.com/11946570/232254864-ea7ba52e-ac71-46ff-82a5-1ff18d4b9251.png)

Old:
![c_old](https://user-images.githubusercontent.com/11946570/232254884-656f211d-846e-4f1c-8606-8c5afc0bd631.png)

<details>
<summary>Nota Bene</summary>
B looks so neat, isn't it. :sunglasses:
</details>

Sorry for the pixelated/not smoothed font and icons, Unciv running here with an old java 1.8 on an old laptop. I play on Android anyway, where everything is crisp.

**Comment by Caballero-Arepa** [comment]
> B looks so neat, isn't it.

Ye bro

**Comment by yairm210** [comment]
Due to performance reasons, we need to disable icons in the notifications...
I hope we'll be able to load notifications gradually or something to avoid the 'freezes entire game while trying to render notification icons' problem but for now this is out :(
