### ISSUE TITLE
Policy screen blanks out

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9198]
Android Galaxy s10/build 848

Since build 848, in the policy screen, when choosing/tapping on a policy, sometimes the screen will blue-blank out, 100% flat blue background. Tapping the screen again usually puts it back to the policy screen, but once in a while there's no fixing it and the app must be restarted. I emphasize sometimes, where for periods the behavior is persistent, other times everything is fine. I don't recognize a specific pattern nor method that triggers the behavior.

**Comment by hackedpassword** [comment]
> Which exact Android is that S10 running
Android 12, latest updates, no root, no fancy UI modifiers. 

> Is there really no correlation to which policy you select? Do the headers maybe behave differently (only they can change the screen layout)? Maybe only a certain policy (maybe having an object type in its description others have not)...?

There is no correlation, no specific policy. I'll try tracking each instance to perhaps produce a breadcrumb trail.

> Reaction to orientation change (with follow orientation enabled)?

Locked in landscape per game settings, OS auto rotation. No issues til this update. Will attempt rotations when this happens. 

> How do you restart when you say "must"? Home screen - back to app? Or Home screen - swipe app out of recent list - start app? Or maybe even developer options "Kill foreground app"?

Going directly to recent list and swipe it out, tap the app to begin again (only when the blue-blank won't be fixed by another tap). Haven't killed the app via any process mechanism. Going to Home and back to the app does not solve the issue.

I did notice the newly updated Display menu (looks nice btw). Experimental rendering and demographics are on. Screen mode default, size medium.

Anything else you feel would be helpful let me know. I'll be back with those breadcrumbs but that will take some time.

**Comment by hackedpassword** [comment]
I'd rather not get all system-y with my phone, even though that process looks safe enough. I posted a video of the behavior in discord #bugs. Strangely the behavior was less frequent with screen record on.

I tapped randomly like that for a while, and every few to every dozen+ policy taps would blue-blank. Doesn't seem to happen with the headers. Strangely, rotating the screen does unblank the screen just like a tap.

Tapping the same policy repeatedly for a minute causes no blanks. I'm finding there's sometimes periods without the issue.

848 happened while I was amidst a game in rekmod. So I just tried a new game in vanilla, same behavior, still blanking.

**Comment by yairm210** [comment]
This is probably related to the RAM crash that others hae reported, should hopefully be solved in the version rolling out

**Comment by yairm210** [comment]
The renderer runs once per icon, so if the gl objects aren't disposed then pile up

**Comment by yairm210** [comment]
Solved in 4.6.4-patch2
