### ISSUE TITLE
Ottoman units doesn't work properly

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#920]
Hi, playing as ottomans and my janniseries don't heal when they kill and my trirems never capture boats. I tried it against barbarians only, does it matter?

**Comment by yairm210** [comment]
Triremes don't capture boats - that's for a different version of Civ V, not in Unciv
Janissary heal problem - could you send me the game data (menu, save game, copy to clipboard, paste to email to yairm210@hotmail.com)?

**Comment by amirberner** [comment]
It says in the description - melee naval units have the prize ships
promotion, allowing them to capture ships.
I will play again as the ottomans and see if the janniseries still don't
get healing after they kill units


בתאריך יום ה׳, 4 ביולי 2019, 19:52, מאת Yair Morgenstern ‏<
notifications@github.com>:

**Comment by yairm210** [comment]
Fixed, is rolling out in 2.17.14 =D
