### ISSUE TITLE
You can trade a resource before researching it, but it doesn't show on the top

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9211]
See title. I traded oil before researching Biology, I can use the oil to build planes, but I can't see on the top that I have it.

**Comment by yairm210** [comment]
You should be able to trade *for* a resource before you have the tech to make it yourself.
Is that the situation?
Or did you manage to trade it *away*? Because that's a bug

**Comment by WhoIsJohannes** [comment]
No, I got it, it's all fine. This is only a UI problem. The top bar does not show this resource. Does it add other such traded resources to the count if you already have discovered the resource? I believe so, correct?

**Comment by yairm210** [comment]
Yes
I see your point - if you traded for a resource before you yourself have revealed it, it should indeed be shown on top bar
