### ISSUE TITLE
`Requires a [Building] in at least [Amount] cities` do not work with one-city challenge

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9242]
**Describe the bug**
Hello,

I have tried the One City Chellange in UnCiv. I noticed that a mod I created and play with has the condition `Requires a [Emergency service] in at least [4] cities`. But I can never fulfill this condition if I can have only one city. Is it possible to automatically change this condition to `Requires a [Emergency service] in at least [1] cities` when playing the one-city Chellange?

**To Reproduce**
1. Create buildings with a condition like `Requires a [Emergency service] in at least [4] cities`.
2. Create mod and load it into UnCiv
3. Play the one city Chellenge
4. Building cannot be built

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
I get `Comment is too long (maximum is 65536 characters)`
https://paste.i2pd.xyz/?8ba88afe7648d145#3bpeTHPZzWWG7MV9RuniWqrqPg5KARvffGXWG3ZRNh3P

**Expected behavior**
Building can be built

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/46723399/233568076-83955171-ed6b-4ad7-9fb0-a4785692b07c.jpg)

**Comment by marek22k** [comment]
Alternatively, perhaps hide the corresponding buildings?

**Comment by yairm210** [comment]
Looks like "working as intended" to me, definitely not a bug.
 We could hide those buildings but that's a feature request
