### ISSUE TITLE
Alert "We have encountered City-State" for a dead CS

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9245]
**Describe the bug**
For a test I started with an AI Austria and gave them 9000 gold. Within the first 12 turns max they found Kabul, allied, and diplo-married them (with two notifications - marriage and destroyed - though I had met neither). Much later, I get the "We have encountered the City-State of Kabul" start-turn Alert, but no corresponding notification.

Saved game - this form as the exact state (alert right on opeining) is only available as Autosave and can't be saved manually to clipboard. Possibly the turn before is needed instead - I'll see.
[Meeting the Dead.zip](https://github.com/yairm210/Unciv/files/11294525/Meeting.the.Dead.zip)

**Additional context**
I will continue lookin into this unless I get distracted...

**Comment by yairm210** [comment]
1 sounds good :)
2 - definitely not, want them to retain ally status if resurrected
3 - not necessary if we do 1, I think
