### ISSUE TITLE
Feature request: New chart showing number of followers of a religion

### ISSUE THREAD

**Issue by Lesiakower** [yairm210/Unciv#9253]
The newly-added charts are a very handy feature and I have no problems with them, but...
could you please add a chart showing spread of  a religion (number of followers). It would be very useful, in my opinion.

**Comment by Ouaz** [comment]
I think that's a good idea, espacially as it can vary a lot without the player noticing it, except from a sudden loss of ressources (the AI spawning a lot of Inquisitor/Missionary, removing sneakily the player's religion).

In the meantime, you have the "numbers of followers" value in Overview > Religion.
