### ISSUE TITLE
Select enemy

### ISSUE THREAD

**Issue by itine** [yairm210/Unciv#9262]
**Describe the bug**
please fix the ability to select the enemy to bombard. after choosing a city, it is difficult and sometimes impossible to select an opponent unit. 

![Screenshot_2023-04-23-19-42-11-007_com unciv app-edit](https://user-images.githubusercontent.com/16553609/233853333-2f8aa13e-9533-44db-911a-16f0deed8038.jpg)
![Screenshot_2023-04-23-19-48-29-798_com unciv app-edit](https://user-images.githubusercontent.com/16553609/233853334-dbe49739-d1ef-43de-9384-0edfe535b71d.jpg)

**Comment by yairm210** [comment]
What you need to do is to *deselect* the current city/unit by clicking the X on the left of the unit take (bottom left), then click on the enemy. The city will automatically be selected.

Unless you have an idea of how we could fix this?

**Comment by itine** [comment]
Thank you. 

as idea: perhaps you can decrease popup buttons when player will zoom in screen

**Comment by yairm210** [comment]
That's a good idea! I'll try it out
