### ISSUE TITLE
CityStats.update is a performance bottleneck

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9270]
From my cap the call from GameState.setTransients took more than 10% of total processing time for a new turn. But there's a lot more call-sites. I don't really understand what it's doing and why it's so expensive. What's up with the stats for next turn that recursively calls it yet again? Can we simplify that? Can we reduce the second round to only look at happiness? What's up with that?

**Comment by yairm210** [comment]
"bug" has a very specific meaning, it means "the game was supposed to have implemented functionality X and it is not working".
Please mark performance, feature, etc as necessary, don't lump them all together

**Comment by yairm210** [comment]
You need to drill down more into the update() to figure out what's actually taking time though

**Comment by WhoIsJohannes** [comment]
Sorry, I don't think I can file anything else than Bugs and I also don't
think I can change the label unless I'm missing where to do that.

The first problem is the number or callers for this function. I'm almost
certain there's a lot of redundancies. I couldn't find a clear culprit
within the method, it's just complex and seems like everything just takes
time in equal parts, but all in all this seems to be the single most
important place to improve.

Any idea how to speed it up beyond what you already said about the second
pass?

Il lun 24 apr 2023, 16:24 Yair Morgenstern ***@***.***> ha
scritto:

**Comment by yairm210** [comment]
I'd need to see the proper drilldown of the function, anything else is just guess-based-development

**Comment by WhoIsJohannes** [comment]
![Screenshot from 2023-04-24 22-21-27](https://user-images.githubusercontent.com/126110113/234108097-3967db41-25fa-4b04-b13f-91dccaa52613.png)

Does this help? It's not really a single point that is slow. I just think the whole method is very complex and we just need to be careful that it isn't ran more often than necessary.

**Comment by yairm210** [comment]
Addressed this a while ago
