### ISSUE TITLE
Loading error from saved game

### ISSUE THREAD

**Issue by Boombastic76** [yairm210/Unciv#9298]
After loading an game from an autosave file I experienced the error in the attached file.

![Screenshot_20230428_134744_Unciv](https://user-images.githubusercontent.com/131948784/235143482-60b138b7-be52-4ca7-8a42-0e6f926cb03c.jpg)

**Comment by yairm210** [comment]
If we can't replicate this then we can't solve it
And your didn't attach a file

**Comment by Boombastic76** [comment]
How to attach a file? If I paste the copied data from clipboard it gives me a big set of data that is not attachable here. I can try it with the given email address instead.

**Comment by Boombastic76** [comment]
/

> How to attach a file? If I paste the copied data from clipboard it gives me a big set of data that is not attachable here. I can try it with the given email address instead.

**Comment by Boombastic76** [comment]
Tried it via email - text to long too. Do I have to save that to a particular file?

**Comment by yairm210** [comment]
That could work, save that to a file and send the file via email / attach here as file

**Comment by Boombastic76** [comment]
Hello,So here is the data from the newest save game. Regards,Boombastic76Gesendet von Outlook für AndroidVon: Yair Morgenstern ***@***.***>Gesendet: Samstag, 29. April 2023, 20:26An: yairm210/Unciv ***@***.***>Cc: Markus ***@***.***>; Author ***@***.***>Betreff: Re: [yairm210/Unciv] Loading error from saved game (Issue #9298)That could work, save that to a file and send the file via email / attach here as file—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Boombastic76** [comment]
I sent it via email as *.docx. Let's hope it helps anyway. 

Another note to further solving the problem: The save file works after the first rounds. It stops working at a certain point while progressing into the game.

**Comment by yairm210** [comment]
Issue was handled via email thread
