### ISSUE TITLE
Question: addRulesetImages doesn't include Policies

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9304]
... and that can look a little strange in places. Like battle modifier lists.
![image](https://user-images.githubusercontent.com/63000004/235495290-9792060c-fb2c-4c41-a1b3-36c7b284c123.png)

Is that maybe intentional as there are no icons for the branch starters/completers? Maybe we should think about adding those?

**Comment by yairm210** [comment]
Not intentional, go for it
