### ISSUE TITLE
Barbarian Brute

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#931]
Hello. I'm here to try and create a new unit. The Brute, my unit in question, is an unique Barbarian unit, weaker than the regular Warrior. I'm opening this issue also because I feel that Barbarian units in the first turns are too strong. I think we, thus, should open this issue and create this new unit.

Oh, and same gose for Galley, weaker than Trireme.

Question is, how can I create them?

- [ ] Create Brute
- [ ] Create Galley

**Comment by Am-per-Sand** [comment]
There are 2 of them Barbarian uniques to do: [Brute](https://thenounproject.com/hamishbuchanan/uploads/?i=645168) and [Axeman](https://thenounproject.com/thenoun.faisal/uploads/?i=2096303) (Axe thrower ranged radius 1).

- add a unit with params to `Units.json`, together with `upgradesTo` property
- add an icon to `UnitIcons`: 100x100px .png 2bpp (monochrome with white shape on black background set as transparent, like other unit icons)
- include this units in barbarian spawning part of code - no idea which one

**Comment by Smashfanful** [comment]
Axemen are exclusive to the Brave New World expansion, so they don't count

**Comment by Smashfanful** [comment]
How about this icon?
![noun_Spiked Club_831794](https://user-images.githubusercontent.com/41149920/61146418-49d48100-a4da-11e9-97b3-e1419dcf5f33.png)

**Comment by Am-per-Sand** [comment]
![](/Am-per-Sand/unciv/raw/master/UnitIcons/brute.png)

**Comment by Smashfanful** [comment]
Thanks.
