### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by Jiangeshi** [yairm210/Unciv#9310]
I have noticed that due to the emergence of nationalfilter, it has become possible to make civilization-specific policies when creating mods. But there is currently a problem that although civilization-specific policies can only be implemented by certain civilizations, they will appear on the policy interfaces of all civilizations.

So I'm curious if it's possible to create a code similar to "Only display <for [nationFilter]>"?

**Comment by yairm210** [comment]
Goes into #3242
