### ISSUE TITLE
Map/dev starting locations

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9319]
Originally posted on discord. 

"As I work on another map, it's clear that setting starting locations (SL) is needed for random spawns." 

Suggestion for the map editor: 1) new entity for general spawn SLs for random spawns 2) civ general SL 3) CS general SL 4) No-spawn SL that occludes tiles from any random SL ; If the user selects to have more AI players than SLs available, overflow players default to random tile SL (current behavior) excluding no-spawn.

It was also suggested that SL classes, like by water, in desert, by mountain, etc are entities able to apply to tiles also. This could be useful for specific or semi random placement in specific areas, like say only on specific shorelines or near certain mountains.

**Comment by Caballero-Arepa** [comment]
I support this.

**Comment by hackedpassword** [comment]
@tuvus Great feature, been super useful! Doesn't update the starting position count, no biggie. Really appreciate the addition!

**Comment by hackedpassword** [comment]
I guess what you're saying is the top count iterates per type, versus total entity count. K, expectations updated.
