### ISSUE TITLE
Barbarian issues

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#932]
https://github.com/yairm210/UnCiv/issues/931

Also, I don't think Barbarians should fortify in their encampments. That makes them too hard to defeat, considering they also have the time to become swarms.

**Comment by yairm210** [comment]
In that case the solution is probably to limit the number of barbs, and not to have them not fortify.
I'm not going to dumb down the AI to solve a problem I can solve otherwise

**Comment by yairm210** [comment]
Again, I must say, "Barbarian issues" is NOT A GOOD NAME FOR THIS ISSUE
You have a SPECIFIC problem, please give it a SPECIFIC name

**Comment by Smashfanful** [comment]
@yairm210 Sorry, man :sweat_smile:
