### ISSUE TITLE
worker will not replace improvement to enable strategy resources

### ISSUE THREAD

**Issue by ninjatao** [yairm210/Unciv#9328]
**Platform**
Android 13, 64bit

**Version**
4.6.8

**Describe the bug**
Worker automation: worker will not replace improvement to enable strategy resources.

**To Reproduce**
1. Let a worker build a farm on tile with Iron
2. Automate the worker
3. Worker will ignore the tile where it should build a mine, whether automatedWorkersReplaceImprovements is on or off.

**Expected behavior**
Worker should build a mine (replacing the farm).

**Additional context**
Not tested but one quick guess:
tileCanBeImproved() in WorkerAutomation.kt, from line 333:

        } else if (!tile.containsGreatImprovement() && tile.hasViewableResource(civInfo)
            && tile.tileResource.isImprovedBy(tile.improvement!!)   **(<- maybe this should have '!' ahead?)**
            && (chooseImprovement(unit, tile) // if the chosen improvement is not null and buildable
                .let { it != null && tile.improvementFunctions.canBuildImprovement(it, civInfo) && unit.canBuildImprovement(it, tile)}))
            return true
        return false // couldn't find anything to construct here

**Comment by SeventhM** [comment]
Closed as Solved as per #9449
