### ISSUE TITLE
CityButton vertical assymmetry

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9342]
I've long wondered why I could see a garrison (on the world map) easily in my capital but less so in all other cities... That's partially due to StatusTable (the connected/wltk/raze/puppet/etc icons). But even accounting for these and their different padding, the vertical alignment is off-center:

![image](https://user-images.githubusercontent.com/63000004/236696858-8f0767e1-6003-4423-8469-ea4bc4782f53.png)
![image](https://user-images.githubusercontent.com/63000004/236696635-69b6df1a-aafe-4819-8ff9-9aa6d92cba70.png)

Note _both_ are cropped to exact tile boundaries (as far as my tottering fingers allowed in gimp).

One can also observe how our actors draw outside their bounds, which hinders layout tweaking to some extent.

Preliminary review led me to CityButton.kt line 452 - but why that was chosen as `centerX` instead of center (thus no explicit control of y that I can see) eludes me. Also, the setOrigin() line above does nothing at all as long as isTransform is false. Lastly, actually calling centerY will equalize things noticeably, but the center of weight as seen from scene2d debug lines _still_ is visibly below the tile center.

Testing whether the tilegroups are not painting where my prejudices expect them to:
![image](https://user-images.githubusercontent.com/63000004/236698849-5d9a11a1-78b4-41a0-93f7-a488f6ccba3a.png)
Nope, they *do* draw outside their declared bounds, and the center _is_ off, but far less than the city buttons are..

**Comment by Ouaz** [comment]
> Testing whether the tilegroups are not painting where my prejudices expect them to:
image
Nope, they do draw outside their declared bounds, and the center is off, but far less than the city buttons are.

Oooooh, does this explain why there's a slight offset using Thin Bubbly Borders?

![offset](https://github.com/yairm210/Unciv/assets/11946570/0dcb9a7e-1190-4082-b196-b3cd78829e90)

I tried for days to fix the borders being not "centered", thinking my svg file was wrong. :sweat_smile:
