### ISSUE TITLE
Attack animations

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9353]
https://user-images.githubusercontent.com/63000004/236915684-9905d1f5-d448-47f0-8334-3afb7e3e8fce.mp4

Did that Carrier just attack? Nope, the Bomber on it did. Which is also why its HP doesn't go down despite the red flash.

Questions...
* I suppose in `BattleTableHelpers.WorldScreen.battleAnimation.getMapActorsForCombatant` changing [line 100/101](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/bottombar/BattleTableHelpers.kt#L100) to `} else if (!combatant.isAirUnit()) {` would fix that - but is that the right approach?
* [`val slot = if (combatant.isCivilian()) 0 else 1`](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/bottombar/BattleTableHelpers.kt#L102) - class TileLayerUnitArt makes no guarantee which slot is used for what -> fragile code merits at least a few comments?
* [`private fun getAttackAnimationLocation`](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/bottombar/BattleTableHelpers.kt#L71) - `unitSpecificAttackAnimationLocation` and `unitTypeAttackAnimationLocation` use the exact same formula. Is the first one meant to use `attacker.unit.name` instead of `attacker.getUnitType().name`?
* Are there any such attack animations in existence to test?
* We won't be getting actual Unit art :small_airplane: for air units anytime soon, right? Animating one in a nice "stuka run" curve might be macabre :ghost: phun... :zany_face: 
* Any reason why [`}.mapTo(arrayListOf()) { it to it.color.cpy() }.toMap()`](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/bottombar/BattleTableHelpers.kt#L111) and not `}.associateWith { it.color.cpy() }`?

**Comment by Ouaz** [comment]
> Numbers??

Nice! Is it in-game?

But you should really join the enchanting of world of the Unciv Discord, full of mushrooms, peons and trolls. :trollface:
This has been discussed and Yairm stated it was planned (which is a good thing).
Mockup by @letstalkaboutdune:

https://github.com/yairm210/Unciv/assets/11946570/f521f04a-da0d-4afa-8b6a-f3a115c8e4ac

Also @letstalkaboutdune did some mockups of animated attacks (sword slash, bombing, etc) which looked pretty cool (I can't find it), and Yairm said it was doable, but requires some work.

> We won't be getting actual Unit art small_airplane for air units anytime soon, right? Animating one in a nice "stuka run" curve might be macabre ghost phun...

Nope, but Dune (again) suggested this: https://github.com/yairm210/Unciv/issues/7482

These little mosquitos flying as they perform an attck or Air Sweep would be nice, though surely a hell to implement.

**Comment by yairm210** [comment]
@SomeTroglodyte 
A. The numbers you implemented look good - remove the horizontal movement, make interpolation linear, and make the numbers redder, and I think it's ready :D
B. "No animation for attacker sprite if air unit" makes sense to me
C. MapTo - probably no reason, doesn't look like my code;)

**Comment by yairm210** [comment]
Since the numbers face out anyway, there's no reason to make them smaller
Just make them go up and fade out :)

**Comment by yairm210** [comment]
Also, looks much better than before!

**Comment by Ouaz** [comment]
I agree with Yairm. Making them smaller leaves less time to read them. Otherwise, it looks good!

**Comment by yairm210** [comment]
A. That's such an edge-case that I think it's fine, in those cases the big question is usually "is this a sure win, sure loss, or up to chance"
B. Not intentional, you can add in some other factor if you want (unit owner? Unit type? Whatever you want l

**Comment by AdityaMH** [comment]
And last animation, can see enemy movement.
