### ISSUE TITLE
Ошибка.

### ISSUE THREAD

**Issue by Timofey-aq** [yairm210/Unciv#9383]
[9876543.txt](https://github.com/yairm210/Unciv/files/11469346/9876543.txt)

**Comment by AdityaMH** [comment]
Nice day

**Comment by yairm210** [comment]
Old version, Please update your game

**Comment by Timofey-aq** [comment]
> Старая версия, пожалуйста, обновите вашу игру

А как обновить версию игры? Я играю с компьютера (Windows).

**Comment by yairm210** [comment]
The same way you downloaded it in the first place (itch.io/github/aur/flathub)

**Comment by Timofey-aq** [comment]
> Тем же способом, которым вы загрузили его в первую очередь (itch.io/github/aur/flathub )

Спасибо.
