### ISSUE TITLE
Brunei civ,  work ship not build kampong ayer

### ISSUE THREAD

**Issue by Dabadudm** [yairm210/Unciv#9384]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
Impossible to make what you're talking about, you put literally no info in the body

I assume this is a mod problem

**Comment by Dabadudm** [comment]
Yair hi... My eng so bad. Last update 30.06.2023, call mistake in rekmod,
when hight unit and close civ

вс, 14 мая 2023 г., 11:25 Yair Morgenstern ***@***.***>:
