### ISSUE TITLE
Feature request: Map list management

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9386]
In the start new game menu under custom maps, there's no way to delete/manage the map list here - only via the mods menu, which installs or deletes all maps from that repo.

Local maps just keep aggregating. Maybe there's a way to clean this up that I don't know about? Though, doing so should be intuitive for a permanent solution.

**Comment by yairm210** [comment]
I think I understand the problem, but I don't have a good solution. Do you have something? Would a 'filter by text' option help?

**Comment by Caballero-Arepa** [comment]
You can delete individual maps in the Map Editor, but I get it that it would be complicated for some people.

**Comment by hackedpassword** [comment]
> You can delete individual maps in the Map Editor, but I get it that it would be complicated for some people.

I see, which does address my disconnect on that matter as mentioned, but that's part of what I'm addressing as a UI improvement.

**Comment by hackedpassword** [comment]
Could a drop-down selection at the top of the map list drop down be "Manage maps via Map Editor", which then pops the user over to the Load menu of the map editor? This could also potentially introduce players to try the editor.

**Comment by hackedpassword** [comment]
Long press map in the New Game screen to:
- edit in map editor
- manage the associated container mod in Mods screen (here it can be properly deleted taking the d/l mod with it)
- delete, if no container mod
- #3242
