### ISSUE TITLE
player's turn is not updated

### ISSUE THREAD

**Issue by AdamTeodoro** [yairm210/Unciv#9398]
This bug occur only in multiplayer mode

An player its using Linux and other player its using, desktop with Linux

Bug description:
The game is in a looping and the turn is never passed.

How to play:
1 - it's player 1's turn;
2 - player 2 leaves the city window open or the technology window;
3 - player 1 passes while player 2 has the window open.

**Comment by yairm210** [comment]
I see this issue was actually already solved
