### ISSUE TITLE
Feature request: Multiplayer wake up function. 

### ISSUE THREAD

**Issue by boust3r** [yairm210/Unciv#9399]
While gaming multiplayer with friends we came to the issue that it's someone else's turn and need to wait for them for weeks or longer.
I think a wake up its your turn button or alike would be nice to remind players it's their turn. Obviously it should only be usable after a certain amount of time and after being used it should be inactive for a certain amount of time again to not be able to annoy others.
Maybe these times could be configurable during setup of the game or something like that.

**Comment by CrsiX** [comment]
I like the general idea of notifying a player after a _longer_ period of time. However, I dislike to introduce any new server functionality for that. Therefore, I have another mechanism in mind:
If a user didn't play the game for some time - let's say 24 hours - the game wakes up, performs the synchronization to determine if any games are waiting for input and goes to sleep again or notifies the user about those games.
This could be done again after something like 48, 72 and 120 hours -- it would not take very much resources, but would probably improve user experience a lot.

Implementation detail: [`AlarmManager`](https://developer.android.com/reference/android/app/AlarmManager) seems the right thing to use
