### ISSUE TITLE
The is mistake

### ISSUE THREAD

**Issue by Pationg** [yairm210/Unciv#9413]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Pationg** [comment]
Hope the author can save my game archive.

**Comment by yairm210** [comment]
No information in this issue at all, you need to describe a problem if you have it.
As it is this is entirely unworkable
