### ISSUE TITLE
End Turn Bug because of a pantheon 

### ISSUE THREAD

**Issue by AFrogatthebottumofaWell** [yairm210/Unciv#9421]
The problem is very simple and should be on all versions on all devices. Because I have more player than pantheons I can't end my turn, because I have enough faith for a pantheon so I am forced to select a pantheon. But all the pantheon's are selected form AIs already so I'm stuck... Please fix this. Maybe just put a button on politics and pantheons so one could skip the selection and save it for later (: 
(btw. It's a very nice game. Congratulations)

**Comment by yairm210** [comment]
No version, no game save, I can't tell if this is just because you didn't update.

**Comment by yairm210** [comment]
Since no more info is forthcoming, I'm closing this as 'unworkable' - we can reopen it if there's something to work from
