### ISSUE TITLE
Feature request: Make `Free [Military] appears` work

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9424]
**Is your feature request related to a problem? Please describe.**
The unique `Free [baseUnitFilter] appears` only works if you specify an exact unit. However, it would be nice if something like `Free [Military] appears` - for example, the weakest military unit could appear here. (https://yairm210.github.io/Unciv/Modders/Unique-parameters/#baseunitfilter there is also Military for example) I used the unique for a building.
I am unsure if this is a bug or a feature request. On the one hand something is not working, on the other hand this unique might be conceptualized differently.

**Describe the solution you'd like**
A unit appears. For example, onetime I also wanted a UnitType to appear like `Archery` depending on what the user has already explored.

**Describe alternatives you've considered**
A other unique that makes a military unit appear.
`Free weak military unit appears` or `Free strong military unit appears`

**Comment by yairm210** [comment]
Military is a unit *filter*, not a unit name. The uniques requiring unit names do not work with filters, and they won't going forward, either. The answer is "no"
