### ISSUE TITLE
Feature request: Have XMPP and Matrix servers

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9442]
**Is your feature request related to a problem? Please describe.**
Many people don't use Discord, but use XMPP and Matrix instead, as they are open protocols and the clients are usually open-sourced.

**Describe the solution you'd like**
Open such servers.

**Comment by yairm210** [comment]
I don't see why you need me for this... I only have the time to work with one such server, if you want to open servers for other clients you have my blessing. Other people have opened alternative Discord servers and they seem to be doing well.
