### ISSUE TITLE
UI prevents city bombard against enemy units in tiles directly above the city

### ISSUE THREAD

**Issue by savingprivatebryan** [yairm210/Unciv#9445]
**Platform**
Windows 10 / Android

**Version**
4.6.12-patch1 (github)

**Describe the bug**
When an enemy unit is directly above a city and the city has a garrisoned unit I am unable to bombard that enemy because when I click the city the garrisoned unit is showing in front of and covering the enemy unit. It appears the hitbox of the garrisoned unit completely overlaps the enemy unit so there is no way to select the enemy unit to bombard.

**To Reproduce**
1. Have an enemy unit in the tile above the city
2. Have a garrisoned unit in the city
3. On the map, click on the city name
4. Try to bombard the unit above the city. The garrisoned unit covers the enemy so it can't be clicked on to be bombarded.

</details>

**Expected behavior**
The enemy unit should be able to be clicked on to bombard.

**Screenshots**

Here the destroyer is directly above the city and I have a canon garrisoned in the city:
![image](https://github.com/yairm210/Unciv/assets/6765837/705a3375-0dc9-4781-b3dd-59e16e17d768)

Clicking on the city then causes the garrisoned unit to cover the destroyer so I can't click on the destroyer to bombard it:
![image](https://github.com/yairm210/Unciv/assets/6765837/5d4fed5c-b64e-44b8-afd8-0c961a054c70)

**Additional context**
I tried adjusting the screen size but it doesn't help. I have 5hex tileset and RekMOD enabled.

A similar situation occurs when there are 2 units garrisoned in the city where I am unable to bombard the enemy in the above right and the above left tiles of the city.

**Comment by yairm210** [comment]
The workaround for this is to deselect the city unit and to click the tile of the unit you want to bombard
We tried to solve this previously by making the icons smaller when zooming, but that didn't work
We still don't have a good solution for this, so I'll keep this issue open instead of closing it like the others #8689 #3420 #4005

**Comment by savingprivatebryan** [comment]
Thank you for the workaround, it is working for me. I noticed the garrisoned units that show when clicking a city are bigger compared to the map units. Would making the city unit icons smaller relative to the map units help? Or even shifting the city units down a bit so they don't completely overlap the other tiles.

**Comment by yairm210** [comment]
Shifting them down would still make them overlap tiles to the left and right
And making them smaller would make them very hard to select on phones ;/ that's why they're so big to begin with
