### ISSUE TITLE
Enemy too easy

### ISSUE THREAD

**Issue by Alvin201777** [yairm210/Unciv#9447]
after update, Enemy can't build new city Even though it's late game, the enemy only has 1 city on all playing difficulties. (Such as 1 city challenge).. I don't know how to report the bug, but it happens a lot after updates.

**Comment by yairm210** [comment]
You *have* to provide more info than that. A save game, what mods you're using, etc

**Comment by Alvin201777** [comment]
![Screenshot_2023-05-24-14-49-33-267_com unciv app](https://github.com/yairm210/Unciv/assets/132994815/a4aad999-9603-4573-9e70-90d72492d2b3)
![Screenshot_2023-05-24-14-49-48-545_com unciv app](https://github.com/yairm210/Unciv/assets/132994815/a326be7f-d83b-4e59-a58c-12509bd6c7dd)


![Screenshot_2023-05-24-14-50-03-415_com unciv app](https://github.com/yairm210/Unciv/assets/132994815/6946fc69-ec63-4725-87f8-55755743ddbe)


Mod :

-all unit can be automatic
-no fog of war
-resource recycle
-policy mod
-civ6 for unciv

**Comment by Alvin201777** [comment]
There is no problem in the mod

**Comment by Alvin201777** [comment]
Enemy Settlers don't move, even though they are level 10

![Uploading Screenshot_2023-05-24-15-22-03-736_com.unciv.app.jpg…]()

**Comment by Alvin201777** [comment]
![Screenshot_2023-05-24-15-22-03-736_com unciv app](https://github.com/yairm210/Unciv/assets/132994815/29783d33-9a67-4100-8d9b-74af316607b9)

Enemy Settlers don't move, even though they are level 10

**Comment by yairm210** [comment]
Okay, found the problem, rolling out as patch version
Thanks!
