### ISSUE TITLE
Will this add Brutes in game?

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#945]
[GameInfoBruteVersion.kt.txt](https://github.com/yairm210/UnCiv/files/3406456/GameInfoBruteVersion.kt.txt)

**Comment by ninjatao** [comment]
Probably not. Your code places a brute only when unitlist is empty, but this should never happen because the list will contain at least one available military unit(such as warrior). What would you like to do exactly?

**Comment by Smashfanful** [comment]
I just want the Brute to be the first Barbarian melee unit, so that early game noves are not too frustrating.

**Comment by ninjatao** [comment]
So what you need to do is replacing warrior with brute for barbarian. But for what purpose? In seems that brute has same combat abilities as warrior.

**Comment by Smashfanful** [comment]
Weird. Brutes should be weaker than them

**Comment by yairm210** [comment]
Brutes are a flavor unit - they have no game differences to a Warrior other than a different name and icon

**Comment by Smashfanful** [comment]
So we just need to make them weaker than Warriors

**Comment by yairm210** [comment]
Closed in #931 
By the way, if there's already an issue for something, don't open another issue for the same thing. This while discussion could have taken place there.
