### ISSUE TITLE
Feature request: Behold... Auto next turn !! Automatically press `Next Turn` for `X` turns !!!

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#9450]
Sometimes in Multiplayer, there is nothing to do except pressing next turns. Auto next turn might be a good option in these scenarios to improve the speed of gameplay.
The idea is auto next turns would be a tick mark below the next turn option that will automatically press next turn when the game updates. If there is nothing to do except next turn and automate.

**Comment by touhidurrr** [comment]
![image](https://github.com/yairm210/Unciv/assets/46617994/833ecb1d-393b-4d72-9e4c-140aa4228a49)

![image](https://github.com/yairm210/Unciv/assets/46617994/d2b60c0b-e669-4c95-8942-c7d1d6fb37ec)

**Comment by CrsiX** [comment]
I upvote this proposal, even though it is not new. See #2375 from April 2020 :)

**Comment by SeventhM** [comment]
#2375 and #10176 are closed thanks to us having Auto play implemented. Closing this one similarly for similar reasons. If this needs to be reopened it would seem more reasonable to open a new issue or comment on #10176
