### ISSUE TITLE
The unique "[-50]% maintenance on road & railroads" doesn't work properly

### ISSUE THREAD

**Issue by nizhuan-jjr** [yairm210/Unciv#9453]
**Platform**
Windows 11 64bit, Android

**Version**
4.6.14-patch1(PC) ; 4.6.13-patch1(Android)

**Describe the bug**
Ruleset: Civ5 - GnK
Mods: Difficulty_Sandbox(for test purpose), my simple nation mod, some other irrelevant mods

I made a simple nation mod which passed the Locate mod errors check. The mod works fine on everything except for the unique "[-50]% maintenance on road & railroads", which is the same unique as Inca.
Base Road Maintenance is 1 gold per road, right? After I built 2 roads using my mod nation, the transportation upkeep shows -2 instead of -1. Please check the screenshots section.

**To Reproduce**
1. build 2 roads on Non-Hill tiles using the nation Inca
2. check the transportation upkeep to see if it's -2 or -1

**Expected behavior**
Under the unique "[-50]% maintenance on road & railroads", the transportation upkeep of 2 roads should be -1.

**Screenshots**
![2](https://github.com/yairm210/Unciv/assets/3255986/4dc8763c-af2f-4a6c-a8fb-f35e600ed9ea)
![1](https://github.com/yairm210/Unciv/assets/3255986/bdae5873-8d2b-4078-85ef-7c6c62f72185)
![0](https://github.com/yairm210/Unciv/assets/3255986/92b49317-8e3e-4026-905e-3aeffebd1314)

**Additional context**

**Comment by alexban011** [comment]
> No compiler warning or IDE inspection for using a non-Unit returning expression as statement?

hah don't blame me for that :DD

> Doesn't even detekt see that the result of operator Stats.times is discarded

ahh detekt allows us to make custom rules to check for whatever we want, I'll try to do this check but I don't promise anything :D
