### ISSUE TITLE
Koniec tury i wyskakuje błąd

### ISSUE THREAD

**Issue by janski1981** [yairm210/Unciv#9458]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alexban011** [comment]
I had to translate the title to find out that this is a crash. "Next turn = crash" ??

Please post a crash report :D

**Comment by yairm210** [comment]
Since no more info is forthcoming, I"m closing this as "unworkable". No info here whatsoever.
