### ISSUE TITLE
Politics overview discloses randomized civ count

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9463]
(In the diagram view, not the default list view)
![image](https://github.com/yairm210/Unciv/assets/63000004/399535e6-db82-4f36-982c-48a0962d2930)

This is right after a start with both randomNumberOfPlayers and randomNumberOfCityStates on, and it discloses both secrets.

**Comment by yairm210** [comment]
I don't think that either of these are really big problems, I'll be fine if both go unaddressed as well
