### ISSUE TITLE
Feature request: wiki link in readme?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9471]
I may be blind, but:
https://yairm210.github.io/Unciv/ is easy to find using ddg, but is it actually linked anywhere from the project [root](https://github.com/yairm210/Unciv) page?
The readme's "Where's the wiki?" points to fandom, and not even to [this page (a little outdated too)](https://civilization.fandom.com/wiki/Unciv) of fandom...

**Comment by yairm210** [comment]
![image](https://github.com/yairm210/Unciv/assets/8366208/32166ef0-6fba-44b5-90fd-742f97b67b37)

All of those are wiki links, if you want to add another be my guest, but that site is not meant for the average player, it's meant for people who want to work on the game
