### ISSUE TITLE
A unrecoverable error message.

### ISSUE THREAD

**Issue by FtFoxyYT** [yairm210/Unciv#9475]
Hi so uh I have spent minutes to get almost every single unciv mod. And then a error message has appeared and it says to remove some mods but honestly I have no idea how to do that because the error message is blocking the way. If this is fixable please tell me I just wanna play some unciv.

**Comment by FtFoxyYT** [comment]
**Platform:** Android
**Version:** 4.6.15 (Build 872)
**Rulesets:** [averageland, Modern Civilizations, Wakanda for Unciv, Iron and Blood, Medieval Civilizations, ph bonifacio unciv, Bamboo Deciv Expans, Modern Russia, 3rd and 4th Unique Component, Warfare Expanded Lite, American Civil War mod, Powerful GDR, Plants vs UnZombies, CCCP Unciv, Son Of War Mod, More Fauna And Flora, Indonesian Kingdoms, Tech Stopper _WW2_, unciv religion mod example, Resourceplus, Civilization4mod, AbsoluteUnits, Empire of the SEA, MasterMod, Uncivilized Expansion, Civ Army Color Style Sheet, Warfare Edited, Future Expansion, HiveCiv Mod, Smoky Skies Redux, LOTR reworked, Expanded Warfare, Bubbly Borders Example, hack land, Fantasia, Respectful Chess, Anime Multiverse, Nab everything, Community Maps, Great New World Mod, Resources Edited, Project Felipe, CS Overhaul, Tech Stopper  _Medieval_, Super Sandbox, Byzantium Buffed, Community Civs, Promotion Fix API, Greece plus The Middle East, AquaExtension GAK, LostTec, Project Tondo, CivBE in Alpha Frontier, Cheat_Sandbox, Unciv Europe Map Example, Modern Joke Religions, Civ V Leader portraits, Fire Emblem Civilizations, Deciv Testbed, ComplexHistory, Urban Area Syntaxed, Dreams of Steam, philosophy mod, Barbarians but Better, WW2 Nations, Chaos Generation, Dimensiondog s Districts, All units can be automated, Project PMC, Christmas for Unciv, Ancient Civilizations, Remilia Scarlet Touhou, Nusantara Civilizations, Advance Wars Mod, CS Unique Components , My Uncivilized Ponies, Maid Empire, The Great Unciv Rework, 5Hex Tileset, Double Great Improvements, Cavemen, Modern Russia unciv mod, theundeadedited, Extra Promotions, Better ruins, Soviet Union, Horses and Iron mod, The Undead, Policy mod, Naciones pa deciv ES, Higher quality builtin sounds, More Speeds, DeCiv, AbsoluteUnitsXL, Brave New World, Historica, DeCiv Redux, The Demon World, Extra Buildings, Tech Stopper Agriculture, moREsources, Nat5 Design, Tiberium Dawn Mod, 2023 Unciv, Elysium for DeCiv Redux, More Luxuries, Antiyoy maps, Tech Stopper _Industrial_, useful alltech, Difficulty_Sandbox, Capital Domination, Pix5 Tileset, Alice Margatroid Touhou, Civ5Nations, Sheep Meta, Greek Civ Split, Civ style set by Bucketeer, No Fog Of War, Resource Recyclers, Penguinia, Civ6 mod, Epic of Fantasy, More Challenges, nab everything for LOTR, Civ6 Tileset, Alpha Frontier, uncivCheatNation, Fairy Alliance Touhou, DeCiv Reworked, Ukraine Mod, Better Pantheons, Palengke, Civ V - Gods & Kings, Ornith, Leaders Plus, Additional Music Various, Outpost Mod, RekMOD, Nation of Nuke, Classical Harbors, Upside Down, UnHax, Tech Stopper _WW1_, fate mod, Leader Mission, Barbarian xp farm, Uncivilized Enhancer, LOTR Unciv, HAAX, The North Pole, Alpha Frontier Fairplay Mod, Latin American_Civs, Dacia Unciv mod, Mitteleuropa and Balkans, Only Mod Civilizations, Tech Stopper _Classical_, Better Units and Natural Wonders, Strategic Resource Visibility, Civ6Nations, Civ V - Vanilla, The Netherlands mod, hsm til MET, DivineJapanMod, Rome Improvements, Ningen no Sato Touhou, MaOr BoWtS mod, Antarctica Unciv mod, Unciv IV mod, Aliens have crashed on Earth, CS Rework, Randos Army Unciv, Arknights Firewatch Mod, Project Lantaka, Marmero Futurismo, Civ6 Nations for Unciv, Unciv modern armies, Naciones pa Unciv ES, Project Paddy Field, VeryQuickSpeed, CivsAgainstDeity, More Natural Wonders, Closer Cities Distance of 1, Civ 5 Icons, DeCiv in Alpha Frontier, Mapping Tools for Unciv]
**Last Screen:** `com.unciv.GameStartScreen`

--------------------------------

Device Model: octopus
API Level: 30

--------------------------------


**Message:**
```
java.lang.Exception: Could not parse json of file HexaRealm.json
	at com.unciv.json.UncivJsonKt.fromJsonFile(UncivJson.kt:48)
	at com.unciv.models.tilesets.TileSetCache.loadConfigFiles(TileSetCache.kt:77)
	at com.unciv.models.tilesets.TileSetCache.loadTileSetConfigs(TileSetCache.kt:66)
	at com.unciv.models.tilesets.TileSetCache.loadTileSetConfigs$default(TileSetCache.kt:41)
	at com.unciv.UncivGame$create$2.invokeSuspend(UncivGame.kt:204)
	at com.unciv.UncivGame$create$2.invoke(Unknown Source:8)
	at com.unciv.UncivGame$create$2.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: [
{
	useColorAsBaseTerrain:  false
	fallbackTileSet:  "FantasyHex"
}
] (com.unciv.models.tilesets.TileSetConfig)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1126)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:834)
	at com.unciv.json.UncivJsonKt.fromJsonFile(UncivJson.kt:46)
	... 20 more

``` btw thats the error message

**Comment by FtFoxyYT** [comment]
> > get almost every single unciv mod
> 
> Diagnosis: Masochism. Treatment: _Find_ the culprit mod. Go get a root file manager and tell us which mod has a HexaRealm.json file - normally that should only exist in the game's internal resources. And ours has correct syntax, not the wrong one shown (it represents an object, not an array -> the [ ] are wrong).

About the root file manager do u have a suggestion of what root file manager I could use? I am running on android and my device is a chromebook. Thank you.

**Comment by FtFoxyYT** [comment]
Hi so uh if I wasted your time then my bad I just wanted to play unciv but I think i'll just redownload the game. So uh i'm so sorry.

**Comment by FtFoxyYT** [comment]
btw I have no idea how to delete this but sorry.

**Comment by CrsiX** [comment]
The forceful option would be to uninstall the game, then re-install it. Afterwards, maybe don't install _every_ mod out there :)

Alternatively, there's a button "clear storage" under the section "storage & cache" in the app info screen, but that's on my Android phone, I don't know if this works on Chromebook too. I think that would also work instead of uninstalling.

**Comment by FtFoxyYT** [comment]
> > but sorry
> 
> No need! Every input, if trying to help, is valuable. And this - well it's not surprising mods can "shoot us down", as in we use external input, so we should [sanitize](https://bobby-tables.com/) **_all_** such input - but there's always potential we overlook a loophole. Of course we'd be interested in closing such loopholes. But do that same thing to reproduce - download all of them - nah, too painful 🤕 💉 🤯 💥

it was painful...

**Comment by yairm210** [comment]
I can't remember if we dealt with this or not, but I do recall that we added some sort of sanitizer to the tileset json paring?
