### ISSUE TITLE
How about... "What is that Worker doing??"

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9476]
![image](https://github.com/yairm210/Unciv/assets/63000004/5e3104d0-4a3b-4d50-af8a-599c8329f34f)

:yum: Yes please or no bleargh :vomiting_face: ?

I mean, yes, it's already there, but so is the rest of the action column (and health) - tiny on the unit icon itself...

**Comment by Caballero-Arepa** [comment]
Yes please

**Comment by Ouaz** [comment]
Big yes please. :fire:
