### ISSUE TITLE
How about... Some visuals to that scientific victory?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9477]
![Spaceship-1](https://github.com/yairm210/Unciv/assets/63000004/f8f8bf6a-5f97-4857-8850-0af659936da7)

Same question - this would be mod only, that sample comes from http://fr.tintin.com/, so not under an open license.

**Comment by Caballero-Arepa** [comment]
Isnt that rocket from Tintin?

**Comment by Caballero-Arepa** [comment]
I like it, what about also being able to show an image upon winning/loosing?

For example, once you win, in the victory screen you can see the spaceship.

The Bucketeer made some a year ago.

**Comment by AdityaMH** [comment]
> ? Where ? Can't find on the GeneralWadaling repos

On discord, dom, cul, sci, victory loses pic was created a year ago

**Comment by Caballero-Arepa** [comment]
> Of course, says so right on the original post

Oh I didnt saw it xD

> ? Where ? Can't find on the GeneralWadaling repos

Here is the [link](https://discord.com/channels/586194543280390151/618434980636393492/704213610922246179), do you have discord?

If not, here is one of them: ![Science_Victory.png](https://github.com/yairm210/Unciv/assets/78449553/e25f509d-d709-45ab-9dc9-43f651c74dca)

**Comment by AdityaMH** [comment]
> Here is the [link](https://discord.com/channels/586194543280390151/618434980636393492/704213610922246179), do you have discord?

trying to persuade someone to join discord again? xD

**Comment by yairm210** [comment]
As for this "how about" - the original one is denied, if you want to do Victory-specific static artwork that's fine, but I don't think we need an issue for that
