### ISSUE TITLE
Make seaports require harbors 

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#948]
Small thing here, but harbors should be made to be a prerequisite for seaports as they are in Civ V

**Comment by Am-per-Sand** [comment]
and harbor prerequisites lighthouse?

**Comment by ozyxcv** [comment]
harbors don't require lighthouses though, do they?

**Comment by Am-per-Sand** [comment]
I 've got a headache

**Comment by yairm210** [comment]
According to the Civ Wiki, the Standard Repository of All Knowledge and Wisdom, Seaport required Harbor and neither of them require Lighthouse.
