### ISSUE TITLE
Feature request: Visual indicator for building outside workable tiles

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9486]
In the construction improvement menu, when in city tile rings 4-6, beyond the 3 inner rings that citizens work, improvements like trading posts or mines should have an indication that improving this tile will net no resources for their city. Luxury items would not have an indicator.

**Comment by yairm210** [comment]
Agree, this sounds like a textual warning in improvement picker screen

**Comment by huckdogg** [comment]
I'm working on this change.

**Comment by hackedpassword** [comment]
@huckdogg Appreciate you adding this feature! It is in fact useful and preventing workers from being misled into overlooking wasted workable population. Thank you!

I've come across a glitch, a logic issue maybe? I'm attaching images here showing when the worker by the mountains on the top right tile (top-left tile adjacent to Nakhon city with the Infantry unit) goes to convert the farm to a trading post, it's reported that the tile is unworkable (I may have deselected the workable icon in the screenshot before taking). The city to the left owns the tile, which is > 3 tiles away. The city to the right works the tile which is in range, so this report is false because it can be worked as designated, and is, properly worked by city on the right.

![Screenshot_20230824_112447](https://github.com/yairm210/Unciv/assets/119975434/69a77305-8f37-496c-9f12-5b0e3463f25d)
![Screenshot_20230824_112314](https://github.com/yairm210/Unciv/assets/119975434/93dcf3e8-5d59-4c59-980d-deae750ee7db)
![Screenshot_20230824_112343](https://github.com/yairm210/Unciv/assets/119975434/e0e7f15f-fc47-4ce7-99d7-fcb3d356278b)
![Screenshot_20230824_112411](https://github.com/yairm210/Unciv/assets/119975434/3d25b8d3-5d5b-4baf-92fe-6f2b96fcec40)

**Comment by huckdogg** [comment]
@hackedpassword Thank you for reporting this. Do you happen to have a save file from that point?

@SomeTroglodyte I was running under the impression that a tile was only workable by the owning city. Is that correct? Or should tiles be workable by a closer city even if the city doesn't own the tiles?

**Comment by hackedpassword** [comment]
[China - 368 turns.txt](https://github.com/yairm210/Unciv/files/12433695/China.-.368.turns.txt)

Ready to go. You'll need to download the Z2 mod.

**Comment by yairm210** [comment]
Yes, cities can work times of other cities, if they're in 3-tile range

**Comment by huckdogg** [comment]
I could change the logic to look for the nearest player city and see if that city can work the tile. Only display the warning if no player cities within three tiles.

**Comment by hackedpassword** [comment]
Run into only a single instance of this issue since being fixed, didn't retain. If there's a next time I'll hold on to it for inspection.
