### ISSUE TITLE
How about: Map painting canvas madness

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9488]
<details><summary>Actual screenshots</summary>

![image](https://github.com/yairm210/Unciv/assets/63000004/460da16d-5208-43cc-9886-7c38f00ea4dc)
![image](https://github.com/yairm210/Unciv/assets/63000004/74694d38-8aa3-4aa6-8034-0ba5d1b86c8a)

</details>

There was another open issue requesting something like this, can anybody link it?

**Comment by Caballero-Arepa** [comment]
Holy cow... this would be absolutely time saving

**Comment by alexban011** [comment]
> ours crashes on X11

won't the file picker used in the LoadGameScreen.kt work for this? I haven't looked too much into how that works, but it looks like that works for me. 

Anyway I do think that #9490 looks much better than whatever this 1999 AD stuff is supposed to look like:
![image](https://github.com/yairm210/Unciv/assets/21990802/ce3778be-d531-4267-abc3-477346efafee)

**Comment by yairm210** [comment]
I recall that someone already made a "create map automagically from file based on pixel colors to base terrain colors", I'm not sure which is better - that one cuts out a lot of work, and this one is better for terrain features...
