### ISSUE TITLE
Feature request: Icon for pillaged tile improvements

### ISSUE THREAD

**Issue by andraaspar** [yairm210/Unciv#9494]
**Is your feature request related to a problem? Please describe.**
It is rather hard to tell whether a tile improvement is pillaged. I see there is a slight color change, but we could use a bit more emphasis.

**Describe the solution you'd like**
I'd like to see the tile improvement icon to be different when pillaged. A red cross on top of it, or maybe an instance of Fire.png. I'd be happy to draw an overlay image if that helps.

**Additional context**
The issue:
![image](https://github.com/yairm210/Unciv/assets/3512382/94521a53-7a66-4ada-a8a7-8b68136114c5)
Proposal:
![Unciv_IVdM2hshEt_2](https://github.com/yairm210/Unciv/assets/3512382/5b1fd197-98d8-4778-bb56-22d588f1d249)

**Comment by AdityaMH** [comment]
pillaged road?

**Comment by andraaspar** [comment]
@AdityaMH I guess – the same? Just without the tile improvement icon?

**Comment by yairm210** [comment]
Looks good! We'll check some options

**Comment by andraaspar** [comment]
Awesome! Thank you!
