### ISSUE TITLE
It won't launch

### ISSUE THREAD

**Issue by Lionelnary** [yairm210/Unciv#9495]
**Platform**
Window 10 32bit

**Version**
Itch.io- Version 4.2.12

**Describe the bug**
The game won't launch even after I uninstall and install multiple times
**To Reproduce**
Click to start the game
If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Game screen won't launch, keep on loading then nothing happens

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
4.2 is *very* old, please update to a recent version

**Comment by yairm210** [comment]
Oh, it's 32 bit, sorry
32 but is no longer support due to the underlying framework no longer supporting it :/
