### ISSUE TITLE
Feature request: Diplomacy 

### ISSUE THREAD

**Issue by Alvin201777** [yairm210/Unciv#9499]
I have a suggestion.

First: in the diplomatic mission section, what if we hold a menu to demand an end to wars between countries that are at war with other countries, the condition is that they must have an UN.
Second suggestion : Help for poor countries.

If my advice is useful, please help me to make it happen..

Thanks 🙏

**Comment by yairm210** [comment]
Closing as duplicate
First ask is in Civ V and is in #4697, second ask is not in Civ V therefore out of scope
