### ISSUE TITLE
Couldnt join my own server but my friend can

### ISSUE THREAD

**Issue by rzrtt** [yairm210/Unciv#9503]
**Platform**
Windows 11 (64 Bit) 22H2 (Build 2261.1702)

**Version**
https://yairm210.itch.io/unciv version 4.6.16 (Build 873)

**Describe the bug**
I created a server with java from: https://github.com/yairm210/Unciv/releases/latest/download/UncivServer.jar and it worked. The Problem: when i can connect to the server, my friend can't. But if he can, i cant. Not even per localhost!

**To Reproduce**
i dont know

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details>

<summary>

Saved game

</summary>

</details>

**Expected behavior**
I expected we both could join the server

**Screenshots**

**Additional context**

**Comment by jujuju430** [comment]
bruh it says that i can connect but when i try to create a game it says it cant connect

![image](https://github.com/yairm210/Unciv/assets/97132049/ab59b77a-caf3-49f5-bbb7-c713533399c0)

![image](https://github.com/yairm210/Unciv/assets/97132049/f0768f7f-2d9a-4548-9bd7-0b8a5ba7080c)

**Comment by jujuju430** [comment]
![image](https://github.com/yairm210/Unciv/assets/97132049/d5c4c6ed-88c7-4db8-b93f-be0c033a2dfb)

**Comment by jujuju430** [comment]
sometimes it works and sometimes it wont

**Comment by Mape6** [comment]
Please use the URL that is written in the terminal output and not only "localhost".
And have you created the folder for the game files like it's mentioned in the doc of the Java Server?

**Comment by yairm210** [comment]
Is this still a problem? Or did using the terminal output URL solve it?

**Comment by yairm210** [comment]
Closing since no answer was recieved
