### ISSUE TITLE
Feature request: Check the consistency of terms

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9511]
**Is your feature request related to a problem? Please describe.**
There are inconsistencies of the keys. For example, in “Buildings.json”, it is called “requiredTech”; in “TileImprovements.json”, it is called “techRequired”.
Minor cases include “tradeRequest” (noun phrase, instead of “requestingTrade”) and “declaringWar” (verb/gerund phrase, instead of “warDeclaration”); “spyNames” (with “name”, instead of “spies”) and “cities” (without “name”, instead of “cityNames”).

**Describe the solution you'd like**
Improve the consistency.

**Comment by yairm210** [comment]
I agree that this makes things difficult, but the amount of change necessary far outweighs the benefits of the standardization
