### ISSUE TITLE
Feature request: List civilizations in a table

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9526]
**Is your feature request related to a problem? Please describe.**
It requires a lot of scrolling to find a specific civilization.

**Describe the solution you'd like**
List icons in a table.

**Comment by yairm210** [comment]
What screen? What do you imagine? There's not much to go on here

**Comment by ravignir** [comment]
total war style 🤔

**Comment by GrimPixel** [comment]
It's hard to add icons for all those policies, beliefs, etc.

**Comment by GrimPixel** [comment]
I think the diplomacy window could be similarly handled. Just two or three in a row.
