### ISSUE TITLE
Feature request: handle duplicated nations

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9535]
**Is your feature request related to a problem? Please describe.**
Some mods have the same nation, so the nation gets enhanced like a religion. An example is Kazakhstan in “Turkic Civilizations” and “Modern Civilizations”.

**Describe the solution you'd like**
Have the option to disable duplicated nations in one of the mods.

**Comment by yairm210** [comment]
This is intentional behavior, to allow overriding nations in extension mods. If you want to have separate nations, you need to call them different names.

**Comment by GrimPixel** [comment]
May I choose which one prevails?
