### ISSUE TITLE
Wrong name of city-state when a nation of the same name is available

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9536]
**Platform**
Android

**Version**
4.6.15

**Describe the bug**
When a mod adding a nation, e.g. Uruguay, exists, then the city-state of “Uruguay” is changed to “Montevideo”, which is the first city of the nation “Uruguay”; in the diplomacy panel of the city-state, it is still named “Uruguay”.

**To Reproduce**
1. Enable a mod that turns original city-state to a nation
2. Start a game
3. Some city-states have wrong names in the diplomacy panel

**Comment by yairm210** [comment]
You can't have both a nation and a city-state of the same name active in the ruleset at the same time, they override each other
Can you provide exactly what mod you used? And a picture of the "wrong" screen?

**Comment by GrimPixel** [comment]
I tried to choose Uruguay, but it disappeared. It is still in the mod json.
https://github.com/Caballero-Arepa/Latin-American_Civs/blob/master/jsons/Nations.json
![Uruguay](https://github.com/yairm210/Unciv/assets/39795763/a2db9f8b-3117-4c8b-95a4-967aaf665b5a)
