### ISSUE TITLE
Wrong asorting by name

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9537]
**Platform**
mobile and desktop

**Version**
4.6.15

**Describe the bug**
Currently, mod sorting “Name ↑” is descending, “Name ↓” is ascending.

**Comment by GrimPixel** [comment]
A to Y is descending; Y to A is ascending.

**Comment by GrimPixel** [comment]
Great. I learned a lot today.

**Comment by Caballero-Arepa** [comment]
I mean, it still is confusing

**Comment by Caballero-Arepa** [comment]
Hmmm, it has to be in Unicode, right?

For I got something started ![236 sin título_20230607153009.png](https://github.com/yairm210/Unciv/assets/78449553/d2721fee-2828-46de-a55a-755b1fd6b59e)
But I'll research about it and hiw to comvert it later.
