### ISSUE TITLE
Feature request: change dark colours of city-states

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9540]
**Describe the solution you'd like**
If the colour is too dark, it is hard to recognise on the black background. Their colours can be changed.
Examples are Hanoi, Valletta, Quebec City.

**Describe alternatives you've considered**
All city-states use silver background instead of black.

**Comment by yairm210** [comment]
No, this is not how city-states are recognized.
We have already conducted readability checks for all civs in Unciv and they are good enough, maybe we can make them a patch lighter, but we're not changing the black background

**Comment by GrimPixel** [comment]
How about adding icons to them?

**Comment by GrimPixel** [comment]
Could be simply text of its name in its native language.
