### ISSUE TITLE
Feature request: Keep ruleset when changing custom map

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9541]
**Is your feature request related to a problem? Please describe.**
After changing a map, all mods are reset, so I have to click on them again to enable them.

**Describe the solution you'd like**
Add buttons to enable/disable all mods.

**Comment by yairm210** [comment]
You can start a new game from within the old game to retain the same starting params
Also, starting a new game should use the parameters of the previous game you started - if that's not working then it should be fixed

**Comment by yairm210** [comment]
Thinking over this again, this actually a really bad idea.
One of the good things in gradually adding mods is that you can see at what point things conflict with each other. "Enable All" is just a recipe for chaos.

What we *could* do is check if the map fits the existing mods, and if so to **not** change the mods. That would require a map-to-ruleset validator, though, which is a large project
