### ISSUE TITLE
Feature request: add “rim-color”

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9547]
**Is your feature request related to a problem? Please describe.**
There are too many nations with similar colours.

**Describe the solution you'd like**
There could be a “rimColor” besides “outerColor” and “innerColor”.
For example, the colours of Nepal can be red as outerColor, white as innerColor, blue as rimColor.

**Comment by Caballero-Arepa** [comment]
Ah yes, the very unique "red, blue, white" flag...

**Comment by GrimPixel** [comment]
How to choose colour combo for Nepal then?

**Comment by Caballero-Arepa** [comment]
Try with these 
![imagen](https://github.com/yairm210/Unciv/assets/78449553/226ae06d-6505-42ca-bb85-bc4c751f5487)
![imagen](https://github.com/yairm210/Unciv/assets/78449553/4fa18887-0fdc-4c0a-a1f1-4270c4adde06)

White: 198, 218, 236, Purple: 72, 39, 47, 1

You don't have to use the exact flag colors of a nation. At the end, these colors are just to give the vibe of the civ,

**Comment by GrimPixel** [comment]
Thank you for trying to do so. I know there are theoretically 255^6-6 combos. I would prefer to use the exact colours to get the maximal vibe. It looks unavoidable to have same colours for different nations.
