### ISSUE TITLE
Feature request: support non-ASCII character filenames

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9548]
**Is your feature request related to a problem? Please describe.**
Non-ASCII characters become question marks.

**Describe the solution you'd like**
Support non-ASCII characters in filenames.

**Comment by yairm210** [comment]
We absolutely do support non ascii this sounds like a problem with your default font
Can you show an example that the font allows, but not in filenames?

**Comment by GrimPixel** [comment]
In https://github.com/NoviceCoder2000/UnCiv-Vanilla-Music-Pack, some files are written in non-ASCII characters.
Here is what the folder looks like after installing it in the game:
![filename](https://github.com/yairm210/Unciv/assets/39795763/fc70ccb3-1aea-446c-b9b9-1afa91f6f1cd)

**Comment by GrimPixel** [comment]
It's MATE on Arch Linux.

**Comment by GrimPixel** [comment]
`LANG=C` and no `LC_`

```
$ echo $LC_COLLATE

```

```
$ java -version
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
```

**Comment by GrimPixel** [comment]
Good to learn that details. My Arch Linux is only customised in few aspects.

**Comment by yairm210** [comment]
@SomeTroglodyte I would vote against the various "fixes" for encoding that mess with the system.
We could have some sort of warning, but I'm not sure where would be the correct place to put it.

As for the e2e flow:

A. It looks like the Zip by default uses UTF-8: 
![image](https://github.com/yairm210/Unciv/assets/8366208/e8b829d0-2718-44dc-bb79-79ef1cb5ca4e)
so I assume this is a problem in *reading the file name* and not it *writing it*

B. @GrimPixel What do the filenames look like to you *outside* on Unciv?

C. Maybe when reading filenames we can specify encodings? I see that in fromJsonFile for example we have `file.readString(Charsets.UTF_8.name())` - but I never even thought about the *name* of the file being encoded differently, I can't find a place where LibGDX allows to state the encoding of the *filesystem*

**Comment by GrimPixel** [comment]
That image is from file manager. It is as shown.

**Comment by yairm210** [comment]
In that case, I was wrong, and it is Scott writing the file name 😞
