### ISSUE TITLE
Correct spelling of M'banza-Kongo

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9549]
It is written as M'Banza-Kongo in game. “M'banza” is one word, so that “b” shouldn't be in upper case. It is written as Mbanza as well.
It's a similar reason why “Rio de Janeiro” is not written as “Rio De Janeiro”.

**Comment by yairm210** [comment]
Changing a civ name would invalidate all existing games that include that civ.
It's just not worth it for such a niggling detail.
