### ISSUE TITLE
Stockpiled Resource can be negative

### ISSUE THREAD

**Issue by Jiangeshi** [yairm210/Unciv#9554]
There is currently a problem with the resources of Stockpiled. If there are projects that consume resources but do not have projects that increase resources, it will cause the resources to become negative. I am not sure if this can be considered as a bug which can be fixed.

**Comment by yairm210** [comment]
What do you suggest, then?

**Comment by itanasi** [comment]
Negative Gold only hurts Science. A while back I had built in penalties for all the stockpile stats just in case via mod they went negative. But that got rejected for not being in main game.

I think the main issue is "Missing resource" only applies to units. But Stockpiles are more generalized, so how would you penalize a Building for example?

**Comment by yairm210** [comment]
Thinking through this again I personally don't see this as a problem. Just like you can have positive and negative happiness, what's to stop me creating effects for positive and negative whatever? This could actually lead to some really cool mechanics for e.g. Morale or something, a la Heroes effects (extra attack with 20% chance when Morale > 10! -30% Strength when Morale < -10!)
