### ISSUE TITLE
"Can Trasnform to [unitFilter]" doesn't accept conditionals

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#9556]
After lots of testing, the unique "Can transform to [Unit]" doesn't accept limiting conditionals, such as "starting from the era" or "after discovering tech".
I tried removing the conditional, and then I could freely transform my unit.

The Civilopedia displays the unique correctly, and in the mod checker, nothing.

![imagen](https://github.com/yairm210/Unciv/assets/78449553/de1ba1b7-ca47-4fee-9b8e-1fc73a3aa771)
![imagen](https://github.com/yairm210/Unciv/assets/78449553/54441b10-8a3b-4650-a807-c8474c50f4d5)

So yeah, I would very much need this in order to not have Industrial Cavalry in ancient times...

*with the mod "Latin American_civs", it is as it's on the screenshots.

**Comment by Caballero-Arepa** [comment]
<details><summary>Test save (with Sandbox difficulty mod)</summary>
<p>

H4sIAAAAAAAAAO2dbXPbOJLHv4pOr+6qzKxIUXxw1b1wPJOHvXjsizOT20u5tiAJsrmRSB0lZeKZync/gE+iLDYJdINWdis1VRlL4gNIgvj/utHo/nP4haebKImH538O491qytPh+fhsOEs52/L5x2j7IH/Z8q/b4fnQfeG9sIPhWbVl4E++fRNbR1+iZfQH24oDbYbnn/6U3/zCVlzs85KlU5ZGTPxwJo4zK443e9i85xvO0tkDn4tdhj+lbMUGLJ4PbhK+TR/F1jdpFG+j+H5wk/KN3P16vY1m8o8rtn3gK1Z8er2LlnP5x8Us2W2qTWYPUcyzA11FsTiM+OPn+F58x9P80y0Trc6/n+9mWevlQWSTst0ud2nK41nWlGS7zb+8uE+j2W653aVcfHqbJvHgY5J+zo/zehevk9/n4tacDT888GSZ3Gfn51u2HFyyzbY43SyJk1Xezktxy7bpblac/Rf2JbqvNyUS96o42SVb8njO5MFfsrg45RXbJHHWstst58vsiKs1y+7XmyTd8CmbfR68j+b55jcPj5v8xB9Stl7nX16Kmxlt8pv+UlzRH7x2TZcP0Re2zH4TlzT4+JCf5SKOVuKi3uw2U/HQsp8/plFxgZeyQwxuefolmvHyBix3aXY3bh6iZbJJ1g/Z7RSnlTfjcXgnOtI6WUaziIs+9Gferep3p/j2/3Z8s71iMbuXPVB+k/JldC82OPjyPlnOeXxxnx1suNkmKZ+/ya5Y9qVz25HbyF5+w5P1kuc78c1aHEcc5OBQ4iLE7o+H59xF8ebgmy0TrZyx5cXb4lhf10t50vf8Pn+/xJvy53C9ZI88/fC4lu/Gm92Kyecs2zo8n0z8s9qL8xuP+R87vmS192aRcv5BvjviAs6GG3Gr4hm/XrwTPSv4sEuzl88Nz0b1/+7OfrxuP16349et6BYfkrJjyG7xPlpkz6j89W18kyb3WX8Q3a/89dwNvx2+rcULdlk8qXPHd/t+gUfG3+B1mnyNVtH2UZ7ww6O8juGluHfZLY2W4lXdf77diV6dv6jVJiwWG9W+EI9yud+gYYiIk220iGY13SyE9tP110WSzge/xlGmz9vHu8ED2wymnMeDqXj/toMoHny6ZCmbsc2dOFc0yw8huiXbvpUf/iKe3Lzq6C/lSyueXf7T0eHlA2f5tuLaZ0vZoc+Hs2T1YheLp/hCvFnR7EVd51+8S/KGX5SnWCb1KxE3cfxNjuniS34vbr44Xq1F3+6eXP675D7bD7wnZTcdJIvBp2KAyO+KaKZ4/gJX/q35Rtzm4yTiGuVYW12ffCGKsbkcn7Ihval9T1/XUzX0aNiAW5yPwydraCEDYPtyUTlV8wpJA1tXaNupmldKK9i+UstO1cBKS8EWFmp2qgaWYgq2r9TvUzWw4ge4hSUunKyJFa/Ab3GOTyd7jQt6A9t3iGOnauYTKKy39m/JTjTqCx/wWCgQnw8EmYvXW55NksWAp+yuq521w326ibiEiwzlHgfTlMXiTuxioeWfwQsuKe8Ouou54XCqu1eYLeAzforpp2rnkbnQ8tZU9tfp3py9CQirTA32T6Y0dQMPbOneKDoZQu7NMrCVT430U7X1yFkA94DChj/Z0y99CGALaz6JUzWy7hYB21l3dZyqoQfulm4VuuLziH/BiBCTXglhiBsQIjEIrVY8nZk41lO8yhxMJ6Sr3MEFv3x1N9DJ3sADXxTY1tyJeKpGFi5MWHDrHsSTSe6BG7NFdDP/4+n0Nnd/wgNu6ew92XBbeZvhe1g4XU92E0unbwsCFv710wFg6eBvgarM2X06osp97bCTZntC4zifLugW0fc8ZtFmIySLa+vo+6wJbBltVqbVr5o4OJmDsJq5gF2Y5XzUydpYTYjBDoZ8JulknoViIgt+hw8mAU/2Kh9ORbZQRDEBeDqQKGcgwTbupxhP1cjaJGer+7+c+zzlHEA1/wrzRDmbezKeqKaT2/kxm4A9KTzmU8At1FPMQ58Oe8qJ8G5dfBvPxdiaRgjz8lXK+TwxIYmfLnbbZJaymQmX6afrNBu5kAe6k1Oos2ibTcB/+rOafpVPJZt8FfvPxWnYxJ0GbOJZEydklrsIXSsIplPLnTm+s7Dn4SKcinOVk9n5lLL4YpHsYumWFAbd8DAaZZ2sd8vqXPVPY7lbMr/NJuuH53kMwPbxaRDAMJvCLqeksyu8SuLdSjxwGaOwWoth4EEGoMnYixu2ZFlUw9tYRqVt+CAtO/FmLR6s+OVddP+wfRDam0/Dp5/5NgvMWCabDd+tsgCOVFzX503tMPOBbNpgXZ8lr02Inw2PJ8nPhtIZsnlI1tlJxRPLAjFeiycn/5LPI/M/besX/Hbz64ant6JJ5+IrLrap/fjfO77j2ROOpJnHB5cPbC048S6LRigadi3Ov1gmv8ughzCPLGJxGbRXBMeUt9yrhVM8iYgowpSiJa/N0Ivu+HV4btln8qNTfMw/ufJT+W35ufr1ya5j2Rt/F3eHzz/Uz+AeH/LJTtHmOhXNFdh6ydaRGLXK+7RYsvvNpeiF23nye3atYvRKdumM/8RXLBYX64Tf9i/BZR6ymJ3qKPZquE3W7/hiK/8U53ey0wfidkyT7TZZvZcdqPjN8rMfrSyyUYxu21vO47cr8Ti+8KyHNo56/9iIce4N2zxcsfVvXEabOKJniM3T/P2s3e9y53+wL+zFksX3L263RYiUMAJ3uRNF9MxZNv4Nv93JKAoxQP8susH17zGfA/drm4gPxfjwKklFH9zyzVacyTsbbsQAsnkTySiaLLrFlv/cinsVhGfDX7IX91I8HvG2ZZ1M9OkiHu3D8Fz8+0oGzIWjs+GbLPBGvAdiY3GfL4bno2/Z2J2HsHkHEWx5/Ms+eq05Xs3/Ea72I1wNGa62h4ICNYDAtePtzv2OCLZAvAxsnqzFkHJTbfVJxoGJdy4VFrZo3ismunT2V8UFWW8Qgii/visDpa8XF0+P1Ht43LNEx/3CxcA5Ff1IXPaeEChRcw1RcgDjfM3GKzlS+yXqjB078O3AswLbnVjuhHEr5O7C8udzPg+nczb1vT3q3DIxfrD75Ih1ynFLmXNso5zTyhhdfCMFter6R+35KM81EE9FiIadtbqJRWpb3ZnDjYPnlX0c5x+D4uMk/+gVH93DX93DXyeNh/KbKOR46yeHru8M0IgiZpgX6lEp1J6bCfUoE+pRJtSjTKa9XKVHmUr7QS7SI1iiw7pEZ+/xD4X+odB9KXRmkGcRvQN5Q9NHQKGPt+tUaMcXr4QYKHfL+fWax5m2Pt5EwnhOi5e2Z4kNepVYM3q6j0Lfa7WMPGfiHrLlxyQWnT0TpuvlfPCKCT1a7DLzU12F7VE+ftqVDM9m3oSzuTVxAtty+WxksWkYWkHoTWb+dDHifrCX4WIIOpTg4ssTeRr6VGApTmluezaLb76BWeGtPaLsc5h/rOz98vtyu+qHUbVF4wFsQG+fbl47wfcgsrKnSJcavxGdP5swk6+cEIO0mEAb1rYpnQ5yWiIR/1+yKB7W9HRS19PqhfyhqT809cSLtL57/XzWBVwqcqq/ggtWRcsrhsBRKYuB489GzB0L6zQMLNdz5xabsNCybd9ljI0Xo8Ddy+INky9/Gk2P7dPaIKMskN4/m0D6zyqQ9ad14AWulMsqbMiw/Ow93cB7ssEEOuQIUM3aBp2N+H5V9E2ykbe2LpFuXSKLl+yHQP4QyB8C+U8mkA32JkEicyOi8t4y1/cn09HEmrvMt1w3mAiLkYeWN5rOprNg7thZt4ifDCOH2lh9fSJlPJiKfgaZbPHi9qGT1SPLPgXZJ+/QeAwOTETv4FNwuOnhcSDnbeNxgydN+H71sGZV1iTRO5DE7DX7oYg/FLEvRZS3gBU3slkV61v8UMZOZTSS/6PFeszHNcutxHHk26478q3pzHGFOPq2FXrOyHJms+ncHXPHdv2aOBYDyhNtLL5Vlkbnn81otMfPazXun1L+OSxDhw7ttypWKnjye/Dkd7/5eC5kMHadr77/aeVRnma6TwUn7ryQBLZayz6TX8862UTHb0Dm2N/HgDli2Fkz2YJf40jumJnKT3YtvdhP9h2r7GuVO/u6Oz+WTv22fWT/m0eLRaZ9j3kQwnyafB3mPeuKreWhVmyduX/4NpucEQOgjArMwndnWxbfi/dVvllis9voD9kxhymbRzuxqSNa/3s0l1n7XDFEP/A8sM0J90MDF1uu5Ggkdi9925tsgUoqM/VEs8FL8cbG2Ssr+txy/jGVrcof8CqZZ6/7OJ1nkOFuH2SApBjVB1IvkzgfAqqkf4Ov68GCpfJV/shS8Rcf/CxfvzmXgZVCIgYvd0I1hOTKC5qxtew5g9c3hUoeJA/8+ato4WA/6ohhRAxb8eBiJUhkxuK/i1FOfvuSS8gY3LBYDEJygLg7yGf4W5nwsEhnOPj37JCDwJ/8h9h7w7NXwAu8sedOJnYwHhVvvcC6l1Gy4hfiWFlU3Ip9vUwEjYiG8WJAmRRDxDvBAY29uog1cOSGU7bhH7gY4CLZmusZz0bnh2ry/1tT/3SKA7jYAxRTM84Yc4BsTwd56vLMNnL/8tJHyP2Le2+HyP2LsJFs3hezf+kQ9JH7lx5HD7l/6U3E9r1CrWxs1ysnDVE9rz6Lie6A5bQktgfaTs2pjzrAuHIS4/bfhy7h9t9HQuH296owLNz+VXA1cv8aF6P2DytCwg1B+wly3P77iXHc/ugT5x0PfV63XCCA231SrhnAadaYKnoORfTqqom6AyTVs4mq5xBVb0xUPZeoehOi6nlE1fOJqhcQVS+kit6IKno2VfQcouiNiaLnEkVvQhQ9jyh6PlH0Apro2SFR9EZE0cOrJU30xjTRc0miV2gmWvLcTs3c5t+84jIYNF/e8jZf36sox/CloQ/tUHS2LtSoh04SWpsotA5RaMdEoXWJQjshCq1HFFqfKLQBUWhDqs6OqDprE3XWIersmKizLlFnJ0Sd9Yg66xN1NqDprB0SdRZtYtg0nXVoOjum6axrRmfJxi1a8hyK5NU1E/X8SZpnEzXPIWremKh5LlHzJkTN84ia5xM1LyBqXkiVvBFR8myi5DlEyRsTJc8lSt6EKHkeUfJ8ouQFNMnDw/qIJnk2TfIcmuSNSZJXKCbc59DW34SqpS5VS8dULaVOUlokM5IkpjZRTB2imI5BMc2m2YcyNKdai/cq2jwoy/NxTy+PqCbPx/1RbX+PKK8+UV4DUF6xdzQk6u2IqLc2pLdqD6TUa7Tejol66xL1dkLUW4+otz5Rb9EPPqTp7YimtzZNbx2a3o479FZRVdGi6FJFcUwVReokpkUyNEmqaBNV0elURTVVhTWwAdcutsly2Q1sbqc+1vTlOlrWvrhYyUDJ7BBqGnzce/U0GNt5/U4NVdLg455Lv/0hUUxHkJjqiTFaTB2imI4hMVWEAZcophOimHpEMUU/uIAkpoUWE6eD0WJq08TUIYlpocVwl0fbvh5VpSdUlXapKk0NsLWoU6AWyYQFZFpxMCHKtAPKtJ7xjDVV3U6ZxevUBJRg+rE9ojz7XfKspO7YDhsSzdkRpMDl/uVCnpeP8p7W1lN03thS3eGRknBsp0u5CcceQ6qO9XmUnIDW+QlR54nR1nhjnaTzBSYQQ63ROm/TdN7pW+fRMj2hyrRLlWlqSLBFnba1SEY1oNN65jzW6HA6dRqvhWNQw1+nbLNZyqT5T4fWfJHy3cGoeBstv2QL8qJ62vvhRZwl6Rxkq6cPLzRbdSsLGMgNm9ZVup0IADRLjSyO34Wf+IanLcetX+42ibnm9Xhd2IC6HB+iCS0YwdJESIEJbVEdQXhhDl16wQunCy/o6IJWXJcIGsTIObwjgwYaAQk0Ck5Bg8aIBhp2T6BREAwssWiC8TsJhgxHaLaZUNmGusjXooZhW/A0utowbnW7IrQGaxLu2CDu1JGkob+8EkOoOP6dipJ2qrUDgtGNTOe7aW7CFUvFvYFbULuLl2z9KIZ5pkkRY5CKFIANg1/H71XbDeh+Bmzzcl9A6b0slFVmiqj9VP9Wo80TCLGqJiNapY94xwNB1/lr/SJLHbXpnPbqbIsPkV29nwD9kfwgAogL4U4KUk/nyUIIC4G7DlLoLVtuu17HVV7N51HmZ5HnT36P5S0aHuQdSYpcN9dNP5ZZVXabz3y7yob3ogbcVWU4OVl6qVUir7JIg7UqfrziqyQtc0ABhOy24bP48e7bGfwr9pEdWn77fC77rD2aQ13J5MaEoCgRAD7/X1MWR1kSKeK7VxI/dgK6pHo0HRODhfBuR4DKFS/bp1F5QKLyAurRVD7qoHIlqO+RvdGA7FEBeUIFZGpCAIu6aMOCQ2o03Y8oKsbx8BtZjuvMLBbbKCz+6y6+z8/VzT8vWSz+03UWOiAWd6IfRu3Lem9Phb78XkXjbZzGV+mAWoyDUS7xeUVlFiNbf8u322Xm1MW001FvJ/iraRPH4OM0fUvc6reTP7kqd0ZnM6Ef0eaXLLhLtf70ra9ebVJPxQ6DRm8lO7qpuaQb6atYb5pNfordCGuyxcDDqh+lVVWm1OewcUvzrB0CFMwdjAHWIvZ6BhbS51Xl0FOcQMmaoTB1gjVTXJqRNKEZSR7NSPJpRlJAMpLsKsU/xcZCrzbL+zNshqBtrDINA9rGKkPG0TZWaaShbSxqqlGLmgzG6l7Mp2ikYWceLPTUQ6l89bEuYU2LF3yNoQ9hafVi7LUYVYg5EIxZZ94UIBJ2kRzenOtWwaxrhm4wPaxeAM9lsl5nF4SYI0LMdyRs/vTO7k8sS1jvCe2XLAW/GvsfD16olmjbAwrYjbgoMHMu0XTQNwWOh+QrOZzJP5FxS2BWXvDAXTgLIzp6OFdpgJmZQxvMEqyF2rXOXGyg1L68bxZ7KHXNWrlejfaC1kB7w1FvmtbVwDCOsywAA0HLvkAbCFDmZC37AmYo7bA9n2YyBCSTwQ5pJsOow2RQMwzwXO9Tud6jcj01m7IFZ7xSxPLu9ciKhsHxO1GNVjqDtQXPgigKi54JcDyQVKHK/ao/nMbZcLARmO6515AvUzYAgff9Ft4P2ni/hbn1+4RxHAfTZ1MaWQvUeeBcFgU7DDm5jLaPg5n4O3soJwL7y8bbc+KJJ7els1WZyps6G5jGnGaBKIa7Ge+WYFZ1qjUDpltX6e+IqZBjIdMzm2LZCrb8mMTz7O5eL+eDVyzaPix2TU4rr9/5JjBZfE9xXoBrbtxuh5i1OMAE9x32k+qQh2198/h1ZP1pAEGD5VetFmtqMcmO6zC8OluGzDhjQ3n/q6epMuQ58Gtjw3aiwVXLUP0ALcuRWLMCbegFJEPPDkmGXmEnos28kGonBlQ70afaidRacxZcDUDRzOvO3dggIooLZS1qtgwLXlECROTfIhaZWvCcDYlxADOwa8kswthsiR4iRhY2j+06E3J7S9Ws+XVs2SCWBPU/92HAIjweHLq7ZUczFVsImz7H403/1k2L1LcYLi32RXdb3qZJTG8JWLBCYXhRMRZgm+d43Gy3eVRnh1Asa5hbdRxsfbUBqsjR3RJELBdxZQwxdAtNuBMa4Xo0wvUBwkXzfkBi3gKZycxLnlxBI6tPRVa4UqQiFMLVPDSZt32OWwsh1XLCUGNHLHjJBnAaUytjLXhag8zI2jMYPS7SOX6vjHENwBJeRztP7AZvm3OpqrI0ucHBki39heJ9H7eqcQ1IVYCmZXqqxxmD13y16WsuR9mOMT+FAJbVec6sF2BtHtPzGGARH9SEPFjShzb4Yvj2WAAAHwkKnqESQupBV6ZE1IbKEWGGRIIhoddV9w2o3ZIP6W6xWHLdTmdDJZG0TBEsORamCDr3sEfzlvs0yyEgWQ5lZQ98waQR1fQIqaZHQDU9fND00LRd0KYHXOrowy6eZ3Gdqq/gT1zffoDTT5Mtn3YhQVk57R4eFW3CmDgtatQi5BR/NMrwqJaMIKyc54TyZrPg+BXW8MrS0oChMLRrSTNMve1wenBVcgG65jWBhapQTAiWreoJZVugTAtl4TfW9FQWVB+rOiECTbVjeHCvPlRcCztM21C5LS2v9PHbWAkhyXcyhvERzX+TDl+yEj6i+c+n8V9giv/Q+BZS8S0A8U2RvnwQ3zT5Dx3QAJfZqro9CugM0pdaKhlDQmApRbFjMK4dqLTYTDsPCQ5AwTpfHWfTiecwlq4PLCr2fOsswbpkPfRTsIZZD+cC651ppW5BcJ8hHMOtYGjwVmt7M+nOTH0WVItf/fggzorDQ+0+V+FhL2k6obpwRIxE+/SgSnFNGNnhMmlhRjT0TQDo02JGNPT5EPQRwx/QZT6tahE0vijNiMqRIciRmiCKdgP6VI6ES55X/f5QYW93aZTNc96ZN4otuPIc4NWptwbFuy0Z1g2dSSlHiGEKVnNkXCx3qyhuHMwDHCtrA26TxGC8cijeJdF1O7AiCBiNnzTgAcvvYS8HrL6HYkCwFp8mCprr6+3djOqHhUoA9smfUN3Ad+zz04lZkF7b+w/1rthQcUE0LELlBon0iXYJjml06NLocEKjQ6+LDtXoks6CaJKrWBCNciEV5QIqyvkgyjWvwASIpo0Sj5+Q2myzEkK+2qWZsVsLra+2rLcwD6+v/aQUYm/BtQdRnqaDi+ipyWBOZ3KLMQSLW3aFwdfjYRA1LWaBjlB9FEH5KPcOVQRg4ngQywBgmUSD6yPBcolKGS3p8/ZguUWl82tRa++vClTBsReTB6r3qAaIULlHHbw0SH5Q/UciSrabBQiURLPgmMaCLo0FJ7Tp4ZIlibVJGyBIlQTheo7kTNUVp+Ir2YxAzNTkVGwO84pTMZhJT/ZRUW4Liiqdv3Dh94VunhJtwi1VTTWj1malxDIWWMFRrck9U7CJVf9AXzC2uA3MBoDjVzDGsRZo+DSbVPbT4FZcZoTE5RZ40cLllgXzCBw2kRbeVEYAsMIgVvLBkoOmsbH/JGlQEUPsrYGqGvYIusddrWn2BDMTDxVJ7HnRLVRcER7Xr1gcLRlyiZRO5VnkiaCCjQAD7M+iNiUwRhE7jNwNHVQx9VFB88earFcuB43jEwjHteIODOA4jMx0HEfDdIXjaJoOO2laEcdV8+5peH19kGG/R9RWrnz3HMyqWw6PGsdgijjBFeQkgD1+d0n+3OPXVf9wzUipOakM5zJFAK6hCXOwXJtp0DO0VAiq54blRajAWy+ueqgcHKp7Q8XhCKvyjVZtxKEaVHSOlh2gEegaJhCL7Y5H9OoHnYzBLbypMf3Z2Ha1tMimLgeqxdeJzwgqRqPrmBhV4BLRdUJD1xJ90WhowzX56OgLl+szh9X4Kx+BVKyJ1diHX2E13PuoWH38XuhRNRyJr+nNKgEaBauktZVt6GyKaMHcp00+nSuWTrWD0yxwPXjf6/1riG2CiWuIbQLuOqBWX/R/4zH/Y8cRSgQxMTpkF0XXLVdD7AVQzTNUnBD6NkOl02go39IVid5YqNgagd6/A+CGSrYBg3kjjcJDeQ80ChWJa2Pr5p67vxbV6dPuS1CryQFVqmuGhWbrJV82pX+DYcCH0VuhPdhqHA4R28fEABCXiO0TU9jeB1rDxfR0Q6XxHvkRla3DTrZWg/MWgtYwx9ud1lrw5GMiFaBV90C7XrJY/KddNdGDqBqdHgEsT9ZbzhwLzP9JcnabQmcwhJZE4ibcws3wi0nVhUdwVR6BsNjUXDhUpUqlOfpIji5S2p+tABWuQqw2TJbzwXWKSzVmYrkj4DTVHFagylkq1ru+hQCvEFOAfxD3levP1FCvL5LHhUGYaybM5zAPY1rWwZF2FwcTgkIcIiOPiYzs0hi5ZOw+CBmuQ6bL7/DV0fkdHe5R8Tuavit+76NnlmyPRfODwR1T2CKAEByXFs2HsNn40jevE6d7dCKDxbhIPndTYA2mKCBxuqF4Cwt0Lj+zS1g14pLoRe+fnKEiVcT7qQ/vaEY26k9Xjha+RSzJhGpqqWkJVFJLbe+uiloUHm5P2qjg/TQbeq3viO0AqFGPcGkT4dIhwuWYCJdu/3DZBxrClb+wOdb2uEnPrIH21Za4acZZC5aVN1Ngs8RX5cgosD0Y93EAwabSyTFca27RcsmvphASrMhk2itjgRlZjZ8JzH+gcqb+HIJWd8iwIaDp4xSz6Eu0FO/A01pt+yMc12ur/1bUbLvlMi2VfGVnuzQVh7+qpo8dRBW3DJQb3PD2cd22dqZu6BFVRgq1LoHP2Gro1r4TwwlPk+GT23jw6ZPoucns8+Ct2OoqSZmcEFO5z5VZ4jQWxOusk6V2CzHBJZ0VshRPHSHTrMB5qNTeNNAewRoLUM0sNRKhlcyCKmaptRwqmKW2N7FeVon66DBmm4jjTheOY5G3BH3zoF6aAH0ETsOFtxow/TJlUwVEhqtptZhzmmYF3gSAq2hp+qyVI55Bqsa4OCoLBAn1GPvhORA+UEF4ZaC8ipZZZ6DbFLiJ1KbW6DbA67QZTJwFrJRF8pU/Y5EGi5RtQtEOiZZfEFXJT+nztSD/ttGIDcPFuzVRvF6Z2pSd4zTZOQ043g7i5Bvb5rCtxxDU78rTMIL6b80BD9/rc6hsnXEjD5U/ZZdk2qo7ugC33wsAfuuva9XinMz1pEZzsQejDaqOZ8gaxE7+dJXA0/V102ri0UrigRXxsBcTEmdgRpDJZ252CDZ/6GFNPRiE4/4NQtjAps834Y03uAifpvmnOoUJ2m6KU1Zg1T26BQWJd+0Qx9J38GOhfZdpstlMk9/NCnhlqPqtE2l+owrWfqavozq8p4drqarfBjyesdU6+xpnJRtPCkG3YYNOGxYwITvXOjzN5FC09SiStfheLc2Qj7V49df6GWmvR5lrM2i891drryosheLR2skNFmci5zkizCrSK9lgzfvv2FSzqjkr0A3hGDXWDM9ual0C9CPJ39VmuP3LG/uNVnKzfdyHZdy1tvp2Kw4nDjZ8Lz4gbWa1Vdd4mxnbSUDLHbYsiJY7dsIUKjeqtjdUbVRnshY7YdpZa1TJGseaTCFxunTUZR+r2dc92MBOXzZwaV33UTEBrk9qznLHW9dwFVFN+xz7rlTmuWrqCdA2ajPGkdOZpiZuW2oyn8RIDDETnddsE21azBjzxlZACaEEWqmcV6XjCtQKUvg9mIsNZk1vdm5LpCfWjYCtqIyCQD3DFz4FYnb6dHZjsx3bvpDf7BR0n3NZTX3+X9ZKcpusJLfRSmpfZaV2b2tl6XqbJ4Tq1qrYPOTcTlCNW0OmDtZYgYrf6pg6WAAjlr4FK99q2TrY1eQh0VYZddkqarZODxaJ079Fgrca4Eq0mnYHdsK6MjuwEdGV2aG6ehNldrRwv7EoytLG0K7tanJWIuyB1BGhUUbNjt6gvYws7G02zcT6rKaWG5zR8SCqN75mrf9KtpZKBYgDypJzGTir4jtMx2VBC4WMtgyZqsuCXOzPFZfbyLrPGBQM1fbVzxulQcO0+r9d5X91Q3KgesA6cX5oPgarAWvh9fFrr+VAPEhKpFvxx4GxHcvdIYTdetjeA3bbfWF3CfSwiYgHeriisCpNw8V+VXEaLL2raRHggR4sXatpEbRAez8sVFoLz0AqpbHQ8wqjsJOgTZwl6IF2MevF9CC2mkbR4+VnAGWAYjVDrUyVKLZUijGYunaVdFkIJu6/WLEFuVNRLW8kxVqpbggIWyYjQSTtw/ECVbFtdu/qHJlWxBasYauFoFiGBCvYaiHo8cvRJIv6WYxa8BLLh2EXHqrhpZbRpIWXfUIg3icLlqHVdAubs9wqKsROrFRUiF3lVVEhNmlIRXfPoQUjiucSQ3g49sJQ3jN4ClsKtpk6hafgKURAW++rAXAT+ggEQ7wlqlHVprPuW1DcrLF7D/nuzBJZI4vpm1Bw5BzCpwyVdzWFiLi1gCqI2KC/HQZLo5sOkX0RrBaLimICa8dqMSfWQejTADCgAWDY5QRU40fYwqHyI2zh4PkRrhdrjE3xZAkWeNVEUzxHglVYNd2TeI4E66Sa50iwhqpxICqRFQeS1JnL8NnY8rjn4pIt+VgnHTAdhMny63Uxp9oTw87odhZVNTutb6LME6pzQnlPcEHJUOQjyJJ6AU+ASw8VAkAjye85R0LGtA38HTRG9LaXAEDeTuO5EKBCrcBUj9EFNmClVky5SrBll8ks0a27A9aApSeZAcvDogoEgcVim7y7CLXwaCTv00g+6PLkKhkCSkmelDKllqYBHmTByrHGKB3fNrBEqyal4yEbrK+qSenY7lpRuonqlChqKNn9GTyzVR02Q2zboiE93rCgi6gRfI5jYwSE61GwMQsAKoCKu2dQVva+88ceDzPGnxIUCElbCkhZLQA4VpV9lEZa0giMJu9J94x0V77aRspFlquieqvRM/9glVStsAU1NgSThh1aHBfxLBJ/DdId2ieNFWePxpI+zSscdE39K6EoFs5K8MS7YMG6qMZcz314tcHyp5pMi33qFdNie13FtHgkBauPGjLxKuhtYU5zg8C+oht8NqJboWkSBIm0AFz2FCVhIj250XncgodN5AMgQI9HCMY01gioUGkf4axQZuumyARj8brQEvieoLoX7yjZ+u4nuqAdPVWibdEICdZC1SJQpVpDGou50Aw4oTGgR/Mn+n2FfwZ9xQWEXdiIRzOwUqkxoOwxzBbuAfoxrmDhUc21V3hCBCuIaiJmH5V/URZ3Z0yuIb4rzaqTeC5DgPl0Z97MeEgKBD0x6vnfA+p5CqhnmCtxvkxqD4RStFLypqEXgHZFdiqFMOAwqxmwFD0zEGCp7d5Z3FKJz7AJkDrLVCrRmJKYIjN+eX0hl98XcgV9IVehFz0EeDpggUpN7yLeTwcWk1Q9AFj8UXX8AIs3amIcnsLASoyaGIe1FZuSHDf65NhSn7Sg4oaqTRt10dJzkEEIMNI/c5xcL/UlgoLjYNBsyIJZ/9E0AJqvIeTTHIKGabW9lJFhWjVFjFDezGfwc6I5E4xZVBUqyJ+nsD8FNMGyeVqcilVHsPyd1kw2lg4mXXGASgxqHhX9vlAx6B0V8aQH1l7TREX8jCxYtExzUhn7LlWoiCc9sMiX8rp6464+PNpBBZn00BC+IsLCiBDAEQOHDrrC5gw71fCEUI+SRuW+9BTC6PqQeqiIUBNfXCaLBde+MlpuQgtcc6z4GnfGl+m/zAR3FoUvOqsOKeEJVhPA+kFaeILliwktNszriyL8viiiwBNYvfB4AhYMUn2jwJI/mnyDxxOwbI4m35iUeLCejG7KeTzxEL1ieFSC6q/o4Q3eLTjqj0FCgEGM4Q08ohIO7QM4oXhDPdo8VVe5Du2XC8wup9hBO9cqqkEE/t0meBYomt9ZvEMJGeAeGkvxYcuPSTzPnKevUyFHA9FT04ing/ecL1S5Au6qBs7h0uhh0kUPKvDRwghKiNEjCaCF3AELc2iSAF7IwUoWmiSAf7XBOg/Kuo/eE6rKoJc5EH/pUFkE1f27igPrQ9ioQ60b3hXViKqwQ62VxB4N3T6gyIq7Q9V+FXcHKwQo7g8m7tJzAqB7KjGExKKY3hQB7szVr6Tf2E43psmmS5PNCU02vS7ZVFLdHkoaO2ASftXODCbT15RtvOqC2e81ZRsvPWBiemXZJtrp1ILU+EuHMrnrqTb+4UP52FX3HwFCqrh/2GHaEiQ+oJm9Pk1kO8tU0kMFLWKedQvMzKNniKM7LzjHrifkqM5LUeLOrOhKQo5V4jFNiV2aEk9oSux1KbGi3uLlEkxvrqm3+CEbzEWuqbd40aIuL6dWYsVfOpTeW09u8SMOlENbT27xuDKiuYJDmuEZ0DTRJxqeYG06PcMX3fvA/CJ6eokfemgOYItigFIErzMLtJJeYrvdmCZ4Lk3wJjTBK/QSj1hgGmdNwcV3WjA5s6bg4kUDTJusLLhEy5Za6JA6DY3XSyinsJ7e4kcsKA2wnt7ieWdEE8yQJpgBUTB9omCClbj0BBfd/cDkCXqCix/8aB5bi2IoUhTTpimmQ1PMMU0xXZpiTgwpJl7wwJSqmoqJN5LBRKfKikm0TQmmKVHwoDyjeoKJFzwoOaieYOJHHCiDp55g4oFnRFO8kKh4AVHxwPrleoqJ7n9gykg9xUT3PzAwWE8x8f2PYCpSJM+mSZ5Dk7wxTfJcmuQViokXPDDjo6bk4hUTTOioKbnocQPdc0rrlGCcEhUTSnmop7h4xYQSDeopLl4xoTyAeoqLV0woB5+e4uIlMyRKZkCUTLBes57kojsgMcWeRVyra4Exs3qSi++ABGORopk2TTMdmmaOaZrpGtJMsplKnknFSx5BLImSB2WS05NMapgxdT01XvKgHGp6kkktUo4fcaDUZ3qSSchJMSJqXkjUvICoeWC9WT3NRPdAMBGanmaieyAxmNUiTilaFHORIno2TfQcmuiNaaJXaKZap7s7G262LN1G8f27ZMbkYWT0353Y+Z6t+A1Lxb9bnsokTcN5tFhEs91yK/Yd3rJ4Pk2+iuOtoviX3WrK0+vFzZI9ZhuLnr9iX4++lkPiuvzw6c/h7CHZ8Pgy+iIOWK9Snm/z4XGdrdvfySxS4kpla2snu4y2j7dbtpXxiu7B+eq/yFE8bt4jFZeQrH7Jr/omSZZZTRvx7Uwu2H+frOT/XvNUnP5R/HW7lvdR/D+J7x9YJP4STY6ybW+SIt3ATZJud/dZHfmrJE1msyTLdMDuxQ2uLUY836Y7Lts1W3KWfuRsLVrwc8ymSz4fni/YciN+/RLN5HOSdyGLyLzNqiNE4hGIo1+KxyCXeIk/f0rETckuQn6I1stkJT7NhrVn+3PKxI18G893m61owXLAswIPK3GQKL/Xtzz9wtNfU3EPhg/b7Xpz/pe/7OJZ9GWT/fDi6+MfcodknjXlnThBPLhY8TSasfjv4gFusnOX/ePvZe+QHUm0U16yXeUBy7vDk0de/PZBbHwrW/0hkmnEbC/wxp7rTezJ2M375Ftxh4Z+6DqLyWhhjUfhyHL9YGFN/enC8vgs8NjYH4/nY3nQBz77vNmtxB430c+/ra//+vLm6q8vR8v//dvD6uH6w3/9z83s9f1/7l+K/NSiDTIxw/8DY+cjw5YKAgA=

</p>
</details>

**Comment by yairm210** [comment]
Please see the very long discussion on Discord regarding what units can and can't be transformed into.

As for the initial "hasUnique" not including the state - WHOOPS, but easy fix

**Comment by yairm210** [comment]
We actually don't need that 'hasUnique' check since we iterate on the uniques anyway, so that's been simplified
Also fixed the 'only available when' state to match the 'getMatchingUniques' state
