### ISSUE TITLE
Feature request: change nation by new era

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9557]
**Is your feature request related to a problem? Please describe.**
Some nations have advantages at the beginning and others at the later phase. This feels always unbalanced in different eras.

**Describe the solution you'd like**
Add the modding ability to change nation from a list of available ones by new era, e.g. The German -> Roman Empire (Germania) / Roman Republic (Germania) / Merovingian dynasty (Austrasia) / Carolingian dynasty (Austrasia) -> East Francia -> Holy Roman Empire (Ottonian dynasty) / Holy Roman Empire (Salian dynasty) -> Holy Roman Empire (Hohenstaufen dynasty) / Holy Roman Empire (Habsburg dynasty) -> German Empire -> German Reich -> Federal Republic of Germany / German Democratic Republic -> European Union (Germany).

**Comment by Caballero-Arepa** [comment]
Oh, that would be cool, like in Humankind

**Comment by GrimPixel** [comment]
I know almost nothing about the code and I have an idea: I guess it is currently using a parameter to identify the player and it is the nation's name; if that's true, then the identifier can be changed to numbers like 1, 2, 3, 4.

**Comment by GrimPixel** [comment]
Now I understand. Thanks for the explanation. So the practical practice is to overwrite the display name and buffs of a nation, cancel all construction orders of unique unit and building in cities.

**Comment by GrimPixel** [comment]
There are 4965 results in 122 files of `civName` and only 39 results in 18 files of `nation.name`. Looks like `civName` is that thing to change.
I think it can be made easy by dividing the files into groups:
* translation files, which can be changed with ease
* those files with `.civName`, which means it belongs to an instance
* the other
Do you use VSCodium? It is easy to search in multiple files with it.

**Comment by yairm210** [comment]
This is functionally **impossible**. If you want to try your hand at it then go for it, but you should be aware that this is like rewriting the entire way that civs in Unciv are recognized.
