### ISSUE TITLE
Automated workers build railroads next to roads

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#9585]
**Platform**
Win10 x64

**Version**
4.7.0-patch1 installed from Itch.io

**Describe the bug**
Automated workers are building railroads on tiles adjacent to tiles with roads that already create city connections.

![image](https://github.com/yairm210/Unciv/assets/56904240/272bc7f9-2263-4630-a451-2627e20002ee)

![image](https://github.com/yairm210/Unciv/assets/56904240/55e0288e-07b6-49d8-83ae-204495f3a2ac)

[Link to discussion on Discord](https://discord.com/channels/586194543280390151/588357826758574106/1118201019889893387)

[Commonwealth - 196 turns.txt](https://github.com/yairm210/Unciv/files/11739777/Commonwealth.-.196.turns.txt)

**Comment by yairm210** [comment]
Resolved by e558ebcc
