### ISSUE TITLE
Save and load screen

### ISSUE THREAD

**Issue by Vin55** [yairm210/UnCiv#961]
If we have a lot of saved games it is quite tedious to always scroll down to the middle to give a new name or to the bottom to see the last one.

I suggest that the latest savegame should come on top and the save name textbox should be aligned to the top as well. 

Related minor issues: Long-pressing backspace on Android won't delete the name word-by-word. Names could be generated from the civ name and turn count like in civ5.

**Comment by yairm210** [comment]
Good ideas, and simple to implement as well, which is always good for me =)
Thanks!
