### ISSUE TITLE
Feature request: multiple promotions/promotions queue

### ISSUE THREAD

**Issue by aucunLien** [yairm210/Unciv#9610]
When a new unit is built in a later game city, it will often have the experience for 3 promotions of the bat. Currently the player needs to select each promotion, in the correct order, and confirm each time. I'm proposing to allow direct selection of e.g. "shock III" then confirmation to get the three promotions done in 2 taps instead. That would make it behave a lot like the tech tree.

There will obviously be an issue where the are different possible paths to the target (e.g. "march" on a crossbowman can be reached either through the accuracy or the barrage paths). To alleviate this, potential solutions:
(a) make the player tap each promotion in the right order like in the current version, simply remove mandatory confirmation on each step (so my first paragraph "shock III" example would be 4 taps in total - still less than 6, and no jumping to different ends of the screen)
(b) keep promotions for which the path is ambiguous greyed out (or make the player first tap and confirm "accuracy II" and only then make march selectable, for the crossbowman example)
(c) naively my preferred option, a combination of the above: all unambiguous-path promotions are selectable, and once one is selected, un-grey everything that has now become unambiguous (so to get to march: tap once on "accuracy II", "march" becomes selectable. Tap "march", confirm. 3 taps. First paragraph example of shock III is still 2 taps)

 ----

Then on top of that a promotion queue would be fantastic! let the player select "drill III" on their new, 0exp swordsman and have promotions auto-attributed as soon as the corresponding exp threshold is reached. Bonus points if the player could opt to apply the same queue on every unit of the same type automatically. Or alternatively: the first time a unit's promotions pop-up opens, auto-select the last promotion path chosen for that unit type, and leave the player to either validate in one tap or amend.

The same issues as above arise for ambiguous paths, but the same solutions do as well as far as I can tell. I suppose that auto promotion might be seen as more than just qol as it will help out an inattentive player.  That's about the potential downsides I can come up with.

------

All purely for quality of life purposes. Micromanaging unit promotions gets real tedious real fast, so anything to make it smoother would be a huge win in my opinion! I spend a disproportionate fraction of my playing time on promotion screens, but it's almost exactly the same paths I pick for a given unit type, making it much more of a chore than engaging play.

*I would further propose a change so that a second tap on a promotion is interpreted as an alternative way for the player to confirm their choice (and even close the promotions menu? Now I feel like I'm getting greedy). Keeping this separate because it would depart from the way other parts of the UI behave. However, if none of the stuff above were deemed possible/desirable, I would still find it much easier to "double tap" each promotion in the path over the current "tap promotion/confirm at the other end of the screen" way.

**Comment by aucunLien** [comment]
Oh dang, double tap does indeed work. I feel pretty silly right now. I definitely tried a number of times, as I do double tap in the tech tree, it must have come down to smaller targets and fat-fingering it in the promotions screen.

I take your other points too, quite reasonable. 

I'll just add that, while I understand the appeal to keep things consistent and while it might vary based on playstyle, promotions are applied at least an order of magnitude more frequently than policy changes or even city building. And as you mention, for city building a queue does exist, so it's not like everything is all that uniform (and I think that's true if the Civ games as well?)

I've no real clue about the work involved, but as a player I'd be psyched about any form of automating promotions. I'd absolutely love a queue like the city building one! I'd also love just being able to promote directly to drill III.

Thank you for taking the time and answering. Hope this is not coming off as complain-y, I love what was done on unciv so far!

**Comment by yairm210** [comment]
The difference between the tech tree and the promotions is that tech tree requirements are mandatory - but for promotions, you only need *one* of the prerequisites, so automating the path can mean the user gets the promotion he didn't want

**Comment by aucunLien** [comment]
Man that's awesome! Thanks for taking this on!

Colours-wise, here's my idea, followed by how it would translate to in your examples and then by how I got there (I can get really verbose, sorry!)

- Gold for acquired promotions
- Green for "currently accessible with the available xp"
- Teal for selected
- Black for everything else 

I would further purpose that teal should apply to all the promotions in the favoured path, if any can be determined. Keep the existing inter-button white lines to highlight all possible paths. Optionally these could also turn teal along the favoured path, and turn to dotted lines where alternative paths meet. As is already the case, the confirmation button being active or greyed out tells you whether or not the selected promotion can be bought right now. 

----------

On you first example, before selecting anything: everything is green (chukonu stays gold obvs). Select logistics: logistics, all three accuracy and all three barrage all turn teal. The connecting lines on both paths turn teal, and the ones merging into logistics turn into dotted lines. The confirmation button is greyed out.

In the second example, before selecting anything: everything is green, except gold for chukonu and barrage I. Select logistics: logistics, barrage II and barrage III turn teal, and the lines connecting them pop up, teal. The confirmation button is active. (If this feels like hiding the accuracy path: also get the lines on that path pop up, in white, and the merging fork is dotted+white on the accuracy side, solid+teal on the barrage side, solid+teal into logistics)

---------

The colour scheme is clearly linked the tech tree's, which I suppose is the reference point, yes? Then the differences match the differences in mechanics between the two trees, but I would think the current scheme for promotions is trying to give more informations than is really necessary, hence 4 colours total rather than 5. 

Anecdotal but I started playing unciv with no familiarity with the civ5 promotions mechanics, and I was initially quite confused with it. I felt the colours didn't help, there's just a lot going on really. Which makes sense too, I think I started playing just after you guys added that tree!

So anyway, I reckon 4 colours ought to be enough: gold and black are obvious, then a colour for "currently accessible" and another for "currently selected". You already have the confirmation button being active or greyed out to signal whether the selected promotion is currently "buyable", and paths are already highlighted with connecting lines. The could pop out even more if the border of each connected button changed colour to match the lines as well, since we're at it.

I think that the 5th colour (the blue of "logistics" in your screenshots) comes from the tech tree, where it signals "your next research points will go here". That concept is not applicable to promotions, so I'd say better remove that colour entirely from the scheme in promotions tree. The only mechanics that are in the promotion tree that aren't in the tech tree, I think, is the concept of alternative paths. If this really needs to be highlighted further, perhaps you would consider dotted or dashed lines for "forks"? For example the one linking accuracy III, barrage III, and logistics. That would mark it as something different from the forks seen in the tech tree, so that a solid line will be a logical AND while a dotted line an OR.

All in all I think this colour scheme brings us closer to matching other parts of the game, hopefully it comes across in all the blabbering above

**Comment by aucunLien** [comment]
Now for mechanics. 

I think the way you're going at it is really great! It will make it easier on the player while not having to introduce a ton of coding and fiddling (well I trust you on that, I've really not much of a clue myself)

I would suggest adding any or all of the following, so as they're doable and don't introduce issues I'm not seeing:

- display the "cost" in the validation button, either in XP or in number of promotions. In your second screenshot, that would be 3, for example. If the player selected barrage III instead, it would be 2 (and 3 in the first screenshot. You get it.) Alternatively, add the little numbers bubbles like in the tech tree. If this is easy enough, it would be better actually, as it would be another visual clue to the alternative paths: barrage I and accuracy I both bear the number 1, same for II and III, and logistics bears 4. Makes it quite clear that it's one path or the other, in my opinion.
- after confirming, and if no more promotion is possible with the XP available, close the promotions menu (qol. Also it matches what the game does elsewhere, although admittedly not everywhere.) ie in your second screenshot: hitting the confirmation button on logistics will apply all 3 available promotions to the unit, and close the pop up since there is not enough XP left for another promotion.
- make promotions an undo-able action, like unit movement is? No clue how difficult that would be to introduce...
- we're getting into the realm of diminishing returns here, but in your first screenshot example: if the player selects any button on either path and then selects logistics, consider that path as the favoured one. So if I open the promotion pop up for your chukonu and select logistics directly: validation button greyed out. If I select barrage II and my next action is to select logistics: the validation button is active for logistics and the barrage path is chosen. I think all it takes is, when a tap on a promotion is registered, first go check the current selection: if it is on one possible path to the newly tapped promotion, make that path the favoured one and pre-select it as in screenshot 2; if it is not, or if nothing was selected, then the path is ambiguous and leave the validation button greyed out as in screenshot 1. Honestly that just turns a double-tap into a single tap, so qol- wise it doesn't bring much ; however it might help with making the whole concept of alternative paths more intuitive to new players.

**Comment by aucunLien** [comment]
Thanks @SomeTroglodyte, that's a very clear window into what might or might not make things difficult to implement. Very insightful!

Here's my thoughts on a few points:
- `doable but needs to introduce history`  does it? I was thinking of a single check of "current selection" before deciding on how to react to "new selection" would be enough. Either "current selection" disambiguates the path to "new selection", or it doesn't. Nothing needs storing/remembering I don't think. But again, it is a very small improvement in the end, definitely not priority material I agree.
- `Your colour comment would mean no separate colours for actual selection and the "rest" of the path, where I currently use a muted selection colour.` very true, but I thought of that as an asset: this is how colours work in the tech tree. The one tech in the selected path that gets a different colour is the (1), not the target tech. And since that is to signal something that has no equivalent in the promotions tree ("this is where your research points will be spent automatically when you buy next turn") it seems logical to not carry it over to promotions. To me it's redundant anyway, you can already tell which promotion is explicitly selected by two very clear cues: it's the rightmost one on the path ; its name is displayed on the confirmation button.
- `And you do not mention how to colour the alternative direct prerequisites` I would personally prefer to leave them green, ie accessible with the available xp, but not part of the selection. The existing lines like in your screenshot 1, the lines merging, and the description text in the target promotion are all direct indications that an alternative path exists. I don't think it will mislead anyone to not also use colours on top of all that to make the unfavoured path pop further, although I can see that's quite subjective.
- `Tried with brown and it's quite chaotic-looking indeed.` fair enough. My guess is that the chaotic feeling comes more from the many button colours, but personal tastes etc.  Maybe a darker blue? Something between the background colour and the blue of the "close" and validate buttons. Or, if you go with leaving the unfavoured path buttons green, the lines on that path could be the very same green. Last alternative to dotted lines would be to play with line width - it looks like that's in use already. ie lines on favoured path: thick and teal; lines on unfavoured path: thin and teal.


Roger on everything else, thanks a lot for taking the time to explain everything!

(I'll learn how to quote properly, promise!)

**Comment by yairm210** [comment]
@aucunLien solved?

**Comment by aucunLien** [comment]
> @aucunLien solved?

I was going to say: up to @SomeTroglodyte 

I put a lot of different things in this thread as we discussed the progress. I understand how the queue is a much bigger ask, now, and while it would be nice to have, I can also now see that it would probably not please everyone the way I imagined it working (essentially repeat the promotions path from the previous unit of the same type). 

The changes with the latest update are doing most of the heavy lifting towards the qol improvements I was hoping for. Zero to logistics is now two double taps, it's great!

I agree with @SomeTroglodyte on the smaller steps to tackle next: auto close upon promotion (if no more promotion can be acquired) would be a great little speedup, and harmonize the general UI behaviour I believe. Streamlining the colour scheme would be helping with clarity for newer players, while also be more appealing overall. 6 button colours when there are like 12 buttons on screen feels like a bit much. I can't speak for the mods thing, I don't even use any.

Maybe we could mark this solved, and open another one with a narrower scope on those smaller steps?

**Comment by yairm210** [comment]
Sure thing
