### ISSUE TITLE
Feature request: Tolerance for missing civs

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9619]
Twice now I've lost a game to a mod update where some component was changed in the mod, both cases specific to a civ/CS being removed, which invalidated the autosave upon updating the mod. Unrecoverable. I don't blame the modder whatsoever, if anything, the logical or common sense thing to do is not update the mod til the next game. But I want to keep up with exciting mod updates!

I was tempted to make this a bug report so I had to weigh user error over game error, and I lost that debate for the above reasons. So, I'd like to see if it is possible to add a feature that would make this scenario tolerated, heal the save instead of dump it.

As it stands, even if this feature was made available, I can't even commit a hard save for this particular game because the autosave can't be loaded, so by starting a new game, 10 turns in, it's gone. For my purposes this is unfortunate as I was on the brink of having had a feature in my test map set up with everything/everyone in place, only to think it was a good idea to update the mod. That's on me. Lesson learned.

Screenshot here in GUR's discord thread.
https://cdn.discordapp.com/attachments/1071804673956266096/1119856338219044966/Screenshot_20230618_000758.jpg

**Comment by yairm210** [comment]
For 95% of missing/broken objects we can deal with it by just saying "okay then remove this thing from everywhere"
For missing civs, wholesale removing the civ would be impossible, but replacing is definitely feasible.
In fact a simple replace on the *jsonified* gameInfo could do the trick, so we don't need to figure out all the places where a civ is referenced by name (because there are a lot of places)

**Comment by hackedpassword** [comment]
That's where I was hoping some regex magic would save the day. You guys have far more sophisticated ways to handle this from inside the code. I'm not giving up yet.

Just went through my saves, found one! Converted to structured json:

[China - 105 getting involved, bad idea.json.txt](https://github.com/yairm210/Unciv/files/11790305/China.-.105.getting.involved.bad.idea.json.txt)

This save complains that Sydney is not present. Let's grep number of Sydney instances: 2850!!!!!! Huh. That could be a problem.

**Comment by hackedpassword** [comment]
> Oh? :partying_face:  Then ***please*** go over the monsters in UiElementDocsWriter and tell me where they're bad.

Hit me up, somewhere, and help me understand the problem. @wphoenix on discord

**Comment by hackedpassword** [comment]
> I'm the no-Discord person around here...

Well how am I supposed to get the 411 on said UiElementThingy? I'm in need of some rigorous regex exercise.

**Comment by hackedpassword** [comment]
Actually I was thinking of this last night ... when I went through and deleted all my old saves that were rendered useless because Can't Load [asset].

In the code for religion, there several instances of fake religion (TheLegend27)[https://github.com/yairm210/Unciv/blob/1694a59fd2e4ed6e60d59ba407c37d54903ad1ab/core/src/com/unciv/Constants.kt#L60C8-L60C8] to handle certain cases. Leading to ...

I agree with the initial thought of a mock civ, but as I go through working out the details, I'm coming up with issues also. However, a new idea is this: Upon finding a civ or CS is unavailable, prompt the user for a replacement civ or CS. From what I understand all units and buildings, even unique, have some counterpart across the board. If none are ultimately available, default to the same asset that aligns with the current era. I imagine this isn't perfect but it keeps the system moving. Unit promotions would either be 1:1 or reset, too bad. Same with build states. Align or reset. What this approach comes down to is competition attitude vs causal/fun attitude - the competitor types will scoff and move on cause someone moved the ball on the table, while the casuals will let it go and play on.

Or: how does the code handle a defeated player? Could the offending civ just be declared defeated?

**Comment by hackedpassword** [comment]
In conclusion, I believe this request to be infeasible with 4.x. However, this should be a feature on the unciv roadmap as more players will be modding, and user-gamers will eventually have wtf's on why their game is defunct cause of an upgrade.

**Comment by hackedpassword** [comment]
I had another idea, low success probability.

UI:
"Could not load game! [nation] not found! Would you like to try a previous version of [mod]?" [y/n] y
"Version: {2.0} (1.9} {1.8} ..." [select] 2.0
--> Pulls asset file for [previous release](https://github.com/A1y0sh4/The-Great-Unciv-Rework/archive/refs/tags/v2.0.zip) making this a new mod so whatever is already in place to get mods working locally just snaps this version in (as ex. [mod]-2.0).

The mod itself could have a .json field specifying previous release versions so seek-and-find is minimized:

ex. ModOptions.json:
```
{
  "previousVersions": "2.0","1.9","1.8",...;
  "2.0": "https://github.com/A1y0sh4/The-Great-Unciv-Rework/archive/refs/tags/v2.0.zip";
  "1.9": "https://github.com/A1y0sh4/The-Great-Unciv-Rework/archive/refs/tags/v1.9.zip";
  "1.8": "https://github.com/A1y0sh4/The-Great-Unciv-Rework/archive/refs/tags/v1.8.zip";
  ...
}
```

That would beat trying to reparse a diff which was my other idea.  [The-Great-Unciv-Rework/compare/v1.3...v2.1](https://github.com/A1y0sh4/The-Great-Unciv-Rework/compare/v1.3...v2.1#diff-185bb4c0230805d22854deafafb96c50522c71e45c0749157d88d3b61c2e195a) Not a good idea.

I think the coding effort would be minimized, responsibility to provide compatibility asset links are on the modder, accessibility is maximized. Worth a consideration.

**Comment by hackedpassword** [comment]
I think the best solution possible atm is using git to pull a previous version, make that version another mod, try to play from there.

Any other ideas or close this?

**Comment by yairm210** [comment]
I think close it :/
There's no good immediate solution for this that I can think of
