### ISSUE TITLE
Aqueducts and Medical Labs not auto-queueing

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#962]
I'm not able to reopen #950 but since medical labs also need addressed now I decided to just make a new issue. Simply put the AI will never prioritize aqueducts or medical labs. (Hospitals will be queued if the player builds an aqueduct, however)

<details>
<summary> example </summary>
H4sIAAAAAAAAAN1cXW/bvJL+K8K5VoJYtmzZd0naNN1NWp8m73aBIhe0zNg8lUUvJaXxG+S/75CiSNqirHHRxWIXBVJFoobzzZmHVN5S9sIy9jcpGc+L2Y+3lJWM6ovdNdwrRZXWD98WFcvKK/ixZPkKxtzzvNrQvAwfWFGynAbXa7KlWXhHSQ4jgkf+i4qAPwdzVpDws+D5Ly5+FuHllmcZD+aCrwTZhHdstS7XvCpo+EiFICkvSxJcis0ufFzT4Cvcyai6/CQoKQNn/EPJYdrviuo1z3hR0GoTPuyWOd0FX7dUkOBWDbz8r4ouQRB4g5QVlUzdsQUV5S6cc5HSjLC85je85cWWlSQLPwmSE7ELL/PVTy6C76QMrwQny5QUpR47JxlJaXjDxYItlzQP9I17Blq5ZiKtiuCevLJNBfytWbqGIZ/Lv0n4kT0/00xTuQcLlDBTcJmSJQWxb9mG/osF1zARSH5PxE9a1rICgRUNb8mKkeCBb9eMhFdE6gwU4Mr7nWRZIaW8IotdxvPwC62KdP2LgEEpy8O/cvZCRQE2Dq8FWI8H3yjwX3IhFU1KQcNvtKBEpOvgjizC+6rWLCVbLkow2UJI1YA2lwzuX5H8J3AlFvD+LRUbEAfYvMzWZAMDwxuSAuXdng1rArckX0lX+UQETF+oEfMdeAVbgkCLgooXol6dV4uMpcFDuuY8C+fAKlmBWF9fn7lYBo44yhnWfBs+kn+B7tdgSHAlrpjl6c/g42u6JlKJ9yRdV+CaKfyn5r3j1QvI/bAFCxZrtg0atr9U4IBEBPOMgFmv2Cq4ormUfQHW+aJCh2QB+F9GgW7th2DwR7rZwoBaYGmQ8AsHxQYfyAZG1bb9d0E3GcufwrQSAoRyI272kDKap/Q9lLEoHRdi8D2kr1uwonz+llZZWQkKggm6nCWD+D0E42XlejaM4jDjqeJt9vY6G7yHOUw7a9xhy7dVpp8+c77UJAbJwH0UDcJiS1NGMnCRwsw3i8KiZm02fH8PS5apjPE6G4Y7ORNcjeBqqK7OIrg8q68jc3dgnw/s87H6Ka/NLUnyLKpHWvLq7sDQ1GPPnNtno8P7I+c6MlTsVf18bO6NzWxj/dSwbGU4c4SoL2PzWmx+H5krO11sSNtxDe+Kx9hMosUfKBa0GCM778By41xGdkBk746szgbWPDVl/Uakfhk4xrHvO7M2HET7poicu/La+dXO7ZrCmnloPMf6UGSuGrktpfGezmPneeRcW9asclzhatk1Sc1ifUv/p18zjJxZns4cb7Qe7irZUYerGWtyK7QrQOwwGNdsxIaodQzHR+L3p1CurnT5aMLxwAr7+vRrI3IVMDiUY3QYn+Zlx8Ui18WegK26pLiWaVCmGPj95YubiyChZTL7OIyPw30nsRGp746tnm2qmVgtTqx2Ergc78XtBdyZGFHcPOBmjYMpmki30x2mpvpyaojvx/bIsDg2bNXjzvZTRBNYzrXiOHEkj81UiR0wrQck3cHppkbrCdZ2ibGyzQ82ysYHWnDiYC9nOHM7HmRT6dARZGh0MTJcTI1wh2Ey2VfU0CrKuWxuT6weEhs1F8YAU3PVeEe4L7V1uqML0MD6l/L/sRng0HI8OHLMZMV31pGxjSVN196pPcbqJTJ6aTTgCO8qxQ509WPTZyOiJZp40kXNdW1t7Y+J5dZZHdxsbdWkrWHIu4naSbBuQrK5NDFXUyOLs8gZyfWti0NXcFKUk15tWh1cOMlUTWBVFlk6+nLqkB/vS2lXAusKiROPY+MK9drj2LtVTdjqyPGG0C1M3Cxt55s6ph8YI9uhExsNkauw2rRGh3qU9ZKBpVtf2mBtFOPox1Y7NudZOyeOhNY4eu3R6cC6iuOAjsROrmmVF86A2Nq3DvOx486Nu73b8spfQY2sYp1VXHnFwPqKw11sB8dGFZN373o+clh06DTEXU+1NcPYSGeXnMS+d/HeFK379bSztDq1ilOvO1n+zM2OI0PD1bFdHqaGs4nzlk1XiXX9xrdsbqk90OZXq7JGkfbu1A6dGgqxtY/z/Gx/gC0KEodFq9IzJ3VZcd1Owqn02uWdU4q65aWtq/ZqLodIQ8NYz1p07FjDFiSWOTfPW/U0nvru1PbediExg8dm2onRT2KNZavUeJ8rT+kaW9eZKPpP4Ypny1k0nEZTdUnzyxXUe295tVlQ8fX5k703gL5TNaS3ZLtlOS0KeC+E1jMv7uhzecPFdd0um3dmQ+B7JUvMOeXQdc/e9C+i4Pmcs9xtXwejeHo+TSaxZmmQROfDcRyFW8GXuveOxhfR+WgwHZlWdzAaJOeTOAFtbxVBYOMLfS0/2Ylm49EFqCrnJXtmqcHUSE3yLc0ISJLyzXmVQxF8nvEVS89dBO78Gjr9SzVcNf116/4ephwq5NkbAbMtZhfnF5NRfDGFXn0Fv0STizhJoN8X8EusHlyAMkpgbfYPiYYEa1IERUkElN8Bz4MfGld4+gcYZZuRHRWPuy2d3VYbIpGBjKUSAnwjS76FV+bNjR8P/IUKylZ5uQtvBKXBw5bSdB0+CrJkimd193HNq9W6DOeCl1TJwopNeM03GyokWAZjlnwTwA0wVEnt6/ZWg83pseGclILnElNSTEp6Sgil5+AbfeFZpRi4lsoMHjg8hNclZSrBIbBD+EDB/kTUvORFyUr9isRtgM0XGnyrJNwGXBKgnKmRwNjfNJdwkJHAsvlNYz8w0rlJt4IWEqBS5J0x4R1d1ReXCnNLBUl34deMrSTOtgvvSL4EE33MGJD5mJdCUsppJdT090BFDftAN/pVDXsRkLh6fhagn6ewCafLA+tFYx1T100UTIfgq9q7/4MpqEviS2Cz9exN/iw+5wqjlfH39oXk0pzrHFxxBTlnNBrUY4sGKITm7sdNJsHZ8KPUKFiMpRKWLOV/DyUlm2CuAM/LlFeFugtaW8hLUNQ9X0ADGDzKaIEn3/iCq4t7JsHk8IGAReD/jxChtWbvSAHCgy5harEL65QAWrkimcSr5LufqnzLfy1hyhvwJxlmEm6lpYTriMSsgV7Kc76pebHYm6LKpPuCqsLLUo4Ax6YSDpRgp3xTWhwCWhpcgr4SDQzmEGVFeMtFQRck/Rl8Y0s9dAF5bClRbYkE0w0wCKQ+50uQXkiArU4AEmHO/64hbSW19XI9+3zNMl7wLTiCnIylctb1rtDa3FalVIqBlHWsQzBCypJI61yaM7wnJTBBtJJYtizCK6YsC4pPf1LJnARIgWm4+ihBWkqF5EgqhtB66IddTjbKWZW9mUxZ4PBLIsI5L0v56uUKbtcep3YAjGTf2LOypxRLEftCXiAQdMywTCLtBnm9YUWhYpVkNJfkYRLGpe3Uq/cEkq9CeCnNwkYbEP1y9VhJ5P2FZBp//r6WY74Lpqx/mbMNOMNtVSwg+KQX1QmEihcmcXzpKlklpFros2ArKmoO5xmpPeyykH7ON9IwRGzADyCrpCQrnurgeORNeMx+7IcQeHRJMxnrRXhTSQUFj/Dw6T18qYPxnsiMB2kfFoA3C5qIBSQxAgmtZxGNW2voNI76F8n3d2cJ6MkPbuQ7hvaIXgexVzaDfc/VUmRgoSV7flYUd7MHWpYZRO4KNABODz+lk8/ePEM2ZCt9oypkaQm/qJXtA30mMAoWZqu+GYQ6NdnyYw4hCRJfNAzK92DJ+wLmFCRz4vCpBrzvyRaUABd3EMmwxi8gGandK5bPrjk4B2ixYA383vSyYMhjA1X1BfHJK1hmZnPQXVYcvPIVEk2+T7tuKnpIW0zgYOAHsJE4GKnbov6p6zL7on9yXRoejJvLbbdib2DsZbJDoy2pPQR1t1vWI27A3+Xi929Vvspov4C6J0FI2KCKxnyQs9YHb30SsF5kkGhCtoFa84XK3dPZHEjJ9Lg3cdMZGHLXRDr4AcFblmV77419WumUC+E1ui3tm3fkm1eNciWFLED33B0k7OHVq32PmRsoxOjrM2StvECYeOoNTc/ApG5p+j3BO84jWIKYVAVta2CH+7W02R6XHPoVNstEXkY8A1WoT/sHDr0e6CEYI13VQOPHZWu/WCPVSFu0JOtwgFay8zA8RU48RRKsscsTo9CA2f38jnz073kFvQ7LW+HYoqjD1uXlTq2/wWY/n9R4y0HKhnabFiUqo95AJdZeLTCaHnpjt1+FGvYxnneZVRsGxUVf3qyx2oNRjxWUomRv3MQ3riv4WlHamlYDuMiQGjmCfV9DCX4YUr4aQm8q4KZopV/8ShkdcohbKDWW38veBLf+yW2QPuOjfBXF1Bk6w9T7SShGWj5tNsSMYH8JkrOWXF1VHEKQyMeex/0TXImr90lPjt4RzheGPk9tD5se5AJPIdi1vvpLqBohJPlfOSsliqm6pftGmpFsc+Sjy6MwIww6r4HI84dSdvIaZtTg5ENG6VYfElKg4RUnZRHyX7nTkoEKN1wfBvzP+WwkPXCjkQY/c9EfYQ5SP/ReuyBqGCRCMC6OcKe6WMcxwBycLNXhv2LWwAsIP0ZYuzc3jH1O7q/MWk7YIqa3wP/k2jjytlwebehTDv1ZJ/IFiiZ43Jn/jL+QquQbBdQ4Hk17/MVRkoN7etT1Xu9EPPLPjlojRC5udliPZQbve7jKD9E1R7hh+tBHf/nW0s7Q60tdtTSy/8RwPDypi2vFtY2VVrOEKJMmOCanvmFdS0Err/jDWW2e5KsACHiKdeltGOTDF+xel+pqz1qLrl+hzf4pJn11RhCGqTGyV28OfpiQ/MoyXJnhbxL2fdytSjk5JOyDZXz1S0eC7UUYtA+0xv0/ScTjE/LwXs6CpCsjpi5wDpPX+Hh6btWSbgN72qK8l2j6+hdfhzX2ZqeOanyMCzpEvflnPMOtNxvsHusVs+Y7if+N2vOK/5Lb5EcL49jsK8ztg4E76of6amNFg89Pe6UqEnevE2ErU3TA3/14gD6OZXzwYa2sg/DcsbfT8wICbQ/MOF8GW8U0arG7JputZ/EZujFbieI3l5fIWxn4kYNeI+GwzQESUWzOMyGRAcTCpw+l9Y+Lu8fhs2pPO4zsVLygFaYqjb3aa+Xyf1YQlLs9I7roxz0Ri1Zi7qgOMGlZH2XsQVe8sepvOvuBVXMoHRMhXbss6PK+3bh0pjIkqj5FrM6tAggRNhFqy8YcaG7J5cXAh97UeApijfDZNpiP0ySmVZqeUEQj5Wyx2xzyPlYotxwRhadM+/2la5McgXGMUBv6r+ZzjN/0ggi5HR57YepT9pv7KlC/gjEaGGL3/hN8ndqxRZKcioz9X2+CmtPpnk5oiMxm6C1YzP5T5APqPab2nt5oH4dpu027zkKtMlOspAlW0qG3AvcuBLFP2M6Org3ZHKmTvRuKrbk6oqV9LMYbLV2Og1kvB0iYry6aLk5O17E3u3oWDGyq7j0a4V9OkXtdLS7aFcvYR80TQcPDhVOersQpbHSymr07Xx6vmvq874TqHru5cAzAPb6g+gHqU/qZ0e9o0LtzgmldRsh6BLmdPe3cZOqrEMYHYqszzv3BkRzf3W9ZFuP6zReGhpcrksO/Vt+Phrr116ynlQ6ITTU8lNOVwlBQf/ONIEb8/gYiQkINibfk9KReZLvZsSj85nmm3+iczJeIxq/kaWrcGte/C9x8tnlqAOmP3pB5EXk8AYcI4o56+bePfeXNBBsTQ28R5olcLxTX1YQh2yjMuZqh1/dbSkx8SuyqkjDbvJHP1drDxr5hp7Sc+MTV1dcdnWPQg4wcmhjlNIm3IO/CpnoBhPrzxePn3rqA2t5TzVoFmHO9uB1BhDPGOEpjbxrpclqMvodoLHCM7NL8Z6W62gNMBCY4HpFovfc8QIcPYJuj4dFNam/+Rm0YTL2p0ZPpPSJ51wP99zhwJZ/3eEeXZ6A+BKj/rMdvA2HjA1V7sTA8uRhDzr++YE69+HFrf62GoOf/QshXMSMPEvmPU2OWiAiZR/2fJfj8vLcgbHaV98jjEibKM/XfdjG+8IFS8ccPufdXOZ5VoAvxw5Qkzd/ZQcR7DVhgJPYmlsRX1XRhfQgZ/SDWSch8f5fRtQ+HVERHiYreeOg5bdi1WmPWVv8nfWhf7dVca7N/8j8dP63Q8R7l7Tsn0bV6IVrEBFl6J0dshAOxBgfNKBrEQn11MEGVXZ5o9hcU/o3UjjoJnSEwn90k+D0lf7P2G+gFcst6emBBJFht/orMSfvok1MaWYQFBtg188yL5XRhggjf1H8j6FS1+c/fdIU6ph5p/toRcilGbLYoipjObegrkf3fiEWnJzvvibMOR+zfuXlF7iccPSkadu2Rjk6Ozhip48hfPx3BOPZ24HlZYnZz/OdxvJuCmMOC3uPC3pzsP53SiRK1iHp3P/fgFsi1uBzY0nHn14iD47tlHacnu5H1J+1Ts3g0fv9vgWR890pdAAA=
</details>

**Comment by yairm210** [comment]
Resolved by @ninjatao
