### ISSUE TITLE
observation for open borders trade

### ISSUE THREAD

**Issue by B5656** [yairm210/UnCiv#963]
In the original game, when the open border trade stop, all of your units in the other player territory are pushed to the borders, even if it's because you declare war (but, in this case, that isn't very realistic).
Currently, in Unciv, units in the other player territory are pushed to the borders, but not in the case of war (you win the possibility to be on this land before you lost it, so your units don't get pushed away).
So, it's up to you if you want Unciv to be realistic or the more similar to Civ5

**Comment by yairm210** [comment]
Gosh, this is a tough decision...
In general open borders are widely considered 'a noob mistake' due to the fact that they hardly give you anything, and this makes it even worse...
I guess I could greatly raise the cost, and have an option to make a 'remove your units or declare war' ultimatum

**Comment by Smashfanful** [comment]
That sounds a great idea. Still, I think you should make that, once a war has been declared, all units in a Civ's territories are pushes back to their borders.

**Comment by odrevet** [comment]
I declared war with a civ with open border agreement  and my military units were not pushed back. the [commit](https://github.com/yairm210/Unciv/commit/23f575d150efef78a1a425d8c79ceb8373dea107) mentioned in this issue do not seems to work...
This sure is a cheap way to win that I understand why there is this push back rule in civ5 (I did not known about this rule before and i google specifically after using it twice for a near instant win)
I am  using  version 4.11.19 on android

**Comment by yairm210** [comment]
Can you send an autosave of the turn *before* you declared war?

**Comment by odrevet** [comment]
[Mongolia.json](https://github.com/user-attachments/files/15917211/Mongolia.json)
Here is the save file with Mongolian units in Siam territory.

**Comment by yairm210** [comment]
Sorry for the late trigger, but could you open a new ticket to keep track of that? Sounds like an entirely separate issue 😓

**Comment by odrevet** [comment]
No problem, I have opened this issue https://github.com/yairm210/Unciv/issues/11803
