### ISSUE TITLE
RFC: UncivGame.isInitialized vs isCurrentInitialized

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9641]
Any coders please help out with a little brainstorm if you got the time:

I just came across Civilization.L77 - `fun getWorkerAutomation` - `if (UncivGame.Current.isInitialized && UncivGame.Current.gameInfo != null)` - and that's my code. I'm positive that `isInitialized` check is a bad mistake and should be `UncivGame.isCurrentInitialized()` instead. The field has a specific and different role during launch, and should be at least `protected` (all other uses are private or in platform launcher code - `AndroidGame` would need to proxy access for `AndroidLauncher.onPause`), normal game logic should have no access.

Am I right or off the rocker?

**Comment by yairm210** [comment]
Looking at the usages, I'm not sure why that check exists in the first place...?
getWorkerAutomation() is a function of civInfo, and there can't be a civInfo if there is no game loaded, something here is definitely fishy
What this really needs it to use the gameInfo of the Civ, and not the static

**Comment by yairm210** [comment]
I mean going to the *current game* to get the *turn* if you already have the game info in yourself is just nonsensical
I assume that this used to make sense because it was a standalone thing, but then a partial refactor happened which put it in CivInfo but didn't get rid of the vestigial static uses

**Comment by yairm210** [comment]
While I was at it I removed all the wrapper functions which were both static (bad) and did nothing except pipe forward with no logic (useless)
