### ISSUE TITLE
Foreign aircraft in own city

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9643]
**Platform**
Android

**Version**
4.7.2 (Build 881)

**Describe the bug**
Hello,

if I have open borders to someone and then I buy a city from the civ and the civ has planes in it, they stay there. I find this very annoying because then I can not put my own planes in. Is that how it's supposed to be? I would say no, because I can't put my planes in a foreign city either. I always wait until the open borders are over, so that the planes are gone from the other civ.

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Airplanes are no longer in my city

**Screenshots**
![game](https://github.com/yairm210/Unciv/assets/46723399/8013bf0b-77f3-4e6f-abb3-cd0d6f543dc7)

Game data: 
[game.json.txt](https://github.com/yairm210/Unciv/files/11846481/game.json.txt)

**Comment by yairm210** [comment]
I think this is more a problem with the teleportation code than it is with the 'can pass through' code. That function does exactly what it's supposed to, it's not its fault that someone else wrongly relies on it to determine if a unit can *enter* the tile

**Comment by yairm210** [comment]
YES
Solved by https://github.com/yairm210/Unciv/commit/06691d429e2cc1e5b6db378f0964501a50ff57d7
