### ISSUE TITLE
Roads that are not owned cost maintenance

### ISSUE THREAD

**Issue by hippie68** [yairm210/Unciv#9661]
Since some versions, neutral tile roads suddenly have maintenance costs. The bug is that the game doesn't properly calculate if road tiles are actually owned by a player. If you invade a city to raze it, after the razing is done the remaining neutral tile roads still require maintenance. I don't think they should. It is a major inconvenience to manually get rid of those random road tiles.

**Comment by Caballero-Arepa** [comment]
Intended feature, as per Civ V Gods % Kings

**Comment by hippie68** [comment]
I think these rules apply for Civ 5:

- If a road tile is built inside own territory or it is acquired: maintenance
- If a road tile is built in neutral territory: maintenance for the player who built it, plus the game internally keeps track of that player forever
- If a road tile changes back to neutral: maintenance for the player (the original builder) that the game keeps track of

If the last rule was changed intentionally, then it's probably not a bug.

**Comment by Caballero-Arepa** [comment]
Ah sorry, you are right

**Comment by hippie68** [comment]
If I understand correctly, on becoming a neutral tile again, ownership should reset to the player who originally built the road, not the previous owner.

**Comment by hippie68** [comment]
I'm finding conflicting answers. It seems at some point a patch changed the behavior. One answer (more recent) even claims upon razing there's no owner anymore.

- razer pays after razing (pre-patch)/original owner pays after razing (after patch): https://forums.civfanatics.com/threads/road-ownership-what-determines-it.433271/
- no owner after razing: https://gaming.stackexchange.com/questions/131975/do-other-civilizations-pay-for-roads-you-build-in-their-territory

**Comment by hippie68** [comment]
So the bug is that after razing a city remaining road tiles have an owner who must pay maintenance.

**Comment by yairm210** [comment]
Not a bug, working as intended - you build it you maintain it

**Comment by hippie68** [comment]
Except I didn't build it, as I said multiple times. I think I have said all there is to say by now.

**Comment by yairm210** [comment]
I do agree that it doesn't *make sense* to consider  those roads as yours if you conquer a city and raze it immediately, but it also doesn't make sense for the conquered civ to pay maintenance - razed city roads should have their owner removed entirely

This is definitely a good feature request, I'm willing to keep the 'bug' label despite the technical issue with that categorization ;

**Comment by itanasi** [comment]
Hm, dunno why email didn't prompt me until now. Sorry it's been a few days.

Anyways, I don't recall the cpp code. But this was very much intended behavior at the time.

If we had to change things, I would also vote for converting to No Owner on City Raze. Flushing the roadOwner on City Razing would be appropriate. Everything else should work just fine since it also has been previously removed from the previous owner's neutralRoads set. And due to rollout it doesn't break things to have no owner for the road for maintenance.
