### ISSUE TITLE
Feature request: Additional unciv-mod-* topics

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9681]
I think this would be useful to help reduce the saturation of ever populating mods - some mods are not meant for production use, some are filling space while they're being worked on.

I'm opening this request to get feedback about adding topics that can be filtered in the mods menu, adding a checkbox "[ ] Developer mods" that then show mods tagged with the following topics. You'd see only tagged dev mods in [category] when checked and no dev mods when unchecked.

Developer mod topics proposed:
[ModCategories.json](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/ModCategories.json)

```
{
	"label": "Experimental",
	"topic": "unciv-mod-experimental",
	"description": "Mods meant for trying experimental work or some form of development not generally intended for the usual unciv gamer.",
},
{
	"label": "Work In Progress",
	"topic": "unciv-mod-wip",
	"description": "Mods in active development, pre-release, or otherwise in some form of continued development. Alpha/Beta/Pre-Release/Delta candidates.",
},
{
	"label": "Combination of existing mods",
	"topic": "unciv-mod-combo",
	"description": "For when a mod is basically a conglomeration of other mods. Usually individual pref of personally desired mods to have.",
},

```

A discussion issue might be putting responsibility on the modder to utilize such tags. That responsibility is already on them for mod inclusion. Repo's seen with creation dates < 3 months could be warning'd against or automatically included as a development mod unless adding a mod-release tag to override. This could lead to all production mods using a release tag to being seen in a "published" state to filter out stale mods in a growing modbase.

edit: Consolidated tags

**Comment by hackedpassword** [comment]
I'm guessing you run mods in a local dev env? You're not wrong, I just don't see how accessible that is to non dev user-modders. Prob cause I have no idea how you'd do that. Could be worth a doc write up. Doesn't address the {current} bigger issue of 1982-esque mod buildup though.

**Comment by hackedpassword** [comment]
What's your experience with cloud databases? Is Unciv in a place where this could even be considered?

Maybe community asset growth issues could be part of a 6.0 roadmap. I imagine to handle such a task beyond tagging of current would need serious contemplation.

**Comment by hackedpassword** [comment]
Adding unciv-mod-combo to the initial list. Removed sandbox and prototype, replaced with experimental. This structure appears more coherent and understandable.

**Comment by yairm210** [comment]
Combo is same as mod-of-mods currently

**Comment by hackedpassword** [comment]
Number of mods continue to increase. Just making the tag request to github is time consuming. A revamp to how mods are displayed in the Mods screen will be needed sooner or later.
#3242
