### ISSUE TITLE
Coders please help thinking: Fogbusting

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9698]
UnitAutomation.tryFogBust(): 
```
        // If everything around this unit is visible, we can stop.
        // Calculations below are quite expensive especially in the late game.
        if (unit.currentTile.getTilesInDistance(5).any { !it.isVisible(unit.civ) }) {
            return false
        }
```

... I'm 99% sure code contradicts comment and intention here. Should be `.none{!isVisible}` or even better `.all{isVisible}` - right?
Any thoughts as to why this is not noticeable in game? Or is it?

**Comment by random271** [comment]
> "Fog busting" is a strategy where you put your units slightly outside your borders to discourage barbarians from spawning

Code seems correct, assuming this only works if you can actually see all the tiles around you? If you can't see at least one, barbarians can spawn there and the FogBust doesn't work, hence it returns false.

+1 on the comment should be 'If at least one tile is not visible, we can stop' instead of logic being faulty

**Comment by yairm210** [comment]
No, this is not logical. The comment says "this unit should not try and fog bust if all tiles in 5-tile range are already visible to civ", and what the code *actually* does is say "If there is *any* tile that is not visible to the civ, stop automating".

This is probably a mistake. Looks like what he meant was:
```kotlin
        if (!unit.currentTile.getTilesInDistance(5).any { !it.isVisible(unit.civ) }) {
            return false
        }
```
(with a ! before the current code)

Which converts to:
```kotlin
if (unit.currentTile.getTilesInDistance(5).all { it.isVisible(unit.civ) }) {
            return false
        }
```

I suggest using the 'all is visible' format for clarity
