### ISSUE TITLE
Reduce app update frequency

### ISSUE THREAD

**Issue by SnoutBug** [yairm210/Unciv#9708]
I was recently talking to a friend of mine who also plays this game. We are both on F-Droid and we noticed that the app needs to be updated quite frequently.
For me personally this procedure has become somewhat bothersome, and, with this update frequency, I find myself rather confused to the point that I am not sure whether the app update fails, or whether the app just has to be updated this often.

I really like the dedication behind this project, but I would not mind if there were less but bigger updates rather than small and frequent updates.

**Comment by yairm210** [comment]
Sorry, this runs directly counter to our development principles of "release early release often"
The game could never have gotten to where it is today without this

If it bothers you (and I do understand the concern), you could just buy decide to not update the app and stay on an older version - some people play for a long time in older versions, or only update between games
