### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by zhavier042** [yairm210/Unciv#9710]
**Is your feature request related to a problem? Please describe.**
I am frustrated at how clunky it is to get workers to build roads.

**Describe the solution you'd like**
I would like to lay out the tiles where I want roads to be built, and then certain automated workers go build them.  

**Describe alternatives you've considered**
Alternately, add an automated roads function to workers that attempts to connect cities to your capital along shortest paths, starting with the nearest city to the capital and checking each new city for the nearest road tile that is part of the capital network.  This would be a separate function from standard improvement automation.

**Additional context**

**Comment by yairm210** [comment]
Closing as duplicate
