### ISSUE TITLE
Allow modders to classify buildings into special categories

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9712]
**BEFORE creating (delete this in the actual issue)**

Is your feature a gameplay feature from Civ VI, or from BNW? If so, don't open it in the first place - see Roadmap
No.

Is your feature a gameplay feature from Vanilla Civ V or from G&K? If so, it should go in https://github.com/yairm210/Unciv/issues/4697 - post a comment there!
No.

Is your feature related to a crash or things that are already implemented but implemented wrong? Please open a Bug Report issue instead!
No.

Is your feature a UI issue, Quality-of-life, user experience or development issue? If so congrats, you're in the right place!
Yes.

**Is your feature request related to a problem? Please describe.**
No. It is just  a suggestion about City Construction Panel. 

**Describe the solution you'd like**
I expect the mod port of Unciv to be able to do this: add a new attribute to buildings for differentiation in the City Construction Panel, just like Wonders and non-Wonders are differentiated in the City Construction Panel.

**Describe alternatives you've considered**
See above.

**Additional context**
None.

**Comment by RealBamboolord** [comment]
Your request is already possible, and your issue text is 100% the default text which literally tells you to delete it before publishing the issue. You should put a little more effort into actually writing an issue if you want to be taken seriously.

**Comment by AutumnPizazz** [comment]
I'm sorry that I forgot to delete these words. Thank you for taking my advice.

> Your request is already possible, and your issue text is 100% the default text which literally tells you to delete it before publishing the issue. You should put a little more effort into actually writing an issue if you want to be taken seriously.

**Comment by yairm210** [comment]
This is a modding request, therefore should be a comment in #3242
