### ISSUE TITLE
new update is heavily flawed

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#973]
since the new update (the engine speed one) technology and production are way too fast.
for example I build worker in my capital and have 5 turns for it to finish. I bought worker in another city and suddenly my capital has one turn only to finish the worker.
techs that should take 20 turns are finished in 3 turns.
and the ruins give double reward, for example a settler and also 100 gp.

**Comment by yairm210** [comment]
2 separate problems, both fixed in 2.18.6-patch2
Thanks!

(Another copy of #971)
