### ISSUE TITLE
How to achieve a diplomatic victory？

### ISSUE THREAD

**Issue by neigl6** [yairm210/Unciv#9735]
Although I built the United Nations, I didn't know how to trigger a diplomatic vote.
Is this because this feature was not developed or is a specific condition triggered?

**Comment by Alvin201777** [comment]
Wait until 10 turns after globalization researched..

**Comment by yairm210** [comment]
A question for the discuss, not Github

**Comment by tex** [comment]
Problem here is that you cannot vote for yourself!
