### ISSUE TITLE
Gold not being totalled correctly

### ISSUE THREAD

**Issue by HeavyMetalFFT** [yairm210/UnCiv#974]
As of last update (28 July 2019), gold totals are showing up wrong both in the Cities tab, as well as the overall Stats tab.  See screenshots.  It appears that only the gold from the capital is being counted toward the civilization's total.
![Screenshot_2019-07-28-12-50-44](https://user-images.githubusercontent.com/49464528/62010750-b5eef000-b13c-11e9-8309-a87e8e161ab0.png)
![Screenshot_2019-07-28-12-50-31](https://user-images.githubusercontent.com/49464528/62010754-b7b8b380-b13c-11e9-8ad4-dd95b06950d7.png)

**Comment by yairm210** [comment]
Correct, thanks!
