### ISSUE TITLE
Cannot bombard tile directly above city

### ISSUE THREAD

**Issue by AldieNightStar** [yairm210/Unciv#9760]
**Platform**
Windows 11

**Version**
4.7.7

**Describe the bug**
When i choose the city and there are some warrior, then button appears above which is ok. But enemy which is standing under the city. 1 Cell up. I can't damage. Because of huge warrior button are so big so i unable to damage him and always pusing it. Why this isn't fixed?

**To Reproduce**
1. Enemy 1 cell up the city
2. Make some warrior stay in city
3. Try to make city shoot to the enemy. You will see that you will not be able to choose enemy to shoot because there would be a button to chose warrior that stays in the city

</details>

**Expected behavior**
Make button smaller on PC's so player would be abble to access all the cells

**Screenshots**
![Screenshot](https://i.imgur.com/UZ5rP7d.png)

**Additional context**
Make some additional setting for pc to make this button smaller than on Mobile. Unable to play and it's annoying

**Comment by yairm210** [comment]
You can click the tile directly above the city after deselecting the current unit, to bombard that unit
But we need to find a better solution so leaving open - so far we've had several attempts which all failed

**Comment by WeiTuFat** [comment]
Would a button to hide city names help?
