### ISSUE TITLE
RFC: Recent "Fixed India's 'double unhappiness' unique" should have been caught by a unit test

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9761]
Ref: [Fixed India's 'double unhappiness' unique](https://github.com/yairm210/Unciv/commit/19bf15558d039edbd82c0470e32c218c376fe728)

* There's only a few untyped uniques left. Two are easy. I intend to fix them - but that raises the question of UniqueMap being keyed on strings... The commented move to UniqueType key - we can't, right, or mods using untyped uniques as keys to be matched in other uniques filters would break??? Or not - a filter remains a string and won't use that map anyway. So, let's think about that map's key move soon.
* "Who knows what the future holds?" - I would tend to simply move that to civilopediaText, right?
* "Units ending their turn on [Mountain] tiles take [50] damage" - Carthage - yes that does _nothing_. And it'd _better_ do nothing or Carthage's units would receive 100 damage on mountains...  I would tend to simply move that to civilopediaText too - but as is (already translated), or better in some form like "remember, all units, however they manage to enter them, take damage on mountains"? Or - revive uniqueText?
* "Aircraft" on UnitTypes - used as filter for carrier uniques. Hmmm... I'd type this one in the enum and comment it's only used as filter, and has no actual implementation. Right?

Once these are done we could step up BasicTests.baseRulesetHasNoBugs with `modCheckerAllowUntypedUniques = false` - except it's broken by tryFixUnknownUniques = false. With that fixed, and raising the error's level to WarningOptionsOnly from OK, the unit test **would have caught that India bug**. Tested.

But - there are also a whole bunch of specific tests (allUnitsUniquesHaveTheirUniqueTypes, allTerrainRelatedUniquesHaveTheirUniqueTypes,... ) - more than half of all RulesetObject types are covered, but not Nation. Ditch them all as a fixed RulesetValidator will catch them all as well?

**Comment by yairm210** [comment]
The unit test required is "no uniques are misspellings", that would have caught this, it's how I noticed (mod validation warned me of this)
