### ISSUE TITLE
rome production bonus no longer working

### ISSUE THREAD

**Issue by amirberner** [yairm210/UnCiv#977]
roman bonus production towards building already created in the capital no longer working

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/62426717-ffb57880-b6f0-11e9-9e81-10c264ae6f10.png)

Still works...?
Do you have a couterexample?

**Comment by amirberner** [comment]
hi,
I guess it's because of the way you do the rounding up/down
when the basic production is 1 it still takes 40 turns to build the
monument (pic1) so no bonus gained.
so it's not a problem.
thanks



בתאריך יום א׳, 4 באוג׳ 2019, 19:50, מאת Yair Morgenstern ‏<
notifications@github.com>:

**Comment by yairm210** [comment]
Cool, closing this
מגניב שעוד מישהו מישראל לוקח בזה חלק אקטיבי :)

**Comment by amirberner** [comment]
פעם הבאה אני אפתח את הבאג בעברית :)
באמת משחק מצוין, וקצב עדכונים מרשים

**Comment by yairm210** [comment]
עדיין מעדיף שתפתח באנגלית, בשביל השיתוף וזה

**Comment by amirberner** [comment]
התכוונתי בתשובות לפניות שלך, ברור שלא בפתיחת הבאג עצמו

בתאריך יום ד׳, 7 באוג׳ 2019, 13:00, מאת Yair Morgenstern ‏<
notifications@github.com>:
