### ISSUE TITLE
the Pantheon of Craftsmen does not work

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9773]
There is a bug that has been going on for a long time, which means that the Pantheon of Craftsmen does not work. Further, the entry "<in cities with at least [amount] [populationFilter]>" is not valid. Screenshot below.
![H5AW FJ8K 82I_UV60TP(`G](https://github.com/yairm210/Unciv/assets/114050365/619f766d-1b6a-4db0-bdcc-478cb08eb487)
![M09``AE8PE08WV203S{YG)E_tmb](https://github.com/yairm210/Unciv/assets/114050365/c8b6f49c-50a1-4e73-aac3-05fe21d6756b)

**Comment by yairm210** [comment]
The reason we removed the old 'applies to cities' is to turn it into a global, for global objects
If it would apply to the city as well we'd have a problem

**Comment by yairm210** [comment]
It will though! Since this is an effect from a Pantheon, and those only activate in cities following the pantheon, that's the whole point :D
