### ISSUE TITLE
The 4.7.8 has  a unbearable BUG for mod!

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9791]
Like this.
![屏幕截图 2023-07-11 171504](https://github.com/yairm210/Unciv/assets/114050365/375ddc01-2b45-4feb-8b43-fc1cedca9a13)

**Comment by AutumnPizazz** [comment]
Well, I have solved it by adding a border folder. This operation would be carried by every mod that ever fixed the Tilesets.

**Comment by yairm210** [comment]
I'll fix this in game as well
