### ISSUE TITLE
Happiness improvement buildings take minutes when bying

### ISSUE THREAD

**Issue by jujunantes** [yairm210/Unciv#9799]
**Platform**
Android 13, 64bits.

**Version**
4.7.7, build 889.

**Describe the bug**
When buying an happiness improvement building (tribunal, coliseum, theater, etc.) It now takes minutes of waiting before the game updates (the UI is not frozen it looks crashed but it isn't  Eventually, the building is bought and the player can go on. It's like it takes ages to compute the happiness scores.
Note that I have a huge map (75 SQ radius and hundred of cities).
All the user buildings are built nearly instantly.

**Expected behavior**
These buildings should be built as fast as any other building.

**Comment by yairm210** [comment]
Please attach a save file for example

**Comment by yairm210** [comment]
'hundereds of cities' if that's literally true, then it's possible this has no solution, since each of your cities now needs to update based on the new civ-wide happiness

**Comment by yairm210** [comment]
Unciv was never meant for that kind of scale

**Comment by jujunantes** [comment]
> Please attach a save file for example

Here's my [latest auto save.](https://ufile.io/073p4f3v) .
For instance, try to buy a colloseum for New Avignon (the latest founded city). It takes about 3mn on my Redmi Note 10S.

There is a little bit less than 150 cities on the map.

**Comment by SeventhM** [comment]
I'm getting an warning from my browser trying to download that save. Can you upload that somewhere else, such as just attaching it to a message here?

**Comment by SeventhM** [comment]
To be fair "warning" does downplay a big red screen not allowing me to even download it. But I'd assume things have to be really bad is the _browser_ is warning

**Comment by jujunantes** [comment]
@all
Sorry, I first uploaded my savegame from my mobile phone's browser, where the drag'n drop isn't available in Github's interface.
Here it is again, attached.
[Autosave.zip](https://github.com/yairm210/Unciv/files/12064997/Autosave.zip)
My Redmi Note 10S has a MediaTek Helio G95 CPU, which [according to this website](https://gadgetversus.com/processor/mediatek-mt6785-helio-g95-vs-rockchip-op1/), can deliver nearly 200 GFLOPS. So, 3 minutes of computing represent about 36 000 GFLOPS. This seems like an awful lot of computing... :)

**Comment by SeventhM** [comment]
> Redmi Note 10S

No offense, but this seems like a lowish tier phone from 2 years ago trying to calculate a game with 142 cities. Idk how you even managed to finish the game. My phone crashes when reloading the game or when switching off the app

If we wanted to fix this, it looks like this is memory bounded, not cpu bounded, so I do imagine maybe it could be investigated. But games of this size is well beyond what's expected

**Comment by yairm210** [comment]
Solved!!! I knew we had an issue for this somewhere
