### ISSUE TITLE
4.7.9 is not friendly for mods that use any entry about [mapUnitFilter]

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9815]
Like this
![屏幕截图 2023-07-19 202055](https://github.com/yairm210/Unciv/assets/114050365/8c6e15b0-52c2-48e8-aa47-3220ca9bbfd7)
Well, the same mod was supported (or not alarmed) in 4.7.8-patch1. Just like this.
![屏幕截图 2023-07-19 202355](https://github.com/yairm210/Unciv/assets/114050365/0086ac02-daa9-4971-8e93-ee7bfb73d42c)
I understand that there was a change in the 4.7.9 update log regarding unit identification, and I think this error is probably related to this.

**Comment by Jiangeshi** [comment]
![Screenshot_20230719_203433.jpg](https://github.com/yairm210/Unciv/assets/121507555/a250a09f-e732-4151-b69b-0e7db81ffe4f)

Very interesting, maybe it's because of your mod

**Comment by AutumnPizazz** [comment]
In fact, some actual valid entries in Beliefs still report errors (yellow characters) in the new version, such as "Free [Settler] appears". Well, I have solved it by tranfering them into GlobalUnique. Now my mod could be operated well in 4.7.9-patch1.
![屏幕截图 2023-07-21 155846](https://github.com/yairm210/Unciv/assets/114050365/be93895d-df79-49c0-b945-f3f071314426)

**Comment by AutumnPizazz** [comment]
> No, don't avoid the warnings, there's valid reason to sift through this and fix those definitions that are wrong, so the warnings that are right are more useful. If you had definitions where you tested and knew they worked but then got that warning anyway, that info would be most valuable!
> 
> I'm starting (slowly) at the top: IgnoresTerrainCost works on BaseUnit UnitType and Promotions as far as I can see, and the target declaration seems to cover that correctly through its inheritance rules. Where did your mod have that so it produced a warning? Did it actually work as designed in-game? If not, I believe the scope could easily be extended with little risk. If yes, I want to dig until I see where the implementation path is. I haven't got a copy of the mod on this dev box, and the current repo is already changed as you said. Could I perhaps have a copy of the previous mod version please?

Sorry, I probably didn't keep the previous version of my mod, and it's 1:30 am (Beijing time). I can only search for it tomorrow, that is, 10 hours later or even longer, to see if I can find an earlier version. QAQ

**Comment by AutumnPizazz** [comment]
Fortunately, I still remember some terms that I can use but will report errors. For example, as I mentioned last time, "Free [Settler] appears", and an entry like this is to get a certain amount of faith every time you consume a great man. (I am sorry, because it is quite late, I am delirious and have to use machine translation software to translate Chinese into English, so the description may be a little strange, please forgive me.) The two examples I submitted above, are in the beliefs.json file before, and have now been moved to globaluniques.json. You can judge by searching the entries I added to the globalunique.json file in the last few days. 
By the way, the beliefs entry in the original Gods and Kings. If I copy the Just War and its antonym into my mod, it will inevitably report the wrong yellow characters in my module.

**Comment by AutumnPizazz** [comment]
[the Coexistence in harmony - 测试版.zip](https://github.com/yairm210/Unciv/files/12135607/the.Coexistence.in.harmony.-.zip)
Yeah, I just find a earlier version of my mod which was done on July 15th, its reported error would be useful. @SomeTroglodyte

**Comment by AutumnPizazz** [comment]
I should add that "Hidden when [Pattern_Viceroy] Victory is disabled" will show an error (yellow) in TileResources.json but it actually works. @SomeTroglodyte

**Comment by AutumnPizazz** [comment]
Strictly speaking, this will force a resource to be hidden on the Tech Tree and Civilization Encyclopedia, but if the resource is a strategic resource and allowed to be displayed on the home screen, then the resource will remain permanently displayed on the home screen even if the corresponding victory mode is turned off. This one doesn't make sense. @SomeTroglodyte

**Comment by AutumnPizazz** [comment]
> Edit: RulesetValidator accepts no startingSettlerUnit in ruleset when the ruleset has a unit with UniqueType.FoundCity, but Era.getStartingUnits doesn't, which will throw up in GameStarter.adjustStartingUnitsForCityStatesAndOneCityChallenge - we should fix that, in the mean time setting `startingSettlerUnit` appropriately would avoid that problem. And no Worker is fine because startingWorkerCount is zero.

Thank you for reminding me. I've been ignoring this for a looong time. QAQ
