### ISSUE TITLE
Feature request: global resources 

### ISSUE THREAD

**Issue by Jiangeshi** [yairm210/Unciv#9817]
Allows designating resources as global resources

This means that through global resources, we can create closer connections between different nations, similar to the greenhouse gases in Civ 6

global resources should be like:

-Displayed in civ top bar and world screen
-Cannot be traded
-Can be provided by any nation or City-states (as long as conditions are met)
-Support as Conditional(such as <when below [amount] [global resource]>)
-ARE considered for constructing buildings requiring resource
-ARE NOT considered for construction units requiring resource

As you can see, currently in mod production, due to code limitations, we focus more on the effects of civilization itself and are unable to adjust the connections between civilizations.I think global resources may be able to solve this problem to some extent.

**Comment by yairm210** [comment]
Can you give an example of what you would do with such a resource?

**Comment by Jiangeshi** [comment]
Oh, like the example I gave, harmful gases in civ6, or the United Nations can provide a certain number of United Nations seats. Another possibility, such as the WorldTension in Hearts of Iron IV.

**Comment by SeventhM** [comment]
This seems like something that should be closed as #3242

**Comment by yairm210** [comment]
Good point, this is definitely #3242 material
