### ISSUE TITLE
Suggestion about the translation of Chinese

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9829]
It would have been an error for a looooooooooooong time that the tranlation of "Paste gameID from clipboard" into Chinese is not true. It would be read as "从剪贴板粘贴游戏ID" instead of "从剪贴板粘贴个人ID", and this error has disturbed too many players in China when playing online. Wish it be fixed next version.
![屏幕截图 2023-07-21 212818](https://github.com/yairm210/Unciv/assets/114050365/680e9311-ede3-4d34-a39b-1f097a5384e7)

**Comment by yairm210** [comment]
Please PR a change in the chinese translation file
https://yairm210.github.io/Unciv/Other/Translating/

**Comment by AutumnPizazz** [comment]
Great, I've already fixed most of the Chinese translations and created pull requests.
https://github.com/yairm210/Unciv/pull/9835
