### ISSUE TITLE
[Android] Feature request: Update to targetSdk 33+

### ISSUE THREAD

**Issue by sebastien46** [yairm210/Unciv#9840]
**Is your feature request related to a problem? Please describe.**

Starting from August 31st 2023 onwards, the Google Play Store won't accept app updates for apps with targetSdk inferior to 33

**Describe the solution you'd like**

Update the Android app to targetSdk 33

**Describe alternatives you've considered**

Don't publish Unciv to the Google Play Store

**Additional context**

[https://support.google.com/googleplay/android-developer/answer/11926878](https://support.google.com/googleplay/android-developer/answer/11926878)

**Comment by yairm210** [comment]
I see that *existing* apps need only target 31
But good point regardless, we'll do this gradually, increasing one per version, to ensure nothing breaks (e.g. f-droid builds)

**Comment by SeventhM** [comment]
I mean we already target 32. Not that big a deal to go up one version to 33 and wait until that hits its deadline

**Comment by sebastien46** [comment]
> I see that _existing_ apps need only target 31 But good point regardless, we'll do this gradually, increasing one per version, to ensure nothing breaks (e.g. f-droid builds)

The first highlighted statement is only for new apps being created & for existing apps staying.
For app updates, that is in fact the stated deadline.
