### ISSUE TITLE
Mod previews aren't working on Windows

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#9854]
![imagen](https://github.com/yairm210/Unciv/assets/78449553/b96076d4-5319-4c55-a7ae-80d720e45357)

I came back and I can't see the mod preview, but on phone I can.

**Comment by yairm210** [comment]
What version are you on?

**Comment by Caballero-Arepa** [comment]
Sorry, 4.7.10.

**Comment by yairm210** [comment]
Hm, working on my Ubuntu, I see you have Windows but I do wonder if that would make a difference 🤔

**Comment by maliprinc420** [comment]
I have the same problem (on Windows11).

I also noticed that resizing the window while being in the mod interface actually hide the mod infos and you have to close and reopen the interface to see it again.

<details><summary>Screenshot</summary>

![image](https://github.com/yairm210/Unciv/assets/47052682/79be14e9-bf02-4dd1-9efa-7ec199e2d99a)

</details>

**Comment by maliprinc420** [comment]
I personnaly use the `Unciv-Windows64.zip` available at each new release and considering my usage of github I would be surprised if the problem is github's rate limit. But which local preview are you talking about?

**Comment by yairm210** [comment]
So what I gather from you is we need to update the JDK on this line:

https://github.com/yairm210/Unciv/blob/ad75ad916b7e597daa815d7a8af8f1642ce99979/.github/workflows/buildAndDeploy.yml#L199
