### ISSUE TITLE
An insignificant startup screen error.

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9886]
As shown in the screenshot below. When opening Unciv on Windows, a white border appears as shown below. This error only occurs in version 4.7.12.
![image](https://github.com/yairm210/Unciv/assets/114050365/5441a264-3509-4a93-9274-eb1a5bbe9995)

**Comment by yairm210** [comment]
Does this always happen? Does it stay this way forever? If not then how long does it stay? What happens if you resize

**Comment by AutumnPizazz** [comment]
Yes, this situation has been occurring regardless of how I adjust the window size. However, it hardly affects the actual usage, as the normal game interface appears after this brief screen (in the previous versions, there was a black screen without the white border).

**Comment by yairm210** [comment]
Hm, this might be a result of updating the JDK used for Windows 🤔

**Comment by AutumnPizazz** [comment]
I agree, because this time the update cannot be directly extracted by overwriting the zip file to the original folder as before, but the folder must be set separately and then the configuration files can be overwritten to open properly.

**Comment by yairm210** [comment]
It should still work by overwriting the zip file though? I mean the zip itself should be JDK-agnostic IIRC

**Comment by AutumnPizazz** [comment]
So this will become a new 'insignificant startup screen error', right? QAQ

**Comment by yairm210** [comment]
I found that you can set the initial color of the screen, maybe that will help

**Comment by AutumnPizazz** [comment]
> Does that mean you never see the intended "loading splash screen" with the unciv banner, where we had the rotating smiley before?

Wow, I never knew about this!

**Comment by AutumnPizazz** [comment]
> OK, next question: Do you see that banner on Options-About:

Yeah, I could see all of them.
![image](https://github.com/yairm210/Unciv/assets/114050365/f0cfe0af-8a75-4bdc-9070-35951d0c06a0)
![image](https://github.com/yairm210/Unciv/assets/114050365/3911a7db-f831-4495-a5b3-d6d685fa53d6)

Well, the startup video is like this.
https://github.com/yairm210/Unciv/assets/114050365/00bc66a3-12c3-47ac-8593-9504ee90d603
@SomeTroglodyte

**Comment by yairm210** [comment]
So is this still happening to you with the recent change?

**Comment by AutumnPizazz** [comment]
It was never gone. (Until 4.7.13) @yairm210

**Comment by AutumnPizazz** [comment]
> Got it: `GraphicsEnvironment.getLocalGraphicsEnvironment().maximumWindowBounds` is badly wrong on certain monitor setups. Here I got 2 screens 2560x1440 each, secondary to the left of primary. maximumWindowBounds should be `{x: -2560, y: 0, width: 5120, height: 1360}` or close, but is `{x: 0, y: 0, width: 2048, height: 1112}`: completely off the rocker.
> 
> What happens next is: Gdx.Game gets created with the saved size, calls DesktopScreenMode.activate, which sees the saved dimensions equal the maximumWindowBounds dimensions, and decides to maximize. But startup is still busy, so the empty window decoration for the original saved size stays visible until the render loop starts properly. Or so.


I could say nothing but how cool you are. (Admiring) OwO

**Comment by AutumnPizazz** [comment]
Yeah, I update it as 4.8.2. However, this white border still never go away. There's the GameSettings.json
`{
    "mapPanningSpeed": 19,
    "showWorkedTiles": true,
    "showTileYields": true,
    "showUnitMovements": true,
    "autoUnitCycle": false,
    "language": "Simplified_Chinese",
    "screenSize": "Huge",
    "tutorialsShown": [
        "Introduction",
        "SlowStart"
    ],
    "tutorialTasksCompleted": [
        "See your stats breakdown",
        "Found city",
        "Enter city screen",
        "Open the options table",
        "Create a trade route",
        "Conquer a city",
        "Pick construction",
        "Move an air unit",
        "Move unit",
        "Pick technology",
        "Meet another civilization",
        "Reassign worked tiles",
        "Pass a turn",
        "Construct an improvement"
    ],
    "soundEffectsVolume": 0.45000002,
    "citySoundsVolume": 0,
    "musicVolume": 0,
    "pauseBetweenTracks": 0,
    "tileSet": "Civ6 Strategic Perspectives",
    "unitSet": null,
    "showTutorials": false,
    "autoAssignCityProduction": false,
    "minimapSize": 8,
    "unitIconOpacity": 0.8,
    "windowState": {
        "width": 3456,
        "height": 2001
    },
    "visualMods": [
        "The Undead",
        "Civ V - Vanilla",
        "RekMOD",
        "Latin-American_Civs-master",
        "DeCiv Redux",
        "philosophy mod",
        "Barbarian xp farm",
        "APmodofUnciv",
        "Latin American_Civs",
        "??????",
        "Latin American",
        "Civ V - Gods & Kings",
        "5Hex Tileset",
        "Leader Mission 2 Rising Power",
        "the Coexistence in harmony"
    ],
    "notificationsLogMaxTurns": 15,
    "showAutosaves": true,
    "multiplayer": {
        "userId": "7019070e-c113-4ad7-936f-cf577595559c",
        "passwords": {
            "class": "java.util.LinkedHashMap",
            "http://bj.unciv.cn": "741852963"
        },
        "server": "http://bj.unciv.cn",
        "friendList": [
            {
                "name": "MingTian",
                "playerID": "e73fb0a3-3304-4e5f-a580-9b4afbac4963"
            },
            {
                "name": "AoSiMan",
                "playerID": "d10f91a6-01c5-44ba-9b6d-0913980a109d"
            },
            {
                "name": "DaiWangShen",
                "playerID": "5422dad8-ddc9-4323-8761-6c020eb5acd6"
            },
            {
                "name": "YunMengXi",
                "playerID": "696a0a0a-67b5-4ff0-9ff5-909e12b04ae1"
            },
            {
                "name": "TanSuoZhe",
                "playerID": "a517c29d-d03f-4ae5-bd56-387fbb3a0c55"
            },
            {
                "name": "LengYu",
                "playerID": "376b0318-fce3-4c94-a59d-4259cc6d04a6"
            },
            {
                "name": "LangCi",
                "playerID": "6d8937b0-166b-49d4-887e-2cb077836e87"
            },
            {
                "name": "ShaoXiao",
                "playerID": "8c23a8ad-20c7-4e09-90ca-07ba240576db"
            },
            {
                "name": "E",
                "playerID": "e2c45378-676e-4278-a3d2-96e299d4ffd6"
            }
        ],
        "currentGameRefreshDelay": "PT3S",
        "allGameRefreshDelay": "PT2M",
        "currentGameTurnNotificationSound": {
            "fileName": "notification1"
        },
        "otherGameTurnNotificationSound": {
            "fileName": "notification2"
        }
    },
    "lastOverviewPage": "Religion",
    "lastGameSetup": {
        "gameParameters": {
            "difficulty": "Difficulty_Online",
            "speed": "Speed_Online",
            "players": [
                {
                    "chosenCiv": "Nation_Mali",
                    "playerType": "Human"
                },
                {
                    "playerType": "Human"
                },
                {
                    "chosenCiv": "Nation_Rome",
                    "playerType": "Human"
                }
            ],
            "numberOfCityStates": 0,
            "noCityRazing": true,
            "victoryTypes": [
                "Victory type_Science",
                "Victory type_Culture",
                "Victory type_Conquest",
                "Victory type_Diplomacy",
                "Victory type_Economic",
                "Victory type_Score",
                "Pattern_Permit to build World Wonder",
                "Pattern_Camorrist",
                "Pattern_Viceroy",
                "Victory type_Religion",
                "Pattern_Landlords"
            ],
            "startingEra": "Era_Ancient",
            "isOnlineMultiplayer": true,
            "multiplayerServerUrl": "http://bj.unciv.cn",
            "baseRuleset": "the Coexistence in harmony",
            "maxTurns": 300
        },
        "mapParameters": {
            "type": "Perlin",
            "shape": "Rectangular",
            "mapSize": {
                "radius": 32,
                "width": 80,
                "height": 40,
                "name": "Custom"
            },
            "mapResources": "Strategic Balance",
            "noRuins": true,
            "noNaturalWonders": true,
            "worldWrap": true,
            "baseRuleset": "the Coexistence in harmony",
            "createdWithVersion": "4.8.2 (Build 910)",
            "seed": 1693995731680,
            "elevationExponent": 0.6,
            "waterThreshold": -0.1
        }
    },
    "enableEasterEggs": false,
    "maxWorldZoomOut": 6,
    "notificationScroll": "Visible",
    "version": 1
}`

**Comment by AutumnPizazz** [comment]
I've been using my Xiaomi laptop all day. I won't be able to turn it on again until tomorrow evening (after 16h from now) to confirm the resolution. My impression is that my computer screen resolution is 1080P, not 4K

**Comment by AutumnPizazz** [comment]
Well, my screen is this.
![image](https://github.com/yairm210/Unciv/assets/114050365/28e25cb3-eb60-4755-906e-b3a7fb1f400a)

**Comment by AutumnPizazz** [comment]
https://github.com/yairm210/Unciv/assets/114050365/e5341d28-0e94-47e8-aca4-1284632635b9

It's so excited that the last-far start-screen error in my PC can be solved.
