### ISSUE TITLE
Feature request: BuildingType

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9890]
Can buildings also have corresponding BuildingTypes for categorization and generalized unique assignments, similar to how units have UnitTypes? BuildingType can include World Wonder, National Wonder, Custom building categories, and so on. For each BuildingType, you can (or add) use unique statements to assign properties. In addition, different custom building categories will be displayed in the city construction queue and the city's constructed buildings panel, categorized and displayed similar to the current classifications of "Specialist Buildings," "Wonders," and "General Buildings."
![image](https://github.com/yairm210/Unciv/assets/114050365/9753a922-e859-4b5a-8766-35fbd43fb735)

**Comment by AutumnPizazz** [comment]
I would like to create such a functionality. Below is a snippet of my imagined "BuildingType.json" file. QAQ @SomeTroglodyte 

[
    {
        "name":"World Wonder",
        "canBeHurriedBy":[""],//Nothing
        "unique":["Limited to [1] <for all the world>",
        "Triggers a global alert upon completion",
        "Never destroyed when the city is captured"]
    },
    {
        "name":"National Wonder",
        "canBeHurriedBy":[""],//Nothing
        "unique":["Limited to [1] <per civilization>",
        "Triggers a global alert upon completion",
        "Destroyed when the city is captured"]
    },
    {
        "name":"Custom Building Type 1",
        "canBeHurriedBy":["Gold","Faith"],
        "unique":[""]
    },
]

**Comment by AutumnPizazz** [comment]
![image](https://github.com/yairm210/Unciv/assets/114050365/81e3a3ce-9b10-4a1d-a8d3-b7b85132851a)

**Comment by yairm210** [comment]
I think this can generalized to "Complex Unique", a unique that when parsed is converted to a list of uniques
Either way this is a lot of work, and I'd rather have the complex unique because that could apply to all objects and would be really cool :)

**Comment by AutumnPizazz** [comment]
Actually, my ultimate goal is to have distinct visual representations on the panel for different categories of buildings defined by the mod.(This is to provide convenience for my mod.)

**Comment by yairm210** [comment]
So the simplest solution would be to have a "building category - [freetext]" unique to add to buildings

**Comment by AutumnPizazz** [comment]
Yeah, I need it.

**Comment by yairm210** [comment]
This to is a #3242
