### ISSUE TITLE
Gifted Great Generals don't respect nation-unique replacement

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9902]
**Describe the bug**
For a Nation with a unique variant of a Great General, as in: 
```json
	{
		"name": "General Grater",
		"unitType": "Civilian",
		"uniqueTo": "Cheese",
		"replaces": "Great General",...
         }
```
... Free units through City State gifting will be vanilla Great Generals, not the nation equivalent. For Naval Tradition only the Notification is wrong, the actual unit is fine.

**Expected behavior**
Intentional? I suspect not.

**Additional context**
Input welcome, but partially this is a reminder to self to analyze some day.

**Comment by SeventhM** [comment]
If I understand correctly, I believe that actually, City States can gift any version of a great person. So a city state can gift another civ's great general replacement, not just the vanilla one. But I'd have to double check if that's how that works

**Comment by yairm210** [comment]
City-states intentionally gift *their own* units, and not *your version* of units.
Closing as "not a bug".
If there are specific units we want to not be gifted by city states, that sounds like a unique we should add to those units

**Comment by SeventhM** [comment]
> City-states intentionally gift _their own_ units, and not _your version_ of units.

Incorrect by our implementation. Idk about Civ 5's. Our current implementation gives any great person when gifting random great people, regardless of if it's unique or not. Regardless of the city state is otherwise allowed to have the unit. Regard if you are otherwise allowed to have the unit

I'm pretty sure this isn't closable yet
