### ISSUE TITLE
Modding request

### ISSUE THREAD

**Issue by A1y0sh4** [yairm210/Unciv#9904]
May you please add a way to customize "Units ignore terrain costs when moving into any tile with Hills" and "All units move through Forest and Jungle Tiles in friendly territory as if they have roads. These tiles can be used to establish City Connections upon researching the Wheel." to respectively "[mapUnitFilter] units ignore terrain costs when moving into any tile with [tileFilter]" and "All units move through [tileFilter] tiles in [terrainFilter] as if they have roads. These tiles can be used to establish City Connections upon researching [technologyFilter]." (personally I would love to make them work with Rivers).

Thank you very much for considering my request, best regards.

**Comment by yairm210** [comment]
#modd
