### ISSUE TITLE
This is a complex bug that causes the game to crash when destroying cities in multiplayer mode

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9907]
**Platform**
Both Android and Windows11

**Version**
4.7.13

**Describe the bug**
As the title.
There's some questioned saves. ( I change it as txt and it could be none '.xxx'' file. )
These two save files require my mod "The Coexistence in harmony".

[Autosave-Nation_Qin-24.txt](https://github.com/yairm210/Unciv/files/12329471/Autosave-Nation_Qin-24.txt)
[Autosave-Nation_Greece-14.txt](https://github.com/yairm210/Unciv/files/12329473/Autosave-Nation_Greece-14.txt)

Based on the tests conducted, this issue rarely occurs (or I haven't observed it) when not using any mods. However, it tends to occur more frequently after applying certain mods, although occasionally the problem does not manifest. 

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/114050365/e691dd27-7188-4b4f-a5e3-348f7f7a0e0c)
![image](https://github.com/yairm210/Unciv/assets/114050365/aa103595-8660-44a2-bfeb-a8397e4a78a5)

**Comment by AutumnPizazz** [comment]
Your response is very profound, to the extent that I may not fully understand your meaning (due to my limited English proficiency). However, I can provide some information to the best of my ability.

**Comment by AutumnPizazz** [comment]
The names "the Coexistence in harmony - xxx" and "... - music" that you mentioned indeed appeared in my previous mod. The actual meaning of "xxx" or "聆彸唳" is "beta version." However, these two mods are only locally isolated and saved in a non-testing version of Unciv, which means they are not used for testing purposes.

**Comment by AutumnPizazz** [comment]
Regarding the issue of non-UTF-8 encoding, what I need to inform you is that I have been using VScode for editing files like JSON and Properties. In the editing interface, I can see that the encoding format is indeed UTF-8.
![image](https://github.com/yairm210/Unciv/assets/114050365/57653fc8-1560-4aef-af76-57e8ce7254c2)

**Comment by AutumnPizazz** [comment]
>Try to open your saves linked above in your VS - either some content will be wrong
Indeed, there is this issue.
![image](https://github.com/yairm210/Unciv/assets/114050365/3a646fff-5fae-4535-8bf7-e0c1b8be938f)

**Comment by AutumnPizazz** [comment]
On a tangent: I'm just a student who has recently finished the Chinese National College Entrance Examination (Gaokao), which means I don't possess the basic skills of a programmer. I only have a basic understanding of the C programming language, and beyond that, I have no knowledge of programming. I can only look at the numerous technical terms you mentioned in the previous text without understanding them.
I can hardly understand the task you want me to accomplish. QAQ

**Comment by AutumnPizazz** [comment]
Thank you for your concern. My locally isolated Unciv version, specifically used for testing, crashed. However, the standalone Unciv program without "-beta version" can still run smoothly.

![image](https://github.com/yairm210/Unciv/assets/114050365/76d30374-aa67-4165-b073-1dde115942e7)
![image](https://github.com/yairm210/Unciv/assets/114050365/630f6c31-dcdf-4e50-9187-85a5d4f9810e)
![image](https://github.com/yairm210/Unciv/assets/114050365/9e5e7e58-e95a-4585-a56f-e8a9a0115ac9)

**Comment by AutumnPizazz** [comment]
Looking back at this conversation, it seems like we have deviated from our original topic.
The initial topic was about me and my friend playing together using my mod, but when one of us deliberately destroyed the city, my save file crashed in the next turn. To address this issue, I presented two save files (the first one being the multiplayer save file, and the second one being a separate version with the suffix "- beta version" which I tested and also crashed).
It seems that the efforts we have made during this period have not resolved the issue I originally raised. QAQ

**Comment by AutumnPizazz** [comment]
> My locally isolated Unciv version, specifically used for testing, crashed

If I simply change the Chinese "-beta version" to English, the crashing error will be resolved.

**Comment by AutumnPizazz** [comment]
It seems that our efforts in this regard have not alleviated this breakdown problem.
I got up from bed in the middle of the night to turn on the light and test it, repeating that action twice. One time, it malfunctioned and the other time, it did not.
Unfortunately, I am unable to upload the video I recorded.
Please wait a moment, I will find a way to send it out in a while.
@SomeTroglodyte

**Comment by AutumnPizazz** [comment]
My two files are both over 10MB and it seems that I can't send them to the GitHub platform. Can I send them to your email instead?

**Comment by AutumnPizazz** [comment]
[No crashing.txt](https://github.com/yairm210/Unciv/files/12410980/No.crashing.txt)
[Crashing.txt](https://github.com/yairm210/Unciv/files/12410984/Crashing.txt)
Okay, I'll use the same old trick and convert the MP4 file to txt. After you receive it, you should be able to browse it correctly by changing the file extension. @SomeTroglodyte

**Comment by AutumnPizazz** [comment]
I believe it is necessary to bring up this agenda again now because this bug has not been resolved in the new version.

**Comment by yairm210** [comment]
Can't download the mods for this, is this still a problem?

**Comment by AutumnPizazz** [comment]
Yes, the bug never goes away.

**Comment by AutumnPizazz** [comment]
I'm sorry that I didn't make it clear. The core of this issue is that when using server online and mods, the act of occupying enemy cities has a probability (emphasis, sometimes it happens and sometimes it doesn't when I try to reproduce it) of causing the game to crash.

**Comment by AutumnPizazz** [comment]
However, I noticed that when there are more and more buildings in the occupied city, the possibility of causing a crash is higher, which may be related to the performance of the running device - but this does not happen when playing offline - I don't understand it.

**Comment by AutumnPizazz** [comment]
This bug has been solved in 4.11.12 by my test.
