### ISSUE TITLE
JSON files format corrections

### ISSUE THREAD

**Issue by Lytecyde** [yairm210/UnCiv#991]

**Comment by Lytecyde** [comment]
There are two types of issues possibly leading to errors too:
a) Comments are not allowed in JSON, we should use _comment field where applicable and JSON parsing would ignore that
b1) commas missing from various spots 
b2) trailing commas are used inconsistently, so perhaps best not to use them? as they are a nonstandard feature

**Comment by Am-per-Sand** [comment]
I noticed that months ago, but all the properties from the files with comma errors were properly recognized in-game, so I wonder whether they are corrected on the production stage or game engine just recognizes line-breaks to separate properties

**Comment by Lytecyde** [comment]
Could not be all I think....
Have to check but there were some missing commas between objects etc
So the structure was broken too. And yes many handlers pre minify json so
comments are removed

**Comment by yairm210** [comment]
I want to stress that there's a big difference between json files *for editing* and *for production* - the first is meant for humans and the second for machines
Handlers that remove comments, minify, uglify etc take human-centric files and optimize them to be machine-centric.
But let's not confuse that, with saying that the new optimized files are also optimized for human interaction...

**Comment by yairm210** [comment]
A. Comments are an essential part of the json files
B. Missing or trailing commas - do with them as you wish

**Comment by Lytecyde** [comment]
Ok this makes sense and improves my understanding, thanks!
I would personally keep a nicer style... I justgot a very strict education
last year.
Still the versions I made break code I think....

**Comment by yairm210** [comment]
In retrospect, this is not important enough for me to keep the issue open, so I'm closing it
