### ISSUE TITLE
Make older realeases available for download from github and install

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#993]
I mean .apk files and something to be installed on iOS.

I especially require 2.17.* as all the later versions crash to desktop.

**Comment by yairm210** [comment]
You can find apk files on lots of sure that store older apk versions
iOS, I don't even know how to compile and I'm not sure that they let you install a non-store app
If it's crashing to desktop, let's try and figure out why instead of reverting - is it a specific game? Settings?

**Comment by Am-per-Sand** [comment]
Right, found some archive: https://sameapk.com/unciv-com-unciv-app/, hope it's not enriched with anything nasty.

this issue was only for older versions, app error is a different one.
