### ISSUE TITLE
Feature request: "Show destination tile" or "Jump to destination" action buttons when selecting travelling unit

### ISSUE THREAD

**Issue by andoruB** [yairm210/Unciv#9936]
**Is your feature request related to a problem? Please describe.**
Currently it's a bit difficult to figure out where the selected unit is headed, which causes me to send multiple similar units to the same place, not realising that I've already sent the required units to that specific spot. The white circle that shows to indicate where the unit is headed is sometimes very hard to see, among the many graphics and UI elements. Also the on-map arrows showing where each unit is moving from/to is not helpful, sometimes it disappears, most of the time it's a bit hard to see and confusing.

**Describe the solution you'd like**
A button on the action menu (where "Build", "Stop movement", "Sleep", "Disband unit", etc commands reside) labelled "Show destination tile" or "Jump to destination" would be available. Or at least improve the visibility of the travel arrows on the map, or  aid in them making sense.

**Describe alternatives you've considered**
As mentioned above, aid in making the travel arrows more visible.

**Comment by yairm210** [comment]
Jump to destination tile is a great idea!

**Comment by andoruB** [comment]
I think this was added in 4.7.19?
Thank you huckdogg for working on this!

**Comment by SeventhM** [comment]
Closed as Solved as per #9955
