### ISSUE TITLE
Hidden in Civilopedia for unitType hide all the unit of said unitType

### ISSUE THREAD

**Issue by amfauzn** [yairm210/Unciv#9939]
**Platform**
Android

**Version**
4.7.15

**Expected behavior**
The unique "Will not be displayed in Civilopedia" should only hide the unitType, not all unit of said unitType. Happens in game with Fantasia mod. (and actually found by Bamboolord)

**Comment by yairm210** [comment]
Your expected behavior is not the expected behavior.
Uniques of a unit type are added to all units, that's the point of the unit type :)

**Comment by RealBamboolord** [comment]
Weird, that should be a special case. Now there's no way of hiding unittypes without hiding all units

**Comment by yairm210** [comment]
Why would you want that, though? The only thing unit types are for is unique grouping and unit movement

**Comment by RealBamboolord** [comment]
Sometimes you end up having a lot of unittypes for only one or two units each, making the Unittype civilopedia page pretty messy. But it's not a big issue, so I won't complain further :)

**Comment by amfauzn** [comment]
Well, if that's the case then I'll remove the unique.
Thanks for your time guys.
