### ISSUE TITLE
Zoom in tech screen

### ISSUE THREAD

**Issue by SoraDevin** [yairm210/Unciv#994]
Also make it so you open tech screen to your current progress instead of at the start

**Comment by SoraDevin** [comment]
Just realised my title is misleading. It is meant to say "add zoom functionality to tech tree screen"

**Comment by yairm210** [comment]
> Also make it so you open tech screen to your current progress instead of at the start

It already does, though...?

**Comment by SoraDevin** [comment]
Whenever I've opened it it's jumped back to the first few techs in the tree. Honestly not a problem if you can zoom out to view the full tree though.

**Comment by darkninec** [comment]
I have the sane problem. No zoom and every time at start when open it.

**Comment by yairm210** [comment]
Dredging this up from the depths.
The world screen zooming was done in a hacky way, ad it won't work here unless we do some serious loopy business.
I honestly can't think of a non-hacky way to do it, so for now, nope =/
