### ISSUE TITLE
Feature request: Tell newcomers that the AI will react to a trade offer in the next turn

### ISSUE THREAD

**Issue by mb720** [yairm210/Unciv#9954]
Hi and thanks a lot for Unciv!

Playing my first game of Unciv, I was confused that I didn't get any immediate feedback after I offered a trade to another civilization. The button in the GUI just said "Retract offer".

It might be obvious to people who played Civ 5 (I haven't), but it would be nice to tell players that they'll get an answer from the other civilization *in the next turn*. Maybe tell the player only the first time they offer a trade and only for difficulty levels "Settler" or "Chieftain" where it can be assumed that the player is new to the game.

Apart from that little issue, I had a very smooth experience with Unciv. Thanks for a great game! 👍

**Comment by Caballero-Arepa** [comment]
Ah yes.

A little comentary of the AI indicating the likelyness of the trade, but not necesarily accepting/denying the trade offer in the same turn.

That's actually a good idea.

**Comment by mb720** [comment]
I'm glad you agree. I'd be completely happy either with a message like "The civilization will decide on your trade offer in the next turn". Alternatively, to add some color, from the point of view of the civilization itself: "We, the mighty [civilization name], will graciously consider your offer. You'll hear from us soon."

**Comment by Caballero-Arepa** [comment]
Or as simple as in Victoria 2, were it just says "They would accept" and "They would not accept"

**Comment by yairm210** [comment]
Half the point of waiting to next turn is that you *don't* know, or else players would microoptimize trade requests ;)
But that's a good point, in some other games it is instant

How about if we change the text of "offer trade" to "offer trade (will be accepted or rejected on their turn)" - does that get the point across well? Can you think of a shorter formulation?

**Comment by mb720** [comment]
>Can you think of a shorter formulation?

* "They'll decide on your offer in the next turn"
* "Decision in next turn"

**Comment by yairm210** [comment]
"They'll decide on their turn" sounds clearest to me - both who is deciding, and when
We'll add this as a second line to the button, probably
Thanks! :D

**Comment by mb720** [comment]
Great, thanks for putting that in the game. :-)

Really nitpicking now: I think "**in** their turn" is more correct than "**on** their turn".

**Comment by yairm210** [comment]
Not yet implemented - we'll close this when it's actually done ;)
