### ISSUE TITLE
Add Android App Option to Enable Notifications

### ISSUE THREAD

**Issue by WeiTuFat** [yairm210/Unciv#9966]
Hi, not sure if this is resolved? I'm new to GitHub and still learning how to navigate everything.

I think this is the same issue I'm having, there is no option for me to turn on Notifications. I first downloaded the game from F-Droid, then this happened so uninstalled and reinstalled from Google Play, but still no option.

Please see screenshots attached:

![Screenshot_20230819_154602_Settings](https://github.com/yairm210/Unciv/assets/142675516/86139eb3-993e-4704-9160-837bb948e258)

![Screenshot_20230819_155559_Settings](https://github.com/yairm210/Unciv/assets/142675516/f27a5d39-bf6c-4f00-ba3f-2d515263da1b)

_Originally posted by @WeiTuFat in https://github.com/yairm210/Unciv/pull/7844#issuecomment-1685022732_

**Comment by WeiTuFat** [comment]
@yairm210 hi, I'm trying to move this to bug issues, but really struggling to add the label. Can you help? Thanks

Amazing game and effort!

**Comment by yairm210** [comment]
It's an option inside the game, but I don't know how to 'externalize' that option out to the Android manager... Interesting

Not a bug imo, but a feature request - since the app is working as intended, but you're asking for an extra way to disable functionality
