### ISSUE TITLE
Modders: How to implement unit stats editing, such as deducting 1 gold from every surviving warrior on the field?

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9975]
How to implement unit stats editing, such as deducting 1 gold from every surviving warrior on the field?
I tried to use exclusive strategic resources to achieve my goals, but unfortunately, the stats of strategic resources are only calculated once, regardless of how much of this resource is accumulated.

**Comment by yairm210** [comment]
This is a question for Discord, NOT Github, as the new issue guidelines clearly state

**Comment by AutumnPizazz** [comment]
> Units don't have gold

It is precisely for this reason that I raised this question. It seems that the existing module entries cannot achieve this function. So, I hope that "[stats]" will also take effect on Units in the next update.

**Comment by AutumnPizazz** [comment]
In order to achieve the effect of deducting money from existing units, I have added something in the "GlobalUniques.json"  and "Units.json" file.

`
		"Consumes [-1] [Resource_Military_Maintenance1]"`
`
        "[-1 Gold] <when above [0] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [1] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [2] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [3] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [4] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [5] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [6] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [7] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [8] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [9] [Resource_Military_Maintenance1]>",
        "[-1 Gold] <when above [10] [Resource_Military_Maintenance1]>",
`
But this approach will affect the running efficiency and seriously impact the gaming experience. Therefore, I hope to find a more user-friendly and convenient alternative method.
@SomeTroglodyte @yairm210
