### ISSUE TITLE
Mod checker objecting to "Improvement" as tile filter, even though it works.

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#9976]
Windows 10, Unciv 4.7.17-patch1

I made a little mod that contains the uniques of `"[+1 Culture] from every [Improvement]"` and `"[100]% Yield from every [Improvement]"`. I ran them through the mod checker and got this message:

> Grey Goo: Grey Goo's unique "[+1 Culture] from every [Improvement]" contains parameter Improvement, which does not fit parameter type tileFilter or specialist or buildingFilter !
> Grey Goo: Grey Goo's unique "[100]% Yield from every [Improvement]" contains parameter Improvement, which does not fit parameter type tileFilter or buildingFilter !

Despite these warnings, the game is actually running just fine. Every improvement yields twice its normal output, including two Culture from the combined effects of both uniques. It's just the mod checker that's throwing up an error message when it shouldn't.
[GreyGoo.zip](https://github.com/yairm210/Unciv/files/12447159/GreyGoo.zip)

**Comment by SeventhM** [comment]
Interesting. I didn't realize it had to be added to the list there as well

**Comment by KrisadaFantasy** [comment]
I think the mod checker still has problem with improvement.

> Mythical Wonders Beta: (Building) Shrine of Eden's unique "[+2 Science] from [Plantation] tiles [in this city]" contains parameter "Plantation", which does not fit parameter type tileFilter !

The code does work as intent though.

**Comment by yairm210** [comment]
Sounds like you didn't select a base ruleset

**Comment by KrisadaFantasy** [comment]
You are right! It's all green once I change it.
