### ISSUE TITLE
"Only available <for units with [promotion]>" not working

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#9982]
Windows 10, itch.io v. 4.7.17-patch1

I designed a promotion with the prerequisite of Drill I but with the unique of `"Only available <for units with [Shock I]>"`. The idea was to make a promotion that requires both previous promotions as prerequisites. It's not working; units with Drill I can access the promotion even without getting Shock I.
[PromotionTest.zip](https://github.com/yairm210/Unciv/files/12448942/PromotionTest.zip)

**Comment by SeventhM** [comment]
Interesting. Situation looks worse than that, actually. Looks like "Only available" itself accidentally isn't functioning for promotions
