### ISSUE TITLE
Mountains cannot be improved, even if the improvement is modified

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#9988]
**Platform**
Android and Windows11.

**Version**
4.7.17-patch1 and before.

I'm sorry I cannot provide the relevant screenshots and saves, but this is something I came up with after collecting feedback from many people who cannot enter Github.

**Comment by SpacedOutChicken** [comment]
Can you tell us more about what's going on here? I've got mods that allow improvements to ocean resources, and I've seen Carthage workers build roads across mountains. Is that not happening for you?

**Comment by AutumnPizazz** [comment]
In my "The Coexistence in Harmony" mod, the Ocean Home cannot be built properly in the ocean.
In previous versions, the mountain road network of the Inca civilization could not be constructed in the mountains. (These were built on the premise that these two improvements were not specifically designed for resource gathering.)

**Comment by AutumnPizazz** [comment]
It didn't.
![image](https://github.com/yairm210/Unciv/assets/114050365/1581e9dc-d159-401d-91ba-9a1fe01fda89)
![image](https://github.com/yairm210/Unciv/assets/114050365/5acd12be-c02b-424d-b79a-d2cde548ebee)
@SomeTroglodyte

**Comment by AutumnPizazz** [comment]
`
	{//海洋家园
		"name": "Improvement_Seastead",
		"terrainsCanBeBuiltOn": ["Ocean","Coast"],
		"food": 2,
		"techRequired": "Tech_Ocean home",
		"uniques": ["Provides [1] [Resource_house_limitation]",
		"[+1 Production] for each adjacent [Improvement_Fishing_Boat]",
		"[+1 Culture] for each adjacent [Landform_Reef]",
		"Can only be built to improve a resource",
		"Pillaging this improvement yields approximately [+20 Gold]",
		"Class_Usual_Improvement"]
	},`

**Comment by AutumnPizazz** [comment]
Okay, I realized my stupid and ridiculous mistake. I added "Can only be built to improve a resource."

**Comment by AutumnPizazz** [comment]
However, things have taken a twist and turn. Even after removing "Can only be built to improve a resource," it still cannot be done.

**Comment by AutumnPizazz** [comment]
![image](https://github.com/yairm210/Unciv/assets/114050365/1a7a0f2c-3068-4065-a73d-3cf4dc891c3a)
![image](https://github.com/yairm210/Unciv/assets/114050365/c10898cd-3792-485a-8d8d-b25d78a5c2ff)
`
	{//印加-山路工人
		"name": "Unit_Mountain_Road_Network",
		"unitType": "Unit_Type_Civilian",
		"uniqueTo":"Nation_Inca",
		"movement": 2,
		"requiredTech":"Civic_Basic trade",
		"uniques": [
			"Can instantly construct a [Improvement_Mountain_Road_Network] improvement <by consuming this unit>",
			"Unit_Class_Builder",
			"Will not be displayed in Civilopedia"],
		"cost": 65
	},`
`
	{//印加-山地路网
		"name": "Improvement_Mountain_Road_Network",
		"uniqueTo": "Nation_Inca",
		"terrainsCanBeBuiltOn": ["Mountain"],
		"food": 1,
		"uniques": [
		"[+1 Food] for each adjacent [Improvement_Terrace_Farm]"
	],
		"techRequired": "Civic_Basic trade"
	},`

**Comment by AutumnPizazz** [comment]
[BugSave.txt](https://github.com/yairm210/Unciv/files/12451810/BugSave.txt)
modRequired: "The Coexistence in harmony"

**Comment by AutumnPizazz** [comment]
This could work finely, as this work in farmers and miners.

**Comment by AutumnPizazz** [comment]
If I modify the mountain range attribute to allow for free passage, then the mountain road network can be built properly.
![image](https://github.com/yairm210/Unciv/assets/114050365/8782412c-4f4d-440a-9e3c-d0021d032399)
`
	{//山脉
		"name": "Mountain",
		"type": "Land",
		"impassable": false,
		"defenceBonus": 0.23,
		"movementCost": 2,
		"RGB": [102, 102, 102],
		"uniques": ["Rough terrain",
            "Has an elevation of [3] for visibility calculations",
            "Occurs in chains at high elevations",
            "Units ending their turn on this terrain take [15] damage",
            "Always Fertility [-2] for Map Generation",
            "Considered [Undesirable] when determining start locations"
		]
	},`

**Comment by AutumnPizazz** [comment]
> And Seasteads do work too

You are right. This bug does not include Ocean. It's my carelessness.
The problem is now occurring in the mountains.

**Comment by yairm210** [comment]
Is this bug still relevant?

**Comment by SpacedOutChicken** [comment]
> Is this bug still relevant?

I don't think so. I've been able to build improvements on mountains and water tiles in my mods for some time now.

**Comment by SeventhM** [comment]
Building in water is possible already. Building on mountain is still not possible from unit action uniques. Seems explicitly disallowed in ``ui.screens.worldscreen.unit.actions.UnitActionsFromUniques`` for some reason

**Comment by SeventhM** [comment]
> This was always possible by simply modding the mountain terrain too, removing unbuildable. Never noticed any negative side effects.

Not for instantly building via unit actions, which is what the issue Author was primarily referring to
