### ISSUE TITLE
Automated workers sometimes selected on new turn

### ISSUE THREAD

**Issue by SoraDevin** [yairm210/UnCiv#999]

**Comment by yairm210** [comment]
Not sure what your mean by this...? And if so, so what?

**Comment by yairm210** [comment]
Okay...?
I'm closing his since I don't see any problem, you can reopen it if you feel it's necessary

**Comment by SoraDevin** [comment]
It interrupts game flow, sorry for the delay in responding I've been super busy.

**Comment by SoraDevin** [comment]
I can't reopen as I'm not a collaborator

**Comment by yairm210** [comment]
Resolved in 0a777e5
