### ISSUE TITLE
Feature request: Credits

### ISSUE THREAD

**Issue by qubodup** [yairm210/Unciv#9994]
There is a credits file which seems more like an asset-licenses.txt: https://github.com/yairm210/Unciv/blob/master/docs/Credits.md

Is there interest in a more common credits file and possibly including it in an in-game screen as well?

FOSS Examples:
* STK https://github.com/supertuxkart/stk-code/blob/master/data/CREDITS
* FLARE https://github.com/flareteam/flare-game/blob/master/CREDITS.txt + https://github.com/flareteam/flare-engine/blob/master/CREDITS.engine.txt
* Wesnoth https://www.mobygames.com/game/21895/the-battle-for-wesnoth/credits/windows/

FLARE, FreedroidRPG and Wesnoth also have the very nice features of allowing to speed through the credits. The latter two even allowing fine grained speed up/slow down.

Commercial game credits look like this:
* https://www.mobygames.com/game/150689/baldurs-gate-iii/credits/windows/?autoplatform=true
* https://www.mobygames.com/game/81903/sid-meiers-civilization-vi/credits/windows/?autoplatform=true

By the way, when submitting credits to mobygames, the following format is imported automatically, so something easily convertible to it would be nice (people per role instead of roles per person):

```
Section

Role
Person
Person

Role
Person
Person

Section

Role
Person

Role
Person
Person
Person
```

Or how they put it:

![mobygames credits format](https://github.com/yairm210/Unciv/assets/18312/0de682b8-51eb-4ad6-8aff-51ac7cde293f)

**Comment by yairm210** [comment]
I don't really see a point to in-game credit screens, and maintaining a page of who did what sounds like a huge hassle, we have over 400 contributors
I'm not planning on doing so, but if you want to go through 400 contributors and sort them, I'm not going to stop you 🙃
